<?php
return [
  3400 => 
  [
    'id' => 3400,
    'type' => 'etcitem',
    'name' => 'Huge Orc Fang',
    'add_name' => '',
    'description' => 'The totem of the Atuba tribe. Gather the totems of the 5 tribes and take them to Pa\'agrio Lord Kakai.',
    'icon' => 'etc_ertheia2',
    'is_tradable' => false,
    'is_dropable' => false,
    'is_sellable' => false,
    'is_depositable' => false,
    'is_stackable' => true,
    'is_questitem' => true,
  ],
  3401 => 
  [
    'id' => 3401,
    'type' => 'etcitem',
    'name' => 'Sumari\'s Letter',
    'add_name' => '',
    'description' => 'A letter from Blacksmith Sumari to Seer Somak in the Town of Dion.',
    'icon' => 'etc_ertheia2',
    'is_tradable' => false,
    'is_dropable' => false,
    'is_sellable' => false,
    'is_depositable' => false,
    'is_stackable' => true,
    'is_questitem' => true,
  ],
  3402 => 
  [
    'id' => 3402,
    'type' => 'etcitem',
    'name' => 'Urutu Blade',
    'add_name' => '',
    'description' => 'A blade crafted by Blacksmith Sumari. Take this to Urutu Chief Hatos.',
    'icon' => 'etc_ertheia2',
    'is_tradable' => false,
    'is_dropable' => false,
    'is_sellable' => false,
    'is_depositable' => false,
    'is_stackable' => true,
    'is_questitem' => true,
  ],
  3403 => 
  [
    'id' => 3403,
    'type' => 'etcitem',
    'name' => 'Timak Orc Skull',
    'add_name' => '',
    'description' => 'The skull of a slain Timak Orc. Gather 10 of these and take them to Urutu chief Hatos.',
    'icon' => 'etc_ertheia2',
    'is_tradable' => false,
    'is_dropable' => false,
    'is_sellable' => false,
    'is_depositable' => false,
    'is_stackable' => true,
    'is_questitem' => true,
  ],
  3404 => 
  [
    'id' => 3404,
    'type' => 'etcitem',
    'name' => 'Sword Into Skull',
    'add_name' => '',
    'description' => 'The totem of the Urutu tribe. Gather the totems of the 5 tribes and take them to Pa\'agrio Lord Kakai.',
    'icon' => 'etc_ertheia2',
    'is_tradable' => false,
    'is_dropable' => false,
    'is_sellable' => false,
    'is_depositable' => false,
    'is_stackable' => true,
    'is_questitem' => true,
  ],
  3405 => 
  [
    'id' => 3405,
    'type' => 'etcitem',
    'name' => 'Neruga Axe Blade',
    'add_name' => '',
    'description' => 'The blade portion of a ceremonial axe. Take this to Neruga Chief Tantus.',
    'icon' => 'etc_ertheia2',
    'is_tradable' => false,
    'is_dropable' => false,
    'is_sellable' => false,
    'is_depositable' => false,
    'is_stackable' => true,
    'is_questitem' => true,
  ],
  3406 => 
  [
    'id' => 3406,
    'type' => 'etcitem',
    'name' => 'Ceremonial Axe',
    'add_name' => '',
    'description' => 'The totem of the Neruga tribe. Gather the totems of the 5 tribes and take them to Pa\'agrio Lord Kakai.',
    'icon' => 'etc_ertheia2',
    'is_tradable' => false,
    'is_dropable' => false,
    'is_sellable' => false,
    'is_depositable' => false,
    'is_stackable' => true,
    'is_questitem' => true,
  ],
  3407 => 
  [
    'id' => 3407,
    'type' => 'etcitem',
    'name' => 'Marsh Spider\'s Pincer',
    'add_name' => '',
    'description' => 'A key ingredient in making the Duda-Mara tribe totem. Gather 10 of these and take them to Duda-Mara Chief Takuna.',
    'icon' => 'etc_ertheia2',
    'is_tradable' => false,
    'is_dropable' => false,
    'is_sellable' => false,
    'is_depositable' => false,
    'is_stackable' => true,
    'is_questitem' => true,
  ],
  3408 => 
  [
    'id' => 3408,
    'type' => 'etcitem',
    'name' => 'Marsh Spider\'s Feet',
    'add_name' => '',
    'description' => 'A key ingredient in making the Duda-Mara tribe totem. Gather 10 of these and take them to Duda-Mara Chief Takuna.',
    'icon' => 'etc_ertheia2',
    'is_tradable' => false,
    'is_dropable' => false,
    'is_sellable' => false,
    'is_depositable' => false,
    'is_stackable' => true,
    'is_questitem' => true,
  ],
  3409 => 
  [
    'id' => 3409,
    'type' => 'etcitem',
    'name' => 'Handiwork Spider Brooch',
    'add_name' => '',
    'description' => 'The totem of the Duda-Mara tribe. Gather the totems of the 5 tribes and take them to Pa\'agrio Lord Kakai.',
    'icon' => 'etc_ertheia2',
    'is_tradable' => false,
    'is_dropable' => false,
    'is_sellable' => false,
    'is_depositable' => false,
    'is_stackable' => true,
    'is_questitem' => true,
  ],
  3410 => 
  [
    'id' => 3410,
    'type' => 'etcitem',
    'name' => 'Reinforced Monster Cornea',
    'add_name' => '',
    'description' => 'A key ingredient in making the Gandi tribe totem. Gather 20 of these and take them to Gandi Chief Chianta.',
    'icon' => 'etc_ertheia2',
    'is_tradable' => false,
    'is_dropable' => false,
    'is_sellable' => false,
    'is_depositable' => false,
    'is_stackable' => true,
    'is_questitem' => true,
  ],
  3411 => 
  [
    'id' => 3411,
    'type' => 'etcitem',
    'name' => 'Monster Eye Woodcarving',
    'add_name' => '',
    'description' => 'The totem of the Gandi tribe. Gather the totems of the 5 tribes and take them to Pa\'agrio Lord Kakai.',
    'icon' => 'etc_ertheia2',
    'is_tradable' => false,
    'is_dropable' => false,
    'is_sellable' => false,
    'is_depositable' => false,
    'is_stackable' => true,
    'is_questitem' => true,
  ],
  3412 => 
  [
    'id' => 3412,
    'type' => 'etcitem',
    'name' => 'Bear Fang Necklace',
    'add_name' => '',
    'description' => 'The totem of the Hestui tribe. Take this and go to the Ancestor Martankus in the Cave of Trials.',
    'icon' => 'etc_ertheia2',
    'is_tradable' => false,
    'is_dropable' => false,
    'is_sellable' => false,
    'is_depositable' => false,
    'is_stackable' => true,
    'is_questitem' => true,
  ],
  3413 => 
  [
    'id' => 3413,
    'type' => 'etcitem',
    'name' => 'Martankus\' Charm',
    'add_name' => '',
    'description' => 'The talisman of the Ancestor Martankus. Go back to him after completing this task.',
    'icon' => 'etc_ertheia2',
    'is_tradable' => false,
    'is_dropable' => false,
    'is_sellable' => false,
    'is_depositable' => false,
    'is_stackable' => true,
    'is_questitem' => true,
  ],
  3414 => 
  [
    'id' => 3414,
    'type' => 'etcitem',
    'name' => 'Ragna Orc Head',
    'add_name' => '',
    'description' => 'The head of a slain Ragna Orc. Take this to the Ancestor Martankus.',
    'icon' => 'etc_ertheia2',
    'is_tradable' => false,
    'is_dropable' => false,
    'is_sellable' => false,
    'is_depositable' => false,
    'is_stackable' => true,
    'is_questitem' => true,
  ],
  3415 => 
  [
    'id' => 3415,
    'type' => 'etcitem',
    'name' => 'Ragna Chief Notice',
    'add_name' => '',
    'description' => '"He who destroys the Lord of Flame shall be appointed Chief." Take this to the ancestral spirit Martankus.',
    'icon' => 'etc_ertheia2',
    'is_tradable' => false,
    'is_dropable' => false,
    'is_sellable' => false,
    'is_depositable' => false,
    'is_stackable' => true,
    'is_questitem' => true,
  ],
  3416 => 
  [
    'id' => 3416,
    'type' => 'etcitem',
    'name' => 'Immortal Flame',
    'add_name' => '',
    'description' => 'The mark received after passing the Ancestor Martankus\' test. Take this to Pa\'agrio Lord Kakai.',
    'icon' => 'etc_ertheia2',
    'is_tradable' => false,
    'is_dropable' => false,
    'is_sellable' => false,
    'is_depositable' => false,
    'is_stackable' => true,
    'is_questitem' => true,
  ],
  3428 => 
  [
    'id' => 3428,
    'type' => 'etcitem',
    'name' => 'Crystal Brooch',
    'add_name' => '',
    'description' => 'A brooch received from Warehouse Keeper Wilfred. Present this to Lilith of the temple at the Village of Talking Island.',
    'icon' => 'etc_ertheia2',
    'is_tradable' => false,
    'is_dropable' => false,
    'is_sellable' => false,
    'is_depositable' => false,
    'is_stackable' => true,
    'is_questitem' => true,
  ],
  3429 => 
  [
    'id' => 3429,
    'type' => 'etcitem',
    'name' => 'Spellbook: Greater Heal',
    'add_name' => '',
    'description' => 'Spellbook needed to learn the Greater Heal spell. Used by Bishops, Elven Elders, and Shillien Elders.',
    'icon' => 'etc_ertheia2',
    'price' => 3200,
    'commissionItemType' => 'SPELLBOOK',
    'is_stackable' => true,
  ],
  3430 => 
  [
    'id' => 3430,
    'type' => 'etcitem',
    'name' => 'Spellbook: Greater Battle Heal',
    'add_name' => '',
    'description' => 'Amulet required for the Greater Battle Heal spell. Used by Bishops.',
    'icon' => 'etc_ertheia2',
    'price' => 3200,
    'commissionItemType' => 'SPELLBOOK',
    'is_stackable' => true,
  ],
  3431 => 
  [
    'id' => 3431,
    'type' => 'etcitem',
    'name' => 'Spellbook: Greater Group Heal',
    'add_name' => '',
    'description' => 'Amulet required for the Greater Group Heal spell. Used by Bishops and Shillien Elders.',
    'icon' => 'etc_ertheia2',
    'price' => 3200,
    'commissionItemType' => 'SPELLBOOK',
    'is_stackable' => true,
  ],
  3432 => 
  [
    'id' => 3432,
    'type' => 'etcitem',
    'name' => 'Spellbook: Remedy',
    'add_name' => '',
    'description' => 'Amulet required for the Remedy spell. Used by Paladins.',
    'icon' => 'etc_ertheia2',
    'price' => 3200,
    'commissionItemType' => 'SPELLBOOK',
    'is_stackable' => true,
  ],
  3433 => 
  [
    'id' => 3433,
    'type' => 'etcitem',
    'name' => 'Elf Figure',
    'add_name' => '',
    'description' => '',
    'icon' => 'etc_ertheia2',
    'is_tradable' => false,
    'is_dropable' => false,
    'is_destroyable' => false,
    'is_sellable' => false,
    'is_depositable' => false,
  ],
  3434 => 
  [
    'id' => 3434,
    'type' => 'etcitem',
    'name' => 'Coke',
    'add_name' => '',
    'description' => '',
    'icon' => 'etc_ertheia2',
    'is_tradable' => false,
    'is_dropable' => false,
    'is_destroyable' => false,
    'is_sellable' => false,
    'is_depositable' => false,
  ],
  3435 => 
  [
    'id' => 3435,
    'type' => 'etcitem',
    'name' => 'Nvidia',
    'add_name' => '',
    'description' => '',
    'icon' => 'etc_ertheia2',
    'is_tradable' => false,
    'is_dropable' => false,
    'is_destroyable' => false,
    'is_sellable' => false,
    'is_depositable' => false,
  ],
  3436 => 
  [
    'id' => 3436,
    'type' => 'etcitem',
    'name' => 'Mouse',
    'add_name' => '',
    'description' => '',
    'icon' => 'etc_ertheia2',
    'is_tradable' => false,
    'is_dropable' => false,
    'is_destroyable' => false,
    'is_sellable' => false,
    'is_depositable' => false,
  ],
  3437 => 
  [
    'id' => 3437,
    'type' => 'etcitem',
    'name' => 'Trade Book of Merchant',
    'add_name' => '',
    'description' => '',
    'icon' => 'etc_ertheia2',
    'weight' => 120,
    'commissionItemType' => 'OTHER_ITEM',
    'price' => 20000,
  ],
  3438 => 
  [
    'id' => 3438,
    'type' => 'etcitem',
    'name' => 'Great Merchant\'s Trade Book',
    'add_name' => '',
    'description' => '',
    'icon' => 'etc_ertheia2',
    'weight' => 120,
    'commissionItemType' => 'OTHER_ITEM',
    'price' => 20000,
  ],
  3440 => 
  [
    'id' => 3440,
    'type' => 'etcitem',
    'name' => 'Cargo Box',
    'add_name' => '',
    'description' => 'Freight box on which the mark of Aden Commercial Guild is stamped.',
    'icon' => 'etc_ertheia2',
    'weight' => 20,
    'price' => 10,
    'is_questitem' => true,
    'commissionItemType' => 'OTHER_ITEM',
    'is_stackable' => true,
    'is_depositable' => false,
  ],
  3441 => 
  [
    'id' => 3441,
    'type' => 'etcitem',
    'name' => 'Cargo Box',
    'add_name' => '',
    'description' => 'Freight box on which the mark of Aden Commercial Guild is stamped.',
    'icon' => 'etc_ertheia2',
    'weight' => 20,
    'price' => 10,
    'is_questitem' => true,
    'commissionItemType' => 'OTHER_ITEM',
    'is_stackable' => true,
    'is_depositable' => false,
  ],
  3442 => 
  [
    'id' => 3442,
    'type' => 'etcitem',
    'name' => 'Cargo Box',
    'add_name' => '',
    'description' => 'Freight box on which the mark of Aden Commercial Guild is stamped.',
    'icon' => 'etc_ertheia2',
    'weight' => 20,
    'price' => 10,
    'is_questitem' => true,
    'commissionItemType' => 'OTHER_ITEM',
    'is_stackable' => true,
    'is_depositable' => false,
  ],
  3443 => 
  [
    'id' => 3443,
    'type' => 'etcitem',
    'name' => 'Cargo Box',
    'add_name' => '',
    'description' => 'Freight box on which the mark of Aden Commercial Guild is stamped.',
    'icon' => 'etc_ertheia2',
    'weight' => 20,
    'price' => 10,
    'is_questitem' => true,
    'commissionItemType' => 'OTHER_ITEM',
    'is_stackable' => true,
    'is_depositable' => false,
  ],
  3444 => 
  [
    'id' => 3444,
    'type' => 'etcitem',
    'name' => 'Gludio Apples',
    'add_name' => '',
    'description' => 'Apple cultivated in the Gludio region. Can be sold at shops.',
    'icon' => 'etc_ertheia2',
    'weight' => 20,
    'price' => 1000,
    'is_questitem' => true,
    'commissionItemType' => 'OTHER_ITEM',
    'is_stackable' => true,
    'is_depositable' => false,
  ],
  3445 => 
  [
    'id' => 3445,
    'type' => 'etcitem',
    'name' => 'Dion Corn Meal',
    'add_name' => '',
    'description' => 'Powder made from corn cultivated in Dion. Can be sold at shops.',
    'icon' => 'etc_ertheia2',
    'weight' => 20,
    'price' => 1000,
    'is_questitem' => true,
    'commissionItemType' => 'OTHER_ITEM',
    'is_stackable' => true,
    'is_depositable' => false,
  ],
  3446 => 
  [
    'id' => 3446,
    'type' => 'etcitem',
    'name' => 'Dire Wolf Pelts',
    'add_name' => '',
    'description' => 'Tanned Dire Wolf pelts . Can be sold at shops.',
    'icon' => 'etc_ertheia2',
    'weight' => 20,
    'price' => 1000,
    'is_questitem' => true,
    'commissionItemType' => 'OTHER_ITEM',
    'is_stackable' => true,
    'is_depositable' => false,
  ],
  3447 => 
  [
    'id' => 3447,
    'type' => 'etcitem',
    'name' => 'Moonstone',
    'add_name' => '',
    'description' => 'Jewel of blue and white light called Moonjang Stone or Moonstone. Can be sold at shops.',
    'icon' => 'etc_ertheia2',
    'weight' => 20,
    'price' => 1500,
    'is_questitem' => true,
    'commissionItemType' => 'OTHER_ITEM',
    'is_stackable' => true,
    'is_depositable' => false,
  ],
  3448 => 
  [
    'id' => 3448,
    'type' => 'etcitem',
    'name' => 'Gludio Wheat Flour',
    'add_name' => '',
    'description' => 'Powder made from wheat cultivated in the Gludio region. Can be sold at shops.',
    'icon' => 'etc_ertheia2',
    'weight' => 20,
    'price' => 1500,
    'is_questitem' => true,
    'commissionItemType' => 'OTHER_ITEM',
    'is_stackable' => true,
    'is_depositable' => false,
  ],
  3449 => 
  [
    'id' => 3449,
    'type' => 'etcitem',
    'name' => 'Spidersilk Rope',
    'add_name' => '',
    'description' => 'Strong rope made of weaving tarantula spider silk. Can be sold at shops.',
    'icon' => 'etc_ertheia2',
    'weight' => 20,
    'price' => 1500,
    'is_questitem' => true,
    'commissionItemType' => 'OTHER_ITEM',
    'is_stackable' => true,
    'is_depositable' => false,
  ],
  3450 => 
  [
    'id' => 3450,
    'type' => 'etcitem',
    'name' => 'Alexandrite',
    'add_name' => '',
    'description' => 'Precious jewel that shines green in the sunlight and red in the moonlight. Can be sold at shops.',
    'icon' => 'etc_ertheia2',
    'weight' => 20,
    'price' => 2000,
    'is_questitem' => true,
    'commissionItemType' => 'OTHER_ITEM',
    'is_stackable' => true,
    'is_depositable' => false,
  ],
  3451 => 
  [
    'id' => 3451,
    'type' => 'etcitem',
    'name' => 'Silver Tea Service',
    'add_name' => '',
    'description' => 'High-quality teacup and dish set crafted of silver. Can be sold at shops.',
    'icon' => 'etc_ertheia2',
    'weight' => 20,
    'price' => 2000,
    'is_questitem' => true,
    'commissionItemType' => 'OTHER_ITEM',
    'is_stackable' => true,
    'is_depositable' => false,
  ],
  3452 => 
  [
    'id' => 3452,
    'type' => 'etcitem',
    'name' => 'Mechanic Golem Spare Parts',
    'add_name' => '',
    'description' => 'A component of mechanic golems. Useless for anything else, it is best sold.',
    'icon' => 'etc_ertheia2',
    'weight' => 20,
    'price' => 2000,
    'is_questitem' => true,
    'commissionItemType' => 'OTHER_ITEM',
    'is_stackable' => true,
    'is_depositable' => false,
  ],
  3453 => 
  [
    'id' => 3453,
    'type' => 'etcitem',
    'name' => 'Fire Emerald',
    'add_name' => '',
    'description' => 'Precious jewel that shines with an intense red light. Can be sold at shops.',
    'icon' => 'etc_ertheia2',
    'weight' => 20,
    'price' => 5000,
    'is_questitem' => true,
    'commissionItemType' => 'OTHER_ITEM',
    'is_stackable' => true,
    'is_depositable' => false,
  ],
  3454 => 
  [
    'id' => 3454,
    'type' => 'etcitem',
    'name' => 'Avellan Silk Frock',
    'add_name' => '',
    'description' => 'High-quality silk dress imported from Avellan of the east. Can be sold at shops.',
    'icon' => 'etc_ertheia2',
    'weight' => 20,
    'price' => 5000,
    'is_questitem' => true,
    'commissionItemType' => 'OTHER_ITEM',
    'is_stackable' => true,
    'is_depositable' => false,
  ],
  3455 => 
  [
    'id' => 3455,
    'type' => 'etcitem',
    'name' => 'Feriotic Porcelain Urn',
    'add_name' => '',
    'description' => 'As a water cup made for their rituals, it is a relic of the ancient Ferios empire. Can be sold at shops.',
    'icon' => 'etc_ertheia2',
    'weight' => 20,
    'price' => 5000,
    'is_questitem' => true,
    'commissionItemType' => 'OTHER_ITEM',
    'is_stackable' => true,
    'is_depositable' => false,
  ],
  3456 => 
  [
    'id' => 3456,
    'type' => 'etcitem',
    'name' => 'Imperial Diamond',
    'add_name' => '',
    'description' => 'Jewel of brilliant light used in decorating the crown of the Elmoreden emperor. Can be sold at shops.',
    'icon' => 'etc_ertheia2',
    'weight' => 20,
    'price' => 20000,
    'is_questitem' => true,
    'commissionItemType' => 'OTHER_ITEM',
    'is_stackable' => true,
    'is_depositable' => false,
  ],
  3457 => 
  [
    'id' => 3457,
    'type' => 'etcitem',
    'name' => 'Statue of Shillien - Head',
    'add_name' => '',
    'description' => 'Part of a broken statue. Can be sold at shops. If you collect the remaining pieces of the statue...?',
    'icon' => 'etc_ertheia2',
    'weight' => 20,
    'price' => 2000,
    'is_questitem' => true,
    'commissionItemType' => 'OTHER_ITEM',
    'is_stackable' => true,
    'is_depositable' => false,
  ],
  3458 => 
  [
    'id' => 3458,
    'type' => 'etcitem',
    'name' => 'Statue of Shillien - Torso',
    'add_name' => '',
    'description' => 'Part of a broken statue. Can be sold at shops. If you collect the remaining pieces of the statue...?',
    'icon' => 'etc_ertheia2',
    'weight' => 20,
    'price' => 2000,
    'is_questitem' => true,
    'commissionItemType' => 'OTHER_ITEM',
    'is_stackable' => true,
    'is_depositable' => false,
  ],
  3459 => 
  [
    'id' => 3459,
    'type' => 'etcitem',
    'name' => 'Statue of Shillien - Arm',
    'add_name' => '',
    'description' => 'Part of a broken statue. Can be sold at shops. If you collect the remaining pieces of the statue...?',
    'icon' => 'etc_ertheia2',
    'weight' => 20,
    'price' => 2000,
    'is_questitem' => true,
    'commissionItemType' => 'OTHER_ITEM',
    'is_stackable' => true,
    'is_depositable' => false,
  ],
  3460 => 
  [
    'id' => 3460,
    'type' => 'etcitem',
    'name' => 'Statue of Shillien - Leg',
    'add_name' => '',
    'description' => 'Part of a broken statue. Can be sold at shops. If you collect the remaining pieces of the statue...?',
    'icon' => 'etc_ertheia2',
    'weight' => 20,
    'price' => 2000,
    'is_questitem' => true,
    'commissionItemType' => 'OTHER_ITEM',
    'is_stackable' => true,
    'is_depositable' => false,
  ],
  3461 => 
  [
    'id' => 3461,
    'type' => 'etcitem',
    'name' => 'Complete Statue of Shillien',
    'add_name' => '',
    'description' => 'Statue of Shilen made in the time of the ancient Elmoreden empire. Can be sold at shops for a high price.',
    'icon' => 'etc_ertheia2',
    'weight' => 20,
    'price' => 20000,
    'is_questitem' => true,
    'commissionItemType' => 'OTHER_ITEM',
    'is_stackable' => true,
    'is_depositable' => false,
  ],
  3462 => 
  [
    'id' => 3462,
    'type' => 'etcitem',
    'name' => 'Ancient Tablet Fragment: 1st Piece',
    'add_name' => '',
    'description' => 'Fragment of ancient clay tablet. If you collect the remaining pieces of the tablet...?',
    'icon' => 'etc_ertheia2',
    'weight' => 20,
    'price' => 2000,
    'is_questitem' => true,
    'commissionItemType' => 'OTHER_ITEM',
    'is_stackable' => true,
    'is_depositable' => false,
  ],
  3463 => 
  [
    'id' => 3463,
    'type' => 'etcitem',
    'name' => 'Ancient Tablet Fragment: 2nd Piece',
    'add_name' => '',
    'description' => 'Fragment of ancient clay tablet. If you collect the remaining pieces of the tablet...?',
    'icon' => 'etc_ertheia2',
    'weight' => 20,
    'price' => 2000,
    'is_questitem' => true,
    'commissionItemType' => 'OTHER_ITEM',
    'is_stackable' => true,
    'is_depositable' => false,
  ],
  3464 => 
  [
    'id' => 3464,
    'type' => 'etcitem',
    'name' => 'Ancient Tablet Fragment: 3rd Piece',
    'add_name' => '',
    'description' => 'Fragment of ancient clay tablet. If you collect the remaining pieces of the tablet...?',
    'icon' => 'etc_ertheia2',
    'weight' => 20,
    'price' => 2000,
    'is_questitem' => true,
    'commissionItemType' => 'OTHER_ITEM',
    'is_stackable' => true,
    'is_depositable' => false,
  ],
  3465 => 
  [
    'id' => 3465,
    'type' => 'etcitem',
    'name' => 'Ancient Tablet Fragment: 4th Piece',
    'add_name' => '',
    'description' => 'Fragment of ancient clay tablet. If you collect the remaining pieces of the tablet...?',
    'icon' => 'etc_ertheia2',
    'weight' => 20,
    'price' => 2000,
    'is_questitem' => true,
    'commissionItemType' => 'OTHER_ITEM',
    'is_stackable' => true,
    'is_depositable' => false,
  ],
  3466 => 
  [
    'id' => 3466,
    'type' => 'etcitem',
    'name' => 'Complete Ancient Tablet',
    'add_name' => '',
    'description' => 'A large clay tablet upon which ancient texts are engraved. You can sell it to a store at a high price.',
    'icon' => 'etc_ertheia2',
    'weight' => 20,
    'price' => 20000,
    'is_questitem' => true,
    'commissionItemType' => 'OTHER_ITEM',
    'is_stackable' => true,
    'is_depositable' => false,
  ],
  3467 => 
  [
    'id' => 3467,
    'type' => 'etcitem',
    'name' => 'The Wishing Potion',
    'add_name' => '',
    'description' => 'Magic potion that is said to make wishes come true.',
    'icon' => 'etc_ertheia2',
    'weight' => 60,
    'is_questitem' => true,
    'commissionItemType' => 'OTHER_ITEM',
    'price' => 10,
    'is_depositable' => false,
  ],
  3468 => 
  [
    'id' => 3468,
    'type' => 'etcitem',
    'name' => 'Ancient Crown',
    'add_name' => '',
    'description' => 'Crown that is full of jewels but is too big to wear on the head. Let\'s sell it.',
    'icon' => 'etc_ertheia2',
    'is_questitem' => true,
    'commissionItemType' => 'OTHER_ITEM',
    'price' => 1000,
    'is_depositable' => false,
  ],
  3469 => 
  [
    'id' => 3469,
    'type' => 'etcitem',
    'name' => 'Certificate of Royalty',
    'add_name' => '',
    'description' => 'Certificate of royalty but nobody knows who made it.',
    'icon' => 'etc_ertheia2',
    'is_questitem' => true,
    'commissionItemType' => 'OTHER_ITEM',
    'price' => 10,
    'is_depositable' => false,
  ],
  3470 => 
  [
    'id' => 3470,
    'type' => 'etcitem',
    'name' => 'Gold Bar',
    'add_name' => '',
    'description' => 'Heavy lump of pure gold.',
    'icon' => 'etc_ertheia2',
    'price' => 10000,
    'is_questitem' => true,
    'commissionItemType' => 'OTHER_ITEM',
    'is_stackable' => true,
    'is_depositable' => false,
  ],
  3471 => 
  [
    'id' => 3471,
    'type' => 'weapon',
    'name' => 'Cybellin\'s Dagger',
    'add_name' => '',
    'description' => 'Dagger used in ceremony to raise the purity of blood crystal.',
    'icon' => 'weapon_doomed_dagger_i00',
    'weapon_type' => 'dagger',
    'bodypart' => 'rhand',
    'weight' => 400,
    'soulshots' => 1,
    'spiritshots' => 1,
    'is_tradable' => false,
    'is_dropable' => false,
    'is_destroyable' => false,
    'is_sellable' => false,
    'is_depositable' => false,
  ],
  3472 => 
  [
    'id' => 3472,
    'type' => 'etcitem',
    'name' => 'Blood Medusa',
    'add_name' => '',
    'description' => 'Lowest-grade coin',
    'icon' => 'etc_ertheia2',
    'price' => 50,
    'is_questitem' => true,
    'commissionItemType' => 'OTHER_ITEM',
    'is_stackable' => true,
    'is_depositable' => false,
  ],
  3473 => 
  [
    'id' => 3473,
    'type' => 'etcitem',
    'name' => 'Blood Werewolf',
    'add_name' => '',
    'description' => 'Low-grade coin',
    'icon' => 'etc_ertheia2',
    'price' => 100,
    'is_questitem' => true,
    'commissionItemType' => 'OTHER_ITEM',
    'is_stackable' => true,
    'is_depositable' => false,
  ],
  3474 => 
  [
    'id' => 3474,
    'type' => 'etcitem',
    'name' => 'Blood Basilisk',
    'add_name' => '',
    'description' => 'Mid-grade coin',
    'icon' => 'etc_ertheia2',
    'price' => 150,
    'is_questitem' => true,
    'commissionItemType' => 'OTHER_ITEM',
    'is_stackable' => true,
    'is_depositable' => false,
  ],
  3475 => 
  [
    'id' => 3475,
    'type' => 'etcitem',
    'name' => 'Blood Dre Vanul',
    'add_name' => '',
    'description' => 'Low-grade coin',
    'icon' => 'etc_ertheia2',
    'price' => 100,
    'is_questitem' => true,
    'commissionItemType' => 'OTHER_ITEM',
    'is_stackable' => true,
    'is_depositable' => false,
  ],
  3476 => 
  [
    'id' => 3476,
    'type' => 'etcitem',
    'name' => 'Blood Succubus',
    'add_name' => '',
    'description' => 'Mid-grade coin',
    'icon' => 'etc_ertheia2',
    'price' => 150,
    'is_questitem' => true,
    'commissionItemType' => 'OTHER_ITEM',
    'is_stackable' => true,
    'is_depositable' => false,
  ],
  3477 => 
  [
    'id' => 3477,
    'type' => 'etcitem',
    'name' => 'Blood Dragon',
    'add_name' => '',
    'description' => 'High-grade coin',
    'icon' => 'etc_ertheia2',
    'price' => 200,
    'is_questitem' => true,
    'commissionItemType' => 'OTHER_ITEM',
    'is_stackable' => true,
    'is_depositable' => false,
  ],
  3478 => 
  [
    'id' => 3478,
    'type' => 'etcitem',
    'name' => 'Beleth\'s Blood Dragon',
    'add_name' => '',
    'description' => 'Highest-grade coin',
    'icon' => 'etc_ertheia2',
    'price' => 300,
    'is_questitem' => true,
    'commissionItemType' => 'OTHER_ITEM',
    'is_stackable' => true,
    'is_depositable' => false,
  ],
  3479 => 
  [
    'id' => 3479,
    'type' => 'etcitem',
    'name' => 'Manak\'s Blood Werewolf',
    'add_name' => '',
    'description' => 'Mid-grade coin',
    'icon' => 'etc_ertheia2',
    'price' => 150,
    'is_questitem' => true,
    'commissionItemType' => 'OTHER_ITEM',
    'is_stackable' => true,
    'is_depositable' => false,
  ],
  3480 => 
  [
    'id' => 3480,
    'type' => 'etcitem',
    'name' => 'Nia\'s Blood Medusa',
    'add_name' => '',
    'description' => 'Low-grade coin',
    'icon' => 'etc_ertheia2',
    'price' => 100,
    'is_questitem' => true,
    'commissionItemType' => 'OTHER_ITEM',
    'is_stackable' => true,
    'is_depositable' => false,
  ],
  3481 => 
  [
    'id' => 3481,
    'type' => 'etcitem',
    'name' => 'Gold Dragon',
    'add_name' => '',
    'description' => 'High-grade coin',
    'icon' => 'etc_ertheia2',
    'price' => 200,
    'is_questitem' => true,
    'commissionItemType' => 'OTHER_ITEM',
    'is_stackable' => true,
    'is_depositable' => false,
  ],
  3482 => 
  [
    'id' => 3482,
    'type' => 'etcitem',
    'name' => 'Gold Wyvern',
    'add_name' => '',
    'description' => 'Lowest-grade coin',
    'icon' => 'etc_ertheia2',
    'price' => 50,
    'is_stackable' => true,
    'is_questitem' => true,
    'commissionItemType' => 'OTHER_ITEM',
    'is_depositable' => false,
  ],
  3483 => 
  [
    'id' => 3483,
    'type' => 'etcitem',
    'name' => 'Gold Knight',
    'add_name' => '',
    'description' => 'Low-grade coin',
    'icon' => 'etc_ertheia2',
    'price' => 100,
    'is_questitem' => true,
    'commissionItemType' => 'OTHER_ITEM',
    'is_stackable' => true,
    'is_depositable' => false,
  ],
  3484 => 
  [
    'id' => 3484,
    'type' => 'etcitem',
    'name' => 'Gold Giant',
    'add_name' => '',
    'description' => 'Mid-grade coin',
    'icon' => 'etc_ertheia2',
    'price' => 150,
    'is_questitem' => true,
    'commissionItemType' => 'OTHER_ITEM',
    'is_stackable' => true,
    'is_depositable' => false,
  ],
  3485 => 
  [
    'id' => 3485,
    'type' => 'etcitem',
    'name' => 'Gold Drake',
    'add_name' => '',
    'description' => 'Low-grade coin',
    'icon' => 'etc_ertheia2',
    'price' => 100,
    'is_questitem' => true,
    'commissionItemType' => 'OTHER_ITEM',
    'is_stackable' => true,
    'is_depositable' => false,
  ],
  3486 => 
  [
    'id' => 3486,
    'type' => 'etcitem',
    'name' => 'Gold Wyrm',
    'add_name' => '',
    'description' => 'Mid-grade coin',
    'icon' => 'etc_ertheia2',
    'price' => 150,
    'is_questitem' => true,
    'commissionItemType' => 'OTHER_ITEM',
    'is_stackable' => true,
    'is_depositable' => false,
  ],
  3487 => 
  [
    'id' => 3487,
    'type' => 'etcitem',
    'name' => 'Beleth\'s Gold Dragon',
    'add_name' => '',
    'description' => 'Highest-grade coin',
    'icon' => 'etc_ertheia2',
    'price' => 300,
    'is_questitem' => true,
    'commissionItemType' => 'OTHER_ITEM',
    'is_stackable' => true,
    'is_depositable' => false,
  ],
  3488 => 
  [
    'id' => 3488,
    'type' => 'etcitem',
    'name' => 'Manak\'s Gold Giant',
    'add_name' => '',
    'description' => 'Mid-grade coin',
    'icon' => 'etc_ertheia2',
    'price' => 150,
    'is_questitem' => true,
    'commissionItemType' => 'OTHER_ITEM',
    'is_stackable' => true,
    'is_depositable' => false,
  ],
  3489 => 
  [
    'id' => 3489,
    'type' => 'etcitem',
    'name' => 'Nia\'s Gold Wyvern',
    'add_name' => '',
    'description' => 'Low-grade coin',
    'icon' => 'etc_ertheia2',
    'price' => 100,
    'is_questitem' => true,
    'commissionItemType' => 'OTHER_ITEM',
    'is_stackable' => true,
    'is_depositable' => false,
  ],
  3490 => 
  [
    'id' => 3490,
    'type' => 'etcitem',
    'name' => 'Silver Unicorn',
    'add_name' => '',
    'description' => 'Lowest-grade coin',
    'icon' => 'etc_ertheia2',
    'price' => 50,
    'is_questitem' => true,
    'commissionItemType' => 'OTHER_ITEM',
    'is_stackable' => true,
    'is_depositable' => false,
  ],
  3491 => 
  [
    'id' => 3491,
    'type' => 'etcitem',
    'name' => 'Silver Fairy',
    'add_name' => '',
    'description' => 'Low-grade coin',
    'icon' => 'etc_ertheia2',
    'price' => 100,
    'is_questitem' => true,
    'commissionItemType' => 'OTHER_ITEM',
    'is_stackable' => true,
    'is_depositable' => false,
  ],
  3492 => 
  [
    'id' => 3492,
    'type' => 'etcitem',
    'name' => 'Silver Dryad',
    'add_name' => '',
    'description' => 'Mid-grade coin',
    'icon' => 'etc_ertheia2',
    'price' => 150,
    'is_questitem' => true,
    'commissionItemType' => 'OTHER_ITEM',
    'is_stackable' => true,
    'is_depositable' => false,
  ],
  3493 => 
  [
    'id' => 3493,
    'type' => 'etcitem',
    'name' => 'Silver Dragon',
    'add_name' => '',
    'description' => 'High-grade coin',
    'icon' => 'etc_ertheia2',
    'price' => 200,
    'is_questitem' => true,
    'commissionItemType' => 'OTHER_ITEM',
    'is_stackable' => true,
    'is_depositable' => false,
  ],
  3494 => 
  [
    'id' => 3494,
    'type' => 'etcitem',
    'name' => 'Silver Golem',
    'add_name' => '',
    'description' => 'Low-grade coin',
    'icon' => 'etc_ertheia2',
    'price' => 100,
    'is_questitem' => true,
    'commissionItemType' => 'OTHER_ITEM',
    'is_stackable' => true,
    'is_depositable' => false,
  ],
  3495 => 
  [
    'id' => 3495,
    'type' => 'etcitem',
    'name' => 'Silver Undine',
    'add_name' => '',
    'description' => 'Mid-grade coin',
    'icon' => 'etc_ertheia2',
    'price' => 150,
    'is_questitem' => true,
    'commissionItemType' => 'OTHER_ITEM',
    'is_stackable' => true,
    'is_depositable' => false,
  ],
  3496 => 
  [
    'id' => 3496,
    'type' => 'etcitem',
    'name' => 'Beleth\'s Silver Dragon',
    'add_name' => '',
    'description' => 'Highest-grade coin',
    'icon' => 'etc_ertheia2',
    'price' => 300,
    'is_questitem' => true,
    'commissionItemType' => 'OTHER_ITEM',
    'is_stackable' => true,
    'is_depositable' => false,
  ],
  3497 => 
  [
    'id' => 3497,
    'type' => 'etcitem',
    'name' => 'Manak\'s Silver Dryad',
    'add_name' => '',
    'description' => 'Mid-grade coin',
    'icon' => 'etc_ertheia2',
    'price' => 150,
    'is_questitem' => true,
    'commissionItemType' => 'OTHER_ITEM',
    'is_stackable' => true,
    'is_depositable' => false,
  ],
  3498 => 
  [
    'id' => 3498,
    'type' => 'etcitem',
    'name' => 'Nia\'s Silver Fairy',
    'add_name' => '',
    'description' => 'Low-grade coin',
    'icon' => 'etc_ertheia2',
    'price' => 100,
    'is_questitem' => true,
    'commissionItemType' => 'OTHER_ITEM',
    'is_stackable' => true,
    'is_depositable' => false,
  ],
  3499 => 
  [
    'id' => 3499,
    'type' => 'etcitem',
    'name' => 'Fairy Dust',
    'add_name' => '',
    'description' => 'Powder that falls from the body of fairy. Is sold at an expensive price at shops.',
    'icon' => 'etc_ertheia2',
    'price' => 10000,
    'is_dropable' => false,
    'commissionItemType' => 'OTHER_ITEM',
    'is_questitem' => true,
    'is_depositable' => false,
  ],
];