<?php
return [
  37662 => 
  [
    'id' => 37662,
    'type' => 'armor',
    'name' => 'Refined Romantic Chapeau: Gold',
    'add_name' => '',
    'description' => '',
    'icon' => 'bm_romantic_chaperon_gold',
    'is_tradable' => false,
    'is_dropable' => false,
    'is_sellable' => false,
    'weight' => 10,
    'is_destroyable' => false,
    'bodypart' => 'hairall',
  ],
  37665 => 
  [
    'id' => 37665,
    'type' => 'armor',
    'name' => 'Refined Romantic Chapeau: Yellow',
    'add_name' => '',
    'description' => '',
    'icon' => 'bm_romantic_chaperon_yellow',
    'is_tradable' => false,
    'is_dropable' => false,
    'is_sellable' => false,
    'weight' => 10,
    'is_destroyable' => false,
    'bodypart' => 'hairall',
  ],
  37688 => 
  [
    'id' => 37688,
    'type' => 'weapon',
    'name' => 'Valentine Dagger',
    'add_name' => '',
    'description' => '',
    'icon' => 'ev_hallowinday_candy_i00',
    'weapon_type' => 'dagger',
    'is_tradable' => false,
    'is_dropable' => false,
    'is_sellable' => false,
    'soulshots' => 1,
    'spiritshots' => 1,
    'bodypart' => 'rhand',
  ],
  37689 => 
  [
    'id' => 37689,
    'type' => 'weapon',
    'name' => 'Valentine One-handed Sword',
    'add_name' => '',
    'description' => '',
    'icon' => 'ev_hallowinday_candy_i00',
    'weapon_type' => 'sword',
    'is_tradable' => false,
    'is_dropable' => false,
    'is_sellable' => false,
    'soulshots' => 1,
    'spiritshots' => 1,
    'bodypart' => 'rhand',
  ],
  37690 => 
  [
    'id' => 37690,
    'type' => 'weapon',
    'name' => 'Valentine Two-handed Sword',
    'add_name' => '',
    'description' => '',
    'icon' => 'ev_hallowinday_candy_i00',
    'weapon_type' => 'sword',
    'is_clan_depositable' => 'false',
    'is_tradable' => false,
    'is_dropable' => false,
    'is_sellable' => false,
    'is_commissionable' => 'false',
    'is_private_storeable' => 'false',
    'soulshots' => 1,
    'spiritshots' => 1,
    'bodypart' => 'lrhand',
    'weight' => 500,
  ],
  37691 => 
  [
    'id' => 37691,
    'type' => 'weapon',
    'name' => 'Valentine One-handed Club',
    'add_name' => '',
    'description' => '',
    'icon' => 'ev_hallowinday_candy_i00',
    'weapon_type' => 'blunt',
    'is_tradable' => false,
    'is_dropable' => false,
    'is_sellable' => false,
    'soulshots' => 1,
    'spiritshots' => 1,
    'bodypart' => 'rhand',
  ],
  37692 => 
  [
    'id' => 37692,
    'type' => 'weapon',
    'name' => 'Valentine Fist Weapon',
    'add_name' => '',
    'description' => '',
    'icon' => 'ev_hallowinday_candy_i00',
    'weapon_type' => 'dualfist',
    'is_tradable' => false,
    'is_dropable' => false,
    'is_sellable' => false,
    'soulshots' => 1,
    'spiritshots' => 1,
    'bodypart' => 'lrhand',
  ],
  37693 => 
  [
    'id' => 37693,
    'type' => 'weapon',
    'name' => 'Valentine Spear',
    'add_name' => '',
    'description' => '',
    'icon' => 'ev_hallowinday_candy_i00',
    'weapon_type' => 'pole',
    'is_tradable' => false,
    'is_dropable' => false,
    'is_sellable' => false,
    'soulshots' => 1,
    'spiritshots' => 1,
    'bodypart' => 'lrhand',
  ],
  37694 => 
  [
    'id' => 37694,
    'type' => 'weapon',
    'name' => 'Valentine Bow',
    'add_name' => '',
    'description' => '',
    'icon' => 'ev_hallowinday_candy_i00',
    'weapon_type' => 'bow',
    'is_tradable' => false,
    'is_dropable' => false,
    'is_sellable' => false,
    'soulshots' => 2,
    'spiritshots' => 1,
    'bodypart' => 'lrhand',
  ],
  37695 => 
  [
    'id' => 37695,
    'type' => 'weapon',
    'name' => 'Valentine Crossbow',
    'add_name' => '',
    'description' => '',
    'icon' => 'ev_hallowinday_candy_i00',
    'weapon_type' => 'twohandcrossbow',
    'is_clan_depositable' => 'false',
    'is_tradable' => false,
    'is_dropable' => false,
    'is_sellable' => false,
    'is_commissionable' => 'false',
    'is_private_storeable' => 'false',
    'soulshots' => 1,
    'spiritshots' => 1,
    'weight' => 500,
  ],
  37696 => 
  [
    'id' => 37696,
    'type' => 'weapon',
    'name' => 'Valentine One-handed Magic Sword',
    'add_name' => '',
    'description' => '',
    'icon' => 'ev_hallowinday_candy_i00',
    'weapon_type' => 'sword',
    'is_clan_depositable' => 'false',
    'is_tradable' => false,
    'is_dropable' => false,
    'is_sellable' => false,
    'is_commissionable' => 'false',
    'is_private_storeable' => 'false',
    'soulshots' => 1,
    'spiritshots' => 1,
    'bodypart' => 'rhand',
    'weight' => 500,
  ],
  37697 => 
  [
    'id' => 37697,
    'type' => 'weapon',
    'name' => 'Valentine One-handed Magic Blunt Weapon',
    'add_name' => '',
    'description' => '',
    'icon' => 'ev_hallowinday_candy_i00',
    'weapon_type' => 'blunt',
    'is_clan_depositable' => 'false',
    'is_tradable' => false,
    'is_dropable' => false,
    'is_sellable' => false,
    'is_commissionable' => 'false',
    'is_private_storeable' => 'false',
    'soulshots' => 1,
    'spiritshots' => 1,
    'bodypart' => 'rhand',
    'weight' => 500,
  ],
  37698 => 
  [
    'id' => 37698,
    'type' => 'weapon',
    'name' => 'Valentine Two-handed Magic Blunt Weapon',
    'add_name' => '',
    'description' => '',
    'icon' => 'ev_hallowinday_candy_i00',
    'weapon_type' => 'blunt',
    'is_clan_depositable' => 'false',
    'is_tradable' => false,
    'is_dropable' => false,
    'is_sellable' => false,
    'is_commissionable' => 'false',
    'is_private_storeable' => 'false',
    'soulshots' => 1,
    'spiritshots' => 1,
    'bodypart' => 'lrhand',
    'weight' => 500,
  ],
  37699 => 
  [
    'id' => 37699,
    'type' => 'weapon',
    'name' => 'Valentine Dual Sword',
    'add_name' => '',
    'description' => '',
    'icon' => 'ev_hallowinday_candy_i00',
    'weapon_type' => 'dual',
    'is_tradable' => false,
    'is_dropable' => false,
    'is_sellable' => false,
    'soulshots' => 1,
    'spiritshots' => 1,
    'bodypart' => 'lrhand',
  ],
];