<?php
return [
  49100 => 
  [
    'id' => 49100,
    'type' => 'etcitem',
    'name' => 'Teleport Stone: Floran Village',
    'add_name' => '',
    'description' => '',
    'icon' => 'etc_capture_stone_i00',
    'weight' => 120,
    'is_tradable' => false,
    'is_dropable' => false,
    'is_sellable' => false,
    'is_freightable' => true,
  ],
  49101 => 
  [
    'id' => 49101,
    'type' => 'etcitem',
    'name' => 'Teleport Stone: Giran',
    'add_name' => '',
    'description' => '',
    'icon' => 'etc_capture_stone_i00',
    'weight' => 120,
    'is_tradable' => false,
    'is_dropable' => false,
    'is_sellable' => false,
    'is_freightable' => true,
  ],
  49102 => 
  [
    'id' => 49102,
    'type' => 'etcitem',
    'name' => 'Teleport Stone: Oren',
    'add_name' => '',
    'description' => '',
    'icon' => 'etc_capture_stone_i00',
    'weight' => 120,
    'is_tradable' => false,
    'is_dropable' => false,
    'is_sellable' => false,
    'is_freightable' => true,
  ],
  49103 => 
  [
    'id' => 49103,
    'type' => 'etcitem',
    'name' => 'Teleport Stone: Ivory Tower',
    'add_name' => '',
    'description' => '',
    'icon' => 'etc_capture_stone_i00',
    'weight' => 120,
    'is_tradable' => false,
    'is_dropable' => false,
    'is_sellable' => false,
    'is_freightable' => true,
  ],
  49104 => 
  [
    'id' => 49104,
    'type' => 'etcitem',
    'name' => 'Teleport Stone: Hunters\' Village',
    'add_name' => '',
    'description' => '',
    'icon' => 'etc_capture_stone_i00',
    'weight' => 120,
    'is_tradable' => false,
    'is_dropable' => false,
    'is_sellable' => false,
    'is_freightable' => true,
  ],
  49105 => 
  [
    'id' => 49105,
    'type' => 'etcitem',
    'name' => 'Teleport Stone: Entrance to Cruma Tower',
    'add_name' => '',
    'description' => '',
    'icon' => 'etc_capture_stone_i00',
    'weight' => 120,
    'is_tradable' => false,
    'is_dropable' => false,
    'is_sellable' => false,
    'is_freightable' => true,
  ],
  49106 => 
  [
    'id' => 49106,
    'type' => 'etcitem',
    'name' => 'Teleport Stone: Entrance to Dragon Valley',
    'add_name' => '',
    'description' => '',
    'icon' => 'etc_capture_stone_i00',
    'weight' => 120,
    'is_tradable' => false,
    'is_dropable' => false,
    'is_sellable' => false,
    'is_freightable' => true,
  ],
  49107 => 
  [
    'id' => 49107,
    'type' => 'etcitem',
    'name' => 'Teleport Stone: Dragon Valley Bridge',
    'add_name' => '',
    'description' => '',
    'icon' => 'etc_capture_stone_i00',
    'weight' => 120,
    'is_tradable' => false,
    'is_dropable' => false,
    'is_sellable' => false,
    'is_freightable' => true,
  ],
  49108 => 
  [
    'id' => 49108,
    'type' => 'etcitem',
    'name' => 'Beauty Chest',
    'add_name' => '',
    'description' => '',
    'icon' => 'etc_box_of_adventure_2_i00',
    'is_stackable' => true,
    'handler' => 'extractableitems',
  ],
  49109 => 
  [
    'id' => 49109,
    'type' => 'etcitem',
    'name' => 'Buff Scroll Chest',
    'add_name' => '',
    'description' => '',
    'icon' => 'etc_box_of_adventure_3_i00',
    'is_stackable' => true,
    'handler' => 'extractableitems',
  ],
  49110 => 
  [
    'id' => 49110,
    'type' => 'etcitem',
    'name' => 'High-Quality Dye Chest',
    'add_name' => '',
    'description' => '',
    'icon' => 'etc_box_of_adventure_4_i00',
    'is_stackable' => true,
    'handler' => 'itemskills',
  ],
  49111 => 
  [
    'id' => 49111,
    'type' => 'etcitem',
    'name' => 'Dye Chest',
    'add_name' => '',
    'description' => '',
    'icon' => 'etc_box_of_adventure_5_i00',
    'is_stackable' => true,
    'handler' => 'itemskills',
  ],
  49112 => 
  [
    'id' => 49112,
    'type' => 'etcitem',
    'name' => 'C-grade Staff Pack',
    'add_name' => '',
    'description' => '',
    'icon' => 'etc_treasure_box_i02',
    'is_stackable' => true,
    'handler' => 'itemskills',
  ],
  49113 => 
  [
    'id' => 49113,
    'type' => 'etcitem',
    'name' => 'C-grade Fist Weapon Pack',
    'add_name' => '',
    'description' => '',
    'icon' => 'etc_treasure_box_i03',
    'is_stackable' => true,
    'handler' => 'itemskills',
  ],
  49114 => 
  [
    'id' => 49114,
    'type' => 'etcitem',
    'name' => 'C-grade Spear Pack',
    'add_name' => '',
    'description' => '',
    'icon' => 'etc_treasure_box_i04',
    'is_stackable' => true,
    'handler' => 'itemskills',
  ],
  49115 => 
  [
    'id' => 49115,
    'type' => 'etcitem',
    'name' => 'C-grade Blunt Weapon Pack',
    'add_name' => '',
    'description' => '',
    'icon' => 'etc_treasure_box_i05',
    'is_stackable' => true,
    'handler' => 'itemskills',
  ],
  49116 => 
  [
    'id' => 49116,
    'type' => 'etcitem',
    'name' => 'C-grade Dagger Pack',
    'add_name' => '',
    'description' => '',
    'icon' => 'etc_treasure_box_i06',
    'is_stackable' => true,
    'handler' => 'itemskills',
  ],
  49117 => 
  [
    'id' => 49117,
    'type' => 'etcitem',
    'name' => 'C-grade One-handed Sword Pack',
    'add_name' => '',
    'description' => '',
    'icon' => 'etc_treasure_box_i07',
    'is_stackable' => true,
    'handler' => 'itemskills',
  ],
  49118 => 
  [
    'id' => 49118,
    'type' => 'etcitem',
    'name' => 'C-grade Bow Pack',
    'add_name' => '',
    'description' => '',
    'icon' => 'etc_treasure_box_i08',
    'is_stackable' => true,
    'handler' => 'itemskills',
  ],
  49119 => 
  [
    'id' => 49119,
    'type' => 'armor',
    'name' => 'Halloween Outfit',
    'add_name' => '',
    'description' => '',
    'icon' => 'ev_wp_halloween',
    'armor_type' => 'heavy',
    'bodypart' => 'alldress',
    'weight' => 1000,
    'is_tradable' => false,
    'is_dropable' => false,
  ],
  49120 => 
  [
    'id' => 49120,
    'type' => 'armor',
    'name' => 'Halloween Outfit',
    'add_name' => '',
    'description' => '',
    'icon' => 'ev_wp_halloween',
    'armor_type' => 'heavy',
    'bodypart' => 'alldress',
    'weight' => 1000,
    'is_dropable' => false,
  ],
  49121 => 
  [
    'id' => 49121,
    'type' => 'armor',
    'name' => 'Party Mask',
    'add_name' => '',
    'description' => '',
    'icon' => 'etc_party_mask_i00',
    'bodypart' => 'hair',
    'weight' => 10,
    'is_tradable' => false,
    'is_dropable' => false,
  ],
  49122 => 
  [
    'id' => 49122,
    'type' => 'armor',
    'name' => 'Ring of Macken',
    'add_name' => '',
    'description' => '',
    'icon' => 'ev_11th_rare_acc_ring',
    'bodypart' => 'rfinger;lfinger',
    'weight' => 150,
    'is_tradable' => false,
    'is_dropable' => false,
  ],
  49123 => 
  [
    'id' => 49123,
    'type' => 'armor',
    'name' => 'Ring of Macken',
    'add_name' => '',
    'description' => '',
    'icon' => 'ev_11th_rare_acc_ring',
    'bodypart' => 'rfinger;lfinger',
    'weight' => 150,
  ],
  49124 => 
  [
    'id' => 49124,
    'type' => 'armor',
    'name' => 'Earring of Macken',
    'add_name' => '',
    'description' => '',
    'icon' => 'ev_11th_rare_acc_earing',
    'bodypart' => 'rear;lear',
    'weight' => 150,
    'is_tradable' => false,
    'is_dropable' => false,
  ],
  49125 => 
  [
    'id' => 49125,
    'type' => 'armor',
    'name' => 'Earring of Macken',
    'add_name' => '',
    'description' => '',
    'icon' => 'ev_11th_rare_acc_earing',
    'bodypart' => 'rear;lear',
    'weight' => 150,
  ],
  49126 => 
  [
    'id' => 49126,
    'type' => 'armor',
    'name' => 'Necklace of Macken',
    'add_name' => '',
    'description' => '',
    'icon' => 'ev_11th_rare_acc_necklace',
    'bodypart' => 'neck',
    'weight' => 150,
    'is_tradable' => false,
    'is_dropable' => false,
  ],
  49127 => 
  [
    'id' => 49127,
    'type' => 'armor',
    'name' => 'Necklace of Macken',
    'add_name' => '',
    'description' => '',
    'icon' => 'ev_11th_rare_acc_necklace',
    'bodypart' => 'neck',
    'weight' => 150,
  ],
  49128 => 
  [
    'id' => 49128,
    'type' => 'etcitem',
    'name' => 'Gift Box',
    'add_name' => '',
    'description' => '',
    'icon' => 'new_user_box',
    'is_tradable' => false,
    'is_dropable' => false,
    'is_sellable' => false,
    'is_stackable' => true,
    'handler' => 'itemskills',
  ],
  49129 => 
  [
    'id' => 49129,
    'type' => 'etcitem',
    'name' => 'Anniversary Coin',
    'add_name' => '',
    'description' => '',
    'icon' => 'etc_11th_token',
    'is_tradable' => false,
    'is_dropable' => false,
    'is_sellable' => false,
    'is_destroyable' => false,
    'is_stackable' => true,
    'is_freightable' => true,
  ],
  49130 => 
  [
    'id' => 49130,
    'type' => 'etcitem',
    'name' => 'Scroll: Summon Piero',
    'add_name' => '',
    'description' => '',
    'icon' => 'etc_11th_event_solo',
    'is_tradable' => false,
    'is_dropable' => false,
    'is_sellable' => false,
    'is_stackable' => true,
  ],
  49131 => 
  [
    'id' => 49131,
    'type' => 'etcitem',
    'name' => 'Magic Number Cube',
    'add_name' => '',
    'description' => '',
    'icon' => 'etc_11th_event_group',
    'is_tradable' => false,
    'is_dropable' => false,
    'is_sellable' => false,
    'is_destroyable' => false,
  ],
  49132 => 
  [
    'id' => 49132,
    'type' => 'etcitem',
    'name' => 'Membership Card',
    'add_name' => '',
    'description' => '',
    'icon' => 'ev_buff_11th',
    'is_tradable' => false,
    'is_dropable' => false,
    'is_sellable' => false,
    'is_destroyable' => false,
  ],
  49133 => 
  [
    'id' => 49133,
    'type' => 'etcitem',
    'name' => 'Venus\' Rune - Low Level',
    'add_name' => '',
    'description' => '',
    'icon' => 'skill19226',
    'etcitem_type' => 'encht_attr_rune',
    'is_tradable' => false,
    'is_dropable' => false,
    'time' => 21600,
    'handler' => 'itemskills',
    'is_oly_restricted' => true,
  ],
  49134 => 
  [
    'id' => 49134,
    'type' => 'weapon',
    'name' => 'Dual Candle Sword',
    'add_name' => '',
    'description' => '',
    'icon' => 'ev_11th_candle',
    'weapon_type' => 'dual',
    'bodypart' => 'lrhand',
    'weight' => 2530,
    'soulshots' => 1,
    'spiritshots' => 1,
    'is_tradable' => false,
    'is_dropable' => false,
    'is_destroyable' => false,
  ],
  49135 => 
  [
    'id' => 49135,
    'type' => 'weapon',
    'name' => 'Dual Candle Sword',
    'add_name' => '',
    'description' => '',
    'icon' => 'ev_11th_candle',
    'weapon_type' => 'dual',
    'bodypart' => 'lrhand',
    'weight' => 2530,
    'soulshots' => 1,
    'spiritshots' => 1,
  ],
  49136 => 
  [
    'id' => 49136,
    'type' => 'etcitem',
    'name' => 'Venus\' Rune - High Level',
    'add_name' => '',
    'description' => '',
    'icon' => 'skill19226',
    'etcitem_type' => 'encht_attr_rune',
    'is_tradable' => false,
    'is_dropable' => false,
    'time' => 21600,
    'handler' => 'itemskills',
    'is_oly_restricted' => true,
  ],
  49137 => 
  [
    'id' => 49137,
    'type' => 'etcitem',
    'name' => 'Venus\' Rune Chest (Low Level]',
    'add_name' => '',
    'description' => '',
    'icon' => 'etc_pi_box_belief_pack',
    'is_tradable' => false,
    'is_dropable' => false,
    'is_destroyable' => false,
    'is_sellable' => false,
    'is_stackable' => true,
    'is_freightable' => true,
    'handler' => 'extractableitems',
  ],
  49138 => 
  [
    'id' => 49138,
    'type' => 'etcitem',
    'name' => 'Venus\' Rune Chest (High Level]',
    'add_name' => '',
    'description' => '',
    'icon' => 'etc_pi_box_love_pack',
    'is_tradable' => false,
    'is_dropable' => false,
    'is_destroyable' => false,
    'is_sellable' => false,
    'is_stackable' => true,
    'is_freightable' => true,
    'handler' => 'extractableitems',
  ],
  49139 => 
  [
    'id' => 49139,
    'type' => 'etcitem',
    'name' => 'Dual Swords\' Gift Pack',
    'add_name' => '',
    'description' => '',
    'icon' => 'etc_pi_box_joy_pack',
    'is_tradable' => false,
    'is_dropable' => false,
    'is_destroyable' => false,
    'is_sellable' => false,
    'is_stackable' => true,
    'is_freightable' => true,
    'handler' => 'extractableitems',
  ],
  49140 => 
  [
    'id' => 49140,
    'type' => 'weapon',
    'name' => 'Horn of Glory',
    'add_name' => '',
    'description' => '',
    'icon' => 'etc_ertheia2',
    'weapon_type' => 'sword',
    'bodypart' => 'rhand',
    'crystal_type' => 'c',
    'weight' => 540,
    'soulshots' => 1,
    'spiritshots' => 1,
    'is_magic_weapon' => true,
  ],
  49141 => 
  [
    'id' => 49141,
    'type' => 'weapon',
    'name' => 'Horn of Glory',
    'add_name' => '',
    'description' => '',
    'icon' => 'etc_ertheia2',
    'weapon_type' => 'sword',
    'bodypart' => 'rhand',
    'crystal_type' => 'c',
    'weight' => 540,
    'soulshots' => 1,
    'spiritshots' => 1,
    'is_magic_weapon' => true,
  ],
  49142 => 
  [
    'id' => 49142,
    'type' => 'weapon',
    'name' => 'Horn of Glory',
    'add_name' => '',
    'description' => '',
    'icon' => 'etc_ertheia2',
    'weapon_type' => 'sword',
    'bodypart' => 'rhand',
    'crystal_type' => 'c',
    'weight' => 540,
    'soulshots' => 1,
    'spiritshots' => 1,
    'is_magic_weapon' => true,
  ],
  49143 => 
  [
    'id' => 49143,
    'type' => 'weapon',
    'name' => 'Pata',
    'add_name' => '',
    'description' => '',
    'icon' => 'etc_ertheia2',
    'weapon_type' => 'dualfist',
    'bodypart' => 'lrhand',
    'crystal_type' => 'b',
    'weight' => 1440,
    'soulshots' => 1,
    'spiritshots' => 1,
  ],
  49144 => 
  [
    'id' => 49144,
    'type' => 'weapon',
    'name' => 'Pata',
    'add_name' => '',
    'description' => '',
    'icon' => 'etc_ertheia2',
    'weapon_type' => 'dualfist',
    'bodypart' => 'lrhand',
    'crystal_type' => 'b',
    'weight' => 1440,
    'soulshots' => 1,
    'spiritshots' => 1,
  ],
  49145 => 
  [
    'id' => 49145,
    'type' => 'weapon',
    'name' => 'Pata',
    'add_name' => '',
    'description' => '',
    'icon' => 'etc_ertheia2',
    'weapon_type' => 'dualfist',
    'bodypart' => 'lrhand',
    'crystal_type' => 'b',
    'weight' => 1440,
    'soulshots' => 1,
    'spiritshots' => 1,
  ],
  49146 => 
  [
    'id' => 49146,
    'type' => 'weapon',
    'name' => 'Bastard Sword',
    'add_name' => '',
    'description' => '',
    'icon' => 'etc_ertheia2',
    'weapon_type' => 'sword',
    'bodypart' => 'rhand',
    'crystal_type' => 'd',
    'weight' => 1510,
    'soulshots' => 1,
    'spiritshots' => 1,
  ],
  49147 => 
  [
    'id' => 49147,
    'type' => 'weapon',
    'name' => 'Bastard Sword',
    'add_name' => '',
    'description' => '',
    'icon' => 'etc_ertheia2',
    'weapon_type' => 'sword',
    'bodypart' => 'rhand',
    'crystal_type' => 'd',
    'weight' => 1510,
    'soulshots' => 1,
    'spiritshots' => 1,
  ],
  49148 => 
  [
    'id' => 49148,
    'type' => 'weapon',
    'name' => 'Bastard Sword',
    'add_name' => '',
    'description' => '',
    'icon' => 'etc_ertheia2',
    'weapon_type' => 'sword',
    'bodypart' => 'rhand',
    'crystal_type' => 'd',
    'weight' => 1510,
    'soulshots' => 1,
    'spiritshots' => 1,
  ],
  49149 => 
  [
    'id' => 49149,
    'type' => 'weapon',
    'name' => 'Saber',
    'add_name' => '',
    'description' => '',
    'icon' => 'etc_ertheia2',
    'weapon_type' => 'sword',
    'bodypart' => 'rhand',
    'crystal_type' => 'd',
    'weight' => 1520,
    'soulshots' => 1,
    'spiritshots' => 1,
  ],
  49150 => 
  [
    'id' => 49150,
    'type' => 'weapon',
    'name' => 'Saber',
    'add_name' => '',
    'description' => '',
    'icon' => 'etc_ertheia2',
    'weapon_type' => 'sword',
    'bodypart' => 'rhand',
    'crystal_type' => 'd',
    'weight' => 1520,
    'soulshots' => 1,
    'spiritshots' => 1,
  ],
  49151 => 
  [
    'id' => 49151,
    'type' => 'weapon',
    'name' => 'Saber',
    'add_name' => '',
    'description' => '',
    'icon' => 'etc_ertheia2',
    'weapon_type' => 'sword',
    'bodypart' => 'rhand',
    'crystal_type' => 'd',
    'weight' => 1520,
    'soulshots' => 1,
    'spiritshots' => 1,
  ],
  49152 => 
  [
    'id' => 49152,
    'type' => 'weapon',
    'name' => 'Spinebone Sword',
    'add_name' => '',
    'description' => '',
    'icon' => 'etc_ertheia2',
    'weapon_type' => 'sword',
    'bodypart' => 'rhand',
    'crystal_type' => 'd',
    'weight' => 1510,
    'soulshots' => 1,
    'spiritshots' => 1,
  ],
  49153 => 
  [
    'id' => 49153,
    'type' => 'weapon',
    'name' => 'Spinebone Sword',
    'add_name' => '',
    'description' => '',
    'icon' => 'etc_ertheia2',
    'weapon_type' => 'sword',
    'bodypart' => 'rhand',
    'crystal_type' => 'd',
    'weight' => 1510,
    'soulshots' => 1,
    'spiritshots' => 1,
  ],
  49154 => 
  [
    'id' => 49154,
    'type' => 'weapon',
    'name' => 'Spinebone Sword',
    'add_name' => '',
    'description' => '',
    'icon' => 'etc_ertheia2',
    'weapon_type' => 'sword',
    'bodypart' => 'rhand',
    'crystal_type' => 'd',
    'weight' => 1510,
    'soulshots' => 1,
    'spiritshots' => 1,
  ],
  49155 => 
  [
    'id' => 49155,
    'type' => 'weapon',
    'name' => 'Artisan\'s Sword',
    'add_name' => '',
    'description' => '',
    'icon' => 'etc_ertheia2',
    'weapon_type' => 'sword',
    'bodypart' => 'rhand',
    'crystal_type' => 'd',
    'weight' => 1500,
    'soulshots' => 1,
    'spiritshots' => 1,
  ],
  49156 => 
  [
    'id' => 49156,
    'type' => 'weapon',
    'name' => 'Artisan\'s Sword',
    'add_name' => '',
    'description' => '',
    'icon' => 'etc_ertheia2',
    'weapon_type' => 'sword',
    'bodypart' => 'rhand',
    'crystal_type' => 'd',
    'weight' => 1500,
    'soulshots' => 1,
    'spiritshots' => 1,
  ],
  49157 => 
  [
    'id' => 49157,
    'type' => 'weapon',
    'name' => 'Artisan\'s Sword',
    'add_name' => '',
    'description' => '',
    'icon' => 'etc_ertheia2',
    'weapon_type' => 'sword',
    'bodypart' => 'rhand',
    'crystal_type' => 'd',
    'weight' => 1500,
    'soulshots' => 1,
    'spiritshots' => 1,
  ],
  49158 => 
  [
    'id' => 49158,
    'type' => 'weapon',
    'name' => 'Crimson Sword',
    'add_name' => '',
    'description' => '',
    'icon' => 'etc_ertheia2',
    'weapon_type' => 'sword',
    'bodypart' => 'rhand',
    'crystal_type' => 'd',
    'weight' => 1490,
    'soulshots' => 1,
    'spiritshots' => 1,
  ],
  49159 => 
  [
    'id' => 49159,
    'type' => 'weapon',
    'name' => 'Crimson Sword',
    'add_name' => '',
    'description' => '',
    'icon' => 'etc_ertheia2',
    'weapon_type' => 'sword',
    'bodypart' => 'rhand',
    'crystal_type' => 'd',
    'weight' => 1490,
    'soulshots' => 1,
    'spiritshots' => 1,
  ],
  49160 => 
  [
    'id' => 49160,
    'type' => 'weapon',
    'name' => 'Crimson Sword',
    'add_name' => '',
    'description' => '',
    'icon' => 'etc_ertheia2',
    'weapon_type' => 'sword',
    'bodypart' => 'rhand',
    'crystal_type' => 'd',
    'weight' => 1490,
    'soulshots' => 1,
    'spiritshots' => 1,
  ],
  49161 => 
  [
    'id' => 49161,
    'type' => 'weapon',
    'name' => 'Knight\'s Sword',
    'add_name' => '',
    'description' => '',
    'icon' => 'etc_ertheia2',
    'weapon_type' => 'sword',
    'bodypart' => 'rhand',
    'crystal_type' => 'd',
    'weight' => 1500,
    'soulshots' => 1,
    'spiritshots' => 1,
  ],
  49162 => 
  [
    'id' => 49162,
    'type' => 'weapon',
    'name' => 'Knight\'s Sword',
    'add_name' => '',
    'description' => '',
    'icon' => 'etc_ertheia2',
    'weapon_type' => 'sword',
    'bodypart' => 'rhand',
    'crystal_type' => 'd',
    'weight' => 1500,
    'soulshots' => 1,
    'spiritshots' => 1,
  ],
  49163 => 
  [
    'id' => 49163,
    'type' => 'weapon',
    'name' => 'Knight\'s Sword',
    'add_name' => '',
    'description' => '',
    'icon' => 'etc_ertheia2',
    'weapon_type' => 'sword',
    'bodypart' => 'rhand',
    'crystal_type' => 'd',
    'weight' => 1500,
    'soulshots' => 1,
    'spiritshots' => 1,
  ],
  49164 => 
  [
    'id' => 49164,
    'type' => 'weapon',
    'name' => 'Sword of Revolution',
    'add_name' => '',
    'description' => '',
    'icon' => 'etc_ertheia2',
    'weapon_type' => 'sword',
    'bodypart' => 'rhand',
    'crystal_type' => 'd',
    'weight' => 1450,
    'soulshots' => 1,
    'spiritshots' => 1,
  ],
  49165 => 
  [
    'id' => 49165,
    'type' => 'weapon',
    'name' => 'Sword of Revolution',
    'add_name' => '',
    'description' => '',
    'icon' => 'etc_ertheia2',
    'weapon_type' => 'sword',
    'bodypart' => 'rhand',
    'crystal_type' => 'd',
    'weight' => 1450,
    'soulshots' => 1,
    'spiritshots' => 1,
  ],
  49166 => 
  [
    'id' => 49166,
    'type' => 'weapon',
    'name' => 'Sword of Revolution',
    'add_name' => '',
    'description' => '',
    'icon' => 'etc_ertheia2',
    'weapon_type' => 'sword',
    'bodypart' => 'rhand',
    'crystal_type' => 'd',
    'weight' => 1450,
    'soulshots' => 1,
    'spiritshots' => 1,
  ],
  49167 => 
  [
    'id' => 49167,
    'type' => 'weapon',
    'name' => 'Elven Sword',
    'add_name' => '',
    'description' => '',
    'icon' => 'etc_ertheia2',
    'weapon_type' => 'sword',
    'bodypart' => 'rhand',
    'crystal_type' => 'd',
    'weight' => 1470,
    'soulshots' => 1,
    'spiritshots' => 1,
  ],
  49168 => 
  [
    'id' => 49168,
    'type' => 'weapon',
    'name' => 'Elven Sword',
    'add_name' => '',
    'description' => '',
    'icon' => 'etc_ertheia2',
    'weapon_type' => 'sword',
    'bodypart' => 'rhand',
    'crystal_type' => 'd',
    'weight' => 1470,
    'soulshots' => 1,
    'spiritshots' => 1,
  ],
  49169 => 
  [
    'id' => 49169,
    'type' => 'weapon',
    'name' => 'Elven Sword',
    'add_name' => '',
    'description' => '',
    'icon' => 'etc_ertheia2',
    'weapon_type' => 'sword',
    'bodypart' => 'rhand',
    'crystal_type' => 'd',
    'weight' => 1470,
    'soulshots' => 1,
    'spiritshots' => 1,
  ],
  49170 => 
  [
    'id' => 49170,
    'type' => 'weapon',
    'name' => 'Elven Long Sword',
    'add_name' => '',
    'description' => '',
    'icon' => 'etc_ertheia2',
    'weapon_type' => 'sword',
    'bodypart' => 'rhand',
    'crystal_type' => 'd',
    'weight' => 1440,
    'soulshots' => 1,
    'spiritshots' => 1,
  ],
  49171 => 
  [
    'id' => 49171,
    'type' => 'weapon',
    'name' => 'Elven Long Sword',
    'add_name' => '',
    'description' => '',
    'icon' => 'etc_ertheia2',
    'weapon_type' => 'sword',
    'bodypart' => 'rhand',
    'crystal_type' => 'd',
    'weight' => 1440,
    'soulshots' => 1,
    'spiritshots' => 1,
  ],
  49172 => 
  [
    'id' => 49172,
    'type' => 'weapon',
    'name' => 'Elven Long Sword',
    'add_name' => '',
    'description' => '',
    'icon' => 'etc_ertheia2',
    'weapon_type' => 'sword',
    'bodypart' => 'rhand',
    'crystal_type' => 'd',
    'weight' => 1440,
    'soulshots' => 1,
    'spiritshots' => 1,
  ],
  49173 => 
  [
    'id' => 49173,
    'type' => 'weapon',
    'name' => 'Tomahawk',
    'add_name' => '',
    'description' => '',
    'icon' => 'etc_ertheia2',
    'weapon_type' => 'blunt',
    'bodypart' => 'rhand',
    'crystal_type' => 'd',
    'weight' => 1780,
    'soulshots' => 1,
    'spiritshots' => 1,
  ],
  49174 => 
  [
    'id' => 49174,
    'type' => 'weapon',
    'name' => 'Tomahawk',
    'add_name' => '',
    'description' => '',
    'icon' => 'etc_ertheia2',
    'weapon_type' => 'blunt',
    'bodypart' => 'rhand',
    'crystal_type' => 'd',
    'weight' => 1780,
    'soulshots' => 1,
    'spiritshots' => 1,
  ],
  49175 => 
  [
    'id' => 49175,
    'type' => 'weapon',
    'name' => 'Tomahawk',
    'add_name' => '',
    'description' => '',
    'icon' => 'etc_ertheia2',
    'weapon_type' => 'blunt',
    'bodypart' => 'rhand',
    'crystal_type' => 'd',
    'weight' => 1780,
    'soulshots' => 1,
    'spiritshots' => 1,
  ],
  49176 => 
  [
    'id' => 49176,
    'type' => 'weapon',
    'name' => 'Morning Star',
    'add_name' => '',
    'description' => '',
    'icon' => 'etc_ertheia2',
    'weapon_type' => 'blunt',
    'bodypart' => 'rhand',
    'crystal_type' => 'd',
    'weight' => 1720,
    'soulshots' => 1,
    'spiritshots' => 1,
  ],
  49177 => 
  [
    'id' => 49177,
    'type' => 'weapon',
    'name' => 'Morning Star',
    'add_name' => '',
    'description' => '',
    'icon' => 'etc_ertheia2',
    'weapon_type' => 'blunt',
    'bodypart' => 'rhand',
    'crystal_type' => 'd',
    'weight' => 1720,
    'soulshots' => 1,
    'spiritshots' => 1,
  ],
  49178 => 
  [
    'id' => 49178,
    'type' => 'weapon',
    'name' => 'Morning Star',
    'add_name' => '',
    'description' => '',
    'icon' => 'etc_ertheia2',
    'weapon_type' => 'blunt',
    'bodypart' => 'rhand',
    'crystal_type' => 'd',
    'weight' => 1720,
    'soulshots' => 1,
    'spiritshots' => 1,
  ],
  49179 => 
  [
    'id' => 49179,
    'type' => 'weapon',
    'name' => 'Hand Axe',
    'add_name' => '',
    'description' => '',
    'icon' => 'etc_ertheia2',
    'weapon_type' => 'blunt',
    'bodypart' => 'rhand',
    'crystal_type' => 'd',
    'weight' => 1820,
    'soulshots' => 1,
    'spiritshots' => 1,
  ],
  49180 => 
  [
    'id' => 49180,
    'type' => 'weapon',
    'name' => 'Hand Axe',
    'add_name' => '',
    'description' => '',
    'icon' => 'etc_ertheia2',
    'weapon_type' => 'blunt',
    'bodypart' => 'rhand',
    'crystal_type' => 'd',
    'weight' => 1820,
    'soulshots' => 1,
    'spiritshots' => 1,
  ],
  49181 => 
  [
    'id' => 49181,
    'type' => 'weapon',
    'name' => 'Hand Axe',
    'add_name' => '',
    'description' => '',
    'icon' => 'etc_ertheia2',
    'weapon_type' => 'blunt',
    'bodypart' => 'rhand',
    'crystal_type' => 'd',
    'weight' => 1820,
    'soulshots' => 1,
    'spiritshots' => 1,
  ],
  49182 => 
  [
    'id' => 49182,
    'type' => 'weapon',
    'name' => 'Spiked Club',
    'add_name' => '',
    'description' => '',
    'icon' => 'etc_ertheia2',
    'weapon_type' => 'blunt',
    'bodypart' => 'rhand',
    'crystal_type' => 'd',
    'weight' => 1750,
    'soulshots' => 1,
    'spiritshots' => 1,
  ],
  49183 => 
  [
    'id' => 49183,
    'type' => 'weapon',
    'name' => 'Spiked Club',
    'add_name' => '',
    'description' => '',
    'icon' => 'etc_ertheia2',
    'weapon_type' => 'blunt',
    'bodypart' => 'rhand',
    'crystal_type' => 'd',
    'weight' => 1750,
    'soulshots' => 1,
    'spiritshots' => 1,
  ],
  49184 => 
  [
    'id' => 49184,
    'type' => 'weapon',
    'name' => 'Spiked Club',
    'add_name' => '',
    'description' => '',
    'icon' => 'etc_ertheia2',
    'weapon_type' => 'blunt',
    'bodypart' => 'rhand',
    'crystal_type' => 'd',
    'weight' => 1750,
    'soulshots' => 1,
    'spiritshots' => 1,
  ],
  49185 => 
  [
    'id' => 49185,
    'type' => 'weapon',
    'name' => 'Tarbar',
    'add_name' => '',
    'description' => '',
    'icon' => 'etc_ertheia2',
    'weapon_type' => 'blunt',
    'bodypart' => 'rhand',
    'crystal_type' => 'd',
    'weight' => 1730,
    'soulshots' => 1,
    'spiritshots' => 1,
  ],
  49186 => 
  [
    'id' => 49186,
    'type' => 'weapon',
    'name' => 'Tarbar',
    'add_name' => '',
    'description' => '',
    'icon' => 'etc_ertheia2',
    'weapon_type' => 'blunt',
    'bodypart' => 'rhand',
    'crystal_type' => 'd',
    'weight' => 1730,
    'soulshots' => 1,
    'spiritshots' => 1,
  ],
  49187 => 
  [
    'id' => 49187,
    'type' => 'weapon',
    'name' => 'Tarbar',
    'add_name' => '',
    'description' => '',
    'icon' => 'etc_ertheia2',
    'weapon_type' => 'blunt',
    'bodypart' => 'rhand',
    'crystal_type' => 'd',
    'weight' => 1730,
    'soulshots' => 1,
    'spiritshots' => 1,
  ],
  49188 => 
  [
    'id' => 49188,
    'type' => 'weapon',
    'name' => 'Bonebreaker',
    'add_name' => '',
    'description' => '',
    'icon' => 'etc_ertheia2',
    'weapon_type' => 'blunt',
    'bodypart' => 'rhand',
    'crystal_type' => 'd',
    'weight' => 1720,
    'soulshots' => 1,
    'spiritshots' => 1,
  ],
  49189 => 
  [
    'id' => 49189,
    'type' => 'weapon',
    'name' => 'Bonebreaker',
    'add_name' => '',
    'description' => '',
    'icon' => 'etc_ertheia2',
    'weapon_type' => 'blunt',
    'bodypart' => 'rhand',
    'crystal_type' => 'd',
    'weight' => 1720,
    'soulshots' => 1,
    'spiritshots' => 1,
  ],
  49190 => 
  [
    'id' => 49190,
    'type' => 'weapon',
    'name' => 'Bonebreaker',
    'add_name' => '',
    'description' => '',
    'icon' => 'etc_ertheia2',
    'weapon_type' => 'blunt',
    'bodypart' => 'rhand',
    'crystal_type' => 'd',
    'weight' => 1720,
    'soulshots' => 1,
    'spiritshots' => 1,
  ],
  49191 => 
  [
    'id' => 49191,
    'type' => 'weapon',
    'name' => 'Heavy Mace',
    'add_name' => '',
    'description' => '',
    'icon' => 'etc_ertheia2',
    'weapon_type' => 'blunt',
    'bodypart' => 'rhand',
    'crystal_type' => 'd',
    'weight' => 1800,
    'soulshots' => 1,
    'spiritshots' => 1,
  ],
  49192 => 
  [
    'id' => 49192,
    'type' => 'weapon',
    'name' => 'Heavy Mace',
    'add_name' => '',
    'description' => '',
    'icon' => 'etc_ertheia2',
    'weapon_type' => 'blunt',
    'bodypart' => 'rhand',
    'crystal_type' => 'd',
    'weight' => 1800,
    'soulshots' => 1,
    'spiritshots' => 1,
  ],
  49193 => 
  [
    'id' => 49193,
    'type' => 'weapon',
    'name' => 'Heavy Mace',
    'add_name' => '',
    'description' => '',
    'icon' => 'etc_ertheia2',
    'weapon_type' => 'blunt',
    'bodypart' => 'rhand',
    'crystal_type' => 'd',
    'weight' => 1800,
    'soulshots' => 1,
    'spiritshots' => 1,
  ],
  49194 => 
  [
    'id' => 49194,
    'type' => 'weapon',
    'name' => 'Scalpel',
    'add_name' => '',
    'description' => '',
    'icon' => 'etc_ertheia2',
    'weapon_type' => 'blunt',
    'bodypart' => 'rhand',
    'crystal_type' => 'd',
    'weight' => 1810,
    'soulshots' => 1,
    'spiritshots' => 1,
  ],
  49195 => 
  [
    'id' => 49195,
    'type' => 'weapon',
    'name' => 'Scalpel',
    'add_name' => '',
    'description' => '',
    'icon' => 'etc_ertheia2',
    'weapon_type' => 'blunt',
    'bodypart' => 'rhand',
    'crystal_type' => 'd',
    'weight' => 1810,
    'soulshots' => 1,
    'spiritshots' => 1,
  ],
  49196 => 
  [
    'id' => 49196,
    'type' => 'weapon',
    'name' => 'Scalpel',
    'add_name' => '',
    'description' => '',
    'icon' => 'etc_ertheia2',
    'weapon_type' => 'blunt',
    'bodypart' => 'rhand',
    'crystal_type' => 'd',
    'weight' => 1810,
    'soulshots' => 1,
    'spiritshots' => 1,
  ],
  49197 => 
  [
    'id' => 49197,
    'type' => 'weapon',
    'name' => 'Work Hammer',
    'add_name' => '',
    'description' => '',
    'icon' => 'etc_ertheia2',
    'weapon_type' => 'blunt',
    'bodypart' => 'rhand',
    'crystal_type' => 'd',
    'weight' => 1790,
    'soulshots' => 1,
    'spiritshots' => 1,
  ],
  49198 => 
  [
    'id' => 49198,
    'type' => 'weapon',
    'name' => 'Work Hammer',
    'add_name' => '',
    'description' => '',
    'icon' => 'etc_ertheia2',
    'weapon_type' => 'blunt',
    'bodypart' => 'rhand',
    'crystal_type' => 'd',
    'weight' => 1790,
    'soulshots' => 1,
    'spiritshots' => 1,
  ],
  49199 => 
  [
    'id' => 49199,
    'type' => 'weapon',
    'name' => 'Work Hammer',
    'add_name' => '',
    'description' => '',
    'icon' => 'etc_ertheia2',
    'weapon_type' => 'blunt',
    'bodypart' => 'rhand',
    'crystal_type' => 'd',
    'weight' => 1790,
    'soulshots' => 1,
    'spiritshots' => 1,
  ],
];