<?php
return [
  500 => 
  [
    'id' => 500,
    'type' => 'armor',
    'name' => 'Great Helmet',
    'add_name' => '',
    'description' => '',
    'icon' => 'armor_helmet_i00',
    'bodypart' => 'head',
    'crystal_count' => 96,
    'crystal_type' => 'c',
    'weight' => 610,
    'price' => 242000,
    'commissionItemType' => 'HELMET',
    'enchant_enabled' => true,
  ],
  503 => 
  [
    'id' => 503,
    'type' => 'armor',
    'name' => 'Sealed Zubei\'s Helmet',
    'add_name' => '',
    'description' => '',
    'icon' => 'armor_helmet_i02',
    'bodypart' => 'head',
    'crystal_count' => 96,
    'crystal_type' => 'b',
    'weight' => 590,
    'price' => 778000,
    'commissionItemType' => 'HELMET',
    'enchant_enabled' => true,
  ],
  512 => 
  [
    'id' => 512,
    'type' => 'armor',
    'name' => 'Dark Crystal Helmet',
    'add_name' => '',
    'description' => '',
    'icon' => 'armor_helmet_i00',
    'bodypart' => 'head',
    'crystal_count' => 96,
    'crystal_type' => 'a',
    'weight' => 570,
    'price' => 1336000,
    'enchant_enabled' => true,
    'commissionItemType' => 'HELMET',
  ],
  517 => 
  [
    'id' => 517,
    'type' => 'armor',
    'name' => 'Compound Helmet',
    'add_name' => '',
    'description' => '',
    'icon' => 'armor_leather_helmet_i00',
    'bodypart' => 'head',
    'crystal_count' => 147,
    'crystal_type' => 'c',
    'weight' => 610,
    'price' => 368000,
    'commissionItemType' => 'HELMET',
    'enchant_enabled' => true,
  ],
  547 => 
  [
    'id' => 547,
    'type' => 'armor',
    'name' => 'Tallum Helmet',
    'add_name' => '',
    'description' => '',
    'icon' => 'armor_helmet_i00',
    'bodypart' => 'head',
    'crystal_count' => 147,
    'crystal_type' => 'a',
    'weight' => 570,
    'price' => 1336000,
    'enchant_enabled' => true,
    'commissionItemType' => 'HELMET',
  ],
  553 => 
  [
    'id' => 553,
    'type' => 'armor',
    'name' => 'Iron Boots',
    'add_name' => '',
    'description' => '',
    'icon' => 'armor_t10_b_i00',
    'bodypart' => 'feet',
    'crystal_count' => 92,
    'crystal_type' => 'd',
    'weight' => 1280,
    'price' => 50800,
    'commissionItemType' => 'FEET',
    'enchant_enabled' => true,
  ],
  554 => 
  [
    'id' => 554,
    'type' => 'armor',
    'name' => 'Sealed Zubei\'s Boots',
    'add_name' => '',
    'description' => '',
    'icon' => 'armor_t64_b_i02',
    'bodypart' => 'feet',
    'crystal_count' => 69,
    'crystal_type' => 'b',
    'weight' => 1180,
    'price' => 519000,
    'enchant_enabled' => true,
    'commissionItemType' => 'FEET',
  ],
  563 => 
  [
    'id' => 563,
    'type' => 'armor',
    'name' => 'Dark Crystal Boots',
    'add_name' => '',
    'description' => '',
    'icon' => 'etc_ertheia2',
    'bodypart' => 'feet',
    'crystal_count' => 69,
    'crystal_type' => 'a',
    'weight' => 1110,
    'price' => 890000,
    'commissionItemType' => 'FEET',
  ],
  572 => 
  [
    'id' => 572,
    'type' => 'armor',
    'name' => 'Boots of Silence',
    'add_name' => '',
    'description' => '',
    'icon' => 'etc_ertheia2',
    'bodypart' => 'feet',
    'crystal_count' => 69,
    'crystal_type' => 'b',
    'weight' => 1190,
    'price' => 399100,
    'commissionItemType' => 'FEET',
  ],
  582 => 
  [
    'id' => 582,
    'type' => 'armor',
    'name' => 'Paradia Boots',
    'add_name' => '',
    'description' => '',
    'icon' => 'etc_ertheia2',
    'bodypart' => 'feet',
    'crystal_count' => 107,
    'crystal_type' => 'b',
    'weight' => 1140,
    'price' => 804000,
    'commissionItemType' => 'FEET',
  ],
  583 => 
  [
    'id' => 583,
    'type' => 'armor',
    'name' => 'Majestic Boots',
    'add_name' => '',
    'description' => '',
    'icon' => 'etc_ertheia2',
    'bodypart' => 'feet',
    'crystal_count' => 107,
    'crystal_type' => 'a',
    'weight' => 1110,
    'price' => 1355000,
    'commissionItemType' => 'FEET',
  ],
  588 => 
  [
    'id' => 588,
    'type' => 'armor',
    'name' => 'Elemental Boots',
    'add_name' => '',
    'description' => '',
    'icon' => 'etc_ertheia2',
    'bodypart' => 'feet',
    'crystal_count' => 107,
    'crystal_type' => 'b',
    'weight' => 1130,
    'price' => 804000,
    'commissionItemType' => 'FEET',
  ],
  590 => 
  [
    'id' => 590,
    'type' => 'armor',
    'name' => 'Boots of Grace',
    'add_name' => '',
    'description' => '',
    'icon' => 'etc_ertheia2',
    'bodypart' => 'feet',
    'crystal_count' => 107,
    'crystal_type' => 'b',
    'weight' => 1130,
    'price' => 804000,
    'commissionItemType' => 'FEET',
  ],
  595 => 
  [
    'id' => 595,
    'type' => 'armor',
    'name' => 'Boots of Blessing',
    'add_name' => '',
    'description' => '',
    'icon' => 'etc_ertheia2',
    'bodypart' => 'feet',
    'crystal_count' => 69,
    'crystal_type' => 'b',
    'weight' => 1160,
    'price' => 519000,
    'commissionItemType' => 'FEET',
  ],
  598 => 
  [
    'id' => 598,
    'type' => 'armor',
    'name' => 'Tallum Boots',
    'add_name' => '',
    'description' => '',
    'icon' => 'etc_ertheia2',
    'bodypart' => 'feet',
    'crystal_count' => 69,
    'crystal_type' => 'a',
    'weight' => 1130,
    'price' => 890000,
    'commissionItemType' => 'FEET',
  ],
];