<?php
return [
  5800 => 
  [
    'id' => 5800,
    'type' => 'weapon',
    'name' => 'Nephilim Lord',
    'add_name' => '',
    'description' => '',
    'icon' => 'etc_ertheia2',
    'weapon_type' => 'sword',
    'bodypart' => 'rhand',
    'crystal_type' => 'c',
    'weight' => 1380,
    'price' => 1226000,
    'soulshots' => 1,
    'spiritshots' => 1,
    'commissionItemType' => 'ONE_HAND_SWORD',
  ],
  5801 => 
  [
    'id' => 5801,
    'type' => 'weapon',
    'name' => 'Dusk',
    'add_name' => '',
    'description' => '',
    'icon' => 'etc_ertheia2',
    'weapon_type' => 'sword',
    'bodypart' => 'rhand',
    'crystal_type' => 'c',
    'weight' => 1380,
    'price' => 1226000,
    'soulshots' => 1,
    'spiritshots' => 1,
    'commissionItemType' => 'ONE_HAND_SWORD',
  ],
  5802 => 
  [
    'id' => 5802,
    'type' => 'weapon',
    'name' => 'Dawn',
    'add_name' => '',
    'description' => '',
    'icon' => 'etc_ertheia2',
    'weapon_type' => 'bow',
    'bodypart' => 'lrhand',
    'crystal_type' => 'c',
    'weight' => 1380,
    'price' => 1226000,
    'soulshots' => 2,
    'spiritshots' => 1,
    'commissionItemType' => 'ONE_HAND_SWORD',
  ],
  5803 => 
  [
    'id' => 5803,
    'type' => 'etcitem',
    'name' => 'D-grade Lucky Charm',
    'add_name' => '',
    'description' => 'Bestows blessing on its owner such that when the owner dies during a boss/raid war, his/her abilities will not be diminished.  This item can only be used on self, by a character whose level is between 20 and 39.',
    'icon' => 'etc_ertheia2',
    'etcitem_type' => 'scroll',
    'weight' => 10,
    'price' => 330,
    'is_stackable' => true,
    'is_oly_restricted' => true,
    'handler' => 'itemskills',
    'commissionItemType' => 'OTHER_ITEM',
  ],
  5804 => 
  [
    'id' => 5804,
    'type' => 'etcitem',
    'name' => 'C-grade Lucky Charm',
    'add_name' => '',
    'description' => 'Bestows blessing on its owner such that when the owner dies during a boss/raid war, his/her abilities will not be diminished.  This item can only be used on self by a character whose level is between 40 and 51.',
    'icon' => 'etc_ertheia2',
    'etcitem_type' => 'scroll',
    'weight' => 10,
    'price' => 660,
    'is_stackable' => true,
    'is_oly_restricted' => true,
    'handler' => 'itemskills',
    'commissionItemType' => 'OTHER_ITEM',
  ],
  5805 => 
  [
    'id' => 5805,
    'type' => 'etcitem',
    'name' => 'B-grade Lucky Charm',
    'add_name' => '',
    'description' => 'Bestows blessing on its owner such that when the owner dies during a boss/raid war, his/her abilities will not be diminished.  This item can only be used on self by a character whose level is between 52 and 60.',
    'icon' => 'etc_ertheia2',
    'etcitem_type' => 'scroll',
    'weight' => 10,
    'price' => 1300,
    'is_stackable' => true,
    'is_oly_restricted' => true,
    'handler' => 'itemskills',
    'commissionItemType' => 'OTHER_ITEM',
  ],
  5808 => 
  [
    'id' => 5808,
    'type' => 'armor',
    'name' => 'Party Mask',
    'add_name' => '',
    'description' => 'A fashion item used to display a unique appearance.',
    'icon' => 'etc_party_mask_i00',
    'bodypart' => 'hair',
    'weight' => 10,
    'price' => 1300,
    'enchant_enabled' => true,
    'commissionItemType' => 'HAIR_ACCESSORY',
  ],
  5809 => 
  [
    'id' => 5809,
    'type' => 'etcitem',
    'name' => 'Spellbook: Aqua Splash',
    'add_name' => '',
    'description' => 'Spellbook needed to learn Aqua Splash. Used by Spellsingers.',
    'icon' => 'etc_ertheia2',
    'price' => 6750,
    'commissionItemType' => 'SPELLBOOK',
    'is_stackable' => true,
  ],
  5810 => 
  [
    'id' => 5810,
    'type' => 'etcitem',
    'name' => 'Spellbook: Rain of Fire',
    'add_name' => '',
    'description' => 'Spellbook needed to learn Rain of Fire. Used by Sorcerers/sses.',
    'icon' => 'etc_ertheia2',
    'price' => 6750,
    'commissionItemType' => 'SPELLBOOK',
    'is_stackable' => true,
  ],
  5811 => 
  [
    'id' => 5811,
    'type' => 'etcitem',
    'name' => 'Spellbook: Mass Slow',
    'add_name' => '',
    'description' => 'Spellbook needed to learn Mass Slow. Used by Necromancers.',
    'icon' => 'etc_ertheia2',
    'price' => 200000,
    'commissionItemType' => 'SPELLBOOK',
    'is_stackable' => true,
    'is_sellable' => false,
  ],
  5812 => 
  [
    'id' => 5812,
    'type' => 'etcitem',
    'name' => 'Spellbook: Servitor Empowerment',
    'add_name' => '',
    'description' => 'Spellbook needed to learn Servitor Empowerment. Used by Warlocks, Elemental Summoners and Phantom Summoners.',
    'icon' => 'etc_ertheia2',
    'price' => 5400,
    'commissionItemType' => 'SPELLBOOK',
    'is_stackable' => true,
  ],
  5813 => 
  [
    'id' => 5813,
    'type' => 'etcitem',
    'name' => 'Spellbook: Servitor Cure',
    'add_name' => '',
    'description' => 'Spellbook needed to learn Servitor Cure. Used by Warlocks, Elemental Summoners and Phantom Summoners.',
    'icon' => 'etc_ertheia2',
    'price' => 3200,
    'commissionItemType' => 'SPELLBOOK',
    'is_stackable' => true,
  ],
  5814 => 
  [
    'id' => 5814,
    'type' => 'etcitem',
    'name' => 'Spellbook: Servitor Blessing',
    'add_name' => '',
    'description' => 'Spellbook needed to learn Servitor Blessing. Used by Warlocks, Elemental Summoners and Phantom Summoners.',
    'icon' => 'etc_ertheia2',
    'price' => 7700,
    'commissionItemType' => 'SPELLBOOK',
    'is_stackable' => true,
  ],
  5815 => 
  [
    'id' => 5815,
    'type' => 'etcitem',
    'name' => 'Spellbook: Wild Magic',
    'add_name' => '',
    'description' => 'Spellbook needed to learn Wild. Used by Elven Elders and Shillien Elders.',
    'icon' => 'etc_ertheia2',
    'price' => 200000,
    'commissionItemType' => 'SPELLBOOK',
    'is_stackable' => true,
    'is_sellable' => false,
  ],
  5816 => 
  [
    'id' => 5816,
    'type' => 'etcitem',
    'name' => 'Spellbook: Advanced Block',
    'add_name' => '',
    'description' => 'Spellbook needed to learn Advanced Block. Used by Elven Elders.',
    'icon' => 'etc_ertheia2',
    'price' => 50000,
    'commissionItemType' => 'SPELLBOOK',
    'is_stackable' => true,
    'is_sellable' => false,
  ],
  5817 => 
  [
    'id' => 5817,
    'type' => 'weapon',
    'name' => 'Chrono Campana',
    'add_name' => '',
    'description' => 'Chronicle III Souvenir!!!',
    'icon' => 'weapon_chrono_campana_i00',
    'weapon_type' => 'pole',
    'bodypart' => 'lrhand',
    'is_dropable' => false,
    'commissionItemType' => 'SPEAR',
    'soulshots' => 1,
    'spiritshots' => 1,
  ],
  5858 => 
  [
    'id' => 5858,
    'type' => 'etcitem',
    'name' => 'Improved Scroll of Escape: Clan Hall',
    'add_name' => '',
    'description' => 'A magical scroll that transports you to your clan hall.  If you don\'t belong to a clan that possesses a clan hall, this scroll will have no effect.',
    'icon' => 'etc_scroll_of_return_agit_i01',
    'etcitem_type' => 'scroll',
    'weight' => 120,
    'price' => 100000,
    'is_stackable' => true,
    'is_oly_restricted' => true,
    'handler' => 'itemskills',
    'commissionItemType' => 'SCROLL_OTHER',
  ],
  5859 => 
  [
    'id' => 5859,
    'type' => 'etcitem',
    'name' => 'Improved Scroll of Escape: Castle',
    'add_name' => '',
    'description' => 'A magical scroll that transports you to your castle.  If you don\'t belong to a clan that controls a castle, this scroll will have no effect.',
    'icon' => 'etc_scroll_of_return_castle_i01',
    'etcitem_type' => 'scroll',
    'weight' => 120,
    'price' => 80000,
    'is_stackable' => true,
    'is_oly_restricted' => true,
    'handler' => 'itemskills',
    'commissionItemType' => 'SCROLL_OTHER',
  ],
  5860 => 
  [
    'id' => 5860,
    'type' => 'etcitem',
    'name' => 'Lienrik Egg',
    'add_name' => '',
    'description' => 'Lienrik\'s egg. It\'s the item that Pet Manager Rood of Heine asked you to find for him.',
    'icon' => 'etc_dragon_egg_i02',
    'is_tradable' => false,
    'is_dropable' => false,
    'is_sellable' => false,
    'is_depositable' => false,
    'is_stackable' => true,
    'is_questitem' => true,
  ],
  5861 => 
  [
    'id' => 5861,
    'type' => 'etcitem',
    'name' => 'Lienrik Egg',
    'add_name' => '',
    'description' => 'Lienrik\'s shiny red egg. Pet Manager Rood of Heine asked you to find it for him, but...?',
    'icon' => 'etc_dragon_egg_i01',
    'is_tradable' => false,
    'is_dropable' => false,
    'is_sellable' => false,
    'is_depositable' => false,
    'is_stackable' => true,
    'is_questitem' => true,
  ],
  5862 => 
  [
    'id' => 5862,
    'type' => 'etcitem',
    'name' => 'Stone of Contract',
    'add_name' => '',
    'description' => 'In order to obtain the power of darkness, you will first need to secure this  Take it to Trader Galman in Dragon Valley.',
    'icon' => 'etc_bead_silver_i00',
    'is_tradable' => false,
    'is_dropable' => false,
    'is_sellable' => false,
    'is_depositable' => false,
    'is_stackable' => true,
    'is_questitem' => true,
  ],
  5863 => 
  [
    'id' => 5863,
    'type' => 'etcitem',
    'name' => 'Alligator Tooth',
    'add_name' => '',
    'description' => 'A sharp tooth from an alligator. Take it to Warehouse Freightman Kluck of Heine.',
    'icon' => 'etc_fang_red_i00',
    'is_tradable' => false,
    'is_dropable' => false,
    'is_sellable' => false,
    'is_depositable' => false,
    'is_stackable' => true,
    'is_questitem' => true,
  ],
  5864 => 
  [
    'id' => 5864,
    'type' => 'etcitem',
    'name' => 'Mysterious Map Piece',
    'add_name' => '',
    'description' => 'A faded piece of paper. Possibly part of a map.',
    'icon' => 'etc_map_piece_ivory_i00',
    'is_tradable' => false,
    'is_dropable' => false,
    'is_sellable' => false,
    'is_depositable' => false,
    'is_stackable' => true,
    'is_questitem' => true,
  ],
  5865 => 
  [
    'id' => 5865,
    'type' => 'etcitem',
    'name' => 'Zoogenous Spores',
    'add_name' => '',
    'description' => 'A tissue sample collected from a spore zombie from the Sea of Spores. It is used as research material by Magister Gauen of the Ivory Tower.',
    'icon' => 'etc_pouch_gray_i00',
    'is_tradable' => false,
    'is_dropable' => false,
    'is_sellable' => false,
    'is_depositable' => false,
    'is_stackable' => true,
    'is_questitem' => true,
  ],
  5866 => 
  [
    'id' => 5866,
    'type' => 'etcitem',
    'name' => 'Phytogenic Spores',
    'add_name' => '',
    'description' => 'A spore sample collected from a rotting tree from the Sea of Spores. It is used as research material by Magister Gauen of the Ivory Tower.',
    'icon' => 'etc_pouch_yellow_i00',
    'is_tradable' => false,
    'is_dropable' => false,
    'is_sellable' => false,
    'is_depositable' => false,
    'is_stackable' => true,
    'is_questitem' => true,
  ],
  5867 => 
  [
    'id' => 5867,
    'type' => 'etcitem',
    'name' => 'Jade Crystal',
    'add_name' => '',
    'description' => 'A jade crystal collected from the Enchanted Valley. Take it to Warehouse Freightman Silva of Hunters Village.',
    'icon' => 'etc_gem_green_i00',
    'is_tradable' => false,
    'is_dropable' => false,
    'is_sellable' => false,
    'is_depositable' => false,
    'is_stackable' => true,
    'is_questitem' => true,
  ],
  5868 => 
  [
    'id' => 5868,
    'type' => 'etcitem',
    'name' => 'Snake Scale',
    'add_name' => '',
    'description' => 'A snake scale from the bodies of Falibati and Trives. Take it to Grand Master Oltlin of Aden Castle Town.',
    'icon' => 'etc_scale_of_medusa_blue_i00',
    'is_tradable' => false,
    'is_dropable' => false,
    'is_sellable' => false,
    'is_depositable' => false,
    'is_stackable' => true,
    'is_questitem' => true,
  ],
  5869 => 
  [
    'id' => 5869,
    'type' => 'etcitem',
    'name' => 'Remains of Aden Residents',
    'add_name' => '',
    'description' => 'Remains of residents of Aden Castle who were killed during the Aden-Elmore war. Collect 60 of them and take them to High Priest Orven.',
    'icon' => 'etc_ashes_white_i00',
    'is_tradable' => false,
    'is_dropable' => false,
    'is_sellable' => false,
    'is_depositable' => false,
    'is_stackable' => true,
    'is_questitem' => true,
  ],
  5870 => 
  [
    'id' => 5870,
    'type' => 'etcitem',
    'name' => 'Supply Receipt',
    'add_name' => '',
    'description' => 'A document made from collected mysterious document pieces. Take it to Guard Coleman.',
    'icon' => 'etc_piece_of_paper_white_i00',
    'is_tradable' => false,
    'is_dropable' => false,
    'is_sellable' => false,
    'is_depositable' => false,
    'is_stackable' => true,
    'is_questitem' => true,
  ],
  5871 => 
  [
    'id' => 5871,
    'type' => 'etcitem',
    'name' => 'Suspicious Document Piece',
    'add_name' => '',
    'description' => 'A piece of document that seems to contain some suspicious contents. If you collect 5 of them, you may be able to decipher the information the document conveys.',
    'icon' => 'etc_piece_of_report_i00',
    'is_tradable' => false,
    'is_dropable' => false,
    'is_sellable' => false,
    'is_depositable' => false,
    'is_stackable' => true,
    'is_questitem' => true,
  ],
  5872 => 
  [
    'id' => 5872,
    'type' => 'etcitem',
    'name' => 'Consumable',
    'add_name' => '',
    'description' => 'Supply items for Taik Orcs. Take it to Guard Coleman and he will give you a reward.',
    'icon' => 'etc_squares_wood_i00',
    'is_tradable' => false,
    'is_dropable' => false,
    'is_sellable' => false,
    'is_depositable' => false,
    'is_stackable' => true,
    'is_questitem' => true,
  ],
  5873 => 
  [
    'id' => 5873,
    'type' => 'etcitem',
    'name' => 'Treasure Chest',
    'add_name' => '',
    'description' => 'A treasure chest that was obtained by slaying Zaken\'s followers. Take it to Warehouse Keeper Randolf of Giran Castle Town.',
    'icon' => 'etc_jewel_box_i00',
    'is_tradable' => false,
    'is_dropable' => false,
    'is_sellable' => false,
    'is_depositable' => false,
    'is_stackable' => true,
    'is_questitem' => true,
  ],
  5874 => 
  [
    'id' => 5874,
    'type' => 'etcitem',
    'name' => 'Sairon\'s Silver Hair',
    'add_name' => '',
    'description' => 'Sairon\'s hair. Take it to Magister Dieter of Giran Castle Town.',
    'icon' => 'etc_pouch_gray_i00',
    'is_tradable' => false,
    'is_dropable' => false,
    'is_sellable' => false,
    'is_depositable' => false,
    'is_stackable' => true,
    'is_questitem' => true,
  ],
  5875 => 
  [
    'id' => 5875,
    'type' => 'etcitem',
    'name' => 'Lesser Giant\'s Lamp',
    'add_name' => '',
    'description' => 'It is called a Titan lamp. It is not lit.',
    'icon' => 'etc_bead_gold_i00',
    'is_tradable' => false,
    'is_dropable' => false,
    'is_sellable' => false,
    'is_depositable' => false,
    'is_stackable' => true,
    'is_questitem' => true,
  ],
  5876 => 
  [
    'id' => 5876,
    'type' => 'etcitem',
    'name' => 'Lesser Giant\'s Lamp',
    'add_name' => '',
    'description' => 'It is called a Titan lamp. It is burning dimly.',
    'icon' => 'etc_bead_silver_i00',
    'is_tradable' => false,
    'is_dropable' => false,
    'is_sellable' => false,
    'is_depositable' => false,
    'is_stackable' => true,
    'is_questitem' => true,
  ],
  5877 => 
  [
    'id' => 5877,
    'type' => 'etcitem',
    'name' => 'Lesser Giant\'s Lamp',
    'add_name' => '',
    'description' => 'It is called a Titan lamp. It is lit.',
    'icon' => 'etc_bead_silver_i00',
    'is_tradable' => false,
    'is_dropable' => false,
    'is_sellable' => false,
    'is_depositable' => false,
    'is_stackable' => true,
    'is_questitem' => true,
  ],
  5878 => 
  [
    'id' => 5878,
    'type' => 'etcitem',
    'name' => 'Lesser Giant\'s Lamp',
    'add_name' => '',
    'description' => 'It is called a Titan lamp. It is lit.',
    'icon' => 'etc_bead_silver_i00',
    'is_tradable' => false,
    'is_dropable' => false,
    'is_sellable' => false,
    'is_depositable' => false,
    'is_stackable' => true,
    'is_questitem' => true,
  ],
  5879 => 
  [
    'id' => 5879,
    'type' => 'etcitem',
    'name' => 'Lesser Giant\'s Lamp',
    'add_name' => '',
    'description' => 'It is called a Titan lamp. It is shining brightly.',
    'icon' => 'etc_bead_white_i00',
    'is_tradable' => false,
    'is_dropable' => false,
    'is_sellable' => false,
    'is_depositable' => false,
    'is_stackable' => true,
    'is_questitem' => true,
  ],
  5880 => 
  [
    'id' => 5880,
    'type' => 'etcitem',
    'name' => 'Broken Lesser Giant\'s Lamp',
    'add_name' => '',
    'description' => 'A broken Titan lamp. Take it to Lorain. ',
    'icon' => 'etc_broken_crystal_silver_i00',
    'is_tradable' => false,
    'is_dropable' => false,
    'is_sellable' => false,
    'is_depositable' => false,
    'is_stackable' => true,
    'is_questitem' => true,
  ],
  5881 => 
  [
    'id' => 5881,
    'type' => 'etcitem',
    'name' => 'Blade Stakato Fang',
    'add_name' => '',
    'description' => 'A fang that was obtained from killing a blade stakato. Take it to Eva\'s Priestess Restina in Heine.',
    'icon' => 'etc_claw_i00',
    'is_tradable' => false,
    'is_dropable' => false,
    'is_sellable' => false,
    'is_depositable' => false,
    'is_stackable' => true,
    'is_questitem' => true,
  ],
  5882 => 
  [
    'id' => 5882,
    'type' => 'etcitem',
    'name' => 'Fire Crystal',
    'add_name' => '',
    'description' => 'A flare shard obtained from the Forgotten Temple. Take it to Magister Nell of Gludin Village.',
    'icon' => 'etc_echo_crystal_i00',
    'is_tradable' => false,
    'is_dropable' => false,
    'is_sellable' => false,
    'is_depositable' => false,
    'is_stackable' => true,
    'is_questitem' => true,
  ],
  5883 => 
  [
    'id' => 5883,
    'type' => 'etcitem',
    'name' => 'Ice Shard',
    'add_name' => '',
    'description' => 'A water shard obtained from the Forgotten Temple. Take it to Magister Nell of Gludin Village.',
    'icon' => 'etc_echo_crystal_i01',
    'is_tradable' => false,
    'is_dropable' => false,
    'is_sellable' => false,
    'is_depositable' => false,
    'is_stackable' => true,
    'is_questitem' => true,
  ],
  5884 => 
  [
    'id' => 5884,
    'type' => 'etcitem',
    'name' => 'Cave Beast Tooth',
    'add_name' => '',
    'description' => 'An ingredient used by Orc Shamans during a ritual. Take it to Seer Manakia.',
    'icon' => 'etc_fang_red_i00',
    'is_tradable' => false,
    'is_dropable' => false,
    'is_sellable' => false,
    'is_depositable' => false,
    'is_stackable' => true,
    'is_questitem' => true,
  ],
  5885 => 
  [
    'id' => 5885,
    'type' => 'etcitem',
    'name' => 'Death Wave Light',
    'add_name' => '',
    'description' => 'An ingredient used by Orc Shamans during their ritual. Take it to Seer Manakia.',
    'icon' => 'etc_crystal_ball_green_i00',
    'is_tradable' => false,
    'is_dropable' => false,
    'is_sellable' => false,
    'is_depositable' => false,
    'is_stackable' => true,
    'is_questitem' => true,
  ],
  5886 => 
  [
    'id' => 5886,
    'type' => 'etcitem',
    'name' => 'Sealed Mysterious Stone',
    'add_name' => '',
    'description' => 'A pebble that radiates a strange aura. It sends out a dim light.',
    'icon' => 'etc_dragon_egg_i02',
    'is_tradable' => false,
    'is_dropable' => false,
    'is_sellable' => false,
    'is_depositable' => false,
    'is_stackable' => true,
    'is_questitem' => true,
  ],
  5887 => 
  [
    'id' => 5887,
    'type' => 'etcitem',
    'name' => 'Mysterious Stone',
    'add_name' => '',
    'description' => 'A pebble that radiates a strange aura. It is shining brightly.',
    'icon' => 'etc_dragon_egg_i00',
    'is_tradable' => false,
    'is_dropable' => false,
    'is_sellable' => false,
    'is_depositable' => false,
    'is_stackable' => true,
    'is_questitem' => true,
  ],
  5888 => 
  [
    'id' => 5888,
    'type' => 'etcitem',
    'name' => 'Karik Horn',
    'add_name' => '',
    'description' => 'An ingredient used by Orc Shamans during a ritual. Take it to Seer Manakia.',
    'icon' => 'etc_horn_i00',
    'is_tradable' => false,
    'is_dropable' => false,
    'is_sellable' => false,
    'is_depositable' => false,
    'is_stackable' => true,
    'is_questitem' => true,
  ],
  5889 => 
  [
    'id' => 5889,
    'type' => 'etcitem',
    'name' => 'Limal Karinness Blood',
    'add_name' => '',
    'description' => 'An ingredient used by Orc Shamans during a ritual. Take it to Seer Manakia.',
    'icon' => 'etc_reagent_red_i00',
    'is_tradable' => false,
    'is_dropable' => false,
    'is_sellable' => false,
    'is_depositable' => false,
    'is_stackable' => true,
    'is_questitem' => true,
  ],
  5890 => 
  [
    'id' => 5890,
    'type' => 'etcitem',
    'name' => 'Mysterious Book',
    'add_name' => '',
    'description' => 'A book obtained from The Giant\'s Cave. Written in an ancient language, its contents cannot be deciphered.',
    'icon' => 'etc_spellbook_blue_i00',
    'is_tradable' => false,
    'is_dropable' => false,
    'is_sellable' => false,
    'is_depositable' => false,
    'is_stackable' => true,
    'is_questitem' => true,
  ],
  5891 => 
  [
    'id' => 5891,
    'type' => 'etcitem',
    'name' => 'Ancient Language Dictionary: Basic Level',
    'add_name' => '',
    'description' => 'A simple dictionary published by scholars of ancient times. By using this, you can interpret some of the texts of the Titans.',
    'icon' => 'etc_spellbook_gray_i00',
    'is_tradable' => false,
    'is_dropable' => false,
    'is_sellable' => false,
    'is_depositable' => false,
    'is_stackable' => true,
    'is_questitem' => true,
  ],
  5892 => 
  [
    'id' => 5892,
    'type' => 'etcitem',
    'name' => 'Ancient Language Dictionary: Intermediate Level',
    'add_name' => '',
    'description' => 'A dictionary published by scholars of ancient times. By using this, you can interpret the entire texts of the Titans.',
    'icon' => 'etc_spellbook_red_i00',
    'is_tradable' => false,
    'is_dropable' => false,
    'is_sellable' => false,
    'is_depositable' => false,
    'is_stackable' => true,
    'is_questitem' => true,
  ],
  5893 => 
  [
    'id' => 5893,
    'type' => 'etcitem',
    'name' => 'Leaf of Eucalyptus',
    'add_name' => '',
    'description' => 'One of the ingredients used to make wine. Collect 80 of them and take them to Guard Harlan located in the Town of Dion.',
    'icon' => 'etc_herb_red_i00',
    'is_tradable' => false,
    'is_dropable' => false,
    'is_sellable' => false,
    'is_depositable' => false,
    'is_stackable' => true,
    'is_questitem' => true,
  ],
  5894 => 
  [
    'id' => 5894,
    'type' => 'etcitem',
    'name' => 'Stone of Icy Air',
    'add_name' => '',
    'description' => 'A magical stone used by Enku Orc Shamans when they cast ice magic. Collect 100 of these and take them to Guard Harlan located in the Town of Dion.',
    'icon' => 'etc_crystal_ball_blue_i00',
    'is_tradable' => false,
    'is_dropable' => false,
    'is_sellable' => false,
    'is_depositable' => false,
    'is_stackable' => true,
    'is_questitem' => true,
  ],
  5895 => 
  [
    'id' => 5895,
    'type' => 'etcitem',
    'name' => 'Ritron\'s Fruit',
    'add_name' => '',
    'description' => 'A fruit with a tough, hard outer skin and a fragrant smell. Collect 4 of these and take them to Magister Rollant in the Town of Dion.',
    'icon' => 'etc_cobol_i05',
    'is_tradable' => false,
    'is_dropable' => false,
    'is_sellable' => false,
    'is_depositable' => false,
    'is_stackable' => true,
    'is_questitem' => true,
  ],
  5896 => 
  [
    'id' => 5896,
    'type' => 'etcitem',
    'name' => 'Moon Face Flower',
    'add_name' => '',
    'description' => 'A flower that is said to bloom only under moonlight. Collect 20 of these and take them to Magister Rollant in the Town of Dion.',
    'icon' => 'etc_flower_i00',
    'is_tradable' => false,
    'is_dropable' => false,
    'is_sellable' => false,
    'is_depositable' => false,
    'is_stackable' => true,
    'is_questitem' => true,
  ],
  5897 => 
  [
    'id' => 5897,
    'type' => 'etcitem',
    'name' => 'Leech Fluids',
    'add_name' => '',
    'description' => 'The bodily fluids of a Leech that can be obtained from the Cruma Marshlands. Collect 10 of these and take them to Magister Rollant in the Town of Dion.',
    'icon' => 'etc_reagent_red_i00',
    'is_tradable' => false,
    'is_dropable' => false,
    'is_sellable' => false,
    'is_depositable' => false,
    'is_stackable' => true,
    'is_questitem' => true,
  ],
  5898 => 
  [
    'id' => 5898,
    'type' => 'etcitem',
    'name' => 'Royal Membership',
    'add_name' => '',
    'description' => 'It\'s a coin collectors\' dream! Take it to Head Blacksmith Vergara.',
    'icon' => 'etc_royal_membership_i00',
    'is_tradable' => false,
    'is_dropable' => false,
    'is_sellable' => false,
    'is_depositable' => false,
    'is_stackable' => true,
    'is_questitem' => true,
  ],
  5899 => 
  [
    'id' => 5899,
    'type' => 'etcitem',
    'name' => 'Kail\'s Coin',
    'add_name' => '',
    'description' => 'A coin owned by Sorcerer Kail who used to be an aid of Beleth. Take it to Warehouse Keeper Sorint.',
    'icon' => 'etc_magic_coin_blood_i00',
    'is_tradable' => false,
    'is_dropable' => false,
    'is_sellable' => false,
    'is_depositable' => false,
    'is_stackable' => true,
    'is_questitem' => true,
  ],
];