<?php
return [
  72007 => 
  [
    'id' => 72007,
    'type' => 'etcitem',
    'name' => 'Dragon\'s Treasure Chest',
    'add_name' => '',
    'description' => '',
    'icon' => 'bm_dragon_present',
    'is_tradable' => false,
    'is_dropable' => false,
    'is_sellable' => false,
    'is_stackable' => true,
    'handler' => 'itemskills',
  ],
  72015 => 
  [
    'id' => 72015,
    'type' => 'etcitem',
    'name' => 'Special Kit: Adena',
    'add_name' => '',
    'description' => '',
    'icon' => 'etc_treasure_box_i09',
    'is_tradable' => false,
    'is_dropable' => false,
    'is_sellable' => false,
    'is_stackable' => true,
    'handler' => 'extractableitems',
  ],
  72016 => 
  [
    'id' => 72016,
    'type' => 'etcitem',
    'name' => 'Giran Treasure Chest',
    'add_name' => '',
    'description' => '',
    'icon' => 'event_hero_treasure_box_i00',
    'is_tradable' => false,
    'is_dropable' => false,
    'is_sellable' => false,
    'is_stackable' => true,
    'handler' => 'extractableitems',
    'extractableCountMin' => '2',
    'extractableCountMax' => '2',
  ],
  72018 => 
  [
    'id' => 72018,
    'type' => 'etcitem',
    'name' => 'Special Kit: Adena',
    'add_name' => '',
    'description' => '',
    'icon' => 'etc_treasure_box_i09',
    'is_tradable' => false,
    'is_dropable' => false,
    'is_sellable' => false,
    'is_stackable' => true,
    'handler' => 'extractableitems',
  ],
  72021 => 
  [
    'id' => 72021,
    'type' => 'etcitem',
    'name' => 'Package: Shield of Nightmare',
    'add_name' => '',
    'description' => '',
    'icon' => 'shield_shield_of_nightmare_i00',
    'is_tradable' => false,
    'is_dropable' => false,
    'is_sellable' => false,
    'is_stackable' => true,
    'handler' => 'extractableitems',
  ],
  72022 => 
  [
    'id' => 72022,
    'type' => 'etcitem',
    'name' => 'Package: Shield of Nightmare',
    'add_name' => '',
    'description' => '',
    'icon' => 'shield_shield_of_nightmare_i00',
    'is_tradable' => false,
    'is_dropable' => false,
    'is_sellable' => false,
    'is_stackable' => true,
    'handler' => 'extractableitems',
  ],
  72023 => 
  [
    'id' => 72023,
    'type' => 'etcitem',
    'name' => 'Growth Supply Pack - Lv. 60',
    'add_name' => '',
    'description' => '',
    'icon' => 'etc_golden_spice_comp_i00',
    'is_tradable' => false,
    'is_dropable' => false,
    'is_sellable' => false,
    'is_stackable' => true,
  ],
  72024 => 
  [
    'id' => 72024,
    'type' => 'etcitem',
    'name' => 'Growth Supply Pack - Lv. 65',
    'add_name' => '',
    'description' => '',
    'icon' => 'etc_golden_spice_comp_i00',
    'is_tradable' => false,
    'is_dropable' => false,
    'is_sellable' => false,
    'is_stackable' => true,
  ],
  72025 => 
  [
    'id' => 72025,
    'type' => 'etcitem',
    'name' => 'Growth Supply Pack - Lv. 68',
    'add_name' => '',
    'description' => '',
    'icon' => 'etc_golden_spice_comp_i00',
    'is_tradable' => false,
    'is_dropable' => false,
    'is_sellable' => false,
    'is_stackable' => true,
  ],
  72026 => 
  [
    'id' => 72026,
    'type' => 'etcitem',
    'name' => 'Growth Supply Pack - Lv. 71',
    'add_name' => '',
    'description' => '',
    'icon' => 'etc_golden_spice_comp_i00',
    'is_tradable' => false,
    'is_dropable' => false,
    'is_sellable' => false,
    'is_stackable' => true,
  ],
  72027 => 
  [
    'id' => 72027,
    'type' => 'etcitem',
    'name' => 'Growth Supply Pack - Lv. 74',
    'add_name' => '',
    'description' => '',
    'icon' => 'etc_golden_spice_comp_i00',
    'is_tradable' => false,
    'is_dropable' => false,
    'is_sellable' => false,
    'is_stackable' => true,
  ],
  72028 => 
  [
    'id' => 72028,
    'type' => 'etcitem',
    'name' => 'Growth Supply Pack - Lv. 76',
    'add_name' => '',
    'description' => '',
    'icon' => 'etc_golden_spice_comp_i00',
    'is_tradable' => false,
    'is_dropable' => false,
    'is_sellable' => false,
    'is_stackable' => true,
  ],
  72029 => 
  [
    'id' => 72029,
    'type' => 'etcitem',
    'name' => 'Growth Supply Pack - Lv. 79',
    'add_name' => '',
    'description' => '',
    'icon' => 'etc_golden_spice_comp_i00',
    'is_tradable' => false,
    'is_dropable' => false,
    'is_sellable' => false,
    'is_stackable' => true,
  ],
  72040 => 
  [
    'id' => 72040,
    'type' => 'etcitem',
    'name' => 'Festival Gift Box',
    'add_name' => '',
    'description' => '',
    'icon' => 'br_gold_box_i00',
    'is_tradable' => false,
    'is_dropable' => false,
    'is_sellable' => false,
    'is_stackable' => true,
    'handler' => 'extractableitems',
    'extractableCountMin' => '1',
    'extractableCountMax' => '1',
  ],
  72041 => 
  [
    'id' => 72041,
    'type' => 'etcitem',
    'name' => 'Festival Coin',
    'add_name' => '',
    'description' => '',
    'icon' => 'BranchIcon.Icon.g_bm_premium_coin_i00',
    'is_tradable' => false,
    'is_dropable' => false,
    'is_sellable' => false,
    'is_stackable' => true,
  ],
  72042 => 
  [
    'id' => 72042,
    'type' => 'etcitem',
    'name' => 'Special Festival Spellbook Chest',
    'add_name' => '',
    'description' => '',
    'icon' => 'sayha2017_box_i01',
    'is_sellable' => false,
    'is_stackable' => true,
    'handler' => 'extractableitems',
  ],
  72043 => 
  [
    'id' => 72043,
    'type' => 'etcitem',
    'name' => 'Sparkling Accessory Pack',
    'add_name' => '',
    'description' => '',
    'icon' => 'BranchSys3.g_cash_fortuna_box_r',
    'is_tradable' => false,
    'is_dropable' => false,
    'is_sellable' => false,
    'is_stackable' => true,
    'handler' => 'extractableitems',
    'extractableCountMin' => '1',
    'extractableCountMax' => '1',
  ],
  72044 => 
  [
    'id' => 72044,
    'type' => 'etcitem',
    'name' => 'Boss\' Accessory Fragment',
    'add_name' => '',
    'description' => '',
    'icon' => 'icon_material_renewal_mineral',
    'is_tradable' => false,
    'is_dropable' => false,
    'is_sellable' => false,
    'is_stackable' => true,
  ],
  72067 => 
  [
    'id' => 72067,
    'type' => 'etcitem',
    'name' => 'Jewelry Box Lv. 5',
    'add_name' => '',
    'description' => '',
    'icon' => 'etc_bm_jewelbox_main_i00',
    'is_tradable' => false,
    'is_dropable' => false,
    'is_sellable' => false,
    'is_stackable' => true,
    'handler' => 'extractableitems',
    'extractableCountMin' => '1',
    'extractableCountMax' => '1',
  ],
  72073 => 
  [
    'id' => 72073,
    'type' => 'etcitem',
    'name' => 'Pack of Seals',
    'add_name' => '',
    'description' => '',
    'icon' => 'etc_bm_jewelbox_main_i01',
    'is_tradable' => false,
    'is_dropable' => false,
    'is_sellable' => false,
    'is_stackable' => true,
    'handler' => 'extractableitems',
    'extractableCountMin' => '2',
    'extractableCountMax' => '2',
  ],
  72074 => 
  [
    'id' => 72074,
    'type' => 'etcitem',
    'name' => 'Halloween Kit',
    'add_name' => '',
    'description' => '',
    'icon' => 'event_halloween_king_pumpkini00',
    'is_tradable' => false,
    'is_dropable' => false,
    'is_sellable' => false,
    'is_stackable' => true,
    'handler' => 'extractableitems',
  ],
  72075 => 
  [
    'id' => 72075,
    'type' => 'etcitem',
    'name' => 'Special Box of Seals',
    'add_name' => '',
    'description' => '',
    'icon' => 'bm_ensoulbox_PvE',
    'is_tradable' => false,
    'is_dropable' => false,
    'is_sellable' => false,
    'is_stackable' => true,
    'handler' => 'extractableitems',
    'extractableCountMin' => '1',
    'extractableCountMax' => '1',
  ],
  72078 => 
  [
    'id' => 72078,
    'type' => 'etcitem',
    'name' => 'Anniversary Gift Box (Time-limited]',
    'add_name' => '',
    'description' => '',
    'icon' => 'etc_ev_draco_gift_box',
    'is_tradable' => false,
    'is_dropable' => false,
    'is_sellable' => false,
    'is_stackable' => true,
    'handler' => 'extractableitems',
  ],
  72080 => 
  [
    'id' => 72080,
    'type' => 'etcitem',
    'name' => 'Pearly Joy Chest',
    'add_name' => '',
    'description' => '',
    'icon' => 'br_ghost_magicalbox_i00',
    'is_tradable' => false,
    'is_dropable' => false,
    'is_sellable' => false,
    'is_stackable' => true,
    'handler' => 'extractableitems',
  ],
  72084 => 
  [
    'id' => 72084,
    'type' => 'armor',
    'name' => 'Devoted Hero\'s Circlet',
    'add_name' => '',
    'description' => '',
    'icon' => 'accessory_barka_karm_i00',
    'bodypart' => 'hairall',
    'weight' => 10,
    'is_tradable' => false,
    'is_dropable' => false,
    'is_sellable' => false,
    'time' => 1440,
  ],
  72085 => 
  [
    'id' => 72085,
    'type' => 'armor',
    'name' => 'Devoted Hero\'s Helmet',
    'add_name' => '',
    'description' => '',
    'icon' => 'armor_leather_helmet_i00',
    'bodypart' => 'head',
    'weight' => 560,
    'is_tradable' => false,
    'is_dropable' => false,
    'is_sellable' => false,
    'time' => 1440,
  ],
  72086 => 
  [
    'id' => 72086,
    'type' => 'armor',
    'name' => 'Devoted Hero\'s Gauntlets',
    'add_name' => '',
    'description' => '',
    'icon' => 'armor_t96_g_i03',
    'bodypart' => 'gloves',
    'weight' => 540,
    'is_tradable' => false,
    'is_dropable' => false,
    'is_sellable' => false,
    'time' => 1440,
  ],
  72087 => 
  [
    'id' => 72087,
    'type' => 'armor',
    'name' => 'Devoted Hero\'s Gloves',
    'add_name' => '',
    'description' => '',
    'icon' => 'armor_t94_g_i01',
    'bodypart' => 'gloves',
    'weight' => 540,
    'is_tradable' => false,
    'is_dropable' => false,
    'is_sellable' => false,
    'time' => 1440,
  ],
  72088 => 
  [
    'id' => 72088,
    'type' => 'armor',
    'name' => 'Devoted Hero\'s Boots',
    'add_name' => '',
    'description' => '',
    'icon' => 'armor_t100_b_i00',
    'bodypart' => 'feet',
    'weight' => 1070,
    'is_tradable' => false,
    'is_dropable' => false,
    'is_sellable' => false,
    'time' => 1440,
  ],
  72089 => 
  [
    'id' => 72089,
    'type' => 'armor',
    'name' => 'Devoted Hero\'s Pendant',
    'add_name' => '',
    'description' => '',
    'icon' => 'BranchIcon.Icon.bm_pendant_pve_white',
    'bodypart' => 'underwear',
    'is_tradable' => false,
    'is_dropable' => false,
    'is_sellable' => false,
    'time' => 1440,
  ],
  72090 => 
  [
    'id' => 72090,
    'type' => 'armor',
    'name' => 'Devoted Hero\'s Ring - Queen Ant',
    'add_name' => '',
    'description' => '',
    'icon' => 'accessory_ring_of_queen_ant_i03',
    'bodypart' => 'rfinger;lfinger',
    'weight' => 150,
    'is_tradable' => false,
    'is_dropable' => false,
    'is_sellable' => false,
    'time' => 1440,
  ],
  72091 => 
  [
    'id' => 72091,
    'type' => 'armor',
    'name' => 'Devoted Hero\'s Necklace - Frintezza',
    'add_name' => '',
    'description' => '',
    'icon' => 'accessory_necklace_of_frintessa_i04',
    'bodypart' => 'neck',
    'weight' => 150,
    'is_tradable' => false,
    'is_dropable' => false,
    'is_sellable' => false,
    'time' => 1440,
  ],
  72092 => 
  [
    'id' => 72092,
    'type' => 'armor',
    'name' => 'Devoted Hero\'s Earring - Zaken',
    'add_name' => '',
    'description' => '',
    'icon' => 'accessory_earring_of_zaken_i03',
    'bodypart' => 'rear;lear',
    'weight' => 150,
    'is_tradable' => false,
    'is_dropable' => false,
    'is_sellable' => false,
    'time' => 1440,
  ],
  72093 => 
  [
    'id' => 72093,
    'type' => 'armor',
    'name' => 'Devoted Hero\'s Ring - Baium',
    'add_name' => '',
    'description' => '',
    'icon' => 'accessory_ring_of_baium_i03',
    'bodypart' => 'rfinger;lfinger',
    'weight' => 150,
    'is_tradable' => false,
    'is_dropable' => false,
    'is_sellable' => false,
    'time' => 1440,
  ],
  72094 => 
  [
    'id' => 72094,
    'type' => 'armor',
    'name' => 'Devoted Hero\'s Earring - Orfen',
    'add_name' => '',
    'description' => '',
    'icon' => 'accessory_earring_of_orfen_i03',
    'bodypart' => 'rear;lear',
    'weight' => 150,
    'is_tradable' => false,
    'is_dropable' => false,
    'is_sellable' => false,
    'time' => 1440,
  ],
  72095 => 
  [
    'id' => 72095,
    'type' => 'armor',
    'name' => 'Devoted Hero\'s Ring - Core',
    'add_name' => '',
    'description' => '',
    'icon' => 'accessory_ring_of_core_i03',
    'bodypart' => 'rfinger;lfinger',
    'weight' => 150,
    'is_tradable' => false,
    'is_dropable' => false,
    'is_sellable' => false,
    'time' => 1440,
  ],
  72096 => 
  [
    'id' => 72096,
    'type' => 'armor',
    'name' => 'Devoted Hero\'s Belt',
    'add_name' => '',
    'description' => '',
    'icon' => 'dragon_belt_2',
    'armor_type' => 'light',
    'bodypart' => 'waist',
    'is_tradable' => false,
    'is_dropable' => false,
    'is_sellable' => false,
    'time' => 1440,
  ],
  72097 => 
  [
    'id' => 72097,
    'type' => 'armor',
    'name' => 'Devoted Hero\'s Shield',
    'add_name' => '',
    'description' => '',
    'icon' => 'shield_of_revenge',
    'weapon_type' => 'fist',
    'bodypart' => 'lhand',
    'weight' => 1180,
    'is_tradable' => false,
    'is_dropable' => false,
    'is_sellable' => false,
    'time' => 1440,
  ],
  72098 => 
  [
    'id' => 72098,
    'type' => 'armor',
    'name' => 'Devoted Hero\'s Sigil',
    'add_name' => '',
    'description' => '',
    'icon' => 'elos_i00',
    'armor_type' => 'sigil',
    'bodypart' => 'lhand',
    'weight' => 1200,
    'is_tradable' => false,
    'is_dropable' => false,
    'is_sellable' => false,
    'time' => 1440,
  ],
  72099 => 
  [
    'id' => 72099,
    'type' => 'etcitem',
    'name' => 'Devoted Hero\'s Doll - Queen Ant',
    'add_name' => '',
    'description' => '',
    'icon' => 'bm_queen_ant_doll_30d',
    'is_tradable' => false,
    'is_dropable' => false,
    'is_sellable' => false,
    'time' => 1440,
  ],
];