<?php
return [
  8800 => 
  [
    'id' => 8800,
    'type' => 'weapon',
    'name' => 'Naga\'s Storm',
    'add_name' => 'Focus',
    'description' => '<Soul Crystal Option>.  Increases critical attack rate by 67. Increases damage inflicted during PvP.',
    'icon' => 'etc_ertheia2',
    'weapon_type' => 'dagger',
    'bodypart' => 'rhand',
    'crystal_count' => 2157,
    'crystal_type' => 'a',
    'weight' => 930,
    'price' => 26968400,
    'soulshots' => 1,
    'spiritshots' => 1,
    'commissionItemType' => 'DAGGER',
  ],
  8801 => 
  [
    'id' => 8801,
    'type' => 'weapon',
    'name' => 'Naga\'s Storm',
    'add_name' => 'Critical Damage',
    'description' => '<Soul Crystal Option>.  Increases P. Atk. by 200 during a critical attack. Increases damage inflicted during PvP.',
    'icon' => 'etc_ertheia2',
    'weapon_type' => 'dagger',
    'bodypart' => 'rhand',
    'crystal_count' => 2157,
    'crystal_type' => 'a',
    'weight' => 930,
    'price' => 26968400,
    'soulshots' => 1,
    'spiritshots' => 1,
    'commissionItemType' => 'DAGGER',
  ],
  8802 => 
  [
    'id' => 8802,
    'type' => 'weapon',
    'name' => 'Naga\'s Storm',
    'add_name' => 'Back Blow',
    'description' => '<Soul Crystal Option>.  Increases the critical attack rate by 37 when attacking a target from behind. Increases damage inflicted during PvP.',
    'icon' => 'etc_ertheia2',
    'weapon_type' => 'dagger',
    'bodypart' => 'rhand',
    'crystal_count' => 2157,
    'crystal_type' => 'a',
    'weight' => 930,
    'price' => 26968400,
    'soulshots' => 1,
    'spiritshots' => 1,
    'commissionItemType' => 'DAGGER',
  ],
  8803 => 
  [
    'id' => 8803,
    'type' => 'weapon',
    'name' => 'Tiphon\'s Spear',
    'add_name' => 'Critical Stun',
    'description' => '<Soul Crystal Option>.  Increases the chance of stun effect by 25% during a critical attack. Increases damage inflicted during PvP.',
    'icon' => 'etc_ertheia2',
    'weapon_type' => 'pole',
    'bodypart' => 'lrhand',
    'crystal_count' => 2157,
    'crystal_type' => 'a',
    'weight' => 1820,
    'price' => 26968400,
    'soulshots' => 1,
    'spiritshots' => 1,
    'commissionItemType' => 'SPEAR',
  ],
  8804 => 
  [
    'id' => 8804,
    'type' => 'weapon',
    'name' => 'Tiphon\'s Spear',
    'add_name' => 'Towering Blow',
    'description' => '<Soul Crystal Option>.  Increases the possibility of increasing attack range. Increases damage inflicted during PvP.',
    'icon' => 'etc_ertheia2',
    'weapon_type' => 'pole',
    'bodypart' => 'lrhand',
    'crystal_count' => 2157,
    'crystal_type' => 'a',
    'weight' => 1820,
    'price' => 26968400,
    'soulshots' => 1,
    'spiritshots' => 1,
    'commissionItemType' => 'SPEAR',
  ],
  8805 => 
  [
    'id' => 8805,
    'type' => 'weapon',
    'name' => 'Tiphon\'s Spear',
    'add_name' => 'Wild Blow',
    'description' => '<Soul Crystal Option>.  Increases the possibility of broadening the angle of attack. Increases damage inflicted during PvP.',
    'icon' => 'etc_ertheia2',
    'weapon_type' => 'pole',
    'bodypart' => 'lrhand',
    'crystal_count' => 2157,
    'crystal_type' => 'a',
    'weight' => 1820,
    'price' => 26968400,
    'soulshots' => 1,
    'spiritshots' => 1,
    'commissionItemType' => 'SPEAR',
  ],
  8806 => 
  [
    'id' => 8806,
    'type' => 'weapon',
    'name' => 'Shyeed\'s Bow',
    'add_name' => 'Cheap Shot',
    'description' => '<Soul Crystal Option>.  Decreases MP consumption by 1 at a 30% probability during an ordinary attack. Increases damage inflicted during PvP.',
    'icon' => 'etc_ertheia2',
    'weapon_type' => 'bow',
    'bodypart' => 'lrhand',
    'crystal_count' => 2157,
    'crystal_type' => 'a',
    'weight' => 1640,
    'price' => 26968400,
    'change_weaponId' => 9361,
    'soulshots' => 2,
    'spiritshots' => 1,
    'mp_consume' => 5,
    'commissionItemType' => 'BOW',
  ],
  8807 => 
  [
    'id' => 8807,
    'type' => 'weapon',
    'name' => 'Shyeed\'s Bow',
    'add_name' => 'Focus',
    'description' => '<Soul Crystal Option> Increases Critical by 61. Increases damage inflicted during PvP.',
    'icon' => 'etc_ertheia2',
    'weapon_type' => 'bow',
    'bodypart' => 'lrhand',
    'crystal_count' => 2157,
    'crystal_type' => 'a',
    'weight' => 1640,
    'price' => 26968400,
    'change_weaponId' => 9362,
    'soulshots' => 2,
    'spiritshots' => 1,
    'mp_consume' => 5,
    'commissionItemType' => 'BOW',
  ],
  8808 => 
  [
    'id' => 8808,
    'type' => 'weapon',
    'name' => 'Shyeed\'s Bow',
    'add_name' => 'Quick Recovery',
    'description' => '<Soul Crystal Option>.  Decreases re-use delay by about 17%. Increases damage inflicted during PvP.',
    'icon' => 'etc_ertheia2',
    'weapon_type' => 'bow',
    'bodypart' => 'lrhand',
    'crystal_count' => 2157,
    'crystal_type' => 'a',
    'weight' => 1640,
    'price' => 26968400,
    'change_weaponId' => 9363,
    'soulshots' => 2,
    'spiritshots' => 1,
    'mp_consume' => 5,
    'commissionItemType' => 'BOW',
  ],
  8809 => 
  [
    'id' => 8809,
    'type' => 'weapon',
    'name' => 'Sobekk\'s Hurricane',
    'add_name' => 'Rsk. Haste',
    'description' => '<Soul Crystal Option>.  Increases Atk. Spd. by 11% when HP falls below 60%. Increases damage inflicted during PvP.',
    'icon' => 'etc_ertheia2',
    'weapon_type' => 'dualfist',
    'bodypart' => 'lrhand',
    'crystal_count' => 2157,
    'crystal_type' => 'a',
    'weight' => 1330,
    'price' => 26968400,
    'soulshots' => 1,
    'spiritshots' => 1,
    'commissionItemType' => 'FIST_WEAPON',
  ],
  8810 => 
  [
    'id' => 8810,
    'type' => 'weapon',
    'name' => 'Sobekk\'s Hurricane',
    'add_name' => 'Haste',
    'description' => '<Soul Crystal Option>.  Increases Atk. Spd. by about 6%. Increases damage inflicted during PvP.',
    'icon' => 'etc_ertheia2',
    'weapon_type' => 'dualfist',
    'bodypart' => 'lrhand',
    'crystal_count' => 2157,
    'crystal_type' => 'a',
    'weight' => 1330,
    'price' => 26968400,
    'soulshots' => 1,
    'spiritshots' => 1,
    'commissionItemType' => 'FIST_WEAPON',
  ],
  8811 => 
  [
    'id' => 8811,
    'type' => 'weapon',
    'name' => 'Sobekk\'s Hurricane',
    'add_name' => 'Critical Drain',
    'description' => '<Soul Crystal Option>.  Increases the possibility of absorbing 14 HP during a critical attack. Increases damage inflicted during PvP.',
    'icon' => 'etc_ertheia2',
    'weapon_type' => 'dualfist',
    'bodypart' => 'lrhand',
    'crystal_count' => 2157,
    'crystal_type' => 'a',
    'weight' => 1330,
    'price' => 26968400,
    'soulshots' => 1,
    'spiritshots' => 1,
    'commissionItemType' => 'FIST_WEAPON',
  ],
  8812 => 
  [
    'id' => 8812,
    'type' => 'weapon',
    'name' => 'Themis\' Tongue',
    'add_name' => 'Mana Up',
    'description' => '<Soul Crystal Option>.  Increases maximum MP by 30%. Increases damage inflicted during PvP.',
    'icon' => 'etc_ertheia2',
    'weapon_type' => 'sword',
    'bodypart' => 'rhand',
    'crystal_count' => 2157,
    'crystal_type' => 'a',
    'weight' => 820,
    'price' => 26968400,
    'soulshots' => 1,
    'spiritshots' => 1,
    'is_magic_weapon' => true,
    'commissionItemType' => 'ONE_HAND_MAGIC_SWORD',
  ],
  8813 => 
  [
    'id' => 8813,
    'type' => 'weapon',
    'name' => 'Themis\' Tongue',
    'add_name' => 'Magic Mental Shield',
    'description' => '<Soul Crystal Option>.  Increases the chances of causing Mental Shield by 50% when using good magic upon a target. Increases damage inflicted during PvP.',
    'icon' => 'etc_ertheia2',
    'weapon_type' => 'sword',
    'bodypart' => 'rhand',
    'crystal_count' => 2157,
    'crystal_type' => 'a',
    'weight' => 820,
    'price' => 26968400,
    'soulshots' => 1,
    'spiritshots' => 1,
    'is_magic_weapon' => true,
    'commissionItemType' => 'ONE_HAND_MAGIC_SWORD',
  ],
  8814 => 
  [
    'id' => 8814,
    'type' => 'weapon',
    'name' => 'Themis\' Tongue',
    'add_name' => 'Magic Focus',
    'description' => '<Soul Crystal Option>.  Increases the chances of causing Focus by 20% when using good magic upon a target. Increases damage inflicted during PvP.',
    'icon' => 'etc_ertheia2',
    'weapon_type' => 'sword',
    'bodypart' => 'rhand',
    'crystal_count' => 2157,
    'crystal_type' => 'a',
    'weight' => 820,
    'price' => 26968400,
    'soulshots' => 1,
    'spiritshots' => 1,
    'is_magic_weapon' => true,
    'commissionItemType' => 'ONE_HAND_MAGIC_SWORD',
  ],
  8815 => 
  [
    'id' => 8815,
    'type' => 'weapon',
    'name' => 'Cabrio\'s Hand',
    'add_name' => 'Conversion',
    'description' => '<Soul Crystal Option>.  Increases maximum MP by 60% and decreases maximum HP by 40%. Increases damage inflicted during PvP.',
    'icon' => 'etc_ertheia2',
    'weapon_type' => 'blunt',
    'bodypart' => 'rhand',
    'crystal_count' => 2157,
    'crystal_type' => 'a',
    'weight' => 1510,
    'price' => 26968400,
    'soulshots' => 1,
    'spiritshots' => 1,
    'is_magic_weapon' => true,
    'commissionItemType' => 'ONE_HAND_MAGIC_BLUNT_WEAPON',
  ],
  8816 => 
  [
    'id' => 8816,
    'type' => 'weapon',
    'name' => 'Cabrio\'s Hand',
    'add_name' => 'Mana Up',
    'description' => '<Soul Crystal Option>.  Increases maximum MP by 30%. Increases damage inflicted during PvP.',
    'icon' => 'etc_ertheia2',
    'weapon_type' => 'blunt',
    'bodypart' => 'rhand',
    'crystal_count' => 2157,
    'crystal_type' => 'a',
    'weight' => 1510,
    'price' => 26968400,
    'soulshots' => 1,
    'spiritshots' => 1,
    'is_magic_weapon' => true,
    'commissionItemType' => 'ONE_HAND_MAGIC_BLUNT_WEAPON',
  ],
  8817 => 
  [
    'id' => 8817,
    'type' => 'weapon',
    'name' => 'Cabrio\'s Hand',
    'add_name' => 'Magic Silence',
    'description' => '<Soul Crystal Option>.  Increases the chances of causing Sleep by 10% when using bad magic upon a target. Increases damage inflicted during PvP.',
    'icon' => 'etc_ertheia2',
    'weapon_type' => 'blunt',
    'bodypart' => 'rhand',
    'crystal_count' => 2157,
    'crystal_type' => 'a',
    'weight' => 1510,
    'price' => 26968400,
    'soulshots' => 1,
    'spiritshots' => 1,
    'is_magic_weapon' => true,
    'commissionItemType' => 'ONE_HAND_MAGIC_BLUNT_WEAPON',
  ],
  8818 => 
  [
    'id' => 8818,
    'type' => 'weapon',
    'name' => 'Daimon Crystal',
    'add_name' => 'Mana Up',
    'description' => '<Soul Crystal Option>.  Increases maximum MP by 30%. Increases damage inflicted during PvP.',
    'icon' => 'etc_ertheia2',
    'weapon_type' => 'blunt',
    'bodypart' => 'lrhand',
    'crystal_count' => 2157,
    'crystal_type' => 'a',
    'weight' => 880,
    'price' => 26968400,
    'soulshots' => 1,
    'spiritshots' => 1,
    'is_magic_weapon' => true,
    'commissionItemType' => 'TWO_HAND_MAGIC_BLUNT_WEAPON',
  ],
  8819 => 
  [
    'id' => 8819,
    'type' => 'weapon',
    'name' => 'Daimon Crystal',
    'add_name' => 'Acumen',
    'description' => '<Soul Crystal Option>.  Increases casting speed by 15%. Increases damage inflicted during PvP.',
    'icon' => 'etc_ertheia2',
    'weapon_type' => 'blunt',
    'bodypart' => 'lrhand',
    'crystal_count' => 2157,
    'crystal_type' => 'a',
    'weight' => 880,
    'price' => 26968400,
    'soulshots' => 1,
    'spiritshots' => 1,
    'is_magic_weapon' => true,
    'commissionItemType' => 'TWO_HAND_MAGIC_BLUNT_WEAPON',
  ],
  8820 => 
  [
    'id' => 8820,
    'type' => 'weapon',
    'name' => 'Daimon Crystal',
    'add_name' => 'Magic Mental Shield',
    'description' => '<Soul Crystal Option>.  Increases the chances of causing Mental Shield by 50% when using good magic upon a target. Increases damage inflicted during PvP.',
    'icon' => 'etc_ertheia2',
    'weapon_type' => 'blunt',
    'bodypart' => 'lrhand',
    'crystal_count' => 2157,
    'crystal_type' => 'a',
    'weight' => 880,
    'price' => 26968400,
    'soulshots' => 1,
    'spiritshots' => 1,
    'is_magic_weapon' => true,
    'commissionItemType' => 'TWO_HAND_MAGIC_BLUNT_WEAPON',
  ],
  8868 => 
  [
    'id' => 8868,
    'type' => 'etcitem',
    'name' => 'Ziggo\'s Jewel',
    'add_name' => '',
    'description' => 'This bright, shiny gemstone looks as though it would fetch a good price if you sold it at the shop.',
    'icon' => 'etc_jewel_red_i00',
    'price' => 200000000,
    'is_questitem' => true,
    'commissionItemType' => 'OTHER_ITEM',
    'is_stackable' => true,
  ],
  8871 => 
  [
    'id' => 8871,
    'type' => 'etcitem',
    'name' => 'Strategy Guide',
    'add_name' => '',
    'description' => 'This book contains information about the methods and strategies used to lead a guild. Invitations to the guild are possible during use.',
    'icon' => 'etc_paper_black_i00',
    'weight' => 20,
    'commissionItemType' => 'OTHER_ITEM',
    'price' => 10000,
  ],
  8872 => 
  [
    'id' => 8872,
    'type' => 'etcitem',
    'name' => 'Flash Gunpowder',
    'add_name' => '',
    'description' => 'This specially processed gunpowder doesn\'t create smoke. It is consumed while using the swoop cannon skill.',
    'icon' => 'etc_powder_gray_i00',
    'weight' => 20,
    'price' => 1500,
    'commissionItemType' => 'OTHER_ITEM',
    'is_stackable' => true,
  ],
  8890 => 
  [
    'id' => 8890,
    'type' => 'etcitem',
    'name' => 'Spellbook: Summon Attractive Cubic',
    'add_name' => '',
    'description' => 'Spellbook needed to learn Summon Attractive Cubic. Used by a Temple Knight.',
    'icon' => 'etc_ertheia2',
    'price' => 200000,
    'commissionItemType' => 'SPELLBOOK',
    'is_stackable' => true,
    'is_sellable' => false,
  ],
  8891 => 
  [
    'id' => 8891,
    'type' => 'etcitem',
    'name' => 'Spellbook: Aura Flash',
    'add_name' => '',
    'description' => 'Spellbook needed to learn Aura Flash. Used by a Sorcerer, Spellsinger, and Spellhowler.',
    'icon' => 'etc_ertheia2',
    'price' => 100000,
    'commissionItemType' => 'SPELLBOOK',
    'is_stackable' => true,
    'is_sellable' => false,
  ],
];