<?php
return [
  91900 => 
  [
    'id' => 91900,
    'type' => 'weapon',
    'name' => 'Colichemarde',
    'add_name' => '',
    'description' => '',
    'icon' => 'weapon_colichemarde_i00',
    'weapon_type' => 'rapier',
    'bodypart' => 'rhand',
    'soulshots' => 1,
    'spiritshots' => 1,
    'crystal_type' => 'b',
    'weight' => 1300,
    'price' => 13100000,
    'enchant_enabled' => true,
    'commissionItemType' => 'RAPIER',
  ],
  91901 => 
  [
    'id' => 91901,
    'type' => 'weapon',
    'name' => 'Military Fleuret',
    'add_name' => '',
    'description' => '',
    'icon' => 'weapon_assult_fleuret_i00',
    'weapon_type' => 'rapier',
    'bodypart' => 'rhand',
    'soulshots' => 1,
    'spiritshots' => 1,
    'crystal_type' => 'b',
    'weight' => 1300,
    'price' => 8680000,
    'enchant_enabled' => true,
    'commissionItemType' => 'RAPIER',
  ],
  91902 => 
  [
    'id' => 91902,
    'type' => 'weapon',
    'name' => 'Éclair Bijou',
    'add_name' => '',
    'description' => '',
    'icon' => 'weapon_greed_stinger_i00',
    'weapon_type' => 'rapier',
    'bodypart' => 'rhand',
    'soulshots' => 1,
    'spiritshots' => 1,
    'crystal_type' => 'a',
    'crystal_count' => 2157,
    'weight' => 1300,
    'price' => 26968400,
    'enchant_enabled' => true,
    'commissionItemType' => 'RAPIER',
  ],
  91903 => 
  [
    'id' => 91903,
    'type' => 'weapon',
    'name' => 'Lacerator',
    'add_name' => '',
    'description' => '',
    'icon' => 'weapon_greed_stinger_i00',
    'weapon_type' => 'rapier',
    'bodypart' => 'rhand',
    'soulshots' => 1,
    'spiritshots' => 1,
    'crystal_type' => 'a',
    'crystal_count' => 1659,
    'weight' => 1300,
    'price' => 20741000,
    'enchant_enabled' => true,
    'commissionItemType' => 'RAPIER',
  ],
  91904 => 
  [
    'id' => 91904,
    'type' => 'weapon',
    'name' => 'White Lightning',
    'add_name' => '',
    'description' => '',
    'icon' => 'weapon_lightning_blaze_i00',
    'weapon_type' => 'rapier',
    'bodypart' => 'rhand',
    'soulshots' => 1,
    'spiritshots' => 1,
    'crystal_type' => 'a',
    'crystal_count' => 1128,
    'weight' => 1300,
    'price' => 14098000,
    'enchant_enabled' => true,
    'commissionItemType' => 'RAPIER',
  ],
  91905 => 
  [
    'id' => 91905,
    'type' => 'weapon',
    'name' => 'Laevateinn',
    'add_name' => '',
    'description' => '',
    'icon' => 'weapon_leavatein_i00',
    'weapon_type' => 'rapier',
    'bodypart' => 'rhand',
    'soulshots' => 4,
    'spiritshots' => 4,
    'crystal_type' => 's',
    'weight' => 1300,
    'price' => 42759400,
    'enchant_enabled' => true,
  ],
  91906 => 
  [
    'id' => 91906,
    'type' => 'etcitem',
    'name' => 'Energy Rune',
    'add_name' => '',
    'description' => '',
    'icon' => 'bm_freya_rune',
    'is_tradable' => false,
    'is_dropable' => false,
    'is_sellable' => false,
  ],
  91907 => 
  [
    'id' => 91907,
    'type' => 'etcitem',
    'name' => '+10 High-grade Agathion Pack',
    'add_name' => '',
    'description' => '',
    'icon' => 'npoint_earthworm_30day_box',
    'is_dropable' => false,
    'is_sellable' => false,
    'is_stackable' => true,
    'handler' => 'extractableitems',
    'extractableCountMin' => '1',
    'extractableCountMax' => '1',
  ],
  91908 => 
  [
    'id' => 91908,
    'type' => 'etcitem',
    'name' => '+12 S-grade Weapon Pack',
    'add_name' => '',
    'description' => '',
    'icon' => 'npoint_earthworm_30day_box',
    'is_dropable' => false,
    'is_sellable' => false,
    'is_stackable' => true,
    'handler' => 'extractableitems',
    'extractableCountMin' => '1',
    'extractableCountMax' => '1',
  ],
  91909 => 
  [
    'id' => 91909,
    'type' => 'etcitem',
    'name' => 'Wind Treasure Chest',
    'add_name' => '',
    'description' => '',
    'icon' => 'sayha2017_box_i01',
    'is_tradable' => false,
    'is_dropable' => false,
    'is_sellable' => false,
    'is_stackable' => true,
    'handler' => 'itemskills',
  ],
  91910 => 
  [
    'id' => 91910,
    'type' => 'etcitem',
    'name' => 'Sayha\'s Blessing - Lv. 1-75',
    'add_name' => '',
    'description' => '',
    'icon' => 'etc_wind_potion_i00',
    'is_tradable' => false,
    'is_dropable' => false,
    'is_sellable' => false,
    'is_stackable' => true,
    'handler' => 'itemskills',
  ],
  91911 => 
  [
    'id' => 91911,
    'type' => 'etcitem',
    'name' => 'Sayha\'s Buff Scroll',
    'add_name' => '',
    'description' => '',
    'icon' => 'etc_ssq_i00',
    'is_tradable' => false,
    'is_dropable' => false,
    'is_sellable' => false,
    'is_stackable' => true,
    'is_freightable' => true,
  ],
  91912 => 
  [
    'id' => 91912,
    'type' => 'etcitem',
    'name' => 'HP Potion',
    'add_name' => '',
    'description' => '',
    'icon' => 'etc_lesser_potion_red_i00',
    'etcitem_type' => 'potion',
    'commissionItemType' => 'POTION',
    'handler' => 'itemskills',
    'weight' => 1,
    'price' => 30,
    'is_sellable' => false,
    'is_stackable' => true,
  ],
  91913 => 
  [
    'id' => 91913,
    'type' => 'etcitem',
    'name' => 'Aden Spellbook Chest',
    'add_name' => '',
    'description' => '',
    'icon' => 'etc_ertheia2',
    'is_tradable' => false,
    'is_dropable' => false,
    'is_sellable' => false,
    'is_stackable' => true,
  ],
  91914 => 
  [
    'id' => 91914,
    'type' => 'etcitem',
    'name' => 'Aden Amulet Chest',
    'add_name' => '',
    'description' => '',
    'icon' => 'etc_ertheia2',
    'is_tradable' => false,
    'is_dropable' => false,
    'is_sellable' => false,
    'is_stackable' => true,
  ],
  91915 => 
  [
    'id' => 91915,
    'type' => 'weapon',
    'name' => 'Enhanced Ancient Warrior\'s Sword',
    'add_name' => '',
    'description' => '',
    'icon' => 'weapon_tulwar_i00',
    'weapon_type' => 'ancientsword',
    'bodypart' => 'lrhand',
    'weight' => 1530,
    'soulshots' => 1,
    'spiritshots' => 1,
    'is_tradable' => false,
    'is_dropable' => false,
    'is_sellable' => false,
  ],
  91916 => 
  [
    'id' => 91916,
    'type' => 'weapon',
    'name' => 'Enhanced Warrior\'s Rapier',
    'add_name' => '',
    'description' => '',
    'icon' => 'weapon_sealed_rapier_i00',
    'weight' => 1300,
    'is_tradable' => false,
    'is_dropable' => false,
    'is_sellable' => false,
    'bodypart' => 'rhand',
    'weapon_type' => 'rapier',
    'soulshots' => 1,
    'spiritshots' => 1,
  ],
  91917 => 
  [
    'id' => 91917,
    'type' => 'etcitem',
    'name' => 'Scroll of Escape: Effective Training',
    'add_name' => '',
    'description' => '',
    'price' => 35000,
    'handler' => 'itemskills',
    'commissionItemType' => 'SCROLL_OTHER',
    'is_tradable' => false,
    'is_dropable' => false,
    'is_sellable' => false,
    'is_stackable' => true,
    'is_oly_restricted' => true,
  ],
  91918 => 
  [
    'id' => 91918,
    'type' => 'etcitem',
    'name' => 'Scroll of Escape: Captain Bathis',
    'add_name' => '',
    'description' => '',
    'icon' => 'etc_scroll_of_return_i04',
    'price' => 35000,
    'handler' => 'itemskills',
    'commissionItemType' => 'SCROLL_OTHER',
    'is_tradable' => false,
    'is_dropable' => false,
    'is_sellable' => false,
    'is_stackable' => true,
    'is_oly_restricted' => true,
  ],
  91919 => 
  [
    'id' => 91919,
    'type' => 'etcitem',
    'name' => 'Scroll of Escape: Captain Bathis',
    'add_name' => '',
    'description' => '',
    'icon' => 'etc_scroll_of_return_i04',
    'price' => 35000,
    'handler' => 'itemskills',
    'commissionItemType' => 'SCROLL_OTHER',
    'is_tradable' => false,
    'is_dropable' => false,
    'is_sellable' => false,
    'is_stackable' => true,
    'is_oly_restricted' => true,
  ],
  91920 => 
  [
    'id' => 91920,
    'type' => 'etcitem',
    'name' => 'Scroll: Magic Break',
    'add_name' => '',
    'description' => '',
    'icon' => 'etc_magic_book_black_i00',
    'is_sellable' => false,
    'is_stackable' => true,
  ],
  91921 => 
  [
    'id' => 91921,
    'type' => 'etcitem',
    'name' => 'Scroll: Disarm',
    'add_name' => '',
    'description' => '',
    'icon' => 'etc_magic_book_black_i00',
    'is_sellable' => false,
    'is_stackable' => true,
  ],
  91922 => 
  [
    'id' => 91922,
    'type' => 'etcitem',
    'name' => 'Scroll: Lightning Barrier',
    'add_name' => '',
    'description' => '',
    'icon' => 'etc_magic_book_black_i00',
    'is_sellable' => false,
    'is_stackable' => true,
  ],
  91923 => 
  [
    'id' => 91923,
    'type' => 'etcitem',
    'name' => 'Scroll: Lightning',
    'add_name' => '',
    'description' => '',
    'icon' => 'etc_magic_book_black_i00',
    'is_sellable' => false,
    'is_stackable' => true,
  ],
  91924 => 
  [
    'id' => 91924,
    'type' => 'etcitem',
    'name' => 'Scroll: Mental Panic',
    'add_name' => '',
    'description' => '',
    'icon' => 'etc_magic_book_black_i00',
    'is_sellable' => false,
    'is_stackable' => true,
  ],
  91925 => 
  [
    'id' => 91925,
    'type' => 'etcitem',
    'name' => 'Scroll: Soul Stigma',
    'add_name' => '',
    'description' => '',
    'icon' => 'etc_magic_book_black_i00',
    'is_sellable' => false,
    'is_stackable' => true,
  ],
  91926 => 
  [
    'id' => 91926,
    'type' => 'etcitem',
    'name' => '+3 Dragon Belt Pack',
    'add_name' => '',
    'description' => '',
    'icon' => 'etc_readybox_bronze',
    'is_tradable' => false,
    'is_dropable' => false,
    'is_sellable' => false,
    'is_stackable' => true,
    'handler' => 'extractableitems',
  ],
  91927 => 
  [
    'id' => 91927,
    'type' => 'etcitem',
    'name' => 'Soulshot',
    'add_name' => '',
    'description' => '',
    'icon' => 'etc_spirit_bullet_gold_i00',
    'price' => 20,
    'is_tradable' => false,
    'is_dropable' => false,
    'is_sellable' => false,
    'is_stackable' => true,
    'handler' => 'soulshots',
    'crystal_type' => 's',
    'etcitem_type' => 'soulshot',
    'commissionItemType' => 'SOULSHOT',
  ],
  91928 => 
  [
    'id' => 91928,
    'type' => 'etcitem',
    'name' => 'Spiritshot',
    'add_name' => '',
    'description' => '',
    'icon' => 'etc_spell_shot_gold_i00',
    'price' => 30,
    'is_tradable' => false,
    'is_dropable' => false,
    'is_sellable' => false,
    'is_stackable' => true,
    'handler' => 'spiritshot',
    'crystal_type' => 's',
    'commissionItemType' => 'SPIRITSHOT',
    'etcitem_type' => 'soulshot',
  ],
  91929 => 
  [
    'id' => 91929,
    'type' => 'etcitem',
    'name' => 'Blessed Soulshot',
    'add_name' => '',
    'description' => '',
    'icon' => 'etc_bless_spirit_bullet_gold_i00',
    'price' => 50,
    'is_tradable' => false,
    'is_dropable' => false,
    'is_sellable' => false,
    'is_stackable' => true,
    'handler' => 'blessedsoulshots',
    'crystal_type' => 's',
    'etcitem_type' => 'soulshot',
    'commissionItemType' => 'SOULSHOT',
  ],
  91930 => 
  [
    'id' => 91930,
    'type' => 'etcitem',
    'name' => 'Blessed Spiritshot',
    'add_name' => '',
    'description' => '',
    'icon' => 'etc_spell_shot_gold_i01',
    'price' => 42,
    'is_tradable' => false,
    'is_dropable' => false,
    'is_sellable' => false,
    'is_stackable' => true,
    'handler' => 'blessedspiritshot',
    'crystal_type' => 's',
    'etcitem_type' => 'soulshot',
    'commissionItemType' => 'SPIRITSHOT',
  ],
  91931 => 
  [
    'id' => 91931,
    'type' => 'etcitem',
    'name' => 'Adventurer\'s Mark Lv. 5',
    'add_name' => '',
    'description' => '',
    'icon' => 'etc_crest_blue_i00',
    'weight' => 10,
    'price' => 1,
    'commissionItemType' => 'OTHER_ITEM',
    'handler' => 'book',
    'is_tradable' => false,
    'is_dropable' => false,
    'is_sellable' => false,
    'is_freightable' => true,
    'is_oly_restricted' => true,
  ],
  91932 => 
  [
    'id' => 91932,
    'type' => 'armor',
    'name' => 'Adventurer\'s Brooch',
    'add_name' => '',
    'description' => '',
    'icon' => 'etc_bm_brooch_lavianrose_i00',
    'bodypart' => 'brooch',
    'weight' => 10,
    'is_dropable' => false,
    'is_sellable' => false,
    'is_tradable' => false,
  ],
  91933 => 
  [
    'id' => 91933,
    'type' => 'armor',
    'name' => 'Adventurer\'s Agathion Bracelet',
    'add_name' => '',
    'description' => '',
    'icon' => 'agathion_magmeld_teleport',
    'bodypart' => 'lbracelet',
    'weight' => 100,
    'is_dropable' => false,
    'is_sellable' => false,
    'is_tradable' => false,
  ],
  91934 => 
  [
    'id' => 91934,
    'type' => 'armor',
    'name' => 'Adventurer\'s Talisman Bracelet',
    'add_name' => '',
    'description' => '',
    'icon' => 'etc_rbracelet_c_i00',
    'bodypart' => 'rbracelet',
    'weight' => 150,
    'price' => 1080000,
    'is_tradable' => false,
    'is_dropable' => false,
    'is_sellable' => false,
    'commissionItemType' => 'BRACELET',
  ],
  91935 => 
  [
    'id' => 91935,
    'type' => 'armor',
    'name' => 'Adventurer\'s Agathion Griffin',
    'add_name' => '',
    'description' => '',
    'icon' => 'griffin_vehicle',
    'bodypart' => 'agathion',
    'weight' => 5,
    'is_tradable' => false,
    'is_dropable' => false,
    'is_sellable' => false,
    'enchant_enabled' => true,
  ],
  91936 => 
  [
    'id' => 91936,
    'type' => 'armor',
    'name' => 'Adventurer\'s Rough Jewel Lv. 1',
    'add_name' => '',
    'description' => '',
    'icon' => 'etc_crystal_piece_i00',
    'bodypart' => 'brooch_jewel',
    'weight' => 5,
    'is_tradable' => false,
    'is_dropable' => false,
    'is_sellable' => false,
  ],
  91937 => 
  [
    'id' => 91937,
    'type' => 'armor',
    'name' => 'Adventurer\'s Talisman',
    'add_name' => '',
    'description' => '',
    'icon' => 'etc_talisman_i04',
    'bodypart' => 'talisman',
    'weight' => 120,
    'enchant_limit' => '1',
    'is_tradable' => false,
    'is_dropable' => false,
    'is_sellable' => false,
    'enchant_enabled' => true,
  ],
  91938 => 
  [
    'id' => 91938,
    'type' => 'etcitem',
    'name' => 'Primeval Isle\'s Time Stone',
    'add_name' => '',
    'description' => '',
    'icon' => 'timezone_refill_1',
    'weight' => 5,
    'is_sellable' => false,
    'is_stackable' => true,
  ],
  91939 => 
  [
    'id' => 91939,
    'type' => 'etcitem',
    'name' => 'Ancient Pirates\' Tomb\'s Prolongation Stone',
    'add_name' => '',
    'description' => '',
    'icon' => 'timezone_refill_2',
    'weight' => 5,
    'is_sellable' => false,
    'is_stackable' => true,
    'handler' => 'itemskills',
  ],
  91940 => 
  [
    'id' => 91940,
    'type' => 'etcitem',
    'name' => 'Heavenly Rift\'s Time Stone',
    'add_name' => '',
    'description' => '',
    'icon' => 'etc_scroll_of_return_i03',
    'weight' => 5,
    'is_sellable' => false,
    'is_stackable' => true,
  ],
  91941 => 
  [
    'id' => 91941,
    'type' => 'etcitem',
    'name' => 'Blessing Chest',
    'add_name' => '',
    'description' => '',
    'icon' => 'event_six_party_box_i00',
    'is_tradable' => false,
    'is_dropable' => false,
    'is_sellable' => false,
    'is_stackable' => true,
    'handler' => 'extractableitems',
    'extractableCountMin' => '2',
    'extractableCountMax' => '2',
  ],
  91942 => 
  [
    'id' => 91942,
    'type' => 'etcitem',
    'name' => 'Crystal of Light',
    'add_name' => '',
    'description' => '',
    'icon' => 'giant_book_i02',
    'weight' => 120,
    'is_sellable' => false,
    'is_stackable' => true,
  ],
  91943 => 
  [
    'id' => 91943,
    'type' => 'etcitem',
    'name' => 'Crystal of Shadows',
    'add_name' => '',
    'description' => '',
    'icon' => 'giant_book_i00',
    'weight' => 120,
    'is_sellable' => false,
    'is_stackable' => true,
  ],
  91944 => 
  [
    'id' => 91944,
    'type' => 'etcitem',
    'name' => 'Book of Light',
    'add_name' => '',
    'description' => '',
    'icon' => 'giant_book_i02',
    'weight' => 120,
    'is_sellable' => false,
    'is_stackable' => true,
  ],
  91945 => 
  [
    'id' => 91945,
    'type' => 'etcitem',
    'name' => 'Book of Shadows',
    'add_name' => '',
    'description' => '',
    'icon' => 'giant_book_i00',
    'weight' => 120,
    'is_sellable' => false,
    'is_stackable' => true,
  ],
  91946 => 
  [
    'id' => 91946,
    'type' => 'etcitem',
    'name' => 'Spellbook: Mount Griffin (Time-limited]',
    'add_name' => '',
    'description' => '',
    'icon' => 'etc_spellbook_red_i00',
    'is_tradable' => false,
    'is_dropable' => false,
    'is_sellable' => false,
    'is_stackable' => true,
  ],
  91947 => 
  [
    'id' => 91947,
    'type' => 'etcitem',
    'name' => 'Package: +7 Admiral\'s Estoc',
    'add_name' => '',
    'description' => '',
    'icon' => 'weapon_rapier_i00',
    'is_tradable' => false,
    'is_dropable' => false,
    'is_sellable' => false,
    'is_stackable' => true,
    'handler' => 'extractableitems',
  ],
  91948 => 
  [
    'id' => 91948,
    'type' => 'etcitem',
    'name' => 'Package: +7 Saber Tooth',
    'add_name' => '',
    'description' => '',
    'icon' => 'weapon_invincible_blade_i00',
    'is_tradable' => false,
    'is_dropable' => false,
    'is_sellable' => false,
    'is_stackable' => true,
    'handler' => 'extractableitems',
  ],
  91949 => 
  [
    'id' => 91949,
    'type' => 'weapon',
    'name' => 'Novice Warrior\'s Rapier',
    'add_name' => '',
    'description' => '',
    'icon' => 'weapon_sealed_rapier_i00',
    'weapon_type' => 'rapier',
    'bodypart' => 'rhand',
    'weight' => 1300,
    'soulshots' => 1,
    'spiritshots' => 1,
    'is_tradable' => false,
    'is_dropable' => false,
    'is_sellable' => false,
    'is_depositable' => false,
  ],
  91950 => 
  [
    'id' => 91950,
    'type' => 'weapon',
    'name' => 'Novice Warrior\'s Ancient Sword',
    'add_name' => '',
    'description' => '',
    'icon' => 'weapon_tulwar_i00',
    'weapon_type' => 'ancientsword',
    'bodypart' => 'lrhand',
    'weight' => 1530,
    'soulshots' => 1,
    'spiritshots' => 1,
    'is_tradable' => false,
    'is_dropable' => false,
    'is_sellable' => false,
    'is_depositable' => false,
  ],
  91951 => 
  [
    'id' => 91951,
    'type' => 'etcitem',
    'name' => 'Scroll: Enchant Talisman of Baium',
    'add_name' => '',
    'description' => '',
    'icon' => 'baium_talisman_new_scroll',
    'is_tradable' => false,
    'is_dropable' => false,
    'is_sellable' => false,
    'is_stackable' => true,
    'etcitem_type' => 'encht_am',
    'handler' => 'enchantscrolls',
  ],
  91952 => 
  [
    'id' => 91952,
    'type' => 'armor',
    'name' => 'Ring of Insolence',
    'add_name' => '',
    'description' => '',
    'icon' => 'ring_of_oman',
    'bodypart' => 'rfinger;lfinger',
    'weight' => 150,
    'price' => 616000,
    'is_sellable' => false,
    'enchant_enabled' => true,
  ],
  91953 => 
  [
    'id' => 91953,
    'type' => 'armor',
    'name' => 'Dragon Valley\'s Earring',
    'add_name' => '',
    'description' => '',
    'icon' => 'accessary_catseye_earing_i00',
    'bodypart' => 'rear;lear',
    'weight' => 150,
    'price' => 924000,
    'is_sellable' => false,
    'enchant_enabled' => true,
  ],
  91954 => 
  [
    'id' => 91954,
    'type' => 'etcitem',
    'name' => 'Scroll of Escape: Tower of Insolence (1st Floor]',
    'add_name' => '',
    'description' => '',
    'icon' => 'etc_scroll_of_return_i04',
    'weight' => 5,
    'price' => 35000,
    'is_stackable' => true,
    'is_oly_restricted' => true,
    'handler' => 'itemskills',
    'commissionItemType' => 'SCROLL_OTHER',
    'is_tradable' => false,
    'is_dropable' => false,
    'is_sellable' => false,
  ],
  91955 => 
  [
    'id' => 91955,
    'type' => 'etcitem',
    'name' => 'Scroll of Escape: Tower of Insolence (2nd Floor]',
    'add_name' => '',
    'description' => '',
    'icon' => 'etc_scroll_of_return_i04',
    'weight' => 5,
    'price' => 35000,
    'is_stackable' => true,
    'is_oly_restricted' => true,
    'handler' => 'itemskills',
    'commissionItemType' => 'SCROLL_OTHER',
    'is_tradable' => false,
    'is_dropable' => false,
    'is_sellable' => false,
  ],
  91956 => 
  [
    'id' => 91956,
    'type' => 'etcitem',
    'name' => 'Scroll of Escape: Tower of Insolence (3rd Floor]',
    'add_name' => '',
    'description' => '',
    'icon' => 'etc_scroll_of_return_i04',
    'weight' => 5,
    'price' => 35000,
    'is_stackable' => true,
    'is_oly_restricted' => true,
    'handler' => 'itemskills',
    'commissionItemType' => 'SCROLL_OTHER',
    'is_tradable' => false,
    'is_dropable' => false,
    'is_sellable' => false,
  ],
  91957 => 
  [
    'id' => 91957,
    'type' => 'etcitem',
    'name' => 'Scroll of Escape: Tower of Insolence (4th Floor]',
    'add_name' => '',
    'description' => '',
    'icon' => 'etc_scroll_of_return_i04',
    'weight' => 5,
    'price' => 35000,
    'is_stackable' => true,
    'is_oly_restricted' => true,
    'handler' => 'itemskills',
    'commissionItemType' => 'SCROLL_OTHER',
    'is_tradable' => false,
    'is_dropable' => false,
    'is_sellable' => false,
  ],
  91958 => 
  [
    'id' => 91958,
    'type' => 'etcitem',
    'name' => 'Scroll of Escape: Tower of Insolence (5th Floor]',
    'add_name' => '',
    'description' => '',
    'icon' => 'etc_scroll_of_return_i04',
    'weight' => 5,
    'price' => 35000,
    'is_stackable' => true,
    'is_oly_restricted' => true,
    'handler' => 'itemskills',
    'commissionItemType' => 'SCROLL_OTHER',
    'is_tradable' => false,
    'is_dropable' => false,
    'is_sellable' => false,
  ],
  91959 => 
  [
    'id' => 91959,
    'type' => 'etcitem',
    'name' => 'Scroll of Escape: Tower of Insolence (6th Floor]',
    'add_name' => '',
    'description' => '',
    'icon' => 'etc_scroll_of_return_i04',
    'weight' => 5,
    'price' => 35000,
    'is_stackable' => true,
    'is_oly_restricted' => true,
    'handler' => 'itemskills',
    'commissionItemType' => 'SCROLL_OTHER',
    'is_tradable' => false,
    'is_dropable' => false,
    'is_sellable' => false,
  ],
  91960 => 
  [
    'id' => 91960,
    'type' => 'etcitem',
    'name' => 'Scroll of Escape: Tower of Insolence (7th Floor]',
    'add_name' => '',
    'description' => '',
    'icon' => 'etc_scroll_of_return_i04',
    'weight' => 5,
    'price' => 35000,
    'is_stackable' => true,
    'is_oly_restricted' => true,
    'handler' => 'itemskills',
    'commissionItemType' => 'SCROLL_OTHER',
    'is_tradable' => false,
    'is_dropable' => false,
    'is_sellable' => false,
  ],
  91961 => 
  [
    'id' => 91961,
    'type' => 'etcitem',
    'name' => 'Scroll of Escape: Tower of Insolence (8th Floor]',
    'add_name' => '',
    'description' => '',
    'icon' => 'etc_scroll_of_return_i04',
    'weight' => 5,
    'price' => 35000,
    'is_stackable' => true,
    'is_oly_restricted' => true,
    'handler' => 'itemskills',
    'commissionItemType' => 'SCROLL_OTHER',
    'is_tradable' => false,
    'is_dropable' => false,
    'is_sellable' => false,
  ],
  91962 => 
  [
    'id' => 91962,
    'type' => 'etcitem',
    'name' => 'Scroll of Escape: Tower of Insolence (9th Floor]',
    'add_name' => '',
    'description' => '',
    'icon' => 'etc_scroll_of_return_i04',
    'weight' => 5,
    'price' => 35000,
    'is_stackable' => true,
    'is_oly_restricted' => true,
    'handler' => 'itemskills',
    'commissionItemType' => 'SCROLL_OTHER',
    'is_tradable' => false,
    'is_dropable' => false,
    'is_sellable' => false,
  ],
  91963 => 
  [
    'id' => 91963,
    'type' => 'etcitem',
    'name' => 'Scroll of Escape: Tower of Insolence (10th Floor]',
    'add_name' => '',
    'description' => '',
    'icon' => 'etc_scroll_of_return_i04',
    'weight' => 5,
    'price' => 35000,
    'is_stackable' => true,
    'is_oly_restricted' => true,
    'handler' => 'itemskills',
    'commissionItemType' => 'SCROLL_OTHER',
    'is_tradable' => false,
    'is_dropable' => false,
    'is_sellable' => false,
  ],
  91964 => 
  [
    'id' => 91964,
    'type' => 'etcitem',
    'name' => 'Scroll of Escape: Tower of Insolence (11th Floor]',
    'add_name' => '',
    'description' => '',
    'icon' => 'etc_scroll_of_return_i04',
    'weight' => 5,
    'price' => 35000,
    'is_stackable' => true,
    'is_oly_restricted' => true,
    'handler' => 'itemskills',
    'commissionItemType' => 'SCROLL_OTHER',
    'is_tradable' => false,
    'is_dropable' => false,
    'is_sellable' => false,
  ],
  91965 => 
  [
    'id' => 91965,
    'type' => 'etcitem',
    'name' => 'Scroll of Escape: Tower of Insolence (12th Floor]',
    'add_name' => '',
    'description' => '',
    'icon' => 'etc_scroll_of_return_i04',
    'weight' => 5,
    'price' => 35000,
    'is_stackable' => true,
    'is_oly_restricted' => true,
    'handler' => 'itemskills',
    'commissionItemType' => 'SCROLL_OTHER',
    'is_tradable' => false,
    'is_dropable' => false,
    'is_sellable' => false,
  ],
  91966 => 
  [
    'id' => 91966,
    'type' => 'etcitem',
    'name' => 'Scroll: Enchant Ring of Insolence',
    'add_name' => '',
    'description' => '',
    'icon' => 'etc_penalty_recovery_i05',
    'is_sellable' => false,
    'is_stackable' => true,
    'etcitem_type' => 'encht_am',
    'is_oly_restricted' => true,
    'handler' => 'enchantscrolls',
  ],
  91967 => 
  [
    'id' => 91967,
    'type' => 'etcitem',
    'name' => 'Scroll: Enchant Dragon Valley\'s Earring',
    'add_name' => '',
    'description' => '',
    'icon' => 'etc_penalty_recovery_i00',
    'is_sellable' => false,
    'is_stackable' => true,
    'etcitem_type' => 'encht_am',
    'is_oly_restricted' => true,
    'handler' => 'enchantscrolls',
  ],
  91968 => 
  [
    'id' => 91968,
    'type' => 'etcitem',
    'name' => 'Enhanced Warrior\'s Rapier Chest',
    'add_name' => '',
    'description' => '',
    'icon' => 'weapon_sealed_rapier_i00',
    'is_tradable' => false,
    'is_dropable' => false,
    'is_sellable' => false,
    'is_stackable' => true,
    'handler' => 'extractableitems',
  ],
  91969 => 
  [
    'id' => 91969,
    'type' => 'etcitem',
    'name' => 'Enhanced Ancient Warrior\'s Sword Chest',
    'add_name' => '',
    'description' => '',
    'icon' => 'weapon_tulwar_i00',
    'is_tradable' => false,
    'is_dropable' => false,
    'is_sellable' => false,
    'is_stackable' => true,
    'handler' => 'extractableitems',
  ],
  91970 => 
  [
    'id' => 91970,
    'type' => 'etcitem',
    'name' => 'Package: +7 Ecliptic Axe',
    'add_name' => '',
    'description' => '',
    'icon' => 'weapon_eclipse_axe_i00',
    'is_dropable' => false,
    'is_sellable' => false,
    'is_stackable' => true,
    'handler' => 'extractableitems',
  ],
  91971 => 
  [
    'id' => 91971,
    'type' => 'etcitem',
    'name' => 'Star Candy',
    'add_name' => '',
    'description' => '',
    'icon' => 'BranchSys.br_valentine_agathion_pack_i00',
    'is_tradable' => false,
    'is_dropable' => false,
    'is_sellable' => false,
    'is_stackable' => true,
    'handler' => 'itemskills',
  ],
  91972 => 
  [
    'id' => 91972,
    'type' => 'etcitem',
    'name' => 'Heavenly Rift Ticket',
    'add_name' => '',
    'description' => '',
    'icon' => 'etc_ticket_red_i00',
    'weight' => 5,
    'is_sellable' => false,
    'is_stackable' => true,
  ],
  91973 => 
  [
    'id' => 91973,
    'type' => 'etcitem',
    'name' => 'Special Dragon\'s Miracle Potion Lv. 1',
    'add_name' => '',
    'description' => '',
    'icon' => 'bm_dragon_posion',
    'is_tradable' => false,
    'is_dropable' => false,
    'is_sellable' => false,
    'is_stackable' => true,
    'handler' => 'itemskills',
  ],
  91974 => 
  [
    'id' => 91974,
    'type' => 'etcitem',
    'name' => 'HP Recovery Potion (Time-limited]',
    'add_name' => '',
    'description' => '',
    'icon' => 'etc_lesser_potion_red_i00',
    'etcitem_type' => 'potion',
    'commissionItemType' => 'POTION',
    'weight' => 1,
    'price' => 30,
    'is_sellable' => false,
    'is_stackable' => true,
    'is_tradable' => false,
    'is_dropable' => false,
    'handler' => 'itemskills',
  ],
  91975 => 
  [
    'id' => 91975,
    'type' => 'etcitem',
    'name' => 'Combat Scroll (Time-limited]',
    'add_name' => '',
    'description' => '',
    'icon' => 'etc_ssq_i00',
    'is_tradable' => false,
    'is_dropable' => false,
    'is_sellable' => false,
    'is_stackable' => true,
    'handler' => 'itemskills',
  ],
  91976 => 
  [
    'id' => 91976,
    'type' => 'etcitem',
    'name' => 'Unidentified Rock',
    'add_name' => '',
    'description' => '',
    'icon' => 'destiny_stone',
    'is_tradable' => false,
    'is_dropable' => false,
    'is_destroyable' => false,
    'is_sellable' => false,
    'is_stackable' => true,
    'handler' => 'extractableitems',
  ],
  91977 => 
  [
    'id' => 91977,
    'type' => 'etcitem',
    'name' => 'Tower of Insolence Scroll: Paralysis Resistance',
    'add_name' => '',
    'description' => '',
    'icon' => 'scroll_of_verification_i08',
    'is_dropable' => false,
    'is_sellable' => false,
    'is_stackable' => true,
  ],
  91978 => 
  [
    'id' => 91978,
    'type' => 'etcitem',
    'name' => 'Dragon Valley Scroll: Mental Resistance',
    'add_name' => '',
    'description' => '',
    'icon' => 'scroll_of_verification_i08',
    'is_dropable' => false,
    'is_sellable' => false,
    'is_stackable' => true,
  ],
  91979 => 
  [
    'id' => 91979,
    'type' => 'etcitem',
    'name' => 'Giant\'s Shining Pack',
    'add_name' => '',
    'description' => '',
    'icon' => 'bm_sheep_agathion_30d_box',
    'is_dropable' => false,
    'is_sellable' => false,
    'is_stackable' => true,
    'handler' => 'extractableitems',
    'extractableCountMin' => '2',
    'extractableCountMax' => '2',
  ],
  91980 => 
  [
    'id' => 91980,
    'type' => 'etcitem',
    'name' => 'Giants\' Coin Pouch',
    'add_name' => '',
    'description' => '',
    'icon' => 'pouch_i01',
    'is_dropable' => false,
    'is_sellable' => false,
    'is_stackable' => true,
    'handler' => 'extractableitems',
    'extractableCountMin' => '1',
    'extractableCountMax' => '1',
  ],
  91981 => 
  [
    'id' => 91981,
    'type' => 'etcitem',
    'name' => 'Giants\' Coin',
    'add_name' => '',
    'description' => '',
    'icon' => 'etc_magic_coin_gold_i01',
    'is_dropable' => false,
    'is_sellable' => false,
    'is_stackable' => true,
  ],
  91982 => 
  [
    'id' => 91982,
    'type' => 'etcitem',
    'name' => '+10 Special White Sayha\'s Cloak Chest',
    'add_name' => '',
    'description' => '',
    'icon' => 'bm_nebit_box',
    'is_dropable' => false,
    'is_sellable' => false,
    'is_stackable' => true,
    'handler' => 'extractableitems',
  ],
  91983 => 
  [
    'id' => 91983,
    'type' => 'etcitem',
    'name' => 'Primeval Isle\'s Time Stone',
    'add_name' => '',
    'description' => '',
    'icon' => 'timezone_refill_1',
    'weight' => 5,
    'is_tradable' => false,
    'is_dropable' => false,
    'is_sellable' => false,
    'is_stackable' => true,
    'handler' => 'itemskills',
  ],
  91984 => 
  [
    'id' => 91984,
    'type' => 'etcitem',
    'name' => 'Ancient Pirates\' Tomb\'s Time Stone',
    'add_name' => '',
    'description' => '',
    'icon' => 'timezone_refill_2',
    'weight' => 5,
    'is_tradable' => false,
    'is_dropable' => false,
    'is_sellable' => false,
    'is_stackable' => true,
    'handler' => 'itemskills',
  ],
  91985 => 
  [
    'id' => 91985,
    'type' => 'etcitem',
    'name' => 'Heavenly Rift\'s Time Stone',
    'add_name' => '',
    'description' => '',
    'icon' => 'etc_scroll_of_return_i03',
    'weight' => 5,
    'is_tradable' => false,
    'is_dropable' => false,
    'is_sellable' => false,
    'is_stackable' => true,
  ],
  91986 => 
  [
    'id' => 91986,
    'type' => 'weapon',
    'name' => 'Monster Only (Grail Apostle Spear]',
    'add_name' => '',
    'description' => '',
    'icon' => 'weapon_monster_i00',
    'weapon_type' => 'pole',
    'bodypart' => 'lrhand',
    'weight' => 2140,
    'price' => 136000,
    'soulshots' => 1,
    'spiritshots' => 1,
  ],
  91987 => 
  [
    'id' => 91987,
    'type' => 'etcitem',
    'name' => '+8 Blue Wolf Heavy Armor Set',
    'add_name' => '',
    'description' => '',
    'icon' => 'armor_t68_u_i00',
    'is_tradable' => false,
    'is_dropable' => false,
    'is_sellable' => false,
    'is_stackable' => true,
    'handler' => 'extractableitems',
  ],
  91988 => 
  [
    'id' => 91988,
    'type' => 'etcitem',
    'name' => '+8 Blue Wolf Light Armor Set',
    'add_name' => '',
    'description' => '',
    'icon' => 'armor_t69_ul_i00',
    'is_tradable' => false,
    'is_dropable' => false,
    'is_sellable' => false,
    'is_stackable' => true,
    'handler' => 'extractableitems',
  ],
  91989 => 
  [
    'id' => 91989,
    'type' => 'etcitem',
    'name' => '+8 Blue Wolf Robe Set',
    'add_name' => '',
    'description' => '',
    'icon' => 'armor_t70_u_i00',
    'is_tradable' => false,
    'is_dropable' => false,
    'is_sellable' => false,
    'is_stackable' => true,
    'handler' => 'extractableitems',
  ],
  91990 => 
  [
    'id' => 91990,
    'type' => 'etcitem',
    'name' => '+8 Doom Heavy Armor Set',
    'add_name' => '',
    'description' => '',
    'icon' => 'armor_t71_ul_i00',
    'is_tradable' => false,
    'is_dropable' => false,
    'is_sellable' => false,
    'is_stackable' => true,
    'handler' => 'extractableitems',
  ],
  91991 => 
  [
    'id' => 91991,
    'type' => 'etcitem',
    'name' => '+8 Doom Light Armor Set',
    'add_name' => '',
    'description' => '',
    'icon' => 'armor_t72_ul_i00',
    'is_tradable' => false,
    'is_dropable' => false,
    'is_sellable' => false,
    'is_stackable' => true,
    'handler' => 'extractableitems',
  ],
  91992 => 
  [
    'id' => 91992,
    'type' => 'etcitem',
    'name' => '+8 Doom Robe Set',
    'add_name' => '',
    'description' => '',
    'icon' => 'armor_t73_u_i00',
    'is_tradable' => false,
    'is_dropable' => false,
    'is_sellable' => false,
    'is_stackable' => true,
    'handler' => 'extractableitems',
  ],
  91993 => 
  [
    'id' => 91993,
    'type' => 'etcitem',
    'name' => '+8 Avadon Robe Set',
    'add_name' => '',
    'description' => '',
    'icon' => 'armor_t59_ul_i00',
    'is_tradable' => false,
    'is_dropable' => false,
    'is_sellable' => false,
    'is_stackable' => true,
    'handler' => 'extractableitems',
  ],
  91994 => 
  [
    'id' => 91994,
    'type' => 'etcitem',
    'name' => '+8 Plated Leather Armor Set',
    'add_name' => '',
    'description' => '',
    'icon' => 'armor_t47_u_i00',
    'is_tradable' => false,
    'is_dropable' => false,
    'is_sellable' => false,
    'is_stackable' => true,
    'handler' => 'extractableitems',
  ],
  91995 => 
  [
    'id' => 91995,
    'type' => 'etcitem',
    'name' => 'A-grade Luxury Box',
    'add_name' => '',
    'description' => '',
    'icon' => 'bm_sayha_gold_present',
    'is_tradable' => false,
    'is_dropable' => false,
    'is_sellable' => false,
    'is_stackable' => true,
    'handler' => 'itemskills',
  ],
  91996 => 
  [
    'id' => 91996,
    'type' => 'etcitem',
    'name' => 'Scroll of Escape Pack: Tower of Insolence (Floors 1-7]',
    'add_name' => '',
    'description' => '',
    'icon' => 'etc_exchange_box_i00',
    'is_tradable' => false,
    'is_dropable' => false,
    'is_sellable' => false,
    'is_stackable' => true,
    'handler' => 'extractableitems',
    'extractableCountMin' => '1',
    'extractableCountMax' => '1',
  ],
  91997 => 
  [
    'id' => 91997,
    'type' => 'etcitem',
    'name' => 'Package: Primeval Isle\'s Time Stone (L-Coins]',
    'add_name' => '',
    'description' => '',
    'icon' => 'timezone_refill_1',
    'is_tradable' => false,
    'is_dropable' => false,
    'is_sellable' => false,
    'is_stackable' => true,
    'handler' => 'extractableitems',
  ],
  91998 => 
  [
    'id' => 91998,
    'type' => 'etcitem',
    'name' => 'Package: Primeval Isle\'s Time Stone (Adena]',
    'add_name' => '',
    'description' => '',
    'icon' => 'timezone_refill_1',
    'is_tradable' => false,
    'is_dropable' => false,
    'is_sellable' => false,
    'is_stackable' => true,
    'handler' => 'extractableitems',
  ],
  91999 => 
  [
    'id' => 91999,
    'type' => 'etcitem',
    'name' => 'Water Spirit Jewel Shard',
    'add_name' => '',
    'description' => '',
    'icon' => 'elemental_water_stone_i00',
    'is_tradable' => false,
    'is_dropable' => false,
    'is_sellable' => false,
    'is_stackable' => true,
    'handler' => 'addspiritexp',
  ],
];