<?php
return [
  94000 => 
  [
    'id' => 94000,
    'type' => 'armor',
    'name' => 'A-grade Armor of Death',
    'add_name' => '',
    'description' => '',
    'icon' => 'etc_ertheia2',
    'bodypart' => 'alldress',
    'crystal_type' => 'a',
    'is_sellable' => false,
  ],
  94001 => 
  [
    'id' => 94001,
    'type' => 'armor',
    'name' => 'B-grade Armor of Death',
    'add_name' => '',
    'description' => '',
    'icon' => 'etc_ertheia2',
    'bodypart' => 'alldress',
    'crystal_type' => 'b',
    'is_sellable' => false,
  ],
  94002 => 
  [
    'id' => 94002,
    'type' => 'armor',
    'name' => 'C-grade Armor of Death',
    'add_name' => '',
    'description' => '',
    'icon' => 'etc_ertheia2',
    'bodypart' => 'alldress',
    'crystal_type' => 'c',
    'is_sellable' => false,
  ],
  94003 => 
  [
    'id' => 94003,
    'type' => 'armor',
    'name' => 'Death Knight\'s Cloak',
    'add_name' => '',
    'description' => '',
    'icon' => 'etc_ertheia2',
    'bodypart' => 'back',
    'weight' => 220,
    'is_tradable' => false,
    'is_dropable' => false,
    'is_sellable' => false,
  ],
  94004 => 
  [
    'id' => 94004,
    'type' => 'armor',
    'name' => 'Worthy Death Knight\'s Cloak',
    'add_name' => '',
    'description' => '',
    'icon' => 'etc_ertheia2',
    'bodypart' => 'back',
    'weight' => 220,
    'is_tradable' => false,
    'is_dropable' => false,
    'is_sellable' => false,
  ],
  94005 => 
  [
    'id' => 94005,
    'type' => 'weapon',
    'name' => 'Character Creation Window - Rapier',
    'add_name' => '',
    'description' => '',
    'icon' => 'etc_ertheia2',
    'weapon_type' => 'rapier',
    'weight' => 1300,
    'bodypart' => 'rhand',
    'soulshots' => 1,
    'spiritshots' => 1,
  ],
  94006 => 
  [
    'id' => 94006,
    'type' => 'weapon',
    'name' => 'Character Creation Window - Ancient Sword',
    'add_name' => '',
    'description' => '',
    'icon' => 'etc_ertheia2',
    'weapon_type' => 'ancientsword',
    'bodypart' => 'lrhand',
    'weight' => 1530,
    'soulshots' => 1,
    'spiritshots' => 1,
  ],
  94007 => 
  [
    'id' => 94007,
    'type' => 'armor',
    'name' => 'Character Creation Window - Helmet',
    'add_name' => '',
    'description' => '',
    'icon' => 'etc_ertheia2',
    'bodypart' => 'head',
    'weight' => 570,
    'is_tradable' => false,
    'is_dropable' => false,
    'is_sellable' => false,
  ],
  94008 => 
  [
    'id' => 94008,
    'type' => 'armor',
    'name' => 'Character Creation Window - Breastplate',
    'add_name' => '',
    'description' => '',
    'icon' => 'etc_ertheia2',
    'armor_type' => 'heavy',
    'bodypart' => 'chest',
    'weight' => 7700,
    'is_tradable' => false,
    'is_dropable' => false,
    'is_sellable' => false,
  ],
  94009 => 
  [
    'id' => 94009,
    'type' => 'armor',
    'name' => 'Character Creation Window - Gaiters',
    'add_name' => '',
    'description' => '',
    'icon' => 'etc_ertheia2',
    'armor_type' => 'heavy',
    'bodypart' => 'legs',
    'weight' => 3320,
    'is_tradable' => false,
    'is_dropable' => false,
    'is_sellable' => false,
  ],
  94010 => 
  [
    'id' => 94010,
    'type' => 'armor',
    'name' => 'Character Creation Window - Gauntlets',
    'add_name' => '',
    'description' => '',
    'icon' => 'etc_ertheia2',
    'bodypart' => 'gloves',
    'weight' => 580,
    'is_tradable' => false,
    'is_dropable' => false,
    'is_sellable' => false,
  ],
  94011 => 
  [
    'id' => 94011,
    'type' => 'armor',
    'name' => 'Character Creation Window - Boots',
    'add_name' => '',
    'description' => '',
    'icon' => 'etc_ertheia2',
    'bodypart' => 'feet',
    'weight' => 1110,
    'is_tradable' => false,
    'is_dropable' => false,
    'is_sellable' => false,
  ],
  94012 => 
  [
    'id' => 94012,
    'type' => 'armor',
    'name' => 'Character Creation Window - Shield',
    'add_name' => '',
    'description' => '',
    'icon' => 'etc_ertheia2',
    'weapon_type' => 'fist',
    'weight' => 1190,
    'bodypart' => 'lhand',
  ],
  94013 => 
  [
    'id' => 94013,
    'type' => 'armor',
    'name' => 'Character Creation Window - Leather Helmet',
    'add_name' => '',
    'description' => '',
    'icon' => 'etc_ertheia2',
    'bodypart' => 'head',
    'weight' => 570,
    'is_tradable' => false,
    'is_dropable' => false,
    'is_sellable' => false,
  ],
  94014 => 
  [
    'id' => 94014,
    'type' => 'armor',
    'name' => 'Character Creation Window - Leather Armor',
    'add_name' => '',
    'description' => '',
    'icon' => 'etc_ertheia2',
    'armor_type' => 'light',
    'bodypart' => 'chest',
    'weight' => 4300,
    'is_tradable' => false,
    'is_dropable' => false,
    'is_sellable' => false,
  ],
  94015 => 
  [
    'id' => 94015,
    'type' => 'armor',
    'name' => 'Character Creation Window - Leather Leggings',
    'add_name' => '',
    'description' => '',
    'icon' => 'etc_ertheia2',
    'armor_type' => 'light',
    'bodypart' => 'legs',
    'weight' => 1480,
    'is_tradable' => false,
    'is_dropable' => false,
    'is_sellable' => false,
  ],
  94016 => 
  [
    'id' => 94016,
    'type' => 'armor',
    'name' => 'Character Creation Window - Leather Gloves',
    'add_name' => '',
    'description' => '',
    'icon' => 'etc_ertheia2',
    'bodypart' => 'gloves',
    'weight' => 580,
    'is_tradable' => false,
    'is_dropable' => false,
    'is_sellable' => false,
  ],
  94017 => 
  [
    'id' => 94017,
    'type' => 'armor',
    'name' => 'Character Creation Window - Leather Boots',
    'add_name' => '',
    'description' => '',
    'icon' => 'etc_ertheia2',
    'bodypart' => 'feet',
    'weight' => 1110,
    'is_tradable' => false,
    'is_dropable' => false,
    'is_sellable' => false,
  ],
  94018 => 
  [
    'id' => 94018,
    'type' => 'armor',
    'name' => 'Character Creation Window - Circlet',
    'add_name' => '',
    'description' => '',
    'icon' => 'etc_ertheia2',
    'bodypart' => 'head',
    'weight' => 570,
    'is_tradable' => false,
    'is_dropable' => false,
    'is_sellable' => false,
  ],
  94019 => 
  [
    'id' => 94019,
    'type' => 'armor',
    'name' => 'Character Creation Window - Tunic',
    'add_name' => '',
    'description' => '',
    'icon' => 'etc_ertheia2',
    'armor_type' => 'magic',
    'bodypart' => 'chest',
    'weight' => 1860,
    'is_tradable' => false,
    'is_dropable' => false,
    'is_sellable' => false,
  ],
  94020 => 
  [
    'id' => 94020,
    'type' => 'armor',
    'name' => 'Character Creation Window - Stockings',
    'add_name' => '',
    'description' => '',
    'icon' => 'etc_ertheia2',
    'armor_type' => 'magic',
    'bodypart' => 'legs',
    'weight' => 920,
    'is_tradable' => false,
    'is_dropable' => false,
    'is_sellable' => false,
  ],
  94021 => 
  [
    'id' => 94021,
    'type' => 'armor',
    'name' => 'Character Creation Window - Gloves',
    'add_name' => '',
    'description' => '',
    'icon' => 'etc_ertheia2',
    'bodypart' => 'gloves',
    'weight' => 580,
    'is_tradable' => false,
    'is_dropable' => false,
    'is_sellable' => false,
  ],
  94022 => 
  [
    'id' => 94022,
    'type' => 'armor',
    'name' => 'Character Creation Window - Shoes',
    'add_name' => '',
    'description' => '',
    'icon' => 'etc_ertheia2',
    'bodypart' => 'feet',
    'weight' => 1130,
    'is_tradable' => false,
    'is_dropable' => false,
    'is_sellable' => false,
  ],
  94023 => 
  [
    'id' => 94023,
    'type' => 'armor',
    'name' => 'Character Creation Window - Sigil',
    'add_name' => '',
    'description' => '',
    'icon' => 'etc_ertheia2',
    'armor_type' => 'sigil',
    'bodypart' => 'lhand',
    'weight' => 1180,
  ],
  94024 => 
  [
    'id' => 94024,
    'type' => 'etcitem',
    'name' => 'Piglet-Bank Lv.2',
    'add_name' => '',
    'description' => '',
    'icon' => 'etc_piggy_bank',
    'is_tradable' => false,
    'is_dropable' => false,
    'is_sellable' => false,
    'is_stackable' => true,
    'handler' => 'extractableitems',
    'extractableCountMin' => '1',
    'extractableCountMax' => '1',
  ],
  94025 => 
  [
    'id' => 94025,
    'type' => 'etcitem',
    'name' => 'Piglet-Bank Lv.3',
    'add_name' => '',
    'description' => '',
    'icon' => 'etc_piggy_bank',
    'is_tradable' => false,
    'is_dropable' => false,
    'is_sellable' => false,
    'is_stackable' => true,
    'handler' => 'extractableitems',
    'extractableCountMin' => '1',
    'extractableCountMax' => '1',
  ],
  94026 => 
  [
    'id' => 94026,
    'type' => 'weapon',
    'name' => 'Emerald Weapon: One-handed Sword',
    'add_name' => '',
    'description' => '',
    'icon' => 'BranchSys3.Icon.g_beam_sword',
    'weapon_type' => 'sword',
    'crystal_type' => 'b',
    'weight' => 144,
    'soulshots' => 1,
    'spiritshots' => 1,
    'is_depositable' => false,
    'is_sellable' => false,
    'bodypart' => 'rhand',
  ],
  94027 => 
  [
    'id' => 94027,
    'type' => 'weapon',
    'name' => 'Emerald Weapon: Dagger',
    'add_name' => '',
    'description' => '',
    'icon' => 'BranchSys3.Icon.g_beam_sword',
    'weapon_type' => 'dagger',
    'crystal_type' => 'b',
    'weight' => 106,
    'soulshots' => 1,
    'spiritshots' => 1,
    'is_depositable' => false,
    'is_sellable' => false,
    'bodypart' => 'rhand',
  ],
  94028 => 
  [
    'id' => 94028,
    'type' => 'weapon',
    'name' => 'Emerald Weapon: Two-handed Sword',
    'add_name' => '',
    'description' => '',
    'icon' => 'BranchSys3.Icon.g_beam_twohand_sword',
    'weapon_type' => 'sword',
    'bodypart' => 'lrhand',
    'crystal_type' => 'b',
    'weight' => 209,
    'soulshots' => 1,
    'spiritshots' => 1,
    'is_depositable' => false,
    'is_sellable' => false,
  ],
  94029 => 
  [
    'id' => 94029,
    'type' => 'weapon',
    'name' => 'Emerald Weapon: Fist Weapon',
    'add_name' => '',
    'description' => '',
    'icon' => 'BranchSys3.Icon.g_beam_dualfist',
    'weapon_type' => 'dualfist',
    'bodypart' => 'lrhand',
    'crystal_type' => 'b',
    'weight' => 152,
    'soulshots' => 1,
    'spiritshots' => 1,
    'is_depositable' => false,
    'is_sellable' => false,
  ],
  94030 => 
  [
    'id' => 94030,
    'type' => 'weapon',
    'name' => 'Emerald Weapon: Spear',
    'add_name' => '',
    'description' => '',
    'icon' => 'BranchSys3.Icon.g_beam_pole',
    'weapon_type' => 'pole',
    'bodypart' => 'lrhand',
    'crystal_type' => 'b',
    'weight' => 205,
    'soulshots' => 1,
    'spiritshots' => 1,
    'is_depositable' => false,
    'is_sellable' => false,
  ],
  94031 => 
  [
    'id' => 94031,
    'type' => 'weapon',
    'name' => 'Emerald Weapon: Bow',
    'add_name' => '',
    'description' => '',
    'icon' => 'BranchSys3.Icon.g_beam_bow',
    'weapon_type' => 'bow',
    'bodypart' => 'lrhand',
    'crystal_type' => 'b',
    'weight' => 181,
    'soulshots' => 2,
    'spiritshots' => 1,
    'mp_consume' => 2,
    'is_depositable' => false,
    'is_sellable' => false,
  ],
  94032 => 
  [
    'id' => 94032,
    'type' => 'weapon',
    'name' => 'Emerald Weapon Appearance',
    'add_name' => '',
    'description' => '',
    'icon' => 'BranchSys3.Icon.g_beam_shield',
    'weapon_type' => 'crossbow',
    'bodypart' => 'lrhand',
    'crystal_type' => 'b',
    'weight' => 181,
    'soulshots' => 1,
    'spiritshots' => 1,
    'is_depositable' => false,
    'is_sellable' => false,
  ],
  94033 => 
  [
    'id' => 94033,
    'type' => 'weapon',
    'name' => 'Emerald Weapon: One-handed Blunt Weapon',
    'add_name' => '',
    'description' => '',
    'icon' => 'BranchSys3.Icon.g_beam_blunt',
    'weapon_type' => 'blunt',
    'weight' => 172,
    'soulshots' => 1,
    'spiritshots' => 1,
    'is_depositable' => false,
    'is_sellable' => false,
    'crystal_type' => 'b',
    'bodypart' => 'rhand',
  ],
  94034 => 
  [
    'id' => 94034,
    'type' => 'weapon',
    'name' => 'Emerald Weapon: Two-handed Blunt Weapon',
    'add_name' => '',
    'description' => '',
    'icon' => 'BranchSys3.Icon.g_beam_twohand_blunt',
    'weapon_type' => 'blunt',
    'bodypart' => 'lrhand',
    'weight' => 101,
    'soulshots' => 1,
    'spiritshots' => 1,
    'is_depositable' => false,
    'is_sellable' => false,
    'crystal_type' => 'b',
  ],
  94035 => 
  [
    'id' => 94035,
    'type' => 'weapon',
    'name' => 'Emerald Weapon - One-handed Staff',
    'add_name' => '',
    'description' => '',
    'icon' => 'BranchSys3.Icon.g_beam_magic_twohand_blunt',
    'weapon_type' => 'blunt',
    'weight' => 172,
    'soulshots' => 1,
    'spiritshots' => 1,
    'is_depositable' => false,
    'is_sellable' => false,
    'crystal_type' => 'b',
    'bodypart' => 'rhand',
  ],
  94036 => 
  [
    'id' => 94036,
    'type' => 'weapon',
    'name' => 'Emerald Weapon - Two-handed Staff',
    'add_name' => '',
    'description' => '',
    'icon' => 'BranchSys3.Icon.g_beam_magic_twohand_blunt',
    'weapon_type' => 'blunt',
    'bodypart' => 'lrhand',
    'weight' => 101,
    'soulshots' => 1,
    'spiritshots' => 1,
    'is_depositable' => false,
    'is_sellable' => false,
    'crystal_type' => 'b',
  ],
  94037 => 
  [
    'id' => 94037,
    'type' => 'weapon',
    'name' => 'Emerald Weapon - Dual Swords',
    'add_name' => '',
    'description' => '',
    'icon' => 'BranchSys3.Icon.g_beam_dual',
    'weapon_type' => 'dual',
    'bodypart' => 'lrhand',
    'crystal_type' => 'b',
    'weight' => 247,
    'soulshots' => 1,
    'spiritshots' => 1,
    'is_depositable' => false,
    'is_sellable' => false,
  ],
  94038 => 
  [
    'id' => 94038,
    'type' => 'weapon',
    'name' => 'Emerald Weapon - Dual Daggers',
    'add_name' => '',
    'description' => '',
    'icon' => 'BranchSys3.Icon.g_beam_dualdagger',
    'weapon_type' => 'dualdagger',
    'bodypart' => 'lrhand',
    'crystal_type' => 'b',
    'weight' => 205,
    'soulshots' => 1,
    'spiritshots' => 1,
    'is_depositable' => false,
    'is_sellable' => false,
  ],
  94039 => 
  [
    'id' => 94039,
    'type' => 'weapon',
    'name' => 'Emerald Weapon: Dual Blunt Weapon',
    'add_name' => '',
    'description' => '',
    'icon' => 'BranchSys3.Icon.g_beam_dualblunt',
    'weapon_type' => 'dualblunt',
    'bodypart' => 'lrhand',
    'weight' => 250,
    'soulshots' => 1,
    'spiritshots' => 1,
    'is_depositable' => false,
    'is_sellable' => false,
    'crystal_type' => 'b',
  ],
  94040 => 
  [
    'id' => 94040,
    'type' => 'armor',
    'name' => 'Dark Assassin Suit',
    'add_name' => '',
    'description' => '',
    'icon' => 'dark_assassin',
    'armor_type' => 'heavy',
    'bodypart' => 'alldress',
    'crystal_type' => 'b',
    'enchant_enabled' => true,
    'is_sellable' => false,
  ],
  94041 => 
  [
    'id' => 94041,
    'type' => 'etcitem',
    'name' => 'Scroll: Restore Equipment',
    'add_name' => '',
    'description' => '',
    'icon' => 'change_restore_i01',
    'etcitem_type' => 'restore_shape_shifting_allitem',
    'is_stackable' => true,
    'is_oly_restricted' => true,
    'handler' => 'appearance',
    'weight' => 120,
    'price' => 100000,
  ],
  94042 => 
  [
    'id' => 94042,
    'type' => 'etcitem',
    'name' => 'Emerald Weapon Appearance Stone',
    'add_name' => '',
    'description' => '',
    'icon' => 'shape_shifting_dagger_i00',
    'handler' => 'appearance',
    'is_tradable' => false,
    'is_dropable' => false,
    'is_sellable' => false,
    'is_oly_restricted' => true,
    'is_freightable' => true,
    'etcitem_type' => 'shape_shifting_wp_fixed',
    'is_stackable' => true,
    'weight' => 120,
  ],
  94043 => 
  [
    'id' => 94043,
    'type' => 'etcitem',
    'name' => 'Test Emerald Weapon Appearance Stone: One-handed Sword',
    'add_name' => '',
    'description' => '',
    'icon' => 'etc_ertheia2',
    'weight' => 120,
    'is_tradable' => false,
    'is_dropable' => false,
    'is_sellable' => false,
    'is_stackable' => true,
  ],
  94044 => 
  [
    'id' => 94044,
    'type' => 'etcitem',
    'name' => 'Appearance Stone: Dark Assassin Suit',
    'add_name' => '',
    'description' => '',
    'icon' => 'br_cashtex.item.br_cash_scrl_of_ench_wp_d_i00',
    'weight' => 120,
    'is_tradable' => false,
    'is_dropable' => false,
    'is_sellable' => false,
    'is_stackable' => true,
  ],
  94045 => 
  [
    'id' => 94045,
    'type' => 'armor',
    'name' => 'Worthy Death Knight\'s Cloak - new',
    'add_name' => '',
    'description' => '',
    'icon' => 'etc_ertheia2',
    'bodypart' => 'back',
    'weight' => 220,
    'is_tradable' => false,
    'is_dropable' => false,
    'is_sellable' => false,
  ],
  94046 => 
  [
    'id' => 94046,
    'type' => 'etcitem',
    'name' => 'Spellbook: Glorious Warrior\'s Ability Lv. 1',
    'add_name' => '',
    'description' => '',
    'icon' => 'etc_spell_books_black_i00',
    'is_tradable' => false,
    'is_dropable' => false,
    'is_destroyable' => false,
    'is_sellable' => false,
    'is_stackable' => true,
    'handler' => 'itemskills',
  ],
  94047 => 
  [
    'id' => 94047,
    'type' => 'etcitem',
    'name' => 'Spellbook: Glorious Warrior\'s Ability',
    'add_name' => '',
    'description' => '',
    'icon' => 'etc_spell_books_black_i00',
    'is_tradable' => false,
    'is_dropable' => false,
    'is_destroyable' => false,
    'is_sellable' => false,
    'is_stackable' => true,
    'handler' => 'itemskills',
  ],
  94048 => 
  [
    'id' => 94048,
    'type' => 'etcitem',
    'name' => '+16 Weapon Craft Kit (Time-limited]',
    'add_name' => '',
    'description' => '',
    'icon' => 'etc_equip_item_box_i02',
    'is_tradable' => false,
    'is_dropable' => false,
    'is_sellable' => false,
    'is_stackable' => true,
    'handler' => 'extractableitems',
  ],
  94051 => 
  [
    'id' => 94051,
    'type' => 'etcitem',
    'name' => '+16 Weapon Craft Coupon (Time-limited]',
    'add_name' => '',
    'description' => '',
    'icon' => 'bm_weapon_ticket_b',
    'is_tradable' => false,
    'is_dropable' => false,
    'is_sellable' => false,
    'is_stackable' => true,
  ],
  94052 => 
  [
    'id' => 94052,
    'type' => 'etcitem',
    'name' => 'Anniversary Coin (Time-limited]',
    'add_name' => '',
    'description' => '',
    'icon' => 'ev_16th_coin',
    'is_tradable' => false,
    'is_dropable' => false,
    'is_sellable' => false,
    'is_stackable' => true,
  ],
  94053 => 
  [
    'id' => 94053,
    'type' => 'etcitem',
    'name' => '+16 Weapon Craft Coupon Box (Time-limited]',
    'add_name' => '',
    'description' => '',
    'icon' => 'etc_bm_lure_box_i00',
    'is_tradable' => false,
    'is_dropable' => false,
    'is_sellable' => false,
    'is_stackable' => true,
    'handler' => 'extractableitems',
  ],
  94054 => 
  [
    'id' => 94054,
    'type' => 'etcitem',
    'name' => 'Master\'s Pack (Time-limited]',
    'add_name' => '',
    'description' => '',
    'icon' => 'bm_silver_lure_box',
    'is_tradable' => false,
    'is_dropable' => false,
    'is_sellable' => false,
    'is_stackable' => true,
    'handler' => 'extractableitems',
    'extractableCountMin' => '1',
    'extractableCountMax' => '1',
  ],
  94055 => 
  [
    'id' => 94055,
    'type' => 'etcitem',
    'name' => '+16 Weapon Pack - Dismantler (Time-limited]',
    'add_name' => '',
    'description' => '',
    'icon' => 'weapon_dismantler_i00',
    'is_tradable' => false,
    'is_dropable' => false,
    'is_sellable' => false,
    'is_stackable' => true,
  ],
  94056 => 
  [
    'id' => 94056,
    'type' => 'etcitem',
    'name' => '+16 Weapon Pack - Art of Battle Axe (Time-limited]',
    'add_name' => '',
    'description' => '',
    'icon' => 'weapon_art_of_battle_axe_i00',
    'is_tradable' => false,
    'is_dropable' => false,
    'is_sellable' => false,
    'is_stackable' => true,
  ],
  94057 => 
  [
    'id' => 94057,
    'type' => 'etcitem',
    'name' => '+16 Weapon Pack - Kaim Vanul\'s Bones (Time-limited]',
    'add_name' => '',
    'description' => '',
    'icon' => 'weapon_bone_of_kaim_vanul_i00',
    'is_tradable' => false,
    'is_dropable' => false,
    'is_sellable' => false,
    'is_stackable' => true,
  ],
  94058 => 
  [
    'id' => 94058,
    'type' => 'etcitem',
    'name' => '+16 Weapon Pack - Bow of Peril (Time-limited]',
    'add_name' => '',
    'description' => '',
    'icon' => 'weapon_hazard_bow_i00',
    'is_tradable' => false,
    'is_dropable' => false,
    'is_sellable' => false,
    'is_stackable' => true,
  ],
  94059 => 
  [
    'id' => 94059,
    'type' => 'etcitem',
    'name' => '+16 Weapon Pack - Wizard\'s Tear (Time-limited]',
    'add_name' => '',
    'description' => '',
    'icon' => 'weapon_tears_of_wizard_i00',
    'is_tradable' => false,
    'is_dropable' => false,
    'is_sellable' => false,
    'is_stackable' => true,
  ],
  94060 => 
  [
    'id' => 94060,
    'type' => 'etcitem',
    'name' => '+16 Weapon Pack - Demon\'s Dagger (Time-limited]',
    'add_name' => '',
    'description' => '',
    'icon' => 'weapon_demons_sword_i00',
    'is_tradable' => false,
    'is_dropable' => false,
    'is_sellable' => false,
    'is_stackable' => true,
  ],
  94061 => 
  [
    'id' => 94061,
    'type' => 'etcitem',
    'name' => '+16 Weapon Pack - Samurai Long Sword*Samurai Long Sword (Time-limited]',
    'add_name' => '',
    'description' => '',
    'icon' => 'weapon_dual_sword_i00',
    'is_tradable' => false,
    'is_dropable' => false,
    'is_sellable' => false,
    'is_stackable' => true,
  ],
  94062 => 
  [
    'id' => 94062,
    'type' => 'etcitem',
    'name' => '+16 Weapon Pack - Bellion Cestus (Time-limited]',
    'add_name' => '',
    'description' => '',
    'icon' => 'weapon_bellion_cestus_i00',
    'is_tradable' => false,
    'is_dropable' => false,
    'is_sellable' => false,
    'is_stackable' => true,
  ],
  94063 => 
  [
    'id' => 94063,
    'type' => 'etcitem',
    'name' => '+16 Weapon Pack - Lance (Time-limited]',
    'add_name' => '',
    'description' => '',
    'icon' => 'weapon_lancia_i00',
    'is_tradable' => false,
    'is_dropable' => false,
    'is_sellable' => false,
    'is_stackable' => true,
  ],
  94064 => 
  [
    'id' => 94064,
    'type' => 'etcitem',
    'name' => '+16 Weapon Pack - Colichemarde (Time-limited]',
    'add_name' => '',
    'description' => '',
    'icon' => 'weapon_colichemarde_i00',
    'is_tradable' => false,
    'is_dropable' => false,
    'is_sellable' => false,
    'is_stackable' => true,
  ],
  94065 => 
  [
    'id' => 94065,
    'type' => 'etcitem',
    'name' => '+16 Weapon Pack - Damascus Sword (Time-limited]',
    'add_name' => '',
    'description' => '',
    'icon' => 'weapon_sword_of_damascus_i00',
    'is_tradable' => false,
    'is_dropable' => false,
    'is_sellable' => false,
    'is_stackable' => true,
  ],
  94066 => 
  [
    'id' => 94066,
    'type' => 'etcitem',
    'name' => '+16 Weapon Pack - Star Buster (Time-limited]',
    'add_name' => '',
    'description' => '',
    'icon' => 'weapon_star_buster_i00',
    'is_tradable' => false,
    'is_dropable' => false,
    'is_sellable' => false,
    'is_stackable' => true,
  ],
  94067 => 
  [
    'id' => 94067,
    'type' => 'etcitem',
    'name' => '+16 Weapon Pack - Staff of Evil Spirits (Time-limited]',
    'add_name' => '',
    'description' => '',
    'icon' => 'weapon_staff_of_evil_sprit_i00',
    'is_tradable' => false,
    'is_dropable' => false,
    'is_sellable' => false,
    'is_stackable' => true,
  ],
  94068 => 
  [
    'id' => 94068,
    'type' => 'etcitem',
    'name' => '+16 Weapon Pack - Guardian\'s Sword (Time-limited]',
    'add_name' => '',
    'description' => '',
    'icon' => 'weapon_guardians_sword_i00',
    'is_tradable' => false,
    'is_dropable' => false,
    'is_sellable' => false,
    'is_stackable' => true,
  ],
  94069 => 
  [
    'id' => 94069,
    'type' => 'etcitem',
    'name' => '+16 Weapon Pack - Saber Tooth (Time-limited]',
    'add_name' => '',
    'description' => '',
    'icon' => 'weapon_invincible_blade_i00',
    'is_tradable' => false,
    'is_dropable' => false,
    'is_sellable' => false,
    'is_stackable' => true,
  ],
  94070 => 
  [
    'id' => 94070,
    'type' => 'etcitem',
    'name' => '+16 Weapon Pack - Yaksa Mace (Time-limited]',
    'add_name' => '',
    'description' => '',
    'icon' => 'weapon_yaksa_mace_i00',
    'is_tradable' => false,
    'is_dropable' => false,
    'is_sellable' => false,
    'is_stackable' => true,
  ],
  94071 => 
  [
    'id' => 94071,
    'type' => 'etcitem',
    'name' => '+16 Weapon Pack - Eminence Bow (Time-limited]',
    'add_name' => '',
    'description' => '',
    'icon' => 'weapon_eminence_bow_i00',
    'is_tradable' => false,
    'is_dropable' => false,
    'is_sellable' => false,
    'is_stackable' => true,
  ],
  94072 => 
  [
    'id' => 94072,
    'type' => 'etcitem',
    'name' => '+16 Weapon Pack - Ecliptic Sword (Time-limited]',
    'add_name' => '',
    'description' => '',
    'icon' => 'weapon_sword_of_eclipse_i00',
    'is_tradable' => false,
    'is_dropable' => false,
    'is_sellable' => false,
    'is_stackable' => true,
  ],
  94073 => 
  [
    'id' => 94073,
    'type' => 'etcitem',
    'name' => '+16 Weapon Pack - Crystal Dagger (Time-limited]',
    'add_name' => '',
    'description' => '',
    'icon' => 'weapon_crystal_dagger_i00',
    'is_tradable' => false,
    'is_dropable' => false,
    'is_sellable' => false,
    'is_stackable' => true,
  ],
  94074 => 
  [
    'id' => 94074,
    'type' => 'etcitem',
    'name' => '+16 Weapon Pack - Katana*Katana (Time-limited]',
    'add_name' => '',
    'description' => '',
    'icon' => 'weapon_dual_sword_i00',
    'is_tradable' => false,
    'is_dropable' => false,
    'is_sellable' => false,
    'is_stackable' => true,
  ],
  94075 => 
  [
    'id' => 94075,
    'type' => 'etcitem',
    'name' => '+16 Weapon Pack - Great Pata (Time-limited]',
    'add_name' => '',
    'description' => '',
    'icon' => 'weapon_great_pata_i00',
    'is_tradable' => false,
    'is_dropable' => false,
    'is_sellable' => false,
    'is_stackable' => true,
  ],
  94076 => 
  [
    'id' => 94076,
    'type' => 'etcitem',
    'name' => '+16 Weapon Pack - Orcish Poleaxe (Time-limited]',
    'add_name' => '',
    'description' => '',
    'icon' => 'weapon_orcish_poleaxe_i00',
    'is_tradable' => false,
    'is_dropable' => false,
    'is_sellable' => false,
    'is_stackable' => true,
  ],
  94077 => 
  [
    'id' => 94077,
    'type' => 'etcitem',
    'name' => '+16 Weapon Pack - Admiral\'s Estoc (Time-limited]',
    'add_name' => '',
    'description' => '',
    'icon' => 'weapon_blink_slasher_i00',
    'is_tradable' => false,
    'is_dropable' => false,
    'is_sellable' => false,
    'is_stackable' => true,
  ],
  94078 => 
  [
    'id' => 94078,
    'type' => 'etcitem',
    'name' => '+16 Weapon Pack - Ecliptic Axe (Time-limited]',
    'add_name' => '',
    'description' => '',
    'icon' => 'weapon_eclipse_axe_i00',
    'is_tradable' => false,
    'is_dropable' => false,
    'is_sellable' => false,
    'is_stackable' => true,
  ],
  94079 => 
  [
    'id' => 94079,
    'type' => 'etcitem',
    'name' => '+16 Weapon Pack - Samurai Long Sword (Time-limited]',
    'add_name' => '',
    'description' => '',
    'icon' => 'weapon_samurai_old_longsword_i00',
    'is_tradable' => false,
    'is_dropable' => false,
    'is_sellable' => false,
    'is_stackable' => true,
  ],
  94080 => 
  [
    'id' => 94080,
    'type' => 'etcitem',
    'name' => '+16 Weapon Pack - Dwarven Hammer (Time-limited]',
    'add_name' => '',
    'description' => '',
    'icon' => 'weapon_dwarven_hammer_i00',
    'is_tradable' => false,
    'is_dropable' => false,
    'is_sellable' => false,
    'is_stackable' => true,
  ],
  94081 => 
  [
    'id' => 94081,
    'type' => 'etcitem',
    'name' => '+16 Weapon Pack - Demon\'s Staff (Time-limited]',
    'add_name' => '',
    'description' => '',
    'icon' => 'weapon_demons_staff_i00',
    'is_tradable' => false,
    'is_dropable' => false,
    'is_sellable' => false,
    'is_stackable' => true,
  ],
  94082 => 
  [
    'id' => 94082,
    'type' => 'etcitem',
    'name' => '+16 Weapon Pack - Berserker Blade (Time-limited]',
    'add_name' => '',
    'description' => '',
    'icon' => 'weapon_berserker_blade_i00',
    'is_tradable' => false,
    'is_dropable' => false,
    'is_sellable' => false,
    'is_stackable' => true,
  ],
  94083 => 
  [
    'id' => 94083,
    'type' => 'armor',
    'name' => 'Helmet of Mana',
    'add_name' => '',
    'description' => '',
    'icon' => 'armor_leather_helmet_i00',
    'bodypart' => 'head',
    'crystal_type' => 'a',
    'weight' => 560,
    'enchant_enabled' => true,
  ],
  94084 => 
  [
    'id' => 94084,
    'type' => 'armor',
    'name' => 'Helmet of Mana',
    'add_name' => '',
    'description' => '',
    'icon' => 'armor_leather_helmet_i00',
    'bodypart' => 'head',
    'crystal_type' => 'a',
    'weight' => 560,
    'enchant_enabled' => true,
    'is_tradable' => false,
    'is_dropable' => false,
    'is_sellable' => false,
  ],
  94085 => 
  [
    'id' => 94085,
    'type' => 'armor',
    'name' => 'Boots of Evasion',
    'add_name' => '',
    'description' => '',
    'icon' => 'armor_t100_b_i00',
    'bodypart' => 'feet',
    'crystal_type' => 'a',
    'weight' => 1070,
    'enchant_enabled' => true,
  ],
  94086 => 
  [
    'id' => 94086,
    'type' => 'armor',
    'name' => 'Boots of Evasion',
    'add_name' => '',
    'description' => '',
    'icon' => 'armor_t100_b_i00',
    'bodypart' => 'feet',
    'crystal_type' => 'a',
    'weight' => 1070,
    'enchant_enabled' => true,
    'is_tradable' => false,
    'is_dropable' => false,
    'is_sellable' => false,
  ],
  94087 => 
  [
    'id' => 94087,
    'type' => 'etcitem',
    'name' => 'Package: Helmet of Mana',
    'add_name' => '',
    'description' => '',
    'icon' => 'armor_leather_helmet_i00',
    'is_tradable' => false,
    'is_dropable' => false,
    'is_sellable' => false,
    'is_stackable' => true,
    'handler' => 'extractableitems',
  ],
  94088 => 
  [
    'id' => 94088,
    'type' => 'etcitem',
    'name' => 'Package: Helmet of Mana',
    'add_name' => '',
    'description' => '',
    'icon' => 'armor_leather_helmet_i00',
    'is_tradable' => false,
    'is_dropable' => false,
    'is_sellable' => false,
    'is_stackable' => true,
    'handler' => 'extractableitems',
  ],
  94089 => 
  [
    'id' => 94089,
    'type' => 'etcitem',
    'name' => 'Package: Boots of Evasion',
    'add_name' => '',
    'description' => '',
    'icon' => 'armor_t100_b_i00',
    'is_tradable' => false,
    'is_dropable' => false,
    'is_sellable' => false,
    'is_stackable' => true,
    'handler' => 'extractableitems',
  ],
  94090 => 
  [
    'id' => 94090,
    'type' => 'etcitem',
    'name' => 'Package: Boots of Evasion',
    'add_name' => '',
    'description' => '',
    'icon' => 'armor_t100_b_i00',
    'is_tradable' => false,
    'is_dropable' => false,
    'is_sellable' => false,
    'is_stackable' => true,
    'handler' => 'extractableitems',
  ],
  94091 => 
  [
    'id' => 94091,
    'type' => 'etcitem',
    'name' => 'Kit: Aden Adventure Reward - Advanced (Time-limited]',
    'add_name' => '',
    'description' => '',
    'icon' => 'etc_pi_box_wish_pack',
    'is_tradable' => false,
    'is_dropable' => false,
    'is_sellable' => false,
    'is_stackable' => true,
    'handler' => 'extractableitems',
  ],
  94092 => 
  [
    'id' => 94092,
    'type' => 'etcitem',
    'name' => 'Dream Box (Time-limited]',
    'add_name' => '',
    'description' => '',
    'icon' => 'bm_special_jewelbox_lv4',
    'is_tradable' => false,
    'is_dropable' => false,
    'is_sellable' => false,
    'is_stackable' => true,
    'handler' => 'extractableitems',
    'extractableCountMin' => '1',
    'extractableCountMax' => '1',
  ],
  94093 => 
  [
    'id' => 94093,
    'type' => 'etcitem',
    'name' => 'High-grade Item Craft Coupon (Time-limited]',
    'add_name' => '',
    'description' => '',
    'icon' => 'bm_jewel_ticket',
    'is_tradable' => false,
    'is_dropable' => false,
    'is_sellable' => false,
    'is_stackable' => true,
  ],
  94094 => 
  [
    'id' => 94094,
    'type' => 'etcitem',
    'name' => '+7 Talisman of Authority Pack',
    'add_name' => '',
    'description' => '',
    'icon' => 'bm_silver_lure_box',
    'is_tradable' => false,
    'is_dropable' => false,
    'is_sellable' => false,
    'is_stackable' => true,
    'handler' => 'extractableitems',
  ],
  94095 => 
  [
    'id' => 94095,
    'type' => 'etcitem',
    'name' => 'Package: Inventory Expansion Ticket Lv. 4-5',
    'add_name' => '',
    'description' => '',
    'icon' => 'etc_ticket_i00',
    'is_depositable' => false,
    'is_sellable' => false,
    'is_stackable' => true,
    'handler' => 'extractableitems',
  ],
  94096 => 
  [
    'id' => 94096,
    'type' => 'etcitem',
    'name' => 'Regular Pet Training Guide',
    'add_name' => '',
    'description' => '',
    'icon' => 'pet_training_red_book_i00',
    'is_sellable' => false,
    'is_stackable' => true,
  ],
  94097 => 
  [
    'id' => 94097,
    'type' => 'etcitem',
    'name' => 'Sealed Wolf Necklace',
    'add_name' => '',
    'description' => '',
    'icon' => 'etc_summon_wolf_r_02',
    'is_tradable' => false,
    'is_dropable' => false,
    'is_depositable' => false,
    'is_sellable' => false,
    'is_stackable' => true,
    'handler' => 'extractableitems',
  ],
  94098 => 
  [
    'id' => 94098,
    'type' => 'etcitem',
    'name' => 'Sealed Buffalo Necklace',
    'add_name' => '',
    'description' => '',
    'icon' => 'buffalo_necklace_i00',
    'is_tradable' => false,
    'is_dropable' => false,
    'is_depositable' => false,
    'is_sellable' => false,
    'is_stackable' => true,
    'handler' => 'extractableitems',
  ],
  94099 => 
  [
    'id' => 94099,
    'type' => 'etcitem',
    'name' => 'Sealed Tiger Necklace',
    'add_name' => '',
    'description' => '',
    'icon' => 'etc_tooth_gragon',
    'is_tradable' => false,
    'is_dropable' => false,
    'is_depositable' => false,
    'is_sellable' => false,
    'is_stackable' => true,
    'handler' => 'extractableitems',
  ],
];