<?php
return [
  11900 => 
  [
    'id' => 11900,
    'type' => 'weapon',
    'name' => 'Common Item - Sword of Valhalla',
    'add_name' => '',
    'description' => 'Sword of Valhalla with limited enhancement options. Enchantment, soul storing and augmenting are impossible.',
    'icon' => 'weapon_sword_of_valhalla_i00',
    'weapon_type' => 'sword',
    'bodypart' => 'rhand',
    'crystal_count' => 47,
    'crystal_type' => 'b',
    'weight' => 300,
    'price' => 349500,
    'soulshots' => 1,
    'spiritshots' => 1,
    'is_magic_weapon' => true,
    'stats' => 
    [
      'pAtk' => 140,
      'mAtk' => 122,
      'critRate' => 8,
      'pAtkSpd' => 379,
    ],
  ],
  11901 => 
  [
    'id' => 11901,
    'type' => 'weapon',
    'name' => 'Common Item - Stormbringer*Samurai Long Sword',
    'add_name' => '',
    'description' => 'Stormbringer*Samurai Long Sword with limited enhancement options. Enchantment, soul storing and augmenting are impossible.',
    'icon' => 'weapon_dual_sword_i00',
    'weapon_type' => 'dual',
    'bodypart' => 'lrhand',
    'crystal_count' => 47,
    'crystal_type' => 'b',
    'weight' => 717,
    'price' => 349500,
    'soulshots' => 1,
    'spiritshots' => 1,
    'stats' => 
    [
      'pAtk' => 213,
      'mAtk' => 91,
      'critRate' => 8,
      'pAtkSpd' => 325,
    ],
  ],
  11902 => 
  [
    'id' => 11902,
    'type' => 'weapon',
    'name' => 'Common Item - Spell Breaker',
    'add_name' => '',
    'description' => 'Spell Breaker with limited enhancement options. Enchantment, soul storing and augmenting are impossible.',
    'icon' => 'weapon_spell_breaker_i00',
    'weapon_type' => 'blunt',
    'bodypart' => 'rhand',
    'crystal_count' => 47,
    'crystal_type' => 'b',
    'weight' => 540,
    'price' => 349500,
    'soulshots' => 1,
    'spiritshots' => 1,
    'is_magic_weapon' => true,
    'stats' => 
    [
      'pAtk' => 140,
      'mAtk' => 122,
      'critRate' => 4,
      'pAtkSpd' => 379,
    ],
  ],
  11903 => 
  [
    'id' => 11903,
    'type' => 'weapon',
    'name' => 'Common Item - Arthro Nail',
    'add_name' => '',
    'description' => 'Arthro Nail with limited enhancement options. Enchantment, soul storing and augmenting are impossible.',
    'icon' => 'weapon_arthro_nail_i00',
    'weapon_type' => 'dualfist',
    'bodypart' => 'lrhand',
    'crystal_count' => 47,
    'crystal_type' => 'b',
    'weight' => 473,
    'price' => 349500,
    'soulshots' => 1,
    'spiritshots' => 1,
    'stats' => 
    [
      'pAtk' => 213,
      'mAtk' => 91,
      'critRate' => 4,
      'pAtkSpd' => 325,
    ],
  ],
  11904 => 
  [
    'id' => 11904,
    'type' => 'weapon',
    'name' => 'Common Item - Ice Storm Hammer',
    'add_name' => '',
    'description' => 'Ice Storm Hammer with limited enhancement options. Enchantment, soul storing and augmenting are impossible.',
    'icon' => 'weapon_ice_storm_hammer_i00',
    'weapon_type' => 'blunt',
    'bodypart' => 'lrhand',
    'crystal_count' => 47,
    'crystal_type' => 'b',
    'weight' => 650,
    'price' => 349500,
    'soulshots' => 1,
    'spiritshots' => 1,
    'stats' => 
    [
      'pAtk' => 213,
      'mAtk' => 91,
      'critRate' => 4,
      'pAtkSpd' => 325,
    ],
  ],
  11905 => 
  [
    'id' => 11905,
    'type' => 'weapon',
    'name' => 'Common Item - Sword of Nightmare*Sword of Nightmare',
    'add_name' => '',
    'description' => 'Sword of Nightmare*Sword of Nightmare with limited enhancement options. Enchantment, soul storing and augmenting are impossible.',
    'icon' => 'weapon_dual_sword_i00',
    'weapon_type' => 'dual',
    'bodypart' => 'lrhand',
    'crystal_count' => 47,
    'crystal_type' => 'b',
    'weight' => 710,
    'price' => 349500,
    'soulshots' => 1,
    'spiritshots' => 1,
    'stats' => 
    [
      'pAtk' => 213,
      'mAtk' => 91,
      'critRate' => 8,
      'pAtkSpd' => 325,
    ],
  ],
  11906 => 
  [
    'id' => 11906,
    'type' => 'weapon',
    'name' => 'Common Item - Sword of Nightmare*Tsurugi',
    'add_name' => '',
    'description' => 'Sword of Nightmare*Tsurugi with limited enhancement options. Enchantment, soul storing and augmenting are impossible.',
    'icon' => 'weapon_dual_sword_i00',
    'weapon_type' => 'dual',
    'bodypart' => 'lrhand',
    'crystal_count' => 47,
    'crystal_type' => 'b',
    'weight' => 713,
    'price' => 349500,
    'soulshots' => 1,
    'spiritshots' => 1,
    'stats' => 
    [
      'pAtk' => 213,
      'mAtk' => 91,
      'critRate' => 8,
      'pAtkSpd' => 325,
    ],
  ],
  11907 => 
  [
    'id' => 11907,
    'type' => 'weapon',
    'name' => 'Common Item - Military Fleuret',
    'add_name' => '',
    'description' => 'Kamael Exclusive Weapon: Shadow weapon - Keshanberk conversion. Military Fleuret with limited ability enhancement. Enchantment, special abilities and augmentation are not possible.',
    'icon' => 'weapon_assult_fleuret_i00',
    'weapon_type' => 'rapier',
    'bodypart' => 'rhand',
    'crystal_count' => 47,
    'crystal_type' => 'b',
    'weight' => 457,
    'price' => 349500,
    'change_weaponId' => 11916,
    'soulshots' => 1,
    'spiritshots' => 1,
    'stats' => 
    [
      'pAtk' => 159,
      'mAtk' => 91,
      'critRate' => 10,
      'pAtkSpd' => 406,
    ],
  ],
  11908 => 
  [
    'id' => 11908,
    'type' => 'weapon',
    'name' => 'Common Item - Sprite\'s Staff',
    'add_name' => '',
    'description' => 'Sprite\'s Staff of Mana with limited enhancement options. Enchantment, soul storing and augmenting are impossible.',
    'icon' => 'weapon_sprites_staff_i00',
    'weapon_type' => 'blunt',
    'bodypart' => 'lrhand',
    'crystal_count' => 47,
    'crystal_type' => 'b',
    'weight' => 320,
    'price' => 349500,
    'soulshots' => 1,
    'spiritshots' => 1,
    'is_magic_weapon' => true,
    'stats' => 
    [
      'pAtk' => 170,
      'mAtk' => 134,
      'critRate' => 4,
      'pAtkSpd' => 325,
    ],
  ],
  11909 => 
  [
    'id' => 11909,
    'type' => 'weapon',
    'name' => 'Common Item - Tsurugi*Tsurugi',
    'add_name' => '',
    'description' => 'Tsurugi*Tsurugi with limited enhancement options. Enchantment, soul storing and augmenting are impossible.',
    'icon' => 'weapon_dual_sword_i00',
    'weapon_type' => 'dual',
    'bodypart' => 'lrhand',
    'crystal_count' => 47,
    'crystal_type' => 'b',
    'weight' => 707,
    'price' => 349500,
    'soulshots' => 1,
    'spiritshots' => 1,
    'stats' => 
    [
      'pAtk' => 213,
      'mAtk' => 91,
      'critRate' => 8,
      'pAtkSpd' => 325,
    ],
  ],
  11910 => 
  [
    'id' => 11910,
    'type' => 'weapon',
    'name' => 'Common Item - Caliburs*Sword of Limit',
    'add_name' => '',
    'description' => 'Caliburs*Sword of Limit with limited enhancement options. Enchantment, soul storing and augmenting are impossible.',
    'icon' => 'weapon_dual_sword_i00',
    'weapon_type' => 'dual',
    'bodypart' => 'lrhand',
    'crystal_count' => 47,
    'crystal_type' => 'b',
    'weight' => 717,
    'price' => 349500,
    'soulshots' => 1,
    'spiritshots' => 1,
    'stats' => 
    [
      'pAtk' => 213,
      'mAtk' => 91,
      'critRate' => 8,
      'pAtkSpd' => 325,
    ],
  ],
  11911 => 
  [
    'id' => 11911,
    'type' => 'weapon',
    'name' => 'Common Item - Caliburs*Sword of Delusion',
    'add_name' => '',
    'description' => 'Caliburs*Sword of Delusion with limited enhancement options. Enchantment, soul storing and augmenting are impossible.',
    'icon' => 'weapon_dual_sword_i00',
    'weapon_type' => 'dual',
    'bodypart' => 'lrhand',
    'crystal_count' => 47,
    'crystal_type' => 'b',
    'weight' => 713,
    'price' => 349500,
    'soulshots' => 1,
    'spiritshots' => 1,
    'stats' => 
    [
      'pAtk' => 213,
      'mAtk' => 91,
      'critRate' => 8,
      'pAtkSpd' => 325,
    ],
  ],
  11912 => 
  [
    'id' => 11912,
    'type' => 'weapon',
    'name' => 'Common Item - Caliburs*Sword of Nightmare',
    'add_name' => '',
    'description' => 'Caliburs*Sword of Delusion with limited enhancement options. Enchantment, soul storing and augmenting are impossible.',
    'icon' => 'weapon_dual_sword_i00',
    'weapon_type' => 'dual',
    'bodypart' => 'lrhand',
    'crystal_count' => 47,
    'crystal_type' => 'b',
    'weight' => 723,
    'price' => 349500,
    'soulshots' => 1,
    'spiritshots' => 1,
    'stats' => 
    [
      'pAtk' => 213,
      'mAtk' => 91,
      'critRate' => 8,
      'pAtkSpd' => 325,
    ],
  ],
  11913 => 
  [
    'id' => 11913,
    'type' => 'weapon',
    'name' => 'Common Item - Caliburs*Tsurugi',
    'add_name' => '',
    'description' => 'Caliburs*Tsurugi with limited enhancement options. Enchantment, soul storing and augmenting are impossible.',
    'icon' => 'weapon_dual_sword_i00',
    'weapon_type' => 'dual',
    'bodypart' => 'lrhand',
    'crystal_count' => 47,
    'crystal_type' => 'b',
    'weight' => 717,
    'price' => 349500,
    'soulshots' => 1,
    'spiritshots' => 1,
    'stats' => 
    [
      'pAtk' => 213,
      'mAtk' => 91,
      'critRate' => 8,
      'pAtkSpd' => 325,
    ],
  ],
  11914 => 
  [
    'id' => 11914,
    'type' => 'weapon',
    'name' => 'Common Item - Caliburs*Caliburs',
    'add_name' => '',
    'description' => 'Caliburs*Caliburs with limited enhancement options. Enchantment, soul storing and augmenting are impossible.',
    'icon' => 'weapon_dual_sword_i00',
    'weapon_type' => 'dual',
    'bodypart' => 'lrhand',
    'crystal_count' => 47,
    'crystal_type' => 'b',
    'weight' => 713,
    'price' => 349500,
    'soulshots' => 1,
    'spiritshots' => 1,
    'stats' => 
    [
      'pAtk' => 213,
      'mAtk' => 91,
      'critRate' => 8,
      'pAtkSpd' => 325,
    ],
  ],
  11915 => 
  [
    'id' => 11915,
    'type' => 'weapon',
    'name' => 'Common Item - Kris',
    'add_name' => '',
    'description' => 'Kris with limited enhancement options. Enchantment, soul storing and augmenting are impossible.',
    'icon' => 'weapon_kris_i00',
    'weapon_type' => 'dagger',
    'bodypart' => 'rhand',
    'crystal_count' => 47,
    'crystal_type' => 'b',
    'weight' => 327,
    'price' => 349500,
    'soulshots' => 1,
    'spiritshots' => 1,
    'stats' => 
    [
      'pAtk' => 153,
      'mAtk' => 91,
      'critRate' => 12,
      'pAtkSpd' => 433,
    ],
  ],
  11916 => 
  [
    'id' => 11916,
    'type' => 'weapon',
    'name' => 'Common Item - Keshanberk',
    'add_name' => '',
    'description' => 'Keshanberk with limited enhancement options. Enchantment, soul storing and augmenting are impossible.',
    'icon' => 'weapon_kshanberk_i00',
    'weapon_type' => 'sword',
    'bodypart' => 'rhand',
    'crystal_count' => 47,
    'crystal_type' => 'b',
    'weight' => 457,
    'price' => 349500,
    'change_weaponId' => 11907,
    'soulshots' => 1,
    'spiritshots' => 1,
    'stats' => 
    [
      'pAtk' => 175,
      'mAtk' => 91,
      'critRate' => 8,
      'pAtkSpd' => 379,
    ],
  ],
  11917 => 
  [
    'id' => 11917,
    'type' => 'weapon',
    'name' => 'Common Item - Peacemaker',
    'add_name' => '',
    'description' => 'Kamael Exclusive Weapon: Shadow weapon - Dark Elven Long Bow conversion. Peacemaker with limited ability enhancement. Enchantment, special abilities and augmentation are not possible.',
    'icon' => 'weapon_peace_maker_i00',
    'weapon_type' => 'crossbow',
    'bodypart' => 'lrhand',
    'crystal_count' => 47,
    'crystal_type' => 'b',
    'weight' => 573,
    'price' => 349500,
    'change_weaponId' => 11896,
    'soulshots' => 2,
    'spiritshots' => 1,
    'stats' => 
    [
      'pAtk' => 221,
      'mAtk' => 91,
      'critRate' => 10,
      'pAtkSpd' => 303,
    ],
  ],
  11918 => 
  [
    'id' => 11918,
    'type' => 'weapon',
    'name' => 'Common Item - Heavy War Axe',
    'add_name' => '',
    'description' => 'Heavy War Axe with limited enhancement options. Enchantment, soul storing and augmenting are impossible.',
    'icon' => 'weapon_heavy_war_axe_i00',
    'weapon_type' => 'blunt',
    'bodypart' => 'rhand',
    'crystal_count' => 47,
    'crystal_type' => 'b',
    'weight' => 540,
    'price' => 349500,
    'soulshots' => 1,
    'spiritshots' => 1,
    'stats' => 
    [
      'pAtk' => 175,
      'mAtk' => 91,
      'critRate' => 4,
      'pAtkSpd' => 379,
    ],
  ],
  11919 => 
  [
    'id' => 11919,
    'type' => 'weapon',
    'name' => 'Common Item - Hell Knife',
    'add_name' => '',
    'description' => 'Hell Knife with limited enhancement options. Enchantment, soul storing and augmenting are impossible.',
    'icon' => 'weapon_hell_knife_i00',
    'weapon_type' => 'dagger',
    'bodypart' => 'rhand',
    'crystal_count' => 47,
    'crystal_type' => 'b',
    'weight' => 247,
    'price' => 349500,
    'soulshots' => 1,
    'spiritshots' => 1,
    'is_magic_weapon' => true,
    'stats' => 
    [
      'pAtk' => 122,
      'mAtk' => 122,
      'critRate' => 12,
      'pAtkSpd' => 433,
    ],
  ],
  11920 => 
  [
    'id' => 11920,
    'type' => 'weapon',
    'name' => 'Common Item - Raid Sword*Samurai Long Sword',
    'add_name' => '',
    'description' => 'Raid Sword*Samurai Long Sword with limited enhancement options. Enchantment, soul storing and augmenting are impossible.',
    'icon' => 'weapon_dual_sword_i00',
    'weapon_type' => 'dual',
    'bodypart' => 'lrhand',
    'crystal_count' => 49,
    'crystal_type' => 'b',
    'weight' => 710,
    'price' => 370000,
    'soulshots' => 1,
    'spiritshots' => 1,
    'stats' => 
    [
      'pAtk' => 220,
      'mAtk' => 94,
      'critRate' => 8,
      'pAtkSpd' => 325,
    ],
  ],
  11921 => 
  [
    'id' => 11921,
    'type' => 'weapon',
    'name' => 'Common Item - Shamshir*Samurai Long Sword',
    'add_name' => '',
    'description' => 'Shamshir*Samurai Long Sword with limited enhancement options. Enchantment, soul storing and augmenting are impossible.',
    'icon' => 'weapon_dual_sword_i00',
    'weapon_type' => 'dual',
    'bodypart' => 'lrhand',
    'crystal_count' => 49,
    'crystal_type' => 'b',
    'weight' => 703,
    'price' => 370000,
    'soulshots' => 1,
    'spiritshots' => 1,
    'stats' => 
    [
      'pAtk' => 220,
      'mAtk' => 94,
      'critRate' => 8,
      'pAtkSpd' => 325,
    ],
  ],
  11922 => 
  [
    'id' => 11922,
    'type' => 'weapon',
    'name' => 'Common Item - Spirit Sword*Samurai Long Sword',
    'add_name' => '',
    'description' => 'Spirit Sword*Samurai Long Sword with limited enhancement options. Enchantment, soul storing and augmenting are impossible.',
    'icon' => 'weapon_dual_sword_i00',
    'weapon_type' => 'dual',
    'bodypart' => 'lrhand',
    'crystal_count' => 49,
    'crystal_type' => 'b',
    'weight' => 703,
    'price' => 370000,
    'soulshots' => 1,
    'spiritshots' => 1,
    'stats' => 
    [
      'pAtk' => 220,
      'mAtk' => 94,
      'critRate' => 8,
      'pAtkSpd' => 325,
    ],
  ],
  11923 => 
  [
    'id' => 11923,
    'type' => 'weapon',
    'name' => 'Common Item - Katana*Samurai Long Sword',
    'add_name' => '',
    'description' => 'Katana*Samurai Long Sword with limited enhancement options. Enchantment, soul storing and augmenting are impossible.',
    'icon' => 'weapon_dual_sword_i00',
    'weapon_type' => 'dual',
    'bodypart' => 'lrhand',
    'crystal_count' => 49,
    'crystal_type' => 'b',
    'weight' => 710,
    'price' => 370000,
    'soulshots' => 1,
    'spiritshots' => 1,
    'stats' => 
    [
      'pAtk' => 220,
      'mAtk' => 94,
      'critRate' => 8,
      'pAtkSpd' => 325,
    ],
  ],
  11924 => 
  [
    'id' => 11924,
    'type' => 'weapon',
    'name' => 'Common Item - Sword of Limit*Samurai Long Sword',
    'add_name' => '',
    'description' => 'Sword of Limit*Samurai Long Sword with limited enhancement options. Enchantment, soul storing and augmenting are impossible.',
    'icon' => 'weapon_dual_sword_i00',
    'weapon_type' => 'dual',
    'bodypart' => 'lrhand',
    'crystal_count' => 73,
    'crystal_type' => 'b',
    'weight' => 700,
    'price' => 549700,
    'soulshots' => 1,
    'spiritshots' => 1,
    'stats' => 
    [
      'pAtk' => 228,
      'mAtk' => 97,
      'critRate' => 8,
      'pAtkSpd' => 325,
    ],
  ],
  11925 => 
  [
    'id' => 11925,
    'type' => 'weapon',
    'name' => 'Common Item - Sword of Delusion*Samurai Long Sword',
    'add_name' => '',
    'description' => 'Sword of Delusion*Samurai Long Sword with limited enhancement options. Enchantment, soul storing and augmenting are impossible.',
    'icon' => 'weapon_dual_sword_i00',
    'weapon_type' => 'dual',
    'bodypart' => 'lrhand',
    'crystal_count' => 73,
    'crystal_type' => 'b',
    'weight' => 703,
    'price' => 549700,
    'soulshots' => 1,
    'spiritshots' => 1,
    'stats' => 
    [
      'pAtk' => 228,
      'mAtk' => 97,
      'critRate' => 8,
      'pAtkSpd' => 325,
    ],
  ],
  11926 => 
  [
    'id' => 11926,
    'type' => 'weapon',
    'name' => 'Common Item - Sword of Nightmare*Samurai Long Sword',
    'add_name' => '',
    'description' => 'Sword of Nightmare*Samurai Long Sword with limited enhancement options. Enchantment, soul storing and augmenting are impossible.',
    'icon' => 'weapon_dual_sword_i00',
    'weapon_type' => 'dual',
    'bodypart' => 'lrhand',
    'crystal_count' => 73,
    'crystal_type' => 'b',
    'weight' => 693,
    'price' => 549700,
    'soulshots' => 1,
    'spiritshots' => 1,
    'stats' => 
    [
      'pAtk' => 228,
      'mAtk' => 97,
      'critRate' => 8,
      'pAtkSpd' => 325,
    ],
  ],
  11927 => 
  [
    'id' => 11927,
    'type' => 'weapon',
    'name' => 'Common Item - Tsurugi*Samurai Long Sword',
    'add_name' => '',
    'description' => 'Tsurugi*Samurai Long Sword with limited enhancement options. Enchantment, soul storing and augmenting are impossible.',
    'icon' => 'weapon_dual_sword_i00',
    'weapon_type' => 'dual',
    'bodypart' => 'lrhand',
    'crystal_count' => 73,
    'crystal_type' => 'b',
    'weight' => 697,
    'price' => 549700,
    'soulshots' => 1,
    'spiritshots' => 1,
    'stats' => 
    [
      'pAtk' => 228,
      'mAtk' => 97,
      'critRate' => 8,
      'pAtkSpd' => 325,
    ],
  ],
  11928 => 
  [
    'id' => 11928,
    'type' => 'weapon',
    'name' => 'Common Item - Caliburs*Samurai Long Sword',
    'add_name' => '',
    'description' => 'Caliburs*Samurai Long Sword with limited enhancement options. Enchantment, soul storing and augmenting are impossible.',
    'icon' => 'weapon_dual_sword_i00',
    'weapon_type' => 'dual',
    'bodypart' => 'lrhand',
    'crystal_count' => 73,
    'crystal_type' => 'b',
    'weight' => 707,
    'price' => 549700,
    'soulshots' => 1,
    'spiritshots' => 1,
    'stats' => 
    [
      'pAtk' => 228,
      'mAtk' => 97,
      'critRate' => 8,
      'pAtkSpd' => 325,
    ],
  ],
  11929 => 
  [
    'id' => 11929,
    'type' => 'weapon',
    'name' => 'Common Item - Guardian Sword',
    'add_name' => '',
    'description' => 'Guardian Sword with limited enhancement options. Enchantment, soul storing and augmenting are impossible.',
    'icon' => 'weapon_guardians_sword_i00',
    'weapon_type' => 'sword',
    'bodypart' => 'lrhand',
    'crystal_count' => 82,
    'crystal_type' => 'b',
    'weight' => 643,
    'price' => 612300,
    'change_weaponId' => 11931,
    'soulshots' => 1,
    'spiritshots' => 1,
    'stats' => 
    [
      'pAtk' => 236,
      'mAtk' => 99,
      'critRate' => 8,
      'pAtkSpd' => 325,
    ],
  ],
  11930 => 
  [
    'id' => 11930,
    'type' => 'weapon',
    'name' => 'Common Item - Sword of Damascus',
    'add_name' => '',
    'description' => 'Sword of Damascus with limited enhancement options. Enchantment, soul storing and augmenting are impossible.',
    'icon' => 'weapon_sword_of_damascus_i00',
    'weapon_type' => 'sword',
    'bodypart' => 'rhand',
    'crystal_count' => 82,
    'crystal_type' => 'b',
    'weight' => 450,
    'price' => 612300,
    'change_weaponId' => 11942,
    'soulshots' => 1,
    'spiritshots' => 1,
    'stats' => 
    [
      'pAtk' => 194,
      'mAtk' => 99,
      'critRate' => 8,
      'pAtkSpd' => 379,
    ],
  ],
  11931 => 
  [
    'id' => 11931,
    'type' => 'weapon',
    'name' => 'Common Item - Dismantler',
    'add_name' => '',
    'description' => 'Kamael Exclusive Weapon: Shadow weapon - Guidance Sword conversion. Dismantler with limited ability enhancement. Enchantment, special abilities and augmentation are not possible.',
    'icon' => 'weapon_dismantler_i00',
    'weapon_type' => 'ancientsword',
    'bodypart' => 'lrhand',
    'crystal_count' => 82,
    'crystal_type' => 'b',
    'weight' => 643,
    'price' => 612300,
    'change_weaponId' => 11929,
    'soulshots' => 1,
    'spiritshots' => 1,
    'stats' => 
    [
      'pAtk' => 210,
      'mAtk' => 99,
      'critRate' => 8,
      'pAtkSpd' => 350,
    ],
  ],
  11932 => 
  [
    'id' => 11932,
    'type' => 'weapon',
    'name' => 'Common Item - Lance',
    'add_name' => '',
    'description' => 'Lance with limited enhancement options. Enchantment, soul storing and augmenting are impossible.',
    'icon' => 'weapon_lancia_i00',
    'weapon_type' => 'pole',
    'bodypart' => 'lrhand',
    'crystal_count' => 82,
    'crystal_type' => 'b',
    'weight' => 640,
    'price' => 612300,
    'soulshots' => 1,
    'spiritshots' => 1,
    'item_skill' => 
    [
      0 => 
      [
        'skill_id' => 3599,
        'level' => 1,
      ],
    ],
    'stats' => 
    [
      'pAtk' => 194,
      'mAtk' => 99,
      'critRate' => 8,
      'pAtkSpd' => 325,
    ],
  ],
  11933 => 
  [
    'id' => 11933,
    'type' => 'weapon',
    'name' => 'Common Item - Bellion Cestus',
    'add_name' => '',
    'description' => 'Bellion Cestus with limited enhancement options. Enchantment, soul storing and augmenting are impossible.',
    'icon' => 'weapon_bellion_cestus_i00',
    'weapon_type' => 'dualfist',
    'bodypart' => 'lrhand',
    'crystal_count' => 82,
    'crystal_type' => 'b',
    'weight' => 463,
    'price' => 612300,
    'soulshots' => 1,
    'spiritshots' => 1,
    'stats' => 
    [
      'pAtk' => 236,
      'mAtk' => 99,
      'critRate' => 4,
      'pAtkSpd' => 325,
    ],
  ],
  11934 => 
  [
    'id' => 11934,
    'type' => 'weapon',
    'name' => 'Common Item - Staff of Evil Spirits',
    'add_name' => '',
    'description' => 'Staff of Evil Spirits of Mana with limited enhancement options. Enchantment, soul storing and augmenting are impossible.',
    'icon' => 'weapon_staff_of_evil_sprit_i00',
    'weapon_type' => 'blunt',
    'bodypart' => 'lrhand',
    'crystal_count' => 82,
    'crystal_type' => 'b',
    'weight' => 310,
    'price' => 612300,
    'soulshots' => 1,
    'spiritshots' => 1,
    'is_magic_weapon' => true,
    'stats' => 
    [
      'pAtk' => 189,
      'mAtk' => 145,
      'critRate' => 4,
      'pAtkSpd' => 325,
    ],
  ],
  11935 => 
  [
    'id' => 11935,
    'type' => 'weapon',
    'name' => 'Common Item - Deadman\'s Glory',
    'add_name' => '',
    'description' => 'Deadman\'s Glory with limited enhancement options. Enchantment, soul storing and augmenting are impossible.',
    'icon' => 'weapon_deadmans_glory_i00',
    'weapon_type' => 'blunt',
    'bodypart' => 'rhand',
    'crystal_count' => 82,
    'crystal_type' => 'b',
    'weight' => 533,
    'price' => 612300,
    'soulshots' => 1,
    'spiritshots' => 1,
    'stats' => 
    [
      'pAtk' => 194,
      'mAtk' => 99,
      'critRate' => 4,
      'pAtkSpd' => 379,
    ],
  ],
  11936 => 
  [
    'id' => 11936,
    'type' => 'weapon',
    'name' => 'Common Item - Star Buster',
    'add_name' => '',
    'description' => 'Star Buster with limited enhancement options. Enchantment, soul storing and augmenting are impossible.',
    'icon' => 'weapon_star_buster_i00',
    'weapon_type' => 'blunt',
    'bodypart' => 'lrhand',
    'crystal_count' => 82,
    'crystal_type' => 'b',
    'weight' => 643,
    'price' => 612300,
    'soulshots' => 1,
    'spiritshots' => 1,
    'stats' => 
    [
      'pAtk' => 236,
      'mAtk' => 99,
      'critRate' => 4,
      'pAtkSpd' => 325,
    ],
  ],
  11937 => 
  [
    'id' => 11937,
    'type' => 'weapon',
    'name' => 'Common Item - Samurai Long Sword*Samurai Long Sword',
    'add_name' => '',
    'description' => 'Samurai Long Sword*Samurai Long Sword with limited enhancement options. Enchantment, soul storing and augmenting are impossible.',
    'icon' => 'weapon_dual_sword_i00',
    'weapon_type' => 'dual',
    'bodypart' => 'lrhand',
    'crystal_count' => 82,
    'crystal_type' => 'b',
    'weight' => 693,
    'price' => 612300,
    'soulshots' => 1,
    'spiritshots' => 1,
    'stats' => 
    [
      'pAtk' => 236,
      'mAtk' => 99,
      'critRate' => 8,
      'pAtkSpd' => 325,
    ],
  ],
  11938 => 
  [
    'id' => 11938,
    'type' => 'weapon',
    'name' => 'Common Item - Art of Battle Axe',
    'add_name' => '',
    'description' => 'Art of Battle Axe with limited enhancement options. Enchantment, soul storing and augmenting are impossible.',
    'icon' => 'weapon_art_of_battle_axe_i00',
    'weapon_type' => 'blunt',
    'bodypart' => 'rhand',
    'crystal_count' => 82,
    'crystal_type' => 'b',
    'weight' => 523,
    'price' => 612300,
    'soulshots' => 1,
    'spiritshots' => 1,
    'stats' => 
    [
      'pAtk' => 194,
      'mAtk' => 99,
      'critRate' => 4,
      'pAtkSpd' => 379,
    ],
  ],
  11939 => 
  [
    'id' => 11939,
    'type' => 'weapon',
    'name' => 'Common Item - Demon\'s Dagger',
    'add_name' => '',
    'description' => 'Demon\'s Dagger with limited enhancement options. Enchantment, soul storing and augmenting are impossible.',
    'icon' => 'weapon_demons_sword_i00',
    'weapon_type' => 'dagger',
    'bodypart' => 'rhand',
    'crystal_count' => 82,
    'crystal_type' => 'b',
    'weight' => 323,
    'price' => 612300,
    'soulshots' => 1,
    'spiritshots' => 1,
    'stats' => 
    [
      'pAtk' => 170,
      'mAtk' => 99,
      'critRate' => 12,
      'pAtkSpd' => 433,
    ],
  ],
  11940 => 
  [
    'id' => 11940,
    'type' => 'weapon',
    'name' => 'Common Item - Demon\'s Dagger',
    'add_name' => '',
    'description' => 'Demon\'s Dagger with limited enhancement options. Enchantment, soul storing and augmenting are impossible.',
    'icon' => 'weapon_demons_sword_i00',
    'weapon_type' => 'dagger',
    'bodypart' => 'rhand',
    'crystal_count' => 82,
    'crystal_type' => 'b',
    'weight' => 323,
    'price' => 612300,
    'soulshots' => 1,
    'spiritshots' => 1,
    'oncrit_chance' => 12,
    'oncrit_skill' => 
    [
      0 => 
      [
        'skill_id' => 3020,
        'level' => 6,
      ],
    ],
    'stats' => 
    [
      'pAtk' => 170,
      'mAtk' => 99,
      'critRate' => 12,
      'pAtkSpd' => 433,
    ],
  ],
  11941 => 
  [
    'id' => 11941,
    'type' => 'weapon',
    'name' => 'Common Item - Kaim Vanul\'s Bones',
    'add_name' => '',
    'description' => 'Kaim Vanul\'s Bones with limited enhancement options. Enchantment, soul storing and augmenting are impossible.',
    'icon' => 'weapon_bone_of_kaim_vanul_i00',
    'weapon_type' => 'blunt',
    'bodypart' => 'rhand',
    'crystal_count' => 82,
    'crystal_type' => 'b',
    'weight' => 523,
    'price' => 612300,
    'soulshots' => 1,
    'spiritshots' => 1,
    'is_magic_weapon' => true,
    'stats' => 
    [
      'pAtk' => 155,
      'mAtk' => 132,
      'critRate' => 4,
      'pAtkSpd' => 379,
    ],
  ],
  11942 => 
  [
    'id' => 11942,
    'type' => 'weapon',
    'name' => 'Common Item - Colichemarde',
    'add_name' => '',
    'description' => 'Kamael Exclusive Weapon: Shadow weapon - Damascus Sword conversion. Colichemarde with limited ability enhancement. Enchantment, special abilities and augmentation are not possible.',
    'icon' => 'weapon_colichemarde_i00',
    'weapon_type' => 'rapier',
    'bodypart' => 'rhand',
    'crystal_count' => 82,
    'crystal_type' => 'b',
    'weight' => 450,
    'price' => 612300,
    'change_weaponId' => 11930,
    'soulshots' => 1,
    'spiritshots' => 1,
    'stats' => 
    [
      'pAtk' => 176,
      'mAtk' => 99,
      'critRate' => 10,
      'pAtkSpd' => 406,
    ],
  ],
  11943 => 
  [
    'id' => 11943,
    'type' => 'weapon',
    'name' => 'Common Item - Wizard\'s Tear',
    'add_name' => '',
    'description' => 'Wizard\'s Tear with limited enhancement options. Enchantment, soul storing and augmenting are impossible.',
    'icon' => 'weapon_tears_of_wizard_i00',
    'weapon_type' => 'sword',
    'bodypart' => 'rhand',
    'crystal_count' => 82,
    'crystal_type' => 'b',
    'weight' => 450,
    'price' => 612300,
    'soulshots' => 1,
    'spiritshots' => 1,
    'is_magic_weapon' => true,
    'stats' => 
    [
      'pAtk' => 155,
      'mAtk' => 132,
      'critRate' => 8,
      'pAtkSpd' => 379,
    ],
  ],
  11944 => 
  [
    'id' => 11944,
    'type' => 'weapon',
    'name' => 'Common Item - Bow of Peril',
    'add_name' => '',
    'description' => 'Bow of Peril with limited enhancement options. Enchantment, soul storing and augmenting are impossible.',
    'icon' => 'weapon_hazard_bow_i00',
    'weapon_type' => 'bow',
    'bodypart' => 'lrhand',
    'crystal_count' => 82,
    'crystal_type' => 'b',
    'weight' => 567,
    'price' => 612300,
    'change_weaponId' => 11945,
    'soulshots' => 3,
    'spiritshots' => 1,
    'mp_consume' => 4,
    'stats' => 
    [
      'pAtk' => 400,
      'mAtk' => 99,
      'critRate' => 12,
      'pAtkSpd' => 293,
    ],
  ],
  11945 => 
  [
    'id' => 11945,
    'type' => 'weapon',
    'name' => 'Common Item - Hell Hound',
    'add_name' => '',
    'description' => 'Kamael Exclusive Weapon: Shadow weapon - Bow of Peril conversion. Hell Hound with limited ability enhancement. Enchantment, special abilities and augmentation are not possible.',
    'icon' => 'weapon_hell_hound_i00',
    'weapon_type' => 'crossbow',
    'bodypart' => 'lrhand',
    'crystal_count' => 82,
    'crystal_type' => 'b',
    'weight' => 567,
    'price' => 612300,
    'change_weaponId' => 11944,
    'soulshots' => 2,
    'spiritshots' => 1,
    'stats' => 
    [
      'pAtk' => 245,
      'mAtk' => 99,
      'critRate' => 10,
      'pAtkSpd' => 303,
    ],
  ],
  11946 => 
  [
    'id' => 11946,
    'type' => 'weapon',
    'name' => 'Common Item - Dasparion\'s Staff',
    'add_name' => '',
    'description' => 'Dasparion\'s Staff with limited enhancement options. Enchantment, soul storing and augmenting are impossible.',
    'icon' => 'weapon_dasparions_staff_i00',
    'weapon_type' => 'blunt',
    'bodypart' => 'lrhand',
    'crystal_count' => 58,
    'crystal_type' => 'a',
    'weight' => 307,
    'price' => 726500,
    'soulshots' => 1,
    'spiritshots' => 1,
    'is_magic_weapon' => true,
    'stats' => 
    [
      'pAtk' => 207,
      'mAtk' => 157,
      'critRate' => 4,
      'pAtkSpd' => 325,
    ],
  ],
  11947 => 
  [
    'id' => 11947,
    'type' => 'weapon',
    'name' => 'Common Item - Doomchanter',
    'add_name' => '',
    'description' => 'Kamael Exclusive Weapon: Shadow weapon - Carnage Bow conversion. Doomchanter with limited ability enhancement. Enchantment, special abilities and augmentation are not possible.',
    'icon' => 'weapon_doom_singer_i00',
    'weapon_type' => 'crossbow',
    'bodypart' => 'lrhand',
    'crystal_count' => 58,
    'crystal_type' => 'a',
    'weight' => 557,
    'price' => 726500,
    'change_weaponId' => 11955,
    'soulshots' => 1,
    'spiritshots' => 1,
    'stats' => 
    [
      'pAtk' => 270,
      'mAtk' => 107,
      'critRate' => 10,
      'pAtkSpd' => 303,
    ],
  ],
  11948 => 
  [
    'id' => 11948,
    'type' => 'weapon',
    'name' => 'Common Item - White Lightning',
    'add_name' => '',
    'description' => 'Kamael Exclusive Weapon: Shadow weapon - Tallum Blade conversion. White Lightning with limited ability enhancement. Enchantment, special abilities and augmentation are not possible.',
    'icon' => 'weapon_lightning_blaze_i00',
    'weapon_type' => 'rapier',
    'bodypart' => 'rhand',
    'crystal_count' => 58,
    'crystal_type' => 'a',
    'weight' => 443,
    'price' => 726500,
    'change_weaponId' => 11957,
    'soulshots' => 1,
    'spiritshots' => 1,
    'stats' => 
    [
      'pAtk' => 193,
      'mAtk' => 107,
      'critRate' => 10,
      'pAtkSpd' => 406,
    ],
  ],
  11949 => 
  [
    'id' => 11949,
    'type' => 'weapon',
    'name' => 'Common Item - Meteor Shower',
    'add_name' => '',
    'description' => 'Meteor Shower with limited enhancement options. Enchantment, soul storing and augmenting are impossible.',
    'icon' => 'weapon_meteor_shower_i00',
    'weapon_type' => 'blunt',
    'bodypart' => 'rhand',
    'crystal_count' => 58,
    'crystal_type' => 'a',
    'weight' => 533,
    'price' => 726500,
    'soulshots' => 1,
    'spiritshots' => 1,
    'stats' => 
    [
      'pAtk' => 213,
      'mAtk' => 107,
      'critRate' => 4,
      'pAtkSpd' => 379,
    ],
  ],
  11950 => 
  [
    'id' => 11950,
    'type' => 'weapon',
    'name' => 'Common Item - Blood Tornado',
    'add_name' => '',
    'description' => 'Blood Tornado with limited enhancement options. Enchantment, soul storing and augmenting are impossible.',
    'icon' => 'weapon_blood_tornado_i00',
    'weapon_type' => 'dualfist',
    'bodypart' => 'lrhand',
    'crystal_count' => 58,
    'crystal_type' => 'a',
    'weight' => 457,
    'price' => 726500,
    'soulshots' => 1,
    'spiritshots' => 1,
    'stats' => 
    [
      'pAtk' => 259,
      'mAtk' => 107,
      'critRate' => 4,
      'pAtkSpd' => 325,
    ],
  ],
  11951 => 
  [
    'id' => 11951,
    'type' => 'weapon',
    'name' => 'Common Item - Bloody Orchid',
    'add_name' => '',
    'description' => 'Bloody Orchid with limited enhancement options. Enchantment, soul storing and augmenting are impossible.',
    'icon' => 'weapon_bloody_orchid_i00',
    'weapon_type' => 'dagger',
    'bodypart' => 'rhand',
    'crystal_count' => 58,
    'crystal_type' => 'a',
    'weight' => 320,
    'price' => 726500,
    'soulshots' => 1,
    'spiritshots' => 1,
    'stats' => 
    [
      'pAtk' => 186,
      'mAtk' => 107,
      'critRate' => 12,
      'pAtkSpd' => 433,
    ],
  ],
  11952 => 
  [
    'id' => 11952,
    'type' => 'weapon',
    'name' => 'Common Item - Elemental Sword',
    'add_name' => '',
    'description' => 'Elemental Sword with limited enhancement options. Enchantment, soul storing and augmenting are impossible.',
    'icon' => 'weapon_elemental_sword_i00',
    'weapon_type' => 'sword',
    'bodypart' => 'rhand',
    'crystal_count' => 58,
    'crystal_type' => 'a',
    'weight' => 277,
    'price' => 726500,
    'soulshots' => 1,
    'spiritshots' => 1,
    'is_magic_weapon' => true,
    'stats' => 
    [
      'pAtk' => 170,
      'mAtk' => 143,
      'critRate' => 8,
      'pAtkSpd' => 379,
    ],
  ],
  11953 => 
  [
    'id' => 11953,
    'type' => 'weapon',
    'name' => 'Common Item - Spiritual Eye',
    'add_name' => '',
    'description' => 'Spiritual Eye with limited enhancement options. Enchantment, soul storing and augmenting are impossible.',
    'icon' => 'weapon_eye_of_soul_i00',
    'weapon_type' => 'blunt',
    'bodypart' => 'rhand',
    'crystal_count' => 58,
    'crystal_type' => 'a',
    'weight' => 517,
    'price' => 726500,
    'soulshots' => 1,
    'spiritshots' => 1,
    'is_magic_weapon' => true,
    'stats' => 
    [
      'pAtk' => 170,
      'mAtk' => 143,
      'critRate' => 4,
      'pAtkSpd' => 379,
    ],
  ],
  11954 => 
  [
    'id' => 11954,
    'type' => 'weapon',
    'name' => 'Common Item - Inferno Master',
    'add_name' => '',
    'description' => 'Inferno Master with limited enhancement options. Enchantment, soul storing and augmenting are impossible.',
    'icon' => 'weapon_inferno_master_i00',
    'weapon_type' => 'sword',
    'bodypart' => 'lrhand',
    'crystal_count' => 58,
    'crystal_type' => 'a',
    'weight' => 633,
    'price' => 726500,
    'change_weaponId' => 11959,
    'soulshots' => 1,
    'spiritshots' => 1,
    'stats' => 
    [
      'pAtk' => 259,
      'mAtk' => 107,
      'critRate' => 8,
      'pAtkSpd' => 325,
    ],
  ],
  11955 => 
  [
    'id' => 11955,
    'type' => 'weapon',
    'name' => 'Common Item - Carnage Bow',
    'add_name' => '',
    'description' => 'Carnage Bow with limited enhancement options. Enchantment, soul storing and augmenting are impossible.',
    'icon' => 'weapon_carnium_bow_i00',
    'weapon_type' => 'bow',
    'bodypart' => 'lrhand',
    'crystal_count' => 58,
    'crystal_type' => 'a',
    'weight' => 557,
    'price' => 726500,
    'change_weaponId' => 11947,
    'soulshots' => 2,
    'spiritshots' => 1,
    'mp_consume' => 4,
    'stats' => 
    [
      'pAtk' => 440,
      'mAtk' => 107,
      'critRate' => 12,
      'pAtkSpd' => 293,
    ],
  ],
  11956 => 
  [
    'id' => 11956,
    'type' => 'weapon',
    'name' => 'Common Item - Keshanberk*Keshanberk',
    'add_name' => '',
    'description' => 'Keshanberk*Keshanberk with limited enhancement options. Enchantment, soul storing and augmenting are impossible.',
    'icon' => 'weapon_dual_sword_i00',
    'weapon_type' => 'dual',
    'bodypart' => 'lrhand',
    'crystal_count' => 58,
    'crystal_type' => 'a',
    'weight' => 693,
    'price' => 726500,
    'soulshots' => 1,
    'spiritshots' => 1,
    'stats' => 
    [
      'pAtk' => 259,
      'mAtk' => 107,
      'critRate' => 8,
      'pAtkSpd' => 325,
    ],
  ],
  11957 => 
  [
    'id' => 11957,
    'type' => 'weapon',
    'name' => 'Common Item - Tallum Blade',
    'add_name' => '',
    'description' => 'Tallum Blade with limited enhancement options. Enchantment, soul storing and augmenting are impossible.',
    'icon' => 'weapon_tallum_blade_i00',
    'weapon_type' => 'sword',
    'bodypart' => 'rhand',
    'crystal_count' => 58,
    'crystal_type' => 'a',
    'weight' => 443,
    'price' => 726500,
    'change_weaponId' => 11948,
    'soulshots' => 1,
    'spiritshots' => 1,
    'stats' => 
    [
      'pAtk' => 213,
      'mAtk' => 107,
      'critRate' => 8,
      'pAtkSpd' => 379,
    ],
  ],
  11958 => 
  [
    'id' => 11958,
    'type' => 'weapon',
    'name' => 'Common Item - Destroyer Hammer',
    'add_name' => '',
    'description' => 'Destroyer Hammer with limited enhancement options. Enchantment, soul storing and augmenting are impossible.',
    'icon' => 'weapon_hammer_of_destroyer_i00',
    'weapon_type' => 'blunt',
    'bodypart' => 'lrhand',
    'crystal_count' => 58,
    'crystal_type' => 'a',
    'weight' => 637,
    'price' => 726500,
    'soulshots' => 1,
    'spiritshots' => 1,
    'stats' => 
    [
      'pAtk' => 259,
      'mAtk' => 107,
      'critRate' => 4,
      'pAtkSpd' => 325,
    ],
  ],
  11959 => 
  [
    'id' => 11959,
    'type' => 'weapon',
    'name' => 'Common Item - Divine Pain',
    'add_name' => '',
    'description' => 'Kamael Exclusive Weapon: Shadow Weapon - Inferno Master conversion. Divine Pain with limited ability enhancement. Enchantment, special abilities and augmentation are not possible.',
    'icon' => 'weapon_pain_of_godness_i00',
    'weapon_type' => 'ancientsword',
    'bodypart' => 'lrhand',
    'crystal_count' => 58,
    'crystal_type' => 'a',
    'weight' => 633,
    'price' => 726500,
    'change_weaponId' => 11954,
    'soulshots' => 1,
    'spiritshots' => 1,
    'stats' => 
    [
      'pAtk' => 231,
      'mAtk' => 107,
      'critRate' => 8,
      'pAtkSpd' => 350,
    ],
  ],
  11960 => 
  [
    'id' => 11960,
    'type' => 'weapon',
    'name' => 'Common Item - Halberd',
    'add_name' => '',
    'description' => 'Halberd with limited enhancement options. Enchantment, soul storing and augmenting are impossible.',
    'icon' => 'weapon_halbard_i00',
    'weapon_type' => 'pole',
    'bodypart' => 'lrhand',
    'crystal_count' => 58,
    'crystal_type' => 'a',
    'weight' => 633,
    'price' => 726500,
    'soulshots' => 1,
    'spiritshots' => 1,
    'item_skill' => 
    [
      0 => 
      [
        'skill_id' => 3599,
        'level' => 1,
      ],
    ],
    'stats' => 
    [
      'pAtk' => 213,
      'mAtk' => 107,
      'critRate' => 8,
      'pAtkSpd' => 325,
    ],
  ],
  11961 => 
  [
    'id' => 11961,
    'type' => 'weapon',
    'name' => 'Common Item - Keshanberk*Damascus',
    'add_name' => '',
    'description' => 'Keshanberk*Damascus with limited enhancement options. Enchantment, soul storing and augmenting are impossible.',
    'icon' => 'weapon_dual_sword_i00',
    'weapon_type' => 'dual',
    'bodypart' => 'lrhand',
    'crystal_count' => 85,
    'crystal_type' => 'a',
    'weight' => 693,
    'price' => 1063000,
    'soulshots' => 1,
    'spiritshots' => 1,
    'stats' => 
    [
      'pAtk' => 275,
      'mAtk' => 112,
      'critRate' => 8,
      'pAtkSpd' => 325,
    ],
  ],
  11962 => 
  [
    'id' => 11962,
    'type' => 'weapon',
    'name' => 'Common Item - Lacerator',
    'add_name' => '',
    'description' => 'Kamael Exclusive Weapon: Shadow weapon - Dark Legion conversion. Lacerator with limited ability enhancement. Enchantment, special abilities and augmentation are not possible.',
    'icon' => 'weapon_greed_stinger_i00',
    'weapon_type' => 'rapier',
    'bodypart' => 'rhand',
    'crystal_count' => 90,
    'crystal_type' => 'a',
    'weight' => 440,
    'price' => 1125000,
    'change_weaponId' => 11964,
    'soulshots' => 1,
    'spiritshots' => 1,
    'stats' => 
    [
      'pAtk' => 210,
      'mAtk' => 114,
      'critRate' => 10,
      'pAtkSpd' => 406,
    ],
  ],
  11963 => 
  [
    'id' => 11963,
    'type' => 'weapon',
    'name' => 'Common Item - Damascus*Damascus',
    'add_name' => '',
    'description' => 'Damascus*Damascus with limited enhancement options. Enchantment, soul storing and augmenting are impossible.',
    'icon' => 'weapon_dual_sword_i00',
    'weapon_type' => 'dual',
    'bodypart' => 'lrhand',
    'crystal_count' => 90,
    'crystal_type' => 'a',
    'weight' => 693,
    'price' => 1125000,
    'soulshots' => 1,
    'spiritshots' => 1,
    'stats' => 
    [
      'pAtk' => 282,
      'mAtk' => 114,
      'critRate' => 8,
      'pAtkSpd' => 325,
    ],
  ],
  11964 => 
  [
    'id' => 11964,
    'type' => 'weapon',
    'name' => 'Common Item - Dark Legion\'s Edge',
    'add_name' => '',
    'description' => 'Dark Legion\'s Edge with limited enhancement options. Enchantment, soul storing and augmenting are impossible.',
    'icon' => 'weapon_dark_legions_edge_i00',
    'weapon_type' => 'sword',
    'bodypart' => 'rhand',
    'crystal_count' => 90,
    'crystal_type' => 'a',
    'weight' => 440,
    'price' => 1125000,
    'change_weaponId' => 11962,
    'soulshots' => 1,
    'spiritshots' => 1,
    'stats' => 
    [
      'pAtk' => 232,
      'mAtk' => 114,
      'critRate' => 8,
      'pAtkSpd' => 379,
    ],
  ],
  11965 => 
  [
    'id' => 11965,
    'type' => 'weapon',
    'name' => 'Common Item - Undertaker',
    'add_name' => '',
    'description' => 'Kamael Exclusive Weapon: Shadow Weapon - Dragon Slayer conversion. Undertaker with limited ability enhancement. Enchantment, special abilities and augmentation are not possible.',
    'icon' => 'weapon_death_bringer_i00',
    'weapon_type' => 'ancientsword',
    'bodypart' => 'lrhand',
    'crystal_count' => 90,
    'crystal_type' => 'a',
    'weight' => 613,
    'price' => 1125000,
    'change_weaponId' => 11968,
    'soulshots' => 1,
    'spiritshots' => 1,
    'stats' => 
    [
      'pAtk' => 251,
      'mAtk' => 114,
      'critRate' => 8,
      'pAtkSpd' => 350,
    ],
  ],
  11966 => 
  [
    'id' => 11966,
    'type' => 'weapon',
    'name' => 'Common Item - Doom Crusher',
    'add_name' => '',
    'description' => 'Doom Crusher with limited enhancement options. Enchantment, soul storing and augmenting are impossible.',
    'icon' => 'weapon_doom_crusher_i00',
    'weapon_type' => 'blunt',
    'bodypart' => 'lrhand',
    'crystal_count' => 90,
    'crystal_type' => 'a',
    'weight' => 633,
    'price' => 1125000,
    'soulshots' => 1,
    'spiritshots' => 1,
    'stats' => 
    [
      'pAtk' => 282,
      'mAtk' => 114,
      'critRate' => 4,
      'pAtkSpd' => 325,
    ],
  ],
  11967 => 
  [
    'id' => 11967,
    'type' => 'weapon',
    'name' => 'Common Item - Dragon Grinder',
    'add_name' => '',
    'description' => 'Dragon Grinder with limited enhancement options. Enchantment, soul storing and augmenting are impossible.',
    'icon' => 'weapon_dragon_grinder_i00',
    'weapon_type' => 'dualfist',
    'bodypart' => 'lrhand',
    'crystal_count' => 90,
    'crystal_type' => 'a',
    'weight' => 450,
    'price' => 1125000,
    'soulshots' => 1,
    'spiritshots' => 1,
    'stats' => 
    [
      'pAtk' => 282,
      'mAtk' => 114,
      'critRate' => 4,
      'pAtkSpd' => 325,
    ],
  ],
  11968 => 
  [
    'id' => 11968,
    'type' => 'weapon',
    'name' => 'Common Item - Dragon Slayer',
    'add_name' => '',
    'description' => 'Dragon Slayer with limited enhancement options. Enchantment, soul storing and augmenting are impossible.',
    'icon' => 'weapon_dragon_slayer_i00',
    'weapon_type' => 'sword',
    'bodypart' => 'lrhand',
    'crystal_count' => 90,
    'crystal_type' => 'a',
    'weight' => 613,
    'price' => 1125000,
    'change_weaponId' => 11965,
    'soulshots' => 1,
    'spiritshots' => 1,
    'stats' => 
    [
      'pAtk' => 282,
      'mAtk' => 114,
      'critRate' => 8,
      'pAtkSpd' => 325,
    ],
  ],
  11969 => 
  [
    'id' => 11969,
    'type' => 'weapon',
    'name' => 'Common Item - Flaming Dragon Skull',
    'add_name' => '',
    'description' => 'Flaming Dragon Skull with limited enhancement options. Enchantment, soul storing and augmenting are impossible.',
    'icon' => 'weapon_dragon_flame_head_i00',
    'weapon_type' => 'blunt',
    'bodypart' => 'rhand',
    'crystal_count' => 90,
    'crystal_type' => 'a',
    'weight' => 510,
    'price' => 1125000,
    'soulshots' => 1,
    'spiritshots' => 1,
    'is_magic_weapon' => true,
    'stats' => 
    [
      'pAtk' => 186,
      'mAtk' => 152,
      'critRate' => 4,
      'pAtkSpd' => 379,
    ],
  ],
  11970 => 
  [
    'id' => 11970,
    'type' => 'weapon',
    'name' => 'Common Item - Branch of the Mother Tree',
    'add_name' => '',
    'description' => 'Branch of Mother Tree with limited enhancement options. Enchantment, soul storing and augmenting are impossible.',
    'icon' => 'weapon_worldtrees_branch_i00',
    'weapon_type' => 'blunt',
    'bodypart' => 'lrhand',
    'crystal_count' => 90,
    'crystal_type' => 'a',
    'weight' => 300,
    'price' => 1125000,
    'soulshots' => 1,
    'spiritshots' => 1,
    'is_magic_weapon' => true,
    'stats' => 
    [
      'pAtk' => 226,
      'mAtk' => 167,
      'critRate' => 4,
      'pAtkSpd' => 325,
    ],
  ],
  11971 => 
  [
    'id' => 11971,
    'type' => 'weapon',
    'name' => 'Common Item - Sword of Miracles',
    'add_name' => '',
    'description' => 'Sword of Miracles with limited enhancement options. Enchantment, soul storing and augmenting are impossible.',
    'icon' => 'weapon_sword_of_miracle_i00',
    'weapon_type' => 'sword',
    'bodypart' => 'rhand',
    'crystal_count' => 90,
    'crystal_type' => 'a',
    'weight' => 280,
    'price' => 1125000,
    'soulshots' => 1,
    'spiritshots' => 1,
    'is_magic_weapon' => true,
    'stats' => 
    [
      'pAtk' => 186,
      'mAtk' => 152,
      'critRate' => 8,
      'pAtkSpd' => 379,
    ],
  ],
  11972 => 
  [
    'id' => 11972,
    'type' => 'weapon',
    'name' => 'Common Item - Reaper',
    'add_name' => '',
    'description' => 'Kamael Exclusive Weapon: Shadow weapon - Soul Bow conversion. Reaper with limited ability enhancement. Enchantment, special abilities and augmentation are not possible.',
    'icon' => 'weapon_soul_shooter_i00',
    'weapon_type' => 'crossbow',
    'bodypart' => 'lrhand',
    'crystal_count' => 90,
    'crystal_type' => 'a',
    'weight' => 553,
    'price' => 1125000,
    'change_weaponId' => 11975,
    'soulshots' => 1,
    'spiritshots' => 1,
    'stats' => 
    [
      'pAtk' => 294,
      'mAtk' => 114,
      'critRate' => 10,
      'pAtkSpd' => 303,
    ],
  ],
  11973 => 
  [
    'id' => 11973,
    'type' => 'weapon',
    'name' => 'Common Item - Soul Separator',
    'add_name' => '',
    'description' => 'Soul Separator with limited enhancement options. Enchantment, soul storing and augmenting are impossible.',
    'icon' => 'weapon_soul_separator_i00',
    'weapon_type' => 'dagger',
    'bodypart' => 'rhand',
    'crystal_count' => 90,
    'crystal_type' => 'a',
    'weight' => 317,
    'price' => 1125000,
    'soulshots' => 1,
    'spiritshots' => 1,
    'stats' => 
    [
      'pAtk' => 203,
      'mAtk' => 114,
      'critRate' => 12,
      'pAtkSpd' => 433,
    ],
  ],
  11974 => 
  [
    'id' => 11974,
    'type' => 'weapon',
    'name' => 'Common Item - Elysian',
    'add_name' => '',
    'description' => 'Elysian with limited enhancement options. Enchantment, soul storing and augmenting are impossible.',
    'icon' => 'weapon_elysian_i00',
    'weapon_type' => 'blunt',
    'bodypart' => 'rhand',
    'crystal_count' => 90,
    'crystal_type' => 'a',
    'weight' => 527,
    'price' => 1125000,
    'soulshots' => 1,
    'spiritshots' => 1,
    'stats' => 
    [
      'pAtk' => 232,
      'mAtk' => 114,
      'critRate' => 4,
      'pAtkSpd' => 379,
    ],
  ],
  11975 => 
  [
    'id' => 11975,
    'type' => 'weapon',
    'name' => 'Common Item - Soul Bow',
    'add_name' => '',
    'description' => 'Soul Bow with limited enhancement options. Enchantment, soul storing and augmenting are impossible.',
    'icon' => 'weapon_soul_bow_i00',
    'weapon_type' => 'bow',
    'bodypart' => 'lrhand',
    'crystal_count' => 90,
    'crystal_type' => 'a',
    'weight' => 553,
    'price' => 1125000,
    'change_weaponId' => 11972,
    'soulshots' => 2,
    'spiritshots' => 1,
    'mp_consume' => 5,
    'stats' => 
    [
      'pAtk' => 528,
      'mAtk' => 125,
      'critRate' => 12,
      'pAtkSpd' => 227,
    ],
  ],
  11976 => 
  [
    'id' => 11976,
    'type' => 'weapon',
    'name' => 'Common Item - Tallum Glaive',
    'add_name' => '',
    'description' => 'Tallum Glaive with limited enhancement options. Enchantment, soul storing and augmenting are impossible.',
    'icon' => 'weapon_tallum_glaive_i00',
    'weapon_type' => 'pole',
    'bodypart' => 'lrhand',
    'crystal_count' => 90,
    'crystal_type' => 'a',
    'weight' => 613,
    'price' => 1125000,
    'soulshots' => 1,
    'spiritshots' => 1,
    'item_skill' => 
    [
      0 => 
      [
        'skill_id' => 3599,
        'level' => 1,
      ],
    ],
    'stats' => 
    [
      'pAtk' => 232,
      'mAtk' => 114,
      'critRate' => 8,
      'pAtkSpd' => 325,
    ],
  ],
  11977 => 
  [
    'id' => 11977,
    'type' => 'weapon',
    'name' => 'Common Item - Naga Storm',
    'add_name' => '',
    'description' => 'Naga Storm with limited enhancement options. Enchantment, soul storing and augmenting are impossible.',
    'icon' => 'weapon_naga_storm_i00',
    'weapon_type' => 'dagger',
    'bodypart' => 'rhand',
    'crystal_count' => 103,
    'crystal_type' => 'a',
    'weight' => 310,
    'price' => 1292000,
    'soulshots' => 1,
    'spiritshots' => 1,
    'stats' => 
    [
      'pAtk' => 220,
      'mAtk' => 121,
      'critRate' => 12,
      'pAtkSpd' => 433,
    ],
  ],
  11978 => 
  [
    'id' => 11978,
    'type' => 'weapon',
    'name' => 'Common Item - Daimon Crystal',
    'add_name' => '',
    'description' => 'Daimon Crystal with limited enhancement options. Enchantment, soul storing and augmenting are impossible.',
    'icon' => 'weapon_crystal_of_deamon_i00',
    'weapon_type' => 'blunt',
    'bodypart' => 'lrhand',
    'crystal_count' => 103,
    'crystal_type' => 'a',
    'weight' => 293,
    'price' => 1292000,
    'soulshots' => 1,
    'spiritshots' => 1,
    'is_magic_weapon' => true,
    'stats' => 
    [
      'pAtk' => 245,
      'mAtk' => 177,
      'critRate' => 4,
      'pAtkSpd' => 325,
    ],
  ],
  11979 => 
  [
    'id' => 11979,
    'type' => 'weapon',
    'name' => 'Common Item - Barakiel\'s Axe',
    'add_name' => '',
    'description' => 'Barakiel\'s Axe with limited enhancement options. Enchantment, soul storing and augmenting are impossible.',
    'icon' => 'weapon_barakiel_axe_i00',
    'weapon_type' => 'blunt',
    'bodypart' => 'rhand',
    'crystal_count' => 103,
    'crystal_type' => 'a',
    'weight' => 517,
    'price' => 1292000,
    'soulshots' => 1,
    'spiritshots' => 1,
    'stats' => 
    [
      'pAtk' => 251,
      'mAtk' => 121,
      'critRate' => 4,
      'pAtkSpd' => 379,
    ],
  ],
  11980 => 
  [
    'id' => 11980,
    'type' => 'weapon',
    'name' => 'Common Item - Screaming Vengeance',
    'add_name' => '',
    'description' => 'Kamael Exclusive Weapon: Shadow weapon - Shyeed\'s Bow conversion. Screaming Vengeance with limited ability enhancement. Enchantment, special abilities and augmentation are not possible.',
    'icon' => 'weapon_soul_shooter_i00',
    'weapon_type' => 'crossbow',
    'bodypart' => 'lrhand',
    'crystal_count' => 103,
    'crystal_type' => 'a',
    'weight' => 547,
    'price' => 1292000,
    'change_weaponId' => 11983,
    'soulshots' => 1,
    'spiritshots' => 1,
    'stats' => 
    [
      'pAtk' => 318,
      'mAtk' => 121,
      'critRate' => 10,
      'pAtkSpd' => 303,
    ],
  ],
  11981 => 
  [
    'id' => 11981,
    'type' => 'weapon',
    'name' => 'Common Item - Behemoth\'s Tuning Fork',
    'add_name' => '',
    'description' => 'Behemoth\'s Tuning Fork with limited enhancement options. Enchantment, soul storing and augmenting are impossible.',
    'icon' => 'weapon_tuning_fork_of_behemoth_i00',
    'weapon_type' => 'blunt',
    'bodypart' => 'lrhand',
    'crystal_count' => 103,
    'crystal_type' => 'a',
    'weight' => 630,
    'price' => 1292000,
    'soulshots' => 1,
    'spiritshots' => 1,
    'stats' => 
    [
      'pAtk' => 305,
      'mAtk' => 121,
      'critRate' => 4,
      'pAtkSpd' => 325,
    ],
  ],
  11982 => 
  [
    'id' => 11982,
    'type' => 'weapon',
    'name' => 'Common Item - Durendal',
    'add_name' => '',
    'description' => 'Kamael Exclusive Weapon: Shadow weapon - Sword of Ipos conversion. Durendal with limited ability enhancement. Enchantment, special abilities and augmentation are not possible.',
    'icon' => 'weapon_death_bringer_i00',
    'weapon_type' => 'ancientsword',
    'bodypart' => 'lrhand',
    'crystal_count' => 103,
    'crystal_type' => 'a',
    'weight' => 607,
    'price' => 1292000,
    'change_weaponId' => 11984,
    'soulshots' => 1,
    'spiritshots' => 1,
    'stats' => 
    [
      'pAtk' => 272,
      'mAtk' => 121,
      'critRate' => 8,
      'pAtkSpd' => 350,
    ],
  ],
  11983 => 
  [
    'id' => 11983,
    'type' => 'weapon',
    'name' => 'Common Item - Shyeed\'s Bow',
    'add_name' => '',
    'description' => 'Shyeed\'s Bow with limited enhancement options. Enchantment, soul storing and augmenting are impossible.',
    'icon' => 'weapon_shyid_bow_i00',
    'weapon_type' => 'bow',
    'bodypart' => 'lrhand',
    'crystal_count' => 103,
    'crystal_type' => 'a',
    'weight' => 547,
    'price' => 1292000,
    'change_weaponId' => 11980,
    'soulshots' => 2,
    'spiritshots' => 1,
    'mp_consume' => 5,
    'stats' => 
    [
      'pAtk' => 570,
      'mAtk' => 133,
      'critRate' => 12,
      'pAtkSpd' => 227,
    ],
  ],
  11984 => 
  [
    'id' => 11984,
    'type' => 'weapon',
    'name' => 'Common Item - Sword of Ipos',
    'add_name' => '',
    'description' => 'Sword of Ipos with limited enhancement options. Enchantment, soul storing and augmenting are impossible.',
    'icon' => 'weapon_sword_of_ipos_i00',
    'weapon_type' => 'sword',
    'bodypart' => 'lrhand',
    'crystal_count' => 103,
    'crystal_type' => 'a',
    'weight' => 607,
    'price' => 1292000,
    'change_weaponId' => 11982,
    'soulshots' => 1,
    'spiritshots' => 1,
    'stats' => 
    [
      'pAtk' => 305,
      'mAtk' => 121,
      'critRate' => 8,
      'pAtkSpd' => 325,
    ],
  ],
  11985 => 
  [
    'id' => 11985,
    'type' => 'weapon',
    'name' => 'Common Item - Sobekk\'s Hurricane',
    'add_name' => '',
    'description' => 'Sobekk\'s Hurricane with limited enhancement options. Enchantment, soul storing and augmenting are impossible.',
    'icon' => 'weapon_sobekk_hurricane_i00',
    'weapon_type' => 'dualfist',
    'bodypart' => 'lrhand',
    'crystal_count' => 103,
    'crystal_type' => 'a',
    'weight' => 443,
    'price' => 1292000,
    'soulshots' => 1,
    'spiritshots' => 1,
    'stats' => 
    [
      'pAtk' => 305,
      'mAtk' => 121,
      'critRate' => 4,
      'pAtkSpd' => 325,
    ],
  ],
  11986 => 
  [
    'id' => 11986,
    'type' => 'weapon',
    'name' => 'Common Item - Sirra\'s Blade',
    'add_name' => '',
    'description' => 'Sirra\'s Blade with limited enhancement options. Enchantment, soul storing and augmenting are impossible.',
    'icon' => 'weapon_sirr_blade_i00',
    'weapon_type' => 'sword',
    'bodypart' => 'rhand',
    'crystal_count' => 103,
    'crystal_type' => 'a',
    'weight' => 433,
    'price' => 1292000,
    'change_weaponId' => 11987,
    'soulshots' => 1,
    'spiritshots' => 1,
    'stats' => 
    [
      'pAtk' => 251,
      'mAtk' => 121,
      'critRate' => 8,
      'pAtkSpd' => 379,
    ],
  ],
  11987 => 
  [
    'id' => 11987,
    'type' => 'weapon',
    'name' => 'Common Item - Éclair Bijou',
    'add_name' => '',
    'description' => 'Kamael Exclusive Weapon: Shadow weapon - Sirra\'s Blade conversion. Éclair Bijou with limited ability enhancement. Enchantment, special abilities and augmentation are not possible.',
    'icon' => 'weapon_greed_stinger_i00',
    'weapon_type' => 'rapier',
    'bodypart' => 'rhand',
    'crystal_count' => 103,
    'crystal_type' => 'a',
    'weight' => 433,
    'price' => 1292000,
    'change_weaponId' => 11986,
    'soulshots' => 1,
    'spiritshots' => 1,
    'stats' => 
    [
      'pAtk' => 228,
      'mAtk' => 121,
      'critRate' => 10,
      'pAtkSpd' => 406,
    ],
  ],
  11988 => 
  [
    'id' => 11988,
    'type' => 'weapon',
    'name' => 'Common Item - Tiphon\'s Spear',
    'add_name' => '',
    'description' => 'Tiphon\'s Spear with limited enhancement options. Enchantment, soul storing and augmenting are impossible.',
    'icon' => 'weapon_tiphon_spear_i00',
    'weapon_type' => 'pole',
    'bodypart' => 'lrhand',
    'crystal_count' => 103,
    'crystal_type' => 'a',
    'weight' => 607,
    'price' => 1292000,
    'soulshots' => 1,
    'spiritshots' => 1,
    'item_skill' => 
    [
      0 => 
      [
        'skill_id' => 3599,
        'level' => 1,
      ],
    ],
    'stats' => 
    [
      'pAtk' => 251,
      'mAtk' => 121,
      'critRate' => 8,
      'pAtkSpd' => 325,
    ],
  ],
  11989 => 
  [
    'id' => 11989,
    'type' => 'weapon',
    'name' => 'Common Item - Tallum Blade*Damascus',
    'add_name' => '',
    'description' => 'Tallum Blade*Damascus with limited enhancement options. Enchantment, soul storing and augmenting are impossible.',
    'icon' => 'weapon_dual_sword_i00',
    'weapon_type' => 'dual',
    'bodypart' => 'lrhand',
    'crystal_count' => 103,
    'crystal_type' => 'a',
    'weight' => 630,
    'price' => 1292000,
    'soulshots' => 1,
    'spiritshots' => 1,
    'stats' => 
    [
      'pAtk' => 305,
      'mAtk' => 121,
      'critRate' => 8,
      'pAtkSpd' => 325,
    ],
  ],
  11990 => 
  [
    'id' => 11990,
    'type' => 'weapon',
    'name' => 'Common Item - Themis\' Tongue',
    'add_name' => '',
    'description' => 'Themis\' Tongue with limited enhancement options. Enchantment, soul storing and augmenting are impossible.',
    'icon' => 'weapon_tongue_of_themis_i00',
    'weapon_type' => 'sword',
    'bodypart' => 'rhand',
    'crystal_count' => 103,
    'crystal_type' => 'a',
    'weight' => 273,
    'price' => 1292000,
    'soulshots' => 1,
    'spiritshots' => 1,
    'is_magic_weapon' => true,
    'stats' => 
    [
      'pAtk' => 202,
      'mAtk' => 162,
      'critRate' => 8,
      'pAtkSpd' => 379,
    ],
  ],
  11991 => 
  [
    'id' => 11991,
    'type' => 'weapon',
    'name' => 'Common Item - Cabrio\'s Hand',
    'add_name' => '',
    'description' => 'Cabrio\'s Hand with limited enhancement options. Enchantment, soul storing and augmenting are impossible.',
    'icon' => 'weapon_hand_of_cabrio_i00',
    'weapon_type' => 'blunt',
    'bodypart' => 'rhand',
    'crystal_count' => 103,
    'crystal_type' => 'a',
    'weight' => 503,
    'price' => 1292000,
    'soulshots' => 1,
    'spiritshots' => 1,
    'is_magic_weapon' => true,
    'stats' => 
    [
      'pAtk' => 202,
      'mAtk' => 162,
      'critRate' => 4,
      'pAtkSpd' => 379,
    ],
  ],
  11992 => 
  [
    'id' => 11992,
    'type' => 'weapon',
    'name' => 'Common Item - Gram',
    'add_name' => '',
    'description' => 'Gram with limited enhancement options. Enchantment, soul storing and augmenting are impossible.',
    'icon' => 'weapon_gram_i00',
    'weapon_type' => 'ancientsword',
    'bodypart' => 'lrhand',
    'crystal_count' => 174,
    'crystal_type' => 's',
    'weight' => 600,
    'price' => 3477000,
    'change_weaponId' => 12005,
    'soulshots' => 1,
    'spiritshots' => 1,
    'element_enabled' => true,
    'stats' => 
    [
      'pAtk' => 304,
      'mAtk' => 132,
      'critRate' => 8,
      'pAtkSpd' => 350,
    ],
  ],
  11993 => 
  [
    'id' => 11993,
    'type' => 'weapon',
    'name' => 'Common Item - Demon Splinter',
    'add_name' => '',
    'description' => 'Demon Splinter with limited enhancement options. Enchantment, soul storing and augmenting are impossible.',
    'icon' => 'weapon_demon_splinter_i00',
    'weapon_type' => 'dualfist',
    'bodypart' => 'lrhand',
    'crystal_count' => 174,
    'crystal_type' => 's',
    'weight' => 450,
    'price' => 3477000,
    'soulshots' => 1,
    'spiritshots' => 1,
    'element_enabled' => true,
    'stats' => 
    [
      'pAtk' => 342,
      'mAtk' => 132,
      'critRate' => 4,
      'pAtkSpd' => 325,
    ],
  ],
  11994 => 
  [
    'id' => 11994,
    'type' => 'weapon',
    'name' => 'Common Item - Draconic Bow',
    'add_name' => '',
    'description' => 'Draconic Bow with limited enhancement options. Enchantment, soul storing and augmenting are impossible.',
    'icon' => 'weapon_draconic_bow_i00',
    'weapon_type' => 'bow',
    'bodypart' => 'lrhand',
    'crystal_count' => 174,
    'crystal_type' => 's',
    'weight' => 550,
    'price' => 3477000,
    'change_weaponId' => 11998,
    'soulshots' => 1,
    'spiritshots' => 1,
    'mp_consume' => 6,
    'element_enabled' => true,
    'stats' => 
    [
      'pAtk' => 581,
      'mAtk' => 132,
      'critRate' => 12,
      'pAtkSpd' => 293,
    ],
  ],
  11995 => 
  [
    'id' => 11995,
    'type' => 'weapon',
    'name' => 'Common Item - Dragon Hunter Axe',
    'add_name' => '',
    'description' => 'Dragon Hunter Axe with limited enhancement options. Enchantment, soul storing and augmenting are impossible.',
    'icon' => 'weapon_dragon_hunter_axe_i00',
    'weapon_type' => 'blunt',
    'bodypart' => 'lrhand',
    'crystal_count' => 174,
    'crystal_type' => 's',
    'weight' => 607,
    'price' => 3477000,
    'soulshots' => 1,
    'spiritshots' => 1,
    'element_enabled' => true,
    'stats' => 
    [
      'pAtk' => 342,
      'mAtk' => 132,
      'critRate' => 4,
      'pAtkSpd' => 325,
    ],
  ],
  11996 => 
  [
    'id' => 11996,
    'type' => 'weapon',
    'name' => 'Common Item - Laevateinn',
    'add_name' => '',
    'description' => 'Laevateinn with limited enhancement options. Enchantment, soul storing and augmenting are impossible.',
    'icon' => 'weapon_leavatein_i00',
    'weapon_type' => 'rapier',
    'bodypart' => 'rhand',
    'crystal_count' => 174,
    'crystal_type' => 's',
    'weight' => 433,
    'price' => 3477000,
    'change_weaponId' => 12004,
    'soulshots' => 1,
    'spiritshots' => 1,
    'element_enabled' => true,
    'stats' => 
    [
      'pAtk' => 255,
      'mAtk' => 132,
      'critRate' => 10,
      'pAtkSpd' => 406,
    ],
  ],
  11997 => 
  [
    'id' => 11997,
    'type' => 'weapon',
    'name' => 'Common Item - Basalt Battlehammer',
    'add_name' => '',
    'description' => 'Basalt Battlehammer with limited enhancement options. Enchantment, soul storing and augmenting are impossible.',
    'icon' => 'weapon_basalt_battlehammer_i00',
    'weapon_type' => 'blunt',
    'bodypart' => 'rhand',
    'crystal_count' => 174,
    'crystal_type' => 's',
    'weight' => 523,
    'price' => 3477000,
    'soulshots' => 1,
    'spiritshots' => 1,
    'element_enabled' => true,
    'stats' => 
    [
      'pAtk' => 281,
      'mAtk' => 132,
      'critRate' => 4,
      'pAtkSpd' => 379,
    ],
  ],
  11998 => 
  [
    'id' => 11998,
    'type' => 'weapon',
    'name' => 'Common Item - Sarunga',
    'add_name' => '',
    'description' => 'Sarunga with limited enhancement options. Enchantment, soul storing and augmenting are impossible.',
    'icon' => 'weapon_sarnga_i00',
    'weapon_type' => 'crossbow',
    'bodypart' => 'lrhand',
    'crystal_count' => 174,
    'crystal_type' => 's',
    'weight' => 533,
    'price' => 3477000,
    'change_weaponId' => 11994,
    'soulshots' => 1,
    'spiritshots' => 1,
    'element_enabled' => true,
    'stats' => 
    [
      'pAtk' => 356,
      'mAtk' => 132,
      'critRate' => 10,
      'pAtkSpd' => 303,
    ],
  ],
  11999 => 
  [
    'id' => 11999,
    'type' => 'weapon',
    'name' => 'Common Item - Saint Spear',
    'add_name' => '',
    'description' => 'Saint Spear with limited enhancement options. Enchantment, soul storing and augmenting are impossible.',
    'icon' => 'weapon_saint_spear_i00',
    'weapon_type' => 'pole',
    'bodypart' => 'lrhand',
    'crystal_count' => 174,
    'crystal_type' => 's',
    'weight' => 600,
    'price' => 3477000,
    'soulshots' => 1,
    'spiritshots' => 1,
    'element_enabled' => true,
    'item_skill' => 
    [
      0 => 
      [
        'skill_id' => 3599,
        'level' => 1,
      ],
    ],
    'stats' => 
    [
      'pAtk' => 281,
      'mAtk' => 132,
      'critRate' => 8,
      'pAtkSpd' => 325,
    ],
  ],
];