<?php
return [
  12400 => 
  [
    'id' => 12400,
    'type' => 'etcitem',
    'name' => 'Foundation Kaim Vanul\'s Bones',
    'add_name' => '',
    'description' => 'A rare Kaim Vanul\'s Bones that requires a thorough varnishing. It can be varnished by the Blacksmith of Mammon.',
    'icon' => 'weapon_bone_of_kaim_vanul_i00',
    'weapon_type' => 'blunt',
    'crystal_type' => 'b',
    'weight' => 1570,
    'price' => 10091400,
    'soulshots' => 1,
    'spiritshots' => 1,
    'stats' => 
    [
      'pAtk' => 194,
      'mAtk' => 99,
      'critRate' => 4,
      'pAtkSpd' => 379,
    ],
  ],
  12401 => 
  [
    'id' => 12401,
    'type' => 'etcitem',
    'name' => 'Foundation Colichemarde',
    'add_name' => '',
    'description' => 'A rare Colichemarde that requires a thorough varnishing. It can be varnished by the Blacksmith of Mammon.',
    'icon' => 'weapon_colichemarde_i00',
    'weapon_type' => 'rapier',
    'crystal_type' => 'b',
    'weight' => 1350,
    'price' => 10091400,
    'soulshots' => 1,
    'spiritshots' => 1,
    'stats' => 
    [
      'pAtk' => 176,
      'mAtk' => 99,
      'critRate' => 10,
      'pAtkSpd' => 406,
    ],
  ],
  12402 => 
  [
    'id' => 12402,
    'type' => 'etcitem',
    'name' => 'Foundation Wizard\'s Tear',
    'add_name' => '',
    'description' => 'A rare Wizard\'s Tear that requires a thorough varnishing. It can be varnished by the Blacksmith of Mammon.',
    'icon' => 'weapon_tears_of_wizard_i00',
    'weapon_type' => 'sword',
    'crystal_type' => 'b',
    'weight' => 1350,
    'price' => 10091400,
    'soulshots' => 1,
    'spiritshots' => 1,
    'stats' => 
    [
      'pAtk' => 194,
      'mAtk' => 99,
      'critRate' => 8,
      'pAtkSpd' => 379,
    ],
  ],
  12403 => 
  [
    'id' => 12403,
    'type' => 'etcitem',
    'name' => 'Foundation Bow of Peril',
    'add_name' => '',
    'description' => 'A rare Bow of Peril that requires a thorough varnishing. It can be varnished by the Blacksmith of Mammon.',
    'icon' => 'weapon_hazard_bow_i00',
    'weapon_type' => 'bow',
    'crystal_type' => 'b',
    'weight' => 1700,
    'price' => 10091400,
    'soulshots' => 3,
    'spiritshots' => 1,
    'mp_consume' => 4,
    'stats' => 
    [
      'pAtk' => 400,
      'mAtk' => 99,
      'critRate' => 12,
      'pAtkSpd' => 293,
    ],
  ],
  12404 => 
  [
    'id' => 12404,
    'type' => 'etcitem',
    'name' => 'Foundation Hell Hound',
    'add_name' => '',
    'description' => 'A rare Hell Hound that requires a thorough varnishing. It can be varnished by the Blacksmith of Mammon.',
    'icon' => 'weapon_hell_hound_i00',
    'weapon_type' => 'crossbow',
    'crystal_type' => 'b',
    'weight' => 1700,
    'price' => 10091400,
    'soulshots' => 1,
    'spiritshots' => 1,
    'stats' => 
    [
      'pAtk' => 245,
      'mAtk' => 99,
      'critRate' => 10,
      'pAtkSpd' => 303,
    ],
  ],
  12405 => 
  [
    'id' => 12405,
    'type' => 'etcitem',
    'name' => 'Foundation Dasparion\'s Staff',
    'add_name' => '',
    'description' => 'A rare Dasparion\'s Staff that requires a thorough varnishing. It can be varnished by the Blacksmith of Mammon.',
    'icon' => 'weapon_dasparions_staff_i00',
    'weapon_type' => 'blunt',
    'crystal_type' => 'a',
    'weight' => 920,
    'price' => 14098000,
    'soulshots' => 1,
    'spiritshots' => 1,
    'stats' => 
    [
      'pAtk' => 213,
      'mAtk' => 107,
      'critRate' => 4,
      'pAtkSpd' => 379,
    ],
  ],
  12406 => 
  [
    'id' => 12406,
    'type' => 'etcitem',
    'name' => 'Foundation Doomchanter',
    'add_name' => '',
    'description' => 'A rare Doomchanter that requires a thorough varnishing. It can be varnished by the Blacksmith of Mammon.',
    'icon' => 'weapon_doom_singer_i00',
    'weapon_type' => 'crossbow',
    'crystal_type' => 'a',
    'weight' => 1670,
    'price' => 14098000,
    'soulshots' => 1,
    'spiritshots' => 1,
    'stats' => 
    [
      'pAtk' => 270,
      'mAtk' => 107,
      'critRate' => 10,
      'pAtkSpd' => 303,
    ],
  ],
  12407 => 
  [
    'id' => 12407,
    'type' => 'etcitem',
    'name' => 'Foundation White Lightning',
    'add_name' => '',
    'description' => 'A rare White Lightning that requires a thorough varnishing. It can be varnished by the Blacksmith of Mammon.',
    'icon' => 'weapon_lightning_blaze_i00',
    'weapon_type' => 'rapier',
    'crystal_type' => 'a',
    'weight' => 1330,
    'price' => 14098000,
    'soulshots' => 1,
    'spiritshots' => 1,
    'stats' => 
    [
      'pAtk' => 193,
      'mAtk' => 107,
      'critRate' => 10,
      'pAtkSpd' => 406,
    ],
  ],
  12408 => 
  [
    'id' => 12408,
    'type' => 'etcitem',
    'name' => 'Foundation Meteor Shower',
    'add_name' => '',
    'description' => 'A rare Meteor Shower that requires a thorough varnishing. It can be varnished by the Blacksmith of Mammon.',
    'icon' => 'weapon_meteor_shower_i00',
    'weapon_type' => 'blunt',
    'crystal_type' => 'a',
    'weight' => 1600,
    'price' => 14098000,
    'soulshots' => 1,
    'spiritshots' => 1,
    'stats' => 
    [
      'pAtk' => 213,
      'mAtk' => 107,
      'critRate' => 4,
      'pAtkSpd' => 379,
    ],
  ],
  12409 => 
  [
    'id' => 12409,
    'type' => 'etcitem',
    'name' => 'Foundation Blood Tornado',
    'add_name' => '',
    'description' => 'A rare Blood Tornado that requires a thorough varnishing. It can be varnished by the Blacksmith of Mammon.',
    'icon' => 'weapon_blood_tornado_i00',
    'weapon_type' => 'dualfist',
    'crystal_type' => 'a',
    'weight' => 1370,
    'price' => 14098000,
    'soulshots' => 1,
    'spiritshots' => 1,
    'stats' => 
    [
      'pAtk' => 213,
      'mAtk' => 107,
      'critRate' => 4,
      'pAtkSpd' => 325,
    ],
  ],
  12410 => 
  [
    'id' => 12410,
    'type' => 'etcitem',
    'name' => 'Foundation Bloody Orchid',
    'add_name' => '',
    'description' => 'A rare Bloody Orchid that requires a thorough varnishing. It can be varnished by the Blacksmith of Mammon.',
    'icon' => 'weapon_bloody_orchid_i00',
    'weapon_type' => 'dagger',
    'crystal_type' => 'a',
    'weight' => 960,
    'price' => 14098000,
    'soulshots' => 1,
    'spiritshots' => 1,
    'stats' => 
    [
      'pAtk' => 186,
      'mAtk' => 107,
      'critRate' => 12,
      'pAtkSpd' => 433,
    ],
  ],
  12411 => 
  [
    'id' => 12411,
    'type' => 'etcitem',
    'name' => 'Foundation Elemental Sword',
    'add_name' => '',
    'description' => 'A rare Elemental Sword that requires a thorough varnishing. It can be varnished by the Blacksmith of Mammon.',
    'icon' => 'weapon_elemental_sword_i00',
    'weapon_type' => 'sword',
    'crystal_type' => 'a',
    'weight' => 830,
    'price' => 14098000,
    'soulshots' => 1,
    'spiritshots' => 1,
    'stats' => 
    [
      'pAtk' => 213,
      'mAtk' => 107,
      'critRate' => 8,
      'pAtkSpd' => 379,
    ],
  ],
  12412 => 
  [
    'id' => 12412,
    'type' => 'etcitem',
    'name' => 'Foundation Spiritual Eye',
    'add_name' => '',
    'description' => 'A rare Spiritual Eye that requires a thorough varnishing. It can be varnished by the Blacksmith of Mammon.',
    'icon' => 'weapon_eye_of_soul_i00',
    'weapon_type' => 'blunt',
    'crystal_type' => 'a',
    'weight' => 1550,
    'price' => 14098000,
    'soulshots' => 1,
    'spiritshots' => 1,
    'stats' => 
    [
      'pAtk' => 213,
      'mAtk' => 107,
      'critRate' => 4,
      'pAtkSpd' => 379,
    ],
  ],
  12413 => 
  [
    'id' => 12413,
    'type' => 'etcitem',
    'name' => 'Foundation Infernal Master',
    'add_name' => '',
    'description' => 'A rare Infernal Master that requires a thorough varnishing. It can be varnished by the Blacksmith of Mammon.',
    'icon' => 'weapon_inferno_master_i00',
    'weapon_type' => 'sword',
    'crystal_type' => 'a',
    'weight' => 1900,
    'price' => 14098000,
    'soulshots' => 1,
    'spiritshots' => 1,
    'stats' => 
    [
      'pAtk' => 213,
      'mAtk' => 107,
      'critRate' => 8,
      'pAtkSpd' => 379,
    ],
  ],
  12414 => 
  [
    'id' => 12414,
    'type' => 'etcitem',
    'name' => 'Foundation Carnage Bow',
    'add_name' => '',
    'description' => 'A rare Carnage Bow that requires a thorough varnishing. It can be varnished by the Blacksmith of Mammon.',
    'icon' => 'weapon_carnium_bow_i00',
    'weapon_type' => 'bow',
    'crystal_type' => 'a',
    'weight' => 1670,
    'price' => 14098000,
    'soulshots' => 2,
    'spiritshots' => 1,
    'mp_consume' => 4,
    'stats' => 
    [
      'pAtk' => 440,
      'mAtk' => 107,
      'critRate' => 12,
      'pAtkSpd' => 293,
    ],
  ],
  12415 => 
  [
    'id' => 12415,
    'type' => 'etcitem',
    'name' => 'Foundation Tallum Blade',
    'add_name' => '',
    'description' => 'A rare Tallum Blade that requires a thorough varnishing. It can be varnished by the Blacksmith of Mammon.',
    'icon' => 'weapon_tallum_blade_i00',
    'weapon_type' => 'sword',
    'crystal_type' => 'a',
    'weight' => 1330,
    'price' => 14098000,
    'soulshots' => 1,
    'spiritshots' => 1,
    'stats' => 
    [
      'pAtk' => 213,
      'mAtk' => 107,
      'critRate' => 8,
      'pAtkSpd' => 379,
    ],
  ],
  12416 => 
  [
    'id' => 12416,
    'type' => 'etcitem',
    'name' => 'Foundation Destroyer Hammer',
    'add_name' => '',
    'description' => 'A rare Destroyer Hammer that requires a thorough varnishing. It can be varnished by the Blacksmith of Mammon.',
    'icon' => 'weapon_hammer_of_destroyer_i00',
    'weapon_type' => 'blunt',
    'crystal_type' => 'a',
    'weight' => 1910,
    'price' => 14098000,
    'soulshots' => 1,
    'spiritshots' => 1,
    'stats' => 
    [
      'pAtk' => 213,
      'mAtk' => 107,
      'critRate' => 4,
      'pAtkSpd' => 379,
    ],
  ],
  12417 => 
  [
    'id' => 12417,
    'type' => 'etcitem',
    'name' => 'Foundation Divine Pain',
    'add_name' => '',
    'description' => 'A rare Divine Pain that requires a thorough varnishing. It can be varnished by the Blacksmith of Mammon.',
    'icon' => 'weapon_pain_of_godness_i00',
    'weapon_type' => 'ancientsword',
    'crystal_type' => 'a',
    'weight' => 1900,
    'price' => 14098000,
    'soulshots' => 1,
    'spiritshots' => 1,
    'stats' => 
    [
      'pAtk' => 231,
      'mAtk' => 107,
      'critRate' => 8,
      'pAtkSpd' => 350,
    ],
  ],
  12418 => 
  [
    'id' => 12418,
    'type' => 'etcitem',
    'name' => 'Foundation Halberd',
    'add_name' => '',
    'description' => 'A rare Halberd that requires a thorough varnishing. It can be varnished by the Blacksmith of Mammon.',
    'icon' => 'weapon_halbard_i00',
    'weapon_type' => 'pole',
    'crystal_type' => 'a',
    'weight' => 1900,
    'price' => 14098000,
    'soulshots' => 1,
    'spiritshots' => 1,
    'stats' => 
    [
      'pAtk' => 213,
      'mAtk' => 107,
      'critRate' => 8,
      'pAtkSpd' => 325,
    ],
  ],
  12419 => 
  [
    'id' => 12419,
    'type' => 'etcitem',
    'name' => 'Foundation Lacerator',
    'add_name' => '',
    'description' => 'A rare Lacerator that requires a thorough varnishing. It can be varnished by the Blacksmith of Mammon.',
    'icon' => 'weapon_greed_stinger_i00',
    'weapon_type' => 'rapier',
    'crystal_type' => 'a',
    'weight' => 1320,
    'price' => 20741000,
    'soulshots' => 1,
    'spiritshots' => 1,
    'stats' => 
    [
      'pAtk' => 210,
      'mAtk' => 114,
      'critRate' => 10,
      'pAtkSpd' => 406,
    ],
  ],
  12420 => 
  [
    'id' => 12420,
    'type' => 'etcitem',
    'name' => 'Foundation Dark Legion\'s Edge',
    'add_name' => '',
    'description' => 'A rare Dark Legion\'s Edge that requires a thorough varnishing. It can be varnished by the Blacksmith of Mammon.',
    'icon' => 'weapon_dark_legions_edge_i00',
    'weapon_type' => 'sword',
    'crystal_type' => 'a',
    'weight' => 1320,
    'price' => 20741000,
    'soulshots' => 1,
    'spiritshots' => 1,
    'stats' => 
    [
      'pAtk' => 232,
      'mAtk' => 114,
      'critRate' => 8,
      'pAtkSpd' => 379,
    ],
  ],
  12421 => 
  [
    'id' => 12421,
    'type' => 'etcitem',
    'name' => 'Foundation Undertaker',
    'add_name' => '',
    'description' => 'A rare Undertaker that requires a thorough varnishing. It can be varnished by the Blacksmith of Mammon.',
    'icon' => 'weapon_death_bringer_i00',
    'weapon_type' => 'ancientsword',
    'crystal_type' => 'a',
    'weight' => 1840,
    'price' => 20741000,
    'soulshots' => 1,
    'spiritshots' => 1,
    'stats' => 
    [
      'pAtk' => 251,
      'mAtk' => 114,
      'critRate' => 8,
      'pAtkSpd' => 350,
    ],
  ],
  12422 => 
  [
    'id' => 12422,
    'type' => 'etcitem',
    'name' => 'Foundation Doom Crusher',
    'add_name' => '',
    'description' => 'A rare Doom Crusher that requires a thorough varnishing. It can be varnished by the Blacksmith of Mammon.',
    'icon' => 'weapon_doom_crusher_i00',
    'weapon_type' => 'blunt',
    'crystal_type' => 'a',
    'weight' => 1900,
    'price' => 20741000,
    'soulshots' => 1,
    'spiritshots' => 1,
    'stats' => 
    [
      'pAtk' => 232,
      'mAtk' => 114,
      'critRate' => 4,
      'pAtkSpd' => 379,
    ],
  ],
  12423 => 
  [
    'id' => 12423,
    'type' => 'etcitem',
    'name' => 'Foundation Dragon Grinder',
    'add_name' => '',
    'description' => 'A rare Dragon Grinder that requires a thorough varnishing. It can be varnished by the Blacksmith of Mammon.',
    'icon' => 'weapon_dragon_grinder_i00',
    'weapon_type' => 'dualfist',
    'crystal_type' => 'a',
    'weight' => 1350,
    'price' => 20741000,
    'soulshots' => 1,
    'spiritshots' => 1,
    'stats' => 
    [
      'pAtk' => 232,
      'mAtk' => 114,
      'critRate' => 4,
      'pAtkSpd' => 325,
    ],
  ],
  12424 => 
  [
    'id' => 12424,
    'type' => 'etcitem',
    'name' => 'Foundation Dragon Slayer',
    'add_name' => '',
    'description' => 'A rare Dragon Slayer that requires a thorough varnishing. It can be varnished by the Blacksmith of Mammon.',
    'icon' => 'weapon_dragon_slayer_i00',
    'weapon_type' => 'sword',
    'crystal_type' => 'a',
    'weight' => 1840,
    'price' => 20741000,
    'soulshots' => 1,
    'spiritshots' => 1,
    'stats' => 
    [
      'pAtk' => 232,
      'mAtk' => 114,
      'critRate' => 8,
      'pAtkSpd' => 379,
    ],
  ],
  12425 => 
  [
    'id' => 12425,
    'type' => 'etcitem',
    'name' => 'Foundation Flaming Dragon Skull',
    'add_name' => '',
    'description' => 'A rare Flaming Dragon Skull that requires a thorough varnishing. It can be varnished by the Blacksmith of Mammon.',
    'icon' => 'weapon_dragon_flame_head_i00',
    'weapon_type' => 'blunt',
    'crystal_type' => 'a',
    'weight' => 1530,
    'price' => 20741000,
    'soulshots' => 1,
    'spiritshots' => 1,
    'stats' => 
    [
      'pAtk' => 232,
      'mAtk' => 114,
      'critRate' => 4,
      'pAtkSpd' => 379,
    ],
  ],
  12426 => 
  [
    'id' => 12426,
    'type' => 'etcitem',
    'name' => 'Foundation Branch of the Mother Tree',
    'add_name' => '',
    'description' => 'A rare Branch of the Mother Tree that requires a thorough varnishing. It can be varnished by the Blacksmith of Mammon.',
    'icon' => 'weapon_worldtrees_branch_i00',
    'weapon_type' => 'blunt',
    'crystal_type' => 'a',
    'weight' => 900,
    'price' => 20741000,
    'soulshots' => 1,
    'spiritshots' => 1,
    'stats' => 
    [
      'pAtk' => 232,
      'mAtk' => 114,
      'critRate' => 4,
      'pAtkSpd' => 379,
    ],
  ],
  12427 => 
  [
    'id' => 12427,
    'type' => 'etcitem',
    'name' => 'Foundation Sword of Miracles',
    'add_name' => '',
    'description' => 'A rare Sword of Miracles that requires a thorough varnishing. It can be varnished by the Blacksmith of Mammon.',
    'icon' => 'weapon_sword_of_miracle_i00',
    'weapon_type' => 'sword',
    'crystal_type' => 'a',
    'weight' => 840,
    'price' => 20741000,
    'soulshots' => 1,
    'spiritshots' => 1,
    'stats' => 
    [
      'pAtk' => 232,
      'mAtk' => 114,
      'critRate' => 8,
      'pAtkSpd' => 379,
    ],
  ],
  12428 => 
  [
    'id' => 12428,
    'type' => 'etcitem',
    'name' => 'Foundation Reaper',
    'add_name' => '',
    'description' => 'A rare Reaper that requires a thorough varnishing. It can be varnished by the Blacksmith of Mammon.',
    'icon' => 'weapon_soul_shooter_i00',
    'weapon_type' => 'crossbow',
    'crystal_type' => 'a',
    'weight' => 1660,
    'price' => 20741000,
    'soulshots' => 1,
    'spiritshots' => 1,
    'stats' => 
    [
      'pAtk' => 294,
      'mAtk' => 114,
      'critRate' => 10,
      'pAtkSpd' => 303,
    ],
  ],
  12429 => 
  [
    'id' => 12429,
    'type' => 'etcitem',
    'name' => 'Foundation Soul Separator',
    'add_name' => '',
    'description' => 'A rare Soul Separator that requires a thorough varnishing. It can be varnished by the Blacksmith of Mammon.',
    'icon' => 'weapon_soul_separator_i00',
    'weapon_type' => 'dagger',
    'crystal_type' => 'a',
    'weight' => 950,
    'price' => 20741000,
    'soulshots' => 1,
    'spiritshots' => 1,
    'stats' => 
    [
      'pAtk' => 203,
      'mAtk' => 114,
      'critRate' => 12,
      'pAtkSpd' => 433,
    ],
  ],
  12430 => 
  [
    'id' => 12430,
    'type' => 'etcitem',
    'name' => 'Foundation Elysian',
    'add_name' => '',
    'description' => 'A rare Elysian that requires a thorough varnishing. It can be varnished by the Blacksmith of Mammon.',
    'icon' => 'weapon_elysian_i00',
    'weapon_type' => 'blunt',
    'crystal_type' => 'a',
    'weight' => 1580,
    'price' => 20741000,
    'soulshots' => 1,
    'spiritshots' => 1,
    'stats' => 
    [
      'pAtk' => 232,
      'mAtk' => 114,
      'critRate' => 4,
      'pAtkSpd' => 379,
    ],
  ],
  12431 => 
  [
    'id' => 12431,
    'type' => 'etcitem',
    'name' => 'Foundation Soul Bow',
    'add_name' => '',
    'description' => 'A rare Soul Bow that requires a thorough varnishing. It can be varnished by the Blacksmith of Mammon.',
    'icon' => 'weapon_soul_bow_i00',
    'weapon_type' => 'bow',
    'crystal_type' => 'a',
    'weight' => 1660,
    'price' => 20741000,
    'soulshots' => 2,
    'spiritshots' => 1,
    'mp_consume' => 5,
    'stats' => 
    [
      'pAtk' => 528,
      'mAtk' => 125,
      'critRate' => 12,
      'pAtkSpd' => 227,
    ],
  ],
  12432 => 
  [
    'id' => 12432,
    'type' => 'etcitem',
    'name' => 'Foundation Tallum Glaive',
    'add_name' => '',
    'description' => 'A rare Tallum Glaive that requires a thorough varnishing. It can be varnished by the Blacksmith of Mammon.',
    'icon' => 'weapon_tallum_glaive_i00',
    'weapon_type' => 'pole',
    'crystal_type' => 'a',
    'weight' => 1840,
    'price' => 20741000,
    'soulshots' => 1,
    'spiritshots' => 1,
    'stats' => 
    [
      'pAtk' => 232,
      'mAtk' => 114,
      'critRate' => 8,
      'pAtkSpd' => 325,
    ],
  ],
  12433 => 
  [
    'id' => 12433,
    'type' => 'etcitem',
    'name' => 'Foundation Naga Storm',
    'add_name' => '',
    'description' => 'A rare Naga Storm that requires a thorough varnishing. It can be varnished by the Blacksmith of Mammon.',
    'icon' => 'weapon_naga_storm_i00',
    'weapon_type' => 'dagger',
    'crystal_type' => 'a',
    'weight' => 930,
    'price' => 26968400,
    'soulshots' => 1,
    'spiritshots' => 1,
    'stats' => 
    [
      'pAtk' => 220,
      'mAtk' => 121,
      'critRate' => 12,
      'pAtkSpd' => 433,
    ],
  ],
  12434 => 
  [
    'id' => 12434,
    'type' => 'etcitem',
    'name' => 'Foundation Daimon Crystal',
    'add_name' => '',
    'description' => 'A rare Daimon Crystal that requires a thorough varnishing. It can be varnished by the Blacksmith of Mammon.',
    'icon' => 'weapon_crystal_of_deamon_i00',
    'weapon_type' => 'blunt',
    'crystal_type' => 'a',
    'weight' => 880,
    'price' => 26968400,
    'soulshots' => 1,
    'spiritshots' => 1,
    'stats' => 
    [
      'pAtk' => 251,
      'mAtk' => 121,
      'critRate' => 4,
      'pAtkSpd' => 379,
    ],
  ],
  12435 => 
  [
    'id' => 12435,
    'type' => 'etcitem',
    'name' => 'Foundation Barakiel\'s Axe',
    'add_name' => '',
    'description' => 'A rare Barakiel\'s Axe that requires a thorough varnishing. It can be varnished by the Blacksmith of Mammon.',
    'icon' => 'weapon_barakiel_axe_i00',
    'weapon_type' => 'blunt',
    'crystal_type' => 'a',
    'weight' => 1550,
    'price' => 26968400,
    'soulshots' => 1,
    'spiritshots' => 1,
    'stats' => 
    [
      'pAtk' => 251,
      'mAtk' => 121,
      'critRate' => 4,
      'pAtkSpd' => 379,
    ],
  ],
  12436 => 
  [
    'id' => 12436,
    'type' => 'etcitem',
    'name' => 'Foundation Screaming Vengeance',
    'add_name' => '',
    'description' => 'A rare Screaming Vengeance that requires a thorough varnishing. It can be varnished by the Blacksmith of Mammon.',
    'icon' => 'weapon_soul_shooter_i00',
    'weapon_type' => 'crossbow',
    'crystal_type' => 'a',
    'weight' => 1640,
    'price' => 26968400,
    'soulshots' => 1,
    'spiritshots' => 1,
    'stats' => 
    [
      'pAtk' => 318,
      'mAtk' => 121,
      'critRate' => 10,
      'pAtkSpd' => 303,
    ],
  ],
  12437 => 
  [
    'id' => 12437,
    'type' => 'etcitem',
    'name' => 'Foundation Behemoth\'s Tuning Fork',
    'add_name' => '',
    'description' => 'A rare Behemoth\'s Tuning Fork that requires a thorough varnishing. It can be varnished by the Blacksmith of Mammon.',
    'icon' => 'weapon_tuning_fork_of_behemoth_i00',
    'weapon_type' => 'blunt',
    'crystal_type' => 'a',
    'weight' => 1890,
    'price' => 26968400,
    'soulshots' => 1,
    'spiritshots' => 1,
    'stats' => 
    [
      'pAtk' => 251,
      'mAtk' => 121,
      'critRate' => 4,
      'pAtkSpd' => 379,
    ],
  ],
  12438 => 
  [
    'id' => 12438,
    'type' => 'etcitem',
    'name' => 'Foundation Durendal',
    'add_name' => '',
    'description' => 'A rare Durendal that requires a thorough varnishing. It can be varnished by the Blacksmith of Mammon.',
    'icon' => 'weapon_death_bringer_i00',
    'weapon_type' => 'ancientsword',
    'crystal_type' => 'a',
    'weight' => 1820,
    'price' => 26968400,
    'soulshots' => 1,
    'spiritshots' => 1,
    'stats' => 
    [
      'pAtk' => 272,
      'mAtk' => 121,
      'critRate' => 8,
      'pAtkSpd' => 350,
    ],
  ],
  12439 => 
  [
    'id' => 12439,
    'type' => 'etcitem',
    'name' => 'Foundation Shyeed\'s Bow',
    'add_name' => '',
    'description' => 'A rare Shyeed\'s Bow that requires a thorough varnishing. It can be varnished by the Blacksmith of Mammon.',
    'icon' => 'weapon_shyid_bow_i00',
    'weapon_type' => 'bow',
    'crystal_type' => 'a',
    'weight' => 1640,
    'price' => 26968400,
    'soulshots' => 1,
    'spiritshots' => 1,
    'mp_consume' => 5,
    'stats' => 
    [
      'pAtk' => 571,
      'mAtk' => 133,
      'critRate' => 12,
      'pAtkSpd' => 227,
    ],
  ],
  12440 => 
  [
    'id' => 12440,
    'type' => 'etcitem',
    'name' => 'Foundation Sword of Ipos',
    'add_name' => '',
    'description' => 'A rare Sword of Ipos that requires a thorough varnishing. It can be varnished by the Blacksmith of Mammon.',
    'icon' => 'weapon_sword_of_ipos_i00',
    'weapon_type' => 'sword',
    'crystal_type' => 'a',
    'weight' => 1820,
    'price' => 26968400,
    'soulshots' => 1,
    'spiritshots' => 1,
    'stats' => 
    [
      'pAtk' => 251,
      'mAtk' => 121,
      'critRate' => 8,
      'pAtkSpd' => 379,
    ],
  ],
  12441 => 
  [
    'id' => 12441,
    'type' => 'etcitem',
    'name' => 'Foundation Sobekk\'s Hurricane',
    'add_name' => '',
    'description' => 'A rare Sobekk\'s Hurricane that requires a thorough varnishing. It can be varnished by the Blacksmith of Mammon.',
    'icon' => 'weapon_sobekk_hurricane_i00',
    'weapon_type' => 'dualfist',
    'crystal_type' => 'a',
    'weight' => 1330,
    'price' => 26968400,
    'soulshots' => 1,
    'spiritshots' => 1,
    'stats' => 
    [
      'pAtk' => 251,
      'mAtk' => 121,
      'critRate' => 4,
      'pAtkSpd' => 325,
    ],
  ],
  12442 => 
  [
    'id' => 12442,
    'type' => 'etcitem',
    'name' => 'Foundation Sirra\'s Blade',
    'add_name' => '',
    'description' => 'A rare Sirra\'s Blade that requires a thorough varnishing. It can be varnished by the Blacksmith of Mammon.',
    'icon' => 'weapon_sirr_blade_i00',
    'weapon_type' => 'sword',
    'crystal_type' => 'a',
    'weight' => 1300,
    'price' => 26968400,
    'soulshots' => 1,
    'spiritshots' => 1,
    'stats' => 
    [
      'pAtk' => 251,
      'mAtk' => 121,
      'critRate' => 8,
      'pAtkSpd' => 379,
    ],
  ],
  12443 => 
  [
    'id' => 12443,
    'type' => 'etcitem',
    'name' => 'Foundation Éclair Bijou',
    'add_name' => '',
    'description' => 'A rare Eclair Bijou that requires a thorough varnishing. It can be varnished by the Blacksmith of Mammon.',
    'icon' => 'weapon_greed_stinger_i00',
    'weapon_type' => 'rapier',
    'crystal_type' => 'a',
    'weight' => 1300,
    'price' => 26968400,
    'soulshots' => 1,
    'spiritshots' => 1,
    'stats' => 
    [
      'pAtk' => 228,
      'mAtk' => 121,
      'critRate' => 10,
      'pAtkSpd' => 406,
    ],
  ],
  12444 => 
  [
    'id' => 12444,
    'type' => 'etcitem',
    'name' => 'Foundation Tiphon\'s Spear',
    'add_name' => '',
    'description' => 'A rare Tiphon\'s Spear that requires a thorough varnishing. It can be varnished by the Blacksmith of Mammon.',
    'icon' => 'weapon_tiphon_spear_i00',
    'weapon_type' => 'pole',
    'crystal_type' => 'a',
    'weight' => 1820,
    'price' => 26968400,
    'soulshots' => 1,
    'spiritshots' => 1,
    'stats' => 
    [
      'pAtk' => 251,
      'mAtk' => 121,
      'critRate' => 8,
      'pAtkSpd' => 325,
    ],
  ],
  12445 => 
  [
    'id' => 12445,
    'type' => 'etcitem',
    'name' => 'Foundation Themis\' Tongue',
    'add_name' => '',
    'description' => 'A rare Themis\' Tongue that requires a thorough varnishing. It can be varnished by the Blacksmith of Mammon.',
    'icon' => 'weapon_tongue_of_themis_i00',
    'weapon_type' => 'sword',
    'crystal_type' => 'a',
    'weight' => 820,
    'price' => 26968400,
    'soulshots' => 1,
    'spiritshots' => 1,
    'stats' => 
    [
      'pAtk' => 251,
      'mAtk' => 121,
      'critRate' => 8,
      'pAtkSpd' => 379,
    ],
  ],
  12446 => 
  [
    'id' => 12446,
    'type' => 'etcitem',
    'name' => 'Foundation Cabrio\'s Hand',
    'add_name' => '',
    'description' => 'A rare Cabrio\'s Hand that requires a thorough varnishing. It can be varnished by the Blacksmith of Mammon.',
    'icon' => 'weapon_hand_of_cabrio_i00',
    'weapon_type' => 'blunt',
    'crystal_type' => 'a',
    'weight' => 1510,
    'price' => 26968400,
    'soulshots' => 1,
    'spiritshots' => 1,
    'stats' => 
    [
      'pAtk' => 251,
      'mAtk' => 121,
      'critRate' => 4,
      'pAtkSpd' => 379,
    ],
  ],
  12447 => 
  [
    'id' => 12447,
    'type' => 'etcitem',
    'name' => 'Foundation Gram',
    'add_name' => '',
    'description' => 'A rare Gram that requires a thorough varnishing. It can be varnished by the Blacksmith of Mammon.',
    'icon' => 'weapon_gram_i00',
    'weapon_type' => 'ancientsword',
    'crystal_type' => 's',
    'weight' => 1800,
    'price' => 42759400,
    'soulshots' => 1,
    'spiritshots' => 1,
    'stats' => 
    [
      'pAtk' => 304,
      'mAtk' => 132,
      'critRate' => 8,
      'pAtkSpd' => 350,
    ],
  ],
  12448 => 
  [
    'id' => 12448,
    'type' => 'etcitem',
    'name' => 'Foundation Demon Splinter',
    'add_name' => '',
    'description' => 'A rare Demon Splinter that requires a thorough varnishing. It can be varnished by the Blacksmith of Mammon.',
    'icon' => 'weapon_demon_splinter_i00',
    'weapon_type' => 'dualfist',
    'crystal_type' => 's',
    'weight' => 1350,
    'price' => 42759400,
    'soulshots' => 1,
    'spiritshots' => 1,
    'stats' => 
    [
      'pAtk' => 281,
      'mAtk' => 132,
      'critRate' => 4,
      'pAtkSpd' => 325,
    ],
  ],
  12449 => 
  [
    'id' => 12449,
    'type' => 'etcitem',
    'name' => 'Foundation Draconic Bow',
    'add_name' => '',
    'description' => 'A rare Draconic Bow that requires a thorough varnishing. It can be varnished by the Blacksmith of Mammon.',
    'icon' => 'weapon_draconic_bow_i00',
    'weapon_type' => 'bow',
    'crystal_type' => 's',
    'weight' => 1650,
    'price' => 42759400,
    'soulshots' => 1,
    'spiritshots' => 1,
    'mp_consume' => 6,
    'stats' => 
    [
      'pAtk' => 581,
      'mAtk' => 132,
      'critRate' => 12,
      'pAtkSpd' => 293,
    ],
  ],
  12450 => 
  [
    'id' => 12450,
    'type' => 'etcitem',
    'name' => 'Foundation Dragon Hunter Axe',
    'add_name' => '',
    'description' => 'A rare Dragon Hunter Axe that requires a thorough varnishing. It can be varnished by the Blacksmith of Mammon.',
    'icon' => 'weapon_dragon_hunter_axe_i00',
    'weapon_type' => 'blunt',
    'crystal_type' => 's',
    'weight' => 1820,
    'price' => 42759400,
    'soulshots' => 1,
    'spiritshots' => 1,
    'stats' => 
    [
      'pAtk' => 281,
      'mAtk' => 132,
      'critRate' => 4,
      'pAtkSpd' => 379,
    ],
  ],
  12451 => 
  [
    'id' => 12451,
    'type' => 'etcitem',
    'name' => 'Foundation Laevateinn',
    'add_name' => '',
    'description' => 'A rare Laevateinn that requires a thorough varnishing. It can be varnished by the Blacksmith of Mammon.',
    'icon' => 'weapon_leavatein_i00',
    'weapon_type' => 'rapier',
    'crystal_type' => 's',
    'weight' => 1300,
    'price' => 42759400,
    'soulshots' => 1,
    'spiritshots' => 1,
    'stats' => 
    [
      'pAtk' => 255,
      'mAtk' => 132,
      'critRate' => 10,
      'pAtkSpd' => 406,
    ],
  ],
  12452 => 
  [
    'id' => 12452,
    'type' => 'etcitem',
    'name' => 'Foundation Basalt Battlehammer',
    'add_name' => '',
    'description' => 'A rare Basalt Battlehammer that requires a thorough varnishing. It can be varnished by the Blacksmith of Mammon.',
    'icon' => 'weapon_basalt_battlehammer_i00',
    'weapon_type' => 'blunt',
    'crystal_type' => 's',
    'weight' => 1570,
    'price' => 42759400,
    'soulshots' => 1,
    'spiritshots' => 1,
    'stats' => 
    [
      'pAtk' => 281,
      'mAtk' => 132,
      'critRate' => 4,
      'pAtkSpd' => 379,
    ],
  ],
  12453 => 
  [
    'id' => 12453,
    'type' => 'etcitem',
    'name' => 'Foundation Sarunga',
    'add_name' => '',
    'description' => 'A rare Sarunga that requires a thorough varnishing. It can be varnished by the Blacksmith of Mammon.',
    'icon' => 'weapon_sarnga_i00',
    'weapon_type' => 'crossbow',
    'crystal_type' => 's',
    'weight' => 1600,
    'price' => 42759400,
    'soulshots' => 1,
    'spiritshots' => 1,
    'stats' => 
    [
      'pAtk' => 356,
      'mAtk' => 132,
      'critRate' => 10,
      'pAtkSpd' => 303,
    ],
  ],
  12454 => 
  [
    'id' => 12454,
    'type' => 'etcitem',
    'name' => 'Foundation Saint Spear',
    'add_name' => '',
    'description' => 'A rare Saint Spear that requires a thorough varnishing. It can be varnished by the Blacksmith of Mammon.',
    'icon' => 'weapon_saint_spear_i00',
    'weapon_type' => 'pole',
    'crystal_type' => 's',
    'weight' => 1800,
    'price' => 42759400,
    'soulshots' => 1,
    'spiritshots' => 1,
    'stats' => 
    [
      'pAtk' => 281,
      'mAtk' => 132,
      'critRate' => 8,
      'pAtkSpd' => 325,
    ],
  ],
  12455 => 
  [
    'id' => 12455,
    'type' => 'etcitem',
    'name' => 'Foundation Arcana Mace',
    'add_name' => '',
    'description' => 'A rare Arcana Mace that requires a thorough varnishing. It can be varnished by the Blacksmith of Mammon.',
    'icon' => 'weapon_arcana_mace_i00',
    'weapon_type' => 'blunt',
    'crystal_type' => 's',
    'weight' => 1300,
    'price' => 42759400,
    'soulshots' => 1,
    'spiritshots' => 1,
    'stats' => 
    [
      'pAtk' => 281,
      'mAtk' => 132,
      'critRate' => 4,
      'pAtkSpd' => 379,
    ],
  ],
  12456 => 
  [
    'id' => 12456,
    'type' => 'etcitem',
    'name' => 'Foundation Angel Slayer',
    'add_name' => '',
    'description' => 'A rare Angel Slayer that requires a thorough varnishing. It can be varnished by the Blacksmith of Mammon.',
    'icon' => 'weapon_angel_slayer_i00',
    'weapon_type' => 'dagger',
    'crystal_type' => 's',
    'weight' => 950,
    'price' => 42759400,
    'soulshots' => 1,
    'spiritshots' => 1,
    'stats' => 
    [
      'pAtk' => 246,
      'mAtk' => 132,
      'critRate' => 12,
      'pAtkSpd' => 433,
    ],
  ],
  12457 => 
  [
    'id' => 12457,
    'type' => 'etcitem',
    'name' => 'Foundation Imperial Staff',
    'add_name' => '',
    'description' => 'A rare Imperial Staff that requires a thorough varnishing. It can be varnished by the Blacksmith of Mammon.',
    'icon' => 'weapon_imperial_staff_i00',
    'weapon_type' => 'blunt',
    'crystal_type' => 's',
    'weight' => 910,
    'price' => 42759400,
    'soulshots' => 1,
    'spiritshots' => 1,
    'stats' => 
    [
      'pAtk' => 281,
      'mAtk' => 132,
      'critRate' => 4,
      'pAtkSpd' => 379,
    ],
  ],
  12458 => 
  [
    'id' => 12458,
    'type' => 'etcitem',
    'name' => 'Foundation Forgotten Blade',
    'add_name' => '',
    'description' => 'A rare Forgotten Blade that requires a thorough varnishing. It can be varnished by the Blacksmith of Mammon.',
    'icon' => 'weapon_forgotten_blade_i00',
    'weapon_type' => 'sword',
    'crystal_type' => 's',
    'weight' => 1300,
    'price' => 42759400,
    'soulshots' => 1,
    'spiritshots' => 1,
    'stats' => 
    [
      'pAtk' => 281,
      'mAtk' => 132,
      'critRate' => 8,
      'pAtkSpd' => 379,
    ],
  ],
  12459 => 
  [
    'id' => 12459,
    'type' => 'etcitem',
    'name' => 'Foundation Heaven\'s Divider',
    'add_name' => '',
    'description' => 'A rare Heaven\'s Divider that requires a thorough varnishing. It can be varnished by the Blacksmith of Mammon.',
    'icon' => 'weapon_heavens_divider_i00',
    'weapon_type' => 'sword',
    'crystal_type' => 's',
    'weight' => 1380,
    'price' => 42759400,
    'soulshots' => 1,
    'spiritshots' => 1,
    'stats' => 
    [
      'pAtk' => 281,
      'mAtk' => 132,
      'critRate' => 8,
      'pAtkSpd' => 379,
    ],
  ],
  12460 => 
  [
    'id' => 12460,
    'type' => 'etcitem',
    'name' => 'Foundation Dynasty Ancient Sword',
    'add_name' => '',
    'description' => 'A rare Dynasty Ancient Sword that requires a thorough varnishing. It can be varnished by the Blacksmith of Mammon.',
    'icon' => 'weapon_dynasty_ancient_sword_i00',
    'weapon_type' => 'ancientsword',
    'crystal_type' => 's',
    'weight' => 1800,
    'price' => 74946000,
    'soulshots' => 1,
    'spiritshots' => 1,
    'stats' => 
    [
      'pAtk' => 361,
      'mAtk' => 151,
      'critRate' => 8,
      'pAtkSpd' => 350,
    ],
  ],
  12461 => 
  [
    'id' => 12461,
    'type' => 'etcitem',
    'name' => 'Foundation Dynasty Knife',
    'add_name' => '',
    'description' => 'A rare Dynasty Knife that requires a thorough varnishing. It can be varnished by the Blacksmith of Mammon.',
    'icon' => 'weapon_dynasty_dagger_i00',
    'weapon_type' => 'dagger',
    'crystal_type' => 's',
    'weight' => 1520,
    'price' => 74946000,
    'soulshots' => 1,
    'spiritshots' => 1,
    'stats' => 
    [
      'pAtk' => 291,
      'mAtk' => 151,
      'critRate' => 12,
      'pAtkSpd' => 433,
    ],
  ],
  12462 => 
  [
    'id' => 12462,
    'type' => 'etcitem',
    'name' => 'Foundation Dynasty Rapier',
    'add_name' => '',
    'description' => 'A rare Dynasty Rapier that requires a thorough varnishing. It can be varnished by the Blacksmith of Mammon.',
    'icon' => 'weapon_dynasty_rapier_i00',
    'weapon_type' => 'rapier',
    'crystal_type' => 's',
    'weight' => 1280,
    'price' => 74946000,
    'soulshots' => 1,
    'spiritshots' => 1,
    'stats' => 
    [
      'pAtk' => 302,
      'mAtk' => 151,
      'critRate' => 10,
      'pAtkSpd' => 406,
    ],
  ],
  12463 => 
  [
    'id' => 12463,
    'type' => 'etcitem',
    'name' => 'Foundation Dynasty Mace',
    'add_name' => '',
    'description' => 'A rare Dynasty Mace that requires a thorough varnishing. It can be varnished by the Blacksmith of Mammon.',
    'icon' => 'weapon_dynasty_staff_i00',
    'weapon_type' => 'blunt',
    'crystal_type' => 's',
    'weight' => 1080,
    'price' => 74946000,
    'soulshots' => 1,
    'spiritshots' => 1,
    'stats' => 
    [
      'pAtk' => 333,
      'mAtk' => 151,
      'critRate' => 4,
      'pAtkSpd' => 379,
    ],
  ],
  12464 => 
  [
    'id' => 12464,
    'type' => 'etcitem',
    'name' => 'Foundation Dynasty Bagh-Nakh',
    'add_name' => '',
    'description' => 'A rare Dynasty Bagh-Nakh that requires a thorough varnishing. It can be varnished by the Blacksmith of Mammon.',
    'icon' => 'weapon_dynasty_jamadhr_i00',
    'weapon_type' => 'dualfist',
    'crystal_type' => 's',
    'weight' => 1550,
    'price' => 74946000,
    'soulshots' => 1,
    'spiritshots' => 1,
    'stats' => 
    [
      'pAtk' => 333,
      'mAtk' => 151,
      'critRate' => 4,
      'pAtkSpd' => 325,
    ],
  ],
  12465 => 
  [
    'id' => 12465,
    'type' => 'etcitem',
    'name' => 'Foundation Dynasty Bow',
    'add_name' => '',
    'description' => 'A rare Dynasty Bow that requires a thorough varnishing. It can be varnished by the Blacksmith of Mammon.',
    'icon' => 'weapon_dynasty_bow_i00',
    'weapon_type' => 'bow',
    'crystal_type' => 's',
    'weight' => 1520,
    'price' => 74946000,
    'soulshots' => 1,
    'spiritshots' => 1,
    'mp_consume' => 6,
    'stats' => 
    [
      'pAtk' => 654,
      'mAtk' => 151,
      'critRate' => 12,
      'pAtkSpd' => 293,
    ],
  ],
  12466 => 
  [
    'id' => 12466,
    'type' => 'etcitem',
    'name' => 'Foundation Dynasty Blade',
    'add_name' => '',
    'description' => 'A rare Dynasty Blade that requires a thorough varnishing. It can be varnished by the Blacksmith of Mammon.',
    'icon' => 'weapon_dynasty_twohand_sword_i00',
    'weapon_type' => 'sword',
    'crystal_type' => 's',
    'weight' => 1740,
    'price' => 74946000,
    'soulshots' => 1,
    'spiritshots' => 1,
    'stats' => 
    [
      'pAtk' => 333,
      'mAtk' => 151,
      'critRate' => 8,
      'pAtkSpd' => 379,
    ],
  ],
  12467 => 
  [
    'id' => 12467,
    'type' => 'etcitem',
    'name' => 'Foundation Dynasty Sword',
    'add_name' => '',
    'description' => 'A rare Dynasty Sword that requires a thorough varnishing. It can be varnished by the Blacksmith of Mammon.',
    'icon' => 'weapon_dynasty_blade_i00',
    'weapon_type' => 'sword',
    'crystal_type' => 's',
    'weight' => 1520,
    'price' => 74946000,
    'soulshots' => 1,
    'spiritshots' => 1,
    'stats' => 
    [
      'pAtk' => 333,
      'mAtk' => 151,
      'critRate' => 8,
      'pAtkSpd' => 379,
    ],
  ],
  12468 => 
  [
    'id' => 12468,
    'type' => 'etcitem',
    'name' => 'Foundation Dynasty Staff',
    'add_name' => '',
    'description' => 'A rare Dynasty Staff that requires a thorough varnishing. It can be varnished by the Blacksmith of Mammon.',
    'icon' => 'weapon_dynasty_twohand_staff_i00',
    'weapon_type' => 'blunt',
    'crystal_type' => 's',
    'weight' => 1080,
    'price' => 74946000,
    'soulshots' => 1,
    'spiritshots' => 1,
    'stats' => 
    [
      'pAtk' => 333,
      'mAtk' => 151,
      'critRate' => 4,
      'pAtkSpd' => 379,
    ],
  ],
  12469 => 
  [
    'id' => 12469,
    'type' => 'etcitem',
    'name' => 'Foundation Dynasty Cudgel',
    'add_name' => '',
    'description' => 'A rare Dynasty Cudgel that requires a thorough varnishing. It can be varnished by the Blacksmith of Mammon.',
    'icon' => 'weapon_dynasty_hammer_i00',
    'weapon_type' => 'blunt',
    'crystal_type' => 's',
    'weight' => 1740,
    'price' => 74946000,
    'soulshots' => 1,
    'spiritshots' => 1,
    'stats' => 
    [
      'pAtk' => 333,
      'mAtk' => 151,
      'critRate' => 4,
      'pAtkSpd' => 379,
    ],
  ],
  12470 => 
  [
    'id' => 12470,
    'type' => 'etcitem',
    'name' => 'Foundation Dynasty Crusher',
    'add_name' => '',
    'description' => 'A rare Dynasty Crusher that requires a thorough varnishing. It can be varnished by the Blacksmith of Mammon.',
    'icon' => 'weapon_dynasty_crusher_i00',
    'weapon_type' => 'blunt',
    'crystal_type' => 's',
    'weight' => 1740,
    'price' => 74946000,
    'soulshots' => 1,
    'spiritshots' => 1,
    'stats' => 
    [
      'pAtk' => 333,
      'mAtk' => 151,
      'critRate' => 4,
      'pAtkSpd' => 379,
    ],
  ],
  12471 => 
  [
    'id' => 12471,
    'type' => 'etcitem',
    'name' => 'Foundation Dynasty Crossbow',
    'add_name' => '',
    'description' => 'A rare Dynasty Crossbow that requires a thorough varnishing. It can be varnished by the Blacksmith of Mammon.',
    'icon' => 'weapon_dynasty_crossbow_i00',
    'weapon_type' => 'crossbow',
    'crystal_type' => 's',
    'weight' => 1580,
    'price' => 74946000,
    'soulshots' => 1,
    'spiritshots' => 1,
    'stats' => 
    [
      'pAtk' => 401,
      'mAtk' => 151,
      'critRate' => 10,
      'pAtkSpd' => 303,
    ],
  ],
  12472 => 
  [
    'id' => 12472,
    'type' => 'etcitem',
    'name' => 'Foundation Dynasty Phantom',
    'add_name' => '',
    'description' => 'A rare Dynasty Phantom that requires a thorough varnishing. It can be varnished by the Blacksmith of Mammon.',
    'icon' => 'weapon_dynasty_magic_sword_i00',
    'weapon_type' => 'sword',
    'crystal_type' => 's',
    'weight' => 1520,
    'price' => 74946000,
    'soulshots' => 1,
    'spiritshots' => 1,
    'stats' => 
    [
      'pAtk' => 333,
      'mAtk' => 151,
      'critRate' => 8,
      'pAtkSpd' => 379,
    ],
  ],
  12473 => 
  [
    'id' => 12473,
    'type' => 'etcitem',
    'name' => 'Foundation Dynasty Halberd',
    'add_name' => '',
    'description' => 'A rare Dynasty Halberd that requires a thorough varnishing. It can be varnished by the Blacksmith of Mammon.',
    'icon' => 'weapon_dynasty_spear_i00',
    'weapon_type' => 'pole',
    'crystal_type' => 's',
    'weight' => 2010,
    'price' => 74946000,
    'soulshots' => 1,
    'spiritshots' => 1,
    'stats' => 
    [
      'pAtk' => 333,
      'mAtk' => 151,
      'critRate' => 8,
      'pAtkSpd' => 325,
    ],
  ],
  12474 => 
  [
    'id' => 12474,
    'type' => 'etcitem',
    'name' => 'Foundation Icarus Disperser',
    'add_name' => '',
    'description' => 'A rare Icarus Disperser that requires a thorough varnishing. It can be varnished by the Blacksmith of Mammon.',
    'icon' => 'weapon_icarus_disperser_i00',
    'weapon_type' => 'dagger',
    'crystal_type' => 's80',
    'weight' => 1520,
    'price' => 103439000,
    'soulshots' => 1,
    'spiritshots' => 1,
    'stats' => 
    [
      'pAtk' => 318,
      'mAtk' => 163,
      'critRate' => 12,
      'pAtkSpd' => 433,
    ],
  ],
  12475 => 
  [
    'id' => 12475,
    'type' => 'etcitem',
    'name' => 'Foundation Icarus Sawsword',
    'add_name' => '',
    'description' => 'A rare Icarus Sawsword that requires a thorough varnishing. It can be varnished by the Blacksmith of Mammon.',
    'icon' => 'weapon_icarus_sowsword_i00',
    'weapon_type' => 'sword',
    'crystal_type' => 's80',
    'weight' => 1520,
    'price' => 103439000,
    'soulshots' => 1,
    'spiritshots' => 1,
    'stats' => 
    [
      'pAtk' => 363,
      'mAtk' => 163,
      'critRate' => 8,
      'pAtkSpd' => 379,
    ],
  ],
  12476 => 
  [
    'id' => 12476,
    'type' => 'etcitem',
    'name' => 'Foundation Icarus Shooter',
    'add_name' => '',
    'description' => 'A rare Icarus Shooter that requires a thorough varnishing. It can be varnished by the Blacksmith of Mammon.',
    'icon' => 'weapon_icarus_shooter_i00',
    'weapon_type' => 'crossbow',
    'crystal_type' => 's80',
    'weight' => 1580,
    'price' => 103439000,
    'soulshots' => 1,
    'spiritshots' => 1,
    'stats' => 
    [
      'pAtk' => 422,
      'mAtk' => 163,
      'critRate' => 10,
      'pAtkSpd' => 303,
    ],
  ],
  12477 => 
  [
    'id' => 12477,
    'type' => 'etcitem',
    'name' => 'Foundation Icarus Stinger',
    'add_name' => '',
    'description' => 'A rare Icarus Stinger that requires a thorough varnishing. It can be varnished by the Blacksmith of Mammon.',
    'icon' => 'weapon_icarus_stinger_i00',
    'weapon_type' => 'rapier',
    'crystal_type' => 's80',
    'weight' => 1280,
    'price' => 103439000,
    'soulshots' => 1,
    'spiritshots' => 1,
    'stats' => 
    [
      'pAtk' => 329,
      'mAtk' => 163,
      'critRate' => 10,
      'pAtkSpd' => 406,
    ],
  ],
  12478 => 
  [
    'id' => 12478,
    'type' => 'etcitem',
    'name' => 'Foundation Icarus Spirit',
    'add_name' => '',
    'description' => 'A rare Icarus Spirit that requires a thorough varnishing. It can be varnished by the Blacksmith of Mammon.',
    'icon' => 'weapon_icarus_spirits_i00',
    'weapon_type' => 'sword',
    'crystal_type' => 's80',
    'weight' => 1520,
    'price' => 103439000,
    'soulshots' => 1,
    'spiritshots' => 1,
    'stats' => 
    [
      'pAtk' => 363,
      'mAtk' => 163,
      'critRate' => 8,
      'pAtkSpd' => 379,
    ],
  ],
  12479 => 
  [
    'id' => 12479,
    'type' => 'etcitem',
    'name' => 'Foundation Icarus Spitter',
    'add_name' => '',
    'description' => 'A rare Icarus Spitter that requires a thorough varnishing. It can be varnished by the Blacksmith of Mammon.',
    'icon' => 'weapon_icarus_spiter_i00',
    'weapon_type' => 'bow',
    'crystal_type' => 's80',
    'weight' => 1520,
    'price' => 103439000,
    'soulshots' => 1,
    'spiritshots' => 1,
    'mp_consume' => 6,
    'stats' => 
    [
      'pAtk' => 689,
      'mAtk' => 163,
      'critRate' => 12,
      'pAtkSpd' => 293,
    ],
  ],
  12480 => 
  [
    'id' => 12480,
    'type' => 'etcitem',
    'name' => 'Foundation Icarus Wingblade',
    'add_name' => '',
    'description' => 'A rare Icarus Wingblade that requires a thorough varnishing. It can be varnished by the Blacksmith of Mammon.',
    'icon' => 'weapon_icarus_wing_blade_i00',
    'weapon_type' => 'ancientsword',
    'crystal_type' => 's80',
    'weight' => 1800,
    'price' => 103439000,
    'soulshots' => 1,
    'spiritshots' => 1,
    'stats' => 
    [
      'pAtk' => 393,
      'mAtk' => 163,
      'critRate' => 8,
      'pAtkSpd' => 350,
    ],
  ],
  12481 => 
  [
    'id' => 12481,
    'type' => 'etcitem',
    'name' => 'Foundation Icarus Trident',
    'add_name' => '',
    'description' => 'A rare Icarus Trident that requires a thorough varnishing. It can be varnished by the Blacksmith of Mammon.',
    'icon' => 'weapon_icarus_trident_i00',
    'weapon_type' => 'pole',
    'crystal_type' => 's80',
    'weight' => 2010,
    'price' => 103439000,
    'soulshots' => 1,
    'spiritshots' => 1,
    'stats' => 
    [
      'pAtk' => 363,
      'mAtk' => 163,
      'critRate' => 8,
      'pAtkSpd' => 325,
    ],
  ],
  12482 => 
  [
    'id' => 12482,
    'type' => 'etcitem',
    'name' => 'Foundation Icarus Hammer',
    'add_name' => '',
    'description' => 'A rare Icarus Hammer that requires a thorough varnishing. It can be varnished by the Blacksmith of Mammon.',
    'icon' => 'weapon_icarus_hammer_i00',
    'weapon_type' => 'blunt',
    'crystal_type' => 's80',
    'weight' => 1740,
    'price' => 103439000,
    'soulshots' => 1,
    'spiritshots' => 1,
    'stats' => 
    [
      'pAtk' => 363,
      'mAtk' => 163,
      'critRate' => 4,
      'pAtkSpd' => 379,
    ],
  ],
  12483 => 
  [
    'id' => 12483,
    'type' => 'etcitem',
    'name' => 'Foundation Icarus Hand',
    'add_name' => '',
    'description' => 'A rare Icarus Hand that requires a thorough varnishing. It can be varnished by the Blacksmith of Mammon.',
    'icon' => 'weapon_icarus_knuckle_i00',
    'weapon_type' => 'dualfist',
    'crystal_type' => 's80',
    'weight' => 1550,
    'price' => 103439000,
    'soulshots' => 1,
    'spiritshots' => 1,
    'stats' => 
    [
      'pAtk' => 363,
      'mAtk' => 163,
      'critRate' => 4,
      'pAtkSpd' => 325,
    ],
  ],
  12484 => 
  [
    'id' => 12484,
    'type' => 'etcitem',
    'name' => 'Foundation Icarus Heavy Arms',
    'add_name' => '',
    'description' => 'A rare Icarus Heavy Arms that requires a thorough varnishing. It can be varnished by the Blacksmith of Mammon.',
    'icon' => 'weapon_icarus_heavy_arms_i00',
    'weapon_type' => 'sword',
    'crystal_type' => 's80',
    'weight' => 1740,
    'price' => 103439000,
    'soulshots' => 1,
    'spiritshots' => 1,
    'stats' => 
    [
      'pAtk' => 363,
      'mAtk' => 163,
      'critRate' => 8,
      'pAtkSpd' => 379,
    ],
  ],
  12485 => 
  [
    'id' => 12485,
    'type' => 'etcitem',
    'name' => 'Foundation Icarus Hall',
    'add_name' => '',
    'description' => 'A rare Icarus Hall that requires a thorough varnishing. It can be varnished by the Blacksmith of Mammon.',
    'icon' => 'weapon_icarus_stick_i00',
    'weapon_type' => 'blunt',
    'crystal_type' => 's80',
    'weight' => 1080,
    'price' => 103439000,
    'soulshots' => 1,
    'spiritshots' => 1,
    'stats' => 
    [
      'pAtk' => 363,
      'mAtk' => 163,
      'critRate' => 4,
      'pAtkSpd' => 379,
    ],
  ],
  12486 => 
  [
    'id' => 12486,
    'type' => 'etcitem',
    'name' => 'Foundation Sealed Zubei\'s Gauntlet',
    'add_name' => '',
    'description' => 'A rare Sealed Zubei\'s Gauntlet that requires a thorough varnishing. It can be varnished by the Blacksmith of Mammon.',
    'icon' => 'armor_t64_g_i02',
    'crystal_type' => 'b',
    'weight' => 590,
    'price' => 399100,
    'stats' => 
    [
    ],
  ],
  12487 => 
  [
    'id' => 12487,
    'type' => 'etcitem',
    'name' => 'Foundation Sealed Zubei\'s Boots',
    'add_name' => '',
    'description' => 'A rare Sealed Zubei\'s Boots that requires a thorough varnishing. It can be varnished by the Blacksmith of Mammon.',
    'icon' => 'armor_t64_b_i02',
    'crystal_type' => 'b',
    'weight' => 1180,
    'price' => 399100,
    'stats' => 
    [
    ],
  ],
  12488 => 
  [
    'id' => 12488,
    'type' => 'etcitem',
    'name' => 'Foundation Sealed Avadon Gloves',
    'add_name' => '',
    'description' => 'A rare Sealed Avadon Gloves that requires a thorough varnishing. It can be varnished by the Blacksmith of Mammon.',
    'icon' => 'armor_t66_g_i02',
    'crystal_type' => 'b',
    'weight' => 590,
    'price' => 399100,
    'stats' => 
    [
    ],
  ],
  12489 => 
  [
    'id' => 12489,
    'type' => 'etcitem',
    'name' => 'Foundation Sealed Avadon Boots',
    'add_name' => '',
    'description' => 'A rare Sealed Avadon Boots that requires a thorough varnishing. It can be varnished by the Blacksmith of Mammon.',
    'icon' => 'armor_t66_b_i02',
    'crystal_type' => 'b',
    'weight' => 1170,
    'price' => 399100,
    'stats' => 
    [
    ],
  ],
  12490 => 
  [
    'id' => 12490,
    'type' => 'etcitem',
    'name' => 'Foundation Zubei\'s Leather Gaiters',
    'add_name' => '',
    'description' => 'A rare Zubei\'s Leather Gaiters that requires a thorough varnishing. It can be varnished by the Blacksmith of Mammon.',
    'icon' => 'armor_t65_l_i00',
    'armor_type' => 'light',
    'crystal_type' => 'b',
    'weight' => 1480,
    'price' => 748300,
    'stats' => 
    [
    ],
  ],
  12491 => 
  [
    'id' => 12491,
    'type' => 'etcitem',
    'name' => 'Foundation Zubei\'s Leather Shirt',
    'add_name' => '',
    'description' => 'A rare Zubei\'s Leather Shirt that requires a thorough varnishing. It can be varnished by the Blacksmith of Mammon.',
    'icon' => 'armor_t65_u_i00',
    'armor_type' => 'light',
    'crystal_type' => 'b',
    'weight' => 4330,
    'price' => 1197000,
    'stats' => 
    [
    ],
  ],
  12492 => 
  [
    'id' => 12492,
    'type' => 'etcitem',
    'name' => 'Foundation Zubei\'s Gaiters',
    'add_name' => '',
    'description' => 'A rare Zubei\'s Gaiters that requires a thorough varnishing. It can be varnished by the Blacksmith of Mammon.',
    'icon' => 'armor_t64_l_i00',
    'armor_type' => 'heavy',
    'crystal_type' => 'b',
    'weight' => 3570,
    'price' => 997700,
    'stats' => 
    [
    ],
  ],
  12493 => 
  [
    'id' => 12493,
    'type' => 'etcitem',
    'name' => 'Foundation Zubei\'s Gauntlet',
    'add_name' => '',
    'description' => 'A rare Zubei\'s Gauntlet that requires a thorough varnishing. It can be varnished by the Blacksmith of Mammon.',
    'icon' => 'armor_t64_g_i00',
    'crystal_type' => 'b',
    'weight' => 590,
    'price' => 399100,
    'stats' => 
    [
    ],
  ],
  12494 => 
  [
    'id' => 12494,
    'type' => 'etcitem',
    'name' => 'Foundation Zubei\'s Gauntlet',
    'add_name' => '',
    'description' => 'A rare Zubei\'s Gauntlet that requires a thorough varnishing. It can be varnished by the Blacksmith of Mammon.',
    'icon' => 'armor_t65_g_i00',
    'crystal_type' => 'b',
    'weight' => 590,
    'price' => 399100,
    'stats' => 
    [
    ],
  ],
  12495 => 
  [
    'id' => 12495,
    'type' => 'etcitem',
    'name' => 'Foundation Zubei\'s Gauntlet',
    'add_name' => '',
    'description' => 'A rare Zubei\'s Gauntlet that requires a thorough varnishing. It can be varnished by the Blacksmith of Mammon.',
    'icon' => 'armor_t56_g_i00',
    'crystal_type' => 'b',
    'weight' => 590,
    'price' => 399100,
    'stats' => 
    [
    ],
  ],
  12496 => 
  [
    'id' => 12496,
    'type' => 'etcitem',
    'name' => 'Foundation Zubei\'s Boots',
    'add_name' => '',
    'description' => 'A rare Zubei\'s Boots that requires a thorough varnishing. It can be varnished by the Blacksmith of Mammon.',
    'icon' => 'armor_t64_b_i00',
    'crystal_type' => 'b',
    'weight' => 1180,
    'price' => 399100,
    'stats' => 
    [
    ],
  ],
  12497 => 
  [
    'id' => 12497,
    'type' => 'etcitem',
    'name' => 'Foundation Zubei\'s Boots',
    'add_name' => '',
    'description' => 'A rare Zubei\'s Boots that requires a thorough varnishing. It can be varnished by the Blacksmith of Mammon.',
    'icon' => 'armor_t65_b_i00',
    'crystal_type' => 'b',
    'weight' => 1180,
    'price' => 399100,
    'stats' => 
    [
    ],
  ],
  12498 => 
  [
    'id' => 12498,
    'type' => 'etcitem',
    'name' => 'Foundation Zubei\'s Boots',
    'add_name' => '',
    'description' => 'A rare Zubei\'s Boots that requires a thorough varnishing. It can be varnished by the Blacksmith of Mammon.',
    'icon' => 'armor_t56_b_i00',
    'crystal_type' => 'b',
    'weight' => 1180,
    'price' => 399100,
    'stats' => 
    [
    ],
  ],
  12499 => 
  [
    'id' => 12499,
    'type' => 'etcitem',
    'name' => 'Foundation Zubei\'s Shield',
    'add_name' => '',
    'description' => 'A rare Zubei\'s Shield that requires a thorough varnishing. It can be varnished by the Blacksmith of Mammon.',
    'icon' => 'shield_shrnoens_shield_i00',
    'crystal_type' => 'b',
    'weight' => 1210,
    'price' => 419000,
    'stats' => 
    [
      'rShld' => 20,
      'sDef' => 216,
    ],
  ],
];