<?php
return [
  15000 => 
  [
    'id' => 15000,
    'type' => 'armor',
    'name' => 'Leather Armor of Doom of Fortune - 30-day limited period',
    'add_name' => '30-day limited period',
    'description' => 'One-piece Body Armor. No exchange/drop available',
    'icon' => 'armor_t72_ul_i00',
    'armor_type' => 'light',
    'bodypart' => 'onepiece',
    'crystal_type' => 'b',
    'weight' => 5500,
    'is_tradable' => false,
    'is_dropable' => false,
    'is_sellable' => false,
    'is_depositable' => false,
    'time' => 43200,
    'stats' => 
    [
    ],
  ],
  15001 => 
  [
    'id' => 15001,
    'type' => 'armor',
    'name' => 'Doom Helmet of Fortune - 30-day limited period',
    'add_name' => '30-day limited period',
    'description' => 'No exchange/drop available',
    'icon' => 'armor_leather_helmet_i00',
    'bodypart' => 'head',
    'crystal_type' => 'b',
    'weight' => 580,
    'is_tradable' => false,
    'is_dropable' => false,
    'is_sellable' => false,
    'is_depositable' => false,
    'time' => 43200,
    'stats' => 
    [
    ],
  ],
  15002 => 
  [
    'id' => 15002,
    'type' => 'armor',
    'name' => 'Doom Gloves of Fortune - Heavy Armor - 30-day limited period',
    'add_name' => '30-day limited period',
    'description' => 'Gloves that make a set with the Doom Plate Armor of Fortune. No exchange/drop available',
    'icon' => 'armor_t71_g_i00',
    'bodypart' => 'gloves',
    'crystal_type' => 'b',
    'weight' => 580,
    'is_tradable' => false,
    'is_dropable' => false,
    'is_sellable' => false,
    'is_depositable' => false,
    'time' => 43200,
    'stats' => 
    [
    ],
  ],
  15003 => 
  [
    'id' => 15003,
    'type' => 'armor',
    'name' => 'Doom Gloves of Fortune - Light Armor - 30-day limited period',
    'add_name' => '30-day limited period',
    'description' => 'Gloves that make a set with the Doom Leather Mail of Fortune. No exchange/drop available',
    'icon' => 'armor_t72_g_i00',
    'bodypart' => 'gloves',
    'crystal_type' => 'b',
    'weight' => 580,
    'is_tradable' => false,
    'is_dropable' => false,
    'is_sellable' => false,
    'is_depositable' => false,
    'time' => 43200,
    'stats' => 
    [
    ],
  ],
  15004 => 
  [
    'id' => 15004,
    'type' => 'armor',
    'name' => 'Doom Boots of Fortune - Heavy Armor - 30-day limited period',
    'add_name' => '30-day limited period',
    'description' => 'Boots that make a set with the Doom Plate Armor of Fortune. No exchange/drop available',
    'icon' => 'armor_t71_b_i00',
    'bodypart' => 'feet',
    'crystal_type' => 'b',
    'weight' => 1130,
    'is_tradable' => false,
    'is_dropable' => false,
    'is_sellable' => false,
    'is_depositable' => false,
    'time' => 43200,
    'stats' => 
    [
    ],
  ],
  15005 => 
  [
    'id' => 15005,
    'type' => 'armor',
    'name' => 'Doom Boots of Fortune - Light Armor - 30-day limited period',
    'add_name' => '30-day limited period',
    'description' => 'Boots that make a set with the Doom Leather Mail of Fortune. No exchange/drop available',
    'icon' => 'armor_t72_b_i00',
    'bodypart' => 'feet',
    'crystal_type' => 'b',
    'weight' => 1130,
    'is_tradable' => false,
    'is_dropable' => false,
    'is_sellable' => false,
    'is_depositable' => false,
    'time' => 43200,
    'stats' => 
    [
    ],
  ],
  15006 => 
  [
    'id' => 15006,
    'type' => 'armor',
    'name' => 'Doom Plate Armor of Fortune - 30-day limited period',
    'add_name' => '30-day limited period',
    'description' => 'One-piece Body Armor. No exchange/drop available',
    'icon' => 'armor_t71_ul_i00',
    'armor_type' => 'heavy',
    'bodypart' => 'onepiece',
    'crystal_type' => 'b',
    'weight' => 9980,
    'is_tradable' => false,
    'is_dropable' => false,
    'is_sellable' => false,
    'is_depositable' => false,
    'time' => 43200,
    'stats' => 
    [
    ],
  ],
  15007 => 
  [
    'id' => 15007,
    'type' => 'armor',
    'name' => 'Doom Shield of Fortune - 30-day limited period',
    'add_name' => '30-day limited period',
    'description' => 'No exchange/drop available',
    'icon' => 'shield_doom_shield_i00',
    'bodypart' => 'lhand',
    'crystal_type' => 'b',
    'weight' => 1200,
    'is_tradable' => false,
    'is_dropable' => false,
    'is_sellable' => false,
    'is_depositable' => false,
    'time' => 43200,
    'stats' => 
    [
      'rShld' => 20,
      'sDef' => 230,
    ],
  ],
  15008 => 
  [
    'id' => 15008,
    'type' => 'armor',
    'name' => 'Plate Leather Armor of Fortune - 30-day limited period',
    'add_name' => '30-day limited period',
    'description' => 'No exchange/drop available',
    'icon' => 'armor_t47_u_i00',
    'armor_type' => 'light',
    'bodypart' => 'chest',
    'crystal_type' => 'c',
    'weight' => 4450,
    'is_tradable' => false,
    'is_dropable' => false,
    'is_sellable' => false,
    'is_depositable' => false,
    'time' => 43200,
    'stats' => 
    [
    ],
  ],
  15009 => 
  [
    'id' => 15009,
    'type' => 'armor',
    'name' => 'Plate Leather Gaiters of Fortune - 30-day limited period',
    'add_name' => '30-day limited period',
    'description' => 'No exchange/drop available',
    'icon' => 'armor_t47_l_i00',
    'armor_type' => 'light',
    'bodypart' => 'legs',
    'crystal_type' => 'c',
    'weight' => 1560,
    'is_tradable' => false,
    'is_dropable' => false,
    'is_sellable' => false,
    'is_depositable' => false,
    'time' => 43200,
    'stats' => 
    [
    ],
  ],
  15010 => 
  [
    'id' => 15010,
    'type' => 'armor',
    'name' => 'Plate Leather Boots of Fortune - 30-day limited period',
    'add_name' => '30-day limited period',
    'description' => 'No exchange/drop available',
    'icon' => 'armor_t47_b_i00',
    'bodypart' => 'feet',
    'crystal_type' => 'c',
    'weight' => 1220,
    'is_tradable' => false,
    'is_dropable' => false,
    'is_sellable' => false,
    'is_depositable' => false,
    'time' => 43200,
    'stats' => 
    [
    ],
  ],
  15011 => 
  [
    'id' => 15011,
    'type' => 'armor',
    'name' => 'Plate Leather Gloves of Fortune - 30-day limited period',
    'add_name' => '30-day limited period',
    'description' => 'No exchange/drop available',
    'icon' => 'armor_t47_g_i00',
    'bodypart' => 'gloves',
    'crystal_type' => 'c',
    'weight' => 610,
    'is_tradable' => false,
    'is_dropable' => false,
    'is_sellable' => false,
    'is_depositable' => false,
    'time' => 43200,
    'stats' => 
    [
    ],
  ],
  15012 => 
  [
    'id' => 15012,
    'type' => 'armor',
    'name' => 'Full Plate Helmet of Fortune - 30-day limited period',
    'add_name' => '30-day limited period',
    'description' => 'No exchange/drop available',
    'icon' => 'armor_leather_helmet_i00',
    'bodypart' => 'head',
    'crystal_type' => 'c',
    'weight' => 600,
    'is_tradable' => false,
    'is_dropable' => false,
    'is_sellable' => false,
    'is_depositable' => false,
    'time' => 43200,
    'stats' => 
    [
    ],
  ],
  15013 => 
  [
    'id' => 15013,
    'type' => 'armor',
    'name' => 'Full Plate Armor of Fortune - 30-day limited period',
    'add_name' => '30-day limited period',
    'description' => 'One-piece Body Armor. No exchange/drop available',
    'icon' => 'armor_t62_ul_i00',
    'armor_type' => 'heavy',
    'bodypart' => 'onepiece',
    'crystal_type' => 'c',
    'weight' => 10480,
    'is_tradable' => false,
    'is_dropable' => false,
    'is_sellable' => false,
    'is_depositable' => false,
    'time' => 43200,
    'stats' => 
    [
    ],
  ],
  15014 => 
  [
    'id' => 15014,
    'type' => 'armor',
    'name' => 'Full Plate Boots of Fortune - 30-day limited period',
    'add_name' => '30-day limited period',
    'description' => 'No exchange/drop available',
    'icon' => 'armor_t62_b_i00',
    'bodypart' => 'feet',
    'crystal_type' => 'c',
    'weight' => 1200,
    'is_tradable' => false,
    'is_dropable' => false,
    'is_sellable' => false,
    'is_depositable' => false,
    'time' => 43200,
    'stats' => 
    [
    ],
  ],
  15015 => 
  [
    'id' => 15015,
    'type' => 'armor',
    'name' => 'Full Plate Gauntlet of Fortune - 30-day limited period',
    'add_name' => '30-day limited period',
    'description' => 'No exchange/drop available',
    'icon' => 'armor_t62_g_i00',
    'bodypart' => 'gloves',
    'crystal_type' => 'c',
    'weight' => 600,
    'is_tradable' => false,
    'is_dropable' => false,
    'is_sellable' => false,
    'is_depositable' => false,
    'time' => 43200,
    'stats' => 
    [
    ],
  ],
  15016 => 
  [
    'id' => 15016,
    'type' => 'armor',
    'name' => 'Full Plate Shield of Fortune - 30-day limited period',
    'add_name' => '30-day limited period',
    'description' => 'No exchange/drop available',
    'icon' => 'shield_full_plate_shield_i00',
    'bodypart' => 'lhand',
    'crystal_type' => 'c',
    'weight' => 1220,
    'is_tradable' => false,
    'is_dropable' => false,
    'is_sellable' => false,
    'is_depositable' => false,
    'time' => 43200,
    'stats' => 
    [
      'rShld' => 20,
      'sDef' => 203,
    ],
  ],
  15017 => 
  [
    'id' => 15017,
    'type' => 'armor',
    'name' => 'Manticore Skin Shirt of Fortune - 30-day limited period',
    'add_name' => '30-day limited period',
    'description' => 'No exchange/drop available',
    'icon' => 'armor_t42_u_i00',
    'armor_type' => 'light',
    'bodypart' => 'chest',
    'crystal_type' => 'd',
    'weight' => 4520,
    'is_tradable' => false,
    'is_dropable' => false,
    'is_sellable' => false,
    'is_depositable' => false,
    'time' => 43200,
    'stats' => 
    [
    ],
  ],
  15018 => 
  [
    'id' => 15018,
    'type' => 'armor',
    'name' => 'Manticore Skin Gaiters of Fortune - 30-day limited period',
    'add_name' => '30-day limited period',
    'description' => 'No exchange/drop available',
    'icon' => 'armor_t42_l_i00',
    'armor_type' => 'light',
    'bodypart' => 'legs',
    'crystal_type' => 'd',
    'weight' => 1550,
    'is_tradable' => false,
    'is_dropable' => false,
    'is_sellable' => false,
    'is_depositable' => false,
    'time' => 43200,
    'stats' => 
    [
    ],
  ],
  15019 => 
  [
    'id' => 15019,
    'type' => 'armor',
    'name' => 'Manticore Skin Boots of Fortune - 30-day limited period',
    'add_name' => '30-day limited period',
    'description' => 'No exchange/drop available',
    'icon' => 'armor_t42_b_i00',
    'bodypart' => 'feet',
    'crystal_type' => 'd',
    'weight' => 1260,
    'is_tradable' => false,
    'is_dropable' => false,
    'is_sellable' => false,
    'is_depositable' => false,
    'time' => 43200,
    'stats' => 
    [
    ],
  ],
  15020 => 
  [
    'id' => 15020,
    'type' => 'armor',
    'name' => 'Manticore Skin Gloves of Fortune - 30-day limited period',
    'add_name' => '30-day limited period',
    'description' => 'No exchange/drop available',
    'icon' => 'armor_t42_g_i00',
    'bodypart' => 'gloves',
    'crystal_type' => 'd',
    'weight' => 630,
    'is_tradable' => false,
    'is_dropable' => false,
    'is_sellable' => false,
    'is_depositable' => false,
    'time' => 43200,
    'stats' => 
    [
    ],
  ],
  15021 => 
  [
    'id' => 15021,
    'type' => 'armor',
    'name' => 'Brigandine of Fortune - 30-day limited period',
    'add_name' => '30-day limited period',
    'description' => 'No exchange/drop available',
    'icon' => 'armor_t43_u_i00',
    'armor_type' => 'heavy',
    'bodypart' => 'chest',
    'crystal_type' => 'd',
    'weight' => 8320,
    'is_tradable' => false,
    'is_dropable' => false,
    'is_sellable' => false,
    'is_depositable' => false,
    'time' => 43200,
    'stats' => 
    [
    ],
  ],
  15022 => 
  [
    'id' => 15022,
    'type' => 'armor',
    'name' => 'Brigandine Gaiters of Fortune - 30-day limited period',
    'add_name' => '30-day limited period',
    'description' => 'No exchange/drop available',
    'icon' => 'armor_t43_l_i00',
    'armor_type' => 'heavy',
    'bodypart' => 'legs',
    'crystal_type' => 'd',
    'weight' => 3820,
    'is_tradable' => false,
    'is_dropable' => false,
    'is_sellable' => false,
    'is_depositable' => false,
    'time' => 43200,
    'stats' => 
    [
    ],
  ],
  15023 => 
  [
    'id' => 15023,
    'type' => 'armor',
    'name' => 'Brigandine Helmet of Fortune - 30-day limited period',
    'add_name' => '30-day limited period',
    'description' => 'No exchange/drop available',
    'icon' => 'armor_leather_helmet_i00',
    'bodypart' => 'head',
    'crystal_type' => 'd',
    'weight' => 630,
    'is_tradable' => false,
    'is_dropable' => false,
    'is_sellable' => false,
    'is_depositable' => false,
    'time' => 43200,
    'stats' => 
    [
    ],
  ],
  15024 => 
  [
    'id' => 15024,
    'type' => 'armor',
    'name' => 'Brigandine Boots of Fortune - 30-day limited period',
    'add_name' => '30-day limited period',
    'description' => 'No exchange/drop available',
    'icon' => 'armor_t43_b_i00',
    'bodypart' => 'feet',
    'crystal_type' => 'd',
    'weight' => 1250,
    'is_tradable' => false,
    'is_dropable' => false,
    'is_sellable' => false,
    'is_depositable' => false,
    'time' => 43200,
    'stats' => 
    [
    ],
  ],
  15025 => 
  [
    'id' => 15025,
    'type' => 'armor',
    'name' => 'Brigandine Gauntlet of Fortune - 30-day limited period',
    'add_name' => '30-day limited period',
    'description' => 'No exchange/drop available',
    'icon' => 'armor_t43_g_i00',
    'bodypart' => 'gloves',
    'crystal_type' => 'd',
    'weight' => 630,
    'is_tradable' => false,
    'is_dropable' => false,
    'is_sellable' => false,
    'is_depositable' => false,
    'time' => 43200,
    'stats' => 
    [
    ],
  ],
  15026 => 
  [
    'id' => 15026,
    'type' => 'armor',
    'name' => 'Brigandine Shield of Fortune - 30-day limited period',
    'add_name' => '30-day limited period',
    'description' => 'No exchange/drop available',
    'icon' => 'shield_brigandine_shield_i00',
    'bodypart' => 'lhand',
    'crystal_type' => 'd',
    'weight' => 1320,
    'is_tradable' => false,
    'is_dropable' => false,
    'is_sellable' => false,
    'is_depositable' => false,
    'time' => 43200,
    'stats' => 
    [
      'rShld' => 20,
      'sDef' => 142,
    ],
  ],
  15027 => 
  [
    'id' => 15027,
    'type' => 'armor',
    'name' => 'Fortune Armor of Nightmare - 30-day limited period',
    'add_name' => '30-day limited period',
    'description' => 'One-piece Body Armor. No exchange/drop available',
    'icon' => 'armor_t80_ul_i00',
    'armor_type' => 'heavy',
    'bodypart' => 'onepiece',
    'crystal_type' => 'a',
    'weight' => 9580,
    'is_tradable' => false,
    'is_dropable' => false,
    'is_sellable' => false,
    'is_depositable' => false,
    'time' => 43200,
    'stats' => 
    [
    ],
  ],
  15028 => 
  [
    'id' => 15028,
    'type' => 'armor',
    'name' => 'Fortune Helm of Nightmare - 30-day limited period',
    'add_name' => '30-day limited period',
    'description' => 'No exchange/drop available',
    'icon' => 'armor_leather_helmet_i00',
    'bodypart' => 'head',
    'crystal_type' => 'a',
    'weight' => 560,
    'is_tradable' => false,
    'is_dropable' => false,
    'is_sellable' => false,
    'is_depositable' => false,
    'time' => 43200,
    'stats' => 
    [
    ],
  ],
  15029 => 
  [
    'id' => 15029,
    'type' => 'armor',
    'name' => 'Fortune Gauntlet of Nightmare - Heavy Armor - 30-day limited period',
    'add_name' => '30-day limited period',
    'description' => 'Gauntlet that makes a set with Fortune Armor of Nightmare. No exchange/drop available',
    'icon' => 'armor_t80_g_i00',
    'bodypart' => 'gloves',
    'crystal_type' => 'a',
    'weight' => 550,
    'is_tradable' => false,
    'is_dropable' => false,
    'is_sellable' => false,
    'is_depositable' => false,
    'time' => 43200,
    'stats' => 
    [
    ],
  ],
  15030 => 
  [
    'id' => 15030,
    'type' => 'armor',
    'name' => 'Fortune Boots of Nightmare - Heavy Armor - 30-day limited period',
    'add_name' => '30-day limited period',
    'description' => 'Boots that make a set with Fortune Armor of Nightmare. No exchange/drop available',
    'icon' => 'armor_t80_b_i00',
    'bodypart' => 'feet',
    'crystal_type' => 'a',
    'weight' => 1110,
    'is_tradable' => false,
    'is_dropable' => false,
    'is_sellable' => false,
    'is_depositable' => false,
    'time' => 43200,
    'stats' => 
    [
    ],
  ],
  15031 => 
  [
    'id' => 15031,
    'type' => 'armor',
    'name' => 'Fortune Shield of Nightmare - 30-day limited period',
    'add_name' => '30-day limited period',
    'description' => 'No exchange/drop available',
    'icon' => 'shield_shield_of_nightmare_i00',
    'bodypart' => 'lhand',
    'crystal_type' => 'a',
    'weight' => 1180,
    'is_tradable' => false,
    'is_dropable' => false,
    'is_sellable' => false,
    'is_depositable' => false,
    'time' => 43200,
    'stats' => 
    [
      'rShld' => 20,
      'sDef' => 256,
    ],
  ],
  15032 => 
  [
    'id' => 15032,
    'type' => 'weapon',
    'name' => 'Sword of Miracles of Fortune - 30-day limited period',
    'add_name' => '30-day limited period',
    'description' => 'Increases Casting Spd. by 15%, and increases damage inflicted during PvP. No exchange/drop available',
    'icon' => 'weapon_sword_of_miracle_i01',
    'weapon_type' => 'sword',
    'bodypart' => 'rhand',
    'crystal_type' => 'a',
    'weight' => 840,
    'soulshots' => 1,
    'spiritshots' => 1,
    'is_tradable' => false,
    'is_dropable' => false,
    'is_sellable' => false,
    'is_depositable' => false,
    'is_magic_weapon' => true,
    'item_skill' => 
    [
      0 => 
      [
        'skill_id' => 3047,
        'level' => 2,
      ],
    ],
    'time' => 43200,
    'enchanted' => 4,
    'stats' => 
    [
      'pAtk' => 186,
      'mAtk' => 152,
      'critRate' => 8,
      'pAtkSpd' => 379,
    ],
  ],
  15033 => 
  [
    'id' => 15033,
    'type' => 'weapon',
    'name' => 'Wizard\'s Tear of Fortune - 30-day limited period',
    'add_name' => '30-day limited period',
    'description' => 'Casting Spd. increases by 15%. No exchange/drop available',
    'icon' => 'weapon_tears_of_wizard_i01',
    'weapon_type' => 'sword',
    'bodypart' => 'rhand',
    'crystal_type' => 'b',
    'weight' => 1350,
    'soulshots' => 1,
    'spiritshots' => 1,
    'is_tradable' => false,
    'is_dropable' => false,
    'is_sellable' => false,
    'is_depositable' => false,
    'is_magic_weapon' => true,
    'item_skill' => 
    [
      0 => 
      [
        'skill_id' => 3047,
        'level' => 1,
      ],
    ],
    'time' => 43200,
    'enchanted' => 4,
    'stats' => 
    [
      'pAtk' => 155,
      'mAtk' => 132,
      'critRate' => 8,
      'pAtkSpd' => 379,
    ],
  ],
  15034 => 
  [
    'id' => 15034,
    'type' => 'weapon',
    'name' => 'Homunkulus\'s Sword of Fortune - 30-day limited period',
    'add_name' => '30-day limited period',
    'description' => 'Casting Spd. increases by 15%. No exchange/drop available',
    'icon' => 'weapon_homunkuluss_sword_i01',
    'weapon_type' => 'sword',
    'bodypart' => 'rhand',
    'crystal_type' => 'c',
    'weight' => 950,
    'soulshots' => 3,
    'spiritshots' => 3,
    'is_tradable' => false,
    'is_dropable' => false,
    'is_sellable' => false,
    'is_depositable' => false,
    'is_magic_weapon' => true,
    'item_skill' => 
    [
      0 => 
      [
        'skill_id' => 3047,
        'level' => 1,
      ],
    ],
    'time' => 43200,
    'enchanted' => 4,
    'stats' => 
    [
      'pAtk' => 111,
      'mAtk' => 101,
      'critRate' => 8,
      'pAtkSpd' => 379,
    ],
  ],
  15035 => 
  [
    'id' => 15035,
    'type' => 'weapon',
    'name' => 'Fortune Staff of Life - 30-day limited period',
    'add_name' => '30-day limited period',
    'description' => 'No exchange/drop available',
    'icon' => 'weapon_life_stick_i00',
    'weapon_type' => 'blunt',
    'bodypart' => 'rhand',
    'crystal_type' => 'd',
    'weight' => 1180,
    'soulshots' => 3,
    'spiritshots' => 3,
    'is_tradable' => false,
    'is_dropable' => false,
    'is_sellable' => false,
    'is_depositable' => false,
    'is_magic_weapon' => true,
    'time' => 43200,
    'enchanted' => 4,
    'stats' => 
    [
      'pAtk' => 74,
      'mAtk' => 72,
      'critRate' => 4,
      'pAtkSpd' => 379,
    ],
  ],
  15036 => 
  [
    'id' => 15036,
    'type' => 'weapon',
    'name' => 'Naga Storm of Fortune - 30-day limited period',
    'add_name' => '30-day limited period',
    'description' => 'Increases Critical by 67, and increases damage inflicted during PvP. No exchange/drop available',
    'icon' => 'weapon_naga_storm_i01',
    'weapon_type' => 'dagger',
    'bodypart' => 'rhand',
    'crystal_type' => 'a',
    'weight' => 930,
    'soulshots' => 1,
    'spiritshots' => 1,
    'is_tradable' => false,
    'is_dropable' => false,
    'is_sellable' => false,
    'is_depositable' => false,
    'item_skill' => 
    [
      0 => 
      [
        'skill_id' => 3051,
        'level' => 2,
      ],
    ],
    'time' => 43200,
    'enchanted' => 4,
    'stats' => 
    [
      'pAtk' => 220,
      'mAtk' => 121,
      'critRate' => 12,
      'pAtkSpd' => 433,
    ],
  ],
  15037 => 
  [
    'id' => 15037,
    'type' => 'weapon',
    'name' => 'Kris of Fortune - 30-day limited period',
    'add_name' => '30-day limited period',
    'description' => 'Increases Critical by 71. No exchange/drop available',
    'icon' => 'weapon_kris_i01',
    'weapon_type' => 'dagger',
    'bodypart' => 'rhand',
    'crystal_type' => 'b',
    'weight' => 980,
    'soulshots' => 1,
    'spiritshots' => 1,
    'is_tradable' => false,
    'is_dropable' => false,
    'is_sellable' => false,
    'is_depositable' => false,
    'item_skill' => 
    [
      0 => 
      [
        'skill_id' => 3011,
        'level' => 5,
      ],
    ],
    'time' => 43200,
    'enchanted' => 4,
    'stats' => 
    [
      'pAtk' => 153,
      'mAtk' => 91,
      'critRate' => 12,
      'pAtkSpd' => 433,
    ],
  ],
  15038 => 
  [
    'id' => 15038,
    'type' => 'weapon',
    'name' => 'Dark Screamer of Fortune - 30-day limited period',
    'add_name' => '30-day limited period',
    'description' => 'Increases Critical by 81. No exchange/drop available',
    'icon' => 'weapon_dark_screamer_i01',
    'weapon_type' => 'dagger',
    'bodypart' => 'rhand',
    'crystal_type' => 'c',
    'weight' => 1010,
    'soulshots' => 3,
    'spiritshots' => 3,
    'is_tradable' => false,
    'is_dropable' => false,
    'is_sellable' => false,
    'is_depositable' => false,
    'item_skill' => 
    [
      0 => 
      [
        'skill_id' => 3011,
        'level' => 3,
      ],
    ],
    'time' => 43200,
    'enchanted' => 4,
    'stats' => 
    [
      'pAtk' => 122,
      'mAtk' => 76,
      'critRate' => 12,
      'pAtkSpd' => 433,
    ],
  ],
  15039 => 
  [
    'id' => 15039,
    'type' => 'weapon',
    'name' => 'Mithril Dagger of Fortune - 30-day limited period',
    'add_name' => '30-day limited period',
    'description' => 'No exchange/drop available',
    'icon' => 'weapon_mithril_dagger_i00',
    'weapon_type' => 'dagger',
    'bodypart' => 'rhand',
    'crystal_type' => 'd',
    'weight' => 1060,
    'soulshots' => 3,
    'spiritshots' => 3,
    'is_tradable' => false,
    'is_dropable' => false,
    'is_sellable' => false,
    'is_depositable' => false,
    'time' => 43200,
    'enchanted' => 4,
    'stats' => 
    [
      'pAtk' => 80,
      'mAtk' => 54,
      'critRate' => 12,
      'pAtkSpd' => 433,
    ],
  ],
  15040 => 
  [
    'id' => 15040,
    'type' => 'weapon',
    'name' => 'Shyeed\'s Bow of Fortune - 30-day limited period',
    'add_name' => '30-day limited period',
    'description' => 'Increases Critical by 61, and increases damage inflicted during PvP. No exchange/drop available',
    'icon' => 'weapon_shyid_bow_i01',
    'weapon_type' => 'bow',
    'bodypart' => 'lrhand',
    'crystal_type' => 'a',
    'weight' => 1640,
    'soulshots' => 2,
    'spiritshots' => 1,
    'mp_consume' => 5,
    'is_tradable' => false,
    'is_dropable' => false,
    'is_sellable' => false,
    'is_depositable' => false,
    'item_skill' => 
    [
      0 => 
      [
        'skill_id' => 3050,
        'level' => 2,
      ],
    ],
    'time' => 43200,
    'enchanted' => 4,
    'stats' => 
    [
      'pAtk' => 570,
      'mAtk' => 133,
      'critRate' => 12,
      'pAtkSpd' => 227,
    ],
  ],
  15041 => 
  [
    'id' => 15041,
    'type' => 'weapon',
    'name' => 'Fortune Bow of Peril - 30-day limited period',
    'add_name' => '30-day limited period',
    'description' => 'During a general attack, MP consumption decreases to 2 with a 42% chance. No exchange/drop available',
    'icon' => 'weapon_hazard_bow_i01',
    'weapon_type' => 'bow',
    'bodypart' => 'lrhand',
    'crystal_type' => 'b',
    'weight' => 1700,
    'soulshots' => 3,
    'spiritshots' => 1,
    'mp_consume' => 4,
    'is_tradable' => false,
    'is_dropable' => false,
    'is_sellable' => false,
    'is_depositable' => false,
    'time' => 43200,
    'enchanted' => 4,
    'stats' => 
    [
      'pAtk' => 400,
      'mAtk' => 99,
      'critRate' => 12,
      'pAtkSpd' => 293,
    ],
  ],
  15042 => 
  [
    'id' => 15042,
    'type' => 'weapon',
    'name' => 'Eminence Bow of Fortune - 30-day limited period',
    'add_name' => '30-day limited period',
    'description' => 'During a general attack, MP consumption decreases to 1 with a 42% chance. No exchange/drop available',
    'icon' => 'weapon_eminence_bow_i01',
    'weapon_type' => 'bow',
    'bodypart' => 'lrhand',
    'crystal_type' => 'c',
    'weight' => 1720,
    'soulshots' => 10,
    'spiritshots' => 3,
    'mp_consume' => 3,
    'is_tradable' => false,
    'is_dropable' => false,
    'is_sellable' => false,
    'is_depositable' => false,
    'time' => 43200,
    'enchanted' => 4,
    'stats' => 
    [
      'pAtk' => 323,
      'mAtk' => 83,
      'critRate' => 12,
      'pAtkSpd' => 293,
    ],
  ],
  15043 => 
  [
    'id' => 15043,
    'type' => 'weapon',
    'name' => 'Light Crossbow of Fortune - 30-day limited period',
    'add_name' => '30-day limited period',
    'description' => 'No exchange/drop available',
    'icon' => 'weapon_cyclone_bow_i00',
    'weapon_type' => 'bow',
    'bodypart' => 'lrhand',
    'crystal_type' => 'd',
    'weight' => 1810,
    'soulshots' => 10,
    'spiritshots' => 3,
    'mp_consume' => 2,
    'is_tradable' => false,
    'is_dropable' => false,
    'is_sellable' => false,
    'is_depositable' => false,
    'time' => 43200,
    'enchanted' => 4,
    'stats' => 
    [
      'pAtk' => 191,
      'mAtk' => 54,
      'critRate' => 12,
      'pAtkSpd' => 293,
    ],
  ],
  15044 => 
  [
    'id' => 15044,
    'type' => 'weapon',
    'name' => 'Barakiel\'s Axe of Fortune - 30-day limited period',
    'add_name' => '30-day limited period',
    'description' => 'Increases Critical by 61, and increases damage inflicted during PvP. No exchange/drop available',
    'icon' => 'weapon_barakiel_axe_i01',
    'weapon_type' => 'blunt',
    'bodypart' => 'rhand',
    'crystal_type' => 'a',
    'weight' => 1550,
    'soulshots' => 1,
    'spiritshots' => 1,
    'is_tradable' => false,
    'is_dropable' => false,
    'is_sellable' => false,
    'is_depositable' => false,
    'item_skill' => 
    [
      0 => 
      [
        'skill_id' => 3050,
        'level' => 2,
      ],
    ],
    'time' => 43200,
    'enchanted' => 4,
    'stats' => 
    [
      'pAtk' => 251,
      'mAtk' => 121,
      'critRate' => 4,
      'pAtkSpd' => 379,
    ],
  ],
  15045 => 
  [
    'id' => 15045,
    'type' => 'weapon',
    'name' => 'Art of Battle Axe of Fortune - 30-day limited period',
    'add_name' => '30-day limited period',
    'description' => 'Max HP increases by 25%. No exchange/drop available',
    'icon' => 'weapon_art_of_battle_axe_i01',
    'weapon_type' => 'blunt',
    'bodypart' => 'rhand',
    'crystal_type' => 'b',
    'weight' => 1570,
    'soulshots' => 1,
    'spiritshots' => 1,
    'is_tradable' => false,
    'is_dropable' => false,
    'is_sellable' => false,
    'is_depositable' => false,
    'item_skill' => 
    [
      0 => 
      [
        'skill_id' => 3013,
        'level' => 1,
      ],
    ],
    'time' => 43200,
    'enchanted' => 4,
    'stats' => 
    [
      'pAtk' => 194,
      'mAtk' => 99,
      'critRate' => 4,
      'pAtkSpd' => 379,
    ],
  ],
  15046 => 
  [
    'id' => 15046,
    'type' => 'weapon',
    'name' => 'Yaksa Mace of Fortune - 30-day limited period',
    'add_name' => '30-day limited period',
    'description' => 'Max HP increases by 25%. No exchange/drop available',
    'icon' => 'weapon_yaksa_mace_i01',
    'weapon_type' => 'blunt',
    'bodypart' => 'rhand',
    'crystal_type' => 'c',
    'weight' => 1640,
    'soulshots' => 3,
    'spiritshots' => 3,
    'is_tradable' => false,
    'is_dropable' => false,
    'is_sellable' => false,
    'is_depositable' => false,
    'item_skill' => 
    [
      0 => 
      [
        'skill_id' => 3013,
        'level' => 1,
      ],
    ],
    'time' => 43200,
    'enchanted' => 4,
    'stats' => 
    [
      'pAtk' => 156,
      'mAtk' => 83,
      'critRate' => 4,
      'pAtkSpd' => 379,
    ],
  ],
  15047 => 
  [
    'id' => 15047,
    'type' => 'weapon',
    'name' => 'Bonebreaker of Fortune - 30-day limited period',
    'add_name' => '30-day limited period',
    'description' => 'No exchange/drop available',
    'icon' => 'weapon_bonebreaker_i00',
    'weapon_type' => 'blunt',
    'bodypart' => 'rhand',
    'crystal_type' => 'd',
    'weight' => 1720,
    'soulshots' => 3,
    'spiritshots' => 3,
    'is_tradable' => false,
    'is_dropable' => false,
    'is_sellable' => false,
    'is_depositable' => false,
    'time' => 43200,
    'enchanted' => 4,
    'stats' => 
    [
      'pAtk' => 92,
      'mAtk' => 54,
      'critRate' => 4,
      'pAtkSpd' => 379,
    ],
  ],
  15048 => 
  [
    'id' => 15048,
    'type' => 'weapon',
    'name' => 'Sirra\'s Blade of Fortune - 30-day limited period',
    'add_name' => '30-day limited period',
    'description' => 'Increases Max HP by 25%, and increases damage inflicted during PvP. No exchange/drop available',
    'icon' => 'weapon_sirr_blade_i01',
    'weapon_type' => 'sword',
    'bodypart' => 'rhand',
    'crystal_type' => 'a',
    'weight' => 1300,
    'soulshots' => 1,
    'spiritshots' => 1,
    'is_tradable' => false,
    'is_dropable' => false,
    'is_sellable' => false,
    'is_depositable' => false,
    'item_skill' => 
    [
      0 => 
      [
        'skill_id' => 3013,
        'level' => 5,
      ],
    ],
    'time' => 43200,
    'enchanted' => 4,
    'stats' => 
    [
      'pAtk' => 251,
      'mAtk' => 121,
      'critRate' => 8,
      'pAtkSpd' => 379,
    ],
  ],
  15049 => 
  [
    'id' => 15049,
    'type' => 'weapon',
    'name' => 'Fortune Sword of Damascus - 30-day limited period',
    'add_name' => '30-day limited period',
    'description' => 'Increases Critical by 64. No exchange/drop available',
    'icon' => 'weapon_sword_of_damascus_i01',
    'weapon_type' => 'sword',
    'bodypart' => 'rhand',
    'crystal_type' => 'b',
    'weight' => 1350,
    'soulshots' => 1,
    'spiritshots' => 1,
    'is_tradable' => false,
    'is_dropable' => false,
    'is_sellable' => false,
    'is_depositable' => false,
    'item_skill' => 
    [
      0 => 
      [
        'skill_id' => 3010,
        'level' => 6,
      ],
    ],
    'time' => 43200,
    'enchanted' => 4,
    'stats' => 
    [
      'pAtk' => 194,
      'mAtk' => 99,
      'critRate' => 8,
      'pAtkSpd' => 379,
    ],
  ],
  15050 => 
  [
    'id' => 15050,
    'type' => 'weapon',
    'name' => 'Samurai Longsword of Fortune - 30-day limited period',
    'add_name' => '30-day limited period',
    'description' => 'Increases Critical by 73. No exchange/drop available',
    'icon' => 'weapon_samurai_longsword_i01',
    'weapon_type' => 'sword',
    'bodypart' => 'rhand',
    'crystal_type' => 'c',
    'weight' => 1380,
    'soulshots' => 3,
    'spiritshots' => 3,
    'is_tradable' => false,
    'is_dropable' => false,
    'is_sellable' => false,
    'is_depositable' => false,
    'item_skill' => 
    [
      0 => 
      [
        'skill_id' => 3010,
        'level' => 4,
      ],
    ],
    'time' => 43200,
    'enchanted' => 4,
    'stats' => 
    [
      'pAtk' => 156,
      'mAtk' => 83,
      'critRate' => 8,
      'pAtkSpd' => 379,
    ],
  ],
  15051 => 
  [
    'id' => 15051,
    'type' => 'weapon',
    'name' => 'Elven Long Sword of Fortune - 30-day limited period',
    'add_name' => '30-day limited period',
    'description' => 'No exchange/drop available',
    'icon' => 'weapon_elven_long_sword_i00',
    'weapon_type' => 'sword',
    'bodypart' => 'rhand',
    'crystal_type' => 'd',
    'weight' => 1440,
    'soulshots' => 3,
    'spiritshots' => 3,
    'is_tradable' => false,
    'is_dropable' => false,
    'is_sellable' => false,
    'is_depositable' => false,
    'time' => 43200,
    'enchanted' => 4,
    'stats' => 
    [
      'pAtk' => 92,
      'mAtk' => 54,
      'critRate' => 8,
      'pAtkSpd' => 379,
    ],
  ],
  15052 => 
  [
    'id' => 15052,
    'type' => 'weapon',
    'name' => 'Fortune Sword of Ipos - 30-day limited period',
    'add_name' => '30-day limited period',
    'description' => 'Increases Critical by 61, and increases damage inflicted during PvP. No exchange/drop available',
    'icon' => 'weapon_sword_of_ipos_i01',
    'weapon_type' => 'sword',
    'bodypart' => 'lrhand',
    'crystal_type' => 'a',
    'weight' => 1820,
    'soulshots' => 1,
    'spiritshots' => 1,
    'is_tradable' => false,
    'is_dropable' => false,
    'is_sellable' => false,
    'is_depositable' => false,
    'item_skill' => 
    [
      0 => 
      [
        'skill_id' => 3050,
        'level' => 2,
      ],
    ],
    'time' => 43200,
    'enchanted' => 4,
    'stats' => 
    [
      'pAtk' => 305,
      'mAtk' => 121,
      'critRate' => 8,
      'pAtkSpd' => 325,
    ],
  ],
  15053 => 
  [
    'id' => 15053,
    'type' => 'weapon',
    'name' => 'Guardian Sword of Fortune - 30-day limited period',
    'add_name' => '30-day limited period',
    'description' => 'Max HP increases by 25%. No exchange/drop available',
    'icon' => 'weapon_guardians_sword_i01',
    'weapon_type' => 'sword',
    'bodypart' => 'lrhand',
    'crystal_type' => 'b',
    'weight' => 1930,
    'soulshots' => 1,
    'spiritshots' => 1,
    'is_tradable' => false,
    'is_dropable' => false,
    'is_sellable' => false,
    'is_depositable' => false,
    'item_skill' => 
    [
      0 => 
      [
        'skill_id' => 3013,
        'level' => 1,
      ],
    ],
    'time' => 43200,
    'enchanted' => 4,
    'stats' => 
    [
      'pAtk' => 236,
      'mAtk' => 99,
      'critRate' => 8,
      'pAtkSpd' => 325,
    ],
  ],
  15054 => 
  [
    'id' => 15054,
    'type' => 'weapon',
    'name' => 'Berserker Blade of Fortune - 30-day limited period',
    'add_name' => '30-day limited period',
    'description' => 'Increases Critical by 73. No exchange/drop available',
    'icon' => 'weapon_berserker_blade_i01',
    'weapon_type' => 'sword',
    'bodypart' => 'lrhand',
    'crystal_type' => 'c',
    'weight' => 1380,
    'soulshots' => 3,
    'spiritshots' => 3,
    'is_tradable' => false,
    'is_dropable' => false,
    'is_sellable' => false,
    'is_depositable' => false,
    'item_skill' => 
    [
      0 => 
      [
        'skill_id' => 3010,
        'level' => 4,
      ],
    ],
    'time' => 43200,
    'enchanted' => 4,
    'stats' => 
    [
      'pAtk' => 190,
      'mAtk' => 83,
      'critRate' => 8,
      'pAtkSpd' => 325,
    ],
  ],
  15055 => 
  [
    'id' => 15055,
    'type' => 'weapon',
    'name' => 'Claymore of Fortune - 30-day limited period',
    'add_name' => '30-day limited period',
    'description' => 'No exchange/drop available',
    'icon' => 'weapon_claymore_i00',
    'weapon_type' => 'sword',
    'bodypart' => 'lrhand',
    'crystal_type' => 'd',
    'weight' => 2090,
    'soulshots' => 3,
    'spiritshots' => 3,
    'is_tradable' => false,
    'is_dropable' => false,
    'is_sellable' => false,
    'is_depositable' => false,
    'time' => 43200,
    'enchanted' => 4,
    'stats' => 
    [
      'pAtk' => 112,
      'mAtk' => 54,
      'critRate' => 8,
      'pAtkSpd' => 325,
    ],
  ],
  15056 => 
  [
    'id' => 15056,
    'type' => 'weapon',
    'name' => 'Sobekk\'s Hurricane of Fortune - 30-day limited period',
    'add_name' => '30-day limited period',
    'description' => 'Atk. Spd. increases by about 6%, and increases damage inflicted during PvP. No exchange/drop available',
    'icon' => 'weapon_sobekk_hurricane_i01',
    'weapon_type' => 'dualfist',
    'bodypart' => 'lrhand',
    'crystal_type' => 'a',
    'weight' => 1330,
    'soulshots' => 1,
    'spiritshots' => 1,
    'is_tradable' => false,
    'is_dropable' => false,
    'is_sellable' => false,
    'is_depositable' => false,
    'item_skill' => 
    [
      0 => 
      [
        'skill_id' => 3068,
        'level' => 3,
      ],
    ],
    'time' => 43200,
    'enchanted' => 4,
    'stats' => 
    [
      'pAtk' => 305,
      'mAtk' => 121,
      'critRate' => 4,
      'pAtkSpd' => 325,
    ],
  ],
  15057 => 
  [
    'id' => 15057,
    'type' => 'weapon',
    'name' => 'Bellion Cestus of Fortune - 30-day limited period',
    'add_name' => '30-day limited period',
    'description' => 'Atk. Spd. increases by 9% when HP is below 60%. No exchange/drop available',
    'icon' => 'weapon_bellion_cestus_i01',
    'weapon_type' => 'dualfist',
    'bodypart' => 'lrhand',
    'crystal_type' => 'b',
    'weight' => 1390,
    'soulshots' => 1,
    'spiritshots' => 1,
    'is_tradable' => false,
    'is_dropable' => false,
    'is_sellable' => false,
    'is_depositable' => false,
    'item_skill' => 
    [
      0 => 
      [
        'skill_id' => 3034,
        'level' => 6,
      ],
    ],
    'time' => 43200,
    'enchanted' => 4,
    'stats' => 
    [
      'pAtk' => 236,
      'mAtk' => 99,
      'critRate' => 4,
      'pAtkSpd' => 325,
    ],
  ],
  15058 => 
  [
    'id' => 15058,
    'type' => 'weapon',
    'name' => 'Great Pata of Fortune - 30-day limited period',
    'add_name' => '30-day limited period',
    'description' => 'Atk. Spd. increases by 11% when HP is below 60%. No exchange/drop available',
    'icon' => 'weapon_great_pata_i01',
    'weapon_type' => 'dualfist',
    'bodypart' => 'lrhand',
    'crystal_type' => 'c',
    'weight' => 1460,
    'soulshots' => 3,
    'spiritshots' => 3,
    'is_tradable' => false,
    'is_dropable' => false,
    'is_sellable' => false,
    'is_depositable' => false,
    'item_skill' => 
    [
      0 => 
      [
        'skill_id' => 3034,
        'level' => 4,
      ],
    ],
    'time' => 43200,
    'enchanted' => 4,
    'stats' => 
    [
      'pAtk' => 190,
      'mAtk' => 83,
      'critRate' => 4,
      'pAtkSpd' => 325,
    ],
  ],
  15059 => 
  [
    'id' => 15059,
    'type' => 'weapon',
    'name' => 'Scallop Jamadhr of Fortune - 30-day limited period',
    'add_name' => '30-day limited period',
    'description' => 'No exchange/drop available',
    'icon' => 'weapon_scallop_jamadhr_i00',
    'weapon_type' => 'dualfist',
    'bodypart' => 'lrhand',
    'crystal_type' => 'd',
    'weight' => 1520,
    'soulshots' => 3,
    'spiritshots' => 3,
    'is_tradable' => false,
    'is_dropable' => false,
    'is_sellable' => false,
    'is_depositable' => false,
    'time' => 43200,
    'enchanted' => 4,
    'stats' => 
    [
      'pAtk' => 112,
      'mAtk' => 54,
      'critRate' => 4,
      'pAtkSpd' => 325,
    ],
  ],
  15060 => 
  [
    'id' => 15060,
    'type' => 'weapon',
    'name' => 'Tallum Blade*Damascus of Fortune - 30-day limited period',
    'add_name' => '30-day limited period',
    'description' => 'Increases Atk. Spd. by 8%, and increases damage inflicted during PvP. No exchange/drop available',
    'icon' => 'weapon_dual_sword_i00',
    'weapon_type' => 'dual',
    'bodypart' => 'lrhand',
    'crystal_type' => 'a',
    'weight' => 1890,
    'soulshots' => 1,
    'spiritshots' => 1,
    'is_tradable' => false,
    'is_dropable' => false,
    'is_sellable' => false,
    'is_depositable' => false,
    'time' => 43200,
    'enchanted' => 4,
    'stats' => 
    [
      'pAtk' => 305,
      'mAtk' => 121,
      'critRate' => 8,
      'pAtkSpd' => 325,
    ],
  ],
  15061 => 
  [
    'id' => 15061,
    'type' => 'weapon',
    'name' => 'Samurai Long Sword*Samurai Long Sword of Fortune - 30-day limited period',
    'add_name' => '30-day limited period',
    'description' => 'Atk. Spd. increases by 4%. No exchange/drop available',
    'icon' => 'weapon_dual_sword_i00',
    'weapon_type' => 'dual',
    'bodypart' => 'lrhand',
    'crystal_type' => 'b',
    'weight' => 2080,
    'soulshots' => 1,
    'spiritshots' => 1,
    'is_tradable' => false,
    'is_dropable' => false,
    'is_sellable' => false,
    'is_depositable' => false,
    'time' => 43200,
    'enchanted' => 4,
    'stats' => 
    [
      'pAtk' => 236,
      'mAtk' => 99,
      'critRate' => 8,
      'pAtkSpd' => 325,
    ],
  ],
  15062 => 
  [
    'id' => 15062,
    'type' => 'weapon',
    'name' => 'Spirit Sword*Raid Sword of Fortune - 30-day limited period',
    'add_name' => '30-day limited period',
    'description' => 'Increases Critical by 40. No exchange/drop available',
    'icon' => 'weapon_dual_sword_i00',
    'weapon_type' => 'dual',
    'bodypart' => 'lrhand',
    'crystal_type' => 'c',
    'weight' => 2260,
    'soulshots' => 3,
    'spiritshots' => 3,
    'is_tradable' => false,
    'is_dropable' => false,
    'is_sellable' => false,
    'is_depositable' => false,
    'time' => 43200,
    'enchanted' => 4,
    'stats' => 
    [
      'pAtk' => 190,
      'mAtk' => 83,
      'critRate' => 8,
      'pAtkSpd' => 325,
    ],
  ],
  15063 => 
  [
    'id' => 15063,
    'type' => 'weapon',
    'name' => 'Bastard Sword*Elven Sword of Fortune - 30-day limited period',
    'add_name' => '30-day limited period',
    'description' => 'No exchange/drop available',
    'icon' => 'weapon_dual_sword_i00',
    'weapon_type' => 'dual',
    'bodypart' => 'lrhand',
    'crystal_type' => 'd',
    'weight' => 2460,
    'soulshots' => 3,
    'spiritshots' => 3,
    'is_tradable' => false,
    'is_dropable' => false,
    'is_sellable' => false,
    'is_depositable' => false,
    'time' => 43200,
    'enchanted' => 4,
    'stats' => 
    [
      'pAtk' => 107,
      'mAtk' => 51,
      'critRate' => 8,
      'pAtkSpd' => 325,
    ],
  ],
  15064 => 
  [
    'id' => 15064,
    'type' => 'weapon',
    'name' => 'Tiphon\'s Spear of Fortune - 30-day limited period',
    'add_name' => '30-day limited period',
    'description' => 'Attack angle widens, and increases damage inflicted during PvP. No exchange/drop available',
    'icon' => 'weapon_tiphon_spear_i01',
    'weapon_type' => 'pole',
    'bodypart' => 'lrhand',
    'crystal_type' => 'a',
    'weight' => 1820,
    'soulshots' => 1,
    'spiritshots' => 1,
    'is_tradable' => false,
    'is_dropable' => false,
    'is_sellable' => false,
    'is_depositable' => false,
    'item_skill' => 
    [
      0 => 
      [
        'skill_id' => 3552,
        'level' => 2,
      ],
    ],
    'time' => 43200,
    'enchanted' => 4,
    'stats' => 
    [
      'pAtk' => 251,
      'mAtk' => 121,
      'critRate' => 8,
      'pAtkSpd' => 325,
    ],
  ],
  15065 => 
  [
    'id' => 15065,
    'type' => 'weapon',
    'name' => 'Lance of Fortune - 30-day limited period',
    'add_name' => '30-day limited period',
    'description' => 'Range increases. No exchange/drop available',
    'icon' => 'weapon_lancia_i01',
    'weapon_type' => 'pole',
    'bodypart' => 'lrhand',
    'crystal_type' => 'b',
    'weight' => 1920,
    'soulshots' => 1,
    'spiritshots' => 1,
    'is_tradable' => false,
    'is_dropable' => false,
    'is_sellable' => false,
    'is_depositable' => false,
    'item_skill' => 
    [
      0 => 
      [
        'skill_id' => 3599,
        'level' => 1,
      ],
    ],
    'time' => 43200,
    'enchanted' => 4,
    'stats' => 
    [
      'pAtk' => 194,
      'mAtk' => 99,
      'critRate' => 8,
      'pAtkSpd' => 325,
    ],
  ],
  15066 => 
  [
    'id' => 15066,
    'type' => 'weapon',
    'name' => 'Orcish Poleaxe of Fortune - 30-day limited period',
    'add_name' => '30-day limited period',
    'description' => 'Attack angle widens. No exchange/drop available',
    'icon' => 'weapon_orcish_poleaxe_i01',
    'weapon_type' => 'pole',
    'bodypart' => 'lrhand',
    'crystal_type' => 'c',
    'weight' => 1950,
    'soulshots' => 3,
    'spiritshots' => 3,
    'is_tradable' => false,
    'is_dropable' => false,
    'is_sellable' => false,
    'is_depositable' => false,
    'item_skill' => 
    [
      0 => 
      [
        'skill_id' => 3599,
        'level' => 1,
      ],
    ],
    'time' => 43200,
    'enchanted' => 4,
    'stats' => 
    [
      'pAtk' => 156,
      'mAtk' => 83,
      'critRate' => 8,
      'pAtkSpd' => 325,
    ],
  ],
  15067 => 
  [
    'id' => 15067,
    'type' => 'weapon',
    'name' => 'Glaive of Fortune - 30-day limited period',
    'add_name' => '30-day limited period',
    'description' => 'No exchange/drop available',
    'icon' => 'weapon_glaive_i00',
    'weapon_type' => 'pole',
    'bodypart' => 'lrhand',
    'crystal_type' => 'd',
    'weight' => 2050,
    'soulshots' => 3,
    'spiritshots' => 3,
    'is_tradable' => false,
    'is_dropable' => false,
    'is_sellable' => false,
    'is_depositable' => false,
    'item_skill' => 
    [
      0 => 
      [
        'skill_id' => 3599,
        'level' => 1,
      ],
    ],
    'time' => 43200,
    'enchanted' => 4,
    'stats' => 
    [
      'pAtk' => 92,
      'mAtk' => 54,
      'critRate' => 8,
      'pAtkSpd' => 325,
    ],
  ],
  15068 => 
  [
    'id' => 15068,
    'type' => 'weapon',
    'name' => 'Durendal of Fortune - 30-day limited period',
    'add_name' => '30-day limited period',
    'description' => 'Kamael Exclusive Weapon. Increases Critical by 61, and increases damage inflicted during PvP. No exchange/drop available',
    'icon' => 'weapon_death_bringer_i01',
    'weapon_type' => 'ancientsword',
    'bodypart' => 'lrhand',
    'crystal_type' => 'a',
    'weight' => 1820,
    'soulshots' => 1,
    'spiritshots' => 1,
    'is_tradable' => false,
    'is_dropable' => false,
    'is_sellable' => false,
    'is_depositable' => false,
    'item_skill' => 
    [
      0 => 
      [
        'skill_id' => 3050,
        'level' => 2,
      ],
    ],
    'time' => 43200,
    'enchanted' => 4,
    'stats' => 
    [
      'pAtk' => 272,
      'mAtk' => 121,
      'critRate' => 8,
      'pAtkSpd' => 350,
    ],
  ],
  15069 => 
  [
    'id' => 15069,
    'type' => 'weapon',
    'name' => 'Dismantler of Fortune - 30-day limited period',
    'add_name' => '30-day limited period',
    'description' => 'Kamael Exclusive Weapon. Max HP increases by 25%. No exchange/drop available',
    'icon' => 'weapon_dismantler_i01',
    'weapon_type' => 'ancientsword',
    'bodypart' => 'lrhand',
    'crystal_type' => 'b',
    'weight' => 1930,
    'soulshots' => 1,
    'spiritshots' => 1,
    'is_tradable' => false,
    'is_dropable' => false,
    'is_sellable' => false,
    'is_depositable' => false,
    'item_skill' => 
    [
      0 => 
      [
        'skill_id' => 3013,
        'level' => 1,
      ],
    ],
    'time' => 43200,
    'enchanted' => 4,
    'stats' => 
    [
      'pAtk' => 210,
      'mAtk' => 99,
      'critRate' => 8,
      'pAtkSpd' => 350,
    ],
  ],
  15070 => 
  [
    'id' => 15070,
    'type' => 'weapon',
    'name' => 'Saber Tooth of Fortune - 30-day limited period',
    'add_name' => '30-day limited period',
    'description' => 'Kamael Exclusive Weapon. Increases Critical by 73. No exchange/drop available',
    'icon' => 'weapon_invincible_blade_i01',
    'weapon_type' => 'ancientsword',
    'bodypart' => 'lrhand',
    'crystal_type' => 'c',
    'weight' => 1950,
    'soulshots' => 3,
    'spiritshots' => 3,
    'is_tradable' => false,
    'is_dropable' => false,
    'is_sellable' => false,
    'is_depositable' => false,
    'item_skill' => 
    [
      0 => 
      [
        'skill_id' => 3010,
        'level' => 4,
      ],
    ],
    'time' => 43200,
    'enchanted' => 4,
    'stats' => 
    [
      'pAtk' => 169,
      'mAtk' => 83,
      'critRate' => 8,
      'pAtkSpd' => 350,
    ],
  ],
  15071 => 
  [
    'id' => 15071,
    'type' => 'weapon',
    'name' => 'General\'s Katzbalger of Fortune - 30-day limited period',
    'add_name' => '30-day limited period',
    'description' => 'Kamael Exclusive Weapon. No exchange/drop available',
    'icon' => 'weapon_tulwar_i00',
    'weapon_type' => 'ancientsword',
    'bodypart' => 'lrhand',
    'crystal_type' => 'd',
    'weight' => 2010,
    'soulshots' => 3,
    'spiritshots' => 3,
    'is_tradable' => false,
    'is_dropable' => false,
    'is_sellable' => false,
    'is_depositable' => false,
    'time' => 43200,
    'enchanted' => 4,
    'stats' => 
    [
      'pAtk' => 100,
      'mAtk' => 54,
      'critRate' => 8,
      'pAtkSpd' => 350,
    ],
  ],
  15072 => 
  [
    'id' => 15072,
    'type' => 'weapon',
    'name' => 'Éclair Bijou of Fortune - 30-day limited period',
    'add_name' => '30-day limited period',
    'description' => 'Kamael Exclusive Weapon. Atk. Spd. increases by about 6%, and increases damage inflicted during PvP. Improves the chance that party members including yourself will get increased P. Atk., M. Atk. and the amount of recieved heal, and decreased MP consumption per skill during a critical attack. No exchange/drop available',
    'icon' => 'weapon_greed_stinger_i01',
    'weapon_type' => 'rapier',
    'bodypart' => 'rhand',
    'crystal_type' => 'a',
    'weight' => 1300,
    'soulshots' => 1,
    'spiritshots' => 1,
    'is_tradable' => false,
    'is_dropable' => false,
    'is_sellable' => false,
    'is_depositable' => false,
    'item_skill' => 
    [
      0 => 
      [
        'skill_id' => 3068,
        'level' => 3,
      ],
    ],
    'time' => 43200,
    'enchanted' => 4,
    'stats' => 
    [
      'pAtk' => 228,
      'mAtk' => 121,
      'critRate' => 10,
      'pAtkSpd' => 406,
    ],
  ],
  15073 => 
  [
    'id' => 15073,
    'type' => 'weapon',
    'name' => 'Colichemarde of Fortune - 30-day limited period',
    'add_name' => '30-day limited period',
    'description' => 'Kamael Exclusive Weapon. Increases Atk. Spd. by about 6%, and improves the chance that party members including yourself will get increased P. Atk., M. Atk. and the amount of recieved heal, and decreased MP consumption per skill during a critical attack. No exchange/drop available',
    'icon' => 'weapon_colichemarde_i01',
    'weapon_type' => 'rapier',
    'bodypart' => 'rhand',
    'crystal_type' => 'b',
    'weight' => 1350,
    'soulshots' => 1,
    'spiritshots' => 1,
    'is_tradable' => false,
    'is_dropable' => false,
    'is_sellable' => false,
    'is_depositable' => false,
    'item_skill' => 
    [
      0 => 
      [
        'skill_id' => 3036,
        'level' => 6,
      ],
    ],
    'time' => 43200,
    'enchanted' => 4,
    'stats' => 
    [
      'pAtk' => 176,
      'mAtk' => 99,
      'critRate' => 10,
      'pAtkSpd' => 406,
    ],
  ],
  15074 => 
  [
    'id' => 15074,
    'type' => 'weapon',
    'name' => 'Admiral\'s Estoc of Fortune - 30-day limited period',
    'add_name' => '30-day limited period',
    'description' => 'Kamael Exclusive Weapon. Increases Atk. Spd. by about 7%, and improves the chance that party members including yourself will get increased P. Atk., M. Atk. and the amount of recieved heal, and decreased MP consumption per skill during a critical attack. No exchange/drop available',
    'icon' => 'weapon_blink_slasher_i01',
    'weapon_type' => 'rapier',
    'bodypart' => 'rhand',
    'crystal_type' => 'c',
    'weight' => 1380,
    'soulshots' => 3,
    'spiritshots' => 3,
    'is_tradable' => false,
    'is_dropable' => false,
    'is_sellable' => false,
    'is_depositable' => false,
    'item_skill' => 
    [
      0 => 
      [
        'skill_id' => 3036,
        'level' => 4,
      ],
    ],
    'time' => 43200,
    'enchanted' => 4,
    'stats' => 
    [
      'pAtk' => 141,
      'mAtk' => 83,
      'critRate' => 10,
      'pAtkSpd' => 406,
    ],
  ],
  15075 => 
  [
    'id' => 15075,
    'type' => 'weapon',
    'name' => 'Grand Epee of Fortune - 30-day limited period',
    'add_name' => '30-day limited period',
    'description' => 'Kamael Exclusive Weapon. Improves the chance that party members including yourself will get increased P. Atk., M. Atk. and the amount of recieved heal, and decreased MP consumption per skill during a critical attack. No exchange/drop available',
    'icon' => 'weapon_rapier_i00',
    'weapon_type' => 'rapier',
    'bodypart' => 'rhand',
    'crystal_type' => 'd',
    'weight' => 1440,
    'soulshots' => 3,
    'spiritshots' => 3,
    'is_tradable' => false,
    'is_dropable' => false,
    'is_sellable' => false,
    'is_depositable' => false,
    'time' => 43200,
    'enchanted' => 4,
    'stats' => 
    [
      'pAtk' => 83,
      'mAtk' => 54,
      'critRate' => 10,
      'pAtkSpd' => 406,
    ],
  ],
  15076 => 
  [
    'id' => 15076,
    'type' => 'weapon',
    'name' => 'Screaming Vengeance of Fortune - 30-day limited period',
    'add_name' => '30-day limited period',
    'description' => 'Kamael Exclusive Weapon. Increases Critical by 61, and increases damage inflicted during PvP. No exchange/drop available',
    'icon' => 'weapon_soul_shooter_i01',
    'weapon_type' => 'crossbow',
    'bodypart' => 'lrhand',
    'crystal_type' => 'a',
    'weight' => 1640,
    'soulshots' => 1,
    'spiritshots' => 1,
    'is_tradable' => false,
    'is_dropable' => false,
    'is_sellable' => false,
    'is_depositable' => false,
    'item_skill' => 
    [
      0 => 
      [
        'skill_id' => 3050,
        'level' => 2,
      ],
    ],
    'time' => 43200,
    'enchanted' => 4,
    'stats' => 
    [
      'pAtk' => 318,
      'mAtk' => 121,
      'critRate' => 10,
      'pAtkSpd' => 303,
    ],
  ],
  15077 => 
  [
    'id' => 15077,
    'type' => 'weapon',
    'name' => 'Hell Hound of Fortune - 30-day limited period',
    'add_name' => '30-day limited period',
    'description' => 'Kamael Exclusive Weapon. MP consumption decreases by about 12% during skill use. No exchange/drop available',
    'icon' => 'weapon_hell_hound_i01',
    'weapon_type' => 'crossbow',
    'bodypart' => 'lrhand',
    'crystal_type' => 'b',
    'weight' => 1700,
    'soulshots' => 2,
    'spiritshots' => 1,
    'is_tradable' => false,
    'is_dropable' => false,
    'is_sellable' => false,
    'is_depositable' => false,
    'item_skill' => 
    [
      0 => 
      [
        'skill_id' => 3360,
        'level' => 1,
      ],
    ],
    'time' => 43200,
    'enchanted' => 4,
    'stats' => 
    [
      'pAtk' => 245,
      'mAtk' => 99,
      'critRate' => 10,
      'pAtkSpd' => 303,
    ],
  ],
  15078 => 
  [
    'id' => 15078,
    'type' => 'weapon',
    'name' => 'Sharpshooter of Fortune - 30-day limited period',
    'add_name' => '30-day limited period',
    'description' => 'Kamael Exclusive Weapon. MP consumption decreases by about 12% during skill use. No exchange/drop available',
    'icon' => 'weapon_taslam_i01',
    'weapon_type' => 'crossbow',
    'bodypart' => 'lrhand',
    'crystal_type' => 'c',
    'weight' => 1740,
    'soulshots' => 6,
    'spiritshots' => 3,
    'is_tradable' => false,
    'is_dropable' => false,
    'is_sellable' => false,
    'is_depositable' => false,
    'item_skill' => 
    [
      0 => 
      [
        'skill_id' => 3360,
        'level' => 1,
      ],
    ],
    'time' => 43200,
    'enchanted' => 4,
    'stats' => 
    [
      'pAtk' => 198,
      'mAtk' => 83,
      'critRate' => 10,
      'pAtkSpd' => 303,
    ],
  ],
  15079 => 
  [
    'id' => 15079,
    'type' => 'weapon',
    'name' => 'Cranequin of Fortune - 30-day limited period',
    'add_name' => '30-day limited period',
    'description' => 'Kamael Exclusive Weapon. No exchange/drop available',
    'icon' => 'weapon_hunting_gun_i00',
    'weapon_type' => 'crossbow',
    'bodypart' => 'lrhand',
    'crystal_type' => 'd',
    'weight' => 1810,
    'soulshots' => 6,
    'spiritshots' => 3,
    'is_tradable' => false,
    'is_dropable' => false,
    'is_sellable' => false,
    'is_depositable' => false,
    'time' => 43200,
    'enchanted' => 4,
    'stats' => 
    [
      'pAtk' => 117,
      'mAtk' => 54,
      'critRate' => 10,
      'pAtkSpd' => 303,
    ],
  ],
  15080 => 
  [
    'id' => 15080,
    'type' => 'armor',
    'name' => 'Majestic Earring of Fortune - 10-day limited period',
    'add_name' => '10-day limited period',
    'description' => 'The effect is MP +25. No exchange/drop available',
    'icon' => 'accessary_inferno_earing_i00',
    'bodypart' => 'rear;lear',
    'crystal_type' => 'a',
    'weight' => 150,
    'is_tradable' => false,
    'is_dropable' => false,
    'is_sellable' => false,
    'is_depositable' => false,
    'time' => 14400,
    'stats' => 
    [
    ],
  ],
  15081 => 
  [
    'id' => 15081,
    'type' => 'armor',
    'name' => 'Majestic Necklace of Fortune - 10-day limited period',
    'add_name' => '10-day limited period',
    'description' => 'The effect is MP +33. No exchange/drop available',
    'icon' => 'accessary_inferno_necklace_i00',
    'bodypart' => 'neck',
    'crystal_type' => 'a',
    'weight' => 150,
    'is_tradable' => false,
    'is_dropable' => false,
    'is_sellable' => false,
    'is_depositable' => false,
    'time' => 14400,
    'stats' => 
    [
    ],
  ],
  15082 => 
  [
    'id' => 15082,
    'type' => 'armor',
    'name' => 'Majestic Ring of Fortune - 10-day limited period',
    'add_name' => '10-day limited period',
    'description' => 'The effect is MP +17. No exchange/drop available',
    'icon' => 'accessary_inferno_ring_i00',
    'bodypart' => 'rfinger;lfinger',
    'crystal_type' => 'a',
    'weight' => 150,
    'is_tradable' => false,
    'is_dropable' => false,
    'is_sellable' => false,
    'is_depositable' => false,
    'time' => 14400,
    'stats' => 
    [
    ],
  ],
  15083 => 
  [
    'id' => 15083,
    'type' => 'armor',
    'name' => 'Fortune Earring of Black Ore - 10-day limited period',
    'add_name' => '10-day limited period',
    'description' => 'No exchange/drop available',
    'icon' => 'accessary_earing_of_black_ore_i00',
    'bodypart' => 'rear;lear',
    'crystal_type' => 'b',
    'weight' => 150,
    'is_tradable' => false,
    'is_dropable' => false,
    'is_sellable' => false,
    'is_depositable' => false,
    'time' => 14400,
    'stats' => 
    [
    ],
  ],
  15084 => 
  [
    'id' => 15084,
    'type' => 'armor',
    'name' => 'Fortune Necklace of Black Ore - 10-day limited period',
    'add_name' => '10-day limited period',
    'description' => 'No exchange/drop available',
    'icon' => 'accessary_necklace_of_black_ore_i00',
    'bodypart' => 'neck',
    'crystal_type' => 'b',
    'weight' => 150,
    'is_tradable' => false,
    'is_dropable' => false,
    'is_sellable' => false,
    'is_depositable' => false,
    'time' => 14400,
    'stats' => 
    [
    ],
  ],
  15085 => 
  [
    'id' => 15085,
    'type' => 'armor',
    'name' => 'Fortune Ring of Black Ore - 10-day limited period',
    'add_name' => '10-day limited period',
    'description' => 'No exchange/drop available',
    'icon' => 'accessary_ring_of_black_ore_i00',
    'bodypart' => 'rfinger;lfinger',
    'crystal_type' => 'b',
    'weight' => 150,
    'is_tradable' => false,
    'is_dropable' => false,
    'is_sellable' => false,
    'is_depositable' => false,
    'time' => 14400,
    'stats' => 
    [
    ],
  ],
  15086 => 
  [
    'id' => 15086,
    'type' => 'armor',
    'name' => 'Fortune Earring of Seal - 10-day limited period',
    'add_name' => '10-day limited period',
    'description' => 'No exchange/drop available',
    'icon' => 'accessary_earing_of_binding_i00',
    'bodypart' => 'rear;lear',
    'crystal_type' => 'c',
    'weight' => 150,
    'is_tradable' => false,
    'is_dropable' => false,
    'is_sellable' => false,
    'is_depositable' => false,
    'time' => 14400,
    'stats' => 
    [
    ],
  ],
  15087 => 
  [
    'id' => 15087,
    'type' => 'armor',
    'name' => 'Fortune Necklace of Seal - 10-day limited period',
    'add_name' => '10-day limited period',
    'description' => 'No exchange/drop available',
    'icon' => 'accessary_necklace_of_binding_i00',
    'bodypart' => 'neck',
    'crystal_type' => 'c',
    'weight' => 150,
    'is_tradable' => false,
    'is_dropable' => false,
    'is_sellable' => false,
    'is_depositable' => false,
    'time' => 14400,
    'stats' => 
    [
    ],
  ],
  15088 => 
  [
    'id' => 15088,
    'type' => 'armor',
    'name' => 'Fortune Ring of Seal - 10-day limited period',
    'add_name' => '10-day limited period',
    'description' => 'No exchange/drop available',
    'icon' => 'accessary_ring_of_binding_i00',
    'bodypart' => 'rfinger;lfinger',
    'crystal_type' => 'c',
    'weight' => 150,
    'is_tradable' => false,
    'is_dropable' => false,
    'is_sellable' => false,
    'is_depositable' => false,
    'time' => 14400,
    'stats' => 
    [
    ],
  ],
  15089 => 
  [
    'id' => 15089,
    'type' => 'armor',
    'name' => 'Elven Earring of Fortune - 10-day limited period',
    'add_name' => '10-day limited period',
    'description' => 'No exchange/drop available',
    'icon' => 'accessary_elven_earing_i00',
    'bodypart' => 'rear;lear',
    'crystal_type' => 'd',
    'weight' => 150,
    'is_tradable' => false,
    'is_dropable' => false,
    'is_sellable' => false,
    'is_depositable' => false,
    'time' => 14400,
    'stats' => 
    [
    ],
  ],
  15090 => 
  [
    'id' => 15090,
    'type' => 'armor',
    'name' => 'Elven Earring of Fortune - 10-day limited period',
    'add_name' => '10-day limited period',
    'description' => 'No exchange/drop available',
    'icon' => 'accessary_elven_necklace_i00',
    'bodypart' => 'neck',
    'crystal_type' => 'd',
    'weight' => 150,
    'is_tradable' => false,
    'is_dropable' => false,
    'is_sellable' => false,
    'is_depositable' => false,
    'time' => 14400,
    'stats' => 
    [
    ],
  ],
  15091 => 
  [
    'id' => 15091,
    'type' => 'armor',
    'name' => 'Elven Ring of Fortune - 10-day limited period',
    'add_name' => '10-day limited period',
    'description' => 'No exchange/drop available',
    'icon' => 'accessary_elven_ring_i00',
    'bodypart' => 'rfinger;lfinger',
    'crystal_type' => 'd',
    'weight' => 150,
    'is_tradable' => false,
    'is_dropable' => false,
    'is_sellable' => false,
    'is_depositable' => false,
    'time' => 14400,
    'stats' => 
    [
    ],
  ],
  15092 => 
  [
    'id' => 15092,
    'type' => 'armor',
    'name' => 'Dark Crystal Robe of Fortune - 10-day limited period',
    'add_name' => '10-day limited period',
    'description' => 'One-piece Body Armor. No exchange/drop available',
    'icon' => 'armor_t76_ul_i00',
    'armor_type' => 'magic',
    'bodypart' => 'onepiece',
    'crystal_type' => 'a',
    'weight' => 2450,
    'is_tradable' => false,
    'is_dropable' => false,
    'is_sellable' => false,
    'is_depositable' => false,
    'time' => 14400,
    'stats' => 
    [
    ],
  ],
  15093 => 
  [
    'id' => 15093,
    'type' => 'armor',
    'name' => 'Dark Crystal Helmet of Fortune - 10-day limited period',
    'add_name' => '10-day limited period',
    'description' => 'No exchange/drop available',
    'icon' => 'armor_helmet_i00',
    'bodypart' => 'head',
    'crystal_type' => 'a',
    'weight' => 570,
    'is_tradable' => false,
    'is_dropable' => false,
    'is_sellable' => false,
    'is_depositable' => false,
    'time' => 14400,
    'stats' => 
    [
    ],
  ],
  15094 => 
  [
    'id' => 15094,
    'type' => 'armor',
    'name' => 'Dark Crystal Gloves of Fortune - Robe - 10-day limited period',
    'add_name' => '10-day limited period',
    'description' => 'Gloves that make a set with the Dark Crystal Robe of Fortune. No exchange/drop available',
    'icon' => 'armor_t76_g_i00',
    'bodypart' => 'gloves',
    'crystal_type' => 'a',
    'weight' => 580,
    'is_tradable' => false,
    'is_dropable' => false,
    'is_sellable' => false,
    'is_depositable' => false,
    'time' => 14400,
    'stats' => 
    [
    ],
  ],
  15095 => 
  [
    'id' => 15095,
    'type' => 'armor',
    'name' => 'Dark Crystal Boots of Fortune - Robe - 10-day limited period',
    'add_name' => '10-day limited period',
    'description' => 'Boots that make a set with the Dark Crystal Robe of Fortune. No exchange/drop available',
    'icon' => 'armor_t76_b_i00',
    'bodypart' => 'feet',
    'crystal_type' => 'a',
    'weight' => 1110,
    'is_tradable' => false,
    'is_dropable' => false,
    'is_sellable' => false,
    'is_depositable' => false,
    'time' => 14400,
    'stats' => 
    [
    ],
  ],
  15096 => 
  [
    'id' => 15096,
    'type' => 'armor',
    'name' => 'Dark Crystal Shield of Fortune - 10-day limited period',
    'add_name' => '10-day limited period',
    'description' => 'No exchange/drop available',
    'icon' => 'shield_dark_crystal_shield_i00',
    'bodypart' => 'lhand',
    'crystal_type' => 'a',
    'weight' => 1190,
    'is_tradable' => false,
    'is_dropable' => false,
    'is_sellable' => false,
    'is_depositable' => false,
    'time' => 14400,
    'stats' => 
    [
      'rShld' => 20,
      'sDef' => 243,
    ],
  ],
  15097 => 
  [
    'id' => 15097,
    'type' => 'armor',
    'name' => 'Avadon Robe of Fortune - 10-day limited period',
    'add_name' => '10-day limited period',
    'description' => 'One-piece Body Armor. No exchange/drop available',
    'icon' => 'armor_t59_ul_i00',
    'armor_type' => 'magic',
    'bodypart' => 'onepiece',
    'crystal_type' => 'b',
    'weight' => 2540,
    'is_tradable' => false,
    'is_dropable' => false,
    'is_sellable' => false,
    'is_depositable' => false,
    'time' => 14400,
    'stats' => 
    [
    ],
  ],
  15098 => 
  [
    'id' => 15098,
    'type' => 'armor',
    'name' => 'Avadon Circlet of Fortune - 10-day limited period',
    'add_name' => '10-day limited period',
    'description' => 'No exchange/drop available',
    'icon' => 'armor_leather_helmet_i00',
    'bodypart' => 'head',
    'crystal_type' => 'b',
    'weight' => 590,
    'is_tradable' => false,
    'is_dropable' => false,
    'is_sellable' => false,
    'is_depositable' => false,
    'time' => 14400,
    'stats' => 
    [
    ],
  ],
  15099 => 
  [
    'id' => 15099,
    'type' => 'armor',
    'name' => 'Avadon Gloves of Fortune - Robe - 10-day limited period',
    'add_name' => '10-day limited period',
    'description' => 'Gloves that make a set with the Avadon Robe of Fortune. No exchange/drop available',
    'icon' => 'armor_t59_g_i00',
    'bodypart' => 'gloves',
    'crystal_type' => 'b',
    'weight' => 590,
    'is_tradable' => false,
    'is_dropable' => false,
    'is_sellable' => false,
    'is_depositable' => false,
    'time' => 14400,
    'stats' => 
    [
    ],
  ],
];