<?php
return [
  22300 => 
  [
    'id' => 22300,
    'type' => 'etcitem',
    'name' => 'Miracle Happy Cake - Decoration - 15-day limited period (event]',
    'add_name' => '15-day limited period (event]',
    'description' => 'Take this along with a Perfect Happy Cake to the Valentine Messenger Queen of Hearts to complete a Miracle Happy Cake. Cannot be exchanged or dropped. Can be destroyed. Can be stored in a private warehouse.',
    'icon' => 'br_valentine_deco_i00',
    'weight' => 10,
    'is_tradable' => false,
    'is_dropable' => false,
    'time' => 21600,
  ],
  22301 => 
  [
    'id' => 22301,
    'type' => 'etcitem',
    'name' => 'Sweet Chocolate Cookie',
    'add_name' => 'Event',
    'description' => 'When used, energy is replenished by 5000 points. Re-use time is 60 minutes. Cannot be exchanged or dropped. Can be destroyed. Can be stored in a private warehouse.',
    'icon' => 'br_valentine_cookie_i00',
    'is_tradable' => false,
    'is_dropable' => false,
    'is_stackable' => true,
  ],
  22302 => 
  [
    'id' => 22302,
    'type' => 'armor',
    'name' => 'Antharas\'s Earring - 3-day limited period (event]',
    'add_name' => '3-day limited period (event]',
    'description' => 'MP +37, resistance to Bleed +40%, Bleed attack rate +40%, increases heal amount, vampiric rage effect, resistance to Stun/Mental attacks +30%, Stun/Mental attack rate +30%, decreases MP consumption, and increases heal amount and resistance to Earth. Only one effect is applied when two of the same earrings are equipped. Cannot be exchanged or dropped. Can be destroyed. Can be stored in a private warehouse.',
    'icon' => 'accessory_earring_of_antaras_i00',
    'bodypart' => 'rear;lear',
    'crystal_type' => 's',
    'weight' => 150,
    'is_tradable' => false,
    'is_dropable' => false,
    'time' => 4320,
    'stats' => 
    [
    ],
  ],
  22303 => 
  [
    'id' => 22303,
    'type' => 'armor',
    'name' => 'Antharas\'s Earring - 7-day limited period (event]',
    'add_name' => '7-day limited period (event]',
    'description' => 'MP +37, resistance to Bleed +40%, Bleed attack rate +40%, increases heal amount, vampiric rage effect, resistance to Stun/Mental attacks +30%, Stun/Mental attack rate +30%, decreases MP consumption, and increases heal amount and resistance to Earth. Only one effect is applied when two of the same earrings are equipped. Cannot be exchanged or dropped. Can be destroyed. Can be stored in a private warehouse.',
    'icon' => 'accessory_earring_of_antaras_i00',
    'bodypart' => 'rear;lear',
    'crystal_type' => 's',
    'weight' => 150,
    'is_tradable' => false,
    'is_dropable' => false,
    'time' => 10080,
    'stats' => 
    [
    ],
  ],
  22304 => 
  [
    'id' => 22304,
    'type' => 'armor',
    'name' => 'Baium\'s Ring - 3-day limited period (event]',
    'add_name' => '3-day limited period (event]',
    'description' => 'MP +21, resistance to Poison +40%, Poison attack rate +40%, resistance to Hold +30%, Hold attack rate +30%, and increases Accuracy, Critical Damage, P. Atk., and Casting Spd. Only one effect is applied when two of the same ring are equipped. Cannot be exchanged or dropped. Can be destroyed. Can be stored in a private warehouse.',
    'icon' => 'accessory_ring_of_baium_i00',
    'bodypart' => 'rfinger;lfinger',
    'crystal_type' => 's',
    'weight' => 150,
    'is_tradable' => false,
    'is_dropable' => false,
    'time' => 4320,
    'stats' => 
    [
    ],
  ],
  22305 => 
  [
    'id' => 22305,
    'type' => 'armor',
    'name' => 'Baium\'s Ring - 7-day limited period (event]',
    'add_name' => '7-day limited period (event]',
    'description' => 'MP +21, resistance to Poison +40%, Poison attack rate +40%, resistance to Hold +30%, Hold attack rate +30%, and increases Accuracy, Critical Damage, P. Atk., and Casting Spd. Only one effect is applied when two of the same ring are equipped.',
    'icon' => 'accessory_ring_of_baium_i00',
    'bodypart' => 'rfinger;lfinger',
    'crystal_type' => 's',
    'weight' => 150,
    'time' => 10080,
    'stats' => 
    [
    ],
  ],
  22306 => 
  [
    'id' => 22306,
    'type' => 'etcitem',
    'name' => 'Scroll: Enchant Weapon (S-Grade] - Event',
    'add_name' => 'Event',
    'description' => 'Increases P. Atk. by 5 for S-grade one-handed sword, one-handed blunt, dagger, spear, and other weapons when enchanted. Increases P. Atk. by 6 for two-handed sword, two-handed blunt, dualsword, and two-handed combat weapon. Increases P. Atk. by 10 for bow weapons. Increases M. Atk. by 4 for all weapons. P. Atk./M. Atk. increase by double starting at +4.',
    'icon' => 'etc_scroll_of_enchant_weapon_i05',
    'weight' => 120,
    'is_stackable' => true,
  ],
  22307 => 
  [
    'id' => 22307,
    'type' => 'etcitem',
    'name' => 'Scroll: Enchant Weapon (A-Grade] - Event',
    'add_name' => 'Event',
    'description' => 'Increases P. Atk. by 4 for A-grade one-handed sword, one-handed blunt, dagger, spear, and other weapons when enchanted. Increases P. Atk. by 5 for two-handed sword, two-handed blunt, dualsword, and two-handed combat weapon. Increases P. Atk. by 8 for bow weapons. Increases M. Atk. by 3 for all weapons. P. Atk./M. Atk. increase by double starting at +4.',
    'icon' => 'etc_scroll_of_enchant_weapon_i04',
    'weight' => 120,
    'is_stackable' => true,
  ],
  22308 => 
  [
    'id' => 22308,
    'type' => 'etcitem',
    'name' => 'Scroll: Enchant Armor (S-Grade] - Event',
    'add_name' => 'Event',
    'description' => 'Increases P. Def. by 1 for S-grade armor and accessories when enchanted. Increases by 3 starting from +4. It can safely be enchanted up to +3. For one-piece armor, it can safely be enchanted up to +4. When armor is enchanted above +4, HP also increases depending on the enchant value.',
    'icon' => 'etc_scroll_of_enchant_armor_i05',
    'weight' => 120,
    'is_stackable' => true,
  ],
  22309 => 
  [
    'id' => 22309,
    'type' => 'etcitem',
    'name' => 'Scroll: Enchant Armor (A-Grade] - Event',
    'add_name' => 'Event',
    'description' => 'Increases P. Def. by 1 for A-grade armor and accessories. Increases by 3 starting from +4. It can safely be enchanted up to +3. For one-piece armor, it can safely be enchanted up to +4. When armor is enchanted above +4, HP also increases depending on the enchant value.',
    'icon' => 'etc_scroll_of_enchant_armor_i04',
    'weight' => 120,
    'is_stackable' => true,
  ],
  22310 => 
  [
    'id' => 22310,
    'type' => 'etcitem',
    'name' => 'Allegra Box',
    'add_name' => '',
    'description' => 'There is a chance of obtaining a high-grade transformation scroll, Blessed Scroll: Enchant Weapon, and Scroll: Enchant Weapon.',
    'icon' => 'Branchsys2.icon2.g_alegra_box',
    'is_stackable' => true,
  ],
  22311 => 
  [
    'id' => 22311,
    'type' => 'etcitem',
    'name' => 'Latus Box',
    'add_name' => '',
    'description' => 'A Divine Weapon Enchant Crystal and a high grade Ancient Weapon Enchant Crystal can be acquired at a constant rate.',
    'icon' => 'Branchsys2.icon2.g-latus_box',
    'is_stackable' => true,
  ],
  22312 => 
  [
    'id' => 22312,
    'type' => 'armor',
    'name' => 'Top-Grade Magic Pin Cloth Belt',
    'add_name' => '',
    'description' => 'Weight +6000. Cannot be exchanged or dropped. Can be destroyed. Can be stored in a private warehouse.',
    'icon' => 'armor_magic_pin_belt_i00',
    'armor_type' => 'light',
    'bodypart' => 'waist',
    'crystal_type' => 'c',
    'weight' => 500,
    'is_tradable' => false,
    'is_dropable' => false,
    'stats' => 
    [
    ],
  ],
  22313 => 
  [
    'id' => 22313,
    'type' => 'armor',
    'name' => 'Top-Grade Magic Pouch Cloth Belt',
    'add_name' => '',
    'description' => 'Inventory Slot +18. Cannot be exchanged or dropped. Can be destroyed. Can be stored in a private warehouse.',
    'icon' => 'armor_magic_pouch_belt_i00',
    'armor_type' => 'light',
    'bodypart' => 'waist',
    'crystal_type' => 'c',
    'weight' => 500,
    'is_tradable' => false,
    'is_dropable' => false,
    'stats' => 
    [
    ],
  ],
  22314 => 
  [
    'id' => 22314,
    'type' => 'etcitem',
    'name' => 'Blessed Scroll: Enchant Weapon (S-Grade]',
    'add_name' => '',
    'description' => 'Increases P. Atk. by 5 for S-grade one-handed sword, one-handed blunt, dagger, spear, and other weapons when enchanted. Increases P. Atk. by 6 for two-handed sword, two-handed blunt, dualsword, and two-handed combat weapon. Increases P. Atk. by 10 for bow weapons. Increases M. Atk. by 4 for all weapons. Starting at +4, P. Atk./M. Atk. increases by double. If enchanting fails, the item will not be crystallized but the enchant value will be reset to 0. Cannot be exchanged or dropped. Can be destroyed. Can be stored in a private warehouse.',
    'icon' => 'etc_blessed_scrl_of_ench_wp_s_i05',
    'weight' => 120,
    'is_tradable' => false,
    'is_dropable' => false,
    'is_stackable' => true,
  ],
  22315 => 
  [
    'id' => 22315,
    'type' => 'etcitem',
    'name' => 'Blessed Scroll: Enchant Armor (S-Grade]',
    'add_name' => '',
    'description' => 'Increases P. Def. by 1 for S-grade armor and accessories when enchanted. Increases by 3 starting from +4. It can safely be enchanted up to +3. For one-piece armor, it can safely be enchanted up to +4. If enchanting fails, the item will not be crystallized but the enchant value will be reset to 0.  When armor is enchanted above +4, HP also increases depending on the enchant value. Cannot be exchanged or dropped. Can be destroyed. Can be stored in a private warehouse.',
    'icon' => 'etc_blessed_scrl_of_ench_am_s_i05',
    'weight' => 120,
    'is_tradable' => false,
    'is_dropable' => false,
    'is_stackable' => true,
  ],
  22316 => 
  [
    'id' => 22316,
    'type' => 'etcitem',
    'name' => 'Blessed Scroll: Enchant Weapon (A-Grade]',
    'add_name' => '',
    'description' => 'Increases P. Atk. by 4 for A-grade one-handed sword, one-handed blunt, dagger, spear, and other weapons when enchanted. Increases P. Atk. by 5 for two-handed sword, two-handed blunt, dualsword, and two-handed combat weapon. Increases P. Atk. by 8 for bow weapons. Increases M. Atk. by 3 for all weapons. P. Atk./M. Atk. increase by double starting at +4. If enchanting fails, the item will not be crystallized but the enchant value will be reset to 0. Cannot be exchanged or dropped. Can be destroyed. Can be stored in a private warehouse.',
    'icon' => 'etc_blessed_scrl_of_ench_wp_a_i04',
    'weight' => 120,
    'is_tradable' => false,
    'is_dropable' => false,
    'is_stackable' => true,
  ],
  22317 => 
  [
    'id' => 22317,
    'type' => 'etcitem',
    'name' => 'Blessed Scroll: Enchant Weapon (B-Grade]',
    'add_name' => '',
    'description' => 'Increases P. Atk. by 3 for B-grade one-handed sword, one-handed blunt, dagger, spear, and other weapons when enchanted. Increases P. Atk. by 4 for two-handed sword, two-handed blunt, dualsword, and two-handed combat weapon. Increases P. Atk. by 6 for bow weapons. Increases M. Atk. by 3 for all weapons. Starting at +4, P. Atk./M. Atk. increases by double. If enchanting fails, the item will not be crystallized but the enchant value will be reset to 0. Cannot be exchanged or dropped. Can be destroyed. Can be stored in a private warehouse.',
    'icon' => 'etc_blessed_scrl_of_ench_wp_b_i03',
    'weight' => 120,
    'is_tradable' => false,
    'is_dropable' => false,
    'is_stackable' => true,
  ],
  22318 => 
  [
    'id' => 22318,
    'type' => 'etcitem',
    'name' => 'Blessed Scroll: Enchant Armor (A-Grade]',
    'add_name' => '',
    'description' => 'Increases P. Def. by 1 for A-grade armor and accessories. Increases by 3 starting from +4. It can safely be enchanted up to +3. For one-piece armor, it can safely be enchanted up to +4. If enchanting fails, the item will not be crystallized but the enchant value will be reset to 0.  When armor is enchanted above +4, HP also increases depending on the enchant value. Cannot be exchanged or dropped. Can be destroyed. Can be stored in a private warehouse.',
    'icon' => 'etc_blessed_scrl_of_ench_am_a_i04',
    'weight' => 120,
    'is_tradable' => false,
    'is_dropable' => false,
    'is_stackable' => true,
  ],
  22319 => 
  [
    'id' => 22319,
    'type' => 'etcitem',
    'name' => 'Blessed Scroll: Enchant Armor (B-Grade]',
    'add_name' => '',
    'description' => 'Increases P. Def. by 1 for B-grade armor and accessories. Increases by 3 starting from +4. It can safely be enchanted up to +3. For one-piece armor, it can safely be enchanted up to +4. If enchanting fails, the item will not be crystallized but the enchant value will be reset to 0. When armor is enchanted above +4, HP also increases depending on the enchant value. Cannot be exchanged or dropped. Can be destroyed. Can be stored in a private warehouse.',
    'icon' => 'etc_blessed_scrl_of_ench_am_b_i03',
    'weight' => 120,
    'is_tradable' => false,
    'is_dropable' => false,
    'is_stackable' => true,
  ],
  22320 => 
  [
    'id' => 22320,
    'type' => 'etcitem',
    'name' => 'Scroll: Enchant Weapon (A-Grade]',
    'add_name' => '',
    'description' => 'Increases P. Atk. by 4 for A-grade one-handed sword, one-handed blunt, dagger, spear, and other weapons when enchanted. Increases P. Atk. by 5 for two-handed sword, two-handed blunt, dualsword, and two-handed combat weapon. Increases P. Atk. by 8 for bow weapons. Increases M. Atk. by 3 for all weapons. P. Atk./M. Atk. increase by double starting at +4. Cannot be exchanged or dropped. Can be destroyed. Can be stored in a private warehouse.',
    'icon' => 'etc_scroll_of_enchant_weapon_i04',
    'weight' => 120,
    'is_tradable' => false,
    'is_dropable' => false,
    'is_stackable' => true,
  ],
  22321 => 
  [
    'id' => 22321,
    'type' => 'etcitem',
    'name' => 'Scroll: Enchant Weapon (B-Grade]',
    'add_name' => '',
    'description' => 'Increases P. Atk. by 3 for B-grade one-handed sword, one-handed blunt, dagger, spear, and other weapons when enchanted. Increases P. Atk. by 4 for two-handed sword, two-handed blunt, dualsword, and two-handed combat weapon. Increases P. Atk. by 6 for bow weapons. Increases M. Atk. by 3 for all weapons. P. Atk./M. Atk. increase by double starting at +4. Cannot be exchanged or dropped. Can be destroyed. Can be stored in a private warehouse.',
    'icon' => 'etc_scroll_of_enchant_weapon_i03',
    'weight' => 120,
    'is_tradable' => false,
    'is_dropable' => false,
    'is_stackable' => true,
  ],
  22322 => 
  [
    'id' => 22322,
    'type' => 'etcitem',
    'name' => 'Scroll: Enchant Armor (A-Grade]',
    'add_name' => '',
    'description' => 'Increases P. Def. by 1 for A-grade armor and accessories. Increases by 3 starting from +4. It can safely be enchanted up to +3. For one-piece armor, it can safely be enchanted up to +4. When armor is enchanted above +4, HP also increases depending on the enchant value. Cannot be exchanged or dropped. Can be destroyed. Can be stored in a private warehouse.',
    'icon' => 'etc_scroll_of_enchant_armor_i04',
    'weight' => 120,
    'is_tradable' => false,
    'is_dropable' => false,
    'is_stackable' => true,
  ],
  22323 => 
  [
    'id' => 22323,
    'type' => 'etcitem',
    'name' => 'Scroll: Enchant Armor (B-Grade]',
    'add_name' => '',
    'description' => 'Increases P. Def. by 1 for B-grade armor and accessories. Increases by 3 starting from +4. It can safely be enchanted up to +3. For one-piece armor, it can safely be enchanted up to +4. When armor is enchanted above +4, HP also increases depending on the enchant value. Cannot be exchanged or dropped. Can be destroyed. Can be stored in a private warehouse.',
    'icon' => 'etc_scroll_of_enchant_armor_i03',
    'weight' => 120,
    'is_tradable' => false,
    'is_dropable' => false,
    'is_stackable' => true,
  ],
  22324 => 
  [
    'id' => 22324,
    'type' => 'etcitem',
    'name' => 'Transformation Scroll: Ranku',
    'add_name' => '',
    'description' => 'Transformation scroll that transform you into Ranku for 30 minute(s]. No effect if used while transformed. Cannot be exchanged or dropped. Can be destroyed. Can be stored in a private warehouse.',
    'icon' => 'etc_trans_4f_s_b_01',
    'weight' => 120,
    'is_tradable' => false,
    'is_dropable' => false,
    'is_stackable' => true,
  ],
  22325 => 
  [
    'id' => 22325,
    'type' => 'etcitem',
    'name' => 'Transformation Scroll: Zaken',
    'add_name' => '',
    'description' => 'Transformation scroll that transform you into Zaken for 30 minute(s]. No effect if used while transformed. Cannot be exchanged or dropped. Can be destroyed. Can be stored in a private warehouse.',
    'icon' => 'etc_trans_4f_s_b_01',
    'weight' => 120,
    'is_tradable' => false,
    'is_dropable' => false,
    'is_stackable' => true,
  ],
  22326 => 
  [
    'id' => 22326,
    'type' => 'armor',
    'name' => 'Blue Talisman - Buff Cancel',
    'add_name' => '',
    'description' => 'Cancels the buffs of nearby enemies upon use. Only one effect is applies when you wear two of the same talismans. Cannot be exchanged or dropped. Can be destroyed. Can be stored in a private warehouse.',
    'icon' => 'etc_talisman_i01',
    'bodypart' => 'underwear',
    'weight' => 150,
    'is_tradable' => false,
    'is_dropable' => false,
  ],
  22327 => 
  [
    'id' => 22327,
    'type' => 'armor',
    'name' => 'Blue Talisman - Buff Steal',
    'add_name' => '',
    'description' => 'Stealsthe target\'s abnormal status upon use. Only one effect is applies when you wear two of the same talismans. Cannot be exchanged or dropped. Can be destroyed. Can be stored in a private warehouse.',
    'icon' => 'etc_talisman_i01',
    'bodypart' => 'underwear',
    'weight' => 150,
    'is_tradable' => false,
    'is_dropable' => false,
  ],
  22328 => 
  [
    'id' => 22328,
    'type' => 'etcitem',
    'name' => 'Territory Health Recovery Potion',
    'add_name' => '',
    'description' => 'Recovers HP upon use. It can only be used by characters between levels 61-75. Can only be used on the battlefield. Cannot be exchanged or dropped. Can be destroyed. Can be stored in a private warehouse.',
    'icon' => 'etc_super_hp_potion_i05',
    'weight' => 5,
    'is_tradable' => false,
    'is_dropable' => false,
    'is_stackable' => true,
  ],
  22329 => 
  [
    'id' => 22329,
    'type' => 'etcitem',
    'name' => 'Territory Mana Recovery Potion',
    'add_name' => '',
    'description' => 'Recovers MP upon use. It can only be used by characters between levels 61-75. Can only be used on the battlefield. Cannot be exchanged or dropped. Can be destroyed. Can be stored in a private warehouse.',
    'icon' => 'etc_super_mp_potion_i05',
    'weight' => 5,
    'is_tradable' => false,
    'is_dropable' => false,
    'is_stackable' => true,
  ],
  22330 => 
  [
    'id' => 22330,
    'type' => 'etcitem',
    'name' => 'Territory CP Recovery Potion',
    'add_name' => '',
    'description' => 'Recovers CP upon use. It can only be used by characters between levels 61-75. Can only be used on the battlefield. Cannot be exchanged or dropped. Can be destroyed. Can be stored in a private warehouse.',
    'icon' => 'etc_super_cp_potion_i05',
    'weight' => 5,
    'is_tradable' => false,
    'is_dropable' => false,
    'is_stackable' => true,
  ],
  22331 => 
  [
    'id' => 22331,
    'type' => 'etcitem',
    'name' => '7th Anniversary Pack',
    'add_name' => '',
    'description' => 'Dimensional  Celebrating the Lineage II 7th anniversary, this pack contains various items that you should find useful. Cannot be exchanged or dropped. Can be destroyed. Can be shared between characters on the same account through the Dimensional Merchant.',
    'icon' => 'br_four_leaf_clover_box_i00',
    'is_tradable' => false,
    'is_dropable' => false,
  ],
  22332 => 
  [
    'id' => 22332,
    'type' => 'etcitem',
    'name' => '7th Anniversary Bonus Pack',
    'add_name' => '',
    'description' => 'Dimensional  Celebrating the Lineage II 7th anniversary, this bonus pack contains various items that you should find useful. Cannot be exchanged or dropped. Can be destroyed. Can be shared between characters on the same account through the Dimensional Merchant.',
    'icon' => 'br_four_leaf_clover_box_i00',
    'is_tradable' => false,
    'is_dropable' => false,
  ],
  22333 => 
  [
    'id' => 22333,
    'type' => 'etcitem',
    'name' => 'Hero\'s Treasure Chest',
    'add_name' => '',
    'description' => 'Dimensional  Chest containing an equipment set pack which can be used for 90 days. Cannot be exchanged or dropped. Can be shared between characters within an account through the Dimensional Merchant.',
    'icon' => 'event_hero_treasure_box_i00',
    'is_tradable' => false,
    'is_dropable' => false,
    'is_freightable' => true,
  ],
  22334 => 
  [
    'id' => 22334,
    'type' => 'etcitem',
    'name' => 'Rune of Experience Points 50%',
    'add_name' => '1 hours limited time',
    'description' => 'Ancient characters that bestow a mysterious ability when possessed in the inventory. Increases acquired Exp. by 50%. The remaining period decreases even while logged off. Cannot be exchanged or dropped. Can be destroyed. Can be stored in a private warehouse.',
    'icon' => 'br_cash_rune_of_exp_i00',
    'etcitem_type' => 'rune',
    'weight' => 120,
    'is_tradable' => false,
    'is_dropable' => false,
    'is_sellable' => false,
    'item_skill' => 
    [
      0 => 
      [
        'skill_id' => 22039,
        'level' => 2,
      ],
    ],
    'time' => 60,
  ],
  22335 => 
  [
    'id' => 22335,
    'type' => 'etcitem',
    'name' => 'Essence of Destruction',
    'add_name' => '',
    'description' => 'An item filled with the essence of Shilen\'s followers that you have defeated.',
    'icon' => 'etc_crystal_blue_i00',
    'weight' => 10,
    'is_stackable' => true,
  ],
  22336 => 
  [
    'id' => 22336,
    'type' => 'etcitem',
    'name' => 'Pathfinder\'s Reward - Contributor',
    'add_name' => '',
    'description' => 'A gift for adventurers who have especially provided high contributions in discovering the cause of the plague.',
    'icon' => 'etc_bead_silver_i00',
    'weight' => 100,
    'is_stackable' => true,
  ],
  22337 => 
  [
    'id' => 22337,
    'type' => 'etcitem',
    'name' => 'Extra Entrance Pass - Rim Kamaloka',
    'add_name' => '',
    'description' => 'Entrance pass that allows you five addtional admissions. Can cancel the limit on entry if used while a limit on entry to Rim Kamaloka exists. Can only be used once per day from outside the instant zone. After use, the effect disappears at the corresponding instant dungeon\'s reset time. Cannot be exchanged or dropped.',
    'icon' => 'ticket_i00',
    'weight' => 5,
    'is_tradable' => false,
    'is_dropable' => false,
    'is_stackable' => true,
  ],
  22338 => 
  [
    'id' => 22338,
    'type' => 'etcitem',
    'name' => 'Extra Entrance Pass - Rim Kamaloka 1 Sheet Pack',
    'add_name' => '',
    'description' => 'Wrapped pack containing an entrance pass that lets you enter Rim Kamaloka.',
    'icon' => 'etc_pi_gift_box_i00',
    'weight' => 100,
    'is_stackable' => true,
  ],
  22339 => 
  [
    'id' => 22339,
    'type' => 'etcitem',
    'name' => 'S84 Top-grade Weapon Chest - Event',
    'add_name' => 'Event',
    'description' => 'The chest contains 1 S84 top-grade weapon. Which one could it be?',
    'icon' => 'etc_pi_gift_box_i04',
    'is_stackable' => true,
  ],
  22340 => 
  [
    'id' => 22340,
    'type' => 'etcitem',
    'name' => 'Elegia Armor Chest',
    'add_name' => 'Event',
    'description' => 'The chest contains 1 Elegia armor. Which one could it be?',
    'icon' => 'etc_pi_gift_box_i04',
    'is_stackable' => true,
  ],
  22341 => 
  [
    'id' => 22341,
    'type' => 'etcitem',
    'name' => 'Scroll: Enchant Weapon - C Grade',
    'add_name' => '',
    'description' => 'When enchanted, P. Atk. increases by 3 for C-grade one-handed swords, one-handed blunts, daggers, spears, and other weapons. P. Atk. increases by 4 for two-handed swords, two-handed blunts, dualswords, and two-handed combat weapons. P. Atk. increases by 6 for bows. M. Atk. increases by 3 for all weapons. Starting at +4, P. Atk. / M. Atk. bonus double. If enchanting fails, the item will not be crystallized but the enchant value will be reset to 0. Can be exchanged, dropped, and destroyed. Can be stored in a Private Warehouse.',
    'icon' => 'etc_blessed_scrl_of_ench_wp_c_i02',
    'weight' => 120,
    'is_stackable' => true,
  ],
  22342 => 
  [
    'id' => 22342,
    'type' => 'etcitem',
    'name' => 'Scroll: Enchant Weapon - C Grade',
    'add_name' => '',
    'description' => 'When enchanted, P. Atk. increases by 3 for C-grade one-handed swords, one-handed blunts, daggers, spears, and other weapons. P. Atk. increases by 4 for two-handed swords, two-handed blunts, dualswords, and two-handed combat weapons. P. Atk. increases by 6 for bows. M. Atk. increases by 3 for all weapons. Starting at +4, P. Atk. / M. Atk. bonus double. Can be exchanged, dropped, and destroyed. Can be stored in a Private Warehouse.',
    'icon' => 'etc_scroll_of_enchant_weapon_i02',
    'weight' => 120,
    'is_stackable' => true,
  ],
  22343 => 
  [
    'id' => 22343,
    'type' => 'etcitem',
    'name' => 'Scroll: Enchant Armor - C Grade',
    'add_name' => '',
    'description' => 'When enchanted, P. Def. increases by 1 for C-grade armor and accessories. Starting at +4, P. Def. increases by 3. Enchanting is safe up to +3, but one-piece body armor can be safely enchanted up to +4. Increases HP according to enchant level when armor is enchanted +4 or above. Cannot be exchanged or dropped. Can be stored in a Private Warehouse.  ',
    'icon' => 'etc_scroll_of_enchant_armor_i02',
    'weight' => 120,
    'is_tradable' => false,
    'is_dropable' => false,
    'is_stackable' => true,
  ],
  22344 => 
  [
    'id' => 22344,
    'type' => 'etcitem',
    'name' => 'Scroll: Enchant Weapon - D Grade',
    'add_name' => '',
    'description' => 'When enchanted, P. Atk. increases by 2 for D-grade one-handed swords, one-handed blunts, daggers, spears, two-handed swords, two-handed blunts, dualswords, two-handed combat weapons, and other weapons. P. Atk. increases by 4 for bows. M. Atk. increases by 2 for all weapons. Starting at +4, P. Atk. / M. Atk. bonus double. Can be exchanged, dropped, and destroyed. Can be stored in a Private Warehouse.',
    'icon' => 'etc_scroll_of_enchant_weapon_i01',
    'weight' => 120,
    'is_stackable' => true,
  ],
  22345 => 
  [
    'id' => 22345,
    'type' => 'etcitem',
    'name' => 'Scroll: Enchant Armor - D Grade',
    'add_name' => '',
    'description' => 'When enchanted, P. Def. increases by 1 for D-grade armor and accessories. Starting at +4, P. Def. increases by 3. Enchanting is safe up to +3, but one-piece body armor can be safely enchanted up to +4. Increases HP according to enchant level when armor is enchanted +4 or above. Cannot be exchanged or dropped. Can be stored in a Private Warehouse.  ',
    'icon' => 'etc_scroll_of_enchant_armor_i01',
    'weight' => 120,
    'is_tradable' => false,
    'is_dropable' => false,
    'is_stackable' => true,
  ],
  22346 => 
  [
    'id' => 22346,
    'type' => 'etcitem',
    'name' => 'Enchantment Tool Box',
    'add_name' => '',
    'description' => 'A box of enchantment-related itmes. Double-click for a chance to receive an  Cannot be exchanged or dropped.',
    'icon' => 'etc_treasure_box_i07',
    'weight' => 100,
    'is_tradable' => false,
    'is_dropable' => false,
    'is_stackable' => true,
  ],
  22347 => 
  [
    'id' => 22347,
    'type' => 'etcitem',
    'name' => 'Rune of Fate',
    'add_name' => '',
    'description' => 'Ancient characters which bestow a mysterious ability if it is possessed in the inventory. It increases acquired XP and SP by 200%. It will be removed from the inventory on June 15, 2011 when the event ends. Cannot be exchanged, dropped, or destroyed. Can be stored in a private warehouse.',
    'icon' => 'br_cash_rune_of_feather_i00',
    'weight' => 120,
    'is_tradable' => false,
    'is_dropable' => false,
    'is_destroyable' => false,
  ],
];