<?php
return [
  300 => 
  [
    'id' => 300,
    'type' => 'weapon',
    'name' => 'Great Axe',
    'add_name' => '',
    'description' => 'Bestows one of the following functions: Anger, Critical Stun or Light.',
    'icon' => 'weapon_great_axe_i00',
    'weapon_type' => 'pole',
    'bodypart' => 'lrhand',
    'crystal_count' => 891,
    'crystal_type' => 'b',
    'weight' => 1940,
    'price' => 6680500,
    'soulshots' => 1,
    'spiritshots' => 1,
    'enchant_enabled' => true,
    'item_skill' => 
    [
      0 => 
      [
        'skill_id' => 3599,
        'level' => 1,
      ],
    ],
    'stats' => 
    [
      'pAtk' => 175,
      'mAtk' => 91,
      'critRate' => 8,
      'pAtkSpd' => 325,
    ],
  ],
  301 => 
  [
    'id' => 301,
    'type' => 'weapon',
    'name' => 'Scorpion',
    'add_name' => '',
    'description' => 'Bestows one of the following functions: Anger, Critical Stun or Wide Blow.',
    'icon' => 'weapon_scorpion_i00',
    'weapon_type' => 'pole',
    'bodypart' => 'lrhand',
    'crystal_count' => 1471,
    'crystal_type' => 'c',
    'weight' => 1990,
    'price' => 3677700,
    'soulshots' => 3,
    'spiritshots' => 3,
    'enchant_enabled' => true,
    'item_skill' => 
    [
      0 => 
      [
        'skill_id' => 3599,
        'level' => 1,
      ],
    ],
    'stats' => 
    [
      'pAtk' => 144,
      'mAtk' => 78,
      'critRate' => 8,
      'pAtkSpd' => 325,
    ],
  ],
  302 => 
  [
    'id' => 302,
    'type' => 'weapon',
    'name' => 'Body Slasher',
    'add_name' => '',
    'description' => 'Bestows one of the following functions: Critical Stun, Towering Blow or Wide Blow.',
    'icon' => 'weapon_body_slasher_i00',
    'weapon_type' => 'pole',
    'bodypart' => 'lrhand',
    'crystal_count' => 705,
    'crystal_type' => 'c',
    'weight' => 2030,
    'price' => 1762900,
    'soulshots' => 2,
    'spiritshots' => 2,
    'enchant_enabled' => true,
    'item_skill' => 
    [
      0 => 
      [
        'skill_id' => 3599,
        'level' => 1,
      ],
    ],
    'stats' => 
    [
      'pAtk' => 107,
      'mAtk' => 61,
      'critRate' => 8,
      'pAtkSpd' => 325,
    ],
  ],
  303 => 
  [
    'id' => 303,
    'type' => 'weapon',
    'name' => 'Widow Maker',
    'add_name' => '',
    'description' => 'Bestows one of the following functions: Critical Stun, Towering Blow or Wide Blow.',
    'icon' => 'weapon_widow_maker_i00',
    'weapon_type' => 'pole',
    'bodypart' => 'lrhand',
    'crystal_count' => 1471,
    'crystal_type' => 'c',
    'weight' => 1980,
    'price' => 3677700,
    'soulshots' => 3,
    'spiritshots' => 3,
    'enchant_enabled' => true,
    'item_skill' => 
    [
      0 => 
      [
        'skill_id' => 3599,
        'level' => 1,
      ],
    ],
    'stats' => 
    [
      'pAtk' => 144,
      'mAtk' => 78,
      'critRate' => 8,
      'pAtkSpd' => 325,
    ],
  ],
  304 => 
  [
    'id' => 304,
    'type' => 'weapon',
    'name' => 'Orcish Halberd',
    'add_name' => '',
    'description' => '',
    'icon' => 'weapon_orcish_halbard_i00',
    'weapon_type' => 'pole',
    'bodypart' => 'lrhand',
    'crystal_count' => 1704,
    'crystal_type' => 'a',
    'weight' => 1880,
    'price' => 21300000,
    'soulshots' => 1,
    'spiritshots' => 1,
    'enchant_enabled' => true,
    'item_skill' => 
    [
      0 => 
      [
        'skill_id' => 3599,
        'level' => 1,
      ],
    ],
    'stats' => 
    [
      'pAtk' => 219,
      'mAtk' => 109,
      'critRate' => 8,
      'pAtkSpd' => 325,
    ],
  ],
  305 => 
  [
    'id' => 305,
    'type' => 'weapon',
    'name' => 'Tallum Glaive',
    'add_name' => '',
    'description' => 'Bestows one of the following functions: Guidance, Health, or Wide Blow.',
    'icon' => 'weapon_tallum_glaive_i00',
    'weapon_type' => 'pole',
    'bodypart' => 'lrhand',
    'crystal_count' => 1659,
    'crystal_type' => 'a',
    'weight' => 1840,
    'price' => 20741000,
    'soulshots' => 1,
    'spiritshots' => 1,
    'enchant_enabled' => true,
    'item_skill' => 
    [
      0 => 
      [
        'skill_id' => 3599,
        'level' => 1,
      ],
    ],
    'stats' => 
    [
      'pAtk' => 232,
      'mAtk' => 114,
      'critRate' => 8,
      'pAtkSpd' => 325,
    ],
  ],
  306 => 
  [
    'id' => 306,
    'type' => 'weapon',
    'name' => 'Dragon Claw Axe',
    'add_name' => '',
    'description' => '',
    'icon' => 'weapon_dragon_hunter_axe_i00',
    'weapon_type' => 'pole',
    'bodypart' => 'lrhand',
    'crystal_count' => 1765,
    'crystal_type' => 's',
    'weight' => 1820,
    'price' => 35300000,
    'soulshots' => 1,
    'spiritshots' => 1,
    'enchant_enabled' => true,
    'item_skill' => 
    [
      0 => 
      [
        'skill_id' => 3599,
        'level' => 1,
      ],
    ],
    'stats' => 
    [
      'pAtk' => 251,
      'mAtk' => 121,
      'critRate' => 8,
      'pAtkSpd' => 325,
    ],
  ],
  307 => 
  [
    'id' => 307,
    'type' => 'weapon',
    'name' => 'Aurakyria Lance',
    'add_name' => '',
    'description' => '',
    'icon' => 'weapon_saint_spear_i00',
    'weapon_type' => 'pole',
    'bodypart' => 'lrhand',
    'crystal_type' => 's',
    'weight' => 1800,
    'soulshots' => 1,
    'spiritshots' => 1,
    'enchant_enabled' => true,
    'is_tradable' => false,
    'is_dropable' => false,
    'is_sellable' => false,
    'item_skill' => 
    [
      0 => 
      [
        'skill_id' => 3599,
        'level' => 1,
      ],
    ],
    'stats' => 
    [
      'pAtk' => 269,
      'mAtk' => 128,
      'critRate' => 8,
      'pAtkSpd' => 325,
    ],
  ],
  308 => 
  [
    'id' => 308,
    'type' => 'weapon',
    'name' => 'Buffalo\'s Horn',
    'add_name' => '',
    'description' => '',
    'icon' => 'weapon_buffalo_horn_i00',
    'weapon_type' => 'etc',
    'bodypart' => 'rhand',
    'weight' => 660,
    'price' => 590,
    'soulshots' => 1,
    'spiritshots' => 1,
    'is_magic_weapon' => true,
    'stats' => 
    [
      'pAtk' => 6,
      'mAtk' => 8,
      'critRate' => 8,
      'pAtkSpd' => 379,
    ],
  ],
  309 => 
  [
    'id' => 309,
    'type' => 'weapon',
    'name' => 'Tears of Eva',
    'add_name' => '',
    'description' => '',
    'icon' => 'weapon_tears_of_eva_i00',
    'weapon_type' => 'etc',
    'bodypart' => 'rhand',
    'weight' => 630,
    'price' => 105000,
    'soulshots' => 2,
    'spiritshots' => 2,
    'is_magic_weapon' => true,
    'stats' => 
    [
      'pAtk' => 19,
      'mAtk' => 22,
      'critRate' => 8,
      'pAtkSpd' => 379,
    ],
  ],
  310 => 
  [
    'id' => 310,
    'type' => 'weapon',
    'name' => 'Relic of the Saints',
    'add_name' => '',
    'description' => '',
    'icon' => 'weapon_apprentices_spellbook_i00',
    'weapon_type' => 'etc',
    'bodypart' => 'rhand',
    'weight' => 610,
    'price' => 105000,
    'soulshots' => 2,
    'spiritshots' => 2,
    'is_magic_weapon' => true,
    'stats' => 
    [
      'pAtk' => 19,
      'mAtk' => 22,
      'critRate' => 8,
      'pAtkSpd' => 379,
    ],
  ],
  311 => 
  [
    'id' => 311,
    'type' => 'weapon',
    'name' => 'Crucifix of Blessing',
    'add_name' => '',
    'description' => '',
    'icon' => 'weapon_crucifix_of_blessing_i00',
    'weapon_type' => 'etc',
    'bodypart' => 'rhand',
    'weight' => 620,
    'price' => 188000,
    'soulshots' => 2,
    'spiritshots' => 2,
    'is_magic_weapon' => true,
    'stats' => 
    [
      'pAtk' => 25,
      'mAtk' => 28,
      'critRate' => 8,
      'pAtkSpd' => 379,
    ],
  ],
  312 => 
  [
    'id' => 312,
    'type' => 'weapon',
    'name' => 'Branch of Life',
    'add_name' => '',
    'description' => '',
    'icon' => 'weapon_branch_of_life_i00',
    'weapon_type' => 'etc',
    'bodypart' => 'rhand',
    'crystal_count' => 582,
    'crystal_type' => 'd',
    'weight' => 620,
    'price' => 315000,
    'soulshots' => 2,
    'spiritshots' => 2,
    'enchant_enabled' => true,
    'is_magic_weapon' => true,
    'stats' => 
    [
      'pAtk' => 32,
      'mAtk' => 35,
      'critRate' => 8,
      'pAtkSpd' => 379,
    ],
  ],
  313 => 
  [
    'id' => 313,
    'type' => 'weapon',
    'name' => 'Temptation of Abyss',
    'add_name' => '',
    'description' => '',
    'icon' => 'weapon_temptation_of_abyss_i00',
    'weapon_type' => 'etc',
    'bodypart' => 'rhand',
    'crystal_count' => 582,
    'crystal_type' => 'd',
    'weight' => 610,
    'price' => 315000,
    'soulshots' => 2,
    'spiritshots' => 2,
    'enchant_enabled' => true,
    'is_magic_weapon' => true,
    'stats' => 
    [
      'pAtk' => 32,
      'mAtk' => 35,
      'critRate' => 8,
      'pAtkSpd' => 379,
    ],
  ],
  314 => 
  [
    'id' => 314,
    'type' => 'weapon',
    'name' => 'Proof of Revenge',
    'add_name' => '',
    'description' => '',
    'icon' => 'weapon_proof_of_revenge_i00',
    'weapon_type' => 'etc',
    'bodypart' => 'rhand',
    'crystal_count' => 582,
    'crystal_type' => 'd',
    'weight' => 600,
    'price' => 315000,
    'soulshots' => 2,
    'spiritshots' => 2,
    'enchant_enabled' => true,
    'is_magic_weapon' => true,
    'stats' => 
    [
      'pAtk' => 32,
      'mAtk' => 35,
      'critRate' => 8,
      'pAtkSpd' => 379,
    ],
  ],
  315 => 
  [
    'id' => 315,
    'type' => 'weapon',
    'name' => 'Divine Tome',
    'add_name' => '',
    'description' => '',
    'icon' => 'weapon_divine_tome_i00',
    'weapon_type' => 'etc',
    'bodypart' => 'rhand',
    'crystal_count' => 915,
    'crystal_type' => 'd',
    'weight' => 570,
    'price' => 495500,
    'soulshots' => 2,
    'spiritshots' => 2,
    'enchant_enabled' => true,
    'is_magic_weapon' => true,
    'stats' => 
    [
      'pAtk' => 41,
      'mAtk' => 43,
      'critRate' => 8,
      'pAtkSpd' => 379,
    ],
  ],
  316 => 
  [
    'id' => 316,
    'type' => 'weapon',
    'name' => 'Sage\'s Blood',
    'add_name' => '',
    'description' => '',
    'icon' => 'weapon_blood_of_saints_i00',
    'weapon_type' => 'etc',
    'bodypart' => 'rhand',
    'crystal_count' => 1373,
    'crystal_type' => 'd',
    'weight' => 580,
    'price' => 743500,
    'soulshots' => 2,
    'spiritshots' => 2,
    'enchant_enabled' => true,
    'is_magic_weapon' => true,
    'stats' => 
    [
      'pAtk' => 51,
      'mAtk' => 52,
      'critRate' => 8,
      'pAtkSpd' => 379,
    ],
  ],
  317 => 
  [
    'id' => 317,
    'type' => 'weapon',
    'name' => 'Tome of Blood',
    'add_name' => '',
    'description' => '',
    'icon' => 'weapon_tome_of_blood_i00',
    'weapon_type' => 'etc',
    'bodypart' => 'rhand',
    'crystal_count' => 1373,
    'crystal_type' => 'd',
    'weight' => 570,
    'price' => 743500,
    'soulshots' => 2,
    'spiritshots' => 2,
    'enchant_enabled' => true,
    'is_magic_weapon' => true,
    'stats' => 
    [
      'pAtk' => 51,
      'mAtk' => 52,
      'critRate' => 8,
      'pAtkSpd' => 379,
    ],
  ],
  318 => 
  [
    'id' => 318,
    'type' => 'weapon',
    'name' => 'Crucifix of Blood',
    'add_name' => '',
    'description' => '',
    'icon' => 'weapon_crucifix_of_blood_i00',
    'weapon_type' => 'etc',
    'bodypart' => 'rhand',
    'crystal_count' => 1983,
    'crystal_type' => 'd',
    'weight' => 540,
    'price' => 1074000,
    'soulshots' => 3,
    'spiritshots' => 3,
    'enchant_enabled' => true,
    'is_magic_weapon' => true,
    'stats' => 
    [
      'pAtk' => 63,
      'mAtk' => 63,
      'critRate' => 8,
      'pAtkSpd' => 379,
    ],
  ],
  319 => 
  [
    'id' => 319,
    'type' => 'weapon',
    'name' => 'Eye of Infinity',
    'add_name' => '',
    'description' => '',
    'icon' => 'weapon_apprentices_spellbook_i00',
    'weapon_type' => 'etc',
    'bodypart' => 'rhand',
    'crystal_count' => 2545,
    'crystal_type' => 'd',
    'weight' => 1600,
    'price' => 1400000,
    'soulshots' => 3,
    'spiritshots' => 3,
    'enchant_enabled' => true,
    'is_magic_weapon' => true,
    'stats' => 
    [
      'pAtk' => 63,
      'mAtk' => 63,
      'critRate' => 8,
      'pAtkSpd' => 379,
    ],
  ],
  320 => 
  [
    'id' => 320,
    'type' => 'weapon',
    'name' => 'Blue Crystal Skull',
    'add_name' => '',
    'description' => '',
    'icon' => 'weapon_apprentices_spellbook_i00',
    'weapon_type' => 'etc',
    'bodypart' => 'rhand',
    'crystal_count' => 2763,
    'crystal_type' => 'd',
    'weight' => 1600,
    'price' => 1520000,
    'soulshots' => 3,
    'spiritshots' => 3,
    'enchant_enabled' => true,
    'is_magic_weapon' => true,
    'stats' => 
    [
      'pAtk' => 67,
      'mAtk' => 66,
      'critRate' => 8,
      'pAtkSpd' => 379,
    ],
  ],
  321 => 
  [
    'id' => 321,
    'type' => 'weapon',
    'name' => 'Demon Fangs',
    'add_name' => '',
    'description' => '',
    'icon' => 'weapon_demon_fangs_i00',
    'weapon_type' => 'etc',
    'bodypart' => 'rhand',
    'crystal_count' => 2164,
    'crystal_type' => 'd',
    'weight' => 1600,
    'price' => 1171900,
    'soulshots' => 3,
    'spiritshots' => 3,
    'enchant_enabled' => true,
    'is_magic_weapon' => true,
    'stats' => 
    [
      'pAtk' => 67,
      'mAtk' => 66,
      'critRate' => 8,
      'pAtkSpd' => 379,
    ],
  ],
  322 => 
  [
    'id' => 322,
    'type' => 'weapon',
    'name' => 'Vajra Wands',
    'add_name' => '',
    'description' => '',
    'icon' => 'weapon_apprentices_spellbook_i00',
    'weapon_type' => 'etc',
    'bodypart' => 'rhand',
    'crystal_count' => 3272,
    'crystal_type' => 'd',
    'weight' => 1600,
    'price' => 1800000,
    'soulshots' => 3,
    'spiritshots' => 3,
    'enchant_enabled' => true,
    'is_magic_weapon' => true,
    'stats' => 
    [
      'pAtk' => 74,
      'mAtk' => 72,
      'critRate' => 8,
      'pAtkSpd' => 379,
    ],
  ],
  323 => 
  [
    'id' => 323,
    'type' => 'weapon',
    'name' => 'Ancient Reagent',
    'add_name' => '',
    'description' => '',
    'icon' => 'weapon_apprentices_spellbook_i00',
    'weapon_type' => 'etc',
    'bodypart' => 'rhand',
    'crystal_count' => 3272,
    'crystal_type' => 'd',
    'weight' => 1600,
    'price' => 1800000,
    'soulshots' => 3,
    'spiritshots' => 3,
    'enchant_enabled' => true,
    'is_magic_weapon' => true,
    'stats' => 
    [
      'pAtk' => 74,
      'mAtk' => 72,
      'critRate' => 8,
      'pAtkSpd' => 379,
    ],
  ],
  324 => 
  [
    'id' => 324,
    'type' => 'weapon',
    'name' => 'Tears of Fairy',
    'add_name' => '',
    'description' => '',
    'icon' => 'weapon_apprentices_spellbook_i00',
    'weapon_type' => 'etc',
    'bodypart' => 'rhand',
    'crystal_count' => 1148,
    'crystal_type' => 'c',
    'weight' => 1600,
    'price' => 2870000,
    'soulshots' => 2,
    'spiritshots' => 2,
    'enchant_enabled' => true,
    'is_magic_weapon' => true,
    'stats' => 
    [
      'pAtk' => 98,
      'mAtk' => 91,
      'critRate' => 8,
      'pAtkSpd' => 379,
    ],
  ],
  325 => 
  [
    'id' => 325,
    'type' => 'weapon',
    'name' => 'Horn of Glory',
    'add_name' => '',
    'description' => '',
    'icon' => 'weapon_horn_of_glory_i00',
    'weapon_type' => 'etc',
    'bodypart' => 'rhand',
    'crystal_count' => 884,
    'crystal_type' => 'c',
    'weight' => 540,
    'price' => 2209700,
    'soulshots' => 2,
    'spiritshots' => 2,
    'enchant_enabled' => true,
    'is_magic_weapon' => true,
    'stats' => 
    [
      'pAtk' => 98,
      'mAtk' => 91,
      'critRate' => 8,
      'pAtkSpd' => 379,
    ],
  ],
  326 => 
  [
    'id' => 326,
    'type' => 'weapon',
    'name' => 'Heathen\'s Book',
    'add_name' => '',
    'description' => '',
    'icon' => 'weapon_heathens_book_i00',
    'weapon_type' => 'etc',
    'bodypart' => 'rhand',
    'crystal_count' => 1322,
    'crystal_type' => 'c',
    'weight' => 560,
    'price' => 3304300,
    'soulshots' => 3,
    'spiritshots' => 3,
    'enchant_enabled' => true,
    'is_magic_weapon' => true,
    'stats' => 
    [
      'pAtk' => 111,
      'mAtk' => 101,
      'critRate' => 8,
      'pAtkSpd' => 379,
    ],
  ],
  327 => 
  [
    'id' => 327,
    'type' => 'weapon',
    'name' => 'Hex Doll',
    'add_name' => '',
    'description' => '',
    'icon' => 'weapon_apprentices_spellbook_i00',
    'weapon_type' => 'etc',
    'bodypart' => 'rhand',
    'crystal_count' => 1720,
    'crystal_type' => 'c',
    'weight' => 1600,
    'price' => 4300000,
    'soulshots' => 3,
    'spiritshots' => 3,
    'enchant_enabled' => true,
    'is_magic_weapon' => true,
    'stats' => 
    [
      'pAtk' => 111,
      'mAtk' => 101,
      'critRate' => 8,
      'pAtkSpd' => 379,
    ],
  ],
  328 => 
  [
    'id' => 328,
    'type' => 'weapon',
    'name' => 'Candle of Wisdom',
    'add_name' => '',
    'description' => '',
    'icon' => 'weapon_apprentices_spellbook_i00',
    'weapon_type' => 'etc',
    'bodypart' => 'rhand',
    'crystal_count' => 2452,
    'crystal_type' => 'c',
    'weight' => 1600,
    'price' => 6130000,
    'soulshots' => 3,
    'spiritshots' => 3,
    'enchant_enabled' => true,
    'is_magic_weapon' => true,
    'stats' => 
    [
      'pAtk' => 125,
      'mAtk' => 111,
      'critRate' => 8,
      'pAtkSpd' => 379,
    ],
  ],
  329 => 
  [
    'id' => 329,
    'type' => 'weapon',
    'name' => 'Blessed Branch',
    'add_name' => '',
    'description' => '',
    'icon' => 'weapon_apprentices_spellbook_i00',
    'weapon_type' => 'etc',
    'bodypart' => 'rhand',
    'crystal_count' => 2452,
    'crystal_type' => 'c',
    'weight' => 800,
    'price' => 6130000,
    'soulshots' => 3,
    'spiritshots' => 3,
    'enchant_enabled' => true,
    'is_magic_weapon' => true,
    'stats' => 
    [
      'pAtk' => 125,
      'mAtk' => 111,
      'critRate' => 8,
      'pAtkSpd' => 379,
    ],
  ],
  330 => 
  [
    'id' => 330,
    'type' => 'weapon',
    'name' => 'Phoenix Feather',
    'add_name' => '',
    'description' => '',
    'icon' => 'weapon_apprentices_spellbook_i00',
    'weapon_type' => 'etc',
    'bodypart' => 'rhand',
    'crystal_count' => 2452,
    'crystal_type' => 'c',
    'weight' => 800,
    'price' => 6130000,
    'soulshots' => 3,
    'spiritshots' => 3,
    'enchant_enabled' => true,
    'is_magic_weapon' => true,
    'stats' => 
    [
      'pAtk' => 125,
      'mAtk' => 111,
      'critRate' => 8,
      'pAtkSpd' => 379,
    ],
  ],
  331 => 
  [
    'id' => 331,
    'type' => 'weapon',
    'name' => 'Cerberus Eye',
    'add_name' => '',
    'description' => '',
    'icon' => 'weapon_apprentices_spellbook_i00',
    'weapon_type' => 'etc',
    'bodypart' => 'rhand',
    'crystal_count' => 2452,
    'crystal_type' => 'c',
    'weight' => 1600,
    'price' => 6130000,
    'soulshots' => 3,
    'spiritshots' => 3,
    'enchant_enabled' => true,
    'is_magic_weapon' => true,
    'stats' => 
    [
      'pAtk' => 125,
      'mAtk' => 111,
      'critRate' => 8,
      'pAtkSpd' => 379,
    ],
  ],
  332 => 
  [
    'id' => 332,
    'type' => 'weapon',
    'name' => 'Scroll of Destruction',
    'add_name' => '',
    'description' => '',
    'icon' => 'weapon_apprentices_spellbook_i00',
    'weapon_type' => 'etc',
    'bodypart' => 'rhand',
    'crystal_count' => 2452,
    'crystal_type' => 'c',
    'weight' => 1600,
    'price' => 6130000,
    'soulshots' => 3,
    'spiritshots' => 3,
    'enchant_enabled' => true,
    'is_magic_weapon' => true,
    'stats' => 
    [
      'pAtk' => 125,
      'mAtk' => 111,
      'critRate' => 8,
      'pAtkSpd' => 379,
    ],
  ],
  333 => 
  [
    'id' => 333,
    'type' => 'weapon',
    'name' => 'Claws of Black Dragon',
    'add_name' => '',
    'description' => '',
    'icon' => 'weapon_apprentices_spellbook_i00',
    'weapon_type' => 'etc',
    'bodypart' => 'rhand',
    'crystal_count' => 2452,
    'crystal_type' => 'c',
    'weight' => 1600,
    'price' => 6130000,
    'soulshots' => 3,
    'spiritshots' => 3,
    'enchant_enabled' => true,
    'is_magic_weapon' => true,
    'stats' => 
    [
      'pAtk' => 125,
      'mAtk' => 111,
      'critRate' => 8,
      'pAtkSpd' => 379,
    ],
  ],
  334 => 
  [
    'id' => 334,
    'type' => 'weapon',
    'name' => 'Three Eyed Crow\'s Feather',
    'add_name' => '',
    'description' => '',
    'icon' => 'weapon_apprentices_spellbook_i00',
    'weapon_type' => 'etc',
    'bodypart' => 'rhand',
    'crystal_count' => 2452,
    'crystal_type' => 'c',
    'weight' => 1600,
    'price' => 6130000,
    'soulshots' => 3,
    'spiritshots' => 3,
    'enchant_enabled' => true,
    'is_magic_weapon' => true,
    'stats' => 
    [
      'pAtk' => 125,
      'mAtk' => 111,
      'critRate' => 8,
      'pAtkSpd' => 379,
    ],
  ],
  335 => 
  [
    'id' => 335,
    'type' => 'weapon',
    'name' => 'Soul Crystal',
    'add_name' => '',
    'description' => '',
    'icon' => 'weapon_apprentices_spellbook_i00',
    'weapon_type' => 'etc',
    'bodypart' => 'rhand',
    'crystal_count' => 1746,
    'crystal_type' => 'b',
    'weight' => 1600,
    'price' => 13100000,
    'soulshots' => 1,
    'spiritshots' => 1,
    'enchant_enabled' => true,
    'is_magic_weapon' => true,
    'stats' => 
    [
      'pAtk' => 155,
      'mAtk' => 132,
      'critRate' => 8,
      'pAtkSpd' => 379,
    ],
  ],
  336 => 
  [
    'id' => 336,
    'type' => 'weapon',
    'name' => 'Scroll of Mana',
    'add_name' => '',
    'description' => '',
    'icon' => 'weapon_apprentices_spellbook_i00',
    'weapon_type' => 'etc',
    'bodypart' => 'rhand',
    'crystal_count' => 2440,
    'crystal_type' => 'b',
    'weight' => 1600,
    'price' => 18300000,
    'soulshots' => 1,
    'spiritshots' => 1,
    'enchant_enabled' => true,
    'is_magic_weapon' => true,
    'stats' => 
    [
      'pAtk' => 170,
      'mAtk' => 143,
      'critRate' => 8,
      'pAtkSpd' => 379,
    ],
  ],
  337 => 
  [
    'id' => 337,
    'type' => 'weapon',
    'name' => 'Scroll of Massacre',
    'add_name' => '',
    'description' => '',
    'icon' => 'weapon_apprentices_spellbook_i00',
    'weapon_type' => 'etc',
    'bodypart' => 'rhand',
    'crystal_count' => 2440,
    'crystal_type' => 'b',
    'weight' => 1600,
    'price' => 18300000,
    'soulshots' => 1,
    'spiritshots' => 1,
    'enchant_enabled' => true,
    'is_magic_weapon' => true,
    'stats' => 
    [
      'pAtk' => 170,
      'mAtk' => 143,
      'critRate' => 8,
      'pAtkSpd' => 379,
    ],
  ],
  338 => 
  [
    'id' => 338,
    'type' => 'weapon',
    'name' => 'Wyvern\'s Skull',
    'add_name' => '',
    'description' => '',
    'icon' => 'weapon_apprentices_spellbook_i00',
    'weapon_type' => 'etc',
    'bodypart' => 'rhand',
    'crystal_count' => 2440,
    'crystal_type' => 'b',
    'weight' => 4800,
    'price' => 18300000,
    'soulshots' => 1,
    'spiritshots' => 1,
    'enchant_enabled' => true,
    'is_magic_weapon' => true,
    'stats' => 
    [
      'pAtk' => 170,
      'mAtk' => 143,
      'critRate' => 8,
      'pAtkSpd' => 379,
    ],
  ],
  339 => 
  [
    'id' => 339,
    'type' => 'weapon',
    'name' => 'Blood Crystal',
    'add_name' => '',
    'description' => '',
    'icon' => 'weapon_apprentices_spellbook_i00',
    'weapon_type' => 'etc',
    'bodypart' => 'rhand',
    'crystal_count' => 2440,
    'crystal_type' => 'b',
    'weight' => 1600,
    'price' => 18300000,
    'soulshots' => 1,
    'spiritshots' => 1,
    'enchant_enabled' => true,
    'is_magic_weapon' => true,
    'stats' => 
    [
      'pAtk' => 170,
      'mAtk' => 143,
      'critRate' => 8,
      'pAtkSpd' => 379,
    ],
  ],
  340 => 
  [
    'id' => 340,
    'type' => 'weapon',
    'name' => 'Unicorn\'s Horn',
    'add_name' => '',
    'description' => '',
    'icon' => 'weapon_apprentices_spellbook_i00',
    'weapon_type' => 'etc',
    'bodypart' => 'rhand',
    'crystal_count' => 2440,
    'crystal_type' => 'b',
    'weight' => 1600,
    'price' => 18300000,
    'soulshots' => 1,
    'spiritshots' => 1,
    'enchant_enabled' => true,
    'is_magic_weapon' => true,
    'stats' => 
    [
      'pAtk' => 170,
      'mAtk' => 143,
      'critRate' => 8,
      'pAtkSpd' => 379,
    ],
  ],
  341 => 
  [
    'id' => 341,
    'type' => 'weapon',
    'name' => 'Forgotten Tome',
    'add_name' => '',
    'description' => '',
    'icon' => 'weapon_apprentices_spellbook_i00',
    'weapon_type' => 'etc',
    'bodypart' => 'rhand',
    'crystal_count' => 2160,
    'crystal_type' => 'a',
    'weight' => 1600,
    'price' => 27000000,
    'soulshots' => 1,
    'spiritshots' => 1,
    'enchant_enabled' => true,
    'is_magic_weapon' => true,
    'stats' => 
    [
      'pAtk' => 186,
      'mAtk' => 152,
      'critRate' => 8,
      'pAtkSpd' => 379,
    ],
  ],
  342 => 
  [
    'id' => 342,
    'type' => 'weapon',
    'name' => 'Enchanted Flute',
    'add_name' => '',
    'description' => '',
    'icon' => 'weapon_apprentices_spellbook_i00',
    'weapon_type' => 'etc',
    'bodypart' => 'rhand',
    'crystal_count' => 2160,
    'crystal_type' => 'a',
    'weight' => 1600,
    'price' => 27000000,
    'soulshots' => 1,
    'spiritshots' => 1,
    'enchant_enabled' => true,
    'is_magic_weapon' => true,
    'stats' => 
    [
      'pAtk' => 186,
      'mAtk' => 152,
      'critRate' => 8,
      'pAtkSpd' => 379,
    ],
  ],
  343 => 
  [
    'id' => 343,
    'type' => 'weapon',
    'name' => 'Headless Arrow',
    'add_name' => '',
    'description' => '',
    'icon' => 'weapon_apprentices_spellbook_i00',
    'weapon_type' => 'etc',
    'bodypart' => 'rhand',
    'crystal_count' => 2160,
    'crystal_type' => 'a',
    'weight' => 1600,
    'price' => 27000000,
    'soulshots' => 1,
    'spiritshots' => 1,
    'enchant_enabled' => true,
    'is_magic_weapon' => true,
    'stats' => 
    [
      'pAtk' => 186,
      'mAtk' => 152,
      'critRate' => 8,
      'pAtkSpd' => 379,
    ],
  ],
  344 => 
  [
    'id' => 344,
    'type' => 'weapon',
    'name' => 'Proof of Overlord',
    'add_name' => '',
    'description' => '',
    'icon' => 'weapon_apprentices_spellbook_i00',
    'weapon_type' => 'etc',
    'bodypart' => 'rhand',
    'crystal_count' => 2160,
    'crystal_type' => 'a',
    'weight' => 1600,
    'price' => 27000000,
    'soulshots' => 1,
    'spiritshots' => 1,
    'enchant_enabled' => true,
    'is_magic_weapon' => true,
    'stats' => 
    [
      'pAtk' => 186,
      'mAtk' => 152,
      'critRate' => 8,
      'pAtkSpd' => 379,
    ],
  ],
  345 => 
  [
    'id' => 345,
    'type' => 'weapon',
    'name' => 'Deathbringer Sword',
    'add_name' => '',
    'description' => '',
    'icon' => 'weapon_apprentices_spellbook_i00',
    'weapon_type' => 'etc',
    'bodypart' => 'rhand',
    'crystal_count' => 2160,
    'crystal_type' => 'a',
    'weight' => 4800,
    'price' => 27000000,
    'soulshots' => 1,
    'spiritshots' => 1,
    'enchant_enabled' => true,
    'is_magic_weapon' => true,
    'stats' => 
    [
      'pAtk' => 186,
      'mAtk' => 152,
      'critRate' => 8,
      'pAtkSpd' => 379,
    ],
  ],
  346 => 
  [
    'id' => 346,
    'type' => 'weapon',
    'name' => 'Tears of Fallen Angel',
    'add_name' => '',
    'description' => '',
    'icon' => 'weapon_apprentices_spellbook_i00',
    'weapon_type' => 'etc',
    'bodypart' => 'rhand',
    'crystal_count' => 1765,
    'crystal_type' => 's',
    'weight' => 1600,
    'price' => 35300000,
    'soulshots' => 1,
    'spiritshots' => 1,
    'enchant_enabled' => true,
    'is_magic_weapon' => true,
    'stats' => 
    [
      'pAtk' => 201,
      'mAtk' => 162,
      'critRate' => 8,
      'pAtkSpd' => 379,
    ],
  ],
  347 => 
  [
    'id' => 347,
    'type' => 'armor',
    'name' => 'Ring Mail Breastplate',
    'add_name' => '',
    'description' => '',
    'icon' => 'armor_t12_u_i00',
    'armor_type' => 'heavy',
    'bodypart' => 'chest',
    'crystal_count' => 119,
    'crystal_type' => 'd',
    'weight' => 8820,
    'price' => 64210,
    'enchant_enabled' => true,
    'stats' => 
    [
    ],
  ],
  348 => 
  [
    'id' => 348,
    'type' => 'armor',
    'name' => 'Scale Mail',
    'add_name' => '',
    'description' => '',
    'icon' => 'armor_t08_u_i00',
    'armor_type' => 'heavy',
    'bodypart' => 'chest',
    'crystal_count' => 189,
    'crystal_type' => 'd',
    'weight' => 8720,
    'price' => 102500,
    'enchant_enabled' => true,
    'stats' => 
    [
    ],
  ],
  349 => 
  [
    'id' => 349,
    'type' => 'armor',
    'name' => 'Compound Scale Mail',
    'add_name' => '',
    'description' => '',
    'icon' => 'armor_t20_u_i00',
    'armor_type' => 'heavy',
    'bodypart' => 'chest',
    'crystal_count' => 260,
    'crystal_type' => 'd',
    'weight' => 8620,
    'price' => 141100,
    'enchant_enabled' => true,
    'stats' => 
    [
    ],
  ],
  350 => 
  [
    'id' => 350,
    'type' => 'armor',
    'name' => 'Dwarven Scale Mail',
    'add_name' => '',
    'description' => '',
    'icon' => 'armor_t15_u_i00',
    'armor_type' => 'heavy',
    'bodypart' => 'chest',
    'crystal_count' => 260,
    'crystal_type' => 'd',
    'weight' => 8540,
    'price' => 141100,
    'enchant_enabled' => true,
    'stats' => 
    [
    ],
  ],
  351 => 
  [
    'id' => 351,
    'type' => 'armor',
    'name' => 'Blast Plate',
    'add_name' => '',
    'description' => '',
    'icon' => 'armor_t40_u_i00',
    'armor_type' => 'heavy',
    'bodypart' => 'chest',
    'crystal_count' => 288,
    'crystal_type' => 'd',
    'weight' => 8420,
    'price' => 156200,
    'enchant_enabled' => true,
    'stats' => 
    [
    ],
  ],
  352 => 
  [
    'id' => 352,
    'type' => 'armor',
    'name' => 'Brigandine Tunic',
    'add_name' => '',
    'description' => '',
    'icon' => 'armor_t43_u_i00',
    'armor_type' => 'heavy',
    'bodypart' => 'chest',
    'crystal_count' => 424,
    'crystal_type' => 'd',
    'weight' => 8320,
    'price' => 229700,
    'enchant_enabled' => true,
    'stats' => 
    [
    ],
  ],
  353 => 
  [
    'id' => 353,
    'type' => 'armor',
    'name' => 'Half Plate Armor',
    'add_name' => '',
    'description' => '',
    'icon' => 'armor_t46_u_i00',
    'armor_type' => 'heavy',
    'bodypart' => 'chest',
    'crystal_count' => 555,
    'crystal_type' => 'd',
    'weight' => 8220,
    'price' => 300800,
    'enchant_enabled' => true,
    'stats' => 
    [
    ],
  ],
  354 => 
  [
    'id' => 354,
    'type' => 'armor',
    'name' => 'Chain Mail Shirt',
    'add_name' => '',
    'description' => '',
    'icon' => 'armor_t48_u_i00',
    'armor_type' => 'heavy',
    'bodypart' => 'chest',
    'crystal_count' => 155,
    'crystal_type' => 'c',
    'weight' => 8120,
    'price' => 388600,
    'enchant_enabled' => true,
    'stats' => 
    [
    ],
  ],
  355 => 
  [
    'id' => 355,
    'type' => 'armor',
    'name' => 'Dwarven Chain Mail Shirt',
    'add_name' => '',
    'description' => '',
    'icon' => 'armor_t60_u_i00',
    'armor_type' => 'heavy',
    'bodypart' => 'chest',
    'crystal_count' => 198,
    'crystal_type' => 'c',
    'weight' => 8070,
    'price' => 495500,
    'enchant_enabled' => true,
    'stats' => 
    [
    ],
  ],
  356 => 
  [
    'id' => 356,
    'type' => 'armor',
    'name' => 'Full Plate Armor',
    'add_name' => '',
    'description' => 'Full body armor.',
    'icon' => 'armor_t62_ul_i00',
    'armor_type' => 'heavy',
    'bodypart' => 'onepiece',
    'crystal_count' => 715,
    'crystal_type' => 'c',
    'weight' => 10480,
    'price' => 1788000,
    'enchant_enabled' => true,
    'stats' => 
    [
    ],
  ],
  357 => 
  [
    'id' => 357,
    'type' => 'armor',
    'name' => 'Zubei\'s Breastplate',
    'add_name' => '',
    'description' => '',
    'icon' => 'armor_t64_u_i00',
    'armor_type' => 'heavy',
    'bodypart' => 'chest',
    'crystal_count' => 213,
    'crystal_type' => 'b',
    'weight' => 7970,
    'price' => 1596000,
    'enchant_enabled' => true,
    'stats' => 
    [
    ],
  ],
  358 => 
  [
    'id' => 358,
    'type' => 'armor',
    'name' => 'Blue Wolf Breastplate',
    'add_name' => '',
    'description' => '',
    'icon' => 'armor_t68_u_i00',
    'armor_type' => 'heavy',
    'bodypart' => 'chest',
    'crystal_count' => 330,
    'crystal_type' => 'b',
    'weight' => 7820,
    'price' => 2475000,
    'enchant_enabled' => true,
    'stats' => 
    [
    ],
  ],
  359 => 
  [
    'id' => 359,
    'type' => 'armor',
    'name' => 'Shining Dragon Armor',
    'add_name' => '',
    'description' => '',
    'icon' => 'armor_composite_armor_i02',
    'armor_type' => 'heavy',
    'bodypart' => 'onepiece',
    'crystal_count' => 902,
    'crystal_type' => 'b',
    'weight' => 6400,
    'price' => 5788000,
    'enchant_enabled' => true,
    'stats' => 
    [
    ],
  ],
  360 => 
  [
    'id' => 360,
    'type' => 'armor',
    'name' => 'Armor of Victory',
    'add_name' => '',
    'description' => '',
    'icon' => 'armor_dwarven_scale_mail_i00',
    'armor_type' => 'heavy',
    'bodypart' => 'chest',
    'crystal_count' => 429,
    'crystal_type' => 'b',
    'weight' => 3360,
    'price' => 2475000,
    'enchant_enabled' => true,
    'stats' => 
    [
    ],
  ],
  361 => 
  [
    'id' => 361,
    'type' => 'armor',
    'name' => 'Breastplate of Valor',
    'add_name' => '',
    'description' => '',
    'icon' => 'armor_dwarven_scale_mail_i00',
    'armor_type' => 'heavy',
    'bodypart' => 'chest',
    'crystal_count' => 617,
    'crystal_type' => 'b',
    'weight' => 3360,
    'price' => 3562000,
    'enchant_enabled' => true,
    'stats' => 
    [
    ],
  ],
  362 => 
  [
    'id' => 362,
    'type' => 'armor',
    'name' => 'Glorious Armor',
    'add_name' => '',
    'description' => '',
    'icon' => 'armor_composite_armor_i02',
    'armor_type' => 'heavy',
    'bodypart' => 'onepiece',
    'crystal_count' => 628,
    'crystal_type' => 'b',
    'weight' => 6720,
    'price' => 4022000,
    'enchant_enabled' => true,
    'stats' => 
    [
    ],
  ],
  363 => 
  [
    'id' => 363,
    'type' => 'armor',
    'name' => 'Red Flame Armor',
    'add_name' => '',
    'description' => '',
    'icon' => 'armor_composite_armor_i02',
    'armor_type' => 'heavy',
    'bodypart' => 'onepiece',
    'crystal_count' => 902,
    'crystal_type' => 'b',
    'weight' => 6400,
    'price' => 5788000,
    'enchant_enabled' => true,
    'stats' => 
    [
    ],
  ],
  364 => 
  [
    'id' => 364,
    'type' => 'armor',
    'name' => 'Elven Crystal Breastplate',
    'add_name' => '',
    'description' => '',
    'icon' => 'armor_dwarven_scale_mail_i00',
    'armor_type' => 'heavy',
    'bodypart' => 'chest',
    'crystal_count' => 429,
    'crystal_type' => 'b',
    'weight' => 2400,
    'price' => 2475000,
    'enchant_enabled' => true,
    'stats' => 
    [
    ],
  ],
  365 => 
  [
    'id' => 365,
    'type' => 'armor',
    'name' => 'Dark Crystal Breastplate',
    'add_name' => '',
    'description' => '',
    'icon' => 'armor_t74_u_i00',
    'armor_type' => 'heavy',
    'bodypart' => 'chest',
    'crystal_count' => 285,
    'crystal_type' => 'a',
    'weight' => 7700,
    'price' => 3562000,
    'enchant_enabled' => true,
    'stats' => 
    [
    ],
  ],
  366 => 
  [
    'id' => 366,
    'type' => 'armor',
    'name' => 'Implosion Armor',
    'add_name' => '',
    'description' => '',
    'icon' => 'armor_composite_armor_i02',
    'armor_type' => 'heavy',
    'bodypart' => 'onepiece',
    'crystal_count' => 628,
    'crystal_type' => 'b',
    'weight' => 6080,
    'price' => 4022000,
    'enchant_enabled' => true,
    'stats' => 
    [
    ],
  ],
  367 => 
  [
    'id' => 367,
    'type' => 'armor',
    'name' => 'Dark Dragon Armor',
    'add_name' => '',
    'description' => '',
    'icon' => 'armor_composite_armor_i02',
    'armor_type' => 'heavy',
    'bodypart' => 'onepiece',
    'crystal_count' => 902,
    'crystal_type' => 'b',
    'weight' => 5760,
    'price' => 5788000,
    'enchant_enabled' => true,
    'stats' => 
    [
    ],
  ],
  368 => 
  [
    'id' => 368,
    'type' => 'armor',
    'name' => 'Elven Vagian Armor',
    'add_name' => '',
    'description' => '',
    'icon' => 'armor_composite_armor_i02',
    'armor_type' => 'heavy',
    'bodypart' => 'onepiece',
    'crystal_count' => 628,
    'crystal_type' => 'b',
    'weight' => 2400,
    'price' => 4022000,
    'enchant_enabled' => true,
    'stats' => 
    [
    ],
  ],
  369 => 
  [
    'id' => 369,
    'type' => 'armor',
    'name' => 'Dark Vagian Armor',
    'add_name' => '',
    'description' => '',
    'icon' => 'armor_composite_armor_i02',
    'armor_type' => 'heavy',
    'bodypart' => 'onepiece',
    'crystal_count' => 902,
    'crystal_type' => 'b',
    'weight' => 2400,
    'price' => 5788000,
    'enchant_enabled' => true,
    'stats' => 
    [
    ],
  ],
  370 => 
  [
    'id' => 370,
    'type' => 'armor',
    'name' => 'Complete Set of Plate Armor',
    'add_name' => '',
    'description' => '',
    'icon' => 'armor_composite_armor_i02',
    'armor_type' => 'heavy',
    'bodypart' => 'onepiece',
    'crystal_count' => 628,
    'crystal_type' => 'b',
    'weight' => 6400,
    'price' => 4022000,
    'enchant_enabled' => true,
    'stats' => 
    [
    ],
  ],
  371 => 
  [
    'id' => 371,
    'type' => 'armor',
    'name' => 'Hell Plate',
    'add_name' => '',
    'description' => '',
    'icon' => 'armor_composite_armor_i02',
    'armor_type' => 'heavy',
    'bodypart' => 'onepiece',
    'crystal_count' => 902,
    'crystal_type' => 'b',
    'weight' => 6400,
    'price' => 5788000,
    'enchant_enabled' => true,
    'stats' => 
    [
    ],
  ],
  372 => 
  [
    'id' => 372,
    'type' => 'armor',
    'name' => 'Art of Plate',
    'add_name' => '',
    'description' => '',
    'icon' => 'armor_composite_armor_i02',
    'armor_type' => 'heavy',
    'bodypart' => 'onepiece',
    'crystal_count' => 628,
    'crystal_type' => 'b',
    'weight' => 6720,
    'price' => 4022000,
    'enchant_enabled' => true,
    'stats' => 
    [
    ],
  ],
  373 => 
  [
    'id' => 373,
    'type' => 'armor',
    'name' => 'Masterpiece Armor',
    'add_name' => '',
    'description' => '',
    'icon' => 'armor_composite_armor_i02',
    'armor_type' => 'heavy',
    'bodypart' => 'onepiece',
    'crystal_count' => 902,
    'crystal_type' => 'b',
    'weight' => 5600,
    'price' => 5788000,
    'enchant_enabled' => true,
    'stats' => 
    [
    ],
  ],
  374 => 
  [
    'id' => 374,
    'type' => 'armor',
    'name' => 'Armor of Nightmare',
    'add_name' => '',
    'description' => 'Full body armor.',
    'icon' => 'armor_t80_ul_i00',
    'armor_type' => 'heavy',
    'bodypart' => 'onepiece',
    'crystal_count' => 704,
    'crystal_type' => 'a',
    'weight' => 9580,
    'price' => 8804000,
    'enchant_enabled' => true,
    'stats' => 
    [
    ],
  ],
  375 => 
  [
    'id' => 375,
    'type' => 'armor',
    'name' => 'Dragon Scale Mail',
    'add_name' => '',
    'description' => '',
    'icon' => 'armor_t15_u_i00',
    'armor_type' => 'heavy',
    'bodypart' => 'chest',
    'crystal_count' => 525,
    'crystal_type' => 's',
    'weight' => 7620,
    'price' => 8291000,
    'enchant_enabled' => true,
    'is_tradable' => false,
    'is_dropable' => false,
    'is_sellable' => false,
    'stats' => 
    [
    ],
  ],
  376 => 
  [
    'id' => 376,
    'type' => 'armor',
    'name' => 'Iron Plate Gaiters',
    'add_name' => '',
    'description' => '',
    'icon' => 'armor_t12_l_i00',
    'armor_type' => 'heavy',
    'bodypart' => 'legs',
    'crystal_count' => 74,
    'crystal_type' => 'd',
    'weight' => 3820,
    'price' => 40100,
    'enchant_enabled' => true,
    'stats' => 
    [
    ],
  ],
  377 => 
  [
    'id' => 377,
    'type' => 'armor',
    'name' => 'Scale Gaiters',
    'add_name' => '',
    'description' => '',
    'icon' => 'armor_t08_l_i00',
    'armor_type' => 'heavy',
    'bodypart' => 'legs',
    'crystal_count' => 118,
    'crystal_type' => 'd',
    'weight' => 3860,
    'price' => 64100,
    'enchant_enabled' => true,
    'stats' => 
    [
    ],
  ],
  378 => 
  [
    'id' => 378,
    'type' => 'armor',
    'name' => 'Compound Scale Gaiters',
    'add_name' => '',
    'description' => '',
    'icon' => 'armor_t20_l_i00',
    'armor_type' => 'heavy',
    'bodypart' => 'legs',
    'crystal_count' => 180,
    'crystal_type' => 'd',
    'weight' => 3770,
    'price' => 97600,
    'enchant_enabled' => true,
    'stats' => 
    [
    ],
  ],
  379 => 
  [
    'id' => 379,
    'type' => 'armor',
    'name' => 'Dwarven Scale Gaiters',
    'add_name' => '',
    'description' => '',
    'icon' => 'armor_t15_l_i00',
    'armor_type' => 'heavy',
    'bodypart' => 'legs',
    'crystal_count' => 180,
    'crystal_type' => 'd',
    'weight' => 3840,
    'price' => 97600,
    'enchant_enabled' => true,
    'stats' => 
    [
    ],
  ],
  380 => 
  [
    'id' => 380,
    'type' => 'armor',
    'name' => 'Plate Gaiters',
    'add_name' => '',
    'description' => '',
    'icon' => 'armor_t46_l_i00',
    'armor_type' => 'heavy',
    'bodypart' => 'legs',
    'crystal_count' => 347,
    'crystal_type' => 'd',
    'weight' => 3770,
    'price' => 188000,
    'enchant_enabled' => true,
    'stats' => 
    [
    ],
  ],
  381 => 
  [
    'id' => 381,
    'type' => 'armor',
    'name' => 'Chain Gaiters',
    'add_name' => '',
    'description' => '',
    'icon' => 'armor_t48_l_i00',
    'armor_type' => 'heavy',
    'bodypart' => 'legs',
    'crystal_count' => 97,
    'crystal_type' => 'c',
    'weight' => 3680,
    'price' => 242900,
    'enchant_enabled' => true,
    'stats' => 
    [
    ],
  ],
  382 => 
  [
    'id' => 382,
    'type' => 'armor',
    'name' => 'Dwarven Chain Gaiters',
    'add_name' => '',
    'description' => '',
    'icon' => 'armor_t60_l_i00',
    'armor_type' => 'heavy',
    'bodypart' => 'legs',
    'crystal_count' => 124,
    'crystal_type' => 'c',
    'weight' => 3620,
    'price' => 309700,
    'enchant_enabled' => true,
    'stats' => 
    [
    ],
  ],
  383 => 
  [
    'id' => 383,
    'type' => 'armor',
    'name' => 'Zubei\'s Gaiters',
    'add_name' => '',
    'description' => '',
    'icon' => 'armor_t64_l_i00',
    'armor_type' => 'heavy',
    'bodypart' => 'legs',
    'crystal_count' => 133,
    'crystal_type' => 'b',
    'weight' => 3570,
    'price' => 997700,
    'enchant_enabled' => true,
    'stats' => 
    [
    ],
  ],
  384 => 
  [
    'id' => 384,
    'type' => 'armor',
    'name' => 'Wolf Gaiters',
    'add_name' => '',
    'description' => '',
    'icon' => 'armor_plate_gaiters_i00',
    'armor_type' => 'heavy',
    'bodypart' => 'legs',
    'crystal_count' => 268,
    'crystal_type' => 'b',
    'weight' => 2560,
    'price' => 1547100,
    'enchant_enabled' => true,
    'stats' => 
    [
    ],
  ],
  385 => 
  [
    'id' => 385,
    'type' => 'armor',
    'name' => 'Gaiters of Victory',
    'add_name' => '',
    'description' => '',
    'icon' => 'armor_plate_gaiters_i00',
    'armor_type' => 'heavy',
    'bodypart' => 'legs',
    'crystal_count' => 268,
    'crystal_type' => 'b',
    'weight' => 2240,
    'price' => 1547100,
    'enchant_enabled' => true,
    'stats' => 
    [
    ],
  ],
  386 => 
  [
    'id' => 386,
    'type' => 'armor',
    'name' => 'Gaiters of Valor',
    'add_name' => '',
    'description' => '',
    'icon' => 'armor_plate_gaiters_i00',
    'armor_type' => 'heavy',
    'bodypart' => 'legs',
    'crystal_count' => 385,
    'crystal_type' => 'b',
    'weight' => 2240,
    'price' => 2226000,
    'enchant_enabled' => true,
    'stats' => 
    [
    ],
  ],
  387 => 
  [
    'id' => 387,
    'type' => 'armor',
    'name' => 'Elven Crystal Gaiters',
    'add_name' => '',
    'description' => '',
    'icon' => 'armor_plate_gaiters_i00',
    'armor_type' => 'heavy',
    'bodypart' => 'legs',
    'crystal_count' => 268,
    'crystal_type' => 'b',
    'weight' => 2240,
    'price' => 1547100,
    'enchant_enabled' => true,
    'stats' => 
    [
    ],
  ],
  388 => 
  [
    'id' => 388,
    'type' => 'armor',
    'name' => 'Dark Crystal Gaiters',
    'add_name' => '',
    'description' => '',
    'icon' => 'armor_t74_l_i00',
    'armor_type' => 'heavy',
    'bodypart' => 'legs',
    'crystal_count' => 178,
    'crystal_type' => 'a',
    'weight' => 3320,
    'price' => 2226000,
    'enchant_enabled' => true,
    'stats' => 
    [
    ],
  ],
  389 => 
  [
    'id' => 389,
    'type' => 'armor',
    'name' => 'Dragon Scale Gaiters',
    'add_name' => '',
    'description' => '',
    'icon' => 'armor_t15_l_i00',
    'armor_type' => 'heavy',
    'bodypart' => 'legs',
    'crystal_count' => 299,
    'crystal_type' => 's',
    'weight' => 3260,
    'price' => 4640000,
    'enchant_enabled' => true,
    'is_tradable' => false,
    'is_dropable' => false,
    'is_sellable' => false,
    'stats' => 
    [
    ],
  ],
  390 => 
  [
    'id' => 390,
    'type' => 'armor',
    'name' => 'Cotton Shirt',
    'add_name' => '',
    'description' => '',
    'icon' => 'armor_t07_u_i00',
    'armor_type' => 'light',
    'bodypart' => 'chest',
    'weight' => 4770,
    'price' => 15600,
    'stats' => 
    [
    ],
  ],
  391 => 
  [
    'id' => 391,
    'type' => 'armor',
    'name' => 'Puma Skin Shirt',
    'add_name' => '',
    'description' => '',
    'icon' => 'armor_t09_u_i00',
    'armor_type' => 'light',
    'bodypart' => 'chest',
    'crystal_count' => 89,
    'crystal_type' => 'd',
    'weight' => 4700,
    'price' => 48200,
    'enchant_enabled' => true,
    'stats' => 
    [
    ],
  ],
  392 => 
  [
    'id' => 392,
    'type' => 'armor',
    'name' => 'Lion Skin Shirt',
    'add_name' => '',
    'description' => '',
    'icon' => 'armor_t18_u_i00',
    'armor_type' => 'light',
    'bodypart' => 'chest',
    'crystal_count' => 142,
    'crystal_type' => 'd',
    'weight' => 4580,
    'price' => 76900,
    'enchant_enabled' => true,
    'stats' => 
    [
    ],
  ],
  393 => 
  [
    'id' => 393,
    'type' => 'armor',
    'name' => 'Mithril Banded Mail',
    'add_name' => '',
    'description' => '',
    'icon' => 'armor_t10_u_i00',
    'armor_type' => 'light',
    'bodypart' => 'chest',
    'crystal_count' => 216,
    'crystal_type' => 'd',
    'weight' => 4570,
    'price' => 117000,
    'enchant_enabled' => true,
    'stats' => 
    [
    ],
  ],
  394 => 
  [
    'id' => 394,
    'type' => 'armor',
    'name' => 'Reinforced Leather Shirt',
    'add_name' => '',
    'description' => '',
    'icon' => 'armor_t13_u_i00',
    'armor_type' => 'light',
    'bodypart' => 'chest',
    'crystal_count' => 216,
    'crystal_type' => 'd',
    'weight' => 4570,
    'price' => 117000,
    'enchant_enabled' => true,
    'stats' => 
    [
    ],
  ],
  395 => 
  [
    'id' => 395,
    'type' => 'armor',
    'name' => 'Manticore Skin Shirt',
    'add_name' => '',
    'description' => '',
    'icon' => 'armor_t42_u_i00',
    'armor_type' => 'light',
    'bodypart' => 'chest',
    'crystal_count' => 318,
    'crystal_type' => 'd',
    'weight' => 4520,
    'price' => 172000,
    'enchant_enabled' => true,
    'stats' => 
    [
    ],
  ],
  396 => 
  [
    'id' => 396,
    'type' => 'armor',
    'name' => 'Salamander Skin Mail',
    'add_name' => '',
    'description' => 'One-piece upper and lower body armor. Additional lower body armor cannot be worn while wearing this.',
    'icon' => 'armor_t45_ul_i00',
    'armor_type' => 'light',
    'bodypart' => 'onepiece',
    'crystal_count' => 677,
    'crystal_type' => 'd',
    'weight' => 6100,
    'price' => 366600,
    'enchant_enabled' => true,
    'stats' => 
    [
    ],
  ],
  397 => 
  [
    'id' => 397,
    'type' => 'armor',
    'name' => 'Mithril Shirt',
    'add_name' => '',
    'description' => '',
    'icon' => 'armor_t47_u_i00',
    'armor_type' => 'light',
    'bodypart' => 'chest',
    'crystal_count' => 116,
    'crystal_type' => 'c',
    'weight' => 4470,
    'price' => 291000,
    'enchant_enabled' => true,
    'stats' => 
    [
    ],
  ],
  398 => 
  [
    'id' => 398,
    'type' => 'armor',
    'name' => 'Plated Leather',
    'add_name' => '',
    'description' => '',
    'icon' => 'armor_t47_u_i00',
    'armor_type' => 'light',
    'bodypart' => 'chest',
    'crystal_count' => 137,
    'crystal_type' => 'c',
    'weight' => 4450,
    'price' => 343000,
    'enchant_enabled' => true,
    'stats' => 
    [
    ],
  ],
  399 => 
  [
    'id' => 399,
    'type' => 'armor',
    'name' => 'Rind Leather Armor',
    'add_name' => '',
    'description' => '',
    'icon' => 'armor_t49_u_i00',
    'armor_type' => 'light',
    'bodypart' => 'chest',
    'crystal_count' => 149,
    'crystal_type' => 'c',
    'weight' => 4420,
    'price' => 372000,
    'enchant_enabled' => true,
    'stats' => 
    [
    ],
  ],
];