<?php return [
  13600 => 
  [
    'item_id' => 13600,
    'icon' => 'scroll_of_verification_i00',
    'name' => 'Transformation Scroll: Giran Archer Mercenary',
    'additionalname' => '',
    'description' => 'Allows you to transform into an Archer mercenary. Can only be used by an elite mercenary in Giran Territory.',
    'is_trade' => 0,
    'is_drop' => 0,
    'is_destruct' => 1,
    'crystal_type' => 'none',
    'consume_type' => 'consume_type_stackable',
  ],
  13601 => 
  [
    'item_id' => 13601,
    'icon' => 'scroll_of_verification_i00',
    'name' => 'Transformation Scroll: Giran Wizard Mercenary',
    'additionalname' => '',
    'description' => 'Allows you to transform into a Wizard mercenary. Can only be used by an elite mercenary in Giran Territory.',
    'is_trade' => 0,
    'is_drop' => 0,
    'is_destruct' => 1,
    'crystal_type' => 'none',
    'consume_type' => 'consume_type_stackable',
  ],
  13602 => 
  [
    'item_id' => 13602,
    'icon' => 'scroll_of_verification_i00',
    'name' => 'Transformation Scroll: Giran Centurion Mercenary',
    'additionalname' => '',
    'description' => 'Allows you to transform into a Centurion Mercenary. Can only be used by an elite mercenary in Giran Territory.',
    'is_trade' => 0,
    'is_drop' => 0,
    'is_destruct' => 1,
    'crystal_type' => 'none',
    'consume_type' => 'consume_type_stackable',
  ],
  13603 => 
  [
    'item_id' => 13603,
    'icon' => 'scroll_of_verification_i00',
    'name' => 'Transformation Scroll: Giran Knight Captain Mercenary',
    'additionalname' => '',
    'description' => 'Allows you to transform into a Knight Captain mercenary. Can only be used by an Exalted Mercenary in Giran Territory.',
    'is_trade' => 0,
    'is_drop' => 0,
    'is_destruct' => 1,
    'crystal_type' => 'none',
    'consume_type' => 'consume_type_stackable',
  ],
  13604 => 
  [
    'item_id' => 13604,
    'icon' => 'scroll_of_verification_i00',
    'name' => 'Transformation Scroll: Giran Commander Mercenary',
    'additionalname' => '',
    'description' => 'Allows you to transform into a Commander mercenary. Can only be used by an Exalted Mercenary in Giran Territory.',
    'is_trade' => 0,
    'is_drop' => 0,
    'is_destruct' => 1,
    'crystal_type' => 'none',
    'consume_type' => 'consume_type_stackable',
  ],
  13605 => 
  [
    'item_id' => 13605,
    'icon' => 'scroll_of_verification_i00',
    'name' => 'Transformation Scroll: Oren Human Mercenary',
    'additionalname' => '',
    'description' => 'Allows you to transform into a Human mercenary. Can only be used by an ordinary mercenary in Oren Territory.',
    'is_trade' => 0,
    'is_drop' => 0,
    'is_destruct' => 1,
    'crystal_type' => 'none',
    'consume_type' => 'consume_type_stackable',
  ],
  13606 => 
  [
    'item_id' => 13606,
    'icon' => 'scroll_of_verification_i00',
    'name' => 'Transformation Scroll: Oren Elf Mercenary',
    'additionalname' => '',
    'description' => 'Allows you to transform into an Elven mercenary. Can only be used by an ordinary mercenary in Oren Territory.',
    'is_trade' => 0,
    'is_drop' => 0,
    'is_destruct' => 1,
    'crystal_type' => 'none',
    'consume_type' => 'consume_type_stackable',
  ],
  13607 => 
  [
    'item_id' => 13607,
    'icon' => 'scroll_of_verification_i00',
    'name' => 'Transformation Scroll: Oren Dark Elf Mercenary',
    'additionalname' => '',
    'description' => 'Allows you to transform into a Dark Elven mercenary. Can only be used by an ordinary mercenary in Oren Territory.',
    'is_trade' => 0,
    'is_drop' => 0,
    'is_destruct' => 1,
    'crystal_type' => 'none',
    'consume_type' => 'consume_type_stackable',
  ],
  13608 => 
  [
    'item_id' => 13608,
    'icon' => 'scroll_of_verification_i00',
    'name' => 'Transformation Scroll: Oren Orc Mercenary',
    'additionalname' => '',
    'description' => 'Allows you to transform into an Orc mercenary. Can only be used by an ordinary mercenary in Oren Territory.',
    'is_trade' => 0,
    'is_drop' => 0,
    'is_destruct' => 1,
    'crystal_type' => 'none',
    'consume_type' => 'consume_type_stackable',
  ],
  13609 => 
  [
    'item_id' => 13609,
    'icon' => 'scroll_of_verification_i00',
    'name' => 'Transformation Scroll: Oren Dwarf Mercenary',
    'additionalname' => '',
    'description' => 'Allows you to transform into a Dwarven mercenary. Can only be used by an ordinary mercenary in Oren Territory.',
    'is_trade' => 0,
    'is_drop' => 0,
    'is_destruct' => 1,
    'crystal_type' => 'none',
    'consume_type' => 'consume_type_stackable',
  ],
  13610 => 
  [
    'item_id' => 13610,
    'icon' => 'scroll_of_verification_i00',
    'name' => 'Transformation Scroll: Oren Kamael Mercenary',
    'additionalname' => '',
    'description' => 'Allows you to transform into a Kamael mercenary. Can only be used by an ordinary mercenary in Oren Territory.',
    'is_trade' => 0,
    'is_drop' => 0,
    'is_destruct' => 1,
    'crystal_type' => 'none',
    'consume_type' => 'consume_type_stackable',
  ],
  13611 => 
  [
    'item_id' => 13611,
    'icon' => 'scroll_of_verification_i00',
    'name' => 'Transformation Scroll: Oren Knight Mercenary',
    'additionalname' => '',
    'description' => 'Allows you to transform into a Knight mercenary. Can only be used by an elite mercenary in Oren Territory.',
    'is_trade' => 0,
    'is_drop' => 0,
    'is_destruct' => 1,
    'crystal_type' => 'none',
    'consume_type' => 'consume_type_stackable',
  ],
  13612 => 
  [
    'item_id' => 13612,
    'icon' => 'scroll_of_verification_i00',
    'name' => 'Transformation Scroll: Oren Archer Mercenary',
    'additionalname' => '',
    'description' => 'Allows you to transform into an Archer mercenary. Can only be used by an elite mercenary in Oren Territory.',
    'is_trade' => 0,
    'is_drop' => 0,
    'is_destruct' => 1,
    'crystal_type' => 'none',
    'consume_type' => 'consume_type_stackable',
  ],
  13613 => 
  [
    'item_id' => 13613,
    'icon' => 'scroll_of_verification_i00',
    'name' => 'Transformation Scroll: Oren Wizard Mercenary',
    'additionalname' => '',
    'description' => 'Allows you to transform into a Wizard mercenary. Can only be used by an elite mercenary in Oren Territory.',
    'is_trade' => 0,
    'is_drop' => 0,
    'is_destruct' => 1,
    'crystal_type' => 'none',
    'consume_type' => 'consume_type_stackable',
  ],
  13614 => 
  [
    'item_id' => 13614,
    'icon' => 'scroll_of_verification_i00',
    'name' => 'Transformation Scroll: Oren Centurion Mercenary',
    'additionalname' => '',
    'description' => 'Allows you to transform into a Centurion Mercenary. Can only be used by an elite mercenary in Oren Territory.',
    'is_trade' => 0,
    'is_drop' => 0,
    'is_destruct' => 1,
    'crystal_type' => 'none',
    'consume_type' => 'consume_type_stackable',
  ],
  13615 => 
  [
    'item_id' => 13615,
    'icon' => 'scroll_of_verification_i00',
    'name' => 'Transformation Scroll: Oren Knight Captain Mercenary',
    'additionalname' => '',
    'description' => 'Allows you to transform into a Knight Captain mercenary. Can only be used by an Exalted Mercenary in Oren Territory.',
    'is_trade' => 0,
    'is_drop' => 0,
    'is_destruct' => 1,
    'crystal_type' => 'none',
    'consume_type' => 'consume_type_stackable',
  ],
  13616 => 
  [
    'item_id' => 13616,
    'icon' => 'scroll_of_verification_i00',
    'name' => 'Transformation Scroll: Oren Commander Mercenary',
    'additionalname' => '',
    'description' => 'Allows you to transform into a Commander mercenary. Can only be used by an Exalted Mercenary in Oren Territory.',
    'is_trade' => 0,
    'is_drop' => 0,
    'is_destruct' => 1,
    'crystal_type' => 'none',
    'consume_type' => 'consume_type_stackable',
  ],
  13617 => 
  [
    'item_id' => 13617,
    'icon' => 'scroll_of_verification_i00',
    'name' => 'Transformation Scroll: Aden Human Mercenary',
    'additionalname' => '',
    'description' => 'Allows you to transform into a Human mercenary. Can only be used by an ordinary mercenary in Aden Territory.',
    'is_trade' => 0,
    'is_drop' => 0,
    'is_destruct' => 1,
    'crystal_type' => 'none',
    'consume_type' => 'consume_type_stackable',
  ],
  13618 => 
  [
    'item_id' => 13618,
    'icon' => 'scroll_of_verification_i00',
    'name' => 'Transformation Scroll: Aden Elf Mercenary',
    'additionalname' => '',
    'description' => 'Allows you to transform into an Elven mercenary. Can only be used by an ordinary mercenary in Aden Territory.',
    'is_trade' => 0,
    'is_drop' => 0,
    'is_destruct' => 1,
    'crystal_type' => 'none',
    'consume_type' => 'consume_type_stackable',
  ],
  13619 => 
  [
    'item_id' => 13619,
    'icon' => 'scroll_of_verification_i00',
    'name' => 'Transformation Scroll: Aden Dark Elf Mercenary',
    'additionalname' => '',
    'description' => 'Allows you to transform into a Dark Elven mercenary. Can only be used by an ordinary mercenary in Aden Territory.',
    'is_trade' => 0,
    'is_drop' => 0,
    'is_destruct' => 1,
    'crystal_type' => 'none',
    'consume_type' => 'consume_type_stackable',
  ],
  13620 => 
  [
    'item_id' => 13620,
    'icon' => 'scroll_of_verification_i00',
    'name' => 'Transformation Scroll: Aden Orc Mercenary',
    'additionalname' => '',
    'description' => 'Allows you to transform into an Orc mercenary. Can only be used by an ordinary mercenary in Aden Territory.',
    'is_trade' => 0,
    'is_drop' => 0,
    'is_destruct' => 1,
    'crystal_type' => 'none',
    'consume_type' => 'consume_type_stackable',
  ],
  13621 => 
  [
    'item_id' => 13621,
    'icon' => 'scroll_of_verification_i00',
    'name' => 'Transformation Scroll: Aden Dwarf Mercenary',
    'additionalname' => '',
    'description' => 'Allows you to transform into a Dwarven mercenary. Can only be used by an ordinary mercenary in Aden Territory.',
    'is_trade' => 0,
    'is_drop' => 0,
    'is_destruct' => 1,
    'crystal_type' => 'none',
    'consume_type' => 'consume_type_stackable',
  ],
  13622 => 
  [
    'item_id' => 13622,
    'icon' => 'scroll_of_verification_i00',
    'name' => 'Transformation Scroll: Aden Kamael Mercenary',
    'additionalname' => '',
    'description' => 'Allows you to transform into a Kamael mercenary. Can only be used by an ordinary mercenary in Aden Territory.',
    'is_trade' => 0,
    'is_drop' => 0,
    'is_destruct' => 1,
    'crystal_type' => 'none',
    'consume_type' => 'consume_type_stackable',
  ],
  13623 => 
  [
    'item_id' => 13623,
    'icon' => 'scroll_of_verification_i00',
    'name' => 'Transformation Scroll: Aden Knight Mercenary',
    'additionalname' => '',
    'description' => 'Allows you to transform into a Knight mercenary. Can only be used by an elite mercenary in Aden Territory.',
    'is_trade' => 0,
    'is_drop' => 0,
    'is_destruct' => 1,
    'crystal_type' => 'none',
    'consume_type' => 'consume_type_stackable',
  ],
  13624 => 
  [
    'item_id' => 13624,
    'icon' => 'scroll_of_verification_i00',
    'name' => 'Transformation Scroll: Aden Archer Mercenary',
    'additionalname' => '',
    'description' => 'Allows you to transform into an Archer mercenary. Can only be used by an elite mercenary in Aden Territory.',
    'is_trade' => 0,
    'is_drop' => 0,
    'is_destruct' => 1,
    'crystal_type' => 'none',
    'consume_type' => 'consume_type_stackable',
  ],
  13625 => 
  [
    'item_id' => 13625,
    'icon' => 'scroll_of_verification_i00',
    'name' => 'Transformation Scroll: Aden Wizard Mercenary',
    'additionalname' => '',
    'description' => 'Allows you to transform into a Wizard mercenary. Can only be used by an elite mercenary in Aden Territory.',
    'is_trade' => 0,
    'is_drop' => 0,
    'is_destruct' => 1,
    'crystal_type' => 'none',
    'consume_type' => 'consume_type_stackable',
  ],
  13626 => 
  [
    'item_id' => 13626,
    'icon' => 'scroll_of_verification_i00',
    'name' => 'Transformation Scroll: Aden Centurion Mercenary',
    'additionalname' => '',
    'description' => 'Allows you to transform into a Centurion Mercenary. Can only be used by an elite mercenary in Aden Territory.',
    'is_trade' => 0,
    'is_drop' => 0,
    'is_destruct' => 1,
    'crystal_type' => 'none',
    'consume_type' => 'consume_type_stackable',
  ],
  13627 => 
  [
    'item_id' => 13627,
    'icon' => 'scroll_of_verification_i00',
    'name' => 'Transformation Scroll: Aden Knight Captain Mercenary',
    'additionalname' => '',
    'description' => 'Allows you to transform into a Knight Captain mercenary. Can only be used by an Exalted Mercenary in Aden Territory.',
    'is_trade' => 0,
    'is_drop' => 0,
    'is_destruct' => 1,
    'crystal_type' => 'none',
    'consume_type' => 'consume_type_stackable',
  ],
  13628 => 
  [
    'item_id' => 13628,
    'icon' => 'scroll_of_verification_i00',
    'name' => 'Transformation Scroll: Aden Commander Mercenary',
    'additionalname' => '',
    'description' => 'Allows you to transform into a Commander mercenary. Can only be used by an Exalted Mercenary in Aden Territory.',
    'is_trade' => 0,
    'is_drop' => 0,
    'is_destruct' => 1,
    'crystal_type' => 'none',
    'consume_type' => 'consume_type_stackable',
  ],
  13629 => 
  [
    'item_id' => 13629,
    'icon' => 'scroll_of_verification_i00',
    'name' => 'Transformation Scroll: Innadril Human Mercenary',
    'additionalname' => '',
    'description' => 'Allows you to transform into a Human mercenary. Can only be used by an ordinary mercenary in Innadril Territory.',
    'is_trade' => 0,
    'is_drop' => 0,
    'is_destruct' => 1,
    'crystal_type' => 'none',
    'consume_type' => 'consume_type_stackable',
  ],
  13630 => 
  [
    'item_id' => 13630,
    'icon' => 'scroll_of_verification_i00',
    'name' => 'Transformation Scroll: Innadril Elf Mercenary',
    'additionalname' => '',
    'description' => 'Allows you to transform into an Elven mercenary. Can only be used by an ordinary mercenary in Innadril Territory.',
    'is_trade' => 0,
    'is_drop' => 0,
    'is_destruct' => 1,
    'crystal_type' => 'none',
    'consume_type' => 'consume_type_stackable',
  ],
  13631 => 
  [
    'item_id' => 13631,
    'icon' => 'scroll_of_verification_i00',
    'name' => 'Transformation Scroll: Innadril Dark Elf Mercenary',
    'additionalname' => '',
    'description' => 'Allows you to transform into a Dark Elven mercenary. Can only be used by an ordinary mercenary in Innadril Territory.',
    'is_trade' => 0,
    'is_drop' => 0,
    'is_destruct' => 1,
    'crystal_type' => 'none',
    'consume_type' => 'consume_type_stackable',
  ],
  13632 => 
  [
    'item_id' => 13632,
    'icon' => 'scroll_of_verification_i00',
    'name' => 'Transformation Scroll: Innadril Orc Mercenary',
    'additionalname' => '',
    'description' => 'Allows you to transform into an Orc mercenary. Can only be used by an ordinary mercenary in Innadril Territory.',
    'is_trade' => 0,
    'is_drop' => 0,
    'is_destruct' => 1,
    'crystal_type' => 'none',
    'consume_type' => 'consume_type_stackable',
  ],
  13633 => 
  [
    'item_id' => 13633,
    'icon' => 'scroll_of_verification_i00',
    'name' => 'Transformation Scroll: Innadril Dwarf Mercenary',
    'additionalname' => '',
    'description' => 'Allows you to transform into a Dwarven mercenary. Can only be used by an ordinary mercenary in Innadril Territory.',
    'is_trade' => 0,
    'is_drop' => 0,
    'is_destruct' => 1,
    'crystal_type' => 'none',
    'consume_type' => 'consume_type_stackable',
  ],
  13634 => 
  [
    'item_id' => 13634,
    'icon' => 'scroll_of_verification_i00',
    'name' => 'Transformation Scroll: Innadril Kamael Mercenary',
    'additionalname' => '',
    'description' => 'Allows you to transform into a Kamael mercenary. Can only be used by an ordinary mercenary in Innadril Territory.',
    'is_trade' => 0,
    'is_drop' => 0,
    'is_destruct' => 1,
    'crystal_type' => 'none',
    'consume_type' => 'consume_type_stackable',
  ],
  13635 => 
  [
    'item_id' => 13635,
    'icon' => 'scroll_of_verification_i00',
    'name' => 'Transformation Scroll: Innadril Knight Mercenary',
    'additionalname' => '',
    'description' => 'Allows you to transform into a Knight mercenary. Can only be used by an elite mercenary in Innadril Territory.',
    'is_trade' => 0,
    'is_drop' => 0,
    'is_destruct' => 1,
    'crystal_type' => 'none',
    'consume_type' => 'consume_type_stackable',
  ],
  13636 => 
  [
    'item_id' => 13636,
    'icon' => 'scroll_of_verification_i00',
    'name' => 'Transformation Scroll: Innadril Archer Mercenary',
    'additionalname' => '',
    'description' => 'Allows you to transform into an Archer mercenary. Can only be used by an elite mercenary in Innadril Territory.',
    'is_trade' => 0,
    'is_drop' => 0,
    'is_destruct' => 1,
    'crystal_type' => 'none',
    'consume_type' => 'consume_type_stackable',
  ],
  13637 => 
  [
    'item_id' => 13637,
    'icon' => 'scroll_of_verification_i00',
    'name' => 'Transformation Scroll: Innadril Wizard Mercenary',
    'additionalname' => '',
    'description' => 'Allows you to transform into a Wizard mercenary. Can only be used by an elite mercenary in Innadril Territory.',
    'is_trade' => 0,
    'is_drop' => 0,
    'is_destruct' => 1,
    'crystal_type' => 'none',
    'consume_type' => 'consume_type_stackable',
  ],
  13638 => 
  [
    'item_id' => 13638,
    'icon' => 'scroll_of_verification_i00',
    'name' => 'Transformation Scroll: Innadril Centurion Mercenary',
    'additionalname' => '',
    'description' => 'Allows you to transform into a Centurion Mercenary. Can only be used by an elite mercenary in Innadril Territory.',
    'is_trade' => 0,
    'is_drop' => 0,
    'is_destruct' => 1,
    'crystal_type' => 'none',
    'consume_type' => 'consume_type_stackable',
  ],
  13639 => 
  [
    'item_id' => 13639,
    'icon' => 'scroll_of_verification_i00',
    'name' => 'Transformation Scroll: Innadril Knight Captain Mercenary',
    'additionalname' => '',
    'description' => 'Allows you to transform into a Knight Captain mercenary. Can only be used by an Exalted Mercenary in Innadril Territory.',
    'is_trade' => 0,
    'is_drop' => 0,
    'is_destruct' => 1,
    'crystal_type' => 'none',
    'consume_type' => 'consume_type_stackable',
  ],
  13640 => 
  [
    'item_id' => 13640,
    'icon' => 'scroll_of_verification_i00',
    'name' => 'Transformation Scroll: Innadril Commander Mercenary',
    'additionalname' => '',
    'description' => 'Allows you to transform into a Commander mercenary. Can only be used by an Exalted Mercenary in Innadril Territory.',
    'is_trade' => 0,
    'is_drop' => 0,
    'is_destruct' => 1,
    'crystal_type' => 'none',
    'consume_type' => 'consume_type_stackable',
  ],
  13641 => 
  [
    'item_id' => 13641,
    'icon' => 'scroll_of_verification_i00',
    'name' => 'Transformation Scroll: Goddard Human Mercenary',
    'additionalname' => '',
    'description' => 'Allows you to transform into a Human mercenary. Can only be used by an ordinary mercenary in Goddard Territory.',
    'is_trade' => 0,
    'is_drop' => 0,
    'is_destruct' => 1,
    'crystal_type' => 'none',
    'consume_type' => 'consume_type_stackable',
  ],
  13642 => 
  [
    'item_id' => 13642,
    'icon' => 'scroll_of_verification_i00',
    'name' => 'Transformation Scroll: Goddard Elf Mercenary',
    'additionalname' => '',
    'description' => 'Allows you to transform into an Elven mercenary. Can only be used by an ordinary mercenary in Goddard Territory.',
    'is_trade' => 0,
    'is_drop' => 0,
    'is_destruct' => 1,
    'crystal_type' => 'none',
    'consume_type' => 'consume_type_stackable',
  ],
  13643 => 
  [
    'item_id' => 13643,
    'icon' => 'scroll_of_verification_i00',
    'name' => 'Transformation Scroll: Goddard Dark Elf Mercenary',
    'additionalname' => '',
    'description' => 'Allows you to transform into a Dark Elven mercenary. Can only be used by an ordinary mercenary in Goddard Territory.',
    'is_trade' => 0,
    'is_drop' => 0,
    'is_destruct' => 1,
    'crystal_type' => 'none',
    'consume_type' => 'consume_type_stackable',
  ],
  13644 => 
  [
    'item_id' => 13644,
    'icon' => 'scroll_of_verification_i00',
    'name' => 'Transformation Scroll: Goddard Orc Mercenary',
    'additionalname' => '',
    'description' => 'Allows you to transform into an Orc mercenary. Can only be used by an ordinary mercenary in Goddard Territory.',
    'is_trade' => 0,
    'is_drop' => 0,
    'is_destruct' => 1,
    'crystal_type' => 'none',
    'consume_type' => 'consume_type_stackable',
  ],
  13645 => 
  [
    'item_id' => 13645,
    'icon' => 'scroll_of_verification_i00',
    'name' => 'Transformation Scroll: Goddard Dwarf Mercenary',
    'additionalname' => '',
    'description' => 'Allows you to transform into a Dwarven mercenary. Can only be used by an ordinary mercenary in Goddard Territory.',
    'is_trade' => 0,
    'is_drop' => 0,
    'is_destruct' => 1,
    'crystal_type' => 'none',
    'consume_type' => 'consume_type_stackable',
  ],
  13646 => 
  [
    'item_id' => 13646,
    'icon' => 'scroll_of_verification_i00',
    'name' => 'Transformation Scroll: Goddard Kamael Mercenary',
    'additionalname' => '',
    'description' => 'Allows you to transform into a Kamael mercenary. Can only be used by an ordinary mercenary in Goddard Territory.',
    'is_trade' => 0,
    'is_drop' => 0,
    'is_destruct' => 1,
    'crystal_type' => 'none',
    'consume_type' => 'consume_type_stackable',
  ],
  13647 => 
  [
    'item_id' => 13647,
    'icon' => 'scroll_of_verification_i00',
    'name' => 'Transformation Scroll: Goddard Knight Mercenary',
    'additionalname' => '',
    'description' => 'Allows you to transform into a Knight mercenary. Can only be used by an elite mercenary in Goddard Territory.',
    'is_trade' => 0,
    'is_drop' => 0,
    'is_destruct' => 1,
    'crystal_type' => 'none',
    'consume_type' => 'consume_type_stackable',
  ],
  13648 => 
  [
    'item_id' => 13648,
    'icon' => 'scroll_of_verification_i00',
    'name' => 'Transformation Scroll: Goddard Archer Mercenary',
    'additionalname' => '',
    'description' => 'Allows you to transform into an Archer mercenary. Can only be used by an elite mercenary in Goddard Territory.',
    'is_trade' => 0,
    'is_drop' => 0,
    'is_destruct' => 1,
    'crystal_type' => 'none',
    'consume_type' => 'consume_type_stackable',
  ],
  13649 => 
  [
    'item_id' => 13649,
    'icon' => 'scroll_of_verification_i00',
    'name' => 'Transformation Scroll: Goddard Wizard Mercenary',
    'additionalname' => '',
    'description' => 'Allows you to transform into a Wizard mercenary. Can only be used by an elite mercenary in Goddard Territory.',
    'is_trade' => 0,
    'is_drop' => 0,
    'is_destruct' => 1,
    'crystal_type' => 'none',
    'consume_type' => 'consume_type_stackable',
  ],
  13650 => 
  [
    'item_id' => 13650,
    'icon' => 'scroll_of_verification_i00',
    'name' => 'Transformation Scroll: Goddard Centurion Mercenary',
    'additionalname' => '',
    'description' => 'Allows you to transform into a Centurion Mercenary. Can only be used by an elite mercenary in Goddard Territory.',
    'is_trade' => 0,
    'is_drop' => 0,
    'is_destruct' => 1,
    'crystal_type' => 'none',
    'consume_type' => 'consume_type_stackable',
  ],
  13651 => 
  [
    'item_id' => 13651,
    'icon' => 'scroll_of_verification_i00',
    'name' => 'Transformation Scroll: Goddard Knight Captain Mercenary',
    'additionalname' => '',
    'description' => 'Allows you to transform into a Knight Captain mercenary. Can only be used by an Exalted Mercenary in Goddard Territory.',
    'is_trade' => 0,
    'is_drop' => 0,
    'is_destruct' => 1,
    'crystal_type' => 'none',
    'consume_type' => 'consume_type_stackable',
  ],
  13652 => 
  [
    'item_id' => 13652,
    'icon' => 'scroll_of_verification_i00',
    'name' => 'Transformation Scroll: Goddard Commander Mercenary',
    'additionalname' => '',
    'description' => 'Allows you to transform into a Commander mercenary. Can only be used by an Exalted Mercenary in Goddard Territory.',
    'is_trade' => 0,
    'is_drop' => 0,
    'is_destruct' => 1,
    'crystal_type' => 'none',
    'consume_type' => 'consume_type_stackable',
  ],
  13653 => 
  [
    'item_id' => 13653,
    'icon' => 'scroll_of_verification_i00',
    'name' => 'Transformation Scroll: Rune Human Mercenary',
    'additionalname' => '',
    'description' => 'Allows you to transform into a Human mercenary. Can only be used by an ordinary mercenary in Rune Territory.',
    'is_trade' => 0,
    'is_drop' => 0,
    'is_destruct' => 1,
    'crystal_type' => 'none',
    'consume_type' => 'consume_type_stackable',
  ],
  13654 => 
  [
    'item_id' => 13654,
    'icon' => 'scroll_of_verification_i00',
    'name' => 'Transformation Scroll: Rune Elf Mercenary',
    'additionalname' => '',
    'description' => 'Allows you to transform into an Elven mercenary. Can only be used by an ordinary mercenary in Rune Territory.',
    'is_trade' => 0,
    'is_drop' => 0,
    'is_destruct' => 1,
    'crystal_type' => 'none',
    'consume_type' => 'consume_type_stackable',
  ],
  13655 => 
  [
    'item_id' => 13655,
    'icon' => 'scroll_of_verification_i00',
    'name' => 'Transformation Scroll: Rune Dark Elf Mercenary',
    'additionalname' => '',
    'description' => 'Allows you to transform into a Dark Elven mercenary. Can only be used by an ordinary mercenary in Rune Territory.',
    'is_trade' => 0,
    'is_drop' => 0,
    'is_destruct' => 1,
    'crystal_type' => 'none',
    'consume_type' => 'consume_type_stackable',
  ],
  13656 => 
  [
    'item_id' => 13656,
    'icon' => 'scroll_of_verification_i00',
    'name' => 'Transformation Scroll: Rune Orc Mercenary',
    'additionalname' => '',
    'description' => 'Allows you to transform into an Orc mercenary. Can only be used by an ordinary mercenary in Rune Territory.',
    'is_trade' => 0,
    'is_drop' => 0,
    'is_destruct' => 1,
    'crystal_type' => 'none',
    'consume_type' => 'consume_type_stackable',
  ],
  13657 => 
  [
    'item_id' => 13657,
    'icon' => 'scroll_of_verification_i00',
    'name' => 'Transformation Scroll: Rune Dwarf Mercenary',
    'additionalname' => '',
    'description' => 'Allows you to transform into a Dwarven mercenary. Can only be used by an ordinary mercenary in Rune Territory.',
    'is_trade' => 0,
    'is_drop' => 0,
    'is_destruct' => 1,
    'crystal_type' => 'none',
    'consume_type' => 'consume_type_stackable',
  ],
  13658 => 
  [
    'item_id' => 13658,
    'icon' => 'scroll_of_verification_i00',
    'name' => 'Transformation Scroll: Rune Kamael Mercenary',
    'additionalname' => '',
    'description' => 'Allows you to transform into a Kamael mercenary. Can only be used by an ordinary mercenary in Rune Territory.',
    'is_trade' => 0,
    'is_drop' => 0,
    'is_destruct' => 1,
    'crystal_type' => 'none',
    'consume_type' => 'consume_type_stackable',
  ],
  13659 => 
  [
    'item_id' => 13659,
    'icon' => 'scroll_of_verification_i00',
    'name' => 'Transformation Scroll: Rune Knight Mercenary',
    'additionalname' => '',
    'description' => 'Allows you to transform into a Knight mercenary. Can only be used by an elite mercenary in Rune Territory.',
    'is_trade' => 0,
    'is_drop' => 0,
    'is_destruct' => 1,
    'crystal_type' => 'none',
    'consume_type' => 'consume_type_stackable',
  ],
  13660 => 
  [
    'item_id' => 13660,
    'icon' => 'scroll_of_verification_i00',
    'name' => 'Transformation Scroll: Rune Archer Mercenary',
    'additionalname' => '',
    'description' => 'Allows you to transform into an Archer mercenary. Can only be used by an elite mercenary in Rune Territory.',
    'is_trade' => 0,
    'is_drop' => 0,
    'is_destruct' => 1,
    'crystal_type' => 'none',
    'consume_type' => 'consume_type_stackable',
  ],
  13661 => 
  [
    'item_id' => 13661,
    'icon' => 'scroll_of_verification_i00',
    'name' => 'Transformation Scroll: Rune Wizard Mercenary',
    'additionalname' => '',
    'description' => 'Allows you to transform into a Wizard mercenary. Can only be used by an elite mercenary in Rune Territory.',
    'is_trade' => 0,
    'is_drop' => 0,
    'is_destruct' => 1,
    'crystal_type' => 'none',
    'consume_type' => 'consume_type_stackable',
  ],
  13662 => 
  [
    'item_id' => 13662,
    'icon' => 'scroll_of_verification_i00',
    'name' => 'Transformation Scroll: Rune Centurion Mercenary',
    'additionalname' => '',
    'description' => 'Allows you to transform into a Centurion Mercenary. Can only be used by an elite mercenary in Rune Territory.',
    'is_trade' => 0,
    'is_drop' => 0,
    'is_destruct' => 1,
    'crystal_type' => 'none',
    'consume_type' => 'consume_type_stackable',
  ],
  13663 => 
  [
    'item_id' => 13663,
    'icon' => 'scroll_of_verification_i00',
    'name' => 'Transformation Scroll: Rune Knight Captain Mercenary',
    'additionalname' => '',
    'description' => 'Allows you to transform into a Knight Captain mercenary. Can only be used by an Exalted Mercenary in Rune Territory.',
    'is_trade' => 0,
    'is_drop' => 0,
    'is_destruct' => 1,
    'crystal_type' => 'none',
    'consume_type' => 'consume_type_stackable',
  ],
  13664 => 
  [
    'item_id' => 13664,
    'icon' => 'scroll_of_verification_i00',
    'name' => 'Transformation Scroll: Rune Commander Mercenary',
    'additionalname' => '',
    'description' => 'Allows you to transform into a Commander mercenary. Can only be used by an Exalted Mercenary in Rune Territory.',
    'is_trade' => 0,
    'is_drop' => 0,
    'is_destruct' => 1,
    'crystal_type' => 'none',
    'consume_type' => 'consume_type_stackable',
  ],
  13665 => 
  [
    'item_id' => 13665,
    'icon' => 'scroll_of_verification_i00',
    'name' => 'Transformation Scroll: Schuttgart Human Mercenary',
    'additionalname' => '',
    'description' => 'Allows you to transform into a Human mercenary. Can only be used by an ordinary mercenary in Schuttgart Territory.',
    'is_trade' => 0,
    'is_drop' => 0,
    'is_destruct' => 1,
    'crystal_type' => 'none',
    'consume_type' => 'consume_type_stackable',
  ],
  13666 => 
  [
    'item_id' => 13666,
    'icon' => 'scroll_of_verification_i00',
    'name' => 'Transformation Scroll: Schuttgart Elf Mercenary',
    'additionalname' => '',
    'description' => 'Allows you to transform into an Elven mercenary. Can only be used by an ordinary mercenary in Schuttgart Territory.',
    'is_trade' => 0,
    'is_drop' => 0,
    'is_destruct' => 1,
    'crystal_type' => 'none',
    'consume_type' => 'consume_type_stackable',
  ],
  13667 => 
  [
    'item_id' => 13667,
    'icon' => 'scroll_of_verification_i00',
    'name' => 'Transformation Scroll: Schuttgart Dark Elf Mercenary',
    'additionalname' => '',
    'description' => 'Allows you to transform into a Dark Elven mercenary. Can only be used by an ordinary mercenary in Schuttgart Territory.',
    'is_trade' => 0,
    'is_drop' => 0,
    'is_destruct' => 1,
    'crystal_type' => 'none',
    'consume_type' => 'consume_type_stackable',
  ],
  13668 => 
  [
    'item_id' => 13668,
    'icon' => 'scroll_of_verification_i00',
    'name' => 'Transformation Scroll: Schuttgart Orc Mercenary',
    'additionalname' => '',
    'description' => 'Allows you to transform into an Orc mercenary. Can only be used by an ordinary mercenary in Schuttgart Territory.',
    'is_trade' => 0,
    'is_drop' => 0,
    'is_destruct' => 1,
    'crystal_type' => 'none',
    'consume_type' => 'consume_type_stackable',
  ],
  13669 => 
  [
    'item_id' => 13669,
    'icon' => 'scroll_of_verification_i00',
    'name' => 'Transformation Scroll: Schuttgart Dwarf Mercenary',
    'additionalname' => '',
    'description' => 'Allows you to transform into a Dwarven mercenary. Can only be used by an ordinary mercenary in Schuttgart Territory.',
    'is_trade' => 0,
    'is_drop' => 0,
    'is_destruct' => 1,
    'crystal_type' => 'none',
    'consume_type' => 'consume_type_stackable',
  ],
  13670 => 
  [
    'item_id' => 13670,
    'icon' => 'scroll_of_verification_i00',
    'name' => 'Transformation Scroll: Schuttgart Kamael Mercenary',
    'additionalname' => '',
    'description' => 'Allows you to transform into a Kamael mercenary. Can only be used by an ordinary mercenary in Schuttgart Territory.',
    'is_trade' => 0,
    'is_drop' => 0,
    'is_destruct' => 1,
    'crystal_type' => 'none',
    'consume_type' => 'consume_type_stackable',
  ],
  13671 => 
  [
    'item_id' => 13671,
    'icon' => 'scroll_of_verification_i00',
    'name' => 'Transformation Scroll: Schuttgart Knight Mercenary',
    'additionalname' => '',
    'description' => 'Allows you to transform into a Knight mercenary. Can only be used by an elite mercenary in Schuttgart Territory.',
    'is_trade' => 0,
    'is_drop' => 0,
    'is_destruct' => 1,
    'crystal_type' => 'none',
    'consume_type' => 'consume_type_stackable',
  ],
  13672 => 
  [
    'item_id' => 13672,
    'icon' => 'scroll_of_verification_i00',
    'name' => 'Transformation Scroll: Schuttgart Archer Mercenary',
    'additionalname' => '',
    'description' => 'Allows you to transform into an Archer mercenary. Can only be used by an elite mercenary in Schuttgart Territory.',
    'is_trade' => 0,
    'is_drop' => 0,
    'is_destruct' => 1,
    'crystal_type' => 'none',
    'consume_type' => 'consume_type_stackable',
  ],
  13673 => 
  [
    'item_id' => 13673,
    'icon' => 'scroll_of_verification_i00',
    'name' => 'Transformation Scroll: Schuttgart Wizard Mercenary',
    'additionalname' => '',
    'description' => 'Allows you to transform into a Wizard mercenary. Can only be used by an elite mercenary in Schuttgart Territory.',
    'is_trade' => 0,
    'is_drop' => 0,
    'is_destruct' => 1,
    'crystal_type' => 'none',
    'consume_type' => 'consume_type_stackable',
  ],
  13674 => 
  [
    'item_id' => 13674,
    'icon' => 'scroll_of_verification_i00',
    'name' => 'Transformation Scroll: Schuttgart Centurion Mercenary',
    'additionalname' => '',
    'description' => 'Allows you to transform into a Centurion Mercenary. Can only be used by an elite mercenary in Schuttgart Territory.',
    'is_trade' => 0,
    'is_drop' => 0,
    'is_destruct' => 1,
    'crystal_type' => 'none',
    'consume_type' => 'consume_type_stackable',
  ],
  13675 => 
  [
    'item_id' => 13675,
    'icon' => 'scroll_of_verification_i00',
    'name' => 'Transformation Scroll: Schuttgart Knight Captain Mercenary',
    'additionalname' => '',
    'description' => 'Allows you to transform into a Knight Captain mercenary. Can only be used by an Exalted Mercenary in Schuttgart Territory.',
    'is_trade' => 0,
    'is_drop' => 0,
    'is_destruct' => 1,
    'crystal_type' => 'none',
    'consume_type' => 'consume_type_stackable',
  ],
  13676 => 
  [
    'item_id' => 13676,
    'icon' => 'scroll_of_verification_i00',
    'name' => 'Transformation Scroll: Schuttgart Commander Mercenary',
    'additionalname' => '',
    'description' => 'Allows you to transform into a Commander mercenary. Can only be used by an Exalted Mercenary in Schuttgart Territory.',
    'is_trade' => 0,
    'is_drop' => 0,
    'is_destruct' => 1,
    'crystal_type' => 'none',
    'consume_type' => 'consume_type_stackable',
  ],
  13677 => 
  [
    'item_id' => 13677,
    'icon' => 'scroll_of_verification_i00',
    'name' => 'Gludio Disguise Scroll',
    'additionalname' => '',
    'description' => 'Allows you to hide your name when participating in a battle in Gludio Territory.',
    'is_trade' => 0,
    'is_drop' => 0,
    'is_destruct' => 1,
    'crystal_type' => 'none',
    'consume_type' => 'consume_type_stackable',
  ],
  13678 => 
  [
    'item_id' => 13678,
    'icon' => 'scroll_of_verification_i00',
    'name' => 'Dion Disguise Scroll',
    'additionalname' => '',
    'description' => 'Allows you to hide your name when participating in a battle in Dion Territory.',
    'is_trade' => 0,
    'is_drop' => 0,
    'is_destruct' => 1,
    'crystal_type' => 'none',
    'consume_type' => 'consume_type_stackable',
  ],
  13679 => 
  [
    'item_id' => 13679,
    'icon' => 'scroll_of_verification_i00',
    'name' => 'Giran Disguise Scroll',
    'additionalname' => '',
    'description' => 'Allows you to hide your name when participating in a battle in Giran Territory.',
    'is_trade' => 0,
    'is_drop' => 0,
    'is_destruct' => 1,
    'crystal_type' => 'none',
    'consume_type' => 'consume_type_stackable',
  ],
  13680 => 
  [
    'item_id' => 13680,
    'icon' => 'scroll_of_verification_i00',
    'name' => 'Oren Disguise Scroll',
    'additionalname' => '',
    'description' => 'Allows you to hide your name when participating in a battle in Oren Territory.',
    'is_trade' => 0,
    'is_drop' => 0,
    'is_destruct' => 1,
    'crystal_type' => 'none',
    'consume_type' => 'consume_type_stackable',
  ],
  13681 => 
  [
    'item_id' => 13681,
    'icon' => 'scroll_of_verification_i00',
    'name' => 'Aden Disguise Scroll',
    'additionalname' => '',
    'description' => 'Allows you to hide your name when participating in a battle in Aden Territory.',
    'is_trade' => 0,
    'is_drop' => 0,
    'is_destruct' => 1,
    'crystal_type' => 'none',
    'consume_type' => 'consume_type_stackable',
  ],
  13682 => 
  [
    'item_id' => 13682,
    'icon' => 'scroll_of_verification_i00',
    'name' => 'Innadril Disguise Scroll',
    'additionalname' => '',
    'description' => 'Allows you to hide your name when participating in a battle in Innadril Territory.',
    'is_trade' => 0,
    'is_drop' => 0,
    'is_destruct' => 1,
    'crystal_type' => 'none',
    'consume_type' => 'consume_type_stackable',
  ],
  13683 => 
  [
    'item_id' => 13683,
    'icon' => 'scroll_of_verification_i00',
    'name' => 'Goddard Disguise Scroll',
    'additionalname' => '',
    'description' => 'Allows you to hide your name when participating in a battle in Goddard Territory.',
    'is_trade' => 0,
    'is_drop' => 0,
    'is_destruct' => 1,
    'crystal_type' => 'none',
    'consume_type' => 'consume_type_stackable',
  ],
  13684 => 
  [
    'item_id' => 13684,
    'icon' => 'scroll_of_verification_i00',
    'name' => 'Rune Disguise Scroll',
    'additionalname' => '',
    'description' => 'Allows you to hide your name when participating in a battle in Rune Territory.',
    'is_trade' => 0,
    'is_drop' => 0,
    'is_destruct' => 1,
    'crystal_type' => 'none',
    'consume_type' => 'consume_type_stackable',
  ],
  13685 => 
  [
    'item_id' => 13685,
    'icon' => 'scroll_of_verification_i00',
    'name' => 'Schuttgart Disguise Scroll',
    'additionalname' => '',
    'description' => 'Allows you to hide your name when participating in a battle in Schuttgart Territory.',
    'is_trade' => 0,
    'is_drop' => 0,
    'is_destruct' => 1,
    'crystal_type' => 'none',
    'consume_type' => 'consume_type_stackable',
  ],
  13686 => 
  [
    'item_id' => 13686,
    'icon' => 'sealed_vesper_cloack_i01',
    'name' => 'Sealed Knight\'s Cloak',
    'additionalname' => '',
    'description' => 'Cloak with luxurious embroidery. When the seal is cancelled, it\'ll have Dark Resistance + 30 effect. The seal can be cancelled through the weaver Olf Kanore and Olf Adams. It cannot be worn before the seal cancellation. Cannot be enchanted, augmented, or assigned an attribute. Cannot be transferred between servers.',
    'is_trade' => 0,
    'is_drop' => 0,
    'is_destruct' => 1,
    'crystal_type' => 's80',
    'consume_type' => 'consume_type_normal',
  ],
  13687 => 
  [
    'item_id' => 13687,
    'icon' => 'vesper_cloack_i00',
    'name' => 'Knight\'s Cloak',
    'additionalname' => '',
    'description' => 'Cloak with luxurious embroidery. Dark Resistance + 30. Can be worn by Barons or higher ranks of the clan that owns a castle. When an armor set above the Dynasty level is worn, the Sealed Cloak Slot will be open so that the cloak can be equipped. Cannot be enchanted, augmented, or assigned an attribute. Cannot be transferred between servers.',
    'is_trade' => 0,
    'is_drop' => 0,
    'is_destruct' => 1,
    'crystal_type' => 's80',
    'consume_type' => 'consume_type_normal',
  ],
  13688 => 
  [
    'item_id' => 13688,
    'icon' => 'vesper_cloack_i00',
    'name' => 'Knight\'s Cloak (Light Armor]',
    'additionalname' => '',
    'description' => 'Cloak with luxurious embroidery. Dark Resistance + 30, and  Can be worn by Barons or higher ranks of the clan that owns a castle. When the entire Vesper Noble or Dynasty set is worn, the Sealed Cloak Slot will be open and one can now wear the cloak. The cloak is exclusively for Bow Masters and Dagger Masters excluding Kamaels. Cannot be enchanted, augmented, or assigned an attribute. Cannot be transferred between servers.',
    'is_trade' => 0,
    'is_drop' => 0,
    'is_destruct' => 1,
    'crystal_type' => 's80',
    'consume_type' => 'consume_type_normal',
  ],
  13689 => 
  [
    'item_id' => 13689,
    'icon' => 'vesper_cloack_i00',
    'name' => 'Knight\'s Cloak (Robe]',
    'additionalname' => '',
    'description' => 'Cloak with luxurious embroidery. Dark Resistance + 30, and  Can be worn by Barons or higher ranks of the clan that owns a castle. When the entire Vesper Noble or Dynasty set is worn, the Sealed Cloak Slot will be open and one can now wear the cloak. The cloak is exclusively for Healer, Enchanter, Summoner and Wizard excluding Kamaels. Cannot be enchanted, augmented, or assigned an attribute. Cannot be transferred between servers.',
    'is_trade' => 0,
    'is_drop' => 0,
    'is_destruct' => 1,
    'crystal_type' => 's80',
    'consume_type' => 'consume_type_normal',
  ],
  13690 => 
  [
    'item_id' => 13690,
    'icon' => 'vesper_cloack_i00',
    'name' => 'Knight\'s Cloak (Kamael]',
    'additionalname' => '',
    'description' => 'Cloak with luxurious embroidery. Dark Resistance + 30, and  Can be worn by Barons or higher ranks of the clan that owns a castle. When the entire Vesper Noble or Dynasty set is worn, the Sealed Cloak Slot will be open and one can now wear the cloak. Kamael-exclusive cloak. Cannot be enchanted, augmented, or assigned an attribute. Cannot be transferred between servers.',
    'is_trade' => 0,
    'is_drop' => 0,
    'is_destruct' => 1,
    'crystal_type' => 's80',
    'consume_type' => 'consume_type_normal',
  ],
  13691 => 
  [
    'item_id' => 13691,
    'icon' => 'etc_badge_black_i00',
    'name' => 'Mark of Keucereus - Stage 1',
    'additionalname' => '',
    'description' => 'Mark given to an adventurer who successfully completes Keucereus\' order to break through to the Hall of Suffering. This mark is required for taking on higher level missions.',
    'is_trade' => 0,
    'is_drop' => 0,
    'is_destruct' => 1,
    'crystal_type' => 'none',
    'consume_type' => 'consume_type_stackable',
  ],
  13692 => 
  [
    'item_id' => 13692,
    'icon' => 'etc_badge_silver_i00',
    'name' => 'Mark of Keucereus - Stage 2',
    'additionalname' => '',
    'description' => 'Mark given to an adventurer who successfully completes Kucereus\' order to conquer the Hall of Erosion. Mark given to prove heroic achievements at the Seed of Infinity.',
    'is_trade' => 0,
    'is_drop' => 0,
    'is_destruct' => 1,
    'crystal_type' => 'none',
    'consume_type' => 'consume_type_stackable',
  ],
  13693 => 
  [
    'item_id' => 13693,
    'icon' => 'etc_coins_silver_i00',
    'name' => 'Gracian Anniversary Coins',
    'additionalname' => '',
    'description' => 'Gracian Anniversary Coins. When possessed, a reward can be acquired.',
    'is_trade' => 0,
    'is_drop' => 0,
    'is_destruct' => 0,
    'crystal_type' => 'none',
    'consume_type' => 'consume_type_stackable',
  ],
  13694 => 
  [
    'item_id' => 13694,
    'icon' => 'etc_key_i00',
    'name' => 'Gracia Key',
    'additionalname' => '',
    'description' => 'You can acquire Gracia Anniversary Coins by using a Gracian treasure chest. Cooldown is 10 min.',
    'is_trade' => 0,
    'is_drop' => 0,
    'is_destruct' => 0,
    'crystal_type' => 'none',
    'consume_type' => 'consume_type_stackable',
  ],
  13695 => 
  [
    'item_id' => 13695,
    'icon' => 'etc_box_of_adventure_1_i00',
    'name' => 'Gludio Supply Box - Magic Pin',
    'additionalname' => 'B-/C-grade',
    'description' => 'Box that has the symbol of Gludio. Low grade magic pin that\'s attached to the belt can be acquired at a certain rate.',
    'is_trade' => 0,
    'is_drop' => 0,
    'is_destruct' => 1,
    'crystal_type' => 'none',
    'consume_type' => 'consume_type_stackable',
  ],
  13696 => 
  [
    'item_id' => 13696,
    'icon' => 'etc_box_of_adventure_1_i00',
    'name' => 'Dion Supply Box - Magic Pin',
    'additionalname' => 'B-/C-grade',
    'description' => 'Box that has the symbol of Dion. Low grade magic pin that\'s attached to the belt can be acquired at a certain rate.',
    'is_trade' => 0,
    'is_drop' => 0,
    'is_destruct' => 1,
    'crystal_type' => 'none',
    'consume_type' => 'consume_type_stackable',
  ],
  13697 => 
  [
    'item_id' => 13697,
    'icon' => 'etc_box_of_adventure_1_i00',
    'name' => 'Giran Supply Box - Magic Pin',
    'additionalname' => 'B-/C-grade',
    'description' => 'Box that has the symbol of Giran. Low grade magic pin that\'s attached to the belt can be acquired at a certain rate.',
    'is_trade' => 0,
    'is_drop' => 0,
    'is_destruct' => 1,
    'crystal_type' => 'none',
    'consume_type' => 'consume_type_stackable',
  ],
  13698 => 
  [
    'item_id' => 13698,
    'icon' => 'etc_box_of_adventure_1_i00',
    'name' => 'Oren Supply Box - Magic Pin',
    'additionalname' => 'B-/C-grade',
    'description' => 'Box that has the symbol of Oren. Low grade magic pin that\'s attached to the belt can be acquired at a certain rate.',
    'is_trade' => 0,
    'is_drop' => 0,
    'is_destruct' => 1,
    'crystal_type' => 'none',
    'consume_type' => 'consume_type_stackable',
  ],
  13699 => 
  [
    'item_id' => 13699,
    'icon' => 'etc_box_of_adventure_1_i00',
    'name' => 'Aden Supply Box - Magic Pin',
    'additionalname' => 'B-/C-grade',
    'description' => 'Box that has the symbol of Aden. Low grade magic pin that\'s attached to the belt can be acquired at a certain rate.',
    'is_trade' => 0,
    'is_drop' => 0,
    'is_destruct' => 1,
    'crystal_type' => 'none',
    'consume_type' => 'consume_type_stackable',
  ],
];