<?php return [
  13800 => 
  [
    'item_id' => 13800,
    'icon' => 'etc_q_frog_green_i00',
    'name' => 'Transformation Scroll: Frog',
    'additionalname' => '',
    'description' => 'Frog transformation scroll that was given by Secret Agent Colin. Use the scroll to obtain the bead from the Frog King at Narsell Lake.',
    'is_trade' => 0,
    'is_drop' => 0,
    'is_destruct' => 1,
    'crystal_type' => 'none',
    'consume_type' => 'consume_type_stackable',
  ],
  13801 => 
  [
    'item_id' => 13801,
    'icon' => 'weapon_apprentices_rod_i00',
    'name' => 'Transformation Scroll: Young Child',
    'additionalname' => '',
    'description' => 'Frog transformation scroll that was given by Secret Agent Colin. Use the scroll to obtain candy from Grandma Tess at Narsell Lake.',
    'is_trade' => 0,
    'is_drop' => 0,
    'is_destruct' => 1,
    'crystal_type' => 'none',
    'consume_type' => 'consume_type_stackable',
  ],
  13802 => 
  [
    'item_id' => 13802,
    'icon' => 'armor_leather_helmet_i00',
    'name' => 'Native\'s Hood',
    'additionalname' => '',
    'description' => 'Equip this hood, obtained from Secret Agent Colin, to alter your appearance, speak with Native Kuta at Narsell Lake and obtain the Native\'s Gloves.',
    'is_trade' => 0,
    'is_drop' => 0,
    'is_destruct' => 0,
    'crystal_type' => 'none',
    'consume_type' => 'consume_type_normal',
  ],
  13803 => 
  [
    'item_id' => 13803,
    'icon' => 'armor_t34_u_i00',
    'name' => 'Native\'s Tunic',
    'additionalname' => '',
    'description' => 'Equip this tunic, obtained from Secret Agent Colin, to alter your appearance, speak with Native Kuta at Narsell Lake and obtain the Native\'s Gloves.',
    'is_trade' => 0,
    'is_drop' => 0,
    'is_destruct' => 0,
    'crystal_type' => 'none',
    'consume_type' => 'consume_type_normal',
  ],
  13804 => 
  [
    'item_id' => 13804,
    'icon' => 'armor_t34_l_i00',
    'name' => 'Native\'s Pants',
    'additionalname' => '',
    'description' => 'Equip these trousers, obtained from Secret Agent Colin, to alter your appearance, speak with Native Kuta at Narsell Lake and obtain the Native\'s Gloves.',
    'is_trade' => 0,
    'is_drop' => 0,
    'is_destruct' => 0,
    'crystal_type' => 'none',
    'consume_type' => 'consume_type_normal',
  ],
  13805 => 
  [
    'item_id' => 13805,
    'icon' => 'armor_leather_helmet_i02',
    'name' => 'Guards of the Dawn Helmet',
    'additionalname' => '',
    'description' => 'Obtained from Secret Agent Colin, it allows you use the Guards\' Transformation skill when equipped with the Guards of Dawn Tunic and Pants.',
    'is_trade' => 0,
    'is_drop' => 0,
    'is_destruct' => 0,
    'crystal_type' => 'none',
    'consume_type' => 'consume_type_normal',
  ],
  13806 => 
  [
    'item_id' => 13806,
    'icon' => 'armor_t08_u_i00',
    'name' => 'Guards of the Dawn Tunic',
    'additionalname' => '',
    'description' => 'Obtained from Secret Agent Colin, it allows you use the Guards\' Transformation skill when equipped with the Guards of Dawn Helmet and Pants.',
    'is_trade' => 0,
    'is_drop' => 0,
    'is_destruct' => 0,
    'crystal_type' => 'none',
    'consume_type' => 'consume_type_normal',
  ],
  13807 => 
  [
    'item_id' => 13807,
    'icon' => 'armor_t08_l_i00',
    'name' => 'Guards of the Dawn Pants',
    'additionalname' => '',
    'description' => 'Obtained from Secret Agent Colin, it allows you use the Guards\' Transformation skill when equipped with the Guards of Dawn Tunic and Helmet.',
    'is_trade' => 0,
    'is_drop' => 0,
    'is_destruct' => 0,
    'crystal_type' => 'none',
    'consume_type' => 'consume_type_normal',
  ],
  13808 => 
  [
    'item_id' => 13808,
    'icon' => 'etc_holy_water_i00',
    'name' => 'Elmoreden\'s Holy Water',
    'additionalname' => '',
    'description' => 'Used by Elmoreden Emperor Shunaiman\'s guards, it can open the door engulfed in the Flame of Lilim inside the Necropolis.',
    'is_trade' => 0,
    'is_drop' => 0,
    'is_destruct' => 1,
    'crystal_type' => 'none',
    'consume_type' => 'consume_type_stackable',
  ],
  13809 => 
  [
    'item_id' => 13809,
    'icon' => 'weapon_apprentices_rod_i00',
    'name' => 'Court Wizard\'s Magic Staff',
    'additionalname' => '',
    'description' => 'This magic staff can open the door to the Disciple\'s Necropolis using its powerful removal skill.',
    'is_trade' => 0,
    'is_drop' => 0,
    'is_destruct' => 1,
    'crystal_type' => 'none',
    'consume_type' => 'consume_type_stackable',
  ],
  13810 => 
  [
    'item_id' => 13810,
    'icon' => 'etc_letter_envelope_i00',
    'name' => 'High Priest Orven\'s Letter',
    'additionalname' => '',
    'description' => 'Letter detailing Gracia\'s imminent crisis. Deliver it to Commander Keucereus in the Gracia region.',
    'is_trade' => 0,
    'is_drop' => 0,
    'is_destruct' => 1,
    'crystal_type' => 'none',
    'consume_type' => 'consume_type_normal',
  ],
  13811 => 
  [
    'item_id' => 13811,
    'icon' => 'etc_letter_white_i00',
    'name' => 'Keucereus\' Introduction - Seed of Infinity',
    'additionalname' => '',
    'description' => 'Introduction received from Keucereus. If you go northwest from Keucereus Alliance Base, you can reach the Seed of Infinity. Deliver this mark to Officer Tepios there.',
    'is_trade' => 0,
    'is_drop' => 0,
    'is_destruct' => 1,
    'crystal_type' => 'none',
    'consume_type' => 'consume_type_normal',
  ],
  13812 => 
  [
    'item_id' => 13812,
    'icon' => 'etc_letter_white_i00',
    'name' => 'Keucereus\' Introduction - Seed of Destruction',
    'additionalname' => '',
    'description' => 'Introduction received from Keucereus. Deliver it to Sergeant Allenos, located at the Seed of Destruction west of Keucereus Alliance Base.',
    'is_trade' => 0,
    'is_drop' => 0,
    'is_destruct' => 1,
    'crystal_type' => 'none',
    'consume_type' => 'consume_type_normal',
  ],
  13813 => 
  [
    'item_id' => 13813,
    'icon' => 'etc_letter_red_i00',
    'name' => 'Croop\'s Introduction',
    'additionalname' => '',
    'description' => 'Introduction received from Croop. Deliver it to Guard Hector at the north entrance to Oren Castle and learn about the whereabouts of Contractor Jacob.',
    'is_trade' => 0,
    'is_drop' => 0,
    'is_destruct' => 1,
    'crystal_type' => 'none',
    'consume_type' => 'consume_type_normal',
  ],
  13814 => 
  [
    'item_id' => 13814,
    'icon' => 'accessary_necklace_of_protection_i00',
    'name' => 'Jacob\'s Necklace',
    'additionalname' => '',
    'description' => 'Necklace discovered at contractor Jacob\'s body.',
    'is_trade' => 0,
    'is_drop' => 0,
    'is_destruct' => 1,
    'crystal_type' => 'none',
    'consume_type' => 'consume_type_normal',
  ],
  13815 => 
  [
    'item_id' => 13815,
    'icon' => 'etc_scroll_white_i00',
    'name' => 'Croop\'s Letter Requesting a Memorial Service',
    'additionalname' => '',
    'description' => 'Deliver Croop\'s letter requesting a memorial service for Contractor Jacob to High Priest Hollint in Einhasad\'s Temple inside Oren Castle.',
    'is_trade' => 0,
    'is_drop' => 0,
    'is_destruct' => 1,
    'crystal_type' => 'none',
    'consume_type' => 'consume_type_normal',
  ],
  13816 => 
  [
    'item_id' => 13816,
    'icon' => 'etc_herb_blue_i00',
    'name' => 'Deadman\'s Herb',
    'additionalname' => '',
    'description' => 'Deliver this herb, collected in Enchanted Valley, to Priest Cain near the Town of Oren.',
    'is_trade' => 0,
    'is_drop' => 0,
    'is_destruct' => 1,
    'crystal_type' => 'none',
    'consume_type' => 'consume_type_normal',
  ],
  13817 => 
  [
    'item_id' => 13817,
    'icon' => 'etc_paper_black_i00',
    'name' => 'Priest Cain\'s Investigation Report',
    'additionalname' => '',
    'description' => 'Deliver Priest Cain\'s report about the Seven Signs to Sir Gustav Athebaldt in the Town of Oren.',
    'is_trade' => 0,
    'is_drop' => 0,
    'is_destruct' => 1,
    'crystal_type' => 'none',
    'consume_type' => 'consume_type_normal',
  ],
  13818 => 
  [
    'item_id' => 13818,
    'icon' => 'etc_letter_white_i00',
    'name' => 'Athebaldt\'s Introduction',
    'additionalname' => '',
    'description' => 'Introduction received from Sir Athebaldt. Bring it to Secret Agent Colin in the Southern entrance of the town of Aden.',
    'is_trade' => 0,
    'is_drop' => 0,
    'is_destruct' => 1,
    'crystal_type' => 'none',
    'consume_type' => 'consume_type_normal',
  ],
  13819 => 
  [
    'item_id' => 13819,
    'icon' => 'armor_short_leather_gloves_i00',
    'name' => 'Native\'s Gloves',
    'additionalname' => '',
    'description' => 'Gloves received from the Native Kuta. Bring it to the Secret Agent Colin of the town of Aden.',
    'is_trade' => 0,
    'is_drop' => 0,
    'is_destruct' => 1,
    'crystal_type' => 'none',
    'consume_type' => 'consume_type_normal',
  ],
  13820 => 
  [
    'item_id' => 13820,
    'icon' => 'etc_crystal_ball_blue_i00',
    'name' => 'Frog King\'s Bead',
    'additionalname' => '',
    'description' => 'Bead obtained from the Frog King. Bring it to the Secret Agent Colin of the town of Aden.',
    'is_trade' => 0,
    'is_drop' => 0,
    'is_destruct' => 1,
    'crystal_type' => 'none',
    'consume_type' => 'consume_type_normal',
  ],
  13821 => 
  [
    'item_id' => 13821,
    'icon' => 'etc_pouch_brown_i00',
    'name' => 'Grandma Tess\' Candy Pouch',
    'additionalname' => '',
    'description' => 'Candy pouch obtained from Grandma Tess. Bring it to the Secret Agent Colin of the town of Aden.',
    'is_trade' => 0,
    'is_drop' => 0,
    'is_destruct' => 1,
    'crystal_type' => 'none',
    'consume_type' => 'consume_type_normal',
  ],
  13822 => 
  [
    'item_id' => 13822,
    'icon' => 'etc_royal_membership_i00',
    'name' => 'Guards of the Dawn Identity Card',
    'additionalname' => '',
    'description' => 'Identity card of the guards of the Dawn that was given by Lady Claudia. The qualification one needs to enter the Dawn Lord\'s temple.',
    'is_trade' => 0,
    'is_drop' => 0,
    'is_destruct' => 1,
    'crystal_type' => 'none',
    'consume_type' => 'consume_type_normal',
  ],
  13823 => 
  [
    'item_id' => 13823,
    'icon' => 'etc_crest_red_i00',
    'name' => 'Emperor Shunaiman\'s Contract',
    'additionalname' => '',
    'description' => 'Details a secret contract between Emperor Shunaiman and the Merchant of Mammon regarding the Seven Signs. Deliver it to High Priest Rayment in the Town of Gludio.',
    'is_trade' => 0,
    'is_drop' => 0,
    'is_destruct' => 1,
    'crystal_type' => 'none',
    'consume_type' => 'consume_type_normal',
  ],
  13824 => 
  [
    'item_id' => 13824,
    'icon' => 'etc_water_rune_i00',
    'name' => 'Ancient Seal Stone of Mammon',
    'additionalname' => '',
    'description' => 'This apparently sealed a promise the Merchant of Mammon made to the Elmoreden Emperor Shunaiman. It seems to be hiding a mysterious power.',
    'is_trade' => 0,
    'is_drop' => 0,
    'is_destruct' => 1,
    'crystal_type' => 'none',
    'consume_type' => 'consume_type_normal',
  ],
  13825 => 
  [
    'item_id' => 13825,
    'icon' => 'etc_holy_grail_i00',
    'name' => 'Einhasad\'s Grail',
    'additionalname' => '',
    'description' => 'Proof that all Necropolis and Catacombs have been sealed. Deliver it to Emperor Shunaiman (Elmoreden Era].',
    'is_trade' => 0,
    'is_drop' => 0,
    'is_destruct' => 1,
    'crystal_type' => 'none',
    'consume_type' => 'consume_type_normal',
  ],
  13826 => 
  [
    'item_id' => 13826,
    'icon' => 'etc_lesser_potion_red_i00',
    'name' => 'Blood of the Emperor',
    'additionalname' => '',
    'description' => 'Vial of Emperor Shunaiman\'s blood, which is the key to activate the Necropolis sealing device. Activate the device!',
    'is_trade' => 0,
    'is_drop' => 0,
    'is_destruct' => 1,
    'crystal_type' => 'none',
    'consume_type' => 'consume_type_normal',
  ],
  13827 => 
  [
    'item_id' => 13827,
    'icon' => 'etc_letter_white_i00',
    'name' => 'Iason\'s Introduction',
    'additionalname' => '',
    'description' => 'This allows you meet Franz. Deliver it to High Priest Orven in the Town of Aden.',
    'is_trade' => 0,
    'is_drop' => 0,
    'is_destruct' => 1,
    'crystal_type' => 'none',
    'consume_type' => 'consume_type_normal',
  ],
  13828 => 
  [
    'item_id' => 13828,
    'icon' => 'etc_spell_books_element_i00',
    'name' => 'Prayer: Emperor\'s Key',
    'additionalname' => '',
    'description' => 'This prayer Has been passed down from one high-ranking Priest of the Dawn to the next, stretching back to the Elmoreden Era.',
    'is_trade' => 0,
    'is_drop' => 0,
    'is_destruct' => 1,
    'crystal_type' => 'none',
    'consume_type' => 'consume_type_normal',
  ],
  13829 => 
  [
    'item_id' => 13829,
    'icon' => 'weapon_apprentices_spellbook_i01',
    'name' => 'Mysterious Hand-written Text',
    'additionalname' => '',
    'description' => 'This obscure text is hand-written in ancient ciphers.',
    'is_trade' => 0,
    'is_drop' => 0,
    'is_destruct' => 1,
    'crystal_type' => 'none',
    'consume_type' => 'consume_type_normal',
  ],
  13830 => 
  [
    'item_id' => 13830,
    'icon' => 'etc_bodypart_liver_i00',
    'name' => 'Tomlan Kamos\' Cellular Tissue',
    'additionalname' => '',
    'description' => 'Deliver this tissue sample to Magister Rohmer in the Temple of Einhasad in the Town of Gludio.',
    'is_trade' => 0,
    'is_drop' => 0,
    'is_destruct' => 1,
    'crystal_type' => 'none',
    'consume_type' => 'consume_type_stackable',
  ],
  13831 => 
  [
    'item_id' => 13831,
    'icon' => 'etc_bodypart_liver_i00',
    'name' => 'Ol Ariosh\'s Cellular Tissue',
    'additionalname' => '',
    'description' => 'Deliver this tissue sample to Magister Rohmer in the Temple of Einhasad in the Town of Gludio.',
    'is_trade' => 0,
    'is_drop' => 0,
    'is_destruct' => 1,
    'crystal_type' => 'none',
    'consume_type' => 'consume_type_stackable',
  ],
  13832 => 
  [
    'item_id' => 13832,
    'icon' => 'etc_bodypart_liver_i00',
    'name' => 'Crimson Hatu Otis\' Cellular Tissue',
    'additionalname' => '',
    'description' => 'Deliver this tissue sample to Magister Mirien in the Temple of Einhasad in the Town of Dion.',
    'is_trade' => 0,
    'is_drop' => 0,
    'is_destruct' => 1,
    'crystal_type' => 'none',
    'consume_type' => 'consume_type_stackable',
  ],
  13833 => 
  [
    'item_id' => 13833,
    'icon' => 'etc_bodypart_liver_i00',
    'name' => 'Seer Flouros\' Cellular Tissue',
    'additionalname' => '',
    'description' => 'Deliver this tissue sample to Magister Mirien in the Temple of Einhasad in the Town of Dion.',
    'is_trade' => 0,
    'is_drop' => 0,
    'is_destruct' => 1,
    'crystal_type' => 'none',
    'consume_type' => 'consume_type_stackable',
  ],
  13834 => 
  [
    'item_id' => 13834,
    'icon' => 'etc_bodypart_liver_i00',
    'name' => 'Blade Otis\' Cellular Tissue',
    'additionalname' => '',
    'description' => 'Deliver this tissue sample to Magister Minevia in the Temple of Einhasad in the Town of Heine.',
    'is_trade' => 0,
    'is_drop' => 0,
    'is_destruct' => 1,
    'crystal_type' => 'none',
    'consume_type' => 'consume_type_stackable',
  ],
  13835 => 
  [
    'item_id' => 13835,
    'icon' => 'etc_bodypart_liver_i00',
    'name' => 'Weird Bunei\'s Cellular Tissue',
    'additionalname' => '',
    'description' => 'Deliver this tissue sample to Magister Minevia in the Temple of Einhasad in the Town of Heine.',
    'is_trade' => 0,
    'is_drop' => 0,
    'is_destruct' => 1,
    'crystal_type' => 'none',
    'consume_type' => 'consume_type_stackable',
  ],
  13836 => 
  [
    'item_id' => 13836,
    'icon' => 'etc_bodypart_liver_i00',
    'name' => 'Kaim Abigore\'s Cellular Tissue',
    'additionalname' => '',
    'description' => 'Deliver this tissue sample to Magister Rovia in the Temple of Einhasad in the Town of Oren.',
    'is_trade' => 0,
    'is_drop' => 0,
    'is_destruct' => 1,
    'crystal_type' => 'none',
    'consume_type' => 'consume_type_stackable',
  ],
  13837 => 
  [
    'item_id' => 13837,
    'icon' => 'etc_bodypart_liver_i00',
    'name' => 'Knight Montagnar\'s Cellular Tissue',
    'additionalname' => '',
    'description' => 'Deliver this tissue sample to Magister Rovia in the Temple of Einhasad in the Town of Oren.',
    'is_trade' => 0,
    'is_drop' => 0,
    'is_destruct' => 1,
    'crystal_type' => 'none',
    'consume_type' => 'consume_type_stackable',
  ],
  13838 => 
  [
    'item_id' => 13838,
    'icon' => 'etc_bodypart_liver_i00',
    'name' => 'Venomous Storace\'s Cellular Tissue',
    'additionalname' => '',
    'description' => 'Deliver this tissue sample to Magister Atraxia in the Temple of Einhasad in the Town of Schuttgart.',
    'is_trade' => 0,
    'is_drop' => 0,
    'is_destruct' => 1,
    'crystal_type' => 'none',
    'consume_type' => 'consume_type_stackable',
  ],
  13839 => 
  [
    'item_id' => 13839,
    'icon' => 'etc_bodypart_liver_i00',
    'name' => 'Kel Bilette\'s Cellular Tissue',
    'additionalname' => '',
    'description' => 'Deliver this tissue sample to Magister Atraxia in the Temple of Einhasad in the Town of Schuttgart.',
    'is_trade' => 0,
    'is_drop' => 0,
    'is_destruct' => 1,
    'crystal_type' => 'none',
    'consume_type' => 'consume_type_stackable',
  ],
  13840 => 
  [
    'item_id' => 13840,
    'icon' => 'etc_bodypart_liver_i00',
    'name' => 'White Allosce\'s Cellular Tissue',
    'additionalname' => '',
    'description' => 'Deliver this tissue sample to Magister Kayan in the Temple of Einhasad in the Town of Rune.',
    'is_trade' => 0,
    'is_drop' => 0,
    'is_destruct' => 1,
    'crystal_type' => 'none',
    'consume_type' => 'consume_type_stackable',
  ],
  13841 => 
  [
    'item_id' => 13841,
    'icon' => 'etc_feather_gold_i00',
    'name' => 'Dragonkin Charm',
    'additionalname' => '',
    'description' => 'Energy from the Dragonkin that infest the Seed of Destruction. Can be used at Special Product Broker Kirklan.',
    'is_trade' => 0,
    'is_drop' => 0,
    'is_destruct' => 1,
    'crystal_type' => 'none',
    'consume_type' => 'consume_type_stackable',
  ],
  13842 => 
  [
    'item_id' => 13842,
    'icon' => 'weapon_monster_i00',
    'name' => 'Tiat Two-handed Weapon',
    'additionalname' => '',
    'description' => 'Tiat\'s two-handed weapon.',
    'is_trade' => 1,
    'is_drop' => 1,
    'is_destruct' => 1,
    'crystal_type' => 'd',
    'consume_type' => 'consume_type_normal',
  ],
  13843 => 
  [
    'item_id' => 13843,
    'icon' => 'weapon_doomed_dagger_i00',
    'name' => 'Draconic Peltast Weapon',
    'additionalname' => '',
    'description' => 'Peltast\'s weapon.',
    'is_trade' => 0,
    'is_drop' => 0,
    'is_destruct' => 0,
    'crystal_type' => 'd',
    'consume_type' => 'consume_type_normal',
  ],
  13844 => 
  [
    'item_id' => 13844,
    'icon' => 'scroll_of_verification_i06',
    'name' => 'Scroll: Extract Star Stone',
    'additionalname' => '',
    'description' => 'SuppleMental scroll created for adventurers who are inexperienced in collecting Star Stones.',
    'is_trade' => 0,
    'is_drop' => 0,
    'is_destruct' => 1,
    'crystal_type' => 'none',
    'consume_type' => 'consume_type_stackable',
  ],
  13845 => 
  [
    'item_id' => 13845,
    'icon' => 'weapon_long_sword_i00',
    'name' => 'Attribute Master Yin\'s Sword',
    'additionalname' => '10-minute',
    'description' => 'Weapon provided by Attribute Master Yin for capturing the Reckless Water Spirits. You can feel the powerful energy of fire. The spirit\'s power contained in this weapon will be useful when capturing the reckless spirit. 10-minute-limited-time Item. 10-minute item. Fire power + 10.',
    'is_trade' => 0,
    'is_drop' => 0,
    'is_destruct' => 0,
    'crystal_type' => 'a',
    'consume_type' => 'consume_type_normal',
  ],
  13846 => 
  [
    'item_id' => 13846,
    'icon' => 'etc_royal_seal_of_lord_i04',
    'name' => 'Seal of Binding',
    'additionalname' => '',
    'description' => 'Obtained after activating the sealing device, it proves that the sealing device was properly sealed. Deliver it to Emperor Shunaiman.',
    'is_trade' => 0,
    'is_drop' => 0,
    'is_destruct' => 1,
    'crystal_type' => 'none',
    'consume_type' => 'consume_type_stackable',
  ],
  13847 => 
  [
    'item_id' => 13847,
    'icon' => 'etc_statue_of_einhasad_bronze_i00',
    'name' => 'Mysterious Fragment',
    'additionalname' => '',
    'description' => 'This Mysterious Fragment seems to possess a wicked power.',
    'is_trade' => 0,
    'is_drop' => 0,
    'is_destruct' => 1,
    'crystal_type' => 'none',
    'consume_type' => 'consume_type_stackable',
  ],
  13848 => 
  [
    'item_id' => 13848,
    'icon' => 'armor_t62_u_i00',
    'name' => 'Headless Knight\'s Armor',
    'additionalname' => '',
    'description' => 'Obtain this ionized set of armor after defeating the Headless Knight who terrorized the natives.',
    'is_trade' => 0,
    'is_drop' => 0,
    'is_destruct' => 1,
    'crystal_type' => 'none',
    'consume_type' => 'consume_type_stackable',
  ],
  13849 => 
  [
    'item_id' => 13849,
    'icon' => 'etc_ginseng_red_i00',
    'name' => 'Mandragora Root',
    'additionalname' => '',
    'description' => 'The signature product of the Town of Dion.',
    'is_trade' => 1,
    'is_drop' => 0,
    'is_destruct' => 1,
    'crystal_type' => 'none',
    'consume_type' => 'consume_type_stackable',
  ],
  13850 => 
  [
    'item_id' => 13850,
    'icon' => 'etc_badge_black_i00',
    'name' => 'Bloody Axe Black Epaulette',
    'additionalname' => '',
    'description' => 'Epaulette once worn by the Bloody Axe Aide.',
    'is_trade' => 0,
    'is_drop' => 0,
    'is_destruct' => 1,
    'crystal_type' => 'none',
    'consume_type' => 'consume_type_stackable',
  ],
  13851 => 
  [
    'item_id' => 13851,
    'icon' => 'etc_crystal_ball_red_i00',
    'name' => 'Nebulite Orb',
    'additionalname' => '',
    'description' => 'Nebulite Orb requested by the Ivory Tower.',
    'is_trade' => 0,
    'is_drop' => 0,
    'is_destruct' => 1,
    'crystal_type' => 'none',
    'consume_type' => 'consume_type_stackable',
  ],
  13852 => 
  [
    'item_id' => 13852,
    'icon' => 'etc_roll_of_paper_black_i00',
    'name' => 'Inspector Medibal\'s Document',
    'additionalname' => '',
    'description' => 'Contains an account of Inspector Medibal\'s investigation of the Seed of Destruction. Deliver it to the wounded Guard Ell at Keucereus Alliance Base.',
    'is_trade' => 0,
    'is_drop' => 0,
    'is_destruct' => 1,
    'crystal_type' => 'none',
    'consume_type' => 'consume_type_stackable',
  ],
  13853 => 
  [
    'item_id' => 13853,
    'icon' => 'etc_powder_black_i00',
    'name' => 'Shards of Broken Darkness',
    'additionalname' => '',
    'description' => 'The Shards of Broken Darkness, which bore out of the life forms of evil when they were destroyed. Collect them and take them to War Mage Artius at Keucereus Alliance Base.',
    'is_trade' => 0,
    'is_drop' => 0,
    'is_destruct' => 1,
    'crystal_type' => 'none',
    'consume_type' => 'consume_type_stackable',
  ],
  13854 => 
  [
    'item_id' => 13854,
    'icon' => 'etc_powder_white_i00',
    'name' => 'Shards of Broken Light',
    'additionalname' => '',
    'description' => 'Obtained by purging the Shards of Broken Darkness, deliver it to War Mage Artius.',
    'is_trade' => 0,
    'is_drop' => 0,
    'is_destruct' => 1,
    'crystal_type' => 'none',
    'consume_type' => 'consume_type_stackable',
  ],
  13855 => 
  [
    'item_id' => 13855,
    'icon' => 'etc_piece_holy_light',
    'name' => 'Sacred Light Fragment',
    'additionalname' => '',
    'description' => 'Fragment piece that looks like it will break at any moment. Sacred light flows out from it. If you are prepared for it to break, the sacred power of this fragment piece may allow you to inflict damage on Witch Tiat of the Dragon of Darkness.',
    'is_trade' => 0,
    'is_drop' => 0,
    'is_destruct' => 1,
    'crystal_type' => 'none',
    'consume_type' => 'consume_type_stackable',
  ],
  13856 => 
  [
    'item_id' => 13856,
    'icon' => 'etc_evil_necklace_i00',
    'name' => 'Rider\'s Badge',
    'additionalname' => '',
    'description' => 'Obtained from Vulture Rider\'s and Elite Rider\'s. Deliver them to Dwarf Engineer Lekon at Keucereus Alliance Base as proof of your skill in flying.',
    'is_trade' => 0,
    'is_drop' => 0,
    'is_destruct' => 1,
    'crystal_type' => 'none',
    'consume_type' => 'consume_type_stackable',
  ],
  13857 => 
  [
    'item_id' => 13857,
    'icon' => 'etc_letter_blue_i00',
    'name' => 'Lekon\'s Certificate',
    'additionalname' => '',
    'description' => 'Issued by Dwarven Engineer Lekon. This certificate proves you have the ability to fly safely in Gracian airs.',
    'is_trade' => 0,
    'is_drop' => 0,
    'is_destruct' => 1,
    'crystal_type' => 'none',
    'consume_type' => 'consume_type_stackable',
  ],
  13858 => 
  [
    'item_id' => 13858,
    'icon' => 'low_star_stone_piece_i00',
    'name' => 'Extracted Coarse Red Star Stone',
    'additionalname' => '',
    'description' => 'Coarse, Red Star Stone fragment. Higher quality Red Star Stone fragments can be extracted when you have more practice.',
    'is_trade' => 0,
    'is_drop' => 0,
    'is_destruct' => 1,
    'crystal_type' => 'none',
    'consume_type' => 'consume_type_stackable',
  ],
  13859 => 
  [
    'item_id' => 13859,
    'icon' => 'low_star_stone_piece_i01',
    'name' => 'Extracted Coarse Blue Star Stone',
    'additionalname' => '',
    'description' => 'Coarse, Blue Star Stone fragment. Higher quality Blue Star Stone fragments can be extracted when you have more practice.',
    'is_trade' => 0,
    'is_drop' => 0,
    'is_destruct' => 1,
    'crystal_type' => 'none',
    'consume_type' => 'consume_type_stackable',
  ],
  13860 => 
  [
    'item_id' => 13860,
    'icon' => 'low_star_stone_piece_i02',
    'name' => 'Extracted Coarse Green Star Stone',
    'additionalname' => '',
    'description' => 'Coarse, Green Star Stone fragment. Higher quality Green Star Stone fragments can be extracted when you have more practice.',
    'is_trade' => 0,
    'is_drop' => 0,
    'is_destruct' => 1,
    'crystal_type' => 'none',
    'consume_type' => 'consume_type_stackable',
  ],
  13861 => 
  [
    'item_id' => 13861,
    'icon' => 'etc_bead_blue_i00',
    'name' => 'Reckless Soul Piece - Water',
    'additionalname' => '',
    'description' => 'Materializes after the reckless Water Spirit is destroyed. Take it to the Male Attribute Master.',
    'is_trade' => 0,
    'is_drop' => 0,
    'is_destruct' => 1,
    'crystal_type' => 'none',
    'consume_type' => 'consume_type_stackable',
  ],
  13862 => 
  [
    'item_id' => 13862,
    'icon' => 'etc_bead_silver_i00',
    'name' => 'Reckless Soul Piece - Air',
    'additionalname' => '',
    'description' => 'Materializes after the reckless Wind Spirit is destroyed. Take it to Attribute Master Yang.',
    'is_trade' => 0,
    'is_drop' => 0,
    'is_destruct' => 1,
    'crystal_type' => 'none',
    'consume_type' => 'consume_type_stackable',
  ],
  13863 => 
  [
    'item_id' => 13863,
    'icon' => 'etc_debris_i00',
    'name' => 'Freed Soul Fragment',
    'additionalname' => '',
    'description' => 'Obtained through hunting in the Seed of Infinity. If you take them to Special Product Broker Kirklan you can exchange 5 of these items for a Freed Soul.',
    'is_trade' => 0,
    'is_drop' => 0,
    'is_destruct' => 1,
    'crystal_type' => 'none',
    'consume_type' => 'consume_type_stackable',
  ],
  13864 => 
  [
    'item_id' => 13864,
    'icon' => 'tiat_seal_i00',
    'name' => 'Seal of Tiat',
    'additionalname' => '',
    'description' => 'Obtained after defeating Tiat, it represents Tiat\'s authority and power. Take it to Special Product Broker Kirklan at Keucereus Alliance Base to exchange it for a special item.',
    'is_trade' => 0,
    'is_drop' => 0,
    'is_destruct' => 1,
    'crystal_type' => 'none',
    'consume_type' => 'consume_type_stackable',
  ],
  13865 => 
  [
    'item_id' => 13865,
    'icon' => 'etc_totem_black_i00',
    'name' => 'Dragonkin Charm Fragment',
    'additionalname' => '',
    'description' => 'Obtained through hunting in the Seed of Destruction. If you take them to Special Product Broker Kirklan, you can exchange 5 of these items for a Dragonkin Charm.',
    'is_trade' => 0,
    'is_drop' => 0,
    'is_destruct' => 1,
    'crystal_type' => 'none',
    'consume_type' => 'consume_type_stackable',
  ],
  13866 => 
  [
    'item_id' => 13866,
    'icon' => 'soul_facet_i00',
    'name' => 'Restless Soul',
    'additionalname' => '',
    'description' => 'Obtained in the Seed of Infinity. Take these Restless Souls to Special Product Broker Kirklan to exchange them for a reward.',
    'is_trade' => 0,
    'is_drop' => 0,
    'is_destruct' => 1,
    'crystal_type' => 'none',
    'consume_type' => 'consume_type_stackable',
  ],
  13867 => 
  [
    'item_id' => 13867,
    'icon' => 'tiat_breath_i00',
    'name' => 'Tiat\'s Breath',
    'additionalname' => '',
    'description' => 'Tiat Charm fragment that can be harvested by collecting in the Seed of Destruction region. If you bring it to the Special Product Broker Kutran at the Kucereus clan outpost, you can exchange it for a useful item.',
    'is_trade' => 0,
    'is_drop' => 0,
    'is_destruct' => 1,
    'crystal_type' => 'none',
    'consume_type' => 'consume_type_stackable',
  ],
  13868 => 
  [
    'item_id' => 13868,
    'icon' => 'etc_badge_black_i00',
    'name' => 'Yehan Klodekus\' Badge',
    'additionalname' => '',
    'description' => 'Badge of Yehan Klodekus, who degenerated into a Death Knight through M. Atk. of the Seed of Infinity.',
    'is_trade' => 0,
    'is_drop' => 0,
    'is_destruct' => 1,
    'crystal_type' => 'none',
    'consume_type' => 'consume_type_stackable',
  ],
  13869 => 
  [
    'item_id' => 13869,
    'icon' => 'etc_badge_silver_i00',
    'name' => 'Yehan Klanikus\' Badge',
    'additionalname' => '',
    'description' => 'Badge of Yehan Klanikus, who degenerated into a Death Knight through M. Atk. of the Seed of Infinity.',
    'is_trade' => 0,
    'is_drop' => 0,
    'is_destruct' => 1,
    'crystal_type' => 'none',
    'consume_type' => 'consume_type_stackable',
  ],
  13870 => 
  [
    'item_id' => 13870,
    'icon' => 'etc_crystal_ball_green_i00',
    'name' => 'Lich Crystal',
    'additionalname' => '',
    'description' => 'Crystal left behind after the death of Kohemenus, who degenerated into a Lich through M. Atk. of the Seed of Infinity.',
    'is_trade' => 0,
    'is_drop' => 0,
    'is_destruct' => 1,
    'crystal_type' => 'none',
    'consume_type' => 'consume_type_stackable',
  ],
  13871 => 
  [
    'item_id' => 13871,
    'icon' => 'etc_feather_gold_i00',
    'name' => 'Vulture\'s Golden Feather',
    'additionalname' => '',
    'description' => 'Take this large golden feather to Dwarven Engineer Lekon at Keucereus Alliance Base and receive a reward.',
    'is_trade' => 0,
    'is_drop' => 0,
    'is_destruct' => 1,
    'crystal_type' => 'none',
    'consume_type' => 'consume_type_stackable',
  ],
  13872 => 
  [
    'item_id' => 13872,
    'icon' => 'etc_skull_white_i00',
    'name' => 'Swallowed Skull',
    'additionalname' => '',
    'description' => 'Swallowed by the Rok that roams the Seed of Destruction\'s dungeon or one of its Variant Falcon or Dra Hawk minions. Collect the remains of those who were sacrificed and take them to Soldier Orbyu at Keucereus Alliance Base.',
    'is_trade' => 0,
    'is_drop' => 0,
    'is_destruct' => 1,
    'crystal_type' => 'none',
    'consume_type' => 'consume_type_stackable',
  ],
  13873 => 
  [
    'item_id' => 13873,
    'icon' => 'etc_rib_white_i00',
    'name' => 'Swallowed Sternum',
    'additionalname' => '',
    'description' => 'Swallowed by the Rok that roams the Seed of Destruction\'s dungeon or one of its Variant Falcon or Dra Hawk minions. Collect the remains of those who were sacrificed and take them to Soldier Orbyu at Keucereus Alliance Base.',
    'is_trade' => 0,
    'is_drop' => 0,
    'is_destruct' => 1,
    'crystal_type' => 'none',
    'consume_type' => 'consume_type_stackable',
  ],
  13874 => 
  [
    'item_id' => 13874,
    'icon' => 'etc_piece_bone_white_i00',
    'name' => 'Swallowed Bones',
    'additionalname' => '',
    'description' => 'Swallowed by the Rok that roams the Seed of Destruction\'s dungeon or one of its Variant Falcon or Dra Hawk minions. Collect the remains of those who were sacrificed and take them to Soldier Orbyu at Keucereus Alliance Base.',
    'is_trade' => 0,
    'is_drop' => 0,
    'is_destruct' => 1,
    'crystal_type' => 'none',
    'consume_type' => 'consume_type_stackable',
  ],
  13875 => 
  [
    'item_id' => 13875,
    'icon' => 'etc_piece_bone_black_i00',
    'name' => 'Deadman\'s Remains',
    'additionalname' => '',
    'description' => 'Obtained by hunting Floating Skulls and Floating Zombies. Take them to War Mage Artius.',
    'is_trade' => 0,
    'is_drop' => 0,
    'is_destruct' => 1,
    'crystal_type' => 'none',
    'consume_type' => 'consume_type_stackable',
  ],
  13876 => 
  [
    'item_id' => 13876,
    'icon' => 'etc_eyeball_i00',
    'name' => 'Banshee Queen\'s Eye',
    'additionalname' => '',
    'description' => 'Proof that you have captured the Banshee Queen. Take it to War Mage Artius.',
    'is_trade' => 0,
    'is_drop' => 0,
    'is_destruct' => 1,
    'crystal_type' => 'none',
    'consume_type' => 'consume_type_stackable',
  ],
  13877 => 
  [
    'item_id' => 13877,
    'icon' => 'etc_meat_of_monstereye_i00',
    'name' => 'Drake\'s Flesh',
    'additionalname' => '',
    'description' => 'Obtained by hunting Variant Drake Wing minions. Collect them and take them to injured Soldier Tenius at Keucereus Alliance Base.',
    'is_trade' => 0,
    'is_drop' => 0,
    'is_destruct' => 1,
    'crystal_type' => 'none',
    'consume_type' => 'consume_type_stackable',
  ],
  13878 => 
  [
    'item_id' => 13878,
    'icon' => 'etc_potion_scarlet_i00',
    'name' => 'Rotten Blood',
    'additionalname' => '',
    'description' => 'Obtained from injured Soldier Tenius, this small vial contains spoiled blood that he claims contains the collected anger toward Keucereus. Its true origin is obscure.',
    'is_trade' => 0,
    'is_drop' => 0,
    'is_destruct' => 1,
    'crystal_type' => 'none',
    'consume_type' => 'consume_type_stackable',
  ],
  13879 => 
  [
    'item_id' => 13879,
    'icon' => 'drake_wing_lure_i00',
    'name' => 'Bait for Drakes',
    'additionalname' => '',
    'description' => 'Drake exclusive bait made by combining Drake flesh and a little bit of the rotten blood. If this Bait for Drakes is used when Seed of Destruction is stabilized, one can call the Dead of Destruction, Dius.',
    'is_trade' => 0,
    'is_drop' => 0,
    'is_destruct' => 1,
    'crystal_type' => 'none',
    'consume_type' => 'consume_type_stackable',
  ],
  13880 => 
  [
    'item_id' => 13880,
    'icon' => 'etc_horn_i00',
    'name' => 'Variant Drake Wing Horns',
    'additionalname' => '',
    'description' => 'Horn that sprouts out from the body of the Variant Drake. If you bring it to the injured soldier Tenis or soldier Plenos at Keucereus Alliance Base, you can receive a reward.',
    'is_trade' => 0,
    'is_drop' => 0,
    'is_destruct' => 1,
    'crystal_type' => 'none',
    'consume_type' => 'consume_type_stackable',
  ],
  13881 => 
  [
    'item_id' => 13881,
    'icon' => 'weapon_long_sword_i00',
    'name' => 'Attribute Master Yang\'s Sword',
    'additionalname' => '10-minute',
    'description' => 'Weapon provided by Attribute Master Yang for capturing the Reckless Wind Spirits. You can feel the powerful energy of earth. The spirit\'s power contained in this weapon will be useful when capturing the reckless spirit. 10-minute-limited-time Item.10-minute item. Earth Attribute + 10.',
    'is_trade' => 0,
    'is_drop' => 0,
    'is_destruct' => 0,
    'crystal_type' => 'a',
    'consume_type' => 'consume_type_normal',
  ],
  13882 => 
  [
    'item_id' => 13882,
    'icon' => 'dual_dagger_i00',
    'name' => 'Dynasty Dual Dagger',
    'additionalname' => '',
    'description' => 'P. Atk. of Dual Daggers increases more than that of regular one-handed swords when enchanted. Can bestow 1 regular Soul Crystal and 1 Special Soul Crystal. Increases the damage inflicted during PvP. Can be equipped by Dagger Masters above level 81.',
    'is_trade' => 1,
    'is_drop' => 1,
    'is_destruct' => 1,
    'crystal_type' => 's',
    'consume_type' => 'consume_type_normal',
  ],
  13883 => 
  [
    'item_id' => 13883,
    'icon' => 'dual_dagger_i00',
    'name' => 'Icarus Dual Daggers',
    'additionalname' => '',
    'description' => 'P. Atk. of Dual Daggers increases more than that of regular one-handed swords when enchanted. Can bestow 1 regular Soul Crystal and 1 Special Soul Crystal. Increases the damage inflicted during PvP. Can be equipped by Dagger Masters above level 81.',
    'is_trade' => 1,
    'is_drop' => 1,
    'is_destruct' => 1,
    'crystal_type' => 's80',
    'consume_type' => 'consume_type_normal',
  ],
  13884 => 
  [
    'item_id' => 13884,
    'icon' => 'dual_dagger_i00',
    'name' => 'Vesper Dual Daggers',
    'additionalname' => '',
    'description' => 'P. Atk. of Dual Daggers increases more than that of regular one-handed swords when enchanted. Can bestow 1 regular Soul Crystal and 1 Special Soul Crystal. Increases the damage inflicted during PvP. Can be equipped by Dagger Masters above level 81.',
    'is_trade' => 1,
    'is_drop' => 1,
    'is_destruct' => 1,
    'crystal_type' => 's80',
    'consume_type' => 'consume_type_normal',
  ],
  13885 => 
  [
    'item_id' => 13885,
    'icon' => 'arcana_sigil_i01',
    'name' => 'Sealed Arcana Sigil',
    'additionalname' => '',
    'description' => 'Sealed Arcana Sigil. Seal can be removed by the blacksmith of Mammon.',
    'is_trade' => 1,
    'is_drop' => 1,
    'is_destruct' => 1,
    'crystal_type' => 's',
    'consume_type' => 'consume_type_normal',
  ],
  13886 => 
  [
    'item_id' => 13886,
    'icon' => 'armor_dynasty_sigil_i01',
    'name' => 'Sealed Dynasty Sigil',
    'additionalname' => '',
    'description' => 'Sealed Dynasty Sigil. Seal can be removed by the blacksmith of Mammon.',
    'is_trade' => 1,
    'is_drop' => 1,
    'is_destruct' => 1,
    'crystal_type' => 's',
    'consume_type' => 'consume_type_normal',
  ],
  13887 => 
  [
    'item_id' => 13887,
    'icon' => 'armor_verper_sigil_i01',
    'name' => 'Sealed Vesper Sigil',
    'additionalname' => '',
    'description' => 'Sealed Vesper Sigil. Seal can be removed by the blacksmith of Mammon and Maestro Ishuma.',
    'is_trade' => 1,
    'is_drop' => 1,
    'is_destruct' => 1,
    'crystal_type' => 's80',
    'consume_type' => 'consume_type_normal',
  ],
  13888 => 
  [
    'item_id' => 13888,
    'icon' => 'feud_load_cloak_i01',
    'name' => 'Sealed Lord\'s Cloak',
    'additionalname' => '',
    'description' => '',
    'is_trade' => 1,
    'is_drop' => 1,
    'is_destruct' => 1,
    'crystal_type' => 's80',
    'consume_type' => 'consume_type_normal',
  ],
  13889 => 
  [
    'item_id' => 13889,
    'icon' => 'vesper_cloack_i00',
    'name' => 'Holy Spirit\'s Cloak (Kamael]',
    'additionalname' => '',
    'description' => 'Cloak covered with energy of the Holy Spirit. Dark Resistance + 30. When the entire set of Vesper Noble or Dynasty set is worn, the Sealed Cloak Slot will be open and one can now wear the cloak. Kamael-exclusive cloak. Cannot be enchanted, augmented, or assigned an attribute.',
    'is_trade' => 1,
    'is_drop' => 1,
    'is_destruct' => 1,
    'crystal_type' => 's80',
    'consume_type' => 'consume_type_normal',
  ],
  13890 => 
  [
    'item_id' => 13890,
    'icon' => 'vesper_cloack_i00',
    'name' => 'Holy Spirit\'s Cloak',
    'additionalname' => '',
    'description' => 'Cloak covered with energy of the Holy Spirit. Dark Resistance + 30. When an armor set above the Dynasty level is worn, the Sealed Cloak Slot will be open so that the cloak can be equipped. Cannot be enchanted, augmented, or assigned an attribute.',
    'is_trade' => 1,
    'is_drop' => 1,
    'is_destruct' => 1,
    'crystal_type' => 's80',
    'consume_type' => 'consume_type_normal',
  ],
  13891 => 
  [
    'item_id' => 13891,
    'icon' => 'vesper_cloack_i00',
    'name' => 'Holy Spirit\'s Cloak (Light Armor]',
    'additionalname' => '',
    'description' => 'Cloak covered with energy of the Holy Spirit. Dark Resistance + 30. When the entire set of Vesper Noble or Dynasty set is worn, the Sealed Cloak Slot will be open and one can now wear the cloak. The cloak is exclusively for Dagger Master and Bow Master excluding Kamaels. Cannot be enchanted, augmented, or assigned an attribute.',
    'is_trade' => 1,
    'is_drop' => 1,
    'is_destruct' => 1,
    'crystal_type' => 's80',
    'consume_type' => 'consume_type_normal',
  ],
  13892 => 
  [
    'item_id' => 13892,
    'icon' => 'vesper_cloack_i00',
    'name' => 'Holy Spirit\'s Cloak (Robe]',
    'additionalname' => '',
    'description' => 'Cloak covered with energy of the Holy Spirit. Dark Resistance + 30. When the entire set of Vesper Noble or Dynasty set is worn, the Sealed Cloak Slot will be open and one can now wear the cloak. The cloak is exclusively for Healer, Enchanter, Summoner and Wizard excluding Kamaels. Cannot be enchanted, augmented, or assigned an attribute.',
    'is_trade' => 1,
    'is_drop' => 1,
    'is_destruct' => 1,
    'crystal_type' => 's80',
    'consume_type' => 'consume_type_normal',
  ],
  13893 => 
  [
    'item_id' => 13893,
    'icon' => 'sealed_vesper_cloack_i01',
    'name' => 'Sealed Holy Spirit\'s Cloak',
    'additionalname' => '',
    'description' => 'Sealed Holy Spirit\'s Cloak. When the seal is cancelled, it\'ll have Dark Attribute Defense + 30 effect. The seal can be cancelled through the weaver Olf Kanore and Olf Adams. It cannot be worn before the seal cancellation. Enchantment, attribute and augmenting are impossible.',
    'is_trade' => 1,
    'is_drop' => 1,
    'is_destruct' => 1,
    'crystal_type' => 's80',
    'consume_type' => 'consume_type_normal',
  ],
  13894 => 
  [
    'item_id' => 13894,
    'icon' => 'armor_belt_i00',
    'name' => 'Cloth Belt',
    'additionalname' => '',
    'description' => 'Functions can be added by using C-grade Magic Pin or Magic Pouch.',
    'is_trade' => 1,
    'is_drop' => 1,
    'is_destruct' => 1,
    'crystal_type' => 'c',
    'consume_type' => 'consume_type_normal',
  ],
  13895 => 
  [
    'item_id' => 13895,
    'icon' => 'armor_belt_i01',
    'name' => 'Leather Belt',
    'additionalname' => '',
    'description' => 'Functions can be added by using B-grade Magic Pin or Magic Pouch.',
    'is_trade' => 1,
    'is_drop' => 1,
    'is_destruct' => 1,
    'crystal_type' => 'b',
    'consume_type' => 'consume_type_normal',
  ],
  13896 => 
  [
    'item_id' => 13896,
    'icon' => 'armor_belt_i02',
    'name' => 'Iron Belt',
    'additionalname' => '',
    'description' => 'One can attach a function using A-grade Magic Pin, Magic Pouch, Rune clip, and Magic ornament.',
    'is_trade' => 1,
    'is_drop' => 1,
    'is_destruct' => 1,
    'crystal_type' => 'a',
    'consume_type' => 'consume_type_normal',
  ],
  13897 => 
  [
    'item_id' => 13897,
    'icon' => 'armor_belt_i03',
    'name' => 'Mithril Belt',
    'additionalname' => '',
    'description' => 'One can attach a function using S-grade Magic Pin, Magic Pouch, Rune clip, and Magic ornament.',
    'is_trade' => 1,
    'is_drop' => 1,
    'is_destruct' => 1,
    'crystal_type' => 's',
    'consume_type' => 'consume_type_normal',
  ],
  13898 => 
  [
    'item_id' => 13898,
    'icon' => 'pin_i00',
    'name' => 'Sealed Magic Pin (C-grade]',
    'additionalname' => '',
    'description' => 'Can be attached to Sealed Magic Pin and Belt. And the seal can be cancelled through the weaver Olf Kanore and Olf Adams.',
    'is_trade' => 1,
    'is_drop' => 1,
    'is_destruct' => 1,
    'crystal_type' => 'none',
    'consume_type' => 'consume_type_normal',
  ],
  13899 => 
  [
    'item_id' => 13899,
    'icon' => 'pin_i00',
    'name' => 'Sealed Magic Pin (B-grade]',
    'additionalname' => '',
    'description' => 'Can be attached to Sealed Magic Pin and Belt. And the seal can be cancelled through the weaver Olf Kanore and Olf Adams.',
    'is_trade' => 1,
    'is_drop' => 1,
    'is_destruct' => 1,
    'crystal_type' => 'none',
    'consume_type' => 'consume_type_normal',
  ],
];