<?php return [
  15400 => 
  [
    'item_id' => 15400,
    'icon' => 'event_energy_belt_i00',
    'name' => 'Vitality Belt (Event]',
    'additionalname' => '60-day',
    'description' => 'Vitality Belt. Can be enchanted using the Scroll: Enchant Vitality Belt. When enchanted, increases Vitality maintenance effect, and decreases Vitality maintenance cooldown.',
    'is_trade' => 0,
    'is_drop' => 0,
    'is_destruct' => 0,
    'crystal_type' => 'none',
    'consume_type' => 'consume_type_normal',
  ],
  15401 => 
  [
    'item_id' => 15401,
    'icon' => 'event_energy_belt_i00',
    'name' => 'Vitality Belt (Event]',
    'additionalname' => '90-day',
    'description' => 'Vitality Belt. Can be enchanted using the Scroll: Enchant Vitality Belt. When enchanted, increases Vitality maintenance effect, and decreases Vitality maintenance cooldown.',
    'is_trade' => 0,
    'is_drop' => 0,
    'is_destruct' => 0,
    'crystal_type' => 'none',
    'consume_type' => 'consume_type_normal',
  ],
  15402 => 
  [
    'item_id' => 15402,
    'icon' => 'event_energy_belt_i00',
    'name' => 'Vitality Belt (Event]',
    'additionalname' => 'Permanent',
    'description' => 'Vitality Belt. Can be enchanted using the Scroll: Enchant Vitality Belt. When enchanted, increases Vitality maintenance effect, and decreases Vitality maintenance cooldown.',
    'is_trade' => 0,
    'is_drop' => 0,
    'is_destruct' => 1,
    'crystal_type' => 'none',
    'consume_type' => 'consume_type_normal',
  ],
  15403 => 
  [
    'item_id' => 15403,
    'icon' => 'weapon_berserker_blade_i01',
    'name' => 'Player Commendation - Berserker Blade',
    'additionalname' => 'PC-exclusive Weapon',
    'description' => 'Berserker Blade with limited ability enhancement. <Special Option>
Critical increases by 73. Expiratory. Cannot be crystallized or granted functions besides enchantment. This item cannot be enhanced except with Destiny Enchant Scrolls.',
    'is_trade' => 0,
    'is_drop' => 0,
    'is_destruct' => 1,
    'crystal_type' => 'c',
    'consume_type' => 'consume_type_normal',
  ],
  15404 => 
  [
    'item_id' => 15404,
    'icon' => 'event_six_party_box_i00',
    'name' => '6th Anniversary Party Gift Box (2003]',
    'additionalname' => 'Event',
    'description' => 'Contains the 6th Anniversary Party Cube, a 30-day expiratory item. It automatically disappears at the end of the 6th anniversary cube event.',
    'is_trade' => 0,
    'is_drop' => 0,
    'is_destruct' => 1,
    'crystal_type' => 'none',
    'consume_type' => 'consume_type_stackable',
  ],
  15405 => 
  [
    'item_id' => 15405,
    'icon' => 'event_six_party_box_i00',
    'name' => '6th Anniversary Party Gift Box (2004]',
    'additionalname' => 'Event',
    'description' => 'Contains the 6th Anniversary Party Cube, a 25-day expiratory item. It automatically disappears at the end of the 6th anniversary cube event.',
    'is_trade' => 0,
    'is_drop' => 0,
    'is_destruct' => 1,
    'crystal_type' => 'none',
    'consume_type' => 'consume_type_stackable',
  ],
  15406 => 
  [
    'item_id' => 15406,
    'icon' => 'event_six_party_box_i00',
    'name' => '6th Anniversary Party Gift Box (2005]',
    'additionalname' => 'Event',
    'description' => 'Contains the 6th Anniversary Party Cube, a 20-day expiratory item. It automatically disappears at the end of the 6th anniversary cube event.',
    'is_trade' => 0,
    'is_drop' => 0,
    'is_destruct' => 1,
    'crystal_type' => 'none',
    'consume_type' => 'consume_type_stackable',
  ],
  15407 => 
  [
    'item_id' => 15407,
    'icon' => 'event_six_party_box_i00',
    'name' => '6th Anniversary Party Gift Box (2006]',
    'additionalname' => 'Event',
    'description' => 'Contains the 6th Anniversary Party Cube, a 15-day expiratory item. It automatically disappears at the end of the 6th anniversary cube event.',
    'is_trade' => 0,
    'is_drop' => 0,
    'is_destruct' => 1,
    'crystal_type' => 'none',
    'consume_type' => 'consume_type_stackable',
  ],
  15408 => 
  [
    'item_id' => 15408,
    'icon' => 'event_six_party_box_i00',
    'name' => '6th Anniversary Party Gift Box (2007]',
    'additionalname' => 'Event',
    'description' => 'Contains the 6th Anniversary Party Cube, a 10-day expiratory item. It automatically disappears at the end of the 6th anniversary cube event.',
    'is_trade' => 0,
    'is_drop' => 0,
    'is_destruct' => 1,
    'crystal_type' => 'none',
    'consume_type' => 'consume_type_stackable',
  ],
  15409 => 
  [
    'item_id' => 15409,
    'icon' => 'event_six_party_box_i00',
    'name' => '6th Anniversary Party Gift Box (2008]',
    'additionalname' => 'Event',
    'description' => 'Contains the 6th Anniversary Party Cube, a 5-day expiratory item. It automatically disappears at the end of the 6th anniversary cube event.',
    'is_trade' => 0,
    'is_drop' => 0,
    'is_destruct' => 1,
    'crystal_type' => 'none',
    'consume_type' => 'consume_type_stackable',
  ],
  15410 => 
  [
    'item_id' => 15410,
    'icon' => 'event_six_party_box_i00',
    'name' => '6th Anniversary Party Gift Box (2009]',
    'additionalname' => 'Event',
    'description' => 'Contains the 6th Anniversary Party Cube, a 3-day expiratory item. It automatically disappears at the end of the 6th anniversary cube event.',
    'is_trade' => 0,
    'is_drop' => 0,
    'is_destruct' => 1,
    'crystal_type' => 'none',
    'consume_type' => 'consume_type_stackable',
  ],
  15411 => 
  [
    'item_id' => 15411,
    'icon' => 'event_six_party_box_i00',
    'name' => '6th Anniversary Party Gift Set (2003]',
    'additionalname' => 'Event',
    'description' => 'Hero\'s Treasure Chest. Contains the 6th Anniversary Party Cube, a 30-day expiratory item. It automatically disappears at the end of the 6th anniversary cube event.',
    'is_trade' => 0,
    'is_drop' => 0,
    'is_destruct' => 1,
    'crystal_type' => 'none',
    'consume_type' => 'consume_type_stackable',
  ],
  15412 => 
  [
    'item_id' => 15412,
    'icon' => 'event_six_party_box_i00',
    'name' => '6th Anniversary Party Gift Set (2004]',
    'additionalname' => 'Event',
    'description' => 'Hero\'s Treasure Chest. Contains the 6th Anniversary Party Cube, a 25-day expiratory item. It automatically disappears at the end of the 6th anniversary cube event.',
    'is_trade' => 0,
    'is_drop' => 0,
    'is_destruct' => 1,
    'crystal_type' => 'none',
    'consume_type' => 'consume_type_stackable',
  ],
  15413 => 
  [
    'item_id' => 15413,
    'icon' => 'event_six_party_box_i00',
    'name' => '6th Anniversary Party Gift Set (2005]',
    'additionalname' => 'Event',
    'description' => 'Hero\'s Treasure Chest. Contains the 6th Anniversary Party Cube, a 20-day expiratory item. It automatically disappears at the end of the 6th anniversary cube event.',
    'is_trade' => 0,
    'is_drop' => 0,
    'is_destruct' => 1,
    'crystal_type' => 'none',
    'consume_type' => 'consume_type_stackable',
  ],
  15414 => 
  [
    'item_id' => 15414,
    'icon' => 'event_six_party_box_i00',
    'name' => '6th Anniversary Party Gift Set (2006]',
    'additionalname' => 'Event',
    'description' => 'Hero\'s Treasure Chest. Contains the 6th Anniversary Party Cube, a 15-day expiratory item. It automatically disappears at the end of the 6th anniversary cube event.',
    'is_trade' => 0,
    'is_drop' => 0,
    'is_destruct' => 1,
    'crystal_type' => 'none',
    'consume_type' => 'consume_type_stackable',
  ],
  15415 => 
  [
    'item_id' => 15415,
    'icon' => 'event_six_party_box_i00',
    'name' => '6th Anniversary Party Gift Set (2007]',
    'additionalname' => 'Event',
    'description' => 'Hero\'s Treasure Chest. Contains the 6th Anniversary Party Cube, a 10-day expiratory item. It automatically disappears at the end of the 6th anniversary cube event.',
    'is_trade' => 0,
    'is_drop' => 0,
    'is_destruct' => 1,
    'crystal_type' => 'none',
    'consume_type' => 'consume_type_stackable',
  ],
  15416 => 
  [
    'item_id' => 15416,
    'icon' => 'event_six_party_box_i00',
    'name' => '6th Anniversary Party Gift Set (2008]',
    'additionalname' => 'Event',
    'description' => 'Hero\'s Treasure Chest. Contains the 6th Anniversary Party Cube, a 5-day expiratory item. It automatically disappears at the end of the 6th anniversary cube event.',
    'is_trade' => 0,
    'is_drop' => 0,
    'is_destruct' => 1,
    'crystal_type' => 'none',
    'consume_type' => 'consume_type_stackable',
  ],
  15417 => 
  [
    'item_id' => 15417,
    'icon' => 'event_six_party_box_i00',
    'name' => '6th Anniversary Party Gift Set (2009]',
    'additionalname' => 'Event',
    'description' => 'Hero\'s Treasure Chest. Contains the 6th Anniversary Party Cube, a 3-day expiratory item. It automatically disappears at the end of the 6th anniversary cube event.',
    'is_trade' => 0,
    'is_drop' => 0,
    'is_destruct' => 1,
    'crystal_type' => 'none',
    'consume_type' => 'consume_type_stackable',
  ],
  15418 => 
  [
    'item_id' => 15418,
    'icon' => 'event_six_party_cube_i00',
    'name' => '6th Anniversary Party Cube (Event]',
    'additionalname' => '30-day',
    'description' => 'When you Double-click, the reward is created. What reward will you receive? That depends on how lucky you are. One use per day. Cooldown is 23 hour.',
    'is_trade' => 0,
    'is_drop' => 0,
    'is_destruct' => 0,
    'crystal_type' => 'none',
    'consume_type' => 'consume_type_normal',
  ],
  15419 => 
  [
    'item_id' => 15419,
    'icon' => 'event_six_party_cube_i00',
    'name' => '6th Anniversary Party Cube (Event]',
    'additionalname' => '25-day',
    'description' => 'When you Double-click, the reward is created. What reward will you receive? That depends on how lucky you are. One use per day. Cooldown is 23 hour.',
    'is_trade' => 0,
    'is_drop' => 0,
    'is_destruct' => 0,
    'crystal_type' => 'none',
    'consume_type' => 'consume_type_normal',
  ],
  15420 => 
  [
    'item_id' => 15420,
    'icon' => 'event_six_party_cube_i00',
    'name' => '6th Anniversary Party Cube (Event]',
    'additionalname' => '20-day',
    'description' => 'When you Double-click, the reward is created. What reward will you receive? That depends on how lucky you are. One use per day. Cooldown is 23 hour.',
    'is_trade' => 0,
    'is_drop' => 0,
    'is_destruct' => 0,
    'crystal_type' => 'none',
    'consume_type' => 'consume_type_normal',
  ],
  15421 => 
  [
    'item_id' => 15421,
    'icon' => 'event_six_party_cube_i00',
    'name' => '6th Anniversary Party Cube (Event]',
    'additionalname' => '15-day',
    'description' => 'When you Double-click, the reward is created. What reward will you receive? That depends on how lucky you are. One use per day. Cooldown is 23 hour.',
    'is_trade' => 0,
    'is_drop' => 0,
    'is_destruct' => 0,
    'crystal_type' => 'none',
    'consume_type' => 'consume_type_normal',
  ],
  15422 => 
  [
    'item_id' => 15422,
    'icon' => 'event_six_party_cube_i00',
    'name' => '6th Anniversary Party Cube (Event]',
    'additionalname' => '10-day',
    'description' => 'When you Double-click, the reward is created. What reward will you receive? That depends on how lucky you are. One use per day. Cooldown is 23 hour.',
    'is_trade' => 0,
    'is_drop' => 0,
    'is_destruct' => 0,
    'crystal_type' => 'none',
    'consume_type' => 'consume_type_normal',
  ],
  15423 => 
  [
    'item_id' => 15423,
    'icon' => 'event_six_party_cube_i00',
    'name' => '6th Anniversary Party Cube (Event]',
    'additionalname' => '5-day',
    'description' => 'When you Double-click, the reward is created. What reward will you receive? That depends on how lucky you are. One use per day. Cooldown is 23 hour.',
    'is_trade' => 0,
    'is_drop' => 0,
    'is_destruct' => 0,
    'crystal_type' => 'none',
    'consume_type' => 'consume_type_normal',
  ],
  15424 => 
  [
    'item_id' => 15424,
    'icon' => 'event_six_party_cube_i00',
    'name' => '6th Anniversary Party Cube (Event]',
    'additionalname' => '3-day',
    'description' => 'When you Double-click, the reward is created. What reward will you receive? That depends on how lucky you are. One use per day. Cooldown is 23 hour.',
    'is_trade' => 0,
    'is_drop' => 0,
    'is_destruct' => 0,
    'crystal_type' => 'none',
    'consume_type' => 'consume_type_normal',
  ],
  15425 => 
  [
    'item_id' => 15425,
    'icon' => 'event_hero_treasure_box_i00',
    'name' => 'Hero\'s Treasure Chest',
    'additionalname' => 'Event',
    'description' => 'Contains an armor set Pack (30-day], a Minion Coupon, and a Hero\'s Escape Point item.',
    'is_trade' => 0,
    'is_drop' => 0,
    'is_destruct' => 1,
    'crystal_type' => 'none',
    'consume_type' => 'consume_type_normal',
  ],
  15426 => 
  [
    'item_id' => 15426,
    'icon' => 'etc_pccafe_point_i00',
    'name' => 'Hero\'s Escape Point',
    'additionalname' => 'Event',
    'description' => 'When Double-clicked, 10000 Player Commendation Points can be acquired. Cooldown is 7 days.',
    'is_trade' => 0,
    'is_drop' => 0,
    'is_destruct' => 1,
    'crystal_type' => 'none',
    'consume_type' => 'consume_type_stackable',
  ],
  15427 => 
  [
    'item_id' => 15427,
    'icon' => 'event_six_party_cake_i00',
    'name' => '6th Anniversary Party Cake',
    'additionalname' => 'Event',
    'description' => 'For 1 hour, Vitality is recovered when acquiring XP. Cooldown is 12 hours. Vitality item with limited usage.',
    'is_trade' => 0,
    'is_drop' => 0,
    'is_destruct' => 1,
    'crystal_type' => 'none',
    'consume_type' => 'consume_type_stackable',
  ],
  15428 => 
  [
    'item_id' => 15428,
    'icon' => 'event_six_party_earing_i00',
    'name' => '6th Anniversary Party Earring (Event]',
    'additionalname' => '30-day',
    'description' => '30-day. Increases MP by 31 and Stun/Mental Attack Resistance by 20%. Increases Stun/Mental Atk. Rate by 20%. Has the Vampiric Rage Effect. Only one effect is applied even when the two identical earrings are worn.',
    'is_trade' => 0,
    'is_drop' => 0,
    'is_destruct' => 0,
    'crystal_type' => 'a',
    'consume_type' => 'consume_type_normal',
  ],
  15429 => 
  [
    'item_id' => 15429,
    'icon' => 'event_energy_belt_i00',
    'name' => '6th Anniversary Party Belt (Event]',
    'additionalname' => '7-day',
    'description' => 'Vitality is maintained for 30 min. 7-day. Cooldown is 23 hours. Vitality item with limited usage.',
    'is_trade' => 0,
    'is_drop' => 0,
    'is_destruct' => 0,
    'crystal_type' => 'none',
    'consume_type' => 'consume_type_normal',
  ],
  15430 => 
  [
    'item_id' => 15430,
    'icon' => 'ev_hallowinday_candy_i00',
    'name' => 'Event - Revita-Pop',
    'additionalname' => 'Event',
    'description' => 'Sweet Revita-Pop. You can give it to Skooldie to exchange for the Halloween Toy Box.',
    'is_trade' => 1,
    'is_drop' => 1,
    'is_destruct' => 1,
    'crystal_type' => 'none',
    'consume_type' => 'consume_type_stackable',
  ],
  15431 => 
  [
    'item_id' => 15431,
    'icon' => 'ev_scroll_of_wooldie_i00',
    'name' => 'Event - Summon Scroll: Uldie',
    'additionalname' => '',
    'description' => 'When used, summons the oldest girl Uldie among the Three Siblings, and can play Jack\'s game. You cannot summon Uldie if a pet is summoned or if the Halloween mask isn\'t equipped. You cannot play Jack\'s game is you are currently transformed or your stance is in a switched state!',
    'is_trade' => 1,
    'is_drop' => 1,
    'is_destruct' => 1,
    'crystal_type' => 'none',
    'consume_type' => 'consume_type_stackable',
  ],
  15432 => 
  [
    'item_id' => 15432,
    'icon' => 'ev_scroll_of_berdandi_i00',
    'name' => 'Event - Summon Scroll: Belldandy',
    'additionalname' => '',
    'description' => 'When used, summons the middle child Belldandy among the Three Siblings, and can play Jack\'s game. You cannot summon Belldandy if a pet is summoned or if the Halloween mask isn\'t equipped. You cannot play Jack\'s game is you are currently transformed or your stance is in a switched state!',
    'is_trade' => 1,
    'is_drop' => 1,
    'is_destruct' => 1,
    'crystal_type' => 'none',
    'consume_type' => 'consume_type_stackable',
  ],
  15433 => 
  [
    'item_id' => 15433,
    'icon' => 'ev_scroll_of_scooldie_i00',
    'name' => 'Event - Summon Scroll: Skooldie',
    'additionalname' => '',
    'description' => 'When used, summons the youngest child Skooldie among the Three Siblings, and can play Jack\'s game. You cannot summon Skooldie if a pet is summoned or if the Halloween mask isn\'t equipped. You cannot play Jack\'s game is you are currently transformed or your stance is in a switched state!',
    'is_trade' => 0,
    'is_drop' => 0,
    'is_destruct' => 1,
    'crystal_type' => 'none',
    'consume_type' => 'consume_type_stackable',
  ],
  15434 => 
  [
    'item_id' => 15434,
    'icon' => 'etc_box_of_adventure_1_i00',
    'name' => 'Halloween Toy Box',
    'additionalname' => '',
    'description' => 'Gives a chance to acquire one of Halloween masks.',
    'is_trade' => 0,
    'is_drop' => 0,
    'is_destruct' => 1,
    'crystal_type' => 'none',
    'consume_type' => 'consume_type_normal',
  ],
  15435 => 
  [
    'item_id' => 15435,
    'icon' => 'etc_box_of_adventure_1_i00',
    'name' => 'Shiny Halloween Toy Box',
    'additionalname' => '',
    'description' => 'Gives a chance to acquire one of Shiny Halloween masks.',
    'is_trade' => 0,
    'is_drop' => 0,
    'is_destruct' => 1,
    'crystal_type' => 'none',
    'consume_type' => 'consume_type_normal',
  ],
  15436 => 
  [
    'item_id' => 15436,
    'icon' => 'weapon_pumpkin_stick_i00',
    'name' => 'Halloween Transformation Stick',
    'additionalname' => '7-day',
    'description' => 'You can transform to Halloween Pumpkin. 7-day accessory.',
    'is_trade' => 0,
    'is_drop' => 0,
    'is_destruct' => 0,
    'crystal_type' => 'none',
    'consume_type' => 'consume_type_normal',
  ],
  15437 => 
  [
    'item_id' => 15437,
    'icon' => 'etc_pi_gift_box_i00',
    'name' => 'Transformation Scroll Pack',
    'additionalname' => '',
    'description' => 'Gives a chance to acquire one of the following transformation scrolls: Onyx Beast, Doom Wraith, and Grail Apostle.',
    'is_trade' => 0,
    'is_drop' => 0,
    'is_destruct' => 1,
    'crystal_type' => 'none',
    'consume_type' => 'consume_type_stackable',
  ],
  15438 => 
  [
    'item_id' => 15438,
    'icon' => 'etc_lesser_potion_blue_i00',
    'name' => 'Vitality Maintaining Potion (10-minute]',
    'additionalname' => '',
    'description' => 'Vitality is maintained for 10 min. Cooldown is 30 min. Vitality item with limited usage.',
    'is_trade' => 0,
    'is_drop' => 0,
    'is_destruct' => 1,
    'crystal_type' => 'none',
    'consume_type' => 'consume_type_stackable',
  ],
  15439 => 
  [
    'item_id' => 15439,
    'icon' => 'etc_sp_scroll3_i00',
    'name' => 'Scroll: 1,000 SP',
    'additionalname' => '',
    'description' => 'Scroll that replenishes 1,000 SP.',
    'is_trade' => 1,
    'is_drop' => 1,
    'is_destruct' => 1,
    'crystal_type' => 'none',
    'consume_type' => 'consume_type_stackable',
  ],
  15440 => 
  [
    'item_id' => 15440,
    'icon' => 'etc_lesser_potion_scarlet_i00',
    'name' => 'Vitality Maintaining Potion (30-minute]',
    'additionalname' => '',
    'description' => 'Vitality is maintained for 30 min. Cooldown is 60 min. Vitality item with limited usage. Effect remains even after death.',
    'is_trade' => 0,
    'is_drop' => 0,
    'is_destruct' => 1,
    'crystal_type' => 'none',
    'consume_type' => 'consume_type_stackable',
  ],
  15441 => 
  [
    'item_id' => 15441,
    'icon' => 'ev_valakas_the_flame_i00',
    'name' => 'Red Flame Valakas Hair Accessory',
    'additionalname' => '',
    'description' => 'Helm the color of blazing fire.',
    'is_trade' => 0,
    'is_drop' => 0,
    'is_destruct' => 1,
    'crystal_type' => 'none',
    'consume_type' => 'consume_type_normal',
  ],
  15442 => 
  [
    'item_id' => 15442,
    'icon' => 'ev_jack0_mask_i00',
    'name' => 'Jack O\'Lantern Mask',
    'additionalname' => '',
    'description' => 'You can use the card skill necessary for playing Jack\'s game when equipped.',
    'is_trade' => 0,
    'is_drop' => 0,
    'is_destruct' => 1,
    'crystal_type' => 'none',
    'consume_type' => 'consume_type_normal',
  ],
  15443 => 
  [
    'item_id' => 15443,
    'icon' => 'br_frankenstein_mask_i00',
    'name' => 'Super Strong Giant\'s Mask',
    'additionalname' => '',
    'description' => 'Super Strong Giant\'s Mask. You can use the card skill necessary for playing Jack\'s game when equipped. 4-hour. Cooldown is 1 hour.',
    'is_trade' => 0,
    'is_drop' => 0,
    'is_destruct' => 1,
    'crystal_type' => 'none',
    'consume_type' => 'consume_type_normal',
  ],
  15444 => 
  [
    'item_id' => 15444,
    'icon' => 'ev_scream_mask_i00',
    'name' => 'Shriek Mask',
    'additionalname' => '',
    'description' => 'Shriek Mask. You can use the card skill necessary for playing Jack\'s game when equipped. 4-hour. Cooldown is 1 hour.',
    'is_trade' => 0,
    'is_drop' => 0,
    'is_destruct' => 1,
    'crystal_type' => 'none',
    'consume_type' => 'consume_type_normal',
  ],
  15445 => 
  [
    'item_id' => 15445,
    'icon' => 'ev_doccabi_mask_i00',
    'name' => 'Red Devil Mask',
    'additionalname' => '',
    'description' => 'Red Devil Mask. You can use the card skill necessary for playing Jack\'s game when equipped. 4-hour. Cooldown is 1 hour.',
    'is_trade' => 0,
    'is_drop' => 0,
    'is_destruct' => 1,
    'crystal_type' => 'none',
    'consume_type' => 'consume_type_normal',
  ],
  15446 => 
  [
    'item_id' => 15446,
    'icon' => 'ev_mummy_mask_i00',
    'name' => 'Mummy Mask',
    'additionalname' => '',
    'description' => 'Mummy Mask. You can use the card skill necessary for playing Jack\'s game when equipped. 4-hour. Cooldown is 1 hour.',
    'is_trade' => 0,
    'is_drop' => 0,
    'is_destruct' => 1,
    'crystal_type' => 'none',
    'consume_type' => 'consume_type_normal',
  ],
  15447 => 
  [
    'item_id' => 15447,
    'icon' => 'ev_alien_mask_i00',
    'name' => 'Alien Mask',
    'additionalname' => '',
    'description' => 'Can use the card skill necessary for playing Jack\'s game when equipped. 4-hour. Cooldown is 1 hour.',
    'is_trade' => 0,
    'is_drop' => 0,
    'is_destruct' => 1,
    'crystal_type' => 'none',
    'consume_type' => 'consume_type_normal',
  ],
  15448 => 
  [
    'item_id' => 15448,
    'icon' => 'ev_golden_jack0_mask_i00',
    'name' => 'Golden Jack O\'Lantern Mask',
    'additionalname' => 'Permanent',
    'description' => 'Jack O\'Lantern Mask made of gold. Shines brightly.',
    'is_trade' => 0,
    'is_drop' => 0,
    'is_destruct' => 1,
    'crystal_type' => 'none',
    'consume_type' => 'consume_type_normal',
  ],
  15449 => 
  [
    'item_id' => 15449,
    'icon' => 'ev_shiny_alien_mask_i00',
    'name' => 'Shiny Alien Mask',
    'additionalname' => '',
    'description' => 'Can use the card skill necessary for playing Jack\'s game when equipped. 4-hour. Cooldown is 1 hour.',
    'is_trade' => 0,
    'is_drop' => 0,
    'is_destruct' => 1,
    'crystal_type' => 'none',
    'consume_type' => 'consume_type_normal',
  ],
  15450 => 
  [
    'item_id' => 15450,
    'icon' => 'ev_shiny_frankenstein_mask_i00',
    'name' => 'Shiny Reanimated Corpse Mask',
    'additionalname' => '',
    'description' => 'Shiny Reanimated Corpse Mask. You can use the card skill necessary for playing Jack\'s game when equipped. 4-hour. Cooldown is 2 hours.',
    'is_trade' => 0,
    'is_drop' => 0,
    'is_destruct' => 1,
    'crystal_type' => 'none',
    'consume_type' => 'consume_type_normal',
  ],
  15451 => 
  [
    'item_id' => 15451,
    'icon' => 'ev_shiny_scream_mask_i00',
    'name' => 'Shiny Shriek Mask',
    'additionalname' => '',
    'description' => 'Shiny Shriek Mask. You can use the card skill necessary for playing Jack\'s game when equipped. 4-hour. Cooldown is 1 hour.',
    'is_trade' => 0,
    'is_drop' => 0,
    'is_destruct' => 1,
    'crystal_type' => 'none',
    'consume_type' => 'consume_type_normal',
  ],
  15452 => 
  [
    'item_id' => 15452,
    'icon' => 'ev_shiny_doccabi_mask_i00',
    'name' => 'Shiny Red Devil Mask',
    'additionalname' => '',
    'description' => 'Shiny Red Devil Mask. You can use the card skill necessary for playing Jack\'s game when equipped. 4-hour. Cooldown is 1 hour.',
    'is_trade' => 0,
    'is_drop' => 0,
    'is_destruct' => 1,
    'crystal_type' => 'none',
    'consume_type' => 'consume_type_normal',
  ],
  15453 => 
  [
    'item_id' => 15453,
    'icon' => 'ev_shiny_mummy_mask_i00',
    'name' => 'Shiny Mummy Mask',
    'additionalname' => '',
    'description' => 'Shiny Mummy Mask. You can use the card skill necessary for playing Jack\'s game when equipped. 4-hour. Cooldown is 1 hour.',
    'is_trade' => 0,
    'is_drop' => 0,
    'is_destruct' => 1,
    'crystal_type' => 'none',
    'consume_type' => 'consume_type_normal',
  ],
  15454 => 
  [
    'item_id' => 15454,
    'icon' => 'etc_pi_gift_box_i04',
    'name' => 'Shiny Alien Mask Pack',
    'additionalname' => 'Event',
    'description' => 'Wrapped Pack containing Shiny Alien Mask.',
    'is_trade' => 0,
    'is_drop' => 0,
    'is_destruct' => 1,
    'crystal_type' => 'none',
    'consume_type' => 'consume_type_stackable',
  ],
  15455 => 
  [
    'item_id' => 15455,
    'icon' => 'etc_pi_gift_box_i04',
    'name' => 'Shiny Reanimated Corpse Mask Pack',
    'additionalname' => 'Event',
    'description' => 'Wrapped Pack containing Shiny Reanimated Corpse Mask.',
    'is_trade' => 0,
    'is_drop' => 0,
    'is_destruct' => 1,
    'crystal_type' => 'none',
    'consume_type' => 'consume_type_stackable',
  ],
  15456 => 
  [
    'item_id' => 15456,
    'icon' => 'etc_pi_gift_box_i04',
    'name' => 'Shiny Shriek Mask Pack',
    'additionalname' => 'Event',
    'description' => 'Wrapped Pack containing Shiny Shriek Mask.',
    'is_trade' => 0,
    'is_drop' => 0,
    'is_destruct' => 1,
    'crystal_type' => 'none',
    'consume_type' => 'consume_type_stackable',
  ],
  15457 => 
  [
    'item_id' => 15457,
    'icon' => 'etc_pi_gift_box_i04',
    'name' => 'Shiny Red Devil Mask Pack',
    'additionalname' => 'Event',
    'description' => 'Wrapped Pack containing Shiny Red Devil Mask.',
    'is_trade' => 0,
    'is_drop' => 0,
    'is_destruct' => 1,
    'crystal_type' => 'none',
    'consume_type' => 'consume_type_stackable',
  ],
  15458 => 
  [
    'item_id' => 15458,
    'icon' => 'etc_pi_gift_box_i04',
    'name' => 'Shiny Mummy Mask Pack',
    'additionalname' => 'Event',
    'description' => 'Wrapped Pack containing Shiny Mummy Mask.',
    'is_trade' => 0,
    'is_drop' => 0,
    'is_destruct' => 1,
    'crystal_type' => 'none',
    'consume_type' => 'consume_type_stackable',
  ],
  15459 => 
  [
    'item_id' => 15459,
    'icon' => 'etc_pi_gift_box_i04',
    'name' => 'Halloween Nectar Pumpkin Pack',
    'additionalname' => 'Event',
    'description' => 'Halloween Nectar Pumpkin Pack. Contains 1 Halloween nectar pumpkin.',
    'is_trade' => 0,
    'is_drop' => 0,
    'is_destruct' => 1,
    'crystal_type' => 'none',
    'consume_type' => 'consume_type_stackable',
  ],
  15460 => 
  [
    'item_id' => 15460,
    'icon' => 'etc_pi_gift_box_i04',
    'name' => 'Halloween King Pumpkin Pack',
    'additionalname' => 'Event',
    'description' => 'Halloween King Pumpkin Pack. Contains 1 Halloween king pumpkin.',
    'is_trade' => 0,
    'is_drop' => 0,
    'is_destruct' => 1,
    'crystal_type' => 'none',
    'consume_type' => 'consume_type_stackable',
  ],
  15461 => 
  [
    'item_id' => 15461,
    'icon' => 'event_halloween_pumpkin_i00',
    'name' => 'Halloween Nectar Pumpkin',
    'additionalname' => 'Event',
    'description' => 'Halloween Nectar Pumpkin. With a certain chance, can obtain a Vitality replenishing drink or a feather of blessing and 1 small Halloween pumpkin.',
    'is_trade' => 1,
    'is_drop' => 0,
    'is_destruct' => 1,
    'crystal_type' => 'none',
    'consume_type' => 'consume_type_normal',
  ],
  15462 => 
  [
    'item_id' => 15462,
    'icon' => 'event_halloween_king_pumpkini00',
    'name' => 'Halloween King Pumpkin',
    'additionalname' => 'Event',
    'description' => 'Halloween King Pumpkin. Contains 6 Halloween nectar pumpkins and a Golden Jack O\'Lantern Mask (7 day].',
    'is_trade' => 1,
    'is_drop' => 0,
    'is_destruct' => 1,
    'crystal_type' => 'none',
    'consume_type' => 'consume_type_stackable',
  ],
  15463 => 
  [
    'item_id' => 15463,
    'icon' => 'event_halloween_pumpkin_i00',
    'name' => 'Small Halloween Pumpkin',
    'additionalname' => 'Event',
    'description' => 'Small Halloween Pumpkin. Double-click and you can obtain 1 bonus item with a certain chance.',
    'is_trade' => 0,
    'is_drop' => 0,
    'is_destruct' => 1,
    'crystal_type' => 'none',
    'consume_type' => 'consume_type_stackable',
  ],
  15464 => 
  [
    'item_id' => 15464,
    'icon' => 'ev_golden_jack0_mask_i00',
    'name' => 'Golden Jack O\'Lantern Mask',
    'additionalname' => '7-day',
    'description' => 'Golden Jack O\'Lantern Mask. Shines brightly. Cooldown is 23 hour.',
    'is_trade' => 0,
    'is_drop' => 0,
    'is_destruct' => 1,
    'crystal_type' => 'none',
    'consume_type' => 'consume_type_normal',
  ],
  15465 => 
  [
    'item_id' => 15465,
    'icon' => 'etc_pi_gift_box_i04',
    'name' => 'Halloween Nectar Pumpkin Pack (Event]',
    'additionalname' => 'Event',
    'description' => 'Halloween Nectar Pumpkin Pack. Contains 1 Halloween nectar pumpkin.',
    'is_trade' => 0,
    'is_drop' => 0,
    'is_destruct' => 1,
    'crystal_type' => 'none',
    'consume_type' => 'consume_type_stackable',
  ],
  15466 => 
  [
    'item_id' => 15466,
    'icon' => 'etc_pi_gift_box_i04',
    'name' => 'Halloween King Pumpkin Pack (Event]',
    'additionalname' => 'Event',
    'description' => 'Halloween King Pumpkin Pack. Contains 1 Halloween king pumpkin.',
    'is_trade' => 0,
    'is_drop' => 0,
    'is_destruct' => 1,
    'crystal_type' => 'none',
    'consume_type' => 'consume_type_stackable',
  ],
  15467 => 
  [
    'item_id' => 15467,
    'icon' => 'event_halloween_pumpkin_i00',
    'name' => 'Halloween Nectar Pumpkin (Event]',
    'additionalname' => 'Event',
    'description' => 'Halloween Nectar Pumpkin. With a certain chance, can obtain a Vitality replenishing drink or a feather of blessing and 1 small Halloween pumpkin.',
    'is_trade' => 1,
    'is_drop' => 0,
    'is_destruct' => 1,
    'crystal_type' => 'none',
    'consume_type' => 'consume_type_normal',
  ],
  15468 => 
  [
    'item_id' => 15468,
    'icon' => 'event_halloween_king_pumpkini00',
    'name' => 'Halloween King Pumpkin (Event]',
    'additionalname' => 'Event',
    'description' => 'Halloween King Pumpkin. Contains 6 Halloween nectar pumpkins and a Golden Jack O\'Lantern Mask (7 day].',
    'is_trade' => 1,
    'is_drop' => 0,
    'is_destruct' => 1,
    'crystal_type' => 'none',
    'consume_type' => 'consume_type_stackable',
  ],
  15469 => 
  [
    'item_id' => 15469,
    'icon' => 'etc_freezing_core_i00',
    'name' => 'Frozen Core',
    'additionalname' => '',
    'description' => 'Magic stone that temporarily neutralizes Freya\'s powerful magic',
    'is_trade' => 0,
    'is_drop' => 0,
    'is_destruct' => 1,
    'crystal_type' => 'none',
    'consume_type' => 'consume_type_normal',
  ],
  15470 => 
  [
    'item_id' => 15470,
    'icon' => 'etc_black_freezing_core_i00',
    'name' => 'Black Frozen Core',
    'additionalname' => '',
    'description' => 'Magic stone that temporarily neutralizes Freya\'s powerful magic',
    'is_trade' => 0,
    'is_drop' => 0,
    'is_destruct' => 1,
    'crystal_type' => 'none',
    'consume_type' => 'consume_type_stackable',
  ],
  15471 => 
  [
    'item_id' => 15471,
    'icon' => 'event_halloween_king_pumpkin_i03',
    'name' => 'Invisible Weapon for Freya',
    'additionalname' => '',
    'description' => '',
    'is_trade' => 0,
    'is_drop' => 0,
    'is_destruct' => 0,
    'crystal_type' => 'none',
    'consume_type' => 'consume_type_normal',
  ],
  15472 => 
  [
    'item_id' => 15472,
    'icon' => 'etc_sealed_mystery_sword_i00',
    'name' => 'Sealed Divine Sword',
    'additionalname' => '',
    'description' => 'Sacred sword that can neutralize Freya\'s power. Cannot use it directly due to some unknown M. Atk.',
    'is_trade' => 0,
    'is_drop' => 0,
    'is_destruct' => 0,
    'crystal_type' => 'none',
    'consume_type' => 'consume_type_normal',
  ],
  15473 => 
  [
    'item_id' => 15473,
    'icon' => 'etc_training_whip_i00',
    'name' => 'Beast Handler\'s Whip',
    'additionalname' => '',
    'description' => 'Obtained from Tunatun on the Beast Farm, this whip will enable the bearer to control tamed pets. Must be equipped to use.',
    'is_trade' => 0,
    'is_drop' => 0,
    'is_destruct' => 1,
    'crystal_type' => 'none',
    'consume_type' => 'consume_type_normal',
  ],
  15474 => 
  [
    'item_id' => 15474,
    'icon' => 'etc_golden_spice_new_i00',
    'name' => 'Golden Spice',
    'additionalname' => '',
    'description' => 'Feed used to tame baby animals on the Beast Farm. Using this feed will allow the monster to drop Adena and/or items, but will give less XP',
    'is_trade' => 1,
    'is_drop' => 1,
    'is_destruct' => 1,
    'crystal_type' => 'none',
    'consume_type' => 'consume_type_stackable',
  ],
  15475 => 
  [
    'item_id' => 15475,
    'icon' => 'etc_crystal_spice_new_i00',
    'name' => 'Crystal Spice',
    'additionalname' => '',
    'description' => 'Feed used to tame baby animals on the Beast Farm. This feed will cause the monster to give more XP, but no Adena or items.',
    'is_trade' => 1,
    'is_drop' => 1,
    'is_destruct' => 1,
    'crystal_type' => 'none',
    'consume_type' => 'consume_type_stackable',
  ],
  15476 => 
  [
    'item_id' => 15476,
    'icon' => 'etc_golden_spice_blessed_i00',
    'name' => 'Blessed Golden Spice',
    'additionalname' => '',
    'description' => 'Better quality feed that has a chance to tame animals on the Beast Farm with just one application.',
    'is_trade' => 0,
    'is_drop' => 0,
    'is_destruct' => 1,
    'crystal_type' => 'none',
    'consume_type' => 'consume_type_stackable',
  ],
  15477 => 
  [
    'item_id' => 15477,
    'icon' => 'etc_crystal_spice_blessed_i00',
    'name' => 'Blessed Crystal Spice',
    'additionalname' => '',
    'description' => 'Better quality feed that has a chance to tame animals on the Beast Farm with just one application.',
    'is_trade' => 0,
    'is_drop' => 0,
    'is_destruct' => 1,
    'crystal_type' => 'none',
    'consume_type' => 'consume_type_stackable',
  ],
  15478 => 
  [
    'item_id' => 15478,
    'icon' => 'etc_golden_spice_s_i00',
    'name' => 'Golden Spice (S-grade]',
    'additionalname' => '',
    'description' => 'Better quality feed that has a chance to turn Beast Farm babies into a fully grown pets with just one application. Using this feed will allow the monster to drop Adena and/or items, but will give less XP',
    'is_trade' => 0,
    'is_drop' => 0,
    'is_destruct' => 1,
    'crystal_type' => 'none',
    'consume_type' => 'consume_type_stackable',
  ],
  15479 => 
  [
    'item_id' => 15479,
    'icon' => 'etc_crystal_spice_s_i00',
    'name' => 'Crystal Spice (S-grade]',
    'additionalname' => '',
    'description' => 'Better quality feed that has a chance to turn Beast Farm babies into a fully grown pets with just one application. This feed causes the monster to give more XP, but no Adena or items.',
    'is_trade' => 0,
    'is_drop' => 0,
    'is_destruct' => 1,
    'crystal_type' => 'none',
    'consume_type' => 'consume_type_stackable',
  ],
  15480 => 
  [
    'item_id' => 15480,
    'icon' => 'event_halloween_king_pumpkin_i12',
    'name' => 'Old Golden Spice',
    'additionalname' => '',
    'description' => 'Old and unusable Beast Farm Feed',
    'is_trade' => 1,
    'is_drop' => 1,
    'is_destruct' => 1,
    'crystal_type' => 'none',
    'consume_type' => 'consume_type_stackable',
  ],
  15481 => 
  [
    'item_id' => 15481,
    'icon' => 'event_halloween_king_pumpkin_i13',
    'name' => 'Old Crystal Spice',
    'additionalname' => '',
    'description' => 'Old and unusable Beast Farm Feed',
    'is_trade' => 1,
    'is_drop' => 1,
    'is_destruct' => 1,
    'crystal_type' => 'none',
    'consume_type' => 'consume_type_stackable',
  ],
  15482 => 
  [
    'item_id' => 15482,
    'icon' => 'etc_golden_spice_comp_i00',
    'name' => 'Golden Spice Crate',
    'additionalname' => '',
    'description' => 'This box hold up to 50 Golden Spices. When converted, there is also a chance that Special Feed will be received.',
    'is_trade' => 1,
    'is_drop' => 1,
    'is_destruct' => 1,
    'crystal_type' => 'none',
    'consume_type' => 'consume_type_stackable',
  ],
  15483 => 
  [
    'item_id' => 15483,
    'icon' => 'etc_crystal_spice_comp_i00',
    'name' => 'Crystal Spice Compressed Pack',
    'additionalname' => '',
    'description' => 'Small pack with a compressed Crystal Spice. When you use it, it changes into a 50 Crystal Spices. Special Feed may also come out.',
    'is_trade' => 1,
    'is_drop' => 1,
    'is_destruct' => 1,
    'crystal_type' => 'none',
    'consume_type' => 'consume_type_stackable',
  ],
  15484 => 
  [
    'item_id' => 15484,
    'icon' => 'accessory_highangel_circlet_i00',
    'name' => 'Archangel Circlet',
    'additionalname' => '',
    'description' => 'High-level Angel Circlet. Uses 2 hair accessory slots. Blessed Escape skill can be used.',
    'is_trade' => 1,
    'is_drop' => 1,
    'is_destruct' => 1,
    'crystal_type' => 'none',
    'consume_type' => 'consume_type_normal',
  ],
  15485 => 
  [
    'item_id' => 15485,
    'icon' => 'etc_torchlight_i00',
    'name' => 'Torch',
    'additionalname' => '',
    'description' => 'Can be used to light a fire.',
    'is_trade' => 0,
    'is_drop' => 0,
    'is_destruct' => 1,
    'crystal_type' => 'none',
    'consume_type' => 'consume_type_normal',
  ],
  15486 => 
  [
    'item_id' => 15486,
    'icon' => 'etc_a_broken_piece_of_soul_stone_i00',
    'name' => 'Soul Stone Fragment',
    'additionalname' => '',
    'description' => 'Energy from the Seed of Annihilation resides within these Soul Stone Fragments. Can be used at Special Product Broker Kirklan.',
    'is_trade' => 1,
    'is_drop' => 1,
    'is_destruct' => 1,
    'crystal_type' => 'none',
    'consume_type' => 'consume_type_stackable',
  ],
  15487 => 
  [
    'item_id' => 15487,
    'icon' => 'etc_machine_for_marguene_i00',
    'name' => 'Maguen Plasma Collector',
    'additionalname' => '',
    'description' => 'This device is used to collect plasma from the Wild Maguen that inhabit the Seed of Annihilation. Under the right circumstances, plasma collection allows you to obtain a pet Maguen.',
    'is_trade' => 0,
    'is_drop' => 0,
    'is_destruct' => 1,
    'crystal_type' => 'none',
    'consume_type' => 'consume_type_normal',
  ],
  15488 => 
  [
    'item_id' => 15488,
    'icon' => 'etc_marguene_pet_collar_i00',
    'name' => 'Maguen Pet Collar',
    'additionalname' => '',
    'description' => 'Necklace that summons a Maguen. The summoned Maguen can eat wolf-type feed, and Takes a part of the XP gained by the Pet master.',
    'is_trade' => 0,
    'is_drop' => 0,
    'is_destruct' => 1,
    'crystal_type' => 'none',
    'consume_type' => 'consume_type_normal',
  ],
  15489 => 
  [
    'item_id' => 15489,
    'icon' => 'etc_elite_marguene_pet_collar_i00',
    'name' => 'Elite Maguen Pet Collar',
    'additionalname' => '',
    'description' => 'Necklace that summons an Elite Maguen. The summoned Maguen can eat wolf-type feed, and Takes a part of the XP gained by the Pet master.',
    'is_trade' => 0,
    'is_drop' => 0,
    'is_destruct' => 1,
    'crystal_type' => 'none',
    'consume_type' => 'consume_type_normal',
  ],
  15490 => 
  [
    'item_id' => 15490,
    'icon' => 'etc_marguene_collection_box_i00',
    'name' => 'Maguen Collection Box',
    'additionalname' => '',
    'description' => 'Its contents are a mystery. The only way to find out what is inside is to open it.',
    'is_trade' => 0,
    'is_drop' => 0,
    'is_destruct' => 1,
    'crystal_type' => 'none',
    'consume_type' => 'consume_type_stackable',
  ],
  15491 => 
  [
    'item_id' => 15491,
    'icon' => 'etc_elite_marguene_collection_box_i00',
    'name' => 'Elite Maguen Collection Box',
    'additionalname' => '',
    'description' => 'Its contents are a mystery. The only way to find out what is inside is to open it.',
    'is_trade' => 0,
    'is_drop' => 0,
    'is_destruct' => 1,
    'crystal_type' => 'none',
    'consume_type' => 'consume_type_stackable',
  ],
  15492 => 
  [
    'item_id' => 15492,
    'icon' => 'etc_salmon_soup_i00',
    'name' => 'Sel Mahum Salmon Porridge',
    'additionalname' => '',
    'description' => 'Sel Mahum salmon porridge. Smells better than expected… but not by much.',
    'is_trade' => 1,
    'is_drop' => 1,
    'is_destruct' => 1,
    'crystal_type' => 'none',
    'consume_type' => 'consume_type_stackable',
  ],
  15493 => 
  [
    'item_id' => 15493,
    'icon' => 'etc_pouch_yellow_i00',
    'name' => 'Fantasy Mushroom Spores',
    'additionalname' => '',
    'description' => 'Pouch containing the spores of Fantasy Mushrooms, which grow in the Plains of the Lizardmen. Detailed information can be obtained from Investigator Sally on the Plains of the Lizardmen.',
    'is_trade' => 0,
    'is_drop' => 0,
    'is_destruct' => 1,
    'crystal_type' => 'none',
    'consume_type' => 'consume_type_stackable',
  ],
  15494 => 
  [
    'item_id' => 15494,
    'icon' => 'etc_pouch_gray_i00',
    'name' => 'Sticky Mushroom\'s Spores',
    'additionalname' => '',
    'description' => 'Pouch containing the spores of Sticky Mushrooms, which grow in the Plains of the Lizardmen. Detailed information can be obtained from Investigator Sally on the Plains of the Lizardmen.',
    'is_trade' => 0,
    'is_drop' => 0,
    'is_destruct' => 1,
    'crystal_type' => 'none',
    'consume_type' => 'consume_type_stackable',
  ],
  15495 => 
  [
    'item_id' => 15495,
    'icon' => 'etc_leaf_blue_i00',
    'name' => 'Vitality Leaf',
    'additionalname' => '',
    'description' => 'Leaf of the Vitality Plant, which grows in the Plains of the Lizardmen. Detailed information can be obtained from Investigator Sally on the Plains of the Lizardmen.',
    'is_trade' => 0,
    'is_drop' => 0,
    'is_destruct' => 1,
    'crystal_type' => 'none',
    'consume_type' => 'consume_type_stackable',
  ],
  15496 => 
  [
    'item_id' => 15496,
    'icon' => 'etc_paper_white_i00',
    'name' => 'Seer Ugoros Pass',
    'additionalname' => '',
    'description' => 'Document from Investigator Johnny in the Plains of the Lizardmen that verifies you possess the required skills. It indicates that you have the right to go and see Tanta Lizardman Seer Ugoros. Show it to Gatekeeper Batracos near the Plains of the Lizardmen.',
    'is_trade' => 0,
    'is_drop' => 0,
    'is_destruct' => 1,
    'crystal_type' => 'none',
    'consume_type' => 'consume_type_stackable',
  ],
  15497 => 
  [
    'item_id' => 15497,
    'icon' => 'etc_godad_fish_scale_i00',
    'name' => 'High-grade Lizard Scale',
    'additionalname' => '',
    'description' => 'The highest-quality Lizardman Scale without any blemishes obtained after defeating Tanta Lizardmen Seer Ugoros. Take it to Researcher Ankumi on the Plains of the Lizardmen.',
    'is_trade' => 0,
    'is_drop' => 0,
    'is_destruct' => 1,
    'crystal_type' => 'none',
    'consume_type' => 'consume_type_stackable',
  ],
  15498 => 
  [
    'item_id' => 15498,
    'icon' => 'etc_innadrile_fish_scale_i00',
    'name' => 'High-quality Lizardmen Scale',
    'additionalname' => '',
    'description' => 'The medium-quality Lizardman Scale obtained after defeating Tanta Lizardmen Seer Ugoros. Take it to Researcher Ankumi on the Plains of the Lizardmen.',
    'is_trade' => 0,
    'is_drop' => 0,
    'is_destruct' => 1,
    'crystal_type' => 'none',
    'consume_type' => 'consume_type_stackable',
  ],
  15499 => 
  [
    'item_id' => 15499,
    'icon' => 'etc_dragons_blood_i04',
    'name' => 'Vial of Tanta Blood',
    'additionalname' => '',
    'description' => 'Vial containing the blood of Tanta Lizardmen. Take it to Investigator Laki on the Plains of the Lizardmen.',
    'is_trade' => 0,
    'is_drop' => 0,
    'is_destruct' => 1,
    'crystal_type' => 'none',
    'consume_type' => 'consume_type_stackable',
  ],
];