<?php return [
  15400 => 
  [
    'item_id' => 15400,
    'icon' => 'event_energy_belt_i00',
    'name' => 'Vitality Belt (Event]',
    'additionalname' => '60-day',
    'description' => 'Vitality Belt. Can be enchanted with Scroll: Enchant Vitality Belt. When enchanted, increases the duration of Vitality Maintenance effect and decreases its cooldown. ',
    'is_trade' => 0,
    'is_drop' => 0,
    'is_destruct' => 0,
    'crystal_type' => 'none',
    'consume_type' => 'consume_type_normal',
  ],
  15401 => 
  [
    'item_id' => 15401,
    'icon' => 'event_energy_belt_i00',
    'name' => 'Vitality Belt (Event]',
    'additionalname' => '90-day',
    'description' => 'Vitality Belt. Can be enchanted with Scroll: Enchant Vitality Belt. When enchanted, increases the duration of Vitality Maintenance effect and decreases its cooldown. ',
    'is_trade' => 0,
    'is_drop' => 0,
    'is_destruct' => 0,
    'crystal_type' => 'none',
    'consume_type' => 'consume_type_normal',
  ],
  15402 => 
  [
    'item_id' => 15402,
    'icon' => 'event_energy_belt_i00',
    'name' => 'Vitality Belt (Event]',
    'additionalname' => 'Permanent',
    'description' => 'Vitality Belt. Can be enchanted with Scroll: Enchant Vitality Belt. When enchanted, increases the duration of Vitality Maintenance effect and decreases its cooldown. ',
    'is_trade' => 0,
    'is_drop' => 0,
    'is_destruct' => 1,
    'crystal_type' => 'none',
    'consume_type' => 'consume_type_normal',
  ],
  15403 => 
  [
    'item_id' => 15403,
    'icon' => 'weapon_berserker_blade_i01',
    'name' => 'PA - Berserker Blade',
    'additionalname' => 'PA',
    'description' => 'Berserker Blade, upgrade options are limited. <Special properties> Critical Rate +73. Time-limited. Cannot be crystallized. Can only be enchanted.',
    'is_trade' => 0,
    'is_drop' => 0,
    'is_destruct' => 1,
    'crystal_type' => 'c',
    'consume_type' => 'consume_type_normal',
  ],
  15404 => 
  [
    'item_id' => 15404,
    'icon' => 'event_six_party_box_i00',
    'name' => 'Anniversary Party Gift Box (2003]',
    'additionalname' => 'Event',
    'description' => 'Double-click to obtain Anniversary Party Cube (30-day].',
    'is_trade' => 0,
    'is_drop' => 0,
    'is_destruct' => 1,
    'crystal_type' => 'crystal_free',
    'consume_type' => 'consume_type_stackable',
  ],
  15405 => 
  [
    'item_id' => 15405,
    'icon' => 'event_six_party_box_i00',
    'name' => 'Anniversary Party Gift Box (2004]',
    'additionalname' => 'Event',
    'description' => 'Double-click to obtain Anniversary Party Cube (25-day].',
    'is_trade' => 0,
    'is_drop' => 0,
    'is_destruct' => 1,
    'crystal_type' => 'crystal_free',
    'consume_type' => 'consume_type_stackable',
  ],
  15406 => 
  [
    'item_id' => 15406,
    'icon' => 'event_six_party_box_i00',
    'name' => 'Anniversary Party Gift Box (2005]',
    'additionalname' => 'Event',
    'description' => 'Double-click to obtain Anniversary Party Cube (20-day].',
    'is_trade' => 0,
    'is_drop' => 0,
    'is_destruct' => 1,
    'crystal_type' => 'crystal_free',
    'consume_type' => 'consume_type_stackable',
  ],
  15407 => 
  [
    'item_id' => 15407,
    'icon' => 'event_six_party_box_i00',
    'name' => 'Anniversary Party Gift Box (2006]',
    'additionalname' => 'Event',
    'description' => 'Double-click to obtain Anniversary Party Cube (15-day].',
    'is_trade' => 0,
    'is_drop' => 0,
    'is_destruct' => 1,
    'crystal_type' => 'crystal_free',
    'consume_type' => 'consume_type_stackable',
  ],
  15408 => 
  [
    'item_id' => 15408,
    'icon' => 'event_six_party_box_i00',
    'name' => 'Anniversary Party Gift Box (2007]',
    'additionalname' => 'Event',
    'description' => 'Double-click to obtain Anniversary Party Cube (10-day].',
    'is_trade' => 0,
    'is_drop' => 0,
    'is_destruct' => 1,
    'crystal_type' => 'crystal_free',
    'consume_type' => 'consume_type_stackable',
  ],
  15409 => 
  [
    'item_id' => 15409,
    'icon' => 'event_six_party_box_i00',
    'name' => 'Anniversary Party Gift Box (2008]',
    'additionalname' => 'Event',
    'description' => 'Double-click to obtain Anniversary Party Cube (5-day]. ',
    'is_trade' => 0,
    'is_drop' => 0,
    'is_destruct' => 1,
    'crystal_type' => 'crystal_free',
    'consume_type' => 'consume_type_stackable',
  ],
  15410 => 
  [
    'item_id' => 15410,
    'icon' => 'event_six_party_box_i00',
    'name' => 'Anniversary Party Gift Box (2009]',
    'additionalname' => 'Event',
    'description' => 'Double-click to obtain Anniversary Party Cube (3-day]. ',
    'is_trade' => 0,
    'is_drop' => 0,
    'is_destruct' => 1,
    'crystal_type' => 'crystal_free',
    'consume_type' => 'consume_type_stackable',
  ],
  15411 => 
  [
    'item_id' => 15411,
    'icon' => 'event_six_party_box_i00',
    'name' => 'Anniversary Party Gift Set (2003]',
    'additionalname' => 'Event',
    'description' => 'Heros Treasure Chest. Double-click to obtain Anniversary Party Cube (30-day].',
    'is_trade' => 0,
    'is_drop' => 0,
    'is_destruct' => 1,
    'crystal_type' => 'crystal_free',
    'consume_type' => 'consume_type_stackable',
  ],
  15412 => 
  [
    'item_id' => 15412,
    'icon' => 'event_six_party_box_i00',
    'name' => 'Anniversary Party Gift Set (2004]',
    'additionalname' => 'Event',
    'description' => 'Heros Treasure Chest. Double-click to obtain Anniversary Party Cube (25-day]. ',
    'is_trade' => 0,
    'is_drop' => 0,
    'is_destruct' => 1,
    'crystal_type' => 'crystal_free',
    'consume_type' => 'consume_type_stackable',
  ],
  15413 => 
  [
    'item_id' => 15413,
    'icon' => 'event_six_party_box_i00',
    'name' => 'Anniversary Party Gift Set (2005]',
    'additionalname' => 'Event',
    'description' => 'Heros Treasure Chest. Double-click to obtain Anniversary Party Cube (20-day]. ',
    'is_trade' => 0,
    'is_drop' => 0,
    'is_destruct' => 1,
    'crystal_type' => 'crystal_free',
    'consume_type' => 'consume_type_stackable',
  ],
  15414 => 
  [
    'item_id' => 15414,
    'icon' => 'event_six_party_box_i00',
    'name' => 'Anniversary Party Gift Set (2006]',
    'additionalname' => 'Event',
    'description' => 'Heros Treasure Chest. Double-click to obtain Anniversary Party Cube (15-day].',
    'is_trade' => 0,
    'is_drop' => 0,
    'is_destruct' => 1,
    'crystal_type' => 'crystal_free',
    'consume_type' => 'consume_type_stackable',
  ],
  15415 => 
  [
    'item_id' => 15415,
    'icon' => 'event_six_party_box_i00',
    'name' => 'Anniversary Party Gift Set (2007]',
    'additionalname' => 'Event',
    'description' => 'Heros Treasure Chest. Double-click to obtain Anniversary Party Cube (10-day]. ',
    'is_trade' => 0,
    'is_drop' => 0,
    'is_destruct' => 1,
    'crystal_type' => 'crystal_free',
    'consume_type' => 'consume_type_stackable',
  ],
  15416 => 
  [
    'item_id' => 15416,
    'icon' => 'event_six_party_box_i00',
    'name' => 'Anniversary Party Gift Set (2008]',
    'additionalname' => 'Event',
    'description' => 'Heros Treasure Chest. Double-click to obtain Anniversary Party Cube (5-day]. ',
    'is_trade' => 0,
    'is_drop' => 0,
    'is_destruct' => 1,
    'crystal_type' => 'crystal_free',
    'consume_type' => 'consume_type_stackable',
  ],
  15417 => 
  [
    'item_id' => 15417,
    'icon' => 'event_six_party_box_i00',
    'name' => 'Anniversary Party Gift Set (2009]',
    'additionalname' => 'Event',
    'description' => 'Heros Treasure Chest. Double-click to obtain Anniversary Party Cube (3-day]. ',
    'is_trade' => 0,
    'is_drop' => 0,
    'is_destruct' => 1,
    'crystal_type' => 'crystal_free',
    'consume_type' => 'consume_type_stackable',
  ],
  15418 => 
  [
    'item_id' => 15418,
    'icon' => 'event_six_party_cube_i00',
    'name' => 'Anniversary Party Cube (Event]',
    'additionalname' => '30-day',
    'description' => 'Double-click to obtain a gift. What will you receive? That depends on how lucky you are. Can be used once per day. Cooldown: 23 h.',
    'is_trade' => 0,
    'is_drop' => 0,
    'is_destruct' => 0,
    'crystal_type' => 'crystal_free',
    'consume_type' => 'consume_type_normal',
  ],
  15419 => 
  [
    'item_id' => 15419,
    'icon' => 'event_six_party_cube_i00',
    'name' => 'Anniversary Party Cube (Event]',
    'additionalname' => '25-day',
    'description' => 'Double-click to obtain a gift. What will you receive? That depends on how lucky you are. Can be used once per day. Cooldown: 23 h.',
    'is_trade' => 0,
    'is_drop' => 0,
    'is_destruct' => 0,
    'crystal_type' => 'crystal_free',
    'consume_type' => 'consume_type_normal',
  ],
  15420 => 
  [
    'item_id' => 15420,
    'icon' => 'event_six_party_cube_i00',
    'name' => 'Anniversary Party Cube (Event]',
    'additionalname' => '20-day',
    'description' => 'Double-click to obtain a gift. What will you receive? That depends on how lucky you are. Can be used once per day. Cooldown: 23 h.',
    'is_trade' => 0,
    'is_drop' => 0,
    'is_destruct' => 0,
    'crystal_type' => 'crystal_free',
    'consume_type' => 'consume_type_normal',
  ],
  15421 => 
  [
    'item_id' => 15421,
    'icon' => 'event_six_party_cube_i00',
    'name' => 'Anniversary Party Cube (Event]',
    'additionalname' => '15-day',
    'description' => 'Double-click to obtain a gift. What will you receive? That depends on how lucky you are. Can be used once per day. Cooldown: 23 h.',
    'is_trade' => 0,
    'is_drop' => 0,
    'is_destruct' => 0,
    'crystal_type' => 'crystal_free',
    'consume_type' => 'consume_type_normal',
  ],
  15422 => 
  [
    'item_id' => 15422,
    'icon' => 'event_six_party_cube_i00',
    'name' => 'Anniversary Party Cube (Event]',
    'additionalname' => '10-day',
    'description' => 'Double-click to obtain a gift. What will you receive? That depends on how lucky you are. Can be used once per day. Cooldown: 23 h.',
    'is_trade' => 0,
    'is_drop' => 0,
    'is_destruct' => 0,
    'crystal_type' => 'crystal_free',
    'consume_type' => 'consume_type_normal',
  ],
  15423 => 
  [
    'item_id' => 15423,
    'icon' => 'event_six_party_cube_i00',
    'name' => 'Anniversary Party Cube (Event]',
    'additionalname' => '5-day',
    'description' => 'Double-click to obtain a gift. What will you receive? That depends on how lucky you are. Can be used once per day. Cooldown: 23 h.',
    'is_trade' => 0,
    'is_drop' => 0,
    'is_destruct' => 0,
    'crystal_type' => 'crystal_free',
    'consume_type' => 'consume_type_normal',
  ],
  15424 => 
  [
    'item_id' => 15424,
    'icon' => 'event_six_party_cube_i00',
    'name' => 'Anniversary Party Cube (Event]',
    'additionalname' => '3-day',
    'description' => 'Double-click to obtain a gift. What will you receive? That depends on how lucky you are. Can be used once per day. Cooldown: 23 h.',
    'is_trade' => 0,
    'is_drop' => 0,
    'is_destruct' => 0,
    'crystal_type' => 'crystal_free',
    'consume_type' => 'consume_type_normal',
  ],
  15425 => 
  [
    'item_id' => 15425,
    'icon' => 'event_hero_treasure_box_i00',
    'name' => 'Heros Treasure Chest',
    'additionalname' => 'Event',
    'description' => 'Double-click to obtain Package: Equipment Set (30-day], Pet Necklace Coupon and Heros Escape Point.',
    'is_trade' => 0,
    'is_drop' => 0,
    'is_destruct' => 1,
    'crystal_type' => 'crystal_free',
    'consume_type' => 'consume_type_normal',
  ],
  15426 => 
  [
    'item_id' => 15426,
    'icon' => 'etc_pccafe_point_i00',
    'name' => 'Heros Escape Point',
    'additionalname' => 'Event',
    'description' => 'Double-clicked to obtain 10,000 PA Points. Cooldown: 7 days.',
    'is_trade' => 0,
    'is_drop' => 0,
    'is_destruct' => 1,
    'crystal_type' => 'crystal_free',
    'consume_type' => 'consume_type_stackable',
  ],
  15427 => 
  [
    'item_id' => 15427,
    'icon' => 'event_six_party_cake_i00',
    'name' => 'Anniversary Party Cake',
    'additionalname' => 'Event',
    'description' => 'For 1 h., Vitality is recovered when acquiring XP. Cooldown is 12 h. Vitality item with limited usage.',
    'is_trade' => 0,
    'is_drop' => 0,
    'is_destruct' => 1,
    'crystal_type' => 'crystal_free',
    'consume_type' => 'consume_type_stackable',
  ],
  15428 => 
  [
    'item_id' => 15428,
    'icon' => 'event_six_party_earing_i00',
    'name' => 'Anniversary Party Earring (Event]',
    'additionalname' => '30-day',
    'description' => 'MP +31, Mental/ Shock Resistance +20%, Mental/ Shock Atk. Rate +20%. Enables Vampiric Rage effect. Effects of two identical earrings do not stack. Available for 30 d.',
    'is_trade' => 0,
    'is_drop' => 0,
    'is_destruct' => 0,
    'crystal_type' => 'a',
    'consume_type' => 'consume_type_normal',
  ],
  15429 => 
  [
    'item_id' => 15429,
    'icon' => 'event_energy_belt_i00',
    'name' => 'Anniversary Party Belt (Event]',
    'additionalname' => '7-day',
    'description' => 'Maintains the Vitality amount for 30 min. Cooldown: 23 h. Available for 7 d. Vitality item with limited usage.',
    'is_trade' => 0,
    'is_drop' => 0,
    'is_destruct' => 0,
    'crystal_type' => 'none',
    'consume_type' => 'consume_type_normal',
  ],
  15430 => 
  [
    'item_id' => 15430,
    'icon' => 'ev_hallowinday_candy_i00',
    'name' => 'Event - Revita-Pop',
    'additionalname' => 'Event',
    'description' => 'A sweet Halloween candy. Can be exchanged for Halloween Toy Box through Skuld.',
    'is_trade' => 1,
    'is_drop' => 1,
    'is_destruct' => 1,
    'crystal_type' => 'crystal_free',
    'consume_type' => 'consume_type_stackable',
  ],
  15431 => 
  [
    'item_id' => 15431,
    'icon' => 'ev_scroll_of_wooldie_i00',
    'name' => 'Scroll: Summon Urd - Event',
    'additionalname' => NULL,
    'description' => 'Summons Urd to play Jacks game. You cannot summon Urd if a pet is summoned or if the Halloween mask isnt equipped. You cannot play Jacks game if you are currently transformed!',
    'is_trade' => 1,
    'is_drop' => 1,
    'is_destruct' => 1,
    'crystal_type' => 'crystal_free',
    'consume_type' => 'consume_type_stackable',
  ],
  15432 => 
  [
    'item_id' => 15432,
    'icon' => 'ev_scroll_of_berdandi_i00',
    'name' => 'Scroll: Summon Verdandi - Event',
    'additionalname' => NULL,
    'description' => 'Summons Verdandi to play Jacks game. You cannot summon Verdandi if a pet is summoned or if the Halloween mask isnt equipped. You cannot play Jacks game if you are transformed!',
    'is_trade' => 1,
    'is_drop' => 1,
    'is_destruct' => 1,
    'crystal_type' => 'crystal_free',
    'consume_type' => 'consume_type_stackable',
  ],
  15433 => 
  [
    'item_id' => 15433,
    'icon' => 'ev_scroll_of_scooldie_i00',
    'name' => 'Scroll: Summon Skuld - Event',
    'additionalname' => NULL,
    'description' => 'Summons Skuld to train the Jacks Game. You cannot summon Skuld if you have a pet summoned or if Halloween Mask isnt equipped. You cannot play Jacks Game while transformed!',
    'is_trade' => 0,
    'is_drop' => 0,
    'is_destruct' => 1,
    'crystal_type' => 'crystal_free',
    'consume_type' => 'consume_type_stackable',
  ],
  15434 => 
  [
    'item_id' => 15434,
    'icon' => 'etc_box_of_adventure_1_i00',
    'name' => 'Halloween Toy Box',
    'additionalname' => NULL,
    'description' => 'Gives a chance to acquire one of Halloween masks.',
    'is_trade' => 0,
    'is_drop' => 0,
    'is_destruct' => 1,
    'crystal_type' => 'crystal_free',
    'consume_type' => 'consume_type_normal',
  ],
  15435 => 
  [
    'item_id' => 15435,
    'icon' => 'etc_box_of_adventure_1_i00',
    'name' => 'Shiny Halloween Toy Box',
    'additionalname' => NULL,
    'description' => 'Gives a chance to acquire one of Shiny Halloween masks.',
    'is_trade' => 0,
    'is_drop' => 0,
    'is_destruct' => 1,
    'crystal_type' => 'crystal_free',
    'consume_type' => 'consume_type_normal',
  ],
  15436 => 
  [
    'item_id' => 15436,
    'icon' => 'weapon_pumpkin_stick_i00',
    'name' => 'Halloween Transformation Stick',
    'additionalname' => '7-day',
    'description' => 'You can transform to Halloween Pumpkin. Requires a weapon slot. It is a Halloween event reward item.',
    'is_trade' => 0,
    'is_drop' => 0,
    'is_destruct' => 0,
    'crystal_type' => 'none',
    'consume_type' => 'consume_type_normal',
  ],
  15437 => 
  [
    'item_id' => 15437,
    'icon' => 'etc_pi_gift_box_i00',
    'name' => 'Transformation Scroll Pack',
    'additionalname' => NULL,
    'description' => 'A chance to get one of transformation scroll: Onyx Beast, Doom Wraith, Grail Apostle. ',
    'is_trade' => 0,
    'is_drop' => 0,
    'is_destruct' => 1,
    'crystal_type' => 'crystal_free',
    'consume_type' => 'consume_type_stackable',
  ],
  15438 => 
  [
    'item_id' => 15438,
    'icon' => 'etc_lesser_potion_blue_i00',
    'name' => 'Vitality Maintaining Potion (10-min.]',
    'additionalname' => NULL,
    'description' => 'Maintains Vitality for 10 min. Cooldown: 30 min.',
    'is_trade' => 0,
    'is_drop' => 0,
    'is_destruct' => 1,
    'crystal_type' => 'crystal_free',
    'consume_type' => 'consume_type_stackable',
  ],
  15439 => 
  [
    'item_id' => 15439,
    'icon' => 'etc_sp_scroll3_i00',
    'name' => 'Scroll: 1 SP',
    'additionalname' => NULL,
    'description' => 'SP +1.',
    'is_trade' => 1,
    'is_drop' => 1,
    'is_destruct' => 1,
    'crystal_type' => 'crystal_free',
    'consume_type' => 'consume_type_stackable',
  ],
  15440 => 
  [
    'item_id' => 15440,
    'icon' => 'etc_lesser_potion_scarlet_i00',
    'name' => 'Vitality Maintaining Potion (30-min.]',
    'additionalname' => NULL,
    'description' => 'Maintains the Vitality amount for 30 min. Cooldown: 60 min. Vitality item with limited usage.',
    'is_trade' => 0,
    'is_drop' => 0,
    'is_destruct' => 1,
    'crystal_type' => 'crystal_free',
    'consume_type' => 'consume_type_stackable',
  ],
  15441 => 
  [
    'item_id' => 15441,
    'icon' => 'ev_valakas_the_flame_i00',
    'name' => 'Red Flame Valakas Head Accessory',
    'additionalname' => NULL,
    'description' => 'Helm the color of blazing fire.',
    'is_trade' => 0,
    'is_drop' => 0,
    'is_destruct' => 1,
    'crystal_type' => 'none',
    'consume_type' => 'consume_type_normal',
  ],
  15442 => 
  [
    'item_id' => 15442,
    'icon' => 'ev_jack0_mask_i00',
    'name' => 'Jack OLantern Mask',
    'additionalname' => NULL,
    'description' => 'You can use the card skill necessary for playing Jacks game when equipped.',
    'is_trade' => 0,
    'is_drop' => 0,
    'is_destruct' => 1,
    'crystal_type' => 'none',
    'consume_type' => 'consume_type_normal',
  ],
  15443 => 
  [
    'item_id' => 15443,
    'icon' => 'br_frankenstein_mask_i00',
    'name' => 'Reanimated Corpse Mask',
    'additionalname' => NULL,
    'description' => 'Super Strong Giants Mask. You can use the card skill necessary for playing Jacks game when equipped. 4-hour. Cooldown is 1 h.',
    'is_trade' => 0,
    'is_drop' => 0,
    'is_destruct' => 1,
    'crystal_type' => 'none',
    'consume_type' => 'consume_type_normal',
  ],
  15444 => 
  [
    'item_id' => 15444,
    'icon' => 'ev_scream_mask_i00',
    'name' => 'Shriek Mask',
    'additionalname' => NULL,
    'description' => 'Shriek Mask. You can use the card skill necessary for playing Jacks game when equipped. 4-hour. Cooldown is 1 h.',
    'is_trade' => 0,
    'is_drop' => 0,
    'is_destruct' => 1,
    'crystal_type' => 'none',
    'consume_type' => 'consume_type_normal',
  ],
  15445 => 
  [
    'item_id' => 15445,
    'icon' => 'ev_doccabi_mask_i00',
    'name' => 'Red Devil Mask',
    'additionalname' => NULL,
    'description' => 'Red Devil Mask. You can use the card skill necessary for playing Jacks game when equipped. 4-hour. Cooldown is 1 h.',
    'is_trade' => 0,
    'is_drop' => 0,
    'is_destruct' => 1,
    'crystal_type' => 'none',
    'consume_type' => 'consume_type_normal',
  ],
  15446 => 
  [
    'item_id' => 15446,
    'icon' => 'ev_mummy_mask_i00',
    'name' => 'Mummy Mask',
    'additionalname' => NULL,
    'description' => 'Mummy Mask. You can use the card skill necessary for playing Jacks game when equipped. 4-hour. Cooldown: 1 h.',
    'is_trade' => 0,
    'is_drop' => 0,
    'is_destruct' => 1,
    'crystal_type' => 'none',
    'consume_type' => 'consume_type_normal',
  ],
  15447 => 
  [
    'item_id' => 15447,
    'icon' => 'ev_alien_mask_i00',
    'name' => 'Alien Mask',
    'additionalname' => NULL,
    'description' => 'Can use the card skill necessary for playing Jacks game when equipped. 4-hour. Cooldown is 1 h.',
    'is_trade' => 0,
    'is_drop' => 0,
    'is_destruct' => 1,
    'crystal_type' => 'none',
    'consume_type' => 'consume_type_normal',
  ],
  15448 => 
  [
    'item_id' => 15448,
    'icon' => 'ev_golden_jack0_mask_i00',
    'name' => 'Golden Pumpkin Head',
    'additionalname' => 'Permanent',
    'description' => 'Jack OLantern Mask made of gold. Shines brightly.',
    'is_trade' => 0,
    'is_drop' => 0,
    'is_destruct' => 1,
    'crystal_type' => 'none',
    'consume_type' => 'consume_type_normal',
  ],
  15449 => 
  [
    'item_id' => 15449,
    'icon' => 'ev_shiny_alien_mask_i00',
    'name' => 'Shiny Alien Mask',
    'additionalname' => NULL,
    'description' => 'Can use the card skill necessary for playing Jacks game when equipped. 4-hour. Cooldown is 1 h.',
    'is_trade' => 0,
    'is_drop' => 0,
    'is_destruct' => 1,
    'crystal_type' => 'none',
    'consume_type' => 'consume_type_normal',
  ],
  15450 => 
  [
    'item_id' => 15450,
    'icon' => 'ev_shiny_frankenstein_mask_i00',
    'name' => 'Shiny Reanimated Corpse Mask',
    'additionalname' => NULL,
    'description' => 'Shiny Reanimated Corpse Mask. You can use the card skill necessary for playing Jacks game when equipped. 4-hour. Cooldown is 2 h.',
    'is_trade' => 0,
    'is_drop' => 0,
    'is_destruct' => 1,
    'crystal_type' => 'none',
    'consume_type' => 'consume_type_normal',
  ],
  15451 => 
  [
    'item_id' => 15451,
    'icon' => 'ev_shiny_scream_mask_i00',
    'name' => 'Shiny Shriek Mask',
    'additionalname' => NULL,
    'description' => 'Shiny Shriek Mask. You can use the card skill necessary for playing Jacks game when equipped. 4-hour. Cooldown is 1 h.',
    'is_trade' => 0,
    'is_drop' => 0,
    'is_destruct' => 1,
    'crystal_type' => 'none',
    'consume_type' => 'consume_type_normal',
  ],
  15452 => 
  [
    'item_id' => 15452,
    'icon' => 'ev_shiny_doccabi_mask_i00',
    'name' => 'Shiny Red Devil Mask',
    'additionalname' => NULL,
    'description' => 'Shiny Red Devil Mask. You can use the card skill necessary for playing Jacks game when equipped. 4-hour. Cooldown is 1 h.',
    'is_trade' => 0,
    'is_drop' => 0,
    'is_destruct' => 1,
    'crystal_type' => 'none',
    'consume_type' => 'consume_type_normal',
  ],
  15453 => 
  [
    'item_id' => 15453,
    'icon' => 'ev_shiny_mummy_mask_i00',
    'name' => 'Shiny Mummy Mask',
    'additionalname' => NULL,
    'description' => 'Shiny Mummy Mask. You can use the card skill necessary for playing Jacks game when equipped. 4-hour. Cooldown is 1 h.',
    'is_trade' => 0,
    'is_drop' => 0,
    'is_destruct' => 1,
    'crystal_type' => 'none',
    'consume_type' => 'consume_type_normal',
  ],
  15454 => 
  [
    'item_id' => 15454,
    'icon' => 'etc_pi_gift_box_i04',
    'name' => 'Package: Shiny Alien Mask',
    'additionalname' => 'Event',
    'description' => 'Double-click to obtain Shiny Alien Mask.',
    'is_trade' => 0,
    'is_drop' => 0,
    'is_destruct' => 1,
    'crystal_type' => 'crystal_free',
    'consume_type' => 'consume_type_stackable',
  ],
  15455 => 
  [
    'item_id' => 15455,
    'icon' => 'etc_pi_gift_box_i04',
    'name' => 'Package: Shiny Reanimated Corpse Mask',
    'additionalname' => 'Event',
    'description' => 'Double-click to obtain Shiny Reanimated Corpse Mask.',
    'is_trade' => 0,
    'is_drop' => 0,
    'is_destruct' => 1,
    'crystal_type' => 'crystal_free',
    'consume_type' => 'consume_type_stackable',
  ],
  15456 => 
  [
    'item_id' => 15456,
    'icon' => 'etc_pi_gift_box_i04',
    'name' => 'Package: Shiny Shriek Mask',
    'additionalname' => 'Event',
    'description' => 'Double-click to obtain Shiny Shriek Mask.',
    'is_trade' => 0,
    'is_drop' => 0,
    'is_destruct' => 1,
    'crystal_type' => 'crystal_free',
    'consume_type' => 'consume_type_stackable',
  ],
  15457 => 
  [
    'item_id' => 15457,
    'icon' => 'etc_pi_gift_box_i04',
    'name' => 'Package: Shiny Red Devil Mask',
    'additionalname' => 'Event',
    'description' => 'Double-click to obtain Shiny Red Devil Mask.',
    'is_trade' => 0,
    'is_drop' => 0,
    'is_destruct' => 1,
    'crystal_type' => 'crystal_free',
    'consume_type' => 'consume_type_stackable',
  ],
  15458 => 
  [
    'item_id' => 15458,
    'icon' => 'etc_pi_gift_box_i04',
    'name' => 'Package: Shiny Mummy Mask',
    'additionalname' => 'Event',
    'description' => 'Double-click to obtain Shiny Mummy Mask.',
    'is_trade' => 0,
    'is_drop' => 0,
    'is_destruct' => 1,
    'crystal_type' => 'crystal_free',
    'consume_type' => 'consume_type_stackable',
  ],
  15459 => 
  [
    'item_id' => 15459,
    'icon' => 'etc_pi_gift_box_i04',
    'name' => 'Package: Halloween Honey Pumpkin',
    'additionalname' => 'Event',
    'description' => 'Double-click to obtain Halloween Honey Pumpkin.',
    'is_trade' => 0,
    'is_drop' => 0,
    'is_destruct' => 1,
    'crystal_type' => 'crystal_free',
    'consume_type' => 'consume_type_stackable',
  ],
  15460 => 
  [
    'item_id' => 15460,
    'icon' => 'etc_pi_gift_box_i04',
    'name' => 'Package: Halloween King Pumpkin',
    'additionalname' => 'Event',
    'description' => 'Double-click to obtain Halloween King Pumpkin.',
    'is_trade' => 0,
    'is_drop' => 0,
    'is_destruct' => 1,
    'crystal_type' => 'crystal_free',
    'consume_type' => 'consume_type_stackable',
  ],
  15461 => 
  [
    'item_id' => 15461,
    'icon' => 'event_halloween_pumpkin_i00',
    'name' => 'Halloween Honey Pumpkin',
    'additionalname' => 'Event',
    'description' => 'Halloween Honey Pumpkin. Double-click to obtain Vitality Replenishing Potion, Feather of Blessing and Small Halloween Pumpkin.',
    'is_trade' => 1,
    'is_drop' => 0,
    'is_destruct' => 1,
    'crystal_type' => 'crystal_free',
    'consume_type' => 'consume_type_normal',
  ],
  15462 => 
  [
    'item_id' => 15462,
    'icon' => 'event_halloween_king_pumpkini00',
    'name' => 'Halloween King Pumpkin',
    'additionalname' => 'Event',
    'description' => 'Large Halloween Pumpkin. Double-click to obtain Halloween Honey Pumpkin (6 pcs.] and Golden Jack OLantern Mask (7-day].',
    'is_trade' => 1,
    'is_drop' => 0,
    'is_destruct' => 1,
    'crystal_type' => 'crystal_free',
    'consume_type' => 'consume_type_stackable',
  ],
  15463 => 
  [
    'item_id' => 15463,
    'icon' => 'event_halloween_pumpkin_i00',
    'name' => 'Small Halloween Pumpkin',
    'additionalname' => 'Event',
    'description' => 'Small Halloween Pumpkin. Double-click and you can obtain 1 bonus item with a certain chance.',
    'is_trade' => 0,
    'is_drop' => 0,
    'is_destruct' => 1,
    'crystal_type' => 'crystal_free',
    'consume_type' => 'consume_type_stackable',
  ],
  15464 => 
  [
    'item_id' => 15464,
    'icon' => 'ev_golden_jack0_mask_i00',
    'name' => 'Golden Pumpkin Head',
    'additionalname' => '7-day',
    'description' => 'Golden Jack OLantern Mask. Shines brightly. Cooldown is 23 h.',
    'is_trade' => 0,
    'is_drop' => 0,
    'is_destruct' => 1,
    'crystal_type' => 'none',
    'consume_type' => 'consume_type_normal',
  ],
  15465 => 
  [
    'item_id' => 15465,
    'icon' => 'etc_pi_gift_box_i04',
    'name' => 'Package: Halloween Honey Pumpkin - Event',
    'additionalname' => 'Event',
    'description' => 'Double-click to obtain Halloween Honey Pumpkin.',
    'is_trade' => 0,
    'is_drop' => 0,
    'is_destruct' => 1,
    'crystal_type' => 'crystal_free',
    'consume_type' => 'consume_type_stackable',
  ],
  15466 => 
  [
    'item_id' => 15466,
    'icon' => 'etc_pi_gift_box_i04',
    'name' => 'Package: Halloween King Pumpkin - Event',
    'additionalname' => 'Event',
    'description' => 'Double-click to obtain Halloween King Pumpkin.',
    'is_trade' => 0,
    'is_drop' => 0,
    'is_destruct' => 1,
    'crystal_type' => 'crystal_free',
    'consume_type' => 'consume_type_stackable',
  ],
  15467 => 
  [
    'item_id' => 15467,
    'icon' => 'event_halloween_pumpkin_i00',
    'name' => 'Halloween Honey Pumpkin - Event',
    'additionalname' => 'Event',
    'description' => 'Halloween Honey Pumpkin. Double-click to obtain Vitality Replenishing Potion, Feather of Blessing and Small Halloween Pumpkin.',
    'is_trade' => 1,
    'is_drop' => 0,
    'is_destruct' => 1,
    'crystal_type' => 'crystal_free',
    'consume_type' => 'consume_type_normal',
  ],
  15468 => 
  [
    'item_id' => 15468,
    'icon' => 'event_halloween_king_pumpkini00',
    'name' => 'Halloween King Pumpkin - Event',
    'additionalname' => 'Event',
    'description' => 'Large Halloween Pumpkin. Double-click to obtain Halloween Honey Pumpkin (6 pcs.] and Golden Jack OLantern Mask (7-day].',
    'is_trade' => 1,
    'is_drop' => 0,
    'is_destruct' => 1,
    'crystal_type' => 'crystal_free',
    'consume_type' => 'consume_type_stackable',
  ],
  15469 => 
  [
    'item_id' => 15469,
    'icon' => 'etc_freezing_core_i00',
    'name' => 'Frozen Core',
    'additionalname' => NULL,
    'description' => 'Magic stone that temporarily neutralizes Freyas powerful magic',
    'is_trade' => 0,
    'is_drop' => 0,
    'is_destruct' => 1,
    'crystal_type' => 'crystal_free',
    'consume_type' => 'consume_type_normal',
  ],
  15470 => 
  [
    'item_id' => 15470,
    'icon' => 'etc_black_freezing_core_i00',
    'name' => 'Black Frozen Core',
    'additionalname' => NULL,
    'description' => 'Magic stone that temporarily neutralizes Freyas powerful magic',
    'is_trade' => 0,
    'is_drop' => 0,
    'is_destruct' => 1,
    'crystal_type' => 'crystal_free',
    'consume_type' => 'consume_type_stackable',
  ],
  15471 => 
  [
    'item_id' => 15471,
    'icon' => 'event_halloween_king_pumpkin_i03',
    'name' => 'Invisible Weapon for Freya',
    'additionalname' => NULL,
    'description' => NULL,
    'is_trade' => 0,
    'is_drop' => 0,
    'is_destruct' => 0,
    'crystal_type' => 'none',
    'consume_type' => 'consume_type_normal',
  ],
  15472 => 
  [
    'item_id' => 15472,
    'icon' => 'etc_sealed_mystery_sword_i00',
    'name' => 'Sealed Divine Sword',
    'additionalname' => NULL,
    'description' => 'Sacred sword that can neutralize Freyas power. Cannot use it directly due to some unknown M. Atk.',
    'is_trade' => 0,
    'is_drop' => 0,
    'is_destruct' => 0,
    'crystal_type' => 'none',
    'consume_type' => 'consume_type_normal',
  ],
  15473 => 
  [
    'item_id' => 15473,
    'icon' => 'etc_training_whip_i00',
    'name' => 'Beast Handlers Whip',
    'additionalname' => NULL,
    'description' => 'Obtained from Tunatun on the Beast Farm, this whip will enable the bearer to control tamed pets. Must be equipped to use.',
    'is_trade' => 0,
    'is_drop' => 0,
    'is_destruct' => 1,
    'crystal_type' => 'none',
    'consume_type' => 'consume_type_normal',
  ],
  15474 => 
  [
    'item_id' => 15474,
    'icon' => 'etc_golden_spice_new_i00',
    'name' => 'Golden Spice',
    'additionalname' => NULL,
    'description' => 'Feed used to tame baby animals on the Beast Farm. Using this feed will allow the monster to drop Adena and/ or items, but will give less XP',
    'is_trade' => 1,
    'is_drop' => 1,
    'is_destruct' => 1,
    'crystal_type' => 'crystal_free',
    'consume_type' => 'consume_type_stackable',
  ],
  15475 => 
  [
    'item_id' => 15475,
    'icon' => 'etc_crystal_spice_new_i00',
    'name' => 'Crystal Spice',
    'additionalname' => NULL,
    'description' => 'Feed used to tame baby animals on the Beast Farm. This feed will cause the monster to give more XP, but no Adena or items.',
    'is_trade' => 1,
    'is_drop' => 1,
    'is_destruct' => 1,
    'crystal_type' => 'crystal_free',
    'consume_type' => 'consume_type_stackable',
  ],
  15476 => 
  [
    'item_id' => 15476,
    'icon' => 'etc_golden_spice_blessed_i00',
    'name' => 'Blessed Golden Spice',
    'additionalname' => NULL,
    'description' => 'Better quality feed that has a strong chance to tame animals on the Beast Farm. ',
    'is_trade' => 0,
    'is_drop' => 0,
    'is_destruct' => 1,
    'crystal_type' => 'crystal_free',
    'consume_type' => 'consume_type_stackable',
  ],
  15477 => 
  [
    'item_id' => 15477,
    'icon' => 'etc_crystal_spice_blessed_i00',
    'name' => 'Blessed Crystal Spice',
    'additionalname' => NULL,
    'description' => 'Better quality feed that has a strong chance to tame animals on the Beast Farm. ',
    'is_trade' => 0,
    'is_drop' => 0,
    'is_destruct' => 1,
    'crystal_type' => 'crystal_free',
    'consume_type' => 'consume_type_stackable',
  ],
  15478 => 
  [
    'item_id' => 15478,
    'icon' => 'etc_golden_spice_s_i00',
    'name' => 'S-grade Golden Spice',
    'additionalname' => NULL,
    'description' => 'Better quality feed that has a chance to turn Beast Farm babies into a fully grown pets with just one application. Using this feed will allow the monster to drop Adena and/ or items, but will give less XP',
    'is_trade' => 0,
    'is_drop' => 0,
    'is_destruct' => 1,
    'crystal_type' => 'crystal_free',
    'consume_type' => 'consume_type_stackable',
  ],
  15479 => 
  [
    'item_id' => 15479,
    'icon' => 'etc_crystal_spice_s_i00',
    'name' => 'S-grade Crystal Spice',
    'additionalname' => NULL,
    'description' => 'Better quality feed that has a chance to turn Beast Farm babies into a fully grown pets with just one application. This feed causes the monster to give more XP, but no Adena or items.',
    'is_trade' => 0,
    'is_drop' => 0,
    'is_destruct' => 1,
    'crystal_type' => 'crystal_free',
    'consume_type' => 'consume_type_stackable',
  ],
  15480 => 
  [
    'item_id' => 15480,
    'icon' => 'event_halloween_king_pumpkin_i12',
    'name' => 'Old Golden Spice',
    'additionalname' => NULL,
    'description' => 'Old and unusable Beast Farm Feed',
    'is_trade' => 1,
    'is_drop' => 1,
    'is_destruct' => 1,
    'crystal_type' => 'none',
    'consume_type' => 'consume_type_stackable',
  ],
  15481 => 
  [
    'item_id' => 15481,
    'icon' => 'event_halloween_king_pumpkin_i13',
    'name' => 'Old Crystal Spice',
    'additionalname' => NULL,
    'description' => 'Old and unusable Beast Farm Feed',
    'is_trade' => 1,
    'is_drop' => 1,
    'is_destruct' => 1,
    'crystal_type' => 'none',
    'consume_type' => 'consume_type_stackable',
  ],
  15482 => 
  [
    'item_id' => 15482,
    'icon' => 'etc_golden_spice_comp_i00',
    'name' => 'Compressed Package: Golden Spice',
    'additionalname' => NULL,
    'description' => 'Double-click to obtain Golden Spice (50 pcs.]. There is a chance to get better spice.',
    'is_trade' => 1,
    'is_drop' => 1,
    'is_destruct' => 1,
    'crystal_type' => 'crystal_free',
    'consume_type' => 'consume_type_stackable',
  ],
  15483 => 
  [
    'item_id' => 15483,
    'icon' => 'etc_crystal_spice_comp_i00',
    'name' => 'Compressed Package: Crystal Spice',
    'additionalname' => NULL,
    'description' => 'Double-click to obtain Crystal Spice (50 pcs.]. There is a chance to get better spice.',
    'is_trade' => 1,
    'is_drop' => 1,
    'is_destruct' => 1,
    'crystal_type' => 'crystal_free',
    'consume_type' => 'consume_type_stackable',
  ],
  15484 => 
  [
    'item_id' => 15484,
    'icon' => 'accessory_highangel_circlet_i00',
    'name' => 'Archangel Circlet',
    'additionalname' => NULL,
    'description' => 'An archangels circlet. Equipped in 2 head accessory slots. Enables Blessed Escape.',
    'is_trade' => 1,
    'is_drop' => 1,
    'is_destruct' => 1,
    'crystal_type' => 'none',
    'consume_type' => 'consume_type_normal',
  ],
  15485 => 
  [
    'item_id' => 15485,
    'icon' => 'etc_torchlight_i00',
    'name' => 'Torch',
    'additionalname' => NULL,
    'description' => 'Can be used to light a fire.',
    'is_trade' => 0,
    'is_drop' => 0,
    'is_destruct' => 1,
    'crystal_type' => 'none',
    'consume_type' => 'consume_type_normal',
  ],
  15486 => 
  [
    'item_id' => 15486,
    'icon' => 'etc_a_broken_piece_of_soul_stone_i00',
    'name' => 'Soul Stone Fragment',
    'additionalname' => NULL,
    'description' => 'Energy from the Seed of Annihilation resides within these Soul Stone Fragments. Can be used at Special Product Broker Kirklan.',
    'is_trade' => 1,
    'is_drop' => 1,
    'is_destruct' => 1,
    'crystal_type' => 'none',
    'consume_type' => 'consume_type_stackable',
  ],
  15487 => 
  [
    'item_id' => 15487,
    'icon' => 'etc_machine_for_marguene_i00',
    'name' => 'Maguen Plasma Collector',
    'additionalname' => NULL,
    'description' => 'This device is used to collect plasma from the Wild Maguen that inhabit the Seed of Annihilation. Under the right circumstances, plasma collection allows you to obtain a pet Maguen.',
    'is_trade' => 0,
    'is_drop' => 0,
    'is_destruct' => 1,
    'crystal_type' => 'none',
    'consume_type' => 'consume_type_normal',
  ],
  15488 => 
  [
    'item_id' => 15488,
    'icon' => 'etc_marguene_pet_collar_i00',
    'name' => 'Maguen Pet Collar',
    'additionalname' => NULL,
    'description' => 'Required for summoning Maguen - a pet that eats Wolf Food and takes a part of XP from its owner.',
    'is_trade' => 0,
    'is_drop' => 0,
    'is_destruct' => 1,
    'crystal_type' => 'none',
    'consume_type' => 'consume_type_normal',
  ],
  15489 => 
  [
    'item_id' => 15489,
    'icon' => 'etc_elite_marguene_pet_collar_i00',
    'name' => 'Elite Maguen Pet Collar',
    'additionalname' => NULL,
    'description' => 'Required for summoning Elite Maguen - a pet that eats Wolf Food and takes a part of XP from its owner.',
    'is_trade' => 0,
    'is_drop' => 0,
    'is_destruct' => 1,
    'crystal_type' => 'none',
    'consume_type' => 'consume_type_normal',
  ],
  15490 => 
  [
    'item_id' => 15490,
    'icon' => 'etc_marguene_collection_box_i00',
    'name' => 'Maguen Collection Box',
    'additionalname' => NULL,
    'description' => 'Its contents are a mystery. The only way to find out what is inside is to open it.',
    'is_trade' => 0,
    'is_drop' => 0,
    'is_destruct' => 1,
    'crystal_type' => 'none',
    'consume_type' => 'consume_type_stackable',
  ],
  15491 => 
  [
    'item_id' => 15491,
    'icon' => 'etc_elite_marguene_collection_box_i00',
    'name' => 'Elite Maguen Collection Box',
    'additionalname' => NULL,
    'description' => 'Its contents are a mystery. The only way to find out what is inside is to open it.',
    'is_trade' => 0,
    'is_drop' => 0,
    'is_destruct' => 1,
    'crystal_type' => 'none',
    'consume_type' => 'consume_type_stackable',
  ],
  15492 => 
  [
    'item_id' => 15492,
    'icon' => 'etc_salmon_soup_i00',
    'name' => 'Sel Mahums Salmon Porridge',
    'additionalname' => NULL,
    'description' => 'Sel Mahums favorite salmon porridge. Looks very tasty and smells even better.',
    'is_trade' => 1,
    'is_drop' => 1,
    'is_destruct' => 1,
    'crystal_type' => 'crystal_free',
    'consume_type' => 'consume_type_stackable',
  ],
  15493 => 
  [
    'item_id' => 15493,
    'icon' => 'etc_pouch_yellow_i00',
    'name' => 'Fantasy Mushrooms Spores',
    'additionalname' => NULL,
    'description' => 'Pouch containing the spores of Fantasy Mushrooms, which grow in the Plains of the Lizardmen. Detailed information can be obtained from Investigator Sally on the Plains of the Lizardmen.',
    'is_trade' => 0,
    'is_drop' => 0,
    'is_destruct' => 1,
    'crystal_type' => 'none',
    'consume_type' => 'consume_type_stackable',
  ],
  15494 => 
  [
    'item_id' => 15494,
    'icon' => 'etc_pouch_gray_i00',
    'name' => 'Sticky Mushrooms Spores',
    'additionalname' => NULL,
    'description' => 'Pouch containing the spores of Sticky Mushrooms, which grow in the Plains of the Lizardmen. Detailed information can be obtained from Investigator Sally on the Plains of the Lizardmen.',
    'is_trade' => 0,
    'is_drop' => 0,
    'is_destruct' => 1,
    'crystal_type' => 'none',
    'consume_type' => 'consume_type_stackable',
  ],
  15495 => 
  [
    'item_id' => 15495,
    'icon' => 'etc_leaf_blue_i00',
    'name' => 'Vitality Leaf',
    'additionalname' => NULL,
    'description' => 'Leaf of the Vitality Plant, which grows in the Plains of the Lizardmen. Detailed information can be obtained from Investigator Sally on the Plains of the Lizardmen.',
    'is_trade' => 0,
    'is_drop' => 0,
    'is_destruct' => 1,
    'crystal_type' => 'none',
    'consume_type' => 'consume_type_stackable',
  ],
  15496 => 
  [
    'item_id' => 15496,
    'icon' => 'etc_paper_white_i00',
    'name' => 'Seer Ugoros Pass',
    'additionalname' => NULL,
    'description' => 'Document from Investigator Johnny in the Plains of the Lizardmen that verifies you possess the required skills. It indicates that you have the right to go and see Tanta Lizardman Seer Ugoros. Show it to Gatekeeper Batracos near the Plains of the Lizardmen.',
    'is_trade' => 0,
    'is_drop' => 0,
    'is_destruct' => 1,
    'crystal_type' => 'none',
    'consume_type' => 'consume_type_stackable',
  ],
  15497 => 
  [
    'item_id' => 15497,
    'icon' => 'etc_godad_fish_scale_i00',
    'name' => 'High-grade Lizard Scale',
    'additionalname' => NULL,
    'description' => 'The highest-quality Lizardman Scale without any blemishes obtained after defeating Tanta Lizardmen Seer Ugoros. Take it to Researcher Ankumi on the Plains of the Lizardmen.',
    'is_trade' => 0,
    'is_drop' => 0,
    'is_destruct' => 1,
    'crystal_type' => 'none',
    'consume_type' => 'consume_type_stackable',
  ],
  15498 => 
  [
    'item_id' => 15498,
    'icon' => 'etc_innadrile_fish_scale_i00',
    'name' => 'High-quality Lizardmen Scale',
    'additionalname' => NULL,
    'description' => 'The medium-quality Lizardman Scale obtained after defeating Tanta Lizardmen Seer Ugoros. Take it to Researcher Ankumi on the Plains of the Lizardmen.',
    'is_trade' => 0,
    'is_drop' => 0,
    'is_destruct' => 1,
    'crystal_type' => 'none',
    'consume_type' => 'consume_type_stackable',
  ],
  15499 => 
  [
    'item_id' => 15499,
    'icon' => 'etc_dragons_blood_i04',
    'name' => 'Vial of Tanta Blood',
    'additionalname' => NULL,
    'description' => 'Vial containing the blood of Tanta Lizardmen. Take it to Investigator Laki on the Plains of the Lizardmen.',
    'is_trade' => 0,
    'is_drop' => 0,
    'is_destruct' => 1,
    'crystal_type' => 'none',
    'consume_type' => 'consume_type_stackable',
  ],
];