<?php return [
  15500 => 
  [
    'item_id' => 15500,
    'icon' => 'etc_spell_books_white_i00',
    'name' => 'Sel Mahum Diary',
    'additionalname' => '',
    'description' => 'Diary containing the daily life of the Sel Mahum. Take it back to Guard Stan of Oren Village.',
    'is_trade' => 0,
    'is_drop' => 0,
    'is_destruct' => 1,
    'crystal_type' => 'none',
    'consume_type' => 'consume_type_stackable',
  ],
  15501 => 
  [
    'item_id' => 15501,
    'icon' => 'etc_hidden_2nd_page_i00',
    'name' => 'Sel Mahum Cookbook Page',
    'additionalname' => '',
    'description' => 'Part of the cookbook used by the Sel Mahum Chef. Take it back to Guard Stan of Oren Village.',
    'is_trade' => 0,
    'is_drop' => 0,
    'is_destruct' => 1,
    'crystal_type' => 'none',
    'consume_type' => 'consume_type_stackable',
  ],
  15502 => 
  [
    'item_id' => 15502,
    'icon' => 'etc_spell_books_assistance_i00',
    'name' => 'Sel Mahum Cookbook',
    'additionalname' => '',
    'description' => 'Cookbook used by the Sel Mahum Chef. Take it back to Guard Stan of Oren Village.',
    'is_trade' => 0,
    'is_drop' => 0,
    'is_destruct' => 1,
    'crystal_type' => 'none',
    'consume_type' => 'consume_type_stackable',
  ],
  15503 => 
  [
    'item_id' => 15503,
    'icon' => 'etc_tuna_i00',
    'name' => 'Shiny Salmon',
    'additionalname' => '',
    'description' => 'Shiny and tantalizing salmon. Take it back to Guard Stan of Oren Village.',
    'is_trade' => 0,
    'is_drop' => 0,
    'is_destruct' => 1,
    'crystal_type' => 'none',
    'consume_type' => 'consume_type_stackable',
  ],
  15504 => 
  [
    'item_id' => 15504,
    'icon' => 'etc_tuna_i02',
    'name' => 'Grey Salmon',
    'additionalname' => '',
    'description' => 'Not so shiny but still OK-looking salmon. If you take it back to Guard Stan of Oren Village, he\'ll take care of everything else, right?',
    'is_trade' => 0,
    'is_drop' => 0,
    'is_destruct' => 1,
    'crystal_type' => 'none',
    'consume_type' => 'consume_type_stackable',
  ],
  15505 => 
  [
    'item_id' => 15505,
    'icon' => 'etc_tuna_i08',
    'name' => 'Sickly Salmon',
    'additionalname' => '',
    'description' => 'Scales are falling off and it doesn\'t look good at all. If you take it back to Guard Stan of Oren Village, he\'ll take care of everything else, right?',
    'is_trade' => 0,
    'is_drop' => 0,
    'is_destruct' => 1,
    'crystal_type' => 'none',
    'consume_type' => 'consume_type_stackable',
  ],
  15506 => 
  [
    'item_id' => 15506,
    'icon' => 'etc_bait_i00',
    'name' => 'Salmon Bait',
    'additionalname' => '',
    'description' => 'Lure used to catch salmon. You cannot catch salmon without it.',
    'is_trade' => 0,
    'is_drop' => 0,
    'is_destruct' => 1,
    'crystal_type' => 'none',
    'consume_type' => 'consume_type_stackable',
  ],
  15507 => 
  [
    'item_id' => 15507,
    'icon' => 'etc_codran_i06',
    'name' => 'Foul Fruit',
    'additionalname' => '',
    'description' => 'Horrible tasting fruit. If you put it in the salmon porridge, which is cooking on the fire at the Sel Mahum Training Grounds, you could ruin the dish.',
    'is_trade' => 0,
    'is_drop' => 0,
    'is_destruct' => 1,
    'crystal_type' => 'none',
    'consume_type' => 'consume_type_stackable',
  ],
  15508 => 
  [
    'item_id' => 15508,
    'icon' => 'etc_spellbook_gray_i00',
    'name' => 'Sel Mahum Training Diary',
    'additionalname' => '',
    'description' => 'Dairy containing detailed examples of the Sel Mahum training. Take it back to Guard Pinaps of Oren Village.',
    'is_trade' => 0,
    'is_drop' => 0,
    'is_destruct' => 1,
    'crystal_type' => 'none',
    'consume_type' => 'consume_type_stackable',
  ],
  15509 => 
  [
    'item_id' => 15509,
    'icon' => 'etc_plan_i00',
    'name' => 'Sel Mahum Training Timetable',
    'additionalname' => '',
    'description' => 'Paper containing the training schedule of the Sel Mahum. Take it back to Guard Pinaps of Oren Village.',
    'is_trade' => 0,
    'is_drop' => 0,
    'is_destruct' => 1,
    'crystal_type' => 'none',
    'consume_type' => 'consume_type_stackable',
  ],
  15510 => 
  [
    'item_id' => 15510,
    'icon' => 'etc_piece_of_paper_white_i00',
    'name' => 'Golem Corps Log',
    'additionalname' => '',
    'description' => 'Paper containing some logs for recognizing Golem Corps. Collect all needed logs.',
    'is_trade' => 0,
    'is_drop' => 0,
    'is_destruct' => 0,
    'crystal_type' => 'none',
    'consume_type' => 'consume_type_stackable',
  ],
  15511 => 
  [
    'item_id' => 15511,
    'icon' => 'etc_roll_of_paper_black_i00',
    'name' => 'Golem Corps Collection',
    'additionalname' => '',
    'description' => 'Bundle of papers containing all the logs for recognizing Golem Corps. Take it back to Collector Gutenhagen at Pavel Ruins.',
    'is_trade' => 0,
    'is_drop' => 0,
    'is_destruct' => 1,
    'crystal_type' => 'none',
    'consume_type' => 'consume_type_stackable',
  ],
  15512 => 
  [
    'item_id' => 15512,
    'icon' => 'etc_letter_white_i00',
    'name' => 'Seed of Annihilation Orders',
    'additionalname' => '',
    'description' => 'Kucereus\' Clan Outpost Commander Kbaldir\'s written orders. Go to the pier of the Seed of Annihilation and deliver it to his subordinate, Officer Klemis.',
    'is_trade' => 0,
    'is_drop' => 0,
    'is_destruct' => 1,
    'crystal_type' => 'none',
    'consume_type' => 'consume_type_stackable',
  ],
  15513 => 
  [
    'item_id' => 15513,
    'icon' => 'etc_ticket_blue_i00',
    'name' => 'Gracian Soldier Tag',
    'additionalname' => '',
    'description' => 'ID Tag of a Gracian soldier who was killed near the Seed of Annihilation. Let\'s take it to Officer Jakan who is stationed at the pier near the Seed of Annihilation.',
    'is_trade' => 0,
    'is_drop' => 0,
    'is_destruct' => 1,
    'crystal_type' => 'none',
    'consume_type' => 'consume_type_stackable',
  ],
  15514 => 
  [
    'item_id' => 15514,
    'icon' => 'etc_cp_potion_i00',
    'name' => 'Cold Resistance Potion',
    'additionalname' => '',
    'description' => 'Potion especially crafted from the Jinia Guild to protect the body from the cursed cold powers of the Ice Queen. Needed to rescue Kegor, who has fallen into a trouble.',
    'is_trade' => 0,
    'is_drop' => 0,
    'is_destruct' => 1,
    'crystal_type' => 'none',
    'consume_type' => 'consume_type_stackable',
  ],
  15515 => 
  [
    'item_id' => 15515,
    'icon' => 'etc_crystal_cave_crystal_i0',
    'name' => 'Seal Breaker - 5th Floor',
    'additionalname' => '',
    'description' => 'Seal Breaker needed to speak face to face with the Demon Prince on the 5th floor of the Tower of Infinitum in the Steel Citadel. It is destroyed after one use.',
    'is_trade' => 0,
    'is_drop' => 0,
    'is_destruct' => 1,
    'crystal_type' => 'none',
    'consume_type' => 'consume_type_stackable',
  ],
  15516 => 
  [
    'item_id' => 15516,
    'icon' => 'etc_crystal_cave_crystal_i00',
    'name' => 'Seal Breaker - 10th Floor',
    'additionalname' => '',
    'description' => 'Seal Breaker needed to speak face to face with Ranku on the 10th floor of the Tower of Infinitum in the Steel Citadel. It is destroyed after one use.',
    'is_trade' => 0,
    'is_drop' => 0,
    'is_destruct' => 1,
    'crystal_type' => 'none',
    'consume_type' => 'consume_type_stackable',
  ],
  15517 => 
  [
    'item_id' => 15517,
    'icon' => 'etc_debris_i00',
    'name' => 'Seal Components Part 1',
    'additionalname' => '',
    'description' => 'A Seal Breaker component. Acquired after defeating the Space Guard in the Tower of Infinitum. You can make a Seal Breaker that negates great power by putting this piece together with others like it.',
    'is_trade' => 0,
    'is_drop' => 0,
    'is_destruct' => 1,
    'crystal_type' => 'none',
    'consume_type' => 'consume_type_stackable',
  ],
  15518 => 
  [
    'item_id' => 15518,
    'icon' => 'etc_stone_black_i00',
    'name' => 'Seal Components Part 2',
    'additionalname' => '',
    'description' => 'A Seal Breaker component. Acquired after defeating the Space Gazer in the Tower of Infinitum. You can make a Seal Breaker that negates great power by putting this piece together with others like it.',
    'is_trade' => 0,
    'is_drop' => 0,
    'is_destruct' => 1,
    'crystal_type' => 'none',
    'consume_type' => 'consume_type_stackable',
  ],
  15519 => 
  [
    'item_id' => 15519,
    'icon' => 'etc_synthetic_cokes_i00',
    'name' => 'Seal Components Part 3',
    'additionalname' => '',
    'description' => 'A Seal Breaker component. Acquired after defeating the Space Priest in the Tower of Infinitum. You can make a Seal Breaker that negates great power by putting this piece together with others like it.',
    'is_trade' => 0,
    'is_drop' => 0,
    'is_destruct' => 1,
    'crystal_type' => 'none',
    'consume_type' => 'consume_type_stackable',
  ],
  15520 => 
  [
    'item_id' => 15520,
    'icon' => 'event_cubic_i00',
    'name' => 'Seal Components Part 4',
    'additionalname' => '',
    'description' => 'A Seal Breaker component. Acquired after defeating the Space Ruler in the Tower of Infinitum. You can make a Seal Breaker that negates great power by putting this piece together with others like it.',
    'is_trade' => 0,
    'is_drop' => 0,
    'is_destruct' => 1,
    'crystal_type' => 'none',
    'consume_type' => 'consume_type_stackable',
  ],
  15521 => 
  [
    'item_id' => 15521,
    'icon' => 'etc_plate_white_i00',
    'name' => 'Broken Golem Shard',
    'additionalname' => '',
    'description' => 'Fragment obtained by hunting golems.',
    'is_trade' => 0,
    'is_drop' => 0,
    'is_destruct' => 1,
    'crystal_type' => 'none',
    'consume_type' => 'consume_type_stackable',
  ],
  15522 => 
  [
    'item_id' => 15522,
    'icon' => 'armor_neck01',
    'name' => 'Shabby Necklace',
    'additionalname' => '',
    'description' => 'Shabby necklace that Watcher of Antharas Theodric supposedly gives only to those who are worthy of going after the Land Dragon Antharas. He says the necklace will transform after you defeat Antharas.',
    'is_trade' => 0,
    'is_drop' => 0,
    'is_destruct' => 1,
    'crystal_type' => 'none',
    'consume_type' => 'consume_type_stackable',
  ],
  15523 => 
  [
    'item_id' => 15523,
    'icon' => 'accessary_necklace_of_protection_i00',
    'name' => 'Proof of Miracle',
    'additionalname' => '',
    'description' => 'After you defeated the Land Dragon Antharas, the shabby necklace that you received from Watcher of Antharas Theodric changed into a this item. Take this necklace to him.',
    'is_trade' => 0,
    'is_drop' => 0,
    'is_destruct' => 1,
    'crystal_type' => 'none',
    'consume_type' => 'consume_type_stackable',
  ],
  15524 => 
  [
    'item_id' => 15524,
    'icon' => 'armor_neck02',
    'name' => 'Poor Necklace',
    'additionalname' => '',
    'description' => 'Valakas Watchman Klein gave you this necklace. It is of poor quality and not worth much. However, it is said to transform into a something worth much more after killing Valakas.',
    'is_trade' => 0,
    'is_drop' => 0,
    'is_destruct' => 1,
    'crystal_type' => 'none',
    'consume_type' => 'consume_type_stackable',
  ],
  15525 => 
  [
    'item_id' => 15525,
    'icon' => 'accessary_necklace_of_valor_i00',
    'name' => 'Proof of Valor',
    'additionalname' => '',
    'description' => 'Defeating Valakas has transformed the shabby necklace, given by Valakas Watchman Klein, into this. Take the necklace back to him.',
    'is_trade' => 0,
    'is_drop' => 0,
    'is_destruct' => 1,
    'crystal_type' => 'none',
    'consume_type' => 'consume_type_stackable',
  ],
  15526 => 
  [
    'item_id' => 15526,
    'icon' => 'etc_leather_gray_i00',
    'name' => 'Tattered Monk Clothes',
    'additionalname' => '',
    'description' => 'Tattered clothes are the remains of the monks you battled in the Monastery of Silence. The clothes are nothing more than rags after their years of use. Let\'s take them to Greymore in the Monastery of Silence.',
    'is_trade' => 0,
    'is_drop' => 0,
    'is_destruct' => 1,
    'crystal_type' => 'none',
    'consume_type' => 'consume_type_stackable',
  ],
  15527 => 
  [
    'item_id' => 15527,
    'icon' => 'etc_potion_yellow_i00',
    'name' => 'Mark of Splendor',
    'additionalname' => '',
    'description' => 'Proof that you successfully defeated the Master of Splendor Anays at Priest Greymore\'s request. If you take it to Greymore, you will receive a reward.',
    'is_trade' => 0,
    'is_drop' => 0,
    'is_destruct' => 1,
    'crystal_type' => 'none',
    'consume_type' => 'consume_type_stackable',
  ],
  15528 => 
  [
    'item_id' => 15528,
    'icon' => 'etc_potion_yellow_i00',
    'name' => 'Mark of Darkness',
    'additionalname' => '',
    'description' => 'You succeeded in defeating the Master of Splendor Anays at Priest Greymore\'s request. But you received the Mark of Darkness rather than the Mark of Splendor. If you take this to Greymore, he will laugh at you.',
    'is_trade' => 0,
    'is_drop' => 0,
    'is_destruct' => 1,
    'crystal_type' => 'none',
    'consume_type' => 'consume_type_stackable',
  ],
  15529 => 
  [
    'item_id' => 15529,
    'icon' => 'etc_piece_of_paper_gray_i00',
    'name' => 'Priest Dominic\'s Letter',
    'additionalname' => '',
    'description' => 'Secret letter sent by Priest Dominic of the Rune Village temple to Greymore. Deliver it to Priest Greymore in the Monastery of Silence.',
    'is_trade' => 0,
    'is_drop' => 0,
    'is_destruct' => 1,
    'crystal_type' => 'none',
    'consume_type' => 'consume_type_stackable',
  ],
  15530 => 
  [
    'item_id' => 15530,
    'icon' => 'etc_magic_book_white_i00',
    'name' => 'Monk Scripture',
    'additionalname' => '',
    'description' => 'Sacred text obtained after defeating the monks in the Monastery of Silence. Bring it to Greymore in the Monastery of Silence.',
    'is_trade' => 0,
    'is_drop' => 0,
    'is_destruct' => 1,
    'crystal_type' => 'none',
    'consume_type' => 'consume_type_stackable',
  ],
  15531 => 
  [
    'item_id' => 15531,
    'icon' => 'etc_mane_i00',
    'name' => 'Sel Mahum Mane',
    'additionalname' => '',
    'description' => 'Mane obtained by defeating the Sel Mahums that were attacking the animals the Beast Farm. Collect them and bring them to Tunatun in the Beast Farm.',
    'is_trade' => 0,
    'is_drop' => 0,
    'is_destruct' => 1,
    'crystal_type' => 'none',
    'consume_type' => 'consume_type_stackable',
  ],
  15532 => 
  [
    'item_id' => 15532,
    'icon' => 'etc_meat_i00',
    'name' => 'Veal',
    'additionalname' => '',
    'description' => 'Meat from a young animal. Smells good but tastes bad. Take it to Beast Herder Tunatun at the Beast Farm.',
    'is_trade' => 0,
    'is_drop' => 0,
    'is_destruct' => 1,
    'crystal_type' => 'none',
    'consume_type' => 'consume_type_stackable',
  ],
  15533 => 
  [
    'item_id' => 15533,
    'icon' => 'etc_crystal_ball_white_i00',
    'name' => 'Jewel of Innocence',
    'additionalname' => '',
    'description' => 'White gem produce by animals. Looking at it reminds you of a time long ago. I wonder what my old friends are doing now…',
    'is_trade' => 0,
    'is_drop' => 0,
    'is_destruct' => 1,
    'crystal_type' => 'none',
    'consume_type' => 'consume_type_stackable',
  ],
  15534 => 
  [
    'item_id' => 15534,
    'icon' => 'etc_meat_of_monstereye_i00',
    'name' => 'Prime Meat',
    'additionalname' => '',
    'description' => 'Prime Meat obtained from an adult animal. Only one piece comes out per animal. Collect these and take them to Beast Herder Tunatun.',
    'is_trade' => 0,
    'is_drop' => 0,
    'is_destruct' => 1,
    'crystal_type' => 'none',
    'consume_type' => 'consume_type_stackable',
  ],
  15535 => 
  [
    'item_id' => 15535,
    'icon' => 'etc_oil_pot_white_i00',
    'name' => 'Concentrated Spirit Energy',
    'additionalname' => '',
    'description' => 'Obtained in the Seed of Annihilation. Take this Concentrated Spirit Energy to Special Product Broker Kirklan to exchange them for a reward.',
    'is_trade' => 0,
    'is_drop' => 0,
    'is_destruct' => 1,
    'crystal_type' => 'none',
    'consume_type' => 'consume_type_stackable',
  ],
  15536 => 
  [
    'item_id' => 15536,
    'icon' => 'etc_pouch_brown_i00',
    'name' => 'Soul Stone Dust',
    'additionalname' => '',
    'description' => 'Obtained through hunting in the Seed of Annihilation. Take this to Officer Klemis in the area.',
    'is_trade' => 0,
    'is_drop' => 0,
    'is_destruct' => 1,
    'crystal_type' => 'none',
    'consume_type' => 'consume_type_stackable',
  ],
  15537 => 
  [
    'item_id' => 15537,
    'icon' => 'etc_jewel_box_i00',
    'name' => 'Strongbox of Promise',
    'additionalname' => '',
    'description' => 'Small safe obtained by defeating the monks in the Monastery of Silence. You can find out about the quest by clicking on it. Quest start item.',
    'is_trade' => 0,
    'is_drop' => 0,
    'is_destruct' => 1,
    'crystal_type' => 'none',
    'consume_type' => 'consume_type_normal',
  ],
  15538 => 
  [
    'item_id' => 15538,
    'icon' => 'high_kamael_skill_book_i00',
    'name' => 'Book of Silence',
    'additionalname' => '',
    'description' => 'Ancient book contained inside the Strongbox of Promise. Before you can return it to its owner, you must figure out who it belongs to. Go to Library of Sages Director Sophia in the Rune Castle Library and ask for help.',
    'is_trade' => 0,
    'is_drop' => 0,
    'is_destruct' => 1,
    'crystal_type' => 'none',
    'consume_type' => 'consume_type_normal',
  ],
  15539 => 
  [
    'item_id' => 15539,
    'icon' => 'high_kamael_skill_book_i00',
    'name' => 'Book of Silence',
    'additionalname' => '',
    'description' => 'You heard about the book\'s owner from the Library of Sages Director Sophia. Return the book to its owner.',
    'is_trade' => 0,
    'is_drop' => 0,
    'is_destruct' => 1,
    'crystal_type' => 'none',
    'consume_type' => 'consume_type_normal',
  ],
  15540 => 
  [
    'item_id' => 15540,
    'icon' => 'weapon_club_i00',
    'name' => 'Unlit Torchlight',
    'additionalname' => '',
    'description' => 'Torch that doesn\'t light. Item needed to obtain the treasure chest in the secret room inside the Monastery of Silence.',
    'is_trade' => 1,
    'is_drop' => 1,
    'is_destruct' => 1,
    'crystal_type' => 'none',
    'consume_type' => 'consume_type_stackable',
  ],
  15541 => 
  [
    'item_id' => 15541,
    'icon' => 'etc_soul_stone_i00',
    'name' => 'Red Soul Crystal - Stage 17',
    'additionalname' => '',
    'description' => 'Red crystal containing the light of absorbed souls. stage 17. Special abilities can be applied to the weapon when absorbing certain amount of souls. MP 26 is consumed each time of use. A crystal of this level is said to absorb crystals on its own, so it doesn\'t seem like you need to use it directly on the monsters.',
    'is_trade' => 1,
    'is_drop' => 1,
    'is_destruct' => 1,
    'crystal_type' => 'none',
    'consume_type' => 'consume_type_normal',
  ],
  15542 => 
  [
    'item_id' => 15542,
    'icon' => 'etc_soul_stone_i01',
    'name' => 'Blue Soul Crystal - Stage 17',
    'additionalname' => '',
    'description' => 'Blue crystal containing the light of absorbed souls. stage 17. Special abilities can be applied to the weapon when absorbing certain amount of souls. MP 26 is consumed each time of use. A crystal of this level is said to absorb crystals on its own, so it doesn\'t seem like you need to use it directly on the monsters.',
    'is_trade' => 1,
    'is_drop' => 1,
    'is_destruct' => 1,
    'crystal_type' => 'none',
    'consume_type' => 'consume_type_normal',
  ],
  15543 => 
  [
    'item_id' => 15543,
    'icon' => 'etc_soul_stone_i02',
    'name' => 'Green Soul Crystal - Stage 17',
    'additionalname' => '',
    'description' => 'Green crystal containing the light of absorbed souls. stage 17. Special abilities can be applied to the weapon when absorbing certain amount of souls. MP 26 is consumed each time of use. A crystal of this level is said to absorb crystals on its own, so it doesn\'t seem like you need to use it directly on the monsters.',
    'is_trade' => 1,
    'is_drop' => 1,
    'is_destruct' => 1,
    'crystal_type' => 'none',
    'consume_type' => 'consume_type_normal',
  ],
  15544 => 
  [
    'item_id' => 15544,
    'icon' => 'weapon_incessantcore_sword_i00',
    'name' => 'Eternal Core Sword',
    'additionalname' => '',
    'description' => 'Can bestow 1 regular Soul Crystal and 1 Special Soul Crystal.',
    'is_trade' => 1,
    'is_drop' => 1,
    'is_destruct' => 1,
    'crystal_type' => 's80',
    'consume_type' => 'consume_type_normal',
  ],
  15545 => 
  [
    'item_id' => 15545,
    'icon' => 'weapon_mambaedge_i00',
    'name' => 'Mamba Edge',
    'additionalname' => '',
    'description' => 'Can bestow 1 regular Soul Crystal and 1 Special Soul Crystal.',
    'is_trade' => 1,
    'is_drop' => 1,
    'is_destruct' => 1,
    'crystal_type' => 's80',
    'consume_type' => 'consume_type_normal',
  ],
  15546 => 
  [
    'item_id' => 15546,
    'icon' => 'weapon_expowder_mace_i00',
    'name' => 'Eversor Mace',
    'additionalname' => '',
    'description' => 'Can bestow 1 regular Soul Crystal and 1 Special Soul Crystal.',
    'is_trade' => 1,
    'is_drop' => 1,
    'is_destruct' => 1,
    'crystal_type' => 's80',
    'consume_type' => 'consume_type_normal',
  ],
  15547 => 
  [
    'item_id' => 15547,
    'icon' => 'weapon_pereztear_hammer_i00',
    'name' => 'Contristo Hammer',
    'additionalname' => '',
    'description' => 'Can bestow 1 regular Soul Crystal and 1 Special Soul Crystal.',
    'is_trade' => 1,
    'is_drop' => 1,
    'is_destruct' => 1,
    'crystal_type' => 's80',
    'consume_type' => 'consume_type_normal',
  ],
  15548 => 
  [
    'item_id' => 15548,
    'icon' => 'weapon_lavamond_saw_i00',
    'name' => 'Lava Saw',
    'additionalname' => '',
    'description' => 'Can bestow 1 regular Soul Crystal and 1 Special Soul Crystal.',
    'is_trade' => 1,
    'is_drop' => 1,
    'is_destruct' => 1,
    'crystal_type' => 's80',
    'consume_type' => 'consume_type_normal',
  ],
  15549 => 
  [
    'item_id' => 15549,
    'icon' => 'weapon_jademice_claw_i00',
    'name' => 'Jade Claw',
    'additionalname' => '',
    'description' => 'Can bestow 1 regular Soul Crystal and 1 Special Soul Crystal.',
    'is_trade' => 1,
    'is_drop' => 1,
    'is_destruct' => 1,
    'crystal_type' => 's80',
    'consume_type' => 'consume_type_normal',
  ],
  15550 => 
  [
    'item_id' => 15550,
    'icon' => 'weapon_ghostcleaner_i00',
    'name' => 'Demitelum',
    'additionalname' => '',
    'description' => 'Can bestow 1 regular Soul Crystal and 1 Special Soul Crystal.',
    'is_trade' => 1,
    'is_drop' => 1,
    'is_destruct' => 1,
    'crystal_type' => 's80',
    'consume_type' => 'consume_type_normal',
  ],
  15551 => 
  [
    'item_id' => 15551,
    'icon' => 'weapon_sacredumors_i00',
    'name' => 'Sacredium',
    'additionalname' => '',
    'description' => 'Can bestow 1 regular Soul Crystal and 1 Special Soul Crystal.',
    'is_trade' => 1,
    'is_drop' => 1,
    'is_destruct' => 1,
    'crystal_type' => 's80',
    'consume_type' => 'consume_type_normal',
  ],
  15552 => 
  [
    'item_id' => 15552,
    'icon' => 'weapon_psyskilt_cane_i00',
    'name' => 'Cyclic Cane',
    'additionalname' => '',
    'description' => 'Can bestow 1 regular Soul Crystal and 1 Special Soul Crystal.',
    'is_trade' => 1,
    'is_drop' => 1,
    'is_destruct' => 1,
    'crystal_type' => 's80',
    'consume_type' => 'consume_type_normal',
  ],
  15553 => 
  [
    'item_id' => 15553,
    'icon' => 'weapon_archangel_sword_i00',
    'name' => 'Archangel Sword',
    'additionalname' => '',
    'description' => 'Can bestow 1 regular Soul Crystal and 1 Special Soul Crystal.',
    'is_trade' => 1,
    'is_drop' => 1,
    'is_destruct' => 1,
    'crystal_type' => 's80',
    'consume_type' => 'consume_type_normal',
  ],
  15554 => 
  [
    'item_id' => 15554,
    'icon' => 'weapon_recurvethorne_bow_i00',
    'name' => 'Recurve Thorne Bow',
    'additionalname' => '',
    'description' => 'Can bestow 1 regular Soul Crystal and 1 Special Soul Crystal.',
    'is_trade' => 1,
    'is_drop' => 1,
    'is_destruct' => 1,
    'crystal_type' => 's80',
    'consume_type' => 'consume_type_normal',
  ],
  15555 => 
  [
    'item_id' => 15555,
    'icon' => 'weapon_heavenstair_rapier_i00',
    'name' => 'Heavenstare Rapier',
    'additionalname' => '',
    'description' => 'Kamael-exclusive Weapon: Eternal Core Sword Conversion
Can bestow 1 regular Soul Crystal and 1 Special Soul Crystal.',
    'is_trade' => 1,
    'is_drop' => 1,
    'is_destruct' => 1,
    'crystal_type' => 's80',
    'consume_type' => 'consume_type_normal',
  ],
  15556 => 
  [
    'item_id' => 15556,
    'icon' => 'weapon_pyseal_blade_i00',
    'name' => 'Pyseal Blade',
    'additionalname' => '',
    'description' => 'Kamael-exclusive Weapon: Lava Saw conversion
Can bestow 1 regular Soul Crystal and 1 Special Soul Crystal.',
    'is_trade' => 1,
    'is_drop' => 1,
    'is_destruct' => 1,
    'crystal_type' => 's80',
    'consume_type' => 'consume_type_normal',
  ],
  15557 => 
  [
    'item_id' => 15557,
    'icon' => 'weapon_thorne_crossbow_i00',
    'name' => 'Thorne Crossbow',
    'additionalname' => '',
    'description' => 'Kamael-exclusive Weapon: Recurvethorne Bow conversion
Can bestow 1 regular Soul Crystal and 1 Special Soul Crystal.',
    'is_trade' => 1,
    'is_drop' => 1,
    'is_destruct' => 1,
    'crystal_type' => 's80',
    'consume_type' => 'consume_type_normal',
  ],
  15558 => 
  [
    'item_id' => 15558,
    'icon' => 'weapon_periwing_sword_i00',
    'name' => 'Periel Sword',
    'additionalname' => '',
    'description' => 'Can bestow 1 regular Soul Crystal and 1 Special Soul Crystal.',
    'is_trade' => 1,
    'is_drop' => 1,
    'is_destruct' => 1,
    'crystal_type' => 's80',
    'consume_type' => 'consume_type_normal',
  ],
  15559 => 
  [
    'item_id' => 15559,
    'icon' => 'weapon_skulledge_i00',
    'name' => 'Skull Edge',
    'additionalname' => '',
    'description' => 'Can bestow 1 regular Soul Crystal and 1 Special Soul Crystal.',
    'is_trade' => 1,
    'is_drop' => 1,
    'is_destruct' => 1,
    'crystal_type' => 's80',
    'consume_type' => 'consume_type_normal',
  ],
  15560 => 
  [
    'item_id' => 15560,
    'icon' => 'weapon_vigwik_axe_i00',
    'name' => 'Vigwik Axe',
    'additionalname' => '',
    'description' => 'Can bestow 1 regular Soul Crystal and 1 Special Soul Crystal.',
    'is_trade' => 1,
    'is_drop' => 1,
    'is_destruct' => 1,
    'crystal_type' => 's80',
    'consume_type' => 'consume_type_normal',
  ],
  15561 => 
  [
    'item_id' => 15561,
    'icon' => 'weapon_evildeity_maul_i00',
    'name' => 'Devilish Maul',
    'additionalname' => '',
    'description' => 'Can bestow 1 regular Soul Crystal and 1 Special Soul Crystal.',
    'is_trade' => 1,
    'is_drop' => 1,
    'is_destruct' => 1,
    'crystal_type' => 's80',
    'consume_type' => 'consume_type_normal',
  ],
  15562 => 
  [
    'item_id' => 15562,
    'icon' => 'weapon_feathereye_blade_i00',
    'name' => 'Feather Eye Blade',
    'additionalname' => '',
    'description' => 'Can bestow 1 regular Soul Crystal and 1 Special Soul Crystal.',
    'is_trade' => 1,
    'is_drop' => 1,
    'is_destruct' => 1,
    'crystal_type' => 's80',
    'consume_type' => 'consume_type_normal',
  ],
  15563 => 
  [
    'item_id' => 15563,
    'icon' => 'weapon_octoclaw_i00',
    'name' => 'Octo Claw',
    'additionalname' => '',
    'description' => 'Can bestow 1 regular Soul Crystal and 1 Special Soul Crystal.',
    'is_trade' => 1,
    'is_drop' => 1,
    'is_destruct' => 1,
    'crystal_type' => 's80',
    'consume_type' => 'consume_type_normal',
  ],
  15564 => 
  [
    'item_id' => 15564,
    'icon' => 'weapon_doubletopa_spear_i00',
    'name' => 'Doubletop Spear',
    'additionalname' => '',
    'description' => 'Can bestow 1 regular Soul Crystal and 1 Special Soul Crystal.',
    'is_trade' => 1,
    'is_drop' => 1,
    'is_destruct' => 1,
    'crystal_type' => 's80',
    'consume_type' => 'consume_type_normal',
  ],
  15565 => 
  [
    'item_id' => 15565,
    'icon' => 'weapon_cuticle_i00',
    'name' => 'Rising Star',
    'additionalname' => '',
    'description' => 'Can bestow 1 regular Soul Crystal and 1 Special Soul Crystal.',
    'is_trade' => 1,
    'is_drop' => 1,
    'is_destruct' => 1,
    'crystal_type' => 's80',
    'consume_type' => 'consume_type_normal',
  ],
  15566 => 
  [
    'item_id' => 15566,
    'icon' => 'weapon_blackvisage_i00',
    'name' => 'Black Visage',
    'additionalname' => '',
    'description' => 'Can bestow 1 regular Soul Crystal and 1 Special Soul Crystal.',
    'is_trade' => 1,
    'is_drop' => 1,
    'is_destruct' => 1,
    'crystal_type' => 's80',
    'consume_type' => 'consume_type_normal',
  ],
  15567 => 
  [
    'item_id' => 15567,
    'icon' => 'weapon_veniplant_sword_i00',
    'name' => 'Veniplant Sword',
    'additionalname' => '',
    'description' => 'Can bestow 1 regular Soul Crystal and 1 Special Soul Crystal.',
    'is_trade' => 1,
    'is_drop' => 1,
    'is_destruct' => 1,
    'crystal_type' => 's80',
    'consume_type' => 'consume_type_normal',
  ],
  15568 => 
  [
    'item_id' => 15568,
    'icon' => 'weapon_skullgrove_bow_i00',
    'name' => 'Skull Carnium Bow',
    'additionalname' => '',
    'description' => 'Can bestow 1 regular Soul Crystal and 1 Special Soul Crystal.',
    'is_trade' => 1,
    'is_drop' => 1,
    'is_destruct' => 1,
    'crystal_type' => 's80',
    'consume_type' => 'consume_type_normal',
  ],
  15569 => 
  [
    'item_id' => 15569,
    'icon' => 'weapon_gemtail_rapier_i00',
    'name' => 'Gemtail Rapier',
    'additionalname' => '',
    'description' => 'Kamael-exclusive Weapon: Periel Sword Conversion
Can bestow 1 regular Soul Crystal and 1 Special Soul Crystal.
When enchanted to 4 or more, there is a chance that party members including yourself will get increased P. Atk., M. Atk. and the amount of received heal, and decreased MP consumption per skill during a Critical Attack.',
    'is_trade' => 1,
    'is_drop' => 1,
    'is_destruct' => 1,
    'crystal_type' => 's80',
    'consume_type' => 'consume_type_normal',
  ],
  15570 => 
  [
    'item_id' => 15570,
    'icon' => 'weapon_findragon blade_i00',
    'name' => 'Finale Blade',
    'additionalname' => '',
    'description' => 'Kamael-exclusive Weapon: Feather Eye Blade conversion
Can bestow 1 regular Soul Crystal and 1 Special Soul Crystal.',
    'is_trade' => 1,
    'is_drop' => 1,
    'is_destruct' => 1,
    'crystal_type' => 's80',
    'consume_type' => 'consume_type_normal',
  ],
  15571 => 
  [
    'item_id' => 15571,
    'icon' => 'weapon_rudecutter_crossbow_i00',
    'name' => 'Dominion Crossbow',
    'additionalname' => '',
    'description' => 'Kamael-exclusive Weapon: Skull Carnium Bow conversion
Can bestow 1 regular Soul Crystal and 1 Special Soul Crystal.',
    'is_trade' => 1,
    'is_drop' => 1,
    'is_destruct' => 1,
    'crystal_type' => 's80',
    'consume_type' => 'consume_type_normal',
  ],
  15572 => 
  [
    'item_id' => 15572,
    'icon' => 'armor_helmet_i00',
    'name' => 'Elegia Helmet',
    'additionalname' => '',
    'description' => '',
    'is_trade' => 1,
    'is_drop' => 1,
    'is_destruct' => 1,
    'crystal_type' => 's80',
    'consume_type' => 'consume_type_normal',
  ],
  15573 => 
  [
    'item_id' => 15573,
    'icon' => 'armor_leather_helmet_i00',
    'name' => 'Elegia Leather Helmet',
    'additionalname' => '',
    'description' => '',
    'is_trade' => 1,
    'is_drop' => 1,
    'is_destruct' => 1,
    'crystal_type' => 's80',
    'consume_type' => 'consume_type_normal',
  ],
  15574 => 
  [
    'item_id' => 15574,
    'icon' => 'armor_circlet_i00',
    'name' => 'Elegia Circlet',
    'additionalname' => '',
    'description' => '',
    'is_trade' => 1,
    'is_drop' => 1,
    'is_destruct' => 1,
    'crystal_type' => 's80',
    'consume_type' => 'consume_type_normal',
  ],
  15575 => 
  [
    'item_id' => 15575,
    'icon' => 'armor_t97_u_i00',
    'name' => 'Elegia Breastplate',
    'additionalname' => '',
    'description' => '',
    'is_trade' => 1,
    'is_drop' => 1,
    'is_destruct' => 1,
    'crystal_type' => 's80',
    'consume_type' => 'consume_type_normal',
  ],
  15576 => 
  [
    'item_id' => 15576,
    'icon' => 'armor_t98_u_i00',
    'name' => 'Elegia Leather Breastplate',
    'additionalname' => '',
    'description' => '',
    'is_trade' => 1,
    'is_drop' => 1,
    'is_destruct' => 1,
    'crystal_type' => 's80',
    'consume_type' => 'consume_type_normal',
  ],
  15577 => 
  [
    'item_id' => 15577,
    'icon' => 'armor_t99_u_i00',
    'name' => 'Elegia Tunic',
    'additionalname' => '',
    'description' => '',
    'is_trade' => 1,
    'is_drop' => 1,
    'is_destruct' => 1,
    'crystal_type' => 's80',
    'consume_type' => 'consume_type_normal',
  ],
  15578 => 
  [
    'item_id' => 15578,
    'icon' => 'armor_t97_l_i00',
    'name' => 'Elegia Gaiters',
    'additionalname' => '',
    'description' => '',
    'is_trade' => 1,
    'is_drop' => 1,
    'is_destruct' => 1,
    'crystal_type' => 's80',
    'consume_type' => 'consume_type_normal',
  ],
  15579 => 
  [
    'item_id' => 15579,
    'icon' => 'armor_t98_l_i00',
    'name' => 'Elegia Leather Leggings',
    'additionalname' => '',
    'description' => '',
    'is_trade' => 1,
    'is_drop' => 1,
    'is_destruct' => 1,
    'crystal_type' => 's80',
    'consume_type' => 'consume_type_normal',
  ],
  15580 => 
  [
    'item_id' => 15580,
    'icon' => 'armor_t99_l_i00',
    'name' => 'Elegia Stockings',
    'additionalname' => '',
    'description' => '',
    'is_trade' => 1,
    'is_drop' => 1,
    'is_destruct' => 1,
    'crystal_type' => 's80',
    'consume_type' => 'consume_type_normal',
  ],
  15581 => 
  [
    'item_id' => 15581,
    'icon' => 'armor_t97_g_i00',
    'name' => 'Elegia Gauntlets',
    'additionalname' => '',
    'description' => '',
    'is_trade' => 1,
    'is_drop' => 1,
    'is_destruct' => 1,
    'crystal_type' => 's80',
    'consume_type' => 'consume_type_normal',
  ],
  15582 => 
  [
    'item_id' => 15582,
    'icon' => 'armor_t98_g_i00',
    'name' => 'Elegia Leather Gloves',
    'additionalname' => '',
    'description' => '',
    'is_trade' => 1,
    'is_drop' => 1,
    'is_destruct' => 1,
    'crystal_type' => 's80',
    'consume_type' => 'consume_type_normal',
  ],
  15583 => 
  [
    'item_id' => 15583,
    'icon' => 'armor_t99_g_i00',
    'name' => 'Elegia Gloves',
    'additionalname' => '',
    'description' => '',
    'is_trade' => 1,
    'is_drop' => 1,
    'is_destruct' => 1,
    'crystal_type' => 's80',
    'consume_type' => 'consume_type_normal',
  ],
  15584 => 
  [
    'item_id' => 15584,
    'icon' => 'armor_t97_b_i00',
    'name' => 'Elegia Boots',
    'additionalname' => '',
    'description' => '',
    'is_trade' => 1,
    'is_drop' => 1,
    'is_destruct' => 1,
    'crystal_type' => 's80',
    'consume_type' => 'consume_type_normal',
  ],
  15585 => 
  [
    'item_id' => 15585,
    'icon' => 'armor_t98_b_i00',
    'name' => 'Elegia Leather Boots',
    'additionalname' => '',
    'description' => '',
    'is_trade' => 1,
    'is_drop' => 1,
    'is_destruct' => 1,
    'crystal_type' => 's80',
    'consume_type' => 'consume_type_normal',
  ],
  15586 => 
  [
    'item_id' => 15586,
    'icon' => 'armor_t99_b_i00',
    'name' => 'Elegia Shoes',
    'additionalname' => '',
    'description' => '',
    'is_trade' => 1,
    'is_drop' => 1,
    'is_destruct' => 1,
    'crystal_type' => 's80',
    'consume_type' => 'consume_type_normal',
  ],
  15587 => 
  [
    'item_id' => 15587,
    'icon' => 'heavengate_shield_i01',
    'name' => 'Elegia Shield',
    'additionalname' => '',
    'description' => '',
    'is_trade' => 1,
    'is_drop' => 1,
    'is_destruct' => 1,
    'crystal_type' => 's80',
    'consume_type' => 'consume_type_normal',
  ],
  15588 => 
  [
    'item_id' => 15588,
    'icon' => 'weapon_pricklelotus_i01',
    'name' => 'Elegia Sigil',
    'additionalname' => '',
    'description' => '',
    'is_trade' => 1,
    'is_drop' => 1,
    'is_destruct' => 1,
    'crystal_type' => 's80',
    'consume_type' => 'consume_type_normal',
  ],
  15589 => 
  [
    'item_id' => 15589,
    'icon' => 'armor_helmet_i00',
    'name' => 'Vorpal Helmet',
    'additionalname' => '',
    'description' => '',
    'is_trade' => 1,
    'is_drop' => 1,
    'is_destruct' => 1,
    'crystal_type' => 's80',
    'consume_type' => 'consume_type_normal',
  ],
  15590 => 
  [
    'item_id' => 15590,
    'icon' => 'armor_leather_helmet_i00',
    'name' => 'Vorpal Leather Helmet',
    'additionalname' => '',
    'description' => '',
    'is_trade' => 1,
    'is_drop' => 1,
    'is_destruct' => 1,
    'crystal_type' => 's80',
    'consume_type' => 'consume_type_normal',
  ],
  15591 => 
  [
    'item_id' => 15591,
    'icon' => 'armor_circlet_i00',
    'name' => 'Vorpal Circlet',
    'additionalname' => '',
    'description' => '',
    'is_trade' => 1,
    'is_drop' => 1,
    'is_destruct' => 1,
    'crystal_type' => 's80',
    'consume_type' => 'consume_type_normal',
  ],
  15592 => 
  [
    'item_id' => 15592,
    'icon' => 'armor_t94_u_i03',
    'name' => 'Vorpal Breastplate',
    'additionalname' => '',
    'description' => '',
    'is_trade' => 1,
    'is_drop' => 1,
    'is_destruct' => 1,
    'crystal_type' => 's80',
    'consume_type' => 'consume_type_normal',
  ],
  15593 => 
  [
    'item_id' => 15593,
    'icon' => 'armor_t95_u_i03',
    'name' => 'Vorpal Leather Breastplate',
    'additionalname' => '',
    'description' => '',
    'is_trade' => 1,
    'is_drop' => 1,
    'is_destruct' => 1,
    'crystal_type' => 's80',
    'consume_type' => 'consume_type_normal',
  ],
  15594 => 
  [
    'item_id' => 15594,
    'icon' => 'armor_t96_u_i03',
    'name' => 'Vorpal Tunic',
    'additionalname' => '',
    'description' => '',
    'is_trade' => 1,
    'is_drop' => 1,
    'is_destruct' => 1,
    'crystal_type' => 's80',
    'consume_type' => 'consume_type_normal',
  ],
  15595 => 
  [
    'item_id' => 15595,
    'icon' => 'armor_t94_l_i03',
    'name' => 'Vorpal Gaiters',
    'additionalname' => '',
    'description' => '',
    'is_trade' => 1,
    'is_drop' => 1,
    'is_destruct' => 1,
    'crystal_type' => 's80',
    'consume_type' => 'consume_type_normal',
  ],
  15596 => 
  [
    'item_id' => 15596,
    'icon' => 'armor_t95_l_i03',
    'name' => 'Vorpal Leather Leggings',
    'additionalname' => '',
    'description' => '',
    'is_trade' => 1,
    'is_drop' => 1,
    'is_destruct' => 1,
    'crystal_type' => 's80',
    'consume_type' => 'consume_type_normal',
  ],
  15597 => 
  [
    'item_id' => 15597,
    'icon' => 'armor_t96_l_i03',
    'name' => 'Vorpal Stockings',
    'additionalname' => '',
    'description' => '',
    'is_trade' => 1,
    'is_drop' => 1,
    'is_destruct' => 1,
    'crystal_type' => 's80',
    'consume_type' => 'consume_type_normal',
  ],
  15598 => 
  [
    'item_id' => 15598,
    'icon' => 'armor_t94_g_i03',
    'name' => 'Vorpal Gauntlets',
    'additionalname' => '',
    'description' => '',
    'is_trade' => 1,
    'is_drop' => 1,
    'is_destruct' => 1,
    'crystal_type' => 's80',
    'consume_type' => 'consume_type_normal',
  ],
  15599 => 
  [
    'item_id' => 15599,
    'icon' => 'armor_t95_g_i03',
    'name' => 'Vorpal Leather Gloves',
    'additionalname' => '',
    'description' => '',
    'is_trade' => 1,
    'is_drop' => 1,
    'is_destruct' => 1,
    'crystal_type' => 's80',
    'consume_type' => 'consume_type_normal',
  ],
];