<?php return [
  15600 => 
  [
    'item_id' => 15600,
    'icon' => 'armor_t96_g_i03',
    'name' => 'Vorpal Gloves',
    'additionalname' => NULL,
    'description' => NULL,
    'is_trade' => 1,
    'is_drop' => 1,
    'is_destruct' => 1,
    'crystal_type' => 's80',
    'consume_type' => 'consume_type_normal',
  ],
  15601 => 
  [
    'item_id' => 15601,
    'icon' => 'armor_t94_b_i03',
    'name' => 'Vorpal Boots',
    'additionalname' => NULL,
    'description' => NULL,
    'is_trade' => 1,
    'is_drop' => 1,
    'is_destruct' => 1,
    'crystal_type' => 's80',
    'consume_type' => 'consume_type_normal',
  ],
  15602 => 
  [
    'item_id' => 15602,
    'icon' => 'armor_t95_b_i03',
    'name' => 'Vorpal Boots',
    'additionalname' => NULL,
    'description' => NULL,
    'is_trade' => 1,
    'is_drop' => 1,
    'is_destruct' => 1,
    'crystal_type' => 's80',
    'consume_type' => 'consume_type_normal',
  ],
  15603 => 
  [
    'item_id' => 15603,
    'icon' => 'armor_t96_b_i03',
    'name' => 'Vorpal Shoes',
    'additionalname' => NULL,
    'description' => NULL,
    'is_trade' => 1,
    'is_drop' => 1,
    'is_destruct' => 1,
    'crystal_type' => 's80',
    'consume_type' => 'consume_type_normal',
  ],
  15604 => 
  [
    'item_id' => 15604,
    'icon' => 'Evilgate_Shield_i01',
    'name' => 'Vorpal Shield',
    'additionalname' => NULL,
    'description' => NULL,
    'is_trade' => 1,
    'is_drop' => 1,
    'is_destruct' => 1,
    'crystal_type' => 's80',
    'consume_type' => 'consume_type_normal',
  ],
  15605 => 
  [
    'item_id' => 15605,
    'icon' => 'belleface_i00',
    'name' => 'Vorpal Sigil',
    'additionalname' => NULL,
    'description' => NULL,
    'is_trade' => 1,
    'is_drop' => 1,
    'is_destruct' => 1,
    'crystal_type' => 's80',
    'consume_type' => 'consume_type_normal',
  ],
  15606 => 
  [
    'item_id' => 15606,
    'icon' => 'armor_helmet_i00',
    'name' => 'Moirai Helmet',
    'additionalname' => NULL,
    'description' => NULL,
    'is_trade' => 1,
    'is_drop' => 1,
    'is_destruct' => 1,
    'crystal_type' => 's80',
    'consume_type' => 'consume_type_normal',
  ],
  15607 => 
  [
    'item_id' => 15607,
    'icon' => 'armor_helmet_i00',
    'name' => 'Moirai Helmet',
    'additionalname' => NULL,
    'description' => NULL,
    'is_trade' => 1,
    'is_drop' => 1,
    'is_destruct' => 1,
    'crystal_type' => 's80',
    'consume_type' => 'consume_type_normal',
  ],
  15608 => 
  [
    'item_id' => 15608,
    'icon' => 'armor_circlet_i00',
    'name' => 'Moirai Circlet',
    'additionalname' => NULL,
    'description' => NULL,
    'is_trade' => 1,
    'is_drop' => 1,
    'is_destruct' => 1,
    'crystal_type' => 's80',
    'consume_type' => 'consume_type_normal',
  ],
  15609 => 
  [
    'item_id' => 15609,
    'icon' => 'armor_t100_u_i00',
    'name' => 'Moirai Breastplate',
    'additionalname' => NULL,
    'description' => NULL,
    'is_trade' => 1,
    'is_drop' => 1,
    'is_destruct' => 1,
    'crystal_type' => 's80',
    'consume_type' => 'consume_type_normal',
  ],
  15610 => 
  [
    'item_id' => 15610,
    'icon' => 'armor_t101_u_i00',
    'name' => 'Moirai Breastplate',
    'additionalname' => NULL,
    'description' => NULL,
    'is_trade' => 1,
    'is_drop' => 1,
    'is_destruct' => 1,
    'crystal_type' => 's80',
    'consume_type' => 'consume_type_normal',
  ],
  15611 => 
  [
    'item_id' => 15611,
    'icon' => 'armor_t102_u_i00',
    'name' => 'Moirai Tunic',
    'additionalname' => NULL,
    'description' => NULL,
    'is_trade' => 1,
    'is_drop' => 1,
    'is_destruct' => 1,
    'crystal_type' => 's80',
    'consume_type' => 'consume_type_normal',
  ],
  15612 => 
  [
    'item_id' => 15612,
    'icon' => 'armor_t100_l_i00',
    'name' => 'Moirai Gaiters',
    'additionalname' => NULL,
    'description' => NULL,
    'is_trade' => 1,
    'is_drop' => 1,
    'is_destruct' => 1,
    'crystal_type' => 's80',
    'consume_type' => 'consume_type_normal',
  ],
  15613 => 
  [
    'item_id' => 15613,
    'icon' => 'armor_t101_l_i00',
    'name' => 'Moirai Leggings',
    'additionalname' => NULL,
    'description' => NULL,
    'is_trade' => 1,
    'is_drop' => 1,
    'is_destruct' => 1,
    'crystal_type' => 's80',
    'consume_type' => 'consume_type_normal',
  ],
  15614 => 
  [
    'item_id' => 15614,
    'icon' => 'armor_t102_l_i00',
    'name' => 'Moirai Stockings',
    'additionalname' => NULL,
    'description' => NULL,
    'is_trade' => 1,
    'is_drop' => 1,
    'is_destruct' => 1,
    'crystal_type' => 's80',
    'consume_type' => 'consume_type_normal',
  ],
  15615 => 
  [
    'item_id' => 15615,
    'icon' => 'armor_t100_g_i00',
    'name' => 'Moirai Gauntlets',
    'additionalname' => NULL,
    'description' => NULL,
    'is_trade' => 1,
    'is_drop' => 1,
    'is_destruct' => 1,
    'crystal_type' => 's80',
    'consume_type' => 'consume_type_normal',
  ],
  15616 => 
  [
    'item_id' => 15616,
    'icon' => 'armor_t101_g_i00',
    'name' => 'Moirai Gloves',
    'additionalname' => NULL,
    'description' => NULL,
    'is_trade' => 1,
    'is_drop' => 1,
    'is_destruct' => 1,
    'crystal_type' => 's80',
    'consume_type' => 'consume_type_normal',
  ],
  15617 => 
  [
    'item_id' => 15617,
    'icon' => 'armor_t102_g_i00',
    'name' => 'Moirai Gloves',
    'additionalname' => NULL,
    'description' => NULL,
    'is_trade' => 1,
    'is_drop' => 1,
    'is_destruct' => 1,
    'crystal_type' => 's80',
    'consume_type' => 'consume_type_normal',
  ],
  15618 => 
  [
    'item_id' => 15618,
    'icon' => 'armor_t100_b_i00',
    'name' => 'Moirai Boots',
    'additionalname' => NULL,
    'description' => NULL,
    'is_trade' => 1,
    'is_drop' => 1,
    'is_destruct' => 1,
    'crystal_type' => 's80',
    'consume_type' => 'consume_type_normal',
  ],
  15619 => 
  [
    'item_id' => 15619,
    'icon' => 'armor_t101_b_i00',
    'name' => 'Moirai Boots',
    'additionalname' => NULL,
    'description' => NULL,
    'is_trade' => 1,
    'is_drop' => 1,
    'is_destruct' => 1,
    'crystal_type' => 's80',
    'consume_type' => 'consume_type_normal',
  ],
  15620 => 
  [
    'item_id' => 15620,
    'icon' => 'armor_t102_b_i00',
    'name' => 'Moirai Shoes',
    'additionalname' => NULL,
    'description' => NULL,
    'is_trade' => 1,
    'is_drop' => 1,
    'is_destruct' => 1,
    'crystal_type' => 's80',
    'consume_type' => 'consume_type_normal',
  ],
  15621 => 
  [
    'item_id' => 15621,
    'icon' => 'weapon_tysandy_shield_i01',
    'name' => 'Moirai Shield',
    'additionalname' => NULL,
    'description' => NULL,
    'is_trade' => 1,
    'is_drop' => 1,
    'is_destruct' => 1,
    'crystal_type' => 's80',
    'consume_type' => 'consume_type_normal',
  ],
  15622 => 
  [
    'item_id' => 15622,
    'icon' => 'weapon_tysandy_sigil_i01',
    'name' => 'Moirai Sigil',
    'additionalname' => NULL,
    'description' => NULL,
    'is_trade' => 1,
    'is_drop' => 1,
    'is_destruct' => 1,
    'crystal_type' => 's80',
    'consume_type' => 'consume_type_normal',
  ],
  15623 => 
  [
    'item_id' => 15623,
    'icon' => 'etc_exp_point_i00',
    'name' => 'XP',
    'additionalname' => NULL,
    'description' => 'You acquire XP as a reward.',
    'is_trade' => 0,
    'is_drop' => 0,
    'is_destruct' => 0,
    'crystal_type' => 'none',
    'consume_type' => 'consume_type_normal',
  ],
  15624 => 
  [
    'item_id' => 15624,
    'icon' => 'etc_sp_point_i00',
    'name' => 'SP',
    'additionalname' => NULL,
    'description' => 'You acquire SP as a reward.',
    'is_trade' => 0,
    'is_drop' => 0,
    'is_destruct' => 0,
    'crystal_type' => 'none',
    'consume_type' => 'consume_type_normal',
  ],
  15625 => 
  [
    'item_id' => 15625,
    'icon' => 'etc_question_mark_i00',
    'name' => 'Unknown Reward',
    'additionalname' => NULL,
    'description' => 'Unknown Reward',
    'is_trade' => 0,
    'is_drop' => 0,
    'is_destruct' => 0,
    'crystal_type' => 'none',
    'consume_type' => 'consume_type_normal',
  ],
  15626 => 
  [
    'item_id' => 15626,
    'icon' => 'etc_vitality_point_i00',
    'name' => 'Vitality',
    'additionalname' => NULL,
    'description' => 'You acquire Vitality points as a reward.',
    'is_trade' => 0,
    'is_drop' => 0,
    'is_destruct' => 0,
    'crystal_type' => 'none',
    'consume_type' => 'consume_type_normal',
  ],
  15627 => 
  [
    'item_id' => 15627,
    'icon' => 'etc_bloodpledge_point_i00',
    'name' => 'Clan Point',
    'additionalname' => NULL,
    'description' => 'You acquire clan points as a reward.',
    'is_trade' => 0,
    'is_drop' => 0,
    'is_destruct' => 0,
    'crystal_type' => 'none',
    'consume_type' => 'consume_type_normal',
  ],
  15628 => 
  [
    'item_id' => 15628,
    'icon' => 'etc_quest_game_reward_i00',
    'name' => 'Gamble Reward',
    'additionalname' => NULL,
    'description' => 'Reward based on a game of chance.',
    'is_trade' => 0,
    'is_drop' => 0,
    'is_destruct' => 0,
    'crystal_type' => 'none',
    'consume_type' => 'consume_type_normal',
  ],
  15629 => 
  [
    'item_id' => 15629,
    'icon' => 'etc_quest_random_reward_i00',
    'name' => 'Random Reward',
    'additionalname' => NULL,
    'description' => 'Random reward given to player.',
    'is_trade' => 0,
    'is_drop' => 0,
    'is_destruct' => 0,
    'crystal_type' => 'none',
    'consume_type' => 'consume_type_normal',
  ],
  15630 => 
  [
    'item_id' => 15630,
    'icon' => 'etc_quest_account_reward_i00',
    'name' => 'Flexible Reward',
    'additionalname' => NULL,
    'description' => 'Reward is chosen based on your performance.',
    'is_trade' => 0,
    'is_drop' => 0,
    'is_destruct' => 0,
    'crystal_type' => 'none',
    'consume_type' => 'consume_type_normal',
  ],
  15631 => 
  [
    'item_id' => 15631,
    'icon' => 'etc_quest_add_reward_i00',
    'name' => 'Bonus Reward',
    'additionalname' => NULL,
    'description' => 'Little extra in addition to the current reward.',
    'is_trade' => 0,
    'is_drop' => 0,
    'is_destruct' => 0,
    'crystal_type' => 'none',
    'consume_type' => 'consume_type_normal',
  ],
  15632 => 
  [
    'item_id' => 15632,
    'icon' => 'etc_quest_subclass_reward_i00',
    'name' => 'Subclass Reward',
    'additionalname' => NULL,
    'description' => 'Subclass authority was obtained.',
    'is_trade' => 0,
    'is_drop' => 0,
    'is_destruct' => 0,
    'crystal_type' => 'none',
    'consume_type' => 'consume_type_normal',
  ],
  15633 => 
  [
    'item_id' => 15633,
    'icon' => 'etc_quest_pkcount_reward_i00',
    'name' => 'PK Reduction',
    'additionalname' => NULL,
    'description' => 'The PK Count is decreased.',
    'is_trade' => 0,
    'is_drop' => 0,
    'is_destruct' => 0,
    'crystal_type' => 'none',
    'consume_type' => 'consume_type_normal',
  ],
  15634 => 
  [
    'item_id' => 15634,
    'icon' => 'etc_vesper_cutter_piece_i00',
    'name' => 'Vesper Cutter Piece',
    'additionalname' => NULL,
    'description' => 'Key material for Dwarves to make Vesper Cutter. It can be sold at ordinary stores.',
    'is_trade' => 1,
    'is_drop' => 1,
    'is_destruct' => 1,
    'crystal_type' => 'none',
    'consume_type' => 'consume_type_stackable',
  ],
  15635 => 
  [
    'item_id' => 15635,
    'icon' => 'etc_vesper_slasher_piece_i00',
    'name' => 'Vesper Slasher Piece',
    'additionalname' => NULL,
    'description' => 'Key material for Dwarves to make Vesper Slasher. It can be sold at ordinary stores.',
    'is_trade' => 1,
    'is_drop' => 1,
    'is_destruct' => 1,
    'crystal_type' => 'none',
    'consume_type' => 'consume_type_stackable',
  ],
  15636 => 
  [
    'item_id' => 15636,
    'icon' => 'etc_vesper_burster_piece_i00',
    'name' => 'Vesper Buster Piece',
    'additionalname' => NULL,
    'description' => 'Key material for Dwarves to make Vesper Buster. It can be sold at ordinary stores.',
    'is_trade' => 1,
    'is_drop' => 1,
    'is_destruct' => 1,
    'crystal_type' => 'none',
    'consume_type' => 'consume_type_stackable',
  ],
  15637 => 
  [
    'item_id' => 15637,
    'icon' => 'etc_vesper_shaper_piece_i00',
    'name' => 'Vesper Shaper Piece',
    'additionalname' => NULL,
    'description' => 'Key material for Dwarves to make Vesper Shaper. It can be sold at ordinary stores.',
    'is_trade' => 1,
    'is_drop' => 1,
    'is_destruct' => 1,
    'crystal_type' => 'none',
    'consume_type' => 'consume_type_stackable',
  ],
  15638 => 
  [
    'item_id' => 15638,
    'icon' => 'etc_vesper_fighter_piece_i00',
    'name' => 'Vesper Fighter Piece',
    'additionalname' => NULL,
    'description' => 'Key material for Dwarves to make Vesper Fighter. It can be sold at ordinary stores.',
    'is_trade' => 1,
    'is_drop' => 1,
    'is_destruct' => 1,
    'crystal_type' => 'none',
    'consume_type' => 'consume_type_stackable',
  ],
  15639 => 
  [
    'item_id' => 15639,
    'icon' => 'etc_vesper_stormer_piece_i00',
    'name' => 'Vesper Stormer Piece',
    'additionalname' => NULL,
    'description' => 'Key material for Dwarves to make Vesper Stormer. It can be sold at ordinary stores.',
    'is_trade' => 1,
    'is_drop' => 1,
    'is_destruct' => 1,
    'crystal_type' => 'none',
    'consume_type' => 'consume_type_stackable',
  ],
  15640 => 
  [
    'item_id' => 15640,
    'icon' => 'etc_vesper_avenger_piece_i00',
    'name' => 'Vesper Avenger Piece',
    'additionalname' => NULL,
    'description' => 'Key material for Dwarves to make Vesper Avenger. It can be sold at ordinary stores.',
    'is_trade' => 1,
    'is_drop' => 1,
    'is_destruct' => 1,
    'crystal_type' => 'none',
    'consume_type' => 'consume_type_stackable',
  ],
  15641 => 
  [
    'item_id' => 15641,
    'icon' => 'etc_vesper_retributer_piece_i00',
    'name' => 'Vesper Retributer Piece',
    'additionalname' => NULL,
    'description' => 'Key material for Dwarves to make Vesper Retributer. It can be sold at ordinary stores.',
    'is_trade' => 1,
    'is_drop' => 1,
    'is_destruct' => 1,
    'crystal_type' => 'none',
    'consume_type' => 'consume_type_stackable',
  ],
  15642 => 
  [
    'item_id' => 15642,
    'icon' => 'etc_vesper_caster_piece_i00',
    'name' => 'Vesper Caster Piece',
    'additionalname' => NULL,
    'description' => 'Key material for Dwarves to make Vesper Caster. It can be sold at ordinary stores.',
    'is_trade' => 1,
    'is_drop' => 1,
    'is_destruct' => 1,
    'crystal_type' => 'none',
    'consume_type' => 'consume_type_stackable',
  ],
  15643 => 
  [
    'item_id' => 15643,
    'icon' => 'etc_vesper_singer_piece_i00',
    'name' => 'Vesper Singer Piece',
    'additionalname' => NULL,
    'description' => 'Key material for Dwarves to make Vesper Singer. It can be sold at ordinary stores.',
    'is_trade' => 1,
    'is_drop' => 1,
    'is_destruct' => 1,
    'crystal_type' => 'none',
    'consume_type' => 'consume_type_stackable',
  ],
  15644 => 
  [
    'item_id' => 15644,
    'icon' => 'etc_vesper_thrower_piece_i00',
    'name' => 'Vesper Thrower Piece',
    'additionalname' => NULL,
    'description' => 'Key material for Dwarves to make Vesper Thrower. It can be sold at ordinary stores.',
    'is_trade' => 1,
    'is_drop' => 1,
    'is_destruct' => 1,
    'crystal_type' => 'none',
    'consume_type' => 'consume_type_stackable',
  ],
  15645 => 
  [
    'item_id' => 15645,
    'icon' => 'etc_sealed_blluelycan_helmet_piece_I00',
    'name' => 'Sealed Moirai Helmet Piece',
    'additionalname' => NULL,
    'description' => 'Key material for Dwarves to make Sealed Moirai Helmet. Not valuable material for crafting old equipment.',
    'is_trade' => 1,
    'is_drop' => 1,
    'is_destruct' => 1,
    'crystal_type' => 'none',
    'consume_type' => 'consume_type_stackable',
  ],
  15646 => 
  [
    'item_id' => 15646,
    'icon' => 'etc_sealed_blluelycan_leather_helmet_piece_I00',
    'name' => 'Sealed Moirai Leather Helmet Piece',
    'additionalname' => NULL,
    'description' => 'Key material for Dwarves to make Sealed Moirai Leather Helmet. Not valuable material for crafting old equipment.',
    'is_trade' => 1,
    'is_drop' => 1,
    'is_destruct' => 1,
    'crystal_type' => 'none',
    'consume_type' => 'consume_type_stackable',
  ],
  15647 => 
  [
    'item_id' => 15647,
    'icon' => 'etc_sealed_blluelycan_circlet_piece_I00',
    'name' => 'Sealed Moirai Circlet Piece',
    'additionalname' => NULL,
    'description' => 'Key material for Dwarves to make Sealed Moirai Circlet. Not valuable material for crafting old equipment.',
    'is_trade' => 1,
    'is_drop' => 1,
    'is_destruct' => 1,
    'crystal_type' => 'none',
    'consume_type' => 'consume_type_stackable',
  ],
  15648 => 
  [
    'item_id' => 15648,
    'icon' => 'etc_sealed_bluelycan_cuirass_piece_I00',
    'name' => 'Sealed Moirai Breastplate Piece',
    'additionalname' => NULL,
    'description' => 'Key material for Dwarves to make Sealed Moirai Breastplate. Not valuable material for crafting old equipment.',
    'is_trade' => 1,
    'is_drop' => 1,
    'is_destruct' => 1,
    'crystal_type' => 'none',
    'consume_type' => 'consume_type_stackable',
  ],
  15649 => 
  [
    'item_id' => 15649,
    'icon' => 'etc_sealed_bluelycan_houberk_piece_I00',
    'name' => 'Sealed Moirai Leather Breastplate Piece',
    'additionalname' => NULL,
    'description' => 'Key material for Dwarves to make Sealed Moirai Leather Breastplate. Not valuable material for crafting old equipment.',
    'is_trade' => 1,
    'is_drop' => 1,
    'is_destruct' => 1,
    'crystal_type' => 'none',
    'consume_type' => 'consume_type_stackable',
  ],
  15650 => 
  [
    'item_id' => 15650,
    'icon' => 'etc_sealed_bluelycan_jaket_piece_I00',
    'name' => 'Sealed Moirai Tunic Piece',
    'additionalname' => NULL,
    'description' => 'Key material for Dwarves to make Sealed Moirai Tunic. Not valuable material for crafting old equipment.',
    'is_trade' => 1,
    'is_drop' => 1,
    'is_destruct' => 1,
    'crystal_type' => 'none',
    'consume_type' => 'consume_type_stackable',
  ],
  15651 => 
  [
    'item_id' => 15651,
    'icon' => 'etc_sealed_bluelycan_gaiter_piece_I00',
    'name' => 'Sealed Moirai Gaiters Piece',
    'additionalname' => NULL,
    'description' => 'Key material for Dwarves to make Sealed Moirai Gaiters. Not valuable material for crafting old equipment.',
    'is_trade' => 1,
    'is_drop' => 1,
    'is_destruct' => 1,
    'crystal_type' => 'none',
    'consume_type' => 'consume_type_stackable',
  ],
  15652 => 
  [
    'item_id' => 15652,
    'icon' => 'etc_sealed_bluelycan_leather_legging_piece_I00',
    'name' => 'Sealed Moirai Leather Leggings Piece',
    'additionalname' => NULL,
    'description' => 'Key material for Dwarves to make Sealed Moirai Leather Leggings. Not valuable material for crafting old equipment.',
    'is_trade' => 1,
    'is_drop' => 1,
    'is_destruct' => 1,
    'crystal_type' => 'none',
    'consume_type' => 'consume_type_stackable',
  ],
  15653 => 
  [
    'item_id' => 15653,
    'icon' => 'etc_sealed_bluelycan_hose_piece_I00',
    'name' => 'Sealed Moirai Stockings Piece',
    'additionalname' => NULL,
    'description' => 'Key material for Dwarves to make Sealed Moirai Stockings. Not valuable material for crafting old equipment.',
    'is_trade' => 1,
    'is_drop' => 1,
    'is_destruct' => 1,
    'crystal_type' => 'none',
    'consume_type' => 'consume_type_stackable',
  ],
  15654 => 
  [
    'item_id' => 15654,
    'icon' => 'etc_sealed_bluelycan_gauntlet_piece_I00',
    'name' => 'Sealed Moirai Gauntlets Piece',
    'additionalname' => NULL,
    'description' => 'Key material for Dwarves to make Sealed Moirai Gauntlets. Not valuable material for crafting old equipment.',
    'is_trade' => 1,
    'is_drop' => 1,
    'is_destruct' => 1,
    'crystal_type' => 'none',
    'consume_type' => 'consume_type_stackable',
  ],
  15655 => 
  [
    'item_id' => 15655,
    'icon' => 'etc_sealed_bluelycan_leather_gloves_piece_I00',
    'name' => 'Sealed Moirai Leather Gloves Piece',
    'additionalname' => NULL,
    'description' => 'Key material for Dwarves to make Sealed Moirai Leather Gloves. Not valuable material for crafting old equipment.',
    'is_trade' => 1,
    'is_drop' => 1,
    'is_destruct' => 1,
    'crystal_type' => 'none',
    'consume_type' => 'consume_type_stackable',
  ],
  15656 => 
  [
    'item_id' => 15656,
    'icon' => 'etc_sealed_bluelycan_gloves_piece_I00',
    'name' => 'Sealed Moirai Gloves Piece',
    'additionalname' => NULL,
    'description' => 'Key material for Dwarves to make Sealed Moirai Gloves. Not valuable material for crafting old equipment.',
    'is_trade' => 1,
    'is_drop' => 1,
    'is_destruct' => 1,
    'crystal_type' => 'none',
    'consume_type' => 'consume_type_stackable',
  ],
  15657 => 
  [
    'item_id' => 15657,
    'icon' => 'etc_sealed_bluelycan_boots_piece_I00',
    'name' => 'Sealed Moirai Boots Piece',
    'additionalname' => NULL,
    'description' => 'Key material for Dwarves to make Sealed Moirai Boots. Not valuable material for crafting old equipment.',
    'is_trade' => 1,
    'is_drop' => 1,
    'is_destruct' => 1,
    'crystal_type' => 'none',
    'consume_type' => 'consume_type_stackable',
  ],
  15658 => 
  [
    'item_id' => 15658,
    'icon' => 'etc_sealed_bluelycan_leather_boots_piece_I00',
    'name' => 'Sealed Moirai Leather Boots Piece',
    'additionalname' => NULL,
    'description' => 'Key material used by Dwarves for crafting Sealed Moirai Leather Boots. Not valuable material for crafting old equipment.',
    'is_trade' => 1,
    'is_drop' => 1,
    'is_destruct' => 1,
    'crystal_type' => 'none',
    'consume_type' => 'consume_type_stackable',
  ],
  15659 => 
  [
    'item_id' => 15659,
    'icon' => 'etc_sealed_bluelycan_shoes_piece_I00',
    'name' => 'Sealed Moirai Shoes Piece',
    'additionalname' => NULL,
    'description' => 'Key material for Dwarves to make Sealed Moirai Shoes. Not valuable material for crafting old equipment.',
    'is_trade' => 1,
    'is_drop' => 1,
    'is_destruct' => 1,
    'crystal_type' => 'none',
    'consume_type' => 'consume_type_stackable',
  ],
  15660 => 
  [
    'item_id' => 15660,
    'icon' => 'etc_sealed_vesper_helmet_piece_I00',
    'name' => 'Sealed Vesper Helmet Piece',
    'additionalname' => NULL,
    'description' => 'Key material for Dwarves to make Sealed Vesper Helmet. Not valuable material for crafting old equipment.',
    'is_trade' => 1,
    'is_drop' => 1,
    'is_destruct' => 1,
    'crystal_type' => 'none',
    'consume_type' => 'consume_type_stackable',
  ],
  15661 => 
  [
    'item_id' => 15661,
    'icon' => 'etc_sealed_vesper_leather_helmet_piece_I00',
    'name' => 'Sealed Vesper Leather Helmet Piece',
    'additionalname' => NULL,
    'description' => 'Key material for Dwarves to make Sealed Vesper Leather Helmet. Not valuable material for crafting old equipment.',
    'is_trade' => 1,
    'is_drop' => 1,
    'is_destruct' => 1,
    'crystal_type' => 'none',
    'consume_type' => 'consume_type_stackable',
  ],
  15662 => 
  [
    'item_id' => 15662,
    'icon' => 'etc_sealed_vesper_circlet_piece_I00',
    'name' => 'Sealed Vesper Circlet Piece',
    'additionalname' => NULL,
    'description' => 'Key material for Dwarves to make Sealed Vesper Circlet. Not valuable material for crafting old equipment.',
    'is_trade' => 1,
    'is_drop' => 1,
    'is_destruct' => 1,
    'crystal_type' => 'none',
    'consume_type' => 'consume_type_stackable',
  ],
  15663 => 
  [
    'item_id' => 15663,
    'icon' => 'etc_sealed_vesper_cuirass_piece_I00',
    'name' => 'Sealed Vesper Breastplate Piece',
    'additionalname' => NULL,
    'description' => 'Key material for Dwarves to make Sealed Vesper Breastplate. Not valuable material for crafting old equipment.',
    'is_trade' => 1,
    'is_drop' => 1,
    'is_destruct' => 1,
    'crystal_type' => 'none',
    'consume_type' => 'consume_type_stackable',
  ],
  15664 => 
  [
    'item_id' => 15664,
    'icon' => 'etc_sealed_vesper_houberk_piece_I00',
    'name' => 'Sealed Vesper Leather Breastplate Piece',
    'additionalname' => NULL,
    'description' => 'Key material for Dwarves to make Sealed Vesper Leather Breastplate. Not valuable material for crafting old equipment.',
    'is_trade' => 1,
    'is_drop' => 1,
    'is_destruct' => 1,
    'crystal_type' => 'none',
    'consume_type' => 'consume_type_stackable',
  ],
  15665 => 
  [
    'item_id' => 15665,
    'icon' => 'etc_sealed_vesper_jaket_piece_I00',
    'name' => 'Sealed Vesper Tunic Piece',
    'additionalname' => NULL,
    'description' => 'Key material for Dwarves to make Sealed Vesper Tunic. Not valuable material for crafting old equipment.',
    'is_trade' => 1,
    'is_drop' => 1,
    'is_destruct' => 1,
    'crystal_type' => 'none',
    'consume_type' => 'consume_type_stackable',
  ],
  15666 => 
  [
    'item_id' => 15666,
    'icon' => 'etc_sealed_vesper_gaiter_piece_I00',
    'name' => 'Sealed Vesper Gaiters Piece',
    'additionalname' => NULL,
    'description' => 'Key material for Dwarves to make Sealed Vesper Gaiters. Not valuable material for crafting old equipment.',
    'is_trade' => 1,
    'is_drop' => 1,
    'is_destruct' => 1,
    'crystal_type' => 'none',
    'consume_type' => 'consume_type_stackable',
  ],
  15667 => 
  [
    'item_id' => 15667,
    'icon' => 'etc_sealed_vesper_gauntlet_piece_I00',
    'name' => 'Sealed Vesper Gauntlets Piece',
    'additionalname' => NULL,
    'description' => 'Key material for Dwarves to make Sealed Vesper Gauntlets. Not valuable material for crafting old equipment.',
    'is_trade' => 1,
    'is_drop' => 1,
    'is_destruct' => 1,
    'crystal_type' => 'none',
    'consume_type' => 'consume_type_stackable',
  ],
  15668 => 
  [
    'item_id' => 15668,
    'icon' => 'etc_sealed_vesper_boots_piece_I00',
    'name' => 'Sealed Vesper Boots Piece',
    'additionalname' => NULL,
    'description' => 'Key material for Dwarves to make Sealed Vesper Boots. Not valuable material for crafting old equipment.',
    'is_trade' => 1,
    'is_drop' => 1,
    'is_destruct' => 1,
    'crystal_type' => 'none',
    'consume_type' => 'consume_type_stackable',
  ],
  15669 => 
  [
    'item_id' => 15669,
    'icon' => 'etc_sealed_vesper_verteidiger_piece_I00',
    'name' => 'Sealed Vesper Shield Fragment',
    'additionalname' => NULL,
    'description' => 'Key material for Dwarves to make Sealed Vesper Shield. Not valuable material for crafting old equipment.',
    'is_trade' => 1,
    'is_drop' => 1,
    'is_destruct' => 1,
    'crystal_type' => 'none',
    'consume_type' => 'consume_type_stackable',
  ],
  15670 => 
  [
    'item_id' => 15670,
    'icon' => 'etc_sealed_vesper_leather_legging_piece_I00',
    'name' => 'Sealed Vesper Leather Leggings Piece',
    'additionalname' => NULL,
    'description' => 'Key material for Dwarves to make Sealed Vesper Leather Leggings. Not valuable material for crafting old equipment.',
    'is_trade' => 1,
    'is_drop' => 1,
    'is_destruct' => 1,
    'crystal_type' => 'none',
    'consume_type' => 'consume_type_stackable',
  ],
  15671 => 
  [
    'item_id' => 15671,
    'icon' => 'etc_sealed_vesper_leather_gloves_piece_I00',
    'name' => 'Sealed Vesper Leather Gloves Piece',
    'additionalname' => NULL,
    'description' => 'Key material for Dwarves to make Sealed Vesper Leather Gloves. Not valuable material for crafting old equipment.',
    'is_trade' => 1,
    'is_drop' => 1,
    'is_destruct' => 1,
    'crystal_type' => 'none',
    'consume_type' => 'consume_type_stackable',
  ],
  15672 => 
  [
    'item_id' => 15672,
    'icon' => 'etc_sealed_vesper_leather_boots_piece_I00',
    'name' => 'Sealed Vesper Leather Boots Piece',
    'additionalname' => NULL,
    'description' => 'Key material for Dwarves to make Sealed Vesper Leather Boots. Not valuable material for crafting old equipment.',
    'is_trade' => 1,
    'is_drop' => 1,
    'is_destruct' => 1,
    'crystal_type' => 'none',
    'consume_type' => 'consume_type_stackable',
  ],
  15673 => 
  [
    'item_id' => 15673,
    'icon' => 'etc_sealed_vesper_hose_piece_I00',
    'name' => 'Sealed Vesper Stockings Piece',
    'additionalname' => NULL,
    'description' => 'Key material for Dwarves to make Sealed Vesper Stockings. Not valuable material for crafting old equipment.',
    'is_trade' => 1,
    'is_drop' => 1,
    'is_destruct' => 1,
    'crystal_type' => 'none',
    'consume_type' => 'consume_type_stackable',
  ],
  15674 => 
  [
    'item_id' => 15674,
    'icon' => 'etc_sealed_vesper_gloves_piece_I00',
    'name' => 'Sealed Vesper Gloves Piece',
    'additionalname' => NULL,
    'description' => 'Key material for Dwarves to make Sealed Vesper Gloves. Not valuable material for crafting old equipment.',
    'is_trade' => 1,
    'is_drop' => 1,
    'is_destruct' => 1,
    'crystal_type' => 'none',
    'consume_type' => 'consume_type_stackable',
  ],
  15675 => 
  [
    'item_id' => 15675,
    'icon' => 'etc_sealed_vesper_shoes_piece_I00',
    'name' => 'Sealed Vesper Shoes Piece',
    'additionalname' => NULL,
    'description' => 'Key material for Dwarves to make Sealed Vesper Shoes. Not valuable material for crafting old equipment.',
    'is_trade' => 1,
    'is_drop' => 1,
    'is_destruct' => 1,
    'crystal_type' => 'none',
    'consume_type' => 'consume_type_stackable',
  ],
  15676 => 
  [
    'item_id' => 15676,
    'icon' => 'weapon_tysandy_blade_i00',
    'name' => 'Triumph Sword',
    'additionalname' => NULL,
    'description' => '<Special Option> Critical Rate +78.9. Increases damage inflicted during PvP. Has a chance of recovering CP during an attack. No Soul Crystal option.',
    'is_trade' => 1,
    'is_drop' => 1,
    'is_destruct' => 1,
    'crystal_type' => 'r',
    'consume_type' => 'consume_type_normal',
  ],
  15677 => 
  [
    'item_id' => 15677,
    'icon' => 'weapon_tysandy_dagger_i00',
    'name' => 'Triumph Knife',
    'additionalname' => NULL,
    'description' => '<Special Option> Critical Rate +82.1. Increases damage inflicted during PvP. Has a chance of inflicting additional damage during an attack. No Soul Crystal option.',
    'is_trade' => 1,
    'is_drop' => 1,
    'is_destruct' => 1,
    'crystal_type' => 'r',
    'consume_type' => 'consume_type_normal',
  ],
  15678 => 
  [
    'item_id' => 15678,
    'icon' => 'weapon_tysandy_hammer_i00',
    'name' => 'Triumph Club',
    'additionalname' => NULL,
    'description' => '<Special Option> Critical Rate +78.9. Increases damage inflicted during PvP. Has a chance of recovering CP during an attack. No Soul Crystal option.',
    'is_trade' => 1,
    'is_drop' => 1,
    'is_destruct' => 1,
    'crystal_type' => 'r',
    'consume_type' => 'consume_type_normal',
  ],
  15679 => 
  [
    'item_id' => 15679,
    'icon' => 'weapon_tysandy_crusher_i00',
    'name' => 'Triumph Crusher',
    'additionalname' => NULL,
    'description' => '<Special Option> Critical Rate +78.9. Increases damage inflicted during PvP. Has a chance of inflicting additional damage during an attack. No Soul Crystal option.',
    'is_trade' => 1,
    'is_drop' => 1,
    'is_destruct' => 1,
    'crystal_type' => 'r',
    'consume_type' => 'consume_type_normal',
  ],
  15680 => 
  [
    'item_id' => 15680,
    'icon' => 'weapon_tysandy_two_hand_sword_i00',
    'name' => 'Triumph Blade',
    'additionalname' => NULL,
    'description' => '<Special Option> Critical Rate +78.9. Increases damage inflicted during PvP. Has a chance of canceling 1 or more of the targets enhanced status, or of decreasing the targets Shield Defense during an attack. No Soul Crystal option.',
    'is_trade' => 1,
    'is_drop' => 1,
    'is_destruct' => 1,
    'crystal_type' => 'r',
    'consume_type' => 'consume_type_normal',
  ],
  15681 => 
  [
    'item_id' => 15681,
    'icon' => 'weapon_tysandy_jamadhr_i00',
    'name' => 'Triumph Bagh-Nakh',
    'additionalname' => NULL,
    'description' => '<Special Option> Critical Rate +75.7. Increases damage inflicted during PvP. Has a chance of inflicting additional damage during an attack. No Soul Crystal option.',
    'is_trade' => 1,
    'is_drop' => 1,
    'is_destruct' => 1,
    'crystal_type' => 'r',
    'consume_type' => 'consume_type_normal',
  ],
  15682 => 
  [
    'item_id' => 15682,
    'icon' => 'weapon_tysandy_spear_i00',
    'name' => 'Triumph Halberd',
    'additionalname' => NULL,
    'description' => '<Special Option> P. Atk. +377. Increases damage inflicted during PvP. Has a chance of canceling 1 or more of the targets enhanced status, or of decreasing the targets Shield Defense during an attack. No Soul Crystal option.',
    'is_trade' => 1,
    'is_drop' => 1,
    'is_destruct' => 1,
    'crystal_type' => 'r',
    'consume_type' => 'consume_type_normal',
  ],
  15683 => 
  [
    'item_id' => 15683,
    'icon' => 'weapon_tysandy_staff_i00',
    'name' => 'Triumph Mace',
    'additionalname' => NULL,
    'description' => '<Special Option> Casting Spd. +15%. Increases damage inflicted during PvP. Has a chance of increasing Casting Spd. when attacked. No Soul Crystal option.',
    'is_trade' => 1,
    'is_drop' => 1,
    'is_destruct' => 1,
    'crystal_type' => 'r',
    'consume_type' => 'consume_type_normal',
  ],
  15684 => 
  [
    'item_id' => 15684,
    'icon' => 'weapon_tysandy_twohand_staff_i00',
    'name' => 'Triumph Staff',
    'additionalname' => NULL,
    'description' => '<Special Option> Casting Spd. +15%. Increases damage inflicted during PvP. Has a chance of increasing Casting Spd. when attacked. No Soul Crystal option.',
    'is_trade' => 1,
    'is_drop' => 1,
    'is_destruct' => 1,
    'crystal_type' => 'r',
    'consume_type' => 'consume_type_normal',
  ],
  15685 => 
  [
    'item_id' => 15685,
    'icon' => 'weapon_tysandy_magic_sword_i00',
    'name' => 'Triumph Phantom',
    'additionalname' => NULL,
    'description' => '<Special Option> Casting Spd. +15%. Increases damage inflicted during PvP. Has a chance of increasing Casting Spd. when attacked. No Soul Crystal option.',
    'is_trade' => 1,
    'is_drop' => 1,
    'is_destruct' => 1,
    'crystal_type' => 'r',
    'consume_type' => 'consume_type_normal',
  ],
  15686 => 
  [
    'item_id' => 15686,
    'icon' => 'weapon_tysandy_bow_i00',
    'name' => 'Triumph Bow',
    'additionalname' => NULL,
    'description' => '<Special Option> Critical Rate +78.9. Increases damage inflicted during PvP. Has a chance of increasing Atk. Spd. of bows/ crossbows during an attack. No Soul Crystal option.',
    'is_trade' => 1,
    'is_drop' => 1,
    'is_destruct' => 1,
    'crystal_type' => 'r',
    'consume_type' => 'consume_type_normal',
  ],
  15687 => 
  [
    'item_id' => 15687,
    'icon' => 'weapon_tysandy_rapier_i00',
    'name' => 'Triumph Rapier',
    'additionalname' => NULL,
    'description' => 'Cannot be transferred between servers.',
    'is_trade' => 1,
    'is_drop' => 1,
    'is_destruct' => 1,
    'crystal_type' => 'r',
    'consume_type' => 'consume_type_normal',
  ],
  15688 => 
  [
    'item_id' => 15688,
    'icon' => 'weapon_tysandy_ancient_sword_i00',
    'name' => 'Triumph Ancient Sword',
    'additionalname' => NULL,
    'description' => 'Cannot be transferred between servers.',
    'is_trade' => 1,
    'is_drop' => 1,
    'is_destruct' => 1,
    'crystal_type' => 'r',
    'consume_type' => 'consume_type_normal',
  ],
  15689 => 
  [
    'item_id' => 15689,
    'icon' => 'seapon_tysandy_crossbow_i00',
    'name' => 'Triumph Crossbow',
    'additionalname' => NULL,
    'description' => 'Cannot be transferred between servers.',
    'is_trade' => 1,
    'is_drop' => 1,
    'is_destruct' => 1,
    'crystal_type' => 'r',
    'consume_type' => 'consume_type_normal',
  ],
  15690 => 
  [
    'item_id' => 15690,
    'icon' => 'etc_key_i00',
    'name' => 'Secret Gate Key',
    'additionalname' => NULL,
    'description' => 'Key that opens a secret gate',
    'is_trade' => 1,
    'is_drop' => 1,
    'is_destruct' => 1,
    'crystal_type' => 'crystal_free',
    'consume_type' => 'consume_type_stackable',
  ],
  15691 => 
  [
    'item_id' => 15691,
    'icon' => 'etc_sealed_vesper_sigil_piece_I00',
    'name' => 'Sealed Vesper Sigil Piece',
    'additionalname' => NULL,
    'description' => 'Key material for Dwarves to make Sealed Vesper Sigil. Not valuable material for crafting old equipment.',
    'is_trade' => 1,
    'is_drop' => 1,
    'is_destruct' => 1,
    'crystal_type' => 'none',
    'consume_type' => 'consume_type_stackable',
  ],
  15692 => 
  [
    'item_id' => 15692,
    'icon' => 'etc_sealed_bluelycan_sigil_piece_I00',
    'name' => 'Sealed Moirai Sigil Piece',
    'additionalname' => NULL,
    'description' => 'Key material for Dwarves to make Sealed Moirai Sigil. Not valuable material for crafting old equipment.',
    'is_trade' => 1,
    'is_drop' => 1,
    'is_destruct' => 1,
    'crystal_type' => 'none',
    'consume_type' => 'consume_type_stackable',
  ],
  15693 => 
  [
    'item_id' => 15693,
    'icon' => 'etc_sealed_bluelycan_shield_piece_I01',
    'name' => 'Sealed Moirai Shield Fragment',
    'additionalname' => NULL,
    'description' => 'Key material for Dwarves to make Sealed Moirai Shield. Not valuable material for crafting old equipment.',
    'is_trade' => 1,
    'is_drop' => 1,
    'is_destruct' => 1,
    'crystal_type' => 'none',
    'consume_type' => 'consume_type_stackable',
  ],
  15694 => 
  [
    'item_id' => 15694,
    'icon' => 'armor_helmet_i02',
    'name' => 'Sealed Moirai Helmet ',
    'additionalname' => NULL,
    'description' => 'Old and not very useful equipment.',
    'is_trade' => 1,
    'is_drop' => 1,
    'is_destruct' => 1,
    'crystal_type' => 's80',
    'consume_type' => 'consume_type_normal',
  ],
  15695 => 
  [
    'item_id' => 15695,
    'icon' => 'armor_helmet_i02',
    'name' => 'Sealed Moirai Helmet ',
    'additionalname' => NULL,
    'description' => 'Old and not very useful equipment.',
    'is_trade' => 1,
    'is_drop' => 1,
    'is_destruct' => 1,
    'crystal_type' => 's80',
    'consume_type' => 'consume_type_normal',
  ],
  15696 => 
  [
    'item_id' => 15696,
    'icon' => 'armor_circlet_i02',
    'name' => 'Sealed Moirai Circlet ',
    'additionalname' => NULL,
    'description' => 'Old and not very useful equipment.',
    'is_trade' => 1,
    'is_drop' => 1,
    'is_destruct' => 1,
    'crystal_type' => 's80',
    'consume_type' => 'consume_type_normal',
  ],
  15697 => 
  [
    'item_id' => 15697,
    'icon' => 'armor_t94_u_i02',
    'name' => 'Sealed Moirai Breastplate ',
    'additionalname' => NULL,
    'description' => 'Old and not very useful equipment.',
    'is_trade' => 1,
    'is_drop' => 1,
    'is_destruct' => 1,
    'crystal_type' => 's80',
    'consume_type' => 'consume_type_normal',
  ],
  15698 => 
  [
    'item_id' => 15698,
    'icon' => 'armor_t95_u_i02',
    'name' => 'Sealed Moirai Breastplate ',
    'additionalname' => NULL,
    'description' => 'Old and not very useful equipment.',
    'is_trade' => 1,
    'is_drop' => 1,
    'is_destruct' => 1,
    'crystal_type' => 's80',
    'consume_type' => 'consume_type_normal',
  ],
  15699 => 
  [
    'item_id' => 15699,
    'icon' => 'armor_t96_u_i02',
    'name' => 'Sealed Moirai Tunic ',
    'additionalname' => NULL,
    'description' => 'Old and not very useful equipment.',
    'is_trade' => 1,
    'is_drop' => 1,
    'is_destruct' => 1,
    'crystal_type' => 's80',
    'consume_type' => 'consume_type_normal',
  ],
];