<?php return [
  18200 => 
  [
    'item_id' => 18200,
    'icon' => 'armor_t403_b_i00',
    'name' => 'Unidentified Seraph Shoes',
    'additionalname' => 'Robe',
    'description' => 'Seraph Shoes in an Unidentified state. Double-click the item to identify it. The acquired item can be Blessed, Standard, or Bound. (Type: Boots / robe]',
    'is_trade' => 1,
    'is_drop' => 1,
    'is_destruct' => 1,
    'crystal_type' => 'r95',
    'consume_type' => 'consume_type_normal',
  ],
  18201 => 
  [
    'item_id' => 18201,
    'icon' => 'airtoil_i00',
    'name' => 'Unidentified Seraph Sigil',
    'additionalname' => 'Robe',
    'description' => 'A Seraph Sigil in an Unidentified state. Double-click the item to identify it. The acquired item can be Blessed, Standard, or Bound. (Type: Shield / robe]',
    'is_trade' => 1,
    'is_drop' => 1,
    'is_destruct' => 1,
    'crystal_type' => 'r95',
    'consume_type' => 'consume_type_normal',
  ],
  18202 => 
  [
    'item_id' => 18202,
    'icon' => 'r95_necklace_i00',
    'name' => 'Unidentified Seraph Necklace',
    'additionalname' => '',
    'description' => 'A Seraph Necklace in an Unidentified state. Double-click the item to identify it. The acquired item can be Blessed, Standard, or Bound. (Type: Necklace]',
    'is_trade' => 1,
    'is_drop' => 1,
    'is_destruct' => 1,
    'crystal_type' => 'r95',
    'consume_type' => 'consume_type_normal',
  ],
  18203 => 
  [
    'item_id' => 18203,
    'icon' => 'r95_earring_i00',
    'name' => 'Unidentified Seraph Earring',
    'additionalname' => '',
    'description' => 'A Seraph Earring in an Unidentified state. Double-click the item to identify it. The acquired item can be Blessed, Standard, or Bound. (Type: Earring]',
    'is_trade' => 1,
    'is_drop' => 1,
    'is_destruct' => 1,
    'crystal_type' => 'r95',
    'consume_type' => 'consume_type_normal',
  ],
  18204 => 
  [
    'item_id' => 18204,
    'icon' => 'r95_ring_i00',
    'name' => 'Unidentified Seraph Ring',
    'additionalname' => '',
    'description' => 'A Seraph Ring in an Unidentified state. Double-click the item to identify it. The acquired item can be Blessed, Standard, or Bound. (Type: Ring]',
    'is_trade' => 1,
    'is_drop' => 1,
    'is_destruct' => 1,
    'crystal_type' => 'r95',
    'consume_type' => 'consume_type_normal',
  ],
  18205 => 
  [
    'item_id' => 18205,
    'icon' => 'weapon_stanpid_i00',
    'name' => 'Unidentified Amaranthine Shaper',
    'additionalname' => '',
    'description' => 'An Amaranthine Shaper in an Unidentified state. Double-click the item to identify it. The acquired item can be Blessed, Standard, or Bound. (Type: one-handed weapon / dagger]',
    'is_trade' => 1,
    'is_drop' => 1,
    'is_destruct' => 1,
    'crystal_type' => 'r99',
    'consume_type' => 'consume_type_normal',
  ],
  18206 => 
  [
    'item_id' => 18206,
    'icon' => 'weapon_plenitas_i00',
    'name' => 'Unidentified Amaranthine Cutter',
    'additionalname' => '',
    'description' => 'An Amaranthine Cutter in an Unidentified state. Double-click the item to identify it. The acquired item can be Blessed, Standard, or Bound. (Type: one-handed weapon / sword]',
    'is_trade' => 1,
    'is_drop' => 1,
    'is_destruct' => 1,
    'crystal_type' => 'r99',
    'consume_type' => 'consume_type_normal',
  ],
  18207 => 
  [
    'item_id' => 18207,
    'icon' => 'weapon_bauen_i00',
    'name' => 'Unidentified Amaranthine Slasher',
    'additionalname' => '',
    'description' => 'An Amaranthine Slasher in an Unidentified state. Double-click the item to identify it. The acquired item can be Blessed, Standard, or Bound. (Type: two-handed weapon / sword]',
    'is_trade' => 1,
    'is_drop' => 1,
    'is_destruct' => 1,
    'crystal_type' => 'r99',
    'consume_type' => 'consume_type_normal',
  ],
  18208 => 
  [
    'item_id' => 18208,
    'icon' => 'weapon_qutram_i00',
    'name' => 'Unidentified Amaranthine Avenger',
    'additionalname' => '',
    'description' => 'An Amaranthine Avenger in an Unidentified state. Double-click the item to identify it. The acquired item can be Blessed, Standard, or Bound. (Type: one-handed weapon / blunt]',
    'is_trade' => 1,
    'is_drop' => 1,
    'is_destruct' => 1,
    'crystal_type' => 'r99',
    'consume_type' => 'consume_type_normal',
  ],
  18209 => 
  [
    'item_id' => 18209,
    'icon' => 'weapon_durga_i00',
    'name' => 'Unidentified Amaranthine Fighter',
    'additionalname' => '',
    'description' => 'An Amaranthine Fighter in an Unidentified state. Double-click the item to identify it. The acquired item can be Blessed, Standard, or Bound. (Type: two-handed weapon / combat]',
    'is_trade' => 1,
    'is_drop' => 1,
    'is_destruct' => 1,
    'crystal_type' => 'r99',
    'consume_type' => 'consume_type_normal',
  ],
  18210 => 
  [
    'item_id' => 18210,
    'icon' => 'weapon_crabel_i00',
    'name' => 'Unidentified Amaranthine Stormer',
    'additionalname' => '',
    'description' => 'An Amaranthine Stormer in an Unidentified state. Double-click the item to identify it. The acquired item can be Blessed, Standard, or Bound. (Type: two-handed weapon / spear]',
    'is_trade' => 1,
    'is_drop' => 1,
    'is_destruct' => 1,
    'crystal_type' => 'r99',
    'consume_type' => 'consume_type_normal',
  ],
  18211 => 
  [
    'item_id' => 18211,
    'icon' => 'weapon_castron_i00',
    'name' => 'Unidentified Amaranthine Thrower',
    'additionalname' => '',
    'description' => 'An Amaranthine Thrower in an Unidentified state. Double-click the item to identify it. The acquired item can be Blessed, Standard, or Bound. (Type: two-handed weapon / bow]',
    'is_trade' => 1,
    'is_drop' => 1,
    'is_destruct' => 1,
    'crystal_type' => 'r99',
    'consume_type' => 'consume_type_normal',
  ],
  18212 => 
  [
    'item_id' => 18212,
    'icon' => 'weapon_stilla_i00',
    'name' => 'Unidentified Amaranthine Shooter',
    'additionalname' => '',
    'description' => 'An Amaranthine Shooter in an Unidentified state. Double-click the item to identify it. The acquired item can be Blessed, Standard, or Bound. (Type: two-handed weapon / crossbow / bow]',
    'is_trade' => 1,
    'is_drop' => 1,
    'is_destruct' => 1,
    'crystal_type' => 'r99',
    'consume_type' => 'consume_type_normal',
  ],
  18213 => 
  [
    'item_id' => 18213,
    'icon' => 'weaon_serapear_i00',
    'name' => 'Unidentified Amaranthine Buster',
    'additionalname' => '',
    'description' => 'An Amaranthine Buster in an Unidentified state. Double-click the item to identify it. The acquired item can be Blessed, Standard, or Bound. (Type: one-handed weapon / sword]',
    'is_trade' => 1,
    'is_drop' => 1,
    'is_destruct' => 1,
    'crystal_type' => 'r99',
    'consume_type' => 'consume_type_normal',
  ],
  18214 => 
  [
    'item_id' => 18214,
    'icon' => 'weapon_pilia_i00',
    'name' => 'Unidentified Amaranthine Caster',
    'additionalname' => '',
    'description' => 'An Amaranthine Caster in an Unidentified state. Double-click the item to identify it. The acquired item can be Blessed, Standard, or Bound. (Type: one-handed weapon / blunt]',
    'is_trade' => 1,
    'is_drop' => 1,
    'is_destruct' => 1,
    'crystal_type' => 'r99',
    'consume_type' => 'consume_type_normal',
  ],
  18215 => 
  [
    'item_id' => 18215,
    'icon' => 'weapon_shaelon_i00',
    'name' => 'Unidentified Amaranthine Retributer',
    'additionalname' => '',
    'description' => 'An Amaranthine Retributer in an Unidentified state. Double-click the item to identify it. The acquired item can be Blessed, Standard, or Bound. (Type: two-handed weapon / blunt]',
    'is_trade' => 1,
    'is_drop' => 1,
    'is_destruct' => 1,
    'crystal_type' => 'r99',
    'consume_type' => 'consume_type_normal',
  ],
  18216 => 
  [
    'item_id' => 18216,
    'icon' => 'weapon_r_dualsword_i00',
    'name' => 'Unidentified Amaranthine Dualsword',
    'additionalname' => '',
    'description' => 'Amaranthine Dualsword in an Unidentified state. Double-click the item to identify it. The acquired item can be Blessed, Standard, or Bound. (Type: two-handed weapon / dualsword]',
    'is_trade' => 1,
    'is_drop' => 1,
    'is_destruct' => 1,
    'crystal_type' => 'r99',
    'consume_type' => 'consume_type_normal',
  ],
  18217 => 
  [
    'item_id' => 18217,
    'icon' => 'weapon_r_dualdagger_i00',
    'name' => 'Unidentified Amaranthine Dual Dagger',
    'additionalname' => '',
    'description' => 'An Amaranthine Dual Dagger in an Unidentified state. Double-click the item to identify it. The acquired item can be Blessed, Standard, or Bound. (Type: two-handed weapon / dualsword / dagger]',
    'is_trade' => 1,
    'is_drop' => 1,
    'is_destruct' => 1,
    'crystal_type' => 'r99',
    'consume_type' => 'consume_type_normal',
  ],
  18218 => 
  [
    'item_id' => 18218,
    'icon' => 'weapon_r_dualblunt_i00',
    'name' => 'Unidentified Amaranthine Dual Blunt Weapon',
    'additionalname' => '',
    'description' => 'An Amaranthine Dual Blunt Weapon in an Unidentified state. Double-click the item to identify it. The acquired item can be Blessed, Standard, or Bound. (Type: two-handed weapon / dualsword / blunt]',
    'is_trade' => 1,
    'is_drop' => 1,
    'is_destruct' => 1,
    'crystal_type' => 'r99',
    'consume_type' => 'consume_type_normal',
  ],
  18219 => 
  [
    'item_id' => 18219,
    'icon' => 'armor_helmet_i00',
    'name' => 'Unidentified Eternal Helmet',
    'additionalname' => 'Heavy Armor',
    'description' => 'An Eternal Helmet in an Unidentified state. Double-click the item to identify it. The acquired item can be Blessed, Standard, or Bound. (Type: Helmet / heavy armor]',
    'is_trade' => 1,
    'is_drop' => 1,
    'is_destruct' => 1,
    'crystal_type' => 'r99',
    'consume_type' => 'consume_type_normal',
  ],
  18220 => 
  [
    'item_id' => 18220,
    'icon' => 'armor_t701_u_i00',
    'name' => 'Unidentified Eternal Breastplate',
    'additionalname' => 'Heavy Armor',
    'description' => 'An Eternal Breastplate in an Unidentified state. Double-click the item to identify it. The acquired item can be Blessed, Standard, or Bound. (Type: upper / heavy armor]',
    'is_trade' => 1,
    'is_drop' => 1,
    'is_destruct' => 1,
    'crystal_type' => 'r99',
    'consume_type' => 'consume_type_normal',
  ],
  18221 => 
  [
    'item_id' => 18221,
    'icon' => 'armor_t701_l_i00',
    'name' => 'Unidentified Eternal Gaiters',
    'additionalname' => 'Heavy Armor',
    'description' => 'Eternal Gaiters in an Unidentified state. Double-click the item to identify it. The acquired item can be Blessed, Standard, or Bound. (Type: lower / heavy armor]',
    'is_trade' => 1,
    'is_drop' => 1,
    'is_destruct' => 1,
    'crystal_type' => 'r99',
    'consume_type' => 'consume_type_normal',
  ],
  18222 => 
  [
    'item_id' => 18222,
    'icon' => 'armor_t701_g_i00',
    'name' => 'Unidentified Eternal Gauntlets',
    'additionalname' => 'Heavy Armor',
    'description' => 'An Eternal Gauntlets in an Unidentified state. Double-click the item to identify it. The acquired item can be Blessed, Standard, or Bound. (Type: Gloves / heavy armor]',
    'is_trade' => 1,
    'is_drop' => 1,
    'is_destruct' => 1,
    'crystal_type' => 'r99',
    'consume_type' => 'consume_type_normal',
  ],
  18223 => 
  [
    'item_id' => 18223,
    'icon' => 'armor_t701_b_i00',
    'name' => 'Unidentified Eternal Boots',
    'additionalname' => 'Heavy Armor',
    'description' => 'Eternal Boots in an Unidentified state. Double-click the item to identify it. The acquired item can be Blessed, Standard, or Bound. (Type: Boots / heavy armor]',
    'is_trade' => 1,
    'is_drop' => 1,
    'is_destruct' => 1,
    'crystal_type' => 'r99',
    'consume_type' => 'consume_type_normal',
  ],
  18224 => 
  [
    'item_id' => 18224,
    'icon' => 'weapon_akra_i00',
    'name' => 'Unidentified Eternal Shield',
    'additionalname' => 'Heavy Armor',
    'description' => 'An Eternal Shield in an Unidentified state. Double-click the item to identify it. The acquired item can be Blessed, Standard, or Bound. (Type: Shield / heavy armor]',
    'is_trade' => 1,
    'is_drop' => 1,
    'is_destruct' => 1,
    'crystal_type' => 'r99',
    'consume_type' => 'consume_type_normal',
  ],
  18225 => 
  [
    'item_id' => 18225,
    'icon' => 'armor_leather_helmet_i00',
    'name' => 'Unidentified Eternal Leather Helmet',
    'additionalname' => 'Light Armor',
    'description' => 'An Eternal Leather Helmet in an Unidentified state. Double-click the item to identify it. The acquired item can be Blessed, Standard, or Bound. (Type: Helmet / light armor]',
    'is_trade' => 1,
    'is_drop' => 1,
    'is_destruct' => 1,
    'crystal_type' => 'r99',
    'consume_type' => 'consume_type_normal',
  ],
  18226 => 
  [
    'item_id' => 18226,
    'icon' => 'armor_t702_u_i00',
    'name' => 'Unidentified Eternal Leather Armor',
    'additionalname' => 'Light Armor',
    'description' => 'An Eternal Leather Armor in an Unidentified state. Double-click the item to identify it. The acquired item can be Blessed, Standard, or Bound. (Type: upper / light armor]',
    'is_trade' => 1,
    'is_drop' => 1,
    'is_destruct' => 1,
    'crystal_type' => 'r99',
    'consume_type' => 'consume_type_normal',
  ],
  18227 => 
  [
    'item_id' => 18227,
    'icon' => 'armor_t702_l_i00',
    'name' => 'Unidentified Eternal Leather Leggings',
    'additionalname' => 'Light Armor',
    'description' => 'Eternal Leather Leggings in an Unidentified state. Double-click the item to identify it. The acquired item can be Blessed, Standard, or Bound. (Type: lower / light armor]',
    'is_trade' => 1,
    'is_drop' => 1,
    'is_destruct' => 1,
    'crystal_type' => 'r99',
    'consume_type' => 'consume_type_normal',
  ],
  18228 => 
  [
    'item_id' => 18228,
    'icon' => 'armor_t702_g_i00',
    'name' => 'Unidentified Eternal Leather Gloves',
    'additionalname' => 'Light Armor',
    'description' => 'Eternal Leather Gloves in an Unidentified state. Double-click the item to identify it. The acquired item can be Blessed, Standard, or Bound. (Type: Gloves / light armor]',
    'is_trade' => 1,
    'is_drop' => 1,
    'is_destruct' => 1,
    'crystal_type' => 'r99',
    'consume_type' => 'consume_type_normal',
  ],
  18229 => 
  [
    'item_id' => 18229,
    'icon' => 'armor_t702_b_i00',
    'name' => 'Unidentified Eternal Leather Boots',
    'additionalname' => 'Light Armor',
    'description' => 'Eternal Leather Boots in an Unidentified state. Double-click the item to identify it. The acquired item can be Blessed, Standard, or Bound. (Type: Boots / light armor]',
    'is_trade' => 1,
    'is_drop' => 1,
    'is_destruct' => 1,
    'crystal_type' => 'r99',
    'consume_type' => 'consume_type_normal',
  ],
  18230 => 
  [
    'item_id' => 18230,
    'icon' => 'armor_circlet_i00',
    'name' => 'Unidentified Eternal Circlet',
    'additionalname' => 'Robe',
    'description' => 'An Eternal Circlet in an Unidentified state. Double-click the item to identify it. The acquired item can be Blessed, Standard, or Bound. (Type: Helmet / robe]',
    'is_trade' => 1,
    'is_drop' => 1,
    'is_destruct' => 1,
    'crystal_type' => 'r99',
    'consume_type' => 'consume_type_normal',
  ],
  18231 => 
  [
    'item_id' => 18231,
    'icon' => 'armor_t703_u_i00',
    'name' => 'Unidentified Eternal Tunic',
    'additionalname' => 'Robe',
    'description' => 'An Eternal Tunic in an Unidentified state. Double-click the item to identify it. The acquired item can be Blessed, Standard, or Bound. (Type: upper / robe]',
    'is_trade' => 1,
    'is_drop' => 1,
    'is_destruct' => 1,
    'crystal_type' => 'r99',
    'consume_type' => 'consume_type_normal',
  ],
  18232 => 
  [
    'item_id' => 18232,
    'icon' => 'armor_t703_l_i00',
    'name' => 'Unidentified Eternal Stockings',
    'additionalname' => 'Robe',
    'description' => 'Eternal Stockings in an Unidentified state. Double-click the item to identify it. The acquired item can be Blessed, Standard, or Bound. (Type: lower / robe]',
    'is_trade' => 1,
    'is_drop' => 1,
    'is_destruct' => 1,
    'crystal_type' => 'r99',
    'consume_type' => 'consume_type_normal',
  ],
  18233 => 
  [
    'item_id' => 18233,
    'icon' => 'armor_t703_g_i00',
    'name' => 'Unidentified Eternal Gloves',
    'additionalname' => 'Robe',
    'description' => 'Eternal Gloves in an Unidentified state. Double-click the item to identify it. The acquired item can be Blessed, Standard, or Bound. (Type: Gloves / robe]',
    'is_trade' => 1,
    'is_drop' => 1,
    'is_destruct' => 1,
    'crystal_type' => 'r99',
    'consume_type' => 'consume_type_normal',
  ],
  18234 => 
  [
    'item_id' => 18234,
    'icon' => 'armor_t703_b_i00',
    'name' => 'Unidentified Eternal Shoes',
    'additionalname' => 'Robe',
    'description' => 'Eternal Shoes in an Unidentified state. Double-click the item to identify it. The acquired item can be Blessed, Standard, or Bound. (Type: Boots / robe]',
    'is_trade' => 1,
    'is_drop' => 1,
    'is_destruct' => 1,
    'crystal_type' => 'r99',
    'consume_type' => 'consume_type_normal',
  ],
  18235 => 
  [
    'item_id' => 18235,
    'icon' => 'elos_i00',
    'name' => 'Unidentified Eternal Sigil',
    'additionalname' => 'Robe',
    'description' => 'An Eternal Sigil in an Unidentified state. Double-click the item to identify it. The acquired item can be Blessed, Standard, or Bound. (Type: Shield / robe]',
    'is_trade' => 1,
    'is_drop' => 1,
    'is_destruct' => 1,
    'crystal_type' => 'r99',
    'consume_type' => 'consume_type_normal',
  ],
  18236 => 
  [
    'item_id' => 18236,
    'icon' => 'r991_necklace_i00',
    'name' => 'Unidentified Eternal Necklace',
    'additionalname' => '',
    'description' => 'An Eternal Necklace in an Unidentified state. Double-click the item to identify it. The acquired item can be Blessed, Standard, or Bound. (Type: Necklace]',
    'is_trade' => 1,
    'is_drop' => 1,
    'is_destruct' => 1,
    'crystal_type' => 'r99',
    'consume_type' => 'consume_type_normal',
  ],
  18237 => 
  [
    'item_id' => 18237,
    'icon' => 'r991_earring_i00',
    'name' => 'Unidentified Eternal Earring',
    'additionalname' => '',
    'description' => 'An Eternal Earring in an Unidentified state. Double-click the item to identify it. The acquired item can be Blessed, Standard, or Bound. (Type: Earring]',
    'is_trade' => 1,
    'is_drop' => 1,
    'is_destruct' => 1,
    'crystal_type' => 'r99',
    'consume_type' => 'consume_type_normal',
  ],
  18238 => 
  [
    'item_id' => 18238,
    'icon' => 'r991_ring_i00',
    'name' => 'Unidentified Eternal Ring',
    'additionalname' => '',
    'description' => 'An Eternal Ring in an Unidentified state. Double-click the item to identify it. The acquired item can be Blessed, Standard, or Bound. (Type: Ring]',
    'is_trade' => 1,
    'is_drop' => 1,
    'is_destruct' => 1,
    'crystal_type' => 'r99',
    'consume_type' => 'consume_type_normal',
  ],
  18239 => 
  [
    'item_id' => 18239,
    'icon' => 'weapon_vesper_shaper_i00',
    'name' => 'Unidentified Kaliel Shaper',
    'additionalname' => '',
    'description' => 'A Kaliel Shaper in an Unidentified state. Double-click the item to identify it. The acquired item can be Blessed, Standard, or Bound. (Type: one-handed weapon / dagger]',
    'is_trade' => 1,
    'is_drop' => 1,
    'is_destruct' => 1,
    'crystal_type' => 'r99',
    'consume_type' => 'consume_type_normal',
  ],
  18240 => 
  [
    'item_id' => 18240,
    'icon' => 'weapon_vesper_cutter_i00',
    'name' => 'Unidentified Kaliel Cutter',
    'additionalname' => '',
    'description' => 'A Kaliel Cutter in an Unidentified state. Double-click the item to identify it. The acquired item can be Blessed, Standard, or Bound. (Type: one-handed weapon / sword]',
    'is_trade' => 1,
    'is_drop' => 1,
    'is_destruct' => 1,
    'crystal_type' => 'r99',
    'consume_type' => 'consume_type_normal',
  ],
  18241 => 
  [
    'item_id' => 18241,
    'icon' => 'weapon_vesper_slasher_i00',
    'name' => 'Unidentified Kaliel Slasher',
    'additionalname' => '',
    'description' => 'A Kaliel Slasher in an Unidentified state. Double-click the item to identify it. The acquired item can be Blessed, Standard, or Bound. (Type: two-handed weapon / sword]',
    'is_trade' => 1,
    'is_drop' => 1,
    'is_destruct' => 1,
    'crystal_type' => 'r99',
    'consume_type' => 'consume_type_normal',
  ],
  18242 => 
  [
    'item_id' => 18242,
    'icon' => 'weapon_vesper_avenger_i00',
    'name' => 'Unidentified Kaliel Avenger',
    'additionalname' => '',
    'description' => 'A Kaliel Avenger in an Unidentified state. Double-click the item to identify it. The acquired item can be Blessed, Standard, or Bound. (Type: one-handed weapon / blunt]',
    'is_trade' => 1,
    'is_drop' => 1,
    'is_destruct' => 1,
    'crystal_type' => 'r99',
    'consume_type' => 'consume_type_normal',
  ],
  18243 => 
  [
    'item_id' => 18243,
    'icon' => 'weapon_octoclaw_i00',
    'name' => 'Unidentified Kaliel Fighter',
    'additionalname' => '',
    'description' => 'A Kaliel Fighter in an Unidentified state. Double-click the item to identify it. The acquired item can be Blessed, Standard, or Bound. (Type: two-handed weapon / combat]',
    'is_trade' => 1,
    'is_drop' => 1,
    'is_destruct' => 1,
    'crystal_type' => 'r99',
    'consume_type' => 'consume_type_normal',
  ],
  18244 => 
  [
    'item_id' => 18244,
    'icon' => 'weapon_vesper_stormer_i00',
    'name' => 'Unidentified Kaliel Stormer',
    'additionalname' => '',
    'description' => 'A Kaliel Stormer in an Unidentified state. Double-click the item to identify it. The acquired item can be Blessed, Standard, or Bound. (Type: two-handed weapon / spear]',
    'is_trade' => 1,
    'is_drop' => 1,
    'is_destruct' => 1,
    'crystal_type' => 'r99',
    'consume_type' => 'consume_type_normal',
  ],
  18245 => 
  [
    'item_id' => 18245,
    'icon' => 'weapon_vesper_thrower_i00',
    'name' => 'Unidentified Kaliel Thrower',
    'additionalname' => '',
    'description' => 'A Kaliel Thrower in an Unidentified state. Double-click the item to identify it. The acquired item can be Blessed, Standard, or Bound. (Type: two-handed weapon / bow]',
    'is_trade' => 1,
    'is_drop' => 1,
    'is_destruct' => 1,
    'crystal_type' => 'r99',
    'consume_type' => 'consume_type_normal',
  ],
  18246 => 
  [
    'item_id' => 18246,
    'icon' => 'weapon_vesper_schutze_i00',
    'name' => 'Unidentified Kaliel Shooter',
    'additionalname' => '',
    'description' => 'A Kaliel Shooter in an Unidentified state. Double-click the item to identify it. The acquired item can be Blessed, Standard, or Bound. (Type: two-handed weapon / crossbow / bow]',
    'is_trade' => 1,
    'is_drop' => 1,
    'is_destruct' => 1,
    'crystal_type' => 'r99',
    'consume_type' => 'consume_type_normal',
  ],
  18247 => 
  [
    'item_id' => 18247,
    'icon' => 'weapon_vesper_burster_i00',
    'name' => 'Unidentified Kaliel Buster',
    'additionalname' => '',
    'description' => 'A Kaliel Buster in an Unidentified state. Double-click the item to identify it. The acquired item can be Blessed, Standard, or Bound. (Type: one-handed weapon / sword]',
    'is_trade' => 1,
    'is_drop' => 1,
    'is_destruct' => 1,
    'crystal_type' => 'r99',
    'consume_type' => 'consume_type_normal',
  ],
  18248 => 
  [
    'item_id' => 18248,
    'icon' => 'weapon_vesper_caster_i00',
    'name' => 'Unidentified Kaliel Caster',
    'additionalname' => '',
    'description' => 'A Kaliel Caster in an Unidentified state. Double-click the item to identify it. The acquired item can be Blessed, Standard, or Bound. (Type: one-handed weapon / blunt]',
    'is_trade' => 1,
    'is_drop' => 1,
    'is_destruct' => 1,
    'crystal_type' => 'r99',
    'consume_type' => 'consume_type_normal',
  ],
  18249 => 
  [
    'item_id' => 18249,
    'icon' => 'weapon_vesper_singer_i00',
    'name' => 'Unidentified Kaliel Retributer',
    'additionalname' => '',
    'description' => 'A Kaliel Retributer in an Unidentified state. Double-click the item to identify it. The acquired item can be Blessed, Standard, or Bound. (Type: two-handed weapon / blunt]',
    'is_trade' => 1,
    'is_drop' => 1,
    'is_destruct' => 1,
    'crystal_type' => 'r99',
    'consume_type' => 'consume_type_normal',
  ],
  18250 => 
  [
    'item_id' => 18250,
    'icon' => 'weapon_r_dualsword_i00',
    'name' => 'Unidentified Kaliel Dualsword',
    'additionalname' => '',
    'description' => 'A Kaliel Dualsword in an Unidentified state. Double-click the item to identify it. The acquired item can be Blessed, Standard, or Bound. (Type: two-handed weapon / dualsword]',
    'is_trade' => 1,
    'is_drop' => 1,
    'is_destruct' => 1,
    'crystal_type' => 'r99',
    'consume_type' => 'consume_type_normal',
  ],
  18251 => 
  [
    'item_id' => 18251,
    'icon' => 'weapon_r_dualdagger_i00',
    'name' => 'Unidentified Kaliel Dual Dagger',
    'additionalname' => '',
    'description' => 'A Kaliel Dual Dagger in an Unidentified state. Double-click the item to identify it. The acquired item can be Blessed, Standard, or Bound. (Type: two-handed weapon / dualsword / dagger]',
    'is_trade' => 1,
    'is_drop' => 1,
    'is_destruct' => 1,
    'crystal_type' => 'r99',
    'consume_type' => 'consume_type_normal',
  ],
  18252 => 
  [
    'item_id' => 18252,
    'icon' => 'weapon_r_dualblunt_i00',
    'name' => 'Unidentified Kaliel Dual Blunt Weapon',
    'additionalname' => '',
    'description' => 'A Kaliel Dual Blunt Weapon in an Unidentified state. Double-click the item to identify it. The acquired item can be Blessed, Standard, or Bound. (Type: two-handed weapon / dualsword / blunt]',
    'is_trade' => 1,
    'is_drop' => 1,
    'is_destruct' => 1,
    'crystal_type' => 'r99',
    'consume_type' => 'consume_type_normal',
  ],
  18253 => 
  [
    'item_id' => 18253,
    'icon' => 'armor_helmet_i00',
    'name' => 'Unidentified Durandia Helmet',
    'additionalname' => 'Heavy Armor',
    'description' => 'A Durandia Helmet in an Unidentified state. Double-click the item to identify it. The acquired item can be Blessed, Standard, or Bound. (Type: Helmet / heavy armor]',
    'is_trade' => 1,
    'is_drop' => 1,
    'is_destruct' => 1,
    'crystal_type' => 'r99',
    'consume_type' => 'consume_type_normal',
  ],
  18254 => 
  [
    'item_id' => 18254,
    'icon' => 'armor_t97_u_i00',
    'name' => 'Unidentified Durandia Breastplate',
    'additionalname' => 'Heavy Armor',
    'description' => 'A Durandia Breastplate in an Unidentified state. Double-click the item to identify it. The acquired item can be Blessed, Standard, or Bound. (Type: upper / heavy armor]',
    'is_trade' => 1,
    'is_drop' => 1,
    'is_destruct' => 1,
    'crystal_type' => 'r99',
    'consume_type' => 'consume_type_normal',
  ],
  18255 => 
  [
    'item_id' => 18255,
    'icon' => 'armor_t97_l_i00',
    'name' => 'Unidentified Durandia Gaiters',
    'additionalname' => 'Heavy Armor',
    'description' => 'Durandia Gaiters in an Unidentified state. Double-click the item to identify it. The acquired item can be Blessed, Standard, or Bound. (Type: lower / heavy armor]',
    'is_trade' => 1,
    'is_drop' => 1,
    'is_destruct' => 1,
    'crystal_type' => 'r99',
    'consume_type' => 'consume_type_normal',
  ],
  18256 => 
  [
    'item_id' => 18256,
    'icon' => 'armor_t97_g_i00',
    'name' => 'Unidentified Durandia Gauntlets',
    'additionalname' => 'Heavy Armor',
    'description' => 'A Durandia Gauntlets in an Unidentified state. Double-click the item to identify it. The acquired item can be Blessed, Standard, or Bound. (Type: Gloves / heavy armor]',
    'is_trade' => 1,
    'is_drop' => 1,
    'is_destruct' => 1,
    'crystal_type' => 'r99',
    'consume_type' => 'consume_type_normal',
  ],
  18257 => 
  [
    'item_id' => 18257,
    'icon' => 'armor_t97_b_i00',
    'name' => 'Unidentified Durandia Boots',
    'additionalname' => 'Heavy Armor',
    'description' => 'Durandia Boots in an Unidentified state. Double-click the item to identify it. The acquired item can be Blessed, Standard, or Bound. (Type: Boots / heavy armor]',
    'is_trade' => 1,
    'is_drop' => 1,
    'is_destruct' => 1,
    'crystal_type' => 'r99',
    'consume_type' => 'consume_type_normal',
  ],
  18258 => 
  [
    'item_id' => 18258,
    'icon' => 'weapon_vesper_verteidiger_i01',
    'name' => 'Unidentified Durandia Shield',
    'additionalname' => 'Heavy Armor',
    'description' => 'A Durandia Shield in an Unidentified state. Double-click the item to identify it. The acquired item can be Blessed, Standard, or Bound. (Type: Shield / heavy armor]',
    'is_trade' => 1,
    'is_drop' => 1,
    'is_destruct' => 1,
    'crystal_type' => 'r99',
    'consume_type' => 'consume_type_normal',
  ],
  18259 => 
  [
    'item_id' => 18259,
    'icon' => 'armor_leather_helmet_i00',
    'name' => 'Unidentified Durandia Leather Helmet',
    'additionalname' => 'Light Armor',
    'description' => 'A Durandia leather Helmet in an Unidentified state. Double-click the item to identify it. The acquired item can be Blessed, Standard, or Bound. (Type: Helmet / light armor]',
    'is_trade' => 1,
    'is_drop' => 1,
    'is_destruct' => 1,
    'crystal_type' => 'r99',
    'consume_type' => 'consume_type_normal',
  ],
  18260 => 
  [
    'item_id' => 18260,
    'icon' => 'armor_t98_u_i00',
    'name' => 'Unidentified Durandia Leather Armor',
    'additionalname' => 'Light Armor',
    'description' => 'A Durandia leather armor in an Unidentified state. Double-click the item to identify it. The acquired item can be Blessed, Standard, or Bound. (Type: upper / light armor]',
    'is_trade' => 1,
    'is_drop' => 1,
    'is_destruct' => 1,
    'crystal_type' => 'r99',
    'consume_type' => 'consume_type_normal',
  ],
  18261 => 
  [
    'item_id' => 18261,
    'icon' => 'armor_t98_l_i00',
    'name' => 'Unidentified Durandia Leather Leggings',
    'additionalname' => 'Light Armor',
    'description' => 'Durandia leather Leggings in an Unidentified state. Double-click the item to identify it. The acquired item can be Blessed, Standard, or Bound. (Type: lower / light armor]',
    'is_trade' => 1,
    'is_drop' => 1,
    'is_destruct' => 1,
    'crystal_type' => 'r99',
    'consume_type' => 'consume_type_normal',
  ],
  18262 => 
  [
    'item_id' => 18262,
    'icon' => 'armor_t98_g_i00',
    'name' => 'Unidentified Durandia Leather Gloves',
    'additionalname' => 'Light Armor',
    'description' => 'Immortal Leather Gloves in an Unidentified state. Double-click the item to identify it. The acquired item can be Blessed, Standard, or Bound. (Type: Gloves / light armor]',
    'is_trade' => 1,
    'is_drop' => 1,
    'is_destruct' => 1,
    'crystal_type' => 'r99',
    'consume_type' => 'consume_type_normal',
  ],
  18263 => 
  [
    'item_id' => 18263,
    'icon' => 'armor_t98_b_i00',
    'name' => 'Unidentified Durandia Leather Boots',
    'additionalname' => 'Light Armor',
    'description' => 'Durandia leather Boots in an Unidentified state. Double-click the item to identify it. The acquired item can be Blessed, Standard, or Bound. (Type: Boots / light armor]',
    'is_trade' => 1,
    'is_drop' => 1,
    'is_destruct' => 1,
    'crystal_type' => 'r99',
    'consume_type' => 'consume_type_normal',
  ],
  18264 => 
  [
    'item_id' => 18264,
    'icon' => 'armor_circlet_i00',
    'name' => 'Unidentified Durandia Circlet',
    'additionalname' => 'Robe',
    'description' => 'A Durandia Circlet in an Unidentified state. Double-click the item to identify it. The acquired item can be Blessed, Standard, or Bound. (Type: Helmet / robe]',
    'is_trade' => 1,
    'is_drop' => 1,
    'is_destruct' => 1,
    'crystal_type' => 'r99',
    'consume_type' => 'consume_type_normal',
  ],
  18265 => 
  [
    'item_id' => 18265,
    'icon' => 'armor_t99_u_i00',
    'name' => 'Unidentified Durandia Tunic',
    'additionalname' => 'Robe',
    'description' => 'A Durandia Tunic in an Unidentified state. Double-click the item to identify it. The acquired item can be Blessed, Standard, or Bound. (Type: upper / robe]',
    'is_trade' => 1,
    'is_drop' => 1,
    'is_destruct' => 1,
    'crystal_type' => 'r99',
    'consume_type' => 'consume_type_normal',
  ],
  18266 => 
  [
    'item_id' => 18266,
    'icon' => 'armor_t99_l_i00',
    'name' => 'Unidentified Durandia Stockings',
    'additionalname' => 'Robe',
    'description' => 'Durandia Stockings in an Unidentified state. Double-click the item to identify it. The acquired item can be Blessed, Standard, or Bound. (Type: lower / robe]',
    'is_trade' => 1,
    'is_drop' => 1,
    'is_destruct' => 1,
    'crystal_type' => 'r99',
    'consume_type' => 'consume_type_normal',
  ],
  18267 => 
  [
    'item_id' => 18267,
    'icon' => 'armor_t99_g_i00',
    'name' => 'Unidentified Durandia Gloves',
    'additionalname' => 'Robe',
    'description' => 'Durandia Gloves in an Unidentified state. Double-click the item to identify it. The acquired item can be Blessed, Standard, or Bound. (Type: Gloves / robe]',
    'is_trade' => 1,
    'is_drop' => 1,
    'is_destruct' => 1,
    'crystal_type' => 'r99',
    'consume_type' => 'consume_type_normal',
  ],
  18268 => 
  [
    'item_id' => 18268,
    'icon' => 'armor_t99_b_i00',
    'name' => 'Unidentified Durandia Shoes',
    'additionalname' => 'Robe',
    'description' => 'Durandia Shoes in an Unidentified state. Double-click the item to identify it. The acquired item can be Blessed, Standard, or Bound. (Type: Boots / robe]',
    'is_trade' => 1,
    'is_drop' => 1,
    'is_destruct' => 1,
    'crystal_type' => 'r99',
    'consume_type' => 'consume_type_normal',
  ],
  18269 => 
  [
    'item_id' => 18269,
    'icon' => 'verper_sigil_i00',
    'name' => 'Unidentified Durandia Sigil',
    'additionalname' => 'Robe',
    'description' => 'Durandia Sigil in an Unidentified state. Double-click the item to identify it. The acquired item can be Blessed, Standard, or Bound. (Type: Shield / robe]',
    'is_trade' => 1,
    'is_drop' => 1,
    'is_destruct' => 1,
    'crystal_type' => 'r99',
    'consume_type' => 'consume_type_normal',
  ],
  18270 => 
  [
    'item_id' => 18270,
    'icon' => 'vesper_necklace_i00',
    'name' => 'Unidentified Durandia Necklace',
    'additionalname' => '',
    'description' => 'A Durandia Necklace in an Unidentified state. Double-click the item to identify it. The acquired item can be Blessed, Standard, or Bound. (Type: Necklace]',
    'is_trade' => 1,
    'is_drop' => 1,
    'is_destruct' => 1,
    'crystal_type' => 'r99',
    'consume_type' => 'consume_type_normal',
  ],
  18271 => 
  [
    'item_id' => 18271,
    'icon' => 'vesper_earring_i00',
    'name' => 'Unidentified Durandia Earring',
    'additionalname' => '',
    'description' => 'A Durandia Earring in an Unidentified state. Double-click the item to identify it. The acquired item can be Blessed, Standard, or Bound. (Type: Earring]',
    'is_trade' => 1,
    'is_drop' => 1,
    'is_destruct' => 1,
    'crystal_type' => 'r99',
    'consume_type' => 'consume_type_normal',
  ],
  18272 => 
  [
    'item_id' => 18272,
    'icon' => 'vesper_ring_i00',
    'name' => 'Unidentified Durandia Ring',
    'additionalname' => '',
    'description' => 'A Durandia Ring in an Unidentified state. Double-click the item to identify it. The acquired item can be Blessed, Standard, or Bound. (Type: Ring]',
    'is_trade' => 1,
    'is_drop' => 1,
    'is_destruct' => 1,
    'crystal_type' => 'r99',
    'consume_type' => 'consume_type_normal',
  ],
  18273 => 
  [
    'item_id' => 18273,
    'icon' => 'r85_talisman_pa_up_passive',
    'name' => 'Talisman (R85-grade] - P. Atk. (Passive]',
    'additionalname' => '',
    'description' => 'P. Atk. + 37 when equipped. Shadow item.',
    'is_trade' => 0,
    'is_drop' => 0,
    'is_destruct' => 1,
    'crystal_type' => 'none',
    'consume_type' => 'consume_type_normal',
  ],
  18274 => 
  [
    'item_id' => 18274,
    'icon' => 'r85_talisman_pa_up_passive',
    'name' => 'Talisman (R90-grade] - P. Atk. (Passive]',
    'additionalname' => '',
    'description' => 'P. Atk. + 43 when equipped. Shadow item.',
    'is_trade' => 0,
    'is_drop' => 0,
    'is_destruct' => 1,
    'crystal_type' => 'none',
    'consume_type' => 'consume_type_normal',
  ],
  18275 => 
  [
    'item_id' => 18275,
    'icon' => 'r85_talisman_pa_up_passive',
    'name' => 'Talisman (R95-grade] - P. Atk. (Passive]',
    'additionalname' => '',
    'description' => 'P. Atk. + 52 when equipped. Shadow item.',
    'is_trade' => 0,
    'is_drop' => 0,
    'is_destruct' => 1,
    'crystal_type' => 'none',
    'consume_type' => 'consume_type_normal',
  ],
  18276 => 
  [
    'item_id' => 18276,
    'icon' => 'r85_talisman_pa_up_passive',
    'name' => 'Talisman (R99-grade] - P. Atk. (Passive]',
    'additionalname' => '',
    'description' => 'P. Atk. + 60 when equipped. Shadow item.',
    'is_trade' => 0,
    'is_drop' => 0,
    'is_destruct' => 1,
    'crystal_type' => 'none',
    'consume_type' => 'consume_type_normal',
  ],
  18277 => 
  [
    'item_id' => 18277,
    'icon' => 'r85_talisman_pd_up_passive',
    'name' => 'Talisman (R85-grade] - P. Def. (Passive]',
    'additionalname' => '',
    'description' => 'P. Def. + 38 when equipped. Shadow item.',
    'is_trade' => 0,
    'is_drop' => 0,
    'is_destruct' => 1,
    'crystal_type' => 'none',
    'consume_type' => 'consume_type_normal',
  ],
  18278 => 
  [
    'item_id' => 18278,
    'icon' => 'r85_talisman_pd_up_passive',
    'name' => 'Talisman (R90-grade] - P. Def. (Passive]',
    'additionalname' => '',
    'description' => 'P. Def. + 43 when equipped. Shadow item.',
    'is_trade' => 0,
    'is_drop' => 0,
    'is_destruct' => 1,
    'crystal_type' => 'none',
    'consume_type' => 'consume_type_normal',
  ],
  18279 => 
  [
    'item_id' => 18279,
    'icon' => 'r85_talisman_pd_up_passive',
    'name' => 'Talisman (R95-grade] - P. Def. (Passive]',
    'additionalname' => '',
    'description' => 'P. Def. + 49 when equipped. Shadow item.',
    'is_trade' => 0,
    'is_drop' => 0,
    'is_destruct' => 1,
    'crystal_type' => 'none',
    'consume_type' => 'consume_type_normal',
  ],
  18280 => 
  [
    'item_id' => 18280,
    'icon' => 'r85_talisman_pd_up_passive',
    'name' => 'Talisman (R99-grade] - P. Def. (Passive]',
    'additionalname' => '',
    'description' => 'P. Def. + 54 when equipped. Shadow item.',
    'is_trade' => 0,
    'is_drop' => 0,
    'is_destruct' => 1,
    'crystal_type' => 'none',
    'consume_type' => 'consume_type_normal',
  ],
  18281 => 
  [
    'item_id' => 18281,
    'icon' => 'r85_talisman_ma_up_passive',
    'name' => 'Talisman (R85-grade] - M. Atk. (Passive]',
    'additionalname' => '',
    'description' => 'M. Atk. + 37 when equipped. Shadow item.',
    'is_trade' => 0,
    'is_drop' => 0,
    'is_destruct' => 1,
    'crystal_type' => 'none',
    'consume_type' => 'consume_type_normal',
  ],
  18282 => 
  [
    'item_id' => 18282,
    'icon' => 'r85_talisman_ma_up_passive',
    'name' => 'Talisman (R90-grade] - M. Atk. (Passive]',
    'additionalname' => '',
    'description' => 'M. Atk. + 46 when equipped. Shadow item.',
    'is_trade' => 0,
    'is_drop' => 0,
    'is_destruct' => 1,
    'crystal_type' => 'none',
    'consume_type' => 'consume_type_normal',
  ],
  18283 => 
  [
    'item_id' => 18283,
    'icon' => 'r85_talisman_ma_up_passive',
    'name' => 'Talisman (R95-grade] - M. Atk. (Passive]',
    'additionalname' => '',
    'description' => 'M. Atk. + 56 when equipped. Shadow item.',
    'is_trade' => 0,
    'is_drop' => 0,
    'is_destruct' => 1,
    'crystal_type' => 'none',
    'consume_type' => 'consume_type_normal',
  ],
  18284 => 
  [
    'item_id' => 18284,
    'icon' => 'r85_talisman_ma_up_passive',
    'name' => 'Talisman (R99-grade] - M. Atk. (Passive]',
    'additionalname' => '',
    'description' => 'M. Atk. + 66 when equipped. Shadow item.',
    'is_trade' => 0,
    'is_drop' => 0,
    'is_destruct' => 1,
    'crystal_type' => 'none',
    'consume_type' => 'consume_type_normal',
  ],
  18285 => 
  [
    'item_id' => 18285,
    'icon' => 'r85_talisman_md_up_passive',
    'name' => 'Talisman (R85-grade] - M. Def. (Passive]',
    'additionalname' => '',
    'description' => 'M. Def. + 21 when equipped. Shadow item.',
    'is_trade' => 0,
    'is_drop' => 0,
    'is_destruct' => 1,
    'crystal_type' => 'none',
    'consume_type' => 'consume_type_normal',
  ],
  18286 => 
  [
    'item_id' => 18286,
    'icon' => 'r85_talisman_md_up_passive',
    'name' => 'Talisman (R90-grade] - M. Def. (Passive]',
    'additionalname' => '',
    'description' => 'M. Def. + 24 when equipped. Shadow item.',
    'is_trade' => 0,
    'is_drop' => 0,
    'is_destruct' => 1,
    'crystal_type' => 'none',
    'consume_type' => 'consume_type_normal',
  ],
  18287 => 
  [
    'item_id' => 18287,
    'icon' => 'r85_talisman_md_up_passive',
    'name' => 'Talisman (R95-grade] - M. Def. (Passive]',
    'additionalname' => '',
    'description' => 'M. Def. + 28 when equipped. Shadow item.',
    'is_trade' => 0,
    'is_drop' => 0,
    'is_destruct' => 1,
    'crystal_type' => 'none',
    'consume_type' => 'consume_type_normal',
  ],
  18288 => 
  [
    'item_id' => 18288,
    'icon' => 'r85_talisman_md_up_passive',
    'name' => 'Talisman (R99-grade] - M. Def. (Passive]',
    'additionalname' => '',
    'description' => 'M. Def. + 32 when equipped. Shadow item.',
    'is_trade' => 0,
    'is_drop' => 0,
    'is_destruct' => 1,
    'crystal_type' => 'none',
    'consume_type' => 'consume_type_normal',
  ],
  18289 => 
  [
    'item_id' => 18289,
    'icon' => 'r85_talisman_hp_up_passive',
    'name' => 'Talisman (R85-grade] - HP (Passive]',
    'additionalname' => '',
    'description' => 'Max HP + 219 when equipped. Shadow item.',
    'is_trade' => 0,
    'is_drop' => 0,
    'is_destruct' => 1,
    'crystal_type' => 'none',
    'consume_type' => 'consume_type_normal',
  ],
  18290 => 
  [
    'item_id' => 18290,
    'icon' => 'r85_talisman_hp_up_passive',
    'name' => 'Talisman (R90-grade] - HP (Passive]',
    'additionalname' => '',
    'description' => 'Max HP + 246 when equipped. Shadow item.',
    'is_trade' => 0,
    'is_drop' => 0,
    'is_destruct' => 1,
    'crystal_type' => 'none',
    'consume_type' => 'consume_type_normal',
  ],
  18291 => 
  [
    'item_id' => 18291,
    'icon' => 'r85_talisman_hp_up_passive',
    'name' => 'Talisman (R95-grade] - HP (Passive]',
    'additionalname' => '',
    'description' => 'Max HP + 277 when equipped. Shadow item.',
    'is_trade' => 0,
    'is_drop' => 0,
    'is_destruct' => 1,
    'crystal_type' => 'none',
    'consume_type' => 'consume_type_normal',
  ],
  18292 => 
  [
    'item_id' => 18292,
    'icon' => 'r85_talisman_hp_up_passive',
    'name' => 'Talisman (R99-grade] - HP (Passive]',
    'additionalname' => '',
    'description' => 'Max HP + 305 when equipped. Shadow item.',
    'is_trade' => 0,
    'is_drop' => 0,
    'is_destruct' => 1,
    'crystal_type' => 'none',
    'consume_type' => 'consume_type_normal',
  ],
  18293 => 
  [
    'item_id' => 18293,
    'icon' => 'r85_talisman_mp_up_passive',
    'name' => 'Talisman (R85-grade] - MP (Passive]',
    'additionalname' => '',
    'description' => 'Max MP + 109 when equipped. Shadow item.',
    'is_trade' => 0,
    'is_drop' => 0,
    'is_destruct' => 1,
    'crystal_type' => 'none',
    'consume_type' => 'consume_type_normal',
  ],
  18294 => 
  [
    'item_id' => 18294,
    'icon' => 'r85_talisman_mp_up_passive',
    'name' => 'Talisman (R90-grade] - MP (Passive]',
    'additionalname' => '',
    'description' => 'Max MP + 119 when equipped. Shadow item.',
    'is_trade' => 0,
    'is_drop' => 0,
    'is_destruct' => 1,
    'crystal_type' => 'none',
    'consume_type' => 'consume_type_normal',
  ],
  18295 => 
  [
    'item_id' => 18295,
    'icon' => 'r85_talisman_mp_up_passive',
    'name' => 'Talisman (R95-grade] - MP (Passive]',
    'additionalname' => '',
    'description' => 'Max MP + 130 when equipped. Shadow item.',
    'is_trade' => 0,
    'is_drop' => 0,
    'is_destruct' => 1,
    'crystal_type' => 'none',
    'consume_type' => 'consume_type_normal',
  ],
  18296 => 
  [
    'item_id' => 18296,
    'icon' => 'r85_talisman_mp_up_passive',
    'name' => 'Talisman (R99-grade] - MP (Passive]',
    'additionalname' => '',
    'description' => 'Max MP + 139 when equipped. Shadow item.',
    'is_trade' => 0,
    'is_drop' => 0,
    'is_destruct' => 1,
    'crystal_type' => 'none',
    'consume_type' => 'consume_type_normal',
  ],
  18297 => 
  [
    'item_id' => 18297,
    'icon' => 'r85_talisman_cp_up_passive',
    'name' => 'Talisman (R85-grade] - CP (Passive]',
    'additionalname' => '',
    'description' => 'Max CP + 99 when equipped. Shadow item.',
    'is_trade' => 0,
    'is_drop' => 0,
    'is_destruct' => 1,
    'crystal_type' => 'none',
    'consume_type' => 'consume_type_normal',
  ],
  18298 => 
  [
    'item_id' => 18298,
    'icon' => 'r85_talisman_cp_up_passive',
    'name' => 'Talisman (R90-grade] - CP (Passive]',
    'additionalname' => '',
    'description' => 'Max CP + 108 when equipped. Shadow item.',
    'is_trade' => 0,
    'is_drop' => 0,
    'is_destruct' => 1,
    'crystal_type' => 'none',
    'consume_type' => 'consume_type_normal',
  ],
  18299 => 
  [
    'item_id' => 18299,
    'icon' => 'r85_talisman_cp_up_passive',
    'name' => 'Talisman (R95-grade] - CP (Passive]',
    'additionalname' => '',
    'description' => 'Max CP + 116 when equipped. Shadow item.',
    'is_trade' => 0,
    'is_drop' => 0,
    'is_destruct' => 1,
    'crystal_type' => 'none',
    'consume_type' => 'consume_type_normal',
  ],
];