<?php return [
  19600 => 
  [
    'item_id' => 19600,
    'icon' => 'armor_t503_g_i00',
    'name' => 'Bound Immortal Gloves',
    'additionalname' => 'Reinforced robe',
    'description' => 'Use Unbind Scroll to change it into a Standard item.',
    'is_trade' => 0,
    'is_drop' => 0,
    'is_destruct' => 1,
    'crystal_type' => 'r',
    'consume_type' => 'consume_type_normal',
  ],
  19601 => 
  [
    'item_id' => 19601,
    'icon' => 'armor_t503_b_i00',
    'name' => 'Bound Immortal Shoes',
    'additionalname' => 'Reinforced robe',
    'description' => 'Use Unbind Scroll to change it into a Standard item.',
    'is_trade' => 0,
    'is_drop' => 0,
    'is_destruct' => 1,
    'crystal_type' => 'r',
    'consume_type' => 'consume_type_normal',
  ],
  19602 => 
  [
    'item_id' => 19602,
    'icon' => 'armor_helmet_i00',
    'name' => 'Bound Twilight Helmet',
    'additionalname' => 'Reinforced heavy armor',
    'description' => 'Use Unbind Scroll to change it into a Standard item.',
    'is_trade' => 0,
    'is_drop' => 0,
    'is_destruct' => 1,
    'crystal_type' => 'r',
    'consume_type' => 'consume_type_normal',
  ],
  19603 => 
  [
    'item_id' => 19603,
    'icon' => 'armor_t601_u_i00',
    'name' => 'Bound Twilight Breastplate',
    'additionalname' => 'Reinforced heavy armor',
    'description' => 'Use Unbind Scroll to change it into a Standard item. When enchanted to +4, decreases received Critical Damage from standard attacks and increases P. Def.',
    'is_trade' => 0,
    'is_drop' => 0,
    'is_destruct' => 1,
    'crystal_type' => 'r',
    'consume_type' => 'consume_type_normal',
  ],
  19604 => 
  [
    'item_id' => 19604,
    'icon' => 'armor_t601_l_i00',
    'name' => 'Bound Twilight Gaiters',
    'additionalname' => 'Reinforced heavy armor',
    'description' => 'Use Unbind Scroll to change it into a Standard item.',
    'is_trade' => 0,
    'is_drop' => 0,
    'is_destruct' => 1,
    'crystal_type' => 'r',
    'consume_type' => 'consume_type_normal',
  ],
  19605 => 
  [
    'item_id' => 19605,
    'icon' => 'armor_t601_g_i00',
    'name' => 'Bound Twilight Gauntlets',
    'additionalname' => 'Reinforced heavy armor',
    'description' => 'Use Unbind Scroll to change it into a Standard item.',
    'is_trade' => 0,
    'is_drop' => 0,
    'is_destruct' => 1,
    'crystal_type' => 'r',
    'consume_type' => 'consume_type_normal',
  ],
  19606 => 
  [
    'item_id' => 19606,
    'icon' => 'armor_t601_b_i00',
    'name' => 'Bound Twilight Boots',
    'additionalname' => 'Reinforced heavy armor',
    'description' => 'Use Unbind Scroll to change it into a Standard item.',
    'is_trade' => 0,
    'is_drop' => 0,
    'is_destruct' => 1,
    'crystal_type' => 'r',
    'consume_type' => 'consume_type_normal',
  ],
  19607 => 
  [
    'item_id' => 19607,
    'icon' => 'kratere_i00',
    'name' => 'Bound Twilight Shield',
    'additionalname' => 'Reinforced',
    'description' => 'Additionally increases Shield Defense. Use an Unbind Scroll to change this item into a Standard item.',
    'is_trade' => 0,
    'is_drop' => 0,
    'is_destruct' => 1,
    'crystal_type' => 'r',
    'consume_type' => 'consume_type_normal',
  ],
  19608 => 
  [
    'item_id' => 19608,
    'icon' => 'armor_helmet_i00',
    'name' => 'Bound Twilight Helmet',
    'additionalname' => 'Not used',
    'description' => 'Use Unbind Scroll to change it into a Standard item.',
    'is_trade' => 0,
    'is_drop' => 0,
    'is_destruct' => 1,
    'crystal_type' => 'r',
    'consume_type' => 'consume_type_normal',
  ],
  19609 => 
  [
    'item_id' => 19609,
    'icon' => 'armor_t602_u_i00',
    'name' => 'Bound Twilight Armor',
    'additionalname' => 'Not used',
    'description' => 'Use Unbind Scroll to change it into a Standard item. When enchanted to +4, increases P. Evasion, Speed and P. Debuff Resistance, and decreases received Critical Rate from standard attacks.',
    'is_trade' => 0,
    'is_drop' => 0,
    'is_destruct' => 1,
    'crystal_type' => 'r',
    'consume_type' => 'consume_type_normal',
  ],
  19610 => 
  [
    'item_id' => 19610,
    'icon' => 'armor_t602_l_i00',
    'name' => 'Bound Twilight Leggings',
    'additionalname' => 'Not used',
    'description' => 'Use Unbind Scroll to change it into a Standard item.',
    'is_trade' => 0,
    'is_drop' => 0,
    'is_destruct' => 1,
    'crystal_type' => 'r',
    'consume_type' => 'consume_type_normal',
  ],
  19611 => 
  [
    'item_id' => 19611,
    'icon' => 'armor_t602_g_i00',
    'name' => 'Bound Twilight Gloves',
    'additionalname' => 'Not used',
    'description' => 'Use Unbind Scroll to change it into a Standard item.',
    'is_trade' => 0,
    'is_drop' => 0,
    'is_destruct' => 1,
    'crystal_type' => 'r',
    'consume_type' => 'consume_type_normal',
  ],
  19612 => 
  [
    'item_id' => 19612,
    'icon' => 'armor_t602_b_i00',
    'name' => 'Bound Twilight Boots',
    'additionalname' => 'Not used',
    'description' => 'Use Unbind Scroll to change it into a Standard item.',
    'is_trade' => 0,
    'is_drop' => 0,
    'is_destruct' => 1,
    'crystal_type' => 'r',
    'consume_type' => 'consume_type_normal',
  ],
  19613 => 
  [
    'item_id' => 19613,
    'icon' => 'armor_circlet_i00',
    'name' => 'Bound Twilight Circlet',
    'additionalname' => 'Reinforced robe',
    'description' => 'Use Unbind Scroll to change it into a Standard item.',
    'is_trade' => 0,
    'is_drop' => 0,
    'is_destruct' => 1,
    'crystal_type' => 'r',
    'consume_type' => 'consume_type_normal',
  ],
  19614 => 
  [
    'item_id' => 19614,
    'icon' => 'armor_t603_u_i00',
    'name' => 'Bound Twilight Tunic',
    'additionalname' => 'Reinforced robe',
    'description' => 'Can be changed into a Standard item with Unbind Scroll. When enchanted to +4, increases M. Evasion and Debuff Resistance, and decreases received Critical Damage from basic attacks and received Critical Rate from basic attacks.',
    'is_trade' => 0,
    'is_drop' => 0,
    'is_destruct' => 1,
    'crystal_type' => 'r',
    'consume_type' => 'consume_type_normal',
  ],
  19615 => 
  [
    'item_id' => 19615,
    'icon' => 'armor_t603_l_i00',
    'name' => 'Bound Twilight Stockings',
    'additionalname' => 'Reinforced robe',
    'description' => 'Use Unbind Scroll to change it into a Standard item.',
    'is_trade' => 0,
    'is_drop' => 0,
    'is_destruct' => 1,
    'crystal_type' => 'r',
    'consume_type' => 'consume_type_normal',
  ],
  19616 => 
  [
    'item_id' => 19616,
    'icon' => 'armor_t603_g_i00',
    'name' => 'Bound Twilight Gloves',
    'additionalname' => 'Reinforced robe',
    'description' => 'Use Unbind Scroll to change it into a Standard item.',
    'is_trade' => 0,
    'is_drop' => 0,
    'is_destruct' => 1,
    'crystal_type' => 'r',
    'consume_type' => 'consume_type_normal',
  ],
  19617 => 
  [
    'item_id' => 19617,
    'icon' => 'armor_t603_b_i00',
    'name' => 'Bound Twilight Shoes',
    'additionalname' => 'Reinforced robe',
    'description' => 'Use Unbind Scroll to change it into a Standard item.',
    'is_trade' => 0,
    'is_drop' => 0,
    'is_destruct' => 1,
    'crystal_type' => 'r',
    'consume_type' => 'consume_type_normal',
  ],
  19618 => 
  [
    'item_id' => 19618,
    'icon' => 'armor_helmet_i00',
    'name' => 'Bound Seraph Helmet',
    'additionalname' => 'Reinforced heavy armor',
    'description' => 'Use Unbind Scroll to change it into a Standard item.',
    'is_trade' => 0,
    'is_drop' => 0,
    'is_destruct' => 1,
    'crystal_type' => 'r95',
    'consume_type' => 'consume_type_normal',
  ],
  19619 => 
  [
    'item_id' => 19619,
    'icon' => 'armor_t401_u_i00',
    'name' => 'Bound Seraph Breastplate',
    'additionalname' => 'Reinforced heavy armor',
    'description' => 'Use Unbind Scroll to change it into a Standard item. When enchanted to +4, decreases received Critical Damage from standard attacks and increases P. Def.',
    'is_trade' => 0,
    'is_drop' => 0,
    'is_destruct' => 1,
    'crystal_type' => 'r95',
    'consume_type' => 'consume_type_normal',
  ],
  19620 => 
  [
    'item_id' => 19620,
    'icon' => 'armor_t401_l_i00',
    'name' => 'Bound Seraph Gaiters',
    'additionalname' => 'Reinforced heavy armor',
    'description' => 'Use Unbind Scroll to change it into a Standard item.',
    'is_trade' => 0,
    'is_drop' => 0,
    'is_destruct' => 1,
    'crystal_type' => 'r95',
    'consume_type' => 'consume_type_normal',
  ],
  19621 => 
  [
    'item_id' => 19621,
    'icon' => 'armor_t401_g_i00',
    'name' => 'Bound Seraph Gauntlets',
    'additionalname' => 'Reinforced heavy armor',
    'description' => 'Use Unbind Scroll to change it into a Standard item.',
    'is_trade' => 0,
    'is_drop' => 0,
    'is_destruct' => 1,
    'crystal_type' => 'r95',
    'consume_type' => 'consume_type_normal',
  ],
  19622 => 
  [
    'item_id' => 19622,
    'icon' => 'armor_t401_b_i00',
    'name' => 'Bound Seraph Boots',
    'additionalname' => 'Reinforced heavy armor',
    'description' => 'Use Unbind Scroll to change it into a Standard item.',
    'is_trade' => 0,
    'is_drop' => 0,
    'is_destruct' => 1,
    'crystal_type' => 'r95',
    'consume_type' => 'consume_type_normal',
  ],
  19623 => 
  [
    'item_id' => 19623,
    'icon' => 'beranka_i00',
    'name' => 'Bound Seraph Shield',
    'additionalname' => 'Reinforced',
    'description' => 'Additionally increases Shield Defense. Use an Unbind Scroll to change this item into a Standard item.',
    'is_trade' => 0,
    'is_drop' => 0,
    'is_destruct' => 1,
    'crystal_type' => 'r95',
    'consume_type' => 'consume_type_normal',
  ],
  19624 => 
  [
    'item_id' => 19624,
    'icon' => 'armor_helmet_i00',
    'name' => 'Bound Seraph Helmet',
    'additionalname' => 'Not used',
    'description' => 'Use Unbind Scroll to change it into a Standard item.',
    'is_trade' => 0,
    'is_drop' => 0,
    'is_destruct' => 1,
    'crystal_type' => 'r95',
    'consume_type' => 'consume_type_normal',
  ],
  19625 => 
  [
    'item_id' => 19625,
    'icon' => 'armor_t402_u_i00',
    'name' => 'Bound Seraph Armor',
    'additionalname' => 'Not used',
    'description' => 'Use Unbind Scroll to change it into a Standard item. When enchanted to +4, increases P. Evasion, Speed and P. Debuff Resistance, and decreases received Critical Rate from standard attacks.',
    'is_trade' => 0,
    'is_drop' => 0,
    'is_destruct' => 1,
    'crystal_type' => 'r95',
    'consume_type' => 'consume_type_normal',
  ],
  19626 => 
  [
    'item_id' => 19626,
    'icon' => 'armor_t402_l_i00',
    'name' => 'Bound Seraph Leggings',
    'additionalname' => 'Not used',
    'description' => 'Use Unbind Scroll to change it into a Standard item.',
    'is_trade' => 0,
    'is_drop' => 0,
    'is_destruct' => 1,
    'crystal_type' => 'r95',
    'consume_type' => 'consume_type_normal',
  ],
  19627 => 
  [
    'item_id' => 19627,
    'icon' => 'armor_t402_g_i00',
    'name' => 'Bound Seraph Gloves',
    'additionalname' => 'Not used',
    'description' => 'Use Unbind Scroll to change it into a Standard item.',
    'is_trade' => 0,
    'is_drop' => 0,
    'is_destruct' => 1,
    'crystal_type' => 'r95',
    'consume_type' => 'consume_type_normal',
  ],
  19628 => 
  [
    'item_id' => 19628,
    'icon' => 'armor_t402_b_i00',
    'name' => 'Bound Seraph Boots',
    'additionalname' => 'Not used',
    'description' => 'Use Unbind Scroll to change it into a Standard item.',
    'is_trade' => 0,
    'is_drop' => 0,
    'is_destruct' => 1,
    'crystal_type' => 'r95',
    'consume_type' => 'consume_type_normal',
  ],
  19629 => 
  [
    'item_id' => 19629,
    'icon' => 'armor_circlet_i00',
    'name' => 'Bound Seraph Circlet',
    'additionalname' => 'Reinforced robe',
    'description' => 'Use Unbind Scroll to change it into a Standard item.',
    'is_trade' => 0,
    'is_drop' => 0,
    'is_destruct' => 1,
    'crystal_type' => 'r95',
    'consume_type' => 'consume_type_normal',
  ],
  19630 => 
  [
    'item_id' => 19630,
    'icon' => 'armor_t403_u_i00',
    'name' => 'Bound Seraph Tunic',
    'additionalname' => 'Reinforced robe',
    'description' => 'Can be changed into a Standard item with Unbind Scroll. When enchanted to +4, increases M. Evasion and Debuff Resistance, and decreases received Critical Damage from basic attacks and received Critical Rate from basic attacks.',
    'is_trade' => 0,
    'is_drop' => 0,
    'is_destruct' => 1,
    'crystal_type' => 'r95',
    'consume_type' => 'consume_type_normal',
  ],
  19631 => 
  [
    'item_id' => 19631,
    'icon' => 'armor_t403_l_i00',
    'name' => 'Bound Seraph Stockings',
    'additionalname' => 'Reinforced robe',
    'description' => 'Use Unbind Scroll to change it into a Standard item.',
    'is_trade' => 0,
    'is_drop' => 0,
    'is_destruct' => 1,
    'crystal_type' => 'r95',
    'consume_type' => 'consume_type_normal',
  ],
  19632 => 
  [
    'item_id' => 19632,
    'icon' => 'armor_t403_g_i00',
    'name' => 'Bound Seraph Gloves',
    'additionalname' => 'Reinforced robe',
    'description' => 'Use Unbind Scroll to change it into a Standard item.',
    'is_trade' => 0,
    'is_drop' => 0,
    'is_destruct' => 1,
    'crystal_type' => 'r95',
    'consume_type' => 'consume_type_normal',
  ],
  19633 => 
  [
    'item_id' => 19633,
    'icon' => 'armor_t403_b_i00',
    'name' => 'Bound Seraph Shoes',
    'additionalname' => 'Reinforced robe',
    'description' => 'Use Unbind Scroll to change it into a Standard item.',
    'is_trade' => 0,
    'is_drop' => 0,
    'is_destruct' => 1,
    'crystal_type' => 'r95',
    'consume_type' => 'consume_type_normal',
  ],
  19634 => 
  [
    'item_id' => 19634,
    'icon' => 'armor_helmet_i00',
    'name' => 'Bound Eternal Helmet',
    'additionalname' => 'Reinforced heavy armor',
    'description' => 'Use Unbind Scroll to change it into a Standard item.',
    'is_trade' => 0,
    'is_drop' => 0,
    'is_destruct' => 1,
    'crystal_type' => 'r99',
    'consume_type' => 'consume_type_normal',
  ],
  19635 => 
  [
    'item_id' => 19635,
    'icon' => 'armor_t701_u_i00',
    'name' => 'Bound Eternal Breastplate',
    'additionalname' => 'Reinforced heavy armor',
    'description' => 'Use Unbind Scroll to change it into a Standard item. When enchanted to +4, decreases received Critical Damage from standard attacks and increases P. Def.',
    'is_trade' => 0,
    'is_drop' => 0,
    'is_destruct' => 1,
    'crystal_type' => 'r99',
    'consume_type' => 'consume_type_normal',
  ],
  19636 => 
  [
    'item_id' => 19636,
    'icon' => 'armor_t701_l_i00',
    'name' => 'Bound Eternal Gaiters',
    'additionalname' => 'Reinforced heavy armor',
    'description' => 'Use Unbind Scroll to change it into a Standard item.',
    'is_trade' => 0,
    'is_drop' => 0,
    'is_destruct' => 1,
    'crystal_type' => 'r99',
    'consume_type' => 'consume_type_normal',
  ],
  19637 => 
  [
    'item_id' => 19637,
    'icon' => 'armor_t701_g_i00',
    'name' => 'Bound Eternal Gauntlets',
    'additionalname' => 'Reinforced heavy armor',
    'description' => 'Use Unbind Scroll to change it into a Standard item.',
    'is_trade' => 0,
    'is_drop' => 0,
    'is_destruct' => 1,
    'crystal_type' => 'r99',
    'consume_type' => 'consume_type_normal',
  ],
  19638 => 
  [
    'item_id' => 19638,
    'icon' => 'armor_t701_b_i00',
    'name' => 'Bound Eternal Boots',
    'additionalname' => 'Reinforced heavy armor',
    'description' => 'Use Unbind Scroll to change it into a Standard item.',
    'is_trade' => 0,
    'is_drop' => 0,
    'is_destruct' => 1,
    'crystal_type' => 'r99',
    'consume_type' => 'consume_type_normal',
  ],
  19639 => 
  [
    'item_id' => 19639,
    'icon' => 'weapon_akra_i00',
    'name' => 'Bound Eternal Shield',
    'additionalname' => 'Reinforced',
    'description' => 'Additionally increases Shield Defense. Use an Unbind Scroll to change this item into a Standard item.',
    'is_trade' => 0,
    'is_drop' => 0,
    'is_destruct' => 1,
    'crystal_type' => 'r99',
    'consume_type' => 'consume_type_normal',
  ],
  19640 => 
  [
    'item_id' => 19640,
    'icon' => 'armor_helmet_i00',
    'name' => 'Bound Eternal Helmet',
    'additionalname' => 'Not used',
    'description' => 'Use Unbind Scroll to change it into a Standard item.',
    'is_trade' => 0,
    'is_drop' => 0,
    'is_destruct' => 1,
    'crystal_type' => 'r99',
    'consume_type' => 'consume_type_normal',
  ],
  19641 => 
  [
    'item_id' => 19641,
    'icon' => 'armor_t702_u_i00',
    'name' => 'Bound Eternal Armor',
    'additionalname' => 'Not used',
    'description' => 'Use Unbind Scroll to change it into a Standard item. When enchanted to +4, increases P. Evasion, Speed and P. Debuff Resistance, and decreases received Critical Rate from standard attacks.',
    'is_trade' => 0,
    'is_drop' => 0,
    'is_destruct' => 1,
    'crystal_type' => 'r99',
    'consume_type' => 'consume_type_normal',
  ],
  19642 => 
  [
    'item_id' => 19642,
    'icon' => 'armor_t702_l_i00',
    'name' => 'Bound Eternal Leggings',
    'additionalname' => 'Not used',
    'description' => 'Use Unbind Scroll to change it into a Standard item.',
    'is_trade' => 0,
    'is_drop' => 0,
    'is_destruct' => 1,
    'crystal_type' => 'r99',
    'consume_type' => 'consume_type_normal',
  ],
  19643 => 
  [
    'item_id' => 19643,
    'icon' => 'armor_t702_g_i00',
    'name' => 'Bound Eternal Gloves',
    'additionalname' => 'Not used',
    'description' => 'Use Unbind Scroll to change it into a Standard item.',
    'is_trade' => 0,
    'is_drop' => 0,
    'is_destruct' => 1,
    'crystal_type' => 'r99',
    'consume_type' => 'consume_type_normal',
  ],
  19644 => 
  [
    'item_id' => 19644,
    'icon' => 'armor_t702_b_i00',
    'name' => 'Bound Eternal Boots',
    'additionalname' => 'Not used',
    'description' => 'Use Unbind Scroll to change it into a Standard item.',
    'is_trade' => 0,
    'is_drop' => 0,
    'is_destruct' => 1,
    'crystal_type' => 'r99',
    'consume_type' => 'consume_type_normal',
  ],
  19645 => 
  [
    'item_id' => 19645,
    'icon' => 'armor_circlet_i00',
    'name' => 'Bound Eternal Circlet',
    'additionalname' => 'Reinforced robe',
    'description' => 'Use Unbind Scroll to change it into a Standard item.',
    'is_trade' => 0,
    'is_drop' => 0,
    'is_destruct' => 1,
    'crystal_type' => 'r99',
    'consume_type' => 'consume_type_normal',
  ],
  19646 => 
  [
    'item_id' => 19646,
    'icon' => 'armor_t703_u_i00',
    'name' => 'Bound Eternal Tunic',
    'additionalname' => 'Reinforced robe',
    'description' => 'Can be changed into a Standard item with Unbind Scroll. When enchanted to +4, increases M. Evasion and Debuff Resistance, and decreases received Critical Damage from basic attacks and received Critical Rate from basic attacks.',
    'is_trade' => 0,
    'is_drop' => 0,
    'is_destruct' => 1,
    'crystal_type' => 'r99',
    'consume_type' => 'consume_type_normal',
  ],
  19647 => 
  [
    'item_id' => 19647,
    'icon' => 'armor_t703_l_i00',
    'name' => 'Bound Eternal Stockings',
    'additionalname' => 'Reinforced robe',
    'description' => 'Use Unbind Scroll to change it into a Standard item.',
    'is_trade' => 0,
    'is_drop' => 0,
    'is_destruct' => 1,
    'crystal_type' => 'r99',
    'consume_type' => 'consume_type_normal',
  ],
  19648 => 
  [
    'item_id' => 19648,
    'icon' => 'armor_t703_g_i00',
    'name' => 'Bound Eternal Gloves',
    'additionalname' => 'Reinforced robe',
    'description' => 'Use Unbind Scroll to change it into a Standard item.',
    'is_trade' => 0,
    'is_drop' => 0,
    'is_destruct' => 1,
    'crystal_type' => 'r99',
    'consume_type' => 'consume_type_normal',
  ],
  19649 => 
  [
    'item_id' => 19649,
    'icon' => 'armor_t703_b_i00',
    'name' => 'Bound Eternal Shoes',
    'additionalname' => 'Reinforced robe',
    'description' => 'Use Unbind Scroll to change it into a Standard item.',
    'is_trade' => 0,
    'is_drop' => 0,
    'is_destruct' => 1,
    'crystal_type' => 'r99',
    'consume_type' => 'consume_type_normal',
  ],
  19650 => 
  [
    'item_id' => 19650,
    'icon' => 'armor_helmet_i00',
    'name' => 'Blessed Immortal Helmet',
    'additionalname' => 'Reinforced heavy armor',
    'description' => NULL,
    'is_trade' => 1,
    'is_drop' => 1,
    'is_destruct' => 1,
    'crystal_type' => 'r',
    'consume_type' => 'consume_type_normal',
  ],
  19651 => 
  [
    'item_id' => 19651,
    'icon' => 'armor_t501_u_i00',
    'name' => 'Blessed Immortal Breastplate',
    'additionalname' => 'Reinforced heavy armor',
    'description' => 'When enchanted to +4, decreases received Critical Damage from basic attacks and increases P. Def.',
    'is_trade' => 1,
    'is_drop' => 1,
    'is_destruct' => 1,
    'crystal_type' => 'r',
    'consume_type' => 'consume_type_normal',
  ],
  19652 => 
  [
    'item_id' => 19652,
    'icon' => 'armor_t501_l_i00',
    'name' => 'Blessed Immortal Gaiters',
    'additionalname' => 'Reinforced heavy armor',
    'description' => NULL,
    'is_trade' => 1,
    'is_drop' => 1,
    'is_destruct' => 1,
    'crystal_type' => 'r',
    'consume_type' => 'consume_type_normal',
  ],
  19653 => 
  [
    'item_id' => 19653,
    'icon' => 'armor_t501_g_i00',
    'name' => 'Blessed Immortal Gauntlets',
    'additionalname' => 'Reinforced heavy armor',
    'description' => NULL,
    'is_trade' => 1,
    'is_drop' => 1,
    'is_destruct' => 1,
    'crystal_type' => 'r',
    'consume_type' => 'consume_type_normal',
  ],
  19654 => 
  [
    'item_id' => 19654,
    'icon' => 'armor_t501_b_i00',
    'name' => 'Blessed Immortal Boots',
    'additionalname' => 'Reinforced heavy armor',
    'description' => NULL,
    'is_trade' => 1,
    'is_drop' => 1,
    'is_destruct' => 1,
    'crystal_type' => 'r',
    'consume_type' => 'consume_type_normal',
  ],
  19655 => 
  [
    'item_id' => 19655,
    'icon' => 'weapon_sacon_i00',
    'name' => 'Blessed Immortal Shield',
    'additionalname' => 'Reinforced',
    'description' => 'Additionally increases Shield Defense.',
    'is_trade' => 1,
    'is_drop' => 1,
    'is_destruct' => 1,
    'crystal_type' => 'r',
    'consume_type' => 'consume_type_normal',
  ],
  19656 => 
  [
    'item_id' => 19656,
    'icon' => 'armor_helmet_i00',
    'name' => 'Blessed Immortal Helmet',
    'additionalname' => 'Not used',
    'description' => NULL,
    'is_trade' => 1,
    'is_drop' => 1,
    'is_destruct' => 1,
    'crystal_type' => 'r',
    'consume_type' => 'consume_type_normal',
  ],
  19657 => 
  [
    'item_id' => 19657,
    'icon' => 'armor_t502_u_i00',
    'name' => 'Blessed Immortal Armor',
    'additionalname' => 'Not used',
    'description' => 'When enchanted to +4, increases P. Evasion, Speed and P. Debuff Resistance, and decreases received Critical Rate from basic attacks.',
    'is_trade' => 1,
    'is_drop' => 1,
    'is_destruct' => 1,
    'crystal_type' => 'r',
    'consume_type' => 'consume_type_normal',
  ],
  19658 => 
  [
    'item_id' => 19658,
    'icon' => 'armor_t502_l_i00',
    'name' => 'Blessed Immortal Leggings',
    'additionalname' => 'Not used',
    'description' => NULL,
    'is_trade' => 1,
    'is_drop' => 1,
    'is_destruct' => 1,
    'crystal_type' => 'r',
    'consume_type' => 'consume_type_normal',
  ],
  19659 => 
  [
    'item_id' => 19659,
    'icon' => 'armor_t502_g_i00',
    'name' => 'Blessed Immortal Gloves',
    'additionalname' => 'Not used',
    'description' => NULL,
    'is_trade' => 1,
    'is_drop' => 1,
    'is_destruct' => 1,
    'crystal_type' => 'r',
    'consume_type' => 'consume_type_normal',
  ],
  19660 => 
  [
    'item_id' => 19660,
    'icon' => 'armor_t502_b_i00',
    'name' => 'Blessed Immortal Boots',
    'additionalname' => 'Not used',
    'description' => NULL,
    'is_trade' => 1,
    'is_drop' => 1,
    'is_destruct' => 1,
    'crystal_type' => 'r',
    'consume_type' => 'consume_type_normal',
  ],
  19661 => 
  [
    'item_id' => 19661,
    'icon' => 'armor_circlet_i00',
    'name' => 'Blessed Immortal Circlet',
    'additionalname' => 'Reinforced robe',
    'description' => NULL,
    'is_trade' => 1,
    'is_drop' => 1,
    'is_destruct' => 1,
    'crystal_type' => 'r',
    'consume_type' => 'consume_type_normal',
  ],
  19662 => 
  [
    'item_id' => 19662,
    'icon' => 'armor_t503_u_i00',
    'name' => 'Blessed Immortal Tunic',
    'additionalname' => 'Reinforced robe',
    'description' => 'When enchanted to +4, increases M. Evasion and M. Debuff Resistance, and decreases received Critical Damage from basic attacks and received Critical Rate from basic attacks.',
    'is_trade' => 1,
    'is_drop' => 1,
    'is_destruct' => 1,
    'crystal_type' => 'r',
    'consume_type' => 'consume_type_normal',
  ],
  19663 => 
  [
    'item_id' => 19663,
    'icon' => 'armor_t503_l_i00',
    'name' => 'Blessed Immortal Stockings',
    'additionalname' => 'Reinforced robe',
    'description' => NULL,
    'is_trade' => 1,
    'is_drop' => 1,
    'is_destruct' => 1,
    'crystal_type' => 'r',
    'consume_type' => 'consume_type_normal',
  ],
  19664 => 
  [
    'item_id' => 19664,
    'icon' => 'armor_t503_g_i00',
    'name' => 'Blessed Immortal Gloves',
    'additionalname' => 'Reinforced robe',
    'description' => NULL,
    'is_trade' => 1,
    'is_drop' => 1,
    'is_destruct' => 1,
    'crystal_type' => 'r',
    'consume_type' => 'consume_type_normal',
  ],
  19665 => 
  [
    'item_id' => 19665,
    'icon' => 'armor_t503_b_i00',
    'name' => 'Blessed Immortal Shoes',
    'additionalname' => 'Reinforced robe',
    'description' => NULL,
    'is_trade' => 1,
    'is_drop' => 1,
    'is_destruct' => 1,
    'crystal_type' => 'r',
    'consume_type' => 'consume_type_normal',
  ],
  19666 => 
  [
    'item_id' => 19666,
    'icon' => 'armor_helmet_i00',
    'name' => 'Blessed Twilight Helmet',
    'additionalname' => 'Reinforced heavy armor',
    'description' => '<Enchanting>Use Scroll: Enchant R-grade Armor.<Enhancing>Take this armor enchanted to +6, R-grade Crystals, R-grade Gemstones and Crystal of Protection and go to Head Blacksmith in any town to enhance the armor to Seraph Armor.',
    'is_trade' => 1,
    'is_drop' => 1,
    'is_destruct' => 1,
    'crystal_type' => 'r',
    'consume_type' => 'consume_type_normal',
  ],
  19667 => 
  [
    'item_id' => 19667,
    'icon' => 'armor_t601_u_i00',
    'name' => 'Blessed Twilight Breastplate',
    'additionalname' => 'Reinforced heavy armor',
    'description' => 'When enchanted to +4, decreases Received Critical Damage from standard attacks, increases P. Def.<Enchanting>Use Scroll: Enchant R-grade Armor.<Enhancing>Take this armor enchanted to +6, R-grade Crystals, R-grade Gemstones and Crystal of Protection and go to Head Blacksmith in any town to enhance the armor to Seraph Armor.',
    'is_trade' => 1,
    'is_drop' => 1,
    'is_destruct' => 1,
    'crystal_type' => 'r',
    'consume_type' => 'consume_type_normal',
  ],
  19668 => 
  [
    'item_id' => 19668,
    'icon' => 'armor_t601_l_i00',
    'name' => 'Blessed Twilight Gaiters',
    'additionalname' => 'Reinforced heavy armor',
    'description' => '<Enchanting>Use Scroll: Enchant R-grade Armor.<Enhancing>Take this armor enchanted to +6, R-grade Crystals, R-grade Gemstones and Crystal of Protection and go to Head Blacksmith in any town to enhance the armor to Seraph Armor.',
    'is_trade' => 1,
    'is_drop' => 1,
    'is_destruct' => 1,
    'crystal_type' => 'r',
    'consume_type' => 'consume_type_normal',
  ],
  19669 => 
  [
    'item_id' => 19669,
    'icon' => 'armor_t601_g_i00',
    'name' => 'Blessed Twilight Gauntlets',
    'additionalname' => 'Reinforced heavy armor',
    'description' => '<Enchanting>Use Scroll: Enchant R-grade Armor.<Enhancing>Take this armor enchanted to +6, R-grade Crystals, R-grade Gemstones and Crystal of Protection and go to Head Blacksmith in any town to enhance the armor to Seraph Armor.',
    'is_trade' => 1,
    'is_drop' => 1,
    'is_destruct' => 1,
    'crystal_type' => 'r',
    'consume_type' => 'consume_type_normal',
  ],
  19670 => 
  [
    'item_id' => 19670,
    'icon' => 'armor_t601_b_i00',
    'name' => 'Blessed Twilight Boots',
    'additionalname' => 'Reinforced heavy armor',
    'description' => '<Enchanting>Use Scroll: Enchant R-grade Armor.<Enhancing>Take this armor enchanted to +6, R-grade Crystals, R-grade Gemstones and Crystal of Protection and go to Head Blacksmith in any town to enhance the armor to Seraph Armor.',
    'is_trade' => 1,
    'is_drop' => 1,
    'is_destruct' => 1,
    'crystal_type' => 'r',
    'consume_type' => 'consume_type_normal',
  ],
  19671 => 
  [
    'item_id' => 19671,
    'icon' => 'kratere_i00',
    'name' => 'Blessed Twilight Shield',
    'additionalname' => 'Reinforced',
    'description' => 'Increases Shield Defense.  <Enchanting> Use Scroll: Enchant R-grade Armor.',
    'is_trade' => 1,
    'is_drop' => 1,
    'is_destruct' => 1,
    'crystal_type' => 'r',
    'consume_type' => 'consume_type_normal',
  ],
  19672 => 
  [
    'item_id' => 19672,
    'icon' => 'armor_helmet_i00',
    'name' => 'Blessed Twilight Helmet',
    'additionalname' => 'Not used',
    'description' => '<Enchanting>Use Scroll: Enchant R-grade Armor.<Enhancing>Take this armor enchanted to +6, R-grade Crystals, R-grade Gemstones and Crystal of Protection and go to Head Blacksmith in any town to enhance the armor to Seraph Armor.',
    'is_trade' => 1,
    'is_drop' => 1,
    'is_destruct' => 1,
    'crystal_type' => 'r',
    'consume_type' => 'consume_type_normal',
  ],
  19673 => 
  [
    'item_id' => 19673,
    'icon' => 'armor_t602_u_i00',
    'name' => 'Blessed Twilight Armor',
    'additionalname' => 'Not used',
    'description' => 'When enchanted to +4, increases P. Evasion, Speed and P. Debuff Resistance, also decreases received Critical Rate from standard attacks.<Enchanting>Use Scroll: Enchant R-grade Armor.<Enhancing>Take this armor enchanted to +6, R-grade Crystals, R-grade Gemstones and Crystal of Protection and go to Head Blacksmith in any town to enhance it to the Seraph armor.',
    'is_trade' => 1,
    'is_drop' => 1,
    'is_destruct' => 1,
    'crystal_type' => 'r',
    'consume_type' => 'consume_type_normal',
  ],
  19674 => 
  [
    'item_id' => 19674,
    'icon' => 'armor_t602_l_i00',
    'name' => 'Blessed Twilight Leggings',
    'additionalname' => 'Not used',
    'description' => '<Enchanting>Use Scroll: Enchant R-grade Armor.<Enhancing>Take this armor enchanted to +6, R-grade Crystals, R-grade Gemstones and Crystal of Protection and go to Head Blacksmith in any town to enhance the armor to Seraph Armor.',
    'is_trade' => 1,
    'is_drop' => 1,
    'is_destruct' => 1,
    'crystal_type' => 'r',
    'consume_type' => 'consume_type_normal',
  ],
  19675 => 
  [
    'item_id' => 19675,
    'icon' => 'armor_t602_g_i00',
    'name' => 'Blessed Twilight Gloves',
    'additionalname' => 'Not used',
    'description' => '<Enchanting>Use Scroll: Enchant R-grade Armor.<Enhancing>Take this armor enchanted to +6, R-grade Crystals, R-grade Gemstones and Crystal of Protection and go to Head Blacksmith in any town to enhance the armor to Seraph Armor.',
    'is_trade' => 1,
    'is_drop' => 1,
    'is_destruct' => 1,
    'crystal_type' => 'r',
    'consume_type' => 'consume_type_normal',
  ],
  19676 => 
  [
    'item_id' => 19676,
    'icon' => 'armor_t602_b_i00',
    'name' => 'Blessed Twilight Boots',
    'additionalname' => 'Not used',
    'description' => '<Enchanting>Use Scroll: Enchant R-grade Armor.<Enhancing>Take this armor enchanted to +6, R-grade Crystals, R-grade Gemstones and Crystal of Protection and go to Head Blacksmith in any town to enhance the armor to Seraph Armor.',
    'is_trade' => 1,
    'is_drop' => 1,
    'is_destruct' => 1,
    'crystal_type' => 'r',
    'consume_type' => 'consume_type_normal',
  ],
  19677 => 
  [
    'item_id' => 19677,
    'icon' => 'armor_circlet_i00',
    'name' => 'Blessed Twilight Circlet',
    'additionalname' => 'Reinforced robe',
    'description' => '<Enchanting>Use Scroll: Enchant R-grade Armor.<Enhancing>Take this armor enchanted to +6, R-grade Crystals, R-grade Gemstones and Crystal of Protection and go to Head Blacksmith in any town to enhance the armor to Seraph Armor.',
    'is_trade' => 1,
    'is_drop' => 1,
    'is_destruct' => 1,
    'crystal_type' => 'r',
    'consume_type' => 'consume_type_normal',
  ],
  19678 => 
  [
    'item_id' => 19678,
    'icon' => 'armor_t603_u_i00',
    'name' => 'Blessed Twilight Tunic',
    'additionalname' => 'Reinforced robe',
    'description' => 'When enchanted to +4, increases M. Evasion and M. Debuff Resistance, also decreases received Critical Damage from standard attacks and received Critical Rate from standard attacks.<Enchanting>Use Scroll: Enchant R-grade Armor.<Enhancing>Take this armor enchanted to +6, R-grade Crystals, R-grade Gemstones and Crystal of Protection and go to Head Blacksmith in any town to enhance it to the Seraph armor.',
    'is_trade' => 1,
    'is_drop' => 1,
    'is_destruct' => 1,
    'crystal_type' => 'r',
    'consume_type' => 'consume_type_normal',
  ],
  19679 => 
  [
    'item_id' => 19679,
    'icon' => 'armor_t603_l_i00',
    'name' => 'Blessed Twilight Stockings',
    'additionalname' => 'Reinforced robe',
    'description' => '<Enchanting>Use Scroll: Enchant R-grade Armor.<Enhancing>Take this armor enchanted to +6, R-grade Crystals, R-grade Gemstones and Crystal of Protection and go to Head Blacksmith in any town to enhance the armor to Seraph Armor.',
    'is_trade' => 1,
    'is_drop' => 1,
    'is_destruct' => 1,
    'crystal_type' => 'r',
    'consume_type' => 'consume_type_normal',
  ],
  19680 => 
  [
    'item_id' => 19680,
    'icon' => 'armor_t603_g_i00',
    'name' => 'Blessed Twilight Gloves',
    'additionalname' => 'Reinforced robe',
    'description' => '<Enchanting>Use Scroll: Enchant R-grade Armor.<Enhancing>Take this armor enchanted to +6, R-grade Crystals, R-grade Gemstones and Crystal of Protection and go to Head Blacksmith in any town to enhance the armor to Seraph Armor.',
    'is_trade' => 1,
    'is_drop' => 1,
    'is_destruct' => 1,
    'crystal_type' => 'r',
    'consume_type' => 'consume_type_normal',
  ],
  19681 => 
  [
    'item_id' => 19681,
    'icon' => 'armor_t603_b_i00',
    'name' => 'Blessed Twilight Shoes',
    'additionalname' => 'Reinforced robe',
    'description' => '<Enchanting>Use Scroll: Enchant R-grade Armor.<Enhancing>Take this armor enchanted to +6, R-grade Crystals, R-grade Gemstones and Crystal of Protection and go to Head Blacksmith in any town to enhance the armor to Seraph Armor.',
    'is_trade' => 1,
    'is_drop' => 1,
    'is_destruct' => 1,
    'crystal_type' => 'r',
    'consume_type' => 'consume_type_normal',
  ],
  19682 => 
  [
    'item_id' => 19682,
    'icon' => 'armor_helmet_i00',
    'name' => 'Blessed Seraph Helmet',
    'additionalname' => 'Reinforced heavy armor',
    'description' => '<Enchanting>Use Scroll: Enchant R-grade Armor.<Enhancing>Take this armor enchanted to +6, R-grade Crystals, R-grade Gemstones and Crystal of Protection and go to Head Blacksmith in any town to enhance the armor to Eternal Armor.',
    'is_trade' => 1,
    'is_drop' => 1,
    'is_destruct' => 1,
    'crystal_type' => 'r95',
    'consume_type' => 'consume_type_normal',
  ],
  19683 => 
  [
    'item_id' => 19683,
    'icon' => 'armor_t401_u_i00',
    'name' => 'Blessed Seraph Breastplate',
    'additionalname' => 'Reinforced heavy armor',
    'description' => 'When enchanted to +4, decreases Received Critical Damage from standard attacks, increases P. Def.<Enchanting>Use Scroll: Enchant R-grade Armor.<Enhancing>Take this armor enchanted to +6, R-grade Crystals, R-grade Gemstones and Crystal of Protection and go to Head Blacksmith in any town to enhance the armor to Eternal Armor.',
    'is_trade' => 1,
    'is_drop' => 1,
    'is_destruct' => 1,
    'crystal_type' => 'r95',
    'consume_type' => 'consume_type_normal',
  ],
  19684 => 
  [
    'item_id' => 19684,
    'icon' => 'armor_t401_l_i00',
    'name' => 'Blessed Seraph Gaiters',
    'additionalname' => 'Reinforced heavy armor',
    'description' => '<Enchanting>Use Scroll: Enchant R-grade Armor.<Enhancing>Take this armor enchanted to +6, R-grade Crystals, R-grade Gemstones and Crystal of Protection and go to Head Blacksmith in any town to enhance the armor to Eternal Armor.',
    'is_trade' => 1,
    'is_drop' => 1,
    'is_destruct' => 1,
    'crystal_type' => 'r95',
    'consume_type' => 'consume_type_normal',
  ],
  19685 => 
  [
    'item_id' => 19685,
    'icon' => 'armor_t401_g_i00',
    'name' => 'Blessed Seraph Gauntlets',
    'additionalname' => 'Reinforced heavy armor',
    'description' => '<Enchanting>Use Scroll: Enchant R-grade Armor.<Enhancing>Take this armor enchanted to +6, R-grade Crystals, R-grade Gemstones and Crystal of Protection and go to Head Blacksmith in any town to enhance the armor to Eternal Armor.',
    'is_trade' => 1,
    'is_drop' => 1,
    'is_destruct' => 1,
    'crystal_type' => 'r95',
    'consume_type' => 'consume_type_normal',
  ],
  19686 => 
  [
    'item_id' => 19686,
    'icon' => 'armor_t401_b_i00',
    'name' => 'Blessed Seraph Boots',
    'additionalname' => 'Reinforced heavy armor',
    'description' => '<Enchanting>Use Scroll: Enchant R-grade Armor.<Enhancing>Take this armor enchanted to +6, R-grade Crystals, R-grade Gemstones and Crystal of Protection and go to Head Blacksmith in any town to enhance the armor to Eternal Armor.',
    'is_trade' => 1,
    'is_drop' => 1,
    'is_destruct' => 1,
    'crystal_type' => 'r95',
    'consume_type' => 'consume_type_normal',
  ],
  19687 => 
  [
    'item_id' => 19687,
    'icon' => 'beranka_i00',
    'name' => 'Blessed Seraph Shield',
    'additionalname' => 'Reinforced',
    'description' => 'Increases Shield Defense.  <Enchanting> Use Scroll: Enchant R-grade Armor.',
    'is_trade' => 1,
    'is_drop' => 1,
    'is_destruct' => 1,
    'crystal_type' => 'r95',
    'consume_type' => 'consume_type_normal',
  ],
  19688 => 
  [
    'item_id' => 19688,
    'icon' => 'armor_helmet_i00',
    'name' => 'Blessed Seraph Helmet',
    'additionalname' => 'Not used',
    'description' => '<Enchanting>Use Scroll: Enchant R-grade Armor.<Enhancing>Take this armor enchanted to +6, R-grade Crystals, R-grade Gemstones and Crystal of Protection and go to Head Blacksmith in any town to enhance the armor to Eternal Armor.',
    'is_trade' => 1,
    'is_drop' => 1,
    'is_destruct' => 1,
    'crystal_type' => 'r95',
    'consume_type' => 'consume_type_normal',
  ],
  19689 => 
  [
    'item_id' => 19689,
    'icon' => 'armor_t402_u_i00',
    'name' => 'Blessed Seraph Armor',
    'additionalname' => 'Not used',
    'description' => 'When enchanted to +4, increases P. Evasion, Speed and P. Debuff Resistance, also decreases received Critical Rate from standard attacks.<Enchanting>Use Scroll: Enchant R-grade Armor.<Enhancing>Take this armor enchanted to +6, R-grade Crystals, R-grade Gemstones and Crystal of Protection and go to Head Blacksmith in any town to enhance it to the Eternal armor.',
    'is_trade' => 1,
    'is_drop' => 1,
    'is_destruct' => 1,
    'crystal_type' => 'r95',
    'consume_type' => 'consume_type_normal',
  ],
  19690 => 
  [
    'item_id' => 19690,
    'icon' => 'armor_t402_l_i00',
    'name' => 'Blessed Seraph Leggings',
    'additionalname' => 'Not used',
    'description' => '<Enchanting>Use Scroll: Enchant R-grade Armor.<Enhancing>Take this armor enchanted to +6, R-grade Crystals, R-grade Gemstones and Crystal of Protection and go to Head Blacksmith in any town to enhance the armor to Eternal Armor.',
    'is_trade' => 1,
    'is_drop' => 1,
    'is_destruct' => 1,
    'crystal_type' => 'r95',
    'consume_type' => 'consume_type_normal',
  ],
  19691 => 
  [
    'item_id' => 19691,
    'icon' => 'armor_t402_g_i00',
    'name' => 'Blessed Seraph Gloves',
    'additionalname' => 'Not used',
    'description' => '<Enchanting>Use Scroll: Enchant R-grade Armor.<Enhancing>Take this armor enchanted to +6, R-grade Crystals, R-grade Gemstones and Crystal of Protection and go to Head Blacksmith in any town to enhance the armor to Eternal Armor.',
    'is_trade' => 1,
    'is_drop' => 1,
    'is_destruct' => 1,
    'crystal_type' => 'r95',
    'consume_type' => 'consume_type_normal',
  ],
  19692 => 
  [
    'item_id' => 19692,
    'icon' => 'armor_t402_b_i00',
    'name' => 'Blessed Seraph Boots',
    'additionalname' => 'Not used',
    'description' => '<Enchanting>Use Scroll: Enchant R-grade Armor.<Enhancing>Take this armor enchanted to +6, R-grade Crystals, R-grade Gemstones and Crystal of Protection and go to Head Blacksmith in any town to enhance the armor to Eternal Armor.',
    'is_trade' => 1,
    'is_drop' => 1,
    'is_destruct' => 1,
    'crystal_type' => 'r95',
    'consume_type' => 'consume_type_normal',
  ],
  19693 => 
  [
    'item_id' => 19693,
    'icon' => 'armor_circlet_i00',
    'name' => 'Blessed Seraph Circlet',
    'additionalname' => 'Reinforced robe',
    'description' => '<Enchanting>Use Scroll: Enchant R-grade Armor.<Enhancing>Take this armor enchanted to +6, R-grade Crystals, R-grade Gemstones and Crystal of Protection and go to Head Blacksmith in any town to enhance the armor to Eternal Armor.',
    'is_trade' => 1,
    'is_drop' => 1,
    'is_destruct' => 1,
    'crystal_type' => 'r95',
    'consume_type' => 'consume_type_normal',
  ],
  19694 => 
  [
    'item_id' => 19694,
    'icon' => 'armor_t403_u_i00',
    'name' => 'Blessed Seraph Tunic',
    'additionalname' => 'Reinforced robe',
    'description' => 'When enchanted to +4, increases M. Evasion and M. Debuff Resistance, also decreases received Critical Damage from standard attacks and received Critical Rate from standard attacks.<Enchanting>Use Scroll: Enchant R-grade Armor.<Enhancing>Take this armor enchanted to +6, R-grade Crystals, R-grade Gemstones and Crystal of Protection and go to Head Blacksmith in any town to enhance it to the Eternal armor.',
    'is_trade' => 1,
    'is_drop' => 1,
    'is_destruct' => 1,
    'crystal_type' => 'r95',
    'consume_type' => 'consume_type_normal',
  ],
  19695 => 
  [
    'item_id' => 19695,
    'icon' => 'armor_t403_l_i00',
    'name' => 'Blessed Seraph Stockings',
    'additionalname' => 'Reinforced robe',
    'description' => '<Enchanting>Use Scroll: Enchant R-grade Armor.<Enhancing>Take this armor enchanted to +6, R-grade Crystals, R-grade Gemstones and Crystal of Protection and go to Head Blacksmith in any town to enhance the armor to Eternal Armor.',
    'is_trade' => 1,
    'is_drop' => 1,
    'is_destruct' => 1,
    'crystal_type' => 'r95',
    'consume_type' => 'consume_type_normal',
  ],
  19696 => 
  [
    'item_id' => 19696,
    'icon' => 'armor_t403_g_i00',
    'name' => 'Blessed Seraph Gloves',
    'additionalname' => 'Reinforced robe',
    'description' => '<Enchanting>Use Scroll: Enchant R-grade Armor.<Enhancing>Take this armor enchanted to +6, R-grade Crystals, R-grade Gemstones and Crystal of Protection and go to Head Blacksmith in any town to enhance the armor to Eternal Armor.',
    'is_trade' => 1,
    'is_drop' => 1,
    'is_destruct' => 1,
    'crystal_type' => 'r95',
    'consume_type' => 'consume_type_normal',
  ],
  19697 => 
  [
    'item_id' => 19697,
    'icon' => 'armor_t403_b_i00',
    'name' => 'Blessed Seraph Shoes',
    'additionalname' => 'Reinforced robe',
    'description' => '<Enchanting>Use Scroll: Enchant R-grade Armor.<Enhancing>Take this armor enchanted to +6, R-grade Crystals, R-grade Gemstones and Crystal of Protection and go to Head Blacksmith in any town to enhance the armor to Eternal Armor.',
    'is_trade' => 1,
    'is_drop' => 1,
    'is_destruct' => 1,
    'crystal_type' => 'r95',
    'consume_type' => 'consume_type_normal',
  ],
  19698 => 
  [
    'item_id' => 19698,
    'icon' => 'armor_helmet_i00',
    'name' => 'Blessed Eternal Helmet',
    'additionalname' => 'Reinforced heavy armor',
    'description' => '<Enchanting>Use Scroll: Enchant R-grade Armor.<Enhancing>Take this armor enchanted to +6, R-grade Crystals, R-grade Gemstones and Crystal of Protection and go to Head Blacksmith in any town to enhance the armor to Leviathan Armor.Can be augmented.',
    'is_trade' => 1,
    'is_drop' => 1,
    'is_destruct' => 1,
    'crystal_type' => 'r99',
    'consume_type' => 'consume_type_normal',
  ],
  19699 => 
  [
    'item_id' => 19699,
    'icon' => 'armor_t701_u_i00',
    'name' => 'Blessed Eternal Breastplate',
    'additionalname' => 'Reinforced heavy armor',
    'description' => 'When enchanted to +4, decreases Received Critical Damage from standard attacks, increases P. Def.<Enchanting>Use Scroll: Enchant R-grade Armor.<Enhancing>Take this armor enchanted to +6, R-grade Crystals, R-grade Gemstones and Crystal of Protection and go to Head Blacksmith in any town to enhance the armor to Leviathan Armor.Can be augmented.',
    'is_trade' => 1,
    'is_drop' => 1,
    'is_destruct' => 1,
    'crystal_type' => 'r99',
    'consume_type' => 'consume_type_normal',
  ],
];