<?php return [
  20700 => 
  [
    'item_id' => 20700,
    'icon' => 'br_four_leaf_clover_box_i00',
    'name' => 'Bamboo Panda Hat Pack',
    'additionalname' => '',
    'description' => 'Wrapped Pack containing Bamboo Panda Hat.',
    'is_trade' => 0,
    'is_drop' => 0,
    'is_destruct' => 1,
    'crystal_type' => 'none',
    'consume_type' => 'consume_type_stackable',
  ],
  20701 => 
  [
    'item_id' => 20701,
    'icon' => 'br_four_leaf_clover_box_i00',
    'name' => 'Bamboo Panda Hat Pack (7-day]',
    'additionalname' => 'Great Adventurer\'s Soul Power',
    'description' => 'Wrapped Pack containing Bamboo Panda Hat (7-day].',
    'is_trade' => 0,
    'is_drop' => 0,
    'is_destruct' => 1,
    'crystal_type' => 'none',
    'consume_type' => 'consume_type_stackable',
  ],
  20702 => 
  [
    'item_id' => 20702,
    'icon' => 'br_four_leaf_clover_box_i00',
    'name' => 'Sexy Panda Hat Pack',
    'additionalname' => '',
    'description' => 'Wrapped Pack containing Sexy Panda Hat.',
    'is_trade' => 0,
    'is_drop' => 0,
    'is_destruct' => 1,
    'crystal_type' => 'none',
    'consume_type' => 'consume_type_stackable',
  ],
  20703 => 
  [
    'item_id' => 20703,
    'icon' => 'br_four_leaf_clover_box_i00',
    'name' => 'Sexy Panda Hat (7-day]',
    'additionalname' => 'Blessed Resurrection',
    'description' => 'Wrapped Pack containing Sexy Panda Hat (7-day].',
    'is_trade' => 0,
    'is_drop' => 0,
    'is_destruct' => 1,
    'crystal_type' => 'none',
    'consume_type' => 'consume_type_stackable',
  ],
  20704 => 
  [
    'item_id' => 20704,
    'icon' => 'br_four_leaf_clover_box_i00',
    'name' => 'Gatekeeper Hat Pack',
    'additionalname' => '',
    'description' => 'Wrapped Pack containing Gatekeeper Hat.',
    'is_trade' => 0,
    'is_drop' => 0,
    'is_destruct' => 1,
    'crystal_type' => 'none',
    'consume_type' => 'consume_type_stackable',
  ],
  20705 => 
  [
    'item_id' => 20705,
    'icon' => 'br_four_leaf_clover_box_i00',
    'name' => 'Gatekeeper Hat Pack (7-day]',
    'additionalname' => 'Appetite for Destruction',
    'description' => 'Wrapped Pack containing Gatekeeper Hat (7-day].',
    'is_trade' => 0,
    'is_drop' => 0,
    'is_destruct' => 1,
    'crystal_type' => 'none',
    'consume_type' => 'consume_type_stackable',
  ],
  20706 => 
  [
    'item_id' => 20706,
    'icon' => 'br_hallowinday_candy_i00',
    'name' => 'Revita-Pop (Event]',
    'additionalname' => '',
    'description' => 'For events. Sweet Revita-Pop. Give it to Skooldie to exchange for Halloween Toy Box.',
    'is_trade' => 1,
    'is_drop' => 1,
    'is_destruct' => 1,
    'crystal_type' => 'none',
    'consume_type' => 'consume_type_stackable',
  ],
  20707 => 
  [
    'item_id' => 20707,
    'icon' => 'br_scroll_of_wooldie_i00',
    'name' => 'Summon Scroll: Uldie (Event]',
    'additionalname' => '',
    'description' => 'For events. Use to summon Uldie, first sister of Halloween Children, to play Jack Game. Uldie can\'t be summoned with pet or if Halloween Mask is not equipped. You can\'t play Jack Game while morphed or in stance status so be cautious!',
    'is_trade' => 1,
    'is_drop' => 1,
    'is_destruct' => 1,
    'crystal_type' => 'none',
    'consume_type' => 'consume_type_stackable',
  ],
  20708 => 
  [
    'item_id' => 20708,
    'icon' => 'br_scroll_of_berdandi_i00',
    'name' => 'Summon Scroll: Belldandy (Event]',
    'additionalname' => '',
    'description' => 'For events. Use to summon Belldandy, second sister of Halloween Children, to play Jack Game. Belldandy can\'t be summoned with pet or if Halloween Mask is not equipped. You can\'t play Jack Game while morphed or in stance status so be cautious!',
    'is_trade' => 1,
    'is_drop' => 1,
    'is_destruct' => 1,
    'crystal_type' => 'none',
    'consume_type' => 'consume_type_stackable',
  ],
  20709 => 
  [
    'item_id' => 20709,
    'icon' => 'br_scroll_of_scooldie_i00',
    'name' => 'Summon Scroll: Skooldie (Event]',
    'additionalname' => '',
    'description' => 'For events. Use to summon Skooldie, little brother of Halloween Children, to practice Jack Game. Skooldie can\'t be summoned with pet or if Halloween Mask is not equipped. You can\'t play Jack Game while morphed or in stance status so be cautious!',
    'is_trade' => 0,
    'is_drop' => 0,
    'is_destruct' => 1,
    'crystal_type' => 'none',
    'consume_type' => 'consume_type_stackable',
  ],
  20710 => 
  [
    'item_id' => 20710,
    'icon' => 'etc_box_of_adventure_1_i00',
    'name' => 'Halloween Toy Box (Event]',
    'additionalname' => '',
    'description' => 'For events. One of Halloween Mask can be obtained with chance.',
    'is_trade' => 0,
    'is_drop' => 0,
    'is_destruct' => 1,
    'crystal_type' => 'none',
    'consume_type' => 'consume_type_normal',
  ],
  20711 => 
  [
    'item_id' => 20711,
    'icon' => 'br_jack0_mask_i00',
    'name' => 'Jack O\'Lantern Mask (Event]',
    'additionalname' => '',
    'description' => 'For events. Jack O\'Lantern Mask. Equip to use card skill needed to play Jack Game.',
    'is_trade' => 0,
    'is_drop' => 0,
    'is_destruct' => 1,
    'crystal_type' => 'none',
    'consume_type' => 'consume_type_normal',
  ],
  20712 => 
  [
    'item_id' => 20712,
    'icon' => 'br_frankenstein_mask_i00',
    'name' => 'Reanimated Corpse Mask (Event]',
    'additionalname' => 'Skooldie\'s Blessing: Protection of Darkness (2-hour]',
    'description' => 'For events. Super Strong Giant\'s Mask. Equip to use card skill needed to play Jack Game. Cooldown is 1 hour.',
    'is_trade' => 0,
    'is_drop' => 0,
    'is_destruct' => 1,
    'crystal_type' => 'none',
    'consume_type' => 'consume_type_normal',
  ],
  20713 => 
  [
    'item_id' => 20713,
    'icon' => 'br_scream_mask_i00',
    'name' => 'Shriek Mask (Event]',
    'additionalname' => 'Skooldie\'s Blessing: Protection of Darkness (2-hour]',
    'description' => 'For events. Shriek Mask. Equip to use card skill needed to play Jack Game. Cooldown is 1 hour.',
    'is_trade' => 0,
    'is_drop' => 0,
    'is_destruct' => 1,
    'crystal_type' => 'none',
    'consume_type' => 'consume_type_normal',
  ],
  20714 => 
  [
    'item_id' => 20714,
    'icon' => 'br_doccabi_mask_i00',
    'name' => 'Red Devil Mask (Event]',
    'additionalname' => 'Skooldie\'s Blessing: Protection of Darkness (2-hour]',
    'description' => 'For events. Red Devil Mask. Equip to use card skill needed to play Jack Game. Cooldown is 1 hour.',
    'is_trade' => 0,
    'is_drop' => 0,
    'is_destruct' => 1,
    'crystal_type' => 'none',
    'consume_type' => 'consume_type_normal',
  ],
  20715 => 
  [
    'item_id' => 20715,
    'icon' => 'br_mummy_mask_i00',
    'name' => 'Mummy Mask (Event]',
    'additionalname' => 'Skooldie\'s Blessing: Protection of Darkness (2-hour]',
    'description' => 'For events. Mummy Mask. Equip to use card skill needed to play Jack Game. Cooldown is 1 hour.',
    'is_trade' => 0,
    'is_drop' => 0,
    'is_destruct' => 1,
    'crystal_type' => 'none',
    'consume_type' => 'consume_type_normal',
  ],
  20716 => 
  [
    'item_id' => 20716,
    'icon' => 'br_alien_mask_i00',
    'name' => 'Alien Mask (Event]',
    'additionalname' => 'Skooldie\'s Blessing: Protection of Darkness (2-hour]',
    'description' => 'For events. Alien Mask. Equip to use card skill needed to play Jack Game. Cooldown is 1 hour.',
    'is_trade' => 0,
    'is_drop' => 0,
    'is_destruct' => 1,
    'crystal_type' => 'none',
    'consume_type' => 'consume_type_normal',
  ],
  20717 => 
  [
    'item_id' => 20717,
    'icon' => 'etc_box_of_adventure_1_i00',
    'name' => 'Shiny Halloween Toy Box (Event]',
    'additionalname' => '',
    'description' => 'For events. One of Shiny Halloween Mask can be obtained with chance.',
    'is_trade' => 0,
    'is_drop' => 0,
    'is_destruct' => 1,
    'crystal_type' => 'none',
    'consume_type' => 'consume_type_normal',
  ],
  20718 => 
  [
    'item_id' => 20718,
    'icon' => 'br_shiny_frankenstein_mask_i00',
    'name' => 'Shiny Reanimated Corpse Mask (Event]',
    'additionalname' => 'Blessing of Halloween (4-hour]',
    'description' => 'For events. Brightly shining Super Strong Giant\'s Mask. Equip to use card skill needed to play Jack Game. Cooldown is 2 hour.',
    'is_trade' => 0,
    'is_drop' => 0,
    'is_destruct' => 1,
    'crystal_type' => 'none',
    'consume_type' => 'consume_type_normal',
  ],
  20719 => 
  [
    'item_id' => 20719,
    'icon' => 'br_shiny_scream_mask_i00',
    'name' => 'Shiny Shriek Mask (Event]',
    'additionalname' => 'Blessing of Halloween (4-hour]',
    'description' => 'For events. Brightly shining Shriek Mask. Equip to use card skill needed to play Jack Game. Cooldown is 2 hour.',
    'is_trade' => 0,
    'is_drop' => 0,
    'is_destruct' => 1,
    'crystal_type' => 'none',
    'consume_type' => 'consume_type_normal',
  ],
  20720 => 
  [
    'item_id' => 20720,
    'icon' => 'br_shiny_doccabi_mask_i00',
    'name' => 'Shiny Red Devil Mask (Event]',
    'additionalname' => 'Blessing of Halloween (4-hour]',
    'description' => 'For events. Brightly shining Red Devil Mask. Equip to use card skill needed to play Jack Game. Cooldown is 2 hour.',
    'is_trade' => 0,
    'is_drop' => 0,
    'is_destruct' => 1,
    'crystal_type' => 'none',
    'consume_type' => 'consume_type_normal',
  ],
  20721 => 
  [
    'item_id' => 20721,
    'icon' => 'br_shiny_mummy_mask_i00',
    'name' => 'Shiny Mummy Mask (Event]',
    'additionalname' => 'Blessing of Halloween (4-hour]',
    'description' => 'For events. Brightly shining Mummy Mask. Equip to use card skill needed to play Jack Game. Cooldown is 2 hour.',
    'is_trade' => 0,
    'is_drop' => 0,
    'is_destruct' => 1,
    'crystal_type' => 'none',
    'consume_type' => 'consume_type_normal',
  ],
  20722 => 
  [
    'item_id' => 20722,
    'icon' => 'br_shiny_alien_mask_i00',
    'name' => 'Shiny Alien Mask (Event]',
    'additionalname' => 'Blessing of Halloween (4-hour]',
    'description' => 'For events. Shiny Alien Mask. Equip to use card skill needed to play Jack Game. Cooldown is 2 hour.',
    'is_trade' => 0,
    'is_drop' => 0,
    'is_destruct' => 1,
    'crystal_type' => 'none',
    'consume_type' => 'consume_type_normal',
  ],
  20723 => 
  [
    'item_id' => 20723,
    'icon' => 'br_golden_jack0_mask_i00',
    'name' => 'Golden Jack O\'Lantern Mask',
    'additionalname' => '',
    'description' => 'Jack O\'Lantern Mask made with gold. It glows gorgeously.',
    'is_trade' => 0,
    'is_drop' => 0,
    'is_destruct' => 1,
    'crystal_type' => 'none',
    'consume_type' => 'consume_type_normal',
  ],
  20724 => 
  [
    'item_id' => 20724,
    'icon' => 'br_golden_jack0_mask_i00',
    'name' => 'Golden Jack O\'Lantern Mask',
    'additionalname' => 'Golden Jack O\'Lantern\'s Authority (7-day]',
    'description' => 'Jack O\'Lantern Mask made with gold. It glows gorgeously. Cooldown is 1 hour.',
    'is_trade' => 0,
    'is_drop' => 0,
    'is_destruct' => 1,
    'crystal_type' => 'none',
    'consume_type' => 'consume_type_normal',
  ],
  20725 => 
  [
    'item_id' => 20725,
    'icon' => 'br_valakas_the_flame_i00',
    'name' => 'Red Flame Valakas',
    'additionalname' => '',
    'description' => 'Valakas\' Helm of red color as if it is burning.',
    'is_trade' => 0,
    'is_drop' => 0,
    'is_destruct' => 1,
    'crystal_type' => 'none',
    'consume_type' => 'consume_type_normal',
  ],
  20726 => 
  [
    'item_id' => 20726,
    'icon' => 'br_aga_gangsi_i00',
    'name' => 'Agathion - Zombie',
    'additionalname' => '',
    'description' => 'Bracelet that summons an Agathion - Zombie.',
    'is_trade' => 0,
    'is_drop' => 0,
    'is_destruct' => 1,
    'crystal_type' => 'none',
    'consume_type' => 'consume_type_normal',
  ],
  20727 => 
  [
    'item_id' => 20727,
    'icon' => 'br_aga_gangsi_i00',
    'name' => 'Agathion - Zombie',
    'additionalname' => 'Soul Stealth (7-day]',
    'description' => 'Bracelet that summons an Agathion - Zombie. Cooldown is 12 hours.',
    'is_trade' => 0,
    'is_drop' => 0,
    'is_destruct' => 1,
    'crystal_type' => 'none',
    'consume_type' => 'consume_type_normal',
  ],
  20728 => 
  [
    'item_id' => 20728,
    'icon' => 'br_lamp_orange_i00',
    'name' => 'Summon Scroll: Lucky Lamp',
    'additionalname' => '',
    'description' => 'Summons Sky Lantern to offer to sky with a wish.',
    'is_trade' => 0,
    'is_drop' => 0,
    'is_destruct' => 1,
    'crystal_type' => 'none',
    'consume_type' => 'consume_type_stackable',
  ],
  20729 => 
  [
    'item_id' => 20729,
    'icon' => 'br_lamp_a_yellow_i00',
    'name' => 'Summon Scroll: Ambience Sky Lantern',
    'additionalname' => '',
    'description' => 'Summons Sky Lantern to offer to sky with a wish.',
    'is_trade' => 0,
    'is_drop' => 0,
    'is_destruct' => 1,
    'crystal_type' => 'none',
    'consume_type' => 'consume_type_stackable',
  ],
  20730 => 
  [
    'item_id' => 20730,
    'icon' => 'br_lamp_b_red_i00',
    'name' => 'Summon Scroll: Rolling Lamp',
    'additionalname' => '',
    'description' => 'Summons Sky Lantern to offer to sky with a wish.',
    'is_trade' => 0,
    'is_drop' => 0,
    'is_destruct' => 1,
    'crystal_type' => 'none',
    'consume_type' => 'consume_type_stackable',
  ],
  20731 => 
  [
    'item_id' => 20731,
    'icon' => 'br_lamp_c_pink_i00',
    'name' => 'Summon Scroll: Comfort Sky Lantern',
    'additionalname' => '',
    'description' => 'Summons Sky Lantern to offer to sky with a wish.',
    'is_trade' => 0,
    'is_drop' => 0,
    'is_destruct' => 1,
    'crystal_type' => 'none',
    'consume_type' => 'consume_type_stackable',
  ],
  20732 => 
  [
    'item_id' => 20732,
    'icon' => 'br_aga_bluebird_i00',
    'name' => 'Agathion - Bluebird',
    'additionalname' => '',
    'description' => 'Bracelet that summons the Bluebird Agathion.',
    'is_trade' => 0,
    'is_drop' => 0,
    'is_destruct' => 1,
    'crystal_type' => 'none',
    'consume_type' => 'consume_type_normal',
  ],
  20733 => 
  [
    'item_id' => 20733,
    'icon' => 'br_aga_hatbird_i00',
    'name' => 'Agathion - Hatbird',
    'additionalname' => '',
    'description' => 'Bracelet that summons the Hatbird Agathion.',
    'is_trade' => 0,
    'is_drop' => 0,
    'is_destruct' => 1,
    'crystal_type' => 'none',
    'consume_type' => 'consume_type_normal',
  ],
  20734 => 
  [
    'item_id' => 20734,
    'icon' => 'br_four_leaf_clover_box_i00',
    'name' => 'Golden Jack O\'Lantern Mask Pack (7-day]',
    'additionalname' => 'Golden Jack O\'Lantern\'s Authority',
    'description' => 'Wrapped Pack with Golden Jack O\'Lantern Mask(7-day].',
    'is_trade' => 0,
    'is_drop' => 0,
    'is_destruct' => 1,
    'crystal_type' => 'none',
    'consume_type' => 'consume_type_stackable',
  ],
  20735 => 
  [
    'item_id' => 20735,
    'icon' => 'br_four_leaf_clover_box_i00',
    'name' => 'Agathion - Zombie Pack',
    'additionalname' => '',
    'description' => 'Wrapped Pack containing Agathion - Zombie.',
    'is_trade' => 0,
    'is_drop' => 0,
    'is_destruct' => 1,
    'crystal_type' => 'none',
    'consume_type' => 'consume_type_stackable',
  ],
  20736 => 
  [
    'item_id' => 20736,
    'icon' => 'br_four_leaf_clover_box_i00',
    'name' => 'Agathion - Zombie Pack (7-day]',
    'additionalname' => 'Soul Stealth',
    'description' => 'Wrapped Pack containing Agathion - Zombie (7-day].',
    'is_trade' => 0,
    'is_drop' => 0,
    'is_destruct' => 1,
    'crystal_type' => 'none',
    'consume_type' => 'consume_type_stackable',
  ],
  20737 => 
  [
    'item_id' => 20737,
    'icon' => 'br_four_leaf_clover_box_i00',
    'name' => 'Agathion - Bluebird Pack',
    'additionalname' => '',
    'description' => 'Wrapped Pack containing Agathion - Bluebird.',
    'is_trade' => 0,
    'is_drop' => 0,
    'is_destruct' => 1,
    'crystal_type' => 'none',
    'consume_type' => 'consume_type_stackable',
  ],
  20738 => 
  [
    'item_id' => 20738,
    'icon' => 'br_four_leaf_clover_box_i00',
    'name' => 'Agathion - Hatbird Pack',
    'additionalname' => '',
    'description' => 'Wrapped Pack containing Agathion - Hatbird.',
    'is_trade' => 0,
    'is_drop' => 0,
    'is_destruct' => 1,
    'crystal_type' => 'none',
    'consume_type' => 'consume_type_stackable',
  ],
  20739 => 
  [
    'item_id' => 20739,
    'icon' => 'etc_pi_gift_box_i00',
    'name' => 'Transformation Scroll Pack',
    'additionalname' => '',
    'description' => 'One of Onyx Beast, Doom Wraith, Apostle Grail morph scroll drops with chance.',
    'is_trade' => 0,
    'is_drop' => 0,
    'is_destruct' => 1,
    'crystal_type' => 'none',
    'consume_type' => 'consume_type_normal',
  ],
  20740 => 
  [
    'item_id' => 20740,
    'icon' => 'etc_pi_gift_box_i00',
    'name' => 'Cocktail Pack',
    'additionalname' => '',
    'description' => 'Wrapped Pack with sweet fruit cocktail and refreshing fruit cocktail.',
    'is_trade' => 0,
    'is_drop' => 0,
    'is_destruct' => 1,
    'crystal_type' => 'none',
    'consume_type' => 'consume_type_stackable',
  ],
  20741 => 
  [
    'item_id' => 20741,
    'icon' => 'br_cash_rune_of_sp_i00',
    'name' => 'SP Rune 30% (Event]',
    'additionalname' => '1-hour',
    'description' => 'For events. Ancient characters which endow mysterious ability if it is possessed in the inventory. It increases acquired SP by 30%. The remaining time decreases even when not playing.',
    'is_trade' => 0,
    'is_drop' => 0,
    'is_destruct' => 1,
    'crystal_type' => 'none',
    'consume_type' => 'consume_type_normal',
  ],
  20742 => 
  [
    'item_id' => 20742,
    'icon' => 'br_cash_rune_of_exp_i00',
    'name' => 'XP Rune III (Lv. 1-100+] 30% (Event]',
    'additionalname' => '1-hour',
    'description' => 'For events. Ancient characters which endow mysterious ability if it is possessed in the inventory. It increases acquired XP by 30%. The remaining time decreases even when not playing.',
    'is_trade' => 0,
    'is_drop' => 0,
    'is_destruct' => 1,
    'crystal_type' => 'none',
    'consume_type' => 'consume_type_normal',
  ],
  20743 => 
  [
    'item_id' => 20743,
    'icon' => 'br_shiny_frankenstein_mask_i00',
    'name' => 'Shiny Reanimated Corpse Mask',
    'additionalname' => 'Blessing of Halloween (7-day]',
    'description' => 'Reanimated Corpse Mask. Cooldown is 1 hour.',
    'is_trade' => 0,
    'is_drop' => 0,
    'is_destruct' => 1,
    'crystal_type' => 'none',
    'consume_type' => 'consume_type_normal',
  ],
  20744 => 
  [
    'item_id' => 20744,
    'icon' => 'br_shiny_scream_mask_i00',
    'name' => 'Shiny Shriek Mask',
    'additionalname' => 'Blessing of Halloween (7-day]',
    'description' => 'Shriek Mask. Cooldown is 1 hour.',
    'is_trade' => 0,
    'is_drop' => 0,
    'is_destruct' => 1,
    'crystal_type' => 'none',
    'consume_type' => 'consume_type_normal',
  ],
  20745 => 
  [
    'item_id' => 20745,
    'icon' => 'br_shiny_doccabi_mask_i00',
    'name' => 'Shiny Red Devil Mask',
    'additionalname' => 'Blessing of Halloween (7-day]',
    'description' => 'Red Devil Mask. Cooldown is 1 hour.',
    'is_trade' => 0,
    'is_drop' => 0,
    'is_destruct' => 1,
    'crystal_type' => 'none',
    'consume_type' => 'consume_type_normal',
  ],
  20746 => 
  [
    'item_id' => 20746,
    'icon' => 'br_shiny_mummy_mask_i00',
    'name' => 'Shiny Mummy Mask',
    'additionalname' => 'Blessing of Halloween (7-day]',
    'description' => 'Mummy Mask. Cooldown is 1 hour.',
    'is_trade' => 0,
    'is_drop' => 0,
    'is_destruct' => 1,
    'crystal_type' => 'none',
    'consume_type' => 'consume_type_normal',
  ],
  20747 => 
  [
    'item_id' => 20747,
    'icon' => 'br_shiny_alien_mask_i00',
    'name' => 'Shiny Alien Mask',
    'additionalname' => 'Blessing of Halloween (7-day]',
    'description' => 'Shiny Alien Mask. Cooldown is 1 hour.',
    'is_trade' => 0,
    'is_drop' => 0,
    'is_destruct' => 1,
    'crystal_type' => 'none',
    'consume_type' => 'consume_type_normal',
  ],
  20748 => 
  [
    'item_id' => 20748,
    'icon' => 'br_four_leaf_clover_box_i00',
    'name' => 'Shiny Reanimated Corpse Mask Pack (7-day]',
    'additionalname' => 'Blessing of Halloween',
    'description' => 'Wrapped Pack with Reanimated Corpse Mask.',
    'is_trade' => 0,
    'is_drop' => 0,
    'is_destruct' => 1,
    'crystal_type' => 'none',
    'consume_type' => 'consume_type_stackable',
  ],
  20749 => 
  [
    'item_id' => 20749,
    'icon' => 'br_four_leaf_clover_box_i00',
    'name' => 'Shiny Shriek Mask Pack (7-day]',
    'additionalname' => 'Blessing of Halloween',
    'description' => 'Wrapped Pack with Shriek Mask.',
    'is_trade' => 0,
    'is_drop' => 0,
    'is_destruct' => 1,
    'crystal_type' => 'none',
    'consume_type' => 'consume_type_stackable',
  ],
  20750 => 
  [
    'item_id' => 20750,
    'icon' => 'br_four_leaf_clover_box_i00',
    'name' => 'Shiny Red Devil Mask Pack (7-day]',
    'additionalname' => 'Blessing of Halloween',
    'description' => 'Wrapped Pack with Red Devil Mask.',
    'is_trade' => 0,
    'is_drop' => 0,
    'is_destruct' => 1,
    'crystal_type' => 'none',
    'consume_type' => 'consume_type_stackable',
  ],
  20751 => 
  [
    'item_id' => 20751,
    'icon' => 'br_four_leaf_clover_box_i00',
    'name' => 'Shiny Mummy Mask Pack (7-day]',
    'additionalname' => 'Blessing of Halloween',
    'description' => 'Wrapped Pack with Mummy Mask.',
    'is_trade' => 0,
    'is_drop' => 0,
    'is_destruct' => 1,
    'crystal_type' => 'none',
    'consume_type' => 'consume_type_stackable',
  ],
  20752 => 
  [
    'item_id' => 20752,
    'icon' => 'br_four_leaf_clover_box_i00',
    'name' => 'Shiny Alien Mask Pack (7-day]',
    'additionalname' => 'Blessing of Halloween',
    'description' => 'Wrapped Pack with Shiny Alien Mask.',
    'is_trade' => 0,
    'is_drop' => 0,
    'is_destruct' => 1,
    'crystal_type' => 'none',
    'consume_type' => 'consume_type_stackable',
  ],
  20753 => 
  [
    'item_id' => 20753,
    'icon' => 'br_four_leaf_clover_box_i00',
    'name' => 'Santa\'s Gift Box',
    'additionalname' => '',
    'description' => 'Box containing Santas\' Christmas Gift. You must receive this gift to end the year on a good note!',
    'is_trade' => 0,
    'is_drop' => 0,
    'is_destruct' => 1,
    'crystal_type' => 'none',
    'consume_type' => 'consume_type_stackable',
  ],
  20754 => 
  [
    'item_id' => 20754,
    'icon' => 'br_four_leaf_clover_box_i00',
    'name' => 'Santa\'s Gift Box - Jackpot',
    'additionalname' => '',
    'description' => 'Box containing Santas\' Biggest Christmas Gift! You must receive this gift to end the year on a good note!',
    'is_trade' => 0,
    'is_drop' => 0,
    'is_destruct' => 1,
    'crystal_type' => 'none',
    'consume_type' => 'consume_type_stackable',
  ],
  20755 => 
  [
    'item_id' => 20755,
    'icon' => 'etc_lottery_card_i00',
    'name' => 'Santa\'s Weapon Coupon - Regular',
    'additionalname' => '24-hour',
    'description' => 'Take this coupon to the Santa in any town, and you will receive a very powerful weapon.',
    'is_trade' => 0,
    'is_drop' => 0,
    'is_destruct' => 1,
    'crystal_type' => 'none',
    'consume_type' => 'consume_type_normal',
  ],
  20756 => 
  [
    'item_id' => 20756,
    'icon' => 'etc_lottery_card_i00',
    'name' => 'Santa\'s Shirt Coupon',
    'additionalname' => '24-hour',
    'description' => 'Take this coupon to the Santa in any town, and you will receive a Holiday Shirt.',
    'is_trade' => 0,
    'is_drop' => 0,
    'is_destruct' => 1,
    'crystal_type' => 'none',
    'consume_type' => 'consume_type_normal',
  ],
  20757 => 
  [
    'item_id' => 20757,
    'icon' => 'etc_lottery_card_i00',
    'name' => 'Santa\'s Weapon Coupon - Jackpot',
    'additionalname' => '24-hour',
    'description' => 'Coupon that can only be obtained by a lucky person. If you take this coupon to Santa in any town, you will receive a very powerful permanent weapon.',
    'is_trade' => 0,
    'is_drop' => 0,
    'is_destruct' => 1,
    'crystal_type' => 'none',
    'consume_type' => 'consume_type_normal',
  ],
  20758 => 
  [
    'item_id' => 20758,
    'icon' => 'etc_pi_gift_box_i00',
    'name' => 'Santa\'s Weapon Coupon Box',
    'additionalname' => '',
    'description' => 'If you use it, you can receive Santa\'s Weapon Coupon. If you\'re lucky, you might have a chance of also receiving a Weapon Coupon - Jackpot!',
    'is_trade' => 0,
    'is_drop' => 0,
    'is_destruct' => 1,
    'crystal_type' => 'none',
    'consume_type' => 'consume_type_stackable',
  ],
  20759 => 
  [
    'item_id' => 20759,
    'icon' => 'br_xmas_shirts_i00',
    'name' => 'Holiday Shirt',
    'additionalname' => '24-hour',
    'description' => 'T-shirt filled with Christmas fortune. When enchanted, it gains a powerful function.',
    'is_trade' => 0,
    'is_drop' => 0,
    'is_destruct' => 1,
    'crystal_type' => 'none',
    'consume_type' => 'consume_type_normal',
  ],
  20760 => 
  [
    'item_id' => 20760,
    'icon' => 'br_rudolf_necklace_i00',
    'name' => 'Rudolph Necklace (Event]',
    'additionalname' => '',
    'description' => 'Necklace that can summon a Rudolph.',
    'is_trade' => 0,
    'is_drop' => 0,
    'is_destruct' => 1,
    'crystal_type' => 'none',
    'consume_type' => 'consume_type_normal',
  ],
  20761 => 
  [
    'item_id' => 20761,
    'icon' => 'br_rudolf_necklace_i01',
    'name' => 'Rudolph Necklace',
    'additionalname' => '',
    'description' => 'Necklace that can summon a Rudolph. Can keep a cute baby Rudolph.',
    'is_trade' => 0,
    'is_drop' => 0,
    'is_destruct' => 1,
    'crystal_type' => 'none',
    'consume_type' => 'consume_type_normal',
  ],
  20762 => 
  [
    'item_id' => 20762,
    'icon' => 'etc_ticket_red_i00',
    'name' => 'Rudolph Pet Coupon',
    'additionalname' => '7-day',
    'description' => 'Coupon that can be exchanged for a Rudolph Necklace.',
    'is_trade' => 0,
    'is_drop' => 0,
    'is_destruct' => 1,
    'crystal_type' => 'none',
    'consume_type' => 'consume_type_normal',
  ],
  20763 => 
  [
    'item_id' => 20763,
    'icon' => 'etc_royal_membership_i00',
    'name' => 'Rudolph Rearing Certificate',
    'additionalname' => '24-hour',
    'description' => 'Certificate that shows you have received three reindeer necklaces. If you have this item, you cannot receive more necklaces until this certificate expires.',
    'is_trade' => 0,
    'is_drop' => 0,
    'is_destruct' => 0,
    'crystal_type' => 'none',
    'consume_type' => 'consume_type_normal',
  ],
  20764 => 
  [
    'item_id' => 20764,
    'icon' => 'br_rudolf_food_purple_i00',
    'name' => 'Purple Star Candy',
    'additionalname' => '',
    'description' => 'Candy containing energy of a star. Replenishes Vitality to a certain degree upon use. Cooldown is 60 min. Vitality item with limited usage. ',
    'is_trade' => 0,
    'is_drop' => 0,
    'is_destruct' => 1,
    'crystal_type' => 'none',
    'consume_type' => 'consume_type_stackable',
  ],
  20765 => 
  [
    'item_id' => 20765,
    'icon' => 'br_rudolf_food_blue_i00',
    'name' => 'Blue Star Candy',
    'additionalname' => '',
    'description' => 'Candy containing energy of a star. Replenishes Vitality to a certain degree upon use. Cooldown is 60 min. Vitality item with limited usage. ',
    'is_trade' => 0,
    'is_drop' => 0,
    'is_destruct' => 1,
    'crystal_type' => 'none',
    'consume_type' => 'consume_type_stackable',
  ],
  20766 => 
  [
    'item_id' => 20766,
    'icon' => 'br_rudolf_food_red_i00',
    'name' => 'Red Star Candy',
    'additionalname' => '',
    'description' => 'Candy containing energy of a star. Replenishes Vitality to a certain degree upon use. Cooldown is 60 min. Vitality item with limited usage. ',
    'is_trade' => 0,
    'is_drop' => 0,
    'is_destruct' => 1,
    'crystal_type' => 'none',
    'consume_type' => 'consume_type_stackable',
  ],
  20767 => 
  [
    'item_id' => 20767,
    'icon' => 'br_rudolf_food_orange_i00',
    'name' => 'Orange Star Candy',
    'additionalname' => '',
    'description' => 'Candy containing energy of a star. Replenishes Vitality to a certain degree upon use. Cooldown is 60 min. Vitality item with limited usage. ',
    'is_trade' => 0,
    'is_drop' => 0,
    'is_destruct' => 1,
    'crystal_type' => 'none',
    'consume_type' => 'consume_type_stackable',
  ],
  20768 => 
  [
    'item_id' => 20768,
    'icon' => 'br_rudolf_food_unknown_i00',
    'name' => 'Mysterious Food',
    'additionalname' => '',
    'description' => 'Food containing mysterious power. When eaten, Vitality is maintained for 20 minutes when acquiring XP. Vitality item with limited usage. ',
    'is_trade' => 0,
    'is_drop' => 0,
    'is_destruct' => 1,
    'crystal_type' => 'none',
    'consume_type' => 'consume_type_stackable',
  ],
  20769 => 
  [
    'item_id' => 20769,
    'icon' => 'br_baby_food_i00',
    'name' => 'Rudolph Baby Food',
    'additionalname' => '',
    'description' => 'Nutritious food that a baby Rudolph must eat to grow into a Boy Rudolph.',
    'is_trade' => 0,
    'is_drop' => 0,
    'is_destruct' => 1,
    'crystal_type' => 'none',
    'consume_type' => 'consume_type_stackable',
  ],
  20770 => 
  [
    'item_id' => 20770,
    'icon' => 'br_Xmas_apple_basket_i00',
    'name' => 'Apple Basket Herb',
    'additionalname' => '',
    'description' => 'Fruit basket full of delicious-looking apples.',
    'is_trade' => 1,
    'is_drop' => 1,
    'is_destruct' => 1,
    'crystal_type' => 'none',
    'consume_type' => 'consume_type_normal',
  ],
  20771 => 
  [
    'item_id' => 20771,
    'icon' => 'br_Xmas_orange_basket_i00',
    'name' => 'Orange Basket Herb',
    'additionalname' => '',
    'description' => 'Fruit basket full of delicious-looking oranges.',
    'is_trade' => 1,
    'is_drop' => 1,
    'is_destruct' => 1,
    'crystal_type' => 'none',
    'consume_type' => 'consume_type_normal',
  ],
  20772 => 
  [
    'item_id' => 20772,
    'icon' => 'br_Xmas_banana_basket_i00',
    'name' => 'Banana Basket Herb',
    'additionalname' => '',
    'description' => 'Fruit basket full of delicious-looking bananas.',
    'is_trade' => 1,
    'is_drop' => 1,
    'is_destruct' => 1,
    'crystal_type' => 'none',
    'consume_type' => 'consume_type_normal',
  ],
  20773 => 
  [
    'item_id' => 20773,
    'icon' => 'br_four_leaf_clover_box_i00',
    'name' => 'Rudolph\'s Gift',
    'additionalname' => '',
    'description' => 'Rudolph\'s Gift filled with Christmas fortune. Contains a wrapped Rudolph Pet Coupon, 4 Vitality Star Candy, Mysterious Food, and Transformation Scroll Pack.',
    'is_trade' => 0,
    'is_drop' => 0,
    'is_destruct' => 1,
    'crystal_type' => 'none',
    'consume_type' => 'consume_type_stackable',
  ],
  20774 => 
  [
    'item_id' => 20774,
    'icon' => 'br_aga_warriorgod_i00',
    'name' => 'Agathion - Guangong',
    'additionalname' => 'Aura of Fury (7-day]',
    'description' => 'Bracelet that summons an Agathion - Guangong. Cooldown is 5 min.',
    'is_trade' => 0,
    'is_drop' => 0,
    'is_destruct' => 1,
    'crystal_type' => 'none',
    'consume_type' => 'consume_type_normal',
  ],
  20775 => 
  [
    'item_id' => 20775,
    'icon' => 'br_aga_mercygod_i00',
    'name' => 'Agathion - Gwanseum Nyang Nyang',
    'additionalname' => 'Blessing of Mercy (7-day]',
    'description' => 'Bracelet that summons an Agathion - Gwanseum Nyang Nyang. Depending on the requirements, the Blessing of Mercy that fills HP casts automatically.',
    'is_trade' => 0,
    'is_drop' => 0,
    'is_destruct' => 1,
    'crystal_type' => 'none',
    'consume_type' => 'consume_type_normal',
  ],
  20776 => 
  [
    'item_id' => 20776,
    'icon' => 'br_aga_blue_pekingopera_i00',
    'name' => 'Agathion - Blue Opera',
    'additionalname' => 'Sword of Recovery (7-day]',
    'description' => 'Bracelet that summons an Agathion - Blue Opera. Depending on the requirements, the Sword of Recovery that fills HP casts automatically.',
    'is_trade' => 0,
    'is_drop' => 0,
    'is_destruct' => 1,
    'crystal_type' => 'none',
    'consume_type' => 'consume_type_normal',
  ],
  20777 => 
  [
    'item_id' => 20777,
    'icon' => 'br_aga_blue_pekingopera_i00',
    'name' => 'Agathion - Blue Opera',
    'additionalname' => 'Sword of Lightning (7-day]',
    'description' => 'Bracelet that summons an Agathion - Blue Opera. Depending on the requirements, the Sword of Lightning that inflicts damage on the enemy casts automatically.',
    'is_trade' => 0,
    'is_drop' => 0,
    'is_destruct' => 1,
    'crystal_type' => 'none',
    'consume_type' => 'consume_type_normal',
  ],
  20778 => 
  [
    'item_id' => 20778,
    'icon' => 'br_aga_pekingopera_i00',
    'name' => 'Agathion - Red Opera',
    'additionalname' => 'Spear of Flames (7-day]',
    'description' => 'Bracelet that summons an Agathion - Red Opera. Depending on the requirements, the Spear of Flames that inflicts damage on the enemy casts automatically.',
    'is_trade' => 0,
    'is_drop' => 0,
    'is_destruct' => 1,
    'crystal_type' => 'none',
    'consume_type' => 'consume_type_normal',
  ],
  20779 => 
  [
    'item_id' => 20779,
    'icon' => 'br_aga_redblue_pekingopera_i00',
    'name' => 'Agathion - Opera',
    'additionalname' => '',
    'description' => 'Bracelet that summons an Agathion - Opera.',
    'is_trade' => 0,
    'is_drop' => 0,
    'is_destruct' => 1,
    'crystal_type' => 'none',
    'consume_type' => 'consume_type_normal',
  ],
  20780 => 
  [
    'item_id' => 20780,
    'icon' => 'br_aga_redblue_pekingopera_i00',
    'name' => 'Agathion - Opera',
    'additionalname' => 'Sword of Life (30-day]',
    'description' => 'Bracelet that summons an Agathion - Opera.',
    'is_trade' => 0,
    'is_drop' => 0,
    'is_destruct' => 1,
    'crystal_type' => 'none',
    'consume_type' => 'consume_type_normal',
  ],
  20781 => 
  [
    'item_id' => 20781,
    'icon' => 'br_aga_chinesedress_i00',
    'name' => 'Agathion - Miss Chipao',
    'additionalname' => 'Decrease Weight (7-day]',
    'description' => 'Bracelet that summons Agathion - Miss Chipao. Cooldown is 4 hours.',
    'is_trade' => 0,
    'is_drop' => 0,
    'is_destruct' => 1,
    'crystal_type' => 'none',
    'consume_type' => 'consume_type_normal',
  ],
  20782 => 
  [
    'item_id' => 20782,
    'icon' => 'br_aga_suno_trumpet_i00',
    'name' => 'Agathion - Nepal Snow',
    'additionalname' => '',
    'description' => 'Bracelet that summons an Agathion - Nepal Snow.',
    'is_trade' => 0,
    'is_drop' => 0,
    'is_destruct' => 1,
    'crystal_type' => 'none',
    'consume_type' => 'consume_type_normal',
  ],
  20783 => 
  [
    'item_id' => 20783,
    'icon' => 'br_aga_suno_ball_i00',
    'name' => 'Agathion - Round Ball Snow',
    'additionalname' => '',
    'description' => 'Bracelet that summons an Agathion - Round Ball Snow.',
    'is_trade' => 0,
    'is_drop' => 0,
    'is_destruct' => 1,
    'crystal_type' => 'none',
    'consume_type' => 'consume_type_normal',
  ],
  20784 => 
  [
    'item_id' => 20784,
    'icon' => 'br_aga_suno_tall_i00',
    'name' => 'Agathion - Ladder Snow',
    'additionalname' => '',
    'description' => 'Bracelet that summons an Agathion - Ladder Snow.',
    'is_trade' => 0,
    'is_drop' => 0,
    'is_destruct' => 1,
    'crystal_type' => 'none',
    'consume_type' => 'consume_type_normal',
  ],
  20785 => 
  [
    'item_id' => 20785,
    'icon' => 'br_aga_suno_trumpet_i00',
    'name' => 'Agathion - Nepal Snow',
    'additionalname' => 'Snow\'s Haste (7-day]',
    'description' => 'Bracelet that summons an Agathion - Nepal Snow. Cooldown is 1 hour.',
    'is_trade' => 0,
    'is_drop' => 0,
    'is_destruct' => 1,
    'crystal_type' => 'none',
    'consume_type' => 'consume_type_normal',
  ],
  20786 => 
  [
    'item_id' => 20786,
    'icon' => 'br_aga_suno_ball_i00',
    'name' => 'Agathion - Round Ball Snow',
    'additionalname' => 'Snow\'s Acumen (7-day]',
    'description' => 'Bracelet that summons an Agathion - Round Ball Snow. Cooldown is 1 hour.',
    'is_trade' => 0,
    'is_drop' => 0,
    'is_destruct' => 1,
    'crystal_type' => 'none',
    'consume_type' => 'consume_type_normal',
  ],
  20787 => 
  [
    'item_id' => 20787,
    'icon' => 'br_aga_suno_tall_i00',
    'name' => 'Agathion - Ladder Snow',
    'additionalname' => 'Snow\'s Wind Walk (7-day]',
    'description' => 'Bracelet that summons an Agathion - Ladder Snow. Cooldown is 1 hour.',
    'is_trade' => 0,
    'is_drop' => 0,
    'is_destruct' => 1,
    'crystal_type' => 'none',
    'consume_type' => 'consume_type_normal',
  ],
  20788 => 
  [
    'item_id' => 20788,
    'icon' => 'br_fire_box_i00',
    'name' => 'Flame Box',
    'additionalname' => '',
    'description' => 'When used, can display a brilliant flame screen.',
    'is_trade' => 0,
    'is_drop' => 0,
    'is_destruct' => 1,
    'crystal_type' => 'none',
    'consume_type' => 'consume_type_stackable',
  ],
  20789 => 
  [
    'item_id' => 20789,
    'icon' => 'br_rocket_cap_i00',
    'name' => 'Rocket Gun Hat',
    'additionalname' => 'Chain Fireworks',
    'description' => 'Hat shaped like a rocket gun. When equipped, grants a Fireworks skill that can be used every 5 min.',
    'is_trade' => 0,
    'is_drop' => 0,
    'is_destruct' => 1,
    'crystal_type' => 'none',
    'consume_type' => 'consume_type_normal',
  ],
  20790 => 
  [
    'item_id' => 20790,
    'icon' => 'br_party_hat_gold_i00',
    'name' => 'Yellow Paper Hat',
    'additionalname' => 'Blessed Body (7-day]',
    'description' => 'Brilliant hat made of yellow paper. Cooldown is 1 hour.',
    'is_trade' => 0,
    'is_drop' => 0,
    'is_destruct' => 1,
    'crystal_type' => 'none',
    'consume_type' => 'consume_type_normal',
  ],
  20791 => 
  [
    'item_id' => 20791,
    'icon' => 'br_party_hat_mask_i00',
    'name' => 'Pink Paper Mask Set',
    'additionalname' => 'Blessed Soul (7-day]',
    'description' => 'Brilliant mask and hat made of pink paper. Cooldown is 1 hour.',
    'is_trade' => 0,
    'is_drop' => 0,
    'is_destruct' => 1,
    'crystal_type' => 'none',
    'consume_type' => 'consume_type_normal',
  ],
  20792 => 
  [
    'item_id' => 20792,
    'icon' => 'br_bigrat_cap_i00',
    'name' => 'Flavorful Cheese Hat',
    'additionalname' => '',
    'description' => 'Hat made of delicious-looking cheese. If you look carefully, you can find a hidden golden mouse.',
    'is_trade' => 0,
    'is_drop' => 0,
    'is_destruct' => 1,
    'crystal_type' => 'none',
    'consume_type' => 'consume_type_normal',
  ],
  20793 => 
  [
    'item_id' => 20793,
    'icon' => 'br_goldrat_cap_i00',
    'name' => 'Sweet Cheese Hat',
    'additionalname' => '',
    'description' => 'Hat made of delicious-looking cheese. If you look carefully, you can find a hidden pink mouse.',
    'is_trade' => 0,
    'is_drop' => 0,
    'is_destruct' => 1,
    'crystal_type' => 'none',
    'consume_type' => 'consume_type_normal',
  ],
  20794 => 
  [
    'item_id' => 20794,
    'icon' => 'br_bigrat_cap_i00',
    'name' => 'Flavorful Cheese Hat',
    'additionalname' => 'Scent of Flavorful Cheese (7-day]',
    'description' => 'Hat made of delicious-looking cheese. If you look carefully, you can find a hidden golden mouse. Cooldown is 1 hour.',
    'is_trade' => 0,
    'is_drop' => 0,
    'is_destruct' => 1,
    'crystal_type' => 'none',
    'consume_type' => 'consume_type_normal',
  ],
  20795 => 
  [
    'item_id' => 20795,
    'icon' => 'br_goldrat_cap_i00',
    'name' => 'Sweet Cheese Hat',
    'additionalname' => 'Scent of Sweet Cheese (7-day]',
    'description' => 'Hat made of delicious-looking cheese. If you look carefully, you can find a hidden pink mouse. Cooldown is 1 hour.',
    'is_trade' => 0,
    'is_drop' => 0,
    'is_destruct' => 1,
    'crystal_type' => 'none',
    'consume_type' => 'consume_type_normal',
  ],
  20796 => 
  [
    'item_id' => 20796,
    'icon' => 'br_four_leaf_clover_box_i00',
    'name' => 'Agathion - Guangong Pack (7-day]',
    'additionalname' => 'Aura of Fury ',
    'description' => 'Wrapped Pack containing Agathion - Guangong (7-day].',
    'is_trade' => 0,
    'is_drop' => 0,
    'is_destruct' => 1,
    'crystal_type' => 'none',
    'consume_type' => 'consume_type_stackable',
  ],
  20797 => 
  [
    'item_id' => 20797,
    'icon' => 'br_four_leaf_clover_box_i00',
    'name' => 'Agathion - Gwanseum Nyang Nyang Pack (7-day]',
    'additionalname' => 'Blessing of Mercy ',
    'description' => 'Wrapped Pack containing Agathion - Gwanseum Nyang Nyang (7-day].',
    'is_trade' => 0,
    'is_drop' => 0,
    'is_destruct' => 1,
    'crystal_type' => 'none',
    'consume_type' => 'consume_type_stackable',
  ],
  20798 => 
  [
    'item_id' => 20798,
    'icon' => 'br_four_leaf_clover_box_i00',
    'name' => 'Agathion - Blue Opera Pack (7-day]',
    'additionalname' => 'Sword of Recovery ',
    'description' => 'Wrapped Pack containing Agathion - Blue Opera (7 day - Sword of Recovery].',
    'is_trade' => 0,
    'is_drop' => 0,
    'is_destruct' => 1,
    'crystal_type' => 'none',
    'consume_type' => 'consume_type_stackable',
  ],
  20799 => 
  [
    'item_id' => 20799,
    'icon' => 'br_four_leaf_clover_box_i00',
    'name' => 'Agathion - Blue Opera Pack (7-day]',
    'additionalname' => 'Sword of Lightning ',
    'description' => 'Wrapped Pack containing Agathion - Blue Opera (7 day - Sword of Lightning].',
    'is_trade' => 0,
    'is_drop' => 0,
    'is_destruct' => 1,
    'crystal_type' => 'none',
    'consume_type' => 'consume_type_stackable',
  ],
];