<?php return [
  20800 => 
  [
    'item_id' => 20800,
    'icon' => 'br_four_leaf_clover_box_i00',
    'name' => 'Agathion - Red Opera Pack (7-day]',
    'additionalname' => 'Spear of Flames',
    'description' => 'Wrapped Pack containing Agathion - Red Opera (7-day].',
    'is_trade' => 0,
    'is_drop' => 0,
    'is_destruct' => 1,
    'crystal_type' => 'none',
    'consume_type' => 'consume_type_stackable',
  ],
  20801 => 
  [
    'item_id' => 20801,
    'icon' => 'br_four_leaf_clover_box_i00',
    'name' => 'Agathion - Opera Pack',
    'additionalname' => '',
    'description' => 'Wrapped Pack containing Agathion - Opera.',
    'is_trade' => 0,
    'is_drop' => 0,
    'is_destruct' => 1,
    'crystal_type' => 'none',
    'consume_type' => 'consume_type_stackable',
  ],
  20802 => 
  [
    'item_id' => 20802,
    'icon' => 'br_four_leaf_clover_box_i00',
    'name' => 'Agathion - Opera Pack (30-day]',
    'additionalname' => 'Sword of Life',
    'description' => 'Wrapped Pack containing Agathion - Opera.',
    'is_trade' => 0,
    'is_drop' => 0,
    'is_destruct' => 1,
    'crystal_type' => 'none',
    'consume_type' => 'consume_type_stackable',
  ],
  20803 => 
  [
    'item_id' => 20803,
    'icon' => 'br_four_leaf_clover_box_i00',
    'name' => 'Agathion - Miss Chipao Pack (7-day]',
    'additionalname' => 'Decrease Weight',
    'description' => 'Wrapped Pack containing Agathion - Miss Chipao (7-day].',
    'is_trade' => 0,
    'is_drop' => 0,
    'is_destruct' => 1,
    'crystal_type' => 'none',
    'consume_type' => 'consume_type_stackable',
  ],
  20804 => 
  [
    'item_id' => 20804,
    'icon' => 'br_four_leaf_clover_box_i00',
    'name' => 'Agathion - Nepal Snow Pack',
    'additionalname' => '',
    'description' => 'Wrapped Pack containing Agathion - Nepal Snow.',
    'is_trade' => 0,
    'is_drop' => 0,
    'is_destruct' => 1,
    'crystal_type' => 'none',
    'consume_type' => 'consume_type_stackable',
  ],
  20805 => 
  [
    'item_id' => 20805,
    'icon' => 'br_four_leaf_clover_box_i00',
    'name' => 'Agathion - Round Ball Snow Pack',
    'additionalname' => '',
    'description' => 'Wrapped Pack containing Agathion - Round Ball Snow.',
    'is_trade' => 0,
    'is_drop' => 0,
    'is_destruct' => 1,
    'crystal_type' => 'none',
    'consume_type' => 'consume_type_stackable',
  ],
  20806 => 
  [
    'item_id' => 20806,
    'icon' => 'br_four_leaf_clover_box_i00',
    'name' => 'Agathion - Ladder Snow Pack',
    'additionalname' => '',
    'description' => 'Wrapped Pack containing Agathion - Ladder Snow.',
    'is_trade' => 0,
    'is_drop' => 0,
    'is_destruct' => 1,
    'crystal_type' => 'none',
    'consume_type' => 'consume_type_stackable',
  ],
  20807 => 
  [
    'item_id' => 20807,
    'icon' => 'br_four_leaf_clover_box_i00',
    'name' => 'Agathion - Nepal Snow Pack (7-day]',
    'additionalname' => 'Snow\'s Haste',
    'description' => 'Wrapped Pack containing Agathion - Nepal Snow (7-day].',
    'is_trade' => 0,
    'is_drop' => 0,
    'is_destruct' => 1,
    'crystal_type' => 'none',
    'consume_type' => 'consume_type_stackable',
  ],
  20808 => 
  [
    'item_id' => 20808,
    'icon' => 'br_four_leaf_clover_box_i00',
    'name' => 'Agathion - Round Ball Snow Pack (7-day]',
    'additionalname' => 'Snow\'s Acumen',
    'description' => 'Wrapped Pack containing Agathion - Round Ball Snow (7-day].',
    'is_trade' => 0,
    'is_drop' => 0,
    'is_destruct' => 1,
    'crystal_type' => 'none',
    'consume_type' => 'consume_type_stackable',
  ],
  20809 => 
  [
    'item_id' => 20809,
    'icon' => 'br_four_leaf_clover_box_i00',
    'name' => 'Agathion - Ladder Snow Pack (7-day]',
    'additionalname' => 'Snow\'s Wind Walk',
    'description' => 'Wrapped Pack containing Agathion - Ladder Snow (7-day].',
    'is_trade' => 0,
    'is_drop' => 0,
    'is_destruct' => 1,
    'crystal_type' => 'none',
    'consume_type' => 'consume_type_stackable',
  ],
  20810 => 
  [
    'item_id' => 20810,
    'icon' => 'br_four_leaf_clover_box_i00',
    'name' => 'Flame Box Pack',
    'additionalname' => '',
    'description' => 'Wrapped Pack containing Flame Box.',
    'is_trade' => 0,
    'is_drop' => 0,
    'is_destruct' => 1,
    'crystal_type' => 'none',
    'consume_type' => 'consume_type_stackable',
  ],
  20811 => 
  [
    'item_id' => 20811,
    'icon' => 'br_four_leaf_clover_box_i00',
    'name' => 'Rocket Gun Hat Pack',
    'additionalname' => 'Chain Fireworks',
    'description' => 'Wrapped Pack containing Rocket Gun Hat.',
    'is_trade' => 0,
    'is_drop' => 0,
    'is_destruct' => 1,
    'crystal_type' => 'none',
    'consume_type' => 'consume_type_stackable',
  ],
  20812 => 
  [
    'item_id' => 20812,
    'icon' => 'br_four_leaf_clover_box_i00',
    'name' => 'Yellow Paper Hat Pack (7-day]',
    'additionalname' => 'Blessed Body',
    'description' => 'Wrapped Pack containing Yellow Paper Hat (7-day].',
    'is_trade' => 0,
    'is_drop' => 0,
    'is_destruct' => 1,
    'crystal_type' => 'none',
    'consume_type' => 'consume_type_stackable',
  ],
  20813 => 
  [
    'item_id' => 20813,
    'icon' => 'br_four_leaf_clover_box_i00',
    'name' => 'Pink Paper Mask Set Pack (7-day]',
    'additionalname' => 'Blessed Soul',
    'description' => 'Wrapped Pack containing Pink Paper Mask Set (7-day].',
    'is_trade' => 0,
    'is_drop' => 0,
    'is_destruct' => 1,
    'crystal_type' => 'none',
    'consume_type' => 'consume_type_stackable',
  ],
  20814 => 
  [
    'item_id' => 20814,
    'icon' => 'br_four_leaf_clover_box_i00',
    'name' => 'Flavorful Cheese Hat Pack',
    'additionalname' => '',
    'description' => 'Wrapped Pack containing Flavorful Cheese Hat.',
    'is_trade' => 0,
    'is_drop' => 0,
    'is_destruct' => 1,
    'crystal_type' => 'none',
    'consume_type' => 'consume_type_stackable',
  ],
  20815 => 
  [
    'item_id' => 20815,
    'icon' => 'br_four_leaf_clover_box_i00',
    'name' => 'Sweet Cheese Hat Pack',
    'additionalname' => '',
    'description' => 'Wrapped Pack containing Sweet Cheese Hat.',
    'is_trade' => 0,
    'is_drop' => 0,
    'is_destruct' => 1,
    'crystal_type' => 'none',
    'consume_type' => 'consume_type_stackable',
  ],
  20816 => 
  [
    'item_id' => 20816,
    'icon' => 'br_four_leaf_clover_box_i00',
    'name' => 'Flavorful Cheese Hat Pack (7-day]',
    'additionalname' => 'Scent of Flavorful Cheese',
    'description' => 'Wrapped Pack containing Flavorful Cheese Hat (7-day].',
    'is_trade' => 0,
    'is_drop' => 0,
    'is_destruct' => 1,
    'crystal_type' => 'none',
    'consume_type' => 'consume_type_stackable',
  ],
  20817 => 
  [
    'item_id' => 20817,
    'icon' => 'br_four_leaf_clover_box_i00',
    'name' => 'Sweet Cheese Hat Pack (7-day]',
    'additionalname' => 'Scent of Sweet Cheese',
    'description' => 'Wrapped Pack containing Sweet Cheese Hat (7-day].',
    'is_trade' => 0,
    'is_drop' => 0,
    'is_destruct' => 1,
    'crystal_type' => 'none',
    'consume_type' => 'consume_type_stackable',
  ],
  20818 => 
  [
    'item_id' => 20818,
    'icon' => 'br_aga_local2009_b_i00',
    'name' => 'Soul Avatar - Iken',
    'additionalname' => '',
    'description' => 'Bracelet that summons the image of Iken as an Soul Avatar through the red Dimensional Door.',
    'is_trade' => 0,
    'is_drop' => 0,
    'is_destruct' => 1,
    'crystal_type' => 'none',
    'consume_type' => 'consume_type_normal',
  ],
  20819 => 
  [
    'item_id' => 20819,
    'icon' => 'br_aga_local2009_b_i00',
    'name' => 'Agathion - Iken',
    'additionalname' => 'Prominent Outsider Adventurer\'s Ability (7-day]',
    'description' => 'Bracelet that summons the image of Iken as an Agathion through the red Dimensional Door.',
    'is_trade' => 0,
    'is_drop' => 0,
    'is_destruct' => 1,
    'crystal_type' => 'none',
    'consume_type' => 'consume_type_normal',
  ],
  20820 => 
  [
    'item_id' => 20820,
    'icon' => 'br_aga_local2009_a_i00',
    'name' => 'Soul Avatar - Lanya',
    'additionalname' => '',
    'description' => 'Bracelet that summons the image of Lanya as an Soul Avatar through the red Dimensional Door.',
    'is_trade' => 0,
    'is_drop' => 0,
    'is_destruct' => 1,
    'crystal_type' => 'none',
    'consume_type' => 'consume_type_normal',
  ],
  20821 => 
  [
    'item_id' => 20821,
    'icon' => 'br_aga_local2009_a_i00',
    'name' => 'Agathion - Lanya',
    'additionalname' => 'Prominent Outsider Adventurer\'s Ability (7-day]',
    'description' => 'Bracelet that summons the image of Lanya as an Agathion through the red Dimensional Door.',
    'is_trade' => 0,
    'is_drop' => 0,
    'is_destruct' => 1,
    'crystal_type' => 'none',
    'consume_type' => 'consume_type_normal',
  ],
  20822 => 
  [
    'item_id' => 20822,
    'icon' => 'br_aga_local2009_f_i00',
    'name' => 'Soul Avatar - Gnosian',
    'additionalname' => '',
    'description' => 'Bracelet that summons the image of Gnosian as an Soul Avatar through the red Dimensional Door.',
    'is_trade' => 0,
    'is_drop' => 0,
    'is_destruct' => 1,
    'crystal_type' => 'none',
    'consume_type' => 'consume_type_normal',
  ],
  20823 => 
  [
    'item_id' => 20823,
    'icon' => 'br_aga_local2009_f_i00',
    'name' => 'Agathion - Gnosian',
    'additionalname' => 'Prominent Outsider Adventurer\'s Ability (7-day]',
    'description' => 'Bracelet that summons the image of Gnosian as an Agathion through the red Dimensional Door.',
    'is_trade' => 0,
    'is_drop' => 0,
    'is_destruct' => 1,
    'crystal_type' => 'none',
    'consume_type' => 'consume_type_normal',
  ],
  20824 => 
  [
    'item_id' => 20824,
    'icon' => 'br_aga_local2009_e_i00',
    'name' => 'Soul Avatar - Orodriel',
    'additionalname' => '',
    'description' => 'Bracelet that summons the image of Orodriel as an Soul Avatar through the red Dimensional Door.',
    'is_trade' => 0,
    'is_drop' => 0,
    'is_destruct' => 1,
    'crystal_type' => 'none',
    'consume_type' => 'consume_type_normal',
  ],
  20825 => 
  [
    'item_id' => 20825,
    'icon' => 'br_aga_local2009_e_i00',
    'name' => 'Agathion - Cheerleader Orodriel',
    'additionalname' => 'Prominent Outsider Adventurer\'s Ability (7-day]',
    'description' => 'Bracelet that summons the image of Orodriel as an Agathion through the red Dimensional Door.',
    'is_trade' => 0,
    'is_drop' => 0,
    'is_destruct' => 1,
    'crystal_type' => 'none',
    'consume_type' => 'consume_type_normal',
  ],
  20826 => 
  [
    'item_id' => 20826,
    'icon' => 'br_aga_local2009_d_i00',
    'name' => 'Soul Avatar - Lakinos',
    'additionalname' => '',
    'description' => 'Bracelet that summons the image of Lakinos as an Soul Avatar through the red Dimensional Door.',
    'is_trade' => 0,
    'is_drop' => 0,
    'is_destruct' => 1,
    'crystal_type' => 'none',
    'consume_type' => 'consume_type_normal',
  ],
  20827 => 
  [
    'item_id' => 20827,
    'icon' => 'br_aga_local2009_d_i00',
    'name' => 'Agathion - Lakinos',
    'additionalname' => 'Prominent Outsider Adventurer\'s Ability (7-day]',
    'description' => 'Bracelet that summons the image of Lakinos as an Agathion through the red Dimensional Door.',
    'is_trade' => 0,
    'is_drop' => 0,
    'is_destruct' => 1,
    'crystal_type' => 'none',
    'consume_type' => 'consume_type_normal',
  ],
  20828 => 
  [
    'item_id' => 20828,
    'icon' => 'br_aga_local2009_c_i00',
    'name' => 'Soul Avatar - Mortia',
    'additionalname' => '',
    'description' => 'Bracelet that summons the image of Mortia as an Soul Avatar through the red Dimensional Door.',
    'is_trade' => 0,
    'is_drop' => 0,
    'is_destruct' => 1,
    'crystal_type' => 'none',
    'consume_type' => 'consume_type_normal',
  ],
  20829 => 
  [
    'item_id' => 20829,
    'icon' => 'br_aga_local2009_c_i00',
    'name' => 'Agathion - Mortia',
    'additionalname' => 'Prominent Outsider Adventurer\'s Ability (7-day]',
    'description' => 'Bracelet that summons the image of Mortia as an Agathion through the red Dimensional Door.',
    'is_trade' => 0,
    'is_drop' => 0,
    'is_destruct' => 1,
    'crystal_type' => 'none',
    'consume_type' => 'consume_type_normal',
  ],
  20830 => 
  [
    'item_id' => 20830,
    'icon' => 'br_aga_local2009_h_i00',
    'name' => 'Soul Avatar - Heintz',
    'additionalname' => '',
    'description' => 'Bracelet that summons the image of Heintz as an Soul Avatar through the red Dimensional Door.',
    'is_trade' => 0,
    'is_drop' => 0,
    'is_destruct' => 1,
    'crystal_type' => 'none',
    'consume_type' => 'consume_type_normal',
  ],
  20831 => 
  [
    'item_id' => 20831,
    'icon' => 'br_aga_local2009_h_i00',
    'name' => 'Agathion - Heintz',
    'additionalname' => 'Prominent Outsider Adventurer\'s Ability (7-day]',
    'description' => 'Bracelet that summons the image of Heintz as an Agathion through the red Dimensional Door.',
    'is_trade' => 0,
    'is_drop' => 0,
    'is_destruct' => 1,
    'crystal_type' => 'none',
    'consume_type' => 'consume_type_normal',
  ],
  20832 => 
  [
    'item_id' => 20832,
    'icon' => 'br_aga_local2009_g_i00',
    'name' => 'Soul Avatar - Meruril',
    'additionalname' => '',
    'description' => 'Bracelet that summons the image of Meruril as an Soul Avatar through the red Dimensional Door.',
    'is_trade' => 0,
    'is_drop' => 0,
    'is_destruct' => 1,
    'crystal_type' => 'none',
    'consume_type' => 'consume_type_normal',
  ],
  20833 => 
  [
    'item_id' => 20833,
    'icon' => 'br_aga_local2009_g_i00',
    'name' => 'Agathion - Meruril',
    'additionalname' => 'Prominent Outsider Adventurer\'s Ability (7-day]',
    'description' => 'Bracelet that summons the image of Meruril as an Agathion through the red Dimensional Door.',
    'is_trade' => 0,
    'is_drop' => 0,
    'is_destruct' => 1,
    'crystal_type' => 'none',
    'consume_type' => 'consume_type_normal',
  ],
  20834 => 
  [
    'item_id' => 20834,
    'icon' => 'br_aga_local2009_i_i00',
    'name' => 'Soul Avatar - Taman Zu Rapatui',
    'additionalname' => '',
    'description' => 'Bracelet that summons the image of Taman Zu Rapatui as an Soul Avatar through the red Dimensional Door.',
    'is_trade' => 0,
    'is_drop' => 0,
    'is_destruct' => 1,
    'crystal_type' => 'none',
    'consume_type' => 'consume_type_normal',
  ],
  20835 => 
  [
    'item_id' => 20835,
    'icon' => 'br_aga_local2009_i_i00',
    'name' => 'Agathion - Taman Zu Rapatui',
    'additionalname' => 'Prominent Outsider Adventurer\'s Ability (7-day]',
    'description' => 'Bracelet that summons the image of Taman Zu Rapatui as an Agathion through the red Dimensional Door.',
    'is_trade' => 0,
    'is_drop' => 0,
    'is_destruct' => 1,
    'crystal_type' => 'none',
    'consume_type' => 'consume_type_normal',
  ],
  20836 => 
  [
    'item_id' => 20836,
    'icon' => 'br_aga_local2009_j_i00',
    'name' => 'Soul Avatar - Kaurin',
    'additionalname' => '',
    'description' => 'Bracelet that summons the image of Kaurin as an Soul Avatar through the red Dimensional Door.',
    'is_trade' => 0,
    'is_drop' => 0,
    'is_destruct' => 1,
    'crystal_type' => 'none',
    'consume_type' => 'consume_type_normal',
  ],
  20837 => 
  [
    'item_id' => 20837,
    'icon' => 'br_aga_local2009_j_i00',
    'name' => 'Agathion - Kaurin',
    'additionalname' => 'Prominent Outsider Adventurer\'s Ability (7-day]',
    'description' => 'Bracelet that summons the image of Kaurin as an Agathion through the red Dimensional Door.',
    'is_trade' => 0,
    'is_drop' => 0,
    'is_destruct' => 1,
    'crystal_type' => 'none',
    'consume_type' => 'consume_type_normal',
  ],
  20838 => 
  [
    'item_id' => 20838,
    'icon' => 'br_aga_local2009_l_i00',
    'name' => 'Soul Avatar - Ahertbein',
    'additionalname' => '',
    'description' => 'Bracelet that summons the image of Ahertbein as an Soul Avatar through the red Dimensional Door.',
    'is_trade' => 0,
    'is_drop' => 0,
    'is_destruct' => 1,
    'crystal_type' => 'none',
    'consume_type' => 'consume_type_normal',
  ],
  20839 => 
  [
    'item_id' => 20839,
    'icon' => 'br_aga_local2009_l_i00',
    'name' => 'Agathion - Ahertbein',
    'additionalname' => 'Prominent Outsider Adventurer\'s Ability (7-day]',
    'description' => 'Bracelet that summons the image of Ahertbein as an Agathion through the red Dimensional Door.',
    'is_trade' => 0,
    'is_drop' => 0,
    'is_destruct' => 1,
    'crystal_type' => 'none',
    'consume_type' => 'consume_type_normal',
  ],
  20840 => 
  [
    'item_id' => 20840,
    'icon' => 'br_aga_local2009_k_i00',
    'name' => 'Soul Avatar - Naonin',
    'additionalname' => '',
    'description' => 'Bracelet that summons the image of Naonin as an Soul Avatar through the red Dimensional Door.',
    'is_trade' => 0,
    'is_drop' => 0,
    'is_destruct' => 1,
    'crystal_type' => 'none',
    'consume_type' => 'consume_type_normal',
  ],
  20841 => 
  [
    'item_id' => 20841,
    'icon' => 'br_aga_local2009_k_i00',
    'name' => 'Agathion - Naonin',
    'additionalname' => 'Prominent Outsider Adventurer\'s Ability (7-day]',
    'description' => 'Bracelet that summons the image of Naonin as an Agathion through the red Dimensional Door.',
    'is_trade' => 0,
    'is_drop' => 0,
    'is_destruct' => 1,
    'crystal_type' => 'none',
    'consume_type' => 'consume_type_normal',
  ],
  20842 => 
  [
    'item_id' => 20842,
    'icon' => 'br_gold_box_i00',
    'name' => 'Soul Avatar - Iken Pack',
    'additionalname' => '',
    'description' => 'Wrapped Pack containing Soul Avatar - Iken.',
    'is_trade' => 0,
    'is_drop' => 0,
    'is_destruct' => 1,
    'crystal_type' => 'none',
    'consume_type' => 'consume_type_stackable',
  ],
  20843 => 
  [
    'item_id' => 20843,
    'icon' => 'br_silver_box_i00',
    'name' => 'Agathion - Iken Pack (7-day]',
    'additionalname' => 'Prominent Outsider Adventurer\'s Ability ',
    'description' => 'Wrapped Pack containing Agathion - Iken (7-day].',
    'is_trade' => 0,
    'is_drop' => 0,
    'is_destruct' => 1,
    'crystal_type' => 'none',
    'consume_type' => 'consume_type_stackable',
  ],
  20844 => 
  [
    'item_id' => 20844,
    'icon' => 'br_gold_box_i00',
    'name' => 'Soul Avatar - Lanya Pack',
    'additionalname' => '',
    'description' => 'Wrapped Pack containing Soul Avatar - Lanya.',
    'is_trade' => 0,
    'is_drop' => 0,
    'is_destruct' => 1,
    'crystal_type' => 'none',
    'consume_type' => 'consume_type_stackable',
  ],
  20845 => 
  [
    'item_id' => 20845,
    'icon' => 'br_silver_box_i00',
    'name' => 'Agathion - Lanya Pack (7-day]',
    'additionalname' => 'Prominent Outsider Adventurer\'s Ability ',
    'description' => 'Wrapped Pack containing Agathion - Lanya (7-day].',
    'is_trade' => 0,
    'is_drop' => 0,
    'is_destruct' => 1,
    'crystal_type' => 'none',
    'consume_type' => 'consume_type_stackable',
  ],
  20846 => 
  [
    'item_id' => 20846,
    'icon' => 'br_gold_box_i00',
    'name' => 'Soul Avatar - Gnosian Pack',
    'additionalname' => '',
    'description' => 'Wrapped Pack containing Soul Avatar - Gnosian.',
    'is_trade' => 0,
    'is_drop' => 0,
    'is_destruct' => 1,
    'crystal_type' => 'none',
    'consume_type' => 'consume_type_stackable',
  ],
  20847 => 
  [
    'item_id' => 20847,
    'icon' => 'br_silver_box_i00',
    'name' => 'Agathion - Gnosian Pack (7-day]',
    'additionalname' => 'Prominent Outsider Adventurer\'s Ability ',
    'description' => 'Wrapped Pack containing Agathion - Gnosian (7-day].',
    'is_trade' => 0,
    'is_drop' => 0,
    'is_destruct' => 1,
    'crystal_type' => 'none',
    'consume_type' => 'consume_type_stackable',
  ],
  20848 => 
  [
    'item_id' => 20848,
    'icon' => 'br_gold_box_i00',
    'name' => 'Soul Avatar - Orodriel Pack',
    'additionalname' => '',
    'description' => 'Wrapped Pack containing Soul Avatar - Orodriel.',
    'is_trade' => 0,
    'is_drop' => 0,
    'is_destruct' => 1,
    'crystal_type' => 'none',
    'consume_type' => 'consume_type_stackable',
  ],
  20849 => 
  [
    'item_id' => 20849,
    'icon' => 'br_silver_box_i00',
    'name' => 'Agathion - Cheerleader Orodriel Pack (7-day]',
    'additionalname' => 'Prominent Outsider Adventurer\'s Ability ',
    'description' => 'Wrapped Pack containing Agathion - Cheerleader Orodriel (7-day].',
    'is_trade' => 0,
    'is_drop' => 0,
    'is_destruct' => 1,
    'crystal_type' => 'none',
    'consume_type' => 'consume_type_stackable',
  ],
  20850 => 
  [
    'item_id' => 20850,
    'icon' => 'br_gold_box_i00',
    'name' => 'Soul Avatar - Lakinos Pack',
    'additionalname' => '',
    'description' => 'Wrapped Pack containing Soul Avatar - Lakinos.',
    'is_trade' => 0,
    'is_drop' => 0,
    'is_destruct' => 1,
    'crystal_type' => 'none',
    'consume_type' => 'consume_type_stackable',
  ],
  20851 => 
  [
    'item_id' => 20851,
    'icon' => 'br_silver_box_i00',
    'name' => 'Agathion - Lakinos Pack (7-day]',
    'additionalname' => 'Prominent Outsider Adventurer\'s Ability ',
    'description' => 'Wrapped Pack containing Agathion - Lakinos (7-day].',
    'is_trade' => 0,
    'is_drop' => 0,
    'is_destruct' => 1,
    'crystal_type' => 'none',
    'consume_type' => 'consume_type_stackable',
  ],
  20852 => 
  [
    'item_id' => 20852,
    'icon' => 'br_gold_box_i00',
    'name' => 'Soul Avatar - Mortia Pack',
    'additionalname' => '',
    'description' => 'Wrapped Pack containing Soul Avatar - Mortia.',
    'is_trade' => 0,
    'is_drop' => 0,
    'is_destruct' => 1,
    'crystal_type' => 'none',
    'consume_type' => 'consume_type_stackable',
  ],
  20853 => 
  [
    'item_id' => 20853,
    'icon' => 'br_silver_box_i00',
    'name' => 'Agathion - Mortia Pack (7-day]',
    'additionalname' => 'Prominent Outsider Adventurer\'s Ability ',
    'description' => 'Wrapped Pack containing Agathion - Mortia (7-day].',
    'is_trade' => 0,
    'is_drop' => 0,
    'is_destruct' => 1,
    'crystal_type' => 'none',
    'consume_type' => 'consume_type_stackable',
  ],
  20854 => 
  [
    'item_id' => 20854,
    'icon' => 'br_gold_box_i00',
    'name' => 'Soul Avatar - Heintz Pack',
    'additionalname' => '',
    'description' => 'Wrapped Pack containing Soul Avatar - Heintz.',
    'is_trade' => 0,
    'is_drop' => 0,
    'is_destruct' => 1,
    'crystal_type' => 'none',
    'consume_type' => 'consume_type_stackable',
  ],
  20855 => 
  [
    'item_id' => 20855,
    'icon' => 'br_silver_box_i00',
    'name' => 'Agathion - Heintz Pack (7-day]',
    'additionalname' => 'Prominent Outsider Adventurer\'s Ability ',
    'description' => 'Wrapped Pack containing Agathion - Heintz (7-day].',
    'is_trade' => 0,
    'is_drop' => 0,
    'is_destruct' => 1,
    'crystal_type' => 'none',
    'consume_type' => 'consume_type_stackable',
  ],
  20856 => 
  [
    'item_id' => 20856,
    'icon' => 'br_gold_box_i00',
    'name' => 'Soul Avatar - Meruril Pack',
    'additionalname' => '',
    'description' => 'Wrapped Pack containing Soul Avatar - Meruril.',
    'is_trade' => 0,
    'is_drop' => 0,
    'is_destruct' => 1,
    'crystal_type' => 'none',
    'consume_type' => 'consume_type_stackable',
  ],
  20857 => 
  [
    'item_id' => 20857,
    'icon' => 'br_silver_box_i00',
    'name' => 'Agathion - Meruril Pack (7-day]',
    'additionalname' => 'Prominent Outsider Adventurer\'s Ability ',
    'description' => 'Wrapped Pack containing Agathion - Meruril (7-day].',
    'is_trade' => 0,
    'is_drop' => 0,
    'is_destruct' => 1,
    'crystal_type' => 'none',
    'consume_type' => 'consume_type_stackable',
  ],
  20858 => 
  [
    'item_id' => 20858,
    'icon' => 'br_gold_box_i00',
    'name' => 'Soul Avatar - Taman Zu Rapatui Pack',
    'additionalname' => '',
    'description' => 'Wrapped Pack containing Soul Avatar - Taman Zu Rapatui.',
    'is_trade' => 0,
    'is_drop' => 0,
    'is_destruct' => 1,
    'crystal_type' => 'none',
    'consume_type' => 'consume_type_stackable',
  ],
  20859 => 
  [
    'item_id' => 20859,
    'icon' => 'br_silver_box_i00',
    'name' => 'Agathion - Taman Zu Rapatui Pack (7-day]',
    'additionalname' => 'Prominent Outsider Adventurer\'s Ability ',
    'description' => 'Wrapped Pack containing Agathion - Taman Zu Rapatui (7-day].',
    'is_trade' => 0,
    'is_drop' => 0,
    'is_destruct' => 1,
    'crystal_type' => 'none',
    'consume_type' => 'consume_type_stackable',
  ],
  20860 => 
  [
    'item_id' => 20860,
    'icon' => 'br_gold_box_i00',
    'name' => 'Soul Avatar - Kaurin Pack',
    'additionalname' => '',
    'description' => 'Wrapped Pack containing Soul Avatar - Kaurin.',
    'is_trade' => 0,
    'is_drop' => 0,
    'is_destruct' => 1,
    'crystal_type' => 'none',
    'consume_type' => 'consume_type_stackable',
  ],
  20861 => 
  [
    'item_id' => 20861,
    'icon' => 'br_silver_box_i00',
    'name' => 'Agathion - Kaurin Pack (7-day]',
    'additionalname' => 'Prominent Outsider Adventurer\'s Ability ',
    'description' => 'Wrapped Pack containing Agathion - Kaurin (7-day].',
    'is_trade' => 0,
    'is_drop' => 0,
    'is_destruct' => 1,
    'crystal_type' => 'none',
    'consume_type' => 'consume_type_stackable',
  ],
  20862 => 
  [
    'item_id' => 20862,
    'icon' => 'br_gold_box_i00',
    'name' => 'Soul Avatar - Ahertbein Pack',
    'additionalname' => '',
    'description' => 'Wrapped Pack containing Soul Avatar - Ahertbein.',
    'is_trade' => 0,
    'is_drop' => 0,
    'is_destruct' => 1,
    'crystal_type' => 'none',
    'consume_type' => 'consume_type_stackable',
  ],
  20863 => 
  [
    'item_id' => 20863,
    'icon' => 'br_silver_box_i00',
    'name' => 'Agathion - Ahertbein Pack (7-day]',
    'additionalname' => 'Prominent Outsider Adventurer\'s Ability ',
    'description' => 'Wrapped Pack containing Agathion - Ahertbein (7-day].',
    'is_trade' => 0,
    'is_drop' => 0,
    'is_destruct' => 1,
    'crystal_type' => 'none',
    'consume_type' => 'consume_type_stackable',
  ],
  20864 => 
  [
    'item_id' => 20864,
    'icon' => 'br_gold_box_i00',
    'name' => 'Soul Avatar - Naonin Pack',
    'additionalname' => '',
    'description' => 'Wrapped Pack containing Soul Avatar - Naonin.',
    'is_trade' => 0,
    'is_drop' => 0,
    'is_destruct' => 1,
    'crystal_type' => 'none',
    'consume_type' => 'consume_type_stackable',
  ],
  20865 => 
  [
    'item_id' => 20865,
    'icon' => 'br_silver_box_i00',
    'name' => 'Agathion - Naonin Pack (7-day]',
    'additionalname' => 'Prominent Outsider Adventurer\'s Ability ',
    'description' => 'Wrapped Pack containing Agathion - Naonin (7-day].',
    'is_trade' => 0,
    'is_drop' => 0,
    'is_destruct' => 1,
    'crystal_type' => 'none',
    'consume_type' => 'consume_type_stackable',
  ],
  20866 => 
  [
    'item_id' => 20866,
    'icon' => 'br_bright_gold_box_i00',
    'name' => 'Soul Avatar Set',
    'additionalname' => '',
    'description' => 'Large Wrapped Pack containing 12 Soul Avatar packs.',
    'is_trade' => 0,
    'is_drop' => 0,
    'is_destruct' => 1,
    'crystal_type' => 'none',
    'consume_type' => 'consume_type_stackable',
  ],
  20867 => 
  [
    'item_id' => 20867,
    'icon' => 'br_kadomatsu_wp_i00',
    'name' => 'Kadomas Transformation Stick',
    'additionalname' => '7-day',
    'description' => 'Kadomas Transformation Stick. 7-day.',
    'is_trade' => 0,
    'is_drop' => 0,
    'is_destruct' => 1,
    'crystal_type' => 'none',
    'consume_type' => 'consume_type_normal',
  ],
  20868 => 
  [
    'item_id' => 20868,
    'icon' => 'br_kotatsu_i00',
    'name' => 'Kotatz',
    'additionalname' => '',
    'description' => 'Summons Kotatz, who increases HP Recovery Rate by 40% and MP Recovery Rate by 20%. The Recovery Bonus effect occurs only when summoned at a certain distance away from the village.',
    'is_trade' => 0,
    'is_drop' => 0,
    'is_destruct' => 1,
    'crystal_type' => 'none',
    'consume_type' => 'consume_type_stackable',
  ],
  20869 => 
  [
    'item_id' => 20869,
    'icon' => 'br_otoshidama_i00',
    'name' => 'New Year\'s Money',
    'additionalname' => '',
    'description' => 'Contains a Kadomas Transformation Stick and 3 Kotatz.',
    'is_trade' => 0,
    'is_drop' => 0,
    'is_destruct' => 1,
    'crystal_type' => 'none',
    'consume_type' => 'consume_type_stackable',
  ],
  20870 => 
  [
    'item_id' => 20870,
    'icon' => 'br_firecracker_red_i00',
    'name' => 'Red Firecracker',
    'additionalname' => '',
    'description' => 'Ignites a Red Firecracker. For 10 minutes, increases Water Resistance by 30 and STR by 1. Cooldown is 4 hours.',
    'is_trade' => 0,
    'is_drop' => 0,
    'is_destruct' => 1,
    'crystal_type' => 'none',
    'consume_type' => 'consume_type_stackable',
  ],
  20871 => 
  [
    'item_id' => 20871,
    'icon' => 'br_firecracker_gold_i00',
    'name' => 'Gold Firecracker',
    'additionalname' => '',
    'description' => 'Ignites a Gold Firecracker. For 10 minutes, increases Holy Resistance by 30 and CON by 1. Cooldown is 4 hours.',
    'is_trade' => 0,
    'is_drop' => 0,
    'is_destruct' => 1,
    'crystal_type' => 'none',
    'consume_type' => 'consume_type_stackable',
  ],
  20872 => 
  [
    'item_id' => 20872,
    'icon' => 'br_firecracker_blue_i00',
    'name' => 'Blue Firecracker',
    'additionalname' => '',
    'description' => 'Ignites a Blue Firecracker. For 10 minutes, increases Fire Resistance by 30 and DEX by 1. Cooldown is 4 hours.',
    'is_trade' => 0,
    'is_drop' => 0,
    'is_destruct' => 1,
    'crystal_type' => 'none',
    'consume_type' => 'consume_type_stackable',
  ],
  20873 => 
  [
    'item_id' => 20873,
    'icon' => 'br_firecracker_pink_i00',
    'name' => 'Pink Firecracker',
    'additionalname' => '',
    'description' => 'Ignites a Pink Firecracker. For 10 minutes, increases Earth Resistance by 30 and MEN by 1. Cooldown is 4 hours.',
    'is_trade' => 0,
    'is_drop' => 0,
    'is_destruct' => 1,
    'crystal_type' => 'none',
    'consume_type' => 'consume_type_stackable',
  ],
  20874 => 
  [
    'item_id' => 20874,
    'icon' => 'br_firecracker_white_i00',
    'name' => 'White Firecracker',
    'additionalname' => '',
    'description' => 'Ignites a white firecracker. For 10 minutes, increases wind attribute defense by 30 and WIT by 1. Cooldown is 4 hours.',
    'is_trade' => 0,
    'is_drop' => 0,
    'is_destruct' => 1,
    'crystal_type' => 'none',
    'consume_type' => 'consume_type_stackable',
  ],
  20875 => 
  [
    'item_id' => 20875,
    'icon' => 'br_firecracker_silver_i00',
    'name' => 'Silver Firecracker',
    'additionalname' => '',
    'description' => 'Ignites a Silver Firecracker. For 10 minutes, increases Dark Resistance by 30 and INT by 1. Cooldown is 4 hours.',
    'is_trade' => 0,
    'is_drop' => 0,
    'is_destruct' => 1,
    'crystal_type' => 'none',
    'consume_type' => 'consume_type_stackable',
  ],
  20876 => 
  [
    'item_id' => 20876,
    'icon' => 'br_taiwan_newyear_food_a_i00',
    'name' => 'Love for All Seasons',
    'additionalname' => 'Empower, Wild Magic',
    'description' => 'For 1 hour, M. Atk. + 75% and the chance of magic damage by 2.',
    'is_trade' => 0,
    'is_drop' => 0,
    'is_destruct' => 1,
    'crystal_type' => 'none',
    'consume_type' => 'consume_type_stackable',
  ],
  20877 => 
  [
    'item_id' => 20877,
    'icon' => 'br_taiwan_newyear_food_b_i00',
    'name' => 'Happy New Year',
    'additionalname' => 'Death Whisper, Focus, Guidance',
    'description' => 'For 1 hour, increases Critical Damage by 35%, Critical Rate by 30, and Accuracy by 4.',
    'is_trade' => 0,
    'is_drop' => 0,
    'is_destruct' => 1,
    'crystal_type' => 'none',
    'consume_type' => 'consume_type_stackable',
  ],
  20878 => 
  [
    'item_id' => 20878,
    'icon' => 'br_taiwan_newyear_food_c_i00',
    'name' => 'Female Aniruddha',
    'additionalname' => 'Shield, Magic Barrier, Blessed Shield',
    'description' => 'For 1 hour, P. Def. + 15, M. Def. by 30%, and Shield Defense rate by 15.',
    'is_trade' => 0,
    'is_drop' => 0,
    'is_destruct' => 1,
    'crystal_type' => 'none',
    'consume_type' => 'consume_type_stackable',
  ],
  20879 => 
  [
    'item_id' => 20879,
    'icon' => 'br_taiwan_newyear_food_d_i00',
    'name' => 'Kung Hei Fat Choy',
    'additionalname' => 'Might, Berserker Spirit, Vampiric Rage',
    'description' => 'Decreases P. Def. by 8%, M. Def. by 16%, and Evasion by 4. P. Atk. + 15%, M. Atk. by 16%, Atk. Spd. by 8%, Casting Spd. by 8%, and Speed by 8 for 1 hour. Has a chance of recovering 9% of the standard melee damage inflicted on the enemy as HP.',
    'is_trade' => 0,
    'is_drop' => 0,
    'is_destruct' => 1,
    'crystal_type' => 'none',
    'consume_type' => 'consume_type_stackable',
  ],
  20880 => 
  [
    'item_id' => 20880,
    'icon' => 'br_taiwan_newyear_food_e_i00',
    'name' => 'Chinese Feast',
    'additionalname' => 'Clarity, Acumen, Blessed Soul',
    'description' => 'For 1 hour, decreases physical skill MP consumption by 20%, magic skill\'s MP consumption by 10%, and song/dance skill\'s MP consumption by 20%. Increases Casting Spd. by 30% and Max MP by 35%.',
    'is_trade' => 0,
    'is_drop' => 0,
    'is_destruct' => 1,
    'crystal_type' => 'none',
    'consume_type' => 'consume_type_stackable',
  ],
  20881 => 
  [
    'item_id' => 20881,
    'icon' => 'br_taiwan_newyear_food_f_i00',
    'name' => 'Hwa Gei Bu Gwi',
    'additionalname' => 'Decrease Weight, Haste',
    'description' => 'Increases Atk. Spd. by 33% and the weight penalty interval by 9000 for 1 hour.',
    'is_trade' => 0,
    'is_drop' => 0,
    'is_destruct' => 1,
    'crystal_type' => 'none',
    'consume_type' => 'consume_type_stackable',
  ],
  20882 => 
  [
    'item_id' => 20882,
    'icon' => 'br_taiwan_newyear_food_g_i00',
    'name' => 'Fire Stamp',
    'additionalname' => 'Wind Walk, Agility, Blessed Body',
    'description' => 'For 1 hour, increases Speed by 33, Evasion rate by 4, and Max HP by 35%.',
    'is_trade' => 0,
    'is_drop' => 0,
    'is_destruct' => 1,
    'crystal_type' => 'none',
    'consume_type' => 'consume_type_stackable',
  ],
  20883 => 
  [
    'item_id' => 20883,
    'icon' => 'br_thanksletter_i00',
    'name' => 'Letter of Thanks',
    'additionalname' => '',
    'description' => 'Thank you letter.',
    'is_trade' => 0,
    'is_drop' => 0,
    'is_destruct' => 1,
    'crystal_type' => 'none',
    'consume_type' => 'consume_type_stackable',
  ],
  20884 => 
  [
    'item_id' => 20884,
    'icon' => 'etc_royal_membership_i00',
    'name' => 'Lancet Character Card',
    'additionalname' => '',
    'description' => 'Card containing Lancet\'s profile and story.',
    'is_trade' => 1,
    'is_drop' => 1,
    'is_destruct' => 1,
    'crystal_type' => 'none',
    'consume_type' => 'consume_type_stackable',
  ],
  20885 => 
  [
    'item_id' => 20885,
    'icon' => 'etc_royal_membership_i00',
    'name' => 'Liposa Character Card',
    'additionalname' => '',
    'description' => 'Card containing Liposa\'s profile and story.',
    'is_trade' => 1,
    'is_drop' => 1,
    'is_destruct' => 1,
    'crystal_type' => 'none',
    'consume_type' => 'consume_type_stackable',
  ],
  20886 => 
  [
    'item_id' => 20886,
    'icon' => 'etc_royal_membership_i00',
    'name' => 'Velarin Character Card',
    'additionalname' => '',
    'description' => 'Card containing Velarin\'s profile and story.',
    'is_trade' => 1,
    'is_drop' => 1,
    'is_destruct' => 1,
    'crystal_type' => 'none',
    'consume_type' => 'consume_type_stackable',
  ],
  20887 => 
  [
    'item_id' => 20887,
    'icon' => 'etc_royal_membership_i00',
    'name' => 'Dulcinel Character Card',
    'additionalname' => '',
    'description' => 'Card containing Dulcinel\'s profile and story.',
    'is_trade' => 1,
    'is_drop' => 1,
    'is_destruct' => 1,
    'crystal_type' => 'none',
    'consume_type' => 'consume_type_stackable',
  ],
  20888 => 
  [
    'item_id' => 20888,
    'icon' => 'etc_royal_membership_i00',
    'name' => 'Chimeros Character Card',
    'additionalname' => '',
    'description' => 'Card containing Chimeros\' profile and story.',
    'is_trade' => 1,
    'is_drop' => 1,
    'is_destruct' => 1,
    'crystal_type' => 'none',
    'consume_type' => 'consume_type_stackable',
  ],
  20889 => 
  [
    'item_id' => 20889,
    'icon' => 'etc_royal_membership_i00',
    'name' => 'Niveri Character Card',
    'additionalname' => '',
    'description' => 'Card containing Niveri\'s profile and story.',
    'is_trade' => 1,
    'is_drop' => 1,
    'is_destruct' => 1,
    'crystal_type' => 'none',
    'consume_type' => 'consume_type_stackable',
  ],
  20890 => 
  [
    'item_id' => 20890,
    'icon' => 'etc_royal_membership_i00',
    'name' => 'Hamell Character Card',
    'additionalname' => '',
    'description' => 'Card containing Hamell\'s profile and story.',
    'is_trade' => 1,
    'is_drop' => 1,
    'is_destruct' => 1,
    'crystal_type' => 'none',
    'consume_type' => 'consume_type_stackable',
  ],
  20891 => 
  [
    'item_id' => 20891,
    'icon' => 'etc_royal_membership_i00',
    'name' => 'Joriya Character Card',
    'additionalname' => '',
    'description' => 'Card containing Joriya\'s profile and story.',
    'is_trade' => 1,
    'is_drop' => 1,
    'is_destruct' => 1,
    'crystal_type' => 'none',
    'consume_type' => 'consume_type_stackable',
  ],
  20892 => 
  [
    'item_id' => 20892,
    'icon' => 'etc_royal_membership_i00',
    'name' => 'Ralmak Character Card',
    'additionalname' => '',
    'description' => 'Card containing Ralmak\'s profile and story.',
    'is_trade' => 1,
    'is_drop' => 1,
    'is_destruct' => 1,
    'crystal_type' => 'none',
    'consume_type' => 'consume_type_stackable',
  ],
  20893 => 
  [
    'item_id' => 20893,
    'icon' => 'etc_royal_membership_i00',
    'name' => 'Goras Character Card',
    'additionalname' => '',
    'description' => 'Card containing Goras\'s profile and story.',
    'is_trade' => 1,
    'is_drop' => 1,
    'is_destruct' => 1,
    'crystal_type' => 'none',
    'consume_type' => 'consume_type_stackable',
  ],
  20894 => 
  [
    'item_id' => 20894,
    'icon' => 'etc_royal_membership_i00',
    'name' => 'Vensar Character Card',
    'additionalname' => '',
    'description' => 'Card containing Vensar\'s profile and story.',
    'is_trade' => 1,
    'is_drop' => 1,
    'is_destruct' => 1,
    'crystal_type' => 'none',
    'consume_type' => 'consume_type_stackable',
  ],
  20895 => 
  [
    'item_id' => 20895,
    'icon' => 'etc_royal_membership_i00',
    'name' => 'Kiela Character Card',
    'additionalname' => '',
    'description' => 'Card containing Kiela\'s profile and story.',
    'is_trade' => 1,
    'is_drop' => 1,
    'is_destruct' => 1,
    'crystal_type' => 'none',
    'consume_type' => 'consume_type_stackable',
  ],
  20896 => 
  [
    'item_id' => 20896,
    'icon' => 'br_stone_of_time_i00',
    'name' => 'Red Dimensional Stone',
    'additionalname' => '',
    'description' => 'Stone that distorts space and time. When used after clearing the Pailaka quest, you can enter 1 more time. Cooldown is 5 hours.',
    'is_trade' => 0,
    'is_drop' => 0,
    'is_destruct' => 1,
    'crystal_type' => 'none',
    'consume_type' => 'consume_type_stackable',
  ],
  20897 => 
  [
    'item_id' => 20897,
    'icon' => 'br_party_mask_purple_i00',
    'name' => 'Purple Paper Mask',
    'additionalname' => 'Blessed Soul (7-day]',
    'description' => 'Brilliant mask made of purple paper. Cooldown is 1 hour.',
    'is_trade' => 0,
    'is_drop' => 0,
    'is_destruct' => 1,
    'crystal_type' => 'none',
    'consume_type' => 'consume_type_normal',
  ],
  20898 => 
  [
    'item_id' => 20898,
    'icon' => 'br_four_leaf_clover_box_i00',
    'name' => 'Purple Paper Mask Pack (7-day]',
    'additionalname' => 'Blessed Soul ',
    'description' => 'Wrapped Pack containing Purple Paper Mask (7-day].',
    'is_trade' => 0,
    'is_drop' => 0,
    'is_destruct' => 1,
    'crystal_type' => 'none',
    'consume_type' => 'consume_type_stackable',
  ],
  20899 => 
  [
    'item_id' => 20899,
    'icon' => 'br_thai_desert_i00',
    'name' => 'Mango Dessert',
    'additionalname' => '',
    'description' => 'Fresh, sweet mango and flavorful sweet rice. Replenishes Vitality to a certain degree. Cooldown is 60 min. Vitality item with limited usage.',
    'is_trade' => 0,
    'is_drop' => 0,
    'is_destruct' => 1,
    'crystal_type' => 'none',
    'consume_type' => 'consume_type_stackable',
  ],
];