<?php return [
  21000 => 
  [
    'item_id' => 21000,
    'icon' => 'br_four_leaf_clover_box_i00',
    'name' => 'Package: Agathion Ball-trapping Gnosian',
    'additionalname' => NULL,
    'description' => 'Double-click to obtain Agathion Ball Trapping Gnosian.',
    'is_trade' => 0,
    'is_drop' => 0,
    'is_destruct' => 1,
    'crystal_type' => 'crystal_free',
    'consume_type' => 'consume_type_stackable',
  ],
  21001 => 
  [
    'item_id' => 21001,
    'icon' => 'br_four_leaf_clover_box_i00',
    'name' => 'Package: Agathion Ball-trapping Orodriel',
    'additionalname' => NULL,
    'description' => 'Double-click to obtain Agathion Ball-trapping Orodriel.',
    'is_trade' => 0,
    'is_drop' => 0,
    'is_destruct' => 1,
    'crystal_type' => 'crystal_free',
    'consume_type' => 'consume_type_stackable',
  ],
  21002 => 
  [
    'item_id' => 21002,
    'icon' => 'br_four_leaf_clover_box_i00',
    'name' => 'Package: Agathion Penalty Kick',
    'additionalname' => NULL,
    'description' => 'Double-click to obtain Agathion Penalty Kick.',
    'is_trade' => 0,
    'is_drop' => 0,
    'is_destruct' => 1,
    'crystal_type' => 'crystal_free',
    'consume_type' => 'consume_type_stackable',
  ],
  21003 => 
  [
    'item_id' => 21003,
    'icon' => 'br_four_leaf_clover_box_i00',
    'name' => 'Package: Agathion Ball-trapping Gnosian',
    'additionalname' => NULL,
    'description' => 'Double-click to obtain Agathion Ball Trapping Gnosian.',
    'is_trade' => 0,
    'is_drop' => 0,
    'is_destruct' => 1,
    'crystal_type' => 'crystal_free',
    'consume_type' => 'consume_type_stackable',
  ],
  21004 => 
  [
    'item_id' => 21004,
    'icon' => 'br_four_leaf_clover_box_i00',
    'name' => 'Package: Agathion Ball-trapping Orodriel',
    'additionalname' => NULL,
    'description' => 'Double-click to obtain Agathion Ball-trapping Orodriel.',
    'is_trade' => 0,
    'is_drop' => 0,
    'is_destruct' => 1,
    'crystal_type' => 'crystal_free',
    'consume_type' => 'consume_type_stackable',
  ],
  21005 => 
  [
    'item_id' => 21005,
    'icon' => 'br_four_leaf_clover_box_i00',
    'name' => 'Package: Agathion Penalty Kick',
    'additionalname' => NULL,
    'description' => 'Double-click to obtain Agathion Penalty Kick.',
    'is_trade' => 0,
    'is_drop' => 0,
    'is_destruct' => 1,
    'crystal_type' => 'crystal_free',
    'consume_type' => 'consume_type_stackable',
  ],
  21006 => 
  [
    'item_id' => 21006,
    'icon' => 'br_four_leaf_clover_box_i00',
    'name' => 'Package: Agathion Ball-trapping Gnosian',
    'additionalname' => NULL,
    'description' => 'Double-click to obtain Agathion Ball Trapping Gnosian.',
    'is_trade' => 0,
    'is_drop' => 0,
    'is_destruct' => 1,
    'crystal_type' => 'crystal_free',
    'consume_type' => 'consume_type_stackable',
  ],
  21007 => 
  [
    'item_id' => 21007,
    'icon' => 'br_four_leaf_clover_box_i00',
    'name' => 'Package: Agathion Ball-trapping Orodriel',
    'additionalname' => NULL,
    'description' => 'Double-click to obtain Agathion Ball-trapping Orodriel.',
    'is_trade' => 0,
    'is_drop' => 0,
    'is_destruct' => 1,
    'crystal_type' => 'crystal_free',
    'consume_type' => 'consume_type_stackable',
  ],
  21008 => 
  [
    'item_id' => 21008,
    'icon' => 'br_four_leaf_clover_box_i00',
    'name' => 'Package: Agathion Penalty Kick',
    'additionalname' => NULL,
    'description' => 'Double-click to obtain Agathion Penalty Kick.',
    'is_trade' => 0,
    'is_drop' => 0,
    'is_destruct' => 1,
    'crystal_type' => 'crystal_free',
    'consume_type' => 'consume_type_stackable',
  ],
  21009 => 
  [
    'item_id' => 21009,
    'icon' => 'br_worldcup_hair_i00',
    'name' => 'Afro Hairstyle - White Ball',
    'additionalname' => NULL,
    'description' => 'An afro wig dyed like a white soccer ball. Equipped in 2 head accessory slots.',
    'is_trade' => 0,
    'is_drop' => 0,
    'is_destruct' => 1,
    'crystal_type' => 'none',
    'consume_type' => 'consume_type_normal',
  ],
  21010 => 
  [
    'item_id' => 21010,
    'icon' => 'br_worldcup_hair_i01',
    'name' => 'Afro Hairstyle - Blue Ball',
    'additionalname' => NULL,
    'description' => 'An afro wig dyed like a blue soccer ball. Equipped in 2 head accessory slots.',
    'is_trade' => 0,
    'is_drop' => 0,
    'is_destruct' => 1,
    'crystal_type' => 'none',
    'consume_type' => 'consume_type_normal',
  ],
  21011 => 
  [
    'item_id' => 21011,
    'icon' => 'br_worldcup_hair_i02',
    'name' => 'Afro Hairstyle - Red Ball',
    'additionalname' => 'Blessing of Victory',
    'description' => 'An afro wig dyed like a red soccer ball. Equipped in 2 head accessory slots. When equipped, Speed +2%.',
    'is_trade' => 0,
    'is_drop' => 0,
    'is_destruct' => 1,
    'crystal_type' => 'none',
    'consume_type' => 'consume_type_normal',
  ],
  21012 => 
  [
    'item_id' => 21012,
    'icon' => 'br_worldcup_face_deco_i00',
    'name' => 'Mark of Victory - Korea',
    'additionalname' => NULL,
    'description' => 'Mark that wishes for victory by the Korean team.',
    'is_trade' => 0,
    'is_drop' => 0,
    'is_destruct' => 1,
    'crystal_type' => 'none',
    'consume_type' => 'consume_type_normal',
  ],
  21013 => 
  [
    'item_id' => 21013,
    'icon' => 'br_worldcup_face_deco_i00',
    'name' => 'Mark of Victory - Japan',
    'additionalname' => NULL,
    'description' => 'Souvenir of the World Cup. Mark that wishes for victory by the Japanese team. ',
    'is_trade' => 0,
    'is_drop' => 0,
    'is_destruct' => 1,
    'crystal_type' => 'none',
    'consume_type' => 'consume_type_normal',
  ],
  21014 => 
  [
    'item_id' => 21014,
    'icon' => 'br_worldcup_face_deco_i00',
    'name' => 'Mark of Cheers',
    'additionalname' => NULL,
    'description' => 'Mark containing cheering heart.',
    'is_trade' => 0,
    'is_drop' => 0,
    'is_destruct' => 1,
    'crystal_type' => 'none',
    'consume_type' => 'consume_type_normal',
  ],
  21015 => 
  [
    'item_id' => 21015,
    'icon' => 'br_worldcup_stick_i00',
    'name' => 'Balloon Stick of Cheers - Red',
    'additionalname' => NULL,
    'description' => 'Balloon stick containing cheering heart.',
    'is_trade' => 0,
    'is_drop' => 0,
    'is_destruct' => 1,
    'crystal_type' => 'none',
    'consume_type' => 'consume_type_normal',
  ],
  21016 => 
  [
    'item_id' => 21016,
    'icon' => 'br_worldcup_stick_i01',
    'name' => 'Balloon Stick of Cheers - Orange',
    'additionalname' => NULL,
    'description' => 'Balloon stick containing cheering heart.',
    'is_trade' => 0,
    'is_drop' => 0,
    'is_destruct' => 1,
    'crystal_type' => 'none',
    'consume_type' => 'consume_type_normal',
  ],
  21017 => 
  [
    'item_id' => 21017,
    'icon' => 'br_worldcup_stick_i02',
    'name' => 'Balloon Stick of Cheers - Yellow',
    'additionalname' => NULL,
    'description' => 'Balloon stick containing cheering heart.',
    'is_trade' => 0,
    'is_drop' => 0,
    'is_destruct' => 1,
    'crystal_type' => 'none',
    'consume_type' => 'consume_type_normal',
  ],
  21018 => 
  [
    'item_id' => 21018,
    'icon' => 'br_worldcup_stick_i03',
    'name' => 'Balloon Stick of Cheers - Green',
    'additionalname' => NULL,
    'description' => 'Balloon stick containing cheering heart.',
    'is_trade' => 0,
    'is_drop' => 0,
    'is_destruct' => 1,
    'crystal_type' => 'none',
    'consume_type' => 'consume_type_normal',
  ],
  21019 => 
  [
    'item_id' => 21019,
    'icon' => 'br_worldcup_stick_i04',
    'name' => 'Balloon Stick of Cheers - Blue',
    'additionalname' => NULL,
    'description' => 'Balloon stick containing cheering heart.',
    'is_trade' => 0,
    'is_drop' => 0,
    'is_destruct' => 1,
    'crystal_type' => 'none',
    'consume_type' => 'consume_type_normal',
  ],
  21020 => 
  [
    'item_id' => 21020,
    'icon' => 'br_worldcup_stick_i05',
    'name' => 'Balloon Stick of Cheers - Indigo Blue',
    'additionalname' => NULL,
    'description' => 'Balloon stick containing cheering heart.',
    'is_trade' => 0,
    'is_drop' => 0,
    'is_destruct' => 1,
    'crystal_type' => 'none',
    'consume_type' => 'consume_type_normal',
  ],
  21021 => 
  [
    'item_id' => 21021,
    'icon' => 'br_worldcup_stick_i06',
    'name' => 'Balloon Stick of Cheers - Purple',
    'additionalname' => NULL,
    'description' => 'Balloon stick containing cheering heart.',
    'is_trade' => 0,
    'is_drop' => 0,
    'is_destruct' => 1,
    'crystal_type' => 'none',
    'consume_type' => 'consume_type_normal',
  ],
  21022 => 
  [
    'item_id' => 21022,
    'icon' => 'br_worldcup_stick_i07',
    'name' => 'Balloon Stick of Cheers - Black',
    'additionalname' => NULL,
    'description' => 'Balloon stick containing cheering heart.',
    'is_trade' => 0,
    'is_drop' => 0,
    'is_destruct' => 1,
    'crystal_type' => 'none',
    'consume_type' => 'consume_type_normal',
  ],
  21023 => 
  [
    'item_id' => 21023,
    'icon' => 'br_worldcup_stick_i08',
    'name' => 'Balloon Stick of Cheers - White',
    'additionalname' => NULL,
    'description' => 'Balloon stick containing cheering heart.',
    'is_trade' => 0,
    'is_drop' => 0,
    'is_destruct' => 1,
    'crystal_type' => 'none',
    'consume_type' => 'consume_type_normal',
  ],
  21024 => 
  [
    'item_id' => 21024,
    'icon' => 'br_four_leaf_clover_box_i00',
    'name' => 'Package: Afro Hairstyle - White Ball',
    'additionalname' => NULL,
    'description' => 'Double-click to obtain Soccer Ball Afro Hair - White.',
    'is_trade' => 0,
    'is_drop' => 0,
    'is_destruct' => 1,
    'crystal_type' => 'crystal_free',
    'consume_type' => 'consume_type_stackable',
  ],
  21025 => 
  [
    'item_id' => 21025,
    'icon' => 'br_four_leaf_clover_box_i00',
    'name' => 'Package: Afro Hairstyle - Blue Ball',
    'additionalname' => NULL,
    'description' => 'Double-click to obtain Soccer Ball Afro Hair - Blue.',
    'is_trade' => 0,
    'is_drop' => 0,
    'is_destruct' => 1,
    'crystal_type' => 'crystal_free',
    'consume_type' => 'consume_type_stackable',
  ],
  21026 => 
  [
    'item_id' => 21026,
    'icon' => 'br_four_leaf_clover_box_i00',
    'name' => 'Package: Afro Hairstyle - Red Ball',
    'additionalname' => 'Blessing of Victory',
    'description' => 'Double-click to obtain Soccer Ball Afro Hair - Red.',
    'is_trade' => 0,
    'is_drop' => 0,
    'is_destruct' => 1,
    'crystal_type' => 'crystal_free',
    'consume_type' => 'consume_type_stackable',
  ],
  21027 => 
  [
    'item_id' => 21027,
    'icon' => 'br_four_leaf_clover_box_i00',
    'name' => 'Package: Mark of Victory - Korea',
    'additionalname' => NULL,
    'description' => 'Double-click to obtain Mark of Victory - Korea. ',
    'is_trade' => 0,
    'is_drop' => 0,
    'is_destruct' => 1,
    'crystal_type' => 'crystal_free',
    'consume_type' => 'consume_type_stackable',
  ],
  21028 => 
  [
    'item_id' => 21028,
    'icon' => 'br_four_leaf_clover_box_i00',
    'name' => 'Package: Mark of Victory - Japan',
    'additionalname' => NULL,
    'description' => 'Double-click to obtain Mark of Victory - Japan. ',
    'is_trade' => 0,
    'is_drop' => 0,
    'is_destruct' => 1,
    'crystal_type' => 'crystal_free',
    'consume_type' => 'consume_type_stackable',
  ],
  21029 => 
  [
    'item_id' => 21029,
    'icon' => 'br_four_leaf_clover_box_i00',
    'name' => 'Package: Mark of Cheers',
    'additionalname' => NULL,
    'description' => 'Double-click to obtain Mark of Cheers.',
    'is_trade' => 0,
    'is_drop' => 0,
    'is_destruct' => 1,
    'crystal_type' => 'crystal_free',
    'consume_type' => 'consume_type_stackable',
  ],
  21030 => 
  [
    'item_id' => 21030,
    'icon' => 'br_protection_hadin_i00',
    'name' => 'Hardins Divine Protection',
    'additionalname' => NULL,
    'description' => 'Potion that gives you Hardins Divine Protection. Increases P. Def. for 10 sec. Cooldown is 15 min. ',
    'is_trade' => 0,
    'is_drop' => 0,
    'is_destruct' => 1,
    'crystal_type' => 'crystal_free',
    'consume_type' => 'consume_type_stackable',
  ],
  21031 => 
  [
    'item_id' => 21031,
    'icon' => 'br_bless_of hadin_i00',
    'name' => 'Hardins Blessing',
    'additionalname' => NULL,
    'description' => 'A potion that gives you Hardins Blessing. Increases M. Def. for 10 sec. Cooldown: 15 min. ',
    'is_trade' => 0,
    'is_drop' => 0,
    'is_destruct' => 1,
    'crystal_type' => 'crystal_free',
    'consume_type' => 'consume_type_stackable',
  ],
  21032 => 
  [
    'item_id' => 21032,
    'icon' => 'br_wing_of_sylphide_i00',
    'name' => 'Silpheeds Wing',
    'additionalname' => NULL,
    'description' => 'For 15 sec., Speed +300. ',
    'is_trade' => 0,
    'is_drop' => 0,
    'is_destruct' => 1,
    'crystal_type' => 'crystal_free',
    'consume_type' => 'consume_type_stackable',
  ],
  21033 => 
  [
    'item_id' => 21033,
    'icon' => 'br_bless_of_sylphide_i00',
    'name' => 'Silpheeds Blessing',
    'additionalname' => NULL,
    'description' => 'Grants Speed +300 to you and nearby allies for 15 sec. ',
    'is_trade' => 0,
    'is_drop' => 0,
    'is_destruct' => 1,
    'crystal_type' => 'crystal_free',
    'consume_type' => 'consume_type_stackable',
  ],
  21034 => 
  [
    'item_id' => 21034,
    'icon' => 'br_scroll_of_yibein_i00',
    'name' => 'Evains Recovery Scroll',
    'additionalname' => NULL,
    'description' => 'Scroll containing the power of Evain. Instantly recovers 500 HP to yourself and friendly nearby targets. ',
    'is_trade' => 0,
    'is_drop' => 0,
    'is_destruct' => 1,
    'crystal_type' => 'crystal_free',
    'consume_type' => 'consume_type_stackable',
  ],
  21035 => 
  [
    'item_id' => 21035,
    'icon' => NULL,
    'name' => 'Good/ Bad of Life',
    'additionalname' => NULL,
    'description' => 'Good luck charm containing the power of life. It automatically restores 500 HP when HP falls below 30%, in doing this 1 talisman is expended. ',
    'is_trade' => 0,
    'is_drop' => 0,
    'is_destruct' => 1,
    'crystal_type' => 'crystal_free',
    'consume_type' => 'consume_type_normal',
  ],
  21036 => 
  [
    'item_id' => 21036,
    'icon' => NULL,
    'name' => 'State of the Mind',
    'additionalname' => NULL,
    'description' => 'Good luck charm containing the power of magic. It automatically restores 500 MP when MP falls below 30%, in doing this 1 talisman is expended. ',
    'is_trade' => 0,
    'is_drop' => 0,
    'is_destruct' => 1,
    'crystal_type' => 'crystal_free',
    'consume_type' => 'consume_type_normal',
  ],
  21037 => 
  [
    'item_id' => 21037,
    'icon' => 'br_breath_of_hero_i00',
    'name' => 'Warriors Quick CP Potion',
    'additionalname' => NULL,
    'description' => 'Potion containing the power of an ancient warrior. It recovers CP by 300. ',
    'is_trade' => 0,
    'is_drop' => 0,
    'is_destruct' => 1,
    'crystal_type' => 'crystal_free',
    'consume_type' => 'consume_type_stackable',
  ],
  21038 => 
  [
    'item_id' => 21038,
    'icon' => 'br_hero_potion_i00',
    'name' => 'Heros Potion',
    'additionalname' => NULL,
    'description' => 'Potion containing the soul of a hero. Instantly recovers 500 HP and 200 MP. Cooldown is 60 sec. ',
    'is_trade' => 0,
    'is_drop' => 0,
    'is_destruct' => 1,
    'crystal_type' => 'crystal_free',
    'consume_type' => 'consume_type_stackable',
  ],
  21039 => 
  [
    'item_id' => 21039,
    'icon' => 'etc_reagent_white_i00',
    'name' => 'Superior HP Replenishing Potion',
    'additionalname' => NULL,
    'description' => 'For 15 sec., recovers 100 HP per sec.',
    'is_trade' => 0,
    'is_drop' => 0,
    'is_destruct' => 1,
    'crystal_type' => 'crystal_free',
    'consume_type' => 'consume_type_stackable',
  ],
  21040 => 
  [
    'item_id' => 21040,
    'icon' => 'etc_potion_gold_i00',
    'name' => 'Superior Quick HP Replenishing Potion',
    'additionalname' => NULL,
    'description' => 'Instantly restores HP by 870. Cannot be used when HP is full.',
    'is_trade' => 0,
    'is_drop' => 0,
    'is_destruct' => 1,
    'crystal_type' => 'crystal_free',
    'consume_type' => 'consume_type_stackable',
  ],
  21041 => 
  [
    'item_id' => 21041,
    'icon' => 'br_fortuna_box_chaos_i00',
    'name' => 'Fortuna of Chaos',
    'additionalname' => NULL,
    'description' => 'There is a certain chance that you will receive Ancient Book: Divine Inspiration (Original]. ',
    'is_trade' => 0,
    'is_drop' => 0,
    'is_destruct' => 1,
    'crystal_type' => 'crystal_free',
    'consume_type' => 'consume_type_stackable',
  ],
  21042 => 
  [
    'item_id' => 21042,
    'icon' => 'br_flag_cap_i00',
    'name' => 'Flag Hat',
    'additionalname' => '7-day',
    'description' => 'A hat colored like Taiwans flag. Ideal for cheering. Equipped in 2 head accessory slots. The special skills cooldown: 12 h.',
    'is_trade' => 0,
    'is_drop' => 0,
    'is_destruct' => 1,
    'crystal_type' => 'none',
    'consume_type' => 'consume_type_normal',
  ],
  21043 => 
  [
    'item_id' => 21043,
    'icon' => 'br_flag_cap_i00',
    'name' => 'Flag Hat',
    'additionalname' => NULL,
    'description' => 'A hat colored like Taiwans flag. Ideal for cheering. Equipped in 2 head accessory slots. ',
    'is_trade' => 0,
    'is_drop' => 0,
    'is_destruct' => 1,
    'crystal_type' => 'none',
    'consume_type' => 'consume_type_normal',
  ],
  21044 => 
  [
    'item_id' => 21044,
    'icon' => 'br_tiger_grandma_cap_i00',
    'name' => 'Granny Tiger Hat',
    'additionalname' => NULL,
    'description' => 'A hat worn by the Granny Tiger. Equipped in 2 head accessory slots. ',
    'is_trade' => 0,
    'is_drop' => 0,
    'is_destruct' => 1,
    'crystal_type' => 'none',
    'consume_type' => 'consume_type_normal',
  ],
  21045 => 
  [
    'item_id' => 21045,
    'icon' => 'None',
    'name' => 'Mischievous Bee Hat',
    'additionalname' => NULL,
    'description' => 'Mischievous Bee Hat. Equipped in 2 head accessory slots. ',
    'is_trade' => 0,
    'is_drop' => 0,
    'is_destruct' => 1,
    'crystal_type' => 'none',
    'consume_type' => 'consume_type_normal',
  ],
  21046 => 
  [
    'item_id' => 21046,
    'icon' => 'br_aga_tiger_grandma_i00',
    'name' => 'Agathion Granny Tiger ',
    'additionalname' => '7-day',
    'description' => 'A bracelet for summoning Agathion Granny Tiger. Special skills cooldown: 1 h.',
    'is_trade' => 0,
    'is_drop' => 0,
    'is_destruct' => 1,
    'crystal_type' => 'none',
    'consume_type' => 'consume_type_normal',
  ],
  21047 => 
  [
    'item_id' => 21047,
    'icon' => 'br_aga_tiger_grandma_i00',
    'name' => 'Agathion Granny Tiger ',
    'additionalname' => NULL,
    'description' => 'Summons Agathion Granny Tiger.',
    'is_trade' => 0,
    'is_drop' => 0,
    'is_destruct' => 1,
    'crystal_type' => 'none',
    'consume_type' => 'consume_type_normal',
  ],
  21048 => 
  [
    'item_id' => 21048,
    'icon' => 'br_aga_flower_i00',
    'name' => 'Agathion Flower Fairy',
    'additionalname' => NULL,
    'description' => 'A bracelet for summoning Agathion Flower Fairy. The special skills cooldown: 1 h.',
    'is_trade' => 0,
    'is_drop' => 0,
    'is_destruct' => 1,
    'crystal_type' => 'none',
    'consume_type' => 'consume_type_normal',
  ],
  21049 => 
  [
    'item_id' => 21049,
    'icon' => 'br_aga_cheer_FElf_i00',
    'name' => 'Agathion Cheerleader Orodriel',
    'additionalname' => '7-day',
    'description' => 'A bracelet for summoning Agathion Cheerleader Orodriel. Special skills cooldown: 2 h.',
    'is_trade' => 0,
    'is_drop' => 0,
    'is_destruct' => 1,
    'crystal_type' => 'none',
    'consume_type' => 'consume_type_normal',
  ],
  21050 => 
  [
    'item_id' => 21050,
    'icon' => 'br_aga_cheer_FElf_i00',
    'name' => 'Agathion Cheerleader Orodriel',
    'additionalname' => NULL,
    'description' => 'Summons Agathion Cheerleader Orodriel.',
    'is_trade' => 0,
    'is_drop' => 0,
    'is_destruct' => 1,
    'crystal_type' => 'none',
    'consume_type' => 'consume_type_normal',
  ],
  21051 => 
  [
    'item_id' => 21051,
    'icon' => 'br_aga_cheer_FFighter_i00',
    'name' => 'Agathion Cheerleader Lanya',
    'additionalname' => '7-day',
    'description' => 'A bracelet for summoning Agathion Cheerleader Lanya. Special skills cooldown: 2 h.',
    'is_trade' => 0,
    'is_drop' => 0,
    'is_destruct' => 1,
    'crystal_type' => 'none',
    'consume_type' => 'consume_type_normal',
  ],
  21052 => 
  [
    'item_id' => 21052,
    'icon' => 'br_aga_cheer_FFighter_i00',
    'name' => 'Agathion Cheerleader Lanya',
    'additionalname' => NULL,
    'description' => 'Summons Agathion Cheerleader Lanya.',
    'is_trade' => 0,
    'is_drop' => 0,
    'is_destruct' => 1,
    'crystal_type' => 'none',
    'consume_type' => 'consume_type_normal',
  ],
  21053 => 
  [
    'item_id' => 21053,
    'icon' => 'br_aga_cheer_FKamael_i00',
    'name' => 'Agathion Cheerleader Naonin',
    'additionalname' => '7-day',
    'description' => 'A bracelet for summoning Agathion Cheerleader Naonin. Special skills cooldown: 2 h.',
    'is_trade' => 0,
    'is_drop' => 0,
    'is_destruct' => 1,
    'crystal_type' => 'none',
    'consume_type' => 'consume_type_normal',
  ],
  21054 => 
  [
    'item_id' => 21054,
    'icon' => 'br_aga_cheer_FKamael_i00',
    'name' => 'Agathion Cheerleader Naonin',
    'additionalname' => NULL,
    'description' => 'Summons Agathion Cheerleader Naonin.',
    'is_trade' => 0,
    'is_drop' => 0,
    'is_destruct' => 1,
    'crystal_type' => 'none',
    'consume_type' => 'consume_type_normal',
  ],
  21055 => 
  [
    'item_id' => 21055,
    'icon' => 'br_aga_cheer_FDarkelf_i00',
    'name' => 'Agathion Cheerleader Mortia',
    'additionalname' => '7-day',
    'description' => 'A bracelet for summoning Agathion Cheerleader Mortia. Special skills cooldown: 2 h.',
    'is_trade' => 0,
    'is_drop' => 0,
    'is_destruct' => 1,
    'crystal_type' => 'none',
    'consume_type' => 'consume_type_normal',
  ],
  21056 => 
  [
    'item_id' => 21056,
    'icon' => 'br_aga_cheer_FDarkelf_i00',
    'name' => 'Agathion Cheerleader Mortia',
    'additionalname' => NULL,
    'description' => 'Summons Agathion Cheerleader Mortia.',
    'is_trade' => 0,
    'is_drop' => 0,
    'is_destruct' => 1,
    'crystal_type' => 'none',
    'consume_type' => 'consume_type_normal',
  ],
  21057 => 
  [
    'item_id' => 21057,
    'icon' => 'br_aga_cheer_FOrc_i00',
    'name' => 'Agathion Cheerleader Kaurin',
    'additionalname' => '7-day',
    'description' => 'Summons Agathion Cheerleader Kaurin. Skill Cooldown: 2 h.',
    'is_trade' => 0,
    'is_drop' => 0,
    'is_destruct' => 1,
    'crystal_type' => 'none',
    'consume_type' => 'consume_type_normal',
  ],
  21058 => 
  [
    'item_id' => 21058,
    'icon' => 'br_aga_cheer_FOrc_i00',
    'name' => 'Agathion Cheerleader Kaurin',
    'additionalname' => NULL,
    'description' => 'Summons Agathion Cheerleader Kaurin.',
    'is_trade' => 0,
    'is_drop' => 0,
    'is_destruct' => 1,
    'crystal_type' => 'none',
    'consume_type' => 'consume_type_normal',
  ],
  21059 => 
  [
    'item_id' => 21059,
    'icon' => 'br_aga_cheer_FDwarf_i00',
    'name' => 'Agathion Cheerleader Meruril',
    'additionalname' => '7-day',
    'description' => 'Summons Agathion Cheerleader Meruril. Skill Cooldown: 2 h.',
    'is_trade' => 0,
    'is_drop' => 0,
    'is_destruct' => 1,
    'crystal_type' => 'none',
    'consume_type' => 'consume_type_normal',
  ],
  21060 => 
  [
    'item_id' => 21060,
    'icon' => 'br_aga_cheer_FDwarf_i00',
    'name' => 'Agathion Cheerleader Meruril',
    'additionalname' => NULL,
    'description' => 'Summons Agathion Cheerleader Meruril.',
    'is_trade' => 0,
    'is_drop' => 0,
    'is_destruct' => 1,
    'crystal_type' => 'none',
    'consume_type' => 'consume_type_normal',
  ],
  21061 => 
  [
    'item_id' => 21061,
    'icon' => 'br_aga_block_mother_i00',
    'name' => 'Agathion Handy',
    'additionalname' => '7-day',
    'description' => 'A bracelet for summoning Agathion Handy from Fantasy Isle. Cooldown: 2 h.',
    'is_trade' => 0,
    'is_drop' => 0,
    'is_destruct' => 1,
    'crystal_type' => 'none',
    'consume_type' => 'consume_type_normal',
  ],
  21062 => 
  [
    'item_id' => 21062,
    'icon' => 'br_aga_block_mother_i00',
    'name' => 'Agathion Handy',
    'additionalname' => NULL,
    'description' => 'Summons Agathion Handy from Fantasy Isle.',
    'is_trade' => 0,
    'is_drop' => 0,
    'is_destruct' => 1,
    'crystal_type' => 'none',
    'consume_type' => 'consume_type_normal',
  ],
  21063 => 
  [
    'item_id' => 21063,
    'icon' => 'br_four_leaf_clover_box_i00',
    'name' => 'Package: Flag Hat (7-day]',
    'additionalname' => NULL,
    'description' => 'Double-click to obtain Flag Hat (7-day].',
    'is_trade' => 0,
    'is_drop' => 0,
    'is_destruct' => 1,
    'crystal_type' => 'crystal_free',
    'consume_type' => 'consume_type_stackable',
  ],
  21064 => 
  [
    'item_id' => 21064,
    'icon' => 'br_four_leaf_clover_box_i00',
    'name' => 'Package: Flag Hat',
    'additionalname' => NULL,
    'description' => 'Double-click to obtain Flag Hat. ',
    'is_trade' => 0,
    'is_drop' => 0,
    'is_destruct' => 1,
    'crystal_type' => 'crystal_free',
    'consume_type' => 'consume_type_stackable',
  ],
  21065 => 
  [
    'item_id' => 21065,
    'icon' => 'br_four_leaf_clover_box_i00',
    'name' => 'Package: Granny Tiger Hat',
    'additionalname' => NULL,
    'description' => 'Double-click to obtain Granny Tiger Hat. ',
    'is_trade' => 0,
    'is_drop' => 0,
    'is_destruct' => 1,
    'crystal_type' => 'crystal_free',
    'consume_type' => 'consume_type_stackable',
  ],
  21066 => 
  [
    'item_id' => 21066,
    'icon' => NULL,
    'name' => 'Package: Mischievous Bee Hat',
    'additionalname' => NULL,
    'description' => 'Double-click to obtain Mischievous Bee Hat. ',
    'is_trade' => 0,
    'is_drop' => 0,
    'is_destruct' => 1,
    'crystal_type' => 'crystal_free',
    'consume_type' => 'consume_type_stackable',
  ],
  21067 => 
  [
    'item_id' => 21067,
    'icon' => 'br_four_leaf_clover_box_i00',
    'name' => 'Package: Agathion Granny Tiger (7-day]',
    'additionalname' => NULL,
    'description' => 'Double-click to obtain Agathion Granny Tiger (7-day].',
    'is_trade' => 0,
    'is_drop' => 0,
    'is_destruct' => 1,
    'crystal_type' => 'crystal_free',
    'consume_type' => 'consume_type_stackable',
  ],
  21068 => 
  [
    'item_id' => 21068,
    'icon' => 'br_four_leaf_clover_box_i00',
    'name' => 'Package: Agathion Granny Tiger',
    'additionalname' => NULL,
    'description' => 'Double-click to obtain Agathion Granny Tiger.',
    'is_trade' => 0,
    'is_drop' => 0,
    'is_destruct' => 1,
    'crystal_type' => 'crystal_free',
    'consume_type' => 'consume_type_stackable',
  ],
  21069 => 
  [
    'item_id' => 21069,
    'icon' => 'br_four_leaf_clover_box_i00',
    'name' => 'Package: Agathion Flower Fairy',
    'additionalname' => NULL,
    'description' => 'Double-click to obtain Agathion Flower Fairy.',
    'is_trade' => 0,
    'is_drop' => 0,
    'is_destruct' => 1,
    'crystal_type' => 'crystal_free',
    'consume_type' => 'consume_type_stackable',
  ],
  21070 => 
  [
    'item_id' => 21070,
    'icon' => 'br_four_leaf_clover_box_i00',
    'name' => 'Package: Agathion Cheerleader Orodriel (7-day]',
    'additionalname' => NULL,
    'description' => 'Double-click to obtain Agathion Cheerleader Orodriel (7-day].',
    'is_trade' => 0,
    'is_drop' => 0,
    'is_destruct' => 1,
    'crystal_type' => 'crystal_free',
    'consume_type' => 'consume_type_stackable',
  ],
  21071 => 
  [
    'item_id' => 21071,
    'icon' => 'br_four_leaf_clover_box_i00',
    'name' => 'Package: Agathion Cheerleader Orodriel',
    'additionalname' => NULL,
    'description' => 'Double-click to obtain Agathion Cheerleader Orodriel.',
    'is_trade' => 0,
    'is_drop' => 0,
    'is_destruct' => 1,
    'crystal_type' => 'crystal_free',
    'consume_type' => 'consume_type_stackable',
  ],
  21072 => 
  [
    'item_id' => 21072,
    'icon' => 'br_four_leaf_clover_box_i00',
    'name' => 'Package: Agathion Cheerleader Lanya (7-day]',
    'additionalname' => NULL,
    'description' => 'Double-click to obtain Agathion Cheerleader Lanya (7-day].',
    'is_trade' => 0,
    'is_drop' => 0,
    'is_destruct' => 1,
    'crystal_type' => 'crystal_free',
    'consume_type' => 'consume_type_stackable',
  ],
  21073 => 
  [
    'item_id' => 21073,
    'icon' => 'br_four_leaf_clover_box_i00',
    'name' => 'Package: Agathion Cheerleader Lanya',
    'additionalname' => NULL,
    'description' => 'Double-click to obtain Agathion Cheerleader Lanya.',
    'is_trade' => 0,
    'is_drop' => 0,
    'is_destruct' => 1,
    'crystal_type' => 'crystal_free',
    'consume_type' => 'consume_type_stackable',
  ],
  21074 => 
  [
    'item_id' => 21074,
    'icon' => 'br_four_leaf_clover_box_i00',
    'name' => 'Package: Agathion Cheerleader Naonin (7-day]',
    'additionalname' => NULL,
    'description' => 'Double-click to obtain Agathion Cheerleader Naonin (7-day].',
    'is_trade' => 0,
    'is_drop' => 0,
    'is_destruct' => 1,
    'crystal_type' => 'crystal_free',
    'consume_type' => 'consume_type_stackable',
  ],
  21075 => 
  [
    'item_id' => 21075,
    'icon' => 'br_four_leaf_clover_box_i00',
    'name' => 'Package: Agathion Cheerleader Naonin',
    'additionalname' => NULL,
    'description' => 'Double-click to obtain Agathion Cheerleader Naonin.',
    'is_trade' => 0,
    'is_drop' => 0,
    'is_destruct' => 1,
    'crystal_type' => 'crystal_free',
    'consume_type' => 'consume_type_stackable',
  ],
  21076 => 
  [
    'item_id' => 21076,
    'icon' => 'br_four_leaf_clover_box_i00',
    'name' => 'Package: Agathion Cheerleader Mortia (7-day]',
    'additionalname' => NULL,
    'description' => 'Double-click to obtain Agathion Cheerleader Mortia (7-day].',
    'is_trade' => 0,
    'is_drop' => 0,
    'is_destruct' => 1,
    'crystal_type' => 'crystal_free',
    'consume_type' => 'consume_type_stackable',
  ],
  21077 => 
  [
    'item_id' => 21077,
    'icon' => 'br_four_leaf_clover_box_i00',
    'name' => 'Package: Agathion Cheerleader Mortia',
    'additionalname' => NULL,
    'description' => 'Double-click to obtain Agathion Cheerleader Mortia.',
    'is_trade' => 0,
    'is_drop' => 0,
    'is_destruct' => 1,
    'crystal_type' => 'crystal_free',
    'consume_type' => 'consume_type_stackable',
  ],
  21078 => 
  [
    'item_id' => 21078,
    'icon' => 'br_four_leaf_clover_box_i00',
    'name' => 'Package: Agathion Cheerleader Kaurin (7-day]',
    'additionalname' => NULL,
    'description' => 'Double-click to obtain Agathion Cheerleader Kaurin (7-day].',
    'is_trade' => 0,
    'is_drop' => 0,
    'is_destruct' => 1,
    'crystal_type' => 'crystal_free',
    'consume_type' => 'consume_type_stackable',
  ],
  21079 => 
  [
    'item_id' => 21079,
    'icon' => 'br_four_leaf_clover_box_i00',
    'name' => 'Package: Agathion Cheerleader Kaurin',
    'additionalname' => NULL,
    'description' => 'Double-click to obtain Agathion Cheerleader Kaurin.',
    'is_trade' => 0,
    'is_drop' => 0,
    'is_destruct' => 1,
    'crystal_type' => 'crystal_free',
    'consume_type' => 'consume_type_stackable',
  ],
  21080 => 
  [
    'item_id' => 21080,
    'icon' => 'br_four_leaf_clover_box_i00',
    'name' => 'Package: Agathion Cheerleader Meruril (7-day]',
    'additionalname' => NULL,
    'description' => 'Double-click to obtain Agathion Cheerleader Meruril (7-day].',
    'is_trade' => 0,
    'is_drop' => 0,
    'is_destruct' => 1,
    'crystal_type' => 'crystal_free',
    'consume_type' => 'consume_type_stackable',
  ],
  21081 => 
  [
    'item_id' => 21081,
    'icon' => 'br_four_leaf_clover_box_i00',
    'name' => 'Package: Agathion Cheerleader Meruril',
    'additionalname' => NULL,
    'description' => 'Double-click to obtain Agathion Cheerleader Meruril.',
    'is_trade' => 0,
    'is_drop' => 0,
    'is_destruct' => 1,
    'crystal_type' => 'crystal_free',
    'consume_type' => 'consume_type_stackable',
  ],
  21082 => 
  [
    'item_id' => 21082,
    'icon' => 'br_four_leaf_clover_box_i00',
    'name' => 'Package: Agathion Handy (7-day]',
    'additionalname' => NULL,
    'description' => 'Double-click to obtain Agathion Handy (7-day].',
    'is_trade' => 0,
    'is_drop' => 0,
    'is_destruct' => 1,
    'crystal_type' => 'crystal_free',
    'consume_type' => 'consume_type_stackable',
  ],
  21083 => 
  [
    'item_id' => 21083,
    'icon' => 'br_four_leaf_clover_box_i00',
    'name' => 'Package: Agathion Handy',
    'additionalname' => NULL,
    'description' => 'Double-click to obtain Agathion Handy.',
    'is_trade' => 0,
    'is_drop' => 0,
    'is_destruct' => 1,
    'crystal_type' => 'crystal_free',
    'consume_type' => 'consume_type_stackable',
  ],
  21084 => 
  [
    'item_id' => 21084,
    'icon' => 'br_cash_rune_of_exp_i00',
    'name' => 'XP Rune 30%',
    'additionalname' => NULL,
    'description' => 'An ancient rune imbued with mystical powers. When in inventory, acquired XP +30%. The remaining time is spent even if you are offline.',
    'is_trade' => 0,
    'is_drop' => 0,
    'is_destruct' => 1,
    'crystal_type' => 'crystal_free',
    'consume_type' => 'consume_type_normal',
  ],
  21085 => 
  [
    'item_id' => 21085,
    'icon' => 'br_four_leaf_clover_box_i00',
    'name' => 'Package: XP Rune 30% (1-hour]',
    'additionalname' => NULL,
    'description' => 'Double-click to obtain XP Rune 30% (1-hour].',
    'is_trade' => 0,
    'is_drop' => 0,
    'is_destruct' => 1,
    'crystal_type' => 'crystal_free',
    'consume_type' => 'consume_type_stackable',
  ],
  21086 => 
  [
    'item_id' => 21086,
    'icon' => 'br_cash_rune_of_sp_i00',
    'name' => 'SP Rune 30%',
    'additionalname' => NULL,
    'description' => 'An ancient rune imbued with mystical powers. When in inventory, acquired SP +30%. The remaining time is spent even if you are offline.',
    'is_trade' => 0,
    'is_drop' => 0,
    'is_destruct' => 1,
    'crystal_type' => 'crystal_free',
    'consume_type' => 'consume_type_normal',
  ],
  21087 => 
  [
    'item_id' => 21087,
    'icon' => 'br_four_leaf_clover_box_i00',
    'name' => 'Package: SP Rune 30% (1-hour]',
    'additionalname' => NULL,
    'description' => 'Double-click to obtain SP Rune 30% (1-hour].',
    'is_trade' => 0,
    'is_drop' => 0,
    'is_destruct' => 1,
    'crystal_type' => 'crystal_free',
    'consume_type' => 'consume_type_stackable',
  ],
  21088 => 
  [
    'item_id' => 21088,
    'icon' => 'br_z_bike_i00',
    'name' => 'Jet Bike Bracelet',
    'additionalname' => NULL,
    'description' => 'Sweet mount made by Dwarven science and engineering. This item enables you to drive a Jet Bike.',
    'is_trade' => 0,
    'is_drop' => 0,
    'is_destruct' => 1,
    'crystal_type' => 'none',
    'consume_type' => 'consume_type_normal',
  ],
  21089 => 
  [
    'item_id' => 21089,
    'icon' => 'br_four_leaf_clover_box_i00',
    'name' => 'Package: Jet Bike',
    'additionalname' => NULL,
    'description' => 'Double-click to obtain Jet Bike. ',
    'is_trade' => 0,
    'is_drop' => 0,
    'is_destruct' => 1,
    'crystal_type' => 'crystal_free',
    'consume_type' => 'consume_type_stackable',
  ],
  21090 => 
  [
    'item_id' => 21090,
    'icon' => 'br_plastic_hair_f_i00',
    'name' => 'Plastic Hair',
    'additionalname' => NULL,
    'description' => 'Plastic hair. It changes to an attractive pink wig for women and a blue wig for men. Uses 2 accessory slots.',
    'is_trade' => 1,
    'is_drop' => 1,
    'is_destruct' => 1,
    'crystal_type' => 'none',
    'consume_type' => 'consume_type_normal',
  ],
  21091 => 
  [
    'item_id' => 21091,
    'icon' => 'br_four_leaf_clover_box_i00',
    'name' => 'Package: XP Rune 50% (7-day]',
    'additionalname' => NULL,
    'description' => 'Double-click to obtain XP Rune 50% (7-day].',
    'is_trade' => 0,
    'is_drop' => 0,
    'is_destruct' => 1,
    'crystal_type' => 'crystal_free',
    'consume_type' => 'consume_type_stackable',
  ],
  21092 => 
  [
    'item_id' => 21092,
    'icon' => 'br_four_leaf_clover_box_i00',
    'name' => 'Package: SP Rune 50% (7-day]',
    'additionalname' => NULL,
    'description' => 'Double-click to obtain SP Rune 50% (7-day].',
    'is_trade' => 0,
    'is_drop' => 0,
    'is_destruct' => 1,
    'crystal_type' => 'crystal_free',
    'consume_type' => 'consume_type_stackable',
  ],
  21093 => 
  [
    'item_id' => 21093,
    'icon' => 'br_fruit_cocktail_i00',
    'name' => 'Sweet Fruit Cocktail',
    'additionalname' => NULL,
    'description' => 'Cocktail drink thats flavored with many rare types of fruit. When consumed, for 1 h., one can feel the effects of Wind Walk, Haste, Vampiric Rage, Might, Shield, Death Whisper, Guidance, and Blessed Body.',
    'is_trade' => 0,
    'is_drop' => 0,
    'is_destruct' => 1,
    'crystal_type' => 'crystal_free',
    'consume_type' => 'consume_type_stackable',
  ],
  21094 => 
  [
    'item_id' => 21094,
    'icon' => 'br_fruit_cocktail_i01',
    'name' => 'Fresh Fruit Cocktail',
    'additionalname' => NULL,
    'description' => 'Cocktail made of various rare fruits. When consumed, for 1 h., one can feel Berserker Spirit, Magic Barrier, Blessed Soul, Empower, Greater Acumen, Clarity, Blessed Body, and Wild Magic.',
    'is_trade' => 0,
    'is_drop' => 0,
    'is_destruct' => 1,
    'crystal_type' => 'crystal_free',
    'consume_type' => 'consume_type_stackable',
  ],
  21095 => 
  [
    'item_id' => 21095,
    'icon' => 'br_four_leaf_clover_box_i00',
    'name' => 'Package: Circlet of Ice',
    'additionalname' => NULL,
    'description' => 'Double-click to obtain Circlet of Ice.',
    'is_trade' => 0,
    'is_drop' => 0,
    'is_destruct' => 1,
    'crystal_type' => 'crystal_free',
    'consume_type' => 'consume_type_stackable',
  ],
  21096 => 
  [
    'item_id' => 21096,
    'icon' => 'event_cubic_piece_i00',
    'name' => 'Shiny Cube D-grade Armor Fragment',
    'additionalname' => NULL,
    'description' => 'Can be exchanged for Blessed Scroll: Enchant D-grade Armor through the Warehouse Keeper. ',
    'is_trade' => 1,
    'is_drop' => 1,
    'is_destruct' => 1,
    'crystal_type' => 'none',
    'consume_type' => 'consume_type_stackable',
  ],
  21097 => 
  [
    'item_id' => 21097,
    'icon' => 'event_cubic_piece_i01',
    'name' => 'Shiny Cube C-grade Armor Fragment',
    'additionalname' => NULL,
    'description' => 'Can be exchanged for Blessed Scroll: Enchant C-grade Armor through the Warehouse Keeper. ',
    'is_trade' => 1,
    'is_drop' => 1,
    'is_destruct' => 1,
    'crystal_type' => 'none',
    'consume_type' => 'consume_type_stackable',
  ],
  21098 => 
  [
    'item_id' => 21098,
    'icon' => 'shine_cubic_a_piece_i02',
    'name' => 'Shiny Cube B-grade Armor Fragment',
    'additionalname' => NULL,
    'description' => 'Can be exchanged for Blessed Scroll: Enchant B-grade Armor through the Warehouse Keeper. ',
    'is_trade' => 1,
    'is_drop' => 1,
    'is_destruct' => 1,
    'crystal_type' => 'none',
    'consume_type' => 'consume_type_stackable',
  ],
  21099 => 
  [
    'item_id' => 21099,
    'icon' => 'shine_cubic_a_piece_i03',
    'name' => 'Shiny Cube A-grade Armor Fragment',
    'additionalname' => NULL,
    'description' => 'Can be exchanged for Blessed Scroll: Enchant A-grade Armor through the Warehouse Keeper. ',
    'is_trade' => 1,
    'is_drop' => 1,
    'is_destruct' => 1,
    'crystal_type' => 'none',
    'consume_type' => 'consume_type_stackable',
  ],
];