<?php return [
  21300 => 
  [
    'item_id' => 21300,
    'icon' => 'br_four_leaf_clover_box_i00',
    'name' => 'Lucky Enchant Stone: Armor Pack (S-grade]',
    'additionalname' => 'Event',
    'description' => 'Wrapped Pack containing Lucky Enchant Stone: Armor (S-grade].',
    'is_trade' => 0,
    'is_drop' => 0,
    'is_destruct' => 1,
    'crystal_type' => 'none',
    'consume_type' => 'consume_type_stackable',
  ],
  21301 => 
  [
    'item_id' => 21301,
    'icon' => 'br_four_leaf_clover_box_i00',
    'name' => 'Crystal of Fortune Treasure Sack Pack',
    'additionalname' => '',
    'description' => 'Wrapped Pack containing a Crystal of Fortune Treasure Sack.',
    'is_trade' => 0,
    'is_drop' => 0,
    'is_destruct' => 1,
    'crystal_type' => 'none',
    'consume_type' => 'consume_type_stackable',
  ],
  21302 => 
  [
    'item_id' => 21302,
    'icon' => 'br_four_leaf_clover_box_i00',
    'name' => 'Crystal of Fortune Treasure Sack Pack',
    'additionalname' => 'Event',
    'description' => 'Wrapped Pack containing a Crystal of Fortune Treasure Sack.',
    'is_trade' => 0,
    'is_drop' => 0,
    'is_destruct' => 1,
    'crystal_type' => 'none',
    'consume_type' => 'consume_type_stackable',
  ],
  21303 => 
  [
    'item_id' => 21303,
    'icon' => 'br_lucky_bag_i00',
    'name' => 'Crystal of Fortune Treasure Sack',
    'additionalname' => '',
    'description' => 'When you open the treasure sack, you can obtain 1 Attribute Crystal or Attribute Stone.',
    'is_trade' => 0,
    'is_drop' => 0,
    'is_destruct' => 1,
    'crystal_type' => 'none',
    'consume_type' => 'consume_type_stackable',
  ],
  21304 => 
  [
    'item_id' => 21304,
    'icon' => 'br_lucky_bag_i00',
    'name' => 'Crystal of Fortune Treasure Sack',
    'additionalname' => 'Event',
    'description' => 'When you open the treasure sack, you can obtain 1 Attribute Crystal or Attribute Stone.',
    'is_trade' => 0,
    'is_drop' => 0,
    'is_destruct' => 1,
    'crystal_type' => 'none',
    'consume_type' => 'consume_type_stackable',
  ],
  21305 => 
  [
    'item_id' => 21305,
    'icon' => 'br_four_leaf_clover_box_i00',
    'name' => 'Enchant Scroll of Fortune Treasure Sack Pack',
    'additionalname' => '',
    'description' => 'Wrapped Pack containing Enchant Scroll of Fortune Treasure Sack.',
    'is_trade' => 0,
    'is_drop' => 0,
    'is_destruct' => 1,
    'crystal_type' => 'none',
    'consume_type' => 'consume_type_stackable',
  ],
  21306 => 
  [
    'item_id' => 21306,
    'icon' => 'br_four_leaf_clover_box_i00',
    'name' => 'Enchant Scroll of Fortune Treasure Sack Pack',
    'additionalname' => 'Event',
    'description' => 'Wrapped Pack containing Enchant Scroll of Fortune Treasure Sack.',
    'is_trade' => 0,
    'is_drop' => 0,
    'is_destruct' => 1,
    'crystal_type' => 'none',
    'consume_type' => 'consume_type_stackable',
  ],
  21307 => 
  [
    'item_id' => 21307,
    'icon' => 'br_lucky_bag_i00',
    'name' => 'Enchant Scroll of Fortune Treasure Sack',
    'additionalname' => '',
    'description' => 'When you open the treasure sack, you can obtain 1 C-grade ~S regular or blessed weapon/armor enchant scroll.',
    'is_trade' => 0,
    'is_drop' => 0,
    'is_destruct' => 1,
    'crystal_type' => 'none',
    'consume_type' => 'consume_type_stackable',
  ],
  21308 => 
  [
    'item_id' => 21308,
    'icon' => 'br_lucky_bag_i00',
    'name' => 'Enchant Scroll of Fortune Treasure Sack',
    'additionalname' => 'Event',
    'description' => 'When you open the treasure sack, you can obtain 1 C-grade ~S regular or blessed weapon/armor enchant scroll.',
    'is_trade' => 0,
    'is_drop' => 0,
    'is_destruct' => 1,
    'crystal_type' => 'none',
    'consume_type' => 'consume_type_stackable',
  ],
  21309 => 
  [
    'item_id' => 21309,
    'icon' => 'br_four_leaf_clover_box_i00',
    'name' => 'Bead of Fortune Treasure Sack Pack',
    'additionalname' => '',
    'description' => 'Wrapped Pack containing Bead of Fortune Treasure Sack.',
    'is_trade' => 0,
    'is_drop' => 0,
    'is_destruct' => 1,
    'crystal_type' => 'none',
    'consume_type' => 'consume_type_stackable',
  ],
  21310 => 
  [
    'item_id' => 21310,
    'icon' => 'br_four_leaf_clover_box_i00',
    'name' => 'Bead of Fortune Treasure Sack Pack',
    'additionalname' => 'Event',
    'description' => 'Wrapped Pack containing Bead of Fortune Treasure Sack.',
    'is_trade' => 0,
    'is_drop' => 0,
    'is_destruct' => 1,
    'crystal_type' => 'none',
    'consume_type' => 'consume_type_stackable',
  ],
  21311 => 
  [
    'item_id' => 21311,
    'icon' => 'br_lucky_bag_i00',
    'name' => 'Bead of Fortune Treasure Sack',
    'additionalname' => '',
    'description' => 'When you open the treasure sack, you can obtain 1 Neolithic Crystal (B~S84], Vitality Replenishing Potion, or Superior Minion coupon (5-hour].',
    'is_trade' => 0,
    'is_drop' => 0,
    'is_destruct' => 1,
    'crystal_type' => 'none',
    'consume_type' => 'consume_type_stackable',
  ],
  21312 => 
  [
    'item_id' => 21312,
    'icon' => 'br_lucky_bag_i00',
    'name' => 'Bead of Fortune Treasure Sack',
    'additionalname' => 'Event',
    'description' => 'When you open the treasure sack, you can obtain 1 Neolithic Crystal (B~S84], Vitality Replenishing Potion, or Superior Minion coupon (5-hour].',
    'is_trade' => 0,
    'is_drop' => 0,
    'is_destruct' => 1,
    'crystal_type' => 'none',
    'consume_type' => 'consume_type_stackable',
  ],
  21313 => 
  [
    'item_id' => 21313,
    'icon' => 'br_four_leaf_clover_box_i00',
    'name' => 'Rider Pouch Pack',
    'additionalname' => '',
    'description' => 'Wrapped Pack containing rider pouch.',
    'is_trade' => 0,
    'is_drop' => 0,
    'is_destruct' => 1,
    'crystal_type' => 'none',
    'consume_type' => 'consume_type_stackable',
  ],
  21314 => 
  [
    'item_id' => 21314,
    'icon' => 'br_four_leaf_clover_box_i00',
    'name' => 'Rider Pouch Pack',
    'additionalname' => 'Event',
    'description' => 'Wrapped Pack containing rider pouch.',
    'is_trade' => 0,
    'is_drop' => 0,
    'is_destruct' => 1,
    'crystal_type' => 'none',
    'consume_type' => 'consume_type_stackable',
  ],
  21315 => 
  [
    'item_id' => 21315,
    'icon' => 'br_lucky_bag_i00',
    'name' => 'Rider Pouch',
    'additionalname' => '',
    'description' => 'Open the pouch to obtain a time-limited (7-day or 30-day] or permanent mount bracelet for Darkmane Pacer, Steam Beetle, Gold Maned Lion, or Jet Bike.',
    'is_trade' => 0,
    'is_drop' => 0,
    'is_destruct' => 1,
    'crystal_type' => 'none',
    'consume_type' => 'consume_type_stackable',
  ],
  21316 => 
  [
    'item_id' => 21316,
    'icon' => 'br_lucky_bag_i00',
    'name' => 'Rider Pouch',
    'additionalname' => 'Event',
    'description' => 'Open the pouch to obtain a time-limited (7-day or 30-day] or permanent mount bracelet for Darkmane Pacer, Steam Beetle, Gold Maned Lion, or Jet Bike.',
    'is_trade' => 0,
    'is_drop' => 0,
    'is_destruct' => 1,
    'crystal_type' => 'none',
    'consume_type' => 'consume_type_stackable',
  ],
  21317 => 
  [
    'item_id' => 21317,
    'icon' => 'br_four_leaf_clover_box_i00',
    'name' => 'Fashion Pouch Pack',
    'additionalname' => '',
    'description' => 'Wrapped Pack containing fashion pouch.',
    'is_trade' => 0,
    'is_drop' => 0,
    'is_destruct' => 1,
    'crystal_type' => 'none',
    'consume_type' => 'consume_type_stackable',
  ],
  21318 => 
  [
    'item_id' => 21318,
    'icon' => 'br_four_leaf_clover_box_i00',
    'name' => 'Fashion Pouch Pack',
    'additionalname' => 'Event',
    'description' => 'Wrapped Pack containing fashion pouch.',
    'is_trade' => 0,
    'is_drop' => 0,
    'is_destruct' => 1,
    'crystal_type' => 'none',
    'consume_type' => 'consume_type_stackable',
  ],
  21319 => 
  [
    'item_id' => 21319,
    'icon' => 'br_lucky_bag_i00',
    'name' => 'Fashion Pouch',
    'additionalname' => '',
    'description' => 'Open the pouch to obtain a time-limited (7-day or 30-day] or permanent Refined Dapper Cap, Valkyrie Circlet, or Plastic Hair.',
    'is_trade' => 0,
    'is_drop' => 0,
    'is_destruct' => 1,
    'crystal_type' => 'none',
    'consume_type' => 'consume_type_stackable',
  ],
  21320 => 
  [
    'item_id' => 21320,
    'icon' => 'br_lucky_bag_i00',
    'name' => 'Fashion Pouch',
    'additionalname' => 'Event',
    'description' => 'Open the pouch to obtain a time-limited (7-day or 30-day] or permanent Refined Dapper Cap, Valkyrie Circlet, or Plastic Hair.',
    'is_trade' => 0,
    'is_drop' => 0,
    'is_destruct' => 1,
    'crystal_type' => 'none',
    'consume_type' => 'consume_type_stackable',
  ],
  21321 => 
  [
    'item_id' => 21321,
    'icon' => 'br_four_leaf_clover_box_i00',
    'name' => 'Buff Pouch Pack',
    'additionalname' => '',
    'description' => 'Wrapped Pack containing buff pouch.',
    'is_trade' => 0,
    'is_drop' => 0,
    'is_destruct' => 1,
    'crystal_type' => 'none',
    'consume_type' => 'consume_type_stackable',
  ],
  21322 => 
  [
    'item_id' => 21322,
    'icon' => 'br_four_leaf_clover_box_i00',
    'name' => 'Buff Pouch Pack',
    'additionalname' => 'Event',
    'description' => 'Wrapped Pack containing buff pouch.',
    'is_trade' => 0,
    'is_drop' => 0,
    'is_destruct' => 1,
    'crystal_type' => 'none',
    'consume_type' => 'consume_type_stackable',
  ],
  21323 => 
  [
    'item_id' => 21323,
    'icon' => 'br_lucky_bag_i00',
    'name' => 'Buff Pouch',
    'additionalname' => '',
    'description' => 'When you open the pouch, you can obtain 1 of the following: cookie (Gludio, Dion, Aden, Giran, Rune], super healthy juice (HP, CP], sweet/fresh fruit cocktail, or fresh milk.',
    'is_trade' => 0,
    'is_drop' => 0,
    'is_destruct' => 1,
    'crystal_type' => 'none',
    'consume_type' => 'consume_type_stackable',
  ],
  21324 => 
  [
    'item_id' => 21324,
    'icon' => 'br_lucky_bag_i00',
    'name' => 'Buff Pouch',
    'additionalname' => 'Event',
    'description' => 'When you open the pouch, you can obtain 1 of the following: cookie (Gludio, Dion, Aden, Giran, Rune], super healthy juice (HP, CP], sweet/fresh fruit cocktail, or fresh milk.',
    'is_trade' => 0,
    'is_drop' => 0,
    'is_destruct' => 1,
    'crystal_type' => 'none',
    'consume_type' => 'consume_type_stackable',
  ],
  21325 => 
  [
    'item_id' => 21325,
    'icon' => 'br_four_leaf_clover_box_i00',
    'name' => 'Agathion - Griffin Pack (7-day]',
    'additionalname' => '',
    'description' => 'Wrapped Pack containing Agathion - Griffin (7-day].',
    'is_trade' => 0,
    'is_drop' => 0,
    'is_destruct' => 1,
    'crystal_type' => 'none',
    'consume_type' => 'consume_type_stackable',
  ],
  21326 => 
  [
    'item_id' => 21326,
    'icon' => 'br_four_leaf_clover_box_i00',
    'name' => 'Agathion - Griffin Pack (7-day]',
    'additionalname' => 'Event',
    'description' => 'Wrapped Pack containing Agathion - Griffin (7-day].',
    'is_trade' => 0,
    'is_drop' => 0,
    'is_destruct' => 1,
    'crystal_type' => 'none',
    'consume_type' => 'consume_type_stackable',
  ],
  21327 => 
  [
    'item_id' => 21327,
    'icon' => 'br_four_leaf_clover_box_i00',
    'name' => 'Agathion - Griffin Pack (30-day]',
    'additionalname' => '',
    'description' => 'Wrapped Pack containing Agathion - Griffin (30-day].',
    'is_trade' => 0,
    'is_drop' => 0,
    'is_destruct' => 1,
    'crystal_type' => 'none',
    'consume_type' => 'consume_type_stackable',
  ],
  21328 => 
  [
    'item_id' => 21328,
    'icon' => 'br_four_leaf_clover_box_i00',
    'name' => 'Agathion - Griffin Pack (30-day]',
    'additionalname' => 'Event',
    'description' => 'Wrapped Pack containing Agathion - Griffin (30-day].',
    'is_trade' => 0,
    'is_drop' => 0,
    'is_destruct' => 1,
    'crystal_type' => 'none',
    'consume_type' => 'consume_type_stackable',
  ],
  21329 => 
  [
    'item_id' => 21329,
    'icon' => 'br_four_leaf_clover_box_i00',
    'name' => 'Agathion - Griffin Pack',
    'additionalname' => '',
    'description' => 'Wrapped Pack containing Agathion - Griffin.',
    'is_trade' => 0,
    'is_drop' => 0,
    'is_destruct' => 1,
    'crystal_type' => 'none',
    'consume_type' => 'consume_type_stackable',
  ],
  21330 => 
  [
    'item_id' => 21330,
    'icon' => 'br_four_leaf_clover_box_i00',
    'name' => 'Agathion - Griffin Pack',
    'additionalname' => 'Event',
    'description' => 'Wrapped Pack containing Agathion - Griffin.',
    'is_trade' => 0,
    'is_drop' => 0,
    'is_destruct' => 1,
    'crystal_type' => 'none',
    'consume_type' => 'consume_type_stackable',
  ],
  21331 => 
  [
    'item_id' => 21331,
    'icon' => 'etc_rbracelet_aga_agit_i00',
    'name' => 'Agathion - Griffin',
    'additionalname' => '7-day',
    'description' => 'Can summon an Agathion - Griffin when equipped. 7-day.',
    'is_trade' => 0,
    'is_drop' => 0,
    'is_destruct' => 0,
    'crystal_type' => 'none',
    'consume_type' => 'consume_type_normal',
  ],
  21332 => 
  [
    'item_id' => 21332,
    'icon' => 'etc_rbracelet_aga_agit_i00',
    'name' => 'Agathion - Griffin',
    'additionalname' => '7-day (Event]',
    'description' => 'Can summon an Agathion - Griffin when equipped. 7-day.',
    'is_trade' => 0,
    'is_drop' => 0,
    'is_destruct' => 0,
    'crystal_type' => 'none',
    'consume_type' => 'consume_type_normal',
  ],
  21333 => 
  [
    'item_id' => 21333,
    'icon' => 'etc_rbracelet_aga_agit_i00',
    'name' => 'Agathion - Griffin',
    'additionalname' => '30-day',
    'description' => 'Can summon an Agathion - Griffin when equipped. 30-day.',
    'is_trade' => 0,
    'is_drop' => 0,
    'is_destruct' => 0,
    'crystal_type' => 'none',
    'consume_type' => 'consume_type_normal',
  ],
  21334 => 
  [
    'item_id' => 21334,
    'icon' => 'etc_rbracelet_aga_agit_i00',
    'name' => 'Agathion - Griffin',
    'additionalname' => '30-day (Event]',
    'description' => 'Can summon an Agathion - Griffin when equipped. 30-day.',
    'is_trade' => 0,
    'is_drop' => 0,
    'is_destruct' => 0,
    'crystal_type' => 'none',
    'consume_type' => 'consume_type_normal',
  ],
  21335 => 
  [
    'item_id' => 21335,
    'icon' => 'etc_rbracelet_aga_agit_i00',
    'name' => 'Agathion - Griffin',
    'additionalname' => '',
    'description' => 'Can summon an Agathion - Griffin when equipped.',
    'is_trade' => 0,
    'is_drop' => 0,
    'is_destruct' => 1,
    'crystal_type' => 'none',
    'consume_type' => 'consume_type_normal',
  ],
  21336 => 
  [
    'item_id' => 21336,
    'icon' => 'etc_rbracelet_aga_agit_i00',
    'name' => 'Agathion - Griffin',
    'additionalname' => 'Event',
    'description' => 'Can summon an Agathion - Griffin when equipped.',
    'is_trade' => 0,
    'is_drop' => 0,
    'is_destruct' => 1,
    'crystal_type' => 'none',
    'consume_type' => 'consume_type_normal',
  ],
  21337 => 
  [
    'item_id' => 21337,
    'icon' => 'br_four_leaf_clover_box_i00',
    'name' => 'Agathion - Cow Pack (7-day]',
    'additionalname' => '',
    'description' => 'Wrapped Pack containing Agathion - Cow (7-day].',
    'is_trade' => 0,
    'is_drop' => 0,
    'is_destruct' => 1,
    'crystal_type' => 'none',
    'consume_type' => 'consume_type_stackable',
  ],
  21338 => 
  [
    'item_id' => 21338,
    'icon' => 'br_four_leaf_clover_box_i00',
    'name' => 'Agathion - Cow Pack (7-day]',
    'additionalname' => 'Event',
    'description' => 'Wrapped Pack containing Agathion - Cow (7-day].',
    'is_trade' => 0,
    'is_drop' => 0,
    'is_destruct' => 1,
    'crystal_type' => 'none',
    'consume_type' => 'consume_type_stackable',
  ],
  21339 => 
  [
    'item_id' => 21339,
    'icon' => 'br_four_leaf_clover_box_i00',
    'name' => 'Agathion - Cow Pack (30-day]',
    'additionalname' => '',
    'description' => 'Wrapped Pack containing Agathion - Cow (30-day].',
    'is_trade' => 0,
    'is_drop' => 0,
    'is_destruct' => 1,
    'crystal_type' => 'none',
    'consume_type' => 'consume_type_stackable',
  ],
  21340 => 
  [
    'item_id' => 21340,
    'icon' => 'br_four_leaf_clover_box_i00',
    'name' => 'Agathion - Cow Pack (30-day]',
    'additionalname' => 'Event',
    'description' => 'Wrapped Pack containing Agathion - Cow (30-day].',
    'is_trade' => 0,
    'is_drop' => 0,
    'is_destruct' => 1,
    'crystal_type' => 'none',
    'consume_type' => 'consume_type_stackable',
  ],
  21341 => 
  [
    'item_id' => 21341,
    'icon' => 'br_four_leaf_clover_box_i00',
    'name' => 'Agathion - Cow Pack',
    'additionalname' => '',
    'description' => 'Wrapped Pack containing Agathion - Cow.',
    'is_trade' => 0,
    'is_drop' => 0,
    'is_destruct' => 1,
    'crystal_type' => 'none',
    'consume_type' => 'consume_type_stackable',
  ],
  21342 => 
  [
    'item_id' => 21342,
    'icon' => 'br_four_leaf_clover_box_i00',
    'name' => 'Agathion - Cow Pack',
    'additionalname' => 'Event',
    'description' => 'Wrapped Pack containing Agathion - Cow.',
    'is_trade' => 0,
    'is_drop' => 0,
    'is_destruct' => 1,
    'crystal_type' => 'none',
    'consume_type' => 'consume_type_stackable',
  ],
  21343 => 
  [
    'item_id' => 21343,
    'icon' => 'etc_rbracelet_aga_agit_i00',
    'name' => 'Agathion - Cow',
    'additionalname' => '7-day',
    'description' => 'Can summon an Agathion - Cow when equipped. 7-day.',
    'is_trade' => 0,
    'is_drop' => 0,
    'is_destruct' => 0,
    'crystal_type' => 'none',
    'consume_type' => 'consume_type_normal',
  ],
  21344 => 
  [
    'item_id' => 21344,
    'icon' => 'etc_rbracelet_aga_agit_i00',
    'name' => 'Agathion - Cow',
    'additionalname' => '7-day (Event]',
    'description' => 'Can summon an Agathion - Cow when equipped. 7-day.',
    'is_trade' => 0,
    'is_drop' => 0,
    'is_destruct' => 0,
    'crystal_type' => 'none',
    'consume_type' => 'consume_type_normal',
  ],
  21345 => 
  [
    'item_id' => 21345,
    'icon' => 'etc_rbracelet_aga_agit_i00',
    'name' => 'Agathion - Cow',
    'additionalname' => '30-day',
    'description' => 'Can summon an Agathion - Cow when equipped. 30-day.',
    'is_trade' => 0,
    'is_drop' => 0,
    'is_destruct' => 0,
    'crystal_type' => 'none',
    'consume_type' => 'consume_type_normal',
  ],
  21346 => 
  [
    'item_id' => 21346,
    'icon' => 'etc_rbracelet_aga_agit_i00',
    'name' => 'Agathion - Cow',
    'additionalname' => '30-day (Event]',
    'description' => 'Can summon an Agathion - Cow when equipped. 30-day.',
    'is_trade' => 0,
    'is_drop' => 0,
    'is_destruct' => 0,
    'crystal_type' => 'none',
    'consume_type' => 'consume_type_normal',
  ],
  21347 => 
  [
    'item_id' => 21347,
    'icon' => 'etc_rbracelet_aga_agit_i00',
    'name' => 'Agathion - Cow',
    'additionalname' => '',
    'description' => 'Can summon an Agathion - Cow when equipped.',
    'is_trade' => 0,
    'is_drop' => 0,
    'is_destruct' => 1,
    'crystal_type' => 'none',
    'consume_type' => 'consume_type_normal',
  ],
  21348 => 
  [
    'item_id' => 21348,
    'icon' => 'etc_rbracelet_aga_agit_i00',
    'name' => 'Agathion - Cow',
    'additionalname' => 'Event',
    'description' => 'Can summon Agathion - Cow when equipped.',
    'is_trade' => 0,
    'is_drop' => 0,
    'is_destruct' => 1,
    'crystal_type' => 'none',
    'consume_type' => 'consume_type_normal',
  ],
  21349 => 
  [
    'item_id' => 21349,
    'icon' => 'br_four_leaf_clover_box_i00',
    'name' => 'Agathion - Makeshift Bat Pack (7-day]',
    'additionalname' => '',
    'description' => 'Wrapped Pack containing Agathion - Makeshift Bat (7-day].',
    'is_trade' => 0,
    'is_drop' => 0,
    'is_destruct' => 1,
    'crystal_type' => 'none',
    'consume_type' => 'consume_type_stackable',
  ],
  21350 => 
  [
    'item_id' => 21350,
    'icon' => 'br_four_leaf_clover_box_i00',
    'name' => 'Agathion - Makeshift Bat Pack (7-day]',
    'additionalname' => 'Event',
    'description' => 'Wrapped Pack containing Agathion - Makeshift Bat (7-day].',
    'is_trade' => 0,
    'is_drop' => 0,
    'is_destruct' => 1,
    'crystal_type' => 'none',
    'consume_type' => 'consume_type_stackable',
  ],
  21351 => 
  [
    'item_id' => 21351,
    'icon' => 'br_four_leaf_clover_box_i00',
    'name' => 'Agathion - Makeshift Bat Pack (30-day]',
    'additionalname' => '',
    'description' => 'Wrapped Pack containing Agathion - Makeshift Bat (30-day].',
    'is_trade' => 0,
    'is_drop' => 0,
    'is_destruct' => 1,
    'crystal_type' => 'none',
    'consume_type' => 'consume_type_stackable',
  ],
  21352 => 
  [
    'item_id' => 21352,
    'icon' => 'br_four_leaf_clover_box_i00',
    'name' => 'Agathion - Makeshift Bat Pack (30-day]',
    'additionalname' => 'Event',
    'description' => 'Wrapped Pack containing Agathion - Makeshift Bat (30-day].',
    'is_trade' => 0,
    'is_drop' => 0,
    'is_destruct' => 1,
    'crystal_type' => 'none',
    'consume_type' => 'consume_type_stackable',
  ],
  21353 => 
  [
    'item_id' => 21353,
    'icon' => 'br_four_leaf_clover_box_i00',
    'name' => 'Agathion - Makeshift Bat Pack',
    'additionalname' => '',
    'description' => 'Wrapped Pack containing Agathion - Makeshift Bat.',
    'is_trade' => 0,
    'is_drop' => 0,
    'is_destruct' => 1,
    'crystal_type' => 'none',
    'consume_type' => 'consume_type_stackable',
  ],
  21354 => 
  [
    'item_id' => 21354,
    'icon' => 'br_four_leaf_clover_box_i00',
    'name' => 'Agathion - Makeshift Bat Pack',
    'additionalname' => 'Event',
    'description' => 'Wrapped Pack containing Agathion - Makeshift Bat.',
    'is_trade' => 0,
    'is_drop' => 0,
    'is_destruct' => 1,
    'crystal_type' => 'none',
    'consume_type' => 'consume_type_stackable',
  ],
  21355 => 
  [
    'item_id' => 21355,
    'icon' => 'etc_rbracelet_aga_agit_i00',
    'name' => 'Agathion - Makeshift Bat',
    'additionalname' => '7-day',
    'description' => 'Can summon an Agathion - Makeshift Bat when equipped. 7-day.',
    'is_trade' => 0,
    'is_drop' => 0,
    'is_destruct' => 0,
    'crystal_type' => 'none',
    'consume_type' => 'consume_type_normal',
  ],
  21356 => 
  [
    'item_id' => 21356,
    'icon' => 'etc_rbracelet_aga_agit_i00',
    'name' => 'Agathion - Makeshift Bat',
    'additionalname' => '7-day (Event]',
    'description' => 'Can summon an Agathion - Makeshift Bat when equipped. 7-day.',
    'is_trade' => 0,
    'is_drop' => 0,
    'is_destruct' => 0,
    'crystal_type' => 'none',
    'consume_type' => 'consume_type_normal',
  ],
  21357 => 
  [
    'item_id' => 21357,
    'icon' => 'etc_rbracelet_aga_agit_i00',
    'name' => 'Agathion - Makeshift Bat',
    'additionalname' => '30-day',
    'description' => 'Can summon an Agathion - Makeshift Bat when equipped. 30-day.',
    'is_trade' => 0,
    'is_drop' => 0,
    'is_destruct' => 0,
    'crystal_type' => 'none',
    'consume_type' => 'consume_type_normal',
  ],
  21358 => 
  [
    'item_id' => 21358,
    'icon' => 'etc_rbracelet_aga_agit_i00',
    'name' => 'Agathion - Makeshift Bat',
    'additionalname' => '30-day (Event]',
    'description' => 'Can summon an Agathion - Makeshift Bat when equipped. 30-day.',
    'is_trade' => 0,
    'is_drop' => 0,
    'is_destruct' => 0,
    'crystal_type' => 'none',
    'consume_type' => 'consume_type_normal',
  ],
  21359 => 
  [
    'item_id' => 21359,
    'icon' => 'etc_rbracelet_aga_agit_i00',
    'name' => 'Agathion - Makeshift Bat',
    'additionalname' => '',
    'description' => 'Can summon Agathion - Makeshift Bat when equipped.',
    'is_trade' => 0,
    'is_drop' => 0,
    'is_destruct' => 1,
    'crystal_type' => 'none',
    'consume_type' => 'consume_type_normal',
  ],
  21360 => 
  [
    'item_id' => 21360,
    'icon' => 'etc_rbracelet_aga_agit_i00',
    'name' => 'Agathion - Makeshift Bat',
    'additionalname' => 'Event',
    'description' => 'Can summon an Agathion - Makeshift Bat when equipped.',
    'is_trade' => 0,
    'is_drop' => 0,
    'is_destruct' => 1,
    'crystal_type' => 'none',
    'consume_type' => 'consume_type_normal',
  ],
  21361 => 
  [
    'item_id' => 21361,
    'icon' => 'br_four_leaf_clover_box_i00',
    'name' => 'Aqua Elf Transformation Harp Pack (7-day]',
    'additionalname' => '',
    'description' => 'Wrapped Pack containing Aqua Elf Transformation Harp (7-day].',
    'is_trade' => 0,
    'is_drop' => 0,
    'is_destruct' => 1,
    'crystal_type' => 'none',
    'consume_type' => 'consume_type_stackable',
  ],
  21362 => 
  [
    'item_id' => 21362,
    'icon' => 'br_four_leaf_clover_box_i00',
    'name' => 'Aqua Elf Transformation Harp Pack (7-day]',
    'additionalname' => 'Event',
    'description' => 'Wrapped Pack containing Aqua Elf Transformation Harp (7-day].',
    'is_trade' => 0,
    'is_drop' => 0,
    'is_destruct' => 1,
    'crystal_type' => 'none',
    'consume_type' => 'consume_type_stackable',
  ],
  21363 => 
  [
    'item_id' => 21363,
    'icon' => 'br_four_leaf_clover_box_i00',
    'name' => 'Aqua Elf Transformation Harp Pack (30-day]',
    'additionalname' => '',
    'description' => 'Wrapped Pack containing Aqua Elf Transformation Harp (30-day].',
    'is_trade' => 0,
    'is_drop' => 0,
    'is_destruct' => 1,
    'crystal_type' => 'none',
    'consume_type' => 'consume_type_stackable',
  ],
  21364 => 
  [
    'item_id' => 21364,
    'icon' => 'br_four_leaf_clover_box_i00',
    'name' => 'Aqua Elf Transformation Harp Pack (30-day]',
    'additionalname' => 'Event',
    'description' => 'Wrapped Pack containing Aqua Elf Transformation Harp (30-day].',
    'is_trade' => 0,
    'is_drop' => 0,
    'is_destruct' => 1,
    'crystal_type' => 'none',
    'consume_type' => 'consume_type_stackable',
  ],
  21365 => 
  [
    'item_id' => 21365,
    'icon' => 'br_four_leaf_clover_box_i00',
    'name' => 'Aqua Elf Transformation Harp Pack',
    'additionalname' => '',
    'description' => 'Wrapped Pack containing Aqua Elf Transformation Harp.',
    'is_trade' => 0,
    'is_drop' => 0,
    'is_destruct' => 1,
    'crystal_type' => 'none',
    'consume_type' => 'consume_type_stackable',
  ],
  21366 => 
  [
    'item_id' => 21366,
    'icon' => 'br_four_leaf_clover_box_i00',
    'name' => 'Aqua Elf Transformation Harp Pack',
    'additionalname' => 'Event',
    'description' => 'Wrapped Pack containing Aqua Elf Transformation Harp.',
    'is_trade' => 0,
    'is_drop' => 0,
    'is_destruct' => 1,
    'crystal_type' => 'none',
    'consume_type' => 'consume_type_stackable',
  ],
  21367 => 
  [
    'item_id' => 21367,
    'icon' => 'harp_of_transform_i00',
    'name' => 'Aqua Elf Transformation Harp',
    'additionalname' => '7-day',
    'description' => 'Transformation Harp that turns you into an Aqua Elf. 7-day.',
    'is_trade' => 0,
    'is_drop' => 0,
    'is_destruct' => 0,
    'crystal_type' => 'none',
    'consume_type' => 'consume_type_normal',
  ],
  21368 => 
  [
    'item_id' => 21368,
    'icon' => 'harp_of_transform_i00',
    'name' => 'Aqua Elf Transformation Harp',
    'additionalname' => '7-day (Event]',
    'description' => 'Transformation Harp that turns you into an Aqua Elf. 7-day.',
    'is_trade' => 0,
    'is_drop' => 0,
    'is_destruct' => 0,
    'crystal_type' => 'none',
    'consume_type' => 'consume_type_normal',
  ],
  21369 => 
  [
    'item_id' => 21369,
    'icon' => 'harp_of_transform_i00',
    'name' => 'Aqua Elf Transformation Harp',
    'additionalname' => '30-day',
    'description' => 'Transformation Harp that turns you into an Aqua Elf. 30-day.',
    'is_trade' => 0,
    'is_drop' => 0,
    'is_destruct' => 0,
    'crystal_type' => 'none',
    'consume_type' => 'consume_type_normal',
  ],
  21370 => 
  [
    'item_id' => 21370,
    'icon' => 'harp_of_transform_i00',
    'name' => 'Aqua Elf Transformation Harp',
    'additionalname' => '30-day (Event]',
    'description' => 'Transformation Harp that turns you into an Aqua Elf. 30-day.',
    'is_trade' => 0,
    'is_drop' => 0,
    'is_destruct' => 0,
    'crystal_type' => 'none',
    'consume_type' => 'consume_type_normal',
  ],
  21371 => 
  [
    'item_id' => 21371,
    'icon' => 'harp_of_transform_i00',
    'name' => 'Aqua Elf Transformation Harp',
    'additionalname' => '',
    'description' => 'Transformation Harp that turns you into an Aqua Elf.',
    'is_trade' => 0,
    'is_drop' => 0,
    'is_destruct' => 1,
    'crystal_type' => 'none',
    'consume_type' => 'consume_type_normal',
  ],
  21372 => 
  [
    'item_id' => 21372,
    'icon' => 'harp_of_transform_i00',
    'name' => 'Aqua Elf Transformation Harp',
    'additionalname' => 'Event',
    'description' => 'Transformation Harp that turns you into an Aqua Elf.',
    'is_trade' => 0,
    'is_drop' => 0,
    'is_destruct' => 1,
    'crystal_type' => 'none',
    'consume_type' => 'consume_type_normal',
  ],
  21373 => 
  [
    'item_id' => 21373,
    'icon' => 'br_four_leaf_clover_box_i00',
    'name' => 'Mount - Darkmane Pacer Pack (7-day]',
    'additionalname' => '',
    'description' => 'Wrapped Pack containing Mount - Darkmane Pacer (7-day].',
    'is_trade' => 0,
    'is_drop' => 0,
    'is_destruct' => 1,
    'crystal_type' => 'none',
    'consume_type' => 'consume_type_stackable',
  ],
  21374 => 
  [
    'item_id' => 21374,
    'icon' => 'br_four_leaf_clover_box_i00',
    'name' => 'Mount - Darkmane Pacer Pack (7-day]',
    'additionalname' => 'Event',
    'description' => 'Wrapped Pack containing Mount - Darkmane Pacer (7-day].',
    'is_trade' => 0,
    'is_drop' => 0,
    'is_destruct' => 1,
    'crystal_type' => 'none',
    'consume_type' => 'consume_type_stackable',
  ],
  21375 => 
  [
    'item_id' => 21375,
    'icon' => 'br_four_leaf_clover_box_i00',
    'name' => 'Mount - Darkmane Pacer Pack (30-day]',
    'additionalname' => '',
    'description' => 'Wrapped Pack containing Mount - Darkmane Pacer (30-day].',
    'is_trade' => 0,
    'is_drop' => 0,
    'is_destruct' => 1,
    'crystal_type' => 'none',
    'consume_type' => 'consume_type_stackable',
  ],
  21376 => 
  [
    'item_id' => 21376,
    'icon' => 'br_four_leaf_clover_box_i00',
    'name' => 'Mount - Darkmane Pacer Pack (30-day]',
    'additionalname' => 'Event',
    'description' => 'Wrapped Pack containing Mount - Darkmane Pacer (30-day].',
    'is_trade' => 0,
    'is_drop' => 0,
    'is_destruct' => 1,
    'crystal_type' => 'none',
    'consume_type' => 'consume_type_stackable',
  ],
  21377 => 
  [
    'item_id' => 21377,
    'icon' => 'br_four_leaf_clover_box_i00',
    'name' => 'Mount - Darkmane Pacer Pack',
    'additionalname' => '',
    'description' => 'Wrapped Pack containing Mount - Darkmane Pacer.',
    'is_trade' => 1,
    'is_drop' => 1,
    'is_destruct' => 1,
    'crystal_type' => 'none',
    'consume_type' => 'consume_type_stackable',
  ],
  21378 => 
  [
    'item_id' => 21378,
    'icon' => 'br_four_leaf_clover_box_i00',
    'name' => 'Mount - Darkmane Pacer Pack',
    'additionalname' => 'Event',
    'description' => 'Wrapped Pack containing Mount - Darkmane Pacer.',
    'is_trade' => 0,
    'is_drop' => 0,
    'is_destruct' => 1,
    'crystal_type' => 'none',
    'consume_type' => 'consume_type_stackable',
  ],
  21379 => 
  [
    'item_id' => 21379,
    'icon' => 'etc_rbracelet_aga_agit_i00',
    'name' => 'Mount - Darkmane Pacer',
    'additionalname' => '7-day',
    'description' => 'Allows you to mount a Darkmane Pacer when equipped. 7-day.',
    'is_trade' => 0,
    'is_drop' => 0,
    'is_destruct' => 0,
    'crystal_type' => 'none',
    'consume_type' => 'consume_type_normal',
  ],
  21380 => 
  [
    'item_id' => 21380,
    'icon' => 'etc_rbracelet_aga_agit_i00',
    'name' => 'Mount - Darkmane Pacer',
    'additionalname' => '7-day (Event]',
    'description' => 'Can mount a Darkmane Pacer when equipped. 7-day.',
    'is_trade' => 0,
    'is_drop' => 0,
    'is_destruct' => 0,
    'crystal_type' => 'none',
    'consume_type' => 'consume_type_normal',
  ],
  21381 => 
  [
    'item_id' => 21381,
    'icon' => 'etc_rbracelet_aga_agit_i00',
    'name' => 'Mount - Darkmane Pacer',
    'additionalname' => '30-day',
    'description' => 'Can ride a Darkmane Pacer when equipped. 30-day.',
    'is_trade' => 0,
    'is_drop' => 0,
    'is_destruct' => 0,
    'crystal_type' => 'none',
    'consume_type' => 'consume_type_normal',
  ],
  21382 => 
  [
    'item_id' => 21382,
    'icon' => 'etc_rbracelet_aga_agit_i00',
    'name' => 'Mount - Darkmane Pacer',
    'additionalname' => '30-day (Event]',
    'description' => 'Can mount a Darkmane Pacer when equipped. 30-day.',
    'is_trade' => 0,
    'is_drop' => 0,
    'is_destruct' => 0,
    'crystal_type' => 'none',
    'consume_type' => 'consume_type_normal',
  ],
  21383 => 
  [
    'item_id' => 21383,
    'icon' => 'etc_rbracelet_aga_agit_i00',
    'name' => 'Mount - Darkmane Pacer',
    'additionalname' => '',
    'description' => 'Can mount a Darkmane Pacer when equipped.',
    'is_trade' => 1,
    'is_drop' => 1,
    'is_destruct' => 1,
    'crystal_type' => 'none',
    'consume_type' => 'consume_type_normal',
  ],
  21384 => 
  [
    'item_id' => 21384,
    'icon' => 'etc_rbracelet_aga_agit_i00',
    'name' => 'Mount - Darkmane Pacer',
    'additionalname' => 'Event',
    'description' => 'Can mount a Darkmane Pacer when equipped.',
    'is_trade' => 0,
    'is_drop' => 0,
    'is_destruct' => 1,
    'crystal_type' => 'none',
    'consume_type' => 'consume_type_normal',
  ],
  21385 => 
  [
    'item_id' => 21385,
    'icon' => 'br_four_leaf_clover_box_i00',
    'name' => 'Mount - Steam Beetle Pack (7-day]',
    'additionalname' => '',
    'description' => 'Wrapped Pack containing Mount - Steam Beetle (7-day].',
    'is_trade' => 0,
    'is_drop' => 0,
    'is_destruct' => 1,
    'crystal_type' => 'none',
    'consume_type' => 'consume_type_stackable',
  ],
  21386 => 
  [
    'item_id' => 21386,
    'icon' => 'br_four_leaf_clover_box_i00',
    'name' => 'Mount - Steam Beetle Pack (7-day]',
    'additionalname' => 'Event',
    'description' => 'Wrapped Pack containing Mount - Steam Beetle (7-day].',
    'is_trade' => 0,
    'is_drop' => 0,
    'is_destruct' => 1,
    'crystal_type' => 'none',
    'consume_type' => 'consume_type_stackable',
  ],
  21387 => 
  [
    'item_id' => 21387,
    'icon' => 'br_four_leaf_clover_box_i00',
    'name' => 'Mount - Steam Beetle Pack (30-day]',
    'additionalname' => '',
    'description' => 'A wrapped box containing Mount - Steam Beetle (30-day].',
    'is_trade' => 0,
    'is_drop' => 0,
    'is_destruct' => 1,
    'crystal_type' => 'none',
    'consume_type' => 'consume_type_stackable',
  ],
  21388 => 
  [
    'item_id' => 21388,
    'icon' => 'br_four_leaf_clover_box_i00',
    'name' => 'Mount - Steam Beetle Pack (30-day]',
    'additionalname' => 'Event',
    'description' => 'Wrapped Pack containing Mount - Steam Beetle (30-day].',
    'is_trade' => 0,
    'is_drop' => 0,
    'is_destruct' => 1,
    'crystal_type' => 'none',
    'consume_type' => 'consume_type_stackable',
  ],
  21389 => 
  [
    'item_id' => 21389,
    'icon' => 'br_four_leaf_clover_box_i00',
    'name' => 'Mount - Steam Beetle Pack',
    'additionalname' => '',
    'description' => 'Wrapped Pack containing Mount - Steam Beetle.',
    'is_trade' => 0,
    'is_drop' => 0,
    'is_destruct' => 1,
    'crystal_type' => 'none',
    'consume_type' => 'consume_type_stackable',
  ],
  21390 => 
  [
    'item_id' => 21390,
    'icon' => 'br_four_leaf_clover_box_i00',
    'name' => 'Mount - Steam Beetle Pack',
    'additionalname' => 'Event',
    'description' => 'Wrapped Pack containing Mount - Steam Beetle.',
    'is_trade' => 0,
    'is_drop' => 0,
    'is_destruct' => 1,
    'crystal_type' => 'none',
    'consume_type' => 'consume_type_stackable',
  ],
  21391 => 
  [
    'item_id' => 21391,
    'icon' => 'etc_rbracelet_aga_agit_i00',
    'name' => 'Mount - Steam Beetle',
    'additionalname' => '7-day',
    'description' => 'Can mount a Steam Beetle when equipped. 7-day.',
    'is_trade' => 0,
    'is_drop' => 0,
    'is_destruct' => 0,
    'crystal_type' => 'none',
    'consume_type' => 'consume_type_normal',
  ],
  21392 => 
  [
    'item_id' => 21392,
    'icon' => 'etc_rbracelet_aga_agit_i00',
    'name' => 'Mount - Steam Beetle',
    'additionalname' => '7-day (Event]',
    'description' => 'Can mount a Steam Beetle when equipped. 7-day.',
    'is_trade' => 0,
    'is_drop' => 0,
    'is_destruct' => 0,
    'crystal_type' => 'none',
    'consume_type' => 'consume_type_normal',
  ],
  21393 => 
  [
    'item_id' => 21393,
    'icon' => 'etc_rbracelet_aga_agit_i00',
    'name' => 'Mount - Steam Beetle',
    'additionalname' => '30-day',
    'description' => 'Can ride a Steam Beetle when equipped. 30-day.',
    'is_trade' => 0,
    'is_drop' => 0,
    'is_destruct' => 0,
    'crystal_type' => 'none',
    'consume_type' => 'consume_type_normal',
  ],
  21394 => 
  [
    'item_id' => 21394,
    'icon' => 'etc_rbracelet_aga_agit_i00',
    'name' => 'Mount - Steam Beetle',
    'additionalname' => '30-day (Event]',
    'description' => 'Can mount a Steam Beetle when equipped. 30-day.',
    'is_trade' => 0,
    'is_drop' => 0,
    'is_destruct' => 0,
    'crystal_type' => 'none',
    'consume_type' => 'consume_type_normal',
  ],
  21395 => 
  [
    'item_id' => 21395,
    'icon' => 'etc_rbracelet_aga_agit_i00',
    'name' => 'Mount - Steam Beetle',
    'additionalname' => '',
    'description' => 'Can mount a Steam Beetle when equipped.',
    'is_trade' => 0,
    'is_drop' => 0,
    'is_destruct' => 1,
    'crystal_type' => 'none',
    'consume_type' => 'consume_type_normal',
  ],
  21396 => 
  [
    'item_id' => 21396,
    'icon' => 'etc_rbracelet_aga_agit_i00',
    'name' => 'Mount - Steam Beetle',
    'additionalname' => 'Event',
    'description' => 'Can mount a Steam Beetle when equipped.',
    'is_trade' => 0,
    'is_drop' => 0,
    'is_destruct' => 1,
    'crystal_type' => 'none',
    'consume_type' => 'consume_type_normal',
  ],
  21397 => 
  [
    'item_id' => 21397,
    'icon' => 'br_four_leaf_clover_box_i00',
    'name' => 'Mount - Gold Maned Lion Pack (7-day]',
    'additionalname' => '',
    'description' => 'Wrapped Pack containing Mount - Gold Maned Lion (7-day].',
    'is_trade' => 0,
    'is_drop' => 0,
    'is_destruct' => 1,
    'crystal_type' => 'none',
    'consume_type' => 'consume_type_stackable',
  ],
  21398 => 
  [
    'item_id' => 21398,
    'icon' => 'br_four_leaf_clover_box_i00',
    'name' => 'Mount - Gold Maned Lion Pack (7-day]',
    'additionalname' => 'Event',
    'description' => 'Wrapped Pack containing Mount - Gold Maned Lion (7-day].',
    'is_trade' => 0,
    'is_drop' => 0,
    'is_destruct' => 1,
    'crystal_type' => 'none',
    'consume_type' => 'consume_type_stackable',
  ],
  21399 => 
  [
    'item_id' => 21399,
    'icon' => 'br_four_leaf_clover_box_i00',
    'name' => 'Mount - Gold Maned Lion Pack (30-day]',
    'additionalname' => '',
    'description' => 'Wrapped Pack containing Mount - Gold Maned Lion (30-day].',
    'is_trade' => 0,
    'is_drop' => 0,
    'is_destruct' => 1,
    'crystal_type' => 'none',
    'consume_type' => 'consume_type_stackable',
  ],
];