<?php return [
  22700 => 
  [
    'item_id' => 22700,
    'icon' => 'g_bless_wp_processing_stone_r',
    'name' => 'Equipment Restoration Stone (R-grade]',
    'additionalname' => '',
    'description' => 'Restores the original appearance of R-grade equipment (only weapons and armor, no hair accessories] whose appearances have been modified. Double-click to use. ',
    'is_trade' => 0,
    'is_drop' => 0,
    'is_destruct' => 1,
    'crystal_type' => 'none',
    'consume_type' => 'consume_type_stackable',
  ],
  22701 => 
  [
    'item_id' => 22701,
    'icon' => 'g_bless_wp_processing_stone_s',
    'name' => 'Equipment Restoration Stone (S-grade]',
    'additionalname' => '',
    'description' => 'Restores the original appearance of S-grade equipment (weapons and armor, no hair accessories] whose appearances have been modified. Double-click to use.',
    'is_trade' => 0,
    'is_drop' => 0,
    'is_destruct' => 1,
    'crystal_type' => 'none',
    'consume_type' => 'consume_type_stackable',
  ],
  22702 => 
  [
    'item_id' => 22702,
    'icon' => 'g_bless_wp_processing_stone_a',
    'name' => 'Equipment Restoration Stone (A-grade]',
    'additionalname' => '',
    'description' => 'Restores the original appearance of A-grade equipment (weapons and armor, no hair accessories] whose appearances have been modified. Double-click to use.',
    'is_trade' => 0,
    'is_drop' => 0,
    'is_destruct' => 1,
    'crystal_type' => 'none',
    'consume_type' => 'consume_type_stackable',
  ],
  22703 => 
  [
    'item_id' => 22703,
    'icon' => 'g_bless_wp_processing_stone_b',
    'name' => 'Equipment Restoration Stone (B-grade]',
    'additionalname' => '',
    'description' => 'Restores the original appearance of B-grade equipment (weapons and armor, no hair accessories] whose appearances have been modified. Double-click to use.',
    'is_trade' => 0,
    'is_drop' => 0,
    'is_destruct' => 1,
    'crystal_type' => 'none',
    'consume_type' => 'consume_type_stackable',
  ],
  22704 => 
  [
    'item_id' => 22704,
    'icon' => 'g_bless_wp_processing_stone_c',
    'name' => 'Equipment Restoration Stone (C-grade]',
    'additionalname' => '',
    'description' => 'Restores the original appearance of C-grade equipment (weapons and armor, no hair accessories] whose appearances have been modified. Double-click to use.',
    'is_trade' => 0,
    'is_drop' => 0,
    'is_destruct' => 1,
    'crystal_type' => 'none',
    'consume_type' => 'consume_type_stackable',
  ],
  22705 => 
  [
    'item_id' => 22705,
    'icon' => 'g_bless_wp_processing_stone_d',
    'name' => 'Equipment Restoration Stone (D-grade]',
    'additionalname' => '',
    'description' => 'Restores the original appearance of D-grade equipment (weapons and armor, no hair accessories] whose appearances have been modified. Double-click to use.',
    'is_trade' => 0,
    'is_drop' => 0,
    'is_destruct' => 1,
    'crystal_type' => 'none',
    'consume_type' => 'consume_type_stackable',
  ],
  22706 => 
  [
    'item_id' => 22706,
    'icon' => 'g_bless_wp_processing_stone_d',
    'name' => '(Test] Formal Wear Appearance Stone',
    'additionalname' => '',
    'description' => 'For test use. Changes whole outfit to formal wear.',
    'is_trade' => 0,
    'is_drop' => 0,
    'is_destruct' => 1,
    'crystal_type' => 'none',
    'consume_type' => 'consume_type_stackable',
  ],
  22707 => 
  [
    'item_id' => 22707,
    'icon' => 'g_bless_wp_processing_stone_d',
    'name' => '(Test] Immortal Top Appearance Stone',
    'additionalname' => '',
    'description' => 'For test use. Top only. Immortal heavy armor.',
    'is_trade' => 0,
    'is_drop' => 0,
    'is_destruct' => 1,
    'crystal_type' => 'none',
    'consume_type' => 'consume_type_stackable',
  ],
  22708 => 
  [
    'item_id' => 22708,
    'icon' => 'g_shape_shifting_hair2_stone',
    'name' => 'Hair Accessory Appearance Stone',
    'additionalname' => '',
    'description' => 'Item that can change a hair accessory\'s appearance. Works for item with the same number of slots. You need an appearance item, which is destroyed after its appearance is extracted. An appearance-modified item has no change in abilities. Double click to use. Consumes 125000 adena for a 1-slot hair accessory and 200000 adena for a 2-slot hair accessory.

Warning: When changed to the appearance of a female-only hair accessory, it cannot be equipped by a male character.',
    'is_trade' => 0,
    'is_drop' => 0,
    'is_destruct' => 1,
    'crystal_type' => 'none',
    'consume_type' => 'consume_type_stackable',
  ],
  22709 => 
  [
    'item_id' => 22709,
    'icon' => 'g_bless_shape_shifting_hair2_stone',
    'name' => 'Blessed Hair Accessory Appearance Stone',
    'additionalname' => '',
    'description' => 'Item that can change a hair accessory\'s appearance. Works for item with the same number of slots. You need an appearance item, which remains intact after its appearance is extracted. An appearance-modified item has no change in abilities. Double click to use.

Warning: When changed to the appearance of a female-only hair accessory, it cannot be equipped by a male character.',
    'is_trade' => 0,
    'is_drop' => 0,
    'is_destruct' => 1,
    'crystal_type' => 'none',
    'consume_type' => 'consume_type_stackable',
  ],
  22710 => 
  [
    'item_id' => 22710,
    'icon' => 'g_vitality_potion_stop',
    'name' => 'Vitality Suspending Potion',
    'additionalname' => '',
    'description' => 'Magic potion that suspends vitality. Vitality consumption stops, but you also cannot receive Vitality bonuses. Cooldown is 30 min.',
    'is_trade' => 0,
    'is_drop' => 0,
    'is_destruct' => 1,
    'crystal_type' => 'none',
    'consume_type' => 'consume_type_stackable',
  ],
  22711 => 
  [
    'item_id' => 22711,
    'icon' => 'g_japan_sword',
    'name' => 'Japanese Sword',
    'additionalname' => '',
    'description' => 'Japanese weapon. One-handed sword form. Basic Japanese Weapon Appearance Stone.',
    'is_trade' => 1,
    'is_drop' => 0,
    'is_destruct' => 1,
    'crystal_type' => 'd',
    'consume_type' => 'consume_type_normal',
  ],
  22712 => 
  [
    'item_id' => 22712,
    'icon' => 'g_japan_dagger',
    'name' => 'Japanese Dagger',
    'additionalname' => '',
    'description' => 'Japanese weapon. Dagger form. Basic Japanese Weapon Appearance Stone.',
    'is_trade' => 1,
    'is_drop' => 0,
    'is_destruct' => 1,
    'crystal_type' => 'd',
    'consume_type' => 'consume_type_normal',
  ],
  22713 => 
  [
    'item_id' => 22713,
    'icon' => 'g_japan_twohand_sword',
    'name' => 'Japanese Long Sword',
    'additionalname' => '',
    'description' => 'Japanese weapon. Two-handed sword form. Basic Japanese Weapon Appearance Stone.',
    'is_trade' => 1,
    'is_drop' => 0,
    'is_destruct' => 1,
    'crystal_type' => 'd',
    'consume_type' => 'consume_type_normal',
  ],
  22714 => 
  [
    'item_id' => 22714,
    'icon' => 'g_japan_dualfist',
    'name' => 'Japanese Fist Weapon',
    'additionalname' => '',
    'description' => 'Japanese weapon. Fist weapon form. Basic Japanese Weapon Appearance Stone.',
    'is_trade' => 1,
    'is_drop' => 0,
    'is_destruct' => 1,
    'crystal_type' => 'd',
    'consume_type' => 'consume_type_normal',
  ],
  22715 => 
  [
    'item_id' => 22715,
    'icon' => 'g_japan_pole',
    'name' => 'Japanese Great Spear',
    'additionalname' => '',
    'description' => 'Japanese weapon. Spear form. Basic Japanese Weapon Appearance Stone.',
    'is_trade' => 1,
    'is_drop' => 0,
    'is_destruct' => 1,
    'crystal_type' => 'd',
    'consume_type' => 'consume_type_normal',
  ],
  22716 => 
  [
    'item_id' => 22716,
    'icon' => 'g_japan_bow',
    'name' => 'Japanese Bow',
    'additionalname' => '',
    'description' => 'Japanese weapon. Bow form. Basic Japanese Weapon Appearance Stone.',
    'is_trade' => 1,
    'is_drop' => 0,
    'is_destruct' => 1,
    'crystal_type' => 'd',
    'consume_type' => 'consume_type_normal',
  ],
  22717 => 
  [
    'item_id' => 22717,
    'icon' => 'g_japan_twohand_crossbow',
    'name' => 'Japanese Crossbow',
    'additionalname' => '',
    'description' => 'Japanese weapon. Crossbow form. Basic Japanese Weapon Appearance Stone.',
    'is_trade' => 1,
    'is_drop' => 0,
    'is_destruct' => 1,
    'crystal_type' => 'd',
    'consume_type' => 'consume_type_normal',
  ],
  22718 => 
  [
    'item_id' => 22718,
    'icon' => 'g_japan_blunt',
    'name' => 'Japanese Blunt Weapon',
    'additionalname' => '',
    'description' => 'Japanese weapon. One-handed blunt form. Basic Japanese Weapon Appearance Stone.',
    'is_trade' => 1,
    'is_drop' => 0,
    'is_destruct' => 1,
    'crystal_type' => 'd',
    'consume_type' => 'consume_type_normal',
  ],
  22719 => 
  [
    'item_id' => 22719,
    'icon' => 'g_japan_twohand_blunt',
    'name' => 'Japanese Giant Blunt Weapon',
    'additionalname' => '',
    'description' => 'Japanese weapon. Two-handed blunt form. Basic Japanese Weapon Appearance Stone.',
    'is_trade' => 1,
    'is_drop' => 0,
    'is_destruct' => 1,
    'crystal_type' => 'd',
    'consume_type' => 'consume_type_normal',
  ],
  22720 => 
  [
    'item_id' => 22720,
    'icon' => 'g_japan_magic_blunt',
    'name' => 'Japanese Magic Blunt Weapon',
    'additionalname' => '',
    'description' => 'Japanese weapon. One-handed magic blunt form. Basic Japanese Weapon Appearance Stone.',
    'is_trade' => 1,
    'is_drop' => 0,
    'is_destruct' => 1,
    'crystal_type' => 'd',
    'consume_type' => 'consume_type_normal',
  ],
  22721 => 
  [
    'item_id' => 22721,
    'icon' => 'g_japan_magic_twohand_blunt',
    'name' => 'Japanese Giant Magic Blunt Weapon',
    'additionalname' => '',
    'description' => 'Japanese weapon. Two-handed magic blunt form. Basic Japanese Weapon Appearance Stone.',
    'is_trade' => 1,
    'is_drop' => 0,
    'is_destruct' => 1,
    'crystal_type' => 'd',
    'consume_type' => 'consume_type_normal',
  ],
  22722 => 
  [
    'item_id' => 22722,
    'icon' => 'g_japan_dual',
    'name' => 'Japanese Dualsword',
    'additionalname' => '',
    'description' => 'Japanese weapon. Dualsword form. Basic Japanese Weapon Appearance Stone.',
    'is_trade' => 1,
    'is_drop' => 0,
    'is_destruct' => 1,
    'crystal_type' => 'd',
    'consume_type' => 'consume_type_normal',
  ],
  22723 => 
  [
    'item_id' => 22723,
    'icon' => 'g_japan_dualdagger',
    'name' => 'Japanese Double Dagger',
    'additionalname' => '',
    'description' => 'Japanese weapon. Dual dagger form. Basic Japanese Weapon Appearance Stone.',
    'is_trade' => 1,
    'is_drop' => 0,
    'is_destruct' => 1,
    'crystal_type' => 'd',
    'consume_type' => 'consume_type_normal',
  ],
  22724 => 
  [
    'item_id' => 22724,
    'icon' => 'g_japan_dualblunt',
    'name' => 'Japanese Double Blunt Weapon',
    'additionalname' => '',
    'description' => 'Japanese weapon. Dual blunt form. Basic Japanese Weapon Appearance Stone.',
    'is_trade' => 1,
    'is_drop' => 0,
    'is_destruct' => 1,
    'crystal_type' => 'd',
    'consume_type' => 'consume_type_normal',
  ],
  22725 => 
  [
    'item_id' => 22725,
    'icon' => 'g_japan_shield',
    'name' => 'Japanese Shield',
    'additionalname' => '',
    'description' => 'Japanese weapon. Shield form. Basic Japanese Weapon Appearance Stone.',
    'is_trade' => 1,
    'is_drop' => 0,
    'is_destruct' => 1,
    'crystal_type' => 'd',
    'consume_type' => 'consume_type_normal',
  ],
  22726 => 
  [
    'item_id' => 22726,
    'icon' => 'g_japan_sigil',
    'name' => 'Japanese Sigil',
    'additionalname' => '',
    'description' => 'Japanese weapon. Sigil form. Basic Japanese Weapon Appearance Stone.',
    'is_trade' => 1,
    'is_drop' => 0,
    'is_destruct' => 1,
    'crystal_type' => 'd',
    'consume_type' => 'consume_type_normal',
  ],
  22727 => 
  [
    'item_id' => 22727,
    'icon' => 'g_shape_shifting_sword',
    'name' => 'Japanese Sword Appearance Stone',
    'additionalname' => '',
    'description' => 'Changes the appearance of a one-handed sword to that of a Japanese Sword.',
    'is_trade' => 0,
    'is_drop' => 0,
    'is_destruct' => 1,
    'crystal_type' => 'none',
    'consume_type' => 'consume_type_stackable',
  ],
  22728 => 
  [
    'item_id' => 22728,
    'icon' => 'g_shape_shifting_dagger',
    'name' => 'Japanese Dagger Appearance Stone',
    'additionalname' => '',
    'description' => 'Changes the appearance of a dagger to that of a Japanese Dagger.',
    'is_trade' => 0,
    'is_drop' => 0,
    'is_destruct' => 1,
    'crystal_type' => 'none',
    'consume_type' => 'consume_type_stackable',
  ],
  22729 => 
  [
    'item_id' => 22729,
    'icon' => 'g_shape_shifting_twohand_sword',
    'name' => 'Japanese Long Sword Appearance Stone',
    'additionalname' => '',
    'description' => 'Changes the appearance of a two-handed sword to that of a Japanese Long Sword.',
    'is_trade' => 0,
    'is_drop' => 0,
    'is_destruct' => 1,
    'crystal_type' => 'none',
    'consume_type' => 'consume_type_stackable',
  ],
  22730 => 
  [
    'item_id' => 22730,
    'icon' => 'g_shape_shifting_dualfist',
    'name' => 'Japanese Fist Weapon Appearance Stone',
    'additionalname' => '',
    'description' => 'Changes the appearance of a fist weapon to that of a Japanese fist weapon.',
    'is_trade' => 0,
    'is_drop' => 0,
    'is_destruct' => 1,
    'crystal_type' => 'none',
    'consume_type' => 'consume_type_stackable',
  ],
  22731 => 
  [
    'item_id' => 22731,
    'icon' => 'g_shape_shifting_pole',
    'name' => 'Japanese Great Spear Appearance Stone',
    'additionalname' => '',
    'description' => 'Changes the appearance of a spear to that of a Japanese Great Spear.',
    'is_trade' => 0,
    'is_drop' => 0,
    'is_destruct' => 1,
    'crystal_type' => 'none',
    'consume_type' => 'consume_type_stackable',
  ],
  22732 => 
  [
    'item_id' => 22732,
    'icon' => 'g_shape_shifting_bow',
    'name' => 'Japanese Bow Appearance Stone',
    'additionalname' => '',
    'description' => 'Changes the appearance of a bow to that of a Japanese Bow.',
    'is_trade' => 0,
    'is_drop' => 0,
    'is_destruct' => 1,
    'crystal_type' => 'none',
    'consume_type' => 'consume_type_stackable',
  ],
  22733 => 
  [
    'item_id' => 22733,
    'icon' => 'g_shape_shifting_twohand_crossbow',
    'name' => 'Japanese Crossbow Appearance Stone',
    'additionalname' => '',
    'description' => 'Changes the appearance of a crossbow to that of a Japanese crossbow.',
    'is_trade' => 0,
    'is_drop' => 0,
    'is_destruct' => 1,
    'crystal_type' => 'none',
    'consume_type' => 'consume_type_stackable',
  ],
  22734 => 
  [
    'item_id' => 22734,
    'icon' => 'g_shape_shifting_blunt',
    'name' => 'Japanese Blunt Appearance Stone',
    'additionalname' => '',
    'description' => 'Changes the appearance of a one-handed blunt to that of a Japanese blunt.',
    'is_trade' => 0,
    'is_drop' => 0,
    'is_destruct' => 1,
    'crystal_type' => 'none',
    'consume_type' => 'consume_type_stackable',
  ],
  22735 => 
  [
    'item_id' => 22735,
    'icon' => 'g_shape_shifting_twohand_blunt',
    'name' => 'Japanese Giant Blunt Appearance Stone',
    'additionalname' => '',
    'description' => 'Changes the appearance of a two-handed blunt to that of a Japanese blunt.',
    'is_trade' => 0,
    'is_drop' => 0,
    'is_destruct' => 1,
    'crystal_type' => 'none',
    'consume_type' => 'consume_type_stackable',
  ],
  22736 => 
  [
    'item_id' => 22736,
    'icon' => 'g_shape_shifting_magic_blunt',
    'name' => 'Japanese Magic Blunt Appearance Stone',
    'additionalname' => '',
    'description' => 'Changes the appearance of a one-handed magic blunt to that of a Japanese magic blunt.',
    'is_trade' => 0,
    'is_drop' => 0,
    'is_destruct' => 1,
    'crystal_type' => 'none',
    'consume_type' => 'consume_type_stackable',
  ],
  22737 => 
  [
    'item_id' => 22737,
    'icon' => 'g_shape_shifting_magic_twohand_blunt',
    'name' => 'Japanese Giant Magic Blunt Appearance Stone',
    'additionalname' => '',
    'description' => 'Changes the appearance of a two-handed magic blunt to that of a Japanese giant magic blunt.',
    'is_trade' => 0,
    'is_drop' => 0,
    'is_destruct' => 1,
    'crystal_type' => 'none',
    'consume_type' => 'consume_type_stackable',
  ],
  22738 => 
  [
    'item_id' => 22738,
    'icon' => 'g_shape_shifting_dual',
    'name' => 'Japanese Dualsword Appearance Stone',
    'additionalname' => '',
    'description' => 'Changes the appearance of a dualsword to that of a Japanese dualsword.',
    'is_trade' => 0,
    'is_drop' => 0,
    'is_destruct' => 1,
    'crystal_type' => 'none',
    'consume_type' => 'consume_type_stackable',
  ],
  22739 => 
  [
    'item_id' => 22739,
    'icon' => 'g_shape_shifting_dualdagger',
    'name' => 'Japanese Double Dagger Appearance Stone',
    'additionalname' => '',
    'description' => 'Changes the appearance of a dual dagger to that of a Japanese Double Dagger.',
    'is_trade' => 0,
    'is_drop' => 0,
    'is_destruct' => 1,
    'crystal_type' => 'none',
    'consume_type' => 'consume_type_stackable',
  ],
  22740 => 
  [
    'item_id' => 22740,
    'icon' => 'g_shape_shifting_dualblunt',
    'name' => 'Japanese Double Blunt Appearance Stone',
    'additionalname' => '',
    'description' => 'Changes the appearance of a dual blunt to that of a Japanese double blunt.',
    'is_trade' => 0,
    'is_drop' => 0,
    'is_destruct' => 1,
    'crystal_type' => 'none',
    'consume_type' => 'consume_type_stackable',
  ],
  22741 => 
  [
    'item_id' => 22741,
    'icon' => 'g_shape_shifting_shield',
    'name' => 'Japanese Shield Appearance Stone',
    'additionalname' => '',
    'description' => 'Changes the appearance of a shield to that of a Japanese shield.',
    'is_trade' => 0,
    'is_drop' => 0,
    'is_destruct' => 1,
    'crystal_type' => 'none',
    'consume_type' => 'consume_type_stackable',
  ],
  22742 => 
  [
    'item_id' => 22742,
    'icon' => 'g_shape_shifting_sigil',
    'name' => 'Japanese Sigil Appearance Stone',
    'additionalname' => '',
    'description' => 'Changes the appearance of a sigil to that of a Japanese sigil.',
    'is_trade' => 0,
    'is_drop' => 0,
    'is_destruct' => 1,
    'crystal_type' => 'none',
    'consume_type' => 'consume_type_stackable',
  ],
  22743 => 
  [
    'item_id' => 22743,
    'icon' => 'etc_trans_4f_s_b_01',
    'name' => 'Transformation Scroll: Fairweather Borna',
    'additionalname' => '',
    'description' => 'For 30 min., transform into a Fairweather Borna, who has the abilities of the Feoh Wizard and Aeore Healer and can also use the Escape: Clan Hall skill. Lv. 80 or above.',
    'is_trade' => 0,
    'is_drop' => 0,
    'is_destruct' => 1,
    'crystal_type' => 'none',
    'consume_type' => 'consume_type_stackable',
  ],
  22744 => 
  [
    'item_id' => 22744,
    'icon' => 'br_four_leaf_clover_box_i00',
    'name' => 'Vitality Suspending Potion Pack',
    'additionalname' => '',
    'description' => 'Wrapped Pack containing Vitality Suspending Potion. ',
    'is_trade' => 0,
    'is_drop' => 0,
    'is_destruct' => 1,
    'crystal_type' => 'none',
    'consume_type' => 'consume_type_stackable',
  ],
  22745 => 
  [
    'item_id' => 22745,
    'icon' => 'g_scrl_vitality_count_up',
    'name' => 'Scroll: Increase Vitality',
    'additionalname' => '',
    'description' => 'Increases the number of Vitality items that can be used per week by 1. Cooldown is 3 days.',
    'is_trade' => 0,
    'is_drop' => 0,
    'is_destruct' => 1,
    'crystal_type' => 'none',
    'consume_type' => 'consume_type_stackable',
  ],
  22746 => 
  [
    'item_id' => 22746,
    'icon' => 'br_four_leaf_clover_box_i00',
    'name' => 'Scroll: Increase Vitality Pack',
    'additionalname' => '',
    'description' => 'Wrapped Pack containing Scroll: increase Vitality.',
    'is_trade' => 0,
    'is_drop' => 0,
    'is_destruct' => 1,
    'crystal_type' => 'none',
    'consume_type' => 'consume_type_stackable',
  ],
  22747 => 
  [
    'item_id' => 22747,
    'icon' => 'g_scrl_vitality_count_up_2',
    'name' => 'Scroll: Increase Vitality (High-grade]',
    'additionalname' => '',
    'description' => 'Increases the number of Vitality items that can be used per week by 2. Cooldown is 3 days.',
    'is_trade' => 0,
    'is_drop' => 0,
    'is_destruct' => 1,
    'crystal_type' => 'none',
    'consume_type' => 'consume_type_stackable',
  ],
  22748 => 
  [
    'item_id' => 22748,
    'icon' => 'br_four_leaf_clover_box_i00',
    'name' => 'Scroll: Increase Vitality Pack (High-grade] ',
    'additionalname' => '',
    'description' => 'Wrapped Pack containing Scroll: increase Vitality (High-grade].',
    'is_trade' => 0,
    'is_drop' => 0,
    'is_destruct' => 1,
    'crystal_type' => 'none',
    'consume_type' => 'consume_type_stackable',
  ],
  22749 => 
  [
    'item_id' => 22749,
    'icon' => 'g_scrl_vitality_count_up_3',
    'name' => 'Scroll: Increase Vitality (Top-grade]',
    'additionalname' => '',
    'description' => 'Increases the number of Vitality items that can be used per week by 3. Cooldown is 3 days.',
    'is_trade' => 0,
    'is_drop' => 0,
    'is_destruct' => 1,
    'crystal_type' => 'none',
    'consume_type' => 'consume_type_stackable',
  ],
  22750 => 
  [
    'item_id' => 22750,
    'icon' => 'br_four_leaf_clover_box_i00',
    'name' => 'Scroll: Increase Vitality Pack (Top-grade]',
    'additionalname' => '',
    'description' => 'Wrapped Pack containing Scroll: increase Vitality (Top-grade].',
    'is_trade' => 0,
    'is_drop' => 0,
    'is_destruct' => 1,
    'crystal_type' => 'none',
    'consume_type' => 'consume_type_stackable',
  ],
  22751 => 
  [
    'item_id' => 22751,
    'icon' => 'g_rune_itemdrop_up',
    'name' => 'Drop Rate Rune 30% (3-hour]',
    'additionalname' => '',
    'description' => 'When stored in the inventory, item acquisition through hunting + 30%.',
    'is_trade' => 0,
    'is_drop' => 0,
    'is_destruct' => 1,
    'crystal_type' => 'none',
    'consume_type' => 'consume_type_normal',
  ],
  22752 => 
  [
    'item_id' => 22752,
    'icon' => 'g_rune_itemdrop_up',
    'name' => 'Drop Rate Rune 30% (5-hour]',
    'additionalname' => '',
    'description' => 'When stored in the inventory, item acquisition through hunting + 30%.',
    'is_trade' => 0,
    'is_drop' => 0,
    'is_destruct' => 1,
    'crystal_type' => 'none',
    'consume_type' => 'consume_type_normal',
  ],
  22753 => 
  [
    'item_id' => 22753,
    'icon' => 'g_rune_itemdrop_up',
    'name' => 'Drop Rate Rune 30% (7-day]',
    'additionalname' => '',
    'description' => 'When stored in the inventory, item acquisition through hunting + 30%.',
    'is_trade' => 0,
    'is_drop' => 0,
    'is_destruct' => 1,
    'crystal_type' => 'none',
    'consume_type' => 'consume_type_normal',
  ],
  22754 => 
  [
    'item_id' => 22754,
    'icon' => 'g_rune_itemdrop_up',
    'name' => 'Drop Rate Rune 50% (3-hour]',
    'additionalname' => '',
    'description' => 'When stored in the inventory, item acquisition through hunting + 50%.',
    'is_trade' => 0,
    'is_drop' => 0,
    'is_destruct' => 1,
    'crystal_type' => 'none',
    'consume_type' => 'consume_type_normal',
  ],
  22755 => 
  [
    'item_id' => 22755,
    'icon' => 'g_rune_itemdrop_up',
    'name' => 'Drop Rate Rune 50% (5-hour]',
    'additionalname' => '',
    'description' => 'When stored in the inventory, item acquisition through hunting + 50%.',
    'is_trade' => 0,
    'is_drop' => 0,
    'is_destruct' => 1,
    'crystal_type' => 'none',
    'consume_type' => 'consume_type_normal',
  ],
  22756 => 
  [
    'item_id' => 22756,
    'icon' => 'g_rune_itemdrop_up',
    'name' => 'Drop Rate Rune 50% (7-day]',
    'additionalname' => '',
    'description' => 'When stored in the inventory, item acquisition through hunting + 50%.',
    'is_trade' => 0,
    'is_drop' => 0,
    'is_destruct' => 1,
    'crystal_type' => 'none',
    'consume_type' => 'consume_type_normal',
  ],
  22757 => 
  [
    'item_id' => 22757,
    'icon' => 'g_rune_itemdrop_up',
    'name' => 'Drop Rate Rune 100% (3-hour]',
    'additionalname' => '',
    'description' => 'When stored in the inventory, item acquisition through hunting + 100%.',
    'is_trade' => 0,
    'is_drop' => 0,
    'is_destruct' => 1,
    'crystal_type' => 'none',
    'consume_type' => 'consume_type_normal',
  ],
  22758 => 
  [
    'item_id' => 22758,
    'icon' => 'g_rune_itemdrop_up',
    'name' => 'Drop Rate Rune 100% (5-hour]',
    'additionalname' => '',
    'description' => 'When stored in the inventory, item acquisition through hunting + 100%.',
    'is_trade' => 0,
    'is_drop' => 0,
    'is_destruct' => 1,
    'crystal_type' => 'none',
    'consume_type' => 'consume_type_normal',
  ],
  22759 => 
  [
    'item_id' => 22759,
    'icon' => 'g_rune_itemdrop_up',
    'name' => 'Drop Rate Rune 100% (7-day]',
    'additionalname' => '',
    'description' => 'When stored in the inventory, item acquisition through hunting + 100%.',
    'is_trade' => 0,
    'is_drop' => 0,
    'is_destruct' => 1,
    'crystal_type' => 'none',
    'consume_type' => 'consume_type_normal',
  ],
  22760 => 
  [
    'item_id' => 22760,
    'icon' => 'g_rune_itemdrop_up',
    'name' => 'Drop Rate Rune 200% (3-hour]',
    'additionalname' => '',
    'description' => 'When stored in the inventory, item acquisition through hunting + 200%.',
    'is_trade' => 0,
    'is_drop' => 0,
    'is_destruct' => 1,
    'crystal_type' => 'none',
    'consume_type' => 'consume_type_normal',
  ],
  22761 => 
  [
    'item_id' => 22761,
    'icon' => 'g_rune_itemdrop_up',
    'name' => 'Drop Rate Rune 200% (5-hour]',
    'additionalname' => '',
    'description' => 'When stored in the inventory, item acquisition through hunting + 200%.',
    'is_trade' => 0,
    'is_drop' => 0,
    'is_destruct' => 1,
    'crystal_type' => 'none',
    'consume_type' => 'consume_type_normal',
  ],
  22762 => 
  [
    'item_id' => 22762,
    'icon' => 'g_rune_itemdrop_up',
    'name' => 'Drop Rate Rune 200% (7-day]',
    'additionalname' => '',
    'description' => 'When stored in the inventory, item acquisition through hunting + 200%.',
    'is_trade' => 0,
    'is_drop' => 0,
    'is_destruct' => 1,
    'crystal_type' => 'none',
    'consume_type' => 'consume_type_normal',
  ],
  22763 => 
  [
    'item_id' => 22763,
    'icon' => 'etc_pi_gift_box_i00',
    'name' => 'Drop Rate Rune 30% Pack (3-hour]',
    'additionalname' => '',
    'description' => 'Wrapped Pack containing Drop Rate Rune 30% (3-hour].',
    'is_trade' => 0,
    'is_drop' => 0,
    'is_destruct' => 1,
    'crystal_type' => 'none',
    'consume_type' => 'consume_type_stackable',
  ],
  22764 => 
  [
    'item_id' => 22764,
    'icon' => 'etc_pi_gift_box_i00',
    'name' => 'Drop Rate Rune 30% Pack (5-hour]',
    'additionalname' => '',
    'description' => 'Wrapped Pack containing Drop Rate Rune 30% (5-hour].',
    'is_trade' => 0,
    'is_drop' => 0,
    'is_destruct' => 1,
    'crystal_type' => 'none',
    'consume_type' => 'consume_type_stackable',
  ],
  22765 => 
  [
    'item_id' => 22765,
    'icon' => 'etc_pi_gift_box_i00',
    'name' => 'Drop Rate Rune 30% Pack (7-day]',
    'additionalname' => '',
    'description' => 'Wrapped Pack containing Drop Rate Rune 30% (7-day.',
    'is_trade' => 0,
    'is_drop' => 0,
    'is_destruct' => 1,
    'crystal_type' => 'none',
    'consume_type' => 'consume_type_stackable',
  ],
  22766 => 
  [
    'item_id' => 22766,
    'icon' => 'etc_pi_gift_box_i00',
    'name' => 'Drop Rate Rune 50% Pack (3-hour]',
    'additionalname' => '',
    'description' => 'Wrapped Pack containing Drop Rate Rune 50% (3-hour].',
    'is_trade' => 0,
    'is_drop' => 0,
    'is_destruct' => 1,
    'crystal_type' => 'none',
    'consume_type' => 'consume_type_stackable',
  ],
  22767 => 
  [
    'item_id' => 22767,
    'icon' => 'etc_pi_gift_box_i00',
    'name' => 'Drop Rate Rune 50% Pack (5-hour]',
    'additionalname' => '',
    'description' => 'Wrapped Pack containing Drop Rate Rune 50% (5-hour].',
    'is_trade' => 0,
    'is_drop' => 0,
    'is_destruct' => 1,
    'crystal_type' => 'none',
    'consume_type' => 'consume_type_stackable',
  ],
  22768 => 
  [
    'item_id' => 22768,
    'icon' => 'etc_pi_gift_box_i00',
    'name' => 'Drop Rate Rune 50% Pack (7-day]',
    'additionalname' => '',
    'description' => 'Wrapped Pack containing Drop Rate Rune 50% (7-day.',
    'is_trade' => 0,
    'is_drop' => 0,
    'is_destruct' => 1,
    'crystal_type' => 'none',
    'consume_type' => 'consume_type_stackable',
  ],
  22769 => 
  [
    'item_id' => 22769,
    'icon' => 'etc_pi_gift_box_i00',
    'name' => 'Drop Rate Rune 100% Pack (3-hour]',
    'additionalname' => '',
    'description' => 'Wrapped Pack containing Drop Rate Rune 100% (3-hour].',
    'is_trade' => 0,
    'is_drop' => 0,
    'is_destruct' => 1,
    'crystal_type' => 'none',
    'consume_type' => 'consume_type_stackable',
  ],
  22770 => 
  [
    'item_id' => 22770,
    'icon' => 'etc_pi_gift_box_i00',
    'name' => 'Drop Rate Rune 100% Pack (5-hour]',
    'additionalname' => '',
    'description' => 'Wrapped Pack containing Drop Rate Rune 100% (5-hour].',
    'is_trade' => 0,
    'is_drop' => 0,
    'is_destruct' => 1,
    'crystal_type' => 'none',
    'consume_type' => 'consume_type_stackable',
  ],
  22771 => 
  [
    'item_id' => 22771,
    'icon' => 'etc_pi_gift_box_i00',
    'name' => 'Drop Rate Rune 100% Pack (7-day]',
    'additionalname' => '',
    'description' => 'Wrapped Pack containing Drop Rate Rune 100% (7-day.',
    'is_trade' => 0,
    'is_drop' => 0,
    'is_destruct' => 1,
    'crystal_type' => 'none',
    'consume_type' => 'consume_type_stackable',
  ],
  22772 => 
  [
    'item_id' => 22772,
    'icon' => 'etc_pi_gift_box_i00',
    'name' => 'Drop Rate Rune 200% Pack (3-hour]',
    'additionalname' => '',
    'description' => 'Wrapped Pack containing Drop Rate Rune 200% (3-hour].',
    'is_trade' => 0,
    'is_drop' => 0,
    'is_destruct' => 1,
    'crystal_type' => 'none',
    'consume_type' => 'consume_type_stackable',
  ],
  22773 => 
  [
    'item_id' => 22773,
    'icon' => 'etc_pi_gift_box_i00',
    'name' => 'Drop Rate Rune 200% Pack (5-hour]',
    'additionalname' => '',
    'description' => 'Wrapped Pack containing Drop Rate Rune 200% (5-hour].',
    'is_trade' => 0,
    'is_drop' => 0,
    'is_destruct' => 1,
    'crystal_type' => 'none',
    'consume_type' => 'consume_type_stackable',
  ],
  22774 => 
  [
    'item_id' => 22774,
    'icon' => 'etc_pi_gift_box_i00',
    'name' => 'Drop Rate Rune 200% Pack (7-day]',
    'additionalname' => '',
    'description' => 'Wrapped Pack containing Drop Rate Rune 200% (7-day].',
    'is_trade' => 0,
    'is_drop' => 0,
    'is_destruct' => 1,
    'crystal_type' => 'none',
    'consume_type' => 'consume_type_stackable',
  ],
  22775 => 
  [
    'item_id' => 22775,
    'icon' => 'g_drake_maul_i00',
    'name' => 'Drake Maul',
    'additionalname' => '',
    'description' => 'Two-handed blunt with special powers used by the Drake Lord. Can bestow 1 regular Soul Crystal and 1 Special Soul Crystal.',
    'is_trade' => 1,
    'is_drop' => 1,
    'is_destruct' => 1,
    'crystal_type' => 's80',
    'consume_type' => 'consume_type_normal',
  ],
  22776 => 
  [
    'item_id' => 22776,
    'icon' => 'g_drake_maul_i01',
    'name' => 'Not used',
    'additionalname' => 'Not used',
    'description' => 'Not used',
    'is_trade' => 1,
    'is_drop' => 1,
    'is_destruct' => 1,
    'crystal_type' => 's80',
    'consume_type' => 'consume_type_normal',
  ],
  22777 => 
  [
    'item_id' => 22777,
    'icon' => 'g_drake_maul_i01',
    'name' => 'Not used',
    'additionalname' => 'Not used',
    'description' => 'Not used',
    'is_trade' => 1,
    'is_drop' => 1,
    'is_destruct' => 1,
    'crystal_type' => 's80',
    'consume_type' => 'consume_type_normal',
  ],
  22778 => 
  [
    'item_id' => 22778,
    'icon' => 'g_drake_maul_i01',
    'name' => 'Not used',
    'additionalname' => 'Not used',
    'description' => 'Not used',
    'is_trade' => 1,
    'is_drop' => 1,
    'is_destruct' => 1,
    'crystal_type' => 's80',
    'consume_type' => 'consume_type_normal',
  ],
  22779 => 
  [
    'item_id' => 22779,
    'icon' => 'g_drake_maul_i00',
    'name' => 'Drake Maul (PvP]',
    'additionalname' => '',
    'description' => 'Two-handed blunt with special powers used by the Drake Lord. Increases damage inflicted during PvP. Has a chance of recovering CP during an attack. 
No Soul Crystal option.',
    'is_trade' => 0,
    'is_drop' => 0,
    'is_destruct' => 1,
    'crystal_type' => 's80',
    'consume_type' => 'consume_type_normal',
  ],
  22780 => 
  [
    'item_id' => 22780,
    'icon' => 'g_drake_maul_i01',
    'name' => 'Drake Maul (PvP] - HP Drain',
    'additionalname' => '',
    'description' => '<Special Option>
Two-handed blunt with special powers used by the Drake Lord. Absorbs 4% of standard melee damage inflicted upon the enemy as HP. Increases damage inflicted during PvP. Has a chance of inflicting additional damage when attacking.
No Soul Crystal option.',
    'is_trade' => 0,
    'is_drop' => 0,
    'is_destruct' => 1,
    'crystal_type' => 's80',
    'consume_type' => 'consume_type_normal',
  ],
  22781 => 
  [
    'item_id' => 22781,
    'icon' => 'g_drake_maul_i01',
    'name' => 'Drake Maul (PvP] - HP Regeneration',
    'additionalname' => '',
    'description' => '<Special Option>
Two-handed blunt with special powers used by the Drake Lord. Increases HP Recovery Rate. Increases damage inflicted during PvP. Has a chance of inflicting additional damage when attacking.
No Soul Crystal option.',
    'is_trade' => 0,
    'is_drop' => 0,
    'is_destruct' => 1,
    'crystal_type' => 's80',
    'consume_type' => 'consume_type_normal',
  ],
  22782 => 
  [
    'item_id' => 22782,
    'icon' => 'g_drake_maul_i01',
    'name' => 'Drake Maul (PvP] - Health',
    'additionalname' => '',
    'description' => '<Special Option>
Two-handed blunt with special powers used by the Drake Lord. Max HP increases by 25%. Increases damage inflicted during PvP. Has a chance of inflicting additional damage when attacking.
No Soul Crystal option.',
    'is_trade' => 0,
    'is_drop' => 0,
    'is_destruct' => 1,
    'crystal_type' => 's80',
    'consume_type' => 'consume_type_normal',
  ],
  22783 => 
  [
    'item_id' => 22783,
    'icon' => 'g_drake_maul_i00',
    'name' => 'Drake Maul - Evil Spirit',
    'additionalname' => '',
    'description' => 'Masterwork Item with chance of HP absorption during an attack.
Can bestow 1 regular Soul Crystal and 1 Special Soul Crystal.',
    'is_trade' => 1,
    'is_drop' => 1,
    'is_destruct' => 1,
    'crystal_type' => 's80',
    'consume_type' => 'consume_type_normal',
  ],
  22784 => 
  [
    'item_id' => 22784,
    'icon' => 'g_drake_maul_i01',
    'name' => 'Not used',
    'additionalname' => 'Not used',
    'description' => 'Not used',
    'is_trade' => 1,
    'is_drop' => 1,
    'is_destruct' => 1,
    'crystal_type' => 's80',
    'consume_type' => 'consume_type_normal',
  ],
  22785 => 
  [
    'item_id' => 22785,
    'icon' => 'g_drake_maul_i01',
    'name' => 'Not used',
    'additionalname' => 'Not used',
    'description' => 'Not used',
    'is_trade' => 1,
    'is_drop' => 1,
    'is_destruct' => 1,
    'crystal_type' => 's80',
    'consume_type' => 'consume_type_normal',
  ],
  22786 => 
  [
    'item_id' => 22786,
    'icon' => 'g_drake_maul_i01',
    'name' => 'Not used',
    'additionalname' => 'Not used',
    'description' => 'Not used',
    'is_trade' => 1,
    'is_drop' => 1,
    'is_destruct' => 1,
    'crystal_type' => 's80',
    'consume_type' => 'consume_type_normal',
  ],
  22787 => 
  [
    'item_id' => 22787,
    'icon' => 'g_drake_maul_i00',
    'name' => 'Drake Maul - Evil Spirit (PvP]',
    'additionalname' => '',
    'description' => 'Masterwork Item with chance of HP absorption during an attack.
Increases damage inflicted during PvP. Has a chance of recovering CP during an attack.
No Soul Crystal option.',
    'is_trade' => 0,
    'is_drop' => 0,
    'is_destruct' => 1,
    'crystal_type' => 's80',
    'consume_type' => 'consume_type_normal',
  ],
  22788 => 
  [
    'item_id' => 22788,
    'icon' => 'g_drake_maul_i01',
    'name' => 'Drake Maul - Evil Spirit (PvP] - HP Drain',
    'additionalname' => '',
    'description' => 'Masterwork Item with chance of HP absorption during an attack
<Special Option>
Two-handed blunt with special powers used by the Drake Lord. Recovers 4% of standard melee physical damage inflicted upon the enemy as HP. Increases damage inflicted during PvP. Has a chance of inflicting additional damage when attacking.
No Soul Crystal option.',
    'is_trade' => 0,
    'is_drop' => 0,
    'is_destruct' => 1,
    'crystal_type' => 's80',
    'consume_type' => 'consume_type_normal',
  ],
  22789 => 
  [
    'item_id' => 22789,
    'icon' => 'g_drake_maul_i01',
    'name' => 'Drake Maul - Evil Spirit (PvP] - HP Regeneration',
    'additionalname' => '',
    'description' => 'Masterwork Item with chance of HP absorption during an attack
<Special Option>
Two-handed blunt with special powers used by the Drake Lord. Increases HP Recovery Rate. Increases damage inflicted during PvP. Has a chance of inflicting additional damage when attacking.
No Soul Crystal option.',
    'is_trade' => 0,
    'is_drop' => 0,
    'is_destruct' => 1,
    'crystal_type' => 's80',
    'consume_type' => 'consume_type_normal',
  ],
  22790 => 
  [
    'item_id' => 22790,
    'icon' => 'g_drake_maul_i01',
    'name' => 'Drake Maul - Evil Spirit (PvP] - Health',
    'additionalname' => '',
    'description' => 'Masterwork Item with chance of HP absorption during an attack
<Special Option>
Two-handed blunt with special powers used by the Drake Lord. Max HP increases by 25%. Increases damage inflicted during PvP. Has a chance of inflicting additional damage when attacking.
No Soul Crystal option.',
    'is_trade' => 0,
    'is_drop' => 0,
    'is_destruct' => 1,
    'crystal_type' => 's80',
    'consume_type' => 'consume_type_normal',
  ],
  22791 => 
  [
    'item_id' => 22791,
    'icon' => 'g_glacierin_i00',
    'name' => 'Freya\'s Staff',
    'additionalname' => '',
    'description' => 'Two-handed magic blunt with special powers used by Freya. Can bestow 1 regular Soul Crystal and 1 Special Soul Crystal.',
    'is_trade' => 1,
    'is_drop' => 1,
    'is_destruct' => 1,
    'crystal_type' => 's80',
    'consume_type' => 'consume_type_normal',
  ],
  22792 => 
  [
    'item_id' => 22792,
    'icon' => 'g_glacierin_i01',
    'name' => 'Not used',
    'additionalname' => 'Not used',
    'description' => 'Not used',
    'is_trade' => 1,
    'is_drop' => 1,
    'is_destruct' => 1,
    'crystal_type' => 's80',
    'consume_type' => 'consume_type_normal',
  ],
  22793 => 
  [
    'item_id' => 22793,
    'icon' => 'g_glacierin_i01',
    'name' => 'Not used',
    'additionalname' => 'Not used',
    'description' => 'Not used',
    'is_trade' => 1,
    'is_drop' => 1,
    'is_destruct' => 1,
    'crystal_type' => 's80',
    'consume_type' => 'consume_type_normal',
  ],
  22794 => 
  [
    'item_id' => 22794,
    'icon' => 'g_glacierin_i01',
    'name' => 'Not used',
    'additionalname' => 'Not used',
    'description' => 'Not used',
    'is_trade' => 1,
    'is_drop' => 1,
    'is_destruct' => 1,
    'crystal_type' => 's80',
    'consume_type' => 'consume_type_normal',
  ],
  22795 => 
  [
    'item_id' => 22795,
    'icon' => 'g_glacierin_i00',
    'name' => 'Freya\'s Staff (PvP]',
    'additionalname' => '',
    'description' => 'Two-handed magic blunt with special powers used by Freya. Increases damage inflicted during PvP. Has a chance of recovering CP during an attack.
No Soul Crystal option.',
    'is_trade' => 0,
    'is_drop' => 0,
    'is_destruct' => 1,
    'crystal_type' => 's80',
    'consume_type' => 'consume_type_normal',
  ],
  22796 => 
  [
    'item_id' => 22796,
    'icon' => 'g_glacierin_i01',
    'name' => 'Freya\'s Staff (PvP] - Magic Hold',
    'additionalname' => '',
    'description' => '<Special Option>
Two-handed magic blunt with special powers used by Freya. A 20% chance of casting Dryad Root on the target during magic use. Increases damage inflicted during PvP. Has a chance of increasing Casting Spd. when attacked.
No Soul Crystal option.',
    'is_trade' => 0,
    'is_drop' => 0,
    'is_destruct' => 1,
    'crystal_type' => 's80',
    'consume_type' => 'consume_type_normal',
  ],
  22797 => 
  [
    'item_id' => 22797,
    'icon' => 'g_glacierin_i01',
    'name' => 'Freya\'s Staff (PvP] - Empower',
    'additionalname' => '',
    'description' => '<Special Option>
Two-handed magic blunt with special powers used by Freya. M. Atk. Increases by 177. Increases damage inflicted during PvP. Has a chance of increasing Casting Spd. when attacked.
No Soul Crystal option.',
    'is_trade' => 0,
    'is_drop' => 0,
    'is_destruct' => 1,
    'crystal_type' => 's80',
    'consume_type' => 'consume_type_normal',
  ],
  22798 => 
  [
    'item_id' => 22798,
    'icon' => 'g_glacierin_i01',
    'name' => 'Freya\'s Staff (PvP] - MP Regeneration',
    'additionalname' => '',
    'description' => '<Special Option>
Two-handed magic blunt with special powers used by Freya. MP Recovery Rate is raised. Increases damage inflicted during PvP. Has a chance of increasing Casting Spd. when attacked.
No Soul Crystal option.',
    'is_trade' => 0,
    'is_drop' => 0,
    'is_destruct' => 1,
    'crystal_type' => 's80',
    'consume_type' => 'consume_type_normal',
  ],
  22799 => 
  [
    'item_id' => 22799,
    'icon' => 'g_glacierin_i00',
    'name' => 'Freya\'s Staff - Cleverness',
    'additionalname' => '',
    'description' => 'Masterwork Item with chance of MP absorption.
Two-handed magic blunt with special powers used by Freya. Can bestow 1 regular Soul Crystal and 1 Special Soul Crystal.',
    'is_trade' => 1,
    'is_drop' => 1,
    'is_destruct' => 1,
    'crystal_type' => 's80',
    'consume_type' => 'consume_type_normal',
  ],
];