<?php return [
  23900 => 
  [
    'item_id' => 23900,
    'icon' => 'g_agathion_anakim',
    'name' => 'Agathion Anakim',
    'additionalname' => NULL,
    'description' => 'Summons Agathion Anakim.',
    'is_trade' => 0,
    'is_drop' => 0,
    'is_destruct' => 1,
    'crystal_type' => 'none',
    'consume_type' => 'consume_type_normal',
  ],
  23901 => 
  [
    'item_id' => 23901,
    'icon' => 'g_premium_dye_attribute_unholy',
    'name' => 'Wondrous Dark Resistance Dye',
    'additionalname' => 'Dark Resistance / 7-day',
    'description' => 'Take it to the Dye Merchant in town to get a 7-day tattoo that grants certain bonuses (Dark Resistance +120 when fighting common monsters]. Requirements: all classes.',
    'is_trade' => 0,
    'is_drop' => 0,
    'is_destruct' => 1,
    'crystal_type' => 'none',
    'consume_type' => 'consume_type_stackable',
  ],
  23902 => 
  [
    'item_id' => 23902,
    'icon' => 'g_premium_dye_attribute_holy',
    'name' => 'Wondrous Holy Resistance Dye',
    'additionalname' => 'Holy Resistance / 7-day',
    'description' => 'Take it to the Dye Merchant in town to get a 7-day tattoo that grants certain bonuses (Holy Resistance +120 when fighting common monsters]. Requirements: all classes.',
    'is_trade' => 0,
    'is_drop' => 0,
    'is_destruct' => 1,
    'crystal_type' => 'none',
    'consume_type' => 'consume_type_stackable',
  ],
  23903 => 
  [
    'item_id' => 23903,
    'icon' => 'g_premium_dye_attribute_fire',
    'name' => 'Wondrous Fire Resistance Dye',
    'additionalname' => 'Fire Resistance / 7-day',
    'description' => 'Take it to the Dye Merchant in town to get a 7-day tattoo that grants certain bonuses (Fire Resistance +120 when fighting common monsters]. Requirements: all classes.',
    'is_trade' => 0,
    'is_drop' => 0,
    'is_destruct' => 1,
    'crystal_type' => 'none',
    'consume_type' => 'consume_type_stackable',
  ],
  23904 => 
  [
    'item_id' => 23904,
    'icon' => 'g_premium_dye_attribute_water',
    'name' => 'Wondrous Water Resistance Dye',
    'additionalname' => 'Water Resistance / 7-day',
    'description' => 'Take it to the Dye Merchant in town to get a 7-day tattoo that grants certain bonuses (Water Resistance +120 when fighting common monsters]. Requirements: all classes.',
    'is_trade' => 0,
    'is_drop' => 0,
    'is_destruct' => 1,
    'crystal_type' => 'none',
    'consume_type' => 'consume_type_stackable',
  ],
  23905 => 
  [
    'item_id' => 23905,
    'icon' => 'g_premium_dye_attribute_wind',
    'name' => 'Wondrous Wind Resistance Dye',
    'additionalname' => 'Wind Resistance / 7-day',
    'description' => 'Take it to the Dye Merchant in town to get a 7-day tattoo that grants certain bonuses (Wind Resistance +120 when fighting common monsters]. Requirements: all classes.',
    'is_trade' => 0,
    'is_drop' => 0,
    'is_destruct' => 1,
    'crystal_type' => 'none',
    'consume_type' => 'consume_type_stackable',
  ],
  23906 => 
  [
    'item_id' => 23906,
    'icon' => 'g_premium_dye_attribute_earth',
    'name' => 'Wondrous Earth Resistance Dye',
    'additionalname' => 'Earth Resistance / 7-day',
    'description' => 'Take it to the Dye Merchant in town to get a 7-day tattoo that grants certain bonuses (Earth Resistance +120 when fighting common monsters]. Requirements: all classes.',
    'is_trade' => 0,
    'is_drop' => 0,
    'is_destruct' => 1,
    'crystal_type' => 'none',
    'consume_type' => 'consume_type_stackable',
  ],
  23907 => 
  [
    'item_id' => 23907,
    'icon' => 'g_premium_dye_etc_debuff',
    'name' => 'Wondrous Debuff Resistance Dye',
    'additionalname' => 'Buff Cancel Resistance / Debuff Resistance / Debuff Reflection / 7-day',
    'description' => 'Take it to the Dye Merchant in town to get a 7-day tattoo that grants certain bonuses (Infection/ Stupor/ Confusion/ Obstruction Resistance +20, Buff Cancel Resistance +20, P./ M. Debuff Reflection Rate +5%]. Requirements: all classes.',
    'is_trade' => 0,
    'is_drop' => 0,
    'is_destruct' => 1,
    'crystal_type' => 'none',
    'consume_type' => 'consume_type_stackable',
  ],
  23908 => 
  [
    'item_id' => 23908,
    'icon' => 'g_premium_dye_etc_buff',
    'name' => 'Wondrous Invincibility Boost Dye',
    'additionalname' => 'Invincibility Duration Increase / 7-day',
    'description' => 'Take it to the Dye Merchant in town to get a 7-day tattoo that grants certain bonuses (basic attack/ skill invincibility duration +50%]. Requirements: all classes.',
    'is_trade' => 0,
    'is_drop' => 0,
    'is_destruct' => 1,
    'crystal_type' => 'none',
    'consume_type' => 'consume_type_stackable',
  ],
  23909 => 
  [
    'item_id' => 23909,
    'icon' => 'g_premium_dye_boss_normal',
    'name' => 'Wondrous Boss Defense Dye',
    'additionalname' => 'P. Def. / M. Def. / 7-day',
    'description' => 'Take it to the Dye Merchant in town to get a 7-day tattoo that grants certain bonuses (Earth Resistance +120 when fighting common monsters]. Requirements: all classes.',
    'is_trade' => 0,
    'is_drop' => 0,
    'is_destruct' => 1,
    'crystal_type' => 'none',
    'consume_type' => 'consume_type_stackable',
  ],
  23910 => 
  [
    'item_id' => 23910,
    'icon' => 'g_premium_dye_boss_antaras',
    'name' => 'Wondrous Antharas Defense Dye',
    'additionalname' => 'P. Def. / M. Def. / 7-day',
    'description' => 'Take it to the Dye Merchant in town to get a 7-day tattoo that grants certain bonuses (P./ M. Def. +20% when fighting Antharas]. Requirements: all classes.',
    'is_trade' => 0,
    'is_drop' => 0,
    'is_destruct' => 1,
    'crystal_type' => 'none',
    'consume_type' => 'consume_type_stackable',
  ],
  23911 => 
  [
    'item_id' => 23911,
    'icon' => 'g_premium_dye_boss_valakas',
    'name' => 'Wondrous Valakas Defense Dye',
    'additionalname' => 'P. Def. / M. Def. / 7-day',
    'description' => 'Take it to the Dye Merchant in town to get a 7-day tattoo that grants certain bonuses (P./ M. Def. +20% when fighting Valakas]. Requirements: all classes.',
    'is_trade' => 0,
    'is_drop' => 0,
    'is_destruct' => 1,
    'crystal_type' => 'none',
    'consume_type' => 'consume_type_stackable',
  ],
  23912 => 
  [
    'item_id' => 23912,
    'icon' => 'g_premium_dye_boss_lindvior',
    'name' => 'Wondrous Lindvior Defense Dye',
    'additionalname' => 'P. Def. / M. Def. / 7-day',
    'description' => 'Take it to the Dye Merchant in town to get a 7-day tattoo that grants certain bonuses (P./ M. Def. +20% when fighting Lindvior]. Requirements: all classes.',
    'is_trade' => 0,
    'is_drop' => 0,
    'is_destruct' => 1,
    'crystal_type' => 'none',
    'consume_type' => 'consume_type_stackable',
  ],
  23913 => 
  [
    'item_id' => 23913,
    'icon' => '.iconWeapon.g_tears_sword_i00',
    'name' => 'One-handed Sword of Tears',
    'additionalname' => NULL,
    'description' => 'Russias weapon crafting contest finalist. A prototype for Appearance Stone.',
    'is_trade' => 1,
    'is_drop' => 0,
    'is_destruct' => 1,
    'crystal_type' => 'd',
    'consume_type' => 'consume_type_normal',
  ],
  23914 => 
  [
    'item_id' => 23914,
    'icon' => '.iconWeapon.g_tears_dagger_i00',
    'name' => 'Dagger of Tears',
    'additionalname' => NULL,
    'description' => 'Russias weapon crafting contest finalist. A prototype for Appearance Stone.',
    'is_trade' => 1,
    'is_drop' => 0,
    'is_destruct' => 1,
    'crystal_type' => 'd',
    'consume_type' => 'consume_type_normal',
  ],
  23915 => 
  [
    'item_id' => 23915,
    'icon' => '.iconWeapon.g_tears_twohand_sword_i00',
    'name' => 'Two-handed Sword of Tears',
    'additionalname' => NULL,
    'description' => 'Russias weapon crafting contest finalist. A prototype for Appearance Stone.',
    'is_trade' => 1,
    'is_drop' => 0,
    'is_destruct' => 1,
    'crystal_type' => 'd',
    'consume_type' => 'consume_type_normal',
  ],
  23916 => 
  [
    'item_id' => 23916,
    'icon' => '.iconWeapon.g_tears_dualfist_i00',
    'name' => 'Fist Weapon of Tears',
    'additionalname' => NULL,
    'description' => 'Russias weapon crafting contest finalist. A prototype for Appearance Stone.',
    'is_trade' => 1,
    'is_drop' => 0,
    'is_destruct' => 1,
    'crystal_type' => 'd',
    'consume_type' => 'consume_type_normal',
  ],
  23917 => 
  [
    'item_id' => 23917,
    'icon' => '.iconWeapon.g_tears_pole_i00',
    'name' => 'Spear of Tears',
    'additionalname' => NULL,
    'description' => 'Russias weapon crafting contest finalist. A prototype for Appearance Stone.',
    'is_trade' => 1,
    'is_drop' => 0,
    'is_destruct' => 1,
    'crystal_type' => 'd',
    'consume_type' => 'consume_type_normal',
  ],
  23918 => 
  [
    'item_id' => 23918,
    'icon' => '.iconWeapon.g_tears_bow_i00',
    'name' => 'Bow of Tears',
    'additionalname' => NULL,
    'description' => 'Russias weapon crafting contest finalist. A prototype for Appearance Stone.',
    'is_trade' => 1,
    'is_drop' => 0,
    'is_destruct' => 1,
    'crystal_type' => 'd',
    'consume_type' => 'consume_type_normal',
  ],
  23919 => 
  [
    'item_id' => 23919,
    'icon' => '.iconWeapon.g_tears_twohand_crossbow_i00',
    'name' => 'Crossbow of Tears',
    'additionalname' => NULL,
    'description' => 'Russias weapon crafting contest finalist. A prototype for Appearance Stone.',
    'is_trade' => 1,
    'is_drop' => 0,
    'is_destruct' => 1,
    'crystal_type' => 'd',
    'consume_type' => 'consume_type_normal',
  ],
  23920 => 
  [
    'item_id' => 23920,
    'icon' => '.iconWeapon.g_tears_blunt_i00',
    'name' => 'One-handed Blunt Weapon of Tears',
    'additionalname' => NULL,
    'description' => 'Russias weapon crafting contest finalist. A prototype for Appearance Stone.',
    'is_trade' => 1,
    'is_drop' => 0,
    'is_destruct' => 1,
    'crystal_type' => 'd',
    'consume_type' => 'consume_type_normal',
  ],
  23921 => 
  [
    'item_id' => 23921,
    'icon' => '.iconWeapon.g_tears_magic_sword_i00',
    'name' => 'Magic Sword of Tears',
    'additionalname' => NULL,
    'description' => 'Russias weapon crafting contest finalist. A prototype for Appearance Stone.',
    'is_trade' => 1,
    'is_drop' => 0,
    'is_destruct' => 1,
    'crystal_type' => 'd',
    'consume_type' => 'consume_type_normal',
  ],
  23922 => 
  [
    'item_id' => 23922,
    'icon' => '.iconWeapon.g_tears_magic_blunt_i00',
    'name' => 'One-handed Staff of Tears',
    'additionalname' => NULL,
    'description' => 'Russias weapon crafting contest finalist. A prototype for Appearance Stone.',
    'is_trade' => 1,
    'is_drop' => 0,
    'is_destruct' => 1,
    'crystal_type' => 'd',
    'consume_type' => 'consume_type_normal',
  ],
  23923 => 
  [
    'item_id' => 23923,
    'icon' => '.iconWeapon.g_tears_magic_twohand_blunt_i00',
    'name' => 'Two-handed Staff of Tears',
    'additionalname' => NULL,
    'description' => 'Russias weapon crafting contest finalist. A prototype for Appearance Stone.',
    'is_trade' => 1,
    'is_drop' => 0,
    'is_destruct' => 1,
    'crystal_type' => 'd',
    'consume_type' => 'consume_type_normal',
  ],
  23924 => 
  [
    'item_id' => 23924,
    'icon' => '.iconWeapon.g_tears_dual_i00',
    'name' => 'Dual Swords of Tears',
    'additionalname' => NULL,
    'description' => 'Russias weapon crafting contest finalist. A prototype for Appearance Stone.',
    'is_trade' => 1,
    'is_drop' => 0,
    'is_destruct' => 1,
    'crystal_type' => 'd',
    'consume_type' => 'consume_type_normal',
  ],
  23925 => 
  [
    'item_id' => 23925,
    'icon' => '.iconWeapon.g_tears_dualdagger_i00',
    'name' => 'Dual Daggers of Tears',
    'additionalname' => NULL,
    'description' => 'Russias weapon crafting contest finalist. A prototype for Appearance Stone.',
    'is_trade' => 1,
    'is_drop' => 0,
    'is_destruct' => 1,
    'crystal_type' => 'd',
    'consume_type' => 'consume_type_normal',
  ],
  23926 => 
  [
    'item_id' => 23926,
    'icon' => '.iconWeapon.g_tears_dualblunt_i00',
    'name' => 'Dual Blunt Weapons of Tears',
    'additionalname' => NULL,
    'description' => 'Russias weapon crafting contest finalist. A prototype for Appearance Stone.',
    'is_trade' => 1,
    'is_drop' => 0,
    'is_destruct' => 1,
    'crystal_type' => 'd',
    'consume_type' => 'consume_type_normal',
  ],
  23927 => 
  [
    'item_id' => 23927,
    'icon' => '.iconWeapon.g_tears_shield_i00',
    'name' => 'Shield of Tears',
    'additionalname' => NULL,
    'description' => 'Russias weapon crafting contest finalist. A prototype for Appearance Stone.',
    'is_trade' => 1,
    'is_drop' => 0,
    'is_destruct' => 1,
    'crystal_type' => 'd',
    'consume_type' => 'consume_type_normal',
  ],
  23928 => 
  [
    'item_id' => 23928,
    'icon' => 'g_tears_sigil_i00',
    'name' => 'Sigil of Tears',
    'additionalname' => NULL,
    'description' => 'Russias weapon crafting contest finalist. A prototype for Appearance Stone.',
    'is_trade' => 1,
    'is_drop' => 0,
    'is_destruct' => 1,
    'crystal_type' => 'd',
    'consume_type' => 'consume_type_normal',
  ],
  23929 => 
  [
    'item_id' => 23929,
    'icon' => 'g_shape_shifting_sword',
    'name' => 'Appearance Stone: One-handed Sword of Tears',
    'additionalname' => '7-day',
    'description' => 'Changes the appearance of a one-handed sword to that of One-handed Sword of Tears. Duration: 7 d.',
    'is_trade' => 0,
    'is_drop' => 0,
    'is_destruct' => 1,
    'crystal_type' => 'crystal_free',
    'consume_type' => 'consume_type_stackable',
  ],
  23930 => 
  [
    'item_id' => 23930,
    'icon' => 'g_shape_shifting_dagger',
    'name' => 'Appearance Stone: Dagger of Tears',
    'additionalname' => '7-day',
    'description' => 'Changes the appearance of a dagger to that of Dagger of Tears. Duration: 7 d.',
    'is_trade' => 0,
    'is_drop' => 0,
    'is_destruct' => 1,
    'crystal_type' => 'crystal_free',
    'consume_type' => 'consume_type_stackable',
  ],
  23931 => 
  [
    'item_id' => 23931,
    'icon' => 'g_shape_shifting_twohand_sword',
    'name' => 'Appearance Stone: Two-handed Sword of Tears',
    'additionalname' => '7-day',
    'description' => 'Changes the appearance of a two-handed sword to that of Two-handed Sword of Tears. Duration: 7 d.',
    'is_trade' => 0,
    'is_drop' => 0,
    'is_destruct' => 1,
    'crystal_type' => 'crystal_free',
    'consume_type' => 'consume_type_stackable',
  ],
  23932 => 
  [
    'item_id' => 23932,
    'icon' => 'g_shape_shifting_dualfist',
    'name' => 'Appearance Stone: Fist Weapon of Tears',
    'additionalname' => '7-day',
    'description' => 'Changes the appearance of a fist weapon to that of Fist Weapon of Tears. Duration: 7 d.',
    'is_trade' => 0,
    'is_drop' => 0,
    'is_destruct' => 1,
    'crystal_type' => 'crystal_free',
    'consume_type' => 'consume_type_stackable',
  ],
  23933 => 
  [
    'item_id' => 23933,
    'icon' => 'g_shape_shifting_pole',
    'name' => 'Appearance Stone: Spear of Tears',
    'additionalname' => '7-day',
    'description' => 'Changes the appearance of a spear to that of Spear of Tears. Duration: 7 d.',
    'is_trade' => 0,
    'is_drop' => 0,
    'is_destruct' => 1,
    'crystal_type' => 'crystal_free',
    'consume_type' => 'consume_type_stackable',
  ],
  23934 => 
  [
    'item_id' => 23934,
    'icon' => 'g_shape_shifting_bow',
    'name' => 'Appearance Stone: Bow of Tears',
    'additionalname' => '7-day',
    'description' => 'Changes the appearance of a bow to that of Bow of Tears. Duration: 7 d.',
    'is_trade' => 0,
    'is_drop' => 0,
    'is_destruct' => 1,
    'crystal_type' => 'crystal_free',
    'consume_type' => 'consume_type_stackable',
  ],
  23935 => 
  [
    'item_id' => 23935,
    'icon' => 'g_shape_shifting_twohand_crossbow',
    'name' => 'Appearance Stone: Crossbow of Tears',
    'additionalname' => '7-day',
    'description' => 'Changes the appearance of a crossbow to that of Crossbow of Tears. Duration: 7 d.',
    'is_trade' => 0,
    'is_drop' => 0,
    'is_destruct' => 1,
    'crystal_type' => 'crystal_free',
    'consume_type' => 'consume_type_stackable',
  ],
  23936 => 
  [
    'item_id' => 23936,
    'icon' => 'g_shape_shifting_blunt',
    'name' => 'Appearance Stone: One-handed Blunt Weapon of Tears',
    'additionalname' => '7-day',
    'description' => 'Changes the appearance of a one-handed blunt weapon to that of One-handed Blunt Weapon of Tears. Duration: 7 d.',
    'is_trade' => 0,
    'is_drop' => 0,
    'is_destruct' => 1,
    'crystal_type' => 'crystal_free',
    'consume_type' => 'consume_type_stackable',
  ],
  23937 => 
  [
    'item_id' => 23937,
    'icon' => 'g_shape_shifting_twohand_blunt',
    'name' => 'Appearance Stone: Magic Sword of Tears',
    'additionalname' => '7-day',
    'description' => 'Changes the appearance of a magic sword to that of Magic Sword of Tears. Duration: 7 d.',
    'is_trade' => 0,
    'is_drop' => 0,
    'is_destruct' => 1,
    'crystal_type' => 'crystal_free',
    'consume_type' => 'consume_type_stackable',
  ],
  23938 => 
  [
    'item_id' => 23938,
    'icon' => 'g_shape_shifting_magic_blunt',
    'name' => 'Appearance Stone: One-handed Staff of Tears',
    'additionalname' => '7-day',
    'description' => 'Changes the appearance of a one-handed staff to that of One-handed Staff of Tears. Duration: 7 d.',
    'is_trade' => 0,
    'is_drop' => 0,
    'is_destruct' => 1,
    'crystal_type' => 'crystal_free',
    'consume_type' => 'consume_type_stackable',
  ],
  23939 => 
  [
    'item_id' => 23939,
    'icon' => 'g_shape_shifting_magic_twohand_blunt',
    'name' => 'Appearance Stone: Two-handed Staff of Tears',
    'additionalname' => '7-day',
    'description' => 'Changes the appearance of a two-handed blunt weapon to that of Two-handed Staff of Tears. Duration: 7 d.',
    'is_trade' => 0,
    'is_drop' => 0,
    'is_destruct' => 1,
    'crystal_type' => 'crystal_free',
    'consume_type' => 'consume_type_stackable',
  ],
  23940 => 
  [
    'item_id' => 23940,
    'icon' => 'g_shape_shifting_dual',
    'name' => 'Appearance Stone: Dual Swords of Tears',
    'additionalname' => '7-day',
    'description' => 'Changes the appearance of dual swords to that of Dual Swords of Tears. Duration: 7 d.',
    'is_trade' => 0,
    'is_drop' => 0,
    'is_destruct' => 1,
    'crystal_type' => 'crystal_free',
    'consume_type' => 'consume_type_stackable',
  ],
  23941 => 
  [
    'item_id' => 23941,
    'icon' => 'g_shape_shifting_dualdagger',
    'name' => 'Appearance Stone: Dual Daggers of Tears',
    'additionalname' => '7-day',
    'description' => 'Changes the appearance of dual daggers to that of Dual Daggers of Tears. Duration: 7 d.',
    'is_trade' => 0,
    'is_drop' => 0,
    'is_destruct' => 1,
    'crystal_type' => 'crystal_free',
    'consume_type' => 'consume_type_stackable',
  ],
  23942 => 
  [
    'item_id' => 23942,
    'icon' => 'g_shape_shifting_dualblunt',
    'name' => 'Appearance Stone: Dual Blunt Weapons of Tears',
    'additionalname' => '7-day',
    'description' => 'Changes the appearance of dual blunt weapons to that of Dual Blunt Weapons of Tears. Duration: 7 d.',
    'is_trade' => 0,
    'is_drop' => 0,
    'is_destruct' => 1,
    'crystal_type' => 'crystal_free',
    'consume_type' => 'consume_type_stackable',
  ],
  23943 => 
  [
    'item_id' => 23943,
    'icon' => 'g_shape_shifting_shield',
    'name' => 'Appearance Stone: Shield of Tears',
    'additionalname' => '7-day',
    'description' => 'Changes the appearance of a shield to that of Shield of Tears. Duration: 7 d.',
    'is_trade' => 0,
    'is_drop' => 0,
    'is_destruct' => 1,
    'crystal_type' => 'crystal_free',
    'consume_type' => 'consume_type_stackable',
  ],
  23944 => 
  [
    'item_id' => 23944,
    'icon' => 'g_shape_shifting_sigil',
    'name' => 'Appearance Stone: Sigil of Tears',
    'additionalname' => '7-day',
    'description' => 'Changes the appearance of a sigil to that of Sigil of Tears. Duration: 7 d.',
    'is_trade' => 0,
    'is_drop' => 0,
    'is_destruct' => 1,
    'crystal_type' => 'crystal_free',
    'consume_type' => 'consume_type_stackable',
  ],
  23945 => 
  [
    'item_id' => 23945,
    'icon' => 'br_four_leaf_clover_box_i00',
    'name' => 'Package: High-grade Maphrs Rune 100%',
    'additionalname' => '3-hour',
    'description' => 'Double-click to obtain High-grade Maphrs Rune 100% (3-hour].',
    'is_trade' => 1,
    'is_drop' => 1,
    'is_destruct' => 1,
    'crystal_type' => 'crystal_free',
    'consume_type' => 'consume_type_stackable',
  ],
  23946 => 
  [
    'item_id' => 23946,
    'icon' => 'etc_pi_gift_box_i04',
    'name' => 'Nevits Rune Box (Dragon Rising] 100% (1-hour]',
    'additionalname' => NULL,
    'description' => 'Double-click to obtain Nevits Rune 100% (1-hour]. Required level: 1-95.',
    'is_trade' => 1,
    'is_drop' => 1,
    'is_destruct' => 1,
    'crystal_type' => 'none',
    'consume_type' => 'consume_type_stackable',
  ],
  23947 => 
  [
    'item_id' => 23947,
    'icon' => 'aphros_key',
    'name' => 'Kamaloka Secret Chest Key',
    'additionalname' => NULL,
    'description' => 'Key to opening treasure chests in the Infernal and Lunatic Kamaloka. Use 5 to open a Secret Chest, and 2 to open a normal Chest.',
    'is_trade' => 1,
    'is_drop' => 1,
    'is_destruct' => 1,
    'crystal_type' => 'none',
    'consume_type' => 'consume_type_stackable',
  ],
  23948 => 
  [
    'item_id' => 23948,
    'icon' => 'etc_old_key_i01',
    'name' => 'Kamaloka Chest Key',
    'additionalname' => NULL,
    'description' => 'Key to opening treasure chests in the Infernal and Lunatic Kamaloka. Use 5 to open a Secret Chest, and 2 to open a normal Chest.',
    'is_trade' => 1,
    'is_drop' => 1,
    'is_destruct' => 1,
    'crystal_type' => 'none',
    'consume_type' => 'consume_type_stackable',
  ],
  23949 => 
  [
    'item_id' => 23949,
    'icon' => 'cube_event_i02',
    'name' => 'Returning Heros Wondrous Cubic',
    'additionalname' => NULL,
    'description' => 'Double-click to obtain either a Vitality Replenishing Potion (30-min.], Feather of Blessing, Heavenly Cocktail x 2, Scroll of Escape Pack: Village, or MP Recovery Potion. Once a day.',
    'is_trade' => 0,
    'is_drop' => 0,
    'is_destruct' => 0,
    'crystal_type' => 'crystal_free',
    'consume_type' => 'consume_type_normal',
  ],
  23950 => 
  [
    'item_id' => 23950,
    'icon' => 'present_of_destination_event',
    'name' => 'Returning Heros Gold Chest',
    'additionalname' => 'Event',
    'description' => 'Double-click to obtain Returning Heros Mark x 250, a Returning Heros Potion Pack, and a Returning Heros Support Box.',
    'is_trade' => 0,
    'is_drop' => 0,
    'is_destruct' => 1,
    'crystal_type' => 'crystal_free',
    'consume_type' => 'consume_type_stackable',
  ],
  23951 => 
  [
    'item_id' => 23951,
    'icon' => 'etc_pi_gift_box_i00',
    'name' => 'Returning Heros Support Box',
    'additionalname' => NULL,
    'description' => 'Double-click to obtain Rerturning Heros Shirt, Returning Heros Belt, and a Returning Heros Wondrous Cubic.',
    'is_trade' => 0,
    'is_drop' => 0,
    'is_destruct' => 1,
    'crystal_type' => 'crystal_free',
    'consume_type' => 'consume_type_stackable',
  ],
  23952 => 
  [
    'item_id' => 23952,
    'icon' => 'etc_ticket_red_i00',
    'name' => 'Extra Pass: Infernal/ Lunatic Kamaloka',
    'additionalname' => NULL,
    'description' => 'Entry Pass to Infernal and Lunatic Kamaloka. Use to reset cooldown and enter the dungeon up to 5 times within the cooldown.',
    'is_trade' => 1,
    'is_drop' => 1,
    'is_destruct' => 1,
    'crystal_type' => 'crystal_free',
    'consume_type' => 'consume_type_normal',
  ],
  23953 => 
  [
    'item_id' => 23953,
    'icon' => 'accessory_archer_hat2_i00',
    'name' => '2014 World Olympiad Heros Accessory',
    'additionalname' => NULL,
    'description' => 'A head accessory of the victor of the 2014 World Olympiad. A symbol of the strongest hero of all servers. When equipped, all stats +5.',
    'is_trade' => 0,
    'is_drop' => 0,
    'is_destruct' => 0,
    'crystal_type' => 'none',
    'consume_type' => 'consume_type_normal',
  ],
  23954 => 
  [
    'item_id' => 23954,
    'icon' => 'accessory_archer_hat2_i00',
    'name' => '2014 World Olympiad Semifinalists Accessory ',
    'additionalname' => NULL,
    'description' => 'A head accessory of the runner-up of the 2014 World Olympiad. A symbol of the 2nd strongest hero of all servers. When equipped, all stats +2.',
    'is_trade' => 0,
    'is_drop' => 0,
    'is_destruct' => 0,
    'crystal_type' => 'none',
    'consume_type' => 'consume_type_normal',
  ],
  23955 => 
  [
    'item_id' => 23955,
    'icon' => 'present_of_destination_event',
    'name' => 'Kamaloka Secret Chest',
    'additionalname' => NULL,
    'description' => 'Kamaloka Secret Chest found in Infernal and Lunatic Kamaloka. Double-click to obtain one of the following items: Dark/ Bloody Helios Enhancement Stone, Dark/ Bloody Eternal Enhancement Stone, Life Stone: Giants Power, Scroll of Blessing: R99-grade Weapon/ Armor, Top-grade R/ R95/ R99-grade Life Stone, Giants Scroll: Enchant R-grade Weapon/ Armor, Attribute Stone (+60], R-grade Gemstone.',
    'is_trade' => 1,
    'is_drop' => 1,
    'is_destruct' => 1,
    'crystal_type' => 'none',
    'consume_type' => 'consume_type_stackable',
  ],
  23956 => 
  [
    'item_id' => 23956,
    'icon' => 'present_of_destination_event',
    'name' => 'Kamaloka Chest',
    'additionalname' => NULL,
    'description' => 'Identical to the Kamaloka Chest found in Infernal and Lunatic Kamaloka. Has a chance of obtaining either a Blessed Scroll: Enchant R-grade Weapon/ Armor, High-grade R/ R95/ R99-grade Life Stone, Scroll: Enchant R-grade Weapon/ Armor, an Attribute Stone, or Blessed Scroll of Resurrection.',
    'is_trade' => 1,
    'is_drop' => 1,
    'is_destruct' => 1,
    'crystal_type' => 'none',
    'consume_type' => 'consume_type_stackable',
  ],
  23957 => 
  [
    'item_id' => 23957,
    'icon' => NULL,
    'name' => 'Illusion 1',
    'additionalname' => NULL,
    'description' => '',
    'is_trade' => 0,
    'is_drop' => 0,
    'is_destruct' => 1,
    'crystal_type' => 'none',
    'consume_type' => 'consume_type_stackable',
  ],
  23958 => 
  [
    'item_id' => 23958,
    'icon' => NULL,
    'name' => 'Illusion 2',
    'additionalname' => NULL,
    'description' => '',
    'is_trade' => 0,
    'is_drop' => 0,
    'is_destruct' => 1,
    'crystal_type' => 'none',
    'consume_type' => 'consume_type_stackable',
  ],
  23959 => 
  [
    'item_id' => 23959,
    'icon' => NULL,
    'name' => 'Illusion 3',
    'additionalname' => NULL,
    'description' => '',
    'is_trade' => 0,
    'is_drop' => 0,
    'is_destruct' => 1,
    'crystal_type' => 'none',
    'consume_type' => 'consume_type_stackable',
  ],
  23960 => 
  [
    'item_id' => 23960,
    'icon' => NULL,
    'name' => 'Illusion 4',
    'additionalname' => NULL,
    'description' => '',
    'is_trade' => 0,
    'is_drop' => 0,
    'is_destruct' => 1,
    'crystal_type' => 'none',
    'consume_type' => 'consume_type_stackable',
  ],
  23961 => 
  [
    'item_id' => 23961,
    'icon' => NULL,
    'name' => 'Illusion 5',
    'additionalname' => NULL,
    'description' => '',
    'is_trade' => 0,
    'is_drop' => 0,
    'is_destruct' => 1,
    'crystal_type' => 'none',
    'consume_type' => 'consume_type_stackable',
  ],
  23962 => 
  [
    'item_id' => 23962,
    'icon' => NULL,
    'name' => 'Illusion 6',
    'additionalname' => NULL,
    'description' => '',
    'is_trade' => 0,
    'is_drop' => 0,
    'is_destruct' => 1,
    'crystal_type' => 'none',
    'consume_type' => 'consume_type_stackable',
  ],
  23963 => 
  [
    'item_id' => 23963,
    'icon' => NULL,
    'name' => 'Illusion 7',
    'additionalname' => NULL,
    'description' => '',
    'is_trade' => 0,
    'is_drop' => 0,
    'is_destruct' => 1,
    'crystal_type' => 'none',
    'consume_type' => 'consume_type_stackable',
  ],
  23964 => 
  [
    'item_id' => 23964,
    'icon' => NULL,
    'name' => 'Illusion 8',
    'additionalname' => NULL,
    'description' => '',
    'is_trade' => 0,
    'is_drop' => 0,
    'is_destruct' => 1,
    'crystal_type' => 'none',
    'consume_type' => 'consume_type_stackable',
  ],
  23965 => 
  [
    'item_id' => 23965,
    'icon' => NULL,
    'name' => 'Illusion 9',
    'additionalname' => NULL,
    'description' => '',
    'is_trade' => 0,
    'is_drop' => 0,
    'is_destruct' => 1,
    'crystal_type' => 'none',
    'consume_type' => 'consume_type_stackable',
  ],
  23966 => 
  [
    'item_id' => 23966,
    'icon' => NULL,
    'name' => 'Illusion 10',
    'additionalname' => NULL,
    'description' => '',
    'is_trade' => 0,
    'is_drop' => 0,
    'is_destruct' => 1,
    'crystal_type' => 'none',
    'consume_type' => 'consume_type_stackable',
  ],
  23967 => 
  [
    'item_id' => 23967,
    'icon' => NULL,
    'name' => 'Illusion 11',
    'additionalname' => NULL,
    'description' => '',
    'is_trade' => 0,
    'is_drop' => 0,
    'is_destruct' => 1,
    'crystal_type' => 'none',
    'consume_type' => 'consume_type_stackable',
  ],
  23968 => 
  [
    'item_id' => 23968,
    'icon' => NULL,
    'name' => 'Illusion 12',
    'additionalname' => NULL,
    'description' => '',
    'is_trade' => 0,
    'is_drop' => 0,
    'is_destruct' => 1,
    'crystal_type' => 'none',
    'consume_type' => 'consume_type_stackable',
  ],
  23969 => 
  [
    'item_id' => 23969,
    'icon' => NULL,
    'name' => 'Illusion 13',
    'additionalname' => NULL,
    'description' => '',
    'is_trade' => 0,
    'is_drop' => 0,
    'is_destruct' => 1,
    'crystal_type' => 'none',
    'consume_type' => 'consume_type_stackable',
  ],
  23970 => 
  [
    'item_id' => 23970,
    'icon' => NULL,
    'name' => 'Illusion 14',
    'additionalname' => NULL,
    'description' => '',
    'is_trade' => 0,
    'is_drop' => 0,
    'is_destruct' => 1,
    'crystal_type' => 'none',
    'consume_type' => 'consume_type_stackable',
  ],
  23971 => 
  [
    'item_id' => 23971,
    'icon' => NULL,
    'name' => 'Illusion 15',
    'additionalname' => NULL,
    'description' => '',
    'is_trade' => 0,
    'is_drop' => 0,
    'is_destruct' => 1,
    'crystal_type' => 'none',
    'consume_type' => 'consume_type_stackable',
  ],
  23972 => 
  [
    'item_id' => 23972,
    'icon' => NULL,
    'name' => 'Illusion 16',
    'additionalname' => NULL,
    'description' => '',
    'is_trade' => 0,
    'is_drop' => 0,
    'is_destruct' => 1,
    'crystal_type' => 'none',
    'consume_type' => 'consume_type_stackable',
  ],
  23973 => 
  [
    'item_id' => 23973,
    'icon' => NULL,
    'name' => 'Illusion 17',
    'additionalname' => NULL,
    'description' => '',
    'is_trade' => 0,
    'is_drop' => 0,
    'is_destruct' => 1,
    'crystal_type' => 'none',
    'consume_type' => 'consume_type_stackable',
  ],
  23974 => 
  [
    'item_id' => 23974,
    'icon' => NULL,
    'name' => 'Illusion 18',
    'additionalname' => NULL,
    'description' => '',
    'is_trade' => 0,
    'is_drop' => 0,
    'is_destruct' => 1,
    'crystal_type' => 'none',
    'consume_type' => 'consume_type_stackable',
  ],
  23975 => 
  [
    'item_id' => 23975,
    'icon' => NULL,
    'name' => 'Illusion 19',
    'additionalname' => NULL,
    'description' => '',
    'is_trade' => 0,
    'is_drop' => 0,
    'is_destruct' => 1,
    'crystal_type' => 'none',
    'consume_type' => 'consume_type_stackable',
  ],
  23976 => 
  [
    'item_id' => 23976,
    'icon' => NULL,
    'name' => 'Illusion 20',
    'additionalname' => NULL,
    'description' => '',
    'is_trade' => 0,
    'is_drop' => 0,
    'is_destruct' => 1,
    'crystal_type' => 'none',
    'consume_type' => 'consume_type_stackable',
  ],
  23977 => 
  [
    'item_id' => 23977,
    'icon' => 'br_four_leaf_clover_box_i00',
    'name' => 'Package: Agathion Pegasus',
    'additionalname' => NULL,
    'description' => 'Double-click to obtain Agathion Pegasus.',
    'is_trade' => 1,
    'is_drop' => 1,
    'is_destruct' => 1,
    'crystal_type' => 'crystal_free',
    'consume_type' => 'consume_type_stackable',
  ],
  23978 => 
  [
    'item_id' => 23978,
    'icon' => 'br_aga_pegasus_i00',
    'name' => 'Agathion Pegasus',
    'additionalname' => NULL,
    'description' => 'A bracelet for summoning Agathion Pegasus.',
    'is_trade' => 1,
    'is_drop' => 1,
    'is_destruct' => 1,
    'crystal_type' => 'none',
    'consume_type' => 'consume_type_normal',
  ],
  23979 => 
  [
    'item_id' => 23979,
    'icon' => 'g_scrl_change_chest',
    'name' => 'Appearance Stone: Vampire Top',
    'additionalname' => NULL,
    'description' => 'Changes the appearance of a top to that of a Vampire Outfit. No change in stats. All armor types. Can be stored in the clan warehouse.',
    'is_trade' => 1,
    'is_drop' => 1,
    'is_destruct' => 1,
    'crystal_type' => 'none',
    'consume_type' => 'consume_type_stackable',
  ],
  23980 => 
  [
    'item_id' => 23980,
    'icon' => 'g_scrl_change_legs',
    'name' => 'Appearance Stone: Vampire Pants',
    'additionalname' => NULL,
    'description' => 'Changes the appearance of pants to those of a Vampire Outfit. No change in stats. All armor types. Can be stored in the clan warehouse.',
    'is_trade' => 1,
    'is_drop' => 1,
    'is_destruct' => 1,
    'crystal_type' => 'none',
    'consume_type' => 'consume_type_stackable',
  ],
  23981 => 
  [
    'item_id' => 23981,
    'icon' => 'g_scrl_change_gloves',
    'name' => 'Appearance Stone: Vampire Gloves',
    'additionalname' => NULL,
    'description' => 'Changes the appearance of gloves to those of a Vampire Outfit. No change in stats. All armor types. Can be stored in the clan warehouse.',
    'is_trade' => 1,
    'is_drop' => 1,
    'is_destruct' => 1,
    'crystal_type' => 'none',
    'consume_type' => 'consume_type_stackable',
  ],
  23982 => 
  [
    'item_id' => 23982,
    'icon' => 'g_scrl_change_feet',
    'name' => 'Appearance Stone: Vampire Shoes',
    'additionalname' => NULL,
    'description' => 'Changes the appearance of shoes to those of a Vampire Outfit. No change in stats. All armor types. Can be stored in the clan warehouse.',
    'is_trade' => 1,
    'is_drop' => 1,
    'is_destruct' => 1,
    'crystal_type' => 'none',
    'consume_type' => 'consume_type_stackable',
  ],
  23983 => 
  [
    'item_id' => 23983,
    'icon' => 'g_shape_shifting_hair2',
    'name' => 'Appearance Stone: Vampire Head Accessory',
    'additionalname' => NULL,
    'description' => 'Changes the appearance of a head accessory into that of Vampire Head Accessory. Can only be used on head accessories equipped in 2 slots. Can be stored in the clan warehouse.',
    'is_trade' => 1,
    'is_drop' => 1,
    'is_destruct' => 1,
    'crystal_type' => 'none',
    'consume_type' => 'consume_type_stackable',
  ],
  23984 => 
  [
    'item_id' => 23984,
    'icon' => 'g_ev_magic_powder',
    'name' => 'Traces of Ancient Kartias Labyrinth',
    'additionalname' => 'PA Event',
    'description' => 'Obtained for PA points. Perhaps, a Kartia Researcher may know more about it. Cannot be exchanged, dropped, or sold. Can be stored in the private warehouse. ',
    'is_trade' => 0,
    'is_drop' => 0,
    'is_destruct' => 1,
    'crystal_type' => 'crystal_free',
    'consume_type' => 'consume_type_stackable',
  ],
  23985 => 
  [
    'item_id' => 23985,
    'icon' => 'etc_ticket_red_i00',
    'name' => 'Extra Pass: Ancient Kartias Labyrinth',
    'additionalname' => 'PA Event',
    'description' => 'Obtained for PA points. Resets the cooldown to Ancient Kartias Labyrinth. Cannot be exchanged, dropped, or sold. Can be stored in the private warehouse. ',
    'is_trade' => 0,
    'is_drop' => 0,
    'is_destruct' => 1,
    'crystal_type' => 'crystal_free',
    'consume_type' => 'consume_type_stackable',
  ],
  23986 => 
  [
    'item_id' => 23986,
    'icon' => 'ev_charge_box',
    'name' => 'Growth Rune Pack',
    'additionalname' => NULL,
    'description' => 'Double-click to obtain Growth Rune (30-day].',
    'is_trade' => 0,
    'is_drop' => 0,
    'is_destruct' => 0,
    'crystal_type' => 'crystal_free',
    'consume_type' => 'consume_type_stackable',
  ],
  23987 => 
  [
    'item_id' => 23987,
    'icon' => 'ev_charge_run',
    'name' => 'Growth Rune (30-day]',
    'additionalname' => NULL,
    'description' => 'When in inventory, Acquired XP/ SP +20%. Can be stacked with all XP/ SP bonus effects with the exception of Emperors Rune.',
    'is_trade' => 0,
    'is_drop' => 0,
    'is_destruct' => 0,
    'crystal_type' => 'crystal_free',
    'consume_type' => 'consume_type_normal',
  ],
  23988 => 
  [
    'item_id' => 23988,
    'icon' => 'ev_charge_scroll',
    'name' => 'Wondrous Wind Scroll',
    'additionalname' => NULL,
    'description' => 'For 60 min., Max HP/ MP/ CP +30%, P./ M. Def. +30%, P. Atk. +10%, M. Atk. +20%, Wind Atk./ Resistance +20. Skill Cooldown -10%. Cannot be used in the Olympiad. Does not stack with Art of Seduction. The effect remains after death.',
    'is_trade' => 0,
    'is_drop' => 0,
    'is_destruct' => 1,
    'crystal_type' => 'crystal_free',
    'consume_type' => 'consume_type_stackable',
  ],
  23989 => 
  [
    'item_id' => 23989,
    'icon' => 'accessary_lbracelet_sign_agathion_aug_i00',
    'name' => 'Agathion Virgo',
    'additionalname' => 'Lv. 1',
    'description' => 'A bracelet for summoning Agathion Virgo.<Active skills>1. Healing Light: Restores entire partys HP/ MP/ CP with a chance to cancel debuffs. Cooldown: 37 min. 30 sec.2. Attribute Enchant: Attribute Resistance +5.',
    'is_trade' => 0,
    'is_drop' => 0,
    'is_destruct' => 1,
    'crystal_type' => 'r',
    'consume_type' => 'consume_type_normal',
  ],
  23990 => 
  [
    'item_id' => 23990,
    'icon' => 'accessary_lbracelet_sign_agathion_aug_i00',
    'name' => 'Agathion Virgo',
    'additionalname' => 'Lv. 2',
    'description' => 'A bracelet for summoning Agathion Virgo.<Active skills>1. Healing Light: Restores entire partys HP/ MP/ CP with a chance to cancel debuffs. Cooldown: 35 min.2. Balanced Power: MEN +1.3. Attribute Enchant: Attribute Resistance +5.',
    'is_trade' => 0,
    'is_drop' => 0,
    'is_destruct' => 1,
    'crystal_type' => 'r',
    'consume_type' => 'consume_type_normal',
  ],
  23991 => 
  [
    'item_id' => 23991,
    'icon' => 'accessary_lbracelet_sign_agathion_aug_i00',
    'name' => 'Agathion Virgo',
    'additionalname' => 'Lv. 3',
    'description' => 'A bracelet for summoning Agathion Virgo.<Active skills>1. Healing Light: Restores entire partys HP/ MP/ CP with a chance to cancel debuffs. Cooldown: 32 min. 30 sec.2. Balanced Power: MEN +1.3. Attribute Enchant: Attribute Resistance +10.',
    'is_trade' => 0,
    'is_drop' => 0,
    'is_destruct' => 1,
    'crystal_type' => 'r',
    'consume_type' => 'consume_type_normal',
  ],
  23992 => 
  [
    'item_id' => 23992,
    'icon' => 'accessary_lbracelet_sign_agathion_aug_i00',
    'name' => 'Agathion Virgo',
    'additionalname' => 'Lv. 4',
    'description' => 'A bracelet for summoning Agathion Virgo.<Active skills>1. Healing Light: Restores entire partys HP/ MP/ CP with a chance to cancel debuffs. Cooldown: 30 min.2. Balanced Power: CON/ MEN +1.3. Attribute Enchant: Attribute Resistance +10.',
    'is_trade' => 0,
    'is_drop' => 0,
    'is_destruct' => 1,
    'crystal_type' => 'r',
    'consume_type' => 'consume_type_normal',
  ],
  23993 => 
  [
    'item_id' => 23993,
    'icon' => 'accessary_lbracelet_sign_agathion_aug_i00',
    'name' => 'Agathion Virgo',
    'additionalname' => 'Lv. 5',
    'description' => 'A bracelet for summoning Agathion Virgo.<Active skills>1. Healing Light: Restores entire partys HP/ MP/ CP with a chance to cancel debuffs. Cooldown: 27 min. 30 sec.2. Balanced Power: CON/ MEN +1.3. Attribute Enchant: Attribute Resistance +15.',
    'is_trade' => 0,
    'is_drop' => 0,
    'is_destruct' => 1,
    'crystal_type' => 'r',
    'consume_type' => 'consume_type_normal',
  ],
  23994 => 
  [
    'item_id' => 23994,
    'icon' => 'accessary_lbracelet_sign_agathion_aug_i00',
    'name' => 'Agathion Virgo',
    'additionalname' => 'Lv. 6',
    'description' => 'A bracelet for summoning Agathion Virgo.<Active skills>1. Healing Light: Restores entire partys HP/ MP/ CP with a chance to cancel debuffs. Cooldown: 25 min.2. Balanced Power: CON/ WIT/ MEN +1.3. Attribute Enchant: Attribute Resistance +15.',
    'is_trade' => 0,
    'is_drop' => 0,
    'is_destruct' => 1,
    'crystal_type' => 'r',
    'consume_type' => 'consume_type_normal',
  ],
  23995 => 
  [
    'item_id' => 23995,
    'icon' => 'accessary_lbracelet_sign_agathion_aug_i00',
    'name' => 'Agathion Virgo',
    'additionalname' => 'Lv. 7',
    'description' => 'A bracelet for summoning Agathion Virgo.<Active skills>1. Healing Light: Restores entire partys HP/ MP/ CP with a chance to cancel debuffs. Cooldown: 22 min. 30 sec.2. Balanced Power: CON/ WIT/ MEN +1.3. Attribute Enchant: Attribute Resistance +20.',
    'is_trade' => 0,
    'is_drop' => 0,
    'is_destruct' => 1,
    'crystal_type' => 'r',
    'consume_type' => 'consume_type_normal',
  ],
  23996 => 
  [
    'item_id' => 23996,
    'icon' => 'accessary_lbracelet_sign_agathion_aug_i00',
    'name' => 'Agathion Virgo',
    'additionalname' => 'Lv. 8',
    'description' => 'A bracelet for summoning Agathion Virgo.<Active skills>1. Healing Light: Restores entire partys HP/ MP/ CP with a chance to cancel debuffs. Cooldown: 20 min.2. Balanced Power: CON/ DEX/ WIT/ MEN +1.3. Attribute Enchant: Attribute Resistance +20.',
    'is_trade' => 0,
    'is_drop' => 0,
    'is_destruct' => 1,
    'crystal_type' => 'r',
    'consume_type' => 'consume_type_normal',
  ],
  23997 => 
  [
    'item_id' => 23997,
    'icon' => 'accessary_lbracelet_sign_agathion_aug_i00',
    'name' => 'Agathion Virgo',
    'additionalname' => 'Lv. 9',
    'description' => 'A bracelet for summoning Agathion Virgo.<Active skills>1. Healing Light: Restores entire partys HP/ MP/ CP with a chance to cancel debuffs. Cooldown: 17 min. 30 sec.2. Balanced Power: CON/ DEX/ WIT/ MEN +1.3. Attribute Enchant: Attribute Resistance +25.',
    'is_trade' => 0,
    'is_drop' => 0,
    'is_destruct' => 1,
    'crystal_type' => 'r',
    'consume_type' => 'consume_type_normal',
  ],
  23998 => 
  [
    'item_id' => 23998,
    'icon' => 'accessary_lbracelet_sign_agathion_aug_i00',
    'name' => 'Agathion Virgo',
    'additionalname' => 'Lv. 10',
    'description' => 'A bracelet for summoning Agathion Virgo.<Active skills>1. Healing Light: Restores entire partys HP/ MP/ CP with a chance to cancel debuffs. Cooldown: 15 min.2. Balanced Power: INT/ CON/ DEX/ WIT/ MEN +1.3. Attribute Enchant: Attribute Resistance +25.',
    'is_trade' => 0,
    'is_drop' => 0,
    'is_destruct' => 1,
    'crystal_type' => 'r',
    'consume_type' => 'consume_type_normal',
  ],
  23999 => 
  [
    'item_id' => 23999,
    'icon' => 'accessary_lbracelet_sign_agathion_aug_i00',
    'name' => 'Agathion Virgo',
    'additionalname' => 'Lv. 11',
    'description' => 'A bracelet for summoning Agathion Virgo.<Active skills>1. Healing Light: Restores entire partys HP/ MP/ CP with a chance to cancel debuffs. Cooldown: 12 min. 30 sec.2. Balanced Power: INT/ CON/ DEX/ WIT/ MEN +1.3. Attribute Enchant: Attribute Resistance +30.',
    'is_trade' => 0,
    'is_drop' => 0,
    'is_destruct' => 1,
    'crystal_type' => 'r',
    'consume_type' => 'consume_type_normal',
  ],
];