<?php return [
  24900 => 
  [
    'item_id' => 24900,
    'icon' => 'g_co_swimsuit_event_03',
    'name' => 'Seductive Swimsuit',
    'additionalname' => 'Mid-grade / Debuff Reflect',
    'description' => 'When modified, Debuff Reflect + 5%.',
    'is_trade' => 0,
    'is_drop' => 0,
    'is_destruct' => 1,
    'crystal_type' => 'none',
    'consume_type' => 'consume_type_normal',
  ],
  24901 => 
  [
    'item_id' => 24901,
    'icon' => 'g_co_swimsuit_event_03',
    'name' => 'Seductive Swimsuit',
    'additionalname' => 'Mid-grade / Damage Reflect Resistance',
    'description' => 'When modified, Debuff Reflect Resistance + 7%.',
    'is_trade' => 0,
    'is_drop' => 0,
    'is_destruct' => 1,
    'crystal_type' => 'none',
    'consume_type' => 'consume_type_normal',
  ],
  24902 => 
  [
    'item_id' => 24902,
    'icon' => 'g_co_swimsuit_event_03',
    'name' => 'Seductive Swimsuit',
    'additionalname' => 'Mid-grade / Ranged Resistance',
    'description' => 'When modified, Bow/Crossbow Resistance + 5%.',
    'is_trade' => 0,
    'is_drop' => 0,
    'is_destruct' => 1,
    'crystal_type' => 'none',
    'consume_type' => 'consume_type_normal',
  ],
  24903 => 
  [
    'item_id' => 24903,
    'icon' => 'g_co_swimsuit_event_03',
    'name' => 'Seductive Swimsuit',
    'additionalname' => 'Mid-grade / P. Def. Increase',
    'description' => 'When modified, P. Def. + 5%.',
    'is_trade' => 0,
    'is_drop' => 0,
    'is_destruct' => 1,
    'crystal_type' => 'none',
    'consume_type' => 'consume_type_normal',
  ],
  24904 => 
  [
    'item_id' => 24904,
    'icon' => 'g_co_swimsuit_event_03',
    'name' => 'Seductive Swimsuit',
    'additionalname' => 'Mid-grade / M. Def. Increase',
    'description' => 'When modified, M. Def. + 5%.',
    'is_trade' => 0,
    'is_drop' => 0,
    'is_destruct' => 1,
    'crystal_type' => 'none',
    'consume_type' => 'consume_type_normal',
  ],
  24905 => 
  [
    'item_id' => 24905,
    'icon' => 'g_co_swimsuit_event_03',
    'name' => 'Seductive Swimsuit',
    'additionalname' => 'Mid-grade / Attribute Resistance',
    'description' => 'When modified, Attribute Resistance + 7.',
    'is_trade' => 0,
    'is_drop' => 0,
    'is_destruct' => 1,
    'crystal_type' => 'none',
    'consume_type' => 'consume_type_normal',
  ],
  24906 => 
  [
    'item_id' => 24906,
    'icon' => 'g_co_swimsuit_event_03',
    'name' => 'Seductive Swimsuit',
    'additionalname' => 'Mid-grade / Received Heal Amount Increase',
    'description' => 'When modified, Received Heal Amount + 7%.',
    'is_trade' => 0,
    'is_drop' => 0,
    'is_destruct' => 1,
    'crystal_type' => 'none',
    'consume_type' => 'consume_type_normal',
  ],
  24907 => 
  [
    'item_id' => 24907,
    'icon' => 'g_co_swimsuit_event_03',
    'name' => 'Seductive Swimsuit',
    'additionalname' => 'Mid-grade / Max. HP Increase',
    'description' => 'When modified, Max. HP + 7%.',
    'is_trade' => 0,
    'is_drop' => 0,
    'is_destruct' => 1,
    'crystal_type' => 'none',
    'consume_type' => 'consume_type_normal',
  ],
  24908 => 
  [
    'item_id' => 24908,
    'icon' => 'g_co_swimsuit_event_03',
    'name' => 'Seductive Swimsuit',
    'additionalname' => 'Mid-grade / Max. MP Increase',
    'description' => 'When modified, Max. MP + 5%.',
    'is_trade' => 0,
    'is_drop' => 0,
    'is_destruct' => 1,
    'crystal_type' => 'none',
    'consume_type' => 'consume_type_normal',
  ],
  24909 => 
  [
    'item_id' => 24909,
    'icon' => 'g_co_swimsuit_event_03',
    'name' => 'Seductive Swimsuit',
    'additionalname' => 'Mid-grade / Max CP Increase',
    'description' => 'When modified, Max. CP + 7%.',
    'is_trade' => 0,
    'is_drop' => 0,
    'is_destruct' => 1,
    'crystal_type' => 'none',
    'consume_type' => 'consume_type_normal',
  ],
  24910 => 
  [
    'item_id' => 24910,
    'icon' => 'g_co_swimsuit_event_03',
    'name' => 'Seductive Swimsuit',
    'additionalname' => 'Mid-grade / Speed Increase',
    'description' => 'When modified, Speed + 7.',
    'is_trade' => 0,
    'is_drop' => 0,
    'is_destruct' => 1,
    'crystal_type' => 'none',
    'consume_type' => 'consume_type_normal',
  ],
  24911 => 
  [
    'item_id' => 24911,
    'icon' => 'g_co_swimsuit_event_03',
    'name' => 'Seductive Swimsuit',
    'additionalname' => 'Mid-grade / HP Recovery Bonus Increase',
    'description' => 'When modified, HP Recovery Bonus + 8.',
    'is_trade' => 0,
    'is_drop' => 0,
    'is_destruct' => 1,
    'crystal_type' => 'none',
    'consume_type' => 'consume_type_normal',
  ],
  24912 => 
  [
    'item_id' => 24912,
    'icon' => 'g_co_swimsuit_event_03',
    'name' => 'Seductive Swimsuit',
    'additionalname' => 'Mid-grade / MP Recovery Bonus Increase',
    'description' => 'When modified, MP Recovery Bonus + 4.',
    'is_trade' => 0,
    'is_drop' => 0,
    'is_destruct' => 1,
    'crystal_type' => 'none',
    'consume_type' => 'consume_type_normal',
  ],
  24913 => 
  [
    'item_id' => 24913,
    'icon' => 'g_co_swimsuit_event_03',
    'name' => 'Seductive Swimsuit',
    'additionalname' => 'Mid-grade / Evasion Increase',
    'description' => 'When modified, P./M. Evasion + 4.',
    'is_trade' => 0,
    'is_drop' => 0,
    'is_destruct' => 1,
    'crystal_type' => 'none',
    'consume_type' => 'consume_type_normal',
  ],
  24914 => 
  [
    'item_id' => 24914,
    'icon' => 'g_co_swimsuit_event_03',
    'name' => 'Seductive Swimsuit',
    'additionalname' => 'Mid-grade / Option 15',
    'description' => 'When modified, Mid-grade / Option + 15.',
    'is_trade' => 0,
    'is_drop' => 0,
    'is_destruct' => 1,
    'crystal_type' => 'none',
    'consume_type' => 'consume_type_normal',
  ],
  24915 => 
  [
    'item_id' => 24915,
    'icon' => 'g_co_swimsuit_event_03',
    'name' => 'Seductive Swimsuit',
    'additionalname' => 'Mid-grade / Option 16',
    'description' => 'When modified, Mid-grade / Option + 16.',
    'is_trade' => 0,
    'is_drop' => 0,
    'is_destruct' => 1,
    'crystal_type' => 'none',
    'consume_type' => 'consume_type_normal',
  ],
  24916 => 
  [
    'item_id' => 24916,
    'icon' => 'g_co_swimsuit_event_03',
    'name' => 'Seductive Swimsuit',
    'additionalname' => 'Mid-grade / Option 17',
    'description' => 'When modified, Mid-grade / Option + 17.',
    'is_trade' => 0,
    'is_drop' => 0,
    'is_destruct' => 1,
    'crystal_type' => 'none',
    'consume_type' => 'consume_type_normal',
  ],
  24917 => 
  [
    'item_id' => 24917,
    'icon' => 'g_co_swimsuit_event_03',
    'name' => 'Seductive Swimsuit',
    'additionalname' => 'Mid-grade / Option 18',
    'description' => 'When modified, Mid-grade / Option + 18.',
    'is_trade' => 0,
    'is_drop' => 0,
    'is_destruct' => 1,
    'crystal_type' => 'none',
    'consume_type' => 'consume_type_normal',
  ],
  24918 => 
  [
    'item_id' => 24918,
    'icon' => 'g_co_swimsuit_event_03',
    'name' => 'Seductive Swimsuit',
    'additionalname' => 'Mid-grade / Option 19',
    'description' => 'When modified, Mid-grade / Option + 19.',
    'is_trade' => 0,
    'is_drop' => 0,
    'is_destruct' => 1,
    'crystal_type' => 'none',
    'consume_type' => 'consume_type_normal',
  ],
  24919 => 
  [
    'item_id' => 24919,
    'icon' => 'g_co_swimsuit_event_03',
    'name' => 'Seductive Swimsuit',
    'additionalname' => 'Mid-grade / Option 20',
    'description' => 'When modified, Mid-grade / Option + 20.',
    'is_trade' => 0,
    'is_drop' => 0,
    'is_destruct' => 1,
    'crystal_type' => 'none',
    'consume_type' => 'consume_type_normal',
  ],
  24920 => 
  [
    'item_id' => 24920,
    'icon' => 'g_co_swimsuit_event_03',
    'name' => 'Seductive Swimsuit',
    'additionalname' => 'Top-grade / Debuff Reflect',
    'description' => 'When modified, Debuff Reflect + 10%.',
    'is_trade' => 0,
    'is_drop' => 0,
    'is_destruct' => 1,
    'crystal_type' => 'none',
    'consume_type' => 'consume_type_normal',
  ],
  24921 => 
  [
    'item_id' => 24921,
    'icon' => 'g_co_swimsuit_event_03',
    'name' => 'Seductive Swimsuit',
    'additionalname' => 'Top-grade / Damage Reflect Resistance',
    'description' => 'When modified, Debuff Reflect Resistance + 15%.',
    'is_trade' => 0,
    'is_drop' => 0,
    'is_destruct' => 1,
    'crystal_type' => 'none',
    'consume_type' => 'consume_type_normal',
  ],
  24922 => 
  [
    'item_id' => 24922,
    'icon' => 'g_co_swimsuit_event_03',
    'name' => 'Seductive Swimsuit',
    'additionalname' => 'Top-grade / Ranged Resistance',
    'description' => 'When modified, Bow/Crossbow Resistance + 10%.',
    'is_trade' => 0,
    'is_drop' => 0,
    'is_destruct' => 1,
    'crystal_type' => 'none',
    'consume_type' => 'consume_type_normal',
  ],
  24923 => 
  [
    'item_id' => 24923,
    'icon' => 'g_co_swimsuit_event_03',
    'name' => 'Seductive Swimsuit',
    'additionalname' => 'Top-grade / P. Def. Increase',
    'description' => 'When modified, P. Def. + 10%.',
    'is_trade' => 0,
    'is_drop' => 0,
    'is_destruct' => 1,
    'crystal_type' => 'none',
    'consume_type' => 'consume_type_normal',
  ],
  24924 => 
  [
    'item_id' => 24924,
    'icon' => 'g_co_swimsuit_event_03',
    'name' => 'Seductive Swimsuit',
    'additionalname' => 'Top-grade / M. Def. Increase',
    'description' => 'When modified, M. Def. + 10%.',
    'is_trade' => 0,
    'is_drop' => 0,
    'is_destruct' => 1,
    'crystal_type' => 'none',
    'consume_type' => 'consume_type_normal',
  ],
  24925 => 
  [
    'item_id' => 24925,
    'icon' => 'g_co_swimsuit_event_03',
    'name' => 'Seductive Swimsuit',
    'additionalname' => 'Top-grade / Attribute Resistance',
    'description' => 'When modified, Attribute Resistance + 15.',
    'is_trade' => 0,
    'is_drop' => 0,
    'is_destruct' => 1,
    'crystal_type' => 'none',
    'consume_type' => 'consume_type_normal',
  ],
  24926 => 
  [
    'item_id' => 24926,
    'icon' => 'g_co_swimsuit_event_03',
    'name' => 'Seductive Swimsuit',
    'additionalname' => 'Top-grade / Received Heal Amount Increase',
    'description' => 'When modified, Received Heal Amount + 15%.',
    'is_trade' => 0,
    'is_drop' => 0,
    'is_destruct' => 1,
    'crystal_type' => 'none',
    'consume_type' => 'consume_type_normal',
  ],
  24927 => 
  [
    'item_id' => 24927,
    'icon' => 'g_co_swimsuit_event_03',
    'name' => 'Seductive Swimsuit',
    'additionalname' => 'Top-grade / Max. HP Increase',
    'description' => 'When modified, Max. HP + 15%.',
    'is_trade' => 0,
    'is_drop' => 0,
    'is_destruct' => 1,
    'crystal_type' => 'none',
    'consume_type' => 'consume_type_normal',
  ],
  24928 => 
  [
    'item_id' => 24928,
    'icon' => 'g_co_swimsuit_event_03',
    'name' => 'Seductive Swimsuit',
    'additionalname' => 'Top-grade / Max. MP Increase',
    'description' => 'When modified, Max. MP + 10%.',
    'is_trade' => 0,
    'is_drop' => 0,
    'is_destruct' => 1,
    'crystal_type' => 'none',
    'consume_type' => 'consume_type_normal',
  ],
  24929 => 
  [
    'item_id' => 24929,
    'icon' => 'g_co_swimsuit_event_03',
    'name' => 'Seductive Swimsuit',
    'additionalname' => 'Top-grade / Max CP Increase',
    'description' => 'When modified, Max. CP + 15%.',
    'is_trade' => 0,
    'is_drop' => 0,
    'is_destruct' => 1,
    'crystal_type' => 'none',
    'consume_type' => 'consume_type_normal',
  ],
  24930 => 
  [
    'item_id' => 24930,
    'icon' => 'g_co_swimsuit_event_03',
    'name' => 'Seductive Swimsuit',
    'additionalname' => 'Top-grade / Speed Increase',
    'description' => 'When modified, Speed + 15.',
    'is_trade' => 0,
    'is_drop' => 0,
    'is_destruct' => 1,
    'crystal_type' => 'none',
    'consume_type' => 'consume_type_normal',
  ],
  24931 => 
  [
    'item_id' => 24931,
    'icon' => 'g_co_swimsuit_event_03',
    'name' => 'Seductive Swimsuit',
    'additionalname' => 'Top-grade / HP Recovery Bonus Increase',
    'description' => 'When modified, HP Recovery Bonus + 16.',
    'is_trade' => 0,
    'is_drop' => 0,
    'is_destruct' => 1,
    'crystal_type' => 'none',
    'consume_type' => 'consume_type_normal',
  ],
  24932 => 
  [
    'item_id' => 24932,
    'icon' => 'g_co_swimsuit_event_03',
    'name' => 'Seductive Swimsuit',
    'additionalname' => 'Top-grade / MP Recovery Bonus Increase',
    'description' => 'When modified, MP Recovery Bonus + 8.',
    'is_trade' => 0,
    'is_drop' => 0,
    'is_destruct' => 1,
    'crystal_type' => 'none',
    'consume_type' => 'consume_type_normal',
  ],
  24933 => 
  [
    'item_id' => 24933,
    'icon' => 'g_co_swimsuit_event_03',
    'name' => 'Seductive Swimsuit',
    'additionalname' => 'Top-grade / Evasion Increase',
    'description' => 'When modified, P./M. Evasion + 8.',
    'is_trade' => 0,
    'is_drop' => 0,
    'is_destruct' => 1,
    'crystal_type' => 'none',
    'consume_type' => 'consume_type_normal',
  ],
  24934 => 
  [
    'item_id' => 24934,
    'icon' => 'g_co_swimsuit_event_03',
    'name' => 'Seductive Swimsuit',
    'additionalname' => 'Top-grade / Option 15',
    'description' => 'When modified, Top-grade / Option + 15.',
    'is_trade' => 0,
    'is_drop' => 0,
    'is_destruct' => 1,
    'crystal_type' => 'none',
    'consume_type' => 'consume_type_normal',
  ],
  24935 => 
  [
    'item_id' => 24935,
    'icon' => 'g_co_swimsuit_event_03',
    'name' => 'Seductive Swimsuit',
    'additionalname' => 'Top-grade / Option 16',
    'description' => 'When modified, Top-grade / Option + 16.',
    'is_trade' => 0,
    'is_drop' => 0,
    'is_destruct' => 1,
    'crystal_type' => 'none',
    'consume_type' => 'consume_type_normal',
  ],
  24936 => 
  [
    'item_id' => 24936,
    'icon' => 'g_co_swimsuit_event_03',
    'name' => 'Seductive Swimsuit',
    'additionalname' => 'Top-grade / Option 17',
    'description' => 'When modified, Top-grade / Option + 17.',
    'is_trade' => 0,
    'is_drop' => 0,
    'is_destruct' => 1,
    'crystal_type' => 'none',
    'consume_type' => 'consume_type_normal',
  ],
  24937 => 
  [
    'item_id' => 24937,
    'icon' => 'g_co_swimsuit_event_03',
    'name' => 'Seductive Swimsuit',
    'additionalname' => 'Top-grade / Option 18',
    'description' => 'When modified, Top-grade / Option + 18.',
    'is_trade' => 0,
    'is_drop' => 0,
    'is_destruct' => 1,
    'crystal_type' => 'none',
    'consume_type' => 'consume_type_normal',
  ],
  24938 => 
  [
    'item_id' => 24938,
    'icon' => 'g_co_swimsuit_event_03',
    'name' => 'Seductive Swimsuit',
    'additionalname' => 'Top-grade / Option 19',
    'description' => 'When modified, Top-grade / Option + 19.',
    'is_trade' => 0,
    'is_drop' => 0,
    'is_destruct' => 1,
    'crystal_type' => 'none',
    'consume_type' => 'consume_type_normal',
  ],
  24939 => 
  [
    'item_id' => 24939,
    'icon' => 'g_co_swimsuit_event_03',
    'name' => 'Seductive Swimsuit',
    'additionalname' => 'Top-grade / Option 20',
    'description' => 'When modified, Top-grade / Option + 20.',
    'is_trade' => 0,
    'is_drop' => 0,
    'is_destruct' => 1,
    'crystal_type' => 'none',
    'consume_type' => 'consume_type_normal',
  ],
  24940 => 
  [
    'item_id' => 24940,
    'icon' => 'armor_ev_santas_clothes',
    'name' => 'Santa Outfit',
    'additionalname' => 'Low-grade / Debuff Reflect',
    'description' => 'When modified, Debuff Reflect + 3%.',
    'is_trade' => 0,
    'is_drop' => 0,
    'is_destruct' => 1,
    'crystal_type' => 'none',
    'consume_type' => 'consume_type_normal',
  ],
  24941 => 
  [
    'item_id' => 24941,
    'icon' => 'armor_ev_santas_clothes',
    'name' => 'Santa Outfit',
    'additionalname' => 'Low-grade / Damage Reflect Resistance',
    'description' => 'When modified, Debuff Reflect Resistance + 5%.',
    'is_trade' => 0,
    'is_drop' => 0,
    'is_destruct' => 1,
    'crystal_type' => 'none',
    'consume_type' => 'consume_type_normal',
  ],
  24942 => 
  [
    'item_id' => 24942,
    'icon' => 'armor_ev_santas_clothes',
    'name' => 'Santa Outfit',
    'additionalname' => 'Low-grade / Ranged Resistance',
    'description' => 'When modified, Bow/Crossbow Resistance + 3%.',
    'is_trade' => 0,
    'is_drop' => 0,
    'is_destruct' => 1,
    'crystal_type' => 'none',
    'consume_type' => 'consume_type_normal',
  ],
  24943 => 
  [
    'item_id' => 24943,
    'icon' => 'armor_ev_santas_clothes',
    'name' => 'Santa Outfit',
    'additionalname' => 'Low-grade / P. Def. Increase',
    'description' => 'When modified, P. Def. + 3%.',
    'is_trade' => 0,
    'is_drop' => 0,
    'is_destruct' => 1,
    'crystal_type' => 'none',
    'consume_type' => 'consume_type_normal',
  ],
  24944 => 
  [
    'item_id' => 24944,
    'icon' => 'armor_ev_santas_clothes',
    'name' => 'Santa Outfit',
    'additionalname' => 'Low-grade / M. Def. Increase',
    'description' => 'When modified, M. Def. + 3%.',
    'is_trade' => 0,
    'is_drop' => 0,
    'is_destruct' => 1,
    'crystal_type' => 'none',
    'consume_type' => 'consume_type_normal',
  ],
  24945 => 
  [
    'item_id' => 24945,
    'icon' => 'armor_ev_santas_clothes',
    'name' => 'Santa Outfit',
    'additionalname' => 'Low-grade / Attribute Resistance',
    'description' => 'When modified, Attribute Resistance + 5.',
    'is_trade' => 0,
    'is_drop' => 0,
    'is_destruct' => 1,
    'crystal_type' => 'none',
    'consume_type' => 'consume_type_normal',
  ],
  24946 => 
  [
    'item_id' => 24946,
    'icon' => 'armor_ev_santas_clothes',
    'name' => 'Santa Outfit',
    'additionalname' => 'Low-grade / Received Heal Amount Increase',
    'description' => 'When modified, Received Heal Amount + 3%.',
    'is_trade' => 0,
    'is_drop' => 0,
    'is_destruct' => 1,
    'crystal_type' => 'none',
    'consume_type' => 'consume_type_normal',
  ],
  24947 => 
  [
    'item_id' => 24947,
    'icon' => 'armor_ev_santas_clothes',
    'name' => 'Santa Outfit',
    'additionalname' => 'Low-grade / Max. HP Increase',
    'description' => 'When modified, Max. HP + 3%.',
    'is_trade' => 0,
    'is_drop' => 0,
    'is_destruct' => 1,
    'crystal_type' => 'none',
    'consume_type' => 'consume_type_normal',
  ],
  24948 => 
  [
    'item_id' => 24948,
    'icon' => 'armor_ev_santas_clothes',
    'name' => 'Santa Outfit',
    'additionalname' => 'Low-grade / Max. MP Increase',
    'description' => 'When modified, Max. MP + 3%.',
    'is_trade' => 0,
    'is_drop' => 0,
    'is_destruct' => 1,
    'crystal_type' => 'none',
    'consume_type' => 'consume_type_normal',
  ],
  24949 => 
  [
    'item_id' => 24949,
    'icon' => 'armor_ev_santas_clothes',
    'name' => 'Santa Outfit',
    'additionalname' => 'Low-grade / Max CP Increase',
    'description' => 'When modified, Max. CP + 3%.',
    'is_trade' => 0,
    'is_drop' => 0,
    'is_destruct' => 1,
    'crystal_type' => 'none',
    'consume_type' => 'consume_type_normal',
  ],
  24950 => 
  [
    'item_id' => 24950,
    'icon' => 'armor_ev_santas_clothes',
    'name' => 'Santa Outfit',
    'additionalname' => 'Low-grade / Speed Increase',
    'description' => 'When modified, Speed + 3.',
    'is_trade' => 0,
    'is_drop' => 0,
    'is_destruct' => 1,
    'crystal_type' => 'none',
    'consume_type' => 'consume_type_normal',
  ],
  24951 => 
  [
    'item_id' => 24951,
    'icon' => 'armor_ev_santas_clothes',
    'name' => 'Santa Outfit',
    'additionalname' => 'Low-grade / HP Recovery Bonus Increase',
    'description' => 'When modified, HP Recovery Bonus + 5.',
    'is_trade' => 0,
    'is_drop' => 0,
    'is_destruct' => 1,
    'crystal_type' => 'none',
    'consume_type' => 'consume_type_normal',
  ],
  24952 => 
  [
    'item_id' => 24952,
    'icon' => 'armor_ev_santas_clothes',
    'name' => 'Santa Outfit',
    'additionalname' => 'Low-grade / MP Recovery Bonus Increase',
    'description' => 'When modified, MP Recovery Bonus + 3.',
    'is_trade' => 0,
    'is_drop' => 0,
    'is_destruct' => 1,
    'crystal_type' => 'none',
    'consume_type' => 'consume_type_normal',
  ],
  24953 => 
  [
    'item_id' => 24953,
    'icon' => 'armor_ev_santas_clothes',
    'name' => 'Santa Outfit',
    'additionalname' => 'Low-grade / Evasion Increase',
    'description' => 'When modified, P./M. Evasion + 3.',
    'is_trade' => 0,
    'is_drop' => 0,
    'is_destruct' => 1,
    'crystal_type' => 'none',
    'consume_type' => 'consume_type_normal',
  ],
  24954 => 
  [
    'item_id' => 24954,
    'icon' => 'armor_ev_santas_clothes',
    'name' => 'Santa Outfit',
    'additionalname' => 'Low-grade / Option 15',
    'description' => 'When modified, Low-grade / Option + 15.',
    'is_trade' => 0,
    'is_drop' => 0,
    'is_destruct' => 1,
    'crystal_type' => 'none',
    'consume_type' => 'consume_type_normal',
  ],
  24955 => 
  [
    'item_id' => 24955,
    'icon' => 'armor_ev_santas_clothes',
    'name' => 'Santa Outfit',
    'additionalname' => 'Low-grade / Option 16',
    'description' => 'When modified, Low-grade / Option + 16.',
    'is_trade' => 0,
    'is_drop' => 0,
    'is_destruct' => 1,
    'crystal_type' => 'none',
    'consume_type' => 'consume_type_normal',
  ],
  24956 => 
  [
    'item_id' => 24956,
    'icon' => 'armor_ev_santas_clothes',
    'name' => 'Santa Outfit',
    'additionalname' => 'Low-grade / Option 17',
    'description' => 'When modified, Low-grade / Option + 17.',
    'is_trade' => 0,
    'is_drop' => 0,
    'is_destruct' => 1,
    'crystal_type' => 'none',
    'consume_type' => 'consume_type_normal',
  ],
  24957 => 
  [
    'item_id' => 24957,
    'icon' => 'armor_ev_santas_clothes',
    'name' => 'Santa Outfit',
    'additionalname' => 'Low-grade / Option 18',
    'description' => 'When modified, Low-grade / Option + 18.',
    'is_trade' => 0,
    'is_drop' => 0,
    'is_destruct' => 1,
    'crystal_type' => 'none',
    'consume_type' => 'consume_type_normal',
  ],
  24958 => 
  [
    'item_id' => 24958,
    'icon' => 'armor_ev_santas_clothes',
    'name' => 'Santa Outfit',
    'additionalname' => 'Low-grade / Option 19',
    'description' => 'When modified, Low-grade / Option + 19.',
    'is_trade' => 0,
    'is_drop' => 0,
    'is_destruct' => 1,
    'crystal_type' => 'none',
    'consume_type' => 'consume_type_normal',
  ],
  24959 => 
  [
    'item_id' => 24959,
    'icon' => 'armor_ev_santas_clothes',
    'name' => 'Santa Outfit',
    'additionalname' => 'Low-grade / Option 20',
    'description' => 'When modified, Low-grade / Option + 20.',
    'is_trade' => 0,
    'is_drop' => 0,
    'is_destruct' => 1,
    'crystal_type' => 'none',
    'consume_type' => 'consume_type_normal',
  ],
  24960 => 
  [
    'item_id' => 24960,
    'icon' => 'armor_ev_santas_clothes',
    'name' => 'Santa Outfit',
    'additionalname' => 'Mid-grade / Debuff Reflect',
    'description' => 'When modified, Debuff Reflect + 5%.',
    'is_trade' => 0,
    'is_drop' => 0,
    'is_destruct' => 1,
    'crystal_type' => 'none',
    'consume_type' => 'consume_type_normal',
  ],
  24961 => 
  [
    'item_id' => 24961,
    'icon' => 'armor_ev_santas_clothes',
    'name' => 'Santa Outfit',
    'additionalname' => 'Mid-grade / Damage Reflect Resistance',
    'description' => 'When modified, Debuff Reflect Resistance + 7%.',
    'is_trade' => 0,
    'is_drop' => 0,
    'is_destruct' => 1,
    'crystal_type' => 'none',
    'consume_type' => 'consume_type_normal',
  ],
  24962 => 
  [
    'item_id' => 24962,
    'icon' => 'armor_ev_santas_clothes',
    'name' => 'Santa Outfit',
    'additionalname' => 'Mid-grade / Ranged Resistance',
    'description' => 'When modified, Bow/Crossbow Resistance + 5%.',
    'is_trade' => 0,
    'is_drop' => 0,
    'is_destruct' => 1,
    'crystal_type' => 'none',
    'consume_type' => 'consume_type_normal',
  ],
  24963 => 
  [
    'item_id' => 24963,
    'icon' => 'armor_ev_santas_clothes',
    'name' => 'Santa Outfit',
    'additionalname' => 'Mid-grade / P. Def. Increase',
    'description' => 'When modified, P. Def. + 5%.',
    'is_trade' => 0,
    'is_drop' => 0,
    'is_destruct' => 1,
    'crystal_type' => 'none',
    'consume_type' => 'consume_type_normal',
  ],
  24964 => 
  [
    'item_id' => 24964,
    'icon' => 'armor_ev_santas_clothes',
    'name' => 'Santa Outfit',
    'additionalname' => 'Mid-grade / M. Def. Increase',
    'description' => 'When modified, M. Def. + 5%.',
    'is_trade' => 0,
    'is_drop' => 0,
    'is_destruct' => 1,
    'crystal_type' => 'none',
    'consume_type' => 'consume_type_normal',
  ],
  24965 => 
  [
    'item_id' => 24965,
    'icon' => 'armor_ev_santas_clothes',
    'name' => 'Santa Outfit',
    'additionalname' => 'Mid-grade / Attribute Resistance',
    'description' => 'When modified, Attribute Resistance + 7.',
    'is_trade' => 0,
    'is_drop' => 0,
    'is_destruct' => 1,
    'crystal_type' => 'none',
    'consume_type' => 'consume_type_normal',
  ],
  24966 => 
  [
    'item_id' => 24966,
    'icon' => 'armor_ev_santas_clothes',
    'name' => 'Santa Outfit',
    'additionalname' => 'Mid-grade / Received Heal Amount Increase',
    'description' => 'When modified, Received Heal Amount + 7%.',
    'is_trade' => 0,
    'is_drop' => 0,
    'is_destruct' => 1,
    'crystal_type' => 'none',
    'consume_type' => 'consume_type_normal',
  ],
  24967 => 
  [
    'item_id' => 24967,
    'icon' => 'armor_ev_santas_clothes',
    'name' => 'Santa Outfit',
    'additionalname' => 'Mid-grade / Max. HP Increase',
    'description' => 'When modified, Max. HP + 7%.',
    'is_trade' => 0,
    'is_drop' => 0,
    'is_destruct' => 1,
    'crystal_type' => 'none',
    'consume_type' => 'consume_type_normal',
  ],
  24968 => 
  [
    'item_id' => 24968,
    'icon' => 'armor_ev_santas_clothes',
    'name' => 'Santa Outfit',
    'additionalname' => 'Mid-grade / Max. MP Increase',
    'description' => 'When modified, Max. MP + 5%.',
    'is_trade' => 0,
    'is_drop' => 0,
    'is_destruct' => 1,
    'crystal_type' => 'none',
    'consume_type' => 'consume_type_normal',
  ],
  24969 => 
  [
    'item_id' => 24969,
    'icon' => 'armor_ev_santas_clothes',
    'name' => 'Santa Outfit',
    'additionalname' => 'Mid-grade / Max CP Increase',
    'description' => 'When modified, Max. CP + 7%.',
    'is_trade' => 0,
    'is_drop' => 0,
    'is_destruct' => 1,
    'crystal_type' => 'none',
    'consume_type' => 'consume_type_normal',
  ],
  24970 => 
  [
    'item_id' => 24970,
    'icon' => 'armor_ev_santas_clothes',
    'name' => 'Santa Outfit',
    'additionalname' => 'Mid-grade / Speed Increase',
    'description' => 'When modified, Speed + 7.',
    'is_trade' => 0,
    'is_drop' => 0,
    'is_destruct' => 1,
    'crystal_type' => 'none',
    'consume_type' => 'consume_type_normal',
  ],
  24971 => 
  [
    'item_id' => 24971,
    'icon' => 'armor_ev_santas_clothes',
    'name' => 'Santa Outfit',
    'additionalname' => 'Mid-grade / HP Recovery Bonus Increase',
    'description' => 'When modified, HP Recovery Bonus + 8.',
    'is_trade' => 0,
    'is_drop' => 0,
    'is_destruct' => 1,
    'crystal_type' => 'none',
    'consume_type' => 'consume_type_normal',
  ],
  24972 => 
  [
    'item_id' => 24972,
    'icon' => 'armor_ev_santas_clothes',
    'name' => 'Santa Outfit',
    'additionalname' => 'Mid-grade / MP Recovery Bonus Increase',
    'description' => 'When modified, MP Recovery Bonus + 4.',
    'is_trade' => 0,
    'is_drop' => 0,
    'is_destruct' => 1,
    'crystal_type' => 'none',
    'consume_type' => 'consume_type_normal',
  ],
  24973 => 
  [
    'item_id' => 24973,
    'icon' => 'armor_ev_santas_clothes',
    'name' => 'Santa Outfit',
    'additionalname' => 'Mid-grade / Evasion Increase',
    'description' => 'When modified, P./M. Evasion + 4.',
    'is_trade' => 0,
    'is_drop' => 0,
    'is_destruct' => 1,
    'crystal_type' => 'none',
    'consume_type' => 'consume_type_normal',
  ],
  24974 => 
  [
    'item_id' => 24974,
    'icon' => 'armor_ev_santas_clothes',
    'name' => 'Santa Outfit',
    'additionalname' => 'Mid-grade / Option 15',
    'description' => 'When modified, Mid-grade / Option + 15.',
    'is_trade' => 0,
    'is_drop' => 0,
    'is_destruct' => 1,
    'crystal_type' => 'none',
    'consume_type' => 'consume_type_normal',
  ],
  24975 => 
  [
    'item_id' => 24975,
    'icon' => 'armor_ev_santas_clothes',
    'name' => 'Santa Outfit',
    'additionalname' => 'Mid-grade / Option 16',
    'description' => 'When modified, Mid-grade / Option + 16.',
    'is_trade' => 0,
    'is_drop' => 0,
    'is_destruct' => 1,
    'crystal_type' => 'none',
    'consume_type' => 'consume_type_normal',
  ],
  24976 => 
  [
    'item_id' => 24976,
    'icon' => 'armor_ev_santas_clothes',
    'name' => 'Santa Outfit',
    'additionalname' => 'Mid-grade / Option 17',
    'description' => 'When modified, Mid-grade / Option + 17.',
    'is_trade' => 0,
    'is_drop' => 0,
    'is_destruct' => 1,
    'crystal_type' => 'none',
    'consume_type' => 'consume_type_normal',
  ],
  24977 => 
  [
    'item_id' => 24977,
    'icon' => 'armor_ev_santas_clothes',
    'name' => 'Santa Outfit',
    'additionalname' => 'Mid-grade / Option 18',
    'description' => 'When modified, Mid-grade / Option + 18.',
    'is_trade' => 0,
    'is_drop' => 0,
    'is_destruct' => 1,
    'crystal_type' => 'none',
    'consume_type' => 'consume_type_normal',
  ],
  24978 => 
  [
    'item_id' => 24978,
    'icon' => 'armor_ev_santas_clothes',
    'name' => 'Santa Outfit',
    'additionalname' => 'Mid-grade / Option 19',
    'description' => 'When modified, Mid-grade / Option + 19.',
    'is_trade' => 0,
    'is_drop' => 0,
    'is_destruct' => 1,
    'crystal_type' => 'none',
    'consume_type' => 'consume_type_normal',
  ],
  24979 => 
  [
    'item_id' => 24979,
    'icon' => 'armor_ev_santas_clothes',
    'name' => 'Santa Outfit',
    'additionalname' => 'Mid-grade / Option 20',
    'description' => 'When modified, Mid-grade / Option + 20.',
    'is_trade' => 0,
    'is_drop' => 0,
    'is_destruct' => 1,
    'crystal_type' => 'none',
    'consume_type' => 'consume_type_normal',
  ],
  24980 => 
  [
    'item_id' => 24980,
    'icon' => 'armor_ev_santas_clothes',
    'name' => 'Santa Outfit',
    'additionalname' => 'Top-grade / Debuff Reflect',
    'description' => 'When modified, Debuff Reflect + 10%.',
    'is_trade' => 0,
    'is_drop' => 0,
    'is_destruct' => 1,
    'crystal_type' => 'none',
    'consume_type' => 'consume_type_normal',
  ],
  24981 => 
  [
    'item_id' => 24981,
    'icon' => 'armor_ev_santas_clothes',
    'name' => 'Santa Outfit',
    'additionalname' => 'Top-grade / Damage Reflect Resistance',
    'description' => 'When modified, Debuff Reflect Resistance + 15%.',
    'is_trade' => 0,
    'is_drop' => 0,
    'is_destruct' => 1,
    'crystal_type' => 'none',
    'consume_type' => 'consume_type_normal',
  ],
  24982 => 
  [
    'item_id' => 24982,
    'icon' => 'armor_ev_santas_clothes',
    'name' => 'Santa Outfit',
    'additionalname' => 'Top-grade / Ranged Resistance',
    'description' => 'When modified, Bow/Crossbow Resistance + 10%.',
    'is_trade' => 0,
    'is_drop' => 0,
    'is_destruct' => 1,
    'crystal_type' => 'none',
    'consume_type' => 'consume_type_normal',
  ],
  24983 => 
  [
    'item_id' => 24983,
    'icon' => 'armor_ev_santas_clothes',
    'name' => 'Santa Outfit',
    'additionalname' => 'Top-grade / P. Def. Increase',
    'description' => 'When modified, P. Def. + 10%.',
    'is_trade' => 0,
    'is_drop' => 0,
    'is_destruct' => 1,
    'crystal_type' => 'none',
    'consume_type' => 'consume_type_normal',
  ],
  24984 => 
  [
    'item_id' => 24984,
    'icon' => 'armor_ev_santas_clothes',
    'name' => 'Santa Outfit',
    'additionalname' => 'Top-grade / M. Def. Increase',
    'description' => 'When modified, M. Def. + 10%.',
    'is_trade' => 0,
    'is_drop' => 0,
    'is_destruct' => 1,
    'crystal_type' => 'none',
    'consume_type' => 'consume_type_normal',
  ],
  24985 => 
  [
    'item_id' => 24985,
    'icon' => 'armor_ev_santas_clothes',
    'name' => 'Santa Outfit',
    'additionalname' => 'Top-grade / Attribute Resistance',
    'description' => 'When modified, Attribute Resistance + 15.',
    'is_trade' => 0,
    'is_drop' => 0,
    'is_destruct' => 1,
    'crystal_type' => 'none',
    'consume_type' => 'consume_type_normal',
  ],
  24986 => 
  [
    'item_id' => 24986,
    'icon' => 'armor_ev_santas_clothes',
    'name' => 'Santa Outfit',
    'additionalname' => 'Top-grade / Received Heal Amount Increase',
    'description' => 'When modified, Received Heal Amount + 15%.',
    'is_trade' => 0,
    'is_drop' => 0,
    'is_destruct' => 1,
    'crystal_type' => 'none',
    'consume_type' => 'consume_type_normal',
  ],
  24987 => 
  [
    'item_id' => 24987,
    'icon' => 'armor_ev_santas_clothes',
    'name' => 'Santa Outfit',
    'additionalname' => 'Top-grade / Max. HP Increase',
    'description' => 'When modified, Max. HP + 15%.',
    'is_trade' => 0,
    'is_drop' => 0,
    'is_destruct' => 1,
    'crystal_type' => 'none',
    'consume_type' => 'consume_type_normal',
  ],
  24988 => 
  [
    'item_id' => 24988,
    'icon' => 'armor_ev_santas_clothes',
    'name' => 'Santa Outfit',
    'additionalname' => 'Top-grade / Max. MP Increase',
    'description' => 'When modified, Max. MP + 10%.',
    'is_trade' => 0,
    'is_drop' => 0,
    'is_destruct' => 1,
    'crystal_type' => 'none',
    'consume_type' => 'consume_type_normal',
  ],
  24989 => 
  [
    'item_id' => 24989,
    'icon' => 'armor_ev_santas_clothes',
    'name' => 'Santa Outfit',
    'additionalname' => 'Top-grade / Max CP Increase',
    'description' => 'When modified, Max. CP + 15%.',
    'is_trade' => 0,
    'is_drop' => 0,
    'is_destruct' => 1,
    'crystal_type' => 'none',
    'consume_type' => 'consume_type_normal',
  ],
  24990 => 
  [
    'item_id' => 24990,
    'icon' => 'armor_ev_santas_clothes',
    'name' => 'Santa Outfit',
    'additionalname' => 'Top-grade / Speed Increase',
    'description' => 'When modified, Speed + 15.',
    'is_trade' => 0,
    'is_drop' => 0,
    'is_destruct' => 1,
    'crystal_type' => 'none',
    'consume_type' => 'consume_type_normal',
  ],
  24991 => 
  [
    'item_id' => 24991,
    'icon' => 'armor_ev_santas_clothes',
    'name' => 'Santa Outfit',
    'additionalname' => 'Top-grade / HP Recovery Bonus Increase',
    'description' => 'When modified, HP Recovery Bonus + 16.',
    'is_trade' => 0,
    'is_drop' => 0,
    'is_destruct' => 1,
    'crystal_type' => 'none',
    'consume_type' => 'consume_type_normal',
  ],
  24992 => 
  [
    'item_id' => 24992,
    'icon' => 'armor_ev_santas_clothes',
    'name' => 'Santa Outfit',
    'additionalname' => 'Top-grade / MP Recovery Bonus Increase',
    'description' => 'When modified, MP Recovery Bonus + 8.',
    'is_trade' => 0,
    'is_drop' => 0,
    'is_destruct' => 1,
    'crystal_type' => 'none',
    'consume_type' => 'consume_type_normal',
  ],
  24993 => 
  [
    'item_id' => 24993,
    'icon' => 'armor_ev_santas_clothes',
    'name' => 'Santa Outfit',
    'additionalname' => 'Top-grade / Evasion Increase',
    'description' => 'When modified, P./M. Evasion + 8.',
    'is_trade' => 0,
    'is_drop' => 0,
    'is_destruct' => 1,
    'crystal_type' => 'none',
    'consume_type' => 'consume_type_normal',
  ],
  24994 => 
  [
    'item_id' => 24994,
    'icon' => 'armor_ev_santas_clothes',
    'name' => 'Santa Outfit',
    'additionalname' => 'Top-grade / Option 15',
    'description' => 'When modified, Top-grade / Option + 15.',
    'is_trade' => 0,
    'is_drop' => 0,
    'is_destruct' => 1,
    'crystal_type' => 'none',
    'consume_type' => 'consume_type_normal',
  ],
  24995 => 
  [
    'item_id' => 24995,
    'icon' => 'armor_ev_santas_clothes',
    'name' => 'Santa Outfit',
    'additionalname' => 'Top-grade / Option 16',
    'description' => 'When modified, Top-grade / Option + 16.',
    'is_trade' => 0,
    'is_drop' => 0,
    'is_destruct' => 1,
    'crystal_type' => 'none',
    'consume_type' => 'consume_type_normal',
  ],
  24996 => 
  [
    'item_id' => 24996,
    'icon' => 'armor_ev_santas_clothes',
    'name' => 'Santa Outfit',
    'additionalname' => 'Top-grade / Option 17',
    'description' => 'When modified, Top-grade / Option + 17.',
    'is_trade' => 0,
    'is_drop' => 0,
    'is_destruct' => 1,
    'crystal_type' => 'none',
    'consume_type' => 'consume_type_normal',
  ],
  24997 => 
  [
    'item_id' => 24997,
    'icon' => 'armor_ev_santas_clothes',
    'name' => 'Santa Outfit',
    'additionalname' => 'Top-grade / Option 18',
    'description' => 'When modified, Top-grade / Option + 18.',
    'is_trade' => 0,
    'is_drop' => 0,
    'is_destruct' => 1,
    'crystal_type' => 'none',
    'consume_type' => 'consume_type_normal',
  ],
  24998 => 
  [
    'item_id' => 24998,
    'icon' => 'armor_ev_santas_clothes',
    'name' => 'Santa Outfit',
    'additionalname' => 'Top-grade / Option 19',
    'description' => 'When modified, Top-grade / Option + 19.',
    'is_trade' => 0,
    'is_drop' => 0,
    'is_destruct' => 1,
    'crystal_type' => 'none',
    'consume_type' => 'consume_type_normal',
  ],
  24999 => 
  [
    'item_id' => 24999,
    'icon' => 'armor_ev_santas_clothes',
    'name' => 'Santa Outfit',
    'additionalname' => 'Top-grade / Option 20',
    'description' => 'When modified, Top-grade / Option + 20.',
    'is_trade' => 0,
    'is_drop' => 0,
    'is_destruct' => 1,
    'crystal_type' => 'none',
    'consume_type' => 'consume_type_normal',
  ],
];