<?php return [
  2500 => 
  [
    'item_id' => 2500,
    'icon' => 'weapon_dark_legions_edge_i00',
    'name' => 'Dark Legions Edge',
    'additionalname' => NULL,
    'description' => '1 common soul crystal and 1 special soul crystal can be inserted.',
    'is_trade' => 1,
    'is_drop' => 1,
    'is_destruct' => 1,
    'crystal_type' => 'a',
    'consume_type' => 'consume_type_normal',
  ],
  2501 => 
  [
    'item_id' => 2501,
    'icon' => 'weapon_club_i00',
    'name' => 'Bone Club',
    'additionalname' => NULL,
    'description' => NULL,
    'is_trade' => 1,
    'is_drop' => 1,
    'is_destruct' => 1,
    'crystal_type' => 'none',
    'consume_type' => 'consume_type_normal',
  ],
  2502 => 
  [
    'item_id' => 2502,
    'icon' => 'weapon_dwarven_warhammer_i00',
    'name' => 'Dwarven War Hammer',
    'additionalname' => NULL,
    'description' => '1 common soul crystal and 1 special soul crystal can be inserted.',
    'is_trade' => 1,
    'is_drop' => 1,
    'is_destruct' => 1,
    'crystal_type' => 'c',
    'consume_type' => 'consume_type_normal',
  ],
  2503 => 
  [
    'item_id' => 2503,
    'icon' => 'weapon_yaksa_mace_i00',
    'name' => 'Yaksa Mace',
    'additionalname' => NULL,
    'description' => '1 common soul crystal and 1 special soul crystal can be inserted.',
    'is_trade' => 1,
    'is_drop' => 1,
    'is_destruct' => 1,
    'crystal_type' => 'c',
    'consume_type' => 'consume_type_normal',
  ],
  2504 => 
  [
    'item_id' => 2504,
    'icon' => 'weapon_meteor_shower_i00',
    'name' => 'Meteor Shower',
    'additionalname' => NULL,
    'description' => '1 common soul crystal and 1 special soul crystal can be inserted.',
    'is_trade' => 1,
    'is_drop' => 1,
    'is_destruct' => 1,
    'crystal_type' => 'a',
    'consume_type' => 'consume_type_normal',
  ],
  2505 => 
  [
    'item_id' => 2505,
    'icon' => 'etc_pet_arms_i00',
    'name' => 'Iron Canine',
    'additionalname' => NULL,
    'description' => 'Double-click to wear. Only for wolves, great wolves, and fenrir.',
    'is_trade' => 1,
    'is_drop' => 1,
    'is_destruct' => 1,
    'crystal_type' => 'none',
    'consume_type' => 'consume_type_normal',
  ],
  2506 => 
  [
    'item_id' => 2506,
    'icon' => 'etc_pet_armor_i00',
    'name' => 'Wolfs Armor',
    'additionalname' => NULL,
    'description' => 'Double-click to wear. Only for wolves, great wolves, and fenrir.',
    'is_trade' => 1,
    'is_drop' => 1,
    'is_destruct' => 1,
    'crystal_type' => 'none',
    'consume_type' => 'consume_type_normal',
  ],
  2507 => 
  [
    'item_id' => 2507,
    'icon' => 'weapon_doomed_dagger_i00',
    'name' => 'Lizardspear',
    'additionalname' => NULL,
    'description' => NULL,
    'is_trade' => 1,
    'is_drop' => 1,
    'is_destruct' => 1,
    'crystal_type' => 'd',
    'consume_type' => 'consume_type_normal',
  ],
  2508 => 
  [
    'item_id' => 2508,
    'icon' => 'etc_piece_bone_red_i00',
    'name' => 'Cursed Bone',
    'additionalname' => NULL,
    'description' => NULL,
    'is_trade' => 1,
    'is_drop' => 1,
    'is_destruct' => 1,
    'crystal_type' => 'none',
    'consume_type' => 'consume_type_stackable',
  ],
  2509 => 
  [
    'item_id' => 2509,
    'icon' => 'etc_spell_shot_white_i00',
    'name' => 'No-grade Spiritshot',
    'additionalname' => NULL,
    'description' => 'Increases weapons magic power. Used with No-grade weapons.',
    'is_trade' => 1,
    'is_drop' => 1,
    'is_destruct' => 1,
    'crystal_type' => 'none',
    'consume_type' => 'consume_type_stackable',
  ],
  2510 => 
  [
    'item_id' => 2510,
    'icon' => 'etc_spell_shot_blue_i00',
    'name' => 'D-grade Spiritshot',
    'additionalname' => NULL,
    'description' => 'Increases weapons magic power. Used with D-grade weapons.',
    'is_trade' => 1,
    'is_drop' => 1,
    'is_destruct' => 1,
    'crystal_type' => 'd',
    'consume_type' => 'consume_type_stackable',
  ],
  2511 => 
  [
    'item_id' => 2511,
    'icon' => 'etc_spell_shot_green_i00',
    'name' => 'C-grade Spiritshot',
    'additionalname' => NULL,
    'description' => 'Increases weapons magic power. Used with C-grade weapons.',
    'is_trade' => 1,
    'is_drop' => 1,
    'is_destruct' => 1,
    'crystal_type' => 'c',
    'consume_type' => 'consume_type_stackable',
  ],
  2512 => 
  [
    'item_id' => 2512,
    'icon' => 'etc_spell_shot_red_i00',
    'name' => 'B-grade Spiritshot',
    'additionalname' => NULL,
    'description' => 'Increases weapons magic power. Used with B-grade weapons.',
    'is_trade' => 1,
    'is_drop' => 1,
    'is_destruct' => 1,
    'crystal_type' => 'b',
    'consume_type' => 'consume_type_stackable',
  ],
  2513 => 
  [
    'item_id' => 2513,
    'icon' => 'etc_spell_shot_silver_i00',
    'name' => 'A-grade Spiritshot',
    'additionalname' => NULL,
    'description' => 'Increases weapons magic power. Used with A-grade weapons.',
    'is_trade' => 1,
    'is_drop' => 1,
    'is_destruct' => 1,
    'crystal_type' => 'a',
    'consume_type' => 'consume_type_stackable',
  ],
  2514 => 
  [
    'item_id' => 2514,
    'icon' => 'etc_spell_shot_gold_i00',
    'name' => 'S-grade Spiritshot',
    'additionalname' => NULL,
    'description' => 'Increases weapons magic power. Used with S-grade weapons.',
    'is_trade' => 1,
    'is_drop' => 1,
    'is_destruct' => 1,
    'crystal_type' => 's',
    'consume_type' => 'consume_type_stackable',
  ],
  2515 => 
  [
    'item_id' => 2515,
    'icon' => 'etc_pouch_yellow_i00',
    'name' => 'Wolf Food',
    'additionalname' => NULL,
    'description' => 'When the hunger gauge of a wolf reaches 55% or below, its food will be consumed automatically.',
    'is_trade' => 1,
    'is_drop' => 1,
    'is_destruct' => 1,
    'crystal_type' => 'crystal_free',
    'consume_type' => 'consume_type_stackable',
  ],
  2516 => 
  [
    'item_id' => 2516,
    'icon' => 'weapon_dual_sword_i00',
    'name' => 'Saber Saber',
    'additionalname' => NULL,
    'description' => NULL,
    'is_trade' => 1,
    'is_drop' => 1,
    'is_destruct' => 1,
    'crystal_type' => 'd',
    'consume_type' => 'consume_type_normal',
  ],
  2517 => 
  [
    'item_id' => 2517,
    'icon' => 'weapon_dual_sword_i00',
    'name' => 'Saber Bastard Sword',
    'additionalname' => NULL,
    'description' => NULL,
    'is_trade' => 1,
    'is_drop' => 1,
    'is_destruct' => 1,
    'crystal_type' => 'd',
    'consume_type' => 'consume_type_normal',
  ],
  2518 => 
  [
    'item_id' => 2518,
    'icon' => 'weapon_dual_sword_i00',
    'name' => 'Saber Spinebone Sword',
    'additionalname' => NULL,
    'description' => NULL,
    'is_trade' => 1,
    'is_drop' => 1,
    'is_destruct' => 1,
    'crystal_type' => 'd',
    'consume_type' => 'consume_type_normal',
  ],
  2519 => 
  [
    'item_id' => 2519,
    'icon' => 'weapon_dual_sword_i00',
    'name' => 'Saber Artisans Sword',
    'additionalname' => NULL,
    'description' => NULL,
    'is_trade' => 1,
    'is_drop' => 1,
    'is_destruct' => 1,
    'crystal_type' => 'd',
    'consume_type' => 'consume_type_normal',
  ],
  2520 => 
  [
    'item_id' => 2520,
    'icon' => 'weapon_dual_sword_i00',
    'name' => 'Saber Knights Sword',
    'additionalname' => NULL,
    'description' => NULL,
    'is_trade' => 1,
    'is_drop' => 1,
    'is_destruct' => 1,
    'crystal_type' => 'd',
    'consume_type' => 'consume_type_normal',
  ],
  2521 => 
  [
    'item_id' => 2521,
    'icon' => 'weapon_dual_sword_i00',
    'name' => 'Saber Crimson Sword',
    'additionalname' => NULL,
    'description' => NULL,
    'is_trade' => 1,
    'is_drop' => 1,
    'is_destruct' => 1,
    'crystal_type' => 'd',
    'consume_type' => 'consume_type_normal',
  ],
  2522 => 
  [
    'item_id' => 2522,
    'icon' => 'weapon_dual_sword_i00',
    'name' => 'Saber Elven Sword',
    'additionalname' => NULL,
    'description' => NULL,
    'is_trade' => 1,
    'is_drop' => 1,
    'is_destruct' => 1,
    'crystal_type' => 'd',
    'consume_type' => 'consume_type_normal',
  ],
  2523 => 
  [
    'item_id' => 2523,
    'icon' => 'weapon_dual_sword_i00',
    'name' => 'Saber Sword of Revolution',
    'additionalname' => NULL,
    'description' => NULL,
    'is_trade' => 1,
    'is_drop' => 1,
    'is_destruct' => 1,
    'crystal_type' => 'c',
    'consume_type' => 'consume_type_normal',
  ],
  2524 => 
  [
    'item_id' => 2524,
    'icon' => 'weapon_dual_sword_i00',
    'name' => 'Saber Elven Long Sword',
    'additionalname' => NULL,
    'description' => NULL,
    'is_trade' => 1,
    'is_drop' => 1,
    'is_destruct' => 1,
    'crystal_type' => 'c',
    'consume_type' => 'consume_type_normal',
  ],
  2525 => 
  [
    'item_id' => 2525,
    'icon' => 'weapon_dual_sword_i00',
    'name' => 'Bastard Sword Bastard Sword',
    'additionalname' => NULL,
    'description' => NULL,
    'is_trade' => 1,
    'is_drop' => 1,
    'is_destruct' => 1,
    'crystal_type' => 'd',
    'consume_type' => 'consume_type_normal',
  ],
  2526 => 
  [
    'item_id' => 2526,
    'icon' => 'weapon_dual_sword_i00',
    'name' => 'Bastard Sword Spinebone Sword',
    'additionalname' => NULL,
    'description' => NULL,
    'is_trade' => 1,
    'is_drop' => 1,
    'is_destruct' => 1,
    'crystal_type' => 'd',
    'consume_type' => 'consume_type_normal',
  ],
  2527 => 
  [
    'item_id' => 2527,
    'icon' => 'weapon_dual_sword_i00',
    'name' => 'Bastard Sword Artisans Sword',
    'additionalname' => NULL,
    'description' => NULL,
    'is_trade' => 1,
    'is_drop' => 1,
    'is_destruct' => 1,
    'crystal_type' => 'd',
    'consume_type' => 'consume_type_normal',
  ],
  2528 => 
  [
    'item_id' => 2528,
    'icon' => 'weapon_dual_sword_i00',
    'name' => 'Bastard Sword Knights Sword',
    'additionalname' => NULL,
    'description' => NULL,
    'is_trade' => 1,
    'is_drop' => 1,
    'is_destruct' => 1,
    'crystal_type' => 'd',
    'consume_type' => 'consume_type_normal',
  ],
  2529 => 
  [
    'item_id' => 2529,
    'icon' => 'weapon_dual_sword_i00',
    'name' => 'Bastard Sword Crimson Sword',
    'additionalname' => NULL,
    'description' => NULL,
    'is_trade' => 1,
    'is_drop' => 1,
    'is_destruct' => 1,
    'crystal_type' => 'd',
    'consume_type' => 'consume_type_normal',
  ],
  2530 => 
  [
    'item_id' => 2530,
    'icon' => 'weapon_dual_sword_i00',
    'name' => 'Bastard Sword Elven Sword',
    'additionalname' => NULL,
    'description' => NULL,
    'is_trade' => 1,
    'is_drop' => 1,
    'is_destruct' => 1,
    'crystal_type' => 'd',
    'consume_type' => 'consume_type_normal',
  ],
  2531 => 
  [
    'item_id' => 2531,
    'icon' => 'weapon_dual_sword_i00',
    'name' => 'Bastard Sword Sword of Revolution',
    'additionalname' => NULL,
    'description' => NULL,
    'is_trade' => 1,
    'is_drop' => 1,
    'is_destruct' => 1,
    'crystal_type' => 'c',
    'consume_type' => 'consume_type_normal',
  ],
  2532 => 
  [
    'item_id' => 2532,
    'icon' => 'weapon_dual_sword_i00',
    'name' => 'Bastard Sword Elven Long Sword',
    'additionalname' => NULL,
    'description' => NULL,
    'is_trade' => 1,
    'is_drop' => 1,
    'is_destruct' => 1,
    'crystal_type' => 'c',
    'consume_type' => 'consume_type_normal',
  ],
  2533 => 
  [
    'item_id' => 2533,
    'icon' => 'weapon_dual_sword_i00',
    'name' => 'Spinebone Sword Spinebone Sword',
    'additionalname' => NULL,
    'description' => NULL,
    'is_trade' => 1,
    'is_drop' => 1,
    'is_destruct' => 1,
    'crystal_type' => 'd',
    'consume_type' => 'consume_type_normal',
  ],
  2534 => 
  [
    'item_id' => 2534,
    'icon' => 'weapon_dual_sword_i00',
    'name' => 'Spinebone Sword Artisans Sword',
    'additionalname' => NULL,
    'description' => NULL,
    'is_trade' => 1,
    'is_drop' => 1,
    'is_destruct' => 1,
    'crystal_type' => 'd',
    'consume_type' => 'consume_type_normal',
  ],
  2535 => 
  [
    'item_id' => 2535,
    'icon' => 'weapon_dual_sword_i00',
    'name' => 'Spinebone Sword Knights Sword',
    'additionalname' => NULL,
    'description' => NULL,
    'is_trade' => 1,
    'is_drop' => 1,
    'is_destruct' => 1,
    'crystal_type' => 'd',
    'consume_type' => 'consume_type_normal',
  ],
  2536 => 
  [
    'item_id' => 2536,
    'icon' => 'weapon_dual_sword_i00',
    'name' => 'Spinebone Sword Crimson Sword',
    'additionalname' => NULL,
    'description' => NULL,
    'is_trade' => 1,
    'is_drop' => 1,
    'is_destruct' => 1,
    'crystal_type' => 'd',
    'consume_type' => 'consume_type_normal',
  ],
  2537 => 
  [
    'item_id' => 2537,
    'icon' => 'weapon_dual_sword_i00',
    'name' => 'Spinebone Sword Elven Sword',
    'additionalname' => NULL,
    'description' => NULL,
    'is_trade' => 1,
    'is_drop' => 1,
    'is_destruct' => 1,
    'crystal_type' => 'd',
    'consume_type' => 'consume_type_normal',
  ],
  2538 => 
  [
    'item_id' => 2538,
    'icon' => 'weapon_dual_sword_i00',
    'name' => 'Spinebone Sword Sword of Revolution',
    'additionalname' => NULL,
    'description' => NULL,
    'is_trade' => 1,
    'is_drop' => 1,
    'is_destruct' => 1,
    'crystal_type' => 'c',
    'consume_type' => 'consume_type_normal',
  ],
  2539 => 
  [
    'item_id' => 2539,
    'icon' => 'weapon_dual_sword_i00',
    'name' => 'Spinebone Sword Elven Long Sword',
    'additionalname' => NULL,
    'description' => NULL,
    'is_trade' => 1,
    'is_drop' => 1,
    'is_destruct' => 1,
    'crystal_type' => 'c',
    'consume_type' => 'consume_type_normal',
  ],
  2540 => 
  [
    'item_id' => 2540,
    'icon' => 'weapon_dual_sword_i00',
    'name' => 'Artisans Sword Artisans Sword',
    'additionalname' => NULL,
    'description' => NULL,
    'is_trade' => 1,
    'is_drop' => 1,
    'is_destruct' => 1,
    'crystal_type' => 'd',
    'consume_type' => 'consume_type_normal',
  ],
  2541 => 
  [
    'item_id' => 2541,
    'icon' => 'weapon_dual_sword_i00',
    'name' => 'Artisans Sword Knights Sword',
    'additionalname' => NULL,
    'description' => NULL,
    'is_trade' => 1,
    'is_drop' => 1,
    'is_destruct' => 1,
    'crystal_type' => 'd',
    'consume_type' => 'consume_type_normal',
  ],
  2542 => 
  [
    'item_id' => 2542,
    'icon' => 'weapon_dual_sword_i00',
    'name' => 'Artisans Sword Crimson Sword',
    'additionalname' => NULL,
    'description' => NULL,
    'is_trade' => 1,
    'is_drop' => 1,
    'is_destruct' => 1,
    'crystal_type' => 'd',
    'consume_type' => 'consume_type_normal',
  ],
  2543 => 
  [
    'item_id' => 2543,
    'icon' => 'weapon_dual_sword_i00',
    'name' => 'Artisans Sword Elven Sword',
    'additionalname' => NULL,
    'description' => NULL,
    'is_trade' => 1,
    'is_drop' => 1,
    'is_destruct' => 1,
    'crystal_type' => 'd',
    'consume_type' => 'consume_type_normal',
  ],
  2544 => 
  [
    'item_id' => 2544,
    'icon' => 'weapon_dual_sword_i00',
    'name' => 'Artisans Sword Sword of Revolution',
    'additionalname' => NULL,
    'description' => NULL,
    'is_trade' => 1,
    'is_drop' => 1,
    'is_destruct' => 1,
    'crystal_type' => 'c',
    'consume_type' => 'consume_type_normal',
  ],
  2545 => 
  [
    'item_id' => 2545,
    'icon' => 'weapon_dual_sword_i00',
    'name' => 'Artisans Sword Elven Long Sword',
    'additionalname' => NULL,
    'description' => NULL,
    'is_trade' => 1,
    'is_drop' => 1,
    'is_destruct' => 1,
    'crystal_type' => 'c',
    'consume_type' => 'consume_type_normal',
  ],
  2546 => 
  [
    'item_id' => 2546,
    'icon' => 'weapon_dual_sword_i00',
    'name' => 'Knights Sword Knights Sword',
    'additionalname' => NULL,
    'description' => NULL,
    'is_trade' => 1,
    'is_drop' => 1,
    'is_destruct' => 1,
    'crystal_type' => 'd',
    'consume_type' => 'consume_type_normal',
  ],
  2547 => 
  [
    'item_id' => 2547,
    'icon' => 'weapon_dual_sword_i00',
    'name' => 'Knights Sword Crimson Sword',
    'additionalname' => NULL,
    'description' => NULL,
    'is_trade' => 1,
    'is_drop' => 1,
    'is_destruct' => 1,
    'crystal_type' => 'd',
    'consume_type' => 'consume_type_normal',
  ],
  2548 => 
  [
    'item_id' => 2548,
    'icon' => 'weapon_dual_sword_i00',
    'name' => 'Knights Sword Elven Sword',
    'additionalname' => NULL,
    'description' => NULL,
    'is_trade' => 1,
    'is_drop' => 1,
    'is_destruct' => 1,
    'crystal_type' => 'd',
    'consume_type' => 'consume_type_normal',
  ],
  2549 => 
  [
    'item_id' => 2549,
    'icon' => 'weapon_dual_sword_i00',
    'name' => 'Knights Sword Sword of Revolution',
    'additionalname' => NULL,
    'description' => NULL,
    'is_trade' => 1,
    'is_drop' => 1,
    'is_destruct' => 1,
    'crystal_type' => 'c',
    'consume_type' => 'consume_type_normal',
  ],
  2550 => 
  [
    'item_id' => 2550,
    'icon' => 'weapon_dual_sword_i00',
    'name' => 'Knights Sword Elven Long Sword',
    'additionalname' => NULL,
    'description' => NULL,
    'is_trade' => 1,
    'is_drop' => 1,
    'is_destruct' => 1,
    'crystal_type' => 'c',
    'consume_type' => 'consume_type_normal',
  ],
  2551 => 
  [
    'item_id' => 2551,
    'icon' => 'weapon_dual_sword_i00',
    'name' => 'Crimson Sword Crimson Sword',
    'additionalname' => NULL,
    'description' => NULL,
    'is_trade' => 1,
    'is_drop' => 1,
    'is_destruct' => 1,
    'crystal_type' => 'c',
    'consume_type' => 'consume_type_normal',
  ],
  2552 => 
  [
    'item_id' => 2552,
    'icon' => 'weapon_dual_sword_i00',
    'name' => 'Crimson Sword Elven Sword',
    'additionalname' => NULL,
    'description' => NULL,
    'is_trade' => 1,
    'is_drop' => 1,
    'is_destruct' => 1,
    'crystal_type' => 'c',
    'consume_type' => 'consume_type_normal',
  ],
  2553 => 
  [
    'item_id' => 2553,
    'icon' => 'weapon_dual_sword_i00',
    'name' => 'Crimson Sword Sword of Revolution',
    'additionalname' => NULL,
    'description' => NULL,
    'is_trade' => 1,
    'is_drop' => 1,
    'is_destruct' => 1,
    'crystal_type' => 'c',
    'consume_type' => 'consume_type_normal',
  ],
  2554 => 
  [
    'item_id' => 2554,
    'icon' => 'weapon_dual_sword_i00',
    'name' => 'Crimson Sword Elven Long Sword',
    'additionalname' => NULL,
    'description' => 'When enchanting dual swords, two-handed swords/ blunts, and fists, the P. Atk. bonus is higher than that of one-handed weapons. 1 common soul crystal and 1 special soul crystal can be inserted.',
    'is_trade' => 1,
    'is_drop' => 1,
    'is_destruct' => 1,
    'crystal_type' => 'c',
    'consume_type' => 'consume_type_normal',
  ],
  2555 => 
  [
    'item_id' => 2555,
    'icon' => 'weapon_dual_sword_i00',
    'name' => 'Elven Sword Elven Sword',
    'additionalname' => NULL,
    'description' => NULL,
    'is_trade' => 1,
    'is_drop' => 1,
    'is_destruct' => 1,
    'crystal_type' => 'c',
    'consume_type' => 'consume_type_normal',
  ],
  2556 => 
  [
    'item_id' => 2556,
    'icon' => 'weapon_dual_sword_i00',
    'name' => 'Elven Sword Sword of Revolution',
    'additionalname' => NULL,
    'description' => NULL,
    'is_trade' => 1,
    'is_drop' => 1,
    'is_destruct' => 1,
    'crystal_type' => 'c',
    'consume_type' => 'consume_type_normal',
  ],
  2557 => 
  [
    'item_id' => 2557,
    'icon' => 'weapon_dual_sword_i00',
    'name' => 'Elven Sword Elven Long Sword',
    'additionalname' => NULL,
    'description' => 'When enchanting dual swords, two-handed swords/ blunts, and fists, the P. Atk. bonus is higher than that of one-handed weapons. 1 common soul crystal and 1 special soul crystal can be inserted.',
    'is_trade' => 1,
    'is_drop' => 1,
    'is_destruct' => 1,
    'crystal_type' => 'c',
    'consume_type' => 'consume_type_normal',
  ],
  2558 => 
  [
    'item_id' => 2558,
    'icon' => 'weapon_dual_sword_i00',
    'name' => 'Sword of Revolution Sword of Revolution',
    'additionalname' => NULL,
    'description' => 'When enchanting dual swords, two-handed swords/ blunts, and fists, the P. Atk. bonus is higher than that of one-handed weapons. 1 common soul crystal and 1 special soul crystal can be inserted.',
    'is_trade' => 1,
    'is_drop' => 1,
    'is_destruct' => 1,
    'crystal_type' => 'c',
    'consume_type' => 'consume_type_normal',
  ],
  2559 => 
  [
    'item_id' => 2559,
    'icon' => 'weapon_dual_sword_i00',
    'name' => 'Sword of Revolution Elven Long Sword',
    'additionalname' => NULL,
    'description' => 'When enchanting dual swords, two-handed swords/ blunts, and fists, the P. Atk. bonus is higher than that of one-handed weapons. 1 common soul crystal and 1 special soul crystal can be inserted.',
    'is_trade' => 1,
    'is_drop' => 1,
    'is_destruct' => 1,
    'crystal_type' => 'c',
    'consume_type' => 'consume_type_normal',
  ],
  2560 => 
  [
    'item_id' => 2560,
    'icon' => 'weapon_dual_sword_i00',
    'name' => 'Elven Long Sword Elven Long Sword',
    'additionalname' => NULL,
    'description' => 'When enchanting dual swords, two-handed swords/ blunts, and fists, the P. Atk. bonus is higher than that of one-handed weapons. 1 common soul crystal and 1 special soul crystal can be inserted.',
    'is_trade' => 1,
    'is_drop' => 1,
    'is_destruct' => 1,
    'crystal_type' => 'c',
    'consume_type' => 'consume_type_normal',
  ],
  2561 => 
  [
    'item_id' => 2561,
    'icon' => 'weapon_dual_sword_i00',
    'name' => 'Stormbringer Stormbringer',
    'additionalname' => NULL,
    'description' => 'When enchanting dual swords, two-handed swords/ blunts, and fists, the P. Atk. bonus is higher than that of one-handed weapons. 1 common soul crystal and 1 special soul crystal can be inserted.',
    'is_trade' => 1,
    'is_drop' => 1,
    'is_destruct' => 1,
    'crystal_type' => 'c',
    'consume_type' => 'consume_type_normal',
  ],
  2562 => 
  [
    'item_id' => 2562,
    'icon' => 'weapon_dual_sword_i00',
    'name' => 'Stormbringer Shamshir',
    'additionalname' => NULL,
    'description' => 'When enchanting dual swords, two-handed swords/ blunts, and fists, the P. Atk. bonus is higher than that of one-handed weapons. 1 common soul crystal and 1 special soul crystal can be inserted.',
    'is_trade' => 1,
    'is_drop' => 1,
    'is_destruct' => 1,
    'crystal_type' => 'c',
    'consume_type' => 'consume_type_normal',
  ],
  2563 => 
  [
    'item_id' => 2563,
    'icon' => 'weapon_dual_sword_i00',
    'name' => 'Stormbringer Katana',
    'additionalname' => NULL,
    'description' => 'When enchanting dual swords, two-handed swords/ blunts, and fists, the P. Atk. bonus is higher than that of one-handed weapons. 1 common soul crystal and 1 special soul crystal can be inserted.',
    'is_trade' => 1,
    'is_drop' => 1,
    'is_destruct' => 1,
    'crystal_type' => 'c',
    'consume_type' => 'consume_type_normal',
  ],
  2564 => 
  [
    'item_id' => 2564,
    'icon' => 'weapon_dual_sword_i00',
    'name' => 'Stormbringer Spirit Sword',
    'additionalname' => NULL,
    'description' => 'When enchanting dual swords, two-handed swords/ blunts, and fists, the P. Atk. bonus is higher than that of one-handed weapons. 1 common soul crystal and 1 special soul crystal can be inserted.',
    'is_trade' => 1,
    'is_drop' => 1,
    'is_destruct' => 1,
    'crystal_type' => 'c',
    'consume_type' => 'consume_type_normal',
  ],
  2565 => 
  [
    'item_id' => 2565,
    'icon' => 'weapon_dual_sword_i00',
    'name' => 'Stormbringer Raid Sword',
    'additionalname' => NULL,
    'description' => 'When enchanting dual swords, two-handed swords/ blunts, and fists, the P. Atk. bonus is higher than that of one-handed weapons. 1 common soul crystal and 1 special soul crystal can be inserted.',
    'is_trade' => 1,
    'is_drop' => 1,
    'is_destruct' => 1,
    'crystal_type' => 'c',
    'consume_type' => 'consume_type_normal',
  ],
  2566 => 
  [
    'item_id' => 2566,
    'icon' => 'weapon_dual_sword_i00',
    'name' => 'Stormbringer Caliburs',
    'additionalname' => NULL,
    'description' => 'When enchanting dual swords, two-handed swords/ blunts, and fists, the P. Atk. bonus is higher than that of one-handed weapons. 1 common soul crystal and 1 special soul crystal can be inserted.',
    'is_trade' => 1,
    'is_drop' => 1,
    'is_destruct' => 1,
    'crystal_type' => 'b',
    'consume_type' => 'consume_type_normal',
  ],
  2567 => 
  [
    'item_id' => 2567,
    'icon' => 'weapon_dual_sword_i00',
    'name' => 'Stormbringer Ultimate Sword',
    'additionalname' => NULL,
    'description' => 'When enchanting dual swords, two-handed swords/ blunts, and fists, the P. Atk. bonus is higher than that of one-handed weapons. 1 common soul crystal and 1 special soul crystal can be inserted.',
    'is_trade' => 1,
    'is_drop' => 1,
    'is_destruct' => 1,
    'crystal_type' => 'b',
    'consume_type' => 'consume_type_normal',
  ],
  2568 => 
  [
    'item_id' => 2568,
    'icon' => 'weapon_dual_sword_i00',
    'name' => 'Stormbringer Sword of Delusion',
    'additionalname' => NULL,
    'description' => 'When enchanting dual swords, two-handed swords/ blunts, and fists, the P. Atk. bonus is higher than that of one-handed weapons. 1 common soul crystal and 1 special soul crystal can be inserted.',
    'is_trade' => 1,
    'is_drop' => 1,
    'is_destruct' => 1,
    'crystal_type' => 'b',
    'consume_type' => 'consume_type_normal',
  ],
  2569 => 
  [
    'item_id' => 2569,
    'icon' => 'weapon_dual_sword_i00',
    'name' => 'Stormbringer Sword of Nightmare',
    'additionalname' => NULL,
    'description' => 'When enchanting dual swords, two-handed swords/ blunts, and fists, the P. Atk. bonus is higher than that of one-handed weapons. 1 common soul crystal and 1 special soul crystal can be inserted.',
    'is_trade' => 1,
    'is_drop' => 1,
    'is_destruct' => 1,
    'crystal_type' => 'b',
    'consume_type' => 'consume_type_normal',
  ],
  2570 => 
  [
    'item_id' => 2570,
    'icon' => 'weapon_dual_sword_i00',
    'name' => 'Stormbringer Tsurugi',
    'additionalname' => NULL,
    'description' => 'When enchanting dual swords, two-handed swords/ blunts, and fists, the P. Atk. bonus is higher than that of one-handed weapons. 1 common soul crystal and 1 special soul crystal can be inserted.',
    'is_trade' => 1,
    'is_drop' => 1,
    'is_destruct' => 1,
    'crystal_type' => 'b',
    'consume_type' => 'consume_type_normal',
  ],
  2571 => 
  [
    'item_id' => 2571,
    'icon' => 'weapon_dual_sword_i00',
    'name' => 'Stormbringer Samurai Long sword',
    'additionalname' => NULL,
    'description' => 'When enchanting dual swords, two-handed swords/ blunts, and fists, the P. Atk. bonus is higher than that of one-handed weapons. 1 common soul crystal and 1 special soul crystal can be inserted.',
    'is_trade' => 1,
    'is_drop' => 1,
    'is_destruct' => 1,
    'crystal_type' => 'b',
    'consume_type' => 'consume_type_normal',
  ],
  2572 => 
  [
    'item_id' => 2572,
    'icon' => 'weapon_dual_sword_i00',
    'name' => 'Shamshir Shamshir',
    'additionalname' => NULL,
    'description' => 'When enchanting dual swords, two-handed swords/ blunts, and fists, the P. Atk. bonus is higher than that of one-handed weapons. 1 common soul crystal and 1 special soul crystal can be inserted.',
    'is_trade' => 1,
    'is_drop' => 1,
    'is_destruct' => 1,
    'crystal_type' => 'c',
    'consume_type' => 'consume_type_normal',
  ],
  2573 => 
  [
    'item_id' => 2573,
    'icon' => 'weapon_dual_sword_i00',
    'name' => 'Shamshir Katana',
    'additionalname' => NULL,
    'description' => 'When enchanting dual swords, two-handed swords/ blunts, and fists, the P. Atk. bonus is higher than that of one-handed weapons. 1 common soul crystal and 1 special soul crystal can be inserted.',
    'is_trade' => 1,
    'is_drop' => 1,
    'is_destruct' => 1,
    'crystal_type' => 'c',
    'consume_type' => 'consume_type_normal',
  ],
  2574 => 
  [
    'item_id' => 2574,
    'icon' => 'weapon_dual_sword_i00',
    'name' => 'Shamshir Spirit Sword',
    'additionalname' => NULL,
    'description' => 'When enchanting dual swords, two-handed swords/ blunts, and fists, the P. Atk. bonus is higher than that of one-handed weapons. 1 common soul crystal and 1 special soul crystal can be inserted.',
    'is_trade' => 1,
    'is_drop' => 1,
    'is_destruct' => 1,
    'crystal_type' => 'c',
    'consume_type' => 'consume_type_normal',
  ],
  2575 => 
  [
    'item_id' => 2575,
    'icon' => 'weapon_dual_sword_i00',
    'name' => 'Shamshir Raid Sword',
    'additionalname' => NULL,
    'description' => 'When enchanting dual swords, two-handed swords/ blunts, and fists, the P. Atk. bonus is higher than that of one-handed weapons. 1 common soul crystal and 1 special soul crystal can be inserted.',
    'is_trade' => 1,
    'is_drop' => 1,
    'is_destruct' => 1,
    'crystal_type' => 'c',
    'consume_type' => 'consume_type_normal',
  ],
  2576 => 
  [
    'item_id' => 2576,
    'icon' => 'weapon_dual_sword_i00',
    'name' => 'Shamshir Caliburs',
    'additionalname' => NULL,
    'description' => 'When enchanting dual swords, two-handed swords/ blunts, and fists, the P. Atk. bonus is higher than that of one-handed weapons. 1 common soul crystal and 1 special soul crystal can be inserted.',
    'is_trade' => 1,
    'is_drop' => 1,
    'is_destruct' => 1,
    'crystal_type' => 'b',
    'consume_type' => 'consume_type_normal',
  ],
  2577 => 
  [
    'item_id' => 2577,
    'icon' => 'weapon_dual_sword_i00',
    'name' => 'Shamshir Ultimate Sword',
    'additionalname' => NULL,
    'description' => 'When enchanting dual swords, two-handed swords/ blunts, and fists, the P. Atk. bonus is higher than that of one-handed weapons. 1 common soul crystal and 1 special soul crystal can be inserted.',
    'is_trade' => 1,
    'is_drop' => 1,
    'is_destruct' => 1,
    'crystal_type' => 'b',
    'consume_type' => 'consume_type_normal',
  ],
  2578 => 
  [
    'item_id' => 2578,
    'icon' => 'weapon_dual_sword_i00',
    'name' => 'Shamshir Sword of Delusion',
    'additionalname' => NULL,
    'description' => 'When enchanting dual swords, two-handed swords/ blunts, and fists, the P. Atk. bonus is higher than that of one-handed weapons. 1 common soul crystal and 1 special soul crystal can be inserted.',
    'is_trade' => 1,
    'is_drop' => 1,
    'is_destruct' => 1,
    'crystal_type' => 'b',
    'consume_type' => 'consume_type_normal',
  ],
  2579 => 
  [
    'item_id' => 2579,
    'icon' => 'weapon_dual_sword_i00',
    'name' => 'Shamshir Sword of Nightmare',
    'additionalname' => NULL,
    'description' => 'When enchanting dual swords, two-handed swords/ blunts, and fists, the P. Atk. bonus is higher than that of one-handed weapons. 1 common soul crystal and 1 special soul crystal can be inserted.',
    'is_trade' => 1,
    'is_drop' => 1,
    'is_destruct' => 1,
    'crystal_type' => 'b',
    'consume_type' => 'consume_type_normal',
  ],
  2580 => 
  [
    'item_id' => 2580,
    'icon' => 'weapon_dual_sword_i00',
    'name' => 'Shamshir Tsurugi',
    'additionalname' => NULL,
    'description' => 'When enchanting dual swords, two-handed swords/ blunts, and fists, the P. Atk. bonus is higher than that of one-handed weapons. 1 common soul crystal and 1 special soul crystal can be inserted.',
    'is_trade' => 1,
    'is_drop' => 1,
    'is_destruct' => 1,
    'crystal_type' => 'b',
    'consume_type' => 'consume_type_normal',
  ],
  2581 => 
  [
    'item_id' => 2581,
    'icon' => 'weapon_dual_sword_i00',
    'name' => 'Shamshir Samurai Long Sword',
    'additionalname' => NULL,
    'description' => 'When enchanting dual swords, two-handed swords/ blunts, and fists, the P. Atk. bonus is higher than that of one-handed weapons. 1 common soul crystal and 1 special soul crystal can be inserted.',
    'is_trade' => 1,
    'is_drop' => 1,
    'is_destruct' => 1,
    'crystal_type' => 'b',
    'consume_type' => 'consume_type_normal',
  ],
  2582 => 
  [
    'item_id' => 2582,
    'icon' => 'weapon_dual_sword_i00',
    'name' => 'Katana Katana',
    'additionalname' => NULL,
    'description' => 'When enchanting dual swords, two-handed swords/ blunts, and fists, the P. Atk. bonus is higher than that of one-handed weapons. 1 common soul crystal and 1 special soul crystal can be inserted.',
    'is_trade' => 1,
    'is_drop' => 1,
    'is_destruct' => 1,
    'crystal_type' => 'c',
    'consume_type' => 'consume_type_normal',
  ],
  2583 => 
  [
    'item_id' => 2583,
    'icon' => 'weapon_dual_sword_i00',
    'name' => 'Katana Spirit Sword',
    'additionalname' => NULL,
    'description' => 'When enchanting dual swords, two-handed swords/ blunts, and fists, the P. Atk. bonus is higher than that of one-handed weapons. 1 common soul crystal and 1 special soul crystal can be inserted.',
    'is_trade' => 1,
    'is_drop' => 1,
    'is_destruct' => 1,
    'crystal_type' => 'c',
    'consume_type' => 'consume_type_normal',
  ],
  2584 => 
  [
    'item_id' => 2584,
    'icon' => 'weapon_dual_sword_i00',
    'name' => 'Katana Raid Sword',
    'additionalname' => NULL,
    'description' => 'When enchanting dual swords, two-handed swords/ blunts, and fists, the P. Atk. bonus is higher than that of one-handed weapons. 1 common soul crystal and 1 special soul crystal can be inserted.',
    'is_trade' => 1,
    'is_drop' => 1,
    'is_destruct' => 1,
    'crystal_type' => 'c',
    'consume_type' => 'consume_type_normal',
  ],
  2585 => 
  [
    'item_id' => 2585,
    'icon' => 'weapon_dual_sword_i00',
    'name' => 'Katana Caliburs',
    'additionalname' => NULL,
    'description' => 'When enchanting dual swords, two-handed swords/ blunts, and fists, the P. Atk. bonus is higher than that of one-handed weapons. 1 common soul crystal and 1 special soul crystal can be inserted.',
    'is_trade' => 1,
    'is_drop' => 1,
    'is_destruct' => 1,
    'crystal_type' => 'b',
    'consume_type' => 'consume_type_normal',
  ],
  2586 => 
  [
    'item_id' => 2586,
    'icon' => 'weapon_dual_sword_i00',
    'name' => 'Katana Ultimate Sword',
    'additionalname' => NULL,
    'description' => 'When enchanting dual swords, two-handed swords/ blunts, and fists, the P. Atk. bonus is higher than that of one-handed weapons. 1 common soul crystal and 1 special soul crystal can be inserted.',
    'is_trade' => 1,
    'is_drop' => 1,
    'is_destruct' => 1,
    'crystal_type' => 'b',
    'consume_type' => 'consume_type_normal',
  ],
  2587 => 
  [
    'item_id' => 2587,
    'icon' => 'weapon_dual_sword_i00',
    'name' => 'Katana Sword of Delusion',
    'additionalname' => NULL,
    'description' => 'When enchanting dual swords, two-handed swords/ blunts, and fists, the P. Atk. bonus is higher than that of one-handed weapons. 1 common soul crystal and 1 special soul crystal can be inserted.',
    'is_trade' => 1,
    'is_drop' => 1,
    'is_destruct' => 1,
    'crystal_type' => 'b',
    'consume_type' => 'consume_type_normal',
  ],
  2588 => 
  [
    'item_id' => 2588,
    'icon' => 'weapon_dual_sword_i00',
    'name' => 'Katana Sword of Nightmare',
    'additionalname' => NULL,
    'description' => 'When enchanting dual swords, two-handed swords/ blunts, and fists, the P. Atk. bonus is higher than that of one-handed weapons. 1 common soul crystal and 1 special soul crystal can be inserted.',
    'is_trade' => 1,
    'is_drop' => 1,
    'is_destruct' => 1,
    'crystal_type' => 'b',
    'consume_type' => 'consume_type_normal',
  ],
  2589 => 
  [
    'item_id' => 2589,
    'icon' => 'weapon_dual_sword_i00',
    'name' => 'Katana Tsurugi',
    'additionalname' => NULL,
    'description' => 'When enchanting dual swords, two-handed swords/ blunts, and fists, the P. Atk. bonus is higher than that of one-handed weapons. 1 common soul crystal and 1 special soul crystal can be inserted.',
    'is_trade' => 1,
    'is_drop' => 1,
    'is_destruct' => 1,
    'crystal_type' => 'b',
    'consume_type' => 'consume_type_normal',
  ],
  2590 => 
  [
    'item_id' => 2590,
    'icon' => 'weapon_dual_sword_i00',
    'name' => 'Katana Samurai Long Sword',
    'additionalname' => NULL,
    'description' => 'When enchanting dual swords, two-handed swords/ blunts, and fists, the P. Atk. bonus is higher than that of one-handed weapons. 1 common soul crystal and 1 special soul crystal can be inserted.',
    'is_trade' => 1,
    'is_drop' => 1,
    'is_destruct' => 1,
    'crystal_type' => 'b',
    'consume_type' => 'consume_type_normal',
  ],
  2591 => 
  [
    'item_id' => 2591,
    'icon' => 'weapon_dual_sword_i00',
    'name' => 'Spirit Sword Spirit Sword',
    'additionalname' => NULL,
    'description' => 'When enchanting dual swords, two-handed swords/ blunts, and fists, the P. Atk. bonus is higher than that of one-handed weapons. 1 common soul crystal and 1 special soul crystal can be inserted.',
    'is_trade' => 1,
    'is_drop' => 1,
    'is_destruct' => 1,
    'crystal_type' => 'c',
    'consume_type' => 'consume_type_normal',
  ],
  2592 => 
  [
    'item_id' => 2592,
    'icon' => 'weapon_dual_sword_i00',
    'name' => 'Spirit Sword Raid Sword',
    'additionalname' => NULL,
    'description' => 'When enchanting dual swords, two-handed swords/ blunts, and fists, the P. Atk. bonus is higher than that of one-handed weapons. 1 common soul crystal and 1 special soul crystal can be inserted.',
    'is_trade' => 1,
    'is_drop' => 1,
    'is_destruct' => 1,
    'crystal_type' => 'c',
    'consume_type' => 'consume_type_normal',
  ],
  2593 => 
  [
    'item_id' => 2593,
    'icon' => 'weapon_dual_sword_i00',
    'name' => 'Spirit Sword Caliburs',
    'additionalname' => NULL,
    'description' => 'When enchanting dual swords, two-handed swords/ blunts, and fists, the P. Atk. bonus is higher than that of one-handed weapons. 1 common soul crystal and 1 special soul crystal can be inserted.',
    'is_trade' => 1,
    'is_drop' => 1,
    'is_destruct' => 1,
    'crystal_type' => 'b',
    'consume_type' => 'consume_type_normal',
  ],
  2594 => 
  [
    'item_id' => 2594,
    'icon' => 'weapon_dual_sword_i00',
    'name' => 'Spirit Sword Ultimate Sword',
    'additionalname' => NULL,
    'description' => 'When enchanting dual swords, two-handed swords/ blunts, and fists, the P. Atk. bonus is higher than that of one-handed weapons. 1 common soul crystal and 1 special soul crystal can be inserted.',
    'is_trade' => 1,
    'is_drop' => 1,
    'is_destruct' => 1,
    'crystal_type' => 'b',
    'consume_type' => 'consume_type_normal',
  ],
  2595 => 
  [
    'item_id' => 2595,
    'icon' => 'weapon_dual_sword_i00',
    'name' => 'Spirit Sword Sword of Delusion',
    'additionalname' => NULL,
    'description' => 'When enchanting dual swords, two-handed swords/ blunts, and fists, the P. Atk. bonus is higher than that of one-handed weapons. 1 common soul crystal and 1 special soul crystal can be inserted.',
    'is_trade' => 1,
    'is_drop' => 1,
    'is_destruct' => 1,
    'crystal_type' => 'b',
    'consume_type' => 'consume_type_normal',
  ],
  2596 => 
  [
    'item_id' => 2596,
    'icon' => 'weapon_dual_sword_i00',
    'name' => 'Spirit Sword Sword of Nightmare',
    'additionalname' => NULL,
    'description' => 'When enchanting dual swords, two-handed swords/ blunts, and fists, the P. Atk. bonus is higher than that of one-handed weapons. 1 common soul crystal and 1 special soul crystal can be inserted.',
    'is_trade' => 1,
    'is_drop' => 1,
    'is_destruct' => 1,
    'crystal_type' => 'b',
    'consume_type' => 'consume_type_normal',
  ],
  2597 => 
  [
    'item_id' => 2597,
    'icon' => 'weapon_dual_sword_i00',
    'name' => 'Spirit Sword Tsurugi',
    'additionalname' => NULL,
    'description' => 'When enchanting dual swords, two-handed swords/ blunts, and fists, the P. Atk. bonus is higher than that of one-handed weapons. 1 common soul crystal and 1 special soul crystal can be inserted.',
    'is_trade' => 1,
    'is_drop' => 1,
    'is_destruct' => 1,
    'crystal_type' => 'b',
    'consume_type' => 'consume_type_normal',
  ],
  2598 => 
  [
    'item_id' => 2598,
    'icon' => 'weapon_dual_sword_i00',
    'name' => 'Spirit Sword Samurai Long Sword',
    'additionalname' => NULL,
    'description' => 'When enchanting dual swords, two-handed swords/ blunts, and fists, the P. Atk. bonus is higher than that of one-handed weapons. 1 common soul crystal and 1 special soul crystal can be inserted.',
    'is_trade' => 1,
    'is_drop' => 1,
    'is_destruct' => 1,
    'crystal_type' => 'b',
    'consume_type' => 'consume_type_normal',
  ],
  2599 => 
  [
    'item_id' => 2599,
    'icon' => 'weapon_dual_sword_i00',
    'name' => 'Raid Sword Raid Sword',
    'additionalname' => NULL,
    'description' => 'When enchanting dual swords, two-handed swords/ blunts, and fists, the P. Atk. bonus is higher than that of one-handed weapons. 1 common soul crystal and 1 special soul crystal can be inserted.',
    'is_trade' => 1,
    'is_drop' => 1,
    'is_destruct' => 1,
    'crystal_type' => 'c',
    'consume_type' => 'consume_type_normal',
  ],
];