<?php return [
  25100 => 
  [
    'item_id' => 25100,
    'icon' => 'g_scrl_change_chest',
    'name' => 'Formal Wear Appearance Stone',
    'additionalname' => 'Top-grade / Debuff Reflect',
    'description' => 'Changes the appearance of the entire armor into that of a Formal Wear. Tops and one-pieces only. Modified armor can be restored to their original appearance with a Restoration Stone. When modified, Debuff Reflect + 10%.',
    'is_trade' => 1,
    'is_drop' => 1,
    'is_destruct' => 1,
    'crystal_type' => 'none',
    'consume_type' => 'consume_type_stackable',
  ],
  25101 => 
  [
    'item_id' => 25101,
    'icon' => 'g_scrl_change_chest',
    'name' => 'Formal Wear Appearance Stone',
    'additionalname' => 'Top-grade / Damage Reflect Resistance',
    'description' => 'Changes the appearance of the entire armor into that of a Formal Wear. Tops and one-pieces only. Modified armor can be restored to their original appearance with a Restoration Stone. When modified, Debuff Reflect Resistance + 15%.',
    'is_trade' => 1,
    'is_drop' => 1,
    'is_destruct' => 1,
    'crystal_type' => 'none',
    'consume_type' => 'consume_type_stackable',
  ],
  25102 => 
  [
    'item_id' => 25102,
    'icon' => 'g_scrl_change_chest',
    'name' => 'Formal Wear Appearance Stone',
    'additionalname' => 'Top-grade / Ranged Resistance',
    'description' => 'Changes the appearance of the entire armor into that of a Formal Wear. Tops and one-pieces only. Modified armor can be restored to their original appearance with a Restoration Stone. When modified, Bow/Crossbow Resistance + 10%.',
    'is_trade' => 1,
    'is_drop' => 1,
    'is_destruct' => 1,
    'crystal_type' => 'none',
    'consume_type' => 'consume_type_stackable',
  ],
  25103 => 
  [
    'item_id' => 25103,
    'icon' => 'g_scrl_change_chest',
    'name' => 'Formal Wear Appearance Stone',
    'additionalname' => 'Top-grade / P. Def. Increase',
    'description' => 'Changes the appearance of the entire armor into that of a Formal Wear. Tops and one-pieces only. Modified armor can be restored to their original appearance with a Restoration Stone. When modified, P. Def. + 10%.',
    'is_trade' => 1,
    'is_drop' => 1,
    'is_destruct' => 1,
    'crystal_type' => 'none',
    'consume_type' => 'consume_type_stackable',
  ],
  25104 => 
  [
    'item_id' => 25104,
    'icon' => 'g_scrl_change_chest',
    'name' => 'Formal Wear Appearance Stone',
    'additionalname' => 'Top-grade / M. Def. Increase',
    'description' => 'Changes the appearance of the entire armor into that of a Formal Wear. Tops and one-pieces only. Modified armor can be restored to their original appearance with a Restoration Stone. When modified, M. Def. + 10%.',
    'is_trade' => 1,
    'is_drop' => 1,
    'is_destruct' => 1,
    'crystal_type' => 'none',
    'consume_type' => 'consume_type_stackable',
  ],
  25105 => 
  [
    'item_id' => 25105,
    'icon' => 'g_scrl_change_chest',
    'name' => 'Formal Wear Appearance Stone',
    'additionalname' => 'Top-grade / Attribute Resistance',
    'description' => 'Changes the appearance of the entire armor into that of a Formal Wear. Tops and one-pieces only. Modified armor can be restored to their original appearance with a Restoration Stone. When modified, Attribute Resistance + 15.',
    'is_trade' => 1,
    'is_drop' => 1,
    'is_destruct' => 1,
    'crystal_type' => 'none',
    'consume_type' => 'consume_type_stackable',
  ],
  25106 => 
  [
    'item_id' => 25106,
    'icon' => 'g_scrl_change_chest',
    'name' => 'Formal Wear Appearance Stone',
    'additionalname' => 'Top-grade / Received Heal Amount Increase',
    'description' => 'Changes the appearance of the entire armor into that of a Formal Wear. Tops and one-pieces only. Modified armor can be restored to their original appearance with a Restoration Stone. When modified, Received Heal Amount + 15%.',
    'is_trade' => 1,
    'is_drop' => 1,
    'is_destruct' => 1,
    'crystal_type' => 'none',
    'consume_type' => 'consume_type_stackable',
  ],
  25107 => 
  [
    'item_id' => 25107,
    'icon' => 'g_scrl_change_chest',
    'name' => 'Formal Wear Appearance Stone',
    'additionalname' => 'Top-grade / Max. HP Increase',
    'description' => 'Changes the appearance of the entire armor into that of a Formal Wear. Tops and one-pieces only. Modified armor can be restored to their original appearance with a Restoration Stone. When modified, Max. HP + 15%.',
    'is_trade' => 1,
    'is_drop' => 1,
    'is_destruct' => 1,
    'crystal_type' => 'none',
    'consume_type' => 'consume_type_stackable',
  ],
  25108 => 
  [
    'item_id' => 25108,
    'icon' => 'g_scrl_change_chest',
    'name' => 'Formal Wear Appearance Stone',
    'additionalname' => 'Top-grade / Max. MP Increase',
    'description' => 'Changes the appearance of the entire armor into that of a Formal Wear. Tops and one-pieces only. Modified armor can be restored to their original appearance with a Restoration Stone. When modified, Max. MP + 10%.',
    'is_trade' => 1,
    'is_drop' => 1,
    'is_destruct' => 1,
    'crystal_type' => 'none',
    'consume_type' => 'consume_type_stackable',
  ],
  25109 => 
  [
    'item_id' => 25109,
    'icon' => 'g_scrl_change_chest',
    'name' => 'Formal Wear Appearance Stone',
    'additionalname' => 'Top-grade / Max CP Increase',
    'description' => 'Changes the appearance of the entire armor into that of a Formal Wear. Tops and one-pieces only. Modified armor can be restored to their original appearance with a Restoration Stone. When modified, Max. CP + 15%.',
    'is_trade' => 1,
    'is_drop' => 1,
    'is_destruct' => 1,
    'crystal_type' => 'none',
    'consume_type' => 'consume_type_stackable',
  ],
  25110 => 
  [
    'item_id' => 25110,
    'icon' => 'g_scrl_change_chest',
    'name' => 'Formal Wear Appearance Stone',
    'additionalname' => 'Top-grade / Speed Increase',
    'description' => 'Changes the appearance of the entire armor into that of a Formal Wear. Tops and one-pieces only. Modified armor can be restored to their original appearance with a Restoration Stone. When modified, Speed + 15.',
    'is_trade' => 1,
    'is_drop' => 1,
    'is_destruct' => 1,
    'crystal_type' => 'none',
    'consume_type' => 'consume_type_stackable',
  ],
  25111 => 
  [
    'item_id' => 25111,
    'icon' => 'g_scrl_change_chest',
    'name' => 'Formal Wear Appearance Stone',
    'additionalname' => 'Top-grade / HP Recovery Bonus Increase',
    'description' => 'Changes the appearance of the entire armor into that of a Formal Wear. Tops and one-pieces only. Modified armor can be restored to their original appearance with a Restoration Stone. When modified, HP Recovery Bonus + 16.',
    'is_trade' => 1,
    'is_drop' => 1,
    'is_destruct' => 1,
    'crystal_type' => 'none',
    'consume_type' => 'consume_type_stackable',
  ],
  25112 => 
  [
    'item_id' => 25112,
    'icon' => 'g_scrl_change_chest',
    'name' => 'Formal Wear Appearance Stone',
    'additionalname' => 'Top-grade / MP Recovery Bonus Increase',
    'description' => 'Changes the appearance of the entire armor into that of a Formal Wear. Tops and one-pieces only. Modified armor can be restored to their original appearance with a Restoration Stone. When modified, MP Recovery Bonus + 8.',
    'is_trade' => 1,
    'is_drop' => 1,
    'is_destruct' => 1,
    'crystal_type' => 'none',
    'consume_type' => 'consume_type_stackable',
  ],
  25113 => 
  [
    'item_id' => 25113,
    'icon' => 'g_scrl_change_chest',
    'name' => 'Formal Wear Appearance Stone',
    'additionalname' => 'Top-grade / Evasion Increase',
    'description' => 'Changes the appearance of the entire armor into that of a Formal Wear. Tops and one-pieces only. Modified armor can be restored to their original appearance with a Restoration Stone. When modified, P./M. Evasion + 8.',
    'is_trade' => 1,
    'is_drop' => 1,
    'is_destruct' => 1,
    'crystal_type' => 'none',
    'consume_type' => 'consume_type_stackable',
  ],
  25114 => 
  [
    'item_id' => 25114,
    'icon' => 'g_scrl_change_chest',
    'name' => 'Formal Wear Appearance Stone',
    'additionalname' => 'Top-grade / Option 15',
    'description' => 'Changes the appearance of the entire armor into that of a Formal Wear. Tops and one-pieces only. Modified armor can be restored to their original appearance with a Restoration Stone. When modified, Top-grade / Option + 15.',
    'is_trade' => 1,
    'is_drop' => 1,
    'is_destruct' => 1,
    'crystal_type' => 'none',
    'consume_type' => 'consume_type_stackable',
  ],
  25115 => 
  [
    'item_id' => 25115,
    'icon' => 'g_scrl_change_chest',
    'name' => 'Formal Wear Appearance Stone',
    'additionalname' => 'Top-grade / Option 16',
    'description' => 'Changes the appearance of the entire armor into that of a Formal Wear. Tops and one-pieces only. Modified armor can be restored to their original appearance with a Restoration Stone. When modified, Top-grade / Option + 16.',
    'is_trade' => 1,
    'is_drop' => 1,
    'is_destruct' => 1,
    'crystal_type' => 'none',
    'consume_type' => 'consume_type_stackable',
  ],
  25116 => 
  [
    'item_id' => 25116,
    'icon' => 'g_scrl_change_chest',
    'name' => 'Formal Wear Appearance Stone',
    'additionalname' => 'Top-grade / Option 17',
    'description' => 'Changes the appearance of the entire armor into that of a Formal Wear. Tops and one-pieces only. Modified armor can be restored to their original appearance with a Restoration Stone. When modified, Top-grade / Option + 17.',
    'is_trade' => 1,
    'is_drop' => 1,
    'is_destruct' => 1,
    'crystal_type' => 'none',
    'consume_type' => 'consume_type_stackable',
  ],
  25117 => 
  [
    'item_id' => 25117,
    'icon' => 'g_scrl_change_chest',
    'name' => 'Formal Wear Appearance Stone',
    'additionalname' => 'Top-grade / Option 18',
    'description' => 'Changes the appearance of the entire armor into that of a Formal Wear. Tops and one-pieces only. Modified armor can be restored to their original appearance with a Restoration Stone. When modified, Top-grade / Option + 18.',
    'is_trade' => 1,
    'is_drop' => 1,
    'is_destruct' => 1,
    'crystal_type' => 'none',
    'consume_type' => 'consume_type_stackable',
  ],
  25118 => 
  [
    'item_id' => 25118,
    'icon' => 'g_scrl_change_chest',
    'name' => 'Formal Wear Appearance Stone',
    'additionalname' => 'Top-grade / Option 19',
    'description' => 'Changes the appearance of the entire armor into that of a Formal Wear. Tops and one-pieces only. Modified armor can be restored to their original appearance with a Restoration Stone. When modified, Top-grade / Option + 19.',
    'is_trade' => 1,
    'is_drop' => 1,
    'is_destruct' => 1,
    'crystal_type' => 'none',
    'consume_type' => 'consume_type_stackable',
  ],
  25119 => 
  [
    'item_id' => 25119,
    'icon' => 'g_scrl_change_chest',
    'name' => 'Formal Wear Appearance Stone',
    'additionalname' => 'Top-grade / Option 20',
    'description' => 'Changes the appearance of the entire armor into that of a Formal Wear. Tops and one-pieces only. Modified armor can be restored to their original appearance with a Restoration Stone. When modified, Top-grade / Option + 20.',
    'is_trade' => 1,
    'is_drop' => 1,
    'is_destruct' => 1,
    'crystal_type' => 'none',
    'consume_type' => 'consume_type_stackable',
  ],
  25120 => 
  [
    'item_id' => 25120,
    'icon' => 'g_scrl_change_chest',
    'name' => 'Appearance Stone: Male Swimsuit No. 1',
    'additionalname' => 'Low-grade / Debuff Reflect',
    'description' => 'Changes the appearance of the entire armor into that of Male Swimsuit No. 1. Tops and one-pieces only. Modified armor can be restored to their original appearance with a Restoration Stone. When modified, Debuff Reflect + 3%.',
    'is_trade' => 1,
    'is_drop' => 1,
    'is_destruct' => 1,
    'crystal_type' => 'none',
    'consume_type' => 'consume_type_stackable',
  ],
  25121 => 
  [
    'item_id' => 25121,
    'icon' => 'g_scrl_change_chest',
    'name' => 'Appearance Stone: Male Swimsuit No. 1',
    'additionalname' => 'Low-grade / Damage Reflect Resistance',
    'description' => 'Changes the appearance of the entire armor into that of Male Swimsuit No. 1. Tops and one-pieces only. Modified armor can be restored to their original appearance with a Restoration Stone. When modified, Debuff Reflect Resistance + 5%.',
    'is_trade' => 1,
    'is_drop' => 1,
    'is_destruct' => 1,
    'crystal_type' => 'none',
    'consume_type' => 'consume_type_stackable',
  ],
  25122 => 
  [
    'item_id' => 25122,
    'icon' => 'g_scrl_change_chest',
    'name' => 'Appearance Stone: Male Swimsuit No. 1',
    'additionalname' => 'Low-grade / Ranged Resistance',
    'description' => 'Changes the appearance of the entire armor into that of Male Swimsuit No. 1. Tops and one-pieces only. Modified armor can be restored to their original appearance with a Restoration Stone. When modified, Bow/Crossbow Resistance + 3%.',
    'is_trade' => 1,
    'is_drop' => 1,
    'is_destruct' => 1,
    'crystal_type' => 'none',
    'consume_type' => 'consume_type_stackable',
  ],
  25123 => 
  [
    'item_id' => 25123,
    'icon' => 'g_scrl_change_chest',
    'name' => 'Appearance Stone: Male Swimsuit No. 1',
    'additionalname' => 'Low-grade / P. Def. Increase',
    'description' => 'Changes the appearance of the entire armor into that of Male Swimsuit No. 1. Tops and one-pieces only. Modified armor can be restored to their original appearance with a Restoration Stone. When modified, P. Def. + 3%.',
    'is_trade' => 1,
    'is_drop' => 1,
    'is_destruct' => 1,
    'crystal_type' => 'none',
    'consume_type' => 'consume_type_stackable',
  ],
  25124 => 
  [
    'item_id' => 25124,
    'icon' => 'g_scrl_change_chest',
    'name' => 'Appearance Stone: Male Swimsuit No. 1',
    'additionalname' => 'Low-grade / M. Def. Increase',
    'description' => 'Changes the appearance of the entire armor into that of Male Swimsuit No. 1. Tops and one-pieces only. Modified armor can be restored to their original appearance with a Restoration Stone. When modified, M. Def. + 3%.',
    'is_trade' => 1,
    'is_drop' => 1,
    'is_destruct' => 1,
    'crystal_type' => 'none',
    'consume_type' => 'consume_type_stackable',
  ],
  25125 => 
  [
    'item_id' => 25125,
    'icon' => 'g_scrl_change_chest',
    'name' => 'Appearance Stone: Male Swimsuit No. 1',
    'additionalname' => 'Low-grade / Attribute Resistance',
    'description' => 'Changes the appearance of the entire armor into that of Male Swimsuit No. 1. Tops and one-pieces only. Modified armor can be restored to their original appearance with a Restoration Stone. When modified, Attribute Resistance + 5.',
    'is_trade' => 1,
    'is_drop' => 1,
    'is_destruct' => 1,
    'crystal_type' => 'none',
    'consume_type' => 'consume_type_stackable',
  ],
  25126 => 
  [
    'item_id' => 25126,
    'icon' => 'g_scrl_change_chest',
    'name' => 'Appearance Stone: Male Swimsuit No. 1',
    'additionalname' => 'Low-grade / Received Heal Amount Increase',
    'description' => 'Changes the appearance of the entire armor into that of Male Swimsuit No. 1. Tops and one-pieces only. Modified armor can be restored to their original appearance with a Restoration Stone. When modified, Received Heal Amount + 3%.',
    'is_trade' => 1,
    'is_drop' => 1,
    'is_destruct' => 1,
    'crystal_type' => 'none',
    'consume_type' => 'consume_type_stackable',
  ],
  25127 => 
  [
    'item_id' => 25127,
    'icon' => 'g_scrl_change_chest',
    'name' => 'Appearance Stone: Male Swimsuit No. 1',
    'additionalname' => 'Low-grade / Max. HP Increase',
    'description' => 'Changes the appearance of the entire armor into that of Male Swimsuit No. 1. Tops and one-pieces only. Modified armor can be restored to their original appearance with a Restoration Stone. When modified, Max. HP + 3%.',
    'is_trade' => 1,
    'is_drop' => 1,
    'is_destruct' => 1,
    'crystal_type' => 'none',
    'consume_type' => 'consume_type_stackable',
  ],
  25128 => 
  [
    'item_id' => 25128,
    'icon' => 'g_scrl_change_chest',
    'name' => 'Appearance Stone: Male Swimsuit No. 1',
    'additionalname' => 'Low-grade / Max. MP Increase',
    'description' => 'Changes the appearance of the entire armor into that of Male Swimsuit No. 1. Tops and one-pieces only. Modified armor can be restored to their original appearance with a Restoration Stone. When modified, Max. MP + 3%.',
    'is_trade' => 1,
    'is_drop' => 1,
    'is_destruct' => 1,
    'crystal_type' => 'none',
    'consume_type' => 'consume_type_stackable',
  ],
  25129 => 
  [
    'item_id' => 25129,
    'icon' => 'g_scrl_change_chest',
    'name' => 'Appearance Stone: Male Swimsuit No. 1',
    'additionalname' => 'Low-grade / Max CP Increase',
    'description' => 'Changes the appearance of the entire armor into that of Male Swimsuit No. 1. Tops and one-pieces only. Modified armor can be restored to their original appearance with a Restoration Stone. When modified, Max. CP + 3%.',
    'is_trade' => 1,
    'is_drop' => 1,
    'is_destruct' => 1,
    'crystal_type' => 'none',
    'consume_type' => 'consume_type_stackable',
  ],
  25130 => 
  [
    'item_id' => 25130,
    'icon' => 'g_scrl_change_chest',
    'name' => 'Appearance Stone: Male Swimsuit No. 1',
    'additionalname' => 'Low-grade / Speed Increase',
    'description' => 'Changes the appearance of the entire armor into that of Male Swimsuit No. 1. Tops and one-pieces only. Modified armor can be restored to their original appearance with a Restoration Stone. When modified, Speed + 3.',
    'is_trade' => 1,
    'is_drop' => 1,
    'is_destruct' => 1,
    'crystal_type' => 'none',
    'consume_type' => 'consume_type_stackable',
  ],
  25131 => 
  [
    'item_id' => 25131,
    'icon' => 'g_scrl_change_chest',
    'name' => 'Appearance Stone: Male Swimsuit No. 1',
    'additionalname' => 'Low-grade / HP Recovery Bonus Increase',
    'description' => 'Changes the appearance of the entire armor into that of Male Swimsuit No. 1. Tops and one-pieces only. Modified armor can be restored to their original appearance with a Restoration Stone. When modified, HP Recovery Bonus + 5.',
    'is_trade' => 1,
    'is_drop' => 1,
    'is_destruct' => 1,
    'crystal_type' => 'none',
    'consume_type' => 'consume_type_stackable',
  ],
  25132 => 
  [
    'item_id' => 25132,
    'icon' => 'g_scrl_change_chest',
    'name' => 'Appearance Stone: Male Swimsuit No. 1',
    'additionalname' => 'Low-grade / MP Recovery Bonus Increase',
    'description' => 'Changes the appearance of the entire armor into that of Male Swimsuit No. 1. Tops and one-pieces only. Modified armor can be restored to their original appearance with a Restoration Stone. When modified, MP Recovery Bonus + 3.',
    'is_trade' => 1,
    'is_drop' => 1,
    'is_destruct' => 1,
    'crystal_type' => 'none',
    'consume_type' => 'consume_type_stackable',
  ],
  25133 => 
  [
    'item_id' => 25133,
    'icon' => 'g_scrl_change_chest',
    'name' => 'Appearance Stone: Male Swimsuit No. 1',
    'additionalname' => 'Low-grade / Evasion Increase',
    'description' => 'Changes the appearance of the entire armor into that of Male Swimsuit No. 1. Tops and one-pieces only. Modified armor can be restored to their original appearance with a Restoration Stone. When modified, P./M. Evasion + 3.',
    'is_trade' => 1,
    'is_drop' => 1,
    'is_destruct' => 1,
    'crystal_type' => 'none',
    'consume_type' => 'consume_type_stackable',
  ],
  25134 => 
  [
    'item_id' => 25134,
    'icon' => 'g_scrl_change_chest',
    'name' => 'Appearance Stone: Male Swimsuit No. 1',
    'additionalname' => 'Low-grade / Option 15',
    'description' => 'Changes the appearance of the entire armor into that of Male Swimsuit No. 1. Tops and one-pieces only. Modified armor can be restored to their original appearance with a Restoration Stone. When modified, Low-grade / Option + 15.',
    'is_trade' => 1,
    'is_drop' => 1,
    'is_destruct' => 1,
    'crystal_type' => 'none',
    'consume_type' => 'consume_type_stackable',
  ],
  25135 => 
  [
    'item_id' => 25135,
    'icon' => 'g_scrl_change_chest',
    'name' => 'Appearance Stone: Male Swimsuit No. 1',
    'additionalname' => 'Low-grade / Option 16',
    'description' => 'Changes the appearance of the entire armor into that of Male Swimsuit No. 1. Tops and one-pieces only. Modified armor can be restored to their original appearance with a Restoration Stone. When modified, Low-grade / Option + 16.',
    'is_trade' => 1,
    'is_drop' => 1,
    'is_destruct' => 1,
    'crystal_type' => 'none',
    'consume_type' => 'consume_type_stackable',
  ],
  25136 => 
  [
    'item_id' => 25136,
    'icon' => 'g_scrl_change_chest',
    'name' => 'Appearance Stone: Male Swimsuit No. 1',
    'additionalname' => 'Low-grade / Option 17',
    'description' => 'Changes the appearance of the entire armor into that of Male Swimsuit No. 1. Tops and one-pieces only. Modified armor can be restored to their original appearance with a Restoration Stone. When modified, Low-grade / Option + 17.',
    'is_trade' => 1,
    'is_drop' => 1,
    'is_destruct' => 1,
    'crystal_type' => 'none',
    'consume_type' => 'consume_type_stackable',
  ],
  25137 => 
  [
    'item_id' => 25137,
    'icon' => 'g_scrl_change_chest',
    'name' => 'Appearance Stone: Male Swimsuit No. 1',
    'additionalname' => 'Low-grade / Option 18',
    'description' => 'Changes the appearance of the entire armor into that of Male Swimsuit No. 1. Tops and one-pieces only. Modified armor can be restored to their original appearance with a Restoration Stone. When modified, Low-grade / Option + 18.',
    'is_trade' => 1,
    'is_drop' => 1,
    'is_destruct' => 1,
    'crystal_type' => 'none',
    'consume_type' => 'consume_type_stackable',
  ],
  25138 => 
  [
    'item_id' => 25138,
    'icon' => 'g_scrl_change_chest',
    'name' => 'Appearance Stone: Male Swimsuit No. 1',
    'additionalname' => 'Low-grade / Option 19',
    'description' => 'Changes the appearance of the entire armor into that of Male Swimsuit No. 1. Tops and one-pieces only. Modified armor can be restored to their original appearance with a Restoration Stone. When modified, Low-grade / Option + 19.',
    'is_trade' => 1,
    'is_drop' => 1,
    'is_destruct' => 1,
    'crystal_type' => 'none',
    'consume_type' => 'consume_type_stackable',
  ],
  25139 => 
  [
    'item_id' => 25139,
    'icon' => 'g_scrl_change_chest',
    'name' => 'Appearance Stone: Male Swimsuit No. 1',
    'additionalname' => 'Low-grade / Option 20',
    'description' => 'Changes the appearance of the entire armor into that of Male Swimsuit No. 1. Tops and one-pieces only. Modified armor can be restored to their original appearance with a Restoration Stone. When modified, Low-grade / Option + 20.',
    'is_trade' => 1,
    'is_drop' => 1,
    'is_destruct' => 1,
    'crystal_type' => 'none',
    'consume_type' => 'consume_type_stackable',
  ],
  25140 => 
  [
    'item_id' => 25140,
    'icon' => 'g_scrl_change_chest',
    'name' => 'Appearance Stone: Male Swimsuit No. 1',
    'additionalname' => 'Mid-grade / Debuff Reflect',
    'description' => 'Changes the appearance of the entire armor into that of Male Swimsuit No. 1. Tops and one-pieces only. Modified armor can be restored to their original appearance with a Restoration Stone. When modified, Debuff Reflect + 5%.',
    'is_trade' => 1,
    'is_drop' => 1,
    'is_destruct' => 1,
    'crystal_type' => 'none',
    'consume_type' => 'consume_type_stackable',
  ],
  25141 => 
  [
    'item_id' => 25141,
    'icon' => 'g_scrl_change_chest',
    'name' => 'Appearance Stone: Male Swimsuit No. 1',
    'additionalname' => 'Mid-grade / Damage Reflect Resistance',
    'description' => 'Changes the appearance of the entire armor into that of Male Swimsuit No. 1. Tops and one-pieces only. Modified armor can be restored to their original appearance with a Restoration Stone. When modified, Debuff Reflect Resistance + 7%.',
    'is_trade' => 1,
    'is_drop' => 1,
    'is_destruct' => 1,
    'crystal_type' => 'none',
    'consume_type' => 'consume_type_stackable',
  ],
  25142 => 
  [
    'item_id' => 25142,
    'icon' => 'g_scrl_change_chest',
    'name' => 'Appearance Stone: Male Swimsuit No. 1',
    'additionalname' => 'Mid-grade / Ranged Resistance',
    'description' => 'Changes the appearance of the entire armor into that of Male Swimsuit No. 1. Tops and one-pieces only. Modified armor can be restored to their original appearance with a Restoration Stone. When modified, Bow/Crossbow Resistance + 5%.',
    'is_trade' => 1,
    'is_drop' => 1,
    'is_destruct' => 1,
    'crystal_type' => 'none',
    'consume_type' => 'consume_type_stackable',
  ],
  25143 => 
  [
    'item_id' => 25143,
    'icon' => 'g_scrl_change_chest',
    'name' => 'Appearance Stone: Male Swimsuit No. 1',
    'additionalname' => 'Mid-grade / P. Def. Increase',
    'description' => 'Changes the appearance of the entire armor into that of Male Swimsuit No. 1. Tops and one-pieces only. Modified armor can be restored to their original appearance with a Restoration Stone. When modified, P. Def. + 5%.',
    'is_trade' => 1,
    'is_drop' => 1,
    'is_destruct' => 1,
    'crystal_type' => 'none',
    'consume_type' => 'consume_type_stackable',
  ],
  25144 => 
  [
    'item_id' => 25144,
    'icon' => 'g_scrl_change_chest',
    'name' => 'Appearance Stone: Male Swimsuit No. 1',
    'additionalname' => 'Mid-grade / M. Def. Increase',
    'description' => 'Changes the appearance of the entire armor into that of Male Swimsuit No. 1. Tops and one-pieces only. Modified armor can be restored to their original appearance with a Restoration Stone. When modified, M. Def. + 5%.',
    'is_trade' => 1,
    'is_drop' => 1,
    'is_destruct' => 1,
    'crystal_type' => 'none',
    'consume_type' => 'consume_type_stackable',
  ],
  25145 => 
  [
    'item_id' => 25145,
    'icon' => 'g_scrl_change_chest',
    'name' => 'Appearance Stone: Male Swimsuit No. 1',
    'additionalname' => 'Mid-grade / Attribute Resistance',
    'description' => 'Changes the appearance of the entire armor into that of Male Swimsuit No. 1. Tops and one-pieces only. Modified armor can be restored to their original appearance with a Restoration Stone. When modified, Attribute Resistance + 7.',
    'is_trade' => 1,
    'is_drop' => 1,
    'is_destruct' => 1,
    'crystal_type' => 'none',
    'consume_type' => 'consume_type_stackable',
  ],
  25146 => 
  [
    'item_id' => 25146,
    'icon' => 'g_scrl_change_chest',
    'name' => 'Appearance Stone: Male Swimsuit No. 1',
    'additionalname' => 'Mid-grade / Received Heal Amount Increase',
    'description' => 'Changes the appearance of the entire armor into that of Male Swimsuit No. 1. Tops and one-pieces only. Modified armor can be restored to their original appearance with a Restoration Stone. When modified, Received Heal Amount + 7%.',
    'is_trade' => 1,
    'is_drop' => 1,
    'is_destruct' => 1,
    'crystal_type' => 'none',
    'consume_type' => 'consume_type_stackable',
  ],
  25147 => 
  [
    'item_id' => 25147,
    'icon' => 'g_scrl_change_chest',
    'name' => 'Appearance Stone: Male Swimsuit No. 1',
    'additionalname' => 'Mid-grade / Max. HP Increase',
    'description' => 'Changes the appearance of the entire armor into that of Male Swimsuit No. 1. Tops and one-pieces only. Modified armor can be restored to their original appearance with a Restoration Stone. When modified, Max. HP + 7%.',
    'is_trade' => 1,
    'is_drop' => 1,
    'is_destruct' => 1,
    'crystal_type' => 'none',
    'consume_type' => 'consume_type_stackable',
  ],
  25148 => 
  [
    'item_id' => 25148,
    'icon' => 'g_scrl_change_chest',
    'name' => 'Appearance Stone: Male Swimsuit No. 1',
    'additionalname' => 'Mid-grade / Max. MP Increase',
    'description' => 'Changes the appearance of the entire armor into that of Male Swimsuit No. 1. Tops and one-pieces only. Modified armor can be restored to their original appearance with a Restoration Stone. When modified, Max. MP + 5%.',
    'is_trade' => 1,
    'is_drop' => 1,
    'is_destruct' => 1,
    'crystal_type' => 'none',
    'consume_type' => 'consume_type_stackable',
  ],
  25149 => 
  [
    'item_id' => 25149,
    'icon' => 'g_scrl_change_chest',
    'name' => 'Appearance Stone: Male Swimsuit No. 1',
    'additionalname' => 'Mid-grade / Max CP Increase',
    'description' => 'Changes the appearance of the entire armor into that of Male Swimsuit No. 1. Tops and one-pieces only. Modified armor can be restored to their original appearance with a Restoration Stone. When modified, Max. CP + 7%.',
    'is_trade' => 1,
    'is_drop' => 1,
    'is_destruct' => 1,
    'crystal_type' => 'none',
    'consume_type' => 'consume_type_stackable',
  ],
  25150 => 
  [
    'item_id' => 25150,
    'icon' => 'g_scrl_change_chest',
    'name' => 'Appearance Stone: Male Swimsuit No. 1',
    'additionalname' => 'Mid-grade / Speed Increase',
    'description' => 'Changes the appearance of the entire armor into that of Male Swimsuit No. 1. Tops and one-pieces only. Modified armor can be restored to their original appearance with a Restoration Stone. When modified, Speed + 7.',
    'is_trade' => 1,
    'is_drop' => 1,
    'is_destruct' => 1,
    'crystal_type' => 'none',
    'consume_type' => 'consume_type_stackable',
  ],
  25151 => 
  [
    'item_id' => 25151,
    'icon' => 'g_scrl_change_chest',
    'name' => 'Appearance Stone: Male Swimsuit No. 1',
    'additionalname' => 'Mid-grade / HP Recovery Bonus Increase',
    'description' => 'Changes the appearance of the entire armor into that of Male Swimsuit No. 1. Tops and one-pieces only. Modified armor can be restored to their original appearance with a Restoration Stone. When modified, HP Recovery Bonus + 8.',
    'is_trade' => 1,
    'is_drop' => 1,
    'is_destruct' => 1,
    'crystal_type' => 'none',
    'consume_type' => 'consume_type_stackable',
  ],
  25152 => 
  [
    'item_id' => 25152,
    'icon' => 'g_scrl_change_chest',
    'name' => 'Appearance Stone: Male Swimsuit No. 1',
    'additionalname' => 'Mid-grade / MP Recovery Bonus Increase',
    'description' => 'Changes the appearance of the entire armor into that of Male Swimsuit No. 1. Tops and one-pieces only. Modified armor can be restored to their original appearance with a Restoration Stone. When modified, MP Recovery Bonus + 4.',
    'is_trade' => 1,
    'is_drop' => 1,
    'is_destruct' => 1,
    'crystal_type' => 'none',
    'consume_type' => 'consume_type_stackable',
  ],
  25153 => 
  [
    'item_id' => 25153,
    'icon' => 'g_scrl_change_chest',
    'name' => 'Appearance Stone: Male Swimsuit No. 1',
    'additionalname' => 'Mid-grade / Evasion Increase',
    'description' => 'Changes the appearance of the entire armor into that of Male Swimsuit No. 1. Tops and one-pieces only. Modified armor can be restored to their original appearance with a Restoration Stone. When modified, P./M. Evasion + 4.',
    'is_trade' => 1,
    'is_drop' => 1,
    'is_destruct' => 1,
    'crystal_type' => 'none',
    'consume_type' => 'consume_type_stackable',
  ],
  25154 => 
  [
    'item_id' => 25154,
    'icon' => 'g_scrl_change_chest',
    'name' => 'Appearance Stone: Male Swimsuit No. 1',
    'additionalname' => 'Mid-grade / Option 15',
    'description' => 'Changes the appearance of the entire armor into that of Male Swimsuit No. 1. Tops and one-pieces only. Modified armor can be restored to their original appearance with a Restoration Stone. When modified, Mid-grade / Option + 15.',
    'is_trade' => 1,
    'is_drop' => 1,
    'is_destruct' => 1,
    'crystal_type' => 'none',
    'consume_type' => 'consume_type_stackable',
  ],
  25155 => 
  [
    'item_id' => 25155,
    'icon' => 'g_scrl_change_chest',
    'name' => 'Appearance Stone: Male Swimsuit No. 1',
    'additionalname' => 'Mid-grade / Option 16',
    'description' => 'Changes the appearance of the entire armor into that of Male Swimsuit No. 1. Tops and one-pieces only. Modified armor can be restored to their original appearance with a Restoration Stone. When modified, Mid-grade / Option + 16.',
    'is_trade' => 1,
    'is_drop' => 1,
    'is_destruct' => 1,
    'crystal_type' => 'none',
    'consume_type' => 'consume_type_stackable',
  ],
  25156 => 
  [
    'item_id' => 25156,
    'icon' => 'g_scrl_change_chest',
    'name' => 'Appearance Stone: Male Swimsuit No. 1',
    'additionalname' => 'Mid-grade / Option 17',
    'description' => 'Changes the appearance of the entire armor into that of Male Swimsuit No. 1. Tops and one-pieces only. Modified armor can be restored to their original appearance with a Restoration Stone. When modified, Mid-grade / Option + 17.',
    'is_trade' => 1,
    'is_drop' => 1,
    'is_destruct' => 1,
    'crystal_type' => 'none',
    'consume_type' => 'consume_type_stackable',
  ],
  25157 => 
  [
    'item_id' => 25157,
    'icon' => 'g_scrl_change_chest',
    'name' => 'Appearance Stone: Male Swimsuit No. 1',
    'additionalname' => 'Mid-grade / Option 18',
    'description' => 'Changes the appearance of the entire armor into that of Male Swimsuit No. 1. Tops and one-pieces only. Modified armor can be restored to their original appearance with a Restoration Stone. When modified, Mid-grade / Option + 18.',
    'is_trade' => 1,
    'is_drop' => 1,
    'is_destruct' => 1,
    'crystal_type' => 'none',
    'consume_type' => 'consume_type_stackable',
  ],
  25158 => 
  [
    'item_id' => 25158,
    'icon' => 'g_scrl_change_chest',
    'name' => 'Appearance Stone: Male Swimsuit No. 1',
    'additionalname' => 'Mid-grade / Option 19',
    'description' => 'Changes the appearance of the entire armor into that of Male Swimsuit No. 1. Tops and one-pieces only. Modified armor can be restored to their original appearance with a Restoration Stone. When modified, Mid-grade / Option + 19.',
    'is_trade' => 1,
    'is_drop' => 1,
    'is_destruct' => 1,
    'crystal_type' => 'none',
    'consume_type' => 'consume_type_stackable',
  ],
  25159 => 
  [
    'item_id' => 25159,
    'icon' => 'g_scrl_change_chest',
    'name' => 'Appearance Stone: Male Swimsuit No. 1',
    'additionalname' => 'Mid-grade / Option 20',
    'description' => 'Changes the appearance of the entire armor into that of Male Swimsuit No. 1. Tops and one-pieces only. Modified armor can be restored to their original appearance with a Restoration Stone. When modified, Mid-grade / Option + 20.',
    'is_trade' => 1,
    'is_drop' => 1,
    'is_destruct' => 1,
    'crystal_type' => 'none',
    'consume_type' => 'consume_type_stackable',
  ],
  25160 => 
  [
    'item_id' => 25160,
    'icon' => 'g_scrl_change_chest',
    'name' => 'Appearance Stone: Male Swimsuit No. 1',
    'additionalname' => 'Top-grade / Debuff Reflect',
    'description' => 'Changes the appearance of the entire armor into that of Male Swimsuit No. 1. Tops and one-pieces only. Modified armor can be restored to their original appearance with a Restoration Stone. When modified, Debuff Reflect + 10%.',
    'is_trade' => 1,
    'is_drop' => 1,
    'is_destruct' => 1,
    'crystal_type' => 'none',
    'consume_type' => 'consume_type_stackable',
  ],
  25161 => 
  [
    'item_id' => 25161,
    'icon' => 'g_scrl_change_chest',
    'name' => 'Appearance Stone: Male Swimsuit No. 1',
    'additionalname' => 'Top-grade / Damage Reflect Resistance',
    'description' => 'Changes the appearance of the entire armor into that of Male Swimsuit No. 1. Tops and one-pieces only. Modified armor can be restored to their original appearance with a Restoration Stone. When modified, Debuff Reflect Resistance + 15%.',
    'is_trade' => 1,
    'is_drop' => 1,
    'is_destruct' => 1,
    'crystal_type' => 'none',
    'consume_type' => 'consume_type_stackable',
  ],
  25162 => 
  [
    'item_id' => 25162,
    'icon' => 'g_scrl_change_chest',
    'name' => 'Appearance Stone: Male Swimsuit No. 1',
    'additionalname' => 'Top-grade / Ranged Resistance',
    'description' => 'Changes the appearance of the entire armor into that of Male Swimsuit No. 1. Tops and one-pieces only. Modified armor can be restored to their original appearance with a Restoration Stone. When modified, Bow/Crossbow Resistance + 10%.',
    'is_trade' => 1,
    'is_drop' => 1,
    'is_destruct' => 1,
    'crystal_type' => 'none',
    'consume_type' => 'consume_type_stackable',
  ],
  25163 => 
  [
    'item_id' => 25163,
    'icon' => 'g_scrl_change_chest',
    'name' => 'Appearance Stone: Male Swimsuit No. 1',
    'additionalname' => 'Top-grade / P. Def. Increase',
    'description' => 'Changes the appearance of the entire armor into that of Male Swimsuit No. 1. Tops and one-pieces only. Modified armor can be restored to their original appearance with a Restoration Stone. When modified, P. Def. + 10%.',
    'is_trade' => 1,
    'is_drop' => 1,
    'is_destruct' => 1,
    'crystal_type' => 'none',
    'consume_type' => 'consume_type_stackable',
  ],
  25164 => 
  [
    'item_id' => 25164,
    'icon' => 'g_scrl_change_chest',
    'name' => 'Appearance Stone: Male Swimsuit No. 1',
    'additionalname' => 'Top-grade / M. Def. Increase',
    'description' => 'Changes the appearance of the entire armor into that of Male Swimsuit No. 1. Tops and one-pieces only. Modified armor can be restored to their original appearance with a Restoration Stone. When modified, M. Def. + 10%.',
    'is_trade' => 1,
    'is_drop' => 1,
    'is_destruct' => 1,
    'crystal_type' => 'none',
    'consume_type' => 'consume_type_stackable',
  ],
  25165 => 
  [
    'item_id' => 25165,
    'icon' => 'g_scrl_change_chest',
    'name' => 'Appearance Stone: Male Swimsuit No. 1',
    'additionalname' => 'Top-grade / Attribute Resistance',
    'description' => 'Changes the appearance of the entire armor into that of Male Swimsuit No. 1. Tops and one-pieces only. Modified armor can be restored to their original appearance with a Restoration Stone. When modified, Attribute Resistance + 15.',
    'is_trade' => 1,
    'is_drop' => 1,
    'is_destruct' => 1,
    'crystal_type' => 'none',
    'consume_type' => 'consume_type_stackable',
  ],
  25166 => 
  [
    'item_id' => 25166,
    'icon' => 'g_scrl_change_chest',
    'name' => 'Appearance Stone: Male Swimsuit No. 1',
    'additionalname' => 'Top-grade / Received Heal Amount Increase',
    'description' => 'Changes the appearance of the entire armor into that of Male Swimsuit No. 1. Tops and one-pieces only. Modified armor can be restored to their original appearance with a Restoration Stone. When modified, Received Heal Amount + 15%.',
    'is_trade' => 1,
    'is_drop' => 1,
    'is_destruct' => 1,
    'crystal_type' => 'none',
    'consume_type' => 'consume_type_stackable',
  ],
  25167 => 
  [
    'item_id' => 25167,
    'icon' => 'g_scrl_change_chest',
    'name' => 'Appearance Stone: Male Swimsuit No. 1',
    'additionalname' => 'Top-grade / Max. HP Increase',
    'description' => 'Changes the appearance of the entire armor into that of Male Swimsuit No. 1. Tops and one-pieces only. Modified armor can be restored to their original appearance with a Restoration Stone. When modified, Max. HP + 15%.',
    'is_trade' => 1,
    'is_drop' => 1,
    'is_destruct' => 1,
    'crystal_type' => 'none',
    'consume_type' => 'consume_type_stackable',
  ],
  25168 => 
  [
    'item_id' => 25168,
    'icon' => 'g_scrl_change_chest',
    'name' => 'Appearance Stone: Male Swimsuit No. 1',
    'additionalname' => 'Top-grade / Max. MP Increase',
    'description' => 'Changes the appearance of the entire armor into that of Male Swimsuit No. 1. Tops and one-pieces only. Modified armor can be restored to their original appearance with a Restoration Stone. When modified, Max. MP + 10%.',
    'is_trade' => 1,
    'is_drop' => 1,
    'is_destruct' => 1,
    'crystal_type' => 'none',
    'consume_type' => 'consume_type_stackable',
  ],
  25169 => 
  [
    'item_id' => 25169,
    'icon' => 'g_scrl_change_chest',
    'name' => 'Appearance Stone: Male Swimsuit No. 1',
    'additionalname' => 'Top-grade / Max CP Increase',
    'description' => 'Changes the appearance of the entire armor into that of Male Swimsuit No. 1. Tops and one-pieces only. Modified armor can be restored to their original appearance with a Restoration Stone. When modified, Max. CP + 15%.',
    'is_trade' => 1,
    'is_drop' => 1,
    'is_destruct' => 1,
    'crystal_type' => 'none',
    'consume_type' => 'consume_type_stackable',
  ],
  25170 => 
  [
    'item_id' => 25170,
    'icon' => 'g_scrl_change_chest',
    'name' => 'Appearance Stone: Male Swimsuit No. 1',
    'additionalname' => 'Top-grade / Speed Increase',
    'description' => 'Changes the appearance of the entire armor into that of Male Swimsuit No. 1. Tops and one-pieces only. Modified armor can be restored to their original appearance with a Restoration Stone. When modified, Speed + 15.',
    'is_trade' => 1,
    'is_drop' => 1,
    'is_destruct' => 1,
    'crystal_type' => 'none',
    'consume_type' => 'consume_type_stackable',
  ],
  25171 => 
  [
    'item_id' => 25171,
    'icon' => 'g_scrl_change_chest',
    'name' => 'Appearance Stone: Male Swimsuit No. 1',
    'additionalname' => 'Top-grade / HP Recovery Bonus Increase',
    'description' => 'Changes the appearance of the entire armor into that of Male Swimsuit No. 1. Tops and one-pieces only. Modified armor can be restored to their original appearance with a Restoration Stone. When modified, HP Recovery Bonus + 16.',
    'is_trade' => 1,
    'is_drop' => 1,
    'is_destruct' => 1,
    'crystal_type' => 'none',
    'consume_type' => 'consume_type_stackable',
  ],
  25172 => 
  [
    'item_id' => 25172,
    'icon' => 'g_scrl_change_chest',
    'name' => 'Appearance Stone: Male Swimsuit No. 1',
    'additionalname' => 'Top-grade / MP Recovery Bonus Increase',
    'description' => 'Changes the appearance of the entire armor into that of Male Swimsuit No. 1. Tops and one-pieces only. Modified armor can be restored to their original appearance with a Restoration Stone. When modified, MP Recovery Bonus + 8.',
    'is_trade' => 1,
    'is_drop' => 1,
    'is_destruct' => 1,
    'crystal_type' => 'none',
    'consume_type' => 'consume_type_stackable',
  ],
  25173 => 
  [
    'item_id' => 25173,
    'icon' => 'g_scrl_change_chest',
    'name' => 'Appearance Stone: Male Swimsuit No. 1',
    'additionalname' => 'Top-grade / Evasion Increase',
    'description' => 'Changes the appearance of the entire armor into that of Male Swimsuit No. 1. Tops and one-pieces only. Modified armor can be restored to their original appearance with a Restoration Stone. When modified, P./M. Evasion + 8.',
    'is_trade' => 1,
    'is_drop' => 1,
    'is_destruct' => 1,
    'crystal_type' => 'none',
    'consume_type' => 'consume_type_stackable',
  ],
  25174 => 
  [
    'item_id' => 25174,
    'icon' => 'g_scrl_change_chest',
    'name' => 'Appearance Stone: Male Swimsuit No. 1',
    'additionalname' => 'Top-grade / Option 15',
    'description' => 'Changes the appearance of the entire armor into that of Male Swimsuit No. 1. Tops and one-pieces only. Modified armor can be restored to their original appearance with a Restoration Stone. When modified, Top-grade / Option + 15.',
    'is_trade' => 1,
    'is_drop' => 1,
    'is_destruct' => 1,
    'crystal_type' => 'none',
    'consume_type' => 'consume_type_stackable',
  ],
  25175 => 
  [
    'item_id' => 25175,
    'icon' => 'g_scrl_change_chest',
    'name' => 'Appearance Stone: Male Swimsuit No. 1',
    'additionalname' => 'Top-grade / Option 16',
    'description' => 'Changes the appearance of the entire armor into that of Male Swimsuit No. 1. Tops and one-pieces only. Modified armor can be restored to their original appearance with a Restoration Stone. When modified, Top-grade / Option + 16.',
    'is_trade' => 1,
    'is_drop' => 1,
    'is_destruct' => 1,
    'crystal_type' => 'none',
    'consume_type' => 'consume_type_stackable',
  ],
  25176 => 
  [
    'item_id' => 25176,
    'icon' => 'g_scrl_change_chest',
    'name' => 'Appearance Stone: Male Swimsuit No. 1',
    'additionalname' => 'Top-grade / Option 17',
    'description' => 'Changes the appearance of the entire armor into that of Male Swimsuit No. 1. Tops and one-pieces only. Modified armor can be restored to their original appearance with a Restoration Stone. When modified, Top-grade / Option + 17.',
    'is_trade' => 1,
    'is_drop' => 1,
    'is_destruct' => 1,
    'crystal_type' => 'none',
    'consume_type' => 'consume_type_stackable',
  ],
  25177 => 
  [
    'item_id' => 25177,
    'icon' => 'g_scrl_change_chest',
    'name' => 'Appearance Stone: Male Swimsuit No. 1',
    'additionalname' => 'Top-grade / Option 18',
    'description' => 'Changes the appearance of the entire armor into that of Male Swimsuit No. 1. Tops and one-pieces only. Modified armor can be restored to their original appearance with a Restoration Stone. When modified, Top-grade / Option + 18.',
    'is_trade' => 1,
    'is_drop' => 1,
    'is_destruct' => 1,
    'crystal_type' => 'none',
    'consume_type' => 'consume_type_stackable',
  ],
  25178 => 
  [
    'item_id' => 25178,
    'icon' => 'g_scrl_change_chest',
    'name' => 'Appearance Stone: Male Swimsuit No. 1',
    'additionalname' => 'Top-grade / Option 19',
    'description' => 'Changes the appearance of the entire armor into that of Male Swimsuit No. 1. Tops and one-pieces only. Modified armor can be restored to their original appearance with a Restoration Stone. When modified, Top-grade / Option + 19.',
    'is_trade' => 1,
    'is_drop' => 1,
    'is_destruct' => 1,
    'crystal_type' => 'none',
    'consume_type' => 'consume_type_stackable',
  ],
  25179 => 
  [
    'item_id' => 25179,
    'icon' => 'g_scrl_change_chest',
    'name' => 'Appearance Stone: Male Swimsuit No. 1',
    'additionalname' => 'Top-grade / Option 20',
    'description' => 'Changes the appearance of the entire armor into that of Male Swimsuit No. 1. Tops and one-pieces only. Modified armor can be restored to their original appearance with a Restoration Stone. When modified, Top-grade / Option + 20.',
    'is_trade' => 1,
    'is_drop' => 1,
    'is_destruct' => 1,
    'crystal_type' => 'none',
    'consume_type' => 'consume_type_stackable',
  ],
  25180 => 
  [
    'item_id' => 25180,
    'icon' => 'g_scrl_change_chest',
    'name' => 'Appearance Stone: Male Swimsuit No. 2',
    'additionalname' => 'Low-grade / Debuff Reflect',
    'description' => 'Changes the appearance of the entire armor into that of Male Swimsuit No. 2. Tops and one-pieces only. Modified armor can be restored to their original appearance with a Restoration Stone. When modified, Debuff Reflect + 3%.',
    'is_trade' => 1,
    'is_drop' => 1,
    'is_destruct' => 1,
    'crystal_type' => 'none',
    'consume_type' => 'consume_type_stackable',
  ],
  25181 => 
  [
    'item_id' => 25181,
    'icon' => 'g_scrl_change_chest',
    'name' => 'Appearance Stone: Male Swimsuit No. 2',
    'additionalname' => 'Low-grade / Damage Reflect Resistance',
    'description' => 'Changes the appearance of the entire armor into that of Male Swimsuit No. 2. Tops and one-pieces only. Modified armor can be restored to their original appearance with a Restoration Stone. When modified, Debuff Reflect Resistance + 5%.',
    'is_trade' => 1,
    'is_drop' => 1,
    'is_destruct' => 1,
    'crystal_type' => 'none',
    'consume_type' => 'consume_type_stackable',
  ],
  25182 => 
  [
    'item_id' => 25182,
    'icon' => 'g_scrl_change_chest',
    'name' => 'Appearance Stone: Male Swimsuit No. 2',
    'additionalname' => 'Low-grade / Ranged Resistance',
    'description' => 'Changes the appearance of the entire armor into that of Male Swimsuit No. 2. Tops and one-pieces only. Modified armor can be restored to their original appearance with a Restoration Stone. When modified, Bow/Crossbow Resistance + 3%.',
    'is_trade' => 1,
    'is_drop' => 1,
    'is_destruct' => 1,
    'crystal_type' => 'none',
    'consume_type' => 'consume_type_stackable',
  ],
  25183 => 
  [
    'item_id' => 25183,
    'icon' => 'g_scrl_change_chest',
    'name' => 'Appearance Stone: Male Swimsuit No. 2',
    'additionalname' => 'Low-grade / P. Def. Increase',
    'description' => 'Changes the appearance of the entire armor into that of Male Swimsuit No. 2. Tops and one-pieces only. Modified armor can be restored to their original appearance with a Restoration Stone. When modified, P. Def. + 3%.',
    'is_trade' => 1,
    'is_drop' => 1,
    'is_destruct' => 1,
    'crystal_type' => 'none',
    'consume_type' => 'consume_type_stackable',
  ],
  25184 => 
  [
    'item_id' => 25184,
    'icon' => 'g_scrl_change_chest',
    'name' => 'Appearance Stone: Male Swimsuit No. 2',
    'additionalname' => 'Low-grade / M. Def. Increase',
    'description' => 'Changes the appearance of the entire armor into that of Male Swimsuit No. 2. Tops and one-pieces only. Modified armor can be restored to their original appearance with a Restoration Stone. When modified, M. Def. + 3%.',
    'is_trade' => 1,
    'is_drop' => 1,
    'is_destruct' => 1,
    'crystal_type' => 'none',
    'consume_type' => 'consume_type_stackable',
  ],
  25185 => 
  [
    'item_id' => 25185,
    'icon' => 'g_scrl_change_chest',
    'name' => 'Appearance Stone: Male Swimsuit No. 2',
    'additionalname' => 'Low-grade / Attribute Resistance',
    'description' => 'Changes the appearance of the entire armor into that of Male Swimsuit No. 2. Tops and one-pieces only. Modified armor can be restored to their original appearance with a Restoration Stone. When modified, Attribute Resistance + 5.',
    'is_trade' => 1,
    'is_drop' => 1,
    'is_destruct' => 1,
    'crystal_type' => 'none',
    'consume_type' => 'consume_type_stackable',
  ],
  25186 => 
  [
    'item_id' => 25186,
    'icon' => 'g_scrl_change_chest',
    'name' => 'Appearance Stone: Male Swimsuit No. 2',
    'additionalname' => 'Low-grade / Received Heal Amount Increase',
    'description' => 'Changes the appearance of the entire armor into that of Male Swimsuit No. 2. Tops and one-pieces only. Modified armor can be restored to their original appearance with a Restoration Stone. When modified, Received Heal Amount + 3%.',
    'is_trade' => 1,
    'is_drop' => 1,
    'is_destruct' => 1,
    'crystal_type' => 'none',
    'consume_type' => 'consume_type_stackable',
  ],
  25187 => 
  [
    'item_id' => 25187,
    'icon' => 'g_scrl_change_chest',
    'name' => 'Appearance Stone: Male Swimsuit No. 2',
    'additionalname' => 'Low-grade / Max. HP Increase',
    'description' => 'Changes the appearance of the entire armor into that of Male Swimsuit No. 2. Tops and one-pieces only. Modified armor can be restored to their original appearance with a Restoration Stone. When modified, Max. HP + 3%.',
    'is_trade' => 1,
    'is_drop' => 1,
    'is_destruct' => 1,
    'crystal_type' => 'none',
    'consume_type' => 'consume_type_stackable',
  ],
  25188 => 
  [
    'item_id' => 25188,
    'icon' => 'g_scrl_change_chest',
    'name' => 'Appearance Stone: Male Swimsuit No. 2',
    'additionalname' => 'Low-grade / Max. MP Increase',
    'description' => 'Changes the appearance of the entire armor into that of Male Swimsuit No. 2. Tops and one-pieces only. Modified armor can be restored to their original appearance with a Restoration Stone. When modified, Max. MP + 3%.',
    'is_trade' => 1,
    'is_drop' => 1,
    'is_destruct' => 1,
    'crystal_type' => 'none',
    'consume_type' => 'consume_type_stackable',
  ],
  25189 => 
  [
    'item_id' => 25189,
    'icon' => 'g_scrl_change_chest',
    'name' => 'Appearance Stone: Male Swimsuit No. 2',
    'additionalname' => 'Low-grade / Max CP Increase',
    'description' => 'Changes the appearance of the entire armor into that of Male Swimsuit No. 2. Tops and one-pieces only. Modified armor can be restored to their original appearance with a Restoration Stone. When modified, Max. CP + 3%.',
    'is_trade' => 1,
    'is_drop' => 1,
    'is_destruct' => 1,
    'crystal_type' => 'none',
    'consume_type' => 'consume_type_stackable',
  ],
  25190 => 
  [
    'item_id' => 25190,
    'icon' => 'g_scrl_change_chest',
    'name' => 'Appearance Stone: Male Swimsuit No. 2',
    'additionalname' => 'Low-grade / Speed Increase',
    'description' => 'Changes the appearance of the entire armor into that of Male Swimsuit No. 2. Tops and one-pieces only. Modified armor can be restored to their original appearance with a Restoration Stone. When modified, Speed + 3.',
    'is_trade' => 1,
    'is_drop' => 1,
    'is_destruct' => 1,
    'crystal_type' => 'none',
    'consume_type' => 'consume_type_stackable',
  ],
  25191 => 
  [
    'item_id' => 25191,
    'icon' => 'g_scrl_change_chest',
    'name' => 'Appearance Stone: Male Swimsuit No. 2',
    'additionalname' => 'Low-grade / HP Recovery Bonus Increase',
    'description' => 'Changes the appearance of the entire armor into that of Male Swimsuit No. 2. Tops and one-pieces only. Modified armor can be restored to their original appearance with a Restoration Stone. When modified, HP Recovery Bonus + 5.',
    'is_trade' => 1,
    'is_drop' => 1,
    'is_destruct' => 1,
    'crystal_type' => 'none',
    'consume_type' => 'consume_type_stackable',
  ],
  25192 => 
  [
    'item_id' => 25192,
    'icon' => 'g_scrl_change_chest',
    'name' => 'Appearance Stone: Male Swimsuit No. 2',
    'additionalname' => 'Low-grade / MP Recovery Bonus Increase',
    'description' => 'Changes the appearance of the entire armor into that of Male Swimsuit No. 2. Tops and one-pieces only. Modified armor can be restored to their original appearance with a Restoration Stone. When modified, MP Recovery Bonus + 3.',
    'is_trade' => 1,
    'is_drop' => 1,
    'is_destruct' => 1,
    'crystal_type' => 'none',
    'consume_type' => 'consume_type_stackable',
  ],
  25193 => 
  [
    'item_id' => 25193,
    'icon' => 'g_scrl_change_chest',
    'name' => 'Appearance Stone: Male Swimsuit No. 2',
    'additionalname' => 'Low-grade / Evasion Increase',
    'description' => 'Changes the appearance of the entire armor into that of Male Swimsuit No. 2. Tops and one-pieces only. Modified armor can be restored to their original appearance with a Restoration Stone. When modified, P./M. Evasion + 3.',
    'is_trade' => 1,
    'is_drop' => 1,
    'is_destruct' => 1,
    'crystal_type' => 'none',
    'consume_type' => 'consume_type_stackable',
  ],
  25194 => 
  [
    'item_id' => 25194,
    'icon' => 'g_scrl_change_chest',
    'name' => 'Appearance Stone: Male Swimsuit No. 2',
    'additionalname' => 'Low-grade / Option 15',
    'description' => 'Changes the appearance of the entire armor into that of Male Swimsuit No. 2. Tops and one-pieces only. Modified armor can be restored to their original appearance with a Restoration Stone. When modified, Low-grade / Option + 15.',
    'is_trade' => 1,
    'is_drop' => 1,
    'is_destruct' => 1,
    'crystal_type' => 'none',
    'consume_type' => 'consume_type_stackable',
  ],
  25195 => 
  [
    'item_id' => 25195,
    'icon' => 'g_scrl_change_chest',
    'name' => 'Appearance Stone: Male Swimsuit No. 2',
    'additionalname' => 'Low-grade / Option 16',
    'description' => 'Changes the appearance of the entire armor into that of Male Swimsuit No. 2. Tops and one-pieces only. Modified armor can be restored to their original appearance with a Restoration Stone. When modified, Low-grade / Option + 16.',
    'is_trade' => 1,
    'is_drop' => 1,
    'is_destruct' => 1,
    'crystal_type' => 'none',
    'consume_type' => 'consume_type_stackable',
  ],
  25196 => 
  [
    'item_id' => 25196,
    'icon' => 'g_scrl_change_chest',
    'name' => 'Appearance Stone: Male Swimsuit No. 2',
    'additionalname' => 'Low-grade / Option 17',
    'description' => 'Changes the appearance of the entire armor into that of Male Swimsuit No. 2. Tops and one-pieces only. Modified armor can be restored to their original appearance with a Restoration Stone. When modified, Low-grade / Option + 17.',
    'is_trade' => 1,
    'is_drop' => 1,
    'is_destruct' => 1,
    'crystal_type' => 'none',
    'consume_type' => 'consume_type_stackable',
  ],
  25197 => 
  [
    'item_id' => 25197,
    'icon' => 'g_scrl_change_chest',
    'name' => 'Appearance Stone: Male Swimsuit No. 2',
    'additionalname' => 'Low-grade / Option 18',
    'description' => 'Changes the appearance of the entire armor into that of Male Swimsuit No. 2. Tops and one-pieces only. Modified armor can be restored to their original appearance with a Restoration Stone. When modified, Low-grade / Option + 18.',
    'is_trade' => 1,
    'is_drop' => 1,
    'is_destruct' => 1,
    'crystal_type' => 'none',
    'consume_type' => 'consume_type_stackable',
  ],
  25198 => 
  [
    'item_id' => 25198,
    'icon' => 'g_scrl_change_chest',
    'name' => 'Appearance Stone: Male Swimsuit No. 2',
    'additionalname' => 'Low-grade / Option 19',
    'description' => 'Changes the appearance of the entire armor into that of Male Swimsuit No. 2. Tops and one-pieces only. Modified armor can be restored to their original appearance with a Restoration Stone. When modified, Low-grade / Option + 19.',
    'is_trade' => 1,
    'is_drop' => 1,
    'is_destruct' => 1,
    'crystal_type' => 'none',
    'consume_type' => 'consume_type_stackable',
  ],
  25199 => 
  [
    'item_id' => 25199,
    'icon' => 'g_scrl_change_chest',
    'name' => 'Appearance Stone: Male Swimsuit No. 2',
    'additionalname' => 'Low-grade / Option 20',
    'description' => 'Changes the appearance of the entire armor into that of Male Swimsuit No. 2. Tops and one-pieces only. Modified armor can be restored to their original appearance with a Restoration Stone. When modified, Low-grade / Option + 20.',
    'is_trade' => 1,
    'is_drop' => 1,
    'is_destruct' => 1,
    'crystal_type' => 'none',
    'consume_type' => 'consume_type_stackable',
  ],
];