<?php return [
  28200 => 
  [
    'item_id' => 28200,
    'icon' => 'armor_t801_u_i01',
    'name' => 'Transcendent Eternal Breastplate',
    'additionalname' => 'Not used',
    'description' => 'Received Damage -8%. P. Atk. +1.3% and M. Atk. +2.6%. When enchanted to +4, decreases Received Critical Damage from standard attacks and increases P. Def.',
    'is_trade' => 1,
    'is_drop' => 1,
    'is_destruct' => 1,
    'crystal_type' => 'r99',
    'consume_type' => 'consume_type_normal',
  ],
  28201 => 
  [
    'item_id' => 28201,
    'icon' => 'armor_t801_l_i01',
    'name' => 'Transcendent Eternal Gaiters',
    'additionalname' => 'Not used',
    'description' => 'Received damage -5%, P. Atk. +1.3%, M. Atk. +2.6%.',
    'is_trade' => 1,
    'is_drop' => 1,
    'is_destruct' => 1,
    'crystal_type' => 'r99',
    'consume_type' => 'consume_type_normal',
  ],
  28202 => 
  [
    'item_id' => 28202,
    'icon' => 'armor_t801_g_i01',
    'name' => 'Transcendent Eternal Gauntlets',
    'additionalname' => 'Not used',
    'description' => 'Received damage -2%, P. Atk. +1.3%, M. Atk. +2.6%.',
    'is_trade' => 1,
    'is_drop' => 1,
    'is_destruct' => 1,
    'crystal_type' => 'r99',
    'consume_type' => 'consume_type_normal',
  ],
  28203 => 
  [
    'item_id' => 28203,
    'icon' => 'armor_t801_b_i01',
    'name' => 'Transcendent Eternal Boots',
    'additionalname' => 'Not used',
    'description' => 'Received damage -2%, P. Atk. +1.3%, M. Atk. +2.6%.',
    'is_trade' => 1,
    'is_drop' => 1,
    'is_destruct' => 1,
    'crystal_type' => 'r99',
    'consume_type' => 'consume_type_normal',
  ],
  28204 => 
  [
    'item_id' => 28204,
    'icon' => 'armor_helmet_i01',
    'name' => 'Transcendent Eternal Helmet',
    'additionalname' => 'Reinforced light armor / Lv. 4',
    'description' => 'Received damage -3%, P. Atk. +1.3%, M. Atk. +2.6%.Can be augmented.',
    'is_trade' => 1,
    'is_drop' => 1,
    'is_destruct' => 1,
    'crystal_type' => 'r99',
    'consume_type' => 'consume_type_normal',
  ],
  28205 => 
  [
    'item_id' => 28205,
    'icon' => 'armor_t802_u_i01',
    'name' => 'Transcendent Eternal Armor',
    'additionalname' => 'Reinforced light armor / Lv. 4',
    'description' => 'Received damage -8%, P. Atk. +1.3%, M. Atk. +2.6%. When enchanted to +4, increases P. Evasion, Speed and P. Debuff Resistance, also decreases received Critical Rate from standard attacks.Can be augmented.',
    'is_trade' => 1,
    'is_drop' => 1,
    'is_destruct' => 1,
    'crystal_type' => 'r99',
    'consume_type' => 'consume_type_normal',
  ],
  28206 => 
  [
    'item_id' => 28206,
    'icon' => 'armor_t802_l_i01',
    'name' => 'Transcendent Eternal Leggings',
    'additionalname' => 'Reinforced light armor / Lv. 4',
    'description' => 'Received damage -5%, P. Atk. +1.3%, M. Atk. +2.6%.Can be augmented.',
    'is_trade' => 1,
    'is_drop' => 1,
    'is_destruct' => 1,
    'crystal_type' => 'r99',
    'consume_type' => 'consume_type_normal',
  ],
  28207 => 
  [
    'item_id' => 28207,
    'icon' => 'armor_t802_g_i01',
    'name' => 'Transcendent Eternal Gloves',
    'additionalname' => 'Reinforced light armor / Lv. 4',
    'description' => 'Received damage -2%, P. Atk. +1.3%, M. Atk. +2.6%.Can be augmented.',
    'is_trade' => 1,
    'is_drop' => 1,
    'is_destruct' => 1,
    'crystal_type' => 'r99',
    'consume_type' => 'consume_type_normal',
  ],
  28208 => 
  [
    'item_id' => 28208,
    'icon' => 'armor_t802_b_i01',
    'name' => 'Transcendent Eternal Boots',
    'additionalname' => 'Reinforced light armor / Lv. 4',
    'description' => 'Received damage -2%, P. Atk. +1.3%, M. Atk. +2.6%.Can be augmented.',
    'is_trade' => 1,
    'is_drop' => 1,
    'is_destruct' => 1,
    'crystal_type' => 'r99',
    'consume_type' => 'consume_type_normal',
  ],
  28209 => 
  [
    'item_id' => 28209,
    'icon' => 'armor_circlet_i01',
    'name' => 'Transcendent Eternal Circlet',
    'additionalname' => 'Not used',
    'description' => 'Received damage -3%, P. Atk. +1.3%, M. Atk. +2.6%.',
    'is_trade' => 1,
    'is_drop' => 1,
    'is_destruct' => 1,
    'crystal_type' => 'r99',
    'consume_type' => 'consume_type_normal',
  ],
  28210 => 
  [
    'item_id' => 28210,
    'icon' => 'armor_t803_u_i01',
    'name' => 'Transcendent Eternal Tunic',
    'additionalname' => 'Not used',
    'description' => 'Received damage -8%, P. Atk. +1.3%, M. Atk. +2.6%. When enchanted to +4, increases M. Evasion and M. Debuff Resistance, also decreases received Critical Damage from standard attacks and received Critical Rate from standard attacks.',
    'is_trade' => 1,
    'is_drop' => 1,
    'is_destruct' => 1,
    'crystal_type' => 'r99',
    'consume_type' => 'consume_type_normal',
  ],
  28211 => 
  [
    'item_id' => 28211,
    'icon' => 'armor_t803_l_i01',
    'name' => 'Transcendent Eternal Stockings',
    'additionalname' => 'Not used',
    'description' => 'Received damage -5%, P. Atk. +1.3%, M. Atk. +2.6%.',
    'is_trade' => 1,
    'is_drop' => 1,
    'is_destruct' => 1,
    'crystal_type' => 'r99',
    'consume_type' => 'consume_type_normal',
  ],
  28212 => 
  [
    'item_id' => 28212,
    'icon' => 'armor_t803_g_i01',
    'name' => 'Transcendent Eternal Gloves',
    'additionalname' => 'Not used',
    'description' => 'Received damage -2%, P. Atk. +1.3%, M. Atk. +2.6%.',
    'is_trade' => 1,
    'is_drop' => 1,
    'is_destruct' => 1,
    'crystal_type' => 'r99',
    'consume_type' => 'consume_type_normal',
  ],
  28213 => 
  [
    'item_id' => 28213,
    'icon' => 'armor_t803_b_i01',
    'name' => 'Transcendent Eternal Shoes',
    'additionalname' => 'Not used',
    'description' => 'Received damage -2%, P. Atk. +1.3%, M. Atk. +2.6%.',
    'is_trade' => 1,
    'is_drop' => 1,
    'is_destruct' => 1,
    'crystal_type' => 'r99',
    'consume_type' => 'consume_type_normal',
  ],
  28214 => 
  [
    'item_id' => 28214,
    'icon' => 'armor_helmet_i01',
    'name' => 'Transcendent Eternal Helmet',
    'additionalname' => 'Heavy armor / Lv. 5',
    'description' => 'Received damage -3%, P. Atk. +1.4%, M. Atk. +2.8%. Heavy Armor that can be enhanced by Blacksmith in any town.Can be augmented.',
    'is_trade' => 1,
    'is_drop' => 1,
    'is_destruct' => 1,
    'crystal_type' => 'r99',
    'consume_type' => 'consume_type_normal',
  ],
  28215 => 
  [
    'item_id' => 28215,
    'icon' => 'armor_t801_u_i01',
    'name' => 'Transcendent Eternal Breastplate',
    'additionalname' => 'Heavy armor / Lv. 5',
    'description' => 'Received damage -8%, P. Atk. +1.4%, M. Atk. +2.8%. Heavy Armor that can be enhanced by Blacksmith in any town. When enchanted to +4, decreases Received Critical Damage from standard attacks and increases P. Def.Can be augmented.',
    'is_trade' => 1,
    'is_drop' => 1,
    'is_destruct' => 1,
    'crystal_type' => 'r99',
    'consume_type' => 'consume_type_normal',
  ],
  28216 => 
  [
    'item_id' => 28216,
    'icon' => 'armor_t801_l_i01',
    'name' => 'Transcendent Eternal Gaiters',
    'additionalname' => 'Heavy armor / Lv. 5',
    'description' => 'Received damage -5%, P. Atk. +1.4%, M. Atk. +2.8%. Heavy Armor that can be enhanced by Blacksmith in any town.Can be augmented.',
    'is_trade' => 1,
    'is_drop' => 1,
    'is_destruct' => 1,
    'crystal_type' => 'r99',
    'consume_type' => 'consume_type_normal',
  ],
  28217 => 
  [
    'item_id' => 28217,
    'icon' => 'armor_t801_g_i01',
    'name' => 'Transcendent Eternal Gauntlets',
    'additionalname' => 'Heavy armor / Lv. 5',
    'description' => 'Received damage -2%, P. Atk. +1.4%, M. Atk. +2.8%. Heavy Armor that can be enhanced by Blacksmith in any town.Can be augmented.',
    'is_trade' => 1,
    'is_drop' => 1,
    'is_destruct' => 1,
    'crystal_type' => 'r99',
    'consume_type' => 'consume_type_normal',
  ],
  28218 => 
  [
    'item_id' => 28218,
    'icon' => 'armor_t801_b_i01',
    'name' => 'Transcendent Eternal Boots',
    'additionalname' => 'Heavy armor / Lv. 5',
    'description' => 'Received damage -2%, P. Atk. +1.4%, M. Atk. +2.8%. Heavy Armor that can be enhanced by Blacksmith in any town.Can be augmented.',
    'is_trade' => 1,
    'is_drop' => 1,
    'is_destruct' => 1,
    'crystal_type' => 'r99',
    'consume_type' => 'consume_type_normal',
  ],
  28219 => 
  [
    'item_id' => 28219,
    'icon' => 'armor_helmet_i01',
    'name' => 'Transcendent Eternal Helmet',
    'additionalname' => 'Light armor / Lv. 5',
    'description' => 'Received damage -3%, P. Atk. +1.4%, M. Atk. +2.8%. Light Armor that can be enhanced by Blacksmith in any town.Can be augmented.',
    'is_trade' => 1,
    'is_drop' => 1,
    'is_destruct' => 1,
    'crystal_type' => 'r99',
    'consume_type' => 'consume_type_normal',
  ],
  28220 => 
  [
    'item_id' => 28220,
    'icon' => 'armor_t802_u_i01',
    'name' => 'Transcendent Eternal Armor',
    'additionalname' => 'Light armor / Lv. 5',
    'description' => 'Received damage -8%, P. Atk. +1.4%, M. Atk. +2.8%. Light armor, can be enhanced by a blacksmith in any town. When enchanted to +4, increases P. Evasion, Speed and P. Debuff Resistance, also decreases received Critical Rate from standard attacks.Can be augmented.',
    'is_trade' => 1,
    'is_drop' => 1,
    'is_destruct' => 1,
    'crystal_type' => 'r99',
    'consume_type' => 'consume_type_normal',
  ],
  28221 => 
  [
    'item_id' => 28221,
    'icon' => 'armor_t802_l_i01',
    'name' => 'Transcendent Eternal Leggings',
    'additionalname' => 'Light armor / Lv. 5',
    'description' => 'Received damage -5%, P. Atk. +1.4%, M. Atk. +2.8%. Light Armor that can be enhanced by Blacksmith in any town.Can be augmented.',
    'is_trade' => 1,
    'is_drop' => 1,
    'is_destruct' => 1,
    'crystal_type' => 'r99',
    'consume_type' => 'consume_type_normal',
  ],
  28222 => 
  [
    'item_id' => 28222,
    'icon' => 'armor_t802_g_i01',
    'name' => 'Transcendent Eternal Gloves',
    'additionalname' => 'Light armor / Lv. 5',
    'description' => 'Received damage -2%, P. Atk. +1.4%, M. Atk. +2.8%. Light Armor that can be enhanced by Blacksmith in any town.Can be augmented.',
    'is_trade' => 1,
    'is_drop' => 1,
    'is_destruct' => 1,
    'crystal_type' => 'r99',
    'consume_type' => 'consume_type_normal',
  ],
  28223 => 
  [
    'item_id' => 28223,
    'icon' => 'armor_t802_b_i01',
    'name' => 'Transcendent Eternal Boots',
    'additionalname' => 'Light armor / Lv. 5',
    'description' => 'Received damage -2%, P. Atk. +1.4%, M. Atk. +2.8%. Light Armor that can be enhanced by Blacksmith in any town.Can be augmented.',
    'is_trade' => 1,
    'is_drop' => 1,
    'is_destruct' => 1,
    'crystal_type' => 'r99',
    'consume_type' => 'consume_type_normal',
  ],
  28224 => 
  [
    'item_id' => 28224,
    'icon' => 'armor_circlet_i01',
    'name' => 'Transcendent Eternal Circlet',
    'additionalname' => 'Robe/ Lv. 5',
    'description' => 'Received damage -3%, P. Atk. +1.4%, M. Atk. +2.8%. Robe that can be enhanced by Blacksmith in any town.Can be augmented.',
    'is_trade' => 1,
    'is_drop' => 1,
    'is_destruct' => 1,
    'crystal_type' => 'r99',
    'consume_type' => 'consume_type_normal',
  ],
  28225 => 
  [
    'item_id' => 28225,
    'icon' => 'armor_t803_u_i01',
    'name' => 'Transcendent Eternal Tunic',
    'additionalname' => 'Robe/ Lv. 5',
    'description' => 'Received damage -8%, P. Atk. +1.4%, M. Atk. +2.8%. Robe, can be enhanced by a blacksmith in any town. When enchanted to +4, increases M. Evasion and M. Debuff Resistance, also decreases received Critical Damage from standard attacks and received Critical Rate from standard attacks.Can be augmented.',
    'is_trade' => 1,
    'is_drop' => 1,
    'is_destruct' => 1,
    'crystal_type' => 'r99',
    'consume_type' => 'consume_type_normal',
  ],
  28226 => 
  [
    'item_id' => 28226,
    'icon' => 'armor_t803_l_i01',
    'name' => 'Transcendent Eternal Stockings',
    'additionalname' => 'Robe/ Lv. 5',
    'description' => 'Received damage -5%, P. Atk. +1.4%, M. Atk. +2.8%. Robe that can be enhanced by Blacksmith in any town.Can be augmented.',
    'is_trade' => 1,
    'is_drop' => 1,
    'is_destruct' => 1,
    'crystal_type' => 'r99',
    'consume_type' => 'consume_type_normal',
  ],
  28227 => 
  [
    'item_id' => 28227,
    'icon' => 'armor_t803_g_i01',
    'name' => 'Transcendent Eternal Gloves',
    'additionalname' => 'Robe/ Lv. 5',
    'description' => 'Received damage -2%, P. Atk. +1.4%, M. Atk. +2.8%. Robe that can be enhanced by Blacksmith in any town.Can be augmented.',
    'is_trade' => 1,
    'is_drop' => 1,
    'is_destruct' => 1,
    'crystal_type' => 'r99',
    'consume_type' => 'consume_type_normal',
  ],
  28228 => 
  [
    'item_id' => 28228,
    'icon' => 'armor_t803_b_i01',
    'name' => 'Transcendent Eternal Shoes',
    'additionalname' => 'Robe/ Lv. 5',
    'description' => 'Received damage -2%, P. Atk. +1.4%, M. Atk. +2.8%. Robe that can be enhanced by Blacksmith in any town.Can be augmented.',
    'is_trade' => 1,
    'is_drop' => 1,
    'is_destruct' => 1,
    'crystal_type' => 'r99',
    'consume_type' => 'consume_type_normal',
  ],
  28229 => 
  [
    'item_id' => 28229,
    'icon' => 'armor_helmet_i01',
    'name' => 'Transcendent Eternal Helmet',
    'additionalname' => 'Reinforced heavy armor / Lv. 5',
    'description' => 'Received damage -3%, P. Atk. +1.4%, M. Atk. +2.8%.Can be augmented.',
    'is_trade' => 1,
    'is_drop' => 1,
    'is_destruct' => 1,
    'crystal_type' => 'r99',
    'consume_type' => 'consume_type_normal',
  ],
  28230 => 
  [
    'item_id' => 28230,
    'icon' => 'armor_t801_u_i01',
    'name' => 'Transcendent Eternal Breastplate',
    'additionalname' => 'Reinforced heavy armor / Lv. 5',
    'description' => 'Received Damage -8%. P. Atk. +1.4% and M. Atk. +2.8%. When enchanted to +4, decreases Received Critical Damage from standard attacks and increases P. Def.Can be augmented.',
    'is_trade' => 1,
    'is_drop' => 1,
    'is_destruct' => 1,
    'crystal_type' => 'r99',
    'consume_type' => 'consume_type_normal',
  ],
  28231 => 
  [
    'item_id' => 28231,
    'icon' => 'armor_t801_l_i01',
    'name' => 'Transcendent Eternal Gaiters',
    'additionalname' => 'Reinforced heavy armor / Lv. 5',
    'description' => 'Received damage -5%, P. Atk. +1.4%, M. Atk. +2.8%.Can be augmented.',
    'is_trade' => 1,
    'is_drop' => 1,
    'is_destruct' => 1,
    'crystal_type' => 'r99',
    'consume_type' => 'consume_type_normal',
  ],
  28232 => 
  [
    'item_id' => 28232,
    'icon' => 'armor_t801_g_i01',
    'name' => 'Transcendent Eternal Gauntlets',
    'additionalname' => 'Reinforced heavy armor / Lv. 5',
    'description' => 'Received damage -2%, P. Atk. +1.4%, M. Atk. +2.8%.Can be augmented.',
    'is_trade' => 1,
    'is_drop' => 1,
    'is_destruct' => 1,
    'crystal_type' => 'r99',
    'consume_type' => 'consume_type_normal',
  ],
  28233 => 
  [
    'item_id' => 28233,
    'icon' => 'armor_t801_b_i01',
    'name' => 'Transcendent Eternal Boots',
    'additionalname' => 'Reinforced heavy armor / Lv. 5',
    'description' => 'Received damage -2%, P. Atk. +1.4%, M. Atk. +2.8%.Can be augmented.',
    'is_trade' => 1,
    'is_drop' => 1,
    'is_destruct' => 1,
    'crystal_type' => 'r99',
    'consume_type' => 'consume_type_normal',
  ],
  28234 => 
  [
    'item_id' => 28234,
    'icon' => 'armor_helmet_i01',
    'name' => 'Transcendent Eternal Helmet',
    'additionalname' => 'Not used',
    'description' => 'Received damage -3%, P. Atk. +1.4%, M. Atk. +2.8%.',
    'is_trade' => 1,
    'is_drop' => 1,
    'is_destruct' => 1,
    'crystal_type' => 'r99',
    'consume_type' => 'consume_type_normal',
  ],
  28235 => 
  [
    'item_id' => 28235,
    'icon' => 'armor_t802_u_i01',
    'name' => 'Transcendent Eternal Armor',
    'additionalname' => 'Not used',
    'description' => 'Received damage -8%, P. Atk. +1.4%, M. Atk. +2.8%. When enchanted to +4, increases P. Evasion, Speed and P. Debuff Resistance, also decreases received Critical Rate from standard attacks.',
    'is_trade' => 1,
    'is_drop' => 1,
    'is_destruct' => 1,
    'crystal_type' => 'r99',
    'consume_type' => 'consume_type_normal',
  ],
  28236 => 
  [
    'item_id' => 28236,
    'icon' => 'armor_t802_l_i01',
    'name' => 'Transcendent Eternal Leggings',
    'additionalname' => 'Not used',
    'description' => 'Received damage -5%, P. Atk. +1.4%, M. Atk. +2.8%.',
    'is_trade' => 1,
    'is_drop' => 1,
    'is_destruct' => 1,
    'crystal_type' => 'r99',
    'consume_type' => 'consume_type_normal',
  ],
  28237 => 
  [
    'item_id' => 28237,
    'icon' => 'armor_t802_g_i01',
    'name' => 'Transcendent Eternal Gloves',
    'additionalname' => 'Not used',
    'description' => 'Received damage -2%, P. Atk. +1.4%, M. Atk. +2.8%.',
    'is_trade' => 1,
    'is_drop' => 1,
    'is_destruct' => 1,
    'crystal_type' => 'r99',
    'consume_type' => 'consume_type_normal',
  ],
  28238 => 
  [
    'item_id' => 28238,
    'icon' => 'armor_t802_b_i01',
    'name' => 'Transcendent Eternal Boots',
    'additionalname' => 'Not used',
    'description' => 'Received damage -2%, P. Atk. +1.4%, M. Atk. +2.8%.',
    'is_trade' => 1,
    'is_drop' => 1,
    'is_destruct' => 1,
    'crystal_type' => 'r99',
    'consume_type' => 'consume_type_normal',
  ],
  28239 => 
  [
    'item_id' => 28239,
    'icon' => 'armor_circlet_i01',
    'name' => 'Transcendent Eternal Circlet',
    'additionalname' => 'Reinforced robe / Lv. 5',
    'description' => 'Received damage -3%, P. Atk. +1.4%, M. Atk. +2.8%.Can be augmented.',
    'is_trade' => 1,
    'is_drop' => 1,
    'is_destruct' => 1,
    'crystal_type' => 'r99',
    'consume_type' => 'consume_type_normal',
  ],
  28240 => 
  [
    'item_id' => 28240,
    'icon' => 'armor_t803_u_i01',
    'name' => 'Transcendent Eternal Tunic',
    'additionalname' => 'Reinforced robe / Lv. 5',
    'description' => 'Received damage -8%, P. Atk. +1.4%, M. Atk. +2.8%. When enchanted to +4, increases M. Evasion and M. Debuff Resistance, also decreases received Critical Damage from standard attacks and received Critical Rate from standard attacks.Can be augmented.',
    'is_trade' => 1,
    'is_drop' => 1,
    'is_destruct' => 1,
    'crystal_type' => 'r99',
    'consume_type' => 'consume_type_normal',
  ],
  28241 => 
  [
    'item_id' => 28241,
    'icon' => 'armor_t803_l_i01',
    'name' => 'Transcendent Eternal Stockings',
    'additionalname' => 'Reinforced robe / Lv. 5',
    'description' => 'Received damage -5%, P. Atk. +1.4%, M. Atk. +2.8%.Can be augmented.',
    'is_trade' => 1,
    'is_drop' => 1,
    'is_destruct' => 1,
    'crystal_type' => 'r99',
    'consume_type' => 'consume_type_normal',
  ],
  28242 => 
  [
    'item_id' => 28242,
    'icon' => 'armor_t803_g_i01',
    'name' => 'Transcendent Eternal Gloves',
    'additionalname' => 'Reinforced robe / Lv. 5',
    'description' => 'Received damage -2%, P. Atk. +1.4%, M. Atk. +2.8%.Can be augmented.',
    'is_trade' => 1,
    'is_drop' => 1,
    'is_destruct' => 1,
    'crystal_type' => 'r99',
    'consume_type' => 'consume_type_normal',
  ],
  28243 => 
  [
    'item_id' => 28243,
    'icon' => 'armor_t803_b_i01',
    'name' => 'Transcendent Eternal Shoes',
    'additionalname' => 'Reinforced robe / Lv. 5',
    'description' => 'Received damage -2%, P. Atk. +1.4%, M. Atk. +2.8%.Can be augmented.',
    'is_trade' => 1,
    'is_drop' => 1,
    'is_destruct' => 1,
    'crystal_type' => 'r99',
    'consume_type' => 'consume_type_normal',
  ],
  28244 => 
  [
    'item_id' => 28244,
    'icon' => 'armor_helmet_i01',
    'name' => 'Transcendent Eternal Helmet',
    'additionalname' => 'Not used',
    'description' => 'Received damage -3%, P. Atk. +1.4%, M. Atk. +2.8%.',
    'is_trade' => 1,
    'is_drop' => 1,
    'is_destruct' => 1,
    'crystal_type' => 'r99',
    'consume_type' => 'consume_type_normal',
  ],
  28245 => 
  [
    'item_id' => 28245,
    'icon' => 'armor_t801_u_i01',
    'name' => 'Transcendent Eternal Breastplate',
    'additionalname' => 'Not used',
    'description' => 'Received Damage -8%. P. Atk. +1.4% and M. Atk. +2.8%. When enchanted to +4, decreases Received Critical Damage from standard attacks and increases P. Def.',
    'is_trade' => 1,
    'is_drop' => 1,
    'is_destruct' => 1,
    'crystal_type' => 'r99',
    'consume_type' => 'consume_type_normal',
  ],
  28246 => 
  [
    'item_id' => 28246,
    'icon' => 'armor_t801_l_i01',
    'name' => 'Transcendent Eternal Gaiters',
    'additionalname' => 'Not used',
    'description' => 'Received damage -5%, P. Atk. +1.4%, M. Atk. +2.8%.',
    'is_trade' => 1,
    'is_drop' => 1,
    'is_destruct' => 1,
    'crystal_type' => 'r99',
    'consume_type' => 'consume_type_normal',
  ],
  28247 => 
  [
    'item_id' => 28247,
    'icon' => 'armor_t801_g_i01',
    'name' => 'Transcendent Eternal Gauntlets',
    'additionalname' => 'Not used',
    'description' => 'Received damage -2%, P. Atk. +1.4%, M. Atk. +2.8%.',
    'is_trade' => 1,
    'is_drop' => 1,
    'is_destruct' => 1,
    'crystal_type' => 'r99',
    'consume_type' => 'consume_type_normal',
  ],
  28248 => 
  [
    'item_id' => 28248,
    'icon' => 'armor_t801_b_i01',
    'name' => 'Transcendent Eternal Boots',
    'additionalname' => 'Not used',
    'description' => 'Received damage -2%, P. Atk. +1.4%, M. Atk. +2.8%.',
    'is_trade' => 1,
    'is_drop' => 1,
    'is_destruct' => 1,
    'crystal_type' => 'r99',
    'consume_type' => 'consume_type_normal',
  ],
  28249 => 
  [
    'item_id' => 28249,
    'icon' => 'armor_helmet_i01',
    'name' => 'Transcendent Eternal Helmet',
    'additionalname' => 'Reinforced light armor / Lv. 5',
    'description' => 'Received damage -3%, P. Atk. +1.4%, M. Atk. +2.8%.Can be augmented.',
    'is_trade' => 1,
    'is_drop' => 1,
    'is_destruct' => 1,
    'crystal_type' => 'r99',
    'consume_type' => 'consume_type_normal',
  ],
  28250 => 
  [
    'item_id' => 28250,
    'icon' => 'armor_t802_u_i01',
    'name' => 'Transcendent Eternal Armor',
    'additionalname' => 'Reinforced light armor / Lv. 5',
    'description' => 'Received damage -8%, P. Atk. +1.4%, M. Atk. +2.8%. When enchanted to +4, increases P. Evasion, Speed and P. Debuff Resistance, also decreases received Critical Rate from standard attacks.Can be augmented.',
    'is_trade' => 1,
    'is_drop' => 1,
    'is_destruct' => 1,
    'crystal_type' => 'r99',
    'consume_type' => 'consume_type_normal',
  ],
  28251 => 
  [
    'item_id' => 28251,
    'icon' => 'armor_t802_l_i01',
    'name' => 'Transcendent Eternal Leggings',
    'additionalname' => 'Reinforced light armor / Lv. 5',
    'description' => 'Received damage -5%, P. Atk. +1.4%, M. Atk. +2.8%.Can be augmented.',
    'is_trade' => 1,
    'is_drop' => 1,
    'is_destruct' => 1,
    'crystal_type' => 'r99',
    'consume_type' => 'consume_type_normal',
  ],
  28252 => 
  [
    'item_id' => 28252,
    'icon' => 'armor_t802_g_i01',
    'name' => 'Transcendent Eternal Gloves',
    'additionalname' => 'Reinforced light armor / Lv. 5',
    'description' => 'Received damage -2%, P. Atk. +1.4%, M. Atk. +2.8%.Can be augmented.',
    'is_trade' => 1,
    'is_drop' => 1,
    'is_destruct' => 1,
    'crystal_type' => 'r99',
    'consume_type' => 'consume_type_normal',
  ],
  28253 => 
  [
    'item_id' => 28253,
    'icon' => 'armor_t802_b_i01',
    'name' => 'Transcendent Eternal Boots',
    'additionalname' => 'Reinforced light armor / Lv. 5',
    'description' => 'Received damage -2%, P. Atk. +1.4%, M. Atk. +2.8%.Can be augmented.',
    'is_trade' => 1,
    'is_drop' => 1,
    'is_destruct' => 1,
    'crystal_type' => 'r99',
    'consume_type' => 'consume_type_normal',
  ],
  28254 => 
  [
    'item_id' => 28254,
    'icon' => 'armor_circlet_i01',
    'name' => 'Transcendent Eternal Circlet',
    'additionalname' => 'Not used',
    'description' => 'Received damage -3%, P. Atk. +1.4%, M. Atk. +2.8%.',
    'is_trade' => 1,
    'is_drop' => 1,
    'is_destruct' => 1,
    'crystal_type' => 'r99',
    'consume_type' => 'consume_type_normal',
  ],
  28255 => 
  [
    'item_id' => 28255,
    'icon' => 'armor_t803_u_i01',
    'name' => 'Transcendent Eternal Tunic',
    'additionalname' => 'Not used',
    'description' => 'Received damage -8%, P. Atk. +1.4%, M. Atk. +2.8%. When enchanted to +4, increases M. Evasion and M. Debuff Resistance, also decreases received Critical Damage from standard attacks and received Critical Rate from standard attacks.',
    'is_trade' => 1,
    'is_drop' => 1,
    'is_destruct' => 1,
    'crystal_type' => 'r99',
    'consume_type' => 'consume_type_normal',
  ],
  28256 => 
  [
    'item_id' => 28256,
    'icon' => 'armor_t803_l_i01',
    'name' => 'Transcendent Eternal Stockings',
    'additionalname' => 'Not used',
    'description' => 'Received damage -5%, P. Atk. +1.4%, M. Atk. +2.8%.',
    'is_trade' => 1,
    'is_drop' => 1,
    'is_destruct' => 1,
    'crystal_type' => 'r99',
    'consume_type' => 'consume_type_normal',
  ],
  28257 => 
  [
    'item_id' => 28257,
    'icon' => 'armor_t803_g_i01',
    'name' => 'Transcendent Eternal Gloves',
    'additionalname' => 'Not used',
    'description' => 'Received damage -2%, P. Atk. +1.4%, M. Atk. +2.8%.',
    'is_trade' => 1,
    'is_drop' => 1,
    'is_destruct' => 1,
    'crystal_type' => 'r99',
    'consume_type' => 'consume_type_normal',
  ],
  28258 => 
  [
    'item_id' => 28258,
    'icon' => 'armor_t803_b_i01',
    'name' => 'Transcendent Eternal Shoes',
    'additionalname' => 'Not used',
    'description' => 'Received damage -2%, P. Atk. +1.4%, M. Atk. +2.8%.',
    'is_trade' => 1,
    'is_drop' => 1,
    'is_destruct' => 1,
    'crystal_type' => 'r99',
    'consume_type' => 'consume_type_normal',
  ],
  28259 => 
  [
    'item_id' => 28259,
    'icon' => 'armor_helmet_i01',
    'name' => 'Transcendent Eternal Helmet',
    'additionalname' => 'Heavy armor / Lv. 6',
    'description' => 'Received damage -3%, P. Atk. +1.5%, M. Atk. +3%. Heavy Armor that can be enhanced by Blacksmith in any town.Can be augmented.',
    'is_trade' => 1,
    'is_drop' => 1,
    'is_destruct' => 1,
    'crystal_type' => 'r99',
    'consume_type' => 'consume_type_normal',
  ],
  28260 => 
  [
    'item_id' => 28260,
    'icon' => 'armor_t801_u_i01',
    'name' => 'Transcendent Eternal Breastplate',
    'additionalname' => 'Heavy armor / Lv. 6',
    'description' => 'Received damage -8%, P. Atk. +1.5%, M. Atk. +3%. Heavy Armor that can be enhanced by Blacksmith in any town. When enchanted to +4, decreases Received Critical Damage from standard attacks and increases P. Def.Can be augmented.',
    'is_trade' => 1,
    'is_drop' => 1,
    'is_destruct' => 1,
    'crystal_type' => 'r99',
    'consume_type' => 'consume_type_normal',
  ],
  28261 => 
  [
    'item_id' => 28261,
    'icon' => 'armor_t801_l_i01',
    'name' => 'Transcendent Eternal Gaiters',
    'additionalname' => 'Heavy armor / Lv. 6',
    'description' => 'Received damage -5%, P. Atk. +1.5%, M. Atk. +3%. Heavy Armor that can be enhanced by Blacksmith in any town.Can be augmented.',
    'is_trade' => 1,
    'is_drop' => 1,
    'is_destruct' => 1,
    'crystal_type' => 'r99',
    'consume_type' => 'consume_type_normal',
  ],
  28262 => 
  [
    'item_id' => 28262,
    'icon' => 'armor_t801_g_i01',
    'name' => 'Transcendent Eternal Gauntlets',
    'additionalname' => 'Heavy armor / Lv. 6',
    'description' => 'Received damage -2%, P. Atk. +1.5%, M. Atk. +3%. Heavy Armor that can be enhanced by Blacksmith in any town.Can be augmented.',
    'is_trade' => 1,
    'is_drop' => 1,
    'is_destruct' => 1,
    'crystal_type' => 'r99',
    'consume_type' => 'consume_type_normal',
  ],
  28263 => 
  [
    'item_id' => 28263,
    'icon' => 'armor_t801_b_i01',
    'name' => 'Transcendent Eternal Boots',
    'additionalname' => 'Heavy armor / Lv. 6',
    'description' => 'Received damage -2%, P. Atk. +1.5%, M. Atk. +3%. Heavy Armor that can be enhanced by Blacksmith in any town.Can be augmented.',
    'is_trade' => 1,
    'is_drop' => 1,
    'is_destruct' => 1,
    'crystal_type' => 'r99',
    'consume_type' => 'consume_type_normal',
  ],
  28264 => 
  [
    'item_id' => 28264,
    'icon' => 'armor_helmet_i01',
    'name' => 'Transcendent Eternal Helmet',
    'additionalname' => 'Light armor / Lv. 6',
    'description' => 'Received damage -3%, P. Atk. +1.5%, M. Atk. +3%. Light Armor that can be enhanced by Blacksmith in any town.Can be augmented.',
    'is_trade' => 1,
    'is_drop' => 1,
    'is_destruct' => 1,
    'crystal_type' => 'r99',
    'consume_type' => 'consume_type_normal',
  ],
  28265 => 
  [
    'item_id' => 28265,
    'icon' => 'armor_t802_u_i01',
    'name' => 'Transcendent Eternal Armor',
    'additionalname' => 'Light armor / Lv. 6',
    'description' => 'Received damage -8%, P. Atk. +1.5%, M. Atk. +3%. Light armor, can be enhanced by a blacksmith in any town. When enchanted to +4, increases P. Evasion, Speed and P. Debuff Resistance, also decreases received Critical Rate from standard attacks.Can be augmented.',
    'is_trade' => 1,
    'is_drop' => 1,
    'is_destruct' => 1,
    'crystal_type' => 'r99',
    'consume_type' => 'consume_type_normal',
  ],
  28266 => 
  [
    'item_id' => 28266,
    'icon' => 'armor_t802_l_i01',
    'name' => 'Transcendent Eternal Leggings',
    'additionalname' => 'Light armor / Lv. 6',
    'description' => 'Received damage -5%, P. Atk. +1.5%, M. Atk. +3%. Light Armor that can be enhanced by Blacksmith in any town.Can be augmented.',
    'is_trade' => 1,
    'is_drop' => 1,
    'is_destruct' => 1,
    'crystal_type' => 'r99',
    'consume_type' => 'consume_type_normal',
  ],
  28267 => 
  [
    'item_id' => 28267,
    'icon' => 'armor_t802_g_i01',
    'name' => 'Transcendent Eternal Gloves',
    'additionalname' => 'Light armor / Lv. 6',
    'description' => 'Received damage -2%, P. Atk. +1.5%, M. Atk. +3%. Light Armor that can be enhanced by Blacksmith in any town.Can be augmented.',
    'is_trade' => 1,
    'is_drop' => 1,
    'is_destruct' => 1,
    'crystal_type' => 'r99',
    'consume_type' => 'consume_type_normal',
  ],
  28268 => 
  [
    'item_id' => 28268,
    'icon' => 'armor_t802_b_i01',
    'name' => 'Transcendent Eternal Boots',
    'additionalname' => 'Light armor / Lv. 6',
    'description' => 'Received damage -2%, P. Atk. +1.5%, M. Atk. +3%. Light Armor that can be enhanced by Blacksmith in any town.Can be augmented.',
    'is_trade' => 1,
    'is_drop' => 1,
    'is_destruct' => 1,
    'crystal_type' => 'r99',
    'consume_type' => 'consume_type_normal',
  ],
  28269 => 
  [
    'item_id' => 28269,
    'icon' => 'armor_circlet_i01',
    'name' => 'Transcendent Eternal Circlet',
    'additionalname' => 'Robe/ Lv. 6',
    'description' => 'Received damage -3%, P. Atk. +1.5%, M. Atk. +3%. Robe that can be enhanced by Blacksmith in any town.Can be augmented.',
    'is_trade' => 1,
    'is_drop' => 1,
    'is_destruct' => 1,
    'crystal_type' => 'r99',
    'consume_type' => 'consume_type_normal',
  ],
  28270 => 
  [
    'item_id' => 28270,
    'icon' => 'armor_t803_u_i01',
    'name' => 'Transcendent Eternal Tunic',
    'additionalname' => 'Robe/ Lv. 6',
    'description' => 'Received damage -8%, P. Atk. +1.5%, M. Atk. +3%. Robe, can be enhanced by a blacksmith in any town. When enchanted to +4, increases M. Evasion and M. Debuff Resistance, also decreases received Critical Damage from standard attacks and received Critical Rate from standard attacks.Can be augmented.',
    'is_trade' => 1,
    'is_drop' => 1,
    'is_destruct' => 1,
    'crystal_type' => 'r99',
    'consume_type' => 'consume_type_normal',
  ],
  28271 => 
  [
    'item_id' => 28271,
    'icon' => 'armor_t803_l_i01',
    'name' => 'Transcendent Eternal Stockings',
    'additionalname' => 'Robe/ Lv. 6',
    'description' => 'Received damage -5%, P. Atk. +1.5%, M. Atk. +3%. Robe that can be enhanced by Blacksmith in any town.Can be augmented.',
    'is_trade' => 1,
    'is_drop' => 1,
    'is_destruct' => 1,
    'crystal_type' => 'r99',
    'consume_type' => 'consume_type_normal',
  ],
  28272 => 
  [
    'item_id' => 28272,
    'icon' => 'armor_t803_g_i01',
    'name' => 'Transcendent Eternal Gloves',
    'additionalname' => 'Robe/ Lv. 6',
    'description' => 'Received damage -2%, P. Atk. +1.5%, M. Atk. +3%. Robe that can be enhanced by Blacksmith in any town.Can be augmented.',
    'is_trade' => 1,
    'is_drop' => 1,
    'is_destruct' => 1,
    'crystal_type' => 'r99',
    'consume_type' => 'consume_type_normal',
  ],
  28273 => 
  [
    'item_id' => 28273,
    'icon' => 'armor_t803_b_i01',
    'name' => 'Transcendent Eternal Shoes',
    'additionalname' => 'Robe/ Lv. 6',
    'description' => 'Received damage -2%, P. Atk. +1.5%, M. Atk. +3%. Robe that can be enhanced by Blacksmith in any town.Can be augmented.',
    'is_trade' => 1,
    'is_drop' => 1,
    'is_destruct' => 1,
    'crystal_type' => 'r99',
    'consume_type' => 'consume_type_normal',
  ],
  28274 => 
  [
    'item_id' => 28274,
    'icon' => 'armor_helmet_i01',
    'name' => 'Transcendent Eternal Helmet',
    'additionalname' => 'Reinforced heavy armor / Lv. 6',
    'description' => 'Received damage -3%, P. Atk. +1.5%, M. Atk. +3%.Can be augmented.',
    'is_trade' => 1,
    'is_drop' => 1,
    'is_destruct' => 1,
    'crystal_type' => 'r99',
    'consume_type' => 'consume_type_normal',
  ],
  28275 => 
  [
    'item_id' => 28275,
    'icon' => 'armor_t801_u_i01',
    'name' => 'Transcendent Eternal Breastplate',
    'additionalname' => 'Reinforced heavy armor / Lv. 6',
    'description' => 'Received Damage -8%. P. Atk. +1.5% and M. Atk. +3%. When enchanted to +4, decreases Received Critical Damage from standard attacks and increases P. Def.Can be augmented.',
    'is_trade' => 1,
    'is_drop' => 1,
    'is_destruct' => 1,
    'crystal_type' => 'r99',
    'consume_type' => 'consume_type_normal',
  ],
  28276 => 
  [
    'item_id' => 28276,
    'icon' => 'armor_t801_l_i01',
    'name' => 'Transcendent Eternal Gaiters',
    'additionalname' => 'Reinforced heavy armor / Lv. 6',
    'description' => 'Received damage -5%, P. Atk. +1.5%, M. Atk. +3%.Can be augmented.',
    'is_trade' => 1,
    'is_drop' => 1,
    'is_destruct' => 1,
    'crystal_type' => 'r99',
    'consume_type' => 'consume_type_normal',
  ],
  28277 => 
  [
    'item_id' => 28277,
    'icon' => 'armor_t801_g_i01',
    'name' => 'Transcendent Eternal Gauntlets',
    'additionalname' => 'Reinforced heavy armor / Lv. 6',
    'description' => 'Received damage -2%, P. Atk. +1.5%, M. Atk. +3%.Can be augmented.',
    'is_trade' => 1,
    'is_drop' => 1,
    'is_destruct' => 1,
    'crystal_type' => 'r99',
    'consume_type' => 'consume_type_normal',
  ],
  28278 => 
  [
    'item_id' => 28278,
    'icon' => 'armor_t801_b_i01',
    'name' => 'Transcendent Eternal Boots',
    'additionalname' => 'Reinforced heavy armor / Lv. 6',
    'description' => 'Received damage -2%, P. Atk. +1.5%, M. Atk. +3%.Can be augmented.',
    'is_trade' => 1,
    'is_drop' => 1,
    'is_destruct' => 1,
    'crystal_type' => 'r99',
    'consume_type' => 'consume_type_normal',
  ],
  28279 => 
  [
    'item_id' => 28279,
    'icon' => 'armor_helmet_i01',
    'name' => 'Transcendent Eternal Helmet',
    'additionalname' => 'Not used',
    'description' => 'Received damage -3%, P. Atk. +1.5%, M. Atk. +3%.',
    'is_trade' => 1,
    'is_drop' => 1,
    'is_destruct' => 1,
    'crystal_type' => 'r99',
    'consume_type' => 'consume_type_normal',
  ],
  28280 => 
  [
    'item_id' => 28280,
    'icon' => 'armor_t802_u_i01',
    'name' => 'Transcendent Eternal Armor',
    'additionalname' => 'Not used',
    'description' => 'Received damage -8%, P. Atk. +1.5%, M. Atk. +3%. When enchanted to +4, increases P. Evasion, Speed and P. Debuff Resistance, also decreases received Critical Rate from standard attacks.',
    'is_trade' => 1,
    'is_drop' => 1,
    'is_destruct' => 1,
    'crystal_type' => 'r99',
    'consume_type' => 'consume_type_normal',
  ],
  28281 => 
  [
    'item_id' => 28281,
    'icon' => 'armor_t802_l_i01',
    'name' => 'Transcendent Eternal Leggings',
    'additionalname' => 'Not used',
    'description' => 'Received damage -5%, P. Atk. +1.5%, M. Atk. +3%.',
    'is_trade' => 1,
    'is_drop' => 1,
    'is_destruct' => 1,
    'crystal_type' => 'r99',
    'consume_type' => 'consume_type_normal',
  ],
  28282 => 
  [
    'item_id' => 28282,
    'icon' => 'armor_t802_g_i01',
    'name' => 'Transcendent Eternal Gloves',
    'additionalname' => 'Not used',
    'description' => 'Received damage -2%, P. Atk. +1.5%, M. Atk. +3%.',
    'is_trade' => 1,
    'is_drop' => 1,
    'is_destruct' => 1,
    'crystal_type' => 'r99',
    'consume_type' => 'consume_type_normal',
  ],
  28283 => 
  [
    'item_id' => 28283,
    'icon' => 'armor_t802_b_i01',
    'name' => 'Transcendent Eternal Boots',
    'additionalname' => 'Not used',
    'description' => 'Received damage -2%, P. Atk. +1.5%, M. Atk. +3%.',
    'is_trade' => 1,
    'is_drop' => 1,
    'is_destruct' => 1,
    'crystal_type' => 'r99',
    'consume_type' => 'consume_type_normal',
  ],
  28284 => 
  [
    'item_id' => 28284,
    'icon' => 'armor_circlet_i01',
    'name' => 'Transcendent Eternal Circlet',
    'additionalname' => 'Reinforced robe / Lv. 6',
    'description' => 'Received damage -3%, P. Atk. +1.5%, M. Atk. +3%.Can be augmented.',
    'is_trade' => 1,
    'is_drop' => 1,
    'is_destruct' => 1,
    'crystal_type' => 'r99',
    'consume_type' => 'consume_type_normal',
  ],
  28285 => 
  [
    'item_id' => 28285,
    'icon' => 'armor_t803_u_i01',
    'name' => 'Transcendent Eternal Tunic',
    'additionalname' => 'Reinforced robe / Lv. 6',
    'description' => 'Received damage -8%, P. Atk. +1.5%, M. Atk. +3%. When enchanted to +4, increases M. Evasion and M. Debuff Resistance, also decreases received Critical Damage from basic attacks and received Critical Rate from basic attacks.Can be augmented.',
    'is_trade' => 1,
    'is_drop' => 1,
    'is_destruct' => 1,
    'crystal_type' => 'r99',
    'consume_type' => 'consume_type_normal',
  ],
  28286 => 
  [
    'item_id' => 28286,
    'icon' => 'armor_t803_l_i01',
    'name' => 'Transcendent Eternal Stockings',
    'additionalname' => 'Reinforced robe / Lv. 6',
    'description' => 'Received damage -5%, P. Atk. +1.5%, M. Atk. +3%.Can be augmented.',
    'is_trade' => 1,
    'is_drop' => 1,
    'is_destruct' => 1,
    'crystal_type' => 'r99',
    'consume_type' => 'consume_type_normal',
  ],
  28287 => 
  [
    'item_id' => 28287,
    'icon' => 'armor_t803_g_i01',
    'name' => 'Transcendent Eternal Gloves',
    'additionalname' => 'Reinforced robe / Lv. 6',
    'description' => 'Received damage -2%, P. Atk. +1.5%, M. Atk. +3%.Can be augmented.',
    'is_trade' => 1,
    'is_drop' => 1,
    'is_destruct' => 1,
    'crystal_type' => 'r99',
    'consume_type' => 'consume_type_normal',
  ],
  28288 => 
  [
    'item_id' => 28288,
    'icon' => 'armor_t803_b_i01',
    'name' => 'Transcendent Eternal Shoes',
    'additionalname' => 'Reinforced robe / Lv. 6',
    'description' => 'Received damage -2%, P. Atk. +1.5%, M. Atk. +3%.Can be augmented.',
    'is_trade' => 1,
    'is_drop' => 1,
    'is_destruct' => 1,
    'crystal_type' => 'r99',
    'consume_type' => 'consume_type_normal',
  ],
  28289 => 
  [
    'item_id' => 28289,
    'icon' => 'armor_helmet_i01',
    'name' => 'Transcendent Eternal Helmet',
    'additionalname' => 'Not used',
    'description' => 'Received damage -3%, P. Atk. +1.5%, M. Atk. +3%.',
    'is_trade' => 1,
    'is_drop' => 1,
    'is_destruct' => 1,
    'crystal_type' => 'r99',
    'consume_type' => 'consume_type_normal',
  ],
  28290 => 
  [
    'item_id' => 28290,
    'icon' => 'armor_t801_u_i01',
    'name' => 'Transcendent Eternal Breastplate',
    'additionalname' => 'Not used',
    'description' => 'Received Damage -8%. P. Atk. +1.5% and M. Atk. +3%. When enchanted to +4, decreases Received Critical Damage from standard attacks and increases P. Def.',
    'is_trade' => 1,
    'is_drop' => 1,
    'is_destruct' => 1,
    'crystal_type' => 'r99',
    'consume_type' => 'consume_type_normal',
  ],
  28291 => 
  [
    'item_id' => 28291,
    'icon' => 'armor_t801_l_i01',
    'name' => 'Transcendent Eternal Gaiters',
    'additionalname' => 'Not used',
    'description' => 'Received damage -5%, P. Atk. +1.5%, M. Atk. +3%.',
    'is_trade' => 1,
    'is_drop' => 1,
    'is_destruct' => 1,
    'crystal_type' => 'r99',
    'consume_type' => 'consume_type_normal',
  ],
  28292 => 
  [
    'item_id' => 28292,
    'icon' => 'armor_t801_g_i01',
    'name' => 'Transcendent Eternal Gauntlets',
    'additionalname' => 'Not used',
    'description' => 'Received damage -2%, P. Atk. +1.5%, M. Atk. +3%.',
    'is_trade' => 1,
    'is_drop' => 1,
    'is_destruct' => 1,
    'crystal_type' => 'r99',
    'consume_type' => 'consume_type_normal',
  ],
  28293 => 
  [
    'item_id' => 28293,
    'icon' => 'armor_t801_b_i01',
    'name' => 'Transcendent Eternal Boots',
    'additionalname' => 'Not used',
    'description' => 'Received damage -2%, P. Atk. +1.5%, M. Atk. +3%.',
    'is_trade' => 1,
    'is_drop' => 1,
    'is_destruct' => 1,
    'crystal_type' => 'r99',
    'consume_type' => 'consume_type_normal',
  ],
  28294 => 
  [
    'item_id' => 28294,
    'icon' => 'armor_helmet_i01',
    'name' => 'Transcendent Eternal Helmet',
    'additionalname' => 'Reinforced light armor / Lv. 6',
    'description' => 'Received damage -3%, P. Atk. +1.5%, M. Atk. +3%.Can be augmented.',
    'is_trade' => 1,
    'is_drop' => 1,
    'is_destruct' => 1,
    'crystal_type' => 'r99',
    'consume_type' => 'consume_type_normal',
  ],
  28295 => 
  [
    'item_id' => 28295,
    'icon' => 'armor_t802_u_i01',
    'name' => 'Transcendent Eternal Armor',
    'additionalname' => 'Reinforced light armor / Lv. 6',
    'description' => 'Received damage -8%, P. Atk. +1.5%, M. Atk. +3%. When enchanted to +4, increases P. Evasion, Speed and P. Debuff Resistance, also decreases received Critical Rate from basic attacks.Can be augmented.',
    'is_trade' => 1,
    'is_drop' => 1,
    'is_destruct' => 1,
    'crystal_type' => 'r99',
    'consume_type' => 'consume_type_normal',
  ],
  28296 => 
  [
    'item_id' => 28296,
    'icon' => 'armor_t802_l_i01',
    'name' => 'Transcendent Eternal Leggings',
    'additionalname' => 'Reinforced light armor / Lv. 6',
    'description' => 'Received damage -5%, P. Atk. +1.5%, M. Atk. +3%.Can be augmented.',
    'is_trade' => 1,
    'is_drop' => 1,
    'is_destruct' => 1,
    'crystal_type' => 'r99',
    'consume_type' => 'consume_type_normal',
  ],
  28297 => 
  [
    'item_id' => 28297,
    'icon' => 'armor_t802_g_i01',
    'name' => 'Transcendent Eternal Gloves',
    'additionalname' => 'Reinforced light armor / Lv. 6',
    'description' => 'Received damage -2%, P. Atk. +1.5%, M. Atk. +3%.Can be augmented.',
    'is_trade' => 1,
    'is_drop' => 1,
    'is_destruct' => 1,
    'crystal_type' => 'r99',
    'consume_type' => 'consume_type_normal',
  ],
  28298 => 
  [
    'item_id' => 28298,
    'icon' => 'armor_t802_b_i01',
    'name' => 'Transcendent Eternal Boots',
    'additionalname' => 'Reinforced light armor / Lv. 6',
    'description' => 'Received damage -2%, P. Atk. +1.5%, M. Atk. +3%.Can be augmented.',
    'is_trade' => 1,
    'is_drop' => 1,
    'is_destruct' => 1,
    'crystal_type' => 'r99',
    'consume_type' => 'consume_type_normal',
  ],
  28299 => 
  [
    'item_id' => 28299,
    'icon' => 'armor_circlet_i01',
    'name' => 'Transcendent Eternal Circlet',
    'additionalname' => 'Not used',
    'description' => 'Received damage -3%, P. Atk. +1.5%, M. Atk. +3%.',
    'is_trade' => 1,
    'is_drop' => 1,
    'is_destruct' => 1,
    'crystal_type' => 'r99',
    'consume_type' => 'consume_type_normal',
  ],
];