<?php return [
  28300 => 
  [
    'item_id' => 28300,
    'icon' => 'armor_t803_u_i01',
    'name' => 'Transcendent Eternal Tunic',
    'additionalname' => 'Recovery Type / Robe / Lv. 6',
    'description' => 'Ultimate enchant item. Decreases Damage Received by 8%.When enchanted to + 4, increases M. Evasion and Mentall Attack Resistance, and decreases P. Critical Damage and the chance of receiving P. Critical Hit. Aeore Healers only.',
    'is_trade' => 1,
    'is_drop' => 1,
    'is_destruct' => 1,
    'crystal_type' => 'r99',
    'consume_type' => 'consume_type_normal',
  ],
  28301 => 
  [
    'item_id' => 28301,
    'icon' => 'armor_t803_l_i01',
    'name' => 'Transcendent Eternal Stockings',
    'additionalname' => 'Recovery Type / Robe / Lv. 6',
    'description' => 'Ultimate enchant item. Decreases Damage Received by 5%. Aeore Healers only.',
    'is_trade' => 1,
    'is_drop' => 1,
    'is_destruct' => 1,
    'crystal_type' => 'r99',
    'consume_type' => 'consume_type_normal',
  ],
  28302 => 
  [
    'item_id' => 28302,
    'icon' => 'armor_t803_g_i01',
    'name' => 'Transcendent Eternal Gloves',
    'additionalname' => 'Recovery Type / Robe / Lv. 6',
    'description' => 'Ultimate enchant item. Decreases Damage Received by 2%. Aeore Healers only.',
    'is_trade' => 1,
    'is_drop' => 1,
    'is_destruct' => 1,
    'crystal_type' => 'r99',
    'consume_type' => 'consume_type_normal',
  ],
  28303 => 
  [
    'item_id' => 28303,
    'icon' => 'armor_t803_b_i01',
    'name' => 'Transcendent Eternal Shoes',
    'additionalname' => 'Recovery Type / Robe / Lv. 6',
    'description' => 'Ultimate enchant item. Decreases Damage Received by 2%. Aeore Healers only.',
    'is_trade' => 1,
    'is_drop' => 1,
    'is_destruct' => 1,
    'crystal_type' => 'r99',
    'consume_type' => 'consume_type_normal',
  ],
  28304 => 
  [
    'item_id' => 28304,
    'icon' => 'ring_earthworm_heart',
    'name' => 'Shilen\'s Ring',
    'additionalname' => '',
    'description' => 'M. Def. + 30%, Dark Resistance + 100, SRT/INT + 5, Critical Damage + 18%. Effect does not stack with additional rings.',
    'is_trade' => 1,
    'is_drop' => 1,
    'is_destruct' => 1,
    'crystal_type' => 'r',
    'consume_type' => 'consume_type_normal',
  ],
  28305 => 
  [
    'item_id' => 28305,
    'icon' => 'ring_earthworm_heart',
    'name' => 'Shilen\'s Ring - Not Used',
    'additionalname' => 'Stage 2',
    'description' => '',
    'is_trade' => 1,
    'is_drop' => 1,
    'is_destruct' => 1,
    'crystal_type' => 'r',
    'consume_type' => 'consume_type_normal',
  ],
  28306 => 
  [
    'item_id' => 28306,
    'icon' => 'ring_earthworm_heart',
    'name' => 'Shilen\'s Ring',
    'additionalname' => 'Stage 3',
    'description' => '',
    'is_trade' => 1,
    'is_drop' => 1,
    'is_destruct' => 1,
    'crystal_type' => 'r',
    'consume_type' => 'consume_type_normal',
  ],
  28307 => 
  [
    'item_id' => 28307,
    'icon' => 'etc_r991_ring_piece',
    'name' => 'Shilen\'s Ring Fragment',
    'additionalname' => '',
    'description' => 'Main ingredient for making Shilen\'s Ring.',
    'is_trade' => 1,
    'is_drop' => 1,
    'is_destruct' => 1,
    'crystal_type' => 'none',
    'consume_type' => 'consume_type_normal',
  ],
  28308 => 
  [
    'item_id' => 28308,
    'icon' => 'accessory_necklace_of_valakas_i00',
    'name' => 'Shilen\'s Necklace - Not Used',
    'additionalname' => '',
    'description' => 'M. Def. + 60%, Dark Resistance + 120, SRT/INT + 7, Physical/Mind attack success rate + 25. Effect does not stack with additional rings.',
    'is_trade' => 1,
    'is_drop' => 1,
    'is_destruct' => 1,
    'crystal_type' => 'r',
    'consume_type' => 'consume_type_normal',
  ],
  28309 => 
  [
    'item_id' => 28309,
    'icon' => 'accessory_necklace_of_valakas_i00',
    'name' => 'Shilen\'s Necklace - Not Used',
    'additionalname' => 'Stage 2',
    'description' => '',
    'is_trade' => 1,
    'is_drop' => 1,
    'is_destruct' => 1,
    'crystal_type' => 'r',
    'consume_type' => 'consume_type_normal',
  ],
  28310 => 
  [
    'item_id' => 28310,
    'icon' => 'accessory_necklace_of_valakas_i00',
    'name' => 'Shilen\'s Necklace - Not Used',
    'additionalname' => 'Stage 3',
    'description' => '',
    'is_trade' => 1,
    'is_drop' => 1,
    'is_destruct' => 1,
    'crystal_type' => 'r',
    'consume_type' => 'consume_type_normal',
  ],
  28311 => 
  [
    'item_id' => 28311,
    'icon' => 'etc_r991_necklace_piece',
    'name' => 'Shilen\'s Necklace Fragment',
    'additionalname' => '',
    'description' => 'Main ingredient for making Shilen\'s Necklace.',
    'is_trade' => 1,
    'is_drop' => 1,
    'is_destruct' => 1,
    'crystal_type' => 'none',
    'consume_type' => 'consume_type_normal',
  ],
  28312 => 
  [
    'item_id' => 28312,
    'icon' => 'accessory_earring_of_lind_i00',
    'name' => 'Shilen\'s Earring',
    'additionalname' => '',
    'description' => 'M. Def. + 50%, Dark Resistance + 110, SRT/INT + 6, Physical/Mind Resistance + 30, Speed + 10. Effect does not stack with additional rings.',
    'is_trade' => 1,
    'is_drop' => 1,
    'is_destruct' => 1,
    'crystal_type' => 'r',
    'consume_type' => 'consume_type_normal',
  ],
  28313 => 
  [
    'item_id' => 28313,
    'icon' => 'accessory_earring_of_lind_i00',
    'name' => 'Shilen\'s Earring - Not Used',
    'additionalname' => 'Stage 2',
    'description' => '',
    'is_trade' => 1,
    'is_drop' => 1,
    'is_destruct' => 1,
    'crystal_type' => 'r',
    'consume_type' => 'consume_type_normal',
  ],
  28314 => 
  [
    'item_id' => 28314,
    'icon' => 'accessory_earring_of_lind_i00',
    'name' => 'Shilen\'s Earring - Not Used',
    'additionalname' => 'Stage 3',
    'description' => '',
    'is_trade' => 1,
    'is_drop' => 1,
    'is_destruct' => 1,
    'crystal_type' => 'r',
    'consume_type' => 'consume_type_normal',
  ],
  28315 => 
  [
    'item_id' => 28315,
    'icon' => 'etc_r991_earring_piece',
    'name' => 'Shilen\'s Earring Fragment',
    'additionalname' => '',
    'description' => 'Main ingredient for making Shilen\'s Earring.',
    'is_trade' => 1,
    'is_drop' => 1,
    'is_destruct' => 1,
    'crystal_type' => 'none',
    'consume_type' => 'consume_type_normal',
  ],
  28316 => 
  [
    'item_id' => 28316,
    'icon' => 'g_scrl_of_ench_wolf_shirt',
    'name' => 'Scroll: Shilen\'s Ring',
    'additionalname' => '',
    'description' => 'Enchant scroll exclusive to Shilen\'s Ring. Unlike regular items, there\'s a chance of failing from + 1 enchant level, and it can be enchanted up to + 5. If it succeeds, M. Def., Dark Resistance, STR/INT and other various stats will increase gradually. Staring from + 3, there\'s a special effect, and from + 4, you can obtain a special skill for each accessory. If it fails, the item will disappear.',
    'is_trade' => 1,
    'is_drop' => 1,
    'is_destruct' => 1,
    'crystal_type' => 'none',
    'consume_type' => 'consume_type_stackable',
  ],
  28317 => 
  [
    'item_id' => 28317,
    'icon' => 'g_scrl_of_ench_wolf_shirt',
    'name' => 'Scroll: Shilen\'s Necklace',
    'additionalname' => '',
    'description' => 'Enchant scroll exclusive to Shilen\'s Necklace. Unlike regular items, there\'s a chance of failing from + 1 enchant level, and it can be enchanted up to + 5. If it succeeds, M. Def., Dark Resistance, STR/INT and other various stats will increase gradually. Staring from + 3, there\'s a special effect, and from + 4, you can obtain a special skill for each accessory. If it fails, the item will disappear.',
    'is_trade' => 1,
    'is_drop' => 1,
    'is_destruct' => 1,
    'crystal_type' => 'none',
    'consume_type' => 'consume_type_stackable',
  ],
  28318 => 
  [
    'item_id' => 28318,
    'icon' => 'g_scrl_of_ench_wolf_shirt',
    'name' => 'Scroll: Shilen\'s Earring',
    'additionalname' => '',
    'description' => 'Enchant scroll exclusive to Shilen\'s Earring. Unlike regular items, there\'s a chance of failing from + 1 enchant level, and it can be enchanted up to + 5. If it succeeds, M. Def., Dark Resistance, STR/INT and other various stats will increase gradually. Staring from + 3, there\'s a special effect, and from + 4, you can obtain a special skill for each accessory. If it fails, the item will disappear.',
    'is_trade' => 1,
    'is_drop' => 1,
    'is_destruct' => 1,
    'crystal_type' => 'none',
    'consume_type' => 'consume_type_stackable',
  ],
  28319 => 
  [
    'item_id' => 28319,
    'icon' => 'necklace_of_grankein_i00',
    'name' => 'Gran Kain\'s Necklace',
    'additionalname' => 'Stage 1',
    'description' => 'Double-click to obtain Grankain\'s Necklace Stage 1.',
    'is_trade' => 1,
    'is_drop' => 1,
    'is_destruct' => 1,
    'crystal_type' => 'none',
    'consume_type' => 'consume_type_stackable',
  ],
  28320 => 
  [
    'item_id' => 28320,
    'icon' => 'necklace_of_grankein_i00',
    'name' => 'Gran Kain\'s Necklace',
    'additionalname' => 'Stage 2',
    'description' => 'Double-click to obtain Grankain\'s Necklace Stage 2.',
    'is_trade' => 1,
    'is_drop' => 1,
    'is_destruct' => 1,
    'crystal_type' => 'none',
    'consume_type' => 'consume_type_stackable',
  ],
  28321 => 
  [
    'item_id' => 28321,
    'icon' => 'necklace_of_grankein_i00',
    'name' => 'Gran Kain\'s Necklace',
    'additionalname' => 'Stage 3',
    'description' => 'Double-click to obtain Grankain\'s Necklace Stage 3.',
    'is_trade' => 1,
    'is_drop' => 1,
    'is_destruct' => 1,
    'crystal_type' => 'none',
    'consume_type' => 'consume_type_stackable',
  ],
  28322 => 
  [
    'item_id' => 28322,
    'icon' => 'necklace_of_grankein_i00',
    'name' => 'Gran Kain\'s Necklace',
    'additionalname' => 'Stage 4',
    'description' => 'Double-click to obtain Grankain\'s Necklace Stage 4.',
    'is_trade' => 1,
    'is_drop' => 1,
    'is_destruct' => 1,
    'crystal_type' => 'none',
    'consume_type' => 'consume_type_stackable',
  ],
  28323 => 
  [
    'item_id' => 28323,
    'icon' => 'necklace_of_grankein_i00',
    'name' => 'Gran Kain\'s Necklace',
    'additionalname' => 'Stage 5',
    'description' => 'Double-click to obtain Grankain\'s Necklace Stage 5.',
    'is_trade' => 1,
    'is_drop' => 1,
    'is_destruct' => 1,
    'crystal_type' => 'none',
    'consume_type' => 'consume_type_stackable',
  ],
  28324 => 
  [
    'item_id' => 28324,
    'icon' => 'necklace_of_grankein_i00',
    'name' => 'Gran Kain\'s Necklace',
    'additionalname' => 'Stage 6',
    'description' => 'Double-click to obtain Grankain\'s Necklace Stage 6.',
    'is_trade' => 1,
    'is_drop' => 1,
    'is_destruct' => 1,
    'crystal_type' => 'none',
    'consume_type' => 'consume_type_stackable',
  ],
  28325 => 
  [
    'item_id' => 28325,
    'icon' => 'necklace_of_einhasad_i00',
    'name' => 'Einhasad\'s Necklace',
    'additionalname' => 'Stage 1',
    'description' => 'Double-click to obtain Einhasad\'s Necklace Stage 1.',
    'is_trade' => 1,
    'is_drop' => 1,
    'is_destruct' => 1,
    'crystal_type' => 'none',
    'consume_type' => 'consume_type_stackable',
  ],
  28326 => 
  [
    'item_id' => 28326,
    'icon' => 'necklace_of_einhasad_i00',
    'name' => 'Einhasad\'s Necklace',
    'additionalname' => 'Stage 2',
    'description' => 'Double-click to obtain Einhasad\'s Necklace Stage 2.',
    'is_trade' => 1,
    'is_drop' => 1,
    'is_destruct' => 1,
    'crystal_type' => 'none',
    'consume_type' => 'consume_type_stackable',
  ],
  28327 => 
  [
    'item_id' => 28327,
    'icon' => 'necklace_of_einhasad_i00',
    'name' => 'Einhasad\'s Necklace',
    'additionalname' => 'Stage 3',
    'description' => 'Double-click to obtain Einhasad\'s Necklace Stage 3.',
    'is_trade' => 1,
    'is_drop' => 1,
    'is_destruct' => 1,
    'crystal_type' => 'none',
    'consume_type' => 'consume_type_stackable',
  ],
  28328 => 
  [
    'item_id' => 28328,
    'icon' => 'necklace_of_einhasad_i00',
    'name' => 'Einhasad\'s Necklace',
    'additionalname' => 'Stage 4',
    'description' => 'Double-click to obtain Einhasad\'s Necklace Stage 4.',
    'is_trade' => 1,
    'is_drop' => 1,
    'is_destruct' => 1,
    'crystal_type' => 'none',
    'consume_type' => 'consume_type_stackable',
  ],
  28329 => 
  [
    'item_id' => 28329,
    'icon' => 'necklace_of_einhasad_i00',
    'name' => 'Einhasad\'s Necklace',
    'additionalname' => 'Stage 5',
    'description' => 'Double-click to obtain Einhasad\'s Necklace Stage 5.',
    'is_trade' => 1,
    'is_drop' => 1,
    'is_destruct' => 1,
    'crystal_type' => 'none',
    'consume_type' => 'consume_type_stackable',
  ],
  28330 => 
  [
    'item_id' => 28330,
    'icon' => 'necklace_of_einhasad_i00',
    'name' => 'Einhasad\'s Necklace',
    'additionalname' => 'Stage 6',
    'description' => 'Double-click to obtain Einhasad\'s Necklace Stage 6.',
    'is_trade' => 1,
    'is_drop' => 1,
    'is_destruct' => 1,
    'crystal_type' => 'none',
    'consume_type' => 'consume_type_stackable',
  ],
  28331 => 
  [
    'item_id' => 28331,
    'icon' => 'earring_of_paagrio_i00',
    'name' => 'Pa\'agrio\'s Earring',
    'additionalname' => 'Stage 1',
    'description' => 'Double-click to obtain Pa\'agrio\'s Earring Stage 1.',
    'is_trade' => 1,
    'is_drop' => 1,
    'is_destruct' => 1,
    'crystal_type' => 'none',
    'consume_type' => 'consume_type_stackable',
  ],
  28332 => 
  [
    'item_id' => 28332,
    'icon' => 'earring_of_paagrio_i00',
    'name' => 'Pa\'agrio\'s Earring',
    'additionalname' => 'Stage 2',
    'description' => 'Double-click to obtain Pa\'agrio\'s Earring Stage 2.',
    'is_trade' => 1,
    'is_drop' => 1,
    'is_destruct' => 1,
    'crystal_type' => 'none',
    'consume_type' => 'consume_type_stackable',
  ],
  28333 => 
  [
    'item_id' => 28333,
    'icon' => 'earring_of_paagrio_i00',
    'name' => 'Pa\'agrio\'s Earring',
    'additionalname' => 'Stage 3',
    'description' => 'Double-click to obtain Pa\'agrio\'s Earring Stage 3.',
    'is_trade' => 1,
    'is_drop' => 1,
    'is_destruct' => 1,
    'crystal_type' => 'none',
    'consume_type' => 'consume_type_stackable',
  ],
  28334 => 
  [
    'item_id' => 28334,
    'icon' => 'earring_of_paagrio_i00',
    'name' => 'Pa\'agrio\'s Earring',
    'additionalname' => 'Stage 4',
    'description' => 'Double-click to obtain Pa\'agrio\'s Earring Stage 4.',
    'is_trade' => 1,
    'is_drop' => 1,
    'is_destruct' => 1,
    'crystal_type' => 'none',
    'consume_type' => 'consume_type_stackable',
  ],
  28335 => 
  [
    'item_id' => 28335,
    'icon' => 'earring_of_paagrio_i00',
    'name' => 'Pa\'agrio\'s Earring',
    'additionalname' => 'Stage 5',
    'description' => 'Double-click to obtain Pa\'agrio\'s Earring Stage 5.',
    'is_trade' => 1,
    'is_drop' => 1,
    'is_destruct' => 1,
    'crystal_type' => 'none',
    'consume_type' => 'consume_type_stackable',
  ],
  28336 => 
  [
    'item_id' => 28336,
    'icon' => 'earring_of_paagrio_i00',
    'name' => 'Pa\'agrio\'s Earring',
    'additionalname' => 'Stage 6',
    'description' => 'Double-click to obtain Pa\'agrio\'s Earring Stage 6.',
    'is_trade' => 1,
    'is_drop' => 1,
    'is_destruct' => 1,
    'crystal_type' => 'none',
    'consume_type' => 'consume_type_stackable',
  ],
  28337 => 
  [
    'item_id' => 28337,
    'icon' => 'earring_of_eva_i00',
    'name' => 'Eva\'s Earring',
    'additionalname' => 'Stage 1',
    'description' => 'Double-click to obtain Eva\'s Earring Stage 1.',
    'is_trade' => 1,
    'is_drop' => 1,
    'is_destruct' => 1,
    'crystal_type' => 'none',
    'consume_type' => 'consume_type_stackable',
  ],
  28338 => 
  [
    'item_id' => 28338,
    'icon' => 'earring_of_eva_i00',
    'name' => 'Eva\'s Earring',
    'additionalname' => 'Stage 2',
    'description' => 'Double-click to obtain Eva\'s Earring Stage 2.',
    'is_trade' => 1,
    'is_drop' => 1,
    'is_destruct' => 1,
    'crystal_type' => 'none',
    'consume_type' => 'consume_type_stackable',
  ],
  28339 => 
  [
    'item_id' => 28339,
    'icon' => 'earring_of_eva_i00',
    'name' => 'Eva\'s Earring',
    'additionalname' => 'Stage 3',
    'description' => 'Double-click to obtain Eva\'s Earring Stage 3.',
    'is_trade' => 1,
    'is_drop' => 1,
    'is_destruct' => 1,
    'crystal_type' => 'none',
    'consume_type' => 'consume_type_stackable',
  ],
  28340 => 
  [
    'item_id' => 28340,
    'icon' => 'earring_of_eva_i00',
    'name' => 'Eva\'s Earring',
    'additionalname' => 'Stage 4',
    'description' => 'Double-click to obtain Eva\'s Earring Stage 4.',
    'is_trade' => 1,
    'is_drop' => 1,
    'is_destruct' => 1,
    'crystal_type' => 'none',
    'consume_type' => 'consume_type_stackable',
  ],
  28341 => 
  [
    'item_id' => 28341,
    'icon' => 'earring_of_eva_i00',
    'name' => 'Eva\'s Earring',
    'additionalname' => 'Stage 5',
    'description' => 'Double-click to obtain Eva\'s Earring Stage 5.',
    'is_trade' => 1,
    'is_drop' => 1,
    'is_destruct' => 1,
    'crystal_type' => 'none',
    'consume_type' => 'consume_type_stackable',
  ],
  28342 => 
  [
    'item_id' => 28342,
    'icon' => 'earring_of_eva_i00',
    'name' => 'Eva\'s Earring',
    'additionalname' => 'Stage 6',
    'description' => 'Double-click to obtain Eva\'s Earring Stage 6.',
    'is_trade' => 1,
    'is_drop' => 1,
    'is_destruct' => 1,
    'crystal_type' => 'none',
    'consume_type' => 'consume_type_stackable',
  ],
  28343 => 
  [
    'item_id' => 28343,
    'icon' => 'ring_of_sayhas_i00',
    'name' => 'Sayha\'s Ring',
    'additionalname' => 'Stage 1',
    'description' => 'Double-click to obtain Sayha\'s Ring Stage 1.',
    'is_trade' => 1,
    'is_drop' => 1,
    'is_destruct' => 1,
    'crystal_type' => 'none',
    'consume_type' => 'consume_type_stackable',
  ],
  28344 => 
  [
    'item_id' => 28344,
    'icon' => 'ring_of_sayhas_i00',
    'name' => 'Sayha\'s Ring',
    'additionalname' => 'Stage 2',
    'description' => 'Double-click to obtain Sayha\'s Ring Stage 2.',
    'is_trade' => 1,
    'is_drop' => 1,
    'is_destruct' => 1,
    'crystal_type' => 'none',
    'consume_type' => 'consume_type_stackable',
  ],
  28345 => 
  [
    'item_id' => 28345,
    'icon' => 'ring_of_sayhas_i00',
    'name' => 'Sayha\'s Ring',
    'additionalname' => 'Stage 3',
    'description' => 'Double-click to obtain Sayha\'s Ring Stage 3.',
    'is_trade' => 1,
    'is_drop' => 1,
    'is_destruct' => 1,
    'crystal_type' => 'none',
    'consume_type' => 'consume_type_stackable',
  ],
  28346 => 
  [
    'item_id' => 28346,
    'icon' => 'ring_of_sayhas_i00',
    'name' => 'Sayha\'s Ring',
    'additionalname' => 'Stage 4',
    'description' => 'Double-click to obtain Sayha\'s Ring Stage 4.',
    'is_trade' => 1,
    'is_drop' => 1,
    'is_destruct' => 1,
    'crystal_type' => 'none',
    'consume_type' => 'consume_type_stackable',
  ],
  28347 => 
  [
    'item_id' => 28347,
    'icon' => 'ring_of_sayhas_i00',
    'name' => 'Sayha\'s Ring',
    'additionalname' => 'Stage 5',
    'description' => 'Double-click to obtain Sayha\'s Ring Stage 5.',
    'is_trade' => 1,
    'is_drop' => 1,
    'is_destruct' => 1,
    'crystal_type' => 'none',
    'consume_type' => 'consume_type_stackable',
  ],
  28348 => 
  [
    'item_id' => 28348,
    'icon' => 'ring_of_sayhas_i00',
    'name' => 'Sayha\'s Ring',
    'additionalname' => 'Stage 6',
    'description' => 'Double-click to obtain Sayha\'s Ring Stage 6.',
    'is_trade' => 1,
    'is_drop' => 1,
    'is_destruct' => 1,
    'crystal_type' => 'none',
    'consume_type' => 'consume_type_stackable',
  ],
  28349 => 
  [
    'item_id' => 28349,
    'icon' => 'ring_of_maphr_i00',
    'name' => 'Maphr\'s Ring',
    'additionalname' => 'Stage 1',
    'description' => 'Double-click to obtain Maphr\'s Ring Stage 1.',
    'is_trade' => 1,
    'is_drop' => 1,
    'is_destruct' => 1,
    'crystal_type' => 'none',
    'consume_type' => 'consume_type_stackable',
  ],
  28350 => 
  [
    'item_id' => 28350,
    'icon' => 'ring_of_maphr_i00',
    'name' => 'Maphr\'s Ring',
    'additionalname' => 'Stage 2',
    'description' => 'Double-click to obtain Maphr\'s Ring Stage 2.',
    'is_trade' => 1,
    'is_drop' => 1,
    'is_destruct' => 1,
    'crystal_type' => 'none',
    'consume_type' => 'consume_type_stackable',
  ],
  28351 => 
  [
    'item_id' => 28351,
    'icon' => 'ring_of_maphr_i00',
    'name' => 'Maphr\'s Ring',
    'additionalname' => 'Stage 3',
    'description' => 'Double-click to obtain Maphr\'s Ring Stage 3.',
    'is_trade' => 1,
    'is_drop' => 1,
    'is_destruct' => 1,
    'crystal_type' => 'none',
    'consume_type' => 'consume_type_stackable',
  ],
  28352 => 
  [
    'item_id' => 28352,
    'icon' => 'ring_of_maphr_i00',
    'name' => 'Maphr\'s Ring',
    'additionalname' => 'Stage 4',
    'description' => 'Double-click to obtain Maphr\'s Ring Stage 4.',
    'is_trade' => 1,
    'is_drop' => 1,
    'is_destruct' => 1,
    'crystal_type' => 'none',
    'consume_type' => 'consume_type_stackable',
  ],
  28353 => 
  [
    'item_id' => 28353,
    'icon' => 'ring_of_maphr_i00',
    'name' => 'Maphr\'s Ring',
    'additionalname' => 'Stage 5',
    'description' => 'Double-click to obtain Maphr\'s Ring Stage 5.',
    'is_trade' => 1,
    'is_drop' => 1,
    'is_destruct' => 1,
    'crystal_type' => 'none',
    'consume_type' => 'consume_type_stackable',
  ],
  28354 => 
  [
    'item_id' => 28354,
    'icon' => 'ring_of_maphr_i00',
    'name' => 'Maphr\'s Ring',
    'additionalname' => 'Stage 6',
    'description' => 'Double-click to obtain Maphr\'s Ring Stage 6.',
    'is_trade' => 1,
    'is_drop' => 1,
    'is_destruct' => 1,
    'crystal_type' => 'none',
    'consume_type' => 'consume_type_stackable',
  ],
  28355 => 
  [
    'item_id' => 28355,
    'icon' => 'etc_dkbrown_crystal_cube_pc_i00',
    'name' => 'Prestige Cube',
    'additionalname' => '7-day',
    'description' => 'Double-click to obtain either Dark/Bloody Eternal Enhancement Stone, various Weapon Enchant Scrolls, Giant\'s Energy, or Gemstone (R-grade]. Once a day. Cannot be used in the Olympiad.',
    'is_trade' => 0,
    'is_drop' => 0,
    'is_destruct' => 0,
    'crystal_type' => 'none',
    'consume_type' => 'consume_type_normal',
  ],
  28356 => 
  [
    'item_id' => 28356,
    'icon' => 'br_lucky_bag_box_i00',
    'name' => 'Prestige Cube Pack',
    'additionalname' => '7-day',
    'description' => 'Wrapped Pack containing 1 Prestige Cube (7-day].',
    'is_trade' => 0,
    'is_drop' => 0,
    'is_destruct' => 1,
    'crystal_type' => 'none',
    'consume_type' => 'consume_type_stackable',
  ],
  28357 => 
  [
    'item_id' => 28357,
    'icon' => 'etc_treasure_box_i02',
    'name' => 'Special Treasure Chest',
    'additionalname' => '',
    'description' => 'Special treasure chest. Double-click to receive a random item.',
    'is_trade' => 1,
    'is_drop' => 1,
    'is_destruct' => 1,
    'crystal_type' => 'none',
    'consume_type' => 'consume_type_stackable',
  ],
  28358 => 
  [
    'item_id' => 28358,
    'icon' => 'etc_g_bm_brooch_lavianrose',
    'name' => 'La Vie En Rose\'s Elegant Brooch',
    'additionalname' => '',
    'description' => 'Activates 6 jewel slots when equipped. Inventory Slot + 12.',
    'is_trade' => 1,
    'is_drop' => 1,
    'is_destruct' => 1,
    'crystal_type' => 'none',
    'consume_type' => 'consume_type_normal',
  ],
  28359 => 
  [
    'item_id' => 28359,
    'icon' => 'etc_g_bm_powder_jewel',
    'name' => 'La Vie En Rose\'s Gemstone Powder',
    'additionalname' => '',
    'description' => 'La Vie En Rose\'s refined gemstone powder. Go find Shadai to use it when exchanging for gemstones.',
    'is_trade' => 1,
    'is_drop' => 1,
    'is_destruct' => 1,
    'crystal_type' => 'none',
    'consume_type' => 'consume_type_stackable',
  ],
  28360 => 
  [
    'item_id' => 28360,
    'icon' => 'etc_bm_jewelbox_catseye_i00',
    'name' => 'Cat\'s Eye Lv. 3 Jewelry Box',
    'additionalname' => '',
    'description' => 'Double-click to obtain a Cat\'s Eye Lv. 3.',
    'is_trade' => 1,
    'is_drop' => 1,
    'is_destruct' => 1,
    'crystal_type' => 'none',
    'consume_type' => 'consume_type_stackable',
  ],
  28361 => 
  [
    'item_id' => 28361,
    'icon' => 'etc_bm_jewelbox_catseye_i00',
    'name' => 'Cat\'s Eye Lv. 4 Jewelry Box',
    'additionalname' => '',
    'description' => 'Double-click to obtain a Cat\'s Eye Lv. 4.',
    'is_trade' => 1,
    'is_drop' => 1,
    'is_destruct' => 1,
    'crystal_type' => 'none',
    'consume_type' => 'consume_type_stackable',
  ],
  28362 => 
  [
    'item_id' => 28362,
    'icon' => 'etc_bm_jewelbox_amethyst_i00',
    'name' => 'Amethyst Lv. 3 Jewelry Box',
    'additionalname' => '',
    'description' => 'Double-click to obtain a Amethyst Lv. 3.',
    'is_trade' => 1,
    'is_drop' => 1,
    'is_destruct' => 1,
    'crystal_type' => 'none',
    'consume_type' => 'consume_type_stackable',
  ],
  28363 => 
  [
    'item_id' => 28363,
    'icon' => 'etc_bm_jewelbox_amethyst_i00',
    'name' => 'Amethyst Lv. 4 Jewelry Box',
    'additionalname' => '',
    'description' => 'Double-click to obtain a Amethyst Lv. 4.',
    'is_trade' => 1,
    'is_drop' => 1,
    'is_destruct' => 1,
    'crystal_type' => 'none',
    'consume_type' => 'consume_type_stackable',
  ],
  28364 => 
  [
    'item_id' => 28364,
    'icon' => 'etc_g_bm_jewel_grinder',
    'name' => 'Jewel Grinder',
    'additionalname' => '',
    'description' => 'A grinder used for refining La Vie En Rose\'s jewels. Ask Shadai to grind gemstones.',
    'is_trade' => 1,
    'is_drop' => 1,
    'is_destruct' => 1,
    'crystal_type' => 'none',
    'consume_type' => 'consume_type_stackable',
  ],
  28365 => 
  [
    'item_id' => 28365,
    'icon' => 'bm_sayha_blessed_box',
    'name' => 'Ultimate Jewelry Box',
    'additionalname' => '',
    'description' => 'Double-click to obtain a La Vie En Rose\'s Jewelry Box.',
    'is_trade' => 1,
    'is_drop' => 1,
    'is_destruct' => 1,
    'crystal_type' => 'none',
    'consume_type' => 'consume_type_stackable',
  ],
  28366 => 
  [
    'item_id' => 28366,
    'icon' => 'etc_bm_jewelbox_vital',
    'name' => 'Vital Stone Lv. 3 Jewelry Box',
    'additionalname' => '',
    'description' => 'Double-click to obtain a Vital Stone Lv. 3.',
    'is_trade' => 1,
    'is_drop' => 1,
    'is_destruct' => 1,
    'crystal_type' => 'none',
    'consume_type' => 'consume_type_stackable',
  ],
  28367 => 
  [
    'item_id' => 28367,
    'icon' => 'etc_bm_jewelbox_tanzanite',
    'name' => 'Tanzanite Lv. 3 Jewelry Box',
    'additionalname' => '',
    'description' => 'Double-click to obtain a Tanzanite Lv. 3.',
    'is_trade' => 1,
    'is_drop' => 1,
    'is_destruct' => 1,
    'crystal_type' => 'none',
    'consume_type' => 'consume_type_stackable',
  ],
  28368 => 
  [
    'item_id' => 28368,
    'icon' => 'etc_bm_jewelbox_vital',
    'name' => 'Vital Stone Lv. 4 Jewelry Box',
    'additionalname' => '',
    'description' => 'Double-click to obtain a Vital Stone Lv. 4.',
    'is_trade' => 1,
    'is_drop' => 1,
    'is_destruct' => 1,
    'crystal_type' => 'none',
    'consume_type' => 'consume_type_stackable',
  ],
  28369 => 
  [
    'item_id' => 28369,
    'icon' => 'etc_bm_jewelbox_tanzanite',
    'name' => 'Tanzanite Lv. 4 Jewelry Box',
    'additionalname' => '',
    'description' => 'Double-click to obtain a Tanzanite Lv. 4.',
    'is_trade' => 1,
    'is_drop' => 1,
    'is_destruct' => 1,
    'crystal_type' => 'none',
    'consume_type' => 'consume_type_stackable',
  ],
  28370 => 
  [
    'item_id' => 28370,
    'icon' => 'etc_bm_jewelbox_garnet',
    'name' => 'Garnet Lv. 3 Jewelry Box',
    'additionalname' => '',
    'description' => 'Double-click to obtain a Tanzanite Lv. 3.',
    'is_trade' => 1,
    'is_drop' => 1,
    'is_destruct' => 1,
    'crystal_type' => 'none',
    'consume_type' => 'consume_type_stackable',
  ],
  28371 => 
  [
    'item_id' => 28371,
    'icon' => 'etc_bm_jewelbox_garnet',
    'name' => 'Garnet Lv. 4 Jewelry Box',
    'additionalname' => '',
    'description' => 'Double-click to obtain a Vital Stone Lv. 4.',
    'is_trade' => 1,
    'is_drop' => 1,
    'is_destruct' => 1,
    'crystal_type' => 'none',
    'consume_type' => 'consume_type_stackable',
  ],
  28372 => 
  [
    'item_id' => 28372,
    'icon' => 'etc_bm_jewelbox_vital',
    'name' => 'Vital Stone Lv. 3 Jewelry Box',
    'additionalname' => '',
    'description' => 'Double-click to obtain a Vital Stone Lv. 3.',
    'is_trade' => 1,
    'is_drop' => 1,
    'is_destruct' => 1,
    'crystal_type' => 'none',
    'consume_type' => 'consume_type_stackable',
  ],
  28373 => 
  [
    'item_id' => 28373,
    'icon' => 'etc_bm_jewelbox_tanzanite',
    'name' => 'Tanzanite Lv. 3 Jewelry Box',
    'additionalname' => '',
    'description' => 'Double-click to obtain a Tanzanite Lv. 3.',
    'is_trade' => 1,
    'is_drop' => 1,
    'is_destruct' => 1,
    'crystal_type' => 'none',
    'consume_type' => 'consume_type_stackable',
  ],
  28374 => 
  [
    'item_id' => 28374,
    'icon' => 'etc_bm_jewelbox_vital',
    'name' => 'Vital Stone Lv. 4 Jewelry Box',
    'additionalname' => '',
    'description' => 'Double-click to obtain a Vital Stone Lv. 4.',
    'is_trade' => 1,
    'is_drop' => 1,
    'is_destruct' => 1,
    'crystal_type' => 'none',
    'consume_type' => 'consume_type_stackable',
  ],
  28375 => 
  [
    'item_id' => 28375,
    'icon' => 'etc_bm_jewelbox_tanzanite',
    'name' => 'Tanzanite Lv. 4 Jewelry Box',
    'additionalname' => '',
    'description' => 'Double-click to obtain a Tanzanite Lv. 4.',
    'is_trade' => 1,
    'is_drop' => 1,
    'is_destruct' => 1,
    'crystal_type' => 'none',
    'consume_type' => 'consume_type_stackable',
  ],
  28376 => 
  [
    'item_id' => 28376,
    'icon' => 'etc_bm_jewel_catseye_i00',
    'name' => 'Greater Cat\'s Eye',
    'additionalname' => '',
    'description' => 'Decreases damage received from Reflect Damage by 50 and there\'s a chance of reflecting debuffs to the enemy. Can use the invincibility skill. Effect does not stack with additional jewels of the same type. Equipping various Greater Jewels will grant additional effects.',
    'is_trade' => 1,
    'is_drop' => 1,
    'is_destruct' => 1,
    'crystal_type' => 'none',
    'consume_type' => 'consume_type_normal',
  ],
  28377 => 
  [
    'item_id' => 28377,
    'icon' => 'etc_bm_jewel_amethyst_i00',
    'name' => 'Greater Amethyst',
    'additionalname' => '',
    'description' => 'PvP Damage + 15%, chance of receiving a critical attack - 25%. Can remove invincibility. Effect does not stack with additional jewels of the same type. Equipping various Greater Jewels will grant additional effects.',
    'is_trade' => 1,
    'is_drop' => 1,
    'is_destruct' => 1,
    'crystal_type' => 'none',
    'consume_type' => 'consume_type_normal',
  ],
  28378 => 
  [
    'item_id' => 28378,
    'icon' => 'bm_jewel_vital_high_lv1_lavianrose',
    'name' => 'Greater Vital Stone',
    'additionalname' => '',
    'description' => 'Increases Vitality Status Bonus EXP by 50% and decreases Vitality Point Consumption Speed by 15%. XP Gain increases by 10%. Can use Vital Wind skill. Effect does not stack with additional jewels of the same type. Equipping various Greater Jewels will grant additional effects.',
    'is_trade' => 1,
    'is_drop' => 1,
    'is_destruct' => 1,
    'crystal_type' => 'none',
    'consume_type' => 'consume_type_normal',
  ],
  28379 => 
  [
    'item_id' => 28379,
    'icon' => 'bm_jewel_garnet_high_lv1_lavianrose',
    'name' => 'Greater Garnet',
    'additionalname' => '',
    'description' => 'Resistance to Debuffs + 30%, and when receiving damage to a PC, Stun/Silence are canceled. Cancels debuff and you become immune to debuffs for 7 seconds. Effect does not stack with additional jewels of the same type. Equipping various Greater Jewels will grant additional effects.',
    'is_trade' => 1,
    'is_drop' => 1,
    'is_destruct' => 1,
    'crystal_type' => 'none',
    'consume_type' => 'consume_type_normal',
  ],
  28380 => 
  [
    'item_id' => 28380,
    'icon' => 'bm_jewel_tanzanite_high_lv1_lavianrose',
    'name' => 'Greater Tanzanite',
    'additionalname' => '',
    'description' => 'Creates a protection shield that absorbs 50,000 damage for 15 seconds. Recover 15% of Max HP instantly. Effect does not stack with additional jewels of the same type. Equipping various Greater Jewels will grant additional effects.',
    'is_trade' => 1,
    'is_drop' => 1,
    'is_destruct' => 1,
    'crystal_type' => 'none',
    'consume_type' => 'consume_type_normal',
  ],
  28381 => 
  [
    'item_id' => 28381,
    'icon' => 'etc_pi_gift_box_i03',
    'name' => 'Abundance Box',
    'additionalname' => 'Infinite',
    'description' => 'Get 1 of the following: 1 type of Talisman - Abundance, Lindvior\'s Earring, Earth Wyrm Heart Ring, Seven Signs\' Energy, Talisman - Lilith, Talisman - Anakim, Talisman - Insanity, Talisman - Longing, Antharas\' Earring, Bottle of Antharas\' Soul, Valakas\' Necklace, Bottle of Valakas\' Soul, Baium\'s Ring, Baium\'s Soul Ring, Octavis\' Ring, Octavis\' Earring, Octavis\' Necklace, Istina\'s Necklace, Istina\'s Ring, Queen Ant\'s Ring, Superior Giant\'s Codex Chapter 1, Superior Giant\'s Codex - Mastery Chapter 1, Superior Giant\'s Codex - Discipline Chapter 1, Lv. 5 Legendary Dye Pack, Elcyum Regular/Crystal, Giant\'s Energy, Orfen\'s Earring, Tempest Stone, Gemstone, Fortune Pocket - Stage 5, Blessed Zaken, Venir\'s Talisman Stage 8/10/14.',
    'is_trade' => 1,
    'is_drop' => 1,
    'is_destruct' => 1,
    'crystal_type' => 'none',
    'consume_type' => 'consume_type_stackable',
  ],
  28382 => 
  [
    'item_id' => 28382,
    'icon' => 'bm_sayha_blessed_box',
    'name' => 'Ultimate Jewelry Box',
    'additionalname' => '',
    'description' => 'Double-click to obtain a La Vie En Rose\'s Jewelry Box.',
    'is_trade' => 1,
    'is_drop' => 1,
    'is_destruct' => 1,
    'crystal_type' => 'none',
    'consume_type' => 'consume_type_stackable',
  ],
  28383 => 
  [
    'item_id' => 28383,
    'icon' => 'bm_jewel_garnet_high_lv1_lavianrose',
    'name' => 'Greater Garnet',
    'additionalname' => '',
    'description' => 'Increases Resistance to all Debuffs by 30%, and when receiving damage to a PC, Stun/Silence are canceled. When used, all debuffs are canceled and you become immune to debuffs for 7 seconds. Effect does not stack with additional jewels of the same type. Equipping various Greater Jewels will grant additional effects.',
    'is_trade' => 1,
    'is_drop' => 1,
    'is_destruct' => 1,
    'crystal_type' => 'none',
    'consume_type' => 'consume_type_normal',
  ],
  28384 => 
  [
    'item_id' => 28384,
    'icon' => 'g_monkey_belt',
    'name' => 'Chef Monkey\'s Belt',
    'additionalname' => '',
    'description' => 'A belt from Chef Monkey. When equipped, Max HP/MP/CP + 300, Weight + 12800, Damage + 7%, Received Damage - 5%, Inventory Slots + 18, Attribute Resistance + 5.',
    'is_trade' => 1,
    'is_drop' => 1,
    'is_destruct' => 1,
    'crystal_type' => 'r',
    'consume_type' => 'consume_type_normal',
  ],
  28385 => 
  [
    'item_id' => 28385,
    'icon' => 'br_four_leaf_clover_box_i00',
    'name' => 'Race Change Ticket Pack',
    'additionalname' => '',
    'description' => 'Double-click to obtain a Race Change Ticket.',
    'is_trade' => 0,
    'is_drop' => 0,
    'is_destruct' => 1,
    'crystal_type' => 'none',
    'consume_type' => 'consume_type_stackable',
  ],
  28386 => 
  [
    'item_id' => 28386,
    'icon' => 'etc_exchange_ticket_i00',
    'name' => 'Race Change Ticket',
    'additionalname' => '',
    'description' => 'Do the following to change your character\'s race.
1.Place this item with the character that you want to change the race for.
2.Submit a ticket at support.lineage2.com with the title "Character Race Change".
<Note>Erteia, Kamael, Tirr Maestro, Iss Dominator characters cannot use this item.',
    'is_trade' => 0,
    'is_drop' => 0,
    'is_destruct' => 1,
    'crystal_type' => 'none',
    'consume_type' => 'consume_type_stackable',
  ],
  28387 => 
  [
    'item_id' => 28387,
    'icon' => 'br_four_leaf_clover_box_i00',
    'name' => 'Agathion - Unlimited Vitality Pack',
    'additionalname' => '',
    'description' => 'Wrapped pack containing Agathion - Unlimited Vitality.',
    'is_trade' => 0,
    'is_drop' => 0,
    'is_destruct' => 1,
    'crystal_type' => 'none',
    'consume_type' => 'consume_type_stackable',
  ],
  28388 => 
  [
    'item_id' => 28388,
    'icon' => 'br_aga_bonus_i00',
    'name' => 'Agathion - Unlimited Vitality',
    'additionalname' => '',
    'description' => 'Summons Unlimited Vitality Agathion.',
    'is_trade' => 0,
    'is_drop' => 0,
    'is_destruct' => 1,
    'crystal_type' => 'none',
    'consume_type' => 'consume_type_normal',
  ],
  28389 => 
  [
    'item_id' => 28389,
    'icon' => 'etc_bait_i01',
    'name' => '',
    'additionalname' => '',
    'description' => '',
    'is_trade' => 0,
    'is_drop' => 0,
    'is_destruct' => 1,
    'crystal_type' => 'none',
    'consume_type' => 'consume_type_stackable',
  ],
  28390 => 
  [
    'item_id' => 28390,
    'icon' => 'etc_bait_i01',
    'name' => '',
    'additionalname' => '',
    'description' => '',
    'is_trade' => 0,
    'is_drop' => 0,
    'is_destruct' => 1,
    'crystal_type' => 'none',
    'consume_type' => 'consume_type_stackable',
  ],
  28391 => 
  [
    'item_id' => 28391,
    'icon' => 'etc_bait_i01',
    'name' => '',
    'additionalname' => '',
    'description' => '',
    'is_trade' => 0,
    'is_drop' => 0,
    'is_destruct' => 1,
    'crystal_type' => 'none',
    'consume_type' => 'consume_type_stackable',
  ],
  28392 => 
  [
    'item_id' => 28392,
    'icon' => 'etc_bait_i01',
    'name' => '',
    'additionalname' => '',
    'description' => '',
    'is_trade' => 0,
    'is_drop' => 0,
    'is_destruct' => 1,
    'crystal_type' => 'none',
    'consume_type' => 'consume_type_stackable',
  ],
  28393 => 
  [
    'item_id' => 28393,
    'icon' => 'etc_bm_lure_ticket',
    'name' => '',
    'additionalname' => '',
    'description' => '',
    'is_trade' => 1,
    'is_drop' => 1,
    'is_destruct' => 1,
    'crystal_type' => 'none',
    'consume_type' => 'consume_type_stackable',
  ],
  28394 => 
  [
    'item_id' => 28394,
    'icon' => 'etc_treasure_box_i08',
    'name' => '',
    'additionalname' => '',
    'description' => '',
    'is_trade' => 1,
    'is_drop' => 1,
    'is_destruct' => 1,
    'crystal_type' => 'none',
    'consume_type' => 'consume_type_stackable',
  ],
  28395 => 
  [
    'item_id' => 28395,
    'icon' => 'etc_bm_lure_box_i00',
    'name' => '',
    'additionalname' => '',
    'description' => '',
    'is_trade' => 1,
    'is_drop' => 1,
    'is_destruct' => 1,
    'crystal_type' => 'none',
    'consume_type' => 'consume_type_stackable',
  ],
  28396 => 
  [
    'item_id' => 28396,
    'icon' => 'etc_bm_lure_box_i00',
    'name' => '',
    'additionalname' => '',
    'description' => '',
    'is_trade' => 1,
    'is_drop' => 1,
    'is_destruct' => 1,
    'crystal_type' => 'none',
    'consume_type' => 'consume_type_stackable',
  ],
  28397 => 
  [
    'item_id' => 28397,
    'icon' => '',
    'name' => '',
    'additionalname' => '',
    'description' => '',
    'is_trade' => 0,
    'is_drop' => 0,
    'is_destruct' => 0,
    'crystal_type' => '',
    'consume_type' => 'consume_type_normal',
  ],
  28398 => 
  [
    'item_id' => 28398,
    'icon' => 'etc_box_of_adventure_2_i00',
    'name' => '',
    'additionalname' => '',
    'description' => '',
    'is_trade' => 0,
    'is_drop' => 0,
    'is_destruct' => 1,
    'crystal_type' => 'none',
    'consume_type' => 'consume_type_normal',
  ],
  28399 => 
  [
    'item_id' => 28399,
    'icon' => 'etc_box_of_adventure_3_i00',
    'name' => '',
    'additionalname' => '',
    'description' => '',
    'is_trade' => 0,
    'is_drop' => 0,
    'is_destruct' => 1,
    'crystal_type' => 'none',
    'consume_type' => 'consume_type_normal',
  ],
];