<?php return [
  28900 => 
  [
    'item_id' => 28900,
    'icon' => 'g_bm_sag_agathion_charm',
    'name' => 'Agathion Charm: Sagittarius',
    'additionalname' => 'Lv. 12',
    'description' => 'Activates the power of Agathion Sagittarius. Can be upgraded up to Lv. 12 through compounding with Starlight Jar. Also can be enchanted to +10 by using Book of Growth.Primary skill: Archers Call Lv. 12. Enables various additional skills when upgraded.Equipping it in the main slot summons the agathion and activates its primary and secondary skills. Equipping in an additional slot activates only secondary skills.Note!1. Compounding the charm resets its enchant value.2. If Agathion Cancer is also equipped, only its secondary skills will be active.',
    'is_trade' => 0,
    'is_drop' => 0,
    'is_destruct' => 1,
    'crystal_type' => 'none',
    'consume_type' => 'consume_type_normal',
  ],
  28901 => 
  [
    'item_id' => 28901,
    'icon' => 'g_bm_can_agathion_charm',
    'name' => 'Agathion Charm: Cancer',
    'additionalname' => 'Lv. 1',
    'description' => 'Activates the power of Agathion Cancer. Can be upgraded up to Lv. 12 through compounding with Starlight Jar. Also can be enchanted to +10 by using Book of Growth.Primary skill: Exoskeletal Shield Lv. 1. Enables various additional skills when upgraded.Equipping it in the main slot summons the agathion and activates its primary and secondary skills. Equipping in an additional slot activates only secondary skills.Note!1. Compounding the charm resets its enchant value.2. If Agathion Taurus is also equipped, only its secondary skills will be active.',
    'is_trade' => 0,
    'is_drop' => 0,
    'is_destruct' => 1,
    'crystal_type' => 'none',
    'consume_type' => 'consume_type_normal',
  ],
  28902 => 
  [
    'item_id' => 28902,
    'icon' => 'g_bm_can_agathion_charm',
    'name' => 'Agathion Charm: Cancer',
    'additionalname' => 'Lv. 2',
    'description' => 'Activates the power of Agathion Cancer. Can be upgraded up to Lv. 12 through compounding with Starlight Jar. Also can be enchanted to +10 by using Book of Growth.Primary skill: Exoskeletal Shield Lv. 2. Enables various additional skills when upgraded.Equipping it in the main slot summons the agathion and activates its primary and secondary skills. Equipping in an additional slot activates only secondary skills.Note!1. Compounding the charm resets its enchant value.2. If Agathion Taurus is also equipped, only its secondary skills will be active.',
    'is_trade' => 0,
    'is_drop' => 0,
    'is_destruct' => 1,
    'crystal_type' => 'none',
    'consume_type' => 'consume_type_normal',
  ],
  28903 => 
  [
    'item_id' => 28903,
    'icon' => 'g_bm_can_agathion_charm',
    'name' => 'Agathion Charm: Cancer',
    'additionalname' => 'Lv. 3',
    'description' => 'Activates the power of Agathion Cancer. Can be upgraded up to Lv. 12 through compounding with Starlight Jar. Also can be enchanted to +10 by using Book of Growth.Primary skill: Exoskeletal Shield Lv. 3. Enables various additional skills when upgraded.Equipping it in the main slot summons the agathion and activates its primary and secondary skills. Equipping in an additional slot activates only secondary skills.Note!1. Compounding the charm resets its enchant value.2. If Agathion Taurus is also equipped, only its secondary skills will be active.',
    'is_trade' => 0,
    'is_drop' => 0,
    'is_destruct' => 1,
    'crystal_type' => 'none',
    'consume_type' => 'consume_type_normal',
  ],
  28904 => 
  [
    'item_id' => 28904,
    'icon' => 'g_bm_can_agathion_charm',
    'name' => 'Agathion Charm: Cancer',
    'additionalname' => 'Lv. 4',
    'description' => 'Activates the power of Agathion Cancer. Can be upgraded up to Lv. 12 through compounding with Starlight Jar. Also can be enchanted to +10 by using Book of Growth.Primary skill: Exoskeletal Shield Lv. 4. Enables various additional skills when upgraded.Equipping it in the main slot summons the agathion and activates its primary and secondary skills. Equipping in an additional slot activates only secondary skills.Note!1. Compounding the charm resets its enchant value.2. If Agathion Taurus is also equipped, only its secondary skills will be active.',
    'is_trade' => 0,
    'is_drop' => 0,
    'is_destruct' => 1,
    'crystal_type' => 'none',
    'consume_type' => 'consume_type_normal',
  ],
  28905 => 
  [
    'item_id' => 28905,
    'icon' => 'g_bm_can_agathion_charm',
    'name' => 'Agathion Charm: Cancer',
    'additionalname' => 'Lv. 5',
    'description' => 'Activates the power of Agathion Cancer. Can be upgraded up to Lv. 12 through compounding with Starlight Jar. Also can be enchanted to +10 by using Book of Growth.Primary skill: Exoskeletal Shield Lv. 5. Enables various additional skills when upgraded.Equipping it in the main slot summons the agathion and activates its primary and secondary skills. Equipping in an additional slot activates only secondary skills.Note!1. Compounding the charm resets its enchant value.2. If Agathion Taurus is also equipped, only its secondary skills will be active.',
    'is_trade' => 0,
    'is_drop' => 0,
    'is_destruct' => 1,
    'crystal_type' => 'none',
    'consume_type' => 'consume_type_normal',
  ],
  28906 => 
  [
    'item_id' => 28906,
    'icon' => 'g_bm_can_agathion_charm',
    'name' => 'Agathion Charm: Cancer',
    'additionalname' => 'Lv. 6',
    'description' => 'Activates the power of Agathion Cancer. Can be upgraded up to Lv. 12 through compounding with Starlight Jar. Also can be enchanted to +10 by using Book of Growth.Primary skill: Exoskeletal Shield Lv. 6. Enables various additional skills when upgraded.Equipping it in the main slot summons the agathion and activates its primary and secondary skills. Equipping in an additional slot activates only secondary skills.Note!1. Compounding the charm resets its enchant value.2. If Agathion Taurus is also equipped, only its secondary skills will be active.',
    'is_trade' => 0,
    'is_drop' => 0,
    'is_destruct' => 1,
    'crystal_type' => 'none',
    'consume_type' => 'consume_type_normal',
  ],
  28907 => 
  [
    'item_id' => 28907,
    'icon' => 'g_bm_can_agathion_charm',
    'name' => 'Agathion Charm: Cancer',
    'additionalname' => 'Lv. 7',
    'description' => 'Activates the power of Agathion Cancer. Can be upgraded up to Lv. 12 through compounding with Starlight Jar. Also can be enchanted to +10 by using Book of Growth.Primary skill: Exoskeletal Shield Lv. 7. Enables various additional skills when upgraded.Equipping it in the main slot summons the agathion and activates its primary and secondary skills. Equipping in an additional slot activates only secondary skills.Note!1. Compounding the charm resets its enchant value.2. If Agathion Taurus is also equipped, only its secondary skills will be active.',
    'is_trade' => 0,
    'is_drop' => 0,
    'is_destruct' => 1,
    'crystal_type' => 'none',
    'consume_type' => 'consume_type_normal',
  ],
  28908 => 
  [
    'item_id' => 28908,
    'icon' => 'g_bm_can_agathion_charm',
    'name' => 'Agathion Charm: Cancer',
    'additionalname' => 'Lv. 8',
    'description' => 'Activates the power of Agathion Cancer. Can be upgraded up to Lv. 12 through compounding with Starlight Jar. Also can be enchanted to +10 by using Book of Growth.Primary skill: Exoskeletal Shield Lv. 8. Enables various additional skills when upgraded.Equipping it in the main slot summons the agathion and activates its primary and secondary skills. Equipping in an additional slot activates only secondary skills.Note!1. Compounding the charm resets its enchant value.2. If Agathion Taurus is also equipped, only its secondary skills will be active.',
    'is_trade' => 0,
    'is_drop' => 0,
    'is_destruct' => 1,
    'crystal_type' => 'none',
    'consume_type' => 'consume_type_normal',
  ],
  28909 => 
  [
    'item_id' => 28909,
    'icon' => 'g_bm_can_agathion_charm',
    'name' => 'Agathion Charm: Cancer',
    'additionalname' => 'Lv. 9',
    'description' => 'Activates the power of Agathion Cancer. Can be upgraded up to Lv. 12 through compounding with Starlight Jar. Also can be enchanted to +10 by using Book of Growth.Primary skill: Exoskeletal Shield Lv. 9. Enables various additional skills when upgraded.Equipping it in the main slot summons the agathion and activates its primary and secondary skills. Equipping in an additional slot activates only secondary skills.Note!1. Compounding the charm resets its enchant value.2. If Agathion Taurus is also equipped, only its secondary skills will be active.',
    'is_trade' => 0,
    'is_drop' => 0,
    'is_destruct' => 1,
    'crystal_type' => 'none',
    'consume_type' => 'consume_type_normal',
  ],
  28910 => 
  [
    'item_id' => 28910,
    'icon' => 'g_bm_can_agathion_charm',
    'name' => 'Agathion Charm: Cancer',
    'additionalname' => 'Lv. 10',
    'description' => 'Activates the power of Agathion Cancer. Can be upgraded up to Lv. 12 through compounding with Starlight Jar. Also can be enchanted to +10 by using Book of Growth.Primary skill: Exoskeletal Shield Lv. 10. Enables various additional skills when upgraded.Equipping it in the main slot summons the agathion and activates its primary and secondary skills. Equipping in an additional slot activates only secondary skills.Note!1. Compounding the charm resets its enchant value.2. If Agathion Taurus is also equipped, only its secondary skills will be active.',
    'is_trade' => 0,
    'is_drop' => 0,
    'is_destruct' => 1,
    'crystal_type' => 'none',
    'consume_type' => 'consume_type_normal',
  ],
  28911 => 
  [
    'item_id' => 28911,
    'icon' => 'g_bm_can_agathion_charm',
    'name' => 'Agathion Charm: Cancer',
    'additionalname' => 'Lv. 11',
    'description' => 'Activates the power of Agathion Cancer. Can be upgraded up to Lv. 12 through compounding with Starlight Jar. Also can be enchanted to +10 by using Book of Growth.Primary skill: Exoskeletal Shield Lv. 11. Enables various additional skills when upgraded.Equipping it in the main slot summons the agathion and activates its primary and secondary skills. Equipping in an additional slot activates only secondary skills.Note!1. Compounding the charm resets its enchant value.2. If Agathion Taurus is also equipped, only its secondary skills will be active.',
    'is_trade' => 0,
    'is_drop' => 0,
    'is_destruct' => 1,
    'crystal_type' => 'none',
    'consume_type' => 'consume_type_normal',
  ],
  28912 => 
  [
    'item_id' => 28912,
    'icon' => 'g_bm_can_agathion_charm',
    'name' => 'Agathion Charm: Cancer',
    'additionalname' => 'Lv. 12',
    'description' => 'Activates the power of Agathion Cancer. Can be upgraded up to Lv. 12 through compounding with Starlight Jar. Also can be enchanted to +10 by using Book of Growth.Primary skill: Exoskeletal Shield Lv. 12. Enables various additional skills when upgraded.Equipping it in the main slot summons the agathion and activates its primary and secondary skills. Equipping in an additional slot activates only secondary skills.Note!1. Compounding the charm resets its enchant value.2. If Agathion Taurus is also equipped, only its secondary skills will be active.',
    'is_trade' => 0,
    'is_drop' => 0,
    'is_destruct' => 1,
    'crystal_type' => 'none',
    'consume_type' => 'consume_type_normal',
  ],
  28913 => 
  [
    'item_id' => 28913,
    'icon' => 'g_bm_virgo_agathion_charm',
    'name' => 'Agathion Charm: Twinkling Virgo',
    'additionalname' => 'Lv. 1',
    'description' => 'Activates the power of Agathion Virgo. Can be upgraded up to Lv. 12 through compounding with Starlight Jar. Also can be enchanted to +10 by using Book of Growth.Primary skill: Healing Light Lv. 1. Enables various additional skills when upgraded.Equipping it in the main slot summons the agathion and activates its primary and secondary skills. Equipping in an additional slot activates only secondary skills.Note!1. Compounding the charm resets its enchant value.2. If Agathion Pisces is also equipped, only its secondary skills will be active.',
    'is_trade' => 0,
    'is_drop' => 0,
    'is_destruct' => 1,
    'crystal_type' => 'none',
    'consume_type' => 'consume_type_normal',
  ],
  28914 => 
  [
    'item_id' => 28914,
    'icon' => 'g_bm_virgo_agathion_charm',
    'name' => 'Agathion Charm: Twinkling Virgo',
    'additionalname' => 'Lv. 2',
    'description' => 'Activates the power of Agathion Virgo. Can be upgraded up to Lv. 12 through compounding with Starlight Jar. Also can be enchanted to +10 by using Book of Growth.Primary skill: Healing Light Lv. 2. Enables various additional skills when upgraded.Equipping it in the main slot summons the agathion and activates its primary and secondary skills. Equipping in an additional slot activates only secondary skills.Note!1. Compounding the charm resets its enchant value.2. If Agathion Pisces is also equipped, only its secondary skills will be active.',
    'is_trade' => 0,
    'is_drop' => 0,
    'is_destruct' => 1,
    'crystal_type' => 'none',
    'consume_type' => 'consume_type_normal',
  ],
  28915 => 
  [
    'item_id' => 28915,
    'icon' => 'g_bm_virgo_agathion_charm',
    'name' => 'Agathion Charm: Twinkling Virgo',
    'additionalname' => 'Lv. 3',
    'description' => 'Activates the power of Agathion Virgo. Can be upgraded up to Lv. 12 through compounding with Starlight Jar. Also can be enchanted to +10 by using Book of Growth.Primary skill: Healing Light Lv. 3. Enables various additional skills when upgraded.Equipping it in the main slot summons the agathion and activates its primary and secondary skills. Equipping in an additional slot activates only secondary skills.Note!1. Compounding the charm resets its enchant value.2. If Agathion Pisces is also equipped, only its secondary skills will be active.',
    'is_trade' => 0,
    'is_drop' => 0,
    'is_destruct' => 1,
    'crystal_type' => 'none',
    'consume_type' => 'consume_type_normal',
  ],
  28916 => 
  [
    'item_id' => 28916,
    'icon' => 'g_bm_virgo_agathion_charm',
    'name' => 'Agathion Charm: Twinkling Virgo',
    'additionalname' => 'Lv. 4',
    'description' => 'Activates the power of Agathion Virgo. Can be upgraded up to Lv. 12 through compounding with Starlight Jar. Also can be enchanted to +10 by using Book of Growth.Primary skill: Healing Light Lv. 4. Enables various additional skills when upgraded.Equipping it in the main slot summons the agathion and activates its primary and secondary skills. Equipping in an additional slot activates only secondary skills.Note!1. Compounding the charm resets its enchant value.2. If Agathion Pisces is also equipped, only its secondary skills will be active.',
    'is_trade' => 0,
    'is_drop' => 0,
    'is_destruct' => 1,
    'crystal_type' => 'none',
    'consume_type' => 'consume_type_normal',
  ],
  28917 => 
  [
    'item_id' => 28917,
    'icon' => 'g_bm_virgo_agathion_charm',
    'name' => 'Agathion Charm: Twinkling Virgo',
    'additionalname' => 'Lv. 5',
    'description' => 'Activates the power of Agathion Virgo. Can be upgraded up to Lv. 12 through compounding with Starlight Jar. Also can be enchanted to +10 by using Book of Growth.Primary skill: Healing Light Lv. 5. Enables various additional skills when upgraded.Equipping it in the main slot summons the agathion and activates its primary and secondary skills. Equipping in an additional slot activates only secondary skills.Note!1. Compounding the charm resets its enchant value.2. If Agathion Pisces is also equipped, only its secondary skills will be active.',
    'is_trade' => 0,
    'is_drop' => 0,
    'is_destruct' => 1,
    'crystal_type' => 'none',
    'consume_type' => 'consume_type_normal',
  ],
  28918 => 
  [
    'item_id' => 28918,
    'icon' => 'g_bm_virgo_agathion_charm',
    'name' => 'Agathion Charm: Twinkling Virgo',
    'additionalname' => 'Lv. 6',
    'description' => 'Activates the power of Agathion Virgo. Can be upgraded up to Lv. 12 through compounding with Starlight Jar. Also can be enchanted to +10 by using Book of Growth.Primary skill: Healing Light Lv. 6. Enables various additional skills when upgraded.Equipping it in the main slot summons the agathion and activates its primary and secondary skills. Equipping in an additional slot activates only secondary skills.Note!1. Compounding the charm resets its enchant value.2. If Agathion Pisces is also equipped, only its secondary skills will be active.',
    'is_trade' => 0,
    'is_drop' => 0,
    'is_destruct' => 1,
    'crystal_type' => 'none',
    'consume_type' => 'consume_type_normal',
  ],
  28919 => 
  [
    'item_id' => 28919,
    'icon' => 'g_bm_virgo_agathion_charm',
    'name' => 'Agathion Charm: Twinkling Virgo',
    'additionalname' => 'Lv. 7',
    'description' => 'Activates the power of Agathion Virgo. Can be upgraded up to Lv. 12 through compounding with Starlight Jar. Also can be enchanted to +10 by using Book of Growth.Primary skill: Healing Light Lv. 7. Enables various additional skills when upgraded.Equipping it in the main slot summons the agathion and activates its primary and secondary skills. Equipping in an additional slot activates only secondary skills.Note!1. Compounding the charm resets its enchant value.2. If Agathion Pisces is also equipped, only its secondary skills will be active.',
    'is_trade' => 0,
    'is_drop' => 0,
    'is_destruct' => 1,
    'crystal_type' => 'none',
    'consume_type' => 'consume_type_normal',
  ],
  28920 => 
  [
    'item_id' => 28920,
    'icon' => 'g_bm_virgo_agathion_charm',
    'name' => 'Agathion Charm: Twinkling Virgo',
    'additionalname' => 'Lv. 8',
    'description' => 'Activates the power of Agathion Virgo. Can be upgraded up to Lv. 12 through compounding with Starlight Jar. Also can be enchanted to +10 by using Book of Growth.Primary skill: Healing Light Lv. 8. Enables various additional skills when upgraded.Equipping it in the main slot summons the agathion and activates its primary and secondary skills. Equipping in an additional slot activates only secondary skills.Note!1. Compounding the charm resets its enchant value.2. If Agathion Pisces is also equipped, only its secondary skills will be active.',
    'is_trade' => 0,
    'is_drop' => 0,
    'is_destruct' => 1,
    'crystal_type' => 'none',
    'consume_type' => 'consume_type_normal',
  ],
  28921 => 
  [
    'item_id' => 28921,
    'icon' => 'g_bm_virgo_agathion_charm',
    'name' => 'Agathion Charm: Twinkling Virgo',
    'additionalname' => 'Lv. 9',
    'description' => 'Activates the power of Agathion Virgo. Can be upgraded up to Lv. 12 through compounding with Starlight Jar. Also can be enchanted to +10 by using Book of Growth.Primary skill: Healing Light Lv. 9. Enables various additional skills when upgraded.Equipping it in the main slot summons the agathion and activates its primary and secondary skills. Equipping in an additional slot activates only secondary skills.Note!1. Compounding the charm resets its enchant value.2. If Agathion Pisces is also equipped, only its secondary skills will be active.',
    'is_trade' => 0,
    'is_drop' => 0,
    'is_destruct' => 1,
    'crystal_type' => 'none',
    'consume_type' => 'consume_type_normal',
  ],
  28922 => 
  [
    'item_id' => 28922,
    'icon' => 'g_bm_virgo_agathion_charm',
    'name' => 'Agathion Charm: Twinkling Virgo',
    'additionalname' => 'Lv. 10',
    'description' => 'Activates the power of Agathion Virgo. Can be upgraded up to Lv. 12 through compounding with Starlight Jar. Also can be enchanted to +10 by using Book of Growth.Primary skill: Healing Light Lv. 10. Enables various additional skills when upgraded.Equipping it in the main slot summons the agathion and activates its primary and secondary skills. Equipping in an additional slot activates only secondary skills.Note!1. Compounding the charm resets its enchant value.2. If Agathion Pisces is also equipped, only its secondary skills will be active.',
    'is_trade' => 0,
    'is_drop' => 0,
    'is_destruct' => 1,
    'crystal_type' => 'none',
    'consume_type' => 'consume_type_normal',
  ],
  28923 => 
  [
    'item_id' => 28923,
    'icon' => 'g_bm_virgo_agathion_charm',
    'name' => 'Agathion Charm: Twinkling Virgo',
    'additionalname' => 'Lv. 11',
    'description' => 'Activates the power of Agathion Virgo. Can be upgraded up to Lv. 12 through compounding with Starlight Jar. Also can be enchanted to +10 by using Book of Growth.Primary skill: Healing Light Lv. 11. Enables various additional skills when upgraded.Equipping it in the main slot summons the agathion and activates its primary and secondary skills. Equipping in an additional slot activates only secondary skills.Note!1. Compounding the charm resets its enchant value.2. If Agathion Pisces is also equipped, only its secondary skills will be active.',
    'is_trade' => 0,
    'is_drop' => 0,
    'is_destruct' => 1,
    'crystal_type' => 'none',
    'consume_type' => 'consume_type_normal',
  ],
  28924 => 
  [
    'item_id' => 28924,
    'icon' => 'g_bm_virgo_agathion_charm',
    'name' => 'Agathion Charm: Twinkling Virgo',
    'additionalname' => 'Lv. 12',
    'description' => 'Activates the power of Agathion Virgo. Can be upgraded up to Lv. 12 through compounding with Starlight Jar. Also can be enchanted to +10 by using Book of Growth.Primary skill: Healing Light Lv. 12. Enables various additional skills when upgraded.Equipping it in the main slot summons the agathion and activates its primary and secondary skills. Equipping in an additional slot activates only secondary skills.Note!1. Compounding the charm resets its enchant value.2. If Agathion Pisces is also equipped, only its secondary skills will be active.',
    'is_trade' => 0,
    'is_drop' => 0,
    'is_destruct' => 1,
    'crystal_type' => 'none',
    'consume_type' => 'consume_type_normal',
  ],
  28925 => 
  [
    'item_id' => 28925,
    'icon' => 'g_bm_capr_agathion_charm',
    'name' => 'Agathion Charm: Twinkling Capricorn',
    'additionalname' => 'Lv. 1',
    'description' => 'Activates the power of Agathion Capricorn. Can be upgraded up to Lv. 12 through compounding with Starlight Jar. Also can be enchanted to +10 by using Book of Growth.Primary skill: Skipping Kid Lv. 1. Enables various additional skills when upgraded.Equipping it in the main slot summons the agathion and activates its primary and secondary skills. Equipping in an additional slot activates only secondary skills.Note!1. Compounding the charm resets its enchant value.2. If Agathion Libra is also equipped, only its secondary skills will be active.',
    'is_trade' => 0,
    'is_drop' => 0,
    'is_destruct' => 1,
    'crystal_type' => 'none',
    'consume_type' => 'consume_type_normal',
  ],
  28926 => 
  [
    'item_id' => 28926,
    'icon' => 'g_bm_capr_agathion_charm',
    'name' => 'Agathion Charm: Twinkling Capricorn',
    'additionalname' => 'Lv. 2',
    'description' => 'Activates the power of Agathion Capricorn. Can be upgraded up to Lv. 12 through compounding with Starlight Jar. Also can be enchanted to +10 by using Book of Growth.Primary skill: Skipping Kid Lv. 2. Enables various additional skills when upgraded.Equipping it in the main slot summons the agathion and activates its primary and secondary skills. Equipping in an additional slot activates only secondary skills.Note!1. Compounding the charm resets its enchant value.2. If Agathion Libra is also equipped, only its secondary skills will be active.',
    'is_trade' => 0,
    'is_drop' => 0,
    'is_destruct' => 1,
    'crystal_type' => 'none',
    'consume_type' => 'consume_type_normal',
  ],
  28927 => 
  [
    'item_id' => 28927,
    'icon' => 'g_bm_capr_agathion_charm',
    'name' => 'Agathion Charm: Twinkling Capricorn',
    'additionalname' => 'Lv. 3',
    'description' => 'Activates the power of Agathion Capricorn. Can be upgraded up to Lv. 12 through compounding with Starlight Jar. Also can be enchanted to +10 by using Book of Growth.Primary skill: Skipping Kid Lv. 3. Enables various additional skills when upgraded.Equipping it in the main slot summons the agathion and activates its primary and secondary skills. Equipping in an additional slot activates only secondary skills.Note!1. Compounding the charm resets its enchant value.2. If Agathion Libra is also equipped, only its secondary skills will be active.',
    'is_trade' => 0,
    'is_drop' => 0,
    'is_destruct' => 1,
    'crystal_type' => 'none',
    'consume_type' => 'consume_type_normal',
  ],
  28928 => 
  [
    'item_id' => 28928,
    'icon' => 'g_bm_capr_agathion_charm',
    'name' => 'Agathion Charm: Twinkling Capricorn',
    'additionalname' => 'Lv. 4',
    'description' => 'Activates the power of Agathion Capricorn. Can be upgraded up to Lv. 12 through compounding with Starlight Jar. Also can be enchanted to +10 by using Book of Growth.Primary skill: Skipping Kid Lv. 4. Enables various additional skills when upgraded.Equipping it in the main slot summons the agathion and activates its primary and secondary skills. Equipping in an additional slot activates only secondary skills.Note!1. Compounding the charm resets its enchant value.2. If Agathion Libra is also equipped, only its secondary skills will be active.',
    'is_trade' => 0,
    'is_drop' => 0,
    'is_destruct' => 1,
    'crystal_type' => 'none',
    'consume_type' => 'consume_type_normal',
  ],
  28929 => 
  [
    'item_id' => 28929,
    'icon' => 'g_bm_capr_agathion_charm',
    'name' => 'Agathion Charm: Twinkling Capricorn',
    'additionalname' => 'Lv. 5',
    'description' => 'Activates the power of Agathion Capricorn. Can be upgraded up to Lv. 12 through compounding with Starlight Jar. Also can be enchanted to +10 by using Book of Growth.Primary skill: Skipping Kid Lv. 5. Enables various additional skills when upgraded.Equipping it in the main slot summons the agathion and activates its primary and secondary skills. Equipping in an additional slot activates only secondary skills.Note!1. Compounding the charm resets its enchant value.2. If Agathion Libra is also equipped, only its secondary skills will be active.',
    'is_trade' => 0,
    'is_drop' => 0,
    'is_destruct' => 1,
    'crystal_type' => 'none',
    'consume_type' => 'consume_type_normal',
  ],
  28930 => 
  [
    'item_id' => 28930,
    'icon' => 'g_bm_capr_agathion_charm',
    'name' => 'Agathion Charm: Twinkling Capricorn',
    'additionalname' => 'Lv. 6',
    'description' => 'Activates the power of Agathion Capricorn. Can be upgraded up to Lv. 12 through compounding with Starlight Jar. Also can be enchanted to +10 by using Book of Growth.Primary skill: Skipping Kid Lv. 6. Enables various additional skills when upgraded.Equipping it in the main slot summons the agathion and activates its primary and secondary skills. Equipping in an additional slot activates only secondary skills.Note!1. Compounding the charm resets its enchant value.2. If Agathion Libra is also equipped, only its secondary skills will be active.',
    'is_trade' => 0,
    'is_drop' => 0,
    'is_destruct' => 1,
    'crystal_type' => 'none',
    'consume_type' => 'consume_type_normal',
  ],
  28931 => 
  [
    'item_id' => 28931,
    'icon' => 'g_bm_capr_agathion_charm',
    'name' => 'Agathion Charm: Twinkling Capricorn',
    'additionalname' => 'Lv. 7',
    'description' => 'Activates the power of Agathion Capricorn. Can be upgraded up to Lv. 12 through compounding with Starlight Jar. Also can be enchanted to +10 by using Book of Growth.Primary skill: Skipping Kid Lv. 7. Enables various additional skills when upgraded.Equipping it in the main slot summons the agathion and activates its primary and secondary skills. Equipping in an additional slot activates only secondary skills.Note!1. Compounding the charm resets its enchant value.2. If Agathion Libra is also equipped, only its secondary skills will be active.',
    'is_trade' => 0,
    'is_drop' => 0,
    'is_destruct' => 1,
    'crystal_type' => 'none',
    'consume_type' => 'consume_type_normal',
  ],
  28932 => 
  [
    'item_id' => 28932,
    'icon' => 'g_bm_capr_agathion_charm',
    'name' => 'Agathion Charm: Twinkling Capricorn',
    'additionalname' => 'Lv. 8',
    'description' => 'Activates the power of Agathion Capricorn. Can be upgraded up to Lv. 12 through compounding with Starlight Jar. Also can be enchanted to +10 by using Book of Growth.Primary skill: Skipping Kid Lv. 8. Enables various additional skills when upgraded.Equipping it in the main slot summons the agathion and activates its primary and secondary skills. Equipping in an additional slot activates only secondary skills.Note!1. Compounding the charm resets its enchant value.2. If Agathion Libra is also equipped, only its secondary skills will be active.',
    'is_trade' => 0,
    'is_drop' => 0,
    'is_destruct' => 1,
    'crystal_type' => 'none',
    'consume_type' => 'consume_type_normal',
  ],
  28933 => 
  [
    'item_id' => 28933,
    'icon' => 'g_bm_capr_agathion_charm',
    'name' => 'Agathion Charm: Twinkling Capricorn',
    'additionalname' => 'Lv. 9',
    'description' => 'Activates the power of Agathion Capricorn. Can be upgraded up to Lv. 12 through compounding with Starlight Jar. Also can be enchanted to +10 by using Book of Growth.Primary skill: Skipping Kid Lv. 9. Enables various additional skills when upgraded.Equipping it in the main slot summons the agathion and activates its primary and secondary skills. Equipping in an additional slot activates only secondary skills.Note!1. Compounding the charm resets its enchant value.2. If Agathion Libra is also equipped, only its secondary skills will be active.',
    'is_trade' => 0,
    'is_drop' => 0,
    'is_destruct' => 1,
    'crystal_type' => 'none',
    'consume_type' => 'consume_type_normal',
  ],
  28934 => 
  [
    'item_id' => 28934,
    'icon' => 'g_bm_capr_agathion_charm',
    'name' => 'Agathion Charm: Twinkling Capricorn',
    'additionalname' => 'Lv. 10',
    'description' => 'Activates the power of Agathion Capricorn. Can be upgraded up to Lv. 12 through compounding with Starlight Jar. Also can be enchanted to +10 by using Book of Growth.Primary skill: Skipping Kid Lv. 10. Enables various additional skills when upgraded.Equipping it in the main slot summons the agathion and activates its primary and secondary skills. Equipping in an additional slot activates only secondary skills.Note!1. Compounding the charm resets its enchant value.2. If Agathion Libra is also equipped, only its secondary skills will be active.',
    'is_trade' => 0,
    'is_drop' => 0,
    'is_destruct' => 1,
    'crystal_type' => 'none',
    'consume_type' => 'consume_type_normal',
  ],
  28935 => 
  [
    'item_id' => 28935,
    'icon' => 'g_bm_capr_agathion_charm',
    'name' => 'Agathion Charm: Twinkling Capricorn',
    'additionalname' => 'Lv. 11',
    'description' => 'Activates the power of Agathion Capricorn. Can be upgraded up to Lv. 12 through compounding with Starlight Jar. Also can be enchanted to +10 by using Book of Growth.Primary skill: Skipping Kid Lv. 11. Enables various additional skills when upgraded.Equipping it in the main slot summons the agathion and activates its primary and secondary skills. Equipping in an additional slot activates only secondary skills.Note!1. Compounding the charm resets its enchant value.2. If Agathion Libra is also equipped, only its secondary skills will be active.',
    'is_trade' => 0,
    'is_drop' => 0,
    'is_destruct' => 1,
    'crystal_type' => 'none',
    'consume_type' => 'consume_type_normal',
  ],
  28936 => 
  [
    'item_id' => 28936,
    'icon' => 'g_bm_capr_agathion_charm',
    'name' => 'Agathion Charm: Twinkling Capricorn',
    'additionalname' => 'Lv. 12',
    'description' => 'Activates the power of Agathion Capricorn. Can be upgraded up to Lv. 12 through compounding with Starlight Jar. Also can be enchanted to +10 by using Book of Growth.Primary skill: Skipping Kid Lv. 12. Enables various additional skills when upgraded.Equipping it in the main slot summons the agathion and activates its primary and secondary skills. Equipping in an additional slot activates only secondary skills.Note!1. Compounding the charm resets its enchant value.2. If Agathion Libra is also equipped, only its secondary skills will be active.',
    'is_trade' => 0,
    'is_drop' => 0,
    'is_destruct' => 1,
    'crystal_type' => 'none',
    'consume_type' => 'consume_type_normal',
  ],
  28937 => 
  [
    'item_id' => 28937,
    'icon' => 'g_bm_lib_agathion_charm',
    'name' => 'Agathion Charm: Twinkling Libra',
    'additionalname' => 'Lv. 1',
    'description' => 'Activates the power of Agathion Libra. Can be upgraded up to Lv. 12 through compounding with Starlight Jar. Also can be enchanted to +10 by using Book of Growth.Primary skill: Scale of Life Lv. 1. Enables various additional skills when upgraded.Equipping it in the main slot summons the agathion and activates its primary and secondary skills. Equipping in an additional slot activates only secondary skills.Note!1. Compounding the charm resets its enchant value.2. If Agathion Capricorn is also equipped, only its secondary skills will be active.',
    'is_trade' => 0,
    'is_drop' => 0,
    'is_destruct' => 1,
    'crystal_type' => 'none',
    'consume_type' => 'consume_type_normal',
  ],
  28938 => 
  [
    'item_id' => 28938,
    'icon' => 'g_bm_lib_agathion_charm',
    'name' => 'Agathion Charm: Twinkling Libra',
    'additionalname' => 'Lv. 2',
    'description' => 'Activates the power of Agathion Libra. Can be upgraded up to Lv. 12 through compounding with Starlight Jar. Also can be enchanted to +10 by using Book of Growth.Primary skill: Scale of Life Lv. 2. Enables various additional skills when upgraded.Equipping it in the main slot summons the agathion and activates its primary and secondary skills. Equipping in an additional slot activates only secondary skills.Note!1. Compounding the charm resets its enchant value.2. If Agathion Capricorn is also equipped, only its secondary skills will be active.',
    'is_trade' => 0,
    'is_drop' => 0,
    'is_destruct' => 1,
    'crystal_type' => 'none',
    'consume_type' => 'consume_type_normal',
  ],
  28939 => 
  [
    'item_id' => 28939,
    'icon' => 'g_bm_lib_agathion_charm',
    'name' => 'Agathion Charm: Twinkling Libra',
    'additionalname' => 'Lv. 3',
    'description' => 'Activates the power of Agathion Libra. Can be upgraded up to Lv. 12 through compounding with Starlight Jar. Also can be enchanted to +10 by using Book of Growth.Primary skill: Scale of Life Lv. 3. Enables various additional skills when upgraded.Equipping it in the main slot summons the agathion and activates its primary and secondary skills. Equipping in an additional slot activates only secondary skills.Note!1. Compounding the charm resets its enchant value.2. If Agathion Capricorn is also equipped, only its secondary skills will be active.',
    'is_trade' => 0,
    'is_drop' => 0,
    'is_destruct' => 1,
    'crystal_type' => 'none',
    'consume_type' => 'consume_type_normal',
  ],
  28940 => 
  [
    'item_id' => 28940,
    'icon' => 'g_bm_lib_agathion_charm',
    'name' => 'Agathion Charm: Twinkling Libra',
    'additionalname' => 'Lv. 4',
    'description' => 'Activates the power of Agathion Libra. Can be upgraded up to Lv. 12 through compounding with Starlight Jar. Also can be enchanted to +10 by using Book of Growth.Primary skill: Scale of Life Lv. 4. Enables various additional skills when upgraded.Equipping it in the main slot summons the agathion and activates its primary and secondary skills. Equipping in an additional slot activates only secondary skills.Note!1. Compounding the charm resets its enchant value.2. If Agathion Capricorn is also equipped, only its secondary skills will be active.',
    'is_trade' => 0,
    'is_drop' => 0,
    'is_destruct' => 1,
    'crystal_type' => 'none',
    'consume_type' => 'consume_type_normal',
  ],
  28941 => 
  [
    'item_id' => 28941,
    'icon' => 'g_bm_lib_agathion_charm',
    'name' => 'Agathion Charm: Twinkling Libra',
    'additionalname' => 'Lv. 5',
    'description' => 'Activates the power of Agathion Libra. Can be upgraded up to Lv. 12 through compounding with Starlight Jar. Also can be enchanted to +10 by using Book of Growth.Primary skill: Scale of Life Lv. 5. Enables various additional skills when upgraded.Equipping it in the main slot summons the agathion and activates its primary and secondary skills. Equipping in an additional slot activates only secondary skills.Note!1. Compounding the charm resets its enchant value.2. If Agathion Capricorn is also equipped, only its secondary skills will be active.',
    'is_trade' => 0,
    'is_drop' => 0,
    'is_destruct' => 1,
    'crystal_type' => 'none',
    'consume_type' => 'consume_type_normal',
  ],
  28942 => 
  [
    'item_id' => 28942,
    'icon' => 'g_bm_lib_agathion_charm',
    'name' => 'Agathion Charm: Twinkling Libra',
    'additionalname' => 'Lv. 6',
    'description' => 'Activates the power of Agathion Libra. Can be upgraded up to Lv. 12 through compounding with Starlight Jar. Also can be enchanted to +10 by using Book of Growth.Primary skill: Scale of Life Lv. 6. Enables various additional skills when upgraded.Equipping it in the main slot summons the agathion and activates its primary and secondary skills. Equipping in an additional slot activates only secondary skills.Note!1. Compounding the charm resets its enchant value.2. If Agathion Capricorn is also equipped, only its secondary skills will be active.',
    'is_trade' => 0,
    'is_drop' => 0,
    'is_destruct' => 1,
    'crystal_type' => 'none',
    'consume_type' => 'consume_type_normal',
  ],
  28943 => 
  [
    'item_id' => 28943,
    'icon' => 'g_bm_lib_agathion_charm',
    'name' => 'Agathion Charm: Twinkling Libra',
    'additionalname' => 'Lv. 7',
    'description' => 'Activates the power of Agathion Libra. Can be upgraded up to Lv. 12 through compounding with Starlight Jar. Also can be enchanted to +10 by using Book of Growth.Primary skill: Scale of Life Lv. 7. Enables various additional skills when upgraded.Equipping it in the main slot summons the agathion and activates its primary and secondary skills. Equipping in an additional slot activates only secondary skills.Note!1. Compounding the charm resets its enchant value.2. If Agathion Capricorn is also equipped, only its secondary skills will be active.',
    'is_trade' => 0,
    'is_drop' => 0,
    'is_destruct' => 1,
    'crystal_type' => 'none',
    'consume_type' => 'consume_type_normal',
  ],
  28944 => 
  [
    'item_id' => 28944,
    'icon' => 'g_bm_lib_agathion_charm',
    'name' => 'Agathion Charm: Twinkling Libra',
    'additionalname' => 'Lv. 8',
    'description' => 'Activates the power of Agathion Libra. Can be upgraded up to Lv. 12 through compounding with Starlight Jar. Also can be enchanted to +10 by using Book of Growth.Primary skill: Scale of Life Lv. 8. Enables various additional skills when upgraded.Equipping it in the main slot summons the agathion and activates its primary and secondary skills. Equipping in an additional slot activates only secondary skills.Note!1. Compounding the charm resets its enchant value.2. If Agathion Capricorn is also equipped, only its secondary skills will be active.',
    'is_trade' => 0,
    'is_drop' => 0,
    'is_destruct' => 1,
    'crystal_type' => 'none',
    'consume_type' => 'consume_type_normal',
  ],
  28945 => 
  [
    'item_id' => 28945,
    'icon' => 'g_bm_lib_agathion_charm',
    'name' => 'Agathion Charm: Twinkling Libra',
    'additionalname' => 'Lv. 9',
    'description' => 'Activates the power of Agathion Libra. Can be upgraded up to Lv. 12 through compounding with Starlight Jar. Also can be enchanted to +10 by using Book of Growth.Primary skill: Scale of Life Lv. 9. Enables various additional skills when upgraded.Equipping it in the main slot summons the agathion and activates its primary and secondary skills. Equipping in an additional slot activates only secondary skills.Note!1. Compounding the charm resets its enchant value.2. If Agathion Capricorn is also equipped, only its secondary skills will be active.',
    'is_trade' => 0,
    'is_drop' => 0,
    'is_destruct' => 1,
    'crystal_type' => 'none',
    'consume_type' => 'consume_type_normal',
  ],
  28946 => 
  [
    'item_id' => 28946,
    'icon' => 'g_bm_lib_agathion_charm',
    'name' => 'Agathion Charm: Twinkling Libra',
    'additionalname' => 'Lv. 10',
    'description' => 'Activates the power of Agathion Libra. Can be upgraded up to Lv. 12 through compounding with Starlight Jar. Also can be enchanted to +10 by using Book of Growth.Primary skill: Scale of Life Lv. 10. Enables various additional skills when upgraded.Equipping it in the main slot summons the agathion and activates its primary and secondary skills. Equipping in an additional slot activates only secondary skills.Note!1. Compounding the charm resets its enchant value.2. If Agathion Capricorn is also equipped, only its secondary skills will be active.',
    'is_trade' => 0,
    'is_drop' => 0,
    'is_destruct' => 1,
    'crystal_type' => 'none',
    'consume_type' => 'consume_type_normal',
  ],
  28947 => 
  [
    'item_id' => 28947,
    'icon' => 'g_bm_lib_agathion_charm',
    'name' => 'Agathion Charm: Twinkling Libra',
    'additionalname' => 'Lv. 11',
    'description' => 'Activates the power of Agathion Libra. Can be upgraded up to Lv. 12 through compounding with Starlight Jar. Also can be enchanted to +10 by using Book of Growth.Primary skill: Scale of Life Lv. 11. Enables various additional skills when upgraded.Equipping it in the main slot summons the agathion and activates its primary and secondary skills. Equipping in an additional slot activates only secondary skills.Note!1. Compounding the charm resets its enchant value.2. If Agathion Capricorn is also equipped, only its secondary skills will be active.',
    'is_trade' => 0,
    'is_drop' => 0,
    'is_destruct' => 1,
    'crystal_type' => 'none',
    'consume_type' => 'consume_type_normal',
  ],
  28948 => 
  [
    'item_id' => 28948,
    'icon' => 'g_bm_lib_agathion_charm',
    'name' => 'Agathion Charm: Twinkling Libra',
    'additionalname' => 'Lv. 12',
    'description' => 'Activates the power of Agathion Libra. Can be upgraded up to Lv. 12 through compounding with Starlight Jar. Also can be enchanted to +10 by using Book of Growth.Primary skill: Scale of Life Lv. 12. Enables various additional skills when upgraded.Equipping it in the main slot summons the agathion and activates its primary and secondary skills. Equipping in an additional slot activates only secondary skills.Note!1. Compounding the charm resets its enchant value.2. If Agathion Capricorn is also equipped, only its secondary skills will be active.',
    'is_trade' => 0,
    'is_drop' => 0,
    'is_destruct' => 1,
    'crystal_type' => 'none',
    'consume_type' => 'consume_type_normal',
  ],
  28949 => 
  [
    'item_id' => 28949,
    'icon' => 'g_bm_aries_agathion_charm',
    'name' => 'Agathion Charm: Twinkling Aries',
    'additionalname' => 'Lv. 1',
    'description' => 'Activates the power of Agathion Aries. Can be upgraded up to Lv. 12 through compounding with Starlight Jar. Also can be enchanted to +10 by using Book of Growth.Primary skill: Rocky Camouflage Lv. 1. Enables various additional skills when upgraded.Equipping it in the main slot summons the agathion and activates its primary and secondary skills. Equipping in an additional slot activates only secondary skills.Note!1. Compounding the charm resets its enchant value.2. If Agathion Aries is also equipped, only its secondary skills will be active.',
    'is_trade' => 0,
    'is_drop' => 0,
    'is_destruct' => 1,
    'crystal_type' => 'none',
    'consume_type' => 'consume_type_normal',
  ],
  28950 => 
  [
    'item_id' => 28950,
    'icon' => 'g_bm_aries_agathion_charm',
    'name' => 'Agathion Charm: Twinkling Aries',
    'additionalname' => 'Lv. 2',
    'description' => 'Activates the power of Agathion Aries. Can be upgraded up to Lv. 12 through compounding with Starlight Jar. Also can be enchanted to +10 by using Book of Growth.Primary skill: Rocky Camouflage Lv. 2. Enables various additional skills when upgraded.Equipping it in the main slot summons the agathion and activates its primary and secondary skills. Equipping in an additional slot activates only secondary skills.Note!1. Compounding the charm resets its enchant value.2. If Agathion Aries is also equipped, only its secondary skills will be active.',
    'is_trade' => 0,
    'is_drop' => 0,
    'is_destruct' => 1,
    'crystal_type' => 'none',
    'consume_type' => 'consume_type_normal',
  ],
  28951 => 
  [
    'item_id' => 28951,
    'icon' => 'g_bm_aries_agathion_charm',
    'name' => 'Agathion Charm: Twinkling Aries',
    'additionalname' => 'Lv. 3',
    'description' => 'Activates the power of Agathion Aries. Can be upgraded up to Lv. 12 through compounding with Starlight Jar. Also can be enchanted to +10 by using Book of Growth.Primary skill: Rocky Camouflage Lv. 3. Enables various additional skills when upgraded.Equipping it in the main slot summons the agathion and activates its primary and secondary skills. Equipping in an additional slot activates only secondary skills.Note!1. Compounding the charm resets its enchant value.2. If Agathion Aries is also equipped, only its secondary skills will be active.',
    'is_trade' => 0,
    'is_drop' => 0,
    'is_destruct' => 1,
    'crystal_type' => 'none',
    'consume_type' => 'consume_type_normal',
  ],
  28952 => 
  [
    'item_id' => 28952,
    'icon' => 'g_bm_aries_agathion_charm',
    'name' => 'Agathion Charm: Twinkling Aries',
    'additionalname' => 'Lv. 4',
    'description' => 'Activates the power of Agathion Aries. Can be upgraded up to Lv. 12 through compounding with Starlight Jar. Also can be enchanted to +10 by using Book of Growth.Primary skill: Rocky Camouflage Lv. 4. Enables various additional skills when upgraded.Equipping it in the main slot summons the agathion and activates its primary and secondary skills. Equipping in an additional slot activates only secondary skills.Note!1. Compounding the charm resets its enchant value.2. If Agathion Aries is also equipped, only its secondary skills will be active.',
    'is_trade' => 0,
    'is_drop' => 0,
    'is_destruct' => 1,
    'crystal_type' => 'none',
    'consume_type' => 'consume_type_normal',
  ],
  28953 => 
  [
    'item_id' => 28953,
    'icon' => 'g_bm_aries_agathion_charm',
    'name' => 'Agathion Charm: Twinkling Aries',
    'additionalname' => 'Lv. 5',
    'description' => 'Activates the power of Agathion Aries. Can be upgraded up to Lv. 12 through compounding with Starlight Jar. Also can be enchanted to +10 by using Book of Growth.Primary skill: Rocky Camouflage Lv. 5. Enables various additional skills when upgraded.Equipping it in the main slot summons the agathion and activates its primary and secondary skills. Equipping in an additional slot activates only secondary skills.Note!1. Compounding the charm resets its enchant value.2. If Agathion Aries is also equipped, only its secondary skills will be active.',
    'is_trade' => 0,
    'is_drop' => 0,
    'is_destruct' => 1,
    'crystal_type' => 'none',
    'consume_type' => 'consume_type_normal',
  ],
  28954 => 
  [
    'item_id' => 28954,
    'icon' => 'g_bm_aries_agathion_charm',
    'name' => 'Agathion Charm: Twinkling Aries',
    'additionalname' => 'Lv. 6',
    'description' => 'Activates the power of Agathion Aries. Can be upgraded up to Lv. 12 through compounding with Starlight Jar. Also can be enchanted to +10 by using Book of Growth.Primary skill: Rocky Camouflage Lv. 6. Enables various additional skills when upgraded.Equipping it in the main slot summons the agathion and activates its primary and secondary skills. Equipping in an additional slot activates only secondary skills.Note!1. Compounding the charm resets its enchant value.2. If Agathion Aries is also equipped, only its secondary skills will be active.',
    'is_trade' => 0,
    'is_drop' => 0,
    'is_destruct' => 1,
    'crystal_type' => 'none',
    'consume_type' => 'consume_type_normal',
  ],
  28955 => 
  [
    'item_id' => 28955,
    'icon' => 'g_bm_aries_agathion_charm',
    'name' => 'Agathion Charm: Twinkling Aries',
    'additionalname' => 'Lv. 7',
    'description' => 'Activates the power of Agathion Aries. Can be upgraded up to Lv. 12 through compounding with Starlight Jar. Also can be enchanted to +10 by using Book of Growth.Primary skill: Rocky Camouflage Lv. 7. Enables various additional skills when upgraded.Equipping it in the main slot summons the agathion and activates its primary and secondary skills. Equipping in an additional slot activates only secondary skills.Note!1. Compounding the charm resets its enchant value.2. If Agathion Aries is also equipped, only its secondary skills will be active.',
    'is_trade' => 0,
    'is_drop' => 0,
    'is_destruct' => 1,
    'crystal_type' => 'none',
    'consume_type' => 'consume_type_normal',
  ],
  28956 => 
  [
    'item_id' => 28956,
    'icon' => 'g_bm_aries_agathion_charm',
    'name' => 'Agathion Charm: Twinkling Aries',
    'additionalname' => 'Lv. 8',
    'description' => 'Activates the power of Agathion Aries. Can be upgraded up to Lv. 12 through compounding with Starlight Jar. Also can be enchanted to +10 by using Book of Growth.Primary skill: Rocky Camouflage Lv. 8. Enables various additional skills when upgraded.Equipping it in the main slot summons the agathion and activates its primary and secondary skills. Equipping in an additional slot activates only secondary skills.Note!1. Compounding the charm resets its enchant value.2. If Agathion Aries is also equipped, only its secondary skills will be active.',
    'is_trade' => 0,
    'is_drop' => 0,
    'is_destruct' => 1,
    'crystal_type' => 'none',
    'consume_type' => 'consume_type_normal',
  ],
  28957 => 
  [
    'item_id' => 28957,
    'icon' => 'g_bm_aries_agathion_charm',
    'name' => 'Agathion Charm: Twinkling Aries',
    'additionalname' => 'Lv. 9',
    'description' => 'Activates the power of Agathion Aries. Can be upgraded up to Lv. 12 through compounding with Starlight Jar. Also can be enchanted to +10 by using Book of Growth.Primary skill: Rocky Camouflage Lv. 9. Enables various additional skills when upgraded.Equipping it in the main slot summons the agathion and activates its primary and secondary skills. Equipping in an additional slot activates only secondary skills.Note!1. Compounding the charm resets its enchant value.2. If Agathion Aries is also equipped, only its secondary skills will be active.',
    'is_trade' => 0,
    'is_drop' => 0,
    'is_destruct' => 1,
    'crystal_type' => 'none',
    'consume_type' => 'consume_type_normal',
  ],
  28958 => 
  [
    'item_id' => 28958,
    'icon' => 'g_bm_aries_agathion_charm',
    'name' => 'Agathion Charm: Twinkling Aries',
    'additionalname' => 'Lv. 10',
    'description' => 'Activates the power of Agathion Aries. Can be upgraded up to Lv. 12 through compounding with Starlight Jar. Also can be enchanted to +10 by using Book of Growth.Primary skill: Rocky Camouflage Lv. 10. Enables various additional skills when upgraded.Equipping it in the main slot summons the agathion and activates its primary and secondary skills. Equipping in an additional slot activates only secondary skills.Note!1. Compounding the charm resets its enchant value.2. If Agathion Aries is also equipped, only its secondary skills will be active.',
    'is_trade' => 0,
    'is_drop' => 0,
    'is_destruct' => 1,
    'crystal_type' => 'none',
    'consume_type' => 'consume_type_normal',
  ],
  28959 => 
  [
    'item_id' => 28959,
    'icon' => 'g_bm_aries_agathion_charm',
    'name' => 'Agathion Charm: Twinkling Aries',
    'additionalname' => 'Lv. 11',
    'description' => 'Activates the power of Agathion Aries. Can be upgraded up to Lv. 12 through compounding with Starlight Jar. Also can be enchanted to +10 by using Book of Growth.Primary skill: Rocky Camouflage Lv. 11. Enables various additional skills when upgraded.Equipping it in the main slot summons the agathion and activates its primary and secondary skills. Equipping in an additional slot activates only secondary skills.Note!1. Compounding the charm resets its enchant value.2. If Agathion Aries is also equipped, only its secondary skills will be active.',
    'is_trade' => 0,
    'is_drop' => 0,
    'is_destruct' => 1,
    'crystal_type' => 'none',
    'consume_type' => 'consume_type_normal',
  ],
  28960 => 
  [
    'item_id' => 28960,
    'icon' => 'g_bm_aries_agathion_charm',
    'name' => 'Agathion Charm: Twinkling Aries',
    'additionalname' => 'Lv. 12',
    'description' => 'Activates the power of Agathion Aries. Can be upgraded up to Lv. 12 through compounding with Starlight Jar. Also can be enchanted to +10 by using Book of Growth.Primary skill: Rocky Camouflage Lv. 12. Enables various additional skills when upgraded.Equipping it in the main slot summons the agathion and activates its primary and secondary skills. Equipping in an additional slot activates only secondary skills.Note!1. Compounding the charm resets its enchant value.2. If Agathion Aries is also equipped, only its secondary skills will be active.',
    'is_trade' => 0,
    'is_drop' => 0,
    'is_destruct' => 1,
    'crystal_type' => 'none',
    'consume_type' => 'consume_type_normal',
  ],
  28961 => 
  [
    'item_id' => 28961,
    'icon' => 'g_bm_tau_agathion_charm',
    'name' => 'Agathion Charm: Twinkling Taurus',
    'additionalname' => 'Lv. 1',
    'description' => 'Activates the power of Agathion Taurus. Can be upgraded up to Lv. 12 through compounding with Starlight Jar. Also can be enchanted to +10 by using Book of Growth.Primary skill: Battle Rhapsody Lv. 1. Enables various additional skills when upgraded.Equipping it in the main slot summons the agathion and activates its primary and secondary skills. Equipping in an additional slot activates only secondary skills.Note!1. Compounding the charm resets its enchant value.2. If Agathion Sagittarius is also equipped, only its secondary skills will be active.',
    'is_trade' => 0,
    'is_drop' => 0,
    'is_destruct' => 1,
    'crystal_type' => 'none',
    'consume_type' => 'consume_type_normal',
  ],
  28962 => 
  [
    'item_id' => 28962,
    'icon' => 'g_bm_tau_agathion_charm',
    'name' => 'Agathion Charm: Twinkling Taurus',
    'additionalname' => 'Lv. 2',
    'description' => 'Activates the power of Agathion Taurus. Can be upgraded up to Lv. 12 through compounding with Starlight Jar. Also can be enchanted to +10 by using Book of Growth.Primary skill: Battle Rhapsody Lv. 2. Enables various additional skills when upgraded.Equipping it in the main slot summons the agathion and activates its primary and secondary skills. Equipping in an additional slot activates only secondary skills.Note!1. Compounding the charm resets its enchant value.2. If Agathion Sagittarius is also equipped, only its secondary skills will be active.',
    'is_trade' => 0,
    'is_drop' => 0,
    'is_destruct' => 1,
    'crystal_type' => 'none',
    'consume_type' => 'consume_type_normal',
  ],
  28963 => 
  [
    'item_id' => 28963,
    'icon' => 'g_bm_tau_agathion_charm',
    'name' => 'Agathion Charm: Twinkling Taurus',
    'additionalname' => 'Lv. 3',
    'description' => 'Activates the power of Agathion Taurus. Can be upgraded up to Lv. 12 through compounding with Starlight Jar. Also can be enchanted to +10 by using Book of Growth.Primary skill: Battle Rhapsody Lv. 3. Enables various additional skills when upgraded.Equipping it in the main slot summons the agathion and activates its primary and secondary skills. Equipping in an additional slot activates only secondary skills.Note!1. Compounding the charm resets its enchant value.2. If Agathion Sagittarius is also equipped, only its secondary skills will be active.',
    'is_trade' => 0,
    'is_drop' => 0,
    'is_destruct' => 1,
    'crystal_type' => 'none',
    'consume_type' => 'consume_type_normal',
  ],
  28964 => 
  [
    'item_id' => 28964,
    'icon' => 'g_bm_tau_agathion_charm',
    'name' => 'Agathion Charm: Twinkling Taurus',
    'additionalname' => 'Lv. 4',
    'description' => 'Activates the power of Agathion Taurus. Can be upgraded up to Lv. 12 through compounding with Starlight Jar. Also can be enchanted to +10 by using Book of Growth.Primary skill: Battle Rhapsody Lv. 4. Enables various additional skills when upgraded.Equipping it in the main slot summons the agathion and activates its primary and secondary skills. Equipping in an additional slot activates only secondary skills.Note!1. Compounding the charm resets its enchant value.2. If Agathion Sagittarius is also equipped, only its secondary skills will be active.',
    'is_trade' => 0,
    'is_drop' => 0,
    'is_destruct' => 1,
    'crystal_type' => 'none',
    'consume_type' => 'consume_type_normal',
  ],
  28965 => 
  [
    'item_id' => 28965,
    'icon' => 'g_bm_tau_agathion_charm',
    'name' => 'Agathion Charm: Twinkling Taurus',
    'additionalname' => 'Lv. 5',
    'description' => 'Activates the power of Agathion Taurus. Can be upgraded up to Lv. 12 through compounding with Starlight Jar. Also can be enchanted to +10 by using Book of Growth.Primary skill: Battle Rhapsody Lv. 5. Enables various additional skills when upgraded.Equipping it in the main slot summons the agathion and activates its primary and secondary skills. Equipping in an additional slot activates only secondary skills.Note!1. Compounding the charm resets its enchant value.2. If Agathion Sagittarius is also equipped, only its secondary skills will be active.',
    'is_trade' => 0,
    'is_drop' => 0,
    'is_destruct' => 1,
    'crystal_type' => 'none',
    'consume_type' => 'consume_type_normal',
  ],
  28966 => 
  [
    'item_id' => 28966,
    'icon' => 'g_bm_tau_agathion_charm',
    'name' => 'Agathion Charm: Twinkling Taurus',
    'additionalname' => 'Lv. 6',
    'description' => 'Activates the power of Agathion Taurus. Can be upgraded up to Lv. 12 through compounding with Starlight Jar. Also can be enchanted to +10 by using Book of Growth.Primary skill: Battle Rhapsody Lv. 6. Enables various additional skills when upgraded.Equipping it in the main slot summons the agathion and activates its primary and secondary skills. Equipping in an additional slot activates only secondary skills.Note!1. Compounding the charm resets its enchant value.2. If Agathion Sagittarius is also equipped, only its secondary skills will be active.',
    'is_trade' => 0,
    'is_drop' => 0,
    'is_destruct' => 1,
    'crystal_type' => 'none',
    'consume_type' => 'consume_type_normal',
  ],
  28967 => 
  [
    'item_id' => 28967,
    'icon' => 'g_bm_tau_agathion_charm',
    'name' => 'Agathion Charm: Twinkling Taurus',
    'additionalname' => 'Lv. 7',
    'description' => 'Activates the power of Agathion Taurus. Can be upgraded up to Lv. 12 through compounding with Starlight Jar. Also can be enchanted to +10 by using Book of Growth.Primary skill: Battle Rhapsody Lv. 7. Enables various additional skills when upgraded.Equipping it in the main slot summons the agathion and activates its primary and secondary skills. Equipping in an additional slot activates only secondary skills.Note!1. Compounding the charm resets its enchant value.2. If Agathion Sagittarius is also equipped, only its secondary skills will be active.',
    'is_trade' => 0,
    'is_drop' => 0,
    'is_destruct' => 1,
    'crystal_type' => 'none',
    'consume_type' => 'consume_type_normal',
  ],
  28968 => 
  [
    'item_id' => 28968,
    'icon' => 'g_bm_tau_agathion_charm',
    'name' => 'Agathion Charm: Twinkling Taurus',
    'additionalname' => 'Lv. 8',
    'description' => 'Activates the power of Agathion Taurus. Can be upgraded up to Lv. 12 through compounding with Starlight Jar. Also can be enchanted to +10 by using Book of Growth.Primary skill: Battle Rhapsody Lv. 8. Enables various additional skills when upgraded.Equipping it in the main slot summons the agathion and activates its primary and secondary skills. Equipping in an additional slot activates only secondary skills.Note!1. Compounding the charm resets its enchant value.2. If Agathion Sagittarius is also equipped, only its secondary skills will be active.',
    'is_trade' => 0,
    'is_drop' => 0,
    'is_destruct' => 1,
    'crystal_type' => 'none',
    'consume_type' => 'consume_type_normal',
  ],
  28969 => 
  [
    'item_id' => 28969,
    'icon' => 'g_bm_tau_agathion_charm',
    'name' => 'Agathion Charm: Twinkling Taurus',
    'additionalname' => 'Lv. 9',
    'description' => 'Activates the power of Agathion Taurus. Can be upgraded up to Lv. 12 through compounding with Starlight Jar. Also can be enchanted to +10 by using Book of Growth.Primary skill: Battle Rhapsody Lv. 9. Enables various additional skills when upgraded.Equipping it in the main slot summons the agathion and activates its primary and secondary skills. Equipping in an additional slot activates only secondary skills.Note!1. Compounding the charm resets its enchant value.2. If Agathion Sagittarius is also equipped, only its secondary skills will be active.',
    'is_trade' => 0,
    'is_drop' => 0,
    'is_destruct' => 1,
    'crystal_type' => 'none',
    'consume_type' => 'consume_type_normal',
  ],
  28970 => 
  [
    'item_id' => 28970,
    'icon' => 'g_bm_tau_agathion_charm',
    'name' => 'Agathion Charm: Twinkling Taurus',
    'additionalname' => 'Lv. 10',
    'description' => 'Activates the power of Agathion Taurus. Can be upgraded up to Lv. 12 through compounding with Starlight Jar. Also can be enchanted to +10 by using Book of Growth.Primary skill: Battle Rhapsody Lv. 10. Enables various additional skills when upgraded.Equipping it in the main slot summons the agathion and activates its primary and secondary skills. Equipping in an additional slot activates only secondary skills.Note!1. Compounding the charm resets its enchant value.2. If Agathion Sagittarius is also equipped, only its secondary skills will be active.',
    'is_trade' => 0,
    'is_drop' => 0,
    'is_destruct' => 1,
    'crystal_type' => 'none',
    'consume_type' => 'consume_type_normal',
  ],
  28971 => 
  [
    'item_id' => 28971,
    'icon' => 'g_bm_tau_agathion_charm',
    'name' => 'Agathion Charm: Twinkling Taurus',
    'additionalname' => 'Lv. 11',
    'description' => 'Activates the power of Agathion Taurus. Can be upgraded up to Lv. 12 through compounding with Starlight Jar. Also can be enchanted to +10 by using Book of Growth.Primary skill: Battle Rhapsody Lv. 11. Enables various additional skills when upgraded.Equipping it in the main slot summons the agathion and activates its primary and secondary skills. Equipping in an additional slot activates only secondary skills.Note!1. Compounding the charm resets its enchant value.2. If Agathion Sagittarius is also equipped, only its secondary skills will be active.',
    'is_trade' => 0,
    'is_drop' => 0,
    'is_destruct' => 1,
    'crystal_type' => 'none',
    'consume_type' => 'consume_type_normal',
  ],
  28972 => 
  [
    'item_id' => 28972,
    'icon' => 'g_bm_tau_agathion_charm',
    'name' => 'Agathion Charm: Twinkling Taurus',
    'additionalname' => 'Lv. 12',
    'description' => 'Activates the power of Agathion Taurus. Can be upgraded up to Lv. 12 through compounding with Starlight Jar. Also can be enchanted to +10 by using Book of Growth.Primary skill: Battle Rhapsody Lv. 12. Enables various additional skills when upgraded.Equipping it in the main slot summons the agathion and activates its primary and secondary skills. Equipping in an additional slot activates only secondary skills.Note!1. Compounding the charm resets its enchant value.2. If Agathion Sagittarius is also equipped, only its secondary skills will be active.',
    'is_trade' => 0,
    'is_drop' => 0,
    'is_destruct' => 1,
    'crystal_type' => 'none',
    'consume_type' => 'consume_type_normal',
  ],
  28973 => 
  [
    'item_id' => 28973,
    'icon' => 'g_bm_leo_agathion_charm',
    'name' => 'Agathion Charm: Twinkling Leo',
    'additionalname' => 'Lv. 1',
    'description' => 'Activates the power of Agathion Leo. Can be upgraded up to Lv. 12 through compounding with Starlight Jar. Also can be enchanted to +10 by using Book of Growth.Primary skill: Nemean Lions Defense Lv. 1. Enables various additional skills when upgraded.Equipping it in the main slot summons the agathion and activates its primary and secondary skills. Equipping in an additional slot activates only secondary skills.Note!1. Compounding the charm resets its enchant value.2. If Agathion Virgo is also equipped, only its secondary skills will be active.',
    'is_trade' => 0,
    'is_drop' => 0,
    'is_destruct' => 1,
    'crystal_type' => 'none',
    'consume_type' => 'consume_type_normal',
  ],
  28974 => 
  [
    'item_id' => 28974,
    'icon' => 'g_bm_leo_agathion_charm',
    'name' => 'Agathion Charm: Twinkling Leo',
    'additionalname' => 'Lv. 2',
    'description' => 'Activates the power of Agathion Leo. Can be upgraded up to Lv. 12 through compounding with Starlight Jar. Also can be enchanted to +10 by using Book of Growth.Primary skill: Nemean Lions Defense Lv. 2. Enables various additional skills when upgraded.Equipping it in the main slot summons the agathion and activates its primary and secondary skills. Equipping in an additional slot activates only secondary skills.Note!1. Compounding the charm resets its enchant value.2. If Agathion Virgo is also equipped, only its secondary skills will be active.',
    'is_trade' => 0,
    'is_drop' => 0,
    'is_destruct' => 1,
    'crystal_type' => 'none',
    'consume_type' => 'consume_type_normal',
  ],
  28975 => 
  [
    'item_id' => 28975,
    'icon' => 'g_bm_leo_agathion_charm',
    'name' => 'Agathion Charm: Twinkling Leo',
    'additionalname' => 'Lv. 3',
    'description' => 'Activates the power of Agathion Leo. Can be upgraded up to Lv. 12 through compounding with Starlight Jar. Also can be enchanted to +10 by using Book of Growth.Primary skill: Nemean Lions Defense Lv. 3. Enables various additional skills when upgraded.Equipping it in the main slot summons the agathion and activates its primary and secondary skills. Equipping in an additional slot activates only secondary skills.Note!1. Compounding the charm resets its enchant value.2. If Agathion Virgo is also equipped, only its secondary skills will be active.',
    'is_trade' => 0,
    'is_drop' => 0,
    'is_destruct' => 1,
    'crystal_type' => 'none',
    'consume_type' => 'consume_type_normal',
  ],
  28976 => 
  [
    'item_id' => 28976,
    'icon' => 'g_bm_leo_agathion_charm',
    'name' => 'Agathion Charm: Twinkling Leo',
    'additionalname' => 'Lv. 4',
    'description' => 'Activates the power of Agathion Leo. Can be upgraded up to Lv. 12 through compounding with Starlight Jar. Also can be enchanted to +10 by using Book of Growth.Primary skill: Nemean Lions Defense Lv. 4. Enables various additional skills when upgraded.Equipping it in the main slot summons the agathion and activates its primary and secondary skills. Equipping in an additional slot activates only secondary skills.Note!1. Compounding the charm resets its enchant value.2. If Agathion Virgo is also equipped, only its secondary skills will be active.',
    'is_trade' => 0,
    'is_drop' => 0,
    'is_destruct' => 1,
    'crystal_type' => 'none',
    'consume_type' => 'consume_type_normal',
  ],
  28977 => 
  [
    'item_id' => 28977,
    'icon' => 'g_bm_leo_agathion_charm',
    'name' => 'Agathion Charm: Twinkling Leo',
    'additionalname' => 'Lv. 5',
    'description' => 'Activates the power of Agathion Leo. Can be upgraded up to Lv. 12 through compounding with Starlight Jar. Also can be enchanted to +10 by using Book of Growth.Primary skill: Nemean Lions Defense Lv. 5. Enables various additional skills when upgraded.Equipping it in the main slot summons the agathion and activates its primary and secondary skills. Equipping in an additional slot activates only secondary skills.Note!1. Compounding the charm resets its enchant value.2. If Agathion Virgo is also equipped, only its secondary skills will be active.',
    'is_trade' => 0,
    'is_drop' => 0,
    'is_destruct' => 1,
    'crystal_type' => 'none',
    'consume_type' => 'consume_type_normal',
  ],
  28978 => 
  [
    'item_id' => 28978,
    'icon' => 'g_bm_leo_agathion_charm',
    'name' => 'Agathion Charm: Twinkling Leo',
    'additionalname' => 'Lv. 6',
    'description' => 'Activates the power of Agathion Leo. Can be upgraded up to Lv. 12 through compounding with Starlight Jar. Also can be enchanted to +10 by using Book of Growth.Primary skill: Nemean Lions Defense Lv. 6. Enables various additional skills when upgraded.Equipping it in the main slot summons the agathion and activates its primary and secondary skills. Equipping in an additional slot activates only secondary skills.Note!1. Compounding the charm resets its enchant value.2. If Agathion Virgo is also equipped, only its secondary skills will be active.',
    'is_trade' => 0,
    'is_drop' => 0,
    'is_destruct' => 1,
    'crystal_type' => 'none',
    'consume_type' => 'consume_type_normal',
  ],
  28979 => 
  [
    'item_id' => 28979,
    'icon' => 'g_bm_leo_agathion_charm',
    'name' => 'Agathion Charm: Twinkling Leo',
    'additionalname' => 'Lv. 7',
    'description' => 'Activates the power of Agathion Leo. Can be upgraded up to Lv. 12 through compounding with Starlight Jar. Also can be enchanted to +10 by using Book of Growth.Primary skill: Nemean Lions Defense Lv. 7. Enables various additional skills when upgraded.Equipping it in the main slot summons the agathion and activates its primary and secondary skills. Equipping in an additional slot activates only secondary skills.Note!1. Compounding the charm resets its enchant value.2. If Agathion Virgo is also equipped, only its secondary skills will be active.',
    'is_trade' => 0,
    'is_drop' => 0,
    'is_destruct' => 1,
    'crystal_type' => 'none',
    'consume_type' => 'consume_type_normal',
  ],
  28980 => 
  [
    'item_id' => 28980,
    'icon' => 'g_bm_leo_agathion_charm',
    'name' => 'Agathion Charm: Twinkling Leo',
    'additionalname' => 'Lv. 8',
    'description' => 'Activates the power of Agathion Leo. Can be upgraded up to Lv. 12 through compounding with Starlight Jar. Also can be enchanted to +10 by using Book of Growth.Primary skill: Nemean Lions Defense Lv. 8. Enables various additional skills when upgraded.Equipping it in the main slot summons the agathion and activates its primary and secondary skills. Equipping in an additional slot activates only secondary skills.Note!1. Compounding the charm resets its enchant value.2. If Agathion Virgo is also equipped, only its secondary skills will be active.',
    'is_trade' => 0,
    'is_drop' => 0,
    'is_destruct' => 1,
    'crystal_type' => 'none',
    'consume_type' => 'consume_type_normal',
  ],
  28981 => 
  [
    'item_id' => 28981,
    'icon' => 'g_bm_leo_agathion_charm',
    'name' => 'Agathion Charm: Twinkling Leo',
    'additionalname' => 'Lv. 9',
    'description' => 'Activates the power of Agathion Leo. Can be upgraded up to Lv. 12 through compounding with Starlight Jar. Also can be enchanted to +10 by using Book of Growth.Primary skill: Nemean Lions Defense Lv. 9. Enables various additional skills when upgraded.Equipping it in the main slot summons the agathion and activates its primary and secondary skills. Equipping in an additional slot activates only secondary skills.Note!1. Compounding the charm resets its enchant value.2. If Agathion Virgo is also equipped, only its secondary skills will be active.',
    'is_trade' => 0,
    'is_drop' => 0,
    'is_destruct' => 1,
    'crystal_type' => 'none',
    'consume_type' => 'consume_type_normal',
  ],
  28982 => 
  [
    'item_id' => 28982,
    'icon' => 'g_bm_leo_agathion_charm',
    'name' => 'Agathion Charm: Twinkling Leo',
    'additionalname' => 'Lv. 10',
    'description' => 'Activates the power of Agathion Leo. Can be upgraded up to Lv. 12 through compounding with Starlight Jar. Also can be enchanted to +10 by using Book of Growth.Primary skill: Nemean Lions Defense Lv. 10. Enables various additional skills when upgraded.Equipping it in the main slot summons the agathion and activates its primary and secondary skills. Equipping in an additional slot activates only secondary skills.Note!1. Compounding the charm resets its enchant value.2. If Agathion Virgo is also equipped, only its secondary skills will be active.',
    'is_trade' => 0,
    'is_drop' => 0,
    'is_destruct' => 1,
    'crystal_type' => 'none',
    'consume_type' => 'consume_type_normal',
  ],
  28983 => 
  [
    'item_id' => 28983,
    'icon' => 'g_bm_leo_agathion_charm',
    'name' => 'Agathion Charm: Twinkling Leo',
    'additionalname' => 'Lv. 11',
    'description' => 'Activates the power of Agathion Leo. Can be upgraded up to Lv. 12 through compounding with Starlight Jar. Also can be enchanted to +10 by using Book of Growth.Primary skill: Nemean Lions Defense Lv. 11. Enables various additional skills when upgraded.Equipping it in the main slot summons the agathion and activates its primary and secondary skills. Equipping in an additional slot activates only secondary skills.Note!1. Compounding the charm resets its enchant value.2. If Agathion Virgo is also equipped, only its secondary skills will be active.',
    'is_trade' => 0,
    'is_drop' => 0,
    'is_destruct' => 1,
    'crystal_type' => 'none',
    'consume_type' => 'consume_type_normal',
  ],
  28984 => 
  [
    'item_id' => 28984,
    'icon' => 'g_bm_leo_agathion_charm',
    'name' => 'Agathion Charm: Twinkling Leo',
    'additionalname' => 'Lv. 12',
    'description' => 'Activates the power of Agathion Leo. Can be upgraded up to Lv. 12 through compounding with Starlight Jar. Also can be enchanted to +10 by using Book of Growth.Primary skill: Nemean Lions Defense Lv. 12. Enables various additional skills when upgraded.Equipping it in the main slot summons the agathion and activates its primary and secondary skills. Equipping in an additional slot activates only secondary skills.Note!1. Compounding the charm resets its enchant value.2. If Agathion Virgo is also equipped, only its secondary skills will be active.',
    'is_trade' => 0,
    'is_drop' => 0,
    'is_destruct' => 1,
    'crystal_type' => 'none',
    'consume_type' => 'consume_type_normal',
  ],
  28985 => 
  [
    'item_id' => 28985,
    'icon' => 'g_bm_gem_agathion_charm',
    'name' => 'Agathion Charm: Twinkling Gemini',
    'additionalname' => 'Lv. 1',
    'description' => 'Activates the power of Agathion Gemini. Can be upgraded up to Lv. 12 through compounding with Starlight Jar. Also can be enchanted to +10 by using Book of Growth.Primary skill: Bountiful Resurrection Lv. 1. Enables various additional skills when upgraded.Equipping it in the main slot summons the agathion and activates its primary and secondary skills. Equipping in an additional slot activates only secondary skills.Note!1. Compounding the charm resets its enchant value.2. If Agathion Gemini is also equipped, only its secondary skills will be active.',
    'is_trade' => 0,
    'is_drop' => 0,
    'is_destruct' => 1,
    'crystal_type' => 'none',
    'consume_type' => 'consume_type_normal',
  ],
  28986 => 
  [
    'item_id' => 28986,
    'icon' => 'g_bm_gem_agathion_charm',
    'name' => 'Agathion Charm: Twinkling Gemini',
    'additionalname' => 'Lv. 2',
    'description' => 'Activates the power of Agathion Gemini. Can be upgraded up to Lv. 12 through compounding with Starlight Jar. Also can be enchanted to +10 by using Book of Growth.Primary skill: Bountiful Resurrection Lv. 2. Enables various additional skills when upgraded.Equipping it in the main slot summons the agathion and activates its primary and secondary skills. Equipping in an additional slot activates only secondary skills.Note!1. Compounding the charm resets its enchant value.2. If Agathion Gemini is also equipped, only its secondary skills will be active.',
    'is_trade' => 0,
    'is_drop' => 0,
    'is_destruct' => 1,
    'crystal_type' => 'none',
    'consume_type' => 'consume_type_normal',
  ],
  28987 => 
  [
    'item_id' => 28987,
    'icon' => 'g_bm_gem_agathion_charm',
    'name' => 'Agathion Charm: Twinkling Gemini',
    'additionalname' => 'Lv. 3',
    'description' => 'Activates the power of Agathion Gemini. Can be upgraded up to Lv. 12 through compounding with Starlight Jar. Also can be enchanted to +10 by using Book of Growth.Primary skill: Bountiful Resurrection Lv. 3. Enables various additional skills when upgraded.Equipping it in the main slot summons the agathion and activates its primary and secondary skills. Equipping in an additional slot activates only secondary skills.Note!1. Compounding the charm resets its enchant value.2. If Agathion Gemini is also equipped, only its secondary skills will be active.',
    'is_trade' => 0,
    'is_drop' => 0,
    'is_destruct' => 1,
    'crystal_type' => 'none',
    'consume_type' => 'consume_type_normal',
  ],
  28988 => 
  [
    'item_id' => 28988,
    'icon' => 'g_bm_gem_agathion_charm',
    'name' => 'Agathion Charm: Twinkling Gemini',
    'additionalname' => 'Lv. 4',
    'description' => 'Activates the power of Agathion Gemini. Can be upgraded up to Lv. 12 through compounding with Starlight Jar. Also can be enchanted to +10 by using Book of Growth.Primary skill: Bountiful Resurrection Lv. 4. Enables various additional skills when upgraded.Equipping it in the main slot summons the agathion and activates its primary and secondary skills. Equipping in an additional slot activates only secondary skills.Note!1. Compounding the charm resets its enchant value.2. If Agathion Gemini is also equipped, only its secondary skills will be active.',
    'is_trade' => 0,
    'is_drop' => 0,
    'is_destruct' => 1,
    'crystal_type' => 'none',
    'consume_type' => 'consume_type_normal',
  ],
  28989 => 
  [
    'item_id' => 28989,
    'icon' => 'g_bm_gem_agathion_charm',
    'name' => 'Agathion Charm: Twinkling Gemini',
    'additionalname' => 'Lv. 5',
    'description' => 'Activates the power of Agathion Gemini. Can be upgraded up to Lv. 12 through compounding with Starlight Jar. Also can be enchanted to +10 by using Book of Growth.Primary skill: Bountiful Resurrection Lv. 5. Enables various additional skills when upgraded.Equipping it in the main slot summons the agathion and activates its primary and secondary skills. Equipping in an additional slot activates only secondary skills.Note!1. Compounding the charm resets its enchant value.2. If Agathion Gemini is also equipped, only its secondary skills will be active.',
    'is_trade' => 0,
    'is_drop' => 0,
    'is_destruct' => 1,
    'crystal_type' => 'none',
    'consume_type' => 'consume_type_normal',
  ],
  28990 => 
  [
    'item_id' => 28990,
    'icon' => 'g_bm_gem_agathion_charm',
    'name' => 'Agathion Charm: Twinkling Gemini',
    'additionalname' => 'Lv. 6',
    'description' => 'Activates the power of Agathion Gemini. Can be upgraded up to Lv. 12 through compounding with Starlight Jar. Also can be enchanted to +10 by using Book of Growth.Primary skill: Bountiful Resurrection Lv. 6. Enables various additional skills when upgraded.Equipping it in the main slot summons the agathion and activates its primary and secondary skills. Equipping in an additional slot activates only secondary skills.Note!1. Compounding the charm resets its enchant value.2. If Agathion Gemini is also equipped, only its secondary skills will be active.',
    'is_trade' => 0,
    'is_drop' => 0,
    'is_destruct' => 1,
    'crystal_type' => 'none',
    'consume_type' => 'consume_type_normal',
  ],
  28991 => 
  [
    'item_id' => 28991,
    'icon' => 'g_bm_gem_agathion_charm',
    'name' => 'Agathion Charm: Twinkling Gemini',
    'additionalname' => 'Lv. 7',
    'description' => 'Activates the power of Agathion Gemini. Can be upgraded up to Lv. 12 through compounding with Starlight Jar. Also can be enchanted to +10 by using Book of Growth.Primary skill: Bountiful Resurrection Lv. 7. Enables various additional skills when upgraded.Equipping it in the main slot summons the agathion and activates its primary and secondary skills. Equipping in an additional slot activates only secondary skills.Note!1. Compounding the charm resets its enchant value.2. If Agathion Gemini is also equipped, only its secondary skills will be active.',
    'is_trade' => 0,
    'is_drop' => 0,
    'is_destruct' => 1,
    'crystal_type' => 'none',
    'consume_type' => 'consume_type_normal',
  ],
  28992 => 
  [
    'item_id' => 28992,
    'icon' => 'g_bm_gem_agathion_charm',
    'name' => 'Agathion Charm: Twinkling Gemini',
    'additionalname' => 'Lv. 8',
    'description' => 'Activates the power of Agathion Gemini. Can be upgraded up to Lv. 12 through compounding with Starlight Jar. Also can be enchanted to +10 by using Book of Growth.Primary skill: Bountiful Resurrection Lv. 8. Enables various additional skills when upgraded.Equipping it in the main slot summons the agathion and activates its primary and secondary skills. Equipping in an additional slot activates only secondary skills.Note!1. Compounding the charm resets its enchant value.2. If Agathion Gemini is also equipped, only its secondary skills will be active.',
    'is_trade' => 0,
    'is_drop' => 0,
    'is_destruct' => 1,
    'crystal_type' => 'none',
    'consume_type' => 'consume_type_normal',
  ],
  28993 => 
  [
    'item_id' => 28993,
    'icon' => 'g_bm_gem_agathion_charm',
    'name' => 'Agathion Charm: Twinkling Gemini',
    'additionalname' => 'Lv. 9',
    'description' => 'Activates the power of Agathion Gemini. Can be upgraded up to Lv. 12 through compounding with Starlight Jar. Also can be enchanted to +10 by using Book of Growth.Primary skill: Bountiful Resurrection Lv. 9. Enables various additional skills when upgraded.Equipping it in the main slot summons the agathion and activates its primary and secondary skills. Equipping in an additional slot activates only secondary skills.Note!1. Compounding the charm resets its enchant value.2. If Agathion Gemini is also equipped, only its secondary skills will be active.',
    'is_trade' => 0,
    'is_drop' => 0,
    'is_destruct' => 1,
    'crystal_type' => 'none',
    'consume_type' => 'consume_type_normal',
  ],
  28994 => 
  [
    'item_id' => 28994,
    'icon' => 'g_bm_gem_agathion_charm',
    'name' => 'Agathion Charm: Twinkling Gemini',
    'additionalname' => 'Lv. 10',
    'description' => 'Activates the power of Agathion Gemini. Can be upgraded up to Lv. 12 through compounding with Starlight Jar. Also can be enchanted to +10 by using Book of Growth.Primary skill: Bountiful Resurrection Lv. 10. Enables various additional skills when upgraded.Equipping it in the main slot summons the agathion and activates its primary and secondary skills. Equipping in an additional slot activates only secondary skills.Note!1. Compounding the charm resets its enchant value.2. If Agathion Gemini is also equipped, only its secondary skills will be active.',
    'is_trade' => 0,
    'is_drop' => 0,
    'is_destruct' => 1,
    'crystal_type' => 'none',
    'consume_type' => 'consume_type_normal',
  ],
  28995 => 
  [
    'item_id' => 28995,
    'icon' => 'g_bm_gem_agathion_charm',
    'name' => 'Agathion Charm: Twinkling Gemini',
    'additionalname' => 'Lv. 11',
    'description' => 'Activates the power of Agathion Gemini. Can be upgraded up to Lv. 12 through compounding with Starlight Jar. Also can be enchanted to +10 by using Book of Growth.Primary skill: Bountiful Resurrection Lv. 11. Enables various additional skills when upgraded.Equipping it in the main slot summons the agathion and activates its primary and secondary skills. Equipping in an additional slot activates only secondary skills.Note!1. Compounding the charm resets its enchant value.2. If Agathion Gemini is also equipped, only its secondary skills will be active.',
    'is_trade' => 0,
    'is_drop' => 0,
    'is_destruct' => 1,
    'crystal_type' => 'none',
    'consume_type' => 'consume_type_normal',
  ],
  28996 => 
  [
    'item_id' => 28996,
    'icon' => 'g_bm_gem_agathion_charm',
    'name' => 'Agathion Charm: Twinkling Gemini',
    'additionalname' => 'Lv. 12',
    'description' => 'Activates the power of Agathion Gemini. Can be upgraded up to Lv. 12 through compounding with Starlight Jar. Also can be enchanted to +10 by using Book of Growth.Primary skill: Bountiful Resurrection Lv. 12. Enables various additional skills when upgraded.Equipping it in the main slot summons the agathion and activates its primary and secondary skills. Equipping in an additional slot activates only secondary skills.Note!1. Compounding the charm resets its enchant value.2. If Agathion Gemini is also equipped, only its secondary skills will be active.',
    'is_trade' => 0,
    'is_drop' => 0,
    'is_destruct' => 1,
    'crystal_type' => 'none',
    'consume_type' => 'consume_type_normal',
  ],
  28997 => 
  [
    'item_id' => 28997,
    'icon' => 'g_bm_sco_agathion_charm',
    'name' => 'Agathion Charm: Twinkling Scorpio',
    'additionalname' => 'Lv. 1',
    'description' => 'Activates the power of Agathion Scorpio. Can be upgraded up to Lv. 12 through compounding with Starlight Jar. Also can be enchanted to +10 by using Book of Growth.Primary skill: Scorpions Mass Exile Lv. 1. Enables various additional skills when upgraded.Equipping it in the main slot summons the agathion and activates its primary and secondary skills. Equipping in an additional slot activates only secondary skills.Note!1. Compounding the charm resets its enchant value.2. If Agathion Scorpio is also equipped, only its secondary skills will be active.',
    'is_trade' => 0,
    'is_drop' => 0,
    'is_destruct' => 1,
    'crystal_type' => 'none',
    'consume_type' => 'consume_type_normal',
  ],
  28998 => 
  [
    'item_id' => 28998,
    'icon' => 'g_bm_sco_agathion_charm',
    'name' => 'Agathion Charm: Twinkling Scorpio',
    'additionalname' => 'Lv. 2',
    'description' => 'Activates the power of Agathion Scorpio. Can be upgraded up to Lv. 12 through compounding with Starlight Jar. Also can be enchanted to +10 by using Book of Growth.Primary skill: Scorpions Mass Exile Lv. 2. Enables various additional skills when upgraded.Equipping it in the main slot summons the agathion and activates its primary and secondary skills. Equipping in an additional slot activates only secondary skills.Note!1. Compounding the charm resets its enchant value.2. If Agathion Scorpio is also equipped, only its secondary skills will be active.',
    'is_trade' => 0,
    'is_drop' => 0,
    'is_destruct' => 1,
    'crystal_type' => 'none',
    'consume_type' => 'consume_type_normal',
  ],
  28999 => 
  [
    'item_id' => 28999,
    'icon' => 'g_bm_sco_agathion_charm',
    'name' => 'Agathion Charm: Twinkling Scorpio',
    'additionalname' => 'Lv. 3',
    'description' => 'Activates the power of Agathion Scorpio. Can be upgraded up to Lv. 12 through compounding with Starlight Jar. Also can be enchanted to +10 by using Book of Growth.Primary skill: Scorpions Mass Exile Lv. 3. Enables various additional skills when upgraded.Equipping it in the main slot summons the agathion and activates its primary and secondary skills. Equipping in an additional slot activates only secondary skills.Note!1. Compounding the charm resets its enchant value.2. If Agathion Scorpio is also equipped, only its secondary skills will be active.',
    'is_trade' => 0,
    'is_drop' => 0,
    'is_destruct' => 1,
    'crystal_type' => 'none',
    'consume_type' => 'consume_type_normal',
  ],
];