<?php return [
  32900 => 
  [
    'item_id' => 32900,
    'icon' => 'weapon_scallop_jamadhr_i00',
    'name' => 'Scallop Jamadhr of Destiny (Fire]',
    'additionalname' => NULL,
    'description' => 'Scallop Jamadhr of Destiny (Fire] with limited ability enhancement. This item cannot be enhanced except with PA Enchant Scrolls. ',
    'is_trade' => 0,
    'is_drop' => 0,
    'is_destruct' => 1,
    'crystal_type' => 'd',
    'consume_type' => 'consume_type_normal',
  ],
  32901 => 
  [
    'item_id' => 32901,
    'icon' => 'weapon_dual_sword_i00',
    'name' => 'Bastard Sword of Destiny Crimson Sword (Fire]',
    'additionalname' => NULL,
    'description' => 'Bastard Sword Crimson Sword of Destiny (Fire] with limited ability enhancement. This item cannot be enhanced except with PA Enchant Scrolls. ',
    'is_trade' => 0,
    'is_drop' => 0,
    'is_destruct' => 1,
    'crystal_type' => 'd',
    'consume_type' => 'consume_type_normal',
  ],
  32902 => 
  [
    'item_id' => 32902,
    'icon' => 'weapon_mithril_dagger_i00',
    'name' => 'Mithril Dagger of Destiny (Water]',
    'additionalname' => NULL,
    'description' => 'Mithril Dagger of Destiny (Water] with limited ability enhancement. This item cannot be enhanced except with PA Enchant Scrolls. ',
    'is_trade' => 0,
    'is_drop' => 0,
    'is_destruct' => 1,
    'crystal_type' => 'd',
    'consume_type' => 'consume_type_normal',
  ],
  32903 => 
  [
    'item_id' => 32903,
    'icon' => 'weapon_elven_long_sword_i00',
    'name' => 'Elven Long Sword of Destiny (Water]',
    'additionalname' => NULL,
    'description' => 'Elven Long Sword of Destiny (Water] with limited ability enhancement. This item cannot be enhanced except with PA Enchant Scrolls. ',
    'is_trade' => 0,
    'is_drop' => 0,
    'is_destruct' => 1,
    'crystal_type' => 'd',
    'consume_type' => 'consume_type_normal',
  ],
  32904 => 
  [
    'item_id' => 32904,
    'icon' => 'weapon_rapier_i00',
    'name' => 'Grand ?p?e of Destiny (Water]',
    'additionalname' => NULL,
    'description' => 'Grand ?p?e of Destiny (Water], upgrade options are limited. When enchanted to +4 or higher, it has a chance to increase P./ M. Atk., Received Healing, and decrease Skill MP consumption for you and your party members after a critical attack. Can only be enchanted. ',
    'is_trade' => 0,
    'is_drop' => 0,
    'is_destruct' => 1,
    'crystal_type' => 'd',
    'consume_type' => 'consume_type_normal',
  ],
  32905 => 
  [
    'item_id' => 32905,
    'icon' => 'weapon_claymore_i00',
    'name' => 'Claymore of Destiny (Water]',
    'additionalname' => NULL,
    'description' => 'Claymore of Destiny (Water] with limited ability enhancement. This item cannot be enhanced except with PA Enchant Scrolls. ',
    'is_trade' => 0,
    'is_drop' => 0,
    'is_destruct' => 1,
    'crystal_type' => 'd',
    'consume_type' => 'consume_type_normal',
  ],
  32906 => 
  [
    'item_id' => 32906,
    'icon' => 'weapon_tulwar_i00',
    'name' => 'Generals Katzbalger of Destiny (Water]',
    'additionalname' => NULL,
    'description' => 'Generals Katzbalger of Destiny (Water] with limited ability enhancement. Kamael-exclusive Weapon: Claymore Conversion. This item cannot be enhanced except with PA Enchant Scrolls. ',
    'is_trade' => 0,
    'is_drop' => 0,
    'is_destruct' => 1,
    'crystal_type' => 'd',
    'consume_type' => 'consume_type_normal',
  ],
  32907 => 
  [
    'item_id' => 32907,
    'icon' => 'weapon_cyclone_bow_i00',
    'name' => 'Light Bow of Destiny (Water]',
    'additionalname' => NULL,
    'description' => 'Light Bow of Destiny (Water] with limited ability enhancement. This item cannot be enhanced except with PA Enchant Scrolls. ',
    'is_trade' => 0,
    'is_drop' => 0,
    'is_destruct' => 1,
    'crystal_type' => 'd',
    'consume_type' => 'consume_type_normal',
  ],
  32908 => 
  [
    'item_id' => 32908,
    'icon' => 'weapon_hunting_gun_i00',
    'name' => 'Cranequin of Destiny (Water]',
    'additionalname' => NULL,
    'description' => 'Cranequin of Destiny (Water] with limited ability enhancement. Kamael-exclusive Weapon: Light Bow Conversion. This item cannot be enhanced except with PA Enchant Scrolls. ',
    'is_trade' => 0,
    'is_drop' => 0,
    'is_destruct' => 1,
    'crystal_type' => 'd',
    'consume_type' => 'consume_type_normal',
  ],
  32909 => 
  [
    'item_id' => 32909,
    'icon' => 'weapon_bonebreaker_i00',
    'name' => 'Bonebreaker of Destiny (Water]',
    'additionalname' => NULL,
    'description' => 'Bonebreaker of Destiny (Water] with limited ability enhancement. This item cannot be enhanced except with PA Enchant Scrolls. ',
    'is_trade' => 0,
    'is_drop' => 0,
    'is_destruct' => 1,
    'crystal_type' => 'd',
    'consume_type' => 'consume_type_normal',
  ],
  32910 => 
  [
    'item_id' => 32910,
    'icon' => 'weapon_life_stick_i00',
    'name' => 'Staff of Life of Destiny (Water]',
    'additionalname' => NULL,
    'description' => 'Staff of Life of Destiny (Water] with limited ability enhancement. This item cannot be enhanced except with PA Enchant Scrolls. ',
    'is_trade' => 0,
    'is_drop' => 0,
    'is_destruct' => 1,
    'crystal_type' => 'd',
    'consume_type' => 'consume_type_normal',
  ],
  32911 => 
  [
    'item_id' => 32911,
    'icon' => 'weapon_atuba_hammer_i00',
    'name' => 'Atuba Hammer of Destiny (Water]',
    'additionalname' => NULL,
    'description' => 'Atuba Hammer of Destiny (Water] with limited ability enhancement. This item cannot be enhanced except with PA Enchant Scrolls. ',
    'is_trade' => 0,
    'is_drop' => 0,
    'is_destruct' => 1,
    'crystal_type' => 'd',
    'consume_type' => 'consume_type_normal',
  ],
  32912 => 
  [
    'item_id' => 32912,
    'icon' => 'weapon_glaive_i00',
    'name' => 'Glaive of Destiny (Water]',
    'additionalname' => NULL,
    'description' => 'Bonebreaker of Destiny (Water] with limited ability enhancement. Cannot be enhanced except with PA Enchant Scrolls. ',
    'is_trade' => 0,
    'is_drop' => 0,
    'is_destruct' => 1,
    'crystal_type' => 'd',
    'consume_type' => 'consume_type_normal',
  ],
  32913 => 
  [
    'item_id' => 32913,
    'icon' => 'weapon_scallop_jamadhr_i00',
    'name' => 'Scallop Jamadhr of Destiny (Water]',
    'additionalname' => NULL,
    'description' => 'Scallop Jamadhr of Destiny (Water] with limited ability enhancement. This item cannot be enhanced except with PA Enchant Scrolls. ',
    'is_trade' => 0,
    'is_drop' => 0,
    'is_destruct' => 1,
    'crystal_type' => 'd',
    'consume_type' => 'consume_type_normal',
  ],
  32914 => 
  [
    'item_id' => 32914,
    'icon' => 'weapon_dual_sword_i00',
    'name' => 'Bastard Sword of Destiny Crimson Sword (Water]',
    'additionalname' => NULL,
    'description' => 'Bastard Sword Crimson Sword of Destiny (Water] with limited ability enhancement. This item cannot be enhanced except with PA Enchant Scrolls. ',
    'is_trade' => 0,
    'is_drop' => 0,
    'is_destruct' => 1,
    'crystal_type' => 'd',
    'consume_type' => 'consume_type_normal',
  ],
  32915 => 
  [
    'item_id' => 32915,
    'icon' => 'weapon_mithril_dagger_i00',
    'name' => 'Mithril Dagger of Destiny (Wind]',
    'additionalname' => NULL,
    'description' => 'Mithril Dagger of Destiny (Wind] with limited ability enhancement. This item cannot be enhanced except with PA Enchant Scrolls. ',
    'is_trade' => 0,
    'is_drop' => 0,
    'is_destruct' => 1,
    'crystal_type' => 'd',
    'consume_type' => 'consume_type_normal',
  ],
  32916 => 
  [
    'item_id' => 32916,
    'icon' => 'weapon_elven_long_sword_i00',
    'name' => 'Elven Long Sword of Destiny (Wind]',
    'additionalname' => NULL,
    'description' => 'Elven Long Sword of Destiny (Wind] with limited ability enhancement. This item cannot be enhanced except with PA Enchant Scrolls. ',
    'is_trade' => 0,
    'is_drop' => 0,
    'is_destruct' => 1,
    'crystal_type' => 'd',
    'consume_type' => 'consume_type_normal',
  ],
  32917 => 
  [
    'item_id' => 32917,
    'icon' => 'weapon_rapier_i00',
    'name' => 'Grand ?p?e of Destiny (Wind]',
    'additionalname' => NULL,
    'description' => 'Grand ?p?e of Destiny (Wind], upgrade options are limited. When enchanted to +4 or higher, it has a chance to increase P./ M. Atk., Received Healing, and decrease Skill MP consumption for you and your party members after a critical attack. Can only be enchanted. ',
    'is_trade' => 0,
    'is_drop' => 0,
    'is_destruct' => 1,
    'crystal_type' => 'd',
    'consume_type' => 'consume_type_normal',
  ],
  32918 => 
  [
    'item_id' => 32918,
    'icon' => 'weapon_claymore_i00',
    'name' => 'Claymore of Destiny (Wind]',
    'additionalname' => NULL,
    'description' => 'Claymore of Destiny (Wind] with limited ability enhancement. This item cannot be enhanced except with PA Enchant Scrolls. ',
    'is_trade' => 0,
    'is_drop' => 0,
    'is_destruct' => 1,
    'crystal_type' => 'd',
    'consume_type' => 'consume_type_normal',
  ],
  32919 => 
  [
    'item_id' => 32919,
    'icon' => 'weapon_tulwar_i00',
    'name' => 'Generals Katzbalger of Destiny (Wind]',
    'additionalname' => NULL,
    'description' => 'Generals Katzbalger of Destiny (Wind] with limited ability enhancement. Kamael-exclusive Weapon: Claymore Conversion. This item cannot be enhanced except with PA Enchant Scrolls. ',
    'is_trade' => 0,
    'is_drop' => 0,
    'is_destruct' => 1,
    'crystal_type' => 'd',
    'consume_type' => 'consume_type_normal',
  ],
  32920 => 
  [
    'item_id' => 32920,
    'icon' => 'weapon_cyclone_bow_i00',
    'name' => 'Light Bow of Destiny (Wind]',
    'additionalname' => NULL,
    'description' => 'Light Bow of Destiny (Wind] with limited ability enhancement. This item cannot be enhanced except with PA Enchant Scrolls. ',
    'is_trade' => 0,
    'is_drop' => 0,
    'is_destruct' => 1,
    'crystal_type' => 'd',
    'consume_type' => 'consume_type_normal',
  ],
  32921 => 
  [
    'item_id' => 32921,
    'icon' => 'weapon_hunting_gun_i00',
    'name' => 'Cranequin of Destiny (Wind]',
    'additionalname' => NULL,
    'description' => 'Cranequin of Destiny (Wind] with limited ability enhancement. Kamael-exclusive Weapon: Light Bow Conversion. This item cannot be enhanced except with PA Enchant Scrolls. ',
    'is_trade' => 0,
    'is_drop' => 0,
    'is_destruct' => 1,
    'crystal_type' => 'd',
    'consume_type' => 'consume_type_normal',
  ],
  32922 => 
  [
    'item_id' => 32922,
    'icon' => 'weapon_bonebreaker_i00',
    'name' => 'Bonebreaker of Destiny (Wind]',
    'additionalname' => NULL,
    'description' => 'Bonebreaker of Destiny (Wind] with limited ability enhancement. Cannot be enhanced except with PA Enchant Scrolls. ',
    'is_trade' => 0,
    'is_drop' => 0,
    'is_destruct' => 1,
    'crystal_type' => 'd',
    'consume_type' => 'consume_type_normal',
  ],
  32923 => 
  [
    'item_id' => 32923,
    'icon' => 'weapon_life_stick_i00',
    'name' => 'Staff of Life of Destiny (Wind]',
    'additionalname' => NULL,
    'description' => 'Staff of Life of Destiny (Wind] with limited ability enhancement. This item cannot be enhanced except with PA Enchant Scrolls. ',
    'is_trade' => 0,
    'is_drop' => 0,
    'is_destruct' => 1,
    'crystal_type' => 'd',
    'consume_type' => 'consume_type_normal',
  ],
  32924 => 
  [
    'item_id' => 32924,
    'icon' => 'weapon_atuba_hammer_i00',
    'name' => 'Atuba Hammer of Destiny (Wind]',
    'additionalname' => NULL,
    'description' => 'Atuba Hammer of Destiny (Wind] with limited ability enhancement. This item cannot be enhanced except with PA Enchant Scrolls. ',
    'is_trade' => 0,
    'is_drop' => 0,
    'is_destruct' => 1,
    'crystal_type' => 'd',
    'consume_type' => 'consume_type_normal',
  ],
  32925 => 
  [
    'item_id' => 32925,
    'icon' => 'weapon_glaive_i00',
    'name' => 'Glaive of Destiny (Wind]',
    'additionalname' => NULL,
    'description' => 'Bonebreaker of Destiny (Wind] with limited ability enhancement. Cannot be enhanced except with PA Enchant Scrolls. ',
    'is_trade' => 0,
    'is_drop' => 0,
    'is_destruct' => 1,
    'crystal_type' => 'd',
    'consume_type' => 'consume_type_normal',
  ],
  32926 => 
  [
    'item_id' => 32926,
    'icon' => 'weapon_scallop_jamadhr_i00',
    'name' => 'Scallop Jamadhr of Destiny (Wind]',
    'additionalname' => NULL,
    'description' => 'Scallop Jamadhr of Destiny (Wind] with limited ability enhancement. This item cannot be enhanced except with PA Enchant Scrolls. ',
    'is_trade' => 0,
    'is_drop' => 0,
    'is_destruct' => 1,
    'crystal_type' => 'd',
    'consume_type' => 'consume_type_normal',
  ],
  32927 => 
  [
    'item_id' => 32927,
    'icon' => 'weapon_dual_sword_i00',
    'name' => 'Bastard Sword of Destiny Crimson Sword (Wind]',
    'additionalname' => NULL,
    'description' => 'Bastard Sword Crimson Sword of Destiny (Wind] with limited ability enhancement. This item cannot be enhanced except with PA Enchant Scrolls. ',
    'is_trade' => 0,
    'is_drop' => 0,
    'is_destruct' => 1,
    'crystal_type' => 'd',
    'consume_type' => 'consume_type_normal',
  ],
  32928 => 
  [
    'item_id' => 32928,
    'icon' => 'weapon_mithril_dagger_i00',
    'name' => 'Mithril Dagger of Destiny (Earth]',
    'additionalname' => NULL,
    'description' => 'Mithril Dagger of Destiny (Earth] with limited ability enhancement. This item cannot be enhanced except with PA Enchant Scrolls. ',
    'is_trade' => 0,
    'is_drop' => 0,
    'is_destruct' => 1,
    'crystal_type' => 'd',
    'consume_type' => 'consume_type_normal',
  ],
  32929 => 
  [
    'item_id' => 32929,
    'icon' => 'weapon_elven_long_sword_i00',
    'name' => 'Elven Long Sword of Destiny (Earth]',
    'additionalname' => NULL,
    'description' => 'Elven Long Sword of Destiny (Earth] with limited ability enhancement. This item cannot be enhanced except with PA Enchant Scrolls. ',
    'is_trade' => 0,
    'is_drop' => 0,
    'is_destruct' => 1,
    'crystal_type' => 'd',
    'consume_type' => 'consume_type_normal',
  ],
  32930 => 
  [
    'item_id' => 32930,
    'icon' => 'weapon_rapier_i00',
    'name' => 'Grand ?p?e of Destiny (Earth]',
    'additionalname' => NULL,
    'description' => 'Grand ?p?e of Destiny (Earth], upgrade options are limited. When enchanted to +4 or higher, it has a chance to increase P./ M. Atk., Received Healing, and decrease Skill MP consumption for you and your party members after a critical attack. Can only be enchanted. ',
    'is_trade' => 0,
    'is_drop' => 0,
    'is_destruct' => 1,
    'crystal_type' => 'd',
    'consume_type' => 'consume_type_normal',
  ],
  32931 => 
  [
    'item_id' => 32931,
    'icon' => 'weapon_claymore_i00',
    'name' => 'Claymore of Destiny (Earth]',
    'additionalname' => NULL,
    'description' => 'Claymore of Destiny (Earth] with limited ability enhancement. This item cannot be enhanced except with PA Enchant Scrolls. ',
    'is_trade' => 0,
    'is_drop' => 0,
    'is_destruct' => 1,
    'crystal_type' => 'd',
    'consume_type' => 'consume_type_normal',
  ],
  32932 => 
  [
    'item_id' => 32932,
    'icon' => 'weapon_tulwar_i00',
    'name' => 'Generals Katzbalger of Destiny (Earth]',
    'additionalname' => NULL,
    'description' => 'Generals Katzbalger of Destiny (Earth] with limited ability enhancement. Kamael-exclusive Weapon: Claymore Conversion. This item cannot be enhanced except with PA Enchant Scrolls. ',
    'is_trade' => 0,
    'is_drop' => 0,
    'is_destruct' => 1,
    'crystal_type' => 'd',
    'consume_type' => 'consume_type_normal',
  ],
  32933 => 
  [
    'item_id' => 32933,
    'icon' => 'weapon_cyclone_bow_i00',
    'name' => 'Light Bow of Destiny (Earth]',
    'additionalname' => NULL,
    'description' => 'Light Bow of Destiny (Earth] with limited ability enhancement. This item cannot be enhanced except with PA Enchant Scrolls. ',
    'is_trade' => 0,
    'is_drop' => 0,
    'is_destruct' => 1,
    'crystal_type' => 'd',
    'consume_type' => 'consume_type_normal',
  ],
  32934 => 
  [
    'item_id' => 32934,
    'icon' => 'weapon_hunting_gun_i00',
    'name' => 'Cranequin of Destiny (Earth]',
    'additionalname' => NULL,
    'description' => 'Cranequin of Destiny (Earth] with limited ability enhancement. Kamael-exclusive Weapon: Light Bow Conversion. This item cannot be enhanced except with PA Enchant Scrolls. ',
    'is_trade' => 0,
    'is_drop' => 0,
    'is_destruct' => 1,
    'crystal_type' => 'd',
    'consume_type' => 'consume_type_normal',
  ],
  32935 => 
  [
    'item_id' => 32935,
    'icon' => 'weapon_bonebreaker_i00',
    'name' => 'Bonebreaker of Destiny (Earth]',
    'additionalname' => NULL,
    'description' => 'Bonebreaker of Destiny (Earth] with limited ability enhancement. Cannot be enhanced except with PA Enchant Scrolls. ',
    'is_trade' => 0,
    'is_drop' => 0,
    'is_destruct' => 1,
    'crystal_type' => 'd',
    'consume_type' => 'consume_type_normal',
  ],
  32936 => 
  [
    'item_id' => 32936,
    'icon' => 'weapon_life_stick_i00',
    'name' => 'Staff of Life of Destiny (Earth]',
    'additionalname' => NULL,
    'description' => 'Staff of Life of Destiny (Earth] with limited ability enhancement. This item cannot be enhanced except with PA Enchant Scrolls. ',
    'is_trade' => 0,
    'is_drop' => 0,
    'is_destruct' => 1,
    'crystal_type' => 'd',
    'consume_type' => 'consume_type_normal',
  ],
  32937 => 
  [
    'item_id' => 32937,
    'icon' => 'weapon_atuba_hammer_i00',
    'name' => 'Atuba Hammer of Destiny (Earth]',
    'additionalname' => NULL,
    'description' => 'Atuba Hammer of Destiny (Earth] with limited ability enhancement. This item cannot be enhanced except with PA Enchant Scrolls. ',
    'is_trade' => 0,
    'is_drop' => 0,
    'is_destruct' => 1,
    'crystal_type' => 'd',
    'consume_type' => 'consume_type_normal',
  ],
  32938 => 
  [
    'item_id' => 32938,
    'icon' => 'weapon_glaive_i00',
    'name' => 'Glaive of Destiny (Earth]',
    'additionalname' => NULL,
    'description' => 'Bonebreaker of Destiny (Earth] with limited ability enhancement. Cannot be enhanced except with PA Enchant Scrolls. ',
    'is_trade' => 0,
    'is_drop' => 0,
    'is_destruct' => 1,
    'crystal_type' => 'd',
    'consume_type' => 'consume_type_normal',
  ],
  32939 => 
  [
    'item_id' => 32939,
    'icon' => 'weapon_scallop_jamadhr_i00',
    'name' => 'Scallop Jamadhr of Destiny (Earth]',
    'additionalname' => NULL,
    'description' => 'Scallop Jamadhr of Destiny (Earth] with limited ability enhancement. This item cannot be enhanced except with PA Enchant Scrolls. ',
    'is_trade' => 0,
    'is_drop' => 0,
    'is_destruct' => 1,
    'crystal_type' => 'd',
    'consume_type' => 'consume_type_normal',
  ],
  32940 => 
  [
    'item_id' => 32940,
    'icon' => 'weapon_dual_sword_i00',
    'name' => 'Bastard Sword of Destiny Crimson Sword (Earth]',
    'additionalname' => NULL,
    'description' => 'Bastard Sword Crimson Sword of Destiny (Earth] with limited ability enhancement. This item cannot be enhanced except with PA Enchant Scrolls. ',
    'is_trade' => 0,
    'is_drop' => 0,
    'is_destruct' => 1,
    'crystal_type' => 'd',
    'consume_type' => 'consume_type_normal',
  ],
  32941 => 
  [
    'item_id' => 32941,
    'icon' => 'weapon_mithril_dagger_i00',
    'name' => 'Mithril Dagger of Destiny (Holy]',
    'additionalname' => NULL,
    'description' => 'Mithril Dagger of Destiny (Holy] with limited ability enhancement. This item cannot be enhanced except with PA Enchant Scrolls. ',
    'is_trade' => 0,
    'is_drop' => 0,
    'is_destruct' => 1,
    'crystal_type' => 'd',
    'consume_type' => 'consume_type_normal',
  ],
  32942 => 
  [
    'item_id' => 32942,
    'icon' => 'weapon_elven_long_sword_i00',
    'name' => 'Elven Long Sword of Destiny (Holy]',
    'additionalname' => NULL,
    'description' => 'Elven Long Sword of Destiny (Holy] with limited ability enhancement. This item cannot be enhanced except with PA Enchant Scrolls. ',
    'is_trade' => 0,
    'is_drop' => 0,
    'is_destruct' => 1,
    'crystal_type' => 'd',
    'consume_type' => 'consume_type_normal',
  ],
  32943 => 
  [
    'item_id' => 32943,
    'icon' => 'weapon_rapier_i00',
    'name' => 'Grand ?p?e of Destiny (Holy]',
    'additionalname' => NULL,
    'description' => 'Grand ?p?e of Destiny (Holy], upgrade options are limited. When enchanted to +4 or higher, it has a chance to increase P./ M. Atk., Received Healing, and decrease Skill MP consumption for you and your party members after a critical attack. Can only be enchanted. ',
    'is_trade' => 0,
    'is_drop' => 0,
    'is_destruct' => 1,
    'crystal_type' => 'd',
    'consume_type' => 'consume_type_normal',
  ],
  32944 => 
  [
    'item_id' => 32944,
    'icon' => 'weapon_claymore_i00',
    'name' => 'Claymore of Destiny (Holy]',
    'additionalname' => NULL,
    'description' => 'Claymore of Destiny (Holy] with limited ability enhancement. This item cannot be enhanced except with PA Enchant Scrolls. ',
    'is_trade' => 0,
    'is_drop' => 0,
    'is_destruct' => 1,
    'crystal_type' => 'd',
    'consume_type' => 'consume_type_normal',
  ],
  32945 => 
  [
    'item_id' => 32945,
    'icon' => 'weapon_tulwar_i00',
    'name' => 'Generals Katzbalger of Destiny (Holy]',
    'additionalname' => NULL,
    'description' => 'Generals Katzbalger of Destiny (Holy] with limited ability enhancement. Kamael-exclusive Weapon: Claymore Conversion. This item cannot be enhanced except with PA Enchant Scrolls. ',
    'is_trade' => 0,
    'is_drop' => 0,
    'is_destruct' => 1,
    'crystal_type' => 'd',
    'consume_type' => 'consume_type_normal',
  ],
  32946 => 
  [
    'item_id' => 32946,
    'icon' => 'weapon_cyclone_bow_i00',
    'name' => 'Light Bow of Destiny (Holy]',
    'additionalname' => NULL,
    'description' => 'Light Bow of Destiny (Holy] with limited ability enhancement. This item cannot be enhanced except with PA Enchant Scrolls. ',
    'is_trade' => 0,
    'is_drop' => 0,
    'is_destruct' => 1,
    'crystal_type' => 'd',
    'consume_type' => 'consume_type_normal',
  ],
  32947 => 
  [
    'item_id' => 32947,
    'icon' => 'weapon_hunting_gun_i00',
    'name' => 'Cranequin of Destiny (Holy]',
    'additionalname' => NULL,
    'description' => 'Cranequin of Destiny (Holy] with limited ability enhancement. Kamael-exclusive Weapon: Light Bow Conversion. This item cannot be enhanced except with PA Enchant Scrolls. ',
    'is_trade' => 0,
    'is_drop' => 0,
    'is_destruct' => 1,
    'crystal_type' => 'd',
    'consume_type' => 'consume_type_normal',
  ],
  32948 => 
  [
    'item_id' => 32948,
    'icon' => 'weapon_bonebreaker_i00',
    'name' => 'Bonebreaker of Destiny (Holy]',
    'additionalname' => NULL,
    'description' => 'Bonebreaker of Destiny (Holy] with limited ability enhancement. This item cannot be enhanced except with PA Enchant Scrolls. ',
    'is_trade' => 0,
    'is_drop' => 0,
    'is_destruct' => 1,
    'crystal_type' => 'd',
    'consume_type' => 'consume_type_normal',
  ],
  32949 => 
  [
    'item_id' => 32949,
    'icon' => 'weapon_life_stick_i00',
    'name' => 'Staff of Life of Destiny (Holy]',
    'additionalname' => NULL,
    'description' => 'Staff of Life of Destiny (Holy] with limited ability enhancement. This item cannot be enhanced except with PA Enchant Scrolls. ',
    'is_trade' => 0,
    'is_drop' => 0,
    'is_destruct' => 1,
    'crystal_type' => 'd',
    'consume_type' => 'consume_type_normal',
  ],
  32950 => 
  [
    'item_id' => 32950,
    'icon' => 'weapon_atuba_hammer_i00',
    'name' => 'Atuba Hammer of Destiny (Holy]',
    'additionalname' => NULL,
    'description' => 'Atuba Hammer of Destiny (Holy] with limited ability enhancement. This item cannot be enhanced except with PA Enchant Scrolls. ',
    'is_trade' => 0,
    'is_drop' => 0,
    'is_destruct' => 1,
    'crystal_type' => 'd',
    'consume_type' => 'consume_type_normal',
  ],
  32951 => 
  [
    'item_id' => 32951,
    'icon' => 'weapon_glaive_i00',
    'name' => 'Glaive of Destiny (Holy]',
    'additionalname' => NULL,
    'description' => 'Glaive of Destiny (Holy] with limited ability enhancement. This item cannot be enhanced except with PA Enchant Scrolls. ',
    'is_trade' => 0,
    'is_drop' => 0,
    'is_destruct' => 1,
    'crystal_type' => 'd',
    'consume_type' => 'consume_type_normal',
  ],
  32952 => 
  [
    'item_id' => 32952,
    'icon' => 'weapon_scallop_jamadhr_i00',
    'name' => 'Scallop Jamadhr of Destiny (Holy]',
    'additionalname' => NULL,
    'description' => 'Scallop Jamadhr of Destiny (Holy] with limited ability enhancement. This item cannot be enhanced except with PA Enchant Scrolls. ',
    'is_trade' => 0,
    'is_drop' => 0,
    'is_destruct' => 1,
    'crystal_type' => 'd',
    'consume_type' => 'consume_type_normal',
  ],
  32953 => 
  [
    'item_id' => 32953,
    'icon' => 'weapon_dual_sword_i00',
    'name' => 'Bastard Sword of Destiny Crimson Sword (Holy]',
    'additionalname' => NULL,
    'description' => 'Bastard Sword Crimson Sword of Destiny (Holy] with limited ability enhancement. This item cannot be enhanced except with PA Enchant Scrolls. ',
    'is_trade' => 0,
    'is_drop' => 0,
    'is_destruct' => 1,
    'crystal_type' => 'd',
    'consume_type' => 'consume_type_normal',
  ],
  32954 => 
  [
    'item_id' => 32954,
    'icon' => 'weapon_mithril_dagger_i00',
    'name' => 'Mithril Dagger of Destiny (Dark]',
    'additionalname' => NULL,
    'description' => 'Mithril Dagger of Destiny (Dark] with limited ability enhancement. This item cannot be enhanced except with PA Enchant Scrolls. ',
    'is_trade' => 0,
    'is_drop' => 0,
    'is_destruct' => 1,
    'crystal_type' => 'd',
    'consume_type' => 'consume_type_normal',
  ],
  32955 => 
  [
    'item_id' => 32955,
    'icon' => 'weapon_elven_long_sword_i00',
    'name' => 'Elven Long Sword of Destiny (Dark]',
    'additionalname' => NULL,
    'description' => 'Elven Long Sword of Destiny (Dark] with limited ability enhancement. This item cannot be enhanced except with PA Enchant Scrolls. ',
    'is_trade' => 0,
    'is_drop' => 0,
    'is_destruct' => 1,
    'crystal_type' => 'd',
    'consume_type' => 'consume_type_normal',
  ],
  32956 => 
  [
    'item_id' => 32956,
    'icon' => 'weapon_rapier_i00',
    'name' => 'Grand ?p?e of Destiny (Dark]',
    'additionalname' => NULL,
    'description' => 'Grand ?p?e of Destiny (Dark], upgrade options are limited. When enchanted to +4 or higher, it has a chance to increase P./ M. Atk., Received Healing, and decrease Skill MP consumption for you and your party members after a critical attack. Can only be enchanted. ',
    'is_trade' => 0,
    'is_drop' => 0,
    'is_destruct' => 1,
    'crystal_type' => 'd',
    'consume_type' => 'consume_type_normal',
  ],
  32957 => 
  [
    'item_id' => 32957,
    'icon' => 'weapon_claymore_i00',
    'name' => 'Claymore of Destiny (Dark]',
    'additionalname' => NULL,
    'description' => 'Claymore of Destiny (Dark] with limited ability enhancement. This item cannot be enhanced except with PA Enchant Scrolls. ',
    'is_trade' => 0,
    'is_drop' => 0,
    'is_destruct' => 1,
    'crystal_type' => 'd',
    'consume_type' => 'consume_type_normal',
  ],
  32958 => 
  [
    'item_id' => 32958,
    'icon' => 'weapon_tulwar_i00',
    'name' => 'Generals Katzbalger of Destiny (Dark]',
    'additionalname' => NULL,
    'description' => 'Generals Katzbalger of Destiny (Dark] with limited ability enhancement. Kamael-exclusive Weapon: Claymore Conversion. This item cannot be enhanced except with PA Enchant Scrolls. ',
    'is_trade' => 0,
    'is_drop' => 0,
    'is_destruct' => 1,
    'crystal_type' => 'd',
    'consume_type' => 'consume_type_normal',
  ],
  32959 => 
  [
    'item_id' => 32959,
    'icon' => 'weapon_cyclone_bow_i00',
    'name' => 'Light Bow of Destiny (Dark]',
    'additionalname' => NULL,
    'description' => 'Light Bow of Destiny (Dark] with limited ability enhancement. This item cannot be enhanced except with PA Enchant Scrolls. ',
    'is_trade' => 0,
    'is_drop' => 0,
    'is_destruct' => 1,
    'crystal_type' => 'd',
    'consume_type' => 'consume_type_normal',
  ],
  32960 => 
  [
    'item_id' => 32960,
    'icon' => 'weapon_hunting_gun_i00',
    'name' => 'Cranequin of Destiny (Dark]',
    'additionalname' => NULL,
    'description' => 'Cranequin of Destiny (Dark] with limited ability enhancement. Kamael-exclusive Weapon: Light Bow Conversion. This item cannot be enhanced except with PA Enchant Scrolls. ',
    'is_trade' => 0,
    'is_drop' => 0,
    'is_destruct' => 1,
    'crystal_type' => 'd',
    'consume_type' => 'consume_type_normal',
  ],
  32961 => 
  [
    'item_id' => 32961,
    'icon' => 'weapon_bonebreaker_i00',
    'name' => 'Bonebreaker of Destiny (Dark]',
    'additionalname' => NULL,
    'description' => 'Bonebreaker of Destiny (Dark] with limited ability enhancement. This item cannot be enhanced except with PA Enchant Scrolls. ',
    'is_trade' => 0,
    'is_drop' => 0,
    'is_destruct' => 1,
    'crystal_type' => 'd',
    'consume_type' => 'consume_type_normal',
  ],
  32962 => 
  [
    'item_id' => 32962,
    'icon' => 'weapon_life_stick_i00',
    'name' => 'Staff of Life of Destiny (Dark]',
    'additionalname' => NULL,
    'description' => 'Staff of Life of Destiny (Dark] with limited ability enhancement. This item cannot be enhanced except with PA Enchant Scrolls. ',
    'is_trade' => 0,
    'is_drop' => 0,
    'is_destruct' => 1,
    'crystal_type' => 'd',
    'consume_type' => 'consume_type_normal',
  ],
  32963 => 
  [
    'item_id' => 32963,
    'icon' => 'weapon_atuba_hammer_i00',
    'name' => 'Atuba Hammer of Destiny (Dark]',
    'additionalname' => NULL,
    'description' => 'Atuba Hammer of Destiny (Dark] with limited ability enhancement. This item cannot be enhanced except with PA Enchant Scrolls. ',
    'is_trade' => 0,
    'is_drop' => 0,
    'is_destruct' => 1,
    'crystal_type' => 'd',
    'consume_type' => 'consume_type_normal',
  ],
  32964 => 
  [
    'item_id' => 32964,
    'icon' => 'weapon_glaive_i00',
    'name' => 'Glaive of Destiny (Dark]',
    'additionalname' => NULL,
    'description' => 'Glaive of Destiny (Dark] with limited ability enhancement. This item cannot be enhanced except with PA Enchant Scrolls. ',
    'is_trade' => 0,
    'is_drop' => 0,
    'is_destruct' => 1,
    'crystal_type' => 'd',
    'consume_type' => 'consume_type_normal',
  ],
  32965 => 
  [
    'item_id' => 32965,
    'icon' => 'weapon_scallop_jamadhr_i00',
    'name' => 'Scallop Jamadhr of Destiny (Dark]',
    'additionalname' => NULL,
    'description' => 'Scallop Jamadhr of Destiny (Dark] with limited ability enhancement. This item cannot be enhanced except with PA Enchant Scrolls. ',
    'is_trade' => 0,
    'is_drop' => 0,
    'is_destruct' => 1,
    'crystal_type' => 'd',
    'consume_type' => 'consume_type_normal',
  ],
  32966 => 
  [
    'item_id' => 32966,
    'icon' => 'weapon_dual_sword_i00',
    'name' => 'Bastard Sword of Destiny Crimson Sword (Dark]',
    'additionalname' => NULL,
    'description' => 'Bastard Sword Crimson Sword of Destiny (Dark] with limited ability enhancement. This item cannot be enhanced except with PA Enchant Scrolls. ',
    'is_trade' => 0,
    'is_drop' => 0,
    'is_destruct' => 1,
    'crystal_type' => 'd',
    'consume_type' => 'consume_type_normal',
  ],
  32967 => 
  [
    'item_id' => 32967,
    'icon' => 'armor_helmet_i00',
    'name' => 'Brigandine Helmet of Destiny (Fire, Wind, Dark]',
    'additionalname' => NULL,
    'description' => 'Brigandine Helmet of Destiny (Fire, Wind, Dark] with limited ability enhancement. This item cannot be enhanced except with PA Enchant Scrolls. ',
    'is_trade' => 0,
    'is_drop' => 0,
    'is_destruct' => 1,
    'crystal_type' => 'd',
    'consume_type' => 'consume_type_normal',
  ],
  32968 => 
  [
    'item_id' => 32968,
    'icon' => 'armor_t43_u_i00',
    'name' => 'Brigandine of Destiny (Fire, Wind, Dark]',
    'additionalname' => NULL,
    'description' => 'Brigandine - Destiny (Fire, Wind, Dark], upgrade options are limited. Can only be enchanted. ',
    'is_trade' => 0,
    'is_drop' => 0,
    'is_destruct' => 1,
    'crystal_type' => 'd',
    'consume_type' => 'consume_type_normal',
  ],
  32969 => 
  [
    'item_id' => 32969,
    'icon' => 'armor_t43_l_i00',
    'name' => 'Brigandine Gaiters of Destiny (Fire, Wind, Dark]',
    'additionalname' => NULL,
    'description' => 'Brigandine Gaiters of Destiny (Fire, Wind, Dark] with limited ability enhancement. This item cannot be enhanced except with PA Enchant Scrolls. ',
    'is_trade' => 0,
    'is_drop' => 0,
    'is_destruct' => 1,
    'crystal_type' => 'd',
    'consume_type' => 'consume_type_normal',
  ],
  32970 => 
  [
    'item_id' => 32970,
    'icon' => 'shield_brigandine_shield_i00',
    'name' => 'Brigandine Shield of Destiny (Fire, Wind, Dark]',
    'additionalname' => NULL,
    'description' => 'Brigandine Shield of Destiny (Fire, Wind, Dark] with limited ability enhancement. This item cannot be enhanced except with PA Enchant Scrolls. ',
    'is_trade' => 0,
    'is_drop' => 0,
    'is_destruct' => 1,
    'crystal_type' => 'd',
    'consume_type' => 'consume_type_normal',
  ],
  32971 => 
  [
    'item_id' => 32971,
    'icon' => 'armor_t43_b_i00',
    'name' => 'Brigandine Boots of Destiny (Fire, Wind, Dark]',
    'additionalname' => NULL,
    'description' => 'Brigandine Boots of Destiny (Fire, Wind, Dark] with limited ability enhancement. This item cannot be enhanced except with PA Enchant Scrolls. ',
    'is_trade' => 0,
    'is_drop' => 0,
    'is_destruct' => 1,
    'crystal_type' => 'd',
    'consume_type' => 'consume_type_normal',
  ],
  32972 => 
  [
    'item_id' => 32972,
    'icon' => 'armor_t43_g_i00',
    'name' => 'Brigandine Gauntlets of Destiny (Fire, Wind, Dark]',
    'additionalname' => NULL,
    'description' => 'Brigandine Gauntlets of Destiny (Fire, Wind, Dark] with limited ability enhancement. This item cannot be enhanced except with PA Enchant Scrolls. ',
    'is_trade' => 0,
    'is_drop' => 0,
    'is_destruct' => 1,
    'crystal_type' => 'd',
    'consume_type' => 'consume_type_normal',
  ],
  32973 => 
  [
    'item_id' => 32973,
    'icon' => 'armor_t42_u_i00',
    'name' => 'Manticore Skin Shirt of Destiny (Fire, Wind, Dark]',
    'additionalname' => NULL,
    'description' => 'Manticore Skin Shirt of Destiny (Fire, Wind, Dark] with limited ability enhancement. This item cannot be enhanced except with PA Enchant Scrolls. ',
    'is_trade' => 0,
    'is_drop' => 0,
    'is_destruct' => 1,
    'crystal_type' => 'd',
    'consume_type' => 'consume_type_normal',
  ],
  32974 => 
  [
    'item_id' => 32974,
    'icon' => 'armor_t42_l_i00',
    'name' => 'Manticore Skin Gaiters of Destiny (Fire, Wind, Dark]',
    'additionalname' => NULL,
    'description' => 'Manticore Skin Gaiters of Destiny (Fire, Wind, Dark] with limited ability enhancement. This item cannot be enhanced except with PA Enchant Scrolls. ',
    'is_trade' => 0,
    'is_drop' => 0,
    'is_destruct' => 1,
    'crystal_type' => 'd',
    'consume_type' => 'consume_type_normal',
  ],
  32975 => 
  [
    'item_id' => 32975,
    'icon' => 'armor_t42_b_i00',
    'name' => 'Manticore Skin Boots of Destiny (Fire, Wind, Dark]',
    'additionalname' => NULL,
    'description' => 'Manticore Skin Boots of Destiny (Fire, Wind, Dark] with limited ability enhancement. This item cannot be enhanced except with PA Enchant Scrolls. ',
    'is_trade' => 0,
    'is_drop' => 0,
    'is_destruct' => 1,
    'crystal_type' => 'd',
    'consume_type' => 'consume_type_normal',
  ],
  32976 => 
  [
    'item_id' => 32976,
    'icon' => 'armor_t42_g_i00',
    'name' => 'Manticore Skin Gloves of Destiny (Fire, Wind, Dark]',
    'additionalname' => NULL,
    'description' => 'Manticore Skin Gloves of Destiny (Fire, Wind, Dark] with limited ability enhancement. This item cannot be enhanced except with PA Enchant Scrolls. ',
    'is_trade' => 0,
    'is_drop' => 0,
    'is_destruct' => 1,
    'crystal_type' => 'd',
    'consume_type' => 'consume_type_normal',
  ],
  32977 => 
  [
    'item_id' => 32977,
    'icon' => 'armor_t51_u_i00',
    'name' => 'Mithril Tunic of Destiny (Fire, Wind, Dark]',
    'additionalname' => NULL,
    'description' => 'Mithril Tunic of Destiny (Fire, Wind, Dark] with limited ability enhancement. This item cannot be enhanced except with PA Enchant Scrolls. ',
    'is_trade' => 0,
    'is_drop' => 0,
    'is_destruct' => 1,
    'crystal_type' => 'd',
    'consume_type' => 'consume_type_normal',
  ],
  32978 => 
  [
    'item_id' => 32978,
    'icon' => 'armor_t51_l_i00',
    'name' => 'Mithril Stockings of Destiny (Fire, Wind, Dark]',
    'additionalname' => NULL,
    'description' => 'Mithril Stockings of Destiny (Fire, Wind, Dark] with limited ability enhancement. This item cannot be enhanced except with PA Enchant Scrolls. ',
    'is_trade' => 0,
    'is_drop' => 0,
    'is_destruct' => 1,
    'crystal_type' => 'd',
    'consume_type' => 'consume_type_normal',
  ],
  32979 => 
  [
    'item_id' => 32979,
    'icon' => 'armor_t51_g_i00',
    'name' => 'Elven Mithril Gloves of Destiny (Fire, Wind, Dark]',
    'additionalname' => NULL,
    'description' => 'Elven Mithril Gloves of Destiny (Fire, Wind, Dark] with limited ability enhancement. This item cannot be enhanced except with PA Enchant Scrolls. ',
    'is_trade' => 0,
    'is_drop' => 0,
    'is_destruct' => 1,
    'crystal_type' => 'd',
    'consume_type' => 'consume_type_normal',
  ],
  32980 => 
  [
    'item_id' => 32980,
    'icon' => 'armor_t51_b_i00',
    'name' => 'Elven Mithril Boots of Destiny (Fire, Wind, Dark]',
    'additionalname' => NULL,
    'description' => 'Elven Mithril Boots of Destiny (Fire, Wind, Dark] with limited ability enhancement. This item cannot be enhanced except with PA Enchant Scrolls. ',
    'is_trade' => 0,
    'is_drop' => 0,
    'is_destruct' => 1,
    'crystal_type' => 'd',
    'consume_type' => 'consume_type_normal',
  ],
  32981 => 
  [
    'item_id' => 32981,
    'icon' => 'armor_helmet_i00',
    'name' => 'Brigandine Helmet of Destiny (Water, Earth, Holy]',
    'additionalname' => NULL,
    'description' => 'Brigandine Helmet of Destiny (Water, Earth, Holy] with limited ability enhancement. This item cannot be enhanced except with PA Enchant Scrolls. ',
    'is_trade' => 0,
    'is_drop' => 0,
    'is_destruct' => 1,
    'crystal_type' => 'd',
    'consume_type' => 'consume_type_normal',
  ],
  32982 => 
  [
    'item_id' => 32982,
    'icon' => 'armor_t43_u_i00',
    'name' => 'Brigandine of Destiny (Water, Earth, Holy]',
    'additionalname' => NULL,
    'description' => 'Brigandine of Destiny (Water, Earth, Holy] with limited ability enhancement. This item cannot be enhanced except with PA Enchant Scrolls. ',
    'is_trade' => 0,
    'is_drop' => 0,
    'is_destruct' => 1,
    'crystal_type' => 'd',
    'consume_type' => 'consume_type_normal',
  ],
  32983 => 
  [
    'item_id' => 32983,
    'icon' => 'armor_t43_l_i00',
    'name' => 'Brigandine Gaiters of Destiny (Water, Earth, Holy]',
    'additionalname' => NULL,
    'description' => 'Brigandine Gaiters of Destiny (Water, Earth, Holy] with limited ability enhancement. This item cannot be enhanced except with PA Enchant Scrolls. ',
    'is_trade' => 0,
    'is_drop' => 0,
    'is_destruct' => 1,
    'crystal_type' => 'd',
    'consume_type' => 'consume_type_normal',
  ],
  32984 => 
  [
    'item_id' => 32984,
    'icon' => 'shield_brigandine_shield_i00',
    'name' => 'Brigandine Shield of Destiny (Water, Earth, Holy]',
    'additionalname' => NULL,
    'description' => 'Brigandine Shield of Destiny (Water, Earth, Holy] with limited ability enhancement. This item cannot be enhanced except with PA Enchant Scrolls. ',
    'is_trade' => 0,
    'is_drop' => 0,
    'is_destruct' => 1,
    'crystal_type' => 'd',
    'consume_type' => 'consume_type_normal',
  ],
  32985 => 
  [
    'item_id' => 32985,
    'icon' => 'armor_t43_b_i00',
    'name' => 'Brigandine Boots of Destiny (Water, Earth, Holy]',
    'additionalname' => NULL,
    'description' => 'Brigandine Boots of Destiny (Water, Earth, Holy] with limited ability enhancement. This item cannot be enhanced except with PA Enchant Scrolls. ',
    'is_trade' => 0,
    'is_drop' => 0,
    'is_destruct' => 1,
    'crystal_type' => 'd',
    'consume_type' => 'consume_type_normal',
  ],
  32986 => 
  [
    'item_id' => 32986,
    'icon' => 'armor_t43_g_i00',
    'name' => 'Brigandine Gauntlets of Destiny (Water, Earth, Holy]',
    'additionalname' => NULL,
    'description' => 'Brigandine Gauntlets of Destiny (Water, Earth, Holy] with limited ability enhancement. This item cannot be enhanced except with PA Enchant Scrolls. ',
    'is_trade' => 0,
    'is_drop' => 0,
    'is_destruct' => 1,
    'crystal_type' => 'd',
    'consume_type' => 'consume_type_normal',
  ],
  32987 => 
  [
    'item_id' => 32987,
    'icon' => 'armor_t42_u_i00',
    'name' => 'Manticore Skin Shirt of Destiny (Water, Earth, Holy]',
    'additionalname' => NULL,
    'description' => 'Manticore Skin Shirt of Destiny (Water, Earth, Holy] with limited ability enhancement. This item cannot be enhanced except with PA Enchant Scrolls. ',
    'is_trade' => 0,
    'is_drop' => 0,
    'is_destruct' => 1,
    'crystal_type' => 'd',
    'consume_type' => 'consume_type_normal',
  ],
  32988 => 
  [
    'item_id' => 32988,
    'icon' => 'armor_t42_l_i00',
    'name' => 'Manticore Skin Gaiters of Destiny (Water, Earth, Holy]',
    'additionalname' => NULL,
    'description' => 'Manticore Skin Gaiters of Destiny (Water, Earth, Holy] with limited ability enhancement. This item cannot be enhanced except with PA Enchant Scrolls. ',
    'is_trade' => 0,
    'is_drop' => 0,
    'is_destruct' => 1,
    'crystal_type' => 'd',
    'consume_type' => 'consume_type_normal',
  ],
  32989 => 
  [
    'item_id' => 32989,
    'icon' => 'armor_t42_b_i00',
    'name' => 'Manticore Skin Boots of Destiny (Water, Earth, Holy]',
    'additionalname' => NULL,
    'description' => 'Manticore Skin Boots of Destiny (Water, Earth, Holy] with limited ability enhancement. This item cannot be enhanced except with PA Enchant Scrolls. ',
    'is_trade' => 0,
    'is_drop' => 0,
    'is_destruct' => 1,
    'crystal_type' => 'd',
    'consume_type' => 'consume_type_normal',
  ],
  32990 => 
  [
    'item_id' => 32990,
    'icon' => 'armor_t42_g_i00',
    'name' => 'Manticore Skin Gloves of Destiny (Water, Earth, Holy]',
    'additionalname' => NULL,
    'description' => 'Manticore Skin Gloves of Destiny (Water, Earth, Holy] with limited ability enhancement. This item cannot be enhanced except with PA Enchant Scrolls. ',
    'is_trade' => 0,
    'is_drop' => 0,
    'is_destruct' => 1,
    'crystal_type' => 'd',
    'consume_type' => 'consume_type_normal',
  ],
  32991 => 
  [
    'item_id' => 32991,
    'icon' => 'armor_t51_u_i00',
    'name' => 'Mithril Tunic of Destiny (Water, Earth, Holy]',
    'additionalname' => NULL,
    'description' => 'Mithril Tunic of Destiny (Water, Earth, Holy] with limited ability enhancement. This item cannot be enhanced except with PA Enchant Scrolls. ',
    'is_trade' => 0,
    'is_drop' => 0,
    'is_destruct' => 1,
    'crystal_type' => 'd',
    'consume_type' => 'consume_type_normal',
  ],
  32992 => 
  [
    'item_id' => 32992,
    'icon' => 'armor_t51_l_i00',
    'name' => 'Mithril Stockings of Destiny (Water, Earth, Holy]',
    'additionalname' => NULL,
    'description' => 'Mithril Stockings of Destiny (Water, Earth, Holy] with limited ability enhancement. This item cannot be enhanced except with PA Enchant Scrolls. ',
    'is_trade' => 0,
    'is_drop' => 0,
    'is_destruct' => 1,
    'crystal_type' => 'd',
    'consume_type' => 'consume_type_normal',
  ],
  32993 => 
  [
    'item_id' => 32993,
    'icon' => 'armor_t51_g_i00',
    'name' => 'Elven Mithril Gloves of Destiny (Water, Earth, Holy]',
    'additionalname' => NULL,
    'description' => 'Elven Mithril Gloves of Destiny (Water, Earth, Holy] with limited ability enhancement. This item cannot be enhanced except with PA Enchant Scrolls. ',
    'is_trade' => 0,
    'is_drop' => 0,
    'is_destruct' => 1,
    'crystal_type' => 'd',
    'consume_type' => 'consume_type_normal',
  ],
  32994 => 
  [
    'item_id' => 32994,
    'icon' => 'armor_t51_b_i00',
    'name' => 'Elven Mithril Boots of Destiny (Water, Earth, Holy]',
    'additionalname' => NULL,
    'description' => 'Elven Mithril Boots of Destiny (Water, Earth, Holy] with limited ability enhancement. This item cannot be enhanced except with PA Enchant Scrolls. ',
    'is_trade' => 0,
    'is_drop' => 0,
    'is_destruct' => 1,
    'crystal_type' => 'd',
    'consume_type' => 'consume_type_normal',
  ],
  32995 => 
  [
    'item_id' => 32995,
    'icon' => 'weapon_crystal_dagger_i01',
    'name' => 'Crystal Dagger of Destiny (Fire] - Critical Damage',
    'additionalname' => NULL,
    'description' => 'Crystal Dagger - Destiny (Fire], upgrade options are limited. <Special properties> P. Atk. +140 after a critical attack. Can only be enchanted. No soul crystal can be inserted.',
    'is_trade' => 0,
    'is_drop' => 0,
    'is_destruct' => 1,
    'crystal_type' => 'c',
    'consume_type' => 'consume_type_normal',
  ],
  32996 => 
  [
    'item_id' => 32996,
    'icon' => 'weapon_samurai_longsword_i01',
    'name' => 'Samurai Long Sword of Destiny (Fire] - Focus',
    'additionalname' => NULL,
    'description' => 'Samurai Long Sword of Destiny (Fire], upgrade options are limited. <Special Option> P. Critical Rate +73. Can only be enchanted. No Soul Crystal option.',
    'is_trade' => 0,
    'is_drop' => 0,
    'is_destruct' => 1,
    'crystal_type' => 'c',
    'consume_type' => 'consume_type_normal',
  ],
  32997 => 
  [
    'item_id' => 32997,
    'icon' => 'weapon_blink_slasher_i01',
    'name' => 'Admirals Estoc of Destiny (Fire] - Focus',
    'additionalname' => NULL,
    'description' => 'Admirals Estoc of Destiny (Fire], upgrade options are limited. <Special Option> P. Critical Rate +73. When enchanted to +4 or higher, it has a chance to increase P./ M. Atk., Received Healing, and decrease Skill MP consumption for you and your party members after a critical attack. Can only be enchanted. No Soul Crystal option.',
    'is_trade' => 0,
    'is_drop' => 0,
    'is_destruct' => 1,
    'crystal_type' => 'c',
    'consume_type' => 'consume_type_normal',
  ],
  32998 => 
  [
    'item_id' => 32998,
    'icon' => 'weapon_berserker_blade_i01',
    'name' => 'Berserker Blade of Destiny (Fire] - Focus',
    'additionalname' => NULL,
    'description' => 'Berserker Blade of Destiny (Fire], upgrade options are limited. <Special Option> P. Critical Rate +73. Can only be enchanted. No Soul Crystal option.',
    'is_trade' => 0,
    'is_drop' => 0,
    'is_destruct' => 1,
    'crystal_type' => 'c',
    'consume_type' => 'consume_type_normal',
  ],
  32999 => 
  [
    'item_id' => 32999,
    'icon' => 'weapon_invincible_blade_i01',
    'name' => 'Saber Tooth of Destiny (Fire] - Focus',
    'additionalname' => NULL,
    'description' => 'Saber Tooth of Destiny (Fire], upgrade options are limited. <Special Option> P. Critical Rate +73. Can only be enchanted. No Soul Crystal option.',
    'is_trade' => 0,
    'is_drop' => 0,
    'is_destruct' => 1,
    'crystal_type' => 'c',
    'consume_type' => 'consume_type_normal',
  ],
];