<?php return [
  34600 => 
  [
    'item_id' => 34600,
    'icon' => 'etc_trans_4f_s_b_01',
    'name' => 'Player Commendation - Transformation Scroll: Rose (F]',
    'additionalname' => 'PC-exclusive',
    'description' => 'Inflicts magic-type attack. Transforms into a Rose (F] for 10 min.',
    'is_trade' => 0,
    'is_drop' => 0,
    'is_destruct' => 1,
    'crystal_type' => 'none',
    'consume_type' => 'consume_type_stackable',
  ],
  34601 => 
  [
    'item_id' => 34601,
    'icon' => 'etc_trans_4f_s_b_01',
    'name' => 'Player Commendation - Transformation Scroll: Rose (M]',
    'additionalname' => 'PC-exclusive',
    'description' => 'Inflicts warrior-type attack. Transforms into a Rose (M] for 10 min.',
    'is_trade' => 0,
    'is_drop' => 0,
    'is_destruct' => 1,
    'crystal_type' => 'none',
    'consume_type' => 'consume_type_stackable',
  ],
  34602 => 
  [
    'item_id' => 34602,
    'icon' => 'etc_potion_gold_i00',
    'name' => 'Player Commendation - Quick Healing Potion',
    'additionalname' => 'PC-exclusive',
    'description' => 'Magic potion that instantly restores HP. Cannot be used when HP is full.',
    'is_trade' => 0,
    'is_drop' => 0,
    'is_destruct' => 1,
    'crystal_type' => 'none',
    'consume_type' => 'consume_type_stackable',
  ],
  34603 => 
  [
    'item_id' => 34603,
    'icon' => 'etc_spirit_bullet_white_i00',
    'name' => 'Mysterious No-grade Soulshot',
    'additionalname' => 'Event',
    'description' => 'The power of a higher-level spirit is bestowed upon a weapon, temporarily increasing power of attack. Used with a No-grade weapon.',
    'is_trade' => 1,
    'is_drop' => 1,
    'is_destruct' => 1,
    'crystal_type' => 'none',
    'consume_type' => 'consume_type_stackable',
  ],
  34604 => 
  [
    'item_id' => 34604,
    'icon' => 'etc_spirit_bullet_blue_i00',
    'name' => 'Mysterious Soulshot (D-grade]',
    'additionalname' => 'Event',
    'description' => 'The power of a higher-level spirit is bestowed upon a weapon, temporarily increasing power of attack. Used with a D-grade weapon.',
    'is_trade' => 1,
    'is_drop' => 1,
    'is_destruct' => 1,
    'crystal_type' => 'd',
    'consume_type' => 'consume_type_stackable',
  ],
  34605 => 
  [
    'item_id' => 34605,
    'icon' => 'etc_spirit_bullet_green_i00',
    'name' => 'Mysterious Soulshot (C-grade]',
    'additionalname' => 'Event',
    'description' => 'The power of a higher-level spirit is bestowed upon a weapon, temporarily increasing power of attack. Used with a C-grade weapon.',
    'is_trade' => 1,
    'is_drop' => 1,
    'is_destruct' => 1,
    'crystal_type' => 'c',
    'consume_type' => 'consume_type_stackable',
  ],
  34606 => 
  [
    'item_id' => 34606,
    'icon' => 'etc_spirit_bullet_red_i00',
    'name' => 'Mysterious Soulshot (B-grade]',
    'additionalname' => 'Event',
    'description' => 'The power of a higher-level spirit is bestowed upon a weapon, temporarily increasing power of attack. Used with a B-grade weapon.',
    'is_trade' => 1,
    'is_drop' => 1,
    'is_destruct' => 1,
    'crystal_type' => 'b',
    'consume_type' => 'consume_type_stackable',
  ],
  34607 => 
  [
    'item_id' => 34607,
    'icon' => 'etc_spirit_bullet_silver_i00',
    'name' => 'Mysterious Soulshot (A-grade]',
    'additionalname' => 'Event',
    'description' => 'The power of a higher-level spirit is bestowed upon a weapon, temporarily increasing power of attack. Used with an A-grade weapon.',
    'is_trade' => 1,
    'is_drop' => 1,
    'is_destruct' => 1,
    'crystal_type' => 'a',
    'consume_type' => 'consume_type_stackable',
  ],
  34608 => 
  [
    'item_id' => 34608,
    'icon' => 'etc_spirit_bullet_gold_i00',
    'name' => 'Mysterious Soulshot (S-grade]',
    'additionalname' => 'Event',
    'description' => 'The power of a higher-level spirit is bestowed upon a weapon, temporarily increasing power of attack. Used with an S-grade weapon.',
    'is_trade' => 1,
    'is_drop' => 1,
    'is_destruct' => 1,
    'crystal_type' => 's',
    'consume_type' => 'consume_type_stackable',
  ],
  34609 => 
  [
    'item_id' => 34609,
    'icon' => 'soulshot_r_i00',
    'name' => 'Mysterious Soulshot (R-grade]',
    'additionalname' => 'Event',
    'description' => 'The power of a higher-level spirit is bestowed upon a weapon, temporarily increasing its P. Atk. significantly. Can be used with an R-grade weapon.',
    'is_trade' => 1,
    'is_drop' => 1,
    'is_destruct' => 1,
    'crystal_type' => 'r',
    'consume_type' => 'consume_type_stackable',
  ],
  34610 => 
  [
    'item_id' => 34610,
    'icon' => 'etc_spell_shot_white_i01',
    'name' => 'Mysterious Blessed No-grade Spiritshot',
    'additionalname' => 'Event',
    'description' => 'The power of a higher-level spirit is bestowed upon a weapon, temporarily increasing its magic significantly. Used with No-grade weapons.',
    'is_trade' => 1,
    'is_drop' => 1,
    'is_destruct' => 1,
    'crystal_type' => 'none',
    'consume_type' => 'consume_type_stackable',
  ],
  34611 => 
  [
    'item_id' => 34611,
    'icon' => 'etc_spell_shot_blue_i01',
    'name' => 'Mysterious Blessed Spiritshot (D-grade]',
    'additionalname' => 'Event',
    'description' => 'The power of a higher-level spirit is bestowed upon a weapon, temporarily increasing its magic significantly. Used with D-grade weapons.',
    'is_trade' => 1,
    'is_drop' => 1,
    'is_destruct' => 1,
    'crystal_type' => 'd',
    'consume_type' => 'consume_type_stackable',
  ],
  34612 => 
  [
    'item_id' => 34612,
    'icon' => 'etc_spell_shot_green_i01',
    'name' => 'Mysterious Blessed Spiritshot (C-grade]',
    'additionalname' => 'Event',
    'description' => 'The power of a higher-level spirit is bestowed upon a weapon, temporarily increasing its magic significantly. Used with C-grade weapons.',
    'is_trade' => 1,
    'is_drop' => 1,
    'is_destruct' => 1,
    'crystal_type' => 'c',
    'consume_type' => 'consume_type_stackable',
  ],
  34613 => 
  [
    'item_id' => 34613,
    'icon' => 'etc_spell_shot_red_i01',
    'name' => 'Mysterious Blessed Spiritshot (B-grade]',
    'additionalname' => 'Event',
    'description' => 'The power of a higher-level spirit is bestowed upon a weapon, temporarily increasing its magic significantly. Used with B-grade weapons.',
    'is_trade' => 1,
    'is_drop' => 1,
    'is_destruct' => 1,
    'crystal_type' => 'b',
    'consume_type' => 'consume_type_stackable',
  ],
  34614 => 
  [
    'item_id' => 34614,
    'icon' => 'etc_spell_shot_silver_i01',
    'name' => 'Mysterious Blessed Spiritshot (A-grade]',
    'additionalname' => 'Event',
    'description' => 'The power of a higher-level spirit is bestowed upon a weapon, temporarily increasing its magic significantly. Used with A-grade weapons.',
    'is_trade' => 1,
    'is_drop' => 1,
    'is_destruct' => 1,
    'crystal_type' => 'a',
    'consume_type' => 'consume_type_stackable',
  ],
  34615 => 
  [
    'item_id' => 34615,
    'icon' => 'etc_spell_shot_gold_i01',
    'name' => 'Mysterious Blessed Spiritshot (S-grade]',
    'additionalname' => 'Event',
    'description' => 'The power of a higher-level spirit is bestowed upon a weapon, temporarily increasing its magic significantly. Used with S-grade weapons.',
    'is_trade' => 1,
    'is_drop' => 1,
    'is_destruct' => 1,
    'crystal_type' => 's',
    'consume_type' => 'consume_type_stackable',
  ],
  34616 => 
  [
    'item_id' => 34616,
    'icon' => 'blessed_spiritshot_r_i00',
    'name' => 'Mysterious Blessed Spiritshot (R-grade]',
    'additionalname' => 'Event',
    'description' => 'The power of a higher-level spirit is bestowed upon a weapon, temporarily increasing its M. Atk. significantly. Can be used with an R-grade weapon.',
    'is_trade' => 1,
    'is_drop' => 1,
    'is_destruct' => 1,
    'crystal_type' => 'r',
    'consume_type' => 'consume_type_stackable',
  ],
  34617 => 
  [
    'item_id' => 34617,
    'icon' => 'present_of_destination_event',
    'name' => 'Player Commendation - Agathion\'s Gift',
    'additionalname' => 'PC-exclusive',
    'description' => 'When used, you can receive an Agathion\'s gift.',
    'is_trade' => 0,
    'is_drop' => 0,
    'is_destruct' => 1,
    'crystal_type' => 'none',
    'consume_type' => 'consume_type_stackable',
  ],
  34618 => 
  [
    'item_id' => 34618,
    'icon' => 'etc_fruit_cocktail_i02',
    'name' => 'Player Commendation - Enhanced Cocktail',
    'additionalname' => 'PC-exclusive',
    'description' => 'Cocktail that contains the flavors of many rare fruits. When consumed, you will feel the effects of Horn Melody, Lute Melody, Pipe Organ Melody, Guitar Melody, Harp Melody, and Drum Melody.',
    'is_trade' => 0,
    'is_drop' => 0,
    'is_destruct' => 1,
    'crystal_type' => 'none',
    'consume_type' => 'consume_type_stackable',
  ],
  34619 => 
  [
    'item_id' => 34619,
    'icon' => 'etc_ticket_i00',
    'name' => 'Player Commendation Points Coupon',
    'additionalname' => 'PC-exclusive',
    'description' => 'Click on the item to acquire PC Points.',
    'is_trade' => 0,
    'is_drop' => 0,
    'is_destruct' => 1,
    'crystal_type' => 'none',
    'consume_type' => 'consume_type_stackable',
  ],
  34620 => 
  [
    'item_id' => 34620,
    'icon' => 'etc_fruit_cocktail_i01',
    'name' => 'Heavenly Cocktail',
    'additionalname' => '',
    'description' => 'For 60 minutes, it receives the following level 1 effects: Horn Melody, Guitar Melody, Pipe Organ Melody, Lute Melody, Harp Melody, and Drum Melody. Cooldown is 60 min.',
    'is_trade' => 0,
    'is_drop' => 0,
    'is_destruct' => 1,
    'crystal_type' => 'none',
    'consume_type' => 'consume_type_stackable',
  ],
  34621 => 
  [
    'item_id' => 34621,
    'icon' => 'r85_talisman_md_up_passive',
    'name' => 'Talisman (R-grade] - Half-kill/Lethal Strike Resistance (Passive]',
    'additionalname' => '',
    'description' => 'Increases resistance to half-kill and lethal strike when equipped. Shadow weapon.',
    'is_trade' => 0,
    'is_drop' => 0,
    'is_destruct' => 1,
    'crystal_type' => 'none',
    'consume_type' => 'consume_type_normal',
  ],
  34622 => 
  [
    'item_id' => 34622,
    'icon' => 'r85_talisman_md_up_passive',
    'name' => 'Talisman (R-grade] - Half-kill/Lethal Strike Resistance (Active]',
    'additionalname' => '',
    'description' => 'Increases resistance to half-kill and lethal strike when used. Shadow weapon.',
    'is_trade' => 0,
    'is_drop' => 0,
    'is_destruct' => 1,
    'crystal_type' => 'none',
    'consume_type' => 'consume_type_normal',
  ],
  34623 => 
  [
    'item_id' => 34623,
    'icon' => 'pi_shirt_of_wolf_2nd_fire',
    'name' => 'Pa\'agrio\'s Shirt',
    'additionalname' => '',
    'description' => 'Magic shirt filled with the power of Pa\'agrio, the god of fire.
Can be enchanted to +10 using Elemental Shirt Enchant Scrolls. When enchanted to +7 or above, can remove abnormal conditions and use the ultimate invincibility skill for a certain amount of time.',
    'is_trade' => 0,
    'is_drop' => 0,
    'is_destruct' => 1,
    'crystal_type' => 'none',
    'consume_type' => 'consume_type_normal',
  ],
  34624 => 
  [
    'item_id' => 34624,
    'icon' => 'pi_shirt_of_wolf_2nd_wind',
    'name' => 'Sayha\'s Shirt',
    'additionalname' => '',
    'description' => 'Magic shirt filled with the power of Sayha, the god of wind.
Can be enchanted to +10 using Elemental Shirt Enchant Scrolls. When enchanted to +7 or above, can use a portal teleport skill that allows you to create a portal at a selected location and teleport to that portal. No effect in the Olympiad.',
    'is_trade' => 0,
    'is_drop' => 0,
    'is_destruct' => 1,
    'crystal_type' => 'none',
    'consume_type' => 'consume_type_normal',
  ],
  34625 => 
  [
    'item_id' => 34625,
    'icon' => 'pi_shirt_of_wolf_2nd_water',
    'name' => 'Eva\'s Shirt',
    'additionalname' => '',
    'description' => 'Magic shirt filled with the power of Eva, the goddess of water.
Can be enchanted to +10 using Elemental Shirt Enchant Scrolls. When enchanted to +7 or above, can use HP/MP/CP recovering skills.',
    'is_trade' => 0,
    'is_drop' => 0,
    'is_destruct' => 1,
    'crystal_type' => 'none',
    'consume_type' => 'consume_type_normal',
  ],
  34626 => 
  [
    'item_id' => 34626,
    'icon' => 'pi_shirt_of_wolf_2nd_earth',
    'name' => 'Maphr\'s Shirt',
    'additionalname' => '',
    'description' => 'Magic shirt filled with the power of Maphr, the goddess of earth.
Can be enchanted to +10 using Elemental Shirt Enchant Scrolls. When enchanted to +7 or above, the enchant success rate is increased. No effect in the Olympiad.',
    'is_trade' => 0,
    'is_drop' => 0,
    'is_destruct' => 1,
    'crystal_type' => 'none',
    'consume_type' => 'consume_type_normal',
  ],
  34627 => 
  [
    'item_id' => 34627,
    'icon' => 'g_scrl_of_ench_wolf_shirt',
    'name' => 'Scroll: Enchant Elemental Shirt',
    'additionalname' => '',
    'description' => 'Enchant scroll for t-shirts. When enchanted, increases P. Def. and M. Def. by 1. P. Def. + 3 starting from + 4. Can be safely enchanted to + 3 and up to a maximum of + 10. From + 4, basic abilities (CON, MEN, STR, INT, DEX, WT] are raised in stages. Depending on the shirt type, various additional options can be applied from + 4 to + 10.',
    'is_trade' => 1,
    'is_drop' => 0,
    'is_destruct' => 1,
    'crystal_type' => 'none',
    'consume_type' => 'consume_type_stackable',
  ],
  34628 => 
  [
    'item_id' => 34628,
    'icon' => 'etc_fruit_juice_glass_bottle_i05',
    'name' => 'Einhasad\'s Energy',
    'additionalname' => '',
    'description' => 'Vitality is replenished for 1 hr.',
    'is_trade' => 0,
    'is_drop' => 0,
    'is_destruct' => 1,
    'crystal_type' => 'none',
    'consume_type' => 'consume_type_stackable',
  ],
  34629 => 
  [
    'item_id' => 34629,
    'icon' => 'accessory_eye_bandage_i00',
    'name' => 'Pirate\'s Eyepatch',
    'additionalname' => '',
    'description' => 'Pirate\'s Eyepatch',
    'is_trade' => 1,
    'is_drop' => 1,
    'is_destruct' => 1,
    'crystal_type' => 'none',
    'consume_type' => 'consume_type_normal',
  ],
  34630 => 
  [
    'item_id' => 34630,
    'icon' => 'accessory_outlaw_eyepatch_i00',
    'name' => 'Outlaw\'s Eyepatch',
    'additionalname' => '',
    'description' => 'Outlaw\'s Eyepatch',
    'is_trade' => 1,
    'is_drop' => 1,
    'is_destruct' => 1,
    'crystal_type' => 'none',
    'consume_type' => 'consume_type_normal',
  ],
  34631 => 
  [
    'item_id' => 34631,
    'icon' => 'Accessary_one_eye_i00',
    'name' => 'Eyepatch',
    'additionalname' => '',
    'description' => 'Eyepatch',
    'is_trade' => 1,
    'is_drop' => 1,
    'is_destruct' => 1,
    'crystal_type' => 'none',
    'consume_type' => 'consume_type_normal',
  ],
  34632 => 
  [
    'item_id' => 34632,
    'icon' => 'accessory_party_hat_i00',
    'name' => 'Party Hat',
    'additionalname' => '',
    'description' => 'Party Hat',
    'is_trade' => 1,
    'is_drop' => 1,
    'is_destruct' => 1,
    'crystal_type' => 'none',
    'consume_type' => 'consume_type_normal',
  ],
  34633 => 
  [
    'item_id' => 34633,
    'icon' => 'accessory_angel_ring_i00',
    'name' => 'Refined Angel Ring',
    'additionalname' => '',
    'description' => 'Refined Angel Ring',
    'is_trade' => 1,
    'is_drop' => 1,
    'is_destruct' => 1,
    'crystal_type' => 'none',
    'consume_type' => 'consume_type_normal',
  ],
  34634 => 
  [
    'item_id' => 34634,
    'icon' => 'accessory_devil_horn_i00',
    'name' => 'Refined Devil Horn',
    'additionalname' => '',
    'description' => 'Refined Devil Horn',
    'is_trade' => 1,
    'is_drop' => 1,
    'is_destruct' => 1,
    'crystal_type' => 'none',
    'consume_type' => 'consume_type_normal',
  ],
  34635 => 
  [
    'item_id' => 34635,
    'icon' => 'accessory_eye_bandage_i00',
    'name' => 'Pirate\'s Eyepatch - STR Pendant',
    'additionalname' => '',
    'description' => 'Can increases STR by equipping the Pirate\'s Eyepatch.',
    'is_trade' => 1,
    'is_drop' => 1,
    'is_destruct' => 1,
    'crystal_type' => 'none',
    'consume_type' => 'consume_type_normal',
  ],
  34636 => 
  [
    'item_id' => 34636,
    'icon' => 'accessory_eye_bandage_i00',
    'name' => 'Pirate\'s Eyepatch - DEX Pendant',
    'additionalname' => '',
    'description' => 'Can increases DEX by equipping the Pirate\'s Eyepatch.',
    'is_trade' => 1,
    'is_drop' => 1,
    'is_destruct' => 1,
    'crystal_type' => 'none',
    'consume_type' => 'consume_type_normal',
  ],
  34637 => 
  [
    'item_id' => 34637,
    'icon' => 'accessory_outlaw_eyepatch_i00',
    'name' => 'Outlaw\'s Eyepatch - CON Pendant',
    'additionalname' => '',
    'description' => 'Can increases CON by equipping the Outlaw\'s Eyepatch.',
    'is_trade' => 1,
    'is_drop' => 1,
    'is_destruct' => 1,
    'crystal_type' => 'none',
    'consume_type' => 'consume_type_normal',
  ],
  34638 => 
  [
    'item_id' => 34638,
    'icon' => 'accessory_outlaw_eyepatch_i00',
    'name' => 'Outlaw\'s Eyepatch - MEN Pendant',
    'additionalname' => '',
    'description' => 'Can increases MEN by equipping the Outlaw\'s Eyepatch.',
    'is_trade' => 1,
    'is_drop' => 1,
    'is_destruct' => 1,
    'crystal_type' => 'none',
    'consume_type' => 'consume_type_normal',
  ],
  34639 => 
  [
    'item_id' => 34639,
    'icon' => 'Accessary_one_eye_i00',
    'name' => 'Eyepatch - INT Pendant',
    'additionalname' => '',
    'description' => 'Can increases INT by equipping the Eyepatch.',
    'is_trade' => 1,
    'is_drop' => 1,
    'is_destruct' => 1,
    'crystal_type' => 'none',
    'consume_type' => 'consume_type_normal',
  ],
  34640 => 
  [
    'item_id' => 34640,
    'icon' => 'Accessary_one_eye_i00',
    'name' => 'Eyepatch - WIT Pendant',
    'additionalname' => '',
    'description' => 'Can increases WIT by equipping the Eyepatch.',
    'is_trade' => 1,
    'is_drop' => 1,
    'is_destruct' => 1,
    'crystal_type' => 'none',
    'consume_type' => 'consume_type_normal',
  ],
  34641 => 
  [
    'item_id' => 34641,
    'icon' => 'accessory_party_hat_i00',
    'name' => 'Party Hat - Critical Rate Pendant',
    'additionalname' => '',
    'description' => 'Can increases P. Critical Rate by equipping a Party Hat.',
    'is_trade' => 1,
    'is_drop' => 1,
    'is_destruct' => 1,
    'crystal_type' => 'none',
    'consume_type' => 'consume_type_normal',
  ],
  34642 => 
  [
    'item_id' => 34642,
    'icon' => 'accessory_party_hat_i00',
    'name' => 'Party Hat - Critical Damage Pendant',
    'additionalname' => '',
    'description' => 'Can increases P. Critical Damage by equipping a Party Hat.',
    'is_trade' => 1,
    'is_drop' => 1,
    'is_destruct' => 1,
    'crystal_type' => 'none',
    'consume_type' => 'consume_type_normal',
  ],
  34643 => 
  [
    'item_id' => 34643,
    'icon' => 'accessory_angel_ring_i00',
    'name' => 'Refined Angel Ring - P. Def. Pendant',
    'additionalname' => '',
    'description' => 'Can P. Def. + equipping a Refined Angel Ring.',
    'is_trade' => 1,
    'is_drop' => 1,
    'is_destruct' => 1,
    'crystal_type' => 'none',
    'consume_type' => 'consume_type_normal',
  ],
  34644 => 
  [
    'item_id' => 34644,
    'icon' => 'accessory_angel_ring_i00',
    'name' => 'Refined Angel Ring - M. Def. Pendant',
    'additionalname' => '',
    'description' => 'Can M. Def. + equipping a Refined Angel Ring.',
    'is_trade' => 1,
    'is_drop' => 1,
    'is_destruct' => 1,
    'crystal_type' => 'none',
    'consume_type' => 'consume_type_normal',
  ],
  34645 => 
  [
    'item_id' => 34645,
    'icon' => 'accessory_angel_ring_i00',
    'name' => 'Refined Angel Ring - Evasion Pendant',
    'additionalname' => '',
    'description' => 'Can increases Evasion by equipping a Refined Angel Ring.',
    'is_trade' => 1,
    'is_drop' => 1,
    'is_destruct' => 1,
    'crystal_type' => 'none',
    'consume_type' => 'consume_type_normal',
  ],
  34646 => 
  [
    'item_id' => 34646,
    'icon' => 'accessory_devil_horn_i00',
    'name' => 'Refined Devil Horn - P. Atk. Pendant',
    'additionalname' => '',
    'description' => 'Can P. Atk. + equipping a Refined Devil Horn.',
    'is_trade' => 1,
    'is_drop' => 1,
    'is_destruct' => 1,
    'crystal_type' => 'none',
    'consume_type' => 'consume_type_normal',
  ],
  34647 => 
  [
    'item_id' => 34647,
    'icon' => 'accessory_devil_horn_i00',
    'name' => 'Refined Devil Horn - M. Atk. Pendant',
    'additionalname' => '',
    'description' => 'Can M. Atk. + equipping a Refined Devil Horn.',
    'is_trade' => 1,
    'is_drop' => 1,
    'is_destruct' => 1,
    'crystal_type' => 'none',
    'consume_type' => 'consume_type_normal',
  ],
  34648 => 
  [
    'item_id' => 34648,
    'icon' => 'accessory_devil_horn_i00',
    'name' => 'Refined Devil Horn - Accuracy Pendant',
    'additionalname' => '',
    'description' => 'Can increases Accuracy by equipping a Refined Devil Horn.',
    'is_trade' => 1,
    'is_drop' => 1,
    'is_destruct' => 1,
    'crystal_type' => 'none',
    'consume_type' => 'consume_type_normal',
  ],
  34649 => 
  [
    'item_id' => 34649,
    'icon' => 'etc_fire_stone_i00',
    'name' => 'Fire Stone Fragment',
    'additionalname' => '',
    'description' => 'Can infuse a bound item or item acquired through mentor/mentee with the fire attribute.',
    'is_trade' => 1,
    'is_drop' => 1,
    'is_destruct' => 1,
    'crystal_type' => 'none',
    'consume_type' => 'consume_type_stackable',
  ],
  34650 => 
  [
    'item_id' => 34650,
    'icon' => 'etc_water_stone_i00',
    'name' => 'Water Stone Fragment',
    'additionalname' => '',
    'description' => 'Can infuse a bound item or item acquired through mentor/mentee with the water attribute.',
    'is_trade' => 1,
    'is_drop' => 1,
    'is_destruct' => 1,
    'crystal_type' => 'none',
    'consume_type' => 'consume_type_stackable',
  ],
  34651 => 
  [
    'item_id' => 34651,
    'icon' => 'etc_wind_stone_i00',
    'name' => 'Wind Stone Fragment',
    'additionalname' => '',
    'description' => 'Can infuse a bound item or item acquired through mentor/mentee with the wind attribute.',
    'is_trade' => 1,
    'is_drop' => 1,
    'is_destruct' => 1,
    'crystal_type' => 'none',
    'consume_type' => 'consume_type_stackable',
  ],
  34652 => 
  [
    'item_id' => 34652,
    'icon' => 'etc_earth_stone_i00',
    'name' => 'Earth Stone Fragment',
    'additionalname' => '',
    'description' => 'Can infuse a bound item or item acquired through mentor/mentee with the earth attribute.',
    'is_trade' => 1,
    'is_drop' => 1,
    'is_destruct' => 1,
    'crystal_type' => 'none',
    'consume_type' => 'consume_type_stackable',
  ],
  34653 => 
  [
    'item_id' => 34653,
    'icon' => 'etc_holy_stone_i00',
    'name' => 'Holy Stone Fragment',
    'additionalname' => '',
    'description' => 'Can infuse a bound item or item acquired through mentor/mentee with the holy attribute.',
    'is_trade' => 1,
    'is_drop' => 1,
    'is_destruct' => 1,
    'crystal_type' => 'none',
    'consume_type' => 'consume_type_stackable',
  ],
  34654 => 
  [
    'item_id' => 34654,
    'icon' => 'etc_unholy_stone_i00',
    'name' => 'Dark Stone Fragment',
    'additionalname' => '',
    'description' => 'Can infuse a bound item or item acquired through mentor/mentee with the dark attribute.',
    'is_trade' => 1,
    'is_drop' => 1,
    'is_destruct' => 1,
    'crystal_type' => 'none',
    'consume_type' => 'consume_type_stackable',
  ],
  34655 => 
  [
    'item_id' => 34655,
    'icon' => 'etc_fire_crystal_i00',
    'name' => 'Fire Crystal Fragment',
    'additionalname' => '',
    'description' => 'Can infuse a bound item or item acquired through mentor/mentee with the fire attribute.',
    'is_trade' => 1,
    'is_drop' => 1,
    'is_destruct' => 1,
    'crystal_type' => 'none',
    'consume_type' => 'consume_type_stackable',
  ],
  34656 => 
  [
    'item_id' => 34656,
    'icon' => 'etc_water_crystal_i00',
    'name' => 'Water Crystal Fragment',
    'additionalname' => '',
    'description' => 'Can infuse a bound item or item acquired through mentor/mentee with the water attribute.',
    'is_trade' => 1,
    'is_drop' => 1,
    'is_destruct' => 1,
    'crystal_type' => 'none',
    'consume_type' => 'consume_type_stackable',
  ],
  34657 => 
  [
    'item_id' => 34657,
    'icon' => 'etc_wind_crystal_i00',
    'name' => 'Wind Crystal Fragment',
    'additionalname' => '',
    'description' => 'Can infuse a bound item or item acquired through mentor/mentee with the wind attribute.',
    'is_trade' => 1,
    'is_drop' => 1,
    'is_destruct' => 1,
    'crystal_type' => 'none',
    'consume_type' => 'consume_type_stackable',
  ],
  34658 => 
  [
    'item_id' => 34658,
    'icon' => 'etc_earth_crystal_i00',
    'name' => 'Earth Crystal Fragment',
    'additionalname' => '',
    'description' => 'Can infuse a bound item or item acquired through mentor/mentee with the earth attribute.',
    'is_trade' => 1,
    'is_drop' => 1,
    'is_destruct' => 1,
    'crystal_type' => 'none',
    'consume_type' => 'consume_type_stackable',
  ],
  34659 => 
  [
    'item_id' => 34659,
    'icon' => 'etc_holy_crystal_i00',
    'name' => 'Holy Crystal Fragment',
    'additionalname' => '',
    'description' => 'Can infuse a bound item or item acquired through mentor/mentee with the holy attribute.',
    'is_trade' => 1,
    'is_drop' => 1,
    'is_destruct' => 1,
    'crystal_type' => 'none',
    'consume_type' => 'consume_type_stackable',
  ],
  34660 => 
  [
    'item_id' => 34660,
    'icon' => 'etc_unholy_crystal_i00',
    'name' => 'Dark Crystal Fragment',
    'additionalname' => '',
    'description' => 'Can infuse a bound item or item acquired through mentor/mentee with the dark attribute.',
    'is_trade' => 1,
    'is_drop' => 1,
    'is_destruct' => 1,
    'crystal_type' => 'none',
    'consume_type' => 'consume_type_stackable',
  ],
  34661 => 
  [
    'item_id' => 34661,
    'icon' => 'etc_fire_stone_i00',
    'name' => 'Fire Stone (+ 60]',
    'additionalname' => '',
    'description' => 'Can bestow fire attribute up to 60 at one time. Additional Elemental attributes cannot be bestowed. Up to 3 types of attributes can be enchanted for armor. Opposite attributes cannot be bestowed at the same time.',
    'is_trade' => 1,
    'is_drop' => 1,
    'is_destruct' => 1,
    'crystal_type' => 'none',
    'consume_type' => 'consume_type_stackable',
  ],
  34662 => 
  [
    'item_id' => 34662,
    'icon' => 'etc_water_stone_i00',
    'name' => 'Water Stone (+ 60]',
    'additionalname' => '',
    'description' => 'Can bestow water attribute up to 60 at one time. Additional Elemental attributes cannot be bestowed. Up to 3 types of attributes can be enchanted for armor. Opposite attributes cannot be bestowed at the same time.',
    'is_trade' => 1,
    'is_drop' => 1,
    'is_destruct' => 1,
    'crystal_type' => 'none',
    'consume_type' => 'consume_type_stackable',
  ],
  34663 => 
  [
    'item_id' => 34663,
    'icon' => 'etc_earth_stone_i00',
    'name' => 'Earth Stone (+ 60]',
    'additionalname' => '',
    'description' => 'Can bestow earth attribute up to 60 at one time. Additional Elemental attributes cannot be bestowed. Up to 3 types of attributes can be enchanted for armor. Opposite attributes cannot be bestowed at the same time.',
    'is_trade' => 1,
    'is_drop' => 1,
    'is_destruct' => 1,
    'crystal_type' => 'none',
    'consume_type' => 'consume_type_stackable',
  ],
  34664 => 
  [
    'item_id' => 34664,
    'icon' => 'etc_wind_stone_i00',
    'name' => 'Wind Stone (+ 60]',
    'additionalname' => '',
    'description' => 'Can bestow wind attribute up to 60 at one time. Additional Elemental attributes cannot be bestowed. Up to 3 types of attributes can be enchanted for armor. Opposite attributes cannot be bestowed at the same time.',
    'is_trade' => 1,
    'is_drop' => 1,
    'is_destruct' => 1,
    'crystal_type' => 'none',
    'consume_type' => 'consume_type_stackable',
  ],
  34665 => 
  [
    'item_id' => 34665,
    'icon' => 'etc_unholy_stone_i00',
    'name' => 'Dark Stone (+ 60]',
    'additionalname' => '',
    'description' => 'Can bestow dark attribute up to 60 at one time. Additional Elemental attributes cannot be bestowed. Up to 3 types of attributes can be enchanted for armor. Opposite attributes cannot be bestowed at the same time.',
    'is_trade' => 1,
    'is_drop' => 1,
    'is_destruct' => 1,
    'crystal_type' => 'none',
    'consume_type' => 'consume_type_stackable',
  ],
  34666 => 
  [
    'item_id' => 34666,
    'icon' => 'etc_holy_stone_i00',
    'name' => 'Holy Stone (+ 60]',
    'additionalname' => '',
    'description' => 'Can bestow holy attribute up to 60 at one time. Additional Elemental attributes cannot be bestowed. Up to 3 types of attributes can be enchanted for armor. Opposite attributes cannot be bestowed at the same time.',
    'is_trade' => 1,
    'is_drop' => 1,
    'is_destruct' => 1,
    'crystal_type' => 'none',
    'consume_type' => 'consume_type_stackable',
  ],
  34667 => 
  [
    'item_id' => 34667,
    'icon' => 'etc_fire_stone_i00',
    'name' => 'Fire Stone (+ 150]',
    'additionalname' => '',
    'description' => 'Can bestow fire attribute up to level 3 at one time. Additional Elemental attributes cannot be bestowed. Up to 3 types of attributes can be enchanted for armor. Opposite attributes cannot be bestowed at the same time.',
    'is_trade' => 1,
    'is_drop' => 1,
    'is_destruct' => 1,
    'crystal_type' => 'none',
    'consume_type' => 'consume_type_stackable',
  ],
  34668 => 
  [
    'item_id' => 34668,
    'icon' => 'etc_water_stone_i00',
    'name' => 'Water Stone (+ 150]',
    'additionalname' => '',
    'description' => 'Can bestow water attribute up to level 3 at one time. Additional Elemental attributes cannot be bestowed. Up to 3 types of attributes can be enchanted for armor. Opposite attributes cannot be bestowed at the same time.',
    'is_trade' => 1,
    'is_drop' => 1,
    'is_destruct' => 1,
    'crystal_type' => 'none',
    'consume_type' => 'consume_type_stackable',
  ],
  34669 => 
  [
    'item_id' => 34669,
    'icon' => 'etc_earth_stone_i00',
    'name' => 'Earth Stone (+ 150]',
    'additionalname' => '',
    'description' => 'Can bestow earth attribute up to level 3 at one time. Additional Elemental attributes cannot be bestowed. Up to 3 types of attributes can be enchanted for armor. Opposite attributes cannot be bestowed at the same time.',
    'is_trade' => 1,
    'is_drop' => 1,
    'is_destruct' => 1,
    'crystal_type' => 'none',
    'consume_type' => 'consume_type_stackable',
  ],
  34670 => 
  [
    'item_id' => 34670,
    'icon' => 'etc_wind_stone_i00',
    'name' => 'Wind Stone (+ 150]',
    'additionalname' => '',
    'description' => 'Can bestow wind attribute up to level 3 at one time. Additional Elemental attributes cannot be bestowed. Up to 3 types of attributes can be enchanted for armor. Opposite attributes cannot be bestowed at the same time.',
    'is_trade' => 1,
    'is_drop' => 1,
    'is_destruct' => 1,
    'crystal_type' => 'none',
    'consume_type' => 'consume_type_stackable',
  ],
  34671 => 
  [
    'item_id' => 34671,
    'icon' => 'etc_unholy_stone_i00',
    'name' => 'Dark Stone (+ 150]',
    'additionalname' => '',
    'description' => 'Can bestow dark attribute up to level 3 at one time. Additional Elemental attributes cannot be bestowed. Up to 3 types of attributes can be enchanted for armor. Opposite attributes cannot be bestowed at the same time.',
    'is_trade' => 1,
    'is_drop' => 1,
    'is_destruct' => 1,
    'crystal_type' => 'none',
    'consume_type' => 'consume_type_stackable',
  ],
  34672 => 
  [
    'item_id' => 34672,
    'icon' => 'etc_holy_stone_i00',
    'name' => 'Holy Stone (+ 150]',
    'additionalname' => '',
    'description' => 'Can bestow holy attribute up to level 3 at one time. Additional Elemental attributes cannot be bestowed. Up to 3 types of attributes can be enchanted for armor. Opposite attributes cannot be bestowed at the same time.',
    'is_trade' => 1,
    'is_drop' => 1,
    'is_destruct' => 1,
    'crystal_type' => 'none',
    'consume_type' => 'consume_type_stackable',
  ],
  34673 => 
  [
    'item_id' => 34673,
    'icon' => 'scroll_of_unidentify_wp_d',
    'name' => 'Scroll: Seal Weapon (D-grade]',
    'additionalname' => '',
    'description' => 'Scroll that returns an item from bound to unidentified status. All enchant values are reset.',
    'is_trade' => 1,
    'is_drop' => 1,
    'is_destruct' => 1,
    'crystal_type' => 'none',
    'consume_type' => 'consume_type_stackable',
  ],
  34674 => 
  [
    'item_id' => 34674,
    'icon' => 'scroll_of_unidentify_wp_c',
    'name' => 'Scroll: Seal Weapon (C-grade]',
    'additionalname' => '',
    'description' => 'Scroll that returns an item from bound to unidentified status. All enchant values are reset.',
    'is_trade' => 1,
    'is_drop' => 1,
    'is_destruct' => 1,
    'crystal_type' => 'none',
    'consume_type' => 'consume_type_stackable',
  ],
  34675 => 
  [
    'item_id' => 34675,
    'icon' => 'scroll_of_unidentify_wp_b',
    'name' => 'Scroll: Seal Weapon (B-grade]',
    'additionalname' => '',
    'description' => 'Scroll that returns an item from bound to unidentified status. All enchant values are reset.',
    'is_trade' => 1,
    'is_drop' => 1,
    'is_destruct' => 1,
    'crystal_type' => 'none',
    'consume_type' => 'consume_type_stackable',
  ],
  34676 => 
  [
    'item_id' => 34676,
    'icon' => 'scroll_of_unidentify_wp_a',
    'name' => 'Scroll: Seal Weapon (A-grade]',
    'additionalname' => '',
    'description' => 'Scroll that returns an item from bound to unidentified status. All enchant values are reset.',
    'is_trade' => 1,
    'is_drop' => 1,
    'is_destruct' => 1,
    'crystal_type' => 'none',
    'consume_type' => 'consume_type_stackable',
  ],
  34677 => 
  [
    'item_id' => 34677,
    'icon' => 'scroll_of_unidentify_wp_s',
    'name' => 'Scroll: Seal Weapon (S-grade]',
    'additionalname' => '',
    'description' => 'Scroll that returns an item from bound to unidentified status. All enchant values are reset.',
    'is_trade' => 1,
    'is_drop' => 1,
    'is_destruct' => 1,
    'crystal_type' => 'none',
    'consume_type' => 'consume_type_stackable',
  ],
  34678 => 
  [
    'item_id' => 34678,
    'icon' => 'scroll_of_unidentify_wp_s',
    'name' => 'Scroll: Seal Weapon (S80-grade]',
    'additionalname' => '',
    'description' => 'Scroll that returns an item from bound to unidentified status. All enchant values are reset.',
    'is_trade' => 1,
    'is_drop' => 1,
    'is_destruct' => 1,
    'crystal_type' => 'none',
    'consume_type' => 'consume_type_stackable',
  ],
  34679 => 
  [
    'item_id' => 34679,
    'icon' => 'scroll_of_unidentify_wp_r',
    'name' => 'Scroll: Seal Weapon (R-grade]',
    'additionalname' => '',
    'description' => 'Scroll that returns an item from bound to unidentified status. All enchant values are reset.',
    'is_trade' => 1,
    'is_drop' => 1,
    'is_destruct' => 1,
    'crystal_type' => 'none',
    'consume_type' => 'consume_type_stackable',
  ],
  34680 => 
  [
    'item_id' => 34680,
    'icon' => 'scroll_of_unidentify_wp_r',
    'name' => 'Scroll: Seal Weapon (R95-grade]',
    'additionalname' => '',
    'description' => 'Scroll that returns an item from bound to unidentified status. All enchant values are reset.',
    'is_trade' => 1,
    'is_drop' => 1,
    'is_destruct' => 1,
    'crystal_type' => 'none',
    'consume_type' => 'consume_type_stackable',
  ],
  34681 => 
  [
    'item_id' => 34681,
    'icon' => 'scroll_of_unidentify_wp_r',
    'name' => 'Scroll: Seal Weapon (R99-grade]',
    'additionalname' => '',
    'description' => 'Scroll that returns an item from bound to unidentified status. All enchant values are reset.',
    'is_trade' => 1,
    'is_drop' => 1,
    'is_destruct' => 1,
    'crystal_type' => 'none',
    'consume_type' => 'consume_type_stackable',
  ],
  34682 => 
  [
    'item_id' => 34682,
    'icon' => 'scroll_of_unidentify_am_d',
    'name' => 'Scroll: Seal Armor (D-grade]',
    'additionalname' => '',
    'description' => 'Scroll that returns an item from bound to unidentified status. All enchant values are reset.',
    'is_trade' => 1,
    'is_drop' => 1,
    'is_destruct' => 1,
    'crystal_type' => 'none',
    'consume_type' => 'consume_type_stackable',
  ],
  34683 => 
  [
    'item_id' => 34683,
    'icon' => 'scroll_of_unidentify_am_c',
    'name' => 'Scroll: Seal Armor (C-grade]',
    'additionalname' => '',
    'description' => 'Scroll that returns an item from bound to unidentified status. All enchant values are reset.',
    'is_trade' => 1,
    'is_drop' => 1,
    'is_destruct' => 1,
    'crystal_type' => 'none',
    'consume_type' => 'consume_type_stackable',
  ],
  34684 => 
  [
    'item_id' => 34684,
    'icon' => 'scroll_of_unidentify_am_b',
    'name' => 'Scroll: Seal Armor (B-grade]',
    'additionalname' => '',
    'description' => 'Scroll that returns an item from bound to unidentified status. All enchant values are reset.',
    'is_trade' => 1,
    'is_drop' => 1,
    'is_destruct' => 1,
    'crystal_type' => 'none',
    'consume_type' => 'consume_type_stackable',
  ],
  34685 => 
  [
    'item_id' => 34685,
    'icon' => 'scroll_of_unidentify_am_a',
    'name' => 'Scroll: Seal Armor (A-grade]',
    'additionalname' => '',
    'description' => 'Scroll that returns an item from bound to unidentified status. All enchant values are reset.',
    'is_trade' => 1,
    'is_drop' => 1,
    'is_destruct' => 1,
    'crystal_type' => 'none',
    'consume_type' => 'consume_type_stackable',
  ],
  34686 => 
  [
    'item_id' => 34686,
    'icon' => 'scroll_of_unidentify_am_s',
    'name' => 'Scroll: Seal Armor (S-grade]',
    'additionalname' => '',
    'description' => 'Scroll that returns an item from bound to unidentified status. All enchant values are reset.',
    'is_trade' => 1,
    'is_drop' => 1,
    'is_destruct' => 1,
    'crystal_type' => 'none',
    'consume_type' => 'consume_type_stackable',
  ],
  34687 => 
  [
    'item_id' => 34687,
    'icon' => 'scroll_of_unidentify_am_s',
    'name' => 'Scroll: Seal Armor (S80-grade]',
    'additionalname' => '',
    'description' => 'Scroll that returns an item from bound to unidentified status. All enchant values are reset.',
    'is_trade' => 1,
    'is_drop' => 1,
    'is_destruct' => 1,
    'crystal_type' => 'none',
    'consume_type' => 'consume_type_stackable',
  ],
  34688 => 
  [
    'item_id' => 34688,
    'icon' => 'scroll_of_unidentify_am_r',
    'name' => 'Scroll: Seal Armor (R-grade]',
    'additionalname' => '',
    'description' => 'Scroll that returns an item from bound to unidentified status. All enchant values are reset.',
    'is_trade' => 1,
    'is_drop' => 1,
    'is_destruct' => 1,
    'crystal_type' => 'none',
    'consume_type' => 'consume_type_stackable',
  ],
  34689 => 
  [
    'item_id' => 34689,
    'icon' => 'scroll_of_unidentify_am_r',
    'name' => 'Scroll: Seal Armor (R95-grade]',
    'additionalname' => '',
    'description' => 'Scroll that returns an item from bound to unidentified status. All enchant values are reset.',
    'is_trade' => 1,
    'is_drop' => 1,
    'is_destruct' => 1,
    'crystal_type' => 'none',
    'consume_type' => 'consume_type_stackable',
  ],
  34690 => 
  [
    'item_id' => 34690,
    'icon' => 'scroll_of_unidentify_am_r',
    'name' => 'Scroll: Seal Armor (R99-grade]',
    'additionalname' => '',
    'description' => 'Scroll that returns an item from bound to unidentified status. All enchant values are reset.',
    'is_trade' => 1,
    'is_drop' => 1,
    'is_destruct' => 1,
    'crystal_type' => 'none',
    'consume_type' => 'consume_type_stackable',
  ],
  34691 => 
  [
    'item_id' => 34691,
    'icon' => 'event_hero_treasure_box_i00',
    'name' => 'Hair Accessory Pack',
    'additionalname' => '',
    'description' => 'Chest containing Hair Accessory.',
    'is_trade' => 1,
    'is_drop' => 1,
    'is_destruct' => 1,
    'crystal_type' => 'none',
    'consume_type' => 'consume_type_stackable',
  ],
  34692 => 
  [
    'item_id' => 34692,
    'icon' => 'event_hero_treasure_box_i00',
    'name' => 'Pendant Pack',
    'additionalname' => '',
    'description' => 'Chest containing Hair Accessory Pendant.',
    'is_trade' => 1,
    'is_drop' => 1,
    'is_destruct' => 1,
    'crystal_type' => 'none',
    'consume_type' => 'consume_type_stackable',
  ],
  34693 => 
  [
    'item_id' => 34693,
    'icon' => 'event_hero_treasure_box_i00',
    'name' => 'Attribute Stone Fragment Box',
    'additionalname' => '',
    'description' => 'Box containing attribute stone.',
    'is_trade' => 1,
    'is_drop' => 1,
    'is_destruct' => 1,
    'crystal_type' => 'none',
    'consume_type' => 'consume_type_stackable',
  ],
  34694 => 
  [
    'item_id' => 34694,
    'icon' => 'event_hero_treasure_box_i00',
    'name' => 'Hero\'s Lucky Enchant Stone Pack',
    'additionalname' => '',
    'description' => 'Box containing Lucky Enchant Stone.',
    'is_trade' => 1,
    'is_drop' => 1,
    'is_destruct' => 1,
    'crystal_type' => 'none',
    'consume_type' => 'consume_type_stackable',
  ],
  34695 => 
  [
    'item_id' => 34695,
    'icon' => 'event_hero_treasure_box_i00',
    'name' => 'Hero\'s Destruction Enchant Scroll Pack',
    'additionalname' => '',
    'description' => 'Box containing Enchant Scroll of Destruction.',
    'is_trade' => 1,
    'is_drop' => 1,
    'is_destruct' => 1,
    'crystal_type' => 'none',
    'consume_type' => 'consume_type_stackable',
  ],
  34696 => 
  [
    'item_id' => 34696,
    'icon' => 'event_hero_treasure_box_i00',
    'name' => 'Hero\'s Blessed Enchant Scroll Pack',
    'additionalname' => '',
    'description' => 'Box containing Blessed Enchant Scroll.',
    'is_trade' => 1,
    'is_drop' => 1,
    'is_destruct' => 1,
    'crystal_type' => 'none',
    'consume_type' => 'consume_type_stackable',
  ],
  34697 => 
  [
    'item_id' => 34697,
    'icon' => 'event_hero_treasure_box_i00',
    'name' => 'Hero\'s Unbind Scroll Pack',
    'additionalname' => '',
    'description' => 'Box containing Bind Removing Scroll.',
    'is_trade' => 1,
    'is_drop' => 1,
    'is_destruct' => 1,
    'crystal_type' => 'none',
    'consume_type' => 'consume_type_stackable',
  ],
  34698 => 
  [
    'item_id' => 34698,
    'icon' => 'event_hero_treasure_box_i00',
    'name' => 'Hero\'s Attribute Crystal Pack',
    'additionalname' => '',
    'description' => 'Box containing attribute crystal or stone (Super - 60/150].',
    'is_trade' => 1,
    'is_drop' => 1,
    'is_destruct' => 1,
    'crystal_type' => 'none',
    'consume_type' => 'consume_type_stackable',
  ],
  34699 => 
  [
    'item_id' => 34699,
    'icon' => 'event_hero_treasure_box_i00',
    'name' => 'Giant\'s Attribute Crystal Pack',
    'additionalname' => '',
    'description' => 'Item that is added to the Aden reconstruction renewal. It\'s functions have not materialized yet.',
    'is_trade' => 1,
    'is_drop' => 1,
    'is_destruct' => 1,
    'crystal_type' => 'none',
    'consume_type' => 'consume_type_stackable',
  ],
];