<?php return [
  34900 => 
  [
    'item_id' => 34900,
    'icon' => 'etc_coins_black_i00',
    'name' => 'Mysterious Mark',
    'additionalname' => '',
    'description' => 'The power of darkness can be faintly felt. Bring it to the Mysterious Butler in each town.',
    'is_trade' => 0,
    'is_drop' => 0,
    'is_destruct' => 0,
    'crystal_type' => 'none',
    'consume_type' => 'consume_type_stackable',
  ],
  34901 => 
  [
    'item_id' => 34901,
    'icon' => 'etc_paper_white_i00',
    'name' => 'Proof of Alliance',
    'additionalname' => '',
    'description' => 'Item needed for a clan leader to raise his/her clan level to 4. Can only be used by the clan leader.',
    'is_trade' => 0,
    'is_drop' => 0,
    'is_destruct' => 1,
    'crystal_type' => 'none',
    'consume_type' => 'consume_type_stackable',
  ],
  34902 => 
  [
    'item_id' => 34902,
    'icon' => 'etc_paper_blue_i00',
    'name' => 'Proof of Aspiration',
    'additionalname' => '',
    'description' => 'Item needed for a clan leader to raise his/her clan level to 5. Can only be used by the clan leader.',
    'is_trade' => 0,
    'is_drop' => 0,
    'is_destruct' => 1,
    'crystal_type' => 'none',
    'consume_type' => 'consume_type_stackable',
  ],
  34903 => 
  [
    'item_id' => 34903,
    'icon' => 'weapon_apprentices_spellbook_i00',
    'name' => 'Mysterious Shadow',
    'additionalname' => '',
    'description' => 'Item that can only be used in the Ceremony of Chaos Arena. Upon use, becomes hidden and decreases Speed by 30%.',
    'is_trade' => 0,
    'is_drop' => 0,
    'is_destruct' => 1,
    'crystal_type' => 'none',
    'consume_type' => 'consume_type_stackable',
  ],
  34904 => 
  [
    'item_id' => 34904,
    'icon' => 'weapon_apprentices_spellbook_i00',
    'name' => 'Mysterious Power',
    'additionalname' => '',
    'description' => 'Item that can only be used in the Ceremony of Chaos Arena. Your MP and CP are all reduced to 1 but 1/3 of your HP is maintained. Has a 50% chance of inflicting a lethal strike on the target.',
    'is_trade' => 0,
    'is_drop' => 0,
    'is_destruct' => 1,
    'crystal_type' => 'none',
    'consume_type' => 'consume_type_stackable',
  ],
  34905 => 
  [
    'item_id' => 34905,
    'icon' => 'accessory_necklace_of_pet_i00',
    'name' => 'Clan-exclusive Pet (Raccoon]',
    'additionalname' => '',
    'description' => 'Item that summons a nurture-type clan pet (Raccoon]. For 72 hours, you acquire 500 Clan Reputation each time it is summoned, and you have a chance of obtaining an additional item. Only PC\'s who belong to a clan that is above level 5 can summon it.',
    'is_trade' => 1,
    'is_drop' => 1,
    'is_destruct' => 1,
    'crystal_type' => 'none',
    'consume_type' => 'consume_type_normal',
  ],
  34906 => 
  [
    'item_id' => 34906,
    'icon' => 'accessory_necklace_of_pet_i00',
    'name' => 'Clan-exclusive Pet (White Cat]',
    'additionalname' => '',
    'description' => 'Item that summons a nurture-type clan pet (White Cat]. For 72 hours, you acquire 500 Clan Reputation each time it is summoned, and you have a chance of obtaining an additional item. Only PC\'s who belong to a clan that is above level 5 can summon it.',
    'is_trade' => 1,
    'is_drop' => 1,
    'is_destruct' => 1,
    'crystal_type' => 'none',
    'consume_type' => 'consume_type_normal',
  ],
  34907 => 
  [
    'item_id' => 34907,
    'icon' => 'accessory_necklace_of_pet_i00',
    'name' => 'Clan-exclusive Pet (Desert Fox]',
    'additionalname' => '',
    'description' => 'Item that summons a nurture-type clan pet (Desert Fox]. For 72 hours, you acquire 500 Clan Reputation each time it is summoned, and you have a chance of obtaining an additional item. Only PC\'s who belong to a clan that is above level 5 can summon it.',
    'is_trade' => 1,
    'is_drop' => 1,
    'is_destruct' => 1,
    'crystal_type' => 'none',
    'consume_type' => 'consume_type_normal',
  ],
  34908 => 
  [
    'item_id' => 34908,
    'icon' => 'accessory_necklace_of_pet_i00',
    'name' => 'Clan-exclusive Pet for Training',
    'additionalname' => '',
    'description' => 'Item that summons a Clan-exclusive Pet for Training. If the pet\'s HP becomes 0 within 30 seconds, you gain 50 Clan Reputation and 10 Individual Fame.',
    'is_trade' => 0,
    'is_drop' => 0,
    'is_destruct' => 1,
    'crystal_type' => 'none',
    'consume_type' => 'consume_type_normal',
  ],
  34909 => 
  [
    'item_id' => 34909,
    'icon' => 'scroll_of_verification_i00',
    'name' => 'Mark of the Resistance',
    'additionalname' => '',
    'description' => 'Mark received for helping the Zofan Resistance. It is need to enter the Tauti battle.',
    'is_trade' => 0,
    'is_drop' => 0,
    'is_destruct' => 1,
    'crystal_type' => 'none',
    'consume_type' => 'consume_type_stackable',
  ],
  34910 => 
  [
    'item_id' => 34910,
    'icon' => 'scroll_of_verification_i01',
    'name' => 'Aku\'s Mark',
    'additionalname' => '',
    'description' => 'Mark received for helping Aku. It is need to enter the Tauti battle (limited].',
    'is_trade' => 0,
    'is_drop' => 0,
    'is_destruct' => 1,
    'crystal_type' => 'none',
    'consume_type' => 'consume_type_stackable',
  ],
  34911 => 
  [
    'item_id' => 34911,
    'icon' => 'etc_spell_books_red_i00',
    'name' => 'Ruler\'s Authority',
    'additionalname' => '',
    'description' => 'Item given to the winner of the tournament held in the Mysterious Mansion. Increases Max HP/MP/CP by 500, Weight Gauge by 12000, damage inflicted during PvP by 5%, Damage Reflect Resistance by 5, and Attribute Resistance by 10. Also increases HP/MP Recovery Rate and Inventory Slot numbers. Decreases damage received during PvP by 6%. You can use these item skills only during the week of victory.',
    'is_trade' => 0,
    'is_drop' => 0,
    'is_destruct' => 1,
    'crystal_type' => 'none',
    'consume_type' => 'consume_type_stackable',
  ],
  34912 => 
  [
    'item_id' => 34912,
    'icon' => 'etc_crystal_ball_white_i00',
    'name' => 'Summoning Stone',
    'additionalname' => '',
    'description' => 'Summoning Stone that can be used during the Noblesse quest. Double-click on it to summon the Water Spirit Lanya.',
    'is_trade' => 0,
    'is_drop' => 0,
    'is_destruct' => 0,
    'crystal_type' => 'none',
    'consume_type' => 'consume_type_normal',
  ],
  34913 => 
  [
    'item_id' => 34913,
    'icon' => 'etc_ancient_treasure_sack_i00',
    'name' => 'Sack Containing Ingredients',
    'additionalname' => '',
    'description' => 'Sack containing ingredients. it contains 4 types of ingredients needed to make a weapon that purifies the water of Eva, the goddess of water.',
    'is_trade' => 0,
    'is_drop' => 0,
    'is_destruct' => 0,
    'crystal_type' => 'none',
    'consume_type' => 'consume_type_stackable',
  ],
  34914 => 
  [
    'item_id' => 34914,
    'icon' => 'etc_jewel_box_i00',
    'name' => 'Transport Goods - Aden',
    'additionalname' => '',
    'description' => 'Box stolen from the transportation unit . Give it to the revolutionaries to receive a campaign reward.',
    'is_trade' => 0,
    'is_drop' => 0,
    'is_destruct' => 1,
    'crystal_type' => 'none',
    'consume_type' => 'consume_type_stackable',
  ],
  34915 => 
  [
    'item_id' => 34915,
    'icon' => 'etc_treasure_box_i02',
    'name' => 'Hard Transport Goods - Aden',
    'additionalname' => '',
    'description' => 'Box stolen from the transportation cart. Give it to the revolutionaries to receive a campaign reward.',
    'is_trade' => 0,
    'is_drop' => 0,
    'is_destruct' => 1,
    'crystal_type' => 'none',
    'consume_type' => 'consume_type_stackable',
  ],
  34916 => 
  [
    'item_id' => 34916,
    'icon' => 'etc_jewel_box_i00',
    'name' => 'Transport Box',
    'additionalname' => '',
    'description' => 'Box stolen from the transportation unit . Give it to the revolutionaries to receive a campaign reward.',
    'is_trade' => 0,
    'is_drop' => 0,
    'is_destruct' => 1,
    'crystal_type' => 'none',
    'consume_type' => 'consume_type_stackable',
  ],
  34917 => 
  [
    'item_id' => 34917,
    'icon' => 'etc_treasure_box_i02',
    'name' => 'Greater Transport Box',
    'additionalname' => '',
    'description' => 'Box stolen from the transportation cart. Give it to the revolutionaries to receive a campaign reward.',
    'is_trade' => 0,
    'is_drop' => 0,
    'is_destruct' => 1,
    'crystal_type' => 'none',
    'consume_type' => 'consume_type_stackable',
  ],
  34918 => 
  [
    'item_id' => 34918,
    'icon' => 'etc_treasure_box_i00',
    'name' => 'Treasure Chest of the King of Aden',
    'additionalname' => '',
    'description' => 'Precious treasure chest being delivered to the King of Aden. Double-click on it to obtain a reward.',
    'is_trade' => 0,
    'is_drop' => 0,
    'is_destruct' => 1,
    'crystal_type' => 'none',
    'consume_type' => 'consume_type_stackable',
  ],
  34919 => 
  [
    'item_id' => 34919,
    'icon' => 'etc_pouch_brown_i00',
    'name' => 'Tax Bundle',
    'additionalname' => '',
    'description' => 'Deliver to the Revolutionaries to receive a Campaign Reward.',
    'is_trade' => 0,
    'is_drop' => 0,
    'is_destruct' => 1,
    'crystal_type' => 'none',
    'consume_type' => 'consume_type_stackable',
  ],
  34920 => 
  [
    'item_id' => 34920,
    'icon' => 'etc_treasure_box_i01',
    'name' => 'Treasure Chest of the King of Rune',
    'additionalname' => '',
    'description' => 'Precious treasure chest being delivered to the King of Rune. Double-click on it to obtain a reward.',
    'is_trade' => 0,
    'is_drop' => 0,
    'is_destruct' => 1,
    'crystal_type' => 'none',
    'consume_type' => 'consume_type_stackable',
  ],
  34921 => 
  [
    'item_id' => 34921,
    'icon' => 'weapon_sword_of_revolution_i00',
    'name' => 'Revolutionary\'s Sword',
    'additionalname' => '',
    'description' => 'Item used by the revolutionaries during an attack on the transportation unit . It can use powerful skills. Can only be used on the siege battlefield. Can only be used by characters who are above level 40.',
    'is_trade' => 0,
    'is_drop' => 0,
    'is_destruct' => 1,
    'crystal_type' => 'd',
    'consume_type' => 'consume_type_normal',
  ],
  34922 => 
  [
    'item_id' => 34922,
    'icon' => 'weapon_gastraphetes_i00',
    'name' => 'Revolutionary\'s Bow',
    'additionalname' => '',
    'description' => 'Item used by the revolutionaries during an attack on the transportation unit . It can use powerful skills. Can only be used on the siege battlefield. Can only be used by characters who are above level 40.',
    'is_trade' => 0,
    'is_drop' => 0,
    'is_destruct' => 1,
    'crystal_type' => 'd',
    'consume_type' => 'consume_type_normal',
  ],
  34923 => 
  [
    'item_id' => 34923,
    'icon' => 'weapon_goathead_staff_i00',
    'name' => 'Revolutionary\'s Staff',
    'additionalname' => '',
    'description' => 'Item used by the revolutionaries during an attack on the transportation unit . It can use powerful skills. Can only be used on the siege battlefield. Can only be used by characters who are above level 40.',
    'is_trade' => 0,
    'is_drop' => 0,
    'is_destruct' => 1,
    'crystal_type' => 'd',
    'consume_type' => 'consume_type_normal',
  ],
  34924 => 
  [
    'item_id' => 34924,
    'icon' => 'weapon_life_stick_i00',
    'name' => 'Revolutionary\'s Wand',
    'additionalname' => '',
    'description' => 'Item used by the revolutionaries during an attack on the transportation unit . It can use powerful skills. Can only be used on the siege battlefield. Can only be used by characters who are above level 40.',
    'is_trade' => 0,
    'is_drop' => 0,
    'is_destruct' => 1,
    'crystal_type' => 'd',
    'consume_type' => 'consume_type_normal',
  ],
  34925 => 
  [
    'item_id' => 34925,
    'icon' => 'amor_goodness_cloak',
    'name' => 'Cloak of Light',
    'additionalname' => '',
    'description' => 'Cloak that symbolizes glory and light. STR/MEN/DEX/WIT/INT/CON + 2, and Damage Received - 5%. Can use Escape: Castle skill. Cannot be used while in a chaotic state. Can only be equipped by marquis or higher. Cannot be transferred between servers.',
    'is_trade' => 0,
    'is_drop' => 0,
    'is_destruct' => 1,
    'crystal_type' => 'none',
    'consume_type' => 'consume_type_normal',
  ],
  34926 => 
  [
    'item_id' => 34926,
    'icon' => 'amor_evilness_cloak',
    'name' => 'Cloak of Darkness',
    'additionalname' => '',
    'description' => 'Cloak that symbolizes avarice and darkness. STR/MEN/DEX/WIT/INT/CON + 2, and Damage Received - 5%. Can use Escape: Castle skill. Can only be equipped by marquis or higher. Cannot be transferred between servers.',
    'is_trade' => 0,
    'is_drop' => 0,
    'is_destruct' => 1,
    'crystal_type' => 'none',
    'consume_type' => 'consume_type_normal',
  ],
  34927 => 
  [
    'item_id' => 34927,
    'icon' => 'event_hero_treasure_box_i00',
    'name' => 'Dimension Keeper\'s Blue Box',
    'additionalname' => '',
    'description' => 'Blue-colored box bestowed by the kingdom of Aden as a reward for defeating the dimension demons in Kartia\'s Labyrinth. Double-click on it to see its contents.',
    'is_trade' => 0,
    'is_drop' => 0,
    'is_destruct' => 1,
    'crystal_type' => 'none',
    'consume_type' => 'consume_type_stackable',
  ],
  34928 => 
  [
    'item_id' => 34928,
    'icon' => 'event_hero_treasure_box_i00',
    'name' => 'Dimension Keeper\'s Red Box',
    'additionalname' => '',
    'description' => 'Red-colored box bestowed by the kingdom of Aden as a reward for defeating the dimension demons in Kartia\'s Labyrinth. Double-click on it to see its contents.',
    'is_trade' => 0,
    'is_drop' => 0,
    'is_destruct' => 1,
    'crystal_type' => 'none',
    'consume_type' => 'consume_type_stackable',
  ],
  34929 => 
  [
    'item_id' => 34929,
    'icon' => 'event_hero_treasure_box_i00',
    'name' => 'Dimension Keeper\'s Golden Box',
    'additionalname' => '',
    'description' => 'Gold-colored box bestowed by the kingdom of Aden as a reward for defeating the dimension demons in Kartia\'s Labyrinth. Double-click on it to see its contents.',
    'is_trade' => 0,
    'is_drop' => 0,
    'is_destruct' => 1,
    'crystal_type' => 'none',
    'consume_type' => 'consume_type_stackable',
  ],
  34930 => 
  [
    'item_id' => 34930,
    'icon' => 'event_hero_treasure_box_i00',
    'name' => 'Dimension Traveler\'s Blue Box',
    'additionalname' => '',
    'description' => 'Blue-colored box given by the Kartia Researcher as a reward for defeating the dimension demons in Kartia\'s Labyrinth. Double-click on it to see its contents.',
    'is_trade' => 0,
    'is_drop' => 0,
    'is_destruct' => 1,
    'crystal_type' => 'none',
    'consume_type' => 'consume_type_stackable',
  ],
  34931 => 
  [
    'item_id' => 34931,
    'icon' => 'event_hero_treasure_box_i00',
    'name' => 'Dimension Traveler\'s Red Box',
    'additionalname' => '',
    'description' => 'Red-colored box given by the Kartia Researcher as a reward for defeating the dimension demons in Kartia\'s Labyrinth. Double-click on it to see its contents.',
    'is_trade' => 0,
    'is_drop' => 0,
    'is_destruct' => 1,
    'crystal_type' => 'none',
    'consume_type' => 'consume_type_stackable',
  ],
  34932 => 
  [
    'item_id' => 34932,
    'icon' => 'event_hero_treasure_box_i00',
    'name' => 'Dimension Traveler\'s Golden Box',
    'additionalname' => '',
    'description' => 'Gold-colored box given by the Kartia Researcher as a reward for defeating the dimension demons in Kartia\'s Labyrinth. Double-click on it to see its contents.',
    'is_trade' => 0,
    'is_drop' => 0,
    'is_destruct' => 1,
    'crystal_type' => 'none',
    'consume_type' => 'consume_type_stackable',
  ],
  34933 => 
  [
    'item_id' => 34933,
    'icon' => 'etc_pouch_gold_i00',
    'name' => 'Kranken\'s Gift',
    'additionalname' => '',
    'description' => 'Gift containing Kranken\'s heart. Open to acquire a Scroll: Enchant Weapon (R-grade] or Scroll: Enchant Armor (R-grade].',
    'is_trade' => 0,
    'is_drop' => 0,
    'is_destruct' => 1,
    'crystal_type' => 'none',
    'consume_type' => 'consume_type_stackable',
  ],
  34934 => 
  [
    'item_id' => 34934,
    'icon' => 'etc_pouch_gold_i00',
    'name' => 'Pobre\'s Gift',
    'additionalname' => '',
    'description' => 'Gift containing Pobre\'s heart. Open to acquire a Scroll: Enchant Weapon (R-grade] or Scroll: Enchant Armor (R-grade].',
    'is_trade' => 0,
    'is_drop' => 0,
    'is_destruct' => 1,
    'crystal_type' => 'none',
    'consume_type' => 'consume_type_stackable',
  ],
  34935 => 
  [
    'item_id' => 34935,
    'icon' => 'bracelet_agathion_bm_i01',
    'name' => 'Star Agathion - Heejin Jang',
    'additionalname' => '7-day',
    'description' => '7-day
Increases CON + 3, MEN + 3, Weight Gauge by 10000, Max HP/MP/CP by 300, M. Def. by 5%, Max HP by 5%, and Attribute Resistance by 10.
Usable Skill: Blessed Escape. ',
    'is_trade' => 0,
    'is_drop' => 0,
    'is_destruct' => 0,
    'crystal_type' => 'none',
    'consume_type' => 'consume_type_normal',
  ],
  34936 => 
  [
    'item_id' => 34936,
    'icon' => 'bracelet_agathion_bm_i01',
    'name' => 'Star Agathion - Hyuk Jang',
    'additionalname' => '7-day',
    'description' => '7-day
Increases CON + 3, MEN + 3, Weight Gauge by 10000, Max HP/MP/CP by 300, P. Atk. by 5%, and Attribute Resistance by 10. 
Usable Skill: Blessed Escape. ',
    'is_trade' => 0,
    'is_drop' => 0,
    'is_destruct' => 0,
    'crystal_type' => 'none',
    'consume_type' => 'consume_type_normal',
  ],
  34937 => 
  [
    'item_id' => 34937,
    'icon' => 'bracelet_agathion_bm_i01',
    'name' => 'Star Agathion - Sooro Kim',
    'additionalname' => '7-day',
    'description' => '7-day
Increases CON + 3, MEN + 3, Weight Gauge by 10000, Max HP/MP/CP by 300, P. Def. by 5%, Max HP by 5%, and Attribute Resistance by 10. 
Usable Skill: Blessed Escape. ',
    'is_trade' => 0,
    'is_drop' => 0,
    'is_destruct' => 0,
    'crystal_type' => 'none',
    'consume_type' => 'consume_type_normal',
  ],
  34938 => 
  [
    'item_id' => 34938,
    'icon' => 'bracelet_agathion_bm_i01',
    'name' => 'Star Agathion - Jaebum Park',
    'additionalname' => '7-day',
    'description' => '7-day
Increases CON + 3, MEN + 3, Weight Gauge by 10000, Max HP/MP/CP by 300, M. Atk. By 6%, and Attribute Resistance by 10. 
Usable Skill: Blessed Escape. ',
    'is_trade' => 0,
    'is_drop' => 0,
    'is_destruct' => 0,
    'crystal_type' => 'none',
    'consume_type' => 'consume_type_normal',
  ],
  34939 => 
  [
    'item_id' => 34939,
    'icon' => 'bracelet_agathion_bm_i01',
    'name' => 'Star Agathion - Shin-young Kim',
    'additionalname' => '7-day',
    'description' => '7-day
Increases CON + 3, MEN + 3, Weight Gauge by 10000, Max HP/MP/CP by 300, and Attribute Resistance by 10. Decreases skill cooldown and MP consumed during skill use by 3%. 
Usable Skill: Blessed Escape. ',
    'is_trade' => 0,
    'is_drop' => 0,
    'is_destruct' => 0,
    'crystal_type' => 'none',
    'consume_type' => 'consume_type_normal',
  ],
  34940 => 
  [
    'item_id' => 34940,
    'icon' => 'etc_scroll_of_enchant_armor_i05',
    'name' => 'Scroll: Enchant Hair Accessory',
    'additionalname' => 'Event',
    'description' => 'Increases M. Def. of hair accessories by 2. It is greatly increased starting at + 4. Can be safely enchanted to + 3.',
    'is_trade' => 1,
    'is_drop' => 1,
    'is_destruct' => 1,
    'crystal_type' => 'none',
    'consume_type' => 'consume_type_stackable',
  ],
  34941 => 
  [
    'item_id' => 34941,
    'icon' => 'life_dust_hairacc_general',
    'name' => 'Life Stone: Hair Accessory',
    'additionalname' => 'Event',
    'description' => 'Life Stone for Hair Accessories.',
    'is_trade' => 1,
    'is_drop' => 1,
    'is_destruct' => 1,
    'crystal_type' => 'none',
    'consume_type' => 'consume_type_stackable',
  ],
  34942 => 
  [
    'item_id' => 34942,
    'icon' => 'present_of_destination_event',
    'name' => 'Lv. 2 Giant Dye Pack',
    'additionalname' => 'Event',
    'description' => 'When opened, you can acquire 1 of the following Lv. 2 Giant Dyes: STR, DEX, CON, INT, WIT, or MEN.',
    'is_trade' => 1,
    'is_drop' => 1,
    'is_destruct' => 1,
    'crystal_type' => 'none',
    'consume_type' => 'consume_type_stackable',
  ],
  34943 => 
  [
    'item_id' => 34943,
    'icon' => 'present_of_destination_event',
    'name' => 'Lv. 2 Legendary Dye Pack',
    'additionalname' => 'Event',
    'description' => 'When opened, you can acquire 1 of the following Lv. 2 Legendary Dyes: STR, DEX, CON, INT, WIT, or MEN.',
    'is_trade' => 1,
    'is_drop' => 1,
    'is_destruct' => 1,
    'crystal_type' => 'none',
    'consume_type' => 'consume_type_stackable',
  ],
  34944 => 
  [
    'item_id' => 34944,
    'icon' => 'present_of_destination_event',
    'name' => 'Lv. 2 Ancient Dye Pack',
    'additionalname' => 'Event',
    'description' => 'When opened, you can acquire 1 of the following Lv. 2 Ancient Dyes: STR, DEX, CON, INT, WIT, or MEN.',
    'is_trade' => 1,
    'is_drop' => 1,
    'is_destruct' => 1,
    'crystal_type' => 'none',
    'consume_type' => 'consume_type_stackable',
  ],
  34945 => 
  [
    'item_id' => 34945,
    'icon' => 'present_of_destination_event',
    'name' => 'Lv. 3 Giant Dye Pack',
    'additionalname' => 'Event',
    'description' => 'When opened, you can acquire 1 of the following Lv. 3 Giant Dyes: STR, DEX, CON, INT, WIT, or MEN.',
    'is_trade' => 1,
    'is_drop' => 1,
    'is_destruct' => 1,
    'crystal_type' => 'none',
    'consume_type' => 'consume_type_stackable',
  ],
  34946 => 
  [
    'item_id' => 34946,
    'icon' => 'present_of_destination_event',
    'name' => 'Lv. 3 Legendary Dye Pack',
    'additionalname' => 'Event',
    'description' => 'When opened, you can acquire 1 of the following Lv. 3 Legendary Dyes: STR, DEX, CON, INT, WIT, or MEN.',
    'is_trade' => 1,
    'is_drop' => 1,
    'is_destruct' => 1,
    'crystal_type' => 'none',
    'consume_type' => 'consume_type_stackable',
  ],
  34947 => 
  [
    'item_id' => 34947,
    'icon' => 'present_of_destination_event',
    'name' => 'Lv. 3 Ancient Dye Pack',
    'additionalname' => 'Event',
    'description' => 'When opened, you can acquire 1 of the following Lv. 3 Ancient Dyes: STR, DEX, CON, INT, WIT, or MEN.',
    'is_trade' => 1,
    'is_drop' => 1,
    'is_destruct' => 1,
    'crystal_type' => 'none',
    'consume_type' => 'consume_type_stackable',
  ],
  34948 => 
  [
    'item_id' => 34948,
    'icon' => 'event_hero_treasure_box_i00',
    'name' => 'Scroll of Escape Pack: Village',
    'additionalname' => 'Event',
    'description' => 'When opened, can acquire 1 Scroll of Escape to a random village.',
    'is_trade' => 1,
    'is_drop' => 1,
    'is_destruct' => 1,
    'crystal_type' => 'none',
    'consume_type' => 'consume_type_stackable',
  ],
  34949 => 
  [
    'item_id' => 34949,
    'icon' => 'shield_bread_i02',
    'name' => 'Letter Collector\'s Gift',
    'additionalname' => 'Event',
    'description' => 'When Letter Collector\'s Gift is used, it increases Atk. Spd. by 10%, Casting Spd. by 10%, Spd. by 10, and Max HP and Max MP by 10% for 2 hours. The appearance of the equipped weapon and armor change to a nostalgic style. Cooldown is 30 min.',
    'is_trade' => 1,
    'is_drop' => 1,
    'is_destruct' => 1,
    'crystal_type' => 'none',
    'consume_type' => 'consume_type_stackable',
  ],
  34950 => 
  [
    'item_id' => 34950,
    'icon' => 'present_of_destination_event',
    'name' => 'Lv. 4 Giant Dye Pack',
    'additionalname' => 'Event',
    'description' => 'When opened, you can acquire 1 of the following Lv. 4 Giant Dyes: STR, DEX, CON, INT, WIT, or MEN.',
    'is_trade' => 1,
    'is_drop' => 1,
    'is_destruct' => 1,
    'crystal_type' => 'none',
    'consume_type' => 'consume_type_stackable',
  ],
  34951 => 
  [
    'item_id' => 34951,
    'icon' => 'present_of_destination_event',
    'name' => 'Lv. 4 Legendary Dye Pack',
    'additionalname' => 'Event',
    'description' => 'When opened, you can acquire 1 of the following Lv. 4 Legendary Dyes: STR, DEX, CON, INT, WIT, or MEN.',
    'is_trade' => 1,
    'is_drop' => 1,
    'is_destruct' => 1,
    'crystal_type' => 'none',
    'consume_type' => 'consume_type_stackable',
  ],
  34952 => 
  [
    'item_id' => 34952,
    'icon' => 'present_of_destination_event',
    'name' => 'Lv. 4 Ancient Dye Pack',
    'additionalname' => 'Event',
    'description' => 'When opened, you can acquire 1 of the following Lv. 4 Ancient Dyes: STR, DEX, CON, INT, WIT, or MEN.',
    'is_trade' => 1,
    'is_drop' => 1,
    'is_destruct' => 1,
    'crystal_type' => 'none',
    'consume_type' => 'consume_type_stackable',
  ],
  34953 => 
  [
    'item_id' => 34953,
    'icon' => 'present_of_destination_event',
    'name' => 'Lv. 5 Giant Dye Pack',
    'additionalname' => 'Event',
    'description' => 'When opened, you can acquire 1 of the following Lv. 5 Giant Dyes: STR, DEX, CON, INT, WIT, or MEN.',
    'is_trade' => 1,
    'is_drop' => 1,
    'is_destruct' => 1,
    'crystal_type' => 'none',
    'consume_type' => 'consume_type_stackable',
  ],
  34954 => 
  [
    'item_id' => 34954,
    'icon' => 'present_of_destination_event',
    'name' => 'Lv. 5 Legendary Dye Pack',
    'additionalname' => 'Event',
    'description' => 'When opened, you can acquire 1 of the following Lv. 5 Legendary Dyes: STR, DEX, CON, INT, WIT, or MEN.',
    'is_trade' => 1,
    'is_drop' => 1,
    'is_destruct' => 1,
    'crystal_type' => 'none',
    'consume_type' => 'consume_type_stackable',
  ],
  34955 => 
  [
    'item_id' => 34955,
    'icon' => 'present_of_destination_event',
    'name' => 'Lv. 5 Ancient Dye Pack',
    'additionalname' => 'Event',
    'description' => 'When opened, you can acquire 1 of the following Lv. 5 Ancient Dyes: STR, DEX, CON, INT, WIT, or MEN.',
    'is_trade' => 1,
    'is_drop' => 1,
    'is_destruct' => 1,
    'crystal_type' => 'none',
    'consume_type' => 'consume_type_stackable',
  ],
  34956 => 
  [
    'item_id' => 34956,
    'icon' => 'etc_alphabet_m_i00',
    'name' => 'Letter - M',
    'additionalname' => '',
    'description' => 'Item for the Lineage II 8th Anniversary event. Combine with other letters to create a special word and bring it to Angel Cat to receive a great gift!',
    'is_trade' => 1,
    'is_drop' => 1,
    'is_destruct' => 1,
    'crystal_type' => 'none',
    'consume_type' => 'consume_type_stackable',
  ],
  34957 => 
  [
    'item_id' => 34957,
    'icon' => 'etc_letter_white_i00',
    'name' => 'Kbaldir\'s Letter',
    'additionalname' => '',
    'description' => 'Letter sent by Kbaldir at the Keucereus Alliance Base to the Seed of Hellfire. Bring it to Sizrak in the Seed of Hellfire.',
    'is_trade' => 0,
    'is_drop' => 0,
    'is_destruct' => 0,
    'crystal_type' => 'none',
    'consume_type' => 'consume_type_stackable',
  ],
  34958 => 
  [
    'item_id' => 34958,
    'icon' => 'etc_torch_on_i09',
    'name' => 'Unstable Petra',
    'additionalname' => '',
    'description' => 'Life energy of the Zofans that contain energy of fire. But it is unstable. Bring it to Aku.',
    'is_trade' => 0,
    'is_drop' => 0,
    'is_destruct' => 1,
    'crystal_type' => 'none',
    'consume_type' => 'consume_type_stackable',
  ],
  34959 => 
  [
    'item_id' => 34959,
    'icon' => 'etc_torch_on_i00',
    'name' => 'Petra',
    'additionalname' => '',
    'description' => 'Life energy of the Zofans that contain energy of fire. Bring it to Aku.',
    'is_trade' => 0,
    'is_drop' => 0,
    'is_destruct' => 1,
    'crystal_type' => 'none',
    'consume_type' => 'consume_type_stackable',
  ],
  34960 => 
  [
    'item_id' => 34960,
    'icon' => 'piece_of_emery_i00',
    'name' => 'Tauti\'s Shard',
    'additionalname' => '',
    'description' => 'Tauti\'s small shard. Bring it to Fergason.',
    'is_trade' => 0,
    'is_drop' => 0,
    'is_destruct' => 1,
    'crystal_type' => 'none',
    'consume_type' => 'consume_type_stackable',
  ],
  34961 => 
  [
    'item_id' => 34961,
    'icon' => 'etc_help_seed_i00',
    'name' => 'Helping Seed',
    'additionalname' => '',
    'description' => 'Helping Herb. Double-click on it in a siege area to plant a Tree of Helping.',
    'is_trade' => 0,
    'is_drop' => 0,
    'is_destruct' => 0,
    'crystal_type' => 'none',
    'consume_type' => 'consume_type_stackable',
  ],
  34962 => 
  [
    'item_id' => 34962,
    'icon' => 'etc_powder_orange_i00',
    'name' => 'Ashes of Remnants',
    'additionalname' => '',
    'description' => 'Ashes of Remnants. If you plant a Tree of Helping in a siege battle area, you can obtain Ashes of Remnants.',
    'is_trade' => 0,
    'is_drop' => 0,
    'is_destruct' => 1,
    'crystal_type' => 'none',
    'consume_type' => 'consume_type_stackable',
  ],
  34963 => 
  [
    'item_id' => 34963,
    'icon' => 'etc_coda_seed_i00',
    'name' => 'Mysterious Seed',
    'additionalname' => '',
    'description' => 'Mysterious plant seed that is need to make the flower bloom.',
    'is_trade' => 0,
    'is_drop' => 0,
    'is_destruct' => 1,
    'crystal_type' => 'none',
    'consume_type' => 'consume_type_stackable',
  ],
  34964 => 
  [
    'item_id' => 34964,
    'icon' => 'etc_flower_i00',
    'name' => 'White Chrysanthemum',
    'additionalname' => '',
    'description' => 'White chrysanthemum. Legend says that this flower blooms like a field of white snow when a pure soul receives salvation from the gods.',
    'is_trade' => 0,
    'is_drop' => 0,
    'is_destruct' => 1,
    'crystal_type' => 'none',
    'consume_type' => 'consume_type_stackable',
  ],
  34965 => 
  [
    'item_id' => 34965,
    'icon' => 'etc_flower_i02',
    'name' => 'Daylily',
    'additionalname' => '',
    'description' => 'Yellow flower called a "Daylily." It symbolizes the alleviation of sorrow and grief.',
    'is_trade' => 0,
    'is_drop' => 0,
    'is_destruct' => 1,
    'crystal_type' => 'none',
    'consume_type' => 'consume_type_stackable',
  ],
  34966 => 
  [
    'item_id' => 34966,
    'icon' => 'etc_flower_i01',
    'name' => 'Peony',
    'additionalname' => '',
    'description' => 'Red flower called a "Peony." It once represented wealth and honor.',
    'is_trade' => 0,
    'is_drop' => 0,
    'is_destruct' => 1,
    'crystal_type' => 'none',
    'consume_type' => 'consume_type_stackable',
  ],
  34967 => 
  [
    'item_id' => 34967,
    'icon' => 'etc_flower_i03',
    'name' => 'Petunia',
    'additionalname' => '',
    'description' => 'Pink flower called a "Petunia." It symbolizes a calm heart.',
    'is_trade' => 0,
    'is_drop' => 0,
    'is_destruct' => 1,
    'crystal_type' => 'none',
    'consume_type' => 'consume_type_stackable',
  ],
  34968 => 
  [
    'item_id' => 34968,
    'icon' => 'etc_flower_i04',
    'name' => 'Pansy',
    'additionalname' => '',
    'description' => 'Purple flower called a "Pansy." It means, "Think of me."',
    'is_trade' => 0,
    'is_drop' => 0,
    'is_destruct' => 1,
    'crystal_type' => 'none',
    'consume_type' => 'consume_type_stackable',
  ],
  34969 => 
  [
    'item_id' => 34969,
    'icon' => 'etc_flower_i05',
    'name' => 'Iris',
    'additionalname' => '',
    'description' => 'Blue flower called an "Iris". It symbolizes the bringing of good news.',
    'is_trade' => 0,
    'is_drop' => 0,
    'is_destruct' => 1,
    'crystal_type' => 'none',
    'consume_type' => 'consume_type_stackable',
  ],
  34970 => 
  [
    'item_id' => 34970,
    'icon' => 'etc_flower_i06',
    'name' => 'Kuon',
    'additionalname' => '',
    'description' => 'Black flower called a "Kuon." It is sometimes misunderstood as the flower of death because of its color. It actually symbolizes paying tribute to the dead.',
    'is_trade' => 0,
    'is_drop' => 0,
    'is_destruct' => 1,
    'crystal_type' => 'none',
    'consume_type' => 'consume_type_stackable',
  ],
  34971 => 
  [
    'item_id' => 34971,
    'icon' => 'etc_bodypart_liver_i00',
    'name' => 'Deadman\'s Flesh',
    'additionalname' => '',
    'description' => 'Chunk of dead flesh obtained after defeating the undead monsters in the Guillotine Fortress. Collect them and bring them to Warden Roderik of the Guillotine Fortress.',
    'is_trade' => 0,
    'is_drop' => 0,
    'is_destruct' => 1,
    'crystal_type' => 'none',
    'consume_type' => 'consume_type_stackable',
  ],
  34972 => 
  [
    'item_id' => 34972,
    'icon' => 'etc_spell_books_assistance_i00',
    'name' => 'Harlan\'s Orders',
    'additionalname' => '',
    'description' => 'Orders sent from Guard Harlan in the Town of Dion to Watchman Endrigo of the Guillotine Fortress. Double-click on it for more information.',
    'is_trade' => 0,
    'is_drop' => 0,
    'is_destruct' => 1,
    'crystal_type' => 'none',
    'consume_type' => 'consume_type_stackable',
  ],
  34973 => 
  [
    'item_id' => 34973,
    'icon' => 'mercenary_certification_i00',
    'name' => 'Endrigo\'s Report',
    'additionalname' => '',
    'description' => 'Investigative document that Watchman Endrigo of the Guillotine Fortress asks to be delivered to his comrade Warden Roderik. Double-click on it for more information.',
    'is_trade' => 0,
    'is_drop' => 0,
    'is_destruct' => 1,
    'crystal_type' => 'none',
    'consume_type' => 'consume_type_stackable',
  ],
  34974 => 
  [
    'item_id' => 34974,
    'icon' => 'etc_branch_gold_i00',
    'name' => 'Mandragora Stem',
    'additionalname' => '',
    'description' => 'Mandragora Stem obtained after defeating the Mandragora of Joy and Sorrow in the Guillotine Fortress. Bring to the Dark Elf Dadphyna in the Guillotine Fortress.',
    'is_trade' => 0,
    'is_drop' => 0,
    'is_destruct' => 1,
    'crystal_type' => 'none',
    'consume_type' => 'consume_type_stackable',
  ],
  34975 => 
  [
    'item_id' => 34975,
    'icon' => 'etc_ginseng_gray_i00',
    'name' => 'Mandragora Root',
    'additionalname' => '',
    'description' => 'Mandragora Root obtained after defeating the Mandragora of Prayer in the Guillotine Fortress. Bring to the Dark Elf Dadphyna in the Guillotine Fortress.',
    'is_trade' => 0,
    'is_drop' => 0,
    'is_destruct' => 1,
    'crystal_type' => 'none',
    'consume_type' => 'consume_type_stackable',
  ],
  34976 => 
  [
    'item_id' => 34976,
    'icon' => 'etc_torch_off_i00',
    'name' => 'Disabled Petra',
    'additionalname' => '',
    'description' => 'Disabled Petra obtained through hunting in the Seed of Hellfire. Take it to Sizrak in the area.',
    'is_trade' => 0,
    'is_drop' => 0,
    'is_destruct' => 1,
    'crystal_type' => 'none',
    'consume_type' => 'consume_type_stackable',
  ],
  34977 => 
  [
    'item_id' => 34977,
    'icon' => 'etc_leash_i00',
    'name' => 'Saw-toothed Wheel of Hellfire',
    'additionalname' => '',
    'description' => 'Item collected in the Seed of Hellfire. Contains energy of the Seed of Hellfire. If you take them to Special Product Broker Kirklan at the Kucereus clan outpost, you can exchange them for useful items.',
    'is_trade' => 0,
    'is_drop' => 0,
    'is_destruct' => 1,
    'crystal_type' => 'none',
    'consume_type' => 'consume_type_stackable',
  ],
  34978 => 
  [
    'item_id' => 34978,
    'icon' => 'etc_scroll_of_return_i04',
    'name' => 'Scroll of Escape: Hot Springs',
    'additionalname' => '',
    'description' => 'Scroll of Escape to the Hot Springs area. Can only be used in the Soul Testing quest. Can move to the special hot springs area for the quest mission. Cannot be received again.',
    'is_trade' => 0,
    'is_drop' => 0,
    'is_destruct' => 0,
    'crystal_type' => 'none',
    'consume_type' => 'consume_type_stackable',
  ],
  34979 => 
  [
    'item_id' => 34979,
    'icon' => 'etc_scroll_of_return_i04',
    'name' => 'Scroll of Escape: Forge of the Gods',
    'additionalname' => '',
    'description' => 'Scroll of Escape to the Forge of the Gods. Can only be used in the Soul Testing quest. Can move to the special Forge of the Gods area for the quest mission. Cannot be received again.',
    'is_trade' => 0,
    'is_drop' => 0,
    'is_destruct' => 0,
    'crystal_type' => 'none',
    'consume_type' => 'consume_type_stackable',
  ],
  34980 => 
  [
    'item_id' => 34980,
    'icon' => 'etc_scroll_of_return_i04',
    'name' => 'Scroll of Escape: Isle of Prayer',
    'additionalname' => '',
    'description' => 'Scroll of Escape to the Isle of Prayer. Can only be used in the Soul Testing quest. Can move to the special Isle of Prayer area for the quest mission. Cannot be received again.',
    'is_trade' => 0,
    'is_drop' => 0,
    'is_destruct' => 0,
    'crystal_type' => 'none',
    'consume_type' => 'consume_type_stackable',
  ],
  34981 => 
  [
    'item_id' => 34981,
    'icon' => 'etc_scroll_of_return_i04',
    'name' => 'Scroll of Escape: Aden Castle (Siege]',
    'additionalname' => '',
    'description' => 'Scroll of Escape to the Aden Castle siege area. Can only be used in the Soul Testing quest. Can move to the special Aden Castle siege area for the quest mission. Cannot be received again.',
    'is_trade' => 0,
    'is_drop' => 0,
    'is_destruct' => 0,
    'crystal_type' => 'none',
    'consume_type' => 'consume_type_stackable',
  ],
  34982 => 
  [
    'item_id' => 34982,
    'icon' => 'etc_scroll_of_return_i04',
    'name' => 'Scroll of Escape: Rune Castle (Siege]',
    'additionalname' => '',
    'description' => 'Scroll of Escape to the Rune Castle siege area. Can only be used in the Soul Testing quest. Can move to the special Rune Castle siege area for the quest mission. Cannot be received again.',
    'is_trade' => 0,
    'is_drop' => 0,
    'is_destruct' => 0,
    'crystal_type' => 'none',
    'consume_type' => 'consume_type_stackable',
  ],
  34983 => 
  [
    'item_id' => 34983,
    'icon' => 'etc_nobless_teleport_coupon_i00',
    'name' => 'Acquire Noblesse Privileges',
    'additionalname' => '',
    'description' => '',
    'is_trade' => 0,
    'is_drop' => 0,
    'is_destruct' => 1,
    'crystal_type' => 'none',
    'consume_type' => 'consume_type_stackable',
  ],
  34984 => 
  [
    'item_id' => 34984,
    'icon' => 'accessory_immortal_talisman_i01',
    'name' => 'Talisman - Infinity',
    'additionalname' => '',
    'description' => 'Increases Max HP/MP/CP by 100, P. Accuracy and M. Accuracy by 1, P. Evasion and M. Evasion by 1 Vampiric Rage Effect by 2%, and Atk. Spd. and Casting Spd. by 10.',
    'is_trade' => 0,
    'is_drop' => 0,
    'is_destruct' => 0,
    'crystal_type' => 'none',
    'consume_type' => 'consume_type_normal',
  ],
  34985 => 
  [
    'item_id' => 34985,
    'icon' => 'accessory_destruction_talisman_i01',
    'name' => 'Talisman - Destruction',
    'additionalname' => '',
    'description' => 'Increases Max HP/MP/CP by 100, P. Accuracy and M. Accuracy by 2, P. Evasion and M. Evasion by 2, Vampiric Rage Effect by 2%, Atk. Spd. and Casting Spd. by 10, P. Critical Rate by 30, and M. Critical Rate by 10.',
    'is_trade' => 0,
    'is_drop' => 0,
    'is_destruct' => 0,
    'crystal_type' => 'none',
    'consume_type' => 'consume_type_normal',
  ],
  34986 => 
  [
    'item_id' => 34986,
    'icon' => 'accessory_extermination_talisman_i01',
    'name' => 'Talisman - Annihilation',
    'additionalname' => '',
    'description' => 'Increases Max HP/MP/CP by 300, P. Accuracy and M. Accuracy by 2, P. Evasion and M. Evasion by 2, Vampiric Rage Effect by 3%, Atk. Spd. and Casting Spd. by 20, P. Critical Rate by 30, M. Critical Rate by 10, P. Atk. by 103, and M. Atk. by 156.',
    'is_trade' => 0,
    'is_drop' => 0,
    'is_destruct' => 0,
    'crystal_type' => 'none',
    'consume_type' => 'consume_type_normal',
  ],
  34987 => 
  [
    'item_id' => 34987,
    'icon' => 'accessory_hellfire_talisman_i01',
    'name' => 'Talisman - Hellfire',
    'additionalname' => '',
    'description' => 'When equipped, increases Max HP, MP, and CP by 400, P. and M. Accuracy by 2, P. and M. Evasion by 2, Vampiric Rage 3% effect, Atk. Spd. and Casting Spd. by 30, Critical Rate by 30, M. Critical Rate by 10, P. Atk. by 103, M. Atk. by 156, Skill Power by 1%, Damage Reflect Resistance by 10, and P. and M. Def. by 20.',
    'is_trade' => 0,
    'is_drop' => 0,
    'is_destruct' => 0,
    'crystal_type' => 'none',
    'consume_type' => 'consume_type_normal',
  ],
  34988 => 
  [
    'item_id' => 34988,
    'icon' => 'accessory_ocean_talisman_i01',
    'name' => 'Talisman - Desire',
    'additionalname' => '',
    'description' => 'When equipped, increases Max HP, MP, and CP by 500, P. and M. Accuracy by 2, P. and M. Evasion by 2, Vampiric Rage 3% effect, Atk. Spd. and Casting Spd. by 40, Critical Rate by 30, M. Critical Rate by 10, P. Atk. by 203, M. Atk. by 256, Skill Power by 2%, Damage Reflect Resistance by 20, and P. and M. Def. by 40. MP consumption decreases by 1%.',
    'is_trade' => 0,
    'is_drop' => 0,
    'is_destruct' => 0,
    'crystal_type' => 'none',
    'consume_type' => 'consume_type_normal',
  ],
  34989 => 
  [
    'item_id' => 34989,
    'icon' => 'accessory_longing_talisman_i01',
    'name' => 'Talisman - Longing',
    'additionalname' => '',
    'description' => 'When equipped, increases Max HP, MP, and CP by 600, P. and M. Accuracy by 2, P. and M. Evasion by 2, Vampiric Rage 3% effect, Atk. Spd. and Casting Spd. by 50, Critical Rate by 30, M. Critical Rate by 10, P. Atk. by 303, M. Atk. by 356, Skill Power by 4%, Damage Reflect Resistance by 30, and P. M. Def. by 60, and STR/INT/CON/MEN/DEX/WIT by 2. MP consumption decreases by 3%.',
    'is_trade' => 0,
    'is_drop' => 0,
    'is_destruct' => 0,
    'crystal_type' => 'none',
    'consume_type' => 'consume_type_normal',
  ],
  34990 => 
  [
    'item_id' => 34990,
    'icon' => 'etc_r_weapon_piece_i01',
    'name' => 'Corroded Weapon Fragment',
    'additionalname' => '',
    'description' => 'Corroded ingredient. Sell it to a store or trade it in through the Aden Reconstruction Society for a new ingredient.',
    'is_trade' => 1,
    'is_drop' => 1,
    'is_destruct' => 1,
    'crystal_type' => 'none',
    'consume_type' => 'consume_type_stackable',
  ],
  34991 => 
  [
    'item_id' => 34991,
    'icon' => 'etc_r_armor_piece_i01',
    'name' => 'Corroded Armor Fragment',
    'additionalname' => '',
    'description' => 'Corroded ingredient. Sell it to a store or trade it in through the Aden Reconstruction Society for a new ingredient.',
    'is_trade' => 1,
    'is_drop' => 1,
    'is_destruct' => 1,
    'crystal_type' => 'none',
    'consume_type' => 'consume_type_stackable',
  ],
  34992 => 
  [
    'item_id' => 34992,
    'icon' => 'etc_r_acc_piece_i01',
    'name' => 'Corroded Accessory Gem',
    'additionalname' => '',
    'description' => 'Corroded ingredient. Sell it to a store or trade it in through the Aden Reconstruction Society for a new ingredient.',
    'is_trade' => 1,
    'is_drop' => 1,
    'is_destruct' => 1,
    'crystal_type' => 'none',
    'consume_type' => 'consume_type_stackable',
  ],
  34993 => 
  [
    'item_id' => 34993,
    'icon' => 'etc_synthetic_cokes_i00',
    'name' => 'Greater Cokes',
    'additionalname' => '',
    'description' => 'Used as an ingredient to make A-grade or S-grade items.',
    'is_trade' => 1,
    'is_drop' => 1,
    'is_destruct' => 1,
    'crystal_type' => 'none',
    'consume_type' => 'consume_type_stackable',
  ],
  34994 => 
  [
    'item_id' => 34994,
    'icon' => 'etc_crystal_ball_silver_i00',
    'name' => 'Gemstone',
    'additionalname' => '',
    'description' => '',
    'is_trade' => 1,
    'is_drop' => 1,
    'is_destruct' => 1,
    'crystal_type' => 'none',
    'consume_type' => 'consume_type_stackable',
  ],
  34995 => 
  [
    'item_id' => 34995,
    'icon' => 'etc_piece_of_paper_white_i00',
    'name' => 'Hair Accessory Exchange Certificate',
    'additionalname' => '',
    'description' => 'Certificate that can be exchanged with the Aden Reconstruction Society Member or Leader for Rabbit Ears, Raccoon Ears, Cat Ears, Romantic Chapeau, Angel Circlet, Demon Circlet, Pirate\'s Eyepatch, Outlaw\'s Eyepatch, Eyepatch, Party Hat, Refined Angel Ring, or Refined Devil Horns.',
    'is_trade' => 1,
    'is_drop' => 1,
    'is_destruct' => 1,
    'crystal_type' => 'none',
    'consume_type' => 'consume_type_stackable',
  ],
  34996 => 
  [
    'item_id' => 34996,
    'icon' => 'amor_goodness_cloak',
    'name' => 'Cloak of Radiant Light',
    'additionalname' => '',
    'description' => 'Cloak that symbolizes glory and light. STR/MEN/DEX/WIT/INT/CON/LUC/CHA + 3, and Damage Received - 15%. Can use Escape: Castle skill. Cannot be used while in a chaotic state. Can only be equipped by a lord. Cannot be transferred between servers.',
    'is_trade' => 0,
    'is_drop' => 0,
    'is_destruct' => 1,
    'crystal_type' => 'none',
    'consume_type' => 'consume_type_normal',
  ],
  34997 => 
  [
    'item_id' => 34997,
    'icon' => 'amor_evilness_cloak',
    'name' => 'Cloak of Cold Darkness',
    'additionalname' => '',
    'description' => 'Cloak that symbolizes avarice and darkness. STR/MEN/DEX/WIT/INT/CON/LUC/CHA + 3, and Damage Received - 15%. Can use Escape: Castle skill. Can only be equipped by a lord. Cannot be transferred between servers.',
    'is_trade' => 0,
    'is_drop' => 0,
    'is_destruct' => 1,
    'crystal_type' => 'none',
    'consume_type' => 'consume_type_normal',
  ],
  34998 => 
  [
    'item_id' => 34998,
    'icon' => 'weapon_tauti_one_hand_axe_i01',
    'name' => 'Tauti\'s One-handed Axe',
    'additionalname' => '',
    'description' => 'Weapon augmented from Tauti\'s Fragment. When equipped, PvP Damage by 15%, Max HP by 25%, P. Atk. by 10%, Atk. Spd. by 15%, and P. Critical Rate by 150. Can use Tauti\'s Rage skill. Enchantment, attribute, crystallization, augmentation or modification is impossible. Can bestow 1 Special Soul Crystal.',
    'is_trade' => 1,
    'is_drop' => 1,
    'is_destruct' => 0,
    'crystal_type' => 'r',
    'consume_type' => 'consume_type_normal',
  ],
  34999 => 
  [
    'item_id' => 34999,
    'icon' => 'weapon_tauti_one_hand_magic_axe_i01',
    'name' => 'Tauti\'s Axe',
    'additionalname' => '',
    'description' => 'Weapon augmented from Tauti\'s Fragment. When equipped, PvP Damage by 15%, Max HP by 25%, P. Atk. by 10%, Atk. Spd. by 15%, and P. Critical Rate by 150. Can use Tauti\'s Rage skill. Enchantment, attribute, crystallization, augmentation or modification is impossible. Can bestow 1 Special Soul Crystal.',
    'is_trade' => 1,
    'is_drop' => 1,
    'is_destruct' => 0,
    'crystal_type' => 'r',
    'consume_type' => 'consume_type_normal',
  ],
];