<?php return [
  35500 => 
  [
    'item_id' => 35500,
    'icon' => 'etc_recipe_gold_i00',
    'name' => 'Recipe: Blessed Seraph Leather Armor (60%]',
    'additionalname' => '',
    'description' => 'For Dwarves only. Recipe for a Blessed Seraph Leather Armor. Requires Create Item - Skill Lv. 13. The success rate is 60%.',
    'is_trade' => 1,
    'is_drop' => 1,
    'is_destruct' => 1,
    'crystal_type' => 'none',
    'consume_type' => 'consume_type_stackable',
  ],
  35501 => 
  [
    'item_id' => 35501,
    'icon' => 'etc_recipe_gold_i00',
    'name' => 'Recipe: Blessed Seraph Leather Leggings (60%]',
    'additionalname' => '',
    'description' => 'For Dwarves only. Recipe for Blessed Seraph Leather Leggings. Requires Create Item - Skill Lv. 13. The success rate is 60%.',
    'is_trade' => 1,
    'is_drop' => 1,
    'is_destruct' => 1,
    'crystal_type' => 'none',
    'consume_type' => 'consume_type_stackable',
  ],
  35502 => 
  [
    'item_id' => 35502,
    'icon' => 'etc_recipe_gold_i00',
    'name' => 'Recipe: Blessed Seraph Leather Gloves (60%]',
    'additionalname' => '',
    'description' => 'For Dwarves only. Recipe for Blessed Seraph Leather Gloves. Requires Create Item - Skill Lv. 13. The success rate is 60%.',
    'is_trade' => 1,
    'is_drop' => 1,
    'is_destruct' => 1,
    'crystal_type' => 'none',
    'consume_type' => 'consume_type_stackable',
  ],
  35503 => 
  [
    'item_id' => 35503,
    'icon' => 'etc_recipe_gold_i00',
    'name' => 'Recipe: Blessed Seraph Leather Boots (60%]',
    'additionalname' => '',
    'description' => 'For Dwarves only. Recipe for Blessed Seraph Leather Boots. Requires Create Item - Skill Lv. 13. The success rate is 60%.',
    'is_trade' => 1,
    'is_drop' => 1,
    'is_destruct' => 1,
    'crystal_type' => 'none',
    'consume_type' => 'consume_type_stackable',
  ],
  35504 => 
  [
    'item_id' => 35504,
    'icon' => 'etc_recipe_gold_i00',
    'name' => 'Recipe: Blessed Seraph Circlet (60%]',
    'additionalname' => '',
    'description' => 'For Dwarves only. Recipe for a Blessed Seraph Circlet. Requires Create Item - Skill Lv. 13. The success rate is 60%.',
    'is_trade' => 1,
    'is_drop' => 1,
    'is_destruct' => 1,
    'crystal_type' => 'none',
    'consume_type' => 'consume_type_stackable',
  ],
  35505 => 
  [
    'item_id' => 35505,
    'icon' => 'etc_recipe_gold_i00',
    'name' => 'Recipe: Blessed Seraph Tunic (60%]',
    'additionalname' => '',
    'description' => 'For Dwarves only. Recipe for a Blessed Seraph Tunic. Requires Create Item - Skill Lv. 13. The success rate is 60%.',
    'is_trade' => 1,
    'is_drop' => 1,
    'is_destruct' => 1,
    'crystal_type' => 'none',
    'consume_type' => 'consume_type_stackable',
  ],
  35506 => 
  [
    'item_id' => 35506,
    'icon' => 'etc_recipe_gold_i00',
    'name' => 'Recipe: Blessed Seraph Stockings (60%]',
    'additionalname' => '',
    'description' => 'For Dwarves only. Recipe for Blessed Seraph Stockings. Requires Create Item - Skill Lv. 13. The success rate is 60%.',
    'is_trade' => 1,
    'is_drop' => 1,
    'is_destruct' => 1,
    'crystal_type' => 'none',
    'consume_type' => 'consume_type_stackable',
  ],
  35507 => 
  [
    'item_id' => 35507,
    'icon' => 'etc_recipe_gold_i00',
    'name' => 'Recipe: Blessed Seraph Gloves (60%]',
    'additionalname' => '',
    'description' => 'For Dwarves only. Recipe for Blessed Seraph Gloves. Requires Create Item - Skill Lv. 13. The success rate is 60%.',
    'is_trade' => 1,
    'is_drop' => 1,
    'is_destruct' => 1,
    'crystal_type' => 'none',
    'consume_type' => 'consume_type_stackable',
  ],
  35508 => 
  [
    'item_id' => 35508,
    'icon' => 'etc_recipe_gold_i00',
    'name' => 'Recipe: Blessed Seraph Shoes (60%]',
    'additionalname' => '',
    'description' => 'For Dwarves only. Recipe for Blessed Seraph Shoes. Requires Create Item - Skill Lv. 13. The success rate is 60%.',
    'is_trade' => 1,
    'is_drop' => 1,
    'is_destruct' => 1,
    'crystal_type' => 'none',
    'consume_type' => 'consume_type_stackable',
  ],
  35509 => 
  [
    'item_id' => 35509,
    'icon' => 'etc_recipe_gold_i00',
    'name' => 'Recipe: Blessed Seraph Sigil (60%]',
    'additionalname' => '',
    'description' => 'For Dwarves only. Recipe for a Blessed Seraph Sigil. Requires Create Item - Skill Lv. 13. The success rate is 60%.',
    'is_trade' => 1,
    'is_drop' => 1,
    'is_destruct' => 1,
    'crystal_type' => 'none',
    'consume_type' => 'consume_type_stackable',
  ],
  35510 => 
  [
    'item_id' => 35510,
    'icon' => 'etc_recipe_gold_i00',
    'name' => 'Recipe: Blessed Seraph Necklace (60%]',
    'additionalname' => '',
    'description' => 'For Dwarves only. Recipe for a Blessed Seraph Necklace. Requires Create Item - Skill Lv. 13. The success rate is 60%.',
    'is_trade' => 1,
    'is_drop' => 1,
    'is_destruct' => 1,
    'crystal_type' => 'none',
    'consume_type' => 'consume_type_stackable',
  ],
  35511 => 
  [
    'item_id' => 35511,
    'icon' => 'etc_recipe_gold_i00',
    'name' => 'Recipe: Blessed Seraph Earring (60%]',
    'additionalname' => '',
    'description' => 'For Dwarves only. Recipe for a Blessed Seraph Earring. Requires Create Item - Skill Lv. 13. The success rate is 60%.',
    'is_trade' => 1,
    'is_drop' => 1,
    'is_destruct' => 1,
    'crystal_type' => 'none',
    'consume_type' => 'consume_type_stackable',
  ],
  35512 => 
  [
    'item_id' => 35512,
    'icon' => 'etc_recipe_gold_i00',
    'name' => 'Recipe: Blessed Seraph Ring (60%]',
    'additionalname' => '',
    'description' => 'For Dwarves only. Recipe for a Blessed Seraph Ring. Requires Create Item - Skill Lv. 13. The success rate is 60%.',
    'is_trade' => 1,
    'is_drop' => 1,
    'is_destruct' => 1,
    'crystal_type' => 'none',
    'consume_type' => 'consume_type_stackable',
  ],
  35513 => 
  [
    'item_id' => 35513,
    'icon' => 'etc_recipe_gold_i00',
    'name' => 'Recipe: Blessed Amaranthine Shaper (60%]',
    'additionalname' => '',
    'description' => 'For Dwarves only. Recipe for a Blessed Amaranthine Shaper. Requires Create Item - Skill Lv. 14. The success rate is 60%.',
    'is_trade' => 1,
    'is_drop' => 1,
    'is_destruct' => 1,
    'crystal_type' => 'none',
    'consume_type' => 'consume_type_stackable',
  ],
  35514 => 
  [
    'item_id' => 35514,
    'icon' => 'etc_recipe_gold_i00',
    'name' => 'Recipe: Blessed Amaranthine Cutter (60%]',
    'additionalname' => '',
    'description' => 'For Dwarves only. Recipe for a Blessed Amaranthine Cutter. Requires Create Item - Skill Lv. 14. The success rate is 60%.',
    'is_trade' => 1,
    'is_drop' => 1,
    'is_destruct' => 1,
    'crystal_type' => 'none',
    'consume_type' => 'consume_type_stackable',
  ],
  35515 => 
  [
    'item_id' => 35515,
    'icon' => 'etc_recipe_gold_i00',
    'name' => 'Recipe: Blessed Amaranthine Slasher (60%]',
    'additionalname' => '',
    'description' => 'For Dwarves only. Recipe for a Blessed Amaranthine Slasher. Requires Create Item - Skill Lv. 14. The success rate is 60%.',
    'is_trade' => 1,
    'is_drop' => 1,
    'is_destruct' => 1,
    'crystal_type' => 'none',
    'consume_type' => 'consume_type_stackable',
  ],
  35516 => 
  [
    'item_id' => 35516,
    'icon' => 'etc_recipe_gold_i00',
    'name' => 'Recipe: Blessed Amaranthine Avenger (60%]',
    'additionalname' => '',
    'description' => 'For Dwarves only. Recipe for a Blessed Amaranthine Avenger. Requires Create Item - Skill Lv. 14. The success rate is 60%.',
    'is_trade' => 1,
    'is_drop' => 1,
    'is_destruct' => 1,
    'crystal_type' => 'none',
    'consume_type' => 'consume_type_stackable',
  ],
  35517 => 
  [
    'item_id' => 35517,
    'icon' => 'etc_recipe_gold_i00',
    'name' => 'Recipe: Blessed Amaranthine Fighter (60%]',
    'additionalname' => '',
    'description' => 'For Dwarves only. Recipe for a Blessed Amaranthine Fighter. Requires Create Item - Skill Lv. 14. The success rate is 60%.',
    'is_trade' => 1,
    'is_drop' => 1,
    'is_destruct' => 1,
    'crystal_type' => 'none',
    'consume_type' => 'consume_type_stackable',
  ],
  35518 => 
  [
    'item_id' => 35518,
    'icon' => 'etc_recipe_gold_i00',
    'name' => 'Recipe: Blessed Amaranthine Stormer (60%]',
    'additionalname' => '',
    'description' => 'For Dwarves only. Recipe for a Blessed Amaranthine Stormer. Requires Create Item - Skill Lv. 14. The success rate is 60%.',
    'is_trade' => 1,
    'is_drop' => 1,
    'is_destruct' => 1,
    'crystal_type' => 'none',
    'consume_type' => 'consume_type_stackable',
  ],
  35519 => 
  [
    'item_id' => 35519,
    'icon' => 'etc_recipe_gold_i00',
    'name' => 'Recipe: Blessed Amaranthine Thrower (60%]',
    'additionalname' => '',
    'description' => 'For Dwarves only. Recipe for a Blessed Amaranthine Thrower. Requires Create Item - Skill Lv. 14. The success rate is 60%.',
    'is_trade' => 1,
    'is_drop' => 1,
    'is_destruct' => 1,
    'crystal_type' => 'none',
    'consume_type' => 'consume_type_stackable',
  ],
  35520 => 
  [
    'item_id' => 35520,
    'icon' => 'etc_recipe_gold_i00',
    'name' => 'Recipe: Blessed Amaranthine Shooter (60%]',
    'additionalname' => '',
    'description' => 'For Dwarves only. Recipe for a Blessed Amaranthine Shooter. Requires Create Item - Skill Lv. 14. The success rate is 60%.',
    'is_trade' => 1,
    'is_drop' => 1,
    'is_destruct' => 1,
    'crystal_type' => 'none',
    'consume_type' => 'consume_type_stackable',
  ],
  35521 => 
  [
    'item_id' => 35521,
    'icon' => 'etc_recipe_gold_i00',
    'name' => 'Recipe: Blessed Amaranthine Buster (60%]',
    'additionalname' => '',
    'description' => 'For Dwarves only. Recipe for a Blessed Amaranthine Buster. Requires Create Item - Skill Lv. 14. The success rate is 60%.',
    'is_trade' => 1,
    'is_drop' => 1,
    'is_destruct' => 1,
    'crystal_type' => 'none',
    'consume_type' => 'consume_type_stackable',
  ],
  35522 => 
  [
    'item_id' => 35522,
    'icon' => 'etc_recipe_gold_i00',
    'name' => 'Recipe: Blessed Amaranthine Caster (60%]',
    'additionalname' => '',
    'description' => 'For Dwarves only. Recipe for a Blessed Amaranthine Caster. Requires Create Item - Skill Lv. 14. The success rate is 60%.',
    'is_trade' => 1,
    'is_drop' => 1,
    'is_destruct' => 1,
    'crystal_type' => 'none',
    'consume_type' => 'consume_type_stackable',
  ],
  35523 => 
  [
    'item_id' => 35523,
    'icon' => 'etc_recipe_gold_i00',
    'name' => 'Recipe: Blessed Amaranthine Retributer (60%]',
    'additionalname' => '',
    'description' => 'For Dwarves only. Recipe for a Blessed Amaranthine Retributer. Requires Create Item - Skill Lv. 14. The success rate is 60%.',
    'is_trade' => 1,
    'is_drop' => 1,
    'is_destruct' => 1,
    'crystal_type' => 'none',
    'consume_type' => 'consume_type_stackable',
  ],
  35524 => 
  [
    'item_id' => 35524,
    'icon' => 'etc_recipe_gold_i00',
    'name' => 'Recipe: Blessed Eternal Helmet (60%]',
    'additionalname' => '',
    'description' => 'For Dwarves only. Recipe for a Blessed Eternal Helmet. Requires Create Item - Skill Lv. 14. The success rate is 60%.',
    'is_trade' => 1,
    'is_drop' => 1,
    'is_destruct' => 1,
    'crystal_type' => 'none',
    'consume_type' => 'consume_type_stackable',
  ],
  35525 => 
  [
    'item_id' => 35525,
    'icon' => 'etc_recipe_gold_i00',
    'name' => 'Recipe: Blessed Eternal Breastplate (60%]',
    'additionalname' => '',
    'description' => 'For Dwarves only. Recipe for a Blessed Eternal Breastplate. Requires Create Item - Skill Lv. 14. The success rate is 60%.',
    'is_trade' => 1,
    'is_drop' => 1,
    'is_destruct' => 1,
    'crystal_type' => 'none',
    'consume_type' => 'consume_type_stackable',
  ],
  35526 => 
  [
    'item_id' => 35526,
    'icon' => 'etc_recipe_gold_i00',
    'name' => 'Recipe: Blessed Eternal Gaiters (60%]',
    'additionalname' => '',
    'description' => 'For Dwarves only. Recipe for Blessed Eternal Gaiters. Requires Create Item - Skill Lv. 14. The success rate is 60%.',
    'is_trade' => 1,
    'is_drop' => 1,
    'is_destruct' => 1,
    'crystal_type' => 'none',
    'consume_type' => 'consume_type_stackable',
  ],
  35527 => 
  [
    'item_id' => 35527,
    'icon' => 'etc_recipe_gold_i00',
    'name' => 'Recipe: Blessed Eternal Gauntlets (60%]',
    'additionalname' => '',
    'description' => 'For Dwarves only. Recipe for a Blessed Eternal Gauntlets. Requires Create Item - Skill Lv. 14. The success rate is 60%.',
    'is_trade' => 1,
    'is_drop' => 1,
    'is_destruct' => 1,
    'crystal_type' => 'none',
    'consume_type' => 'consume_type_stackable',
  ],
  35528 => 
  [
    'item_id' => 35528,
    'icon' => 'etc_recipe_gold_i00',
    'name' => 'Recipe: Blessed Eternal Boots (60%]',
    'additionalname' => '',
    'description' => 'For Dwarves only. Recipe for Blessed Eternal Boots. Requires Create Item - Skill Lv. 14. The success rate is 60%.',
    'is_trade' => 1,
    'is_drop' => 1,
    'is_destruct' => 1,
    'crystal_type' => 'none',
    'consume_type' => 'consume_type_stackable',
  ],
  35529 => 
  [
    'item_id' => 35529,
    'icon' => 'etc_recipe_gold_i00',
    'name' => 'Recipe: Blessed Eternal Shield (60%]',
    'additionalname' => '',
    'description' => 'For Dwarves only. Recipe for a Blessed Eternal Shield. Requires Create Item - Skill Lv. 14. The success rate is 60%.',
    'is_trade' => 1,
    'is_drop' => 1,
    'is_destruct' => 1,
    'crystal_type' => 'none',
    'consume_type' => 'consume_type_stackable',
  ],
  35530 => 
  [
    'item_id' => 35530,
    'icon' => 'etc_recipe_gold_i00',
    'name' => 'Recipe: Blessed Eternal Leather Helmet (60%]',
    'additionalname' => '',
    'description' => 'For Dwarves only. Recipe for a Blessed Eternal Leather Helmet. Requires Create Item - Skill Lv. 14. The success rate is 60%.',
    'is_trade' => 1,
    'is_drop' => 1,
    'is_destruct' => 1,
    'crystal_type' => 'none',
    'consume_type' => 'consume_type_stackable',
  ],
  35531 => 
  [
    'item_id' => 35531,
    'icon' => 'etc_recipe_gold_i00',
    'name' => 'Recipe: Blessed Eternal Leather Armor (60%]',
    'additionalname' => '',
    'description' => 'For Dwarves only. Recipe for a Blessed Eternal Leather Armor. Requires Create Item - Skill Lv. 14. The success rate is 60%.',
    'is_trade' => 1,
    'is_drop' => 1,
    'is_destruct' => 1,
    'crystal_type' => 'none',
    'consume_type' => 'consume_type_stackable',
  ],
  35532 => 
  [
    'item_id' => 35532,
    'icon' => 'etc_recipe_gold_i00',
    'name' => 'Recipe: Blessed Eternal Leather Leggings (60%]',
    'additionalname' => '',
    'description' => 'For Dwarves only. Recipe for Blessed Eternal Leather Leggings. Requires Create Item - Skill Lv. 14. The success rate is 60%.',
    'is_trade' => 1,
    'is_drop' => 1,
    'is_destruct' => 1,
    'crystal_type' => 'none',
    'consume_type' => 'consume_type_stackable',
  ],
  35533 => 
  [
    'item_id' => 35533,
    'icon' => 'etc_recipe_gold_i00',
    'name' => 'Recipe: Blessed Eternal Leather Gloves (60%]',
    'additionalname' => '',
    'description' => 'For Dwarves only. Recipe for Blessed Eternal Leather Gloves. Requires Create Item - Skill Lv. 14. The success rate is 60%.',
    'is_trade' => 1,
    'is_drop' => 1,
    'is_destruct' => 1,
    'crystal_type' => 'none',
    'consume_type' => 'consume_type_stackable',
  ],
  35534 => 
  [
    'item_id' => 35534,
    'icon' => 'etc_recipe_gold_i00',
    'name' => 'Recipe: Blessed Eternal Leather Boots (60%]',
    'additionalname' => '',
    'description' => 'For Dwarves only. Recipe for Blessed Eternal Leather Boots. Requires Create Item - Skill Lv. 14. The success rate is 60%.',
    'is_trade' => 1,
    'is_drop' => 1,
    'is_destruct' => 1,
    'crystal_type' => 'none',
    'consume_type' => 'consume_type_stackable',
  ],
  35535 => 
  [
    'item_id' => 35535,
    'icon' => 'etc_recipe_gold_i00',
    'name' => 'Recipe: Blessed Eternal Circlet (60%]',
    'additionalname' => '',
    'description' => 'For Dwarves only. Recipe for a Blessed Eternal Circlet. Requires Create Item - Skill Lv. 14. The success rate is 60%.',
    'is_trade' => 1,
    'is_drop' => 1,
    'is_destruct' => 1,
    'crystal_type' => 'none',
    'consume_type' => 'consume_type_stackable',
  ],
  35536 => 
  [
    'item_id' => 35536,
    'icon' => 'etc_recipe_gold_i00',
    'name' => 'Recipe: Blessed Eternal Tunic (60%]',
    'additionalname' => '',
    'description' => 'For Dwarves only. Recipe for a Blessed Eternal Tunic. Requires Create Item - Skill Lv. 14. The success rate is 60%.',
    'is_trade' => 1,
    'is_drop' => 1,
    'is_destruct' => 1,
    'crystal_type' => 'none',
    'consume_type' => 'consume_type_stackable',
  ],
  35537 => 
  [
    'item_id' => 35537,
    'icon' => 'etc_recipe_gold_i00',
    'name' => 'Recipe: Blessed Eternal Stockings (60%]',
    'additionalname' => '',
    'description' => 'For Dwarves only. Recipe for Blessed Eternal Stockings. Requires Create Item - Skill Lv. 14. The success rate is 60%.',
    'is_trade' => 1,
    'is_drop' => 1,
    'is_destruct' => 1,
    'crystal_type' => 'none',
    'consume_type' => 'consume_type_stackable',
  ],
  35538 => 
  [
    'item_id' => 35538,
    'icon' => 'etc_recipe_gold_i00',
    'name' => 'Recipe: Blessed Eternal Gloves (60%]',
    'additionalname' => '',
    'description' => 'For Dwarves only. Recipe for Blessed Eternal Gloves. Requires Create Item - Skill Lv. 14. The success rate is 60%.',
    'is_trade' => 1,
    'is_drop' => 1,
    'is_destruct' => 1,
    'crystal_type' => 'none',
    'consume_type' => 'consume_type_stackable',
  ],
  35539 => 
  [
    'item_id' => 35539,
    'icon' => 'etc_recipe_gold_i00',
    'name' => 'Recipe: Blessed Eternal Shoes (60%]',
    'additionalname' => '',
    'description' => 'For Dwarves only. Recipe for Blessed Eternal Shoes. Requires Create Item - Skill Lv. 14. The success rate is 60%.',
    'is_trade' => 1,
    'is_drop' => 1,
    'is_destruct' => 1,
    'crystal_type' => 'none',
    'consume_type' => 'consume_type_stackable',
  ],
  35540 => 
  [
    'item_id' => 35540,
    'icon' => 'etc_recipe_gold_i00',
    'name' => 'Recipe: Blessed Eternal Sigil (60%]',
    'additionalname' => '',
    'description' => 'For Dwarves only. Recipe for a Blessed Eternal Sigil. Requires Create Item - Skill Lv. 14. The success rate is 60%.',
    'is_trade' => 1,
    'is_drop' => 1,
    'is_destruct' => 1,
    'crystal_type' => 'none',
    'consume_type' => 'consume_type_stackable',
  ],
  35541 => 
  [
    'item_id' => 35541,
    'icon' => 'etc_recipe_gold_i00',
    'name' => 'Recipe: Blessed Eternal Necklace (60%]',
    'additionalname' => '',
    'description' => 'For Dwarves only. Recipe for a Blessed Eternal Necklace. Requires Create Item - Skill Lv. 14. The success rate is 60%.',
    'is_trade' => 1,
    'is_drop' => 1,
    'is_destruct' => 1,
    'crystal_type' => 'none',
    'consume_type' => 'consume_type_stackable',
  ],
  35542 => 
  [
    'item_id' => 35542,
    'icon' => 'etc_recipe_gold_i00',
    'name' => 'Recipe: Blessed Eternal Earring (60%]',
    'additionalname' => '',
    'description' => 'For Dwarves only. Recipe for a Blessed Eternal Earring. Requires Create Item - Skill Lv. 14. The success rate is 60%.',
    'is_trade' => 1,
    'is_drop' => 1,
    'is_destruct' => 1,
    'crystal_type' => 'none',
    'consume_type' => 'consume_type_stackable',
  ],
  35543 => 
  [
    'item_id' => 35543,
    'icon' => 'etc_recipe_gold_i00',
    'name' => 'Recipe: Blessed Eternal Ring (60%]',
    'additionalname' => '',
    'description' => 'For Dwarves only. Recipe for a Blessed Eternal Ring. Requires Create Item - Skill Lv. 14. The success rate is 60%.',
    'is_trade' => 1,
    'is_drop' => 1,
    'is_destruct' => 1,
    'crystal_type' => 'none',
    'consume_type' => 'consume_type_stackable',
  ],
  35544 => 
  [
    'item_id' => 35544,
    'icon' => 'etc_badge_silver_i00',
    'name' => 'Tournament Remnants I',
    'additionalname' => '',
    'description' => 'A mysterious mark. It is used at the Mysterious Mansion in the Mysterious Suggestion quest as proof of participation in the tournament.',
    'is_trade' => 0,
    'is_drop' => 0,
    'is_destruct' => 1,
    'crystal_type' => 'none',
    'consume_type' => 'consume_type_stackable',
  ],
  35546 => 
  [
    'item_id' => 35546,
    'icon' => 'etc_exchange_box_i00',
    'name' => 'Deadman\'s Chest',
    'additionalname' => '',
    'description' => 'Box obtained after consoling the soul of the dead wandering in the Guillotine Fortress. Double-click to check for more information.',
    'is_trade' => 0,
    'is_drop' => 0,
    'is_destruct' => 0,
    'crystal_type' => 'none',
    'consume_type' => 'consume_type_stackable',
  ],
  35547 => 
  [
    'item_id' => 35547,
    'icon' => 'etc_exchange_box_i00',
    'name' => 'Deadman\'s Chest',
    'additionalname' => '',
    'description' => 'Box obtained after consoling the soul of the dead wandering in the Guillotine Fortress. Double-click to check for more information.',
    'is_trade' => 0,
    'is_drop' => 0,
    'is_destruct' => 0,
    'crystal_type' => 'none',
    'consume_type' => 'consume_type_stackable',
  ],
  35548 => 
  [
    'item_id' => 35548,
    'icon' => 'etc_pi_gift_box_i01',
    'name' => 'Engineer Zofan\'s Supply Box',
    'additionalname' => '',
    'description' => 'Box obtaining after completing the Destroy the Machine Device mission on the 2nd floor of the Seed of Hellfire. Double-click to check for more information.',
    'is_trade' => 0,
    'is_drop' => 0,
    'is_destruct' => 0,
    'crystal_type' => 'none',
    'consume_type' => 'consume_type_stackable',
  ],
  35549 => 
  [
    'item_id' => 35549,
    'icon' => 'etc_pi_gift_box_i00',
    'name' => 'Rebel\'s Supply Box',
    'additionalname' => '',
    'description' => 'Box obtained after helping the resistances forces in the Seed of Hellfire. Double-click to check for more information.',
    'is_trade' => 0,
    'is_drop' => 0,
    'is_destruct' => 0,
    'crystal_type' => 'none',
    'consume_type' => 'consume_type_stackable',
  ],
  35550 => 
  [
    'item_id' => 35550,
    'icon' => 'etc_pi_gift_box_i04',
    'name' => 'Aku\'s Supply Box',
    'additionalname' => '',
    'description' => 'Box obtained after helping Aku in the Seed of Hellfire. Double-click to check for more information.',
    'is_trade' => 0,
    'is_drop' => 0,
    'is_destruct' => 0,
    'crystal_type' => 'none',
    'consume_type' => 'consume_type_stackable',
  ],
  35551 => 
  [
    'item_id' => 35551,
    'icon' => 'etc_badge_silver_i00',
    'name' => 'Tournament Remnants II',
    'additionalname' => '',
    'description' => 'A mysterious mark. It is used at the Mysterious Mansion in the Mysterious Suggestion quest as proof of participation in the tournament.',
    'is_trade' => 0,
    'is_drop' => 0,
    'is_destruct' => 1,
    'crystal_type' => 'none',
    'consume_type' => 'consume_type_stackable',
  ],
  35552 => 
  [
    'item_id' => 35552,
    'icon' => 'etc_badge_gold_i00',
    'name' => 'Einhasad\'s Superior Medal',
    'additionalname' => '',
    'description' => 'Einhasad\'s Superior Medal obtained after defeating the Chamberlain of Darkness. Exchange it for a reward from the Captain of the Revolutionaries.',
    'is_trade' => 0,
    'is_drop' => 0,
    'is_destruct' => 1,
    'crystal_type' => 'none',
    'consume_type' => 'consume_type_stackable',
  ],
  35553 => 
  [
    'item_id' => 35553,
    'icon' => 'etc_badge_black_i00',
    'name' => 'Einhasad\'s Medal',
    'additionalname' => '',
    'description' => 'Einhasad\'s Medal obtained after defeating the Chamberlain of Darkness. Exchange it for a reward from the Captain of the Revolutionaries.',
    'is_trade' => 0,
    'is_drop' => 0,
    'is_destruct' => 1,
    'crystal_type' => 'none',
    'consume_type' => 'consume_type_stackable',
  ],
  35554 => 
  [
    'item_id' => 35554,
    'icon' => 'etc_badge_gold_i00',
    'name' => 'Revolutionaries\' Superior Medal',
    'additionalname' => '',
    'description' => 'Revolutionaries\' Superior Medal obtained after defeating the Chamberlain of Darkness. Exchange it for a reward from the Captain of the Revolutionaries.',
    'is_trade' => 0,
    'is_drop' => 0,
    'is_destruct' => 1,
    'crystal_type' => 'none',
    'consume_type' => 'consume_type_stackable',
  ],
  35555 => 
  [
    'item_id' => 35555,
    'icon' => 'etc_badge_black_i00',
    'name' => 'Revolutionaries\' Medal',
    'additionalname' => '',
    'description' => 'Revolutionaries\' Medal obtained after defeating the Chamberlain of Darkness. Exchange it for a reward from the Captain of the Revolutionaries.',
    'is_trade' => 0,
    'is_drop' => 0,
    'is_destruct' => 1,
    'crystal_type' => 'none',
    'consume_type' => 'consume_type_stackable',
  ],
  35556 => 
  [
    'item_id' => 35556,
    'icon' => 'etc_ticket_red_i00',
    'name' => 'Entrance Pass: Kartia\'s Labyrinth Lv. 85 Solo',
    'additionalname' => '',
    'description' => 'Kartia\'s Labyrinth Extra Pass delivered to adventurers from the Kartia Research Center. When used, you can reset your instance timer for the level 85 solo dungeon. Can be used only once a day.',
    'is_trade' => 0,
    'is_drop' => 0,
    'is_destruct' => 1,
    'crystal_type' => 'none',
    'consume_type' => 'consume_type_normal',
  ],
  35557 => 
  [
    'item_id' => 35557,
    'icon' => 'etc_ticket_red_i00',
    'name' => 'Entrance Pass: Kartia\'s Labyrinth Lv. 90 Solo',
    'additionalname' => '',
    'description' => 'Kartia\'s Labyrinth Extra Pass delivered to adventurers from the Kartia Research Center. When used, you can reset your instance timer for the level 90 solo dungeon. Can be used only once a day.',
    'is_trade' => 0,
    'is_drop' => 0,
    'is_destruct' => 1,
    'crystal_type' => 'none',
    'consume_type' => 'consume_type_normal',
  ],
  35558 => 
  [
    'item_id' => 35558,
    'icon' => 'etc_ticket_red_i00',
    'name' => 'Entrance Pass: Kartia\'s Labyrinth Lv. 95 Solo',
    'additionalname' => '',
    'description' => 'Kartia\'s Labyrinth Extra Pass delivered to adventurers from the Kartia Research Center. When used, you can reset your instance timer for the level 95 solo dungeon. Can be used only once a day.',
    'is_trade' => 0,
    'is_drop' => 0,
    'is_destruct' => 1,
    'crystal_type' => 'none',
    'consume_type' => 'consume_type_normal',
  ],
  35559 => 
  [
    'item_id' => 35559,
    'icon' => 'etc_ticket_red_i00',
    'name' => 'Entrance Pass: Kartia\'s Labyrinth Lv. 85 Party',
    'additionalname' => '',
    'description' => 'Kartia\'s Labyrinth Extra Pass delivered to adventurers from the Kartia Research Center. When used, you can reset your instance timer for the level 85 party dungeon. Can be used only once a day.',
    'is_trade' => 0,
    'is_drop' => 0,
    'is_destruct' => 1,
    'crystal_type' => 'none',
    'consume_type' => 'consume_type_normal',
  ],
  35560 => 
  [
    'item_id' => 35560,
    'icon' => 'etc_ticket_red_i00',
    'name' => 'Entrance Pass: Kartia\'s Labyrinth Lv. 90 Party',
    'additionalname' => '',
    'description' => 'Kartia\'s Labyrinth Extra Pass delivered to adventurers from the Kartia Research Center. When used, you can reset your instance timer for the level 90 party dungeon. Can be used only once a day.',
    'is_trade' => 0,
    'is_drop' => 0,
    'is_destruct' => 1,
    'crystal_type' => 'none',
    'consume_type' => 'consume_type_normal',
  ],
  35561 => 
  [
    'item_id' => 35561,
    'icon' => 'etc_ticket_red_i00',
    'name' => 'Entrance Pass: Kartia\'s Labyrinth Lv. 95 Party',
    'additionalname' => '',
    'description' => 'Kartia\'s Labyrinth Extra Pass delivered to adventurers from the Kartia Research Center. When used, you can reset your instance timer for the level 95 party dungeon. Can be used only once a day.',
    'is_trade' => 0,
    'is_drop' => 0,
    'is_destruct' => 1,
    'crystal_type' => 'none',
    'consume_type' => 'consume_type_normal',
  ],
  35562 => 
  [
    'item_id' => 35562,
    'icon' => 'etc_talisman_beads_i01',
    'name' => 'Energy of Destruction',
    'additionalname' => '',
    'description' => 'Use to exchange or enhance special items.',
    'is_trade' => 0,
    'is_drop' => 0,
    'is_destruct' => 1,
    'crystal_type' => 'none',
    'consume_type' => 'consume_type_stackable',
  ],
  35563 => 
  [
    'item_id' => 35563,
    'icon' => 'etc_talisman_energy_i01',
    'name' => 'Giant\'s Energy',
    'additionalname' => '',
    'description' => 'Use to exchange or enhance special items.',
    'is_trade' => 1,
    'is_drop' => 1,
    'is_destruct' => 1,
    'crystal_type' => 'none',
    'consume_type' => 'consume_type_stackable',
  ],
  35564 => 
  [
    'item_id' => 35564,
    'icon' => 'belt_rulers_authority',
    'name' => 'Ruler\'s Authority',
    'additionalname' => '',
    'description' => 'Item given to the winner of the Ceremony of Chaos that takes place in the Mysterious Mansion. When equipped, increases Max HP, MP, and CP by 1000, weight by 25600, and damage by 8%. Decreases received damage by 9% and Damage Reflect Resistance by 5%. Increases the number of inventory slots by 36, and Attribute Resistance by 15.',
    'is_trade' => 1,
    'is_drop' => 1,
    'is_destruct' => 1,
    'crystal_type' => 'r',
    'consume_type' => 'consume_type_normal',
  ],
  35565 => 
  [
    'item_id' => 35565,
    'icon' => 'belt_rulers_authority',
    'name' => 'Mysterious Belt',
    'additionalname' => '3-day',
    'description' => 'Item acquired after winning the Ceremony of Chaos Tournament in the Mysterious Mansion. When equipped, increases Max HP, MP, and CP by 500, PvP damage by 6%, and Damage Reflect Resistance by 5%. Decreases damage received during PvP by 7%.',
    'is_trade' => 0,
    'is_drop' => 0,
    'is_destruct' => 1,
    'crystal_type' => 's',
    'consume_type' => 'consume_type_normal',
  ],
  35566 => 
  [
    'item_id' => 35566,
    'icon' => 'energy_condenser_i03',
    'name' => 'Dark Amaranthine Enhancement Stone',
    'additionalname' => '',
    'description' => 'Bestows the PvP option on an Amaranthine weapon through the blacksmith. When the option is bestowed, Energy of Destruction and Giant\'s Energy, as well as an additional fee are required.',
    'is_trade' => 1,
    'is_drop' => 1,
    'is_destruct' => 1,
    'crystal_type' => 'none',
    'consume_type' => 'consume_type_stackable',
  ],
  35567 => 
  [
    'item_id' => 35567,
    'icon' => 'energy_condenser_i04',
    'name' => 'Dark Eternal Enhancement Stone',
    'additionalname' => '',
    'description' => 'Bestows the PvP option on Eternal armor through the blacksmith. When the option is bestowed, Energy of Destruction and Giant\'s Energy, as well as an additional fee are required.',
    'is_trade' => 1,
    'is_drop' => 1,
    'is_destruct' => 1,
    'crystal_type' => 'none',
    'consume_type' => 'consume_type_stackable',
  ],
  35568 => 
  [
    'item_id' => 35568,
    'icon' => 'energy_condenser_i05',
    'name' => 'Bloody Amaranthine Enhancement Stone',
    'additionalname' => '',
    'description' => 'Bestows the PvE option on an Amaranthine weapon through the blacksmith. When the option is bestowed, Energy of Destruction and Giant\'s Energy, as well as an additional fee are required.',
    'is_trade' => 1,
    'is_drop' => 1,
    'is_destruct' => 1,
    'crystal_type' => 'none',
    'consume_type' => 'consume_type_stackable',
  ],
  35569 => 
  [
    'item_id' => 35569,
    'icon' => 'energy_condenser_i06',
    'name' => 'Bloody Eternal Enhancement Stone',
    'additionalname' => '',
    'description' => 'Bestows the PvE option on Eternal armor through the blacksmith. When the option is bestowed, Energy of Destruction and Giant\'s Energy, as well as an additional fee are required.',
    'is_trade' => 1,
    'is_drop' => 1,
    'is_destruct' => 1,
    'crystal_type' => 'none',
    'consume_type' => 'consume_type_stackable',
  ],
  35570 => 
  [
    'item_id' => 35570,
    'icon' => 'accessary_tauti_ring',
    'name' => 'Tauti\'s Ring',
    'additionalname' => '',
    'description' => 'Tauti\'s Ring. Fire/Dark Resistance + 25, MP + 38, Critical Damage + 15%, Skill Power + 5%, PvP damage + 5%, Paralysis/Binding/Banishment Resistance + 10, Damage Reflect Resistance + 5, Absorption Resistance + 5, received PvP damage - 5%, and critical + 54 when a blunt is equipped. Even if you wear two identical rings, only the effects of one apply (excluding attributes/M. Def.].',
    'is_trade' => 1,
    'is_drop' => 1,
    'is_destruct' => 1,
    'crystal_type' => 'r',
    'consume_type' => 'consume_type_normal',
  ],
  35571 => 
  [
    'item_id' => 35571,
    'icon' => 'accessary_inferno_necklace_i00',
    'name' => 'Water Resistance Necklace',
    'additionalname' => '',
    'description' => 'Necklace purchased at the Mysterious Mansion. Water Resistance + 26, MP + 33.',
    'is_trade' => 1,
    'is_drop' => 1,
    'is_destruct' => 1,
    'crystal_type' => 'a',
    'consume_type' => 'consume_type_normal',
  ],
  35572 => 
  [
    'item_id' => 35572,
    'icon' => 'accessary_inferno_necklace_i00',
    'name' => 'Holy Resistance Necklace',
    'additionalname' => '',
    'description' => 'Necklace purchased at the Mysterious Mansion. Holy Resistance + 26, MP + 33.',
    'is_trade' => 1,
    'is_drop' => 1,
    'is_destruct' => 1,
    'crystal_type' => 'a',
    'consume_type' => 'consume_type_normal',
  ],
  35573 => 
  [
    'item_id' => 35573,
    'icon' => 'accessary_inferno_necklace_i00',
    'name' => 'Wind Resistance Necklace',
    'additionalname' => '',
    'description' => 'Necklace purchased at the Mysterious Mansion. Wind Resistance + 26, MP + 33.',
    'is_trade' => 1,
    'is_drop' => 1,
    'is_destruct' => 1,
    'crystal_type' => 'a',
    'consume_type' => 'consume_type_normal',
  ],
  35574 => 
  [
    'item_id' => 35574,
    'icon' => 'accessary_inferno_necklace_i00',
    'name' => 'Dark Resistance Necklace',
    'additionalname' => '',
    'description' => 'Necklace purchased at the Mysterious Mansion. Dark Resistance + 26, MP + 33.',
    'is_trade' => 1,
    'is_drop' => 1,
    'is_destruct' => 1,
    'crystal_type' => 'a',
    'consume_type' => 'consume_type_normal',
  ],
  35575 => 
  [
    'item_id' => 35575,
    'icon' => 'accessary_inferno_necklace_i00',
    'name' => 'Earth Resistance Necklace',
    'additionalname' => '',
    'description' => 'Necklace purchased at the Mysterious Mansion. Earth Resistance + 26, MP + 33.',
    'is_trade' => 1,
    'is_drop' => 1,
    'is_destruct' => 1,
    'crystal_type' => 'a',
    'consume_type' => 'consume_type_normal',
  ],
  35576 => 
  [
    'item_id' => 35576,
    'icon' => 'accessary_inferno_necklace_i00',
    'name' => 'Fire Resistance Necklace',
    'additionalname' => '',
    'description' => 'Necklace purchased at the Mysterious Mansion. Fire Resistance + 26, MP + 33.',
    'is_trade' => 1,
    'is_drop' => 1,
    'is_destruct' => 1,
    'crystal_type' => 'a',
    'consume_type' => 'consume_type_normal',
  ],
  35577 => 
  [
    'item_id' => 35577,
    'icon' => 'accessary_inferno_necklace_i00',
    'name' => 'Top-grade Water Resistance Necklace',
    'additionalname' => '',
    'description' => 'Necklace purchased at the Mysterious Mansion. Water Resistance + 30, MP + 62.',
    'is_trade' => 1,
    'is_drop' => 1,
    'is_destruct' => 1,
    'crystal_type' => 'r',
    'consume_type' => 'consume_type_normal',
  ],
  35578 => 
  [
    'item_id' => 35578,
    'icon' => 'accessary_inferno_necklace_i00',
    'name' => 'Top-grade Fire Resistance Necklace',
    'additionalname' => '',
    'description' => 'Necklace purchased at the Mysterious Mansion. Fire Resistance + 30, MP + 62.',
    'is_trade' => 1,
    'is_drop' => 1,
    'is_destruct' => 1,
    'crystal_type' => 'r',
    'consume_type' => 'consume_type_normal',
  ],
  35579 => 
  [
    'item_id' => 35579,
    'icon' => 'accessary_inferno_necklace_i00',
    'name' => 'Top-grade Holy Resistance Necklace',
    'additionalname' => '',
    'description' => 'Necklace purchased at the Mysterious Mansion. Holy Resistance + 30, MP + 62.',
    'is_trade' => 1,
    'is_drop' => 1,
    'is_destruct' => 1,
    'crystal_type' => 'r',
    'consume_type' => 'consume_type_normal',
  ],
  35580 => 
  [
    'item_id' => 35580,
    'icon' => 'accessary_inferno_necklace_i00',
    'name' => 'Top-grade Dark Resistance Necklace',
    'additionalname' => '',
    'description' => 'Necklace purchased at the Mysterious Mansion. Dark Resistance + 30, MP + 62.',
    'is_trade' => 1,
    'is_drop' => 1,
    'is_destruct' => 1,
    'crystal_type' => 'r',
    'consume_type' => 'consume_type_normal',
  ],
  35581 => 
  [
    'item_id' => 35581,
    'icon' => 'accessary_inferno_necklace_i00',
    'name' => 'Top-grade Wind Resistance Necklace',
    'additionalname' => '',
    'description' => 'Necklace purchased at the Mysterious Mansion. Wind Resistance + 30, MP + 62.',
    'is_trade' => 1,
    'is_drop' => 1,
    'is_destruct' => 1,
    'crystal_type' => 'r',
    'consume_type' => 'consume_type_normal',
  ],
  35582 => 
  [
    'item_id' => 35582,
    'icon' => 'accessary_inferno_necklace_i00',
    'name' => 'Top-grade Earth Resistance Necklace',
    'additionalname' => '',
    'description' => 'Necklace purchased at the Mysterious Mansion. Earth Resistance + 30, MP + 62.',
    'is_trade' => 1,
    'is_drop' => 1,
    'is_destruct' => 1,
    'crystal_type' => 'r',
    'consume_type' => 'consume_type_normal',
  ],
  35583 => 
  [
    'item_id' => 35583,
    'icon' => 'accessary_inferno_ring_i00',
    'name' => 'Earth Resistance Ring',
    'additionalname' => '',
    'description' => 'Ring purchased at the Mysterious Mansion. Earth Resistance + 12, MP + 17. Only one effect is applied when two rings with the same effect are equipped.',
    'is_trade' => 1,
    'is_drop' => 1,
    'is_destruct' => 1,
    'crystal_type' => 'a',
    'consume_type' => 'consume_type_normal',
  ],
  35584 => 
  [
    'item_id' => 35584,
    'icon' => 'accessary_inferno_ring_i00',
    'name' => 'Water Resistance Ring',
    'additionalname' => '',
    'description' => 'Ring purchased at the Mysterious Mansion. Water Resistance + 12, MP + 17. Only one effect is applied when two rings with the same effect are equipped.',
    'is_trade' => 1,
    'is_drop' => 1,
    'is_destruct' => 1,
    'crystal_type' => 'a',
    'consume_type' => 'consume_type_normal',
  ],
  35585 => 
  [
    'item_id' => 35585,
    'icon' => 'accessary_inferno_ring_i00',
    'name' => 'Fire Resistance Ring',
    'additionalname' => '',
    'description' => 'Ring purchased at the Mysterious Mansion. Fire Resistance + 12, MP + 17. Only one effect is applied when two rings with the same effect are equipped.',
    'is_trade' => 1,
    'is_drop' => 1,
    'is_destruct' => 1,
    'crystal_type' => 'a',
    'consume_type' => 'consume_type_normal',
  ],
  35586 => 
  [
    'item_id' => 35586,
    'icon' => 'accessary_inferno_ring_i00',
    'name' => 'Holy Resistance Ring',
    'additionalname' => '',
    'description' => 'Ring purchased at the Mysterious Mansion. Holy Resistance + 12, MP + 17. Only one effect is applied when two rings with the same effect are equipped.',
    'is_trade' => 1,
    'is_drop' => 1,
    'is_destruct' => 1,
    'crystal_type' => 'a',
    'consume_type' => 'consume_type_normal',
  ],
  35587 => 
  [
    'item_id' => 35587,
    'icon' => 'accessary_inferno_ring_i00',
    'name' => 'Dark Resistance Ring',
    'additionalname' => '',
    'description' => 'Ring purchased at the Mysterious Mansion. Dark Resistance + 12, MP + 17. Only one effect is applied when two rings with the same effect are equipped.',
    'is_trade' => 1,
    'is_drop' => 1,
    'is_destruct' => 1,
    'crystal_type' => 'a',
    'consume_type' => 'consume_type_normal',
  ],
  35588 => 
  [
    'item_id' => 35588,
    'icon' => 'accessary_inferno_ring_i00',
    'name' => 'Wind Resistance Ring',
    'additionalname' => '',
    'description' => 'Ring purchased at the Mysterious Mansion. Wind Resistance + 12, MP + 17. Only one effect is applied when two rings with the same effect are equipped.',
    'is_trade' => 1,
    'is_drop' => 1,
    'is_destruct' => 1,
    'crystal_type' => 'a',
    'consume_type' => 'consume_type_normal',
  ],
  35589 => 
  [
    'item_id' => 35589,
    'icon' => 'accessary_inferno_ring_i00',
    'name' => 'Top-grade Earth Resistance Ring',
    'additionalname' => '',
    'description' => 'Ring purchased at the Mysterious Mansion. Earth Resistance + 15, MP + 31. Only one effect is applied when two rings with the same effect are equipped.',
    'is_trade' => 1,
    'is_drop' => 1,
    'is_destruct' => 1,
    'crystal_type' => 'r',
    'consume_type' => 'consume_type_normal',
  ],
  35590 => 
  [
    'item_id' => 35590,
    'icon' => 'accessary_inferno_ring_i00',
    'name' => 'Top-grade Water Resistance Ring',
    'additionalname' => '',
    'description' => 'Ring purchased at the Mysterious Mansion. Water Resistance + 15, MP + 31. Only one effect is applied when two rings with the same effect are equipped.',
    'is_trade' => 1,
    'is_drop' => 1,
    'is_destruct' => 1,
    'crystal_type' => 'r',
    'consume_type' => 'consume_type_normal',
  ],
  35591 => 
  [
    'item_id' => 35591,
    'icon' => 'accessary_inferno_ring_i00',
    'name' => 'Top-grade Fire Resistance Ring',
    'additionalname' => '',
    'description' => 'Ring purchased at the Mysterious Mansion. Fire Resistance + 15, MP + 31. Only one effect is applied when two rings with the same effect are equipped.',
    'is_trade' => 1,
    'is_drop' => 1,
    'is_destruct' => 1,
    'crystal_type' => 'r',
    'consume_type' => 'consume_type_normal',
  ],
  35592 => 
  [
    'item_id' => 35592,
    'icon' => 'accessary_inferno_ring_i00',
    'name' => 'Top-grade Holy Resistance Ring',
    'additionalname' => '',
    'description' => 'Ring purchased at the Mysterious Mansion. Holy Resistance + 15, MP + 31. Only one effect is applied when two rings with the same effect are equipped.',
    'is_trade' => 1,
    'is_drop' => 1,
    'is_destruct' => 1,
    'crystal_type' => 'r',
    'consume_type' => 'consume_type_normal',
  ],
  35593 => 
  [
    'item_id' => 35593,
    'icon' => 'accessary_inferno_ring_i00',
    'name' => 'Top-grade Dark Resistance Ring',
    'additionalname' => '',
    'description' => 'Ring purchased at the Mysterious Mansion. Dark Resistance + 15, MP + 31. Only one effect is applied when two rings with the same effect are equipped.',
    'is_trade' => 1,
    'is_drop' => 1,
    'is_destruct' => 1,
    'crystal_type' => 'r',
    'consume_type' => 'consume_type_normal',
  ],
  35594 => 
  [
    'item_id' => 35594,
    'icon' => 'accessary_inferno_ring_i00',
    'name' => 'Top-grade Wind Resistance Ring',
    'additionalname' => '',
    'description' => 'Ring purchased at the Mysterious Mansion. Wind Resistance + 15, MP + 31. Only one effect is applied when two rings with the same effect are equipped.',
    'is_trade' => 1,
    'is_drop' => 1,
    'is_destruct' => 1,
    'crystal_type' => 'r',
    'consume_type' => 'consume_type_normal',
  ],
  35595 => 
  [
    'item_id' => 35595,
    'icon' => 'accessory_nectklace_of_domi_protection_i00',
    'name' => 'Water Royal Guard Necklace',
    'additionalname' => '',
    'description' => 'Necklace purchased at the Mysterious Mansion. Water Resistance + 30, MP + 46.',
    'is_trade' => 1,
    'is_drop' => 1,
    'is_destruct' => 1,
    'crystal_type' => 's80',
    'consume_type' => 'consume_type_normal',
  ],
  35596 => 
  [
    'item_id' => 35596,
    'icon' => 'accessory_nectklace_of_domi_protection_i00',
    'name' => 'Earth Royal Guard Necklace',
    'additionalname' => '',
    'description' => 'Necklace purchased at the Mysterious Mansion. Earth Resistance + 30, MP + 46.',
    'is_trade' => 1,
    'is_drop' => 1,
    'is_destruct' => 1,
    'crystal_type' => 's80',
    'consume_type' => 'consume_type_normal',
  ],
  35597 => 
  [
    'item_id' => 35597,
    'icon' => 'accessory_nectklace_of_domi_protection_i00',
    'name' => 'Fire Royal Guard Necklace',
    'additionalname' => '',
    'description' => 'Necklace purchased at the Mysterious Mansion. Fire Resistance + 30, MP + 46.',
    'is_trade' => 1,
    'is_drop' => 1,
    'is_destruct' => 1,
    'crystal_type' => 's80',
    'consume_type' => 'consume_type_normal',
  ],
  35598 => 
  [
    'item_id' => 35598,
    'icon' => 'accessory_nectklace_of_domi_protection_i00',
    'name' => 'Holy Royal Guard Necklace',
    'additionalname' => '',
    'description' => 'Necklace purchased at the Mysterious Mansion. Holy Resistance + 30, MP + 46.',
    'is_trade' => 1,
    'is_drop' => 1,
    'is_destruct' => 1,
    'crystal_type' => 's80',
    'consume_type' => 'consume_type_normal',
  ],
  35599 => 
  [
    'item_id' => 35599,
    'icon' => 'accessory_nectklace_of_domi_protection_i00',
    'name' => 'Dark Royal Guard Necklace',
    'additionalname' => '',
    'description' => 'Necklace purchased at the Mysterious Mansion. Dark Resistance + 30, MP + 46.',
    'is_trade' => 1,
    'is_drop' => 1,
    'is_destruct' => 1,
    'crystal_type' => 's80',
    'consume_type' => 'consume_type_normal',
  ],
];