<?php return [
  35800 => 
  [
    'item_id' => 35800,
    'icon' => 'accessory_romantic_chaperon_i00',
    'name' => 'Romantic Chapeau',
    'additionalname' => 'MEN',
    'description' => 'MEN +3 when equipped.',
    'is_trade' => 1,
    'is_drop' => 1,
    'is_destruct' => 1,
    'crystal_type' => 'none',
    'consume_type' => 'consume_type_normal',
  ],
  35801 => 
  [
    'item_id' => 35801,
    'icon' => 'accessory_romantic_chaperon_i00',
    'name' => 'Romantic Chapeau',
    'additionalname' => 'INT',
    'description' => 'INT +3 when equipped.',
    'is_trade' => 1,
    'is_drop' => 1,
    'is_destruct' => 1,
    'crystal_type' => 'none',
    'consume_type' => 'consume_type_normal',
  ],
  35802 => 
  [
    'item_id' => 35802,
    'icon' => 'accessory_romantic_chaperon_i00',
    'name' => 'Romantic Chapeau',
    'additionalname' => 'WIT',
    'description' => 'WIT +3 when equipped.',
    'is_trade' => 1,
    'is_drop' => 1,
    'is_destruct' => 1,
    'crystal_type' => 'none',
    'consume_type' => 'consume_type_normal',
  ],
  35803 => 
  [
    'item_id' => 35803,
    'icon' => 'accessory_romantic_chaperon_i00',
    'name' => 'Romantic Chapeau',
    'additionalname' => 'P. Def.',
    'description' => 'P. Def. +5% when equipped.',
    'is_trade' => 1,
    'is_drop' => 1,
    'is_destruct' => 1,
    'crystal_type' => 'none',
    'consume_type' => 'consume_type_normal',
  ],
  35804 => 
  [
    'item_id' => 35804,
    'icon' => 'accessory_romantic_chaperon_i00',
    'name' => 'Romantic Chapeau',
    'additionalname' => 'M. Def.',
    'description' => 'M. Def. +5% when equipped.',
    'is_trade' => 1,
    'is_drop' => 1,
    'is_destruct' => 1,
    'crystal_type' => 'none',
    'consume_type' => 'consume_type_normal',
  ],
  35805 => 
  [
    'item_id' => 35805,
    'icon' => 'accessory_romantic_chaperon_i00',
    'name' => 'Romantic Chapeau',
    'additionalname' => 'Evasion',
    'description' => 'Evasion +5 when equipped.',
    'is_trade' => 1,
    'is_drop' => 1,
    'is_destruct' => 1,
    'crystal_type' => 'none',
    'consume_type' => 'consume_type_normal',
  ],
  35806 => 
  [
    'item_id' => 35806,
    'icon' => 'accessory_romantic_chaperon_i00',
    'name' => 'Romantic Chapeau',
    'additionalname' => 'P. Atk.',
    'description' => 'P. Atk. +5%.',
    'is_trade' => 1,
    'is_drop' => 1,
    'is_destruct' => 1,
    'crystal_type' => 'none',
    'consume_type' => 'consume_type_normal',
  ],
  35807 => 
  [
    'item_id' => 35807,
    'icon' => 'accessory_romantic_chaperon_i00',
    'name' => 'Romantic Chapeau',
    'additionalname' => 'M. Atk.',
    'description' => 'M. Atk. +10% when equipped.',
    'is_trade' => 1,
    'is_drop' => 1,
    'is_destruct' => 1,
    'crystal_type' => 'none',
    'consume_type' => 'consume_type_normal',
  ],
  35808 => 
  [
    'item_id' => 35808,
    'icon' => 'accessory_romantic_chaperon_i00',
    'name' => 'Romantic Chapeau',
    'additionalname' => 'Accuracy',
    'description' => 'P. Accuracy +5.',
    'is_trade' => 1,
    'is_drop' => 1,
    'is_destruct' => 1,
    'crystal_type' => 'none',
    'consume_type' => 'consume_type_normal',
  ],
  35809 => 
  [
    'item_id' => 35809,
    'icon' => 'accessary_angel_circlet_i00',
    'name' => 'Angel Circlet',
    'additionalname' => 'STR',
    'description' => 'STR +3.',
    'is_trade' => 1,
    'is_drop' => 1,
    'is_destruct' => 1,
    'crystal_type' => 'none',
    'consume_type' => 'consume_type_normal',
  ],
  35810 => 
  [
    'item_id' => 35810,
    'icon' => 'accessary_angel_circlet_i00',
    'name' => 'Angel Circlet',
    'additionalname' => 'DEX',
    'description' => 'DEX +3.',
    'is_trade' => 1,
    'is_drop' => 1,
    'is_destruct' => 1,
    'crystal_type' => 'none',
    'consume_type' => 'consume_type_normal',
  ],
  35811 => 
  [
    'item_id' => 35811,
    'icon' => 'accessary_angel_circlet_i00',
    'name' => 'Angel Circlet',
    'additionalname' => 'CON',
    'description' => 'CON +3 when equipped.',
    'is_trade' => 1,
    'is_drop' => 1,
    'is_destruct' => 1,
    'crystal_type' => 'none',
    'consume_type' => 'consume_type_normal',
  ],
  35812 => 
  [
    'item_id' => 35812,
    'icon' => 'accessary_angel_circlet_i00',
    'name' => 'Angel Circlet',
    'additionalname' => 'MEN',
    'description' => 'MEN +3 when equipped.',
    'is_trade' => 1,
    'is_drop' => 1,
    'is_destruct' => 1,
    'crystal_type' => 'none',
    'consume_type' => 'consume_type_normal',
  ],
  35813 => 
  [
    'item_id' => 35813,
    'icon' => 'accessary_angel_circlet_i00',
    'name' => 'Angel Circlet',
    'additionalname' => 'INT',
    'description' => 'INT +3 when equipped.',
    'is_trade' => 1,
    'is_drop' => 1,
    'is_destruct' => 1,
    'crystal_type' => 'none',
    'consume_type' => 'consume_type_normal',
  ],
  35814 => 
  [
    'item_id' => 35814,
    'icon' => 'accessary_angel_circlet_i00',
    'name' => 'Angel Circlet',
    'additionalname' => 'WIT',
    'description' => 'WIT +3 when equipped.',
    'is_trade' => 1,
    'is_drop' => 1,
    'is_destruct' => 1,
    'crystal_type' => 'none',
    'consume_type' => 'consume_type_normal',
  ],
  35815 => 
  [
    'item_id' => 35815,
    'icon' => 'accessary_angel_circlet_i00',
    'name' => 'Angel Circlet',
    'additionalname' => 'Critical Rate',
    'description' => 'When equipped, Critical Rate for basic attacks +50.',
    'is_trade' => 1,
    'is_drop' => 1,
    'is_destruct' => 1,
    'crystal_type' => 'none',
    'consume_type' => 'consume_type_normal',
  ],
  35816 => 
  [
    'item_id' => 35816,
    'icon' => 'accessary_angel_circlet_i00',
    'name' => 'Angel Circlet',
    'additionalname' => 'Critical Damage',
    'description' => 'When equipped, Critical Damage for basic attacks +90, M. Skill Critical Damage +68.',
    'is_trade' => 1,
    'is_drop' => 1,
    'is_destruct' => 1,
    'crystal_type' => 'none',
    'consume_type' => 'consume_type_normal',
  ],
  35817 => 
  [
    'item_id' => 35817,
    'icon' => 'accessary_angel_circlet_i00',
    'name' => 'Angel Circlet',
    'additionalname' => 'P. Atk.',
    'description' => 'P. Atk. +5%.',
    'is_trade' => 1,
    'is_drop' => 1,
    'is_destruct' => 1,
    'crystal_type' => 'none',
    'consume_type' => 'consume_type_normal',
  ],
  35818 => 
  [
    'item_id' => 35818,
    'icon' => 'accessary_angel_circlet_i00',
    'name' => 'Angel Circlet',
    'additionalname' => 'M. Atk.',
    'description' => 'M. Atk. +10% when equipped.',
    'is_trade' => 1,
    'is_drop' => 1,
    'is_destruct' => 1,
    'crystal_type' => 'none',
    'consume_type' => 'consume_type_normal',
  ],
  35819 => 
  [
    'item_id' => 35819,
    'icon' => 'accessary_angel_circlet_i00',
    'name' => 'Angel Circlet',
    'additionalname' => 'Accuracy',
    'description' => 'P. Accuracy +5.',
    'is_trade' => 1,
    'is_drop' => 1,
    'is_destruct' => 1,
    'crystal_type' => 'none',
    'consume_type' => 'consume_type_normal',
  ],
  35820 => 
  [
    'item_id' => 35820,
    'icon' => 'accessary_demon_circlet_i00',
    'name' => 'Demon Circlet',
    'additionalname' => 'STR',
    'description' => 'STR +3.',
    'is_trade' => 1,
    'is_drop' => 1,
    'is_destruct' => 1,
    'crystal_type' => 'none',
    'consume_type' => 'consume_type_normal',
  ],
  35821 => 
  [
    'item_id' => 35821,
    'icon' => 'accessary_demon_circlet_i00',
    'name' => 'Demon Circlet',
    'additionalname' => 'DEX',
    'description' => 'DEX +3.',
    'is_trade' => 1,
    'is_drop' => 1,
    'is_destruct' => 1,
    'crystal_type' => 'none',
    'consume_type' => 'consume_type_normal',
  ],
  35822 => 
  [
    'item_id' => 35822,
    'icon' => 'accessary_demon_circlet_i00',
    'name' => 'Demon Circlet',
    'additionalname' => 'CON',
    'description' => 'CON +3 when equipped.',
    'is_trade' => 1,
    'is_drop' => 1,
    'is_destruct' => 1,
    'crystal_type' => 'none',
    'consume_type' => 'consume_type_normal',
  ],
  35823 => 
  [
    'item_id' => 35823,
    'icon' => 'accessary_demon_circlet_i00',
    'name' => 'Demon Circlet',
    'additionalname' => 'MEN',
    'description' => 'MEN +3 when equipped.',
    'is_trade' => 1,
    'is_drop' => 1,
    'is_destruct' => 1,
    'crystal_type' => 'none',
    'consume_type' => 'consume_type_normal',
  ],
  35824 => 
  [
    'item_id' => 35824,
    'icon' => 'accessary_demon_circlet_i00',
    'name' => 'Demon Circlet',
    'additionalname' => 'INT',
    'description' => 'INT +3 when equipped.',
    'is_trade' => 1,
    'is_drop' => 1,
    'is_destruct' => 1,
    'crystal_type' => 'none',
    'consume_type' => 'consume_type_normal',
  ],
  35825 => 
  [
    'item_id' => 35825,
    'icon' => 'accessary_demon_circlet_i00',
    'name' => 'Demon Circlet',
    'additionalname' => 'WIT',
    'description' => 'WIT +3 when equipped.',
    'is_trade' => 1,
    'is_drop' => 1,
    'is_destruct' => 1,
    'crystal_type' => 'none',
    'consume_type' => 'consume_type_normal',
  ],
  35826 => 
  [
    'item_id' => 35826,
    'icon' => 'accessary_demon_circlet_i00',
    'name' => 'Demon Circlet',
    'additionalname' => 'Critical Rate',
    'description' => 'When equipped, Critical Rate for basic attacks +50.',
    'is_trade' => 1,
    'is_drop' => 1,
    'is_destruct' => 1,
    'crystal_type' => 'none',
    'consume_type' => 'consume_type_normal',
  ],
  35827 => 
  [
    'item_id' => 35827,
    'icon' => 'accessary_demon_circlet_i00',
    'name' => 'Demon Circlet',
    'additionalname' => 'Critical Damage',
    'description' => 'When equipped, Critical Damage for basic attacks +90, M. Skill Critical Damage +68.',
    'is_trade' => 1,
    'is_drop' => 1,
    'is_destruct' => 1,
    'crystal_type' => 'none',
    'consume_type' => 'consume_type_normal',
  ],
  35828 => 
  [
    'item_id' => 35828,
    'icon' => 'accessary_demon_circlet_i00',
    'name' => 'Demon Circlet',
    'additionalname' => 'P. Def.',
    'description' => 'P. Def. +5% when equipped.',
    'is_trade' => 1,
    'is_drop' => 1,
    'is_destruct' => 1,
    'crystal_type' => 'none',
    'consume_type' => 'consume_type_normal',
  ],
  35829 => 
  [
    'item_id' => 35829,
    'icon' => 'accessary_demon_circlet_i00',
    'name' => 'Demon Circlet',
    'additionalname' => 'M. Def.',
    'description' => 'M. Def. +5% when equipped.',
    'is_trade' => 1,
    'is_drop' => 1,
    'is_destruct' => 1,
    'crystal_type' => 'none',
    'consume_type' => 'consume_type_normal',
  ],
  35830 => 
  [
    'item_id' => 35830,
    'icon' => 'accessary_demon_circlet_i00',
    'name' => 'Demon Circlet',
    'additionalname' => 'Evasion',
    'description' => 'Evasion +5 when equipped.',
    'is_trade' => 1,
    'is_drop' => 1,
    'is_destruct' => 1,
    'crystal_type' => 'none',
    'consume_type' => 'consume_type_normal',
  ],
  35831 => 
  [
    'item_id' => 35831,
    'icon' => 'accessory_eye_bandage_i00',
    'name' => 'Pirates Eyepatch',
    'additionalname' => 'CON',
    'description' => 'CON +3 when equipped.',
    'is_trade' => 1,
    'is_drop' => 1,
    'is_destruct' => 1,
    'crystal_type' => 'none',
    'consume_type' => 'consume_type_normal',
  ],
  35832 => 
  [
    'item_id' => 35832,
    'icon' => 'accessory_eye_bandage_i00',
    'name' => 'Pirates Eyepatch',
    'additionalname' => 'MEN',
    'description' => 'MEN +3 when equipped.',
    'is_trade' => 1,
    'is_drop' => 1,
    'is_destruct' => 1,
    'crystal_type' => 'none',
    'consume_type' => 'consume_type_normal',
  ],
  35833 => 
  [
    'item_id' => 35833,
    'icon' => 'accessory_eye_bandage_i00',
    'name' => 'Pirates Eyepatch',
    'additionalname' => 'INT',
    'description' => 'INT +3 when equipped.',
    'is_trade' => 1,
    'is_drop' => 1,
    'is_destruct' => 1,
    'crystal_type' => 'none',
    'consume_type' => 'consume_type_normal',
  ],
  35834 => 
  [
    'item_id' => 35834,
    'icon' => 'accessory_eye_bandage_i00',
    'name' => 'Pirates Eyepatch',
    'additionalname' => 'WIT',
    'description' => 'WIT +3 when equipped.',
    'is_trade' => 1,
    'is_drop' => 1,
    'is_destruct' => 1,
    'crystal_type' => 'none',
    'consume_type' => 'consume_type_normal',
  ],
  35835 => 
  [
    'item_id' => 35835,
    'icon' => 'accessory_eye_bandage_i00',
    'name' => 'Pirates Eyepatch',
    'additionalname' => 'Critical Rate',
    'description' => 'When equipped, Critical Rate for basic attacks +50.',
    'is_trade' => 1,
    'is_drop' => 1,
    'is_destruct' => 1,
    'crystal_type' => 'none',
    'consume_type' => 'consume_type_normal',
  ],
  35836 => 
  [
    'item_id' => 35836,
    'icon' => 'accessory_eye_bandage_i00',
    'name' => 'Pirates Eyepatch',
    'additionalname' => 'Critical Damage',
    'description' => 'When equipped, Critical Damage for basic attacks +90, M. Skill Critical Damage +68.',
    'is_trade' => 1,
    'is_drop' => 1,
    'is_destruct' => 1,
    'crystal_type' => 'none',
    'consume_type' => 'consume_type_normal',
  ],
  35837 => 
  [
    'item_id' => 35837,
    'icon' => 'accessory_eye_bandage_i00',
    'name' => 'Pirates Eyepatch',
    'additionalname' => 'P. Def.',
    'description' => 'P. Def. +5% when equipped.',
    'is_trade' => 1,
    'is_drop' => 1,
    'is_destruct' => 1,
    'crystal_type' => 'none',
    'consume_type' => 'consume_type_normal',
  ],
  35838 => 
  [
    'item_id' => 35838,
    'icon' => 'accessory_eye_bandage_i00',
    'name' => 'Pirates Eyepatch',
    'additionalname' => 'M. Def.',
    'description' => 'M. Def. +5% when equipped.',
    'is_trade' => 1,
    'is_drop' => 1,
    'is_destruct' => 1,
    'crystal_type' => 'none',
    'consume_type' => 'consume_type_normal',
  ],
  35839 => 
  [
    'item_id' => 35839,
    'icon' => 'accessory_eye_bandage_i00',
    'name' => 'Pirates Eyepatch',
    'additionalname' => 'Evasion',
    'description' => 'Evasion +5 when equipped.',
    'is_trade' => 1,
    'is_drop' => 1,
    'is_destruct' => 1,
    'crystal_type' => 'none',
    'consume_type' => 'consume_type_normal',
  ],
  35840 => 
  [
    'item_id' => 35840,
    'icon' => 'accessory_eye_bandage_i00',
    'name' => 'Pirates Eyepatch',
    'additionalname' => 'P. Atk.',
    'description' => 'P. Atk. +5%.',
    'is_trade' => 1,
    'is_drop' => 1,
    'is_destruct' => 1,
    'crystal_type' => 'none',
    'consume_type' => 'consume_type_normal',
  ],
  35841 => 
  [
    'item_id' => 35841,
    'icon' => 'accessory_eye_bandage_i00',
    'name' => 'Pirates Eyepatch',
    'additionalname' => 'M. Atk.',
    'description' => 'M. Atk. +10% when equipped.',
    'is_trade' => 1,
    'is_drop' => 1,
    'is_destruct' => 1,
    'crystal_type' => 'none',
    'consume_type' => 'consume_type_normal',
  ],
  35842 => 
  [
    'item_id' => 35842,
    'icon' => 'accessory_eye_bandage_i00',
    'name' => 'Pirates Eyepatch',
    'additionalname' => 'Accuracy',
    'description' => 'P. Accuracy +5.',
    'is_trade' => 1,
    'is_drop' => 1,
    'is_destruct' => 1,
    'crystal_type' => 'none',
    'consume_type' => 'consume_type_normal',
  ],
  35843 => 
  [
    'item_id' => 35843,
    'icon' => 'accessory_outlaw_eyepatch_i00',
    'name' => 'Outlaws Eyepatch',
    'additionalname' => 'STR',
    'description' => 'STR +3.',
    'is_trade' => 1,
    'is_drop' => 1,
    'is_destruct' => 1,
    'crystal_type' => 'none',
    'consume_type' => 'consume_type_normal',
  ],
  35844 => 
  [
    'item_id' => 35844,
    'icon' => 'accessory_outlaw_eyepatch_i00',
    'name' => 'Outlaws Eyepatch',
    'additionalname' => 'DEX',
    'description' => 'DEX +3.',
    'is_trade' => 1,
    'is_drop' => 1,
    'is_destruct' => 1,
    'crystal_type' => 'none',
    'consume_type' => 'consume_type_normal',
  ],
  35845 => 
  [
    'item_id' => 35845,
    'icon' => 'accessory_outlaw_eyepatch_i00',
    'name' => 'Outlaws Eyepatch',
    'additionalname' => 'INT',
    'description' => 'INT +3 when equipped.',
    'is_trade' => 1,
    'is_drop' => 1,
    'is_destruct' => 1,
    'crystal_type' => 'none',
    'consume_type' => 'consume_type_normal',
  ],
  35846 => 
  [
    'item_id' => 35846,
    'icon' => 'accessory_outlaw_eyepatch_i00',
    'name' => 'Outlaws Eyepatch',
    'additionalname' => 'WIT',
    'description' => 'WIT +3 when equipped.',
    'is_trade' => 1,
    'is_drop' => 1,
    'is_destruct' => 1,
    'crystal_type' => 'none',
    'consume_type' => 'consume_type_normal',
  ],
  35847 => 
  [
    'item_id' => 35847,
    'icon' => 'accessory_outlaw_eyepatch_i00',
    'name' => 'Outlaws Eyepatch',
    'additionalname' => 'Critical Rate',
    'description' => 'When equipped, Critical Rate for basic attacks +50.',
    'is_trade' => 1,
    'is_drop' => 1,
    'is_destruct' => 1,
    'crystal_type' => 'none',
    'consume_type' => 'consume_type_normal',
  ],
  35848 => 
  [
    'item_id' => 35848,
    'icon' => 'accessory_outlaw_eyepatch_i00',
    'name' => 'Outlaws Eyepatch',
    'additionalname' => 'Critical Damage',
    'description' => 'When equipped, Critical Damage for basic attacks +90, M. Skill Critical Damage +68.',
    'is_trade' => 1,
    'is_drop' => 1,
    'is_destruct' => 1,
    'crystal_type' => 'none',
    'consume_type' => 'consume_type_normal',
  ],
  35849 => 
  [
    'item_id' => 35849,
    'icon' => 'accessory_outlaw_eyepatch_i00',
    'name' => 'Outlaws Eyepatch',
    'additionalname' => 'P. Def.',
    'description' => 'P. Def. +5%, when equipped.',
    'is_trade' => 1,
    'is_drop' => 1,
    'is_destruct' => 1,
    'crystal_type' => 'none',
    'consume_type' => 'consume_type_normal',
  ],
  35850 => 
  [
    'item_id' => 35850,
    'icon' => 'accessory_outlaw_eyepatch_i00',
    'name' => 'Outlaws Eyepatch',
    'additionalname' => 'M. Def.',
    'description' => 'M. Def. +5%, when equipped.',
    'is_trade' => 1,
    'is_drop' => 1,
    'is_destruct' => 1,
    'crystal_type' => 'none',
    'consume_type' => 'consume_type_normal',
  ],
  35851 => 
  [
    'item_id' => 35851,
    'icon' => 'accessory_outlaw_eyepatch_i00',
    'name' => 'Outlaws Eyepatch',
    'additionalname' => 'Evasion',
    'description' => 'Evasion +5, when equipped.',
    'is_trade' => 1,
    'is_drop' => 1,
    'is_destruct' => 1,
    'crystal_type' => 'none',
    'consume_type' => 'consume_type_normal',
  ],
  35852 => 
  [
    'item_id' => 35852,
    'icon' => 'accessory_outlaw_eyepatch_i00',
    'name' => 'Outlaws Eyepatch',
    'additionalname' => 'P. Atk.',
    'description' => 'P. Atk. +5%, when equipped.',
    'is_trade' => 1,
    'is_drop' => 1,
    'is_destruct' => 1,
    'crystal_type' => 'none',
    'consume_type' => 'consume_type_normal',
  ],
  35853 => 
  [
    'item_id' => 35853,
    'icon' => 'accessory_outlaw_eyepatch_i00',
    'name' => 'Outlaws Eyepatch',
    'additionalname' => 'M. Atk.',
    'description' => 'M. Atk. +10%, when equipped.',
    'is_trade' => 1,
    'is_drop' => 1,
    'is_destruct' => 1,
    'crystal_type' => 'none',
    'consume_type' => 'consume_type_normal',
  ],
  35854 => 
  [
    'item_id' => 35854,
    'icon' => 'accessory_outlaw_eyepatch_i00',
    'name' => 'Outlaws Eyepatch',
    'additionalname' => 'Accuracy',
    'description' => 'P. Accuracy +5, when equipped.',
    'is_trade' => 1,
    'is_drop' => 1,
    'is_destruct' => 1,
    'crystal_type' => 'none',
    'consume_type' => 'consume_type_normal',
  ],
  35855 => 
  [
    'item_id' => 35855,
    'icon' => 'accessary_one_eye_i00',
    'name' => 'Eyepatch',
    'additionalname' => 'STR',
    'description' => 'STR +3.',
    'is_trade' => 1,
    'is_drop' => 1,
    'is_destruct' => 1,
    'crystal_type' => 'none',
    'consume_type' => 'consume_type_normal',
  ],
  35856 => 
  [
    'item_id' => 35856,
    'icon' => 'accessary_one_eye_i00',
    'name' => 'Eyepatch',
    'additionalname' => 'DEX',
    'description' => 'DEX +3.',
    'is_trade' => 1,
    'is_drop' => 1,
    'is_destruct' => 1,
    'crystal_type' => 'none',
    'consume_type' => 'consume_type_normal',
  ],
  35857 => 
  [
    'item_id' => 35857,
    'icon' => 'accessary_one_eye_i00',
    'name' => 'Eyepatch',
    'additionalname' => 'CON',
    'description' => 'CON +3 when equipped.',
    'is_trade' => 1,
    'is_drop' => 1,
    'is_destruct' => 1,
    'crystal_type' => 'none',
    'consume_type' => 'consume_type_normal',
  ],
  35858 => 
  [
    'item_id' => 35858,
    'icon' => 'accessary_one_eye_i00',
    'name' => 'Eyepatch',
    'additionalname' => 'MEN',
    'description' => 'MEN +3 when equipped.',
    'is_trade' => 1,
    'is_drop' => 1,
    'is_destruct' => 1,
    'crystal_type' => 'none',
    'consume_type' => 'consume_type_normal',
  ],
  35859 => 
  [
    'item_id' => 35859,
    'icon' => 'accessary_one_eye_i00',
    'name' => 'Eyepatch',
    'additionalname' => 'Critical Rate',
    'description' => 'When equipped, Critical Rate for basic attacks +50.',
    'is_trade' => 1,
    'is_drop' => 1,
    'is_destruct' => 1,
    'crystal_type' => 'none',
    'consume_type' => 'consume_type_normal',
  ],
  35860 => 
  [
    'item_id' => 35860,
    'icon' => 'accessary_one_eye_i00',
    'name' => 'Eyepatch',
    'additionalname' => 'Critical Damage',
    'description' => 'When equipped, Critical Damage for basic attacks +90, M. Skill Critical Damage +68.',
    'is_trade' => 1,
    'is_drop' => 1,
    'is_destruct' => 1,
    'crystal_type' => 'none',
    'consume_type' => 'consume_type_normal',
  ],
  35861 => 
  [
    'item_id' => 35861,
    'icon' => 'accessary_one_eye_i00',
    'name' => 'Eyepatch',
    'additionalname' => 'P. Def.',
    'description' => 'P. Def. +5% when equipped.',
    'is_trade' => 1,
    'is_drop' => 1,
    'is_destruct' => 1,
    'crystal_type' => 'none',
    'consume_type' => 'consume_type_normal',
  ],
  35862 => 
  [
    'item_id' => 35862,
    'icon' => 'accessary_one_eye_i00',
    'name' => 'Eyepatch',
    'additionalname' => 'M. Def.',
    'description' => 'M. Def. +5% when equipped.',
    'is_trade' => 1,
    'is_drop' => 1,
    'is_destruct' => 1,
    'crystal_type' => 'none',
    'consume_type' => 'consume_type_normal',
  ],
  35863 => 
  [
    'item_id' => 35863,
    'icon' => 'accessary_one_eye_i00',
    'name' => 'Eyepatch',
    'additionalname' => 'Evasion',
    'description' => 'Evasion +5 when equipped.',
    'is_trade' => 1,
    'is_drop' => 1,
    'is_destruct' => 1,
    'crystal_type' => 'none',
    'consume_type' => 'consume_type_normal',
  ],
  35864 => 
  [
    'item_id' => 35864,
    'icon' => 'accessary_one_eye_i00',
    'name' => 'Eyepatch',
    'additionalname' => 'P. Atk.',
    'description' => 'P. Atk. +5%.',
    'is_trade' => 1,
    'is_drop' => 1,
    'is_destruct' => 1,
    'crystal_type' => 'none',
    'consume_type' => 'consume_type_normal',
  ],
  35865 => 
  [
    'item_id' => 35865,
    'icon' => 'accessary_one_eye_i00',
    'name' => 'Eyepatch',
    'additionalname' => 'M. Atk.',
    'description' => 'M. Atk. +10% when equipped.',
    'is_trade' => 1,
    'is_drop' => 1,
    'is_destruct' => 1,
    'crystal_type' => 'none',
    'consume_type' => 'consume_type_normal',
  ],
  35866 => 
  [
    'item_id' => 35866,
    'icon' => 'accessary_one_eye_i00',
    'name' => 'Eyepatch',
    'additionalname' => 'Accuracy',
    'description' => 'P. Accuracy +5, when equipped.',
    'is_trade' => 1,
    'is_drop' => 1,
    'is_destruct' => 1,
    'crystal_type' => 'none',
    'consume_type' => 'consume_type_normal',
  ],
  35867 => 
  [
    'item_id' => 35867,
    'icon' => 'accessory_party_hat_i00',
    'name' => 'Party Hat',
    'additionalname' => 'STR',
    'description' => 'STR +3.',
    'is_trade' => 1,
    'is_drop' => 1,
    'is_destruct' => 1,
    'crystal_type' => 'none',
    'consume_type' => 'consume_type_normal',
  ],
  35868 => 
  [
    'item_id' => 35868,
    'icon' => 'accessory_party_hat_i00',
    'name' => 'Party Hat',
    'additionalname' => 'DEX',
    'description' => 'DEX +3.',
    'is_trade' => 1,
    'is_drop' => 1,
    'is_destruct' => 1,
    'crystal_type' => 'none',
    'consume_type' => 'consume_type_normal',
  ],
  35869 => 
  [
    'item_id' => 35869,
    'icon' => 'accessory_party_hat_i00',
    'name' => 'Party Hat',
    'additionalname' => 'CON',
    'description' => 'CON +3 when equipped.',
    'is_trade' => 1,
    'is_drop' => 1,
    'is_destruct' => 1,
    'crystal_type' => 'none',
    'consume_type' => 'consume_type_normal',
  ],
  35870 => 
  [
    'item_id' => 35870,
    'icon' => 'accessory_party_hat_i00',
    'name' => 'Party Hat',
    'additionalname' => 'MEN',
    'description' => 'MEN +3 when equipped.',
    'is_trade' => 1,
    'is_drop' => 1,
    'is_destruct' => 1,
    'crystal_type' => 'none',
    'consume_type' => 'consume_type_normal',
  ],
  35871 => 
  [
    'item_id' => 35871,
    'icon' => 'accessory_party_hat_i00',
    'name' => 'Party Hat',
    'additionalname' => 'INT',
    'description' => 'INT +3 when equipped.',
    'is_trade' => 1,
    'is_drop' => 1,
    'is_destruct' => 1,
    'crystal_type' => 'none',
    'consume_type' => 'consume_type_normal',
  ],
  35872 => 
  [
    'item_id' => 35872,
    'icon' => 'accessory_party_hat_i00',
    'name' => 'Party Hat',
    'additionalname' => 'WIT',
    'description' => 'WIT +3 when equipped.',
    'is_trade' => 1,
    'is_drop' => 1,
    'is_destruct' => 1,
    'crystal_type' => 'none',
    'consume_type' => 'consume_type_normal',
  ],
  35873 => 
  [
    'item_id' => 35873,
    'icon' => 'accessory_party_hat_i00',
    'name' => 'Party Hat',
    'additionalname' => 'P. Def.',
    'description' => 'P. Def. +5%, when equipped.',
    'is_trade' => 1,
    'is_drop' => 1,
    'is_destruct' => 1,
    'crystal_type' => 'none',
    'consume_type' => 'consume_type_normal',
  ],
  35874 => 
  [
    'item_id' => 35874,
    'icon' => 'accessory_party_hat_i00',
    'name' => 'Party Hat',
    'additionalname' => 'M. Def.',
    'description' => 'M. Def. +5%, when equipped.',
    'is_trade' => 1,
    'is_drop' => 1,
    'is_destruct' => 1,
    'crystal_type' => 'none',
    'consume_type' => 'consume_type_normal',
  ],
  35875 => 
  [
    'item_id' => 35875,
    'icon' => 'accessory_party_hat_i00',
    'name' => 'Party Hat',
    'additionalname' => 'Evasion',
    'description' => 'Evasion +5, when equipped.',
    'is_trade' => 1,
    'is_drop' => 1,
    'is_destruct' => 1,
    'crystal_type' => 'none',
    'consume_type' => 'consume_type_normal',
  ],
  35876 => 
  [
    'item_id' => 35876,
    'icon' => 'accessory_party_hat_i00',
    'name' => 'Party Hat',
    'additionalname' => 'P. Atk.',
    'description' => 'P. Atk. +5%, when equipped.',
    'is_trade' => 1,
    'is_drop' => 1,
    'is_destruct' => 1,
    'crystal_type' => 'none',
    'consume_type' => 'consume_type_normal',
  ],
  35877 => 
  [
    'item_id' => 35877,
    'icon' => 'accessory_party_hat_i00',
    'name' => 'Party Hat',
    'additionalname' => 'M. Atk.',
    'description' => 'M. Atk. +10%, when equipped.',
    'is_trade' => 1,
    'is_drop' => 1,
    'is_destruct' => 1,
    'crystal_type' => 'none',
    'consume_type' => 'consume_type_normal',
  ],
  35878 => 
  [
    'item_id' => 35878,
    'icon' => 'accessory_party_hat_i00',
    'name' => 'Party Hat',
    'additionalname' => 'Accuracy',
    'description' => 'P. Accuracy +5.',
    'is_trade' => 1,
    'is_drop' => 1,
    'is_destruct' => 1,
    'crystal_type' => 'none',
    'consume_type' => 'consume_type_normal',
  ],
  35879 => 
  [
    'item_id' => 35879,
    'icon' => 'accessory_angel_ring_i00',
    'name' => 'Refined Angel Ring',
    'additionalname' => 'STR',
    'description' => 'STR +3.',
    'is_trade' => 1,
    'is_drop' => 1,
    'is_destruct' => 1,
    'crystal_type' => 'none',
    'consume_type' => 'consume_type_normal',
  ],
  35880 => 
  [
    'item_id' => 35880,
    'icon' => 'accessory_angel_ring_i00',
    'name' => 'Refined Angel Ring',
    'additionalname' => 'DEX',
    'description' => 'DEX +3.',
    'is_trade' => 1,
    'is_drop' => 1,
    'is_destruct' => 1,
    'crystal_type' => 'none',
    'consume_type' => 'consume_type_normal',
  ],
  35881 => 
  [
    'item_id' => 35881,
    'icon' => 'accessory_angel_ring_i00',
    'name' => 'Refined Angel Ring',
    'additionalname' => 'CON',
    'description' => 'CON +3 when equipped.',
    'is_trade' => 1,
    'is_drop' => 1,
    'is_destruct' => 1,
    'crystal_type' => 'none',
    'consume_type' => 'consume_type_normal',
  ],
  35882 => 
  [
    'item_id' => 35882,
    'icon' => 'accessory_angel_ring_i00',
    'name' => 'Refined Angel Ring',
    'additionalname' => 'MEN',
    'description' => 'MEN +3 when equipped.',
    'is_trade' => 1,
    'is_drop' => 1,
    'is_destruct' => 1,
    'crystal_type' => 'none',
    'consume_type' => 'consume_type_normal',
  ],
  35883 => 
  [
    'item_id' => 35883,
    'icon' => 'accessory_angel_ring_i00',
    'name' => 'Refined Angel Ring',
    'additionalname' => 'INT',
    'description' => 'INT +3 when equipped.',
    'is_trade' => 1,
    'is_drop' => 1,
    'is_destruct' => 1,
    'crystal_type' => 'none',
    'consume_type' => 'consume_type_normal',
  ],
  35884 => 
  [
    'item_id' => 35884,
    'icon' => 'accessory_angel_ring_i00',
    'name' => 'Refined Angel Ring',
    'additionalname' => 'WIT',
    'description' => 'WIT +3 when equipped.',
    'is_trade' => 1,
    'is_drop' => 1,
    'is_destruct' => 1,
    'crystal_type' => 'none',
    'consume_type' => 'consume_type_normal',
  ],
  35885 => 
  [
    'item_id' => 35885,
    'icon' => 'accessory_angel_ring_i00',
    'name' => 'Refined Angel Ring',
    'additionalname' => 'Critical Rate',
    'description' => 'When equipped, Critical Rate for basic attacks +50.',
    'is_trade' => 1,
    'is_drop' => 1,
    'is_destruct' => 1,
    'crystal_type' => 'none',
    'consume_type' => 'consume_type_normal',
  ],
  35886 => 
  [
    'item_id' => 35886,
    'icon' => 'accessory_angel_ring_i00',
    'name' => 'Refined Angel Ring',
    'additionalname' => 'Critical Damage',
    'description' => 'When equipped, Critical Damage for basic attacks +90, M. Skill Critical Damage +68.',
    'is_trade' => 1,
    'is_drop' => 1,
    'is_destruct' => 1,
    'crystal_type' => 'none',
    'consume_type' => 'consume_type_normal',
  ],
  35887 => 
  [
    'item_id' => 35887,
    'icon' => 'accessory_angel_ring_i00',
    'name' => 'Refined Angel Ring',
    'additionalname' => 'P. Atk.',
    'description' => 'P. Atk. +5%.',
    'is_trade' => 1,
    'is_drop' => 1,
    'is_destruct' => 1,
    'crystal_type' => 'none',
    'consume_type' => 'consume_type_normal',
  ],
  35888 => 
  [
    'item_id' => 35888,
    'icon' => 'accessory_angel_ring_i00',
    'name' => 'Refined Angel Ring',
    'additionalname' => 'M. Atk.',
    'description' => 'M. Atk. +10% when equipped.',
    'is_trade' => 1,
    'is_drop' => 1,
    'is_destruct' => 1,
    'crystal_type' => 'none',
    'consume_type' => 'consume_type_normal',
  ],
  35889 => 
  [
    'item_id' => 35889,
    'icon' => 'accessory_angel_ring_i00',
    'name' => 'Refined Angel Ring',
    'additionalname' => 'Accuracy',
    'description' => 'P. Accuracy +5.',
    'is_trade' => 1,
    'is_drop' => 1,
    'is_destruct' => 1,
    'crystal_type' => 'none',
    'consume_type' => 'consume_type_normal',
  ],
  35890 => 
  [
    'item_id' => 35890,
    'icon' => 'accessory_devil_horn_i00',
    'name' => 'Refined Devil Horn',
    'additionalname' => 'STR',
    'description' => 'STR +3.',
    'is_trade' => 1,
    'is_drop' => 1,
    'is_destruct' => 1,
    'crystal_type' => 'none',
    'consume_type' => 'consume_type_normal',
  ],
  35891 => 
  [
    'item_id' => 35891,
    'icon' => 'accessory_devil_horn_i00',
    'name' => 'Refined Devil Horn',
    'additionalname' => 'DEX',
    'description' => 'DEX +3.',
    'is_trade' => 1,
    'is_drop' => 1,
    'is_destruct' => 1,
    'crystal_type' => 'none',
    'consume_type' => 'consume_type_normal',
  ],
  35892 => 
  [
    'item_id' => 35892,
    'icon' => 'accessory_devil_horn_i00',
    'name' => 'Refined Devil Horn',
    'additionalname' => 'CON',
    'description' => 'CON +3 when equipped.',
    'is_trade' => 1,
    'is_drop' => 1,
    'is_destruct' => 1,
    'crystal_type' => 'none',
    'consume_type' => 'consume_type_normal',
  ],
  35893 => 
  [
    'item_id' => 35893,
    'icon' => 'accessory_devil_horn_i00',
    'name' => 'Refined Devil Horn',
    'additionalname' => 'MEN',
    'description' => 'MEN +3 when equipped.',
    'is_trade' => 1,
    'is_drop' => 1,
    'is_destruct' => 1,
    'crystal_type' => 'none',
    'consume_type' => 'consume_type_normal',
  ],
  35894 => 
  [
    'item_id' => 35894,
    'icon' => 'accessory_devil_horn_i00',
    'name' => 'Refined Devil Horn',
    'additionalname' => 'INT',
    'description' => 'INT +3 when equipped.',
    'is_trade' => 1,
    'is_drop' => 1,
    'is_destruct' => 1,
    'crystal_type' => 'none',
    'consume_type' => 'consume_type_normal',
  ],
  35895 => 
  [
    'item_id' => 35895,
    'icon' => 'accessory_devil_horn_i00',
    'name' => 'Refined Devil Horn',
    'additionalname' => 'WIT',
    'description' => 'WIT +3 when equipped.',
    'is_trade' => 1,
    'is_drop' => 1,
    'is_destruct' => 1,
    'crystal_type' => 'none',
    'consume_type' => 'consume_type_normal',
  ],
  35896 => 
  [
    'item_id' => 35896,
    'icon' => 'accessory_devil_horn_i00',
    'name' => 'Refined Devil Horn',
    'additionalname' => 'Critical Rate',
    'description' => 'When equipped, Critical Rate for basic attacks +50.',
    'is_trade' => 1,
    'is_drop' => 1,
    'is_destruct' => 1,
    'crystal_type' => 'none',
    'consume_type' => 'consume_type_normal',
  ],
  35897 => 
  [
    'item_id' => 35897,
    'icon' => 'accessory_devil_horn_i00',
    'name' => 'Refined Devil Horn',
    'additionalname' => 'Critical Damage',
    'description' => 'When equipped, Critical Damage for basic attacks +90, M. Skill Critical Damage +68.',
    'is_trade' => 1,
    'is_drop' => 1,
    'is_destruct' => 1,
    'crystal_type' => 'none',
    'consume_type' => 'consume_type_normal',
  ],
  35898 => 
  [
    'item_id' => 35898,
    'icon' => 'accessory_devil_horn_i00',
    'name' => 'Refined Devil Horn',
    'additionalname' => 'P. Def.',
    'description' => 'P. Def. +5% when equipped.',
    'is_trade' => 1,
    'is_drop' => 1,
    'is_destruct' => 1,
    'crystal_type' => 'none',
    'consume_type' => 'consume_type_normal',
  ],
  35899 => 
  [
    'item_id' => 35899,
    'icon' => 'accessory_devil_horn_i00',
    'name' => 'Refined Devil Horn',
    'additionalname' => 'M. Def.',
    'description' => 'M. Def. +5% when equipped.',
    'is_trade' => 1,
    'is_drop' => 1,
    'is_destruct' => 1,
    'crystal_type' => 'none',
    'consume_type' => 'consume_type_normal',
  ],
];