<?php return [
  38000 => 
  [
    'item_id' => 38000,
    'icon' => 'event_hero_treasure_box_i00',
    'name' => 'Twilight Leather Leggings Crafting Pack',
    'additionalname' => 'Light Armor',
    'description' => 'Wrapped Pack containing all ingredients needed for crafting Twilight Leather Leggings.',
    'is_trade' => 1,
    'is_drop' => 1,
    'is_destruct' => 1,
    'crystal_type' => 'none',
    'consume_type' => 'consume_type_stackable',
  ],
  38001 => 
  [
    'item_id' => 38001,
    'icon' => 'event_hero_treasure_box_i00',
    'name' => 'Twilight Leather Gloves Crafting Pack',
    'additionalname' => 'Light Armor',
    'description' => 'Wrapped Pack containing all ingredients needed for crafting Twilight Leather Gloves.',
    'is_trade' => 1,
    'is_drop' => 1,
    'is_destruct' => 1,
    'crystal_type' => 'none',
    'consume_type' => 'consume_type_stackable',
  ],
  38002 => 
  [
    'item_id' => 38002,
    'icon' => 'event_hero_treasure_box_i00',
    'name' => 'Twilight Leather Boots Crafting Pack',
    'additionalname' => 'Light Armor',
    'description' => 'Wrapped Pack containing all ingredients needed for crafting Twilight Leather Boots.',
    'is_trade' => 1,
    'is_drop' => 1,
    'is_destruct' => 1,
    'crystal_type' => 'none',
    'consume_type' => 'consume_type_stackable',
  ],
  38003 => 
  [
    'item_id' => 38003,
    'icon' => 'event_hero_treasure_box_i00',
    'name' => 'Twilight Circlet Crafting Pack',
    'additionalname' => 'Robe',
    'description' => 'Wrapped Pack containing all ingredients needed for crafting Twilight Circlet.',
    'is_trade' => 1,
    'is_drop' => 1,
    'is_destruct' => 1,
    'crystal_type' => 'none',
    'consume_type' => 'consume_type_stackable',
  ],
  38004 => 
  [
    'item_id' => 38004,
    'icon' => 'event_hero_treasure_box_i00',
    'name' => 'Twilight Tunic Crafting Pack',
    'additionalname' => 'Robe',
    'description' => 'Wrapped Pack containing all ingredients needed for crafting Twilight Tunic.',
    'is_trade' => 1,
    'is_drop' => 1,
    'is_destruct' => 1,
    'crystal_type' => 'none',
    'consume_type' => 'consume_type_stackable',
  ],
  38005 => 
  [
    'item_id' => 38005,
    'icon' => 'event_hero_treasure_box_i00',
    'name' => 'Twilight Stockings Crafting Pack',
    'additionalname' => 'Robe',
    'description' => 'Wrapped Pack containing all ingredients needed for crafting Twilight Stockings.',
    'is_trade' => 1,
    'is_drop' => 1,
    'is_destruct' => 1,
    'crystal_type' => 'none',
    'consume_type' => 'consume_type_stackable',
  ],
  38006 => 
  [
    'item_id' => 38006,
    'icon' => 'event_hero_treasure_box_i00',
    'name' => 'Twilight Gloves Crafting Pack',
    'additionalname' => 'Robe',
    'description' => 'Wrapped Pack containing all ingredients needed for crafting Twilight Gloves.',
    'is_trade' => 1,
    'is_drop' => 1,
    'is_destruct' => 1,
    'crystal_type' => 'none',
    'consume_type' => 'consume_type_stackable',
  ],
  38007 => 
  [
    'item_id' => 38007,
    'icon' => 'event_hero_treasure_box_i00',
    'name' => 'Twilight Shoes Crafting Pack',
    'additionalname' => 'Robe',
    'description' => 'Wrapped Pack containing all ingredients needed for crafting Twilight Shoes.',
    'is_trade' => 1,
    'is_drop' => 1,
    'is_destruct' => 1,
    'crystal_type' => 'none',
    'consume_type' => 'consume_type_stackable',
  ],
  38008 => 
  [
    'item_id' => 38008,
    'icon' => 'event_hero_treasure_box_i00',
    'name' => 'Twilight Sigil Crafting Pack',
    'additionalname' => 'Robe',
    'description' => 'Wrapped Pack containing all ingredients needed for crafting Twilight Sigil.',
    'is_trade' => 1,
    'is_drop' => 1,
    'is_destruct' => 1,
    'crystal_type' => 'none',
    'consume_type' => 'consume_type_stackable',
  ],
  38009 => 
  [
    'item_id' => 38009,
    'icon' => 'event_hero_treasure_box_i00',
    'name' => 'Twilight Necklace Crafting Pack',
    'additionalname' => '',
    'description' => 'Wrapped Pack containing all ingredients needed for crafting Twilight Necklace.',
    'is_trade' => 1,
    'is_drop' => 1,
    'is_destruct' => 1,
    'crystal_type' => 'none',
    'consume_type' => 'consume_type_stackable',
  ],
  38010 => 
  [
    'item_id' => 38010,
    'icon' => 'event_hero_treasure_box_i00',
    'name' => 'Twilight Earring Crafting Pack',
    'additionalname' => '',
    'description' => 'Wrapped Pack containing all ingredients needed for crafting Twilight Earring.',
    'is_trade' => 1,
    'is_drop' => 1,
    'is_destruct' => 1,
    'crystal_type' => 'none',
    'consume_type' => 'consume_type_stackable',
  ],
  38011 => 
  [
    'item_id' => 38011,
    'icon' => 'event_hero_treasure_box_i00',
    'name' => 'Twilight Ring Crafting Pack',
    'additionalname' => '',
    'description' => 'Wrapped Pack containing all ingredients needed for crafting Twilight Ring.',
    'is_trade' => 1,
    'is_drop' => 1,
    'is_destruct' => 1,
    'crystal_type' => 'none',
    'consume_type' => 'consume_type_stackable',
  ],
  38012 => 
  [
    'item_id' => 38012,
    'icon' => 'event_hero_treasure_box_i00',
    'name' => 'Specter Shaper Crafting Pack',
    'additionalname' => '',
    'description' => 'Wrapped Pack containing all ingredients needed for crafting Specter Shaper.',
    'is_trade' => 1,
    'is_drop' => 1,
    'is_destruct' => 1,
    'crystal_type' => 'none',
    'consume_type' => 'consume_type_stackable',
  ],
  38013 => 
  [
    'item_id' => 38013,
    'icon' => 'event_hero_treasure_box_i00',
    'name' => 'Specter Cutter Crafting Pack',
    'additionalname' => '',
    'description' => 'Wrapped Pack containing all ingredients needed for crafting Specter Cutter.',
    'is_trade' => 1,
    'is_drop' => 1,
    'is_destruct' => 1,
    'crystal_type' => 'none',
    'consume_type' => 'consume_type_stackable',
  ],
  38014 => 
  [
    'item_id' => 38014,
    'icon' => 'event_hero_treasure_box_i00',
    'name' => 'Specter Slasher Crafting Pack',
    'additionalname' => '',
    'description' => 'Wrapped Pack containing all ingredients needed for crafting Specter Slasher.',
    'is_trade' => 1,
    'is_drop' => 1,
    'is_destruct' => 1,
    'crystal_type' => 'none',
    'consume_type' => 'consume_type_stackable',
  ],
  38015 => 
  [
    'item_id' => 38015,
    'icon' => 'event_hero_treasure_box_i00',
    'name' => 'Specter Avenger Crafting Pack',
    'additionalname' => '',
    'description' => 'Wrapped Pack containing all ingredients needed for crafting Specter Avenger.',
    'is_trade' => 1,
    'is_drop' => 1,
    'is_destruct' => 1,
    'crystal_type' => 'none',
    'consume_type' => 'consume_type_stackable',
  ],
  38016 => 
  [
    'item_id' => 38016,
    'icon' => 'event_hero_treasure_box_i00',
    'name' => 'Specter Fighter Crafting Pack',
    'additionalname' => '',
    'description' => 'Wrapped Pack containing all ingredients needed for crafting Specter Fighter.',
    'is_trade' => 1,
    'is_drop' => 1,
    'is_destruct' => 1,
    'crystal_type' => 'none',
    'consume_type' => 'consume_type_stackable',
  ],
  38017 => 
  [
    'item_id' => 38017,
    'icon' => 'event_hero_treasure_box_i00',
    'name' => 'Specter Stormer Crafting Pack',
    'additionalname' => '',
    'description' => 'Wrapped Pack containing all ingredients needed for crafting Specter Stormer.',
    'is_trade' => 1,
    'is_drop' => 1,
    'is_destruct' => 1,
    'crystal_type' => 'none',
    'consume_type' => 'consume_type_stackable',
  ],
  38018 => 
  [
    'item_id' => 38018,
    'icon' => 'event_hero_treasure_box_i00',
    'name' => 'Specter Thrower Crafting Pack',
    'additionalname' => '',
    'description' => 'Wrapped Pack containing all ingredients needed for crafting Specter Thrower.',
    'is_trade' => 1,
    'is_drop' => 1,
    'is_destruct' => 1,
    'crystal_type' => 'none',
    'consume_type' => 'consume_type_stackable',
  ],
  38019 => 
  [
    'item_id' => 38019,
    'icon' => 'event_hero_treasure_box_i00',
    'name' => 'Specter Shooter Crafting Pack',
    'additionalname' => '',
    'description' => 'Wrapped Pack containing all ingredients needed for crafting Specter Shooter.',
    'is_trade' => 1,
    'is_drop' => 1,
    'is_destruct' => 1,
    'crystal_type' => 'none',
    'consume_type' => 'consume_type_stackable',
  ],
  38020 => 
  [
    'item_id' => 38020,
    'icon' => 'event_hero_treasure_box_i00',
    'name' => 'Specter Buster Crafting Pack',
    'additionalname' => '',
    'description' => 'Wrapped Pack containing all ingredients needed for crafting Specter Buster.',
    'is_trade' => 1,
    'is_drop' => 1,
    'is_destruct' => 1,
    'crystal_type' => 'none',
    'consume_type' => 'consume_type_stackable',
  ],
  38021 => 
  [
    'item_id' => 38021,
    'icon' => 'event_hero_treasure_box_i00',
    'name' => 'Specter Caster Crafting Pack',
    'additionalname' => '',
    'description' => 'Wrapped Pack containing all ingredients needed for crafting Specter Caster.',
    'is_trade' => 1,
    'is_drop' => 1,
    'is_destruct' => 1,
    'crystal_type' => 'none',
    'consume_type' => 'consume_type_stackable',
  ],
  38022 => 
  [
    'item_id' => 38022,
    'icon' => 'event_hero_treasure_box_i00',
    'name' => 'Specter Retributer Crafting Pack',
    'additionalname' => '',
    'description' => 'Wrapped Pack containing all ingredients needed for crafting Specter Retributer.',
    'is_trade' => 1,
    'is_drop' => 1,
    'is_destruct' => 1,
    'crystal_type' => 'none',
    'consume_type' => 'consume_type_stackable',
  ],
  38023 => 
  [
    'item_id' => 38023,
    'icon' => 'event_hero_treasure_box_i00',
    'name' => 'Seraph Helmet Crafting Pack',
    'additionalname' => 'Heavy Armor',
    'description' => 'Wrapped Pack containing all ingredients needed for crafting Seraph Helmet.',
    'is_trade' => 1,
    'is_drop' => 1,
    'is_destruct' => 1,
    'crystal_type' => 'none',
    'consume_type' => 'consume_type_stackable',
  ],
  38024 => 
  [
    'item_id' => 38024,
    'icon' => 'event_hero_treasure_box_i00',
    'name' => 'Seraph Breastplate Crafting Pack',
    'additionalname' => 'Heavy Armor',
    'description' => 'Wrapped Pack containing all ingredients needed for crafting Seraph Breastplate.',
    'is_trade' => 1,
    'is_drop' => 1,
    'is_destruct' => 1,
    'crystal_type' => 'none',
    'consume_type' => 'consume_type_stackable',
  ],
  38025 => 
  [
    'item_id' => 38025,
    'icon' => 'event_hero_treasure_box_i00',
    'name' => 'Seraph Gaiters Crafting Pack',
    'additionalname' => 'Heavy Armor',
    'description' => 'Wrapped Pack containing all ingredients needed for crafting Seraph Gaiter.',
    'is_trade' => 1,
    'is_drop' => 1,
    'is_destruct' => 1,
    'crystal_type' => 'none',
    'consume_type' => 'consume_type_stackable',
  ],
  38026 => 
  [
    'item_id' => 38026,
    'icon' => 'event_hero_treasure_box_i00',
    'name' => 'Seraph Gauntlets Crafting Pack',
    'additionalname' => 'Heavy Armor',
    'description' => 'Wrapped Pack containing all ingredients needed for crafting Seraph Gauntlets.',
    'is_trade' => 1,
    'is_drop' => 1,
    'is_destruct' => 1,
    'crystal_type' => 'none',
    'consume_type' => 'consume_type_stackable',
  ],
  38027 => 
  [
    'item_id' => 38027,
    'icon' => 'event_hero_treasure_box_i00',
    'name' => 'Seraph Boots Crafting Pack',
    'additionalname' => 'Heavy Armor',
    'description' => 'Wrapped Pack containing all ingredients needed for crafting Seraph Boots.',
    'is_trade' => 1,
    'is_drop' => 1,
    'is_destruct' => 1,
    'crystal_type' => 'none',
    'consume_type' => 'consume_type_stackable',
  ],
  38028 => 
  [
    'item_id' => 38028,
    'icon' => 'event_hero_treasure_box_i00',
    'name' => 'Seraph Shield Crafting Pack',
    'additionalname' => 'Heavy Armor',
    'description' => 'Wrapped Pack containing all ingredients needed for crafting Seraph Shield.',
    'is_trade' => 1,
    'is_drop' => 1,
    'is_destruct' => 1,
    'crystal_type' => 'none',
    'consume_type' => 'consume_type_stackable',
  ],
  38029 => 
  [
    'item_id' => 38029,
    'icon' => 'event_hero_treasure_box_i00',
    'name' => 'Seraph Leather Helmet Crafting Pack',
    'additionalname' => 'Light Armor',
    'description' => 'Wrapped Pack containing all ingredients needed for crafting Seraph Leather Helmet.',
    'is_trade' => 1,
    'is_drop' => 1,
    'is_destruct' => 1,
    'crystal_type' => 'none',
    'consume_type' => 'consume_type_stackable',
  ],
  38030 => 
  [
    'item_id' => 38030,
    'icon' => 'event_hero_treasure_box_i00',
    'name' => 'Seraph Leather Armor Crafting Pack',
    'additionalname' => 'Light Armor',
    'description' => 'Wrapped Pack containing all ingredients needed for crafting Seraph Leather Armor.',
    'is_trade' => 1,
    'is_drop' => 1,
    'is_destruct' => 1,
    'crystal_type' => 'none',
    'consume_type' => 'consume_type_stackable',
  ],
  38031 => 
  [
    'item_id' => 38031,
    'icon' => 'event_hero_treasure_box_i00',
    'name' => 'Seraph Leather Leggings Crafting Pack',
    'additionalname' => 'Light Armor',
    'description' => 'Wrapped Pack containing all ingredients needed for crafting Seraph Leather Leggings.',
    'is_trade' => 1,
    'is_drop' => 1,
    'is_destruct' => 1,
    'crystal_type' => 'none',
    'consume_type' => 'consume_type_stackable',
  ],
  38032 => 
  [
    'item_id' => 38032,
    'icon' => 'event_hero_treasure_box_i00',
    'name' => 'Seraph Leather Gloves Crafting Pack',
    'additionalname' => 'Light Armor',
    'description' => 'Wrapped Pack containing all ingredients needed for crafting Seraph Leather Gloves.',
    'is_trade' => 1,
    'is_drop' => 1,
    'is_destruct' => 1,
    'crystal_type' => 'none',
    'consume_type' => 'consume_type_stackable',
  ],
  38033 => 
  [
    'item_id' => 38033,
    'icon' => 'event_hero_treasure_box_i00',
    'name' => 'Seraph Leather Boots Crafting Pack',
    'additionalname' => 'Light Armor',
    'description' => 'Wrapped Pack containing all ingredients needed for crafting Seraph Leather Boots.',
    'is_trade' => 1,
    'is_drop' => 1,
    'is_destruct' => 1,
    'crystal_type' => 'none',
    'consume_type' => 'consume_type_stackable',
  ],
  38034 => 
  [
    'item_id' => 38034,
    'icon' => 'event_hero_treasure_box_i00',
    'name' => 'Seraph Circlet Crafting Pack',
    'additionalname' => 'Robe',
    'description' => 'Wrapped Pack containing all ingredients needed for crafting Seraph Circlet.',
    'is_trade' => 1,
    'is_drop' => 1,
    'is_destruct' => 1,
    'crystal_type' => 'none',
    'consume_type' => 'consume_type_stackable',
  ],
  38035 => 
  [
    'item_id' => 38035,
    'icon' => 'event_hero_treasure_box_i00',
    'name' => 'Seraph Tunic Crafting Pack',
    'additionalname' => 'Robe',
    'description' => 'Wrapped Pack containing all ingredients needed for crafting Seraph Tunic.',
    'is_trade' => 1,
    'is_drop' => 1,
    'is_destruct' => 1,
    'crystal_type' => 'none',
    'consume_type' => 'consume_type_stackable',
  ],
  38036 => 
  [
    'item_id' => 38036,
    'icon' => 'event_hero_treasure_box_i00',
    'name' => 'Seraph Stockings Crafting Pack',
    'additionalname' => 'Robe',
    'description' => 'Wrapped Pack containing all ingredients needed for crafting Seraph Stockings.',
    'is_trade' => 1,
    'is_drop' => 1,
    'is_destruct' => 1,
    'crystal_type' => 'none',
    'consume_type' => 'consume_type_stackable',
  ],
  38037 => 
  [
    'item_id' => 38037,
    'icon' => 'event_hero_treasure_box_i00',
    'name' => 'Seraph Gloves Crafting Pack',
    'additionalname' => 'Robe',
    'description' => 'Wrapped Pack containing all ingredients needed for crafting Seraph Gloves.',
    'is_trade' => 1,
    'is_drop' => 1,
    'is_destruct' => 1,
    'crystal_type' => 'none',
    'consume_type' => 'consume_type_stackable',
  ],
  38038 => 
  [
    'item_id' => 38038,
    'icon' => 'event_hero_treasure_box_i00',
    'name' => 'Seraph Shoes Crafting Pack',
    'additionalname' => 'Robe',
    'description' => 'Wrapped Pack containing all ingredients needed for crafting Seraph Shoes.',
    'is_trade' => 1,
    'is_drop' => 1,
    'is_destruct' => 1,
    'crystal_type' => 'none',
    'consume_type' => 'consume_type_stackable',
  ],
  38039 => 
  [
    'item_id' => 38039,
    'icon' => 'event_hero_treasure_box_i00',
    'name' => 'Seraph Sigil Crafting Pack',
    'additionalname' => 'Robe',
    'description' => 'Wrapped Pack containing all ingredients needed for crafting Seraph Sigil.',
    'is_trade' => 1,
    'is_drop' => 1,
    'is_destruct' => 1,
    'crystal_type' => 'none',
    'consume_type' => 'consume_type_stackable',
  ],
  38040 => 
  [
    'item_id' => 38040,
    'icon' => 'event_hero_treasure_box_i00',
    'name' => 'Seraph Necklace Crafting Pack',
    'additionalname' => '',
    'description' => 'Wrapped Pack containing all ingredients needed for crafting Seraph Necklace.',
    'is_trade' => 1,
    'is_drop' => 1,
    'is_destruct' => 1,
    'crystal_type' => 'none',
    'consume_type' => 'consume_type_stackable',
  ],
  38041 => 
  [
    'item_id' => 38041,
    'icon' => 'event_hero_treasure_box_i00',
    'name' => 'Seraph Earring Crafting Pack',
    'additionalname' => '',
    'description' => 'Wrapped Pack containing all ingredients needed for crafting Seraph Earring.',
    'is_trade' => 1,
    'is_drop' => 1,
    'is_destruct' => 1,
    'crystal_type' => 'none',
    'consume_type' => 'consume_type_stackable',
  ],
  38042 => 
  [
    'item_id' => 38042,
    'icon' => 'event_hero_treasure_box_i00',
    'name' => 'Seraph Ring Crafting Pack',
    'additionalname' => '',
    'description' => 'Wrapped Pack containing all ingredients needed for crafting Seraph Ring.',
    'is_trade' => 1,
    'is_drop' => 1,
    'is_destruct' => 1,
    'crystal_type' => 'none',
    'consume_type' => 'consume_type_stackable',
  ],
  38043 => 
  [
    'item_id' => 38043,
    'icon' => 'event_hero_treasure_box_i00',
    'name' => 'Amaranthine Shaper Crafting Pack',
    'additionalname' => '',
    'description' => 'Wrapped Pack containing all ingredients needed for crafting Amaranthine Shaper.',
    'is_trade' => 1,
    'is_drop' => 1,
    'is_destruct' => 1,
    'crystal_type' => 'none',
    'consume_type' => 'consume_type_stackable',
  ],
  38044 => 
  [
    'item_id' => 38044,
    'icon' => 'event_hero_treasure_box_i00',
    'name' => 'Amaranthine Cutter Crafting Pack',
    'additionalname' => '',
    'description' => 'Wrapped Pack containing all ingredients needed for crafting Amaranthine Cutter.',
    'is_trade' => 1,
    'is_drop' => 1,
    'is_destruct' => 1,
    'crystal_type' => 'none',
    'consume_type' => 'consume_type_stackable',
  ],
  38045 => 
  [
    'item_id' => 38045,
    'icon' => 'event_hero_treasure_box_i00',
    'name' => 'Amaranthine Slasher Crafting Pack',
    'additionalname' => '',
    'description' => 'Wrapped Pack containing all ingredients needed for crafting Amaranthine Slasher.',
    'is_trade' => 1,
    'is_drop' => 1,
    'is_destruct' => 1,
    'crystal_type' => 'none',
    'consume_type' => 'consume_type_stackable',
  ],
  38046 => 
  [
    'item_id' => 38046,
    'icon' => 'event_hero_treasure_box_i00',
    'name' => 'Amaranthine Avenger Crafting Pack',
    'additionalname' => '',
    'description' => 'Wrapped Pack containing all ingredients needed for crafting Amaranthine Avenger.',
    'is_trade' => 1,
    'is_drop' => 1,
    'is_destruct' => 1,
    'crystal_type' => 'none',
    'consume_type' => 'consume_type_stackable',
  ],
  38047 => 
  [
    'item_id' => 38047,
    'icon' => 'event_hero_treasure_box_i00',
    'name' => 'Amaranthine Fighter Crafting Pack',
    'additionalname' => '',
    'description' => 'Wrapped Pack containing all ingredients needed for crafting Amaranthine Fighter.',
    'is_trade' => 1,
    'is_drop' => 1,
    'is_destruct' => 1,
    'crystal_type' => 'none',
    'consume_type' => 'consume_type_stackable',
  ],
  38048 => 
  [
    'item_id' => 38048,
    'icon' => 'event_hero_treasure_box_i00',
    'name' => 'Amaranthine Stormer Crafting Pack',
    'additionalname' => '',
    'description' => 'Wrapped Pack containing all ingredients needed for crafting Amaranthine Stormer.',
    'is_trade' => 1,
    'is_drop' => 1,
    'is_destruct' => 1,
    'crystal_type' => 'none',
    'consume_type' => 'consume_type_stackable',
  ],
  38049 => 
  [
    'item_id' => 38049,
    'icon' => 'event_hero_treasure_box_i00',
    'name' => 'Amaranthine Thrower Crafting Pack',
    'additionalname' => '',
    'description' => 'Wrapped Pack containing all ingredients needed for crafting Amaranthine Thrower.',
    'is_trade' => 1,
    'is_drop' => 1,
    'is_destruct' => 1,
    'crystal_type' => 'none',
    'consume_type' => 'consume_type_stackable',
  ],
  38050 => 
  [
    'item_id' => 38050,
    'icon' => 'event_hero_treasure_box_i00',
    'name' => 'Amaranthine Shooter Crafting Pack',
    'additionalname' => '',
    'description' => 'Wrapped Pack containing all ingredients needed for crafting Amaranthine Shooter.',
    'is_trade' => 1,
    'is_drop' => 1,
    'is_destruct' => 1,
    'crystal_type' => 'none',
    'consume_type' => 'consume_type_stackable',
  ],
  38051 => 
  [
    'item_id' => 38051,
    'icon' => 'event_hero_treasure_box_i00',
    'name' => 'Amaranthine Buster Crafting Pack',
    'additionalname' => '',
    'description' => 'Wrapped Pack containing all ingredients needed for crafting Amaranthine Buster.',
    'is_trade' => 1,
    'is_drop' => 1,
    'is_destruct' => 1,
    'crystal_type' => 'none',
    'consume_type' => 'consume_type_stackable',
  ],
  38052 => 
  [
    'item_id' => 38052,
    'icon' => 'event_hero_treasure_box_i00',
    'name' => 'Amaranthine Caster Crafting Pack',
    'additionalname' => '',
    'description' => 'Wrapped Pack containing all ingredients needed for crafting Amaranthine Caster.',
    'is_trade' => 1,
    'is_drop' => 1,
    'is_destruct' => 1,
    'crystal_type' => 'none',
    'consume_type' => 'consume_type_stackable',
  ],
  38053 => 
  [
    'item_id' => 38053,
    'icon' => 'event_hero_treasure_box_i00',
    'name' => 'Amaranthine Retributer Crafting Pack',
    'additionalname' => '',
    'description' => 'Wrapped Pack containing all ingredients needed for crafting Amaranthine Retributer.',
    'is_trade' => 1,
    'is_drop' => 1,
    'is_destruct' => 1,
    'crystal_type' => 'none',
    'consume_type' => 'consume_type_stackable',
  ],
  38054 => 
  [
    'item_id' => 38054,
    'icon' => 'event_hero_treasure_box_i00',
    'name' => 'Eternal Helmet Crafting Pack',
    'additionalname' => 'Heavy Armor',
    'description' => 'Wrapped Pack containing all ingredients needed for crafting Eternal Helmet.',
    'is_trade' => 1,
    'is_drop' => 1,
    'is_destruct' => 1,
    'crystal_type' => 'none',
    'consume_type' => 'consume_type_stackable',
  ],
  38055 => 
  [
    'item_id' => 38055,
    'icon' => 'event_hero_treasure_box_i00',
    'name' => 'Eternal Breastplate Crafting Pack',
    'additionalname' => 'Heavy Armor',
    'description' => 'Wrapped Pack containing all ingredients needed for crafting Eternal Breastplate.',
    'is_trade' => 1,
    'is_drop' => 1,
    'is_destruct' => 1,
    'crystal_type' => 'none',
    'consume_type' => 'consume_type_stackable',
  ],
  38056 => 
  [
    'item_id' => 38056,
    'icon' => 'event_hero_treasure_box_i00',
    'name' => 'Eternal Gaiters Crafting Pack',
    'additionalname' => 'Heavy Armor',
    'description' => 'Wrapped Pack containing all ingredients needed for crafting Eternal Gaiter.',
    'is_trade' => 1,
    'is_drop' => 1,
    'is_destruct' => 1,
    'crystal_type' => 'none',
    'consume_type' => 'consume_type_stackable',
  ],
  38057 => 
  [
    'item_id' => 38057,
    'icon' => 'event_hero_treasure_box_i00',
    'name' => 'Eternal Gauntlets Crafting Pack',
    'additionalname' => 'Heavy Armor',
    'description' => 'Wrapped Pack containing all ingredients needed for crafting Eternal Gauntlets.',
    'is_trade' => 1,
    'is_drop' => 1,
    'is_destruct' => 1,
    'crystal_type' => 'none',
    'consume_type' => 'consume_type_stackable',
  ],
  38058 => 
  [
    'item_id' => 38058,
    'icon' => 'event_hero_treasure_box_i00',
    'name' => 'Eternal Boots Crafting Pack',
    'additionalname' => 'Heavy Armor',
    'description' => 'Wrapped Pack containing all ingredients needed for crafting Eternal Boots.',
    'is_trade' => 1,
    'is_drop' => 1,
    'is_destruct' => 1,
    'crystal_type' => 'none',
    'consume_type' => 'consume_type_stackable',
  ],
  38059 => 
  [
    'item_id' => 38059,
    'icon' => 'event_hero_treasure_box_i00',
    'name' => 'Eternal Shield Crafting Pack',
    'additionalname' => 'Heavy Armor',
    'description' => 'Wrapped Pack containing all ingredients needed for crafting Eternal Shield.',
    'is_trade' => 1,
    'is_drop' => 1,
    'is_destruct' => 1,
    'crystal_type' => 'none',
    'consume_type' => 'consume_type_stackable',
  ],
  38060 => 
  [
    'item_id' => 38060,
    'icon' => 'event_hero_treasure_box_i00',
    'name' => 'Eternal Leather Helmet Crafting Pack',
    'additionalname' => 'Light Armor',
    'description' => 'Wrapped Pack containing all ingredients needed for crafting Eternal Leather Helmet.',
    'is_trade' => 1,
    'is_drop' => 1,
    'is_destruct' => 1,
    'crystal_type' => 'none',
    'consume_type' => 'consume_type_stackable',
  ],
  38061 => 
  [
    'item_id' => 38061,
    'icon' => 'event_hero_treasure_box_i00',
    'name' => 'Eternal Leather Armor Crafting Pack',
    'additionalname' => 'Light Armor',
    'description' => 'Wrapped Pack containing all ingredients needed for crafting Eternal Leather Armor.',
    'is_trade' => 1,
    'is_drop' => 1,
    'is_destruct' => 1,
    'crystal_type' => 'none',
    'consume_type' => 'consume_type_stackable',
  ],
  38062 => 
  [
    'item_id' => 38062,
    'icon' => 'event_hero_treasure_box_i00',
    'name' => 'Eternal Leather Leggings Crafting Pack',
    'additionalname' => 'Light Armor',
    'description' => 'Wrapped Pack containing all ingredients needed for crafting Eternal Leather Leggings.',
    'is_trade' => 1,
    'is_drop' => 1,
    'is_destruct' => 1,
    'crystal_type' => 'none',
    'consume_type' => 'consume_type_stackable',
  ],
  38063 => 
  [
    'item_id' => 38063,
    'icon' => 'event_hero_treasure_box_i00',
    'name' => 'Eternal Leather Gloves Crafting Pack',
    'additionalname' => 'Light Armor',
    'description' => 'Wrapped Pack containing all ingredients needed for crafting Eternal Leather Gloves.',
    'is_trade' => 1,
    'is_drop' => 1,
    'is_destruct' => 1,
    'crystal_type' => 'none',
    'consume_type' => 'consume_type_stackable',
  ],
  38064 => 
  [
    'item_id' => 38064,
    'icon' => 'event_hero_treasure_box_i00',
    'name' => 'Eternal Leather Boots Crafting Pack',
    'additionalname' => 'Light Armor',
    'description' => 'Wrapped Pack containing all ingredients needed for crafting Eternal Leather Boots.',
    'is_trade' => 1,
    'is_drop' => 1,
    'is_destruct' => 1,
    'crystal_type' => 'none',
    'consume_type' => 'consume_type_stackable',
  ],
  38065 => 
  [
    'item_id' => 38065,
    'icon' => 'event_hero_treasure_box_i00',
    'name' => 'Eternal Circlet Crafting Pack',
    'additionalname' => 'Robe',
    'description' => 'Wrapped Pack containing all ingredients needed for crafting Eternal Circlet.',
    'is_trade' => 1,
    'is_drop' => 1,
    'is_destruct' => 1,
    'crystal_type' => 'none',
    'consume_type' => 'consume_type_stackable',
  ],
  38066 => 
  [
    'item_id' => 38066,
    'icon' => 'event_hero_treasure_box_i00',
    'name' => 'Eternal Tunic Crafting Pack',
    'additionalname' => 'Robe',
    'description' => 'Wrapped Pack containing all ingredients needed for crafting Eternal Tunic.',
    'is_trade' => 1,
    'is_drop' => 1,
    'is_destruct' => 1,
    'crystal_type' => 'none',
    'consume_type' => 'consume_type_stackable',
  ],
  38067 => 
  [
    'item_id' => 38067,
    'icon' => 'event_hero_treasure_box_i00',
    'name' => 'Eternal Stockings Crafting Pack',
    'additionalname' => 'Robe',
    'description' => 'Wrapped Pack containing all ingredients needed for crafting Eternal Stockings.',
    'is_trade' => 1,
    'is_drop' => 1,
    'is_destruct' => 1,
    'crystal_type' => 'none',
    'consume_type' => 'consume_type_stackable',
  ],
  38068 => 
  [
    'item_id' => 38068,
    'icon' => 'event_hero_treasure_box_i00',
    'name' => 'Eternal Gloves Crafting Pack',
    'additionalname' => 'Robe',
    'description' => 'Wrapped Pack containing all ingredients needed for crafting Eternal Gloves.',
    'is_trade' => 1,
    'is_drop' => 1,
    'is_destruct' => 1,
    'crystal_type' => 'none',
    'consume_type' => 'consume_type_stackable',
  ],
  38069 => 
  [
    'item_id' => 38069,
    'icon' => 'event_hero_treasure_box_i00',
    'name' => 'Eternal Shoes Crafting Pack',
    'additionalname' => 'Robe',
    'description' => 'Wrapped Pack containing all ingredients needed for crafting Eternal Shoes.',
    'is_trade' => 1,
    'is_drop' => 1,
    'is_destruct' => 1,
    'crystal_type' => 'none',
    'consume_type' => 'consume_type_stackable',
  ],
  38070 => 
  [
    'item_id' => 38070,
    'icon' => 'event_hero_treasure_box_i00',
    'name' => 'Eternal Sigil Crafting Pack',
    'additionalname' => 'Robe',
    'description' => 'Wrapped Pack containing all ingredients needed for crafting Eternal Sigil.',
    'is_trade' => 1,
    'is_drop' => 1,
    'is_destruct' => 1,
    'crystal_type' => 'none',
    'consume_type' => 'consume_type_stackable',
  ],
  38071 => 
  [
    'item_id' => 38071,
    'icon' => 'event_hero_treasure_box_i00',
    'name' => 'Eternal Necklace Crafting Pack',
    'additionalname' => '',
    'description' => 'Wrapped Pack containing all ingredients needed for crafting Eternal Necklace.',
    'is_trade' => 1,
    'is_drop' => 1,
    'is_destruct' => 1,
    'crystal_type' => 'none',
    'consume_type' => 'consume_type_stackable',
  ],
  38072 => 
  [
    'item_id' => 38072,
    'icon' => 'event_hero_treasure_box_i00',
    'name' => 'Eternal Earring Crafting Pack',
    'additionalname' => '',
    'description' => 'Wrapped Pack containing all ingredients needed for crafting Eternal Earring.',
    'is_trade' => 1,
    'is_drop' => 1,
    'is_destruct' => 1,
    'crystal_type' => 'none',
    'consume_type' => 'consume_type_stackable',
  ],
  38073 => 
  [
    'item_id' => 38073,
    'icon' => 'event_hero_treasure_box_i00',
    'name' => 'Eternal Ring Crafting Pack',
    'additionalname' => '',
    'description' => 'Wrapped Pack containing all ingredients needed for crafting Eternal Ring.',
    'is_trade' => 1,
    'is_drop' => 1,
    'is_destruct' => 1,
    'crystal_type' => 'none',
    'consume_type' => 'consume_type_stackable',
  ],
  38074 => 
  [
    'item_id' => 38074,
    'icon' => 'card2_event_giyotine',
    'name' => 'Territory Card: Guillotine Fortress',
    'additionalname' => '',
    'description' => '',
    'is_trade' => 1,
    'is_drop' => 1,
    'is_destruct' => 1,
    'crystal_type' => 'none',
    'consume_type' => 'consume_type_stackable',
  ],
  38075 => 
  [
    'item_id' => 38075,
    'icon' => 'card2_event_heresy',
    'name' => 'Territory Card: Pagan Temple',
    'additionalname' => '',
    'description' => '',
    'is_trade' => 1,
    'is_drop' => 1,
    'is_destruct' => 1,
    'crystal_type' => 'none',
    'consume_type' => 'consume_type_stackable',
  ],
  38076 => 
  [
    'item_id' => 38076,
    'icon' => 'card2_event_predator',
    'name' => 'Territory Card: Raider\'s Crossroads',
    'additionalname' => '',
    'description' => '',
    'is_trade' => 1,
    'is_drop' => 1,
    'is_destruct' => 1,
    'crystal_type' => 'none',
    'consume_type' => 'consume_type_stackable',
  ],
  38077 => 
  [
    'item_id' => 38077,
    'icon' => 'card2_event_exile',
    'name' => 'Territory Card: Prison of Darkness',
    'additionalname' => '',
    'description' => '',
    'is_trade' => 1,
    'is_drop' => 1,
    'is_destruct' => 1,
    'crystal_type' => 'none',
    'consume_type' => 'consume_type_stackable',
  ],
  38078 => 
  [
    'item_id' => 38078,
    'icon' => 'card2_event_hellfire',
    'name' => 'Territory Card: Seed of Hellfire',
    'additionalname' => '',
    'description' => '',
    'is_trade' => 1,
    'is_drop' => 1,
    'is_destruct' => 1,
    'crystal_type' => 'none',
    'consume_type' => 'consume_type_stackable',
  ],
  38079 => 
  [
    'item_id' => 38079,
    'icon' => 'card2_event_tomb',
    'name' => 'Territory Card: Imperial Tomb',
    'additionalname' => '',
    'description' => '',
    'is_trade' => 1,
    'is_drop' => 1,
    'is_destruct' => 1,
    'crystal_type' => 'none',
    'consume_type' => 'consume_type_stackable',
  ],
  38080 => 
  [
    'item_id' => 38080,
    'icon' => 'card2_event_annihilation',
    'name' => 'Territory Card: Seed of Annihilation',
    'additionalname' => '',
    'description' => '',
    'is_trade' => 1,
    'is_drop' => 1,
    'is_destruct' => 1,
    'crystal_type' => 'none',
    'consume_type' => 'consume_type_stackable',
  ],
  38081 => 
  [
    'item_id' => 38081,
    'icon' => 'card2_event_orcbase',
    'name' => 'Territory Card: Ketra Orc Outpost',
    'additionalname' => '',
    'description' => '',
    'is_trade' => 1,
    'is_drop' => 1,
    'is_destruct' => 1,
    'crystal_type' => 'none',
    'consume_type' => 'consume_type_stackable',
  ],
  38082 => 
  [
    'item_id' => 38082,
    'icon' => 'card2_event_settlement',
    'name' => 'Territory Card: Fairy Settlement',
    'additionalname' => '',
    'description' => '',
    'is_trade' => 1,
    'is_drop' => 1,
    'is_destruct' => 1,
    'crystal_type' => 'none',
    'consume_type' => 'consume_type_stackable',
  ],
  38083 => 
  [
    'item_id' => 38083,
    'icon' => 'card2_event_spore',
    'name' => 'Territory Card: Sea of Spores',
    'additionalname' => '',
    'description' => '',
    'is_trade' => 1,
    'is_drop' => 1,
    'is_destruct' => 1,
    'crystal_type' => 'none',
    'consume_type' => 'consume_type_stackable',
  ],
  38084 => 
  [
    'item_id' => 38084,
    'icon' => 'card2_event_hellbound',
    'name' => 'Territory Card: Hellbound',
    'additionalname' => '',
    'description' => '',
    'is_trade' => 1,
    'is_drop' => 1,
    'is_destruct' => 1,
    'crystal_type' => 'none',
    'consume_type' => 'consume_type_stackable',
  ],
  38085 => 
  [
    'item_id' => 38085,
    'icon' => 'card2_event_chaos',
    'name' => 'Territory Card: Land of Chaos',
    'additionalname' => '',
    'description' => '',
    'is_trade' => 1,
    'is_drop' => 1,
    'is_destruct' => 1,
    'crystal_type' => 'none',
    'consume_type' => 'consume_type_stackable',
  ],
  38086 => 
  [
    'item_id' => 38086,
    'icon' => 'card_event_dragon_pocket',
    'name' => 'Territory Card Pouch: Demon',
    'additionalname' => '',
    'description' => 'Pouch filled with evil power. Double-click to obtain a card for either Seed of Hellfire or Prison of Darkness.',
    'is_trade' => 1,
    'is_drop' => 1,
    'is_destruct' => 1,
    'crystal_type' => 'none',
    'consume_type' => 'consume_type_stackable',
  ],
  38087 => 
  [
    'item_id' => 38087,
    'icon' => 'card_event_devil_pocket',
    'name' => 'Territory Card Pouch: Undead',
    'additionalname' => '',
    'description' => 'Pouch filled with a rotting stench. Double-click to obtain a card for either Imperial Tomb, Guillotine Fortress, or Pagan Temple.',
    'is_trade' => 1,
    'is_drop' => 1,
    'is_destruct' => 1,
    'crystal_type' => 'none',
    'consume_type' => 'consume_type_stackable',
  ],
  38088 => 
  [
    'item_id' => 38088,
    'icon' => 'card2_event_monster_pocket',
    'name' => 'Territory Card Pouch: Monster',
    'additionalname' => '',
    'description' => 'Pouch with a creepy feel. Double-click to obtain a card for either Seed of Annihilation, Sea of Spores, or Land of Chaos.',
    'is_trade' => 1,
    'is_drop' => 1,
    'is_destruct' => 1,
    'crystal_type' => 'none',
    'consume_type' => 'consume_type_stackable',
  ],
  38089 => 
  [
    'item_id' => 38089,
    'icon' => 'card2_event_orc_pocket',
    'name' => 'Territory Card Pouch: Orc',
    'additionalname' => '',
    'description' => 'Pouch with a tough and heavy feel. Double-click to obtain a card for either Ketra Orc Outpost or Raider\'s Crossroads.',
    'is_trade' => 1,
    'is_drop' => 1,
    'is_destruct' => 1,
    'crystal_type' => 'none',
    'consume_type' => 'consume_type_stackable',
  ],
  38090 => 
  [
    'item_id' => 38090,
    'icon' => 'card_event_luck_pocket',
    'name' => 'Territory Card: Lucky Pouch',
    'additionalname' => '',
    'description' => 'Test your luck! You have a chance of obtaining any Territory Card except the Fairy Settlement card. You might also fail to get any!',
    'is_trade' => 1,
    'is_drop' => 1,
    'is_destruct' => 1,
    'crystal_type' => 'none',
    'consume_type' => 'consume_type_stackable',
  ],
  38091 => 
  [
    'item_id' => 38091,
    'icon' => 'card_hero_red',
    'name' => 'Destruction\'s Shadow',
    'additionalname' => '',
    'description' => 'Card obtained from combining the Destruction\'s Shadow card. For 30 min., Attribute Atk. + 50, and Attribute Resistance + 50. ',
    'is_trade' => 1,
    'is_drop' => 1,
    'is_destruct' => 1,
    'crystal_type' => 'none',
    'consume_type' => 'consume_type_stackable',
  ],
  38092 => 
  [
    'item_id' => 38092,
    'icon' => 'card_devil_black',
    'name' => 'Evolving Darkness',
    'additionalname' => '',
    'description' => 'Card obtained from combining the Evolving Darkness card. For 30 min., Attribute Atk. + 50.',
    'is_trade' => 1,
    'is_drop' => 1,
    'is_destruct' => 1,
    'crystal_type' => 'none',
    'consume_type' => 'consume_type_stackable',
  ],
  38093 => 
  [
    'item_id' => 38093,
    'icon' => 'card_angel_blue',
    'name' => 'Sliver of Truth',
    'additionalname' => '',
    'description' => 'Card obtained from combining the Sliver of Truth card. For 30 min., Attribute Resistance + 50.',
    'is_trade' => 1,
    'is_drop' => 1,
    'is_destruct' => 1,
    'crystal_type' => 'none',
    'consume_type' => 'consume_type_stackable',
  ],
  38094 => 
  [
    'item_id' => 38094,
    'icon' => 'card_dragon_gold',
    'name' => 'Chaotic Ambush',
    'additionalname' => '',
    'description' => 'Card obtained from combining the Chaotic Ambush card. For 30 min., Attribute Atk. + 30, and Attribute Resistance + 30. ',
    'is_trade' => 1,
    'is_drop' => 1,
    'is_destruct' => 1,
    'crystal_type' => 'none',
    'consume_type' => 'consume_type_stackable',
  ],
  38095 => 
  [
    'item_id' => 38095,
    'icon' => 'etc_violet_crystal_cube_pc_i00',
    'name' => 'Leona\'s Cube',
    'additionalname' => '30-day',
    'description' => 'Double-click for a chance to obtain either Emperor\'s Rune (2-hour], Emperor\'s Vitality Tonic, Scroll: 1,000,000 SP, Scroll: 5,000,000 SP, or Scroll: 10,000,000 SP. Once a day. 30-day.',
    'is_trade' => 0,
    'is_drop' => 0,
    'is_destruct' => 1,
    'crystal_type' => 'none',
    'consume_type' => 'consume_type_normal',
  ],
  38096 => 
  [
    'item_id' => 38096,
    'icon' => 'br_cash_rune_of_feather_i00',
    'name' => 'Emperor\'s Rune',
    'additionalname' => '2-hour',
    'description' => 'While possessed, character\'s XP/SP gained + 30%. 2-hour. Only one effect applies if used with Emperor\'s Rune (8-hour].',
    'is_trade' => 0,
    'is_drop' => 0,
    'is_destruct' => 1,
    'crystal_type' => 'none',
    'consume_type' => 'consume_type_normal',
  ],
  38097 => 
  [
    'item_id' => 38097,
    'icon' => 'etc_pi_gift_box_i00',
    'name' => 'Emperor\'s Rune Pack (2-hour]',
    'additionalname' => '',
    'description' => 'Wrapped Pack containing Emperor\'s Rune (2-hour].',
    'is_trade' => 1,
    'is_drop' => 1,
    'is_destruct' => 1,
    'crystal_type' => 'none',
    'consume_type' => 'consume_type_stackable',
  ],
  38098 => 
  [
    'item_id' => 38098,
    'icon' => 'etc_pi_box_belief_pack',
    'name' => 'Leona\'s Will',
    'additionalname' => '',
    'description' => 'Wrapped Pack containing supplies sent by Leona. Double-click for a chance to obtain either Leona\'s Scroll: Buffs x 10, High-grade Lucky Enchant Stone Special Box, Blessed  Blessed Lucky Enchant Stone: Weapon (R-grade], or Blessed Lucky Enchant Stone: Armor (R-grade].',
    'is_trade' => 1,
    'is_drop' => 1,
    'is_destruct' => 1,
    'crystal_type' => 'none',
    'consume_type' => 'consume_type_stackable',
  ],
  38099 => 
  [
    'item_id' => 38099,
    'icon' => 'event_altair_enchant_scroll_i00',
    'name' => 'Leona\'s Scroll: Buffs',
    'additionalname' => '',
    'description' => 'For 30 min., XP/SP gained + 30%, Max HP/MP/CP + 30%, P. Def./ M. Def. + 30%, Speed + 20, P. Atk. + 10%, M. Atk. + 20%. Skill MP Consumption - 15%. Cannot be used with the Art of Seduction. Cooldown is 30min. Cannot be used in the Olympiad.',
    'is_trade' => 1,
    'is_drop' => 1,
    'is_destruct' => 1,
    'crystal_type' => 'none',
    'consume_type' => 'consume_type_stackable',
  ],
];