<?php return [
  38400 => 
  [
    'item_id' => 38400,
    'icon' => 'etc_equip_item_box_i00',
    'name' => 'Expertise Rune Pack',
    'additionalname' => 'C-grade',
    'description' => 'Can be exchanged for Powerful Fish through the Fishing Guild members. Double-click to obtain C-grade Expertise Rune (2-hour].',
    'is_trade' => 1,
    'is_drop' => 1,
    'is_destruct' => 1,
    'crystal_type' => 'crystal_free',
    'consume_type' => 'consume_type_stackable',
  ],
  38401 => 
  [
    'item_id' => 38401,
    'icon' => 'br_cash_rune_of_feather_i00',
    'name' => 'B-grade Expertise Rune',
    'additionalname' => '2-hour',
    'description' => '2-hour item. Gives Expertise B-grade Skill while in possession.',
    'is_trade' => 0,
    'is_drop' => 0,
    'is_destruct' => 1,
    'crystal_type' => 'crystal_free',
    'consume_type' => 'consume_type_normal',
  ],
  38402 => 
  [
    'item_id' => 38402,
    'icon' => 'etc_equip_item_box_i00',
    'name' => 'Expertise Rune Pack',
    'additionalname' => 'B-grade',
    'description' => 'Can be exchanged for Powerful Fish through the Fishing Guild members. Double-click to obtain B-grade Expertise Rune (2-hour].',
    'is_trade' => 1,
    'is_drop' => 1,
    'is_destruct' => 1,
    'crystal_type' => 'crystal_free',
    'consume_type' => 'consume_type_stackable',
  ],
  38403 => 
  [
    'item_id' => 38403,
    'icon' => 'br_cash_rune_of_feather_i00',
    'name' => 'A-grade Expertise Rune',
    'additionalname' => '2-hour',
    'description' => '2-hour item. Gives Expertise A-grade Skill while in possession.',
    'is_trade' => 0,
    'is_drop' => 0,
    'is_destruct' => 1,
    'crystal_type' => 'crystal_free',
    'consume_type' => 'consume_type_normal',
  ],
  38404 => 
  [
    'item_id' => 38404,
    'icon' => 'etc_equip_item_box_i00',
    'name' => 'Expertise Rune Pack',
    'additionalname' => 'A-grade',
    'description' => 'Can be exchanged for Powerful Fish through the Fishing Guild members. Double-click to obtain A-grade Expertise Rune (2-hour].',
    'is_trade' => 1,
    'is_drop' => 1,
    'is_destruct' => 1,
    'crystal_type' => 'crystal_free',
    'consume_type' => 'consume_type_stackable',
  ],
  38405 => 
  [
    'item_id' => 38405,
    'icon' => 'br_cash_rune_of_feather_i00',
    'name' => 'S-grade Expertise Rune',
    'additionalname' => '2-hour',
    'description' => 'Available for 2 h. Gives Expertise S-grade Skill while in possession.',
    'is_trade' => 0,
    'is_drop' => 0,
    'is_destruct' => 1,
    'crystal_type' => 'crystal_free',
    'consume_type' => 'consume_type_normal',
  ],
  38406 => 
  [
    'item_id' => 38406,
    'icon' => 'etc_equip_item_box_i00',
    'name' => 'Expertise Rune Pack',
    'additionalname' => 'S-grade',
    'description' => 'Can be exchanged for Powerful Fish through the Fishing Guild members. Double-click to obtain S-grade Expertise Rune (2-hour].',
    'is_trade' => 1,
    'is_drop' => 1,
    'is_destruct' => 1,
    'crystal_type' => 'crystal_free',
    'consume_type' => 'consume_type_stackable',
  ],
  38407 => 
  [
    'item_id' => 38407,
    'icon' => 'br_cash_rune_of_feather_i00',
    'name' => 'Expertise Rune (S80-grade]',
    'additionalname' => '2-hour',
    'description' => '2-hour item. Gives Expertise S80 Skill while in possession.',
    'is_trade' => 0,
    'is_drop' => 0,
    'is_destruct' => 1,
    'crystal_type' => 'crystal_free',
    'consume_type' => 'consume_type_normal',
  ],
  38408 => 
  [
    'item_id' => 38408,
    'icon' => 'etc_equip_item_box_i00',
    'name' => 'Expertise Rune Pack',
    'additionalname' => 'S80',
    'description' => 'Can be exchanged for Powerful Fish through the Fishing Guild members. Double-click to obtain S80-grade Expertise Rune (2-hour].',
    'is_trade' => 1,
    'is_drop' => 1,
    'is_destruct' => 1,
    'crystal_type' => 'crystal_free',
    'consume_type' => 'consume_type_stackable',
  ],
  38409 => 
  [
    'item_id' => 38409,
    'icon' => 'br_cash_rune_of_feather_i00',
    'name' => 'R-grade Expertise Rune',
    'additionalname' => '2-hour',
    'description' => '2-hour item. Gives Expertise R-grade Skill while in possession.',
    'is_trade' => 0,
    'is_drop' => 0,
    'is_destruct' => 1,
    'crystal_type' => 'crystal_free',
    'consume_type' => 'consume_type_normal',
  ],
  38410 => 
  [
    'item_id' => 38410,
    'icon' => 'etc_equip_item_box_i01',
    'name' => 'Expertise Rune Pack',
    'additionalname' => 'R',
    'description' => 'Can be exchanged for Powerful Fish through the Fishing Guild members. Double-click to obtain R-grade Expertise Rune (2-hour].',
    'is_trade' => 1,
    'is_drop' => 1,
    'is_destruct' => 1,
    'crystal_type' => 'crystal_free',
    'consume_type' => 'consume_type_stackable',
  ],
  38411 => 
  [
    'item_id' => 38411,
    'icon' => 'br_cash_rune_of_feather_i00',
    'name' => 'R95-grade Expertise Rune',
    'additionalname' => '2-hour',
    'description' => '2-hour item. Gives Expertise R95 Skill while in possession.',
    'is_trade' => 0,
    'is_drop' => 0,
    'is_destruct' => 1,
    'crystal_type' => 'crystal_free',
    'consume_type' => 'consume_type_normal',
  ],
  38412 => 
  [
    'item_id' => 38412,
    'icon' => 'etc_equip_item_box_i02',
    'name' => 'Expertise Rune Pack',
    'additionalname' => 'R95',
    'description' => 'Can be exchanged for Powerful Fish through the Fishing Guild members. Double-click to obtain R95-grade Expertise Rune (2-hour].',
    'is_trade' => 1,
    'is_drop' => 1,
    'is_destruct' => 1,
    'crystal_type' => 'crystal_free',
    'consume_type' => 'consume_type_stackable',
  ],
  38413 => 
  [
    'item_id' => 38413,
    'icon' => 'br_cash_rune_of_feather_i00',
    'name' => 'R99-grade Expertise Rune',
    'additionalname' => '2-hour',
    'description' => '2-hour item. Gives Expertise R99 Skill while in possession.',
    'is_trade' => 0,
    'is_drop' => 0,
    'is_destruct' => 1,
    'crystal_type' => 'crystal_free',
    'consume_type' => 'consume_type_normal',
  ],
  38414 => 
  [
    'item_id' => 38414,
    'icon' => 'etc_equip_item_box_i03',
    'name' => 'Expertise Rune Pack',
    'additionalname' => 'R99',
    'description' => 'Can be exchanged for Powerful Fish through the Fishing Guild members. Double-click to obtain R99-grade Expertise Rune (2-hour].',
    'is_trade' => 1,
    'is_drop' => 1,
    'is_destruct' => 1,
    'crystal_type' => 'crystal_free',
    'consume_type' => 'consume_type_stackable',
  ],
  38415 => 
  [
    'item_id' => 38415,
    'icon' => 'shape_shifting_dualblunt_i00',
    'name' => 'Appearance Stone: Blue Mackerel - Dual Blunt Weapons',
    'additionalname' => '30-day',
    'description' => 'Changes the appearance of dual blunt weapons to that of Blue Mackerel for 30 d.',
    'is_trade' => 1,
    'is_drop' => 1,
    'is_destruct' => 1,
    'crystal_type' => 'crystal_free',
    'consume_type' => 'consume_type_stackable',
  ],
  38416 => 
  [
    'item_id' => 38416,
    'icon' => 'shape_shifting_dualblunt_i00',
    'name' => 'Appearance Stone: Trumpetfish - Dual Daggers',
    'additionalname' => '30-day',
    'description' => 'Changes the appearance of dual daggers to that of Trumpetfish for 30 d.',
    'is_trade' => 1,
    'is_drop' => 1,
    'is_destruct' => 1,
    'crystal_type' => 'crystal_free',
    'consume_type' => 'consume_type_stackable',
  ],
  38417 => 
  [
    'item_id' => 38417,
    'icon' => 'shape_shifting_dualblunt_i00',
    'name' => 'Appearance Stone: Blue Mackerel - Dual Blunt Weapons',
    'additionalname' => NULL,
    'description' => 'Changes the appearance of dual blunt weapons to that of Blue Mackerel.',
    'is_trade' => 1,
    'is_drop' => 1,
    'is_destruct' => 1,
    'crystal_type' => 'crystal_free',
    'consume_type' => 'consume_type_stackable',
  ],
  38418 => 
  [
    'item_id' => 38418,
    'icon' => 'shape_shifting_dualblunt_i00',
    'name' => 'Appearance Stone: Trumpetfish - Dual Daggers',
    'additionalname' => NULL,
    'description' => 'Turns the appearance of a dual dagger into that of a Trumpetfish.',
    'is_trade' => 1,
    'is_drop' => 1,
    'is_destruct' => 1,
    'crystal_type' => 'crystal_free',
    'consume_type' => 'consume_type_stackable',
  ],
  38419 => 
  [
    'item_id' => 38419,
    'icon' => 'shape_shifting_dualblunt_i00',
    'name' => 'Appearance Stone: Blue Mackerel - One-handed Blunt Weapon',
    'additionalname' => '30-day',
    'description' => 'Changes the appearance of a one-handed blunt weapon to that of Blue Mackerel for 30 d.',
    'is_trade' => 1,
    'is_drop' => 1,
    'is_destruct' => 1,
    'crystal_type' => 'crystal_free',
    'consume_type' => 'consume_type_stackable',
  ],
  38420 => 
  [
    'item_id' => 38420,
    'icon' => 'shape_shifting_dualblunt_i00',
    'name' => 'Appearance Stone: Blue Mackerel - One-handed Blunt Weapon',
    'additionalname' => NULL,
    'description' => 'Changes the appearance of a one-handed blunt weapon to that of Blue Mackerel.',
    'is_trade' => 1,
    'is_drop' => 1,
    'is_destruct' => 1,
    'crystal_type' => 'crystal_free',
    'consume_type' => 'consume_type_stackable',
  ],
  38421 => 
  [
    'item_id' => 38421,
    'icon' => 'wp_fishing1',
    'name' => 'Blue Mackerel - One-handed Blunt Weapon',
    'additionalname' => NULL,
    'description' => 'Blue Mackerel-shaped weapon. Type: one-handed blunt weapon. An item for changing a weapons appearance.',
    'is_trade' => 1,
    'is_drop' => 0,
    'is_destruct' => 1,
    'crystal_type' => 'd',
    'consume_type' => 'consume_type_normal',
  ],
  38422 => 
  [
    'item_id' => 38422,
    'icon' => 'wp_fishing13',
    'name' => 'Trumpetfish - Dual Daggers',
    'additionalname' => NULL,
    'description' => 'Trumpetfish-shaped weapon. Dual Dagger.',
    'is_trade' => 1,
    'is_drop' => 0,
    'is_destruct' => 1,
    'crystal_type' => 'd',
    'consume_type' => 'consume_type_normal',
  ],
  38423 => 
  [
    'item_id' => 38423,
    'icon' => 'wp_fishing11',
    'name' => 'Blue Mackerel - Dual Blunt Weapons',
    'additionalname' => NULL,
    'description' => 'Blue Mackerel-shaped weapon. Type: dual blunt weapons. An item for changing a weapons appearance.',
    'is_trade' => 1,
    'is_drop' => 0,
    'is_destruct' => 1,
    'crystal_type' => 'd',
    'consume_type' => 'consume_type_normal',
  ],
  38424 => 
  [
    'item_id' => 38424,
    'icon' => 'Summon_orc_1hs_wp_i00',
    'name' => 'Monster Only: Amden Sword',
    'additionalname' => NULL,
    'description' => 'Monster weapon. One-handed Sword.',
    'is_trade' => 1,
    'is_drop' => 0,
    'is_destruct' => 1,
    'crystal_type' => 'd',
    'consume_type' => 'consume_type_normal',
  ],
  38425 => 
  [
    'item_id' => 38425,
    'icon' => 'g_beam_dualblunt',
    'name' => 'Monster Only: Amden Blunt Weapon',
    'additionalname' => NULL,
    'description' => 'Monster weapon. One-handed Sword.',
    'is_trade' => 1,
    'is_drop' => 0,
    'is_destruct' => 1,
    'crystal_type' => 'd',
    'consume_type' => 'consume_type_normal',
  ],
  38426 => 
  [
    'item_id' => 38426,
    'icon' => 'pailaka_invader_bow_wp_i00',
    'name' => 'Monster Only: Amden Bow',
    'additionalname' => NULL,
    'description' => 'Monster weapon. Bow',
    'is_trade' => 1,
    'is_drop' => 0,
    'is_destruct' => 1,
    'crystal_type' => 'd',
    'consume_type' => 'consume_type_normal',
  ],
  38427 => 
  [
    'item_id' => 38427,
    'icon' => 'Summon_orc_1hs_wp_i00',
    'name' => 'Monster Only: Centaur Weapon',
    'additionalname' => NULL,
    'description' => 'Monster weapon. One-handed Sword.',
    'is_trade' => 1,
    'is_drop' => 0,
    'is_destruct' => 1,
    'crystal_type' => 'd',
    'consume_type' => 'consume_type_normal',
  ],
  38428 => 
  [
    'item_id' => 38428,
    'icon' => 'Deathslayer_a_wp_i00',
    'name' => 'Monster Only: Minotaur Dagger',
    'additionalname' => NULL,
    'description' => 'Monster weapon. Dagger ',
    'is_trade' => 1,
    'is_drop' => 0,
    'is_destruct' => 1,
    'crystal_type' => 'd',
    'consume_type' => 'consume_type_normal',
  ],
  38429 => 
  [
    'item_id' => 38429,
    'icon' => 'Summon_orc_1hs_wp_i00',
    'name' => 'Monster Only: Tiger Sword',
    'additionalname' => NULL,
    'description' => 'Monster weapon. One-handed sword type. Base appearance of Monster Weapon Appearance Stone.',
    'is_trade' => 1,
    'is_drop' => 0,
    'is_destruct' => 1,
    'crystal_type' => 'd',
    'consume_type' => 'consume_type_normal',
  ],
  38430 => 
  [
    'item_id' => 38430,
    'icon' => 'pailaka_invader_bow_wp_i00',
    'name' => 'Monster Only: Tiger Bow',
    'additionalname' => NULL,
    'description' => 'Monster weapon. Bow ',
    'is_trade' => 1,
    'is_drop' => 0,
    'is_destruct' => 1,
    'crystal_type' => 'd',
    'consume_type' => 'consume_type_normal',
  ],
  38431 => 
  [
    'item_id' => 38431,
    'icon' => 'Deathslayer_a_wp_i00',
    'name' => 'Monster Only: Tiger Dagger',
    'additionalname' => NULL,
    'description' => 'Monster weapon. Dual dagger type. ',
    'is_trade' => 1,
    'is_drop' => 0,
    'is_destruct' => 1,
    'crystal_type' => 'd',
    'consume_type' => 'consume_type_normal',
  ],
  38432 => 
  [
    'item_id' => 38432,
    'icon' => 'Summon_orc_1hs_wp_i00',
    'name' => 'Monster Only: Tiger Jewel',
    'additionalname' => NULL,
    'description' => 'Monster weapon. One-handed Sword.',
    'is_trade' => 1,
    'is_drop' => 0,
    'is_destruct' => 1,
    'crystal_type' => 'd',
    'consume_type' => 'consume_type_normal',
  ],
  38433 => 
  [
    'item_id' => 38433,
    'icon' => 'g_beam_dualblunt',
    'name' => 'Monster Only: Tiger Blunt Weapon',
    'additionalname' => NULL,
    'description' => 'Monster weapon. One-handed Sword.',
    'is_trade' => 1,
    'is_drop' => 0,
    'is_destruct' => 1,
    'crystal_type' => 'd',
    'consume_type' => 'consume_type_normal',
  ],
  38434 => 
  [
    'item_id' => 38434,
    'icon' => 'Summon_orc_pole_wp_i00',
    'name' => 'Monster Only: Tiger Polearm',
    'additionalname' => NULL,
    'description' => 'Monster weapon. Spear.  ',
    'is_trade' => 1,
    'is_drop' => 0,
    'is_destruct' => 1,
    'crystal_type' => 'd',
    'consume_type' => 'consume_type_normal',
  ],
  38435 => 
  [
    'item_id' => 38435,
    'icon' => 'Summon_orc_shield_i00',
    'name' => 'Monster Only: Tiger Shield',
    'additionalname' => NULL,
    'description' => 'Monster weapon. Shield ',
    'is_trade' => 1,
    'is_drop' => 0,
    'is_destruct' => 1,
    'crystal_type' => 'd',
    'consume_type' => 'consume_type_normal',
  ],
  38436 => 
  [
    'item_id' => 38436,
    'icon' => 'Summon_orc_shield_i00',
    'name' => 'Monster Only: Tiger Sigil',
    'additionalname' => NULL,
    'description' => 'Monster weapon. Shield ',
    'is_trade' => 1,
    'is_drop' => 0,
    'is_destruct' => 1,
    'crystal_type' => 'd',
    'consume_type' => 'consume_type_normal',
  ],
  38437 => 
  [
    'item_id' => 38437,
    'icon' => 'Summon_orc_pole_wp_i00',
    'name' => 'Monster Only: Tiger Staff',
    'additionalname' => NULL,
    'description' => 'Monster weapon. Spear.  ',
    'is_trade' => 1,
    'is_drop' => 0,
    'is_destruct' => 1,
    'crystal_type' => 'd',
    'consume_type' => 'consume_type_normal',
  ],
  38438 => 
  [
    'item_id' => 38438,
    'icon' => 'etc_exchange_box_i00',
    'name' => 'Agathion Virgo Pack Lv. 5',
    'additionalname' => NULL,
    'description' => 'Double-click to obtain Agathion Virgo Lv. 5.',
    'is_trade' => 1,
    'is_drop' => 1,
    'is_destruct' => 1,
    'crystal_type' => 'crystal_free',
    'consume_type' => 'consume_type_stackable',
  ],
  38439 => 
  [
    'item_id' => 38439,
    'icon' => 'etc_exchange_box_i00',
    'name' => 'Agathion Virgo Pack Lv. 4',
    'additionalname' => NULL,
    'description' => 'Double-click to obtain Agathion Virgo Lv. 4.',
    'is_trade' => 1,
    'is_drop' => 1,
    'is_destruct' => 1,
    'crystal_type' => 'crystal_free',
    'consume_type' => 'consume_type_stackable',
  ],
  38440 => 
  [
    'item_id' => 38440,
    'icon' => 'etc_exchange_box_i00',
    'name' => 'Agathion Virgo Pack Lv. 3',
    'additionalname' => NULL,
    'description' => 'Double-click to obtain Agathion Virgo Lv. 3.',
    'is_trade' => 1,
    'is_drop' => 1,
    'is_destruct' => 1,
    'crystal_type' => 'crystal_free',
    'consume_type' => 'consume_type_stackable',
  ],
  38441 => 
  [
    'item_id' => 38441,
    'icon' => 'etc_exchange_box_i00',
    'name' => 'Agathion Virgo Pack Lv. 2',
    'additionalname' => NULL,
    'description' => 'Double-click to obtain Agathion Virgo Lv. 2.',
    'is_trade' => 1,
    'is_drop' => 1,
    'is_destruct' => 1,
    'crystal_type' => 'crystal_free',
    'consume_type' => 'consume_type_stackable',
  ],
  38442 => 
  [
    'item_id' => 38442,
    'icon' => 'etc_exchange_box_i00',
    'name' => 'Agathion Virgo Pack Lv. 1',
    'additionalname' => NULL,
    'description' => 'Double-click to obtain Agathion Virgo Lv. 1.',
    'is_trade' => 1,
    'is_drop' => 1,
    'is_destruct' => 1,
    'crystal_type' => 'crystal_free',
    'consume_type' => 'consume_type_stackable',
  ],
  38443 => 
  [
    'item_id' => 38443,
    'icon' => 'Summon_orc_1hs_wp_i00',
    'name' => 'Monster Only: Centaur Axe',
    'additionalname' => NULL,
    'description' => 'Monster weapon. One-handed Sword. ',
    'is_trade' => 1,
    'is_drop' => 0,
    'is_destruct' => 1,
    'crystal_type' => 'd',
    'consume_type' => 'consume_type_normal',
  ],
  38444 => 
  [
    'item_id' => 38444,
    'icon' => 'Summon_orc_shield_i00',
    'name' => 'Monster Only: Centaur Shield',
    'additionalname' => NULL,
    'description' => 'Monster weapon. Shield ',
    'is_trade' => 1,
    'is_drop' => 0,
    'is_destruct' => 1,
    'crystal_type' => 'd',
    'consume_type' => 'consume_type_normal',
  ],
  38445 => 
  [
    'item_id' => 38445,
    'icon' => 'g_beam_dualblunt',
    'name' => 'Monster Only: One-handed Blunt Weapon',
    'additionalname' => NULL,
    'description' => 'Monster weapon. One-handed Blunt weapon ',
    'is_trade' => 1,
    'is_drop' => 0,
    'is_destruct' => 1,
    'crystal_type' => 'd',
    'consume_type' => 'consume_type_normal',
  ],
  38446 => 
  [
    'item_id' => 38446,
    'icon' => 'Deathslayer_a_wp_i00',
    'name' => 'Monster Only: Centaur Throwing Blade',
    'additionalname' => NULL,
    'description' => 'Monster weapon. Dagger ',
    'is_trade' => 1,
    'is_drop' => 0,
    'is_destruct' => 1,
    'crystal_type' => 'd',
    'consume_type' => 'consume_type_normal',
  ],
  38447 => 
  [
    'item_id' => 38447,
    'icon' => 'Summon_orc_pole_wp_i00',
    'name' => 'Monster Only: Miniotaur Polearm',
    'additionalname' => NULL,
    'description' => 'Monster weapon. Spear.  ',
    'is_trade' => 1,
    'is_drop' => 0,
    'is_destruct' => 1,
    'crystal_type' => 'd',
    'consume_type' => 'consume_type_normal',
  ],
  38448 => 
  [
    'item_id' => 38448,
    'icon' => 'g_beam_dualdagger',
    'name' => 'Monster Only: Minotaur Two-handed Axe',
    'additionalname' => NULL,
    'description' => 'Monster weapon. Two-handed blunt weapon type.',
    'is_trade' => 1,
    'is_drop' => 0,
    'is_destruct' => 1,
    'crystal_type' => 'd',
    'consume_type' => 'consume_type_normal',
  ],
  38449 => 
  [
    'item_id' => 38449,
    'icon' => 'accessary_lbracelet_sign_agathion_dec_i00',
    'name' => 'Agathion Capricorn Lv. 5',
    'additionalname' => NULL,
    'description' => 'Summons Agathion Capricorn.<Active Skill>1. Agathion Teleport: Teleports you to the Town of Aden/ Town of Rune/ Town of Giran/ Heine (Cooldown: 30 min.]<Item Skill>1. Balanced Power: STR/ INT/ CON/ DEX/ WIT/ MEN/ CHA/ LUC +1.2. Attribute Enchant: Fire/ Water/ Earth/ Wind/ Dark/ Holy Atk. Rate +50 and Resistance +30.',
    'is_trade' => 1,
    'is_drop' => 1,
    'is_destruct' => 1,
    'crystal_type' => 'none',
    'consume_type' => 'consume_type_normal',
  ],
  38450 => 
  [
    'item_id' => 38450,
    'icon' => 'accessary_lbracelet_sign_agathion_dec_i00',
    'name' => 'Agathion Capricorn Lv. 4',
    'additionalname' => NULL,
    'description' => 'Summons Agathion Capricorn.<Active Skill>1. Agathion Teleport: Teleports you to the Town of Aden/ Town of Rune/ Town of Giran/ Heine (Cooldown: 30 min.]<Item Skill>1. Balanced Power: STR/ INT/ CON/ DEX/ WIT/ MEN +1.2. Enchanted Attribute Attack: Fire/ Water/ Earth/ Wind/ Dark/ Holy Atk. Rate +30.',
    'is_trade' => 1,
    'is_drop' => 1,
    'is_destruct' => 1,
    'crystal_type' => 'none',
    'consume_type' => 'consume_type_normal',
  ],
  38451 => 
  [
    'item_id' => 38451,
    'icon' => 'accessary_lbracelet_sign_agathion_dec_i00',
    'name' => 'Agathion Capricorn Lv. 3',
    'additionalname' => NULL,
    'description' => 'A bracelet for summoning Agathion Capricorn.<Active skill>1. Agathion Teleport: Teleports to Aden/ Rune/ Giran/ Heine. Cooldown: 30 min.<Item skills>1. Balanced Power: STR/ INT/ CON/ DEX/ WIT/ MEN +1.2. Attribute Resistance: Fire/ Water/ Earth/ Wind/ Dark/ Holy Resistance +30.',
    'is_trade' => 1,
    'is_drop' => 1,
    'is_destruct' => 1,
    'crystal_type' => 'none',
    'consume_type' => 'consume_type_normal',
  ],
  38452 => 
  [
    'item_id' => 38452,
    'icon' => 'accessary_lbracelet_sign_agathion_dec_i00',
    'name' => 'Agathion Capricorn Lv. 2',
    'additionalname' => NULL,
    'description' => 'Summons Agathion Capricorn.<Active Skill>1. Agathion Teleport: Teleports you to the Town of Aden/ Town of Rune/ Town of Giran/ Heine. (Cooldown: 30min.]<Item Skill>1. Balanced Power: STR/ INT/ CON/ DEX/ WIT/ MEN +1.',
    'is_trade' => 1,
    'is_drop' => 1,
    'is_destruct' => 1,
    'crystal_type' => 'none',
    'consume_type' => 'consume_type_normal',
  ],
  38453 => 
  [
    'item_id' => 38453,
    'icon' => 'accessary_lbracelet_sign_agathion_dec_i00',
    'name' => 'Agathion Capricorn Lv. 1',
    'additionalname' => NULL,
    'description' => 'Summons Agathion Capricorn.<Active skill>1. Agathion Teleport: Teleports you to the Teleports to Aden/ Rune/ Giran/ Heine (Cooldown: 30 min.].',
    'is_trade' => 1,
    'is_drop' => 1,
    'is_destruct' => 1,
    'crystal_type' => 'none',
    'consume_type' => 'consume_type_normal',
  ],
  38454 => 
  [
    'item_id' => 38454,
    'icon' => 'accessary_lbracelet_sign_agathion_sep_i00',
    'name' => 'Agathion Libra Lv. 5',
    'additionalname' => NULL,
    'description' => 'Summons Agathion Libra.<Active Skill>1. Agathion Teleport: Teleports you to the Town of Aden/ Town of Rune/ Town of Giran/ Heine (Cooldown: 30 min.]<Item Skill>1. Balanced Power: STR/ INT/ CON/ DEX/ WIT/ MEN/ CHA/ LUC +1.2. Attribute Enchant: Fire/ Water/ Earth/ Wind/ Dark/ Holy Atk. Rate +50 and Resistance +30.',
    'is_trade' => 1,
    'is_drop' => 1,
    'is_destruct' => 1,
    'crystal_type' => 'none',
    'consume_type' => 'consume_type_normal',
  ],
  38455 => 
  [
    'item_id' => 38455,
    'icon' => 'accessary_lbracelet_sign_agathion_sep_i00',
    'name' => 'Agathion Libra Lv. 4',
    'additionalname' => NULL,
    'description' => 'Summons Agathion Libra.<Active Skill>1. Agathion Teleport: Teleports you to the Town of Aden/ Town of Rune/ Town of Giran/ Heine (Cooldown: 30 min.]<Item Skill>1. Balanced Power: STR/ INT/ CON/ DEX/ WIT/ MEN +1.2. Enchanted Attribute Attack: Fire/ Water/ Earth/ Wind/ Dark/ Holy Atk. Rate +30.',
    'is_trade' => 1,
    'is_drop' => 1,
    'is_destruct' => 1,
    'crystal_type' => 'none',
    'consume_type' => 'consume_type_normal',
  ],
  38456 => 
  [
    'item_id' => 38456,
    'icon' => 'accessary_lbracelet_sign_agathion_sep_i00',
    'name' => 'Agathion Libra Lv. 3',
    'additionalname' => NULL,
    'description' => 'Summons Agathion Libra.<Active skill>1. Agathion Teleport: Teleports you to the Teleports to Aden/ Rune/ Giran/ Heine (Cooldown: 30 min.].<Item skill>1. Balanced Power: STR/ INT/ CON/ DEX/ WIT/ MEN +1.2. Attribute Resistance: Fire/ Water/ Earth/ Wind/ Dark/ Holy Resistance +30.',
    'is_trade' => 1,
    'is_drop' => 1,
    'is_destruct' => 1,
    'crystal_type' => 'none',
    'consume_type' => 'consume_type_normal',
  ],
  38457 => 
  [
    'item_id' => 38457,
    'icon' => 'accessary_lbracelet_sign_agathion_sep_i00',
    'name' => 'Agathion Libra Lv. 2',
    'additionalname' => NULL,
    'description' => 'Summons Agathion Libra.<Active Skill>1. Agathion Teleport: Teleports you to the Town of Aden/ Town of Rune/ Town of Giran/ Heine. (Cooldown: 30min.]<Item Skill>1. Balanced Power: STR/ INT/ CON/ DEX/ WIT/ MEN +1.',
    'is_trade' => 1,
    'is_drop' => 1,
    'is_destruct' => 1,
    'crystal_type' => 'none',
    'consume_type' => 'consume_type_normal',
  ],
  38458 => 
  [
    'item_id' => 38458,
    'icon' => 'accessary_lbracelet_sign_agathion_sep_i00',
    'name' => 'Agathion Libra Lv. 1',
    'additionalname' => NULL,
    'description' => 'Summons Agathion Libra.<Active Skill>1. Agathion Teleport: Teleports you to the Town of Aden/ Town of Rune/ Town of Giran/ Heine. (Cooldown is 30min.]',
    'is_trade' => 1,
    'is_drop' => 1,
    'is_destruct' => 1,
    'crystal_type' => 'none',
    'consume_type' => 'consume_type_normal',
  ],
  38459 => 
  [
    'item_id' => 38459,
    'icon' => 'accessary_lbracelet_sign_agathion_march_i00',
    'name' => 'Agathion Aries Lv. 5',
    'additionalname' => NULL,
    'description' => 'Summons Agathion Aries.<Active Skill>1. Agathion Teleport: Teleports you to the Town of Aden/ Town of Rune/ Town of Giran/ Heine (Cooldown: 30 min.]<Item Skill>1. Balanced Power: STR/ INT/ CON/ DEX/ WIT/ MEN/ CHA/ LUC +1.2. Attribute Enchant: Fire/ Water/ Earth/ Wind/ Dark/ Holy Atk. Rate +50 and Resistance +30.',
    'is_trade' => 1,
    'is_drop' => 1,
    'is_destruct' => 1,
    'crystal_type' => 'none',
    'consume_type' => 'consume_type_normal',
  ],
  38460 => 
  [
    'item_id' => 38460,
    'icon' => 'accessary_lbracelet_sign_agathion_march_i00',
    'name' => 'Agathion Aries Lv. 4',
    'additionalname' => NULL,
    'description' => 'Summons Agathion Aries.<Active Skill>1. Agathion Teleport: Teleports you to the Town of Aden/ Town of Rune/ Town of Giran/ Heine (Cooldown: 30 min.]<Item Skill>1. Balanced Power: STR/ INT/ CON/ DEX/ WIT/ MEN +1.2. Enchanted Attribute Attack: Fire/ Water/ Earth/ Wind/ Dark/ Holy Atk. Rate +30.',
    'is_trade' => 1,
    'is_drop' => 1,
    'is_destruct' => 1,
    'crystal_type' => 'none',
    'consume_type' => 'consume_type_normal',
  ],
  38461 => 
  [
    'item_id' => 38461,
    'icon' => 'accessary_lbracelet_sign_agathion_march_i00',
    'name' => 'Agathion Aries Lv. 3',
    'additionalname' => NULL,
    'description' => 'A bracelet for summoning Agathion Aries.<Active skill>1. Agathion Teleport: Teleports to Aden/ Rune/ Giran/ Heine. Cooldown: 30 min.<Item skills>1. Balanced Power: STR/ INT/ CON/ DEX/ WIT/ MEN +1.2. Attribute Resistance: Fire/ Water/ Earth/ Wind/ Dark/ Holy Resistance +30.',
    'is_trade' => 1,
    'is_drop' => 1,
    'is_destruct' => 1,
    'crystal_type' => 'none',
    'consume_type' => 'consume_type_normal',
  ],
  38462 => 
  [
    'item_id' => 38462,
    'icon' => 'accessary_lbracelet_sign_agathion_march_i00',
    'name' => 'Agathion Aries Lv. 2',
    'additionalname' => NULL,
    'description' => 'Summons Agathion Aries.<Active Skill>1. Agathion Teleport: Teleports you to the Town of Aden/ Town of Rune/ Town of Giran/ Heine. (Cooldown: 30min.]<Item Skill>1. Balanced Power: STR/ INT/ CON/ DEX/ WIT/ MEN +1.',
    'is_trade' => 1,
    'is_drop' => 1,
    'is_destruct' => 1,
    'crystal_type' => 'none',
    'consume_type' => 'consume_type_normal',
  ],
  38463 => 
  [
    'item_id' => 38463,
    'icon' => 'accessary_lbracelet_sign_agathion_march_i00',
    'name' => 'Agathion Aries Lv. 1',
    'additionalname' => NULL,
    'description' => 'Summons Agathion Aries.<Active Skill>1. Agathion Teleport: Teleports you to the Town of Aden/ Town of Rune/ Town of Giran/ Heine. (Cooldown is 30min.]',
    'is_trade' => 1,
    'is_drop' => 1,
    'is_destruct' => 1,
    'crystal_type' => 'none',
    'consume_type' => 'consume_type_normal',
  ],
  38464 => 
  [
    'item_id' => 38464,
    'icon' => 'accessary_lbracelet_sign_agathion_april_i00',
    'name' => 'Agathion Taurus Lv. 5',
    'additionalname' => NULL,
    'description' => 'Summons Agathion Taurus.<Active Skill>1. Agathion Teleport: Teleports you to the Town of Aden/ Town of Rune/ Town of Giran/ Heine (Cooldown: 30 min.]<Item Skill>1. Balanced Power: STR/ INT/ CON/ DEX/ WIT/ MEN/ CHA/ LUC +1.2. Attribute Enchant: Fire/ Water/ Earth/ Wind/ Dark/ Holy Atk. Rate +50 and Resistance +30.',
    'is_trade' => 1,
    'is_drop' => 1,
    'is_destruct' => 1,
    'crystal_type' => 'none',
    'consume_type' => 'consume_type_normal',
  ],
  38465 => 
  [
    'item_id' => 38465,
    'icon' => 'accessary_lbracelet_sign_agathion_april_i00',
    'name' => 'Agathion Taurus Lv. 4',
    'additionalname' => NULL,
    'description' => 'Summons Agathion Taurus.<Active Skill>1. Agathion Teleport: Teleports you to the Town of Aden/ Town of Rune/ Town of Giran/ Heine (Cooldown: 30 min.]<Item Skill>1. Balanced Power: STR/ INT/ CON/ DEX/ WIT/ MEN +1.2. Enchanted Attribute Attack: Fire/ Water/ Earth/ Wind/ Dark/ Holy Atk. Rate +30.',
    'is_trade' => 1,
    'is_drop' => 1,
    'is_destruct' => 1,
    'crystal_type' => 'none',
    'consume_type' => 'consume_type_normal',
  ],
  38466 => 
  [
    'item_id' => 38466,
    'icon' => 'accessary_lbracelet_sign_agathion_april_i00',
    'name' => 'Agathion Taurus Lv. 3',
    'additionalname' => NULL,
    'description' => 'A bracelet for summoning Agathion Taurus.<Active skill>1. Agathion Teleport: Teleports to Aden/ Rune/ Giran/ Heine. Cooldown: 30 min.<Item skills>1. Balanced Power: STR/ INT/ CON/ DEX/ WIT/ MEN +1.2. Attribute Resistance: Fire/ Water/ Earth/ Wind/ Dark/ Holy Resistance +30.',
    'is_trade' => 1,
    'is_drop' => 1,
    'is_destruct' => 1,
    'crystal_type' => 'none',
    'consume_type' => 'consume_type_normal',
  ],
  38467 => 
  [
    'item_id' => 38467,
    'icon' => 'accessary_lbracelet_sign_agathion_april_i00',
    'name' => 'Agathion Taurus Lv. 2',
    'additionalname' => NULL,
    'description' => 'Summons Agathion Taurus.<Active Skill>1. Agathion Teleport: Teleports you to the Town of Aden/ Town of Rune/ Town of Giran/ Heine. (Cooldown: 30min.]<Item Skill>1. Balanced Power: STR/ INT/ CON/ DEX/ WIT/ MEN +1.',
    'is_trade' => 1,
    'is_drop' => 1,
    'is_destruct' => 1,
    'crystal_type' => 'none',
    'consume_type' => 'consume_type_normal',
  ],
  38468 => 
  [
    'item_id' => 38468,
    'icon' => 'accessary_lbracelet_sign_agathion_april_i00',
    'name' => 'Agathion Taurus Lv. 1',
    'additionalname' => NULL,
    'description' => 'Summons Agathion Taurus.<Active Skill>1. Agathion Teleport: Teleports you to the Town of Aden/ Town of Rune/ Town of Giran/ Heine. (Cooldown is 30min.]',
    'is_trade' => 1,
    'is_drop' => 1,
    'is_destruct' => 1,
    'crystal_type' => 'none',
    'consume_type' => 'consume_type_normal',
  ],
  38469 => 
  [
    'item_id' => 38469,
    'icon' => 'accessary_lbracelet_sign_agathion_july_i00',
    'name' => 'Agathion Leo Lv. 5',
    'additionalname' => NULL,
    'description' => 'Summons Agathion Leo.<Active Skill>1. Agathion Teleport: Teleports you to the Town of Aden/ Town of Rune/ Town of Giran/ Heine (Cooldown: 30 min.]<Item Skill>1. Balanced Power: STR/ INT/ CON/ DEX/ WIT/ MEN/ CHA/ LUC +1.2. Attribute Enchant: Fire/ Water/ Earth/ Wind/ Dark/ Holy Atk. Rate +50 and Resistance +30.',
    'is_trade' => 1,
    'is_drop' => 1,
    'is_destruct' => 1,
    'crystal_type' => 'none',
    'consume_type' => 'consume_type_normal',
  ],
  38470 => 
  [
    'item_id' => 38470,
    'icon' => 'accessary_lbracelet_sign_agathion_july_i00',
    'name' => 'Agathion Leo Lv. 4',
    'additionalname' => NULL,
    'description' => 'Summons Agathion Leo.<Active Skill>1. Agathion Teleport: Teleports you to the Town of Aden/ Town of Rune/ Town of Giran/ Heine (Cooldown: 30 min.]<Item Skill>1. Balanced Power: STR/ INT/ CON/ DEX/ WIT/ MEN +1.2. Enchanted Attribute Attack: Fire/ Water/ Earth/ Wind/ Dark/ Holy Atk. Rate +30.',
    'is_trade' => 1,
    'is_drop' => 1,
    'is_destruct' => 1,
    'crystal_type' => 'none',
    'consume_type' => 'consume_type_normal',
  ],
  38471 => 
  [
    'item_id' => 38471,
    'icon' => 'accessary_lbracelet_sign_agathion_july_i00',
    'name' => 'Agathion Leo Lv. 3',
    'additionalname' => NULL,
    'description' => 'A bracelet for summoning Agathion Leo.<Active skill>1. Agathion Teleport: Teleports to Aden/ Rune/ Giran/ Heine. Cooldown: 30 min.<Item skills>1. Balanced Power: STR/ INT/ CON/ DEX/ WIT/ MEN +1.2. Attribute Resistance: Fire/ Water/ Earth/ Wind/ Dark/ Holy Resistance +30.',
    'is_trade' => 1,
    'is_drop' => 1,
    'is_destruct' => 1,
    'crystal_type' => 'none',
    'consume_type' => 'consume_type_normal',
  ],
  38472 => 
  [
    'item_id' => 38472,
    'icon' => 'accessary_lbracelet_sign_agathion_july_i00',
    'name' => 'Agathion Leo Lv. 2',
    'additionalname' => NULL,
    'description' => 'Summons Agathion Leo.<Active Skill>1. Agathion Teleport: Teleports you to the Town of Aden/ Town of Rune/ Town of Giran/ Heine. (Cooldown: 30min.]<Item Skill>1. Balanced Power: STR/ INT/ CON/ DEX/ WIT/ MEN +1.',
    'is_trade' => 1,
    'is_drop' => 1,
    'is_destruct' => 1,
    'crystal_type' => 'none',
    'consume_type' => 'consume_type_normal',
  ],
  38473 => 
  [
    'item_id' => 38473,
    'icon' => 'accessary_lbracelet_sign_agathion_july_i00',
    'name' => 'Agathion Leo Lv. 1',
    'additionalname' => NULL,
    'description' => 'Summons Agathion Leo.<Active Skill>1. Agathion Teleport: Teleports you to the Town of Aden/ Town of Rune/ Town of Giran/ Heine. (Cooldown is 30min.]',
    'is_trade' => 1,
    'is_drop' => 1,
    'is_destruct' => 1,
    'crystal_type' => 'none',
    'consume_type' => 'consume_type_normal',
  ],
  38474 => 
  [
    'item_id' => 38474,
    'icon' => 'accessary_lbracelet_sign_agathion_may_i00',
    'name' => 'Agathion Gemini Lv. 5',
    'additionalname' => NULL,
    'description' => 'Summons Agathion Gemini.<Active Skill>1. Agathion Teleport: Teleports you to the Town of Aden/ Town of Rune/ Town of Giran/ Heine (Cooldown: 30 min.]<Item Skill>1. Balanced Power: STR/ INT/ CON/ DEX/ WIT/ MEN/ CHA/ LUC +1.2. Attribute Enchant: Fire/ Water/ Earth/ Wind/ Dark/ Holy Atk. Rate +50 and Resistance +30.',
    'is_trade' => 1,
    'is_drop' => 1,
    'is_destruct' => 1,
    'crystal_type' => 'none',
    'consume_type' => 'consume_type_normal',
  ],
  38475 => 
  [
    'item_id' => 38475,
    'icon' => 'accessary_lbracelet_sign_agathion_may_i00',
    'name' => 'Agathion Gemini Lv. 4',
    'additionalname' => NULL,
    'description' => 'Summons Agathion Gemini.<Active Skill>1. Agathion Teleport: Teleports you to the Town of Aden/ Town of Rune/ Town of Giran/ Heine (Cooldown: 30 min.]<Item Skill>1. Balanced Power: STR/ INT/ CON/ DEX/ WIT/ MEN +1.2. Enchanted Attribute Attack: Fire/ Water/ Earth/ Wind/ Dark/ Holy Atk. Rate +30.',
    'is_trade' => 1,
    'is_drop' => 1,
    'is_destruct' => 1,
    'crystal_type' => 'none',
    'consume_type' => 'consume_type_normal',
  ],
  38476 => 
  [
    'item_id' => 38476,
    'icon' => 'accessary_lbracelet_sign_agathion_may_i00',
    'name' => 'Agathion Gemini Lv. 3',
    'additionalname' => NULL,
    'description' => 'A bracelet for summoning Agathion Gemini.<Active skill>1. Agathion Teleport: Teleports to Aden/ Rune/ Giran/ Heine. Cooldown: 30 min.<Item skills>1. Balanced Power: STR/ INT/ CON/ DEX/ WIT/ MEN +1.2. Attribute Resistance: Fire/ Water/ Earth/ Wind/ Dark/ Holy Resistance +30.',
    'is_trade' => 1,
    'is_drop' => 1,
    'is_destruct' => 1,
    'crystal_type' => 'none',
    'consume_type' => 'consume_type_normal',
  ],
  38477 => 
  [
    'item_id' => 38477,
    'icon' => 'accessary_lbracelet_sign_agathion_may_i00',
    'name' => 'Agathion Gemini Lv. 2',
    'additionalname' => NULL,
    'description' => 'Summons Agathion Gemini.<Active Skill>1. Agathion Teleport: Teleports you to the Town of Aden/ Town of Rune/ Town of Giran/ Heine. (Cooldown: 30min.]<Item Skill>1. Balanced Power: STR/ INT/ CON/ DEX/ WIT/ MEN +1.',
    'is_trade' => 1,
    'is_drop' => 1,
    'is_destruct' => 1,
    'crystal_type' => 'none',
    'consume_type' => 'consume_type_normal',
  ],
  38478 => 
  [
    'item_id' => 38478,
    'icon' => 'accessary_lbracelet_sign_agathion_may_i00',
    'name' => 'Agathion Gemini Lv. 1',
    'additionalname' => NULL,
    'description' => 'Summons Agathion Gemini.<Active Skill>1. Agathion Teleport: Teleports you to the Town of Aden/ Town of Rune/ Town of Giran/ Heine. (Cooldown is 30min.]',
    'is_trade' => 1,
    'is_drop' => 1,
    'is_destruct' => 1,
    'crystal_type' => 'none',
    'consume_type' => 'consume_type_normal',
  ],
  38479 => 
  [
    'item_id' => 38479,
    'icon' => 'accessary_lbracelet_sign_agathion_oct_i00',
    'name' => 'Agathion Scorpio Lv. 5',
    'additionalname' => NULL,
    'description' => 'Summons Agathion Scorpio.<Active Skill>1. Agathion Teleport: Teleports you to the Town of Aden/ Town of Rune/ Town of Giran/ Heine (Cooldown: 30 min.]<Item Skill>1. Balanced Power: STR/ INT/ CON/ DEX/ WIT/ MEN/ CHA/ LUC +1.2. Attribute Enchant: Fire/ Water/ Earth/ Wind/ Dark/ Holy Atk. Rate +50 and Resistance +30.',
    'is_trade' => 1,
    'is_drop' => 1,
    'is_destruct' => 1,
    'crystal_type' => 'none',
    'consume_type' => 'consume_type_normal',
  ],
  38480 => 
  [
    'item_id' => 38480,
    'icon' => 'accessary_lbracelet_sign_agathion_oct_i00',
    'name' => 'Agathion Scorpio Lv. 4',
    'additionalname' => NULL,
    'description' => 'Summons Agathion Scorpio.<Active Skill>1. Agathion Teleport: Teleports you to the Town of Aden/ Town of Rune/ Town of Giran/ Heine (Cooldown: 30 min.]<Item Skill>1. Balanced Power: STR/ INT/ CON/ DEX/ WIT/ MEN +1.2. Enchanted Attribute Attack: Fire/ Water/ Earth/ Wind/ Dark/ Holy Atk. Rate +30.',
    'is_trade' => 1,
    'is_drop' => 1,
    'is_destruct' => 1,
    'crystal_type' => 'none',
    'consume_type' => 'consume_type_normal',
  ],
  38481 => 
  [
    'item_id' => 38481,
    'icon' => 'accessary_lbracelet_sign_agathion_oct_i00',
    'name' => 'Agathion Scorpio Lv. 3',
    'additionalname' => NULL,
    'description' => 'A bracelet for summoning Agathion Scorpio.<Active skill>1. Agathion Teleport: Teleports to Aden/ Rune/ Giran/ Heine. Cooldown: 30 min.<Item skills>1. Balanced Power: STR/ INT/ CON/ DEX/ WIT/ MEN +1.2. Attribute Resistance: Fire/ Water/ Earth/ Wind/ Dark/ Holy Resistance +30.',
    'is_trade' => 1,
    'is_drop' => 1,
    'is_destruct' => 1,
    'crystal_type' => 'none',
    'consume_type' => 'consume_type_normal',
  ],
  38482 => 
  [
    'item_id' => 38482,
    'icon' => 'accessary_lbracelet_sign_agathion_oct_i00',
    'name' => 'Agathion Scorpio Lv. 2',
    'additionalname' => NULL,
    'description' => 'Summons Agathion Scorpio.<Active Skill>1. Agathion Teleport: Teleports you to the Town of Aden/ Town of Rune/ Town of Giran/ Heine. (Cooldown: 30 min.]<Item Skill>1. Balanced Power: STR/ INT/ CON/ DEX/ WIT/ MEN +1.',
    'is_trade' => 1,
    'is_drop' => 1,
    'is_destruct' => 1,
    'crystal_type' => 'none',
    'consume_type' => 'consume_type_normal',
  ],
  38483 => 
  [
    'item_id' => 38483,
    'icon' => 'accessary_lbracelet_sign_agathion_oct_i00',
    'name' => 'Agathion Scorpio Lv. 1',
    'additionalname' => NULL,
    'description' => 'Summons Agathion Scorpio.<Active Skill>1. Agathion Teleport: Teleports you to the Town of Aden/ Town of Rune/ Town of Giran/ Heine. (Cooldown is 30 min.]',
    'is_trade' => 1,
    'is_drop' => 1,
    'is_destruct' => 1,
    'crystal_type' => 'none',
    'consume_type' => 'consume_type_normal',
  ],
  38484 => 
  [
    'item_id' => 38484,
    'icon' => 'accessary_lbracelet_sign_agathion_jan_i00',
    'name' => 'Agathion Aquarius Lv. 5',
    'additionalname' => NULL,
    'description' => 'Summons Agathion Aquarius.<Active Skill>1. Agathion Teleport: Teleports you to the Town of Aden/ Town of Rune/ Town of Giran/ Heine (Cooldown: 30 min.]<Item Skill>1. Balanced Power: STR/ INT/ CON/ DEX/ WIT/ MEN/ CHA/ LUC +1.2. Attribute Enchant: Fire/ Water/ Earth/ Wind/ Dark/ Holy Atk. Rate +50 and Resistance +30.',
    'is_trade' => 1,
    'is_drop' => 1,
    'is_destruct' => 1,
    'crystal_type' => 'none',
    'consume_type' => 'consume_type_normal',
  ],
  38485 => 
  [
    'item_id' => 38485,
    'icon' => 'accessary_lbracelet_sign_agathion_jan_i00',
    'name' => 'Agathion Aquarius Lv. 4',
    'additionalname' => NULL,
    'description' => 'Summons Agathion Aquarius.<Active Skill>1. Agathion Teleport: Teleports you to the Town of Aden/ Town of Rune/ Town of Giran/ Heine (Cooldown: 30 min.]<Item Skill>1. Balanced Power: STR/ INT/ CON/ DEX/ WIT/ MEN +1.2. Enchanted Attribute Attack: Fire/ Water/ Earth/ Wind/ Dark/ Holy Atk. Rate +30.',
    'is_trade' => 1,
    'is_drop' => 1,
    'is_destruct' => 1,
    'crystal_type' => 'none',
    'consume_type' => 'consume_type_normal',
  ],
  38486 => 
  [
    'item_id' => 38486,
    'icon' => 'accessary_lbracelet_sign_agathion_jan_i00',
    'name' => 'Agathion Aquarius Lv. 3',
    'additionalname' => NULL,
    'description' => 'A bracelet for summoning Agathion Aquarius.<Active skill>1. Agathion Teleport: Teleports to Aden/ Rune/ Giran/ Heine. Cooldown: 30 min.<Item skills>1. Balanced Power: STR/ INT/ CON/ DEX/ WIT/ MEN +1.2. Attribute Resistance: Fire/ Water/ Earth/ Wind/ Dark/ Holy Resistance +30.',
    'is_trade' => 1,
    'is_drop' => 1,
    'is_destruct' => 1,
    'crystal_type' => 'none',
    'consume_type' => 'consume_type_normal',
  ],
  38487 => 
  [
    'item_id' => 38487,
    'icon' => 'accessary_lbracelet_sign_agathion_jan_i00',
    'name' => 'Agathion Aquarius Lv. 2',
    'additionalname' => NULL,
    'description' => 'Summons Agathion Aquarius.<Active Skill>1. Agathion Teleport: Teleports you to the Town of Aden/ Town of Rune/ Town of Giran/ Heine. (Cooldown: 30min.]<Item Skill>1. Balanced Power: STR/ INT/ CON/ DEX/ WIT/ MEN +1.',
    'is_trade' => 1,
    'is_drop' => 1,
    'is_destruct' => 1,
    'crystal_type' => 'none',
    'consume_type' => 'consume_type_normal',
  ],
  38488 => 
  [
    'item_id' => 38488,
    'icon' => 'accessary_lbracelet_sign_agathion_jan_i00',
    'name' => 'Agathion Aquarius Lv. 1',
    'additionalname' => NULL,
    'description' => 'Summons Agathion Aquarius.<Active skill>1. Agathion Teleport: Teleports you to the Teleports to Aden/ Rune/ Giran/ Heine (Cooldown: 30 min.].',
    'is_trade' => 1,
    'is_drop' => 1,
    'is_destruct' => 1,
    'crystal_type' => 'none',
    'consume_type' => 'consume_type_normal',
  ],
  38489 => 
  [
    'item_id' => 38489,
    'icon' => 'accessary_lbracelet_sign_agathion_feb_i00',
    'name' => 'Agathion Pisces Lv. 5',
    'additionalname' => NULL,
    'description' => 'Summons Agathion Pisces.<Active Skill>1. Agathion Teleport: Teleports you to the Town of Aden/ Town of Rune/ Town of Giran/ Heine (Cooldown: 30 min.]<Item Skill>1. Balanced Power: STR/ INT/ CON/ DEX/ WIT/ MEN/ CHA/ LUC +1.2. Attribute Enchant: Fire/ Water/ Earth/ Wind/ Dark/ Holy Atk. Rate +50 and Resistance +30.',
    'is_trade' => 1,
    'is_drop' => 1,
    'is_destruct' => 1,
    'crystal_type' => 'none',
    'consume_type' => 'consume_type_normal',
  ],
  38490 => 
  [
    'item_id' => 38490,
    'icon' => 'accessary_lbracelet_sign_agathion_feb_i00',
    'name' => 'Agathion Pisces Lv. 4',
    'additionalname' => NULL,
    'description' => 'Summons Agathion Pisces.<Active Skill>1. Agathion Teleport: Teleports you to the Town of Aden/ Town of Rune/ Town of Giran/ Heine (Cooldown: 30 min.]<Item Skill>1. Balanced Power: STR/ INT/ CON/ DEX/ WIT/ MEN +1.2. Enchanted Attribute Attack: Fire/ Water/ Earth/ Wind/ Dark/ Holy Atk. Rate +30.',
    'is_trade' => 1,
    'is_drop' => 1,
    'is_destruct' => 1,
    'crystal_type' => 'none',
    'consume_type' => 'consume_type_normal',
  ],
  38491 => 
  [
    'item_id' => 38491,
    'icon' => 'accessary_lbracelet_sign_agathion_feb_i00',
    'name' => 'Agathion Pisces Lv. 3',
    'additionalname' => NULL,
    'description' => 'A bracelet for summoning Agathion Pisces.<Active skill>1. Agathion Teleport: Teleports to Aden/ Rune/ Giran/ Heine. Cooldown: 30 min.<Item skills>1. Balanced Power: STR/ INT/ CON/ DEX/ WIT/ MEN +1.2. Attribute Resistance: Fire/ Water/ Earth/ Wind/ Dark/ Holy Resistance +30.',
    'is_trade' => 1,
    'is_drop' => 1,
    'is_destruct' => 1,
    'crystal_type' => 'none',
    'consume_type' => 'consume_type_normal',
  ],
  38492 => 
  [
    'item_id' => 38492,
    'icon' => 'accessary_lbracelet_sign_agathion_feb_i00',
    'name' => 'Agathion Pisces Lv. 2',
    'additionalname' => NULL,
    'description' => 'Summons Agathion Pisces.<Active Skill>1. Agathion Teleport: Teleports you to the Town of Aden/ Town of Rune/ Town of Giran/ Heine. (Cooldown: 30min.]<Item Skill>1. Balanced Power: STR/ INT/ CON/ DEX/ WIT/ MEN +1.',
    'is_trade' => 1,
    'is_drop' => 1,
    'is_destruct' => 1,
    'crystal_type' => 'none',
    'consume_type' => 'consume_type_normal',
  ],
  38493 => 
  [
    'item_id' => 38493,
    'icon' => 'accessary_lbracelet_sign_agathion_feb_i00',
    'name' => 'Agathion Pisces Lv. 1',
    'additionalname' => NULL,
    'description' => 'Summons Agathion Pisces.<Active Skill>1. Agathion Teleport: Teleports you to the Town of Aden/ Town of Rune/ Town of Giran/ Heine. (Cooldown is 30min.]',
    'is_trade' => 1,
    'is_drop' => 1,
    'is_destruct' => 1,
    'crystal_type' => 'none',
    'consume_type' => 'consume_type_normal',
  ],
  38494 => 
  [
    'item_id' => 38494,
    'icon' => 'accessary_lbracelet_sign_agathion_nov_i00',
    'name' => 'Agathion Sagittarius Lv. 5',
    'additionalname' => NULL,
    'description' => 'Summons Agathion Sagittarius.<Active Skill>1. Agathion Teleport: Teleports you to the Town of Aden/ Town of Rune/ Town of Giran/ Heine (Cooldown: 30 min.]<Item Skill>1. Balanced Power: STR/ INT/ CON/ DEX/ WIT/ MEN/ CHA/ LUC +1.2. Attribute Enchant: Fire/ Water/ Earth/ Wind/ Dark/ Holy Atk. Rate +50 and Resistance +30.',
    'is_trade' => 1,
    'is_drop' => 1,
    'is_destruct' => 1,
    'crystal_type' => 'none',
    'consume_type' => 'consume_type_normal',
  ],
  38495 => 
  [
    'item_id' => 38495,
    'icon' => 'accessary_lbracelet_sign_agathion_nov_i00',
    'name' => 'Agathion Sagittarius Lv. 4',
    'additionalname' => NULL,
    'description' => 'Summons Agathion Sagittarius.<Active Skill>1. Agathion Teleport: Teleports you to the Town of Aden/ Town of Rune/ Town of Giran/ Heine (Cooldown: 30 min.]<Item Skill>1. Balanced Power: STR/ INT/ CON/ DEX/ WIT/ MEN +1.2. Enchanted Attribute Attack: Fire/ Water/ Earth/ Wind/ Dark/ Holy Atk. Rate +30.',
    'is_trade' => 1,
    'is_drop' => 1,
    'is_destruct' => 1,
    'crystal_type' => 'none',
    'consume_type' => 'consume_type_normal',
  ],
  38496 => 
  [
    'item_id' => 38496,
    'icon' => 'accessary_lbracelet_sign_agathion_nov_i00',
    'name' => 'Agathion Sagittarius Lv. 3',
    'additionalname' => NULL,
    'description' => 'A bracelet for summoning Agathion Sagittarius.<Active skill>1. Agathion Teleport: Teleports to Aden/ Rune/ Giran/ Heine. Cooldown: 30 min.<Item skills>1. Balanced Power: STR/ INT/ CON/ DEX/ WIT/ MEN +1.2. Attribute Resistance: Fire/ Water/ Earth/ Wind/ Dark/ Holy Resistance +30.',
    'is_trade' => 1,
    'is_drop' => 1,
    'is_destruct' => 1,
    'crystal_type' => 'none',
    'consume_type' => 'consume_type_normal',
  ],
  38497 => 
  [
    'item_id' => 38497,
    'icon' => 'accessary_lbracelet_sign_agathion_nov_i00',
    'name' => 'Agathion Sagittarius Lv. 2',
    'additionalname' => NULL,
    'description' => 'Summons Agathion Sagittarius.<Active Skill>1. Agathion Teleport: Teleports you to the Town of Aden/ Town of Rune/ Town of Giran/ Heine. (Cooldown: 30min.]<Item Skill>1. Balanced Power: STR/ INT/ CON/ DEX/ WIT/ MEN +1.',
    'is_trade' => 1,
    'is_drop' => 1,
    'is_destruct' => 1,
    'crystal_type' => 'none',
    'consume_type' => 'consume_type_normal',
  ],
  38498 => 
  [
    'item_id' => 38498,
    'icon' => 'accessary_lbracelet_sign_agathion_nov_i00',
    'name' => 'Agathion Sagittarius Lv. 1',
    'additionalname' => NULL,
    'description' => 'Summons Agathion Sagittarius.<Active Skill>1. Agathion Teleport: Teleports you to the Town of Aden/ Town of Rune/ Town of Giran/ Heine. (Cooldown is 30min.]',
    'is_trade' => 1,
    'is_drop' => 1,
    'is_destruct' => 1,
    'crystal_type' => 'none',
    'consume_type' => 'consume_type_normal',
  ],
  38499 => 
  [
    'item_id' => 38499,
    'icon' => 'accessary_lbracelet_sign_agathion_june_i00',
    'name' => 'Agathion Cancer Lv. 5',
    'additionalname' => NULL,
    'description' => 'Summons Agathion Cancer.<Active Skill>1. Agathion Teleport: Teleports you to the Town of Aden/ Town of Rune/ Town of Giran/ Heine (Cooldown: 30 min.]<Item Skill>1. Balanced Power: STR/ INT/ CON/ DEX/ WIT/ MEN/ CHA/ LUC +1.2. Attribute Enchant: Fire/ Water/ Earth/ Wind/ Dark/ Holy Atk. Rate +50 and Resistance +30.',
    'is_trade' => 1,
    'is_drop' => 1,
    'is_destruct' => 1,
    'crystal_type' => 'none',
    'consume_type' => 'consume_type_normal',
  ],
];