<?php return [
  39900 => 
  [
    'item_id' => 39900,
    'icon' => 'dimension_bracelet_i03',
    'name' => 'Dimensional Bracelet Lv. 4',
    'additionalname' => 'WIT',
    'description' => 'When equipped, unlocks 4 talisman slots. Increases WIT.',
    'is_trade' => 0,
    'is_drop' => 0,
    'is_destruct' => 1,
    'crystal_type' => 'r',
    'consume_type' => 'consume_type_normal',
  ],
  39901 => 
  [
    'item_id' => 39901,
    'icon' => 'dimension_bracelet_i03',
    'name' => 'Dimensional Bracelet Lv. 4',
    'additionalname' => 'LUC',
    'description' => 'When equipped, unlocks 4 talisman slots. Increases LUC.',
    'is_trade' => 0,
    'is_drop' => 0,
    'is_destruct' => 1,
    'crystal_type' => 'r',
    'consume_type' => 'consume_type_normal',
  ],
  39902 => 
  [
    'item_id' => 39902,
    'icon' => 'dimension_bracelet_i03',
    'name' => 'Dimensional Bracelet Lv. 4',
    'additionalname' => 'CHA',
    'description' => 'When equipped, unlocks 4 talisman slots. Increases CHA.',
    'is_trade' => 0,
    'is_drop' => 0,
    'is_destruct' => 1,
    'crystal_type' => 'r',
    'consume_type' => 'consume_type_normal',
  ],
  39903 => 
  [
    'item_id' => 39903,
    'icon' => 'dimension_bracelet_i03',
    'name' => 'Dimensional Bracelet Lv. 4',
    'additionalname' => 'STR +1',
    'description' => 'When equipped, unlocks 4 talisman slots. STR +1.',
    'is_trade' => 0,
    'is_drop' => 0,
    'is_destruct' => 1,
    'crystal_type' => 'r',
    'consume_type' => 'consume_type_normal',
  ],
  39904 => 
  [
    'item_id' => 39904,
    'icon' => 'dimension_bracelet_i03',
    'name' => 'Dimensional Bracelet Lv. 4',
    'additionalname' => 'STR+2',
    'description' => 'When equipped, unlocks 4 talisman slots. STR +2.',
    'is_trade' => 0,
    'is_drop' => 0,
    'is_destruct' => 1,
    'crystal_type' => 'r',
    'consume_type' => 'consume_type_normal',
  ],
  39905 => 
  [
    'item_id' => 39905,
    'icon' => 'dimension_bracelet_i03',
    'name' => 'Dimensional Bracelet Lv. 4',
    'additionalname' => 'STR+3',
    'description' => 'When equipped, unlocks 4 talisman slots. STR +3.',
    'is_trade' => 0,
    'is_drop' => 0,
    'is_destruct' => 1,
    'crystal_type' => 'r',
    'consume_type' => 'consume_type_normal',
  ],
  39906 => 
  [
    'item_id' => 39906,
    'icon' => 'dimension_bracelet_i03',
    'name' => 'Dimensional Bracelet Lv. 4',
    'additionalname' => 'STR+4',
    'description' => 'When equipped, unlocks 4 talisman slots. STR +4.',
    'is_trade' => 0,
    'is_drop' => 0,
    'is_destruct' => 1,
    'crystal_type' => 'r',
    'consume_type' => 'consume_type_normal',
  ],
  39907 => 
  [
    'item_id' => 39907,
    'icon' => 'dimension_bracelet_i03',
    'name' => 'Dimensional Bracelet Lv. 4',
    'additionalname' => 'STR +5',
    'description' => 'When equipped, unlocks 4 talisman slots. STR +5.',
    'is_trade' => 0,
    'is_drop' => 0,
    'is_destruct' => 1,
    'crystal_type' => 'r',
    'consume_type' => 'consume_type_normal',
  ],
  39908 => 
  [
    'item_id' => 39908,
    'icon' => 'dimension_bracelet_i03',
    'name' => 'Dimensional Bracelet Lv. 4',
    'additionalname' => 'DEX +1',
    'description' => 'When equipped, unlocks 4 talisman slots. DEX +1.',
    'is_trade' => 0,
    'is_drop' => 0,
    'is_destruct' => 1,
    'crystal_type' => 'r',
    'consume_type' => 'consume_type_normal',
  ],
  39909 => 
  [
    'item_id' => 39909,
    'icon' => 'dimension_bracelet_i03',
    'name' => 'Dimensional Bracelet Lv. 4',
    'additionalname' => 'DEX+2',
    'description' => 'When equipped, unlocks 4 talisman slots. DEX +2.',
    'is_trade' => 0,
    'is_drop' => 0,
    'is_destruct' => 1,
    'crystal_type' => 'r',
    'consume_type' => 'consume_type_normal',
  ],
  39910 => 
  [
    'item_id' => 39910,
    'icon' => 'dimension_bracelet_i03',
    'name' => 'Dimensional Bracelet Lv. 4',
    'additionalname' => 'DEX+3',
    'description' => 'When equipped, unlocks 4 talisman slots. DEX +3.',
    'is_trade' => 0,
    'is_drop' => 0,
    'is_destruct' => 1,
    'crystal_type' => 'r',
    'consume_type' => 'consume_type_normal',
  ],
  39911 => 
  [
    'item_id' => 39911,
    'icon' => 'dimension_bracelet_i03',
    'name' => 'Dimensional Bracelet Lv. 4',
    'additionalname' => 'DEX+4',
    'description' => 'When equipped, unlocks 4 talisman slots. DEX +4.',
    'is_trade' => 0,
    'is_drop' => 0,
    'is_destruct' => 1,
    'crystal_type' => 'r',
    'consume_type' => 'consume_type_normal',
  ],
  39912 => 
  [
    'item_id' => 39912,
    'icon' => 'dimension_bracelet_i03',
    'name' => 'Dimensional Bracelet Lv. 4',
    'additionalname' => 'DEX +5',
    'description' => 'When equipped, unlocks 4 talisman slots. DEX +5.',
    'is_trade' => 0,
    'is_drop' => 0,
    'is_destruct' => 1,
    'crystal_type' => 'r',
    'consume_type' => 'consume_type_normal',
  ],
  39913 => 
  [
    'item_id' => 39913,
    'icon' => 'dimension_bracelet_i03',
    'name' => 'Dimensional Bracelet Lv. 4',
    'additionalname' => 'CON +1',
    'description' => 'When equipped, unlocks 4 talisman slots. CON +1.',
    'is_trade' => 0,
    'is_drop' => 0,
    'is_destruct' => 1,
    'crystal_type' => 'r',
    'consume_type' => 'consume_type_normal',
  ],
  39914 => 
  [
    'item_id' => 39914,
    'icon' => 'dimension_bracelet_i03',
    'name' => 'Dimensional Bracelet Lv. 4',
    'additionalname' => 'CON +2',
    'description' => 'When equipped, unlocks 4 talisman slots. CON +2.',
    'is_trade' => 0,
    'is_drop' => 0,
    'is_destruct' => 1,
    'crystal_type' => 'r',
    'consume_type' => 'consume_type_normal',
  ],
  39915 => 
  [
    'item_id' => 39915,
    'icon' => 'dimension_bracelet_i03',
    'name' => 'Dimensional Bracelet Lv. 4',
    'additionalname' => 'CON +3',
    'description' => 'When equipped, unlocks 4 talisman slots. CON +3.',
    'is_trade' => 0,
    'is_drop' => 0,
    'is_destruct' => 1,
    'crystal_type' => 'r',
    'consume_type' => 'consume_type_normal',
  ],
  39916 => 
  [
    'item_id' => 39916,
    'icon' => 'dimension_bracelet_i03',
    'name' => 'Dimensional Bracelet Lv. 4',
    'additionalname' => 'CON+4',
    'description' => 'When equipped, unlocks 4 talisman slots. CON +4.',
    'is_trade' => 0,
    'is_drop' => 0,
    'is_destruct' => 1,
    'crystal_type' => 'r',
    'consume_type' => 'consume_type_normal',
  ],
  39917 => 
  [
    'item_id' => 39917,
    'icon' => 'dimension_bracelet_i03',
    'name' => 'Dimensional Bracelet Lv. 4',
    'additionalname' => 'CON +5',
    'description' => 'When equipped, unlocks 4 talisman slots. CON +5.',
    'is_trade' => 0,
    'is_drop' => 0,
    'is_destruct' => 1,
    'crystal_type' => 'r',
    'consume_type' => 'consume_type_normal',
  ],
  39918 => 
  [
    'item_id' => 39918,
    'icon' => 'dimension_bracelet_i03',
    'name' => 'Dimensional Bracelet Lv. 4',
    'additionalname' => 'INT +1',
    'description' => 'When equipped, unlocks 4 talisman slots. INT +1.',
    'is_trade' => 0,
    'is_drop' => 0,
    'is_destruct' => 1,
    'crystal_type' => 'r',
    'consume_type' => 'consume_type_normal',
  ],
  39919 => 
  [
    'item_id' => 39919,
    'icon' => 'dimension_bracelet_i03',
    'name' => 'Dimensional Bracelet Lv. 4',
    'additionalname' => 'INT+2',
    'description' => 'When equipped, unlocks 4 talisman slots. INT +2.',
    'is_trade' => 0,
    'is_drop' => 0,
    'is_destruct' => 1,
    'crystal_type' => 'r',
    'consume_type' => 'consume_type_normal',
  ],
  39920 => 
  [
    'item_id' => 39920,
    'icon' => 'dimension_bracelet_i03',
    'name' => 'Dimensional Bracelet Lv. 4',
    'additionalname' => 'INT+3',
    'description' => 'When equipped, unlocks 4 talisman slots. INT +3.',
    'is_trade' => 0,
    'is_drop' => 0,
    'is_destruct' => 1,
    'crystal_type' => 'r',
    'consume_type' => 'consume_type_normal',
  ],
  39921 => 
  [
    'item_id' => 39921,
    'icon' => 'dimension_bracelet_i03',
    'name' => 'Dimensional Bracelet Lv. 4',
    'additionalname' => 'INT+4',
    'description' => 'When equipped, unlocks 4 talisman slots. INT +4.',
    'is_trade' => 0,
    'is_drop' => 0,
    'is_destruct' => 1,
    'crystal_type' => 'r',
    'consume_type' => 'consume_type_normal',
  ],
  39922 => 
  [
    'item_id' => 39922,
    'icon' => 'dimension_bracelet_i03',
    'name' => 'Dimensional Bracelet Lv. 4',
    'additionalname' => 'INT +5',
    'description' => 'When equipped, unlocks 4 talisman slots. INT +5.',
    'is_trade' => 0,
    'is_drop' => 0,
    'is_destruct' => 1,
    'crystal_type' => 'r',
    'consume_type' => 'consume_type_normal',
  ],
  39923 => 
  [
    'item_id' => 39923,
    'icon' => 'dimension_bracelet_i03',
    'name' => 'Dimensional Bracelet Lv. 4',
    'additionalname' => 'MEN +1',
    'description' => 'When equipped, unlocks 4 talisman slots. MEN +1.',
    'is_trade' => 0,
    'is_drop' => 0,
    'is_destruct' => 1,
    'crystal_type' => 'r',
    'consume_type' => 'consume_type_normal',
  ],
  39924 => 
  [
    'item_id' => 39924,
    'icon' => 'dimension_bracelet_i03',
    'name' => 'Dimensional Bracelet Lv. 4',
    'additionalname' => 'MEN +2',
    'description' => 'When equipped, unlocks 4 talisman slots. MEN +2.',
    'is_trade' => 0,
    'is_drop' => 0,
    'is_destruct' => 1,
    'crystal_type' => 'r',
    'consume_type' => 'consume_type_normal',
  ],
  39925 => 
  [
    'item_id' => 39925,
    'icon' => 'dimension_bracelet_i03',
    'name' => 'Dimensional Bracelet Lv. 4',
    'additionalname' => 'MEN +3',
    'description' => 'When equipped, unlocks 4 talisman slots. MEN +3.',
    'is_trade' => 0,
    'is_drop' => 0,
    'is_destruct' => 1,
    'crystal_type' => 'r',
    'consume_type' => 'consume_type_normal',
  ],
  39926 => 
  [
    'item_id' => 39926,
    'icon' => 'dimension_bracelet_i03',
    'name' => 'Dimensional Bracelet Lv. 4',
    'additionalname' => 'MEN+4',
    'description' => 'When equipped, unlocks 4 talisman slots. MEN +4.',
    'is_trade' => 0,
    'is_drop' => 0,
    'is_destruct' => 1,
    'crystal_type' => 'r',
    'consume_type' => 'consume_type_normal',
  ],
  39927 => 
  [
    'item_id' => 39927,
    'icon' => 'dimension_bracelet_i03',
    'name' => 'Dimensional Bracelet Lv. 4',
    'additionalname' => 'MEN +5',
    'description' => 'When equipped, unlocks 4 talisman slots. MEN +5.',
    'is_trade' => 0,
    'is_drop' => 0,
    'is_destruct' => 1,
    'crystal_type' => 'r',
    'consume_type' => 'consume_type_normal',
  ],
  39928 => 
  [
    'item_id' => 39928,
    'icon' => 'dimension_bracelet_i03',
    'name' => 'Dimensional Bracelet Lv. 4',
    'additionalname' => 'WIT +1',
    'description' => 'When equipped, unlocks 4 talisman slots. WIT +1.',
    'is_trade' => 0,
    'is_drop' => 0,
    'is_destruct' => 1,
    'crystal_type' => 'r',
    'consume_type' => 'consume_type_normal',
  ],
  39929 => 
  [
    'item_id' => 39929,
    'icon' => 'dimension_bracelet_i03',
    'name' => 'Dimensional Bracelet Lv. 4',
    'additionalname' => 'WIT+2',
    'description' => 'When equipped, unlocks 4 talisman slots. WIT +2.',
    'is_trade' => 0,
    'is_drop' => 0,
    'is_destruct' => 1,
    'crystal_type' => 'r',
    'consume_type' => 'consume_type_normal',
  ],
  39930 => 
  [
    'item_id' => 39930,
    'icon' => 'dimension_bracelet_i03',
    'name' => 'Dimensional Bracelet Lv. 4',
    'additionalname' => 'WIT+3',
    'description' => 'When equipped, unlocks 4 talisman slots. WIT +3.',
    'is_trade' => 0,
    'is_drop' => 0,
    'is_destruct' => 1,
    'crystal_type' => 'r',
    'consume_type' => 'consume_type_normal',
  ],
  39931 => 
  [
    'item_id' => 39931,
    'icon' => 'dimension_bracelet_i03',
    'name' => 'Dimensional Bracelet Lv. 4',
    'additionalname' => 'WIT+4',
    'description' => 'When equipped, unlocks 4 talisman slots. WIT +4.',
    'is_trade' => 0,
    'is_drop' => 0,
    'is_destruct' => 1,
    'crystal_type' => 'r',
    'consume_type' => 'consume_type_normal',
  ],
  39932 => 
  [
    'item_id' => 39932,
    'icon' => 'dimension_bracelet_i03',
    'name' => 'Dimensional Bracelet Lv. 4',
    'additionalname' => 'WIT +5',
    'description' => 'When equipped, unlocks 4 talisman slots. WIT +5.',
    'is_trade' => 0,
    'is_drop' => 0,
    'is_destruct' => 1,
    'crystal_type' => 'r',
    'consume_type' => 'consume_type_normal',
  ],
  39933 => 
  [
    'item_id' => 39933,
    'icon' => 'dimension_bracelet_i03',
    'name' => 'Dimensional Bracelet Lv. 4',
    'additionalname' => 'LUC +1',
    'description' => 'When equipped, unlocks 4 talisman slots. LUC +1.',
    'is_trade' => 0,
    'is_drop' => 0,
    'is_destruct' => 1,
    'crystal_type' => 'r',
    'consume_type' => 'consume_type_normal',
  ],
  39934 => 
  [
    'item_id' => 39934,
    'icon' => 'dimension_bracelet_i03',
    'name' => 'Dimensional Bracelet Lv. 4',
    'additionalname' => 'LUC +2',
    'description' => 'When equipped, unlocks 4 talisman slots. LUC +2.',
    'is_trade' => 0,
    'is_drop' => 0,
    'is_destruct' => 1,
    'crystal_type' => 'r',
    'consume_type' => 'consume_type_normal',
  ],
  39935 => 
  [
    'item_id' => 39935,
    'icon' => 'dimension_bracelet_i03',
    'name' => 'Dimensional Bracelet Lv. 4',
    'additionalname' => 'LUC +3',
    'description' => 'When equipped, unlocks 4 talisman slots. LUC +3.',
    'is_trade' => 0,
    'is_drop' => 0,
    'is_destruct' => 1,
    'crystal_type' => 'r',
    'consume_type' => 'consume_type_normal',
  ],
  39936 => 
  [
    'item_id' => 39936,
    'icon' => 'dimension_bracelet_i03',
    'name' => 'Dimensional Bracelet Lv. 4',
    'additionalname' => 'LUC +4',
    'description' => 'When equipped, unlocks 4 talisman slots. LUC +4.',
    'is_trade' => 0,
    'is_drop' => 0,
    'is_destruct' => 1,
    'crystal_type' => 'r',
    'consume_type' => 'consume_type_normal',
  ],
  39937 => 
  [
    'item_id' => 39937,
    'icon' => 'dimension_bracelet_i03',
    'name' => 'Dimensional Bracelet Lv. 4',
    'additionalname' => 'LUC +5',
    'description' => 'When equipped, unlocks 4 talisman slots. LUC +5.',
    'is_trade' => 0,
    'is_drop' => 0,
    'is_destruct' => 1,
    'crystal_type' => 'r',
    'consume_type' => 'consume_type_normal',
  ],
  39938 => 
  [
    'item_id' => 39938,
    'icon' => 'dimension_bracelet_i03',
    'name' => 'Dimensional Bracelet Lv. 4',
    'additionalname' => 'CHA +1',
    'description' => 'When equipped, unlocks 4 talisman slots. CHA +1.',
    'is_trade' => 0,
    'is_drop' => 0,
    'is_destruct' => 1,
    'crystal_type' => 'r',
    'consume_type' => 'consume_type_normal',
  ],
  39939 => 
  [
    'item_id' => 39939,
    'icon' => 'dimension_bracelet_i03',
    'name' => 'Dimensional Bracelet Lv. 4',
    'additionalname' => 'CHA +2',
    'description' => 'When equipped, unlocks 4 talisman slots. CHA +2.',
    'is_trade' => 0,
    'is_drop' => 0,
    'is_destruct' => 1,
    'crystal_type' => 'r',
    'consume_type' => 'consume_type_normal',
  ],
  39940 => 
  [
    'item_id' => 39940,
    'icon' => 'dimension_bracelet_i03',
    'name' => 'Dimensional Bracelet Lv. 4',
    'additionalname' => 'CHA +3',
    'description' => 'When equipped, unlocks 4 talisman slots. CHA +3.',
    'is_trade' => 0,
    'is_drop' => 0,
    'is_destruct' => 1,
    'crystal_type' => 'r',
    'consume_type' => 'consume_type_normal',
  ],
  39941 => 
  [
    'item_id' => 39941,
    'icon' => 'dimension_bracelet_i03',
    'name' => 'Dimensional Bracelet Lv. 4',
    'additionalname' => 'CHA +4',
    'description' => 'When equipped, unlocks 4 talisman slots. CHA +4.',
    'is_trade' => 0,
    'is_drop' => 0,
    'is_destruct' => 1,
    'crystal_type' => 'r',
    'consume_type' => 'consume_type_normal',
  ],
  39942 => 
  [
    'item_id' => 39942,
    'icon' => 'dimension_bracelet_i03',
    'name' => 'Dimensional Bracelet Lv. 4',
    'additionalname' => 'CHA +5',
    'description' => 'When equipped, unlocks 4 talisman slots. CHA +5.',
    'is_trade' => 0,
    'is_drop' => 0,
    'is_destruct' => 1,
    'crystal_type' => 'r',
    'consume_type' => 'consume_type_normal',
  ],
  39943 => 
  [
    'item_id' => 39943,
    'icon' => 'dimension_bracelet_i04',
    'name' => 'Dimensional Bracelet Lv. 5',
    'additionalname' => 'Basic',
    'description' => 'When equipped, unlocks 5 talisman slots.',
    'is_trade' => 0,
    'is_drop' => 0,
    'is_destruct' => 1,
    'crystal_type' => 'r',
    'consume_type' => 'consume_type_normal',
  ],
  39944 => 
  [
    'item_id' => 39944,
    'icon' => 'dimension_bracelet_i04',
    'name' => 'Dimensional Bracelet Lv. 5',
    'additionalname' => 'STR',
    'description' => 'When equipped, unlocks 5 talisman slots. Increases STR.',
    'is_trade' => 0,
    'is_drop' => 0,
    'is_destruct' => 1,
    'crystal_type' => 'r',
    'consume_type' => 'consume_type_normal',
  ],
  39945 => 
  [
    'item_id' => 39945,
    'icon' => 'dimension_bracelet_i04',
    'name' => 'Dimensional Bracelet Lv. 5',
    'additionalname' => 'DEX',
    'description' => 'When equipped, unlocks 5 talisman slots. Increases DEX.',
    'is_trade' => 0,
    'is_drop' => 0,
    'is_destruct' => 1,
    'crystal_type' => 'r',
    'consume_type' => 'consume_type_normal',
  ],
  39946 => 
  [
    'item_id' => 39946,
    'icon' => 'dimension_bracelet_i04',
    'name' => 'Dimensional Bracelet Lv. 5',
    'additionalname' => 'CON',
    'description' => 'When equipped, unlocks 5 talisman slots. Increases CON.',
    'is_trade' => 0,
    'is_drop' => 0,
    'is_destruct' => 1,
    'crystal_type' => 'r',
    'consume_type' => 'consume_type_normal',
  ],
  39947 => 
  [
    'item_id' => 39947,
    'icon' => 'dimension_bracelet_i04',
    'name' => 'Dimensional Bracelet Lv. 5',
    'additionalname' => 'INT',
    'description' => 'When equipped, unlocks 5 talisman slots. Increases INT.',
    'is_trade' => 0,
    'is_drop' => 0,
    'is_destruct' => 1,
    'crystal_type' => 'r',
    'consume_type' => 'consume_type_normal',
  ],
  39948 => 
  [
    'item_id' => 39948,
    'icon' => 'dimension_bracelet_i04',
    'name' => 'Dimensional Bracelet Lv. 5',
    'additionalname' => 'MEN',
    'description' => 'When equipped, unlocks 5 talisman slots. Increases MEN.',
    'is_trade' => 0,
    'is_drop' => 0,
    'is_destruct' => 1,
    'crystal_type' => 'r',
    'consume_type' => 'consume_type_normal',
  ],
  39949 => 
  [
    'item_id' => 39949,
    'icon' => 'dimension_bracelet_i04',
    'name' => 'Dimensional Bracelet Lv. 5',
    'additionalname' => 'WIT',
    'description' => 'When equipped, unlocks 5 talisman slots. Increases WIT.',
    'is_trade' => 0,
    'is_drop' => 0,
    'is_destruct' => 1,
    'crystal_type' => 'r',
    'consume_type' => 'consume_type_normal',
  ],
  39950 => 
  [
    'item_id' => 39950,
    'icon' => 'dimension_bracelet_i04',
    'name' => 'Dimensional Bracelet Lv. 5',
    'additionalname' => 'LUC',
    'description' => 'When equipped, unlocks 5 talisman slots. Increases LUC.',
    'is_trade' => 0,
    'is_drop' => 0,
    'is_destruct' => 1,
    'crystal_type' => 'r',
    'consume_type' => 'consume_type_normal',
  ],
  39951 => 
  [
    'item_id' => 39951,
    'icon' => 'dimension_bracelet_i04',
    'name' => 'Dimensional Bracelet Lv. 5',
    'additionalname' => 'CHA',
    'description' => 'When equipped, unlocks 5 talisman slots. Increases CHA.',
    'is_trade' => 0,
    'is_drop' => 0,
    'is_destruct' => 1,
    'crystal_type' => 'r',
    'consume_type' => 'consume_type_normal',
  ],
  39952 => 
  [
    'item_id' => 39952,
    'icon' => 'dimension_bracelet_i04',
    'name' => 'Dimensional Bracelet Lv. 5',
    'additionalname' => 'STR +1',
    'description' => 'When equipped, unlocks 5 talisman slots. STR +1.',
    'is_trade' => 0,
    'is_drop' => 0,
    'is_destruct' => 1,
    'crystal_type' => 'r',
    'consume_type' => 'consume_type_normal',
  ],
  39953 => 
  [
    'item_id' => 39953,
    'icon' => 'dimension_bracelet_i04',
    'name' => 'Dimensional Bracelet Lv. 5',
    'additionalname' => 'STR+2',
    'description' => 'When equipped, unlocks 5 talisman slots. STR +2.',
    'is_trade' => 0,
    'is_drop' => 0,
    'is_destruct' => 1,
    'crystal_type' => 'r',
    'consume_type' => 'consume_type_normal',
  ],
  39954 => 
  [
    'item_id' => 39954,
    'icon' => 'dimension_bracelet_i04',
    'name' => 'Dimensional Bracelet Lv. 5',
    'additionalname' => 'STR+3',
    'description' => 'When equipped, unlocks 5 talisman slots. STR +3.',
    'is_trade' => 0,
    'is_drop' => 0,
    'is_destruct' => 1,
    'crystal_type' => 'r',
    'consume_type' => 'consume_type_normal',
  ],
  39955 => 
  [
    'item_id' => 39955,
    'icon' => 'dimension_bracelet_i04',
    'name' => 'Dimensional Bracelet Lv. 5',
    'additionalname' => 'STR+4',
    'description' => 'When equipped, unlocks 5 talisman slots. STR +4.',
    'is_trade' => 0,
    'is_drop' => 0,
    'is_destruct' => 1,
    'crystal_type' => 'r',
    'consume_type' => 'consume_type_normal',
  ],
  39956 => 
  [
    'item_id' => 39956,
    'icon' => 'dimension_bracelet_i04',
    'name' => 'Dimensional Bracelet Lv. 5',
    'additionalname' => 'STR +5',
    'description' => 'When equipped, unlocks 5 talisman slots. STR +5.',
    'is_trade' => 0,
    'is_drop' => 0,
    'is_destruct' => 1,
    'crystal_type' => 'r',
    'consume_type' => 'consume_type_normal',
  ],
  39957 => 
  [
    'item_id' => 39957,
    'icon' => 'dimension_bracelet_i04',
    'name' => 'Dimensional Bracelet Lv. 5',
    'additionalname' => 'DEX +1',
    'description' => 'When equipped, unlocks 5 talisman slots. DEX +1.',
    'is_trade' => 0,
    'is_drop' => 0,
    'is_destruct' => 1,
    'crystal_type' => 'r',
    'consume_type' => 'consume_type_normal',
  ],
  39958 => 
  [
    'item_id' => 39958,
    'icon' => 'dimension_bracelet_i04',
    'name' => 'Dimensional Bracelet Lv. 5',
    'additionalname' => 'DEX+2',
    'description' => 'When equipped, unlocks 5 talisman slots. DEX +2.',
    'is_trade' => 0,
    'is_drop' => 0,
    'is_destruct' => 1,
    'crystal_type' => 'r',
    'consume_type' => 'consume_type_normal',
  ],
  39959 => 
  [
    'item_id' => 39959,
    'icon' => 'dimension_bracelet_i04',
    'name' => 'Dimensional Bracelet Lv. 5',
    'additionalname' => 'DEX+3',
    'description' => 'When equipped, unlocks 5 talisman slots. DEX +3.',
    'is_trade' => 0,
    'is_drop' => 0,
    'is_destruct' => 1,
    'crystal_type' => 'r',
    'consume_type' => 'consume_type_normal',
  ],
  39960 => 
  [
    'item_id' => 39960,
    'icon' => 'dimension_bracelet_i04',
    'name' => 'Dimensional Bracelet Lv. 5',
    'additionalname' => 'DEX+4',
    'description' => 'When equipped, unlocks 5 talisman slots. DEX +4.',
    'is_trade' => 0,
    'is_drop' => 0,
    'is_destruct' => 1,
    'crystal_type' => 'r',
    'consume_type' => 'consume_type_normal',
  ],
  39961 => 
  [
    'item_id' => 39961,
    'icon' => 'dimension_bracelet_i04',
    'name' => 'Dimensional Bracelet Lv. 5',
    'additionalname' => 'DEX +5',
    'description' => 'When equipped, unlocks 5 talisman slots. DEX +5.',
    'is_trade' => 0,
    'is_drop' => 0,
    'is_destruct' => 1,
    'crystal_type' => 'r',
    'consume_type' => 'consume_type_normal',
  ],
  39962 => 
  [
    'item_id' => 39962,
    'icon' => 'dimension_bracelet_i04',
    'name' => 'Dimensional Bracelet Lv. 5',
    'additionalname' => 'CON +1',
    'description' => 'When equipped, unlocks 5 talisman slots. CON +1.',
    'is_trade' => 0,
    'is_drop' => 0,
    'is_destruct' => 1,
    'crystal_type' => 'r',
    'consume_type' => 'consume_type_normal',
  ],
  39963 => 
  [
    'item_id' => 39963,
    'icon' => 'dimension_bracelet_i04',
    'name' => 'Dimensional Bracelet Lv. 5',
    'additionalname' => 'CON +2',
    'description' => 'When equipped, unlocks 5 talisman slots. CON +2.',
    'is_trade' => 0,
    'is_drop' => 0,
    'is_destruct' => 1,
    'crystal_type' => 'r',
    'consume_type' => 'consume_type_normal',
  ],
  39964 => 
  [
    'item_id' => 39964,
    'icon' => 'dimension_bracelet_i04',
    'name' => 'Dimensional Bracelet Lv. 5',
    'additionalname' => 'CON +3',
    'description' => 'When equipped, unlocks 5 talisman slots. CON +3.',
    'is_trade' => 0,
    'is_drop' => 0,
    'is_destruct' => 1,
    'crystal_type' => 'r',
    'consume_type' => 'consume_type_normal',
  ],
  39965 => 
  [
    'item_id' => 39965,
    'icon' => 'dimension_bracelet_i04',
    'name' => 'Dimensional Bracelet Lv. 5',
    'additionalname' => 'CON+4',
    'description' => 'When equipped, unlocks 5 talisman slots. CON +4.',
    'is_trade' => 0,
    'is_drop' => 0,
    'is_destruct' => 1,
    'crystal_type' => 'r',
    'consume_type' => 'consume_type_normal',
  ],
  39966 => 
  [
    'item_id' => 39966,
    'icon' => 'dimension_bracelet_i04',
    'name' => 'Dimensional Bracelet Lv. 5',
    'additionalname' => 'CON +5',
    'description' => 'When equipped, unlocks 5 talisman slots. CON +5.',
    'is_trade' => 0,
    'is_drop' => 0,
    'is_destruct' => 1,
    'crystal_type' => 'r',
    'consume_type' => 'consume_type_normal',
  ],
  39967 => 
  [
    'item_id' => 39967,
    'icon' => 'dimension_bracelet_i04',
    'name' => 'Dimensional Bracelet Lv. 5',
    'additionalname' => 'INT +1',
    'description' => 'When equipped, unlocks 5 talisman slots. INT +1.',
    'is_trade' => 0,
    'is_drop' => 0,
    'is_destruct' => 1,
    'crystal_type' => 'r',
    'consume_type' => 'consume_type_normal',
  ],
  39968 => 
  [
    'item_id' => 39968,
    'icon' => 'dimension_bracelet_i04',
    'name' => 'Dimensional Bracelet Lv. 5',
    'additionalname' => 'INT+2',
    'description' => 'When equipped, unlocks 5 talisman slots. INT +2.',
    'is_trade' => 0,
    'is_drop' => 0,
    'is_destruct' => 1,
    'crystal_type' => 'r',
    'consume_type' => 'consume_type_normal',
  ],
  39969 => 
  [
    'item_id' => 39969,
    'icon' => 'dimension_bracelet_i04',
    'name' => 'Dimensional Bracelet Lv. 5',
    'additionalname' => 'INT+3',
    'description' => 'When equipped, unlocks 5 talisman slots. INT +3.',
    'is_trade' => 0,
    'is_drop' => 0,
    'is_destruct' => 1,
    'crystal_type' => 'r',
    'consume_type' => 'consume_type_normal',
  ],
  39970 => 
  [
    'item_id' => 39970,
    'icon' => 'dimension_bracelet_i04',
    'name' => 'Dimensional Bracelet Lv. 5',
    'additionalname' => 'INT+4',
    'description' => 'When equipped, unlocks 5 talisman slots. INT +4.',
    'is_trade' => 0,
    'is_drop' => 0,
    'is_destruct' => 1,
    'crystal_type' => 'r',
    'consume_type' => 'consume_type_normal',
  ],
  39971 => 
  [
    'item_id' => 39971,
    'icon' => 'dimension_bracelet_i04',
    'name' => 'Dimensional Bracelet Lv. 5',
    'additionalname' => 'INT +5',
    'description' => 'When equipped, unlocks 5 talisman slots. INT +5.',
    'is_trade' => 0,
    'is_drop' => 0,
    'is_destruct' => 1,
    'crystal_type' => 'r',
    'consume_type' => 'consume_type_normal',
  ],
  39972 => 
  [
    'item_id' => 39972,
    'icon' => 'dimension_bracelet_i04',
    'name' => 'Dimensional Bracelet Lv. 5',
    'additionalname' => 'MEN +1',
    'description' => 'When equipped, unlocks 5 talisman slots. MEN +1.',
    'is_trade' => 0,
    'is_drop' => 0,
    'is_destruct' => 1,
    'crystal_type' => 'r',
    'consume_type' => 'consume_type_normal',
  ],
  39973 => 
  [
    'item_id' => 39973,
    'icon' => 'dimension_bracelet_i04',
    'name' => 'Dimensional Bracelet Lv. 5',
    'additionalname' => 'MEN +2',
    'description' => 'When equipped, unlocks 5 talisman slots. MEN +2.',
    'is_trade' => 0,
    'is_drop' => 0,
    'is_destruct' => 1,
    'crystal_type' => 'r',
    'consume_type' => 'consume_type_normal',
  ],
  39974 => 
  [
    'item_id' => 39974,
    'icon' => 'dimension_bracelet_i04',
    'name' => 'Dimensional Bracelet Lv. 5',
    'additionalname' => 'MEN +3',
    'description' => 'When equipped, unlocks 5 talisman slots. MEN +3.',
    'is_trade' => 0,
    'is_drop' => 0,
    'is_destruct' => 1,
    'crystal_type' => 'r',
    'consume_type' => 'consume_type_normal',
  ],
  39975 => 
  [
    'item_id' => 39975,
    'icon' => 'dimension_bracelet_i04',
    'name' => 'Dimensional Bracelet Lv. 5',
    'additionalname' => 'MEN+4',
    'description' => 'When equipped, unlocks 5 talisman slots. MEN +4.',
    'is_trade' => 0,
    'is_drop' => 0,
    'is_destruct' => 1,
    'crystal_type' => 'r',
    'consume_type' => 'consume_type_normal',
  ],
  39976 => 
  [
    'item_id' => 39976,
    'icon' => 'dimension_bracelet_i04',
    'name' => 'Dimensional Bracelet Lv. 5',
    'additionalname' => 'MEN +5',
    'description' => 'When equipped, unlocks 5 talisman slots. MEN +5.',
    'is_trade' => 0,
    'is_drop' => 0,
    'is_destruct' => 1,
    'crystal_type' => 'r',
    'consume_type' => 'consume_type_normal',
  ],
  39977 => 
  [
    'item_id' => 39977,
    'icon' => 'dimension_bracelet_i04',
    'name' => 'Dimensional Bracelet Lv. 5',
    'additionalname' => 'WIT +1',
    'description' => 'When equipped, unlocks 5 talisman slots. WIT +1.',
    'is_trade' => 0,
    'is_drop' => 0,
    'is_destruct' => 1,
    'crystal_type' => 'r',
    'consume_type' => 'consume_type_normal',
  ],
  39978 => 
  [
    'item_id' => 39978,
    'icon' => 'dimension_bracelet_i04',
    'name' => 'Dimensional Bracelet Lv. 5',
    'additionalname' => 'WIT+2',
    'description' => 'When equipped, unlocks 5 talisman slots. WIT +2.',
    'is_trade' => 0,
    'is_drop' => 0,
    'is_destruct' => 1,
    'crystal_type' => 'r',
    'consume_type' => 'consume_type_normal',
  ],
  39979 => 
  [
    'item_id' => 39979,
    'icon' => 'dimension_bracelet_i04',
    'name' => 'Dimensional Bracelet Lv. 5',
    'additionalname' => 'WIT+3',
    'description' => 'When equipped, unlocks 5 talisman slots. WIT +3.',
    'is_trade' => 0,
    'is_drop' => 0,
    'is_destruct' => 1,
    'crystal_type' => 'r',
    'consume_type' => 'consume_type_normal',
  ],
  39980 => 
  [
    'item_id' => 39980,
    'icon' => 'dimension_bracelet_i04',
    'name' => 'Dimensional Bracelet Lv. 5',
    'additionalname' => 'WIT+4',
    'description' => 'When equipped, unlocks 5 talisman slots. WIT +4.',
    'is_trade' => 0,
    'is_drop' => 0,
    'is_destruct' => 1,
    'crystal_type' => 'r',
    'consume_type' => 'consume_type_normal',
  ],
  39981 => 
  [
    'item_id' => 39981,
    'icon' => 'dimension_bracelet_i04',
    'name' => 'Dimensional Bracelet Lv. 5',
    'additionalname' => 'WIT +5',
    'description' => 'When equipped, unlocks 5 talisman slots. WIT +5.',
    'is_trade' => 0,
    'is_drop' => 0,
    'is_destruct' => 1,
    'crystal_type' => 'r',
    'consume_type' => 'consume_type_normal',
  ],
  39982 => 
  [
    'item_id' => 39982,
    'icon' => 'dimension_bracelet_i04',
    'name' => 'Dimensional Bracelet Lv. 5',
    'additionalname' => 'LUC +1',
    'description' => 'When equipped, unlocks 5 talisman slots. LUC +1.',
    'is_trade' => 0,
    'is_drop' => 0,
    'is_destruct' => 1,
    'crystal_type' => 'r',
    'consume_type' => 'consume_type_normal',
  ],
  39983 => 
  [
    'item_id' => 39983,
    'icon' => 'dimension_bracelet_i04',
    'name' => 'Dimensional Bracelet Lv. 5',
    'additionalname' => 'LUC +2',
    'description' => 'When equipped, unlocks 5 talisman slots. LUC +2.',
    'is_trade' => 0,
    'is_drop' => 0,
    'is_destruct' => 1,
    'crystal_type' => 'r',
    'consume_type' => 'consume_type_normal',
  ],
  39984 => 
  [
    'item_id' => 39984,
    'icon' => 'dimension_bracelet_i04',
    'name' => 'Dimensional Bracelet Lv. 5',
    'additionalname' => 'LUC +3',
    'description' => 'When equipped, unlocks 5 talisman slots. LUC +3.',
    'is_trade' => 0,
    'is_drop' => 0,
    'is_destruct' => 1,
    'crystal_type' => 'r',
    'consume_type' => 'consume_type_normal',
  ],
  39985 => 
  [
    'item_id' => 39985,
    'icon' => 'dimension_bracelet_i04',
    'name' => 'Dimensional Bracelet Lv. 5',
    'additionalname' => 'LUC +4',
    'description' => 'When equipped, unlocks 5 talisman slots. LUC +4.',
    'is_trade' => 0,
    'is_drop' => 0,
    'is_destruct' => 1,
    'crystal_type' => 'r',
    'consume_type' => 'consume_type_normal',
  ],
  39986 => 
  [
    'item_id' => 39986,
    'icon' => 'dimension_bracelet_i04',
    'name' => 'Dimensional Bracelet Lv. 5',
    'additionalname' => 'LUC +5',
    'description' => 'When equipped, unlocks 5 talisman slots. LUC +5.',
    'is_trade' => 0,
    'is_drop' => 0,
    'is_destruct' => 1,
    'crystal_type' => 'r',
    'consume_type' => 'consume_type_normal',
  ],
  39987 => 
  [
    'item_id' => 39987,
    'icon' => 'dimension_bracelet_i04',
    'name' => 'Dimensional Bracelet Lv. 5',
    'additionalname' => 'CHA +1',
    'description' => 'When equipped, unlocks 5 talisman slots. CHA +1.',
    'is_trade' => 0,
    'is_drop' => 0,
    'is_destruct' => 1,
    'crystal_type' => 'r',
    'consume_type' => 'consume_type_normal',
  ],
  39988 => 
  [
    'item_id' => 39988,
    'icon' => 'dimension_bracelet_i04',
    'name' => 'Dimensional Bracelet Lv. 5',
    'additionalname' => 'CHA +2',
    'description' => 'When equipped, unlocks 5 talisman slots. CHA +2.',
    'is_trade' => 0,
    'is_drop' => 0,
    'is_destruct' => 1,
    'crystal_type' => 'r',
    'consume_type' => 'consume_type_normal',
  ],
  39989 => 
  [
    'item_id' => 39989,
    'icon' => 'dimension_bracelet_i04',
    'name' => 'Dimensional Bracelet Lv. 5',
    'additionalname' => 'CHA +3',
    'description' => 'When equipped, unlocks 5 talisman slots. CHA +3.',
    'is_trade' => 0,
    'is_drop' => 0,
    'is_destruct' => 1,
    'crystal_type' => 'r',
    'consume_type' => 'consume_type_normal',
  ],
  39990 => 
  [
    'item_id' => 39990,
    'icon' => 'dimension_bracelet_i04',
    'name' => 'Dimensional Bracelet Lv. 5',
    'additionalname' => 'CHA +4',
    'description' => 'When equipped, unlocks 5 talisman slots. CHA +4.',
    'is_trade' => 0,
    'is_drop' => 0,
    'is_destruct' => 1,
    'crystal_type' => 'r',
    'consume_type' => 'consume_type_normal',
  ],
  39991 => 
  [
    'item_id' => 39991,
    'icon' => 'dimension_bracelet_i04',
    'name' => 'Dimensional Bracelet Lv. 5',
    'additionalname' => 'CHA +5',
    'description' => 'When equipped, unlocks 5 talisman slots. CHA +5.',
    'is_trade' => 0,
    'is_drop' => 0,
    'is_destruct' => 1,
    'crystal_type' => 'r',
    'consume_type' => 'consume_type_normal',
  ],
  39992 => 
  [
    'item_id' => 39992,
    'icon' => 'dimension_bracelet_i05',
    'name' => 'Dimensional Bracelet Lv. 6',
    'additionalname' => 'Basic',
    'description' => 'When equipped, unlocks 6 talisman slots.',
    'is_trade' => 0,
    'is_drop' => 0,
    'is_destruct' => 1,
    'crystal_type' => 'r',
    'consume_type' => 'consume_type_normal',
  ],
  39993 => 
  [
    'item_id' => 39993,
    'icon' => 'dimension_bracelet_i05',
    'name' => 'Dimensional Bracelet Lv. 6',
    'additionalname' => 'STR',
    'description' => 'When equipped, unlocks 6 talisman slots. Increases STR.',
    'is_trade' => 0,
    'is_drop' => 0,
    'is_destruct' => 1,
    'crystal_type' => 'r',
    'consume_type' => 'consume_type_normal',
  ],
  39994 => 
  [
    'item_id' => 39994,
    'icon' => 'dimension_bracelet_i05',
    'name' => 'Dimensional Bracelet Lv. 6',
    'additionalname' => 'DEX',
    'description' => 'When equipped, unlocks 6 talisman slots. Increases DEX.',
    'is_trade' => 0,
    'is_drop' => 0,
    'is_destruct' => 1,
    'crystal_type' => 'r',
    'consume_type' => 'consume_type_normal',
  ],
  39995 => 
  [
    'item_id' => 39995,
    'icon' => 'dimension_bracelet_i05',
    'name' => 'Dimensional Bracelet Lv. 6',
    'additionalname' => 'CON',
    'description' => 'When equipped, unlocks 6 talisman slots. Increases CON.',
    'is_trade' => 0,
    'is_drop' => 0,
    'is_destruct' => 1,
    'crystal_type' => 'r',
    'consume_type' => 'consume_type_normal',
  ],
  39996 => 
  [
    'item_id' => 39996,
    'icon' => 'dimension_bracelet_i05',
    'name' => 'Dimensional Bracelet Lv. 6',
    'additionalname' => 'INT',
    'description' => 'When equipped, unlocks 6 talisman slots. Increases INT.',
    'is_trade' => 0,
    'is_drop' => 0,
    'is_destruct' => 1,
    'crystal_type' => 'r',
    'consume_type' => 'consume_type_normal',
  ],
  39997 => 
  [
    'item_id' => 39997,
    'icon' => 'dimension_bracelet_i05',
    'name' => 'Dimensional Bracelet Lv. 6',
    'additionalname' => 'MEN',
    'description' => 'When equipped, unlocks 6 talisman slots. Increases MEN.',
    'is_trade' => 0,
    'is_drop' => 0,
    'is_destruct' => 1,
    'crystal_type' => 'r',
    'consume_type' => 'consume_type_normal',
  ],
  39998 => 
  [
    'item_id' => 39998,
    'icon' => 'dimension_bracelet_i05',
    'name' => 'Dimensional Bracelet Lv. 6',
    'additionalname' => 'WIT',
    'description' => 'When equipped, unlocks 6 talisman slots. Increases WIT.',
    'is_trade' => 0,
    'is_drop' => 0,
    'is_destruct' => 1,
    'crystal_type' => 'r',
    'consume_type' => 'consume_type_normal',
  ],
  39999 => 
  [
    'item_id' => 39999,
    'icon' => 'dimension_bracelet_i05',
    'name' => 'Dimensional Bracelet Lv. 6',
    'additionalname' => 'LUC',
    'description' => 'When equipped, unlocks 6 talisman slots. Increases LUC.',
    'is_trade' => 0,
    'is_drop' => 0,
    'is_destruct' => 1,
    'crystal_type' => 'r',
    'consume_type' => 'consume_type_normal',
  ],
];