<?php return [
  4300 => 
  [
    'item_id' => 4300,
    'icon' => 'etc_piece_of_paper_white_i00',
    'name' => 'Operation Document - 2/10',
    'additionalname' => NULL,
    'description' => 'This document was found in the cargo of the Trade Guild. The document contains various information regarding Innadril. How could this have happened...?',
    'is_trade' => 0,
    'is_drop' => 0,
    'is_destruct' => 1,
    'crystal_type' => 'none',
    'consume_type' => 'consume_type_stackable',
  ],
  4301 => 
  [
    'item_id' => 4301,
    'icon' => 'etc_piece_of_paper_white_i00',
    'name' => 'Operation Document - 3/10',
    'additionalname' => NULL,
    'description' => 'This document was found in the cargo of the Trade Guild. The document contains various information regarding Innadril. How could this have happened...?',
    'is_trade' => 0,
    'is_drop' => 0,
    'is_destruct' => 1,
    'crystal_type' => 'none',
    'consume_type' => 'consume_type_stackable',
  ],
  4302 => 
  [
    'item_id' => 4302,
    'icon' => 'etc_piece_of_paper_white_i00',
    'name' => 'Operation Document - 4/10',
    'additionalname' => NULL,
    'description' => 'This document was found in the cargo of the Trade Guild. The document contains various information regarding Innadril. How could this have happened...?',
    'is_trade' => 0,
    'is_drop' => 0,
    'is_destruct' => 1,
    'crystal_type' => 'none',
    'consume_type' => 'consume_type_stackable',
  ],
  4303 => 
  [
    'item_id' => 4303,
    'icon' => 'etc_piece_of_paper_white_i00',
    'name' => 'Operation Document - 5/10',
    'additionalname' => NULL,
    'description' => 'This document was found in the cargo of the Trade Guild. The document contains various information regarding Innadril. How could this have happened...?',
    'is_trade' => 0,
    'is_drop' => 0,
    'is_destruct' => 1,
    'crystal_type' => 'none',
    'consume_type' => 'consume_type_stackable',
  ],
  4304 => 
  [
    'item_id' => 4304,
    'icon' => 'etc_piece_of_paper_white_i00',
    'name' => 'Operation Document - 6/10',
    'additionalname' => NULL,
    'description' => 'This document was found in the cargo of the Trade Guild. The document contains various information regarding Innadril. How could this have happened...?',
    'is_trade' => 0,
    'is_drop' => 0,
    'is_destruct' => 1,
    'crystal_type' => 'none',
    'consume_type' => 'consume_type_stackable',
  ],
  4305 => 
  [
    'item_id' => 4305,
    'icon' => 'etc_piece_of_paper_white_i00',
    'name' => 'Operation Document - 7/10',
    'additionalname' => NULL,
    'description' => 'This document was found in the cargo of the Trade Guild. The document contains various information regarding Innadril. How could this have happened...?',
    'is_trade' => 0,
    'is_drop' => 0,
    'is_destruct' => 1,
    'crystal_type' => 'none',
    'consume_type' => 'consume_type_stackable',
  ],
  4306 => 
  [
    'item_id' => 4306,
    'icon' => 'etc_piece_of_paper_white_i00',
    'name' => 'Operation Document - 8/10',
    'additionalname' => NULL,
    'description' => 'This document was found in the cargo of the Trade Guild. The document contains various information regarding Innadril. How could this have happened...?',
    'is_trade' => 0,
    'is_drop' => 0,
    'is_destruct' => 1,
    'crystal_type' => 'none',
    'consume_type' => 'consume_type_stackable',
  ],
  4307 => 
  [
    'item_id' => 4307,
    'icon' => 'etc_piece_of_paper_white_i00',
    'name' => 'Operation Document - 9/10',
    'additionalname' => NULL,
    'description' => 'This document was found in the cargo of the Trade Guild. The document contains various information regarding Innadril. How could this have happened...?',
    'is_trade' => 0,
    'is_drop' => 0,
    'is_destruct' => 1,
    'crystal_type' => 'none',
    'consume_type' => 'consume_type_stackable',
  ],
  4308 => 
  [
    'item_id' => 4308,
    'icon' => 'etc_piece_of_paper_white_i00',
    'name' => 'Operation Document - 10/10',
    'additionalname' => NULL,
    'description' => 'This document was found in the cargo of the Trade Guild. The document contains various information regarding Innadril. How could this have happened...?',
    'is_trade' => 0,
    'is_drop' => 0,
    'is_destruct' => 1,
    'crystal_type' => 'none',
    'consume_type' => 'consume_type_stackable',
  ],
  4309 => 
  [
    'item_id' => 4309,
    'icon' => 'etc_spellbook_gray_i00',
    'name' => 'Completed Operation Order',
    'additionalname' => NULL,
    'description' => 'Book consisting of 10 pages of operation orders bound together. Who should we take it to...?',
    'is_trade' => 0,
    'is_drop' => 0,
    'is_destruct' => 1,
    'crystal_type' => 'none',
    'consume_type' => 'consume_type_stackable',
  ],
  4310 => 
  [
    'item_id' => 4310,
    'icon' => 'etc_paper_black_i00',
    'name' => 'Iason Heines Bill',
    'additionalname' => NULL,
    'description' => 'The bills face value is 1,000 Adena. If you take it to Roman of the Blacksmith Guild in Innadril, you can use it to purchase various ingredients.',
    'is_trade' => 0,
    'is_drop' => 0,
    'is_destruct' => 1,
    'crystal_type' => 'none',
    'consume_type' => 'consume_type_stackable',
  ],
  4311 => 
  [
    'item_id' => 4311,
    'icon' => 'etc_spellbook_gray_i00',
    'name' => 'Gillians Diary',
    'additionalname' => NULL,
    'description' => 'Gillians diary. The last entry was made one year ago.',
    'is_trade' => 0,
    'is_drop' => 0,
    'is_destruct' => 1,
    'crystal_type' => 'none',
    'consume_type' => 'consume_type_stackable',
  ],
  4312 => 
  [
    'item_id' => 4312,
    'icon' => 'etc_piece_of_paper_gray_i00',
    'name' => 'Gillians Notes',
    'additionalname' => NULL,
    'description' => 'Partial lyrics of a song Gillian was jotting down.',
    'is_trade' => 0,
    'is_drop' => 0,
    'is_destruct' => 1,
    'crystal_type' => 'none',
    'consume_type' => 'consume_type_stackable',
  ],
  4313 => 
  [
    'item_id' => 4313,
    'icon' => 'etc_musical_note_i01',
    'name' => 'Unfinished Music',
    'additionalname' => NULL,
    'description' => 'Unfinished music score of a song that Gilian composed for a former lover.',
    'is_trade' => 0,
    'is_drop' => 0,
    'is_destruct' => 1,
    'crystal_type' => 'none',
    'consume_type' => 'consume_type_stackable',
  ],
  4314 => 
  [
    'item_id' => 4314,
    'icon' => 'etc_bodypart_heart_i00',
    'name' => 'Gillians Heart',
    'additionalname' => NULL,
    'description' => 'The heart that Gillian threw out to forget his feelings of love. Return it to the Revenant of Gillian.',
    'is_trade' => 0,
    'is_drop' => 0,
    'is_destruct' => 1,
    'crystal_type' => 'none',
    'consume_type' => 'consume_type_stackable',
  ],
  4315 => 
  [
    'item_id' => 4315,
    'icon' => 'etc_royal_seal_of_lord_i00',
    'name' => 'Gandi Tribes Relic',
    'additionalname' => NULL,
    'description' => 'The sacred object of the Gandi Tribe that has been recovered from Bugbears. Take it to Gandi Chief Chianta in the Town of Dion.',
    'is_trade' => 0,
    'is_drop' => 0,
    'is_destruct' => 1,
    'crystal_type' => 'none',
    'consume_type' => 'consume_type_stackable',
  ],
  4316 => 
  [
    'item_id' => 4316,
    'icon' => 'etc_dragon_flute_i00',
    'name' => 'Swans Flute',
    'additionalname' => NULL,
    'description' => 'Flute that Troubadour Swan had obtained as a gift for Musician Nanarin.',
    'is_trade' => 0,
    'is_drop' => 0,
    'is_destruct' => 1,
    'crystal_type' => 'none',
    'consume_type' => 'consume_type_stackable',
  ],
  4317 => 
  [
    'item_id' => 4317,
    'icon' => 'etc_scroll_white_i00',
    'name' => 'Swans Letter',
    'additionalname' => NULL,
    'description' => 'Love letter that Troubadour Swan wants to send to Musician Nanarin along with the flute. Take them to Musician Nanarin.',
    'is_trade' => 0,
    'is_drop' => 0,
    'is_destruct' => 1,
    'crystal_type' => 'none',
    'consume_type' => 'consume_type_stackable',
  ],
  4318 => 
  [
    'item_id' => 4318,
    'icon' => 'etc_ladys_dress_i00',
    'name' => 'Event Clothes',
    'additionalname' => NULL,
    'description' => 'Gift that Musician Nanarin is sending to Musician Barbado. Take it to Barbado.',
    'is_trade' => 0,
    'is_drop' => 0,
    'is_destruct' => 0,
    'crystal_type' => 'none',
    'consume_type' => 'consume_type_stackable',
  ],
  4319 => 
  [
    'item_id' => 4319,
    'icon' => 'etc_dragon_flute_i00',
    'name' => 'Nanarins Flute',
    'additionalname' => NULL,
    'description' => 'Gift that Musician Nanarin is sending to Musician Barbado. Take it to Barbado.',
    'is_trade' => 0,
    'is_drop' => 0,
    'is_destruct' => 0,
    'crystal_type' => 'none',
    'consume_type' => 'consume_type_stackable',
  ],
  4320 => 
  [
    'item_id' => 4320,
    'icon' => 'etc_oil_pot_black_i00',
    'name' => 'Sabrins Black Beer',
    'additionalname' => NULL,
    'description' => 'Gift that Musician Nanarin is sending to Musician Barbado. Take it to Barbado.',
    'is_trade' => 0,
    'is_drop' => 0,
    'is_destruct' => 0,
    'crystal_type' => 'none',
    'consume_type' => 'consume_type_stackable',
  ],
  4321 => 
  [
    'item_id' => 4321,
    'icon' => 'etc_oil_pot_black_i00',
    'name' => 'Stolen Black Beer',
    'additionalname' => NULL,
    'description' => 'Black beer that was stolen from Jonas. Take it to Trader Sabrin.',
    'is_trade' => 0,
    'is_drop' => 0,
    'is_destruct' => 1,
    'crystal_type' => 'none',
    'consume_type' => 'consume_type_stackable',
  ],
  4322 => 
  [
    'item_id' => 4322,
    'icon' => 'etc_ladys_dress_i00',
    'name' => 'Stolen Event Clothes',
    'additionalname' => NULL,
    'description' => 'Event clothes that were stolen from Trader Sonia. Take them to Guard Xaber.',
    'is_trade' => 0,
    'is_drop' => 0,
    'is_destruct' => 1,
    'crystal_type' => 'none',
    'consume_type' => 'consume_type_stackable',
  ],
  4323 => 
  [
    'item_id' => 4323,
    'icon' => 'etc_old_key_i01',
    'name' => 'Clothes Chest Key',
    'additionalname' => NULL,
    'description' => 'The key given by Bard Swan. Use this key to open the clothes chest and retrieve the event clothes.',
    'is_trade' => 0,
    'is_drop' => 0,
    'is_destruct' => 1,
    'crystal_type' => 'none',
    'consume_type' => 'consume_type_stackable',
  ],
  4324 => 
  [
    'item_id' => 4324,
    'icon' => 'etc_old_key_i02',
    'name' => 'Beer Chest Key',
    'additionalname' => NULL,
    'description' => 'The key given by Bard Swan. Use this key to open the beer chest and get the black beer out of it.',
    'is_trade' => 0,
    'is_drop' => 0,
    'is_destruct' => 1,
    'crystal_type' => 'none',
    'consume_type' => 'consume_type_stackable',
  ],
  4325 => 
  [
    'item_id' => 4325,
    'icon' => 'etc_leaf_green_i00',
    'name' => 'Fairy Leaf',
    'additionalname' => NULL,
    'description' => 'Leaf given by Fairy Mimyu to put on the fairys neck wound that was inflicted by a Hatchling.',
    'is_trade' => 0,
    'is_drop' => 0,
    'is_destruct' => 1,
    'crystal_type' => 'none',
    'consume_type' => 'consume_type_stackable',
  ],
  4326 => 
  [
    'item_id' => 4326,
    'icon' => 'etc_pet_arms_i04',
    'name' => 'Ratman Scavengers Skull',
    'additionalname' => NULL,
    'description' => 'Heads of Ratman Scavengers that you hunted after receiving a request from Katari. Collect 10 of them and take them to Katari.',
    'is_trade' => 0,
    'is_drop' => 0,
    'is_destruct' => 1,
    'crystal_type' => 'none',
    'consume_type' => 'consume_type_stackable',
  ],
  4327 => 
  [
    'item_id' => 4327,
    'icon' => 'etc_mane_i00',
    'name' => 'Turek War Hounds Tail',
    'additionalname' => NULL,
    'description' => 'The tails of Turek war Hounds that Piotur asks you to catch. Collect 10 of them and take them to Piotur.',
    'is_trade' => 0,
    'is_drop' => 0,
    'is_destruct' => 1,
    'crystal_type' => 'none',
    'consume_type' => 'consume_type_stackable',
  ],
  4328 => 
  [
    'item_id' => 4328,
    'icon' => 'etc_heart_i00',
    'name' => 'Tyrant Kingpins Heart',
    'additionalname' => NULL,
    'description' => 'Tyrant Kingpins Heart. Take it to Elder Casian.',
    'is_trade' => 0,
    'is_drop' => 0,
    'is_destruct' => 1,
    'crystal_type' => 'none',
    'consume_type' => 'consume_type_stackable',
  ],
  4329 => 
  [
    'item_id' => 4329,
    'icon' => 'etc_poison_pouch_i00',
    'name' => 'Trisalim Tarantulas Venom Sac',
    'additionalname' => NULL,
    'description' => 'The venom sacs of Trisalim Tarantulas that Magister Joan asked you to hunt. Collect three and take them to Magister Joan.',
    'is_trade' => 0,
    'is_drop' => 0,
    'is_destruct' => 1,
    'crystal_type' => 'none',
    'consume_type' => 'consume_type_stackable',
  ],
  4330 => 
  [
    'item_id' => 4330,
    'icon' => 'etc_leash_i00',
    'name' => 'Penitents Manacles',
    'additionalname' => NULL,
    'description' => 'Heavy set of manacles forged at the Dark Judges behest. Take them to the Dark Judge.',
    'is_trade' => 0,
    'is_drop' => 0,
    'is_destruct' => 1,
    'crystal_type' => 'none',
    'consume_type' => 'consume_type_stackable',
  ],
  4331 => 
  [
    'item_id' => 4331,
    'icon' => 'etc_recipe_red_i00',
    'name' => 'Manual of Manacles',
    'additionalname' => NULL,
    'description' => 'Blacksmith Frame x1, Steel x5, Adamantite Nugget x2, Silver Nugget x10, Cokes x10',
    'is_trade' => 0,
    'is_drop' => 0,
    'is_destruct' => 1,
    'crystal_type' => 'none',
    'consume_type' => 'consume_type_stackable',
  ],
  4332 => 
  [
    'item_id' => 4332,
    'icon' => 'etc_orcish_talisman_i00',
    'name' => 'Tarlk Amulet',
    'additionalname' => NULL,
    'description' => 'Equipped in 1 head accessory slot.',
    'is_trade' => 0,
    'is_drop' => 0,
    'is_destruct' => 1,
    'crystal_type' => 'none',
    'consume_type' => 'consume_type_stackable',
  ],
  4333 => 
  [
    'item_id' => 4333,
    'icon' => 'etc_paper_black_i00',
    'name' => 'Contest Certificate',
    'additionalname' => NULL,
    'description' => 'Certificate that one can present to participate in the hunt for Tarlk Basilisks, a preliminary contest for a Clan Hall Siege War.',
    'is_trade' => 0,
    'is_drop' => 0,
    'is_destruct' => 1,
    'crystal_type' => 'none',
    'consume_type' => 'consume_type_stackable',
  ],
  4334 => 
  [
    'item_id' => 4334,
    'icon' => 'etc_reagent_red_i00',
    'name' => 'Ant Fluids',
    'additionalname' => NULL,
    'description' => 'Bodily fluids extracted from ants or Ant Captains. Collect 20 and take them to Elder Casian.',
    'is_trade' => 0,
    'is_drop' => 0,
    'is_destruct' => 1,
    'crystal_type' => 'none',
    'consume_type' => 'consume_type_stackable',
  ],
  4335 => 
  [
    'item_id' => 4335,
    'icon' => 'etc_bodypart_brain_i00',
    'name' => 'Noble Ants Nerve Tissue',
    'additionalname' => NULL,
    'description' => 'The nerve tissue harvested from a Noble Ants head. Take it to Elder Casian along with the Ant Fluids.',
    'is_trade' => 0,
    'is_drop' => 0,
    'is_destruct' => 1,
    'crystal_type' => 'none',
    'consume_type' => 'consume_type_stackable',
  ],
  4336 => 
  [
    'item_id' => 4336,
    'icon' => 'etc_spell_shot_silver_i00',
    'name' => 'Casians Enzyme',
    'additionalname' => NULL,
    'description' => 'Enzyme created by Elder Casian. Find the Ant Larvae Sleeping within the Ant Nest Dungeon and administer the enzyme to them.',
    'is_trade' => 0,
    'is_drop' => 0,
    'is_destruct' => 1,
    'crystal_type' => 'none',
    'consume_type' => 'consume_type_stackable',
  ],
  4337 => 
  [
    'item_id' => 4337,
    'icon' => 'etc_scale_of_medusa_green_i00',
    'name' => 'Alligator Leather',
    'additionalname' => NULL,
    'description' => 'Pelts obtained from alligators caught on Alligator Island. You can sell it to Enverun.',
    'is_trade' => 0,
    'is_drop' => 0,
    'is_destruct' => 1,
    'crystal_type' => 'none',
    'consume_type' => 'consume_type_stackable',
  ],
  4338 => 
  [
    'item_id' => 4338,
    'icon' => 'etc_scale_of_medusa_blue_i00',
    'name' => 'Bluebacked Alligator Leather',
    'additionalname' => NULL,
    'description' => 'Leather from Blue Alligator s caught on Alligator Island. You can sell it to Enverun at a high price.',
    'is_trade' => 0,
    'is_drop' => 0,
    'is_destruct' => 1,
    'crystal_type' => 'none',
    'consume_type' => 'consume_type_stackable',
  ],
  4339 => 
  [
    'item_id' => 4339,
    'icon' => 'etc_scale_of_medusa_red_i00',
    'name' => 'Bejeweled Alligator Leather',
    'additionalname' => NULL,
    'description' => 'Piece of Bejeweled Alligator Leather caught on Alligator Island. You can sell it to Enverun at a high price.',
    'is_trade' => 0,
    'is_drop' => 0,
    'is_destruct' => 1,
    'crystal_type' => 'none',
    'consume_type' => 'consume_type_stackable',
  ],
  4340 => 
  [
    'item_id' => 4340,
    'icon' => 'etc_recipe_red_i00',
    'name' => 'Certificate of Approval to Create a Belt',
    'additionalname' => NULL,
    'description' => 'If you take a sufficient amount of Alligator Leather and show it to Gabana, a master leather craftsman, you can have an Alligator Leather Belt made.',
    'is_trade' => 0,
    'is_drop' => 0,
    'is_destruct' => 1,
    'crystal_type' => 'none',
    'consume_type' => 'consume_type_stackable',
  ],
  4341 => 
  [
    'item_id' => 4341,
    'icon' => 'etc_recipe_blue_i00',
    'name' => 'Certificate of Approval to Create a Purse',
    'additionalname' => NULL,
    'description' => 'If you take a sufficient amount of Alligator Leather and show it to Gabana, a master leather craftsman, you can have an Alligator Leather Purse made.',
    'is_trade' => 0,
    'is_drop' => 0,
    'is_destruct' => 1,
    'crystal_type' => 'none',
    'consume_type' => 'consume_type_stackable',
  ],
  4342 => 
  [
    'item_id' => 4342,
    'icon' => 'etc_gem_blue_i00',
    'name' => 'Water Crystal',
    'additionalname' => NULL,
    'description' => 'Lump of crystal that contains the energy of water. You should find the Stone Statue of Water and dedicate it to the statue.',
    'is_trade' => 0,
    'is_drop' => 0,
    'is_destruct' => 1,
    'crystal_type' => 'none',
    'consume_type' => 'consume_type_stackable',
  ],
  4343 => 
  [
    'item_id' => 4343,
    'icon' => 'etc_gem_red_i00',
    'name' => 'Fire Crystal',
    'additionalname' => NULL,
    'description' => 'Lump of crystal that contains the energy of fire. You should find the Stone Statue of Fire and dedicate it to the statue.',
    'is_trade' => 0,
    'is_drop' => 0,
    'is_destruct' => 1,
    'crystal_type' => 'none',
    'consume_type' => 'consume_type_stackable',
  ],
  4344 => 
  [
    'item_id' => 4344,
    'icon' => 'etc_gem_green_i00',
    'name' => 'Wind Crystal',
    'additionalname' => NULL,
    'description' => 'Lump of crystal that contains the energy of wind. You should find the Stone Statue of Wind and dedicate it to the statue.',
    'is_trade' => 0,
    'is_drop' => 0,
    'is_destruct' => 1,
    'crystal_type' => 'none',
    'consume_type' => 'consume_type_stackable',
  ],
  4345 => 
  [
    'item_id' => 4345,
    'icon' => 'etc_gem_yellow_i00',
    'name' => 'Earth Crystal',
    'additionalname' => NULL,
    'description' => 'Lump of crystal that contains the energy of earth. You should find the Stone Statue of Earth and dedicate it to the statue.',
    'is_trade' => 0,
    'is_drop' => 0,
    'is_destruct' => 1,
    'crystal_type' => 'none',
    'consume_type' => 'consume_type_stackable',
  ],
  4346 => 
  [
    'item_id' => 4346,
    'icon' => 'etc_gem_clear_i00',
    'name' => 'Dark Crystal',
    'additionalname' => NULL,
    'description' => 'Lump of crystal that contains the energy of darkness. You should find the Stone Statue of Darkness and dedicate it to the statue.',
    'is_trade' => 0,
    'is_drop' => 0,
    'is_destruct' => 1,
    'crystal_type' => 'none',
    'consume_type' => 'consume_type_stackable',
  ],
  4347 => 
  [
    'item_id' => 4347,
    'icon' => 'etc_gem_black_i00',
    'name' => 'Crystal of Light',
    'additionalname' => NULL,
    'description' => 'Lump of crystal that contains the energy of light. You should find the Stone Statue of Light and dedicate it to the statue.',
    'is_trade' => 0,
    'is_drop' => 0,
    'is_destruct' => 1,
    'crystal_type' => 'none',
    'consume_type' => 'consume_type_stackable',
  ],
  4348 => 
  [
    'item_id' => 4348,
    'icon' => 'etc_gem_green_i00',
    'name' => 'Jade Crystal',
    'additionalname' => NULL,
    'description' => 'Jade from the Enchanted Valley. Collect and take them to Bentley in Hunters Village.',
    'is_trade' => 1,
    'is_drop' => 1,
    'is_destruct' => 1,
    'crystal_type' => 'none',
    'consume_type' => 'consume_type_stackable',
  ],
  4349 => 
  [
    'item_id' => 4349,
    'icon' => 'etc_holy_statue_silver_i00',
    'name' => 'Ancient Bust',
    'additionalname' => NULL,
    'description' => 'Statue of a goddess that was created by the ancient sculptor Berona in ancient times.',
    'is_trade' => 1,
    'is_drop' => 1,
    'is_destruct' => 1,
    'crystal_type' => 'none',
    'consume_type' => 'consume_type_stackable',
  ],
  4350 => 
  [
    'item_id' => 4350,
    'icon' => 'etc_statue_of_einhasad_gold_i00',
    'name' => 'Ancient Goddess Statue: ?',
    'additionalname' => NULL,
    'description' => 'Statue created by the ancient sculptor Berona. It Has not been evaluated by antique experts yet.',
    'is_trade' => 1,
    'is_drop' => 1,
    'is_destruct' => 1,
    'crystal_type' => 'none',
    'consume_type' => 'consume_type_stackable',
  ],
  4351 => 
  [
    'item_id' => 4351,
    'icon' => 'etc_statue_of_einhasad_gold_i00',
    'name' => 'Ancient Goddess Statue: Prototype',
    'additionalname' => NULL,
    'description' => 'Statue created by Berona, an ancient sculptor. - Prototype',
    'is_trade' => 1,
    'is_drop' => 1,
    'is_destruct' => 1,
    'crystal_type' => 'none',
    'consume_type' => 'consume_type_stackable',
  ],
  4352 => 
  [
    'item_id' => 4352,
    'icon' => 'etc_statue_of_einhasad_gold_i00',
    'name' => 'Ancient Goddess Statue: Original',
    'additionalname' => NULL,
    'description' => 'Statue created by Berona, a sculptor in ancient times. - Original',
    'is_trade' => 1,
    'is_drop' => 1,
    'is_destruct' => 1,
    'crystal_type' => 'none',
    'consume_type' => 'consume_type_stackable',
  ],
  4353 => 
  [
    'item_id' => 4353,
    'icon' => 'etc_statue_of_einhasad_gold_i00',
    'name' => 'Ancient Goddess Statue: Replica',
    'additionalname' => NULL,
    'description' => 'Replicated statues that have been created by present day sculptors who imitated Beronas works.',
    'is_trade' => 1,
    'is_drop' => 1,
    'is_destruct' => 1,
    'crystal_type' => 'none',
    'consume_type' => 'consume_type_stackable',
  ],
  4354 => 
  [
    'item_id' => 4354,
    'icon' => 'etc_statue_of_einhasad_gold_i00',
    'name' => 'Ancient Goddess Statue: Forgery',
    'additionalname' => NULL,
    'description' => 'Forgeries that have been created in imitation of the ancient sculptor Beronas works.',
    'is_trade' => 1,
    'is_drop' => 1,
    'is_destruct' => 1,
    'crystal_type' => 'none',
    'consume_type' => 'consume_type_stackable',
  ],
  4355 => 
  [
    'item_id' => 4355,
    'icon' => 'etc_magic_coin_blue_i01',
    'name' => 'Blue Eva',
    'additionalname' => NULL,
    'description' => 'Special Coin',
    'is_trade' => 1,
    'is_drop' => 1,
    'is_destruct' => 1,
    'crystal_type' => 'none',
    'consume_type' => 'consume_type_stackable',
  ],
  4356 => 
  [
    'item_id' => 4356,
    'icon' => 'etc_magic_coin_gold_i02',
    'name' => 'Gold Einhasad',
    'additionalname' => NULL,
    'description' => 'Special Coin',
    'is_trade' => 1,
    'is_drop' => 1,
    'is_destruct' => 1,
    'crystal_type' => 'none',
    'consume_type' => 'consume_type_stackable',
  ],
  4357 => 
  [
    'item_id' => 4357,
    'icon' => 'etc_magic_coin_silver_i02',
    'name' => 'Silver Shillien',
    'additionalname' => NULL,
    'description' => 'Special Coin',
    'is_trade' => 1,
    'is_drop' => 1,
    'is_destruct' => 1,
    'crystal_type' => 'none',
    'consume_type' => 'consume_type_stackable',
  ],
  4358 => 
  [
    'item_id' => 4358,
    'icon' => 'etc_magic_coin_blood_i02',
    'name' => 'Bloody Paagrio',
    'additionalname' => NULL,
    'description' => 'Special Coin',
    'is_trade' => 1,
    'is_drop' => 1,
    'is_destruct' => 1,
    'crystal_type' => 'none',
    'consume_type' => 'consume_type_stackable',
  ],
  4359 => 
  [
    'item_id' => 4359,
    'icon' => 'etc_wine_barrel_i00',
    'name' => 'Barrel of Liquor',
    'additionalname' => NULL,
    'description' => 'Barrel that is filled to the brim with delicious and fragrant liquor. The barrel is very heavy.',
    'is_trade' => 1,
    'is_drop' => 1,
    'is_destruct' => 1,
    'crystal_type' => 'none',
    'consume_type' => 'consume_type_normal',
  ],
  4360 => 
  [
    'item_id' => 4360,
    'icon' => 'etc_beetle_i00',
    'name' => 'Precious Scarab',
    'additionalname' => NULL,
    'description' => 'Scarab that is transparent and shines like a precious stone. Among hustlers it is traded at a high price.',
    'is_trade' => 1,
    'is_drop' => 1,
    'is_destruct' => 1,
    'crystal_type' => 'none',
    'consume_type' => 'consume_type_normal',
  ],
  4361 => 
  [
    'item_id' => 4361,
    'icon' => 'etc_flower_i00',
    'name' => 'Simbelmyne',
    'additionalname' => NULL,
    'description' => 'Type of flower that is believed to have the power to heal sickness. It is a favorite of elves.',
    'is_trade' => 1,
    'is_drop' => 1,
    'is_destruct' => 1,
    'crystal_type' => 'none',
    'consume_type' => 'consume_type_normal',
  ],
  4362 => 
  [
    'item_id' => 4362,
    'icon' => 'etc_totem_black_i00',
    'name' => 'Odd Doll',
    'additionalname' => NULL,
    'description' => 'It is a strange looking statue of a living creature that looks like an imp. It is an orcs favorite item.',
    'is_trade' => 1,
    'is_drop' => 1,
    'is_destruct' => 1,
    'crystal_type' => 'none',
    'consume_type' => 'consume_type_normal',
  ],
  4363 => 
  [
    'item_id' => 4363,
    'icon' => 'etc_ladys_dress_i00',
    'name' => 'Scarlet Dress',
    'additionalname' => NULL,
    'description' => 'Very attractive scarlet Aden-style dress designed for a virtuous lady.',
    'is_trade' => 1,
    'is_drop' => 1,
    'is_destruct' => 1,
    'crystal_type' => 'none',
    'consume_type' => 'consume_type_normal',
  ],
  4364 => 
  [
    'item_id' => 4364,
    'icon' => 'etc_crystal_ball_red_i00',
    'name' => 'Nebulite Orb',
    'additionalname' => NULL,
    'description' => 'It is made by cutting Nebulite into a spherical shape. Take this to Magic Trader Cema in Hardins Academy.',
    'is_trade' => 1,
    'is_drop' => 1,
    'is_destruct' => 1,
    'crystal_type' => 'none',
    'consume_type' => 'consume_type_stackable',
  ],
  4365 => 
  [
    'item_id' => 4365,
    'icon' => 'etc_dragon_blood_i00',
    'name' => 'Ectoplasm Liqueur',
    'additionalname' => NULL,
    'description' => 'Exotic tasting liqueur made from ectoplasm. Very popular among connoisseurs.',
    'is_trade' => 1,
    'is_drop' => 1,
    'is_destruct' => 1,
    'crystal_type' => 'none',
    'consume_type' => 'consume_type_normal',
  ],
  4366 => 
  [
    'item_id' => 4366,
    'icon' => 'etc_trophy_i00',
    'name' => 'Princes Trophy',
    'additionalname' => NULL,
    'description' => 'The winning trophy that Prince Malcom won in a dance competition. You can sell it at a store or keep it as a souvenir.',
    'is_trade' => 1,
    'is_drop' => 1,
    'is_destruct' => 1,
    'crystal_type' => 'none',
    'consume_type' => 'consume_type_stackable',
  ],
  4367 => 
  [
    'item_id' => 4367,
    'icon' => 'etc_spellbook_red_i00',
    'name' => 'Princes Autobiography',
    'additionalname' => NULL,
    'description' => 'The autobiography of Prince Malcom that bears his hand-written signature. Sell it at a store.',
    'is_trade' => 1,
    'is_drop' => 1,
    'is_destruct' => 1,
    'crystal_type' => 'none',
    'consume_type' => 'consume_type_stackable',
  ],
  4368 => 
  [
    'item_id' => 4368,
    'icon' => 'etc_holy_statue_gold_i00',
    'name' => 'Princes Bust',
    'additionalname' => NULL,
    'description' => 'Statue of Prince Malcom made of pure gold. Although quite ugly, it will fetch a handsome price.',
    'is_trade' => 1,
    'is_drop' => 1,
    'is_destruct' => 1,
    'crystal_type' => 'none',
    'consume_type' => 'consume_type_stackable',
  ],
  4369 => 
  [
    'item_id' => 4369,
    'icon' => 'etc_kerchief_i00',
    'name' => 'Silk Handkerchief',
    'additionalname' => NULL,
    'description' => 'Beautiful and elaborate handkerchief decorated with a flower pattern and lace. Its design could attract the attention of princes and princesses.',
    'is_trade' => 1,
    'is_drop' => 1,
    'is_destruct' => 1,
    'crystal_type' => 'none',
    'consume_type' => 'consume_type_stackable',
  ],
  4370 => 
  [
    'item_id' => 4370,
    'icon' => 'etc_holy_grail_i01',
    'name' => 'Luxurious Goblet',
    'additionalname' => NULL,
    'description' => 'A luxurious goblet created at the times of the Elmoreden Empire.',
    'is_trade' => 1,
    'is_drop' => 1,
    'is_destruct' => 1,
    'crystal_type' => 'none',
    'consume_type' => 'consume_type_stackable',
  ],
  4371 => 
  [
    'item_id' => 4371,
    'icon' => 'etc_imperial_scepter_i02',
    'name' => 'Scepter of Darkness',
    'additionalname' => NULL,
    'description' => 'Staff that gives off dark M. Atk. On its handle, the words Great Demon King are engraved.',
    'is_trade' => 1,
    'is_drop' => 1,
    'is_destruct' => 1,
    'crystal_type' => 'none',
    'consume_type' => 'consume_type_stackable',
  ],
  4372 => 
  [
    'item_id' => 4372,
    'icon' => 'etc_dragons_blood_i02',
    'name' => 'Succubus Perfume',
    'additionalname' => NULL,
    'description' => 'Perfume used by Succubus noblewomen. Very strong fragrance, not popular among Elves and Humans.',
    'is_trade' => 1,
    'is_drop' => 1,
    'is_destruct' => 1,
    'crystal_type' => 'none',
    'consume_type' => 'consume_type_stackable',
  ],
  4373 => 
  [
    'item_id' => 4373,
    'icon' => 'etc_mirror_i00',
    'name' => 'Succubus Mirror',
    'additionalname' => NULL,
    'description' => 'Mirror used by Succubus noblewomen when they put on cosmetics. It is also said to be used occasionally by blood queens.',
    'is_trade' => 1,
    'is_drop' => 1,
    'is_destruct' => 1,
    'crystal_type' => 'none',
    'consume_type' => 'consume_type_stackable',
  ],
  4374 => 
  [
    'item_id' => 4374,
    'icon' => 'etc_heart_i00',
    'name' => 'Heart of Darkness',
    'additionalname' => NULL,
    'description' => 'Heart-shaped stone piece that gives off the aura of dark M. Atk. On its reverse, the words I love you Merkenis! are engraved.',
    'is_trade' => 1,
    'is_drop' => 1,
    'is_destruct' => 1,
    'crystal_type' => 'none',
    'consume_type' => 'consume_type_stackable',
  ],
  4375 => 
  [
    'item_id' => 4375,
    'icon' => 'etc_totem_red_i00',
    'name' => 'Royal Orc Totem',
    'additionalname' => NULL,
    'description' => 'Totem made by carving out a whole lump of red granite.',
    'is_trade' => 1,
    'is_drop' => 1,
    'is_destruct' => 1,
    'crystal_type' => 'none',
    'consume_type' => 'consume_type_stackable',
  ],
  4376 => 
  [
    'item_id' => 4376,
    'icon' => 'etc_crystal_ball_silver_i00',
    'name' => 'Pearl Bead',
    'additionalname' => NULL,
    'description' => 'Walnut sized bead that is smeared with dirt. Perhaps, it is a pearl.',
    'is_trade' => 1,
    'is_drop' => 1,
    'is_destruct' => 1,
    'crystal_type' => 'none',
    'consume_type' => 'consume_type_stackable',
  ],
  4377 => 
  [
    'item_id' => 4377,
    'icon' => 'etc_horn_i00',
    'name' => 'Boars Tusk',
    'additionalname' => NULL,
    'description' => 'The tusk of a boar that looks somewhat similar to the ivory of an elephant.',
    'is_trade' => 1,
    'is_drop' => 1,
    'is_destruct' => 1,
    'crystal_type' => 'none',
    'consume_type' => 'consume_type_stackable',
  ],
  4378 => 
  [
    'item_id' => 4378,
    'icon' => 'etc_seed_yellow_i00',
    'name' => 'Sweet Potato',
    'additionalname' => NULL,
    'description' => 'A large sweet potato that has just been plucked out of soil. Roast it to make a delicious treat.',
    'is_trade' => 1,
    'is_drop' => 1,
    'is_destruct' => 1,
    'crystal_type' => 'none',
    'consume_type' => 'consume_type_stackable',
  ],
  4379 => 
  [
    'item_id' => 4379,
    'icon' => 'etc_fang_ivory_i00',
    'name' => 'Beasts Claws',
    'additionalname' => NULL,
    'description' => 'White lions sharp claws. It is rumored that it is being traded among collectors at a high price.',
    'is_trade' => 1,
    'is_drop' => 1,
    'is_destruct' => 1,
    'crystal_type' => 'none',
    'consume_type' => 'consume_type_stackable',
  ],
  4380 => 
  [
    'item_id' => 4380,
    'icon' => 'etc_metallic_fiber_i00',
    'name' => 'Beasts Mane',
    'additionalname' => NULL,
    'description' => 'White lions luxuriant mane. It is rumored to be sold at a high price among collectors.',
    'is_trade' => 1,
    'is_drop' => 1,
    'is_destruct' => 1,
    'crystal_type' => 'none',
    'consume_type' => 'consume_type_stackable',
  ],
  4381 => 
  [
    'item_id' => 4381,
    'icon' => 'etc_ginseng_red_i00',
    'name' => 'Ginseng Root',
    'additionalname' => NULL,
    'description' => 'Rare medicine imported from the Orient.',
    'is_trade' => 1,
    'is_drop' => 1,
    'is_destruct' => 1,
    'crystal_type' => 'none',
    'consume_type' => 'consume_type_stackable',
  ],
  4382 => 
  [
    'item_id' => 4382,
    'icon' => 'etc_oil_pot_white_i00',
    'name' => 'Honey Jar',
    'additionalname' => NULL,
    'description' => 'Jar containing sweet honey.',
    'is_trade' => 1,
    'is_drop' => 1,
    'is_destruct' => 1,
    'crystal_type' => 'none',
    'consume_type' => 'consume_type_stackable',
  ],
  4383 => 
  [
    'item_id' => 4383,
    'icon' => 'etc_bodypart_liver_i00',
    'name' => 'Bears Gall',
    'additionalname' => NULL,
    'description' => 'The gall of a bear that is known to be highly effective in promoting ones health and well-being as well as having mysterious healing properties.',
    'is_trade' => 1,
    'is_drop' => 1,
    'is_destruct' => 1,
    'crystal_type' => 'none',
    'consume_type' => 'consume_type_stackable',
  ],
  4384 => 
  [
    'item_id' => 4384,
    'icon' => 'etc_fish_seawater_i01',
    'name' => 'Fresh Salmon',
    'additionalname' => NULL,
    'description' => 'Fresh salmon that seems to have been just caught from a river.',
    'is_trade' => 1,
    'is_drop' => 1,
    'is_destruct' => 1,
    'crystal_type' => 'none',
    'consume_type' => 'consume_type_stackable',
  ],
  4385 => 
  [
    'item_id' => 4385,
    'icon' => 'etc_meat_i00',
    'name' => 'Sushi Riceball',
    'additionalname' => NULL,
    'description' => 'The Schuttgart type sushi rice ball. The delicious seasoning of well minced meat gets absorbed into a the rice and produces a wonderful taste.',
    'is_trade' => 1,
    'is_drop' => 1,
    'is_destruct' => 1,
    'crystal_type' => 'none',
    'consume_type' => 'consume_type_stackable',
  ],
  4386 => 
  [
    'item_id' => 4386,
    'icon' => 'etc_powder_red_i00',
    'name' => 'Avellan Spice',
    'additionalname' => NULL,
    'description' => 'Exotic spice that has been imported from Avella of the Orient.',
    'is_trade' => 1,
    'is_drop' => 1,
    'is_destruct' => 1,
    'crystal_type' => 'none',
    'consume_type' => 'consume_type_stackable',
  ],
  4387 => 
  [
    'item_id' => 4387,
    'icon' => 'etc_herb_green_i00',
    'name' => 'Lucky Rabbit Weed',
    'additionalname' => NULL,
    'description' => 'Rabbit weed that is supposed to bring luck. It is the favorite food of rabbits and elpys.',
    'is_trade' => 1,
    'is_drop' => 1,
    'is_destruct' => 1,
    'crystal_type' => 'none',
    'consume_type' => 'consume_type_stackable',
  ],
  4388 => 
  [
    'item_id' => 4388,
    'icon' => 'etc_paper_blue_i00',
    'name' => 'Malcoms Check',
    'additionalname' => NULL,
    'description' => 'Check of tremendous face value signed by Prince Malcom. It can be cashed at a warehouse in Town of Giran.',
    'is_trade' => 1,
    'is_drop' => 1,
    'is_destruct' => 1,
    'crystal_type' => 'none',
    'consume_type' => 'consume_type_stackable',
  ],
  4389 => 
  [
    'item_id' => 4389,
    'icon' => 'etc_old_key_i03',
    'name' => 'Deposit Box Key',
    'additionalname' => NULL,
    'description' => 'Key for a private deposit box located in a warehouse in Town of Giran.',
    'is_trade' => 1,
    'is_drop' => 1,
    'is_destruct' => 1,
    'crystal_type' => 'none',
    'consume_type' => 'consume_type_stackable',
  ],
  4390 => 
  [
    'item_id' => 4390,
    'icon' => 'etc_royal_seal_of_lord_i04',
    'name' => 'Dwarven Royal Seal',
    'additionalname' => NULL,
    'description' => 'Royal seal made of carved jade. It is engraved with the seal of the Dwarven royal family.',
    'is_trade' => 1,
    'is_drop' => 1,
    'is_destruct' => 1,
    'crystal_type' => 'none',
    'consume_type' => 'consume_type_stackable',
  ],
  4391 => 
  [
    'item_id' => 4391,
    'icon' => 'etc_ancient_crown_i02',
    'name' => 'Dwarven Royal Crown',
    'additionalname' => NULL,
    'description' => 'Kings crown made of gold. It is engraved with the seal of the Dwarven royal family.',
    'is_trade' => 1,
    'is_drop' => 1,
    'is_destruct' => 1,
    'crystal_type' => 'none',
    'consume_type' => 'consume_type_stackable',
  ],
  4392 => 
  [
    'item_id' => 4392,
    'icon' => 'etc_spellbook_blue_i00',
    'name' => 'Dwarven Dance Manual',
    'additionalname' => NULL,
    'description' => 'Dance manual that details ballroom dancing techniques. This book will make you a dancing hero!',
    'is_trade' => 1,
    'is_drop' => 1,
    'is_destruct' => 1,
    'crystal_type' => 'none',
    'consume_type' => 'consume_type_stackable',
  ],
  4393 => 
  [
    'item_id' => 4393,
    'icon' => 'etc_calculator_i00',
    'name' => 'Calculator',
    'additionalname' => NULL,
    'description' => 'Allows one to perform a simple calculation.',
    'is_trade' => 1,
    'is_drop' => 1,
    'is_destruct' => 1,
    'crystal_type' => 'none',
    'consume_type' => 'consume_type_normal',
  ],
  4394 => 
  [
    'item_id' => 4394,
    'icon' => 'etc_flower_i00',
    'name' => 'Hanellins White Flower',
    'additionalname' => NULL,
    'description' => 'Mark of Hanellin. Along with your companions each carrying a red flower and yellow flower respectively, go to Town of Aden to see her.',
    'is_trade' => 1,
    'is_drop' => 0,
    'is_destruct' => 0,
    'crystal_type' => 'none',
    'consume_type' => 'consume_type_normal',
  ],
  4395 => 
  [
    'item_id' => 4395,
    'icon' => 'etc_flower_i01',
    'name' => 'Hanellins Red Flower',
    'additionalname' => NULL,
    'description' => 'Mark of Hanellin. Along with your companions each carrying a white flower and yellow flower respectively, go to Town of Aden to see her.',
    'is_trade' => 1,
    'is_drop' => 0,
    'is_destruct' => 0,
    'crystal_type' => 'none',
    'consume_type' => 'consume_type_normal',
  ],
  4396 => 
  [
    'item_id' => 4396,
    'icon' => 'etc_flower_i02',
    'name' => 'Hanellins Yellow Flower',
    'additionalname' => NULL,
    'description' => 'Mark of Hanellin. Along with your companions each carrying a white flower and red flower respectively, go to Town of Aden to see her.',
    'is_trade' => 1,
    'is_drop' => 0,
    'is_destruct' => 0,
    'crystal_type' => 'none',
    'consume_type' => 'consume_type_normal',
  ],
  4397 => 
  [
    'item_id' => 4397,
    'icon' => 'etc_spellbook_gray_i00',
    'name' => 'Book of Saint',
    'additionalname' => NULL,
    'description' => 'The book of Saint Solina. Take it along with the blood of a Saint and the bough of a Saint to Magister Hanellin.',
    'is_trade' => 1,
    'is_drop' => 0,
    'is_destruct' => 0,
    'crystal_type' => 'none',
    'consume_type' => 'consume_type_normal',
  ],
  4398 => 
  [
    'item_id' => 4398,
    'icon' => 'etc_dragons_blood_i00',
    'name' => 'Blood of Saint',
    'additionalname' => NULL,
    'description' => 'The blood of Saint Solina, hardened into a dark-colored substance contained in a glass bottle. Take it, along with the Book of Saint and the Bough of Saint to Magister Hanellin.',
    'is_trade' => 1,
    'is_drop' => 0,
    'is_destruct' => 0,
    'crystal_type' => 'none',
    'consume_type' => 'consume_type_normal',
  ],
  4399 => 
  [
    'item_id' => 4399,
    'icon' => 'etc_branch_gold_i00',
    'name' => 'Bough of Saint',
    'additionalname' => NULL,
    'description' => 'The Scepter of Saint Solina. It appears to be just a dead dry tree branch. Take it along with the book of a Saint and the blood of a Saint and take it to Magister Hanellin.',
    'is_trade' => 1,
    'is_drop' => 0,
    'is_destruct' => 0,
    'crystal_type' => 'none',
    'consume_type' => 'consume_type_normal',
  ],
];