<?php return [
  45900 => 
  [
    'item_id' => 45900,
    'icon' => 'egg_white',
    'name' => 'Kokkos Egg',
    'additionalname' => NULL,
    'description' => 'Kokkos egg. Double-click to find out what is inside. ',
    'is_trade' => 0,
    'is_drop' => 0,
    'is_destruct' => 1,
    'crystal_type' => 'none',
    'consume_type' => 'consume_type_stackable',
  ],
  45901 => 
  [
    'item_id' => 45901,
    'icon' => 'egg_twinkle',
    'name' => 'Kokkos Shiny Egg',
    'additionalname' => NULL,
    'description' => 'Kokkos shiny egg imbued with Maphs gratitude. Double-click to find out what is inside.  Note! An item obtained from the egg cannot be shared on account.',
    'is_trade' => 0,
    'is_drop' => 0,
    'is_destruct' => 1,
    'crystal_type' => 'none',
    'consume_type' => 'consume_type_normal',
  ],
  45902 => 
  [
    'item_id' => 45902,
    'icon' => 'egg_gold',
    'name' => 'Kokkos Golden Egg',
    'additionalname' => NULL,
    'description' => 'Kokkos golden egg imbued with Maphs gratitude. Double-click to find out what is inside.  Note! An item obtained from the egg cannot be shared on account.',
    'is_trade' => 0,
    'is_drop' => 0,
    'is_destruct' => 1,
    'crystal_type' => 'none',
    'consume_type' => 'consume_type_normal',
  ],
  45903 => 
  [
    'item_id' => 45903,
    'icon' => 'fairy_encounter_letter',
    'name' => 'Apocalypse Weapon Pack Coupon',
    'additionalname' => NULL,
    'description' => 'Take it to Maphrs agent Yuna to get a box containing an Apocalypse weapon. ',
    'is_trade' => 0,
    'is_drop' => 0,
    'is_destruct' => 1,
    'crystal_type' => 'none',
    'consume_type' => 'consume_type_stackable',
  ],
  45904 => 
  [
    'item_id' => 45904,
    'icon' => 'r1_shirt_i01',
    'name' => 'Pippis Shirt',
    'additionalname' => NULL,
    'description' => 'Speed +7, STR +1, INT +1.',
    'is_trade' => 0,
    'is_drop' => 0,
    'is_destruct' => 1,
    'crystal_type' => 'none',
    'consume_type' => 'consume_type_normal',
  ],
  45905 => 
  [
    'item_id' => 45905,
    'icon' => 'r1_shirt_i01',
    'name' => 'Kokkos Shirt',
    'additionalname' => NULL,
    'description' => 'Speed +7, STR +1, INT +1, CON +1, MEN +1.',
    'is_trade' => 0,
    'is_drop' => 0,
    'is_destruct' => 1,
    'crystal_type' => 'none',
    'consume_type' => 'consume_type_normal',
  ],
  45906 => 
  [
    'item_id' => 45906,
    'icon' => 'belt_i03',
    'name' => 'Pippis Belt',
    'additionalname' => NULL,
    'description' => 'Weight limit +12,800, inventory slots +12.',
    'is_trade' => 0,
    'is_drop' => 0,
    'is_destruct' => 1,
    'crystal_type' => 'none',
    'consume_type' => 'consume_type_normal',
  ],
  45907 => 
  [
    'item_id' => 45907,
    'icon' => 'belt_i03',
    'name' => 'Kokkos Belt',
    'additionalname' => NULL,
    'description' => 'Weight limit +12,800, inventory slots +18.',
    'is_trade' => 0,
    'is_drop' => 0,
    'is_destruct' => 1,
    'crystal_type' => 'none',
    'consume_type' => 'consume_type_normal',
  ],
  45908 => 
  [
    'item_id' => 45908,
    'icon' => 'ev_charge_box',
    'name' => 'Apocalypse Shaper Pack',
    'additionalname' => NULL,
    'description' => 'Double-click to obtain Apocalypse Shaper - Focus enchanted to +3/ +4/ +6/ +9/ +11.',
    'is_trade' => 0,
    'is_drop' => 0,
    'is_destruct' => 1,
    'crystal_type' => 'none',
    'consume_type' => 'consume_type_normal',
  ],
  45909 => 
  [
    'item_id' => 45909,
    'icon' => 'ev_charge_box',
    'name' => 'Apocalypse Cutter Pack',
    'additionalname' => NULL,
    'description' => 'Double-click to obtain Apocalypse Cutter - Focus enchanted to +3/ +4/ +6/ +9/ +11.',
    'is_trade' => 0,
    'is_drop' => 0,
    'is_destruct' => 1,
    'crystal_type' => 'none',
    'consume_type' => 'consume_type_normal',
  ],
  45910 => 
  [
    'item_id' => 45910,
    'icon' => 'ev_charge_box',
    'name' => 'Apocalypse Slasher Pack',
    'additionalname' => NULL,
    'description' => 'Double-click to obtain Apocalypse Slasher - Focus enchanted to +3/ +4/ +6/ +9/ +11.',
    'is_trade' => 0,
    'is_drop' => 0,
    'is_destruct' => 1,
    'crystal_type' => 'none',
    'consume_type' => 'consume_type_normal',
  ],
  45911 => 
  [
    'item_id' => 45911,
    'icon' => 'ev_charge_box',
    'name' => 'Apocalypse Avenger Pack',
    'additionalname' => NULL,
    'description' => 'Double-click to obtain Apocalypse Avenger - Focus enchanted to +3/ +4/ +6/ +9/ +11.',
    'is_trade' => 0,
    'is_drop' => 0,
    'is_destruct' => 1,
    'crystal_type' => 'none',
    'consume_type' => 'consume_type_normal',
  ],
  45912 => 
  [
    'item_id' => 45912,
    'icon' => 'ev_charge_box',
    'name' => 'Apocalypse Fighter Pack',
    'additionalname' => NULL,
    'description' => 'Double-click to obtain Apocalypse Fighter - Focus enchanted to +3/ +4/ +6/ +9/ +11.',
    'is_trade' => 0,
    'is_drop' => 0,
    'is_destruct' => 1,
    'crystal_type' => 'none',
    'consume_type' => 'consume_type_normal',
  ],
  45913 => 
  [
    'item_id' => 45913,
    'icon' => 'ev_charge_box',
    'name' => 'Apocalypse Stormer Pack',
    'additionalname' => NULL,
    'description' => 'Double-click to obtain Apocalypse Stormer - Damage Up enchanted to +3/ +4/ +6/ +9/ +11.',
    'is_trade' => 0,
    'is_drop' => 0,
    'is_destruct' => 1,
    'crystal_type' => 'none',
    'consume_type' => 'consume_type_normal',
  ],
  45914 => 
  [
    'item_id' => 45914,
    'icon' => 'ev_charge_box',
    'name' => 'Apocalypse Thrower Pack',
    'additionalname' => NULL,
    'description' => 'Double-click to obtain Apocalypse Thrower - Focus enchanted to +3/ +4/ +6/ +9/ +11.',
    'is_trade' => 0,
    'is_drop' => 0,
    'is_destruct' => 1,
    'crystal_type' => 'none',
    'consume_type' => 'consume_type_normal',
  ],
  45915 => 
  [
    'item_id' => 45915,
    'icon' => 'ev_charge_box',
    'name' => 'Apocalypse Guardian Pack',
    'additionalname' => NULL,
    'description' => 'Double-click to obtain Apocalypse Guardian - Focus enchanted to +3/ +4/ +6/ +9/ +11.',
    'is_trade' => 0,
    'is_drop' => 0,
    'is_destruct' => 1,
    'crystal_type' => 'none',
    'consume_type' => 'consume_type_normal',
  ],
  45916 => 
  [
    'item_id' => 45916,
    'icon' => 'ev_charge_box',
    'name' => 'Apocalypse Buster Pack',
    'additionalname' => NULL,
    'description' => 'Double-click to obtain Apocalypse Buster - Acumen enchanted to +3/ +4/ +6/ +9/ +11.',
    'is_trade' => 0,
    'is_drop' => 0,
    'is_destruct' => 1,
    'crystal_type' => 'none',
    'consume_type' => 'consume_type_normal',
  ],
  45917 => 
  [
    'item_id' => 45917,
    'icon' => 'ev_charge_box',
    'name' => 'Apocalypse Caster Pack',
    'additionalname' => NULL,
    'description' => 'Double-click to obtain Apocalypse Caster - Acumen enchanted to +3/ +4/ +6/ +9/ +11.',
    'is_trade' => 0,
    'is_drop' => 0,
    'is_destruct' => 1,
    'crystal_type' => 'none',
    'consume_type' => 'consume_type_normal',
  ],
  45918 => 
  [
    'item_id' => 45918,
    'icon' => 'ev_charge_box',
    'name' => 'Apocalypse Retributer Pack',
    'additionalname' => NULL,
    'description' => 'Double-click to get a +3/ 4/ 6/ 9/ 11 enchanted Apocalypse Retributer Acumen.',
    'is_trade' => 0,
    'is_drop' => 0,
    'is_destruct' => 1,
    'crystal_type' => 'none',
    'consume_type' => 'consume_type_normal',
  ],
  45919 => 
  [
    'item_id' => 45919,
    'icon' => 'ev_charge_box',
    'name' => 'Apocalypse Dual Swords Pack',
    'additionalname' => NULL,
    'description' => 'Double-click to obtain Apocalypse Dual Swords - Damage Up enchanted to +3/ +4/ +6/ +9/ +11.',
    'is_trade' => 0,
    'is_drop' => 0,
    'is_destruct' => 1,
    'crystal_type' => 'none',
    'consume_type' => 'consume_type_normal',
  ],
  45920 => 
  [
    'item_id' => 45920,
    'icon' => 'ev_charge_box',
    'name' => 'Apocalypse Dual Daggers Pack',
    'additionalname' => NULL,
    'description' => 'Double-click to obtain Apocalypse Dual Daggers - Focus enchanted to +3/ +4/ +6/ +9/ +11.',
    'is_trade' => 0,
    'is_drop' => 0,
    'is_destruct' => 1,
    'crystal_type' => 'none',
    'consume_type' => 'consume_type_normal',
  ],
  45921 => 
  [
    'item_id' => 45921,
    'icon' => 'ev_charge_box',
    'name' => 'Apocalypse Dual Blunt Weapon Pack',
    'additionalname' => NULL,
    'description' => 'Double-click to obtain Apocalypse Dual Blunt Weapons - Damage Up enchanted to +3/ +4/ +6/ +9/ +11.',
    'is_trade' => 0,
    'is_drop' => 0,
    'is_destruct' => 1,
    'crystal_type' => 'none',
    'consume_type' => 'consume_type_normal',
  ],
  45922 => 
  [
    'item_id' => 45922,
    'icon' => 'giant_book_i02',
    'name' => 'Spellbook: Dignity of the Exalted',
    'additionalname' => 'Lv. 1 ',
    'description' => 'Required for learning Dignity of the Exalted Lv. 1. Only for the main class.',
    'is_trade' => 0,
    'is_drop' => 0,
    'is_destruct' => 1,
    'crystal_type' => 'crystal_free',
    'consume_type' => 'consume_type_normal',
  ],
  45923 => 
  [
    'item_id' => 45923,
    'icon' => 'giant_book_i02',
    'name' => 'Spellbook: Dignity of the Exalted',
    'additionalname' => 'Lv. 2',
    'description' => 'Required for learning Dignity of the Exalted Lv. 2. Only for the main class.',
    'is_trade' => 0,
    'is_drop' => 0,
    'is_destruct' => 1,
    'crystal_type' => 'crystal_free',
    'consume_type' => 'consume_type_normal',
  ],
  45924 => 
  [
    'item_id' => 45924,
    'icon' => 'giant_book_i02',
    'name' => 'Spellbook: Dignity of the Exalted',
    'additionalname' => 'Lv. 3',
    'description' => 'Required for learning Dignity of the Exalted Lv. 3. Only for the main class.',
    'is_trade' => 0,
    'is_drop' => 0,
    'is_destruct' => 1,
    'crystal_type' => 'crystal_free',
    'consume_type' => 'consume_type_normal',
  ],
  45925 => 
  [
    'item_id' => 45925,
    'icon' => 'giant_book_i00',
    'name' => 'Spellbook: Belief of the Exalted',
    'additionalname' => NULL,
    'description' => 'Required for learning the Belief of the Exalted skill. Only for the main class.',
    'is_trade' => 0,
    'is_drop' => 0,
    'is_destruct' => 1,
    'crystal_type' => 'crystal_free',
    'consume_type' => 'consume_type_normal',
  ],
  45926 => 
  [
    'item_id' => 45926,
    'icon' => 'giant_book_i00',
    'name' => 'Spellbook: Blessing of the Exalted',
    'additionalname' => NULL,
    'description' => 'Required for learning the Belief of the Exalted skill. Only for the main class.',
    'is_trade' => 0,
    'is_drop' => 0,
    'is_destruct' => 1,
    'crystal_type' => 'crystal_free',
    'consume_type' => 'consume_type_normal',
  ],
  45927 => 
  [
    'item_id' => 45927,
    'icon' => 'giant_book_i01',
    'name' => 'Spellbook: Summon Battle Potion',
    'additionalname' => NULL,
    'description' => 'Required for learning the Summon Battle Potion skill. Only for the main class.',
    'is_trade' => 0,
    'is_drop' => 0,
    'is_destruct' => 1,
    'crystal_type' => 'crystal_free',
    'consume_type' => 'consume_type_normal',
  ],
  45928 => 
  [
    'item_id' => 45928,
    'icon' => 'giant_book_i00',
    'name' => 'Spellbook: Favor of the Exalted',
    'additionalname' => 'Lv. 1 ',
    'description' => 'Required for learning Favor of the Exalted Lv. 1. Only for the main class.',
    'is_trade' => 0,
    'is_drop' => 0,
    'is_destruct' => 1,
    'crystal_type' => 'crystal_free',
    'consume_type' => 'consume_type_normal',
  ],
  45929 => 
  [
    'item_id' => 45929,
    'icon' => 'renewal_mineral_46_i00',
    'name' => 'Augmenting Stone: Weapon',
    'additionalname' => NULL,
    'description' => 'A rare mineral solidified by shock from physical and magical strikes and dimensional abnormalities. Required for augmenting weapons. The higher the Augmenting Stones level, the higher the augmentation value. Double-click on the item or speak to a blacksmith to augment what you need.',
    'is_trade' => 1,
    'is_drop' => 1,
    'is_destruct' => 1,
    'crystal_type' => 'none',
    'consume_type' => 'consume_type_stackable',
  ],
  45930 => 
  [
    'item_id' => 45930,
    'icon' => 'renewal_mineral_r_i00',
    'name' => 'Mid-grade Augmenting Stone: Weapon',
    'additionalname' => NULL,
    'description' => 'A rare mineral solidified by shock from physical and magical strikes and dimensional abnormalities. Required for augmenting weapons. The higher the Augmenting Stones level, the higher the augmentation value. Double-click on the item or speak to a blacksmith to augment what you need.',
    'is_trade' => 1,
    'is_drop' => 1,
    'is_destruct' => 1,
    'crystal_type' => 'none',
    'consume_type' => 'consume_type_stackable',
  ],
  45931 => 
  [
    'item_id' => 45931,
    'icon' => 'renewal_mineral_r95_i00',
    'name' => 'High-grade Augmenting Stone: Weapon',
    'additionalname' => NULL,
    'description' => 'A rare mineral solidified by shock from physical and magical strikes and dimensional abnormalities. Required for augmenting weapons. The higher the Augmenting Stones level, the higher the augmentation value. Double-click on the item or speak to a blacksmith to augment what you need.',
    'is_trade' => 1,
    'is_drop' => 1,
    'is_destruct' => 1,
    'crystal_type' => 'none',
    'consume_type' => 'consume_type_stackable',
  ],
  45932 => 
  [
    'item_id' => 45932,
    'icon' => 'renewal_mineral_r99_i00',
    'name' => 'Top-grade Augmenting Stone: Weapon',
    'additionalname' => NULL,
    'description' => 'A rare mineral solidified by shock from physical and magical strikes and dimensional abnormalities. Required for augmenting weapons. The higher the Augmenting Stones level, the higher the augmentation value. Double-click on the item or speak to a blacksmith to augment what you need.',
    'is_trade' => 1,
    'is_drop' => 1,
    'is_destruct' => 1,
    'crystal_type' => 'none',
    'consume_type' => 'consume_type_stackable',
  ],
  45933 => 
  [
    'item_id' => 45933,
    'icon' => 'renewal_mineral_46',
    'name' => 'Spirit Stone: Accessory',
    'additionalname' => NULL,
    'description' => 'A rare mineral solidified by shock from physical and magical strikes and dimensional abnormalities. Required for augmenting accessories. The higher the Spirit Stones level, the higher the augmentation value.',
    'is_trade' => 1,
    'is_drop' => 1,
    'is_destruct' => 1,
    'crystal_type' => 'none',
    'consume_type' => 'consume_type_stackable',
  ],
  45934 => 
  [
    'item_id' => 45934,
    'icon' => 'renewal_mineral_r',
    'name' => 'Intermediate Accessory Spirit Stone',
    'additionalname' => NULL,
    'description' => 'A rare mineral solidified by shock from physical and magical strikes and dimensional abnormalities. Required for augmenting accessories. The higher the Spirit Stones level, the higher the augmentation value.',
    'is_trade' => 1,
    'is_drop' => 1,
    'is_destruct' => 1,
    'crystal_type' => 'none',
    'consume_type' => 'consume_type_stackable',
  ],
  45935 => 
  [
    'item_id' => 45935,
    'icon' => 'renewal_mineral_r95',
    'name' => 'Advanced Accessory Spirit Stone',
    'additionalname' => NULL,
    'description' => 'Ordinary mineral that has been petrified by a creatures physical or magical damage and dimensional anomalies. Key component used in weapon Augmentation, and the higher the level of the Spirit Stone, the higher the augmentation option.',
    'is_trade' => 1,
    'is_drop' => 1,
    'is_destruct' => 1,
    'crystal_type' => 'none',
    'consume_type' => 'consume_type_stackable',
  ],
  45936 => 
  [
    'item_id' => 45936,
    'icon' => 'renewal_mineral_r99',
    'name' => 'Top-grade Accessory Spirit Stone',
    'additionalname' => NULL,
    'description' => 'Ordinary mineral that has been petrified by a creatures physical or magical damage and dimensional anomalies. Key component used in weapon Augmentation, and the higher the level of the Spirit Stone, the higher the augmentation option.',
    'is_trade' => 1,
    'is_drop' => 1,
    'is_destruct' => 1,
    'crystal_type' => 'none',
    'consume_type' => 'consume_type_stackable',
  ],
  45937 => 
  [
    'item_id' => 45937,
    'icon' => 'renewal_mineral_hairacc',
    'name' => 'Spirit Stone: Head Accessory',
    'additionalname' => NULL,
    'description' => 'No longer used. Can be sold in a store for adena.',
    'is_trade' => 1,
    'is_drop' => 1,
    'is_destruct' => 1,
    'crystal_type' => 'none',
    'consume_type' => 'consume_type_stackable',
  ],
  45938 => 
  [
    'item_id' => 45938,
    'icon' => 'etc_gold_knight_i00',
    'name' => 'Dimensional Coin',
    'additionalname' => NULL,
    'description' => 'Receive various rewards through Merlot.',
    'is_trade' => 0,
    'is_drop' => 0,
    'is_destruct' => 0,
    'crystal_type' => 'none',
    'consume_type' => 'consume_type_stackable',
  ],
  45939 => 
  [
    'item_id' => 45939,
    'icon' => 'etc_gold_knight_i00',
    'name' => 'Dimensional Coin',
    'additionalname' => NULL,
    'description' => 'Receive various rewards through Merlot.',
    'is_trade' => 0,
    'is_drop' => 0,
    'is_destruct' => 0,
    'crystal_type' => 'none',
    'consume_type' => 'consume_type_stackable',
  ],
  45940 => 
  [
    'item_id' => 45940,
    'icon' => 'etc_gold_knight_i00',
    'name' => 'Dimensional Coin',
    'additionalname' => NULL,
    'description' => 'Receive various rewards through Merlot.',
    'is_trade' => 0,
    'is_drop' => 0,
    'is_destruct' => 0,
    'crystal_type' => 'none',
    'consume_type' => 'consume_type_stackable',
  ],
  45941 => 
  [
    'item_id' => 45941,
    'icon' => 'etc_gold_knight_i00',
    'name' => 'Dimensional Coin',
    'additionalname' => NULL,
    'description' => 'Receive various rewards through Merlot.',
    'is_trade' => 0,
    'is_drop' => 0,
    'is_destruct' => 0,
    'crystal_type' => 'none',
    'consume_type' => 'consume_type_stackable',
  ],
  45942 => 
  [
    'item_id' => 45942,
    'icon' => 'event_hero_treasure_box_i00',
    'name' => 'Atelia Energy Combination Box',
    'additionalname' => NULL,
    'description' => 'A mysterious box that combines Atelia Energy Crystals and creates 1~5 new Atelia Energy Crystals of Grade 2~4. If it fails, you might not get anything. ',
    'is_trade' => 0,
    'is_drop' => 0,
    'is_destruct' => 0,
    'crystal_type' => 'none',
    'consume_type' => 'consume_type_stackable',
  ],
  45943 => 
  [
    'item_id' => 45943,
    'icon' => 'event_hero_treasure_box_i00',
    'name' => 'Enhanced Atelia Energy Combination Box',
    'additionalname' => NULL,
    'description' => 'A mysterious box that combines Atelia Energy Crystals and creates 1~5 new Atelia Energy Crystals of Grade 1~2. If it fails, you might not get anything. ',
    'is_trade' => 0,
    'is_drop' => 0,
    'is_destruct' => 0,
    'crystal_type' => 'none',
    'consume_type' => 'consume_type_stackable',
  ],
  45944 => 
  [
    'item_id' => 45944,
    'icon' => 'new_user_box',
    'name' => 'Dimensional Heros Supply Box',
    'additionalname' => NULL,
    'description' => 'Double-click to obtain one of the following items: Top-grade Spirit Stone, Elcyum, Blessed Scroll: Enchant R-grade Weapon, Blessed Scroll: Enchant R-grade Armor, Bloody Weapon Enhancement Stone, Bloody Armor Enhancement Stone.',
    'is_trade' => 0,
    'is_drop' => 0,
    'is_destruct' => 0,
    'crystal_type' => 'none',
    'consume_type' => 'consume_type_stackable',
  ],
  45945 => 
  [
    'item_id' => 45945,
    'icon' => 'etc_potion_gold_i00',
    'name' => 'Combat Recovery Potion',
    'additionalname' => NULL,
    'description' => 'Recovers 3000 HP. If HP is full, recovers CP. No cooldown.',
    'is_trade' => 1,
    'is_drop' => 1,
    'is_destruct' => 1,
    'crystal_type' => 'crystal_free',
    'consume_type' => 'consume_type_stackable',
  ],
  45946 => 
  [
    'item_id' => 45946,
    'icon' => 'weapon_sirr_blade_i01',
    'name' => 'Capsule: Sirras Blade - Fortune',
    'additionalname' => 'Event',
    'description' => 'Double-click to get a +4 enchanted Sirras Blade of Fortune.',
    'is_trade' => 0,
    'is_drop' => 0,
    'is_destruct' => 1,
    'crystal_type' => 'crystal_free',
    'consume_type' => 'consume_type_normal',
  ],
  45947 => 
  [
    'item_id' => 45947,
    'icon' => 'weapon_sword_of_damascus_i01',
    'name' => 'Capsule: Damascus Sword of Fortune',
    'additionalname' => 'Event',
    'description' => 'Double-click to get a +4 enchanted Damascus Sword of Fortune.',
    'is_trade' => 0,
    'is_drop' => 0,
    'is_destruct' => 1,
    'crystal_type' => 'crystal_free',
    'consume_type' => 'consume_type_normal',
  ],
  45948 => 
  [
    'item_id' => 45948,
    'icon' => 'weapon_samurai_longsword_i01',
    'name' => 'Capsule: Samurai Long Sword - Fortune',
    'additionalname' => 'Event',
    'description' => 'Double-click to obtain Samurai Long Sword enchanted to +4.',
    'is_trade' => 0,
    'is_drop' => 0,
    'is_destruct' => 1,
    'crystal_type' => 'crystal_free',
    'consume_type' => 'consume_type_normal',
  ],
  45949 => 
  [
    'item_id' => 45949,
    'icon' => 'weapon_dynasty_blade_i01',
    'name' => 'Capsule: Dynasty Sword of Fortune',
    'additionalname' => 'Event',
    'description' => 'Double-click to get a +4 enchanted Dynasty Sword of Fortune.',
    'is_trade' => 0,
    'is_drop' => 0,
    'is_destruct' => 1,
    'crystal_type' => 'crystal_free',
    'consume_type' => 'consume_type_normal',
  ],
  45950 => 
  [
    'item_id' => 45950,
    'icon' => 'weapon_dual_sword_i00',
    'name' => 'Capsule: Tallum Blade*Damascus Sword - Fortune',
    'additionalname' => 'Event',
    'description' => 'Double-click to obtain Tallum Blade*Damascus Sword enchanted to +4.',
    'is_trade' => 0,
    'is_drop' => 0,
    'is_destruct' => 1,
    'crystal_type' => 'crystal_free',
    'consume_type' => 'consume_type_normal',
  ],
  45951 => 
  [
    'item_id' => 45951,
    'icon' => 'weapon_dual_sword_i00',
    'name' => 'Capsule: Samurai Long Sword*Samurai Long Sword of Fortune',
    'additionalname' => 'Event',
    'description' => 'Double-click to get a +4 enchanted Samurai Long Sword*Samurai Long Sword of Fortune.',
    'is_trade' => 0,
    'is_drop' => 0,
    'is_destruct' => 1,
    'crystal_type' => 'crystal_free',
    'consume_type' => 'consume_type_normal',
  ],
  45952 => 
  [
    'item_id' => 45952,
    'icon' => 'weapon_dual_sword_i00',
    'name' => 'Capsule: Spirit Sword*Raid Sword of Fortune',
    'additionalname' => 'Event',
    'description' => 'Double-click to get a +4 enchanted Spirit Sword*Raid Sword of Fortune.',
    'is_trade' => 0,
    'is_drop' => 0,
    'is_destruct' => 1,
    'crystal_type' => 'crystal_free',
    'consume_type' => 'consume_type_normal',
  ],
  45953 => 
  [
    'item_id' => 45953,
    'icon' => 'weapon_dual_sword_i00',
    'name' => 'Capsule: Dynasty Dual Swords of Fortune',
    'additionalname' => 'Event',
    'description' => 'Double-click to obtain +4 Dynasty Dual Swords.',
    'is_trade' => 0,
    'is_drop' => 0,
    'is_destruct' => 1,
    'crystal_type' => 'crystal_free',
    'consume_type' => 'consume_type_normal',
  ],
  45954 => 
  [
    'item_id' => 45954,
    'icon' => 'weapon_tiphon_spear_i01',
    'name' => 'Capsule: Tiphons Spear - Fortune',
    'additionalname' => 'Event',
    'description' => 'Double-click to get a +4 enchanted Tiphons Spear of Fortune.',
    'is_trade' => 0,
    'is_drop' => 0,
    'is_destruct' => 1,
    'crystal_type' => 'crystal_free',
    'consume_type' => 'consume_type_normal',
  ],
  45955 => 
  [
    'item_id' => 45955,
    'icon' => 'weapon_lancia_i01',
    'name' => 'Capsule: Lance - Fortune',
    'additionalname' => 'Event',
    'description' => 'Double-click to get a +4 enchanted Lance of Fortune.',
    'is_trade' => 0,
    'is_drop' => 0,
    'is_destruct' => 1,
    'crystal_type' => 'crystal_free',
    'consume_type' => 'consume_type_normal',
  ],
  45956 => 
  [
    'item_id' => 45956,
    'icon' => 'weapon_orcish_poleaxe_i01',
    'name' => 'Capsule: Orcish Poleaxe - Fortune',
    'additionalname' => 'Event',
    'description' => 'Double-click to get a +4 enchanted Orcish Poleaxe of Fortune.',
    'is_trade' => 0,
    'is_drop' => 0,
    'is_destruct' => 1,
    'crystal_type' => 'crystal_free',
    'consume_type' => 'consume_type_normal',
  ],
  45957 => 
  [
    'item_id' => 45957,
    'icon' => 'weapon_dynasty_spear_i01',
    'name' => 'Capsule: Dynasty Halberd - Fortune',
    'additionalname' => 'Event',
    'description' => 'Double-click to get a +4 enchanted Dynasty Halberd of Fortune.',
    'is_trade' => 0,
    'is_drop' => 0,
    'is_destruct' => 1,
    'crystal_type' => 'crystal_free',
    'consume_type' => 'consume_type_normal',
  ],
  45958 => 
  [
    'item_id' => 45958,
    'icon' => 'weapon_barakiel_axe_i01',
    'name' => 'Capsule: Barakiels Axe of Fortune',
    'additionalname' => 'Event',
    'description' => 'Double-click to obtain Barakiels Axe enchanted to +4.',
    'is_trade' => 0,
    'is_drop' => 0,
    'is_destruct' => 1,
    'crystal_type' => 'crystal_free',
    'consume_type' => 'consume_type_normal',
  ],
  45959 => 
  [
    'item_id' => 45959,
    'icon' => 'weapon_art_of_battle_axe_i01',
    'name' => 'Capsule: Art of Battle Axe of Fortune',
    'additionalname' => 'Event',
    'description' => 'Double-click to get a +4 enchanted Art of Battle Axe of Fortune.',
    'is_trade' => 0,
    'is_drop' => 0,
    'is_destruct' => 1,
    'crystal_type' => 'crystal_free',
    'consume_type' => 'consume_type_normal',
  ],
  45960 => 
  [
    'item_id' => 45960,
    'icon' => 'weapon_yaksa_mace_i01',
    'name' => 'Capsule: Yaksa Mace - Fortune',
    'additionalname' => 'Event',
    'description' => 'Double-click to get a +4 enchanted Yaksa Mace of Fortune.',
    'is_trade' => 0,
    'is_drop' => 0,
    'is_destruct' => 1,
    'crystal_type' => 'crystal_free',
    'consume_type' => 'consume_type_normal',
  ],
  45961 => 
  [
    'item_id' => 45961,
    'icon' => 'weapon_dynasty_spear_i01',
    'name' => 'Capsule: Dynasty Cudgel of Fortune',
    'additionalname' => 'Event',
    'description' => 'Double-click to get a +4 enchanted Dynasty Cudgel of Fortune.',
    'is_trade' => 0,
    'is_drop' => 0,
    'is_destruct' => 1,
    'crystal_type' => 'crystal_free',
    'consume_type' => 'consume_type_normal',
  ],
  45962 => 
  [
    'item_id' => 45962,
    'icon' => 'weapon_sword_of_ipos_i01',
    'name' => 'Capsule: Sword of Ipos - Fortune',
    'additionalname' => 'Event',
    'description' => 'Double-click to get a +4 enchanted Sword of Ipos of Fortune.',
    'is_trade' => 0,
    'is_drop' => 0,
    'is_destruct' => 1,
    'crystal_type' => 'crystal_free',
    'consume_type' => 'consume_type_normal',
  ],
  45963 => 
  [
    'item_id' => 45963,
    'icon' => 'weapon_guardians_sword_i01',
    'name' => 'Capsule: Guardians Sword - Fortune',
    'additionalname' => 'Event',
    'description' => 'Double-click to obtain Guardians Sword enchanted to +4.',
    'is_trade' => 0,
    'is_drop' => 0,
    'is_destruct' => 1,
    'crystal_type' => 'crystal_free',
    'consume_type' => 'consume_type_normal',
  ],
  45964 => 
  [
    'item_id' => 45964,
    'icon' => 'weapon_berserker_blade_i01',
    'name' => 'Capsule: Berserker Blade - Fortune',
    'additionalname' => 'Event',
    'description' => 'Double-click to obtain Berserker Blade enchanted to +4.',
    'is_trade' => 0,
    'is_drop' => 0,
    'is_destruct' => 1,
    'crystal_type' => 'crystal_free',
    'consume_type' => 'consume_type_normal',
  ],
  45965 => 
  [
    'item_id' => 45965,
    'icon' => 'weapon_dynasty_twohand_sword_i01',
    'name' => 'Capsule: Dynasty Blade of Fortune',
    'additionalname' => 'Event',
    'description' => 'Double-click to get a +4 enchanted Dynasty Blade of Fortune.',
    'is_trade' => 0,
    'is_drop' => 0,
    'is_destruct' => 1,
    'crystal_type' => 'crystal_free',
    'consume_type' => 'consume_type_normal',
  ],
  45966 => 
  [
    'item_id' => 45966,
    'icon' => 'weapon_sobekk_hurricane_i01',
    'name' => 'Capsule: Sobekks Hurricane - Fortune',
    'additionalname' => 'Event',
    'description' => 'Double-click to get a +4 enchanted Sobekks Hurricane of Fortune.',
    'is_trade' => 0,
    'is_drop' => 0,
    'is_destruct' => 1,
    'crystal_type' => 'crystal_free',
    'consume_type' => 'consume_type_normal',
  ],
  45967 => 
  [
    'item_id' => 45967,
    'icon' => 'weapon_bellion_cestus_i01',
    'name' => 'Capsule: Bellion Cestus of Fortune',
    'additionalname' => 'Event',
    'description' => 'Double-click to get a +4 enchanted Bellion Cestus of Fortune.',
    'is_trade' => 0,
    'is_drop' => 0,
    'is_destruct' => 1,
    'crystal_type' => 'crystal_free',
    'consume_type' => 'consume_type_normal',
  ],
  45968 => 
  [
    'item_id' => 45968,
    'icon' => 'weapon_great_pata_i01',
    'name' => 'Capsule: Great Pata - Fortune',
    'additionalname' => 'Event',
    'description' => 'Double-click to get a +4 enchanted Great Pata of Fortune.',
    'is_trade' => 0,
    'is_drop' => 0,
    'is_destruct' => 1,
    'crystal_type' => 'crystal_free',
    'consume_type' => 'consume_type_normal',
  ],
  45969 => 
  [
    'item_id' => 45969,
    'icon' => 'weapon_dynasty_jamadhr_i01',
    'name' => 'Capsule: Dynasty Bagh-Nakh - Fortune',
    'additionalname' => 'Event',
    'description' => 'Double-click to get a +4 enchanted Dynasty Bagh-Nakh of Fortune.',
    'is_trade' => 0,
    'is_drop' => 0,
    'is_destruct' => 1,
    'crystal_type' => 'crystal_free',
    'consume_type' => 'consume_type_normal',
  ],
  45970 => 
  [
    'item_id' => 45970,
    'icon' => 'weapon_naga_storm_i01',
    'name' => 'Capsule: Nagas Storm of Fortune',
    'additionalname' => 'Event',
    'description' => 'Double-click to get a +4 enchanted Nagas Storm of Fortune.',
    'is_trade' => 0,
    'is_drop' => 0,
    'is_destruct' => 1,
    'crystal_type' => 'crystal_free',
    'consume_type' => 'consume_type_normal',
  ],
  45971 => 
  [
    'item_id' => 45971,
    'icon' => 'weapon_kris_i01',
    'name' => 'Capsule: Kris - Fortune',
    'additionalname' => 'Event',
    'description' => 'Double-click to get a +4 enchanted Kris of Fortune.',
    'is_trade' => 0,
    'is_drop' => 0,
    'is_destruct' => 1,
    'crystal_type' => 'crystal_free',
    'consume_type' => 'consume_type_normal',
  ],
  45972 => 
  [
    'item_id' => 45972,
    'icon' => 'weapon_dark_screamer_i01',
    'name' => 'Capsule: Dark Screamer - Fortune',
    'additionalname' => 'Event',
    'description' => 'Double-click to get a +4 enchanted Dark Screamer of Fortune.',
    'is_trade' => 0,
    'is_drop' => 0,
    'is_destruct' => 1,
    'crystal_type' => 'crystal_free',
    'consume_type' => 'consume_type_normal',
  ],
  45973 => 
  [
    'item_id' => 45973,
    'icon' => 'weapon_dynasty_dagger_i01',
    'name' => 'Capsule: Dynasty Knife of Fortune',
    'additionalname' => 'Event',
    'description' => 'Double-click to get a +4 enchanted Dynasty Knife of Fortune.',
    'is_trade' => 0,
    'is_drop' => 0,
    'is_destruct' => 1,
    'crystal_type' => 'crystal_free',
    'consume_type' => 'consume_type_normal',
  ],
  45974 => 
  [
    'item_id' => 45974,
    'icon' => 'weapon_shyid_bow_i01',
    'name' => 'Capsule: Shyeeds Bow - Fortune',
    'additionalname' => 'Event',
    'description' => 'Double-click to get a +4 enchanted Shyeeds Bow of Fortune.',
    'is_trade' => 0,
    'is_drop' => 0,
    'is_destruct' => 1,
    'crystal_type' => 'crystal_free',
    'consume_type' => 'consume_type_normal',
  ],
  45975 => 
  [
    'item_id' => 45975,
    'icon' => 'weapon_hazard_bow_i01',
    'name' => 'Capsule: Bow of Peril - Fortune',
    'additionalname' => 'Event',
    'description' => 'Double-click to obtain Bow of Peril enchanted to +4.',
    'is_trade' => 0,
    'is_drop' => 0,
    'is_destruct' => 1,
    'crystal_type' => 'crystal_free',
    'consume_type' => 'consume_type_normal',
  ],
  45976 => 
  [
    'item_id' => 45976,
    'icon' => 'weapon_eminence_bow_i01',
    'name' => 'Capsule: Eminence Bow - Fortune',
    'additionalname' => 'Event',
    'description' => 'Double-click to get a +4 enchanted Eminence Bow of Fortune.',
    'is_trade' => 0,
    'is_drop' => 0,
    'is_destruct' => 1,
    'crystal_type' => 'crystal_free',
    'consume_type' => 'consume_type_normal',
  ],
  45977 => 
  [
    'item_id' => 45977,
    'icon' => 'weapon_dynasty_bow_i01',
    'name' => 'Capsule: Dynasty Bow of Fortune',
    'additionalname' => 'Event',
    'description' => 'Double-click to get a +4 enchanted Dynasty Bow of Fortune.',
    'is_trade' => 0,
    'is_drop' => 0,
    'is_destruct' => 1,
    'crystal_type' => 'crystal_free',
    'consume_type' => 'consume_type_normal',
  ],
  45978 => 
  [
    'item_id' => 45978,
    'icon' => 'weapon_sword_of_miracle_i01',
    'name' => 'Capsule: Sword of Miracles - Fortune',
    'additionalname' => 'Event',
    'description' => 'Double-click to get a +4 enchanted Sword of Miracles of Fortune.',
    'is_trade' => 0,
    'is_drop' => 0,
    'is_destruct' => 1,
    'crystal_type' => 'crystal_free',
    'consume_type' => 'consume_type_normal',
  ],
  45979 => 
  [
    'item_id' => 45979,
    'icon' => 'weapon_tears_of_wizard_i01',
    'name' => 'Capsule: Wizards Tear - Fortune',
    'additionalname' => 'Event',
    'description' => 'Double-click to obtain Wizards Tear enchanted to +4.',
    'is_trade' => 0,
    'is_drop' => 0,
    'is_destruct' => 1,
    'crystal_type' => 'crystal_free',
    'consume_type' => 'consume_type_normal',
  ],
  45980 => 
  [
    'item_id' => 45980,
    'icon' => 'weapon_homunkuluss_sword_i01',
    'name' => 'Capsule: Homunkulus Sword - Fortune',
    'additionalname' => 'Event',
    'description' => 'Double-click to obtain Homunkulus Sword enchanted to +4.',
    'is_trade' => 0,
    'is_drop' => 0,
    'is_destruct' => 1,
    'crystal_type' => 'crystal_free',
    'consume_type' => 'consume_type_normal',
  ],
  45981 => 
  [
    'item_id' => 45981,
    'icon' => 'weapon_dynasty_magic_sword_i01',
    'name' => 'Capsule: Dynasty Phantom of Fortune',
    'additionalname' => 'Event',
    'description' => 'Double-click to get a +4 enchanted Dynasty Phantom of Fortune.',
    'is_trade' => 0,
    'is_drop' => 0,
    'is_destruct' => 1,
    'crystal_type' => 'crystal_free',
    'consume_type' => 'consume_type_normal',
  ],
  45982 => 
  [
    'item_id' => 45982,
    'icon' => 'weapon_death_bringer_i01',
    'name' => 'Capsule: Durendal - Fortune',
    'additionalname' => 'Event',
    'description' => 'Double-click to get a +4 enchanted Durendal of Fortune.',
    'is_trade' => 0,
    'is_drop' => 0,
    'is_destruct' => 1,
    'crystal_type' => 'crystal_free',
    'consume_type' => 'consume_type_normal',
  ],
  45983 => 
  [
    'item_id' => 45983,
    'icon' => 'weapon_dismantler_i01',
    'name' => 'Capsule: Dismantler of Fortune',
    'additionalname' => 'Event',
    'description' => 'Double-click to obtain Dismantler enchanted to +4.',
    'is_trade' => 0,
    'is_drop' => 0,
    'is_destruct' => 1,
    'crystal_type' => 'crystal_free',
    'consume_type' => 'consume_type_normal',
  ],
  45984 => 
  [
    'item_id' => 45984,
    'icon' => 'weapon_invincible_blade_i01',
    'name' => 'Capsule: Saber Tooth of Fortune',
    'additionalname' => 'Event',
    'description' => 'Double-click to get a +4 enchanted Saber Tooth of Fortune.',
    'is_trade' => 0,
    'is_drop' => 0,
    'is_destruct' => 1,
    'crystal_type' => 'crystal_free',
    'consume_type' => 'consume_type_normal',
  ],
  45985 => 
  [
    'item_id' => 45985,
    'icon' => 'weapon_dynasty_ancient_sword_i01',
    'name' => 'Capsule: Dynasty Ancient Sword of Fortune',
    'additionalname' => 'Event',
    'description' => 'Double-click to get a +4 enchanted Dynasty Ancient Sword of Fortune.',
    'is_trade' => 0,
    'is_drop' => 0,
    'is_destruct' => 1,
    'crystal_type' => 'crystal_free',
    'consume_type' => 'consume_type_normal',
  ],
  45986 => 
  [
    'item_id' => 45986,
    'icon' => 'weapon_greed_stinger_i01',
    'name' => 'Capsule: ?clair Bijou - Fortune',
    'additionalname' => 'Event',
    'description' => 'Double-click to get a +4 enchanted ?clair Bijou of Fortune.',
    'is_trade' => 0,
    'is_drop' => 0,
    'is_destruct' => 1,
    'crystal_type' => 'crystal_free',
    'consume_type' => 'consume_type_normal',
  ],
  45987 => 
  [
    'item_id' => 45987,
    'icon' => 'weapon_colichemarde_i01',
    'name' => 'Capsule: Colichemarde - Fortune',
    'additionalname' => 'Event',
    'description' => 'Double-click to get a +4 enchanted Colichemarde of Fortune.',
    'is_trade' => 0,
    'is_drop' => 0,
    'is_destruct' => 1,
    'crystal_type' => 'crystal_free',
    'consume_type' => 'consume_type_normal',
  ],
  45988 => 
  [
    'item_id' => 45988,
    'icon' => 'weapon_blink_slasher_i01',
    'name' => 'Capsule: Admirals Estoc - Fortune',
    'additionalname' => 'Event',
    'description' => 'Double-click to get a +4 enchanted Admirals Estoc of Fortune.',
    'is_trade' => 0,
    'is_drop' => 0,
    'is_destruct' => 1,
    'crystal_type' => 'crystal_free',
    'consume_type' => 'consume_type_normal',
  ],
  45989 => 
  [
    'item_id' => 45989,
    'icon' => 'weapon_dynasty_rapier_i01',
    'name' => 'Capsule: Dynasty Rapier of Fortune',
    'additionalname' => 'Event',
    'description' => 'Double-click to get a +4 enchanted Dynasty Rapier of Fortune.',
    'is_trade' => 0,
    'is_drop' => 0,
    'is_destruct' => 1,
    'crystal_type' => 'crystal_free',
    'consume_type' => 'consume_type_normal',
  ],
  45990 => 
  [
    'item_id' => 45990,
    'icon' => 'weapon_soul_shooter_i01',
    'name' => 'Capsule: Screaming Vengeance of Fortune',
    'additionalname' => 'Event',
    'description' => 'Double-click to get a +4 enchanted Screaming Vengeance of Fortune.',
    'is_trade' => 0,
    'is_drop' => 0,
    'is_destruct' => 1,
    'crystal_type' => 'crystal_free',
    'consume_type' => 'consume_type_normal',
  ],
  45991 => 
  [
    'item_id' => 45991,
    'icon' => 'weapon_hell_hound_i01',
    'name' => 'Capsule: Hell Hound of Fortune',
    'additionalname' => 'Event',
    'description' => 'Double-click to get a +4 enchanted Hell Hound of Fortune.',
    'is_trade' => 0,
    'is_drop' => 0,
    'is_destruct' => 1,
    'crystal_type' => 'crystal_free',
    'consume_type' => 'consume_type_normal',
  ],
  45992 => 
  [
    'item_id' => 45992,
    'icon' => 'weapon_taslam_i01',
    'name' => 'Capsule: Sharpshooter of Fortune',
    'additionalname' => 'Event',
    'description' => 'Double-click to get a +4 enchanted Sharpshooter of Fortune.',
    'is_trade' => 0,
    'is_drop' => 0,
    'is_destruct' => 1,
    'crystal_type' => 'crystal_free',
    'consume_type' => 'consume_type_normal',
  ],
  45993 => 
  [
    'item_id' => 45993,
    'icon' => 'weapon_dynasty_crossbow_i01',
    'name' => 'Capsule: Dynasty Crossbow of Fortune',
    'additionalname' => 'Event',
    'description' => 'Double-click to get a +4 enchanted Dynasty Crossbow of Fortune.',
    'is_trade' => 0,
    'is_drop' => 0,
    'is_destruct' => 1,
    'crystal_type' => 'crystal_free',
    'consume_type' => 'consume_type_normal',
  ],
  45994 => 
  [
    'item_id' => 45994,
    'icon' => 'weapon_phasian_i01',
    'name' => 'Capsule: Apocalypse Shaper - Focus',
    'additionalname' => 'Event',
    'description' => 'Double-click to obtain Apocalypse Shaper - Focus (30-day] enchanted to +6. ',
    'is_trade' => 0,
    'is_drop' => 0,
    'is_destruct' => 1,
    'crystal_type' => 'crystal_free',
    'consume_type' => 'consume_type_normal',
  ],
  45995 => 
  [
    'item_id' => 45995,
    'icon' => 'weapon_pasis_i01',
    'name' => 'Capsule: Apocalypse Cutter - Focus',
    'additionalname' => 'Event',
    'description' => 'Double-click to obtain Apocalypse Cutter - Focus (30-day] enchanted to +6. ',
    'is_trade' => 0,
    'is_drop' => 0,
    'is_destruct' => 1,
    'crystal_type' => 'crystal_free',
    'consume_type' => 'consume_type_normal',
  ],
  45996 => 
  [
    'item_id' => 45996,
    'icon' => 'weapon_volver_i01',
    'name' => 'Capsule: Apocalypse Slasher - Focus',
    'additionalname' => 'Event',
    'description' => 'Double-click to obtain Apocalypse Slasher - Focus (30-day] enchanted to +6. ',
    'is_trade' => 0,
    'is_drop' => 0,
    'is_destruct' => 1,
    'crystal_type' => 'crystal_free',
    'consume_type' => 'consume_type_normal',
  ],
  45997 => 
  [
    'item_id' => 45997,
    'icon' => 'weapon_r_dualsword_i21',
    'name' => 'Capsule: Apocalypse Dual Swords - Damage Up',
    'additionalname' => 'Event',
    'description' => 'Double-click to obtain Apocalypse Dual Swords - Damage Up (30-day] enchanted to +6. ',
    'is_trade' => 0,
    'is_drop' => 0,
    'is_destruct' => 1,
    'crystal_type' => 'crystal_free',
    'consume_type' => 'consume_type_normal',
  ],
  45998 => 
  [
    'item_id' => 45998,
    'icon' => 'weapon_r_dualdagger_i21',
    'name' => 'Capsule: Apocalypse Dual Daggers - Focus',
    'additionalname' => 'Event',
    'description' => 'Double-click to obtain Apocalypse Dual Daggers - Focus (30-day] enchanted to +6. ',
    'is_trade' => 0,
    'is_drop' => 0,
    'is_destruct' => 1,
    'crystal_type' => 'crystal_free',
    'consume_type' => 'consume_type_normal',
  ],
  45999 => 
  [
    'item_id' => 45999,
    'icon' => 'weapon_r_dualblunt_i21',
    'name' => 'Capsule: Apocalypse Dual Blunt Weapons - Damage Up',
    'additionalname' => 'Event',
    'description' => 'Double-click to obtain Apocalypse Dual Blunt Weapons - Damage Up (30-day] enchanted to +6. ',
    'is_trade' => 0,
    'is_drop' => 0,
    'is_destruct' => 1,
    'crystal_type' => 'crystal_free',
    'consume_type' => 'consume_type_normal',
  ],
];