<?php return [
  4600 => 
  [
    'item_id' => 4600,
    'icon' => 'etc_wit_hena_i02',
    'name' => 'Greater WIT Dye <WIT +2 MEN -2>',
    'additionalname' => NULL,
    'description' => 'Collect 10 units and take them to the Dye Merchant to get a symbol that boosts your abilities. Requirements: all mages after the 2nd class change. Can be used by Ertheia after the 1st Liberation. The effect remains after the 2nd Liberation.',
    'is_trade' => 1,
    'is_drop' => 1,
    'is_destruct' => 1,
    'crystal_type' => 'none',
    'consume_type' => 'consume_type_stackable',
  ],
  4601 => 
  [
    'item_id' => 4601,
    'icon' => 'etc_str_hena_i02',
    'name' => 'Greater STR Dye <STR +3 CON -3>',
    'additionalname' => NULL,
    'description' => 'Greater Dye of STR. Collect 10 units and take them to the Dye Merchant to get a symbol that boosts your abilities. Requirements: all classes after the 2nd class change. Can be used by Ertheia after the 1st Liberation. ',
    'is_trade' => 1,
    'is_drop' => 1,
    'is_destruct' => 1,
    'crystal_type' => 'none',
    'consume_type' => 'consume_type_stackable',
  ],
  4602 => 
  [
    'item_id' => 4602,
    'icon' => 'etc_str_hena_i02',
    'name' => 'Greater STR Dye <STR +3 DEX -3>',
    'additionalname' => NULL,
    'description' => 'Greater Dye of STR. Collect 10 units and take them to the Dye Merchant to get a symbol that boosts your abilities. Requirements: all classes after the 2nd class change. Can be used by Ertheia after the 1st Liberation. ',
    'is_trade' => 1,
    'is_drop' => 1,
    'is_destruct' => 1,
    'crystal_type' => 'none',
    'consume_type' => 'consume_type_stackable',
  ],
  4603 => 
  [
    'item_id' => 4603,
    'icon' => 'etc_con_hena_i02',
    'name' => 'Greater CON Dye <CON +3 STR -3>',
    'additionalname' => NULL,
    'description' => 'Greater Dye of CON. Collect 10 units and take them to the Dye Merchant to get a symbol that boosts your abilities. Requirements: all classes after the 2nd class change. Can be used by Ertheia after the 1st Liberation. ',
    'is_trade' => 1,
    'is_drop' => 1,
    'is_destruct' => 1,
    'crystal_type' => 'none',
    'consume_type' => 'consume_type_stackable',
  ],
  4604 => 
  [
    'item_id' => 4604,
    'icon' => 'etc_con_hena_i02',
    'name' => 'Greater CON Dye <CON +3 DEX -3>',
    'additionalname' => NULL,
    'description' => 'Greater Dye of CON. Collect 10 units and take them to the Dye Merchant to get a symbol that boosts your abilities. Requirements: all classes after the 2nd class change. Can be used by Ertheia after the 1st Liberation. ',
    'is_trade' => 1,
    'is_drop' => 1,
    'is_destruct' => 1,
    'crystal_type' => 'none',
    'consume_type' => 'consume_type_stackable',
  ],
  4605 => 
  [
    'item_id' => 4605,
    'icon' => 'etc_dex_hena_i02',
    'name' => 'Greater DEX Dye <DEX +3 STR -3>',
    'additionalname' => NULL,
    'description' => 'Greater Dye of DEX. Collect 10 units and take them to the Dye Merchant to get a symbol that boosts your abilities. Requirements: all classes after the 2nd class change. Can be used by Ertheia after the 1st Liberation. ',
    'is_trade' => 1,
    'is_drop' => 1,
    'is_destruct' => 1,
    'crystal_type' => 'none',
    'consume_type' => 'consume_type_stackable',
  ],
  4606 => 
  [
    'item_id' => 4606,
    'icon' => 'etc_dex_hena_i02',
    'name' => 'Greater DEX Dye <DEX +3 CON -3>',
    'additionalname' => NULL,
    'description' => 'Greater Dye of DEX. Collect 10 units and take them to the Dye Merchant to get a symbol that boosts your abilities. Requirements: all classes after the 2nd class change. Can be used by Ertheia after the 1st Liberation. ',
    'is_trade' => 1,
    'is_drop' => 1,
    'is_destruct' => 1,
    'crystal_type' => 'none',
    'consume_type' => 'consume_type_stackable',
  ],
  4607 => 
  [
    'item_id' => 4607,
    'icon' => 'etc_int_hena_i02',
    'name' => 'Greater INT Dye <INT +3 MEN -3>',
    'additionalname' => NULL,
    'description' => 'Collect 10 units and take them to the Dye Merchant to get a symbol that boosts your abilities. Requirements: non-healing mages after the 2nd class change. Can be used by Ertheia after the 1st Liberation. The effect remains after the 2nd Liberation.',
    'is_trade' => 1,
    'is_drop' => 1,
    'is_destruct' => 1,
    'crystal_type' => 'none',
    'consume_type' => 'consume_type_stackable',
  ],
  4608 => 
  [
    'item_id' => 4608,
    'icon' => 'etc_int_hena_i02',
    'name' => 'Greater INT Dye <INT +3 WIT -3>',
    'additionalname' => NULL,
    'description' => 'Collect 10 units and take them to the Dye Merchant to get a symbol that boosts your abilities. Requirements: warriors and non-healing mages after the 2nd class change. Can be used by Ertheia after the 1st Liberation. The effect remains after the 2nd Liberation.',
    'is_trade' => 1,
    'is_drop' => 1,
    'is_destruct' => 1,
    'crystal_type' => 'none',
    'consume_type' => 'consume_type_stackable',
  ],
  4609 => 
  [
    'item_id' => 4609,
    'icon' => 'etc_men_hena_i02',
    'name' => 'Greater MEN Dye <MEN +3 INT -3>',
    'additionalname' => NULL,
    'description' => 'Collect 10 units and take them to the Dye Merchant to get a symbol that boosts your abilities. Requirements: non-healing mages after the 2nd class change. Can be used by Ertheia after the 1st Liberation. The effect remains after the 2nd Liberation.',
    'is_trade' => 1,
    'is_drop' => 1,
    'is_destruct' => 1,
    'crystal_type' => 'none',
    'consume_type' => 'consume_type_stackable',
  ],
  4610 => 
  [
    'item_id' => 4610,
    'icon' => 'etc_men_hena_i02',
    'name' => 'Greater MEN Dye <MEN +3 WIT -3>',
    'additionalname' => NULL,
    'description' => 'Collect 10 units and take them to the Dye Merchant to get a symbol that boosts your abilities. Requirements: all mages after the 2nd class change. Can be used by Ertheia after the 1st Liberation. The effect remains after the 2nd Liberation.',
    'is_trade' => 1,
    'is_drop' => 1,
    'is_destruct' => 1,
    'crystal_type' => 'none',
    'consume_type' => 'consume_type_stackable',
  ],
  4611 => 
  [
    'item_id' => 4611,
    'icon' => 'etc_wit_hena_i02',
    'name' => 'Greater WIT Dye <WIT +3 INT -3>',
    'additionalname' => NULL,
    'description' => 'Collect 10 units and take them to the Dye Merchant to get a symbol that boosts your abilities. Requirements: warriors and non-healing mages after the 2nd class change. Can be used by Ertheia after the 1st Liberation. The effect remains after the 2nd Liberation.',
    'is_trade' => 1,
    'is_drop' => 1,
    'is_destruct' => 1,
    'crystal_type' => 'none',
    'consume_type' => 'consume_type_stackable',
  ],
  4612 => 
  [
    'item_id' => 4612,
    'icon' => 'etc_wit_hena_i02',
    'name' => 'Greater WIT Dye <WIT +3 MEN -3>',
    'additionalname' => NULL,
    'description' => 'Collect 10 units and take them to the Dye Merchant to get a symbol that boosts your abilities. Requirements: all mages after the 2nd class change. Can be used by Ertheia after the 1st Liberation. The effect remains after the 2nd Liberation.',
    'is_trade' => 1,
    'is_drop' => 1,
    'is_destruct' => 1,
    'crystal_type' => 'none',
    'consume_type' => 'consume_type_stackable',
  ],
  4613 => 
  [
    'item_id' => 4613,
    'icon' => 'etc_str_hena_i02',
    'name' => 'Greater STR Dye <STR +4 CON -4>',
    'additionalname' => NULL,
    'description' => 'Greater Dye of STR. Collect 10 units and take them to the Dye Merchant to get a symbol that boosts your abilities. Requirements: all classes after the 2nd class change. Can be used by Ertheia after the 1st Liberation. ',
    'is_trade' => 1,
    'is_drop' => 1,
    'is_destruct' => 1,
    'crystal_type' => 'none',
    'consume_type' => 'consume_type_stackable',
  ],
  4614 => 
  [
    'item_id' => 4614,
    'icon' => 'etc_str_hena_i02',
    'name' => 'Greater STR Dye <STR +4 DEX -4>',
    'additionalname' => NULL,
    'description' => 'Greater Dye of STR. Collect 10 units and take them to the Dye Merchant to get a symbol that boosts your abilities. Requirements: all classes after the 2nd class change. Can be used by Ertheia after the 1st Liberation. ',
    'is_trade' => 1,
    'is_drop' => 1,
    'is_destruct' => 1,
    'crystal_type' => 'none',
    'consume_type' => 'consume_type_stackable',
  ],
  4615 => 
  [
    'item_id' => 4615,
    'icon' => 'etc_con_hena_i02',
    'name' => 'Greater CON Dye <CON +4 STR -4>',
    'additionalname' => NULL,
    'description' => 'Greater Dye of CON. Collect 10 units and take them to the Dye Merchant to get a symbol that boosts your abilities. Requirements: all classes after the 2nd class change. Can be used by Ertheia after the 1st Liberation. ',
    'is_trade' => 1,
    'is_drop' => 1,
    'is_destruct' => 1,
    'crystal_type' => 'none',
    'consume_type' => 'consume_type_stackable',
  ],
  4616 => 
  [
    'item_id' => 4616,
    'icon' => 'etc_con_hena_i02',
    'name' => 'Greater CON Dye <CON +4 DEX -4>',
    'additionalname' => NULL,
    'description' => 'Greater Dye of CON. Collect 10 units and take them to the Dye Merchant to get a symbol that boosts your abilities. Requirements: all classes after the 2nd class change. Can be used by Ertheia after the 1st Liberation. ',
    'is_trade' => 1,
    'is_drop' => 1,
    'is_destruct' => 1,
    'crystal_type' => 'none',
    'consume_type' => 'consume_type_stackable',
  ],
  4617 => 
  [
    'item_id' => 4617,
    'icon' => 'etc_dex_hena_i02',
    'name' => 'Greater DEX Dye <DEX +4 STR -4>',
    'additionalname' => NULL,
    'description' => 'Greater Dye of DEX. Collect 10 units and take them to the Dye Merchant to get a symbol that boosts your abilities. Requirements: all classes after the 2nd class change. Can be used by Ertheia after the 1st Liberation. ',
    'is_trade' => 1,
    'is_drop' => 1,
    'is_destruct' => 1,
    'crystal_type' => 'none',
    'consume_type' => 'consume_type_stackable',
  ],
  4618 => 
  [
    'item_id' => 4618,
    'icon' => 'etc_dex_hena_i02',
    'name' => 'Greater DEX Dye <DEX +4 CON -4>',
    'additionalname' => NULL,
    'description' => 'Greater Dye of DEX. Collect 10 units and take them to the Dye Merchant to get a symbol that boosts your abilities. Requirements: all classes after the 2nd class change. Can be used by Ertheia after the 1st Liberation. ',
    'is_trade' => 1,
    'is_drop' => 1,
    'is_destruct' => 1,
    'crystal_type' => 'none',
    'consume_type' => 'consume_type_stackable',
  ],
  4619 => 
  [
    'item_id' => 4619,
    'icon' => 'etc_int_hena_i02',
    'name' => 'Greater INT Dye <INT +4 MEN -4>',
    'additionalname' => NULL,
    'description' => 'Collect 10 units and take them to the Dye Merchant to get a symbol that boosts your abilities. Requirements: non-healing mages after the 2nd class change. Can be used by Ertheia after the 1st Liberation. The effect remains after the 2nd Liberation.',
    'is_trade' => 1,
    'is_drop' => 1,
    'is_destruct' => 1,
    'crystal_type' => 'none',
    'consume_type' => 'consume_type_stackable',
  ],
  4620 => 
  [
    'item_id' => 4620,
    'icon' => 'etc_int_hena_i02',
    'name' => 'Greater INT Dye <INT +4 WIT -4>',
    'additionalname' => NULL,
    'description' => 'Collect 10 units and take them to the Dye Merchant to get a symbol that boosts your abilities. Requirements: warriors and non-healing mages after the 2nd class change. Can be used by Ertheia after the 1st Liberation. The effect remains after the 2nd Liberation.',
    'is_trade' => 1,
    'is_drop' => 1,
    'is_destruct' => 1,
    'crystal_type' => 'none',
    'consume_type' => 'consume_type_stackable',
  ],
  4621 => 
  [
    'item_id' => 4621,
    'icon' => 'etc_men_hena_i02',
    'name' => 'Greater MEN Dye <MEN +4 INT -4>',
    'additionalname' => NULL,
    'description' => 'Collect 10 units and take them to the Dye Merchant to get a symbol that boosts your abilities. Requirements: non-healing mages after the 2nd class change. Can be used by Ertheia after the 1st Liberation. The effect remains after the 2nd Liberation.',
    'is_trade' => 1,
    'is_drop' => 1,
    'is_destruct' => 1,
    'crystal_type' => 'none',
    'consume_type' => 'consume_type_stackable',
  ],
  4622 => 
  [
    'item_id' => 4622,
    'icon' => 'etc_men_hena_i02',
    'name' => 'Greater MEN Dye <MEN +4 WIT -4>',
    'additionalname' => NULL,
    'description' => 'Collect 10 units and take them to the Dye Merchant to get a symbol that boosts your abilities. Requirements: all mages after the 2nd class change. Can be used by Ertheia after the 1st Liberation. The effect remains after the 2nd Liberation.',
    'is_trade' => 1,
    'is_drop' => 1,
    'is_destruct' => 1,
    'crystal_type' => 'none',
    'consume_type' => 'consume_type_stackable',
  ],
  4623 => 
  [
    'item_id' => 4623,
    'icon' => 'etc_wit_hena_i02',
    'name' => 'Greater WIT Dye <WIT +4 INT -4>',
    'additionalname' => NULL,
    'description' => 'Collect 10 units and take them to the Dye Merchant to get a symbol that boosts your abilities. Requirements: warriors and non-healing mages after the 2nd class change. Can be used by Ertheia after the 1st Liberation. The effect remains after the 2nd Liberation.',
    'is_trade' => 1,
    'is_drop' => 1,
    'is_destruct' => 1,
    'crystal_type' => 'none',
    'consume_type' => 'consume_type_stackable',
  ],
  4624 => 
  [
    'item_id' => 4624,
    'icon' => 'etc_wit_hena_i02',
    'name' => 'Greater WIT Dye <WIT +4 MEN -4>',
    'additionalname' => NULL,
    'description' => 'Collect 10 units and take them to the Dye Merchant to get a symbol that boosts your abilities. Requirements: all mages after the 2nd class change. Can be used by Ertheia after the 1st Liberation. The effect remains after the 2nd Liberation.',
    'is_trade' => 1,
    'is_drop' => 1,
    'is_destruct' => 1,
    'crystal_type' => 'none',
    'consume_type' => 'consume_type_stackable',
  ],
  4625 => 
  [
    'item_id' => 4625,
    'icon' => 'etc_dice_a_i00',
    'name' => 'Dice (Heart]',
    'additionalname' => NULL,
    'description' => 'Simple game of chance! Roll em!!',
    'is_trade' => 1,
    'is_drop' => 0,
    'is_destruct' => 1,
    'crystal_type' => 'none',
    'consume_type' => 'consume_type_normal',
  ],
  4626 => 
  [
    'item_id' => 4626,
    'icon' => 'etc_dice_b_i00',
    'name' => 'Dice (Spade]',
    'additionalname' => NULL,
    'description' => 'Simple game of chance! Roll em!!',
    'is_trade' => 1,
    'is_drop' => 0,
    'is_destruct' => 1,
    'crystal_type' => 'none',
    'consume_type' => 'consume_type_normal',
  ],
  4627 => 
  [
    'item_id' => 4627,
    'icon' => 'etc_dice_c_i00',
    'name' => 'Dice (Clover]',
    'additionalname' => NULL,
    'description' => 'Simple game of chance! Roll em!!',
    'is_trade' => 1,
    'is_drop' => 0,
    'is_destruct' => 1,
    'crystal_type' => 'none',
    'consume_type' => 'consume_type_normal',
  ],
  4628 => 
  [
    'item_id' => 4628,
    'icon' => 'etc_dice_d_i00',
    'name' => 'Dice (Diamond]',
    'additionalname' => NULL,
    'description' => 'Simple game of chance! Roll em!!',
    'is_trade' => 1,
    'is_drop' => 0,
    'is_destruct' => 1,
    'crystal_type' => 'none',
    'consume_type' => 'consume_type_normal',
  ],
  4629 => 
  [
    'item_id' => 4629,
    'icon' => 'etc_soul_stone_i00',
    'name' => 'Red Soul Crystal',
    'additionalname' => NULL,
    'description' => 'Red crystal that contains the light of absorbed souls. Once saturated, it bestows special abilities to a weapon. Consumes 26 MP when used.',
    'is_trade' => 1,
    'is_drop' => 1,
    'is_destruct' => 1,
    'crystal_type' => 'crystal_free',
    'consume_type' => 'consume_type_normal',
  ],
  4630 => 
  [
    'item_id' => 4630,
    'icon' => 'etc_soul_stone_i00',
    'name' => 'Red Soul Crystal Lv. 1',
    'additionalname' => NULL,
    'description' => 'Red crystal that contains the light of absorbed souls. Level 1. Once saturated, it bestows special abilities to a weapon. Consumes 26 MP when used.',
    'is_trade' => 1,
    'is_drop' => 1,
    'is_destruct' => 1,
    'crystal_type' => 'crystal_free',
    'consume_type' => 'consume_type_normal',
  ],
  4631 => 
  [
    'item_id' => 4631,
    'icon' => 'etc_soul_stone_i00',
    'name' => 'Red Soul Crystal Lv. 2',
    'additionalname' => NULL,
    'description' => 'Red crystal that contains the light of absorbed souls. Level 2. Once saturated, it bestows special abilities to a weapon. Consumes 26 MP when used.',
    'is_trade' => 1,
    'is_drop' => 1,
    'is_destruct' => 1,
    'crystal_type' => 'crystal_free',
    'consume_type' => 'consume_type_normal',
  ],
  4632 => 
  [
    'item_id' => 4632,
    'icon' => 'etc_soul_stone_i00',
    'name' => 'Red Soul Crystal Lv. 3',
    'additionalname' => NULL,
    'description' => 'Red crystal that contains the light of absorbed souls. Level 3. Once saturated, it bestows special abilities to a weapon. Consumes 26 MP when used.',
    'is_trade' => 1,
    'is_drop' => 1,
    'is_destruct' => 1,
    'crystal_type' => 'crystal_free',
    'consume_type' => 'consume_type_normal',
  ],
  4633 => 
  [
    'item_id' => 4633,
    'icon' => 'etc_soul_stone_i00',
    'name' => 'Red Soul Crystal Lv. 4',
    'additionalname' => NULL,
    'description' => 'Red crystal that contains the light of absorbed souls. Level 4. Once saturated, it bestows special abilities to a weapon. Consumes 26 MP when used.',
    'is_trade' => 1,
    'is_drop' => 1,
    'is_destruct' => 1,
    'crystal_type' => 'crystal_free',
    'consume_type' => 'consume_type_normal',
  ],
  4634 => 
  [
    'item_id' => 4634,
    'icon' => 'etc_soul_stone_i00',
    'name' => 'Red Soul Crystal Lv. 5',
    'additionalname' => NULL,
    'description' => 'Red crystal that contains the light of absorbed souls. Level 5. Once saturated, it bestows special abilities to a weapon. Consumes 26 MP when used.',
    'is_trade' => 1,
    'is_drop' => 1,
    'is_destruct' => 1,
    'crystal_type' => 'crystal_free',
    'consume_type' => 'consume_type_normal',
  ],
  4635 => 
  [
    'item_id' => 4635,
    'icon' => 'etc_soul_stone_i00',
    'name' => 'Red Soul Crystal Lv. 6',
    'additionalname' => NULL,
    'description' => 'Red crystal that contains the light of absorbed souls. Level 6. Once saturated, it bestows special abilities to a weapon. Consumes 26 MP when used.',
    'is_trade' => 1,
    'is_drop' => 1,
    'is_destruct' => 1,
    'crystal_type' => 'crystal_free',
    'consume_type' => 'consume_type_normal',
  ],
  4636 => 
  [
    'item_id' => 4636,
    'icon' => 'etc_soul_stone_i00',
    'name' => 'Red Soul Crystal Lv. 7',
    'additionalname' => NULL,
    'description' => 'Red crystal that contains the light of absorbed souls. Level 7. Once saturated, it bestows special abilities to a weapon. Consumes 26 MP when used.',
    'is_trade' => 1,
    'is_drop' => 1,
    'is_destruct' => 1,
    'crystal_type' => 'crystal_free',
    'consume_type' => 'consume_type_normal',
  ],
  4637 => 
  [
    'item_id' => 4637,
    'icon' => 'etc_soul_stone_i00',
    'name' => 'Red Soul Crystal Lv. 8',
    'additionalname' => NULL,
    'description' => 'Red crystal that contains the light of absorbed souls. Level 8. Once saturated, it bestows special abilities to a weapon. Consumes 26 MP when used.',
    'is_trade' => 1,
    'is_drop' => 1,
    'is_destruct' => 1,
    'crystal_type' => 'crystal_free',
    'consume_type' => 'consume_type_normal',
  ],
  4638 => 
  [
    'item_id' => 4638,
    'icon' => 'etc_soul_stone_i00',
    'name' => 'Red Soul Crystal Lv. 9',
    'additionalname' => NULL,
    'description' => 'Red crystal that contains the light of absorbed souls. Level 9. Once saturated, it bestows special abilities to a weapon. Consumes 26 MP when used.',
    'is_trade' => 1,
    'is_drop' => 1,
    'is_destruct' => 1,
    'crystal_type' => 'crystal_free',
    'consume_type' => 'consume_type_normal',
  ],
  4639 => 
  [
    'item_id' => 4639,
    'icon' => 'etc_soul_stone_i00',
    'name' => 'Red Soul Crystal Lv. 10',
    'additionalname' => NULL,
    'description' => 'Red crystal that contains the light of absorbed souls. Level 10. Once saturated, it bestows special abilities to a weapon. Consumes 26 MP when used. A crystal of this level is said to absorb souls on its own, so you dont have to use it directly on monsters.',
    'is_trade' => 1,
    'is_drop' => 1,
    'is_destruct' => 1,
    'crystal_type' => 'crystal_free',
    'consume_type' => 'consume_type_normal',
  ],
  4640 => 
  [
    'item_id' => 4640,
    'icon' => 'etc_soul_stone_i02',
    'name' => 'Green Soul Crystal',
    'additionalname' => NULL,
    'description' => 'Green crystal that contains the light of absorbed souls. Once saturated, it bestows special abilities to a weapon. Consumes 26 MP when used.',
    'is_trade' => 1,
    'is_drop' => 1,
    'is_destruct' => 1,
    'crystal_type' => 'crystal_free',
    'consume_type' => 'consume_type_normal',
  ],
  4641 => 
  [
    'item_id' => 4641,
    'icon' => 'etc_soul_stone_i02',
    'name' => 'Green Soul Crystal Lv. 1',
    'additionalname' => NULL,
    'description' => 'Green crystal that contains the light of absorbed souls. Level 1. Once saturated, it bestows special abilities to a weapon. Consumes 26 MP when used.',
    'is_trade' => 1,
    'is_drop' => 1,
    'is_destruct' => 1,
    'crystal_type' => 'crystal_free',
    'consume_type' => 'consume_type_normal',
  ],
  4642 => 
  [
    'item_id' => 4642,
    'icon' => 'etc_soul_stone_i02',
    'name' => 'Green Soul Crystal Lv. 2',
    'additionalname' => NULL,
    'description' => 'Green crystal that contains the light of absorbed souls. Level 2. Once saturated, it bestows special abilities to a weapon. Consumes 26 MP when used.',
    'is_trade' => 1,
    'is_drop' => 1,
    'is_destruct' => 1,
    'crystal_type' => 'crystal_free',
    'consume_type' => 'consume_type_normal',
  ],
  4643 => 
  [
    'item_id' => 4643,
    'icon' => 'etc_soul_stone_i02',
    'name' => 'Green Soul Crystal Lv. 3',
    'additionalname' => NULL,
    'description' => 'Green crystal that contains the light of absorbed souls. Level 3. Once saturated, it bestows special abilities to a weapon. Consumes 26 MP when used.',
    'is_trade' => 1,
    'is_drop' => 1,
    'is_destruct' => 1,
    'crystal_type' => 'crystal_free',
    'consume_type' => 'consume_type_normal',
  ],
  4644 => 
  [
    'item_id' => 4644,
    'icon' => 'etc_soul_stone_i02',
    'name' => 'Green Soul Crystal Lv. 4',
    'additionalname' => NULL,
    'description' => 'Green crystal that contains the light of absorbed souls. Level 4. Once saturated, it bestows special abilities to a weapon. Consumes 26 MP when used.',
    'is_trade' => 1,
    'is_drop' => 1,
    'is_destruct' => 1,
    'crystal_type' => 'crystal_free',
    'consume_type' => 'consume_type_normal',
  ],
  4645 => 
  [
    'item_id' => 4645,
    'icon' => 'etc_soul_stone_i02',
    'name' => 'Green Soul Crystal Lv. 5',
    'additionalname' => NULL,
    'description' => 'Green crystal that contains the light of absorbed souls. Level 5. Once saturated, it bestows special abilities to a weapon. Consumes 26 MP when used.',
    'is_trade' => 1,
    'is_drop' => 1,
    'is_destruct' => 1,
    'crystal_type' => 'crystal_free',
    'consume_type' => 'consume_type_normal',
  ],
  4646 => 
  [
    'item_id' => 4646,
    'icon' => 'etc_soul_stone_i02',
    'name' => 'Green Soul Crystal Lv. 6',
    'additionalname' => NULL,
    'description' => 'Green crystal that contains the light of absorbed souls. Level 6. Once saturated, it bestows special abilities to a weapon. Consumes 26 MP when used.',
    'is_trade' => 1,
    'is_drop' => 1,
    'is_destruct' => 1,
    'crystal_type' => 'crystal_free',
    'consume_type' => 'consume_type_normal',
  ],
  4647 => 
  [
    'item_id' => 4647,
    'icon' => 'etc_soul_stone_i02',
    'name' => 'Green Soul Crystal Lv. 7',
    'additionalname' => NULL,
    'description' => 'Green crystal that contains the light of absorbed souls. Level 7. Once saturated, it bestows special abilities to a weapon. Consumes 26 MP when used.',
    'is_trade' => 1,
    'is_drop' => 1,
    'is_destruct' => 1,
    'crystal_type' => 'crystal_free',
    'consume_type' => 'consume_type_normal',
  ],
  4648 => 
  [
    'item_id' => 4648,
    'icon' => 'etc_soul_stone_i02',
    'name' => 'Green Soul Crystal Lv. 8',
    'additionalname' => NULL,
    'description' => 'Green crystal that contains the light of absorbed souls. Level 8. Once saturated, it bestows special abilities to a weapon. Consumes 26 MP when used.',
    'is_trade' => 1,
    'is_drop' => 1,
    'is_destruct' => 1,
    'crystal_type' => 'crystal_free',
    'consume_type' => 'consume_type_normal',
  ],
  4649 => 
  [
    'item_id' => 4649,
    'icon' => 'etc_soul_stone_i02',
    'name' => 'Green Soul Crystal Lv. 9',
    'additionalname' => NULL,
    'description' => 'Green crystal that contains the light of absorbed souls. Level 9. Once saturated, it bestows special abilities to a weapon. Consumes 26 MP when used.',
    'is_trade' => 1,
    'is_drop' => 1,
    'is_destruct' => 1,
    'crystal_type' => 'crystal_free',
    'consume_type' => 'consume_type_normal',
  ],
  4650 => 
  [
    'item_id' => 4650,
    'icon' => 'etc_soul_stone_i02',
    'name' => 'Green Soul Crystal Lv. 10',
    'additionalname' => NULL,
    'description' => 'Green crystal that contains the light of absorbed souls. Level 10. Once saturated, it bestows special abilities to a weapon. Consumes 26 MP when used. A crystal of this level is said to absorb souls on its own, so you dont have to use it directly on monsters.',
    'is_trade' => 1,
    'is_drop' => 1,
    'is_destruct' => 1,
    'crystal_type' => 'crystal_free',
    'consume_type' => 'consume_type_normal',
  ],
  4651 => 
  [
    'item_id' => 4651,
    'icon' => 'etc_soul_stone_i01',
    'name' => 'Blue Soul Crystal',
    'additionalname' => NULL,
    'description' => 'Blue crystal that contains the light of absorbed souls. Once saturated, it bestows special abilities to a weapon. Consumes 26 MP when used.',
    'is_trade' => 1,
    'is_drop' => 1,
    'is_destruct' => 1,
    'crystal_type' => 'crystal_free',
    'consume_type' => 'consume_type_normal',
  ],
  4652 => 
  [
    'item_id' => 4652,
    'icon' => 'etc_soul_stone_i01',
    'name' => 'Blue Soul Crystal Lv. 1',
    'additionalname' => NULL,
    'description' => 'Blue crystal that contains the light of absorbed souls. Level 1. Once saturated, it bestows special abilities to a weapon. Consumes 26 MP when used.',
    'is_trade' => 1,
    'is_drop' => 1,
    'is_destruct' => 1,
    'crystal_type' => 'crystal_free',
    'consume_type' => 'consume_type_normal',
  ],
  4653 => 
  [
    'item_id' => 4653,
    'icon' => 'etc_soul_stone_i01',
    'name' => 'Blue Soul Crystal Lv. 2',
    'additionalname' => NULL,
    'description' => 'Blue crystal that contains the light of absorbed souls. Level 2. Once saturated, it bestows special abilities to a weapon. Consumes 26 MP when used.',
    'is_trade' => 1,
    'is_drop' => 1,
    'is_destruct' => 1,
    'crystal_type' => 'crystal_free',
    'consume_type' => 'consume_type_normal',
  ],
  4654 => 
  [
    'item_id' => 4654,
    'icon' => 'etc_soul_stone_i01',
    'name' => 'Blue Soul Crystal Lv. 3',
    'additionalname' => NULL,
    'description' => 'Blue crystal that contains the light of absorbed souls. Level 3. Once saturated, it bestows special abilities to a weapon. Consumes 26 MP when used.',
    'is_trade' => 1,
    'is_drop' => 1,
    'is_destruct' => 1,
    'crystal_type' => 'crystal_free',
    'consume_type' => 'consume_type_normal',
  ],
  4655 => 
  [
    'item_id' => 4655,
    'icon' => 'etc_soul_stone_i01',
    'name' => 'Blue Soul Crystal Lv. 4',
    'additionalname' => NULL,
    'description' => 'Blue crystal that contains the light of absorbed souls. Level 4. Once saturated, it bestows special abilities to a weapon. Consumes 26 MP when used.',
    'is_trade' => 1,
    'is_drop' => 1,
    'is_destruct' => 1,
    'crystal_type' => 'crystal_free',
    'consume_type' => 'consume_type_normal',
  ],
  4656 => 
  [
    'item_id' => 4656,
    'icon' => 'etc_soul_stone_i01',
    'name' => 'Blue Soul Crystal Lv. 5',
    'additionalname' => NULL,
    'description' => 'Blue crystal that contains the light of absorbed souls. Level 5. Once saturated, it bestows special abilities to a weapon. Consumes 26 MP when used.',
    'is_trade' => 1,
    'is_drop' => 1,
    'is_destruct' => 1,
    'crystal_type' => 'crystal_free',
    'consume_type' => 'consume_type_normal',
  ],
  4657 => 
  [
    'item_id' => 4657,
    'icon' => 'etc_soul_stone_i01',
    'name' => 'Blue Soul Crystal Lv. 6',
    'additionalname' => NULL,
    'description' => 'Blue crystal that contains the light of absorbed souls. Level 6. Once saturated, it bestows special abilities to a weapon. Consumes 26 MP when used.',
    'is_trade' => 1,
    'is_drop' => 1,
    'is_destruct' => 1,
    'crystal_type' => 'crystal_free',
    'consume_type' => 'consume_type_normal',
  ],
  4658 => 
  [
    'item_id' => 4658,
    'icon' => 'etc_soul_stone_i01',
    'name' => 'Blue Soul Crystal Lv. 7',
    'additionalname' => NULL,
    'description' => 'Blue crystal that contains the light of absorbed souls. Level 7. Once saturated, it bestows special abilities to a weapon. Consumes 26 MP when used.',
    'is_trade' => 1,
    'is_drop' => 1,
    'is_destruct' => 1,
    'crystal_type' => 'crystal_free',
    'consume_type' => 'consume_type_normal',
  ],
  4659 => 
  [
    'item_id' => 4659,
    'icon' => 'etc_soul_stone_i01',
    'name' => 'Blue Soul Crystal Lv. 8',
    'additionalname' => NULL,
    'description' => 'Blue crystal that contains the light of absorbed souls. Level 8. Once saturated, it bestows special abilities to a weapon. Consumes 26 MP when used.',
    'is_trade' => 1,
    'is_drop' => 1,
    'is_destruct' => 1,
    'crystal_type' => 'crystal_free',
    'consume_type' => 'consume_type_normal',
  ],
  4660 => 
  [
    'item_id' => 4660,
    'icon' => 'etc_soul_stone_i01',
    'name' => 'Blue Soul Crystal Lv. 9',
    'additionalname' => NULL,
    'description' => 'Blue crystal that contains the light of absorbed souls. Level 9. Once saturated, it bestows special abilities to a weapon. Consumes 26 MP when used.',
    'is_trade' => 1,
    'is_drop' => 1,
    'is_destruct' => 1,
    'crystal_type' => 'crystal_free',
    'consume_type' => 'consume_type_normal',
  ],
  4661 => 
  [
    'item_id' => 4661,
    'icon' => 'etc_soul_stone_i01',
    'name' => 'Blue Soul Crystal Lv. 10',
    'additionalname' => NULL,
    'description' => 'Blue crystal that contains the light of absorbed souls. Level 10. Once saturated, it bestows special abilities to a weapon. Consumes 26 MP when used. A crystal of this level is said to absorb souls on its own, so you dont have to use it directly on monsters.',
    'is_trade' => 1,
    'is_drop' => 1,
    'is_destruct' => 1,
    'crystal_type' => 'crystal_free',
    'consume_type' => 'consume_type_normal',
  ],
  4662 => 
  [
    'item_id' => 4662,
    'icon' => 'etc_broken_crystal_red_i00',
    'name' => 'Broken Red Soul Crystal',
    'additionalname' => NULL,
    'description' => 'Red-colored crystal that absorbs souls. Internal imbalance between absorbed souls has rendered it useless.',
    'is_trade' => 1,
    'is_drop' => 1,
    'is_destruct' => 1,
    'crystal_type' => 'crystal_free',
    'consume_type' => 'consume_type_normal',
  ],
  4663 => 
  [
    'item_id' => 4663,
    'icon' => 'etc_broken_crystal_green_i00',
    'name' => 'Broken Green Soul Crystal',
    'additionalname' => NULL,
    'description' => 'Green-colored crystal that absorbs souls. Internal imbalance between absorbed souls has rendered it useless.',
    'is_trade' => 1,
    'is_drop' => 1,
    'is_destruct' => 1,
    'crystal_type' => 'crystal_free',
    'consume_type' => 'consume_type_normal',
  ],
  4664 => 
  [
    'item_id' => 4664,
    'icon' => 'etc_broken_crystal_blue_i00',
    'name' => 'Broken Blue Soul Crystal',
    'additionalname' => NULL,
    'description' => 'Blue-colored crystal that absorbs souls. Internal imbalance between absorbed souls has rendered it useless.',
    'is_trade' => 1,
    'is_drop' => 1,
    'is_destruct' => 1,
    'crystal_type' => 'crystal_free',
    'consume_type' => 'consume_type_normal',
  ],
  4665 => 
  [
    'item_id' => 4665,
    'icon' => 'weapon_knife_i00',
    'name' => 'Pipette Knife',
    'additionalname' => NULL,
    'description' => 'Instrument used to collect the blood of living creatures. Use it to cut Baium and obtain a blood sample.',
    'is_trade' => 0,
    'is_drop' => 0,
    'is_destruct' => 0,
    'crystal_type' => 'none',
    'consume_type' => 'consume_type_normal',
  ],
  4666 => 
  [
    'item_id' => 4666,
    'icon' => 'etc_bead_white_i00',
    'name' => 'Reirias Soul Orb',
    'additionalname' => NULL,
    'description' => 'Sphere containing Reirias Soul. Take it to Maestro Reorin.',
    'is_trade' => 0,
    'is_drop' => 0,
    'is_destruct' => 1,
    'crystal_type' => 'none',
    'consume_type' => 'consume_type_stackable',
  ],
  4667 => 
  [
    'item_id' => 4667,
    'icon' => 'etc_imperial_scepter_i02',
    'name' => 'Kernons Infernium Scepter',
    'additionalname' => NULL,
    'description' => 'Scepter made of infernium that was recovered from the demon Kernon. Take it to Maestro Reorin.',
    'is_trade' => 0,
    'is_drop' => 0,
    'is_destruct' => 1,
    'crystal_type' => 'none',
    'consume_type' => 'consume_type_stackable',
  ],
  4668 => 
  [
    'item_id' => 4668,
    'icon' => 'etc_imperial_scepter_i01',
    'name' => 'Golkondas Infernium Scepter',
    'additionalname' => NULL,
    'description' => 'Scepter made of infernium that was recovered from Golkonda, the Longhorn General. Take it to Maestro Reorin.',
    'is_trade' => 0,
    'is_drop' => 0,
    'is_destruct' => 1,
    'crystal_type' => 'none',
    'consume_type' => 'consume_type_stackable',
  ],
  4669 => 
  [
    'item_id' => 4669,
    'icon' => 'etc_imperial_scepter_i00',
    'name' => 'Hallates Infernium Scepter',
    'additionalname' => NULL,
    'description' => 'Scepter made of infernium that was recovered from the Death Lord Hallate. Take it to Maestro Reorin.',
    'is_trade' => 0,
    'is_drop' => 0,
    'is_destruct' => 1,
    'crystal_type' => 'none',
    'consume_type' => 'consume_type_stackable',
  ],
  4670 => 
  [
    'item_id' => 4670,
    'icon' => 'weapon_iron_hammer_i01',
    'name' => 'Maestro Reorins Hammer',
    'additionalname' => NULL,
    'description' => 'Hammer used by a blacksmith. It is made by processing an adamantite nugget of high purity. Take it to Maestro Reorin.',
    'is_trade' => 0,
    'is_drop' => 0,
    'is_destruct' => 1,
    'crystal_type' => 'none',
    'consume_type' => 'consume_type_stackable',
  ],
  4671 => 
  [
    'item_id' => 4671,
    'icon' => 'etc_artisans_frame_i00',
    'name' => 'Maestro Reorins Mold',
    'additionalname' => NULL,
    'description' => 'Mold used by Dwarven Artisans to manufacture top grade equipment. Take it to Maestro Reorin.',
    'is_trade' => 0,
    'is_drop' => 0,
    'is_destruct' => 1,
    'crystal_type' => 'none',
    'consume_type' => 'consume_type_stackable',
  ],
  4672 => 
  [
    'item_id' => 4672,
    'icon' => 'etc_powder_red_i00',
    'name' => 'Infernium Varnish',
    'additionalname' => NULL,
    'description' => 'Varnish used when manufacturing an infernium weapon. Take it to Maestro Reorin.',
    'is_trade' => 0,
    'is_drop' => 0,
    'is_destruct' => 1,
    'crystal_type' => 'none',
    'consume_type' => 'consume_type_stackable',
  ],
  4673 => 
  [
    'item_id' => 4673,
    'icon' => 'weapon_knife_i01',
    'name' => 'Red Pipette Knife',
    'additionalname' => NULL,
    'description' => 'Pipette knife that holds Baiums blood. Bring it to Magister Casper at Hardins Academy.',
    'is_trade' => 0,
    'is_drop' => 0,
    'is_destruct' => 1,
    'crystal_type' => 'none',
    'consume_type' => 'consume_type_stackable',
  ],
  4674 => 
  [
    'item_id' => 4674,
    'icon' => 'etc_magic_coin_gold_i00',
    'name' => 'Medal of Glory',
    'additionalname' => NULL,
    'description' => NULL,
    'is_trade' => 0,
    'is_drop' => 0,
    'is_destruct' => 1,
    'crystal_type' => 'none',
    'consume_type' => 'consume_type_stackable',
  ],
  4675 => 
  [
    'item_id' => 4675,
    'icon' => 'etc_magic_coin_silver_i00',
    'name' => 'Medal of Friendship',
    'additionalname' => NULL,
    'description' => NULL,
    'is_trade' => 0,
    'is_drop' => 0,
    'is_destruct' => 1,
    'crystal_type' => 'none',
    'consume_type' => 'consume_type_stackable',
  ],
  4676 => 
  [
    'item_id' => 4676,
    'icon' => 'etc_magic_coin_blood_i00',
    'name' => 'Medal of Victory',
    'additionalname' => NULL,
    'description' => NULL,
    'is_trade' => 0,
    'is_drop' => 0,
    'is_destruct' => 1,
    'crystal_type' => 'none',
    'consume_type' => 'consume_type_stackable',
  ],
  4677 => 
  [
    'item_id' => 4677,
    'icon' => 'etc_potion_red_i00',
    'name' => 'Potion of Critical Escape',
    'additionalname' => NULL,
    'description' => 'Allows to evade enemies attacks, but decreases Speed.',
    'is_trade' => 1,
    'is_drop' => 1,
    'is_destruct' => 1,
    'crystal_type' => 'crystal_free',
    'consume_type' => 'consume_type_stackable',
  ],
  4678 => 
  [
    'item_id' => 4678,
    'icon' => 'etc_scroll_white_i00',
    'name' => 'Scroll: Decrease Hate',
    'additionalname' => NULL,
    'description' => 'Decreases ones level of Aggression.',
    'is_trade' => 1,
    'is_drop' => 1,
    'is_destruct' => 1,
    'crystal_type' => 'crystal_free',
    'consume_type' => 'consume_type_stackable',
  ],
  4679 => 
  [
    'item_id' => 4679,
    'icon' => 'etc_bless_of_eva_i00',
    'name' => 'Evas Blessing',
    'additionalname' => NULL,
    'description' => 'Allows one to breathe under water for extended periods.',
    'is_trade' => 1,
    'is_drop' => 1,
    'is_destruct' => 1,
    'crystal_type' => 'crystal_free',
    'consume_type' => 'consume_type_stackable',
  ],
  4680 => 
  [
    'item_id' => 4680,
    'icon' => 'etc_potion_blue_i00',
    'name' => 'Potion of Critical Escape',
    'additionalname' => NULL,
    'description' => 'Decreases P. Def. and reflects damage back to the enemy.',
    'is_trade' => 1,
    'is_drop' => 1,
    'is_destruct' => 1,
    'crystal_type' => 'crystal_free',
    'consume_type' => 'consume_type_stackable',
  ],
  4681 => 
  [
    'item_id' => 4681,
    'icon' => 'weapon_stormbringer_i01',
    'name' => 'Stormbringer',
    'additionalname' => 'Critical Anger',
    'description' => 'Not used',
    'is_trade' => 1,
    'is_drop' => 1,
    'is_destruct' => 1,
    'crystal_type' => 'c',
    'consume_type' => 'consume_type_normal',
  ],
  4682 => 
  [
    'item_id' => 4682,
    'icon' => 'weapon_stormbringer_i01',
    'name' => 'Stormbringer',
    'additionalname' => 'Focus',
    'description' => 'Not used',
    'is_trade' => 1,
    'is_drop' => 1,
    'is_destruct' => 1,
    'crystal_type' => 'c',
    'consume_type' => 'consume_type_normal',
  ],
  4683 => 
  [
    'item_id' => 4683,
    'icon' => 'weapon_stormbringer_i01',
    'name' => 'Stormbringer',
    'additionalname' => 'Decrease Weight',
    'description' => 'Not used',
    'is_trade' => 1,
    'is_drop' => 1,
    'is_destruct' => 1,
    'crystal_type' => 'c',
    'consume_type' => 'consume_type_normal',
  ],
  4684 => 
  [
    'item_id' => 4684,
    'icon' => 'weapon_shamshir_i01',
    'name' => 'Shamshir',
    'additionalname' => 'Guidance',
    'description' => 'Not used',
    'is_trade' => 1,
    'is_drop' => 1,
    'is_destruct' => 1,
    'crystal_type' => 'c',
    'consume_type' => 'consume_type_normal',
  ],
  4685 => 
  [
    'item_id' => 4685,
    'icon' => 'weapon_shamshir_i01',
    'name' => 'Shamshir',
    'additionalname' => 'Backstab',
    'description' => 'Not used',
    'is_trade' => 1,
    'is_drop' => 1,
    'is_destruct' => 1,
    'crystal_type' => 'c',
    'consume_type' => 'consume_type_normal',
  ],
  4686 => 
  [
    'item_id' => 4686,
    'icon' => 'weapon_shamshir_i01',
    'name' => 'Shamshir',
    'additionalname' => 'Rsk. Evasion',
    'description' => 'Not used',
    'is_trade' => 1,
    'is_drop' => 1,
    'is_destruct' => 1,
    'crystal_type' => 'c',
    'consume_type' => 'consume_type_normal',
  ],
  4687 => 
  [
    'item_id' => 4687,
    'icon' => 'weapon_katana_i01',
    'name' => 'Katana',
    'additionalname' => 'Focus',
    'description' => 'Not used',
    'is_trade' => 1,
    'is_drop' => 1,
    'is_destruct' => 1,
    'crystal_type' => 'c',
    'consume_type' => 'consume_type_normal',
  ],
  4688 => 
  [
    'item_id' => 4688,
    'icon' => 'weapon_katana_i01',
    'name' => 'Katana',
    'additionalname' => 'Critical Damage',
    'description' => 'Not used',
    'is_trade' => 1,
    'is_drop' => 1,
    'is_destruct' => 1,
    'crystal_type' => 'c',
    'consume_type' => 'consume_type_normal',
  ],
  4689 => 
  [
    'item_id' => 4689,
    'icon' => 'weapon_katana_i01',
    'name' => 'Katana',
    'additionalname' => 'Haste',
    'description' => 'Not used',
    'is_trade' => 1,
    'is_drop' => 1,
    'is_destruct' => 1,
    'crystal_type' => 'c',
    'consume_type' => 'consume_type_normal',
  ],
  4690 => 
  [
    'item_id' => 4690,
    'icon' => 'weapon_spirits_sword_i01',
    'name' => 'Spirit Sword',
    'additionalname' => 'Critical Damage',
    'description' => 'Not used',
    'is_trade' => 1,
    'is_drop' => 1,
    'is_destruct' => 1,
    'crystal_type' => 'c',
    'consume_type' => 'consume_type_normal',
  ],
  4691 => 
  [
    'item_id' => 4691,
    'icon' => 'weapon_spirits_sword_i01',
    'name' => 'Spirit Sword',
    'additionalname' => 'Critical Poison',
    'description' => 'Not used',
    'is_trade' => 1,
    'is_drop' => 1,
    'is_destruct' => 1,
    'crystal_type' => 'c',
    'consume_type' => 'consume_type_normal',
  ],
  4692 => 
  [
    'item_id' => 4692,
    'icon' => 'weapon_spirits_sword_i01',
    'name' => 'Spirit Sword',
    'additionalname' => 'Haste',
    'description' => 'Not used',
    'is_trade' => 1,
    'is_drop' => 1,
    'is_destruct' => 1,
    'crystal_type' => 'c',
    'consume_type' => 'consume_type_normal',
  ],
  4693 => 
  [
    'item_id' => 4693,
    'icon' => 'weapon_raid_sword_i01',
    'name' => 'Raid Sword',
    'additionalname' => 'Focus',
    'description' => 'Not used',
    'is_trade' => 1,
    'is_drop' => 1,
    'is_destruct' => 1,
    'crystal_type' => 'c',
    'consume_type' => 'consume_type_normal',
  ],
  4694 => 
  [
    'item_id' => 4694,
    'icon' => 'weapon_raid_sword_i01',
    'name' => 'Raid Sword',
    'additionalname' => 'Critical Drain',
    'description' => 'Not used',
    'is_trade' => 1,
    'is_drop' => 1,
    'is_destruct' => 1,
    'crystal_type' => 'c',
    'consume_type' => 'consume_type_normal',
  ],
  4695 => 
  [
    'item_id' => 4695,
    'icon' => 'weapon_raid_sword_i01',
    'name' => 'Raid Sword',
    'additionalname' => 'Critical Poison',
    'description' => 'Not used',
    'is_trade' => 1,
    'is_drop' => 1,
    'is_destruct' => 1,
    'crystal_type' => 'c',
    'consume_type' => 'consume_type_normal',
  ],
  4696 => 
  [
    'item_id' => 4696,
    'icon' => 'weapon_caliburs_i01',
    'name' => 'Caliburs',
    'additionalname' => 'Guidance',
    'description' => 'Not used',
    'is_trade' => 1,
    'is_drop' => 1,
    'is_destruct' => 1,
    'crystal_type' => 'c',
    'consume_type' => 'consume_type_normal',
  ],
  4697 => 
  [
    'item_id' => 4697,
    'icon' => 'weapon_caliburs_i01',
    'name' => 'Caliburs',
    'additionalname' => 'Focus',
    'description' => 'Not used',
    'is_trade' => 1,
    'is_drop' => 1,
    'is_destruct' => 1,
    'crystal_type' => 'c',
    'consume_type' => 'consume_type_normal',
  ],
  4698 => 
  [
    'item_id' => 4698,
    'icon' => 'weapon_caliburs_i01',
    'name' => 'Caliburs',
    'additionalname' => 'Critical Damage',
    'description' => 'Not used',
    'is_trade' => 1,
    'is_drop' => 1,
    'is_destruct' => 1,
    'crystal_type' => 'c',
    'consume_type' => 'consume_type_normal',
  ],
  4699 => 
  [
    'item_id' => 4699,
    'icon' => 'weapon_sword_of_delusion_i01',
    'name' => 'Sword of Delusion',
    'additionalname' => 'Focus',
    'description' => 'Not used',
    'is_trade' => 1,
    'is_drop' => 1,
    'is_destruct' => 1,
    'crystal_type' => 'c',
    'consume_type' => 'consume_type_normal',
  ],
];