<?php return [
  47501 => 
  [
    'item_id' => 47501,
    'icon' => 'low_energy_condense_i05',
    'name' => 'Rune Stone Fragment',
    'additionalname' => '',
    'description' => 'A Rune Stone Fragment engraved in ancient Rune language. Collect 10 and take them to Lias in the Dimensional Rift to exchange for a Rune Stone.',
    'is_trade' => 0,
    'is_drop' => 0,
    'is_destruct' => 1,
    'crystal_type' => 'none',
    'consume_type' => 'consume_type_stackable',
  ],
  47502 => 
  [
    'item_id' => 47502,
    'icon' => 'etc_cave_page_i00',
    'name' => 'Superior Giant\'s Codex Chapter 1 - Fragment',
    'additionalname' => '',
    'description' => 'A single page from the Superior Giant\'s Codex Chapter 1. Collect 10 and take them to Lias in the Dimensional Rift to exchange for the Superior Giant\'s Codex Chapter 1.',
    'is_trade' => 0,
    'is_drop' => 0,
    'is_destruct' => 1,
    'crystal_type' => 'none',
    'consume_type' => 'consume_type_stackable',
  ],
  47503 => 
  [
    'item_id' => 47503,
    'icon' => 'renewal_mineral_r95',
    'name' => 'High-grade Spirit Stone',
    'additionalname' => '',
    'description' => 'Ordinary mineral that has been petrified by a creature\'s physical or magical damage and dimensional anomalies. Key component used in weapon Augmentation by characters with Lv. 95 or above.',
    'is_trade' => 0,
    'is_drop' => 0,
    'is_destruct' => 1,
    'crystal_type' => 'none',
    'consume_type' => 'consume_type_stackable',
  ],
  47504 => 
  [
    'item_id' => 47504,
    'icon' => 'etc_marguene_collection_box_i00',
    'name' => 'Lias Supply Items',
    'additionalname' => '',
    'description' => 'Supplies given by Lias to agents having completed "Dimensional Rift - 100-day Subjugation Operation".',
    'is_trade' => 0,
    'is_drop' => 0,
    'is_destruct' => 1,
    'crystal_type' => 'none',
    'consume_type' => 'consume_type_stackable',
  ],
  47505 => 
  [
    'item_id' => 47505,
    'icon' => 'ertheia_bracelet_i01',
    'name' => 'Bracelet of the Conqueror - CON',
    'additionalname' => '',
    'description' => 'The Bracelet of the Conqueror. Equip to activate 5 Talisman slots. HP +531 CON +3.',
    'is_trade' => 0,
    'is_drop' => 0,
    'is_destruct' => 1,
    'crystal_type' => 'r',
    'consume_type' => 'consume_type_normal',
  ],
  47506 => 
  [
    'item_id' => 47506,
    'icon' => 'ertheia_bracelet_i01',
    'name' => 'Bracelet of the Conqueror - MEN',
    'additionalname' => '',
    'description' => 'The Bracelet of the Conqueror. Equip to activate 5 Talisman slots. HP +531 MEN +3.',
    'is_trade' => 0,
    'is_drop' => 0,
    'is_destruct' => 1,
    'crystal_type' => 'r',
    'consume_type' => 'consume_type_normal',
  ],
  47507 => 
  [
    'item_id' => 47507,
    'icon' => 'ertheia_bracelet_i01',
    'name' => 'Bracelet of the Conqueror - DEX',
    'additionalname' => '',
    'description' => 'The Bracelet of the Conqueror. Equip to activate 5 Talisman slots. HP +531 DEX +3.',
    'is_trade' => 0,
    'is_drop' => 0,
    'is_destruct' => 1,
    'crystal_type' => 'r',
    'consume_type' => 'consume_type_normal',
  ],
  47508 => 
  [
    'item_id' => 47508,
    'icon' => 'ertheia_bracelet_i01',
    'name' => 'Bracelet of the Conqueror - WIT',
    'additionalname' => '',
    'description' => 'The Bracelet of the Conqueror. Equip to activate 5 Talisman slots. HP +531 WIT +3.',
    'is_trade' => 0,
    'is_drop' => 0,
    'is_destruct' => 1,
    'crystal_type' => 'r',
    'consume_type' => 'consume_type_normal',
  ],
  47509 => 
  [
    'item_id' => 47509,
    'icon' => 'ertheia_bracelet_i01',
    'name' => 'Bracelet of the Conqueror - STR',
    'additionalname' => '',
    'description' => 'The Bracelet of the Conqueror. Equip to activate 5 Talisman slots. HP +531 STR +3.',
    'is_trade' => 0,
    'is_drop' => 0,
    'is_destruct' => 1,
    'crystal_type' => 'r',
    'consume_type' => 'consume_type_normal',
  ],
  47510 => 
  [
    'item_id' => 47510,
    'icon' => 'ertheia_bracelet_i01',
    'name' => 'Bracelet of the Conqueror - INT',
    'additionalname' => '',
    'description' => 'The Bracelet of the Conqueror. Equip to activate 5 Talisman slots. HP +531 INT +3.',
    'is_trade' => 0,
    'is_drop' => 0,
    'is_destruct' => 1,
    'crystal_type' => 'r',
    'consume_type' => 'consume_type_normal',
  ],
  47511 => 
  [
    'item_id' => 47511,
    'icon' => 'etc_black_freezing_core_i00',
    'name' => 'Dimensional Traces',
    'additionalname' => '',
    'description' => 'Traces that have naturally accumulated during activity in the Dimensional Rift. They carry dimensional energy, and help to reach special areas within the Dimensional Rift.',
    'is_trade' => 0,
    'is_drop' => 0,
    'is_destruct' => 0,
    'crystal_type' => 'none',
    'consume_type' => 'consume_type_stackable',
  ],
  47512 => 
  [
    'item_id' => 47512,
    'icon' => 'etc_hard_fossil_i00',
    'name' => 'Attacker\'s Soul',
    'additionalname' => '',
    'description' => 'The soul of the Attacker that attempts to attack through the Dimensional Rift. Collect these and take them to the Dimensional Researcher Lias.',
    'is_trade' => 0,
    'is_drop' => 0,
    'is_destruct' => 0,
    'crystal_type' => 'none',
    'consume_type' => 'consume_type_stackable',
  ],
  47513 => 
  [
    'item_id' => 47513,
    'icon' => 'hunter_comminssion_paper',
    'name' => 'Request - Altar of Evil',
    'additionalname' => '',
    'description' => 'A request from the Hunter Guild calling on you to defeat the giant monsters in the Bloody Swampland and the Altar of Evil. The request can be accepted by characters between Lv. 85-93. Double-click to receive the request',
    'is_trade' => 0,
    'is_drop' => 0,
    'is_destruct' => 1,
    'crystal_type' => 'none',
    'consume_type' => 'consume_type_normal',
  ],
  47514 => 
  [
    'item_id' => 47514,
    'icon' => 'hunter_comminssion_paper',
    'name' => 'Request - Gludio Territory',
    'additionalname' => '',
    'description' => 'A request from the Hunter Guild calling on you to defeat the giant monsters in the Gludio Territory. The request can be accepted by characters between Lv. 85-93. Double-click to receive the request',
    'is_trade' => 0,
    'is_drop' => 0,
    'is_destruct' => 1,
    'crystal_type' => 'none',
    'consume_type' => 'consume_type_normal',
  ],
  47515 => 
  [
    'item_id' => 47515,
    'icon' => 'hunter_comminssion_paper',
    'name' => 'Request - Turek Orc Campsite',
    'additionalname' => '',
    'description' => 'A request from the Hunter Guild calling on you to defeat the giant monsters in the Turek Orc Campsite. The request can be accepted by characters between Lv. 87-97. Double-click to receive the request',
    'is_trade' => 0,
    'is_drop' => 0,
    'is_destruct' => 1,
    'crystal_type' => 'none',
    'consume_type' => 'consume_type_normal',
  ],
  47516 => 
  [
    'item_id' => 47516,
    'icon' => 'hunter_comminssion_paper',
    'name' => 'Request - Elven Forest',
    'additionalname' => '',
    'description' => 'A request from the Hunter Guild calling on you to defeat the giant monsters in the Elven Forest and the Shadow of the Mother Tree. The request can be accepted by characters between Lv. 88-98. Double-click to receive the request',
    'is_trade' => 0,
    'is_drop' => 0,
    'is_destruct' => 1,
    'crystal_type' => 'none',
    'consume_type' => 'consume_type_normal',
  ],
  47517 => 
  [
    'item_id' => 47517,
    'icon' => 'hunter_comminssion_paper',
    'name' => 'Request - Fairy Settlement',
    'additionalname' => '',
    'description' => 'A request from the Hunter Guild calling on you to defeat the giant monsters in the Fairy Settlement. The request can be accepted by characters between Lv. 88-98. Double-click to receive the request',
    'is_trade' => 0,
    'is_drop' => 0,
    'is_destruct' => 1,
    'crystal_type' => 'none',
    'consume_type' => 'consume_type_normal',
  ],
  47518 => 
  [
    'item_id' => 47518,
    'icon' => 'hunter_comminssion_paper',
    'name' => 'Request - Garden of Beasts',
    'additionalname' => '',
    'description' => 'A request from the Hunter Guild calling on you to defeat the giant monsters in the Garden of Beasts. The request can be accepted by characters between Lv. 89-99. Double-click to receive the request',
    'is_trade' => 0,
    'is_drop' => 0,
    'is_destruct' => 1,
    'crystal_type' => 'none',
    'consume_type' => 'consume_type_normal',
  ],
  47519 => 
  [
    'item_id' => 47519,
    'icon' => 'hunter_comminssion_paper',
    'name' => 'Request - North of the Town of Giran',
    'additionalname' => '',
    'description' => 'A request from the Hunter Guild calling on you to defeat the giant monsters in the Gorgon Flower Garden and the Breka\'s Stronghold. The request can be accepted by characters between Lv. 92-102. Double-click to receive the request',
    'is_trade' => 0,
    'is_drop' => 0,
    'is_destruct' => 1,
    'crystal_type' => 'none',
    'consume_type' => 'consume_type_normal',
  ],
  47520 => 
  [
    'item_id' => 47520,
    'icon' => 'hunter_comminssion_paper',
    'name' => 'Request - Cruma Marshlands',
    'additionalname' => '',
    'description' => 'A request from the Hunter Guild calling on you to defeat the giant monsters in the Bloody Swampland. The request can be accepted by characters between Lv. 92-102. Double-click to receive the request',
    'is_trade' => 0,
    'is_drop' => 0,
    'is_destruct' => 1,
    'crystal_type' => 'none',
    'consume_type' => 'consume_type_normal',
  ],
  47521 => 
  [
    'item_id' => 47521,
    'icon' => 'hunter_comminssion_paper',
    'name' => 'Request - The Fields',
    'additionalname' => '',
    'description' => 'A request from the Hunter Guild calling on you to defeat the giant monsters in the Field of Silence and the Field of Whispers. The request can be accepted by characters between Lv. 92-102. Double-click to receive the request',
    'is_trade' => 0,
    'is_drop' => 0,
    'is_destruct' => 1,
    'crystal_type' => 'none',
    'consume_type' => 'consume_type_normal',
  ],
  47522 => 
  [
    'item_id' => 47522,
    'icon' => 'hunter_comminssion_paper',
    'name' => 'Request - The Immortal Plateau',
    'additionalname' => '',
    'description' => 'A request from the Hunter Guild calling on you to defeat the giant monsters in the Immortal Plateau. The request can be accepted by characters between Lv. 93-103. Double-click to receive the request',
    'is_trade' => 0,
    'is_drop' => 0,
    'is_destruct' => 1,
    'crystal_type' => 'none',
    'consume_type' => 'consume_type_normal',
  ],
  47523 => 
  [
    'item_id' => 47523,
    'icon' => 'hunter_comminssion_paper',
    'name' => 'Request - Isle of Souls',
    'additionalname' => '',
    'description' => 'A request from the Hunter Guild calling on you to defeat the giant monsters in the Isle of Souls. The request can be accepted by characters between Lv. 93-103. Double-click to receive the request',
    'is_trade' => 0,
    'is_drop' => 0,
    'is_destruct' => 1,
    'crystal_type' => 'none',
    'consume_type' => 'consume_type_normal',
  ],
  47524 => 
  [
    'item_id' => 47524,
    'icon' => 'hunter_comminssion_paper',
    'name' => 'Request - Cemetery',
    'additionalname' => '',
    'description' => 'A request from the Hunter Guild calling on you to defeat the giant monsters in the Seal of Shilen and the Cemetery. The request can be accepted by characters between Lv. 93-103. Double-click to receive the request',
    'is_trade' => 0,
    'is_drop' => 0,
    'is_destruct' => 1,
    'crystal_type' => 'none',
    'consume_type' => 'consume_type_normal',
  ],
  47525 => 
  [
    'item_id' => 47525,
    'icon' => 'hunter_comminssion_paper',
    'name' => 'Request - Valley of Saints',
    'additionalname' => '',
    'description' => 'A request from the Hunter Guild calling on you to defeat the giant monsters in the Valley of Saints. The request can be accepted by characters between Lv. 93-103. Double-click to receive the request',
    'is_trade' => 0,
    'is_drop' => 0,
    'is_destruct' => 1,
    'crystal_type' => 'none',
    'consume_type' => 'consume_type_normal',
  ],
  47526 => 
  [
    'item_id' => 47526,
    'icon' => 'hunter_comminssion_paper',
    'name' => 'Request - Southern Region, Isle of Prayer',
    'additionalname' => '',
    'description' => 'A request from the Hunter Guild calling on you to defeat the giant monsters in the southern region of Isle of Prayer. The request can be accepted by characters between Lv. 96-106. Double-click to receive the request',
    'is_trade' => 0,
    'is_drop' => 0,
    'is_destruct' => 1,
    'crystal_type' => 'none',
    'consume_type' => 'consume_type_normal',
  ],
  47527 => 
  [
    'item_id' => 47527,
    'icon' => 'hunter_comminssion_paper',
    'name' => 'Request - Northern Region, Isle of Prayer',
    'additionalname' => '',
    'description' => 'A request from the Hunter Guild calling on you to defeat the giant monsters in the northern region of Isle of Prayer. The request can be accepted by characters between Lv. 96-106. Double-click to receive the request',
    'is_trade' => 0,
    'is_drop' => 0,
    'is_destruct' => 1,
    'crystal_type' => 'none',
    'consume_type' => 'consume_type_normal',
  ],
  47528 => 
  [
    'item_id' => 47528,
    'icon' => 'hunter_comminssion_paper',
    'name' => 'Request - Garden of Spirits',
    'additionalname' => '',
    'description' => 'A request from the Hunter Guild calling on you to defeat the giant monsters in the Garden of Spirits. The request can be accepted by characters between Lv. 98-108. Double-click to receive the request',
    'is_trade' => 0,
    'is_drop' => 0,
    'is_destruct' => 1,
    'crystal_type' => 'none',
    'consume_type' => 'consume_type_normal',
  ],
  47529 => 
  [
    'item_id' => 47529,
    'icon' => 'hunter_comminssion_paper',
    'name' => 'Request - Atelia Fortress',
    'additionalname' => '',
    'description' => 'A request from the Hunter Guild calling on you to defeat the giant monsters in the Atelia Fortress. The request can be accepted by characters between Lv. 98-108. Double-click to receive the request',
    'is_trade' => 0,
    'is_drop' => 0,
    'is_destruct' => 1,
    'crystal_type' => 'none',
    'consume_type' => 'consume_type_normal',
  ],
  47530 => 
  [
    'item_id' => 47530,
    'icon' => 'hunter_comminssion_paper',
    'name' => 'Request - Altar of Evil',
    'additionalname' => '',
    'description' => 'A request from the Hunter Guild calling on you to defeat the giant monsters in the Bloody Swampland and the Altar of Evil.',
    'is_trade' => 0,
    'is_drop' => 0,
    'is_destruct' => 1,
    'crystal_type' => 'none',
    'consume_type' => 'consume_type_stackable',
  ],
  47531 => 
  [
    'item_id' => 47531,
    'icon' => 'hunter_comminssion_paper',
    'name' => 'Request - Gludio Territory',
    'additionalname' => '',
    'description' => 'A request from the Hunter Guild calling on you to defeat the giant monsters in the Gludio Territory.',
    'is_trade' => 0,
    'is_drop' => 0,
    'is_destruct' => 1,
    'crystal_type' => 'none',
    'consume_type' => 'consume_type_stackable',
  ],
  47532 => 
  [
    'item_id' => 47532,
    'icon' => 'hunter_comminssion_paper',
    'name' => 'Request - Turek Orc Campsite',
    'additionalname' => '',
    'description' => 'A request from the Hunter Guild calling on you to defeat the giant monsters in the Turek Orc Campsite.',
    'is_trade' => 0,
    'is_drop' => 0,
    'is_destruct' => 1,
    'crystal_type' => 'none',
    'consume_type' => 'consume_type_stackable',
  ],
  47533 => 
  [
    'item_id' => 47533,
    'icon' => 'hunter_comminssion_paper',
    'name' => 'Request - Elven Forest',
    'additionalname' => '',
    'description' => 'A request from the Hunter Guild calling on you to defeat the giant monsters in the Elven Forest and the Shadow of the Mother Tree.',
    'is_trade' => 0,
    'is_drop' => 0,
    'is_destruct' => 1,
    'crystal_type' => 'none',
    'consume_type' => 'consume_type_stackable',
  ],
  47534 => 
  [
    'item_id' => 47534,
    'icon' => 'hunter_comminssion_paper',
    'name' => 'Request - Fairy Settlement',
    'additionalname' => '',
    'description' => 'A request from the Hunter Guild calling on you to defeat the giant monsters in the Fairy Settlement.',
    'is_trade' => 0,
    'is_drop' => 0,
    'is_destruct' => 1,
    'crystal_type' => 'none',
    'consume_type' => 'consume_type_stackable',
  ],
  47535 => 
  [
    'item_id' => 47535,
    'icon' => 'hunter_comminssion_paper',
    'name' => 'Request - Garden of Beasts',
    'additionalname' => '',
    'description' => 'A request from the Hunter Guild calling on you to defeat the giant monsters in the Garden of Beasts.',
    'is_trade' => 0,
    'is_drop' => 0,
    'is_destruct' => 1,
    'crystal_type' => 'none',
    'consume_type' => 'consume_type_stackable',
  ],
  47536 => 
  [
    'item_id' => 47536,
    'icon' => 'hunter_comminssion_paper',
    'name' => 'Request - North of the Town of Giran',
    'additionalname' => '',
    'description' => 'A request from the Hunter Guild calling on you to defeat the giant monsters in the Gorgon Flower Garden and the Breka\'s Stronghold.',
    'is_trade' => 0,
    'is_drop' => 0,
    'is_destruct' => 1,
    'crystal_type' => 'none',
    'consume_type' => 'consume_type_stackable',
  ],
  47537 => 
  [
    'item_id' => 47537,
    'icon' => 'hunter_comminssion_paper',
    'name' => 'Request - Cruma Marshlands',
    'additionalname' => '',
    'description' => 'A request from the Hunter Guild calling on you to defeat the giant monsters in the Bloody Swampland.',
    'is_trade' => 0,
    'is_drop' => 0,
    'is_destruct' => 1,
    'crystal_type' => 'none',
    'consume_type' => 'consume_type_stackable',
  ],
  47538 => 
  [
    'item_id' => 47538,
    'icon' => 'hunter_comminssion_paper',
    'name' => 'Request - The Fields',
    'additionalname' => '',
    'description' => 'A request from the Hunter Guild calling on you to defeat the giant monsters in the Field of Silence and the Field of Whispers.',
    'is_trade' => 0,
    'is_drop' => 0,
    'is_destruct' => 1,
    'crystal_type' => 'none',
    'consume_type' => 'consume_type_stackable',
  ],
  47539 => 
  [
    'item_id' => 47539,
    'icon' => 'hunter_comminssion_paper',
    'name' => 'Request - The Immortal Plateau',
    'additionalname' => '',
    'description' => 'A request from the Hunter Guild calling on you to defeat the giant monsters in the Immortal Plateau.',
    'is_trade' => 0,
    'is_drop' => 0,
    'is_destruct' => 1,
    'crystal_type' => 'none',
    'consume_type' => 'consume_type_stackable',
  ],
  47540 => 
  [
    'item_id' => 47540,
    'icon' => 'hunter_comminssion_paper',
    'name' => 'Request - Isle of Souls',
    'additionalname' => '',
    'description' => 'A request from the Hunter Guild calling on you to defeat the giant monsters in the Isle of Souls.',
    'is_trade' => 0,
    'is_drop' => 0,
    'is_destruct' => 1,
    'crystal_type' => 'none',
    'consume_type' => 'consume_type_stackable',
  ],
  47541 => 
  [
    'item_id' => 47541,
    'icon' => 'hunter_comminssion_paper',
    'name' => 'Request - Cemetery',
    'additionalname' => '',
    'description' => 'A request from the Hunter Guild calling on you to defeat the giant monsters in the Seal of Shilen and the Cemetery.',
    'is_trade' => 0,
    'is_drop' => 0,
    'is_destruct' => 1,
    'crystal_type' => 'none',
    'consume_type' => 'consume_type_stackable',
  ],
  47542 => 
  [
    'item_id' => 47542,
    'icon' => 'hunter_comminssion_paper',
    'name' => 'Request - Valley of Saints',
    'additionalname' => '',
    'description' => 'A request from the Hunter Guild calling on you to defeat the giant monsters in the Valley of Saints.',
    'is_trade' => 0,
    'is_drop' => 0,
    'is_destruct' => 1,
    'crystal_type' => 'none',
    'consume_type' => 'consume_type_stackable',
  ],
  47543 => 
  [
    'item_id' => 47543,
    'icon' => 'hunter_comminssion_paper',
    'name' => 'Request - Southern Region, Isle of Prayer',
    'additionalname' => '',
    'description' => 'A request from the Hunter Guild calling on you to defeat the giant monsters in the southern region of Isle of Prayer.',
    'is_trade' => 0,
    'is_drop' => 0,
    'is_destruct' => 1,
    'crystal_type' => 'none',
    'consume_type' => 'consume_type_stackable',
  ],
  47544 => 
  [
    'item_id' => 47544,
    'icon' => 'hunter_comminssion_paper',
    'name' => 'Request - Northern Region, Isle of Prayer',
    'additionalname' => '',
    'description' => 'A request from the Hunter Guild calling on you to defeat the giant monsters in the northern region of Isle of Prayer.',
    'is_trade' => 0,
    'is_drop' => 0,
    'is_destruct' => 1,
    'crystal_type' => 'none',
    'consume_type' => 'consume_type_stackable',
  ],
  47545 => 
  [
    'item_id' => 47545,
    'icon' => 'hunter_comminssion_paper',
    'name' => 'Request - Garden of Spirits',
    'additionalname' => '',
    'description' => 'A request from the Hunter Guild calling on you to defeat the giant monsters in the Garden of Spirits.',
    'is_trade' => 0,
    'is_drop' => 0,
    'is_destruct' => 1,
    'crystal_type' => 'none',
    'consume_type' => 'consume_type_stackable',
  ],
  47546 => 
  [
    'item_id' => 47546,
    'icon' => 'hunter_comminssion_paper',
    'name' => 'Request - Atelia Fortress',
    'additionalname' => '',
    'description' => 'A request from the Hunter Guild calling on you to defeat the giant monsters in the Atelia Fortress.',
    'is_trade' => 0,
    'is_drop' => 0,
    'is_destruct' => 1,
    'crystal_type' => 'none',
    'consume_type' => 'consume_type_stackable',
  ],
  47547 => 
  [
    'item_id' => 47547,
    'icon' => 'etc_normal_lure',
    'name' => 'Bait',
    'additionalname' => '',
    'description' => 'Fishing time: 105 seconds
Standby time: 15 seconds

Standard Fishing Bait. Fish using this bait to catch a Blueish Box with low probability.',
    'is_trade' => 1,
    'is_drop' => 1,
    'is_destruct' => 1,
    'crystal_type' => 'none',
    'consume_type' => 'consume_type_stackable',
  ],
  47548 => 
  [
    'item_id' => 47548,
    'icon' => 'etc_huge_lure',
    'name' => 'Bait',
    'additionalname' => 'R99',
    'description' => 'Fishing time: 105 seconds
Standby time: 15 seconds

Fishing bait that can be used by characters of Level 99 or higher. Fish using this bait to catch a Reddish Box with low probability.',
    'is_trade' => 1,
    'is_drop' => 1,
    'is_destruct' => 1,
    'crystal_type' => 'none',
    'consume_type' => 'consume_type_stackable',
  ],
  47549 => 
  [
    'item_id' => 47549,
    'icon' => 'etc_bait_i01',
    'name' => 'PC Cafe Bait',
    'additionalname' => '',
    'description' => 'Fishing time: 105 seconds
Standby time: 15 seconds

Special Fishing Bait. Fish using this bait to catch a Purplish Box with low probability. Can be used outside PC Cafes.',
    'is_trade' => 0,
    'is_drop' => 0,
    'is_destruct' => 1,
    'crystal_type' => 'none',
    'consume_type' => 'consume_type_stackable',
  ],
  47550 => 
  [
    'item_id' => 47550,
    'icon' => 'etc_angler_i01',
    'name' => 'Ugly Fish',
    'additionalname' => '',
    'description' => 'Can be exchanged for a Fish Stew item through a Fishing Guild member.',
    'is_trade' => 1,
    'is_drop' => 1,
    'is_destruct' => 1,
    'crystal_type' => 'none',
    'consume_type' => 'consume_type_stackable',
  ],
  47551 => 
  [
    'item_id' => 47551,
    'icon' => 'etc_tuna_i01',
    'name' => 'Nimble Fish',
    'additionalname' => '',
    'description' => 'Can be exchanged for a Fish Stew item or Appearance Stone item through a Fishing Guild member.',
    'is_trade' => 1,
    'is_drop' => 1,
    'is_destruct' => 1,
    'crystal_type' => 'none',
    'consume_type' => 'consume_type_stackable',
  ],
  47552 => 
  [
    'item_id' => 47552,
    'icon' => 'etc_bream_i01',
    'name' => 'Powerful Fish',
    'additionalname' => '',
    'description' => 'Can be exchanged for a Stardust item or hair accessories through a Fishing Guild member.',
    'is_trade' => 1,
    'is_drop' => 1,
    'is_destruct' => 1,
    'crystal_type' => 'none',
    'consume_type' => 'consume_type_stackable',
  ],
  47553 => 
  [
    'item_id' => 47553,
    'icon' => 'etc_treasure_box_i01',
    'name' => 'Blueish Box',
    'additionalname' => '',
    'description' => 'Double click to obtain the item.',
    'is_trade' => 0,
    'is_drop' => 0,
    'is_destruct' => 1,
    'crystal_type' => 'none',
    'consume_type' => 'consume_type_stackable',
  ],
  47554 => 
  [
    'item_id' => 47554,
    'icon' => 'etc_treasure_box_i03',
    'name' => 'Reddish Box',
    'additionalname' => '',
    'description' => 'Double click to obtain the item.',
    'is_trade' => 0,
    'is_drop' => 0,
    'is_destruct' => 1,
    'crystal_type' => 'none',
    'consume_type' => 'consume_type_stackable',
  ],
  47555 => 
  [
    'item_id' => 47555,
    'icon' => 'etc_treasure_box_i04',
    'name' => 'Purplish Box',
    'additionalname' => '',
    'description' => 'Double click to obtain the item.',
    'is_trade' => 0,
    'is_drop' => 0,
    'is_destruct' => 1,
    'crystal_type' => 'none',
    'consume_type' => 'consume_type_stackable',
  ],
  47556 => 
  [
    'item_id' => 47556,
    'icon' => 'star_crystal_piece',
    'name' => 'Stardust',
    'additionalname' => '',
    'description' => 'Ingredient used to produce the Zodiac Agathion',
    'is_trade' => 1,
    'is_drop' => 1,
    'is_destruct' => 1,
    'crystal_type' => 'none',
    'consume_type' => 'consume_type_stackable',
  ],
  47557 => 
  [
    'item_id' => 47557,
    'icon' => 'fishing_rod01',
    'name' => 'Master Fishing Rod',
    'additionalname' => 'Stage 1',
    'description' => 'Fishing time reduced by: 10 seconds

A fishing rod modified personally by Santiago, head of the Fishing Guild. Engraved with the name of a legendary master angler of the east. Fishing Shots consumed: 1',
    'is_trade' => 0,
    'is_drop' => 0,
    'is_destruct' => 1,
    'crystal_type' => 'none',
    'consume_type' => 'consume_type_normal',
  ],
  47558 => 
  [
    'item_id' => 47558,
    'icon' => 'fishing_rod02',
    'name' => 'Master Fishing Rod',
    'additionalname' => 'Stage 2',
    'description' => 'Fishing time reduced by: 15 seconds

A fishing rod modified personally by Santiago, head of the Fishing Guild. Engraved with the name of a legendary master angler of the east. Fishing Shots consumed: 1',
    'is_trade' => 0,
    'is_drop' => 0,
    'is_destruct' => 1,
    'crystal_type' => 'none',
    'consume_type' => 'consume_type_normal',
  ],
  47559 => 
  [
    'item_id' => 47559,
    'icon' => 'fishing_rod03',
    'name' => 'Master Fishing Rod',
    'additionalname' => 'Stage 3',
    'description' => 'Fishing time reduced by: 20 seconds

A fishing rod modified personally by Santiago, head of the Fishing Guild. Engraved with the name of a legendary master angler of the east. Fishing Shots consumed: 1',
    'is_trade' => 0,
    'is_drop' => 0,
    'is_destruct' => 1,
    'crystal_type' => 'none',
    'consume_type' => 'consume_type_normal',
  ],
  47560 => 
  [
    'item_id' => 47560,
    'icon' => 'fishing_rod04',
    'name' => 'Master Fishing Rod',
    'additionalname' => 'Stage 4',
    'description' => 'Fishing time reduced by: 25 seconds

A fishing rod modified personally by Santiago, head of the Fishing Guild. Engraved with the name of a legendary master angler of the east. Fishing Shots consumed: 1',
    'is_trade' => 0,
    'is_drop' => 0,
    'is_destruct' => 1,
    'crystal_type' => 'none',
    'consume_type' => 'consume_type_normal',
  ],
  47561 => 
  [
    'item_id' => 47561,
    'icon' => 'fishing_rod05',
    'name' => 'Master Fishing Rod',
    'additionalname' => 'Stage 5',
    'description' => 'Fishing time reduced by: 30 seconds

A fishing rod modified personally by Santiago, head of the Fishing Guild. Engraved with the name of a legendary master angler of the east. Fishing Shots consumed: 1',
    'is_trade' => 0,
    'is_drop' => 0,
    'is_destruct' => 1,
    'crystal_type' => 'none',
    'consume_type' => 'consume_type_normal',
  ],
  47562 => 
  [
    'item_id' => 47562,
    'icon' => 'etc_power_of_soul',
    'name' => 'Santiago\'s Reel Fragment',
    'additionalname' => '',
    'description' => 'Ingredient necessary for production of the Master Fishing Rod. Also needed when leveling up the Master Fishing Rod.',
    'is_trade' => 0,
    'is_drop' => 0,
    'is_destruct' => 1,
    'crystal_type' => 'none',
    'consume_type' => 'consume_type_stackable',
  ],
  47563 => 
  [
    'item_id' => 47563,
    'icon' => 'etc_exchange_box_i00',
    'name' => 'Zodiac Agathion Box',
    'additionalname' => '',
    'description' => 'Double click to obtain one of the 12 types of Zodiac Agathion Stage 1.',
    'is_trade' => 1,
    'is_drop' => 1,
    'is_destruct' => 1,
    'crystal_type' => 'none',
    'consume_type' => 'consume_type_stackable',
  ],
  47564 => 
  [
    'item_id' => 47564,
    'icon' => 'etc_readybox_gold',
    'name' => 'Reward for Defeating the Giant Monsters',
    'additionalname' => '',
    'description' => 'A reward given by the Hunter Guild for completing the mission to defeat the giant monsters. Double click to obtain the item.',
    'is_trade' => 0,
    'is_drop' => 0,
    'is_destruct' => 1,
    'crystal_type' => 'none',
    'consume_type' => 'consume_type_stackable',
  ],
  47565 => 
  [
    'item_id' => 47565,
    'icon' => 'etc_readybox_gold',
    'name' => 'Reward for Defeating the Giant Monsters',
    'additionalname' => '',
    'description' => 'A reward given by the Hunter Guild for completing the mission to defeat the giant monsters. Double click to obtain the item.',
    'is_trade' => 0,
    'is_drop' => 0,
    'is_destruct' => 1,
    'crystal_type' => 'none',
    'consume_type' => 'consume_type_stackable',
  ],
  47566 => 
  [
    'item_id' => 47566,
    'icon' => 'etc_readybox_gold',
    'name' => 'Reward for Defeating the Giant Monsters',
    'additionalname' => '',
    'description' => 'A reward given by the Hunter Guild for completing the mission to defeat the giant monsters. Double click to obtain the item.',
    'is_trade' => 0,
    'is_drop' => 0,
    'is_destruct' => 1,
    'crystal_type' => 'none',
    'consume_type' => 'consume_type_stackable',
  ],
  47567 => 
  [
    'item_id' => 47567,
    'icon' => 'etc_readybox_gold',
    'name' => 'Reward for Defeating the Giant Monsters',
    'additionalname' => '',
    'description' => 'A reward given by the Hunter Guild for completing the mission to defeat the giant monsters. Double click to obtain the item.',
    'is_trade' => 0,
    'is_drop' => 0,
    'is_destruct' => 1,
    'crystal_type' => 'none',
    'consume_type' => 'consume_type_stackable',
  ],
  47568 => 
  [
    'item_id' => 47568,
    'icon' => 'etc_readybox_gold',
    'name' => 'Reward for Defeating the Giant Monsters',
    'additionalname' => '',
    'description' => 'A reward given by the Hunter Guild for completing the mission to defeat the giant monsters. Double click to obtain the item.',
    'is_trade' => 0,
    'is_drop' => 0,
    'is_destruct' => 1,
    'crystal_type' => 'none',
    'consume_type' => 'consume_type_stackable',
  ],
  47569 => 
  [
    'item_id' => 47569,
    'icon' => 'etc_readybox_gold',
    'name' => 'Reward for Defeating the Giant Monsters',
    'additionalname' => '',
    'description' => 'A reward given by the Hunter Guild for completing the mission to defeat the giant monsters. Double click to obtain the item.',
    'is_trade' => 0,
    'is_drop' => 0,
    'is_destruct' => 1,
    'crystal_type' => 'none',
    'consume_type' => 'consume_type_stackable',
  ],
  47570 => 
  [
    'item_id' => 47570,
    'icon' => 'etc_readybox_gold',
    'name' => 'Reward for Defeating the Giant Monsters',
    'additionalname' => '',
    'description' => 'A reward given by the Hunter Guild for completing the mission to defeat the giant monsters. Double click to obtain the item.',
    'is_trade' => 0,
    'is_drop' => 0,
    'is_destruct' => 1,
    'crystal_type' => 'none',
    'consume_type' => 'consume_type_stackable',
  ],
  47571 => 
  [
    'item_id' => 47571,
    'icon' => 'etc_readybox_bronze',
    'name' => 'Basic Supply Box',
    'additionalname' => 'Fishing Guild',
    'description' => 'A supply box given by Santiago, head of the Fishing Guild, for your hard work in reviving the Fishing Guild. Double click to obtain the item.',
    'is_trade' => 0,
    'is_drop' => 0,
    'is_destruct' => 1,
    'crystal_type' => 'none',
    'consume_type' => 'consume_type_stackable',
  ],
  47572 => 
  [
    'item_id' => 47572,
    'icon' => 'etc_readybox_silver',
    'name' => 'Intermediate Supply Box',
    'additionalname' => 'Fishing Guild',
    'description' => 'A supply box given by Santiago, head of the Fishing Guild, for your sustained effort toward reviving the Fishing Guild. Double click to obtain the item.',
    'is_trade' => 0,
    'is_drop' => 0,
    'is_destruct' => 1,
    'crystal_type' => 'none',
    'consume_type' => 'consume_type_stackable',
  ],
  47573 => 
  [
    'item_id' => 47573,
    'icon' => 'etc_powder_orange_i00',
    'name' => 'Magic Spices',
    'additionalname' => '',
    'description' => 'Spices created by Santiago and the numerous famous chefs of the Aden Continent through their Fish Stew research. With these spices and a fish, Fish Stew with excellent performance can be made.',
    'is_trade' => 0,
    'is_drop' => 0,
    'is_destruct' => 1,
    'crystal_type' => 'none',
    'consume_type' => 'consume_type_stackable',
  ],
  47574 => 
  [
    'item_id' => 47574,
    'icon' => 'new_user_box',
    'name' => 'PC Cafe Treasure Chest',
    'additionalname' => '',
    'description' => 'Double click to obtain the item.',
    'is_trade' => 0,
    'is_drop' => 0,
    'is_destruct' => 1,
    'crystal_type' => 'none',
    'consume_type' => 'consume_type_stackable',
  ],
  47575 => 
  [
    'item_id' => 47575,
    'icon' => 'bm_royal_white_save_ticket',
    'name' => 'Royal White Save Ticket (R]',
    'additionalname' => '',
    'description' => 'A ticket that enhances probability by 15% when using a Normal Armor Enchant Scroll to enchant R-grade Armor. Can only be used on 3-9 enchanted items. When Enchant fails, the item does not crystallize, but the existing enchant level decreases by 1.',
    'is_trade' => 1,
    'is_drop' => 1,
    'is_destruct' => 1,
    'crystal_type' => 'none',
    'consume_type' => 'consume_type_stackable',
  ],
  47576 => 
  [
    'item_id' => 47576,
    'icon' => 'bm_royal_white_save_ticket',
    'name' => 'Royal White Save Ticket (R95]',
    'additionalname' => '',
    'description' => 'A ticket that enhances probability by 15% when using a Normal Armor Enchant Scroll to enchant R95 grade Armor. Can only be used on 3-9 enchanted items. When Enchant fails, the item does not crystallize, but the existing enchant level decreases by 1.',
    'is_trade' => 1,
    'is_drop' => 1,
    'is_destruct' => 1,
    'crystal_type' => 'none',
    'consume_type' => 'consume_type_stackable',
  ],
  47577 => 
  [
    'item_id' => 47577,
    'icon' => 'bm_royal_white_save_ticket',
    'name' => 'Royal White Save Ticket (R99]',
    'additionalname' => '',
    'description' => 'A ticket that enhances probability by 15% when using a Normal Armor Enchant Scroll to enchant R99 grade Armor. Can only be used on 3-9 enchanted items. When Enchant fails, the item does not crystallize, but the existing enchant level decreases by 1.',
    'is_trade' => 1,
    'is_drop' => 1,
    'is_destruct' => 1,
    'crystal_type' => 'none',
    'consume_type' => 'consume_type_stackable',
  ],
  47578 => 
  [
    'item_id' => 47578,
    'icon' => 'bm_grankain_potion',
    'name' => 'Gran Kain\'s Miraculous Medicine',
    'additionalname' => '',
    'description' => 'Legendary Miraculous Medicine said to have been concocted using a secret passed on by Gran Kain.
Use to recover 7000 HP; the remaining effect of the medicine recovers your CP. 
Can be used in Mass state.
Cannot be used in the Olympiad.',
    'is_trade' => 1,
    'is_drop' => 1,
    'is_destruct' => 1,
    'crystal_type' => 'none',
    'consume_type' => 'consume_type_stackable',
  ],
  47579 => 
  [
    'item_id' => 47579,
    'icon' => 'general_fuel_i00',
    'name' => 'Christmas Party Herb',
    'additionalname' => '',
    'description' => 'Christmas Party Herb. P. Atk./M. Atk./P. Def./M. Def. are increased by 50%, and you are turned into Santa for 2 minutes. Effect disappears when restarted.',
    'is_trade' => 1,
    'is_drop' => 1,
    'is_destruct' => 1,
    'crystal_type' => 'none',
    'consume_type' => 'consume_type_stackable',
  ],
  47580 => 
  [
    'item_id' => 47580,
    'icon' => 'weapon_fishing_rod_i00',
    'name' => 'Practice Fishing Rod',
    'additionalname' => '1-hour',
    'description' => 'A shoddy fishing rod that has been given to you for practice. It\'s fine for practice, though.',
    'is_trade' => 0,
    'is_drop' => 0,
    'is_destruct' => 1,
    'crystal_type' => 'none',
    'consume_type' => 'consume_type_normal',
  ],
  47581 => 
  [
    'item_id' => 47581,
    'icon' => 'etc_scroll_white_i00',
    'name' => 'Transformation Scroll: Tow',
    'additionalname' => '',
    'description' => 'No special abilities, but allows you to transform into Tow for 10 minutes. Cannot be used in the Olympiad.',
    'is_trade' => 1,
    'is_drop' => 1,
    'is_destruct' => 1,
    'crystal_type' => 'none',
    'consume_type' => 'consume_type_stackable',
  ],
  47582 => 
  [
    'item_id' => 47582,
    'icon' => 'etc_scroll_white_i00',
    'name' => 'Transformation Scroll: Lady Tow',
    'additionalname' => '',
    'description' => 'No special abilities, but allows you to transform into Lady Tow for 10 minutes. Cannot be used in the Olympiad.',
    'is_trade' => 1,
    'is_drop' => 1,
    'is_destruct' => 1,
    'crystal_type' => 'none',
    'consume_type' => 'consume_type_stackable',
  ],
  47583 => 
  [
    'item_id' => 47583,
    'icon' => 'etc_scroll_white_i00',
    'name' => 'Transformation Scroll: Angry Tow',
    'additionalname' => '',
    'description' => 'No special abilities, but allows you to transform into Angry tow for 10 minutes. Cannot be used in the Olympiad.',
    'is_trade' => 1,
    'is_drop' => 1,
    'is_destruct' => 1,
    'crystal_type' => 'none',
    'consume_type' => 'consume_type_stackable',
  ],
  47584 => 
  [
    'item_id' => 47584,
    'icon' => 'etc_scroll_white_i00',
    'name' => 'Transformation Scroll: Sleepy Tow',
    'additionalname' => '',
    'description' => 'No special abilities, but allows you to transform into Sleepy Tow for 10 minutes. Cannot be used in the Olympiad.',
    'is_trade' => 1,
    'is_drop' => 1,
    'is_destruct' => 1,
    'crystal_type' => 'none',
    'consume_type' => 'consume_type_stackable',
  ],
  47585 => 
  [
    'item_id' => 47585,
    'icon' => 'etc_scroll_white_i00',
    'name' => 'Transformation Scroll: Pig',
    'additionalname' => '',
    'description' => 'No special abilities, but allows you to transform into a pig for 10 minutes. Cannot be used in the Olympiad.',
    'is_trade' => 1,
    'is_drop' => 1,
    'is_destruct' => 1,
    'crystal_type' => 'none',
    'consume_type' => 'consume_type_stackable',
  ],
  47586 => 
  [
    'item_id' => 47586,
    'icon' => 'etc_scroll_white_i00',
    'name' => 'Transformation Scroll: Rabbit',
    'additionalname' => '',
    'description' => 'No special abilities, but allows you to transform into a rabbit for 10 minutes. Cannot be used in the Olympiad.',
    'is_trade' => 1,
    'is_drop' => 1,
    'is_destruct' => 1,
    'crystal_type' => 'none',
    'consume_type' => 'consume_type_stackable',
  ],
  47587 => 
  [
    'item_id' => 47587,
    'icon' => 'etc_scroll_white_i00',
    'name' => 'Transformation Scroll: Queen Ant',
    'additionalname' => '',
    'description' => 'No special abilities, but allows you to transform into a Queen Ant for 10 minutes. Cannot be used in the Olympiad.',
    'is_trade' => 1,
    'is_drop' => 1,
    'is_destruct' => 1,
    'crystal_type' => 'none',
    'consume_type' => 'consume_type_stackable',
  ],
  47588 => 
  [
    'item_id' => 47588,
    'icon' => 'etc_scroll_white_i00',
    'name' => 'Transformation Scroll: Orfen',
    'additionalname' => '',
    'description' => 'No special abilities, but allows you to transform into Orfen for 10 minutes. Cannot be used in the Olympiad.',
    'is_trade' => 1,
    'is_drop' => 1,
    'is_destruct' => 1,
    'crystal_type' => 'none',
    'consume_type' => 'consume_type_stackable',
  ],
  47589 => 
  [
    'item_id' => 47589,
    'icon' => 'etc_scroll_white_i00',
    'name' => 'Transformation Scroll: Anakim',
    'additionalname' => '',
    'description' => 'No special abilities, but allows you to transform into Anakim for 10 minutes. Cannot be used in the Olympiad.',
    'is_trade' => 1,
    'is_drop' => 1,
    'is_destruct' => 1,
    'crystal_type' => 'none',
    'consume_type' => 'consume_type_stackable',
  ],
  47590 => 
  [
    'item_id' => 47590,
    'icon' => 'etc_scroll_white_i00',
    'name' => 'Transformation Scroll: Lilith',
    'additionalname' => '',
    'description' => 'No special abilities, but allows you to transform into Lilith for 10 minutes. Cannot be used in the Olympiad.',
    'is_trade' => 1,
    'is_drop' => 1,
    'is_destruct' => 1,
    'crystal_type' => 'none',
    'consume_type' => 'consume_type_stackable',
  ],
  47591 => 
  [
    'item_id' => 47591,
    'icon' => 'shape_shifting_dualfist_i00',
    'name' => 'Cat Fighter Appearance Stone - Ertheia Only',
    'additionalname' => '',
    'description' => 'An appearance stone that changes the appearance of your fist weapons into that of a Cat Fighter.

<Caution> Items whose appearance has been changed can be equipped on by Ertheia. Remember this when extracting appearances.',
    'is_trade' => 1,
    'is_drop' => 1,
    'is_destruct' => 1,
    'crystal_type' => 'none',
    'consume_type' => 'consume_type_stackable',
  ],
  47592 => 
  [
    'item_id' => 47592,
    'icon' => 'shape_shifting_dualfist_i00',
    'name' => 'Warm Bear Paws Appearance Stone',
    'additionalname' => '',
    'description' => 'An appearance stone that changes the appearance of your fist weapons in to that of Warm Bear Paws.',
    'is_trade' => 1,
    'is_drop' => 1,
    'is_destruct' => 1,
    'crystal_type' => 'none',
    'consume_type' => 'consume_type_stackable',
  ],
  47593 => 
  [
    'item_id' => 47593,
    'icon' => 'shape_shifting_dualfist_i00',
    'name' => 'Boxing Glove Appearance Stone - Ertheia Only',
    'additionalname' => '',
    'description' => 'An appearance stone that changes the appearance of your fist weapons into that of Boxing Gloves.

<Caution> Items whose appearance has been changed can be equipped on by Ertheia. Remember this when extracting appearances.',
    'is_trade' => 1,
    'is_drop' => 1,
    'is_destruct' => 1,
    'crystal_type' => 'none',
    'consume_type' => 'consume_type_stackable',
  ],
  47594 => 
  [
    'item_id' => 47594,
    'icon' => 'shape_shifting_bow_i00',
    'name' => 'Cupid\'s Arrow Appearance Stone',
    'additionalname' => '',
    'description' => 'An appearance stone that changes the appearance of your bow into Cupid\'s Bow.',
    'is_trade' => 1,
    'is_drop' => 1,
    'is_destruct' => 1,
    'crystal_type' => 'none',
    'consume_type' => 'consume_type_stackable',
  ],
  47595 => 
  [
    'item_id' => 47595,
    'icon' => 'shape_shifting_blunt_i00',
    'name' => 'Wedding Bouquet Appearance Stone',
    'additionalname' => '',
    'description' => 'An appearance stone that changes the appearance of your one-handed Blunt Weapon into that of a Wedding Bouquet.',
    'is_trade' => 1,
    'is_drop' => 1,
    'is_destruct' => 1,
    'crystal_type' => 'none',
    'consume_type' => 'consume_type_stackable',
  ],
  47596 => 
  [
    'item_id' => 47596,
    'icon' => 'shape_shifting_sword_i00',
    'name' => 'Pig Lollipop Appearance Stone',
    'additionalname' => '',
    'description' => 'An appearance stone that changes the appearance of your one-handed Dagger into that of a Pig Lollipop.',
    'is_trade' => 1,
    'is_drop' => 1,
    'is_destruct' => 1,
    'crystal_type' => 'none',
    'consume_type' => 'consume_type_stackable',
  ],
  47597 => 
  [
    'item_id' => 47597,
    'icon' => 'br_wedding_bouquet_i00',
    'name' => 'Wedding Bouquet',
    'additionalname' => '',
    'description' => '',
    'is_trade' => 1,
    'is_drop' => 1,
    'is_destruct' => 1,
    'crystal_type' => 'none',
    'consume_type' => 'consume_type_normal',
  ],
  47598 => 
  [
    'item_id' => 47598,
    'icon' => 'bm_krono_bow',
    'name' => 'Cupid\'s Bow',
    'additionalname' => '',
    'description' => '',
    'is_trade' => 1,
    'is_drop' => 1,
    'is_destruct' => 1,
    'crystal_type' => 'none',
    'consume_type' => 'consume_type_normal',
  ],
  47599 => 
  [
    'item_id' => 47599,
    'icon' => 'bm_pig_candy',
    'name' => 'Pig Lollipop',
    'additionalname' => '',
    'description' => '',
    'is_trade' => 1,
    'is_drop' => 1,
    'is_destruct' => 1,
    'crystal_type' => 'none',
    'consume_type' => 'consume_type_normal',
  ],
];