<?php return [
  6600 => 
  [
    'item_id' => 6600,
    'icon' => 'weapon_saint_spear_i01',
    'name' => 'Saint Spear',
    'additionalname' => 'Guidance',
    'description' => 'Not used',
    'is_trade' => 1,
    'is_drop' => 1,
    'is_destruct' => 1,
    'crystal_type' => 's',
    'consume_type' => 'consume_type_normal',
  ],
  6601 => 
  [
    'item_id' => 6601,
    'icon' => 'weapon_saint_spear_i01',
    'name' => 'Saint Spear',
    'additionalname' => 'Haste',
    'description' => 'Not used',
    'is_trade' => 1,
    'is_drop' => 1,
    'is_destruct' => 1,
    'crystal_type' => 's',
    'consume_type' => 'consume_type_normal',
  ],
  6602 => 
  [
    'item_id' => 6602,
    'icon' => 'weapon_demon_splinter_i01',
    'name' => 'Demon Splinter',
    'additionalname' => 'Focus',
    'description' => 'Not used',
    'is_trade' => 1,
    'is_drop' => 1,
    'is_destruct' => 1,
    'crystal_type' => 's',
    'consume_type' => 'consume_type_normal',
  ],
  6603 => 
  [
    'item_id' => 6603,
    'icon' => 'weapon_demon_splinter_i01',
    'name' => 'Demon Splinter',
    'additionalname' => 'Health',
    'description' => 'Not used',
    'is_trade' => 1,
    'is_drop' => 1,
    'is_destruct' => 1,
    'crystal_type' => 's',
    'consume_type' => 'consume_type_normal',
  ],
  6604 => 
  [
    'item_id' => 6604,
    'icon' => 'weapon_demon_splinter_i01',
    'name' => 'Demon Splinter',
    'additionalname' => 'Critical Stun',
    'description' => 'Not used',
    'is_trade' => 1,
    'is_drop' => 1,
    'is_destruct' => 1,
    'crystal_type' => 's',
    'consume_type' => 'consume_type_normal',
  ],
  6605 => 
  [
    'item_id' => 6605,
    'icon' => 'weapon_heavens_divider_i01',
    'name' => 'Heavens Divider',
    'additionalname' => 'Haste',
    'description' => 'Not used',
    'is_trade' => 1,
    'is_drop' => 1,
    'is_destruct' => 1,
    'crystal_type' => 's',
    'consume_type' => 'consume_type_normal',
  ],
  6606 => 
  [
    'item_id' => 6606,
    'icon' => 'weapon_heavens_divider_i01',
    'name' => 'Heavens Divider',
    'additionalname' => 'Health',
    'description' => 'Not used',
    'is_trade' => 1,
    'is_drop' => 1,
    'is_destruct' => 1,
    'crystal_type' => 's',
    'consume_type' => 'consume_type_normal',
  ],
  6607 => 
  [
    'item_id' => 6607,
    'icon' => 'weapon_heavens_divider_i01',
    'name' => 'Heavens Divider',
    'additionalname' => 'Focus',
    'description' => 'Not used',
    'is_trade' => 1,
    'is_drop' => 1,
    'is_destruct' => 1,
    'crystal_type' => 's',
    'consume_type' => 'consume_type_normal',
  ],
  6608 => 
  [
    'item_id' => 6608,
    'icon' => 'weapon_arcana_mace_i01',
    'name' => 'Arcana Mace',
    'additionalname' => 'Acumen',
    'description' => 'Not used',
    'is_trade' => 1,
    'is_drop' => 1,
    'is_destruct' => 1,
    'crystal_type' => 's',
    'consume_type' => 'consume_type_normal',
  ],
  6609 => 
  [
    'item_id' => 6609,
    'icon' => 'weapon_arcana_mace_i01',
    'name' => 'Arcana Mace',
    'additionalname' => 'MP Regeneration',
    'description' => 'Not used',
    'is_trade' => 1,
    'is_drop' => 1,
    'is_destruct' => 1,
    'crystal_type' => 's',
    'consume_type' => 'consume_type_normal',
  ],
  6610 => 
  [
    'item_id' => 6610,
    'icon' => 'weapon_arcana_mace_i01',
    'name' => 'Arcana Mace',
    'additionalname' => 'Mana Up',
    'description' => 'Not used',
    'is_trade' => 1,
    'is_drop' => 1,
    'is_destruct' => 1,
    'crystal_type' => 's',
    'consume_type' => 'consume_type_normal',
  ],
  6611 => 
  [
    'item_id' => 6611,
    'icon' => 'weapon_the_sword_of_hero_i00',
    'name' => 'Infinity Blade',
    'additionalname' => NULL,
    'description' => 'Divine heros weapon. After a critical attack, casts a P. Def.-decreasing debuff on the target. Increases Max HP/ MP/ CP and Shield Defense. With a certain chance, reflects debuffs back to the enemy. Deals additional PvP damage.',
    'is_trade' => 0,
    'is_drop' => 0,
    'is_destruct' => 0,
    'crystal_type' => 's',
    'consume_type' => 'consume_type_normal',
  ],
  6612 => 
  [
    'item_id' => 6612,
    'icon' => 'weapon_the_two_handed_sword_of_hero_i00',
    'name' => 'Infinity Cleaver',
    'additionalname' => NULL,
    'description' => 'Divine heros weapon. Increases Critical Rate/ Damage for basic attacks, Max HP, Max CP. Deals additional PvP damage. With a certain chance, reflects debuffs back to the enemy.',
    'is_trade' => 0,
    'is_drop' => 0,
    'is_destruct' => 0,
    'crystal_type' => 's',
    'consume_type' => 'consume_type_normal',
  ],
  6613 => 
  [
    'item_id' => 6613,
    'icon' => 'weapon_the_axe_of_hero_i00',
    'name' => 'Infinity Axe',
    'additionalname' => NULL,
    'description' => 'Divine heros weapon. After a critical attack, reflects a part of the damage and inflicts Confusion on the target. Increases Shield Defense Rate and Max HP/ MP/ CP. Inflicts additional PvP Damage.',
    'is_trade' => 0,
    'is_drop' => 0,
    'is_destruct' => 0,
    'crystal_type' => 's',
    'consume_type' => 'consume_type_normal',
  ],
  6614 => 
  [
    'item_id' => 6614,
    'icon' => 'weapon_the_mace_of_hero_i00',
    'name' => 'Infinity Rod',
    'additionalname' => NULL,
    'description' => 'Divine heros weapon. After buff casting, increases HP Recovery by 100%. Increases Max MP/ CP, Casting Spd. and MP Recovery Rate. Deals additional PvP damage.',
    'is_trade' => 0,
    'is_drop' => 0,
    'is_destruct' => 0,
    'crystal_type' => 's',
    'consume_type' => 'consume_type_normal',
  ],
  6615 => 
  [
    'item_id' => 6615,
    'icon' => 'weapon_the_hammer_of_hero_i00',
    'name' => 'Infinity Crusher',
    'additionalname' => NULL,
    'description' => 'Divine heros weapon. Increases Max HP/ CP and Atk. Spd. Stuns the target after a critical attack. With a certain chance, reflects debuffs back to the enemy. Deals additional PvP damage.',
    'is_trade' => 0,
    'is_drop' => 0,
    'is_destruct' => 0,
    'crystal_type' => 's',
    'consume_type' => 'consume_type_normal',
  ],
  6616 => 
  [
    'item_id' => 6616,
    'icon' => 'weapon_the_staff_of_hero_i00',
    'name' => 'Infinity Scepter',
    'additionalname' => NULL,
    'description' => 'Divine heros weapon. After a buff casting, has a chance of HP Recovery by 100%. Increases Max MP/ CP, M. Atk., M. Skill Critical Rate and decreases MP Consumption and Casting Interruption Rate. Inflicts additional PvP Damage.',
    'is_trade' => 0,
    'is_drop' => 0,
    'is_destruct' => 0,
    'crystal_type' => 's',
    'consume_type' => 'consume_type_normal',
  ],
  6617 => 
  [
    'item_id' => 6617,
    'icon' => 'weapon_the_dagger_of_hero_i00',
    'name' => 'Infinity Stinger',
    'additionalname' => NULL,
    'description' => 'Divine heros weapon. Increases Max MP/ Max CP, Atk. Spd. and MP Recovery Rate. Also increases success rate of Mortal Blow when backstabing. after a Critical Attack, inflicts Silence on the target and causes Vampiric Rage. Inflicts additional PvP Damage.',
    'is_trade' => 0,
    'is_drop' => 0,
    'is_destruct' => 0,
    'crystal_type' => 's',
    'consume_type' => 'consume_type_normal',
  ],
  6618 => 
  [
    'item_id' => 6618,
    'icon' => 'weapon_the_fist_of_hero_i00',
    'name' => 'Infinity Fang',
    'additionalname' => NULL,
    'description' => 'Divine heros weapon. Increases Max HP/ MP/ CP and Evasion. Stuns the target after a critical attack. With a certain chance, reflects debuffs back to the enemy. Deals additional PvP damage.',
    'is_trade' => 0,
    'is_drop' => 0,
    'is_destruct' => 0,
    'crystal_type' => 's',
    'consume_type' => 'consume_type_normal',
  ],
  6619 => 
  [
    'item_id' => 6619,
    'icon' => 'weapon_the_bow_of_hero_i00',
    'name' => 'Infinity Bow',
    'additionalname' => NULL,
    'description' => 'Divine heros weapon. After a critical attack, inflicts Slow on the target, causes the Cheap Shot effect, and decreases Skill Cooldown. Increases Max MP/ CP. Inflicts additional PvP Damage.',
    'is_trade' => 0,
    'is_drop' => 0,
    'is_destruct' => 0,
    'crystal_type' => 's',
    'consume_type' => 'consume_type_normal',
  ],
  6620 => 
  [
    'item_id' => 6620,
    'icon' => 'weapon_the_dualsword_of_hero_i00',
    'name' => 'Infinity Wing',
    'additionalname' => NULL,
    'description' => 'Divine heros weapon. After a critical attack, inflicts Silence on the target. With a certain chance, reflects debuffs back to the enemy. Iincreases Max HP/ MP/ CP and P. Critical Rate. Deals additional PvP damage.',
    'is_trade' => 0,
    'is_drop' => 0,
    'is_destruct' => 0,
    'crystal_type' => 's',
    'consume_type' => 'consume_type_normal',
  ],
  6621 => 
  [
    'item_id' => 6621,
    'icon' => 'weapon_the_pole_of_hero_i00',
    'name' => 'Infinity Spear',
    'additionalname' => NULL,
    'description' => 'Divine heros weapon. After a critical attack, removes buffs from the target. With a certain chance, reflects debuffs back to the enemy. Increases Max HP/ CP, Atk. Spd. and P. Accuracy. Deals additional PvP damage.',
    'is_trade' => 0,
    'is_drop' => 0,
    'is_destruct' => 0,
    'crystal_type' => 's',
    'consume_type' => 'consume_type_normal',
  ],
  6622 => 
  [
    'item_id' => 6622,
    'icon' => 'etc_codex_of_giant_i00',
    'name' => 'Lesser Giants Codex',
    'additionalname' => NULL,
    'description' => 'Item required for skill enchanting.',
    'is_trade' => 1,
    'is_drop' => 1,
    'is_destruct' => 1,
    'crystal_type' => 'none',
    'consume_type' => 'consume_type_stackable',
  ],
  6623 => 
  [
    'item_id' => 6623,
    'icon' => 'etc_socks_i00',
    'name' => 'Dummy - Quest Item 1',
    'additionalname' => NULL,
    'description' => 'Testing purpose - Quest Item',
    'is_trade' => 0,
    'is_drop' => 0,
    'is_destruct' => 1,
    'crystal_type' => 'none',
    'consume_type' => 'consume_type_stackable',
  ],
  6624 => 
  [
    'item_id' => 6624,
    'icon' => 'etc_socks_i00',
    'name' => 'Dummy - Quest Item 2',
    'additionalname' => NULL,
    'description' => 'Testing purpose - Quest Item',
    'is_trade' => 0,
    'is_drop' => 0,
    'is_destruct' => 1,
    'crystal_type' => 'none',
    'consume_type' => 'consume_type_stackable',
  ],
  6625 => 
  [
    'item_id' => 6625,
    'icon' => 'etc_socks_i00',
    'name' => 'Dummy - Quest Item 3',
    'additionalname' => NULL,
    'description' => 'Testing purpose - Quest Item',
    'is_trade' => 0,
    'is_drop' => 0,
    'is_destruct' => 1,
    'crystal_type' => 'none',
    'consume_type' => 'consume_type_stackable',
  ],
  6626 => 
  [
    'item_id' => 6626,
    'icon' => 'etc_socks_i00',
    'name' => 'Dummy - Quest Item 4',
    'additionalname' => NULL,
    'description' => 'Testing purpose - Quest Item',
    'is_trade' => 0,
    'is_drop' => 0,
    'is_destruct' => 1,
    'crystal_type' => 'none',
    'consume_type' => 'consume_type_stackable',
  ],
  6627 => 
  [
    'item_id' => 6627,
    'icon' => 'etc_socks_i00',
    'name' => 'Dummy - Quest Item 5',
    'additionalname' => NULL,
    'description' => 'Testing purpose - Quest Item',
    'is_trade' => 0,
    'is_drop' => 0,
    'is_destruct' => 1,
    'crystal_type' => 'none',
    'consume_type' => 'consume_type_stackable',
  ],
  6628 => 
  [
    'item_id' => 6628,
    'icon' => 'etc_socks_i00',
    'name' => 'Dummy - Quest Item 6',
    'additionalname' => NULL,
    'description' => 'Testing purpose - Quest Item',
    'is_trade' => 0,
    'is_drop' => 0,
    'is_destruct' => 1,
    'crystal_type' => 'none',
    'consume_type' => 'consume_type_stackable',
  ],
  6629 => 
  [
    'item_id' => 6629,
    'icon' => 'etc_socks_i00',
    'name' => 'Dummy - Quest Item 7',
    'additionalname' => NULL,
    'description' => 'Testing purpose - Quest Item',
    'is_trade' => 0,
    'is_drop' => 0,
    'is_destruct' => 1,
    'crystal_type' => 'none',
    'consume_type' => 'consume_type_stackable',
  ],
  6630 => 
  [
    'item_id' => 6630,
    'icon' => 'etc_socks_i00',
    'name' => 'Dummy - Quest Item 8',
    'additionalname' => NULL,
    'description' => 'Testing purpose - Quest Item',
    'is_trade' => 0,
    'is_drop' => 0,
    'is_destruct' => 1,
    'crystal_type' => 'none',
    'consume_type' => 'consume_type_stackable',
  ],
  6631 => 
  [
    'item_id' => 6631,
    'icon' => 'etc_socks_i00',
    'name' => 'Dummy - Quest Item 9',
    'additionalname' => NULL,
    'description' => 'Testing purpose - Quest Item',
    'is_trade' => 0,
    'is_drop' => 0,
    'is_destruct' => 1,
    'crystal_type' => 'none',
    'consume_type' => 'consume_type_stackable',
  ],
  6632 => 
  [
    'item_id' => 6632,
    'icon' => 'etc_socks_i00',
    'name' => 'Dummy - Quest Item 10',
    'additionalname' => NULL,
    'description' => 'Testing purpose - Quest Item',
    'is_trade' => 0,
    'is_drop' => 0,
    'is_destruct' => 1,
    'crystal_type' => 'none',
    'consume_type' => 'consume_type_stackable',
  ],
  6633 => 
  [
    'item_id' => 6633,
    'icon' => 'etc_socks_i01',
    'name' => 'Dummy - Common Item 1',
    'additionalname' => NULL,
    'description' => 'Testing purpose - Common Item',
    'is_trade' => 1,
    'is_drop' => 1,
    'is_destruct' => 1,
    'crystal_type' => 'none',
    'consume_type' => 'consume_type_stackable',
  ],
  6634 => 
  [
    'item_id' => 6634,
    'icon' => 'etc_socks_i01',
    'name' => 'Dummy - Common Item 2',
    'additionalname' => NULL,
    'description' => 'Testing purpose - Common Item',
    'is_trade' => 1,
    'is_drop' => 1,
    'is_destruct' => 1,
    'crystal_type' => 'none',
    'consume_type' => 'consume_type_stackable',
  ],
  6635 => 
  [
    'item_id' => 6635,
    'icon' => 'etc_socks_i01',
    'name' => 'Dummy - Common Item 3',
    'additionalname' => NULL,
    'description' => 'Testing purpose - Common Item',
    'is_trade' => 1,
    'is_drop' => 1,
    'is_destruct' => 1,
    'crystal_type' => 'none',
    'consume_type' => 'consume_type_stackable',
  ],
  6636 => 
  [
    'item_id' => 6636,
    'icon' => 'etc_socks_i01',
    'name' => 'Dummy - Common Item 4',
    'additionalname' => NULL,
    'description' => 'Testing purpose - Common Item',
    'is_trade' => 1,
    'is_drop' => 1,
    'is_destruct' => 1,
    'crystal_type' => 'none',
    'consume_type' => 'consume_type_stackable',
  ],
  6637 => 
  [
    'item_id' => 6637,
    'icon' => 'etc_socks_i01',
    'name' => 'Dummy - Common Item 5',
    'additionalname' => NULL,
    'description' => 'Testing purpose - Common Item',
    'is_trade' => 1,
    'is_drop' => 1,
    'is_destruct' => 1,
    'crystal_type' => 'none',
    'consume_type' => 'consume_type_stackable',
  ],
  6638 => 
  [
    'item_id' => 6638,
    'icon' => 'etc_socks_i01',
    'name' => 'Dummy - Common Item 6',
    'additionalname' => NULL,
    'description' => 'Testing purpose - Common Item',
    'is_trade' => 1,
    'is_drop' => 1,
    'is_destruct' => 1,
    'crystal_type' => 'none',
    'consume_type' => 'consume_type_stackable',
  ],
  6639 => 
  [
    'item_id' => 6639,
    'icon' => 'etc_socks_i01',
    'name' => 'Dummy - Common Item 7',
    'additionalname' => NULL,
    'description' => 'Testing purpose - Common Item',
    'is_trade' => 1,
    'is_drop' => 1,
    'is_destruct' => 1,
    'crystal_type' => 'none',
    'consume_type' => 'consume_type_stackable',
  ],
  6640 => 
  [
    'item_id' => 6640,
    'icon' => 'etc_socks_i01',
    'name' => 'Dummy - Common Item 8',
    'additionalname' => NULL,
    'description' => 'Testing purpose - Common Item',
    'is_trade' => 1,
    'is_drop' => 1,
    'is_destruct' => 1,
    'crystal_type' => 'none',
    'consume_type' => 'consume_type_stackable',
  ],
  6641 => 
  [
    'item_id' => 6641,
    'icon' => 'etc_socks_i01',
    'name' => 'Dummy - Common Item 9',
    'additionalname' => NULL,
    'description' => 'Testing purpose - Common Item',
    'is_trade' => 1,
    'is_drop' => 1,
    'is_destruct' => 1,
    'crystal_type' => 'none',
    'consume_type' => 'consume_type_stackable',
  ],
  6642 => 
  [
    'item_id' => 6642,
    'icon' => 'etc_socks_i01',
    'name' => 'Dummy - Common Item 10',
    'additionalname' => NULL,
    'description' => 'Testing purpose - Common Item',
    'is_trade' => 1,
    'is_drop' => 1,
    'is_destruct' => 1,
    'crystal_type' => 'none',
    'consume_type' => 'consume_type_stackable',
  ],
  6643 => 
  [
    'item_id' => 6643,
    'icon' => 'etc_pouch_yellow_i00',
    'name' => 'Old Golden Spice',
    'additionalname' => NULL,
    'description' => 'Food for creatures on the Beast Farm. - When this food is fed to monsters that are capable of evolving, they will do so at various rates. Once a monster reaches a certain level of growth, it can then become a pet. This food also causes monsters to only drop Adena.',
    'is_trade' => 1,
    'is_drop' => 1,
    'is_destruct' => 1,
    'crystal_type' => 'crystal_free',
    'consume_type' => 'consume_type_stackable',
  ],
  6644 => 
  [
    'item_id' => 6644,
    'icon' => 'etc_pouch_brown_i00',
    'name' => 'Old Crystal Spice',
    'additionalname' => NULL,
    'description' => 'Food for creatures on the Beast Farm. - When this food is fed to monsters that are capable of evolving, they will do so at various rates. Once a monster reaches a certain level of growth, it can then become a pet. This food also causes monsters to only drop materials.',
    'is_trade' => 1,
    'is_drop' => 1,
    'is_destruct' => 1,
    'crystal_type' => 'crystal_free',
    'consume_type' => 'consume_type_stackable',
  ],
  6645 => 
  [
    'item_id' => 6645,
    'icon' => 'etc_beast_soul_shot_i00',
    'name' => 'Beast Soulshot',
    'additionalname' => NULL,
    'description' => 'The light of a spirit is bestowed upon a pet/ servitor and temporarily increases the power of attack. The number of soulshots consumed can be viewed in the Pet/ Servitor Information window. (Used in the masters inventory.]',
    'is_trade' => 1,
    'is_drop' => 1,
    'is_destruct' => 1,
    'crystal_type' => 'none',
    'consume_type' => 'consume_type_stackable',
  ],
  6646 => 
  [
    'item_id' => 6646,
    'icon' => 'etc_beast_spirit_shot_i00',
    'name' => 'Beast Spiritshot',
    'additionalname' => NULL,
    'description' => 'Increases pets/servitors magic power. The required number of Spiritshots is shown in a pets/servitors info window. (Used from the masters inventory.]',
    'is_trade' => 1,
    'is_drop' => 1,
    'is_destruct' => 1,
    'crystal_type' => 'none',
    'consume_type' => 'consume_type_stackable',
  ],
  6647 => 
  [
    'item_id' => 6647,
    'icon' => 'etc_blessed_beast_spirit_shot_i00',
    'name' => 'Blessed Beast Spiritshot',
    'additionalname' => NULL,
    'description' => 'Increases pets/servitors magic power. The required number of Spiritshots is shown in a pets/servitors info window. (Used from the masters inventory.]',
    'is_trade' => 1,
    'is_drop' => 1,
    'is_destruct' => 1,
    'crystal_type' => 'none',
    'consume_type' => 'consume_type_stackable',
  ],
  6648 => 
  [
    'item_id' => 6648,
    'icon' => 'etc_buffalo_panpipe_i00',
    'name' => 'Baby Buffalo Panpipe',
    'additionalname' => NULL,
    'description' => 'Panpipe that is used to call a baby buffalo. The baby buffalo will take away 5 percent of the XP that its master acquires.',
    'is_trade' => 1,
    'is_drop' => 1,
    'is_destruct' => 1,
    'crystal_type' => 'none',
    'consume_type' => 'consume_type_normal',
  ],
  6649 => 
  [
    'item_id' => 6649,
    'icon' => 'etc_cougar_chime_i00',
    'name' => 'Baby Cougar Chime',
    'additionalname' => NULL,
    'description' => 'Chime that is used to call a baby cougar. The baby cougar will take away 5 percent of the XP that its master acquires.',
    'is_trade' => 1,
    'is_drop' => 1,
    'is_destruct' => 1,
    'crystal_type' => 'none',
    'consume_type' => 'consume_type_normal',
  ],
  6650 => 
  [
    'item_id' => 6650,
    'icon' => 'etc_kukaburo_ocarina_i00',
    'name' => 'Baby Kookaburra Ocarina',
    'additionalname' => NULL,
    'description' => 'Ocarina that is used to call a baby Kookaburra. The baby Kookaburra will take away 5 percent of the XP that its master acquires.',
    'is_trade' => 1,
    'is_drop' => 1,
    'is_destruct' => 1,
    'crystal_type' => 'none',
    'consume_type' => 'consume_type_normal',
  ],
  6651 => 
  [
    'item_id' => 6651,
    'icon' => 'etc_nobless_teleport_coupon_i00',
    'name' => 'Noblesse Gate Pass',
    'additionalname' => NULL,
    'description' => 'Expired certificate. Can be purchased from a shop.',
    'is_trade' => 1,
    'is_drop' => 1,
    'is_destruct' => 1,
    'crystal_type' => 'none',
    'consume_type' => 'consume_type_stackable',
  ],
  6652 => 
  [
    'item_id' => 6652,
    'icon' => 'etc_blesscharm_ward_val_i00',
    'name' => 'Amulet: Protection of Valakas',
    'additionalname' => NULL,
    'description' => 'Fire dragons protection amulet. Upon use, resistance against Fire dragons front attack increases.',
    'is_trade' => 1,
    'is_drop' => 1,
    'is_destruct' => 1,
    'crystal_type' => 'crystal_free',
    'consume_type' => 'consume_type_stackable',
  ],
  6653 => 
  [
    'item_id' => 6653,
    'icon' => 'etc_aidcharm_cancel_deathfire_i00',
    'name' => 'Amulet: Flames of Valakas',
    'additionalname' => NULL,
    'description' => NULL,
    'is_trade' => 1,
    'is_drop' => 1,
    'is_destruct' => 1,
    'crystal_type' => 'none',
    'consume_type' => 'consume_type_stackable',
  ],
  6654 => 
  [
    'item_id' => 6654,
    'icon' => 'etc_aidcharm_cancel_valbreath_i00',
    'name' => 'Amulet: Flames of Valakas',
    'additionalname' => NULL,
    'description' => 'Removes the anomaly state resulting from the fiery breath attack of Valakas.',
    'is_trade' => 1,
    'is_drop' => 1,
    'is_destruct' => 1,
    'crystal_type' => 'crystal_free',
    'consume_type' => 'consume_type_stackable',
  ],
  6655 => 
  [
    'item_id' => 6655,
    'icon' => 'etc_blesscharm_slay_val_i00',
    'name' => 'Amulet: Slay Valakas',
    'additionalname' => NULL,
    'description' => 'Increases P. Atk., when fighting against Valakas.',
    'is_trade' => 1,
    'is_drop' => 1,
    'is_destruct' => 1,
    'crystal_type' => 'crystal_free',
    'consume_type' => 'consume_type_stackable',
  ],
  6656 => 
  [
    'item_id' => 6656,
    'icon' => 'accessory_earring_of_antaras_i00',
    'name' => 'Antharas Earring',
    'additionalname' => NULL,
    'description' => 'MP +37, Infection Atk. Rate and Resistance +30%, Earth Resistance +15, Vampiric Rage effect +4%, MP consumption -5%. Effects of two identical earrings do not stack.<Enchanting>Use Scroll: Enchant S-grade Armor.<Enhancing>Take the item and Bottle of Antharas Soul to Denign in Giran to get Blessed Antharas Earring.',
    'is_trade' => 1,
    'is_drop' => 1,
    'is_destruct' => 1,
    'crystal_type' => 's',
    'consume_type' => 'consume_type_normal',
  ],
  6657 => 
  [
    'item_id' => 6657,
    'icon' => 'accessory_necklace_of_valakas_i00',
    'name' => 'Valakas Necklace',
    'additionalname' => NULL,
    'description' => 'MP +50, Stupor Resistance and Atk. Rate +40%, HP +445, Fire Resistance +15, P. Atk. +4%, M. Atk. +8%, M. Critical Rate +2, Damage Reflection +5, Skill Cooldown -10%.<Enchanting>Use Scroll: Enchant S-grade Armor.<Enhancing>Take a Bottle of Valakas Soul to Denign in Giran to obtain Blessed Valakas Necklace.',
    'is_trade' => 1,
    'is_drop' => 1,
    'is_destruct' => 1,
    'crystal_type' => 's',
    'consume_type' => 'consume_type_normal',
  ],
  6658 => 
  [
    'item_id' => 6658,
    'icon' => 'accessory_ring_of_baium_i00',
    'name' => 'Baiums Ring',
    'additionalname' => NULL,
    'description' => 'MP +21, Poison Resistance +40%, Poison Atk. Rate +40%, accuracy +2, Critical Damage for basic attacks +15%, Hold Resistance +30%, Hold Atk. Rate +30%, atk. Spd. +4%, Casting Spd. +4%. Effects of two identical rings do not stack. Can be crystallized to obtain Selenite.',
    'is_trade' => 1,
    'is_drop' => 1,
    'is_destruct' => 1,
    'crystal_type' => 's',
    'consume_type' => 'consume_type_normal',
  ],
  6659 => 
  [
    'item_id' => 6659,
    'icon' => 'accessory_earring_of_zaken_i00',
    'name' => 'Zakens Earring',
    'additionalname' => NULL,
    'description' => 'MP +31, Bleed Atk. Rate and Resistance +30%, Confusion Atk. Rate and Resistance +20%. Increases Received Healing, grants Vampiric Rage effect. Effects of two identical earrings do not stack. When equipped with Blessed Zakens Earring, only the effect of the latter is applied. Can be crystallized to obtain Selenite.',
    'is_trade' => 1,
    'is_drop' => 1,
    'is_destruct' => 1,
    'crystal_type' => 's',
    'consume_type' => 'consume_type_normal',
  ],
  6660 => 
  [
    'item_id' => 6660,
    'icon' => 'accessory_ring_of_queen_ant_i00',
    'name' => 'Queen Ants Ring',
    'additionalname' => NULL,
    'description' => 'MP +21, Infection Atk. Rate and Resistance +30%, Obstruction Atk. Rate and Resistance +20%. Increases P. Accuracy and Critical Damage for basic attacks. Effects of two identical rings do not stack. Can be crystallized to obtain Selenite.',
    'is_trade' => 1,
    'is_drop' => 1,
    'is_destruct' => 1,
    'crystal_type' => 'b',
    'consume_type' => 'consume_type_normal',
  ],
  6661 => 
  [
    'item_id' => 6661,
    'icon' => 'accessory_earring_of_orfen_i00',
    'name' => 'Orfens Earring',
    'additionalname' => NULL,
    'description' => 'MP +31, Infection Atk. Rate and Resistance +20%. Increases Received Healing. Effects of two identical earrings do not stack. Can be crystallized to obtain Selenite.',
    'is_trade' => 1,
    'is_drop' => 1,
    'is_destruct' => 1,
    'crystal_type' => 'a',
    'consume_type' => 'consume_type_normal',
  ],
  6662 => 
  [
    'item_id' => 6662,
    'icon' => 'accessory_ring_of_core_i00',
    'name' => 'Ring of Core',
    'additionalname' => NULL,
    'description' => 'MP +21, Infection Atk. Rate and Resistance +20%. Increases P. Accuracy. Effects of two identical rings do not stack. Can be crystallized to obtain Selenite.',
    'is_trade' => 1,
    'is_drop' => 1,
    'is_destruct' => 1,
    'crystal_type' => 'a',
    'consume_type' => 'consume_type_normal',
  ],
  6663 => 
  [
    'item_id' => 6663,
    'icon' => 'etc_scroll_of_return_agit_i00',
    'name' => 'Scroll of Escape: Ketra Orc Village',
    'additionalname' => NULL,
    'description' => NULL,
    'is_trade' => 1,
    'is_drop' => 1,
    'is_destruct' => 1,
    'crystal_type' => 'none',
    'consume_type' => 'consume_type_stackable',
  ],
  6664 => 
  [
    'item_id' => 6664,
    'icon' => 'etc_scroll_of_return_agit_i00',
    'name' => 'Scroll of Escape: Varka Silenos Village',
    'additionalname' => NULL,
    'description' => NULL,
    'is_trade' => 1,
    'is_drop' => 1,
    'is_destruct' => 1,
    'crystal_type' => 'none',
    'consume_type' => 'consume_type_stackable',
  ],
  6665 => 
  [
    'item_id' => 6665,
    'icon' => 'etc_old_key_i00',
    'name' => 'Deluxe Chest Key - Grade 1',
    'additionalname' => NULL,
    'description' => 'Old, rusty key that cannot be used anymore. Can be bought at the shop.',
    'is_trade' => 1,
    'is_drop' => 1,
    'is_destruct' => 1,
    'crystal_type' => 'crystal_free',
    'consume_type' => 'consume_type_stackable',
  ],
  6666 => 
  [
    'item_id' => 6666,
    'icon' => 'etc_old_key_i00',
    'name' => 'Deluxe Chest Key - Grade 2',
    'additionalname' => NULL,
    'description' => 'Old, rusty key that cannot be used anymore. Can be bought at the shop.',
    'is_trade' => 1,
    'is_drop' => 1,
    'is_destruct' => 1,
    'crystal_type' => 'crystal_free',
    'consume_type' => 'consume_type_stackable',
  ],
  6667 => 
  [
    'item_id' => 6667,
    'icon' => 'etc_old_key_i00',
    'name' => 'Deluxe Chest Key - Grade 3',
    'additionalname' => NULL,
    'description' => 'Old, rusty key that cannot be used anymore. Can be bought at the shop.',
    'is_trade' => 1,
    'is_drop' => 1,
    'is_destruct' => 1,
    'crystal_type' => 'crystal_free',
    'consume_type' => 'consume_type_stackable',
  ],
  6668 => 
  [
    'item_id' => 6668,
    'icon' => 'etc_old_key_i00',
    'name' => 'Deluxe Chest Key - Grade 4',
    'additionalname' => NULL,
    'description' => 'Old, rusty key that cannot be used anymore. Can be bought at the shop.',
    'is_trade' => 1,
    'is_drop' => 1,
    'is_destruct' => 1,
    'crystal_type' => 'crystal_free',
    'consume_type' => 'consume_type_stackable',
  ],
  6669 => 
  [
    'item_id' => 6669,
    'icon' => 'etc_old_key_i00',
    'name' => 'Deluxe Chest Key - Grade 5',
    'additionalname' => NULL,
    'description' => 'Old, rusty key that cannot be used anymore. Can be bought at the shop.',
    'is_trade' => 1,
    'is_drop' => 1,
    'is_destruct' => 1,
    'crystal_type' => 'crystal_free',
    'consume_type' => 'consume_type_stackable',
  ],
  6670 => 
  [
    'item_id' => 6670,
    'icon' => 'etc_old_key_i00',
    'name' => 'Deluxe Chest Key - Grade 6',
    'additionalname' => NULL,
    'description' => 'Old, rusty key that cannot be used anymore. Can be bought at the shop.',
    'is_trade' => 1,
    'is_drop' => 1,
    'is_destruct' => 1,
    'crystal_type' => 'crystal_free',
    'consume_type' => 'consume_type_stackable',
  ],
  6671 => 
  [
    'item_id' => 6671,
    'icon' => 'etc_old_key_i00',
    'name' => 'Deluxe Chest Key - Grade 7',
    'additionalname' => NULL,
    'description' => 'Old, rusty key that cannot be used anymore. Can be bought at the shop.',
    'is_trade' => 1,
    'is_drop' => 1,
    'is_destruct' => 1,
    'crystal_type' => 'crystal_free',
    'consume_type' => 'consume_type_stackable',
  ],
  6672 => 
  [
    'item_id' => 6672,
    'icon' => 'etc_old_key_i00',
    'name' => 'Deluxe Chest Key - Grade 8',
    'additionalname' => NULL,
    'description' => 'Old, rusty key that cannot be used anymore. Can be bought at the shop.',
    'is_trade' => 1,
    'is_drop' => 1,
    'is_destruct' => 1,
    'crystal_type' => 'crystal_free',
    'consume_type' => 'consume_type_stackable',
  ],
  6673 => 
  [
    'item_id' => 6673,
    'icon' => 'etc_coin_of_fair_i00',
    'name' => 'Festival Adena',
    'additionalname' => NULL,
    'description' => 'Currency used in the 2005 Lineage II Live event.',
    'is_trade' => 0,
    'is_drop' => 0,
    'is_destruct' => 1,
    'crystal_type' => 'none',
    'consume_type' => 'consume_type_stackable',
  ],
  6674 => 
  [
    'item_id' => 6674,
    'icon' => 'armor_t88_u_i02',
    'name' => 'Sealed Imperial Crusader Breastplate',
    'additionalname' => NULL,
    'description' => 'Old and not very useful equipment.',
    'is_trade' => 1,
    'is_drop' => 1,
    'is_destruct' => 1,
    'crystal_type' => 's',
    'consume_type' => 'consume_type_normal',
  ],
  6675 => 
  [
    'item_id' => 6675,
    'icon' => 'armor_t88_l_i02',
    'name' => 'Sealed Imperial Crusader Gaiters',
    'additionalname' => NULL,
    'description' => 'Old and not very useful equipment.',
    'is_trade' => 1,
    'is_drop' => 1,
    'is_destruct' => 1,
    'crystal_type' => 's',
    'consume_type' => 'consume_type_normal',
  ],
  6676 => 
  [
    'item_id' => 6676,
    'icon' => 'armor_t88_g_i02',
    'name' => 'Sealed Imperial Crusader Gauntlets',
    'additionalname' => NULL,
    'description' => 'Old and not very useful equipment.',
    'is_trade' => 1,
    'is_drop' => 1,
    'is_destruct' => 1,
    'crystal_type' => 's',
    'consume_type' => 'consume_type_normal',
  ],
  6677 => 
  [
    'item_id' => 6677,
    'icon' => 'armor_t88_b_i02',
    'name' => 'Sealed Imperial Crusader Boots',
    'additionalname' => NULL,
    'description' => 'Old and not very useful equipment.',
    'is_trade' => 1,
    'is_drop' => 1,
    'is_destruct' => 1,
    'crystal_type' => 's',
    'consume_type' => 'consume_type_normal',
  ],
  6678 => 
  [
    'item_id' => 6678,
    'icon' => 'shield_imperial_crusader_shield_i02',
    'name' => 'Sealed Imperial Crusader Shield',
    'additionalname' => NULL,
    'description' => 'Old and not very useful equipment.',
    'is_trade' => 1,
    'is_drop' => 1,
    'is_destruct' => 1,
    'crystal_type' => 's',
    'consume_type' => 'consume_type_normal',
  ],
  6679 => 
  [
    'item_id' => 6679,
    'icon' => 'armor_helmet_i02',
    'name' => 'Sealed Imperial Crusader Helmet',
    'additionalname' => NULL,
    'description' => 'Old and not very useful equipment.',
    'is_trade' => 1,
    'is_drop' => 1,
    'is_destruct' => 1,
    'crystal_type' => 's',
    'consume_type' => 'consume_type_normal',
  ],
  6680 => 
  [
    'item_id' => 6680,
    'icon' => 'armor_t89_ul_i02',
    'name' => 'Sealed Draconic Armor',
    'additionalname' => NULL,
    'description' => 'Old and not very useful equipment.',
    'is_trade' => 1,
    'is_drop' => 1,
    'is_destruct' => 1,
    'crystal_type' => 's',
    'consume_type' => 'consume_type_normal',
  ],
  6681 => 
  [
    'item_id' => 6681,
    'icon' => 'armor_t89_g_i02',
    'name' => 'Sealed Draconic Gloves',
    'additionalname' => NULL,
    'description' => 'Old and not very useful equipment.',
    'is_trade' => 1,
    'is_drop' => 1,
    'is_destruct' => 1,
    'crystal_type' => 's',
    'consume_type' => 'consume_type_normal',
  ],
  6682 => 
  [
    'item_id' => 6682,
    'icon' => 'armor_t89_b_i02',
    'name' => 'Sealed Draconic Boots',
    'additionalname' => NULL,
    'description' => 'Old and not very useful equipment.',
    'is_trade' => 1,
    'is_drop' => 1,
    'is_destruct' => 1,
    'crystal_type' => 's',
    'consume_type' => 'consume_type_normal',
  ],
  6683 => 
  [
    'item_id' => 6683,
    'icon' => 'armor_helmet_i02',
    'name' => 'Sealed Draconic Helmet',
    'additionalname' => NULL,
    'description' => 'Old and not very useful equipment.',
    'is_trade' => 1,
    'is_drop' => 1,
    'is_destruct' => 1,
    'crystal_type' => 's',
    'consume_type' => 'consume_type_normal',
  ],
  6684 => 
  [
    'item_id' => 6684,
    'icon' => 'armor_t90_ul_i02',
    'name' => 'Sealed Major Arcana Robe',
    'additionalname' => NULL,
    'description' => 'Old and not very useful equipment.',
    'is_trade' => 1,
    'is_drop' => 1,
    'is_destruct' => 1,
    'crystal_type' => 's',
    'consume_type' => 'consume_type_normal',
  ],
  6685 => 
  [
    'item_id' => 6685,
    'icon' => 'armor_t90_g_i02',
    'name' => 'Sealed Major Arcana Gloves',
    'additionalname' => NULL,
    'description' => 'Old and not very useful equipment.',
    'is_trade' => 1,
    'is_drop' => 1,
    'is_destruct' => 1,
    'crystal_type' => 's',
    'consume_type' => 'consume_type_normal',
  ],
  6686 => 
  [
    'item_id' => 6686,
    'icon' => 'armor_t90_b_i02',
    'name' => 'Sealed Major Arcana Boots',
    'additionalname' => NULL,
    'description' => 'Old and not very useful equipment.',
    'is_trade' => 1,
    'is_drop' => 1,
    'is_destruct' => 1,
    'crystal_type' => 's',
    'consume_type' => 'consume_type_normal',
  ],
  6687 => 
  [
    'item_id' => 6687,
    'icon' => 'armor_circlet_i02',
    'name' => 'Sealed Major Arcana Circlet',
    'additionalname' => NULL,
    'description' => 'Old and not very useful equipment.',
    'is_trade' => 1,
    'is_drop' => 1,
    'is_destruct' => 1,
    'crystal_type' => 's',
    'consume_type' => 'consume_type_normal',
  ],
  6688 => 
  [
    'item_id' => 6688,
    'icon' => 'etc_sword_body_i00',
    'name' => 'Forgotten Blade Edge',
    'additionalname' => NULL,
    'description' => 'Key material for Dwarves to make Forgotten Blade. Can be sold in any shop.',
    'is_trade' => 1,
    'is_drop' => 1,
    'is_destruct' => 1,
    'crystal_type' => 'none',
    'consume_type' => 'consume_type_stackable',
  ],
  6689 => 
  [
    'item_id' => 6689,
    'icon' => 'etc_squares_gray_i00',
    'name' => 'Basalt Battlehammer Head',
    'additionalname' => NULL,
    'description' => 'Key material for Dwarves to make Basalt Battlehammer. Can be sold in any shop.',
    'is_trade' => 1,
    'is_drop' => 1,
    'is_destruct' => 1,
    'crystal_type' => 'none',
    'consume_type' => 'consume_type_stackable',
  ],
  6690 => 
  [
    'item_id' => 6690,
    'icon' => 'etc_bark_blue_i00',
    'name' => 'Imperial Staff Head',
    'additionalname' => NULL,
    'description' => 'Key material for Dwarves to make Imperial Staff. Can also be sold in any shop.',
    'is_trade' => 1,
    'is_drop' => 1,
    'is_destruct' => 1,
    'crystal_type' => 'none',
    'consume_type' => 'consume_type_stackable',
  ],
  6691 => 
  [
    'item_id' => 6691,
    'icon' => 'etc_sword_body_i00',
    'name' => 'Angel Slayer Blade',
    'additionalname' => NULL,
    'description' => 'Key material for Dwarves to make Angel Slayer. Can be sold in any shop.',
    'is_trade' => 1,
    'is_drop' => 1,
    'is_destruct' => 1,
    'crystal_type' => 'none',
    'consume_type' => 'consume_type_stackable',
  ],
  6692 => 
  [
    'item_id' => 6692,
    'icon' => 'etc_branch_gold_i00',
    'name' => 'Bow of Light Shaft',
    'additionalname' => NULL,
    'description' => NULL,
    'is_trade' => 1,
    'is_drop' => 1,
    'is_destruct' => 1,
    'crystal_type' => 'none',
    'consume_type' => 'consume_type_stackable',
  ],
  6693 => 
  [
    'item_id' => 6693,
    'icon' => 'etc_sword_body_i00',
    'name' => 'Dragon Hunter Axe Blade',
    'additionalname' => NULL,
    'description' => 'Key material for Dwarves to make Dragon Hunter Axe. Can be sold in any shop.',
    'is_trade' => 1,
    'is_drop' => 1,
    'is_destruct' => 1,
    'crystal_type' => 'none',
    'consume_type' => 'consume_type_stackable',
  ],
  6694 => 
  [
    'item_id' => 6694,
    'icon' => 'etc_sword_body_i00',
    'name' => 'Saint Spear Blade',
    'additionalname' => NULL,
    'description' => 'Key material for Dwarves to make Saint Spear. Can be sold in any shop.',
    'is_trade' => 1,
    'is_drop' => 1,
    'is_destruct' => 1,
    'crystal_type' => 'none',
    'consume_type' => 'consume_type_stackable',
  ],
  6695 => 
  [
    'item_id' => 6695,
    'icon' => 'etc_sword_body_i00',
    'name' => 'Demon Splinter Blade',
    'additionalname' => NULL,
    'description' => 'Key material for Dwarves to make Demon Splinter. Can be sold in any shop.',
    'is_trade' => 1,
    'is_drop' => 1,
    'is_destruct' => 1,
    'crystal_type' => 'none',
    'consume_type' => 'consume_type_stackable',
  ],
  6696 => 
  [
    'item_id' => 6696,
    'icon' => 'etc_sword_body_i00',
    'name' => 'Heavens Divider Edge',
    'additionalname' => NULL,
    'description' => 'Key material for Dwarves to make Heavens Divider. Can be sold in any shop.',
    'is_trade' => 1,
    'is_drop' => 1,
    'is_destruct' => 1,
    'crystal_type' => 'none',
    'consume_type' => 'consume_type_stackable',
  ],
  6697 => 
  [
    'item_id' => 6697,
    'icon' => 'etc_squares_gray_i00',
    'name' => 'Arcana Mace Head',
    'additionalname' => NULL,
    'description' => 'Key material for Dwarves to make Arcana Mace. Can be sold in any shop.',
    'is_trade' => 1,
    'is_drop' => 1,
    'is_destruct' => 1,
    'crystal_type' => 'none',
    'consume_type' => 'consume_type_stackable',
  ],
  6698 => 
  [
    'item_id' => 6698,
    'icon' => 'etc_broken_crystal_silver_i00',
    'name' => 'Sealed Tateossian Earring Part',
    'additionalname' => NULL,
    'description' => 'Key material for Dwarves to make Sealed Tateossian Earring. Not valuable material for crafting old equipment.',
    'is_trade' => 1,
    'is_drop' => 1,
    'is_destruct' => 1,
    'crystal_type' => 'none',
    'consume_type' => 'consume_type_stackable',
  ],
  6699 => 
  [
    'item_id' => 6699,
    'icon' => 'etc_crystal_ball_gold_i00',
    'name' => 'Sealed Tateossian Ring Gem',
    'additionalname' => NULL,
    'description' => 'Key material for Dwarves to make Sealed Tateossian Ring. Not valuable material for crafting old equipment.',
    'is_trade' => 1,
    'is_drop' => 1,
    'is_destruct' => 1,
    'crystal_type' => 'none',
    'consume_type' => 'consume_type_stackable',
  ],
];