<?php return [
  80000 => 
  [
    'item_id' => 80000,
    'icon' => 'bm_artifact_peice',
    'name' => 'Artifact Fragment',
    'additionalname' => NULL,
    'description' => 'Required for crafting artifacts. Take it to Artifact Merchant Alexandria in Giran to obtain the following items: Artifact - Received Damage When Immobilized, Artifact - P. Skill Power, Artifact - M. Skill Power.',
    'is_trade' => 1,
    'is_drop' => 1,
    'is_destruct' => 1,
    'crystal_type' => 'crystal_free',
    'consume_type' => 'consume_type_stackable',
  ],
  80001 => 
  [
    'item_id' => 80001,
    'icon' => 'lbracelet_agathion_charm',
    'name' => 'Superior Seed Bracelet Lv. 1',
    'additionalname' => '30-day',
    'description' => 'When equipped, unlocks the agathions main slot and 1 additional slot.<Active skill>1. Agathion Teleport: Teleports to Aden/ Rune/ Giran/ Heine (cooldown: 30 min.].<Item skills>1. STR/ INT/ CON/ DEX/ WIT/ MEN/ CHA/ LUC +1.2. Fire/ Water/ Earth/ Wind/ Dark/ Holy Atk. Rate +50 and Resistance +30.3. Vitality bonus +5%.',
    'is_trade' => 0,
    'is_drop' => 0,
    'is_destruct' => 1,
    'crystal_type' => 'none',
    'consume_type' => 'consume_type_normal',
  ],
  80002 => 
  [
    'item_id' => 80002,
    'icon' => 'bm_earring_of_antaras',
    'name' => 'Blessed Antharas Earring',
    'additionalname' => 'Event',
    'description' => 'MP +59, P./ M. Def. +15%, CON/ MEN +3, Holy/ Earth Resistance +30, Infection Atk. Rate and Resistance +50%, Confusion Atk. Rate and Resistance +40%, Received Healing +10%, Skill MP Consumption -5%, Vampiric Rage effect +4%.Active skill: Removes Shock debuffs and grants immunity to Confusion for 5 sec.Effects of two identical earrings do not stack.',
    'is_trade' => 0,
    'is_drop' => 0,
    'is_destruct' => 1,
    'crystal_type' => 'r',
    'consume_type' => 'consume_type_normal',
  ],
  80003 => 
  [
    'item_id' => 80003,
    'icon' => 'bm_necklace_of_valakas',
    'name' => 'Blessed Valakas Necklace',
    'additionalname' => 'Event',
    'description' => 'MP +79, Max HP +625, P. Atk. +10%, M. Atk. +20%, M. Skill Critical Rate +20, STR/ INT +3, Fire Resistance +30, Dark Resistance +20, Stupor Atk. Rate and Resistance +50%, P. Skill Power +5%, Skill Cooldown -10%, Damage Reflection +5%.Active skill: Removes Hold debuffs and grants immunity to Obstruction for 5 sec. Cannot be used in the Olympiad.',
    'is_trade' => 0,
    'is_drop' => 0,
    'is_destruct' => 1,
    'crystal_type' => 'r',
    'consume_type' => 'consume_type_normal',
  ],
  80004 => 
  [
    'item_id' => 80004,
    'icon' => 'npoint_earring_of_lind_30day',
    'name' => 'Lindviors Earring',
    'additionalname' => 'Event',
    'description' => 'MP +59, P. Critical Damage/ M. Skill Critical Damage +10%, Speed +5, DEX/ WIT +3, Dark/ Wind Resistance +30, Petrification Atk. Rate and Resistance +50%, Confusion Atk. Rate and Resistance +40%, Danger Zone Resistance +40%, P./ M. Debuff Reflection Rate +10%, M. Damage Reflection Rate +10%.Active skill: Removes Knockback/ Knockdown debuffs and grants immunity to Confusion for 5 sec.Effects of two identical earrings do not stack.',
    'is_trade' => 0,
    'is_drop' => 0,
    'is_destruct' => 1,
    'crystal_type' => 'r',
    'consume_type' => 'consume_type_normal',
  ],
  80005 => 
  [
    'item_id' => 80005,
    'icon' => 'etc_alphabet_v_i00',
    'name' => 'Letter V',
    'additionalname' => 'Event',
    'description' => 'Gather letters to complete Victory Korea or Korea, and take them to Event NPC Lineage II to get a reward. ',
    'is_trade' => 1,
    'is_drop' => 1,
    'is_destruct' => 1,
    'crystal_type' => 'crystal_free',
    'consume_type' => 'consume_type_stackable',
  ],
  80006 => 
  [
    'item_id' => 80006,
    'icon' => 'etc_alphabet_i_i00',
    'name' => 'Letter I',
    'additionalname' => 'Event',
    'description' => 'Gather letters to complete Victory Korea or Korea, and take them to Event NPC Lineage II to get a reward. ',
    'is_trade' => 1,
    'is_drop' => 1,
    'is_destruct' => 1,
    'crystal_type' => 'crystal_free',
    'consume_type' => 'consume_type_stackable',
  ],
  80007 => 
  [
    'item_id' => 80007,
    'icon' => 'etc_alphabet_c_i00',
    'name' => 'Letter C',
    'additionalname' => 'Event',
    'description' => 'Gather letters to complete Victory Korea or Korea, and take them to Event NPC Lineage II to get a reward. ',
    'is_trade' => 1,
    'is_drop' => 1,
    'is_destruct' => 1,
    'crystal_type' => 'crystal_free',
    'consume_type' => 'consume_type_stackable',
  ],
  80008 => 
  [
    'item_id' => 80008,
    'icon' => 'etc_alphabet_t_i00',
    'name' => 'Letter T',
    'additionalname' => 'Event',
    'description' => 'Gather letters to complete Victory Korea or Korea, and take them to Event NPC Lineage II to get a reward. ',
    'is_trade' => 1,
    'is_drop' => 1,
    'is_destruct' => 1,
    'crystal_type' => 'crystal_free',
    'consume_type' => 'consume_type_stackable',
  ],
  80009 => 
  [
    'item_id' => 80009,
    'icon' => 'etc_alphabet_o_i00',
    'name' => 'Letter O',
    'additionalname' => 'Event',
    'description' => 'Gather letters to complete Victory Korea or Korea, and take them to Event NPC Lineage II to get a reward. ',
    'is_trade' => 1,
    'is_drop' => 1,
    'is_destruct' => 1,
    'crystal_type' => 'crystal_free',
    'consume_type' => 'consume_type_stackable',
  ],
  80010 => 
  [
    'item_id' => 80010,
    'icon' => 'etc_alphabet_r_i00',
    'name' => 'Letter R',
    'additionalname' => 'Event',
    'description' => 'Gather letters to complete Victory Korea or Korea, and take them to Event NPC Lineage II to get a reward. ',
    'is_trade' => 1,
    'is_drop' => 1,
    'is_destruct' => 1,
    'crystal_type' => 'crystal_free',
    'consume_type' => 'consume_type_stackable',
  ],
  80011 => 
  [
    'item_id' => 80011,
    'icon' => 'etc_alphabet_y_i00',
    'name' => 'Letter Y',
    'additionalname' => 'Event',
    'description' => 'Gather letters to complete Victory Korea or Korea, and take them to Event NPC Lineage II to get a reward. ',
    'is_trade' => 1,
    'is_drop' => 1,
    'is_destruct' => 1,
    'crystal_type' => 'crystal_free',
    'consume_type' => 'consume_type_stackable',
  ],
  80012 => 
  [
    'item_id' => 80012,
    'icon' => 'etc_alphabet_k_i00',
    'name' => 'Letter K',
    'additionalname' => 'Event',
    'description' => 'Gather letters to complete Victory Korea or Korea, and take them to Event NPC Lineage II to get a reward. ',
    'is_trade' => 1,
    'is_drop' => 1,
    'is_destruct' => 1,
    'crystal_type' => 'crystal_free',
    'consume_type' => 'consume_type_stackable',
  ],
  80013 => 
  [
    'item_id' => 80013,
    'icon' => 'etc_alphabet_e_i00',
    'name' => 'Letter E',
    'additionalname' => 'Event',
    'description' => 'Gather letters to complete Victory Korea or Korea, and take them to Event NPC Lineage II to get a reward. ',
    'is_trade' => 1,
    'is_drop' => 1,
    'is_destruct' => 1,
    'crystal_type' => 'crystal_free',
    'consume_type' => 'consume_type_stackable',
  ],
  80014 => 
  [
    'item_id' => 80014,
    'icon' => 'etc_alphabet_a_i00',
    'name' => 'Letter A',
    'additionalname' => 'Event',
    'description' => 'Gather letters to complete Victory Korea or Korea, and take them to Event NPC Lineage II to get a reward. ',
    'is_trade' => 1,
    'is_drop' => 1,
    'is_destruct' => 1,
    'crystal_type' => 'crystal_free',
    'consume_type' => 'consume_type_stackable',
  ],
  80015 => 
  [
    'item_id' => 80015,
    'icon' => 'ev_2018_soccer_box',
    'name' => 'Gold Trophy',
    'additionalname' => NULL,
    'description' => 'For the victory of Korea, Lineage II has prepared this Gold Trophy for warriors. Double-click to receive a reward. ',
    'is_trade' => 1,
    'is_drop' => 1,
    'is_destruct' => 1,
    'crystal_type' => 'crystal_free',
    'consume_type' => 'consume_type_stackable',
  ],
  80016 => 
  [
    'item_id' => 80016,
    'icon' => 'ev_soccer_herb',
    'name' => 'Soccer Ball Herb',
    'additionalname' => NULL,
    'description' => 'Party Herb for 2018 Russia World Cup',
    'is_trade' => 0,
    'is_drop' => 1,
    'is_destruct' => 1,
    'crystal_type' => 'crystal_free',
    'consume_type' => 'consume_type_normal',
  ],
  80017 => 
  [
    'item_id' => 80017,
    'icon' => 'accessory_worldcup_mask_i00',
    'name' => 'Mask of Spirits',
    'additionalname' => '2018',
    'description' => 'An event head accessory.Additional effects are applied when equipped along with Knights/ wizards/ Warriors Circlet enchanted to +7.Equipped in 1 head accessory slot.M. Def. +6%, Debuff Resistance +7%, P. Atk./ M. Atk./ P. Def. +1%.',
    'is_trade' => 0,
    'is_drop' => 0,
    'is_destruct' => 1,
    'crystal_type' => 'none',
    'consume_type' => 'consume_type_normal',
  ],
  80018 => 
  [
    'item_id' => 80018,
    'icon' => 'ev_2018_soccer_homerunball',
    'name' => 'Soccer Ball of Victory',
    'additionalname' => NULL,
    'description' => 'A soccer ball prepared for the victory of Korea. For 1 h. acquired XP/ SP +100%. Cannot be stacked with the Fall of the Dragon buff/ Nevits Hourglass/ Dandys Home Run Ball. ',
    'is_trade' => 0,
    'is_drop' => 0,
    'is_destruct' => 1,
    'crystal_type' => 'crystal_free',
    'consume_type' => 'consume_type_stackable',
  ],
  80019 => 
  [
    'item_id' => 80019,
    'icon' => 'ev_2018_soccer_cap',
    'name' => 'Hat of Cheers',
    'additionalname' => NULL,
    'description' => 'A red-and-white hat worn by Polish fans at soccer games. Equipped in 2 head accessory slots. ',
    'is_trade' => 0,
    'is_drop' => 0,
    'is_destruct' => 1,
    'crystal_type' => 'none',
    'consume_type' => 'consume_type_normal',
  ],
  80020 => 
  [
    'item_id' => 80020,
    'icon' => 'ev_bm_white_buff',
    'name' => 'White Potion',
    'additionalname' => NULL,
    'description' => 'For 30 min., Max HP/ MP/ CP +20%, P./ M. Atk. and P./ M. Def. +30%, Atk. Spd./ Casting Spd. +10%, Speed +20, Attribute Attack/ Resistance +100, Skill MP Consumption -15%. Additionally acquired XP/ SP +30%. Cooldown: 5 min. The effect does not stack with the Art of Seduction and Paagrios Blessing effects. Cannot be used in the Olympiad.',
    'is_trade' => 1,
    'is_drop' => 1,
    'is_destruct' => 1,
    'crystal_type' => 'crystal_free',
    'consume_type' => 'consume_type_stackable',
  ],
  80021 => 
  [
    'item_id' => 80021,
    'icon' => 'bm_polyne_R99_1_dagger',
    'name' => 'Paulinas Helios Shaper',
    'additionalname' => NULL,
    'description' => '<Special properties> Atk. Spd. +15%, Critical Rate for standard attacks +50, Critical Damage for standard attacks +10%, Max HP +15%, PvE damage +10%. Its appearance cannot be modified. Cannot be enchanted, augmented, upgraded with Soul Crystal, crystallized, imbued with an attribute.',
    'is_trade' => 0,
    'is_drop' => 0,
    'is_destruct' => 1,
    'crystal_type' => 'r',
    'consume_type' => 'consume_type_normal',
  ],
  80022 => 
  [
    'item_id' => 80022,
    'icon' => 'bm_polyne_R99_onehand_sword',
    'name' => 'Paulinas Helios Cutter',
    'additionalname' => NULL,
    'description' => '<Special properties> Atk. Spd. +15%, Critical Rate for standard attacks +100, Critical Damage for standard attacks +5%, Max HP +15%, PvE damage +10%. Its appearance cannot be modified. Cannot be enchanted, augmented, upgraded with Soul Crystal, crystallized, imbued with an attribute.',
    'is_trade' => 0,
    'is_drop' => 0,
    'is_destruct' => 1,
    'crystal_type' => 'r',
    'consume_type' => 'consume_type_normal',
  ],
  80023 => 
  [
    'item_id' => 80023,
    'icon' => 'bm_polyne_R99_twohand_sword',
    'name' => 'Paulinas Helios Slasher',
    'additionalname' => NULL,
    'description' => '<Special properties> Atk. Spd. +15%, Critical Rate for standard attacks +100, Critical Damage for standard attacks +5%, Max HP +15%, PvE damage +10%. Its appearance cannot be modified. Cannot be enchanted, augmented, upgraded with Soul Crystal, crystallized, imbued with an attribute.',
    'is_trade' => 0,
    'is_drop' => 0,
    'is_destruct' => 1,
    'crystal_type' => 'r',
    'consume_type' => 'consume_type_normal',
  ],
  80024 => 
  [
    'item_id' => 80024,
    'icon' => 'bm_polyne_R99_onehand_blunt',
    'name' => 'Paulinas Helios Avenger',
    'additionalname' => NULL,
    'description' => '<Special properties> Atk. Spd. +15%, Critical Rate for standard attacks +100, Critical Damage for standard attacks +5%, Max HP +15%, PvE damage +10%. Its appearance cannot be modified. Cannot be enchanted, augmented, upgraded with Soul Crystal, crystallized, imbued with an attribute.',
    'is_trade' => 0,
    'is_drop' => 0,
    'is_destruct' => 1,
    'crystal_type' => 'r',
    'consume_type' => 'consume_type_normal',
  ],
  80025 => 
  [
    'item_id' => 80025,
    'icon' => 'bm_polyne_R99_fist',
    'name' => 'Paulinas Helios Fighter',
    'additionalname' => NULL,
    'description' => '<Special properties> Atk. Spd. +15%, Critical Rate for standard attacks +100, Critical Damage for standard attacks +5%, Max HP +15%, PvE damage +10%. Its appearance cannot be modified. Cannot be enchanted, augmented, upgraded with Soul Crystal, crystallized, imbued with an attribute.',
    'is_trade' => 0,
    'is_drop' => 0,
    'is_destruct' => 1,
    'crystal_type' => 'r',
    'consume_type' => 'consume_type_normal',
  ],
  80026 => 
  [
    'item_id' => 80026,
    'icon' => 'bm_polyne_R99_spear',
    'name' => 'Paulinas Helios Stormer',
    'additionalname' => NULL,
    'description' => '<Special properties> Atk. Spd. +15%, Critical Rate for standard attacks +100, Critical Damage for standard attacks +5%, Max HP +15%, PvE damage +10%. Its appearance cannot be modified. Cannot be enchanted, augmented, upgraded with Soul Crystal, crystallized, imbued with an attribute.',
    'is_trade' => 0,
    'is_drop' => 0,
    'is_destruct' => 1,
    'crystal_type' => 'r',
    'consume_type' => 'consume_type_normal',
  ],
  80027 => 
  [
    'item_id' => 80027,
    'icon' => 'bm_polyne_R99_bow',
    'name' => 'Paulinas Helios Thrower',
    'additionalname' => NULL,
    'description' => '<Special properties> Atk. Spd. +15%, Critical Rate for standard attacks +50, Critical Damage for standard attacks +10%, Max HP +15%, PvE damage +10%. Its appearance cannot be modified. Cannot be enchanted, augmented, upgraded with Soul Crystal, crystallized, imbued with an attribute.',
    'is_trade' => 0,
    'is_drop' => 0,
    'is_destruct' => 1,
    'crystal_type' => 'r',
    'consume_type' => 'consume_type_normal',
  ],
  80028 => 
  [
    'item_id' => 80028,
    'icon' => 'bm_polyne_R99_crossbow',
    'name' => 'Paulinas Helios Guardian',
    'additionalname' => NULL,
    'description' => '<Special properties> Atk. Spd. +15%, Critical Rate for standard attacks +50, Critical Damage for standard attacks +10%, Max HP +15%, PvE damage +10%. Its appearance cannot be modified. Cannot be enchanted, augmented, upgraded with Soul Crystal, crystallized, imbued with an attribute.',
    'is_trade' => 0,
    'is_drop' => 0,
    'is_destruct' => 1,
    'crystal_type' => 'r',
    'consume_type' => 'consume_type_normal',
  ],
  80029 => 
  [
    'item_id' => 80029,
    'icon' => 'bm_polyne_R99_1_onehand_magic_sword',
    'name' => 'Paulinas Helios Buster',
    'additionalname' => NULL,
    'description' => '<Special Features> Casting Spd. +15%, M. Critical Rate +50, M. Critical Damage +10%, Max HP +15%, PvE Damage +10%. Cannot be enchanted, augmented, upgraded with Soul Crystal, crystallized, appearance modified, assigned an attribute.',
    'is_trade' => 0,
    'is_drop' => 0,
    'is_destruct' => 1,
    'crystal_type' => 'r',
    'consume_type' => 'consume_type_normal',
  ],
  80030 => 
  [
    'item_id' => 80030,
    'icon' => 'bm_polyne_R99_onehand_magic_blunt',
    'name' => 'Paulinas Helios Caster',
    'additionalname' => NULL,
    'description' => '<Special Features> Casting Spd. +15%, M. Critical Rate +50, M. Critical Damage +10%, Max HP +15%, PvE Damage +10%. Cannot be enchanted, augmented, upgraded with Soul Crystal, crystallized, appearance modified, assigned an attribute.',
    'is_trade' => 0,
    'is_drop' => 0,
    'is_destruct' => 1,
    'crystal_type' => 'r',
    'consume_type' => 'consume_type_normal',
  ],
  80031 => 
  [
    'item_id' => 80031,
    'icon' => 'bm_polyne_R99_twohand_magic_blunt',
    'name' => 'Paulinas Helios Retributer',
    'additionalname' => NULL,
    'description' => '<Special Option> Atk./ Casting Spd. +15%, Critical Damage for standard attacks +10%, M. Skill Critical Damage +10%, PvE Damage +10%, Max HP +15%. Cannot be enchanted, augmented, upgraded with Soul Crystal, crystallized, appearance modified, imbued with an attribute.',
    'is_trade' => 0,
    'is_drop' => 0,
    'is_destruct' => 1,
    'crystal_type' => 'r',
    'consume_type' => 'consume_type_normal',
  ],
  80032 => 
  [
    'item_id' => 80032,
    'icon' => 'bm_polyne_R99_dual_sword',
    'name' => 'Paulinas Helios Dual Swords',
    'additionalname' => NULL,
    'description' => '<Special properties> Atk. Spd. +15%, Critical Rate for standard attacks +100, Critical Damage for standard attacks +5%, Max HP +15%, PvE damage +10%. Its appearance cannot be modified. Cannot be enchanted, augmented, upgraded with Soul Crystal, crystallized, imbued with an attribute.',
    'is_trade' => 0,
    'is_drop' => 0,
    'is_destruct' => 1,
    'crystal_type' => 'r',
    'consume_type' => 'consume_type_normal',
  ],
  80033 => 
  [
    'item_id' => 80033,
    'icon' => 'bm_polyne_R99_dual_dagger',
    'name' => 'Paulinas Helios Dual Daggers',
    'additionalname' => NULL,
    'description' => '<Special properties> Atk. Spd. +15%, Critical Rate for standard attacks +50, Critical Damage for standard attacks +10%, Max HP +15%, PvE damage +10%. Its appearance cannot be modified. Cannot be enchanted, augmented, upgraded with Soul Crystal, crystallized, imbued with an attribute.',
    'is_trade' => 0,
    'is_drop' => 0,
    'is_destruct' => 1,
    'crystal_type' => 'r',
    'consume_type' => 'consume_type_normal',
  ],
  80034 => 
  [
    'item_id' => 80034,
    'icon' => 'bm_polyne_R99_1_dual_blunt',
    'name' => 'Paulinas Helios Dual Blunt Weapon',
    'additionalname' => NULL,
    'description' => '<Special properties> Atk. Spd. +15%, Critical Rate for standard attacks +100, Critical Damage for standard attacks +5%, Max HP +15%, PvE damage +10%. Its appearance cannot be modified. Cannot be enchanted, augmented, upgraded with Soul Crystal, crystallized, imbued with an attribute.',
    'is_trade' => 0,
    'is_drop' => 0,
    'is_destruct' => 1,
    'crystal_type' => 'r',
    'consume_type' => 'consume_type_normal',
  ],
  80035 => 
  [
    'item_id' => 80035,
    'icon' => 'bm_armor_helmet_i00',
    'name' => 'Paulinas Eternal Helmet',
    'additionalname' => 'Heavy armor',
    'description' => 'Cannot be enchanted, crystallized or assigned an attribute.',
    'is_trade' => 0,
    'is_drop' => 0,
    'is_destruct' => 1,
    'crystal_type' => 'r',
    'consume_type' => 'consume_type_normal',
  ],
  80036 => 
  [
    'item_id' => 80036,
    'icon' => 'bm_polyne_R99_1_heavy_upbody',
    'name' => 'Paulinas Eternal Breastplate',
    'additionalname' => 'Heavy armor',
    'description' => 'Cannot be enchanted, crystallized or assigned an attribute.',
    'is_trade' => 0,
    'is_drop' => 0,
    'is_destruct' => 1,
    'crystal_type' => 'r',
    'consume_type' => 'consume_type_normal',
  ],
  80037 => 
  [
    'item_id' => 80037,
    'icon' => 'bm_polyne_R99_1_heavy_downbody',
    'name' => 'Paulinas Eternal Gaiters',
    'additionalname' => 'Heavy armor',
    'description' => 'Cannot be enchanted, crystallized or assigned an attribute.',
    'is_trade' => 0,
    'is_drop' => 0,
    'is_destruct' => 1,
    'crystal_type' => 'r',
    'consume_type' => 'consume_type_normal',
  ],
  80038 => 
  [
    'item_id' => 80038,
    'icon' => 'bm_polyne_R99_1_heavy_gloves',
    'name' => 'Paulinas Eternal Gauntlets',
    'additionalname' => 'Heavy armor',
    'description' => 'Cannot be enchanted, crystallized or assigned an attribute.',
    'is_trade' => 0,
    'is_drop' => 0,
    'is_destruct' => 1,
    'crystal_type' => 'r',
    'consume_type' => 'consume_type_normal',
  ],
  80039 => 
  [
    'item_id' => 80039,
    'icon' => 'bm_polyne_R99_1_heavy_shoes',
    'name' => 'Paulinas Eternal Boots',
    'additionalname' => 'Heavy armor',
    'description' => 'Cannot be enchanted, crystallized or assigned an attribute.',
    'is_trade' => 0,
    'is_drop' => 0,
    'is_destruct' => 1,
    'crystal_type' => 'r',
    'consume_type' => 'consume_type_normal',
  ],
  80040 => 
  [
    'item_id' => 80040,
    'icon' => 'bm_polyne_R99_1_heavy_shield',
    'name' => 'Paulinas Eternal Shield',
    'additionalname' => NULL,
    'description' => 'Cannot be enchanted or crystallized.',
    'is_trade' => 0,
    'is_drop' => 0,
    'is_destruct' => 1,
    'crystal_type' => 'r',
    'consume_type' => 'consume_type_normal',
  ],
  80041 => 
  [
    'item_id' => 80041,
    'icon' => 'bm_armor_helmet_i00',
    'name' => 'Paulinas Eternal Helmet',
    'additionalname' => 'Light armor',
    'description' => 'Cannot be enchanted, crystallized or assigned an attribute.',
    'is_trade' => 0,
    'is_drop' => 0,
    'is_destruct' => 1,
    'crystal_type' => 'r',
    'consume_type' => 'consume_type_normal',
  ],
  80042 => 
  [
    'item_id' => 80042,
    'icon' => 'bm_polyne_R99_1_light_upbody',
    'name' => 'Paulinas Eternal Armor',
    'additionalname' => 'Light armor',
    'description' => 'Cannot be enchanted, crystallized or assigned an attribute.',
    'is_trade' => 0,
    'is_drop' => 0,
    'is_destruct' => 1,
    'crystal_type' => 'r',
    'consume_type' => 'consume_type_normal',
  ],
  80043 => 
  [
    'item_id' => 80043,
    'icon' => 'bm_polyne_R99_1_light_downbody',
    'name' => 'Paulinas Eternal Leggings',
    'additionalname' => 'Light armor',
    'description' => 'Cannot be enchanted, crystallized or assigned an attribute.',
    'is_trade' => 0,
    'is_drop' => 0,
    'is_destruct' => 1,
    'crystal_type' => 'r',
    'consume_type' => 'consume_type_normal',
  ],
  80044 => 
  [
    'item_id' => 80044,
    'icon' => 'bm_polyne_R99_1_light_gloves',
    'name' => 'Paulinas Eternal Gloves',
    'additionalname' => 'Light armor',
    'description' => 'Cannot be enchanted, crystallized or assigned an attribute.',
    'is_trade' => 0,
    'is_drop' => 0,
    'is_destruct' => 1,
    'crystal_type' => 'r',
    'consume_type' => 'consume_type_normal',
  ],
  80045 => 
  [
    'item_id' => 80045,
    'icon' => 'bm_polyne_R99_1_light_shoes',
    'name' => 'Paulinas Eternal Boots',
    'additionalname' => 'Light armor',
    'description' => 'Cannot be enchanted, crystallized or assigned an attribute.',
    'is_trade' => 0,
    'is_drop' => 0,
    'is_destruct' => 1,
    'crystal_type' => 'r',
    'consume_type' => 'consume_type_normal',
  ],
  80046 => 
  [
    'item_id' => 80046,
    'icon' => 'bm_armor_circlet_i00',
    'name' => 'Paulinas Eternal Circlet',
    'additionalname' => 'Robe',
    'description' => 'Cannot be enchanted, crystallized or assigned an attribute.',
    'is_trade' => 0,
    'is_drop' => 0,
    'is_destruct' => 1,
    'crystal_type' => 'r',
    'consume_type' => 'consume_type_normal',
  ],
  80047 => 
  [
    'item_id' => 80047,
    'icon' => 'bm_polyne_R99_1_robe_upbody',
    'name' => 'Paulinas Eternal Tunic',
    'additionalname' => 'Robe',
    'description' => 'Cannot be enchanted, crystallized or assigned an attribute.',
    'is_trade' => 0,
    'is_drop' => 0,
    'is_destruct' => 1,
    'crystal_type' => 'r',
    'consume_type' => 'consume_type_normal',
  ],
  80048 => 
  [
    'item_id' => 80048,
    'icon' => 'bm_polyne_R99_1_robe_downbody',
    'name' => 'Paulinas Eternal Stockings',
    'additionalname' => 'Robe',
    'description' => 'Cannot be enchanted, crystallized or assigned an attribute.',
    'is_trade' => 0,
    'is_drop' => 0,
    'is_destruct' => 1,
    'crystal_type' => 'r',
    'consume_type' => 'consume_type_normal',
  ],
  80049 => 
  [
    'item_id' => 80049,
    'icon' => 'bm_polyne_R99_1_robe_gloves',
    'name' => 'Paulinas Eternal Gloves',
    'additionalname' => 'Robe',
    'description' => 'Cannot be enchanted, crystallized or assigned an attribute.',
    'is_trade' => 0,
    'is_drop' => 0,
    'is_destruct' => 1,
    'crystal_type' => 'r',
    'consume_type' => 'consume_type_normal',
  ],
  80050 => 
  [
    'item_id' => 80050,
    'icon' => 'bm_polyne_R99_1_robe_shoes',
    'name' => 'Paulinas Eternal Shoes',
    'additionalname' => 'Robe',
    'description' => 'Cannot be enchanted, crystallized or assigned an attribute.',
    'is_trade' => 0,
    'is_drop' => 0,
    'is_destruct' => 1,
    'crystal_type' => 'r',
    'consume_type' => 'consume_type_normal',
  ],
  80051 => 
  [
    'item_id' => 80051,
    'icon' => 'bm_polyne_R99_1_robe_sigil',
    'name' => 'Paulinas Eternal Sigil',
    'additionalname' => NULL,
    'description' => 'Cannot be enchanted or crystallized.',
    'is_trade' => 0,
    'is_drop' => 0,
    'is_destruct' => 1,
    'crystal_type' => 'r',
    'consume_type' => 'consume_type_normal',
  ],
  80052 => 
  [
    'item_id' => 80052,
    'icon' => 'bm_polyne_R99_1_necklace',
    'name' => 'Paulinas Eternal Necklace',
    'additionalname' => 'Skill Cooldown',
    'description' => 'MP +65, Skill Cooldown -10%.Cannot be enchanted or crystallized.',
    'is_trade' => 0,
    'is_drop' => 0,
    'is_destruct' => 1,
    'crystal_type' => 'r',
    'consume_type' => 'consume_type_normal',
  ],
  80053 => 
  [
    'item_id' => 80053,
    'icon' => 'bm_polyne_R99_1_earring',
    'name' => 'Paulinas Eternal Earring',
    'additionalname' => 'MP Consumption',
    'description' => 'MP +49, Received Healing +10%, MP Consumption -5%. Effects of two identical earrings do not stack.Cannot be enchanted or crystallized.',
    'is_trade' => 0,
    'is_drop' => 0,
    'is_destruct' => 1,
    'crystal_type' => 'r',
    'consume_type' => 'consume_type_normal',
  ],
  80054 => 
  [
    'item_id' => 80054,
    'icon' => 'bm_polyne_R99_1_earring',
    'name' => 'Paulinas Eternal Earring',
    'additionalname' => 'Vampiric Rage',
    'description' => 'MP +49, Vampiric Rage effect +5%. Effects of two identical earrings do not stack.Cannot be enchanted or crystallized.',
    'is_trade' => 0,
    'is_drop' => 0,
    'is_destruct' => 1,
    'crystal_type' => 'r',
    'consume_type' => 'consume_type_normal',
  ],
  80055 => 
  [
    'item_id' => 80055,
    'icon' => 'bm_polyne_R99_1_ring',
    'name' => 'Paulinas Eternal Ring',
    'additionalname' => 'Critical Rate',
    'description' => 'MP +33, P Critical Rate/ M. Skill Critical Rate +50. The effect doesnt stack if two identical earring are equipped.Cannot be enchanted or crystallized.',
    'is_trade' => 0,
    'is_drop' => 0,
    'is_destruct' => 1,
    'crystal_type' => 'r',
    'consume_type' => 'consume_type_normal',
  ],
  80056 => 
  [
    'item_id' => 80056,
    'icon' => 'bm_polyne_R99_1_ring',
    'name' => 'Paulinas Eternal Ring',
    'additionalname' => 'Critical Damage',
    'description' => 'MP +33, P. Critical Damage and P./ M. Skill Critical Damage +15%. The effect doesnt stack if two identical earring are equipped.Cannot be enchanted or crystallized.',
    'is_trade' => 0,
    'is_drop' => 0,
    'is_destruct' => 1,
    'crystal_type' => 'r',
    'consume_type' => 'consume_type_normal',
  ],
  80057 => 
  [
    'item_id' => 80057,
    'icon' => 'bm_polyne_R99_bracelet',
    'name' => 'Paulinas Eternal Bracelet',
    'additionalname' => NULL,
    'description' => 'MP +225, unlocks 6 talisman slots. P./ M. Atk. and P./ M. Def. +3%.Cannot be enchanted or crystallized.',
    'is_trade' => 0,
    'is_drop' => 0,
    'is_destruct' => 1,
    'crystal_type' => 'r',
    'consume_type' => 'consume_type_normal',
  ],
  80058 => 
  [
    'item_id' => 80058,
    'icon' => 'ainhasard_shirt_box_1',
    'name' => '+5 Shiny Elemental Shirt Pack',
    'additionalname' => NULL,
    'description' => 'Double-click to obtain a +5 Enchanted Shiny Elemental Shirt.',
    'is_trade' => 1,
    'is_drop' => 1,
    'is_destruct' => 1,
    'crystal_type' => 'crystal_free',
    'consume_type' => 'consume_type_stackable',
  ],
  80059 => 
  [
    'item_id' => 80059,
    'icon' => 'reflect_attack_shirt_box_2',
    'name' => '+5 Physical Reflect Shirt Pack',
    'additionalname' => NULL,
    'description' => 'Double-click to obtain +5 Physical Reflect Shirt.',
    'is_trade' => 1,
    'is_drop' => 1,
    'is_destruct' => 1,
    'crystal_type' => 'crystal_free',
    'consume_type' => 'consume_type_stackable',
  ],
  80060 => 
  [
    'item_id' => 80060,
    'icon' => 'reflect_magic_shirt_box_3',
    'name' => '+5 Magical Reflect Shirt Pack',
    'additionalname' => NULL,
    'description' => 'Double-click to obtain +5 Magical Reflect Shirt.',
    'is_trade' => 1,
    'is_drop' => 1,
    'is_destruct' => 1,
    'crystal_type' => 'crystal_free',
    'consume_type' => 'consume_type_stackable',
  ],
  80061 => 
  [
    'item_id' => 80061,
    'icon' => 'bm_special_cocktail_of_king_p',
    'name' => 'Emperors Special Cocktail',
    'additionalname' => 'Attack',
    'description' => 'For 60 min., applies the following effects: Musicians Melody Lv. 5, Warriors Harmony Lv. 2, Drum Concert, United Resistance. Note! Emperors Special Cocktail extends the duration of the last used item.',
    'is_trade' => 1,
    'is_drop' => 1,
    'is_destruct' => 1,
    'crystal_type' => 'crystal_free',
    'consume_type' => 'consume_type_stackable',
  ],
  80062 => 
  [
    'item_id' => 80062,
    'icon' => 'bm_special_cocktail_of_king_m',
    'name' => 'Emperors Special Cocktail',
    'additionalname' => 'Magic',
    'description' => 'For 60 min., applies the following effects: Musicians Melody Lv. 5, Wizards Harmony Lv. 2, Drum Concert, United Resistance. Note! Emperors Special Cocktail extends the duration of the last used item.',
    'is_trade' => 1,
    'is_drop' => 1,
    'is_destruct' => 1,
    'crystal_type' => 'crystal_free',
    'consume_type' => 'consume_type_stackable',
  ],
  80063 => 
  [
    'item_id' => 80063,
    'icon' => 'bm_special_cocktail_of_king_d',
    'name' => 'Emperors Special Cocktail',
    'additionalname' => 'Defense',
    'description' => 'For 60 min., applies the following effects: Musicians Melody Lv. 5, Knights Harmony Lv. 2, Drum Concert, United Resistance. Note! Emperors Special Cocktail extends the duration of the last used item.',
    'is_trade' => 1,
    'is_drop' => 1,
    'is_destruct' => 1,
    'crystal_type' => 'crystal_free',
    'consume_type' => 'consume_type_stackable',
  ],
  80064 => 
  [
    'item_id' => 80064,
    'icon' => 'bm_challenger_scroll',
    'name' => 'Challengers Scroll of Growth',
    'additionalname' => NULL,
    'description' => 'For 10 min., acquired XP/ SP while hunting +200%. The effect remains after death. Cooldown: 9 min. Required level: 1-105.  The effect does not stack with those of Freyas Frozen Scroll and Freyas Scroll of Storm.',
    'is_trade' => 0,
    'is_drop' => 0,
    'is_destruct' => 1,
    'crystal_type' => 'crystal_free',
    'consume_type' => 'consume_type_stackable',
  ],
  80065 => 
  [
    'item_id' => 80065,
    'icon' => 'etc_bm_kalie_instantzone_re',
    'name' => 'Extra Pass: Altar of Shillien',
    'additionalname' => NULL,
    'description' => 'Additional pass to the Altar of Shillien. Double-click to reset cooldown to the dungeon. Can only be used when on a cooldown to the instance zone. Can only be used once during the set time period outside of the instance zone.',
    'is_trade' => 1,
    'is_drop' => 1,
    'is_destruct' => 1,
    'crystal_type' => 'crystal_free',
    'consume_type' => 'consume_type_stackable',
  ],
  80066 => 
  [
    'item_id' => 80066,
    'icon' => 'fafurion_avenger_i00',
    'name' => 'Fafurion Avenger',
    'additionalname' => 'Low-grade',
    'description' => 'Fafurion Avenger Fragment. Max HP can be more than 150,000. Cannot be enchanted, augmented, crystallized, appearance modified, assigned an attribute.  <Enhancing> Take the fragment and Dragon Claw to Lionel Hunter in Heine to get a Fafurions standard weapon.',
    'is_trade' => 1,
    'is_drop' => 1,
    'is_destruct' => 1,
    'crystal_type' => 'r',
    'consume_type' => 'consume_type_normal',
  ],
  80067 => 
  [
    'item_id' => 80067,
    'icon' => 'fafurion_fighter_i00',
    'name' => 'Fafurion Fighter',
    'additionalname' => 'Low-grade',
    'description' => 'Fafurion Fighter Fragment. Max HP can be more than 150,000. Cannot be enchanted, augmented, crystallized, appearance modified, assigned an attribute.  <Enhancing> Take the fragment and Dragon Claw to Lionel Hunter in Heine to get a Fafurions standard weapon.',
    'is_trade' => 1,
    'is_drop' => 1,
    'is_destruct' => 1,
    'crystal_type' => 'r',
    'consume_type' => 'consume_type_normal',
  ],
  80068 => 
  [
    'item_id' => 80068,
    'icon' => 'fafurion_stormer_i00',
    'name' => 'Fafurion Stormer',
    'additionalname' => 'Low-grade',
    'description' => 'Fafurion Stormer Fragment. Max HP can be more than 150,000. Cannot be enchanted, augmented, crystallized, appearance modified, assigned an attribute.  <Enhancing> Take the fragment and Dragon Claw to Lionel Hunter in Heine to get a Fafurions standard weapon.',
    'is_trade' => 1,
    'is_drop' => 1,
    'is_destruct' => 1,
    'crystal_type' => 'r',
    'consume_type' => 'consume_type_normal',
  ],
  80069 => 
  [
    'item_id' => 80069,
    'icon' => 'fafurion_retributer_i00',
    'name' => 'Fafurion Retributer',
    'additionalname' => 'Low-grade',
    'description' => 'Fafurion Retributer Fragment. Max HP can be more than 150,000. Cannot be enchanted, augmented, crystallized, appearance modified, assigned an attribute.  <Enhancing> Take the fragment and Dragon Claw to Lionel Hunter in Heine to get a Fafurions standard weapon.',
    'is_trade' => 1,
    'is_drop' => 1,
    'is_destruct' => 1,
    'crystal_type' => 'r',
    'consume_type' => 'consume_type_normal',
  ],
  80070 => 
  [
    'item_id' => 80070,
    'icon' => 'fafurion_dual_blunt_i00',
    'name' => 'Fafurion Dual Blunt Weapon',
    'additionalname' => 'Low-grade',
    'description' => 'Fafurion Dual Blunt Weapon Fragment. Max HP can be more than 150,000. Cannot be enchanted, augmented, crystallized, appearance modified, assigned an attribute.  <Enhancing> Take the fragment and Dragon Claw to Lionel Hunter in Heine to get a Fafurions standard weapon.',
    'is_trade' => 1,
    'is_drop' => 1,
    'is_destruct' => 1,
    'crystal_type' => 'r',
    'consume_type' => 'consume_type_normal',
  ],
  80071 => 
  [
    'item_id' => 80071,
    'icon' => 'fafurion_onehand_dual_sword_i00',
    'name' => 'Fafurion Dual Swords',
    'additionalname' => 'Low-grade',
    'description' => 'Fafurion Dual Swords Fragment. Max HP can be more than 150,000. Cannot be enchanted, augmented, crystallized, appearance modified, assigned an attribute.  <Enhancing> Take the fragment and Dragon Claw to Lionel Hunter in Heine to get a Fafurions standard weapon.',
    'is_trade' => 1,
    'is_drop' => 1,
    'is_destruct' => 1,
    'crystal_type' => 'r',
    'consume_type' => 'consume_type_normal',
  ],
  80072 => 
  [
    'item_id' => 80072,
    'icon' => 'fafurion_avenger_i01',
    'name' => 'Fafurion Avenger',
    'additionalname' => 'Standard',
    'description' => 'A weapon imbued with the power of the dragons. Cannot be enchanted, crystallized or imbued with an attribute. The items appearance cannot be modified. 2 common soul crystals and 1 special soul crystal can be inserted.  <font color=ff6666><Additional effect when equipped></font> PvP damage +30% Max HP/ MP/ CP +30% Atk. Spd. +30% Critical Rate for basic attacks +100 P. Skill Critical Rate +30% P. Skill Critical Damage +30% Damage to dragons +100% Max HP can be more than 150,000.  <Upgrading> Take the weapon and Dragon Claw to Fafurions Watcher Lionel Hunter to enhance it to a high-grade Fafurions weapon.',
    'is_trade' => 1,
    'is_drop' => 1,
    'is_destruct' => 1,
    'crystal_type' => 'r',
    'consume_type' => 'consume_type_normal',
  ],
  80073 => 
  [
    'item_id' => 80073,
    'icon' => 'fafurion_fighter_i01',
    'name' => 'Fafurion Fighter',
    'additionalname' => 'Standard',
    'description' => 'A weapon imbued with the power of the dragons. Cannot be enchanted, crystallized or imbued with an attribute. The items appearance cannot be modified. 2 common soul crystals and 1 special soul crystal can be inserted.  <font color=ff6666><Additional effect when equipped></font> PvP damage +30% Max HP/ MP/ CP +30% Atk. Spd. +30% Critical Rate for basic attacks +100 P. Skill Critical Rate +30% P. Skill Critical Damage +30% Damage to dragons +100% Max HP can be more than 150,000.  <Upgrading> Take the weapon and Dragon Claw to Fafurions Watcher Lionel Hunter to enhance it to a high-grade Fafurions weapon.',
    'is_trade' => 1,
    'is_drop' => 1,
    'is_destruct' => 1,
    'crystal_type' => 'r',
    'consume_type' => 'consume_type_normal',
  ],
  80074 => 
  [
    'item_id' => 80074,
    'icon' => 'fafurion_stormer_i01',
    'name' => 'Fafurion Stormer',
    'additionalname' => 'Standard',
    'description' => 'A weapon imbued with the power of the dragons. Cannot be enchanted, crystallized or imbued with an attribute. The items appearance cannot be modified. 2 common soul crystals and 1 special soul crystal can be inserted.  <font color=ff6666><Additional effect when equipped></font> PvP damage +30% Max HP/ MP/ CP +30% Atk. Spd. +30% Critical Rate for basic attacks +100 P. Skill Critical Rate +30% P. Skill Critical Damage +30% Damage to dragons +100% Max HP can be more than 150,000.  <Upgrading> Take the weapon and Dragon Claw to Fafurions Watcher Lionel Hunter to enhance it to a high-grade Fafurions weapon.',
    'is_trade' => 1,
    'is_drop' => 1,
    'is_destruct' => 1,
    'crystal_type' => 'r',
    'consume_type' => 'consume_type_normal',
  ],
  80075 => 
  [
    'item_id' => 80075,
    'icon' => 'fafurion_retributer_i01',
    'name' => 'Fafurion Retributer',
    'additionalname' => 'Standard',
    'description' => 'A weapon imbued with the wisdom of the dragons. Cannot be enchanted, crystallized or imbued with an attribute. The items appearance cannot be modified. 2 common soul crystals and 1 special soul crystal can be inserted.  <font color=ff6666><Additional effect when equipped></font> PvP damage +30% Max HP/ MP/ CP +30% Casting Spd. +30% Critical Rate for basic attacks +100 M. Skill Critical Rate +100 M. Skill Critical Damage +30% Damage to dragons +100% Max HP can be more than 150,000.  <Upgrading> Take the weapon and Dragon Claw to Fafurions Watcher Lionel Hunter to enhance it to a high-grade Fafurions weapon.',
    'is_trade' => 1,
    'is_drop' => 1,
    'is_destruct' => 1,
    'crystal_type' => 'r',
    'consume_type' => 'consume_type_normal',
  ],
  80076 => 
  [
    'item_id' => 80076,
    'icon' => 'fafurion_dual_blunt_i01',
    'name' => 'Fafurion Dual Blunt Weapon',
    'additionalname' => 'Standard',
    'description' => 'A weapon imbued with the power of the dragons. Cannot be enchanted, crystallized or imbued with an attribute. The items appearance cannot be modified. 2 common soul crystals and 1 special soul crystal can be inserted.  <font color=ff6666><Additional effect when equipped></font> PvP damage +30% Max HP/ MP/ CP +30% Atk. Spd. +30% Critical Rate for basic attacks +100 P. Skill Critical Rate +30% P. Skill Critical Damage +30% Damage to dragons +100% Max HP can be more than 150,000.  <Upgrading> Take the weapon and Dragon Claw to Fafurions Watcher Lionel Hunter to enhance it to a high-grade Fafurions weapon.',
    'is_trade' => 1,
    'is_drop' => 1,
    'is_destruct' => 1,
    'crystal_type' => 'r',
    'consume_type' => 'consume_type_normal',
  ],
  80077 => 
  [
    'item_id' => 80077,
    'icon' => 'fafurion_onehand_dual_sword_i01',
    'name' => 'Fafurion Dual Swords',
    'additionalname' => 'Standard',
    'description' => 'A weapon imbued with the power of the dragons. Cannot be enchanted, crystallized or imbued with an attribute. The items appearance cannot be modified. 2 common soul crystals and 1 special soul crystal can be inserted.  <font color=ff6666><Additional effect when equipped></font> PvP damage +30% Max HP/ MP/ CP +30% Atk. Spd. +30% Critical Rate for basic attacks +100 P. Skill Critical Rate +30% P. Skill Critical Damage +30% Damage to dragons +100% Max HP can be more than 150,000.  <Upgrading> Take the weapon and Dragon Claw to Fafurions Watcher Lionel Hunter to enhance it to a high-grade Fafurions weapon.',
    'is_trade' => 1,
    'is_drop' => 1,
    'is_destruct' => 1,
    'crystal_type' => 'r',
    'consume_type' => 'consume_type_normal',
  ],
  80078 => 
  [
    'item_id' => 80078,
    'icon' => 'fafurion_avenger_i01',
    'name' => 'Fafurion Avenger',
    'additionalname' => 'High-grade',
    'description' => 'A weapon imbued with the power of the dragons. Cannot be enchanted, crystallized or imbued with an attribute. The items appearance cannot be modified. 2 common soul crystals and 1 special soul crystal can be inserted.  <font color=ff6666><Additional effect when equipped></font> PvP damage +30% Max HP/ MP/ CP +30% Atk. Spd. +30% Critical Rate for basic attacks +100 P. Skill Critical Rate +30% P. Skill Critical Damage +30% Damage to dragons +100% Max HP can be more than 150,000.  <font color=ff6666><Skills available when equipped></font> Dignity Fafurions Rising Wave  <Upgrading> Take the weapon and Dragon Claw to Fafurions Watcher Lionel Hunter to enhance it to a top-grade Fafurions weapon.',
    'is_trade' => 1,
    'is_drop' => 1,
    'is_destruct' => 1,
    'crystal_type' => 'r',
    'consume_type' => 'consume_type_normal',
  ],
  80079 => 
  [
    'item_id' => 80079,
    'icon' => 'fafurion_fighter_i01',
    'name' => 'Fafurion Fighter',
    'additionalname' => 'High-grade',
    'description' => 'A weapon imbued with the power of the dragons. Cannot be enchanted, crystallized or imbued with an attribute. The items appearance cannot be modified. 2 common soul crystals and 1 special soul crystal can be inserted.  <font color=ff6666><Additional effect when equipped></font> PvP damage +30% Max HP/ MP/ CP +30% Atk. Spd. +30% Critical Rate for basic attacks +100 P. Skill Critical Rate +30% P. Skill Critical Damage +30% Damage to dragons +100% Max HP can be more than 150,000.  <font color=ff6666><Skills available when equipped></font> Dignity Fafurions Rising Wave  <Upgrading> Take the weapon and Dragon Claw to Fafurions Watcher Lionel Hunter to enhance it to a top-grade Fafurions weapon.',
    'is_trade' => 1,
    'is_drop' => 1,
    'is_destruct' => 1,
    'crystal_type' => 'r',
    'consume_type' => 'consume_type_normal',
  ],
  80080 => 
  [
    'item_id' => 80080,
    'icon' => 'fafurion_stormer_i01',
    'name' => 'Fafurion Stormer',
    'additionalname' => 'High-grade',
    'description' => 'A weapon imbued with the power of the dragons. Cannot be enchanted, crystallized or imbued with an attribute. The items appearance cannot be modified. 2 common soul crystals and 1 special soul crystal can be inserted.  <font color=ff6666><Additional effect when equipped></font> PvP damage +30% Max HP/ MP/ CP +30% Atk. Spd. +30% Critical Rate for basic attacks +100 P. Skill Critical Rate +30% P. Skill Critical Damage +30% Damage to dragons +100% Max HP can be more than 150,000.  <font color=ff6666><Skills available when equipped></font> Dignity Fafurions Rising Wave  <Upgrading> Take the weapon and Dragon Claw to Fafurions Watcher Lionel Hunter to enhance it to a top-grade Fafurions weapon.',
    'is_trade' => 1,
    'is_drop' => 1,
    'is_destruct' => 1,
    'crystal_type' => 'r',
    'consume_type' => 'consume_type_normal',
  ],
  80081 => 
  [
    'item_id' => 80081,
    'icon' => 'fafurion_retributer_i01',
    'name' => 'Fafurion Retributer',
    'additionalname' => 'High-grade',
    'description' => 'A weapon imbued with the wisdom of the dragons. Cannot be enchanted, crystallized or imbued with an attribute. The items appearance cannot be modified. 2 common soul crystals and 1 special soul crystal can be inserted.  <font color=ff6666><Additional effect when equipped></font> PvP damage +30% Max HP/ MP/ CP +30% Casting Spd. +30% Critical Rate for basic attacks +100 M. Skill Critical Rate +100 M. Skill Critical Damage +30% Damage to dragons +100% Max HP can be more than 150,000.  <font color=ff6666><Skills available when equipped></font> Dignity Fafurions Rising Wave  <Upgrading> Take the weapon and Dragon Claw to Fafurions Watcher Lionel Hunter to enhance it to a top-grade Fafurions weapon.',
    'is_trade' => 1,
    'is_drop' => 1,
    'is_destruct' => 1,
    'crystal_type' => 'r',
    'consume_type' => 'consume_type_normal',
  ],
  80082 => 
  [
    'item_id' => 80082,
    'icon' => 'fafurion_dual_blunt_i01',
    'name' => 'Fafurion Dual Blunt Weapon',
    'additionalname' => 'High-grade',
    'description' => 'A weapon imbued with the power of the dragons. Cannot be enchanted, crystallized or imbued with an attribute. The items appearance cannot be modified. 2 common soul crystals and 1 special soul crystal can be inserted.  <font color=ff6666><Additional effect when equipped></font> PvP damage +30% Max HP/ MP/ CP +30% Atk. Spd. +30% Critical Rate for basic attacks +100 P. Skill Critical Rate +30% P. Skill Critical Damage +30% Damage to dragons +100% Max HP can be more than 150,000.  <font color=ff6666><Skills available when equipped></font> Dignity Fafurions Rising Wave  <Upgrading> Take the weapon and Dragon Claw to Fafurions Watcher Lionel Hunter to enhance it to a top-grade Fafurions weapon.',
    'is_trade' => 1,
    'is_drop' => 1,
    'is_destruct' => 1,
    'crystal_type' => 'r',
    'consume_type' => 'consume_type_normal',
  ],
  80083 => 
  [
    'item_id' => 80083,
    'icon' => 'fafurion_onehand_dual_sword_i01',
    'name' => 'Fafurion Dual Swords',
    'additionalname' => 'High-grade',
    'description' => 'A weapon imbued with the power of the dragons. Cannot be enchanted, crystallized or imbued with an attribute. The items appearance cannot be modified. 2 common soul crystals and 1 special soul crystal can be inserted.  <font color=ff6666><Additional effect when equipped></font> PvP damage +30% Max HP/ MP/ CP +30% Atk. Spd. +30% Critical Rate for basic attacks +100 P. Skill Critical Rate +30% P. Skill Critical Damage +30% Damage to dragons +100% Max HP can be more than 150,000.  <font color=ff6666><Skills available when equipped></font> Dignity Fafurions Rising Wave  <Upgrading> Take the weapon and Dragon Claw to Fafurions Watcher Lionel Hunter to enhance it to a top-grade Fafurions weapon.',
    'is_trade' => 1,
    'is_drop' => 1,
    'is_destruct' => 1,
    'crystal_type' => 'r',
    'consume_type' => 'consume_type_normal',
  ],
  80084 => 
  [
    'item_id' => 80084,
    'icon' => 'fafurion_avenger_i01',
    'name' => 'Fafurion Avenger',
    'additionalname' => 'Top-grade',
    'description' => 'A weapon imbued with the power of the dragons. Cannot be enchanted, crystallized or imbued with an attribute. The items appearance cannot be modified. 2 common soul crystals and 1 special soul crystal can be inserted.  <font color=ff6666><Additional effect when equipped></font> PvP damage +50% Max HP/ MP/ CP +100% Atk. Spd. +100% Critical Rate for basic attacks +500 P. Skill Critical Rate +50% P. Skill Critical Damage +50% Damage to dragons +300% Max HP can be more than 150,000.  <font color=ff6666><Skills available when equipped></font> Dignity Fafurions Rising Wave Fafurions Breath',
    'is_trade' => 1,
    'is_drop' => 1,
    'is_destruct' => 1,
    'crystal_type' => 'r',
    'consume_type' => 'consume_type_normal',
  ],
  80085 => 
  [
    'item_id' => 80085,
    'icon' => 'fafurion_fighter_i01',
    'name' => 'Fafurion Fighter',
    'additionalname' => 'Top-grade',
    'description' => 'A weapon imbued with the power of the dragons. Cannot be enchanted, crystallized or imbued with an attribute. The items appearance cannot be modified. 2 common soul crystals and 1 special soul crystal can be inserted.  <font color=ff6666><Additional effect when equipped></font> PvP damage +50% Max HP/ MP/ CP +100% Atk. Spd. +100% Critical Rate for basic attacks +500 P. Skill Critical Rate +50% P. Skill Critical Damage +50% Damage to dragons +300% Max HP can be more than 150,000.  <font color=ff6666><Skills available when equipped></font> Dignity Fafurions Rising Wave Fafurions Breath',
    'is_trade' => 1,
    'is_drop' => 1,
    'is_destruct' => 1,
    'crystal_type' => 'r',
    'consume_type' => 'consume_type_normal',
  ],
  80086 => 
  [
    'item_id' => 80086,
    'icon' => 'fafurion_stormer_i01',
    'name' => 'Fafurion Stormer',
    'additionalname' => 'Top-grade',
    'description' => 'A weapon imbued with the power of the dragons. Cannot be enchanted, crystallized or imbued with an attribute. The items appearance cannot be modified. 2 common soul crystals and 1 special soul crystal can be inserted.  <font color=ff6666><Additional effect when equipped></font> PvP damage +50% Max HP/ MP/ CP +100% Atk. Spd. +100% Critical Rate for basic attacks +500 P. Skill Critical Rate +50% P. Skill Critical Damage +50% Damage to dragons +300% Max HP can be more than 150,000.  <font color=ff6666><Skills available when equipped></font> Dignity Fafurions Rising Wave Fafurions Breath',
    'is_trade' => 1,
    'is_drop' => 1,
    'is_destruct' => 1,
    'crystal_type' => 'r',
    'consume_type' => 'consume_type_normal',
  ],
  80087 => 
  [
    'item_id' => 80087,
    'icon' => 'fafurion_retributer_i01',
    'name' => 'Fafurion Retributer',
    'additionalname' => 'Top-grade',
    'description' => 'A weapon imbued with the wisdom of the dragons. Cannot be enchanted, crystallized or imbued with an attribute. The items appearance cannot be modified. 2 common soul crystals and 1 special soul crystal can be inserted.  <font color=ff6666><Additional effect when equipped></font> PvP damage +50% Max HP/ MP/ CP +100% Casting Spd. +100% Critical Rate for basic attacks +500 M. Skill Critical Rate +500 M. Skill Critical Damage +50% Damage to dragons +300% Max HP can be more than 150,000.  <font color=ff6666><Skills available when equipped></font> Dignity Fafurions Rising Wave Fafurions Breath',
    'is_trade' => 1,
    'is_drop' => 1,
    'is_destruct' => 1,
    'crystal_type' => 'r',
    'consume_type' => 'consume_type_normal',
  ],
  80088 => 
  [
    'item_id' => 80088,
    'icon' => 'fafurion_dual_blunt_i01',
    'name' => 'Fafurion Dual Blunt Weapon',
    'additionalname' => 'Top-grade',
    'description' => 'A weapon imbued with the power of the dragons. Cannot be enchanted, crystallized or imbued with an attribute. The items appearance cannot be modified. 2 common soul crystals and 1 special soul crystal can be inserted.  <font color=ff6666><Additional effect when equipped></font> PvP damage +50% Max HP/ MP/ CP +100% Atk. Spd. +100% Critical Rate for basic attacks +500 P. Skill Critical Rate +50% P. Skill Critical Damage +50% Damage to dragons +300% Max HP can be more than 150,000.  <font color=ff6666><Skills available when equipped></font> Dignity Fafurions Rising Wave Fafurions Breath',
    'is_trade' => 1,
    'is_drop' => 1,
    'is_destruct' => 1,
    'crystal_type' => 'r',
    'consume_type' => 'consume_type_normal',
  ],
  80089 => 
  [
    'item_id' => 80089,
    'icon' => 'fafurion_onehand_dual_sword_i01',
    'name' => 'Fafurion Dual Swords',
    'additionalname' => 'Top-grade',
    'description' => 'A weapon imbued with the power of the dragons. Cannot be enchanted, crystallized or imbued with an attribute. The items appearance cannot be modified. 2 common soul crystals and 1 special soul crystal can be inserted.  <font color=ff6666><Additional effect when equipped></font> PvP damage +50% Max HP/ MP/ CP +100% Atk. Spd. +100% Critical Rate for basic attacks +500 P. Skill Critical Rate +50% P. Skill Critical Damage +50% Damage to dragons +300% Max HP can be more than 150,000.  <font color=ff6666><Skills available when equipped></font> Dignity Fafurions Rising Wave Fafurions Breath',
    'is_trade' => 1,
    'is_drop' => 1,
    'is_destruct' => 1,
    'crystal_type' => 'r',
    'consume_type' => 'consume_type_normal',
  ],
  80090 => 
  [
    'item_id' => 80090,
    'icon' => 'weapon_r110_dagger_i00',
    'name' => 'Krishna Shaper',
    'additionalname' => NULL,
    'description' => '2 regular Soul Crystals and 1 special Soul Crystal can be inserted. When enchanted to +4, P. Accuracy +4, P. Skill Critical Damage +2%.  <Enchanting> Use Scroll: Enchant R-grade Weapon.',
    'is_trade' => 1,
    'is_drop' => 1,
    'is_destruct' => 1,
    'crystal_type' => 'r110',
    'consume_type' => 'consume_type_normal',
  ],
  80091 => 
  [
    'item_id' => 80091,
    'icon' => 'weapon_r110_onehand_sword_i00',
    'name' => 'Krishna Cutter',
    'additionalname' => NULL,
    'description' => '2 regular Soul Crystals and 1 special Soul Crystal can be inserted. When enchanted to +4, P. Accuracy +4, Critical Rate for standard attacks +30.  <Enchanting> Use Scroll: Enchant R-grade Weapon.',
    'is_trade' => 1,
    'is_drop' => 1,
    'is_destruct' => 1,
    'crystal_type' => 'r110',
    'consume_type' => 'consume_type_normal',
  ],
  80092 => 
  [
    'item_id' => 80092,
    'icon' => 'weapon_r110_twohand_sword_i00',
    'name' => 'Krishna Slasher',
    'additionalname' => NULL,
    'description' => '2 regular Soul Crystals and 1 special Soul Crystal can be inserted. When enchanted to +4, P. Atk. +5%.  <Enchanting> Use Scroll: Enchant R-grade Weapon.',
    'is_trade' => 1,
    'is_drop' => 1,
    'is_destruct' => 1,
    'crystal_type' => 'r110',
    'consume_type' => 'consume_type_normal',
  ],
  80093 => 
  [
    'item_id' => 80093,
    'icon' => 'weapon_r110_onehand_blunt_i00',
    'name' => 'Krishna Avenger',
    'additionalname' => NULL,
    'description' => '2 regular Soul Crystals and 1 special Soul Crystal can be inserted. When enchanted to +4, P. Accuracy +4, P./ M. Skill Power +2%.  <Enchanting> Use Scroll: Enchant R-grade Weapon.',
    'is_trade' => 1,
    'is_drop' => 1,
    'is_destruct' => 1,
    'crystal_type' => 'r110',
    'consume_type' => 'consume_type_normal',
  ],
  80094 => 
  [
    'item_id' => 80094,
    'icon' => 'weapon_r110_fist_i00',
    'name' => 'Krishna Fighter',
    'additionalname' => NULL,
    'description' => '2 regular Soul Crystals and 1 special Soul Crystal can be inserted. When enchanted to +4, P. Atk. +2%, Critical Damage for standard attacks +2%.  <Enchanting> Use Scroll: Enchant R-grade Weapon.',
    'is_trade' => 1,
    'is_drop' => 1,
    'is_destruct' => 1,
    'crystal_type' => 'r110',
    'consume_type' => 'consume_type_normal',
  ],
  80095 => 
  [
    'item_id' => 80095,
    'icon' => 'weapon_r110_spear_i00',
    'name' => 'Krishna Stormer',
    'additionalname' => NULL,
    'description' => '2 regular Soul Crystals and 1 special Soul Crystal can be inserted. When enchanted to +4, P. Atk. +2%, increases the number of targets attacked with a spear.  <Enchanting> Use Scroll: Enchant R-grade Weapon.',
    'is_trade' => 1,
    'is_drop' => 1,
    'is_destruct' => 1,
    'crystal_type' => 'r110',
    'consume_type' => 'consume_type_normal',
  ],
  80096 => 
  [
    'item_id' => 80096,
    'icon' => 'weapon_r110_bow_i00',
    'name' => 'Krishna Thrower',
    'additionalname' => NULL,
    'description' => '2 regular Soul Crystals and 1 special Soul Crystal can be inserted. When enchanted to +4, P. Atk. +2%, Atk. Spd. +2%.  <Enchanting> Use Scroll: Enchant R-grade Weapon.',
    'is_trade' => 1,
    'is_drop' => 1,
    'is_destruct' => 1,
    'crystal_type' => 'r110',
    'consume_type' => 'consume_type_normal',
  ],
  80097 => 
  [
    'item_id' => 80097,
    'icon' => 'weapon_r110_crossbow_i00',
    'name' => 'Krishna Guardian',
    'additionalname' => NULL,
    'description' => '2 regular Soul Crystals and 1 special Soul Crystal can be inserted. When enchanted to +4, P. Atk. +2%, P. Skill Power +2%.  <Enchanting> Use Scroll: Enchant R-grade Weapon.',
    'is_trade' => 1,
    'is_drop' => 1,
    'is_destruct' => 1,
    'crystal_type' => 'r110',
    'consume_type' => 'consume_type_normal',
  ],
  80098 => 
  [
    'item_id' => 80098,
    'icon' => 'weapon_r110_onehand_magic_sword_i00',
    'name' => 'Krishna Buster',
    'additionalname' => NULL,
    'description' => '2 regular Soul Crystals and 1 special Soul Crystal can be inserted. When enchanted to +4, M. Accuracy +4, M. Skill Power +2%.  <Enchanting> Use Scroll: Enchant R-grade Weapon.',
    'is_trade' => 1,
    'is_drop' => 1,
    'is_destruct' => 1,
    'crystal_type' => 'r110',
    'consume_type' => 'consume_type_normal',
  ],
  80099 => 
  [
    'item_id' => 80099,
    'icon' => 'weapon_r110_onehand_magic_blunt_i00',
    'name' => 'Krishna Caster',
    'additionalname' => NULL,
    'description' => '2 regular Soul Crystals and 1 special Soul Crystal can be inserted. When enchanted to +4, M. Accuracy +4, Casting Spd. +2%.  <Enchanting> Use Scroll: Enchant R-grade Weapon.',
    'is_trade' => 1,
    'is_drop' => 1,
    'is_destruct' => 1,
    'crystal_type' => 'r110',
    'consume_type' => 'consume_type_normal',
  ],
];