<?php return [
  9200 => 
  [
    'item_id' => 9200,
    'icon' => 'accessory_jester_cap_i00',
    'name' => 'Shadow Item: Jester Hat',
    'additionalname' => 'Firework',
    'description' => 'Festive, shadow-type jester hat with 2 points. Uses 2 hair accessory slots. Event hair accessory that grants a magical effect. ',
    'is_trade' => 0,
    'is_drop' => 0,
    'is_destruct' => 1,
    'crystal_type' => 'none',
    'consume_type' => 'consume_type_normal',
  ],
  9201 => 
  [
    'item_id' => 9201,
    'icon' => 'accessory_magic_cap_i00',
    'name' => 'Shadow Item: Wizard Hat',
    'additionalname' => 'Firework',
    'description' => 'Shadow-type wizard hat with a wide brim and bent tip. Uses 2 hair accessory slots. Event hair accessory that grants a magical effect. ',
    'is_trade' => 0,
    'is_drop' => 0,
    'is_destruct' => 1,
    'crystal_type' => 'none',
    'consume_type' => 'consume_type_normal',
  ],
  9202 => 
  [
    'item_id' => 9202,
    'icon' => 'accessory_dandy_cap_i00',
    'name' => 'Shadow Item: Dapper Cap',
    'additionalname' => 'Firework',
    'description' => 'Shadow-type hair accessory with a visor. Uses 2 hair accessory slots. Event hair accessory that grants a magical effect. ',
    'is_trade' => 0,
    'is_drop' => 0,
    'is_destruct' => 1,
    'crystal_type' => 'none',
    'consume_type' => 'consume_type_normal',
  ],
  9203 => 
  [
    'item_id' => 9203,
    'icon' => 'accessory_romantic_chaperon_i00',
    'name' => 'Shadow Item: Romantic Chapeau',
    'additionalname' => 'Firework',
    'description' => 'Shadow-type hair accessory adorned with feathers. Uses 2 hair accessory slots. Event hair accessory that grants a magical effect. ',
    'is_trade' => 0,
    'is_drop' => 0,
    'is_destruct' => 1,
    'crystal_type' => 'none',
    'consume_type' => 'consume_type_normal',
  ],
  9204 => 
  [
    'item_id' => 9204,
    'icon' => 'accessory_iron_circlet_i00',
    'name' => 'Shadow Item: Iron Circlet',
    'additionalname' => 'Firework',
    'description' => 'Shadow-type hair accessory made of iron. Uses 2 hair accessory slots. Event hair accessory that grants a magical effect. ',
    'is_trade' => 0,
    'is_drop' => 0,
    'is_destruct' => 1,
    'crystal_type' => 'none',
    'consume_type' => 'consume_type_normal',
  ],
  9205 => 
  [
    'item_id' => 9205,
    'icon' => 'etc_old_key_i02',
    'name' => 'Alchemist\'s Chest Key',
    'additionalname' => '',
    'description' => 'Key to open an Alchemist\'s Chest. For event use only.',
    'is_trade' => 1,
    'is_drop' => 1,
    'is_destruct' => 1,
    'crystal_type' => 'none',
    'consume_type' => 'consume_type_stackable',
  ],
  9206 => 
  [
    'item_id' => 9206,
    'icon' => 'etc_reagent_white_i00',
    'name' => 'Major Healing Potion (Event]',
    'additionalname' => '',
    'description' => 'Magical potion that quickly restores HP. Its effect lasts for 15 seconds. Designed for use in events only.',
    'is_trade' => 1,
    'is_drop' => 1,
    'is_destruct' => 1,
    'crystal_type' => 'none',
    'consume_type' => 'consume_type_stackable',
  ],
  9207 => 
  [
    'item_id' => 9207,
    'icon' => 'etc_potion_gold_i00',
    'name' => 'Quick Healing Potion (Event]',
    'additionalname' => '',
    'description' => 'Magic potion that instantly restores HP. Instant effect with no duration. Event item. Cannot be used when HP is full.',
    'is_trade' => 1,
    'is_drop' => 1,
    'is_destruct' => 1,
    'crystal_type' => 'none',
    'consume_type' => 'consume_type_stackable',
  ],
  9208 => 
  [
    'item_id' => 9208,
    'icon' => 'accessary_mask_of_chaotic_i00',
    'name' => 'Phantom Mask (Event]',
    'additionalname' => '',
    'description' => 'Scary hair accessory. Uses 2 hair accessory slots. This item is designed for use in events only and ',
    'is_trade' => 0,
    'is_drop' => 0,
    'is_destruct' => 1,
    'crystal_type' => 'none',
    'consume_type' => 'consume_type_normal',
  ],
  9209 => 
  [
    'item_id' => 9209,
    'icon' => 'weapon_rapier_i00',
    'name' => 'Rapier',
    'additionalname' => '',
    'description' => 'Kamael-exclusive Weapon: Saber Conversion
When enchanted to 4 or more, it Has a chance of increasing P. Atk., M. Atk., and healing power, and of decreasing MP consumption for skill use for you and your party members during a Critical Attack.',
    'is_trade' => 1,
    'is_drop' => 1,
    'is_destruct' => 1,
    'crystal_type' => 'd',
    'consume_type' => 'consume_type_normal',
  ],
  9210 => 
  [
    'item_id' => 9210,
    'icon' => 'weapon_tulwar_i00',
    'name' => 'Talwar',
    'additionalname' => '',
    'description' => 'Kamael-exclusive Weapon: Heavy Sword Conversion.',
    'is_trade' => 1,
    'is_drop' => 1,
    'is_destruct' => 1,
    'crystal_type' => 'd',
    'consume_type' => 'consume_type_normal',
  ],
  9211 => 
  [
    'item_id' => 9211,
    'icon' => 'weapon_tulwar_i00',
    'name' => 'Talwar',
    'additionalname' => '',
    'description' => 'Kamael-exclusive Weapon: Steel Sword Conversion.',
    'is_trade' => 1,
    'is_drop' => 1,
    'is_destruct' => 1,
    'crystal_type' => 'd',
    'consume_type' => 'consume_type_normal',
  ],
  9212 => 
  [
    'item_id' => 9212,
    'icon' => 'weapon_hunting_gun_i00',
    'name' => 'Field Gun',
    'additionalname' => '',
    'description' => 'Kamael-exclusive Weapon: Reinforced Bow Conversion.',
    'is_trade' => 1,
    'is_drop' => 1,
    'is_destruct' => 1,
    'crystal_type' => 'd',
    'consume_type' => 'consume_type_normal',
  ],
  9213 => 
  [
    'item_id' => 9213,
    'icon' => 'weapon_rapier_i00',
    'name' => 'Fleuret',
    'additionalname' => '',
    'description' => 'Kamael-exclusive Weapon: Bastard Sword Conversion
When enchanted to 4 or more, it Has a chance of increasing P. Atk., M. Atk., and healing power, and of decreasing MP consumption for skill use for you and your party members during a Critical Attack.',
    'is_trade' => 1,
    'is_drop' => 1,
    'is_destruct' => 1,
    'crystal_type' => 'd',
    'consume_type' => 'consume_type_normal',
  ],
  9214 => 
  [
    'item_id' => 9214,
    'icon' => 'weapon_rapier_i00',
    'name' => 'Fleuret',
    'additionalname' => '',
    'description' => 'Kamael-exclusive Weapon: Spinebone Sword Conversion
When enchanted to 4 or more, it Has a chance of increasing P. Atk., M. Atk., and healing power, and of decreasing MP consumption for skill use for you and your party members during a Critical Attack.',
    'is_trade' => 1,
    'is_drop' => 1,
    'is_destruct' => 1,
    'crystal_type' => 'd',
    'consume_type' => 'consume_type_normal',
  ],
  9215 => 
  [
    'item_id' => 9215,
    'icon' => 'weapon_rapier_i00',
    'name' => 'Fleuret',
    'additionalname' => '',
    'description' => 'Kamael-exclusive Weapon: Artisan\'s Sword Conversion
When enchanted to 4 or more, it Has a chance of increasing P. Atk., M. Atk., and healing power, and of decreasing MP consumption for skill use for you and your party members during a Critical Attack.',
    'is_trade' => 1,
    'is_drop' => 1,
    'is_destruct' => 1,
    'crystal_type' => 'd',
    'consume_type' => 'consume_type_normal',
  ],
  9216 => 
  [
    'item_id' => 9216,
    'icon' => 'weapon_tulwar_i00',
    'name' => 'Military Talwar',
    'additionalname' => '',
    'description' => 'Kamael-exclusive Weapon: Saber Conversion.',
    'is_trade' => 1,
    'is_drop' => 1,
    'is_destruct' => 1,
    'crystal_type' => 'd',
    'consume_type' => 'consume_type_normal',
  ],
  9217 => 
  [
    'item_id' => 9217,
    'icon' => 'weapon_hunting_gun_i00',
    'name' => 'Hand Crossbow',
    'additionalname' => '',
    'description' => 'Kamael-exclusive Weapon: Longbow Conversion.',
    'is_trade' => 1,
    'is_drop' => 1,
    'is_destruct' => 1,
    'crystal_type' => 'd',
    'consume_type' => 'consume_type_normal',
  ],
  9218 => 
  [
    'item_id' => 9218,
    'icon' => 'weapon_rapier_i00',
    'name' => 'Estoc',
    'additionalname' => '',
    'description' => 'Kamael-exclusive Weapon: Scream Sword Conversion
When enchanted to 4 or more, it Has a chance of increasing P. Atk., M. Atk., and healing power, and of decreasing MP consumption for skill use for you and your party members during a Critical Attack.',
    'is_trade' => 1,
    'is_drop' => 1,
    'is_destruct' => 1,
    'crystal_type' => 'd',
    'consume_type' => 'consume_type_normal',
  ],
  9219 => 
  [
    'item_id' => 9219,
    'icon' => 'weapon_rapier_i00',
    'name' => 'Estoc',
    'additionalname' => '',
    'description' => 'Kamael-exclusive Weapon: Elven Sword Conversion
When enchanted to 4 or more, it Has a chance of increasing P. Atk., M. Atk., and healing power, and of decreasing MP consumption for skill use for you and your party members during a Critical Attack.',
    'is_trade' => 1,
    'is_drop' => 1,
    'is_destruct' => 1,
    'crystal_type' => 'd',
    'consume_type' => 'consume_type_normal',
  ],
  9220 => 
  [
    'item_id' => 9220,
    'icon' => 'weapon_tulwar_i00',
    'name' => 'Field Sword',
    'additionalname' => '',
    'description' => 'Kamael-exclusive Weapon: Two-handed Sword Conversion.',
    'is_trade' => 1,
    'is_drop' => 1,
    'is_destruct' => 1,
    'crystal_type' => 'd',
    'consume_type' => 'consume_type_normal',
  ],
  9221 => 
  [
    'item_id' => 9221,
    'icon' => 'weapon_hunting_gun_i00',
    'name' => 'Crossbow',
    'additionalname' => '',
    'description' => 'Kamael-exclusive Weapon: Gastraphetes Conversion.',
    'is_trade' => 1,
    'is_drop' => 1,
    'is_destruct' => 1,
    'crystal_type' => 'd',
    'consume_type' => 'consume_type_normal',
  ],
  9222 => 
  [
    'item_id' => 9222,
    'icon' => 'weapon_rapier_i00',
    'name' => 'Épée',
    'additionalname' => '',
    'description' => 'Kamael-exclusive Weapon: Sword of Revolution Conversion
When enchanted to 4 or more, it Has a chance of increasing P. Atk., M. Atk., and healing power, and of decreasing MP consumption for skill use for you and your party members during a Critical Attack.',
    'is_trade' => 1,
    'is_drop' => 1,
    'is_destruct' => 1,
    'crystal_type' => 'd',
    'consume_type' => 'consume_type_normal',
  ],
  9223 => 
  [
    'item_id' => 9223,
    'icon' => 'weapon_tulwar_i00',
    'name' => 'Katzbalger',
    'additionalname' => '',
    'description' => 'Kamael-exclusive Weapon: Lesser Giant\'s Sword Conversion.',
    'is_trade' => 1,
    'is_drop' => 1,
    'is_destruct' => 1,
    'crystal_type' => 'd',
    'consume_type' => 'consume_type_normal',
  ],
  9224 => 
  [
    'item_id' => 9224,
    'icon' => 'weapon_hunting_gun_i00',
    'name' => 'Arm Breaker',
    'additionalname' => '',
    'description' => 'Kamael-exclusive Weapon: Reinforced Longbow Conversion.',
    'is_trade' => 1,
    'is_drop' => 1,
    'is_destruct' => 1,
    'crystal_type' => 'd',
    'consume_type' => 'consume_type_normal',
  ],
  9225 => 
  [
    'item_id' => 9225,
    'icon' => 'weapon_rapier_i00',
    'name' => 'Grand Épée',
    'additionalname' => '',
    'description' => 'Kamael-exclusive Weapon: Elven Long Sword Conversion
When enchanted to 4 or more, it Has a chance of increasing P. Atk., M. Atk., and healing power, and of decreasing MP consumption for skill use for you and your party members during a Critical Attack.',
    'is_trade' => 1,
    'is_drop' => 1,
    'is_destruct' => 1,
    'crystal_type' => 'd',
    'consume_type' => 'consume_type_normal',
  ],
  9226 => 
  [
    'item_id' => 9226,
    'icon' => 'weapon_tulwar_i00',
    'name' => 'General\'s Katzbalger',
    'additionalname' => '',
    'description' => 'Kamael-exclusive Weapon: Claymore Conversion.',
    'is_trade' => 1,
    'is_drop' => 1,
    'is_destruct' => 1,
    'crystal_type' => 'd',
    'consume_type' => 'consume_type_normal',
  ],
  9227 => 
  [
    'item_id' => 9227,
    'icon' => 'weapon_hunting_gun_i00',
    'name' => 'Cranequin',
    'additionalname' => '',
    'description' => 'Kamael-exclusive Weapon: Light Crossbow Conversion.',
    'is_trade' => 1,
    'is_drop' => 1,
    'is_destruct' => 1,
    'crystal_type' => 'd',
    'consume_type' => 'consume_type_normal',
  ],
  9228 => 
  [
    'item_id' => 9228,
    'icon' => 'weapon_soldat_estoc_i00',
    'name' => 'Soldat Estoc',
    'additionalname' => '',
    'description' => 'Kamael-exclusive Weapon: StormBringer Conversion
Can bestow 1 regular Soul Crystal and 1 Special Soul Crystal.
When enchanted to 4 or more, it Has a chance of increasing P. Atk., M. Atk., and healing power, and of decreasing MP consumption for skill use for you and your party members during a Critical Attack.',
    'is_trade' => 1,
    'is_drop' => 1,
    'is_destruct' => 1,
    'crystal_type' => 'c',
    'consume_type' => 'consume_type_normal',
  ],
  9229 => 
  [
    'item_id' => 9229,
    'icon' => 'weapon_soldat_estoc_i01',
    'name' => 'Soldat Estoc',
    'additionalname' => 'Critical Anger',
    'description' => 'Kamael Exclusive Weapon: Stormbringer Conversion<Soul Crystal Enhancement> Decreases HP by 12 and increases P. Atk. by 248 on a critical attack. When enchanted to 4 or more, it has a chance of increasing P. Atk., M. Atk., and healing power, and of decreaseing MP consumption for skill use for you and your party members during a critical attack.',
    'is_trade' => 1,
    'is_drop' => 1,
    'is_destruct' => 1,
    'crystal_type' => 'c',
    'consume_type' => 'consume_type_normal',
  ],
  9230 => 
  [
    'item_id' => 9230,
    'icon' => 'weapon_soldat_estoc_i01',
    'name' => 'Soldat Estoc',
    'additionalname' => 'Focus',
    'description' => 'Kamael Exclusive Weapon: Stormbringer Conversion<Soul Crystal Enhancement> Increases Critical by 86. When enchanted to 4 or more, it has a chance of increasing P. Atk., M. Atk., and healing power, and of decreaseing MP consumption for skill use for you and your party members during a critical attack.',
    'is_trade' => 1,
    'is_drop' => 1,
    'is_destruct' => 1,
    'crystal_type' => 'c',
    'consume_type' => 'consume_type_normal',
  ],
  9231 => 
  [
    'item_id' => 9231,
    'icon' => 'weapon_soldat_estoc_i01',
    'name' => 'Soldat Estoc',
    'additionalname' => 'Light',
    'description' => 'Kamael Exclusive Weapon: Stormbringer Conversion <Soul Crystal Enhancement> Increases weight gauge by 20%. When enchanted to 4 or more, there is a chance that party members including yourself will get increased P. Atk., M. Atk. and the amount of recieved heal, and decreased MP consumption per skill during a critical attack.',
    'is_trade' => 1,
    'is_drop' => 1,
    'is_destruct' => 1,
    'crystal_type' => 'c',
    'consume_type' => 'consume_type_normal',
  ],
  9232 => 
  [
    'item_id' => 9232,
    'icon' => 'weapon_schlaeger_i00',
    'name' => 'Schlager',
    'additionalname' => '',
    'description' => 'Kamael-exclusive Weapon: Flamberge Conversion
Can bestow 1 regular Soul Crystal and 1 Special Soul Crystal.',
    'is_trade' => 1,
    'is_drop' => 1,
    'is_destruct' => 1,
    'crystal_type' => 'c',
    'consume_type' => 'consume_type_normal',
  ],
  9233 => 
  [
    'item_id' => 9233,
    'icon' => 'weapon_schlaeger_i01',
    'name' => 'Schlager',
    'additionalname' => 'Critical Damage',
    'description' => 'Kamael Exclusive Weapon: Flamberge Conversion <Soul Crystal Enhancement> Increases P. Atk. by 174 on a critical attack.',
    'is_trade' => 1,
    'is_drop' => 1,
    'is_destruct' => 1,
    'crystal_type' => 'c',
    'consume_type' => 'consume_type_normal',
  ],
  9234 => 
  [
    'item_id' => 9234,
    'icon' => 'weapon_schlaeger_i01',
    'name' => 'Schlager',
    'additionalname' => 'Focus',
    'description' => 'Kamael Exclusive Weapon: Flamberge Conversion <Soul Crystal Enhancement> Increases Critical by 86.',
    'is_trade' => 1,
    'is_drop' => 1,
    'is_destruct' => 1,
    'crystal_type' => 'c',
    'consume_type' => 'consume_type_normal',
  ],
  9235 => 
  [
    'item_id' => 9235,
    'icon' => 'weapon_schlaeger_i01',
    'name' => 'Schlager',
    'additionalname' => 'Light',
    'description' => 'Kamael Exclusive Weapon: Flamberge Conversion <Soul Crystal Enhancement> Increases weight gauge by 20%.',
    'is_trade' => 1,
    'is_drop' => 1,
    'is_destruct' => 1,
    'crystal_type' => 'c',
    'consume_type' => 'consume_type_normal',
  ],
  9236 => 
  [
    'item_id' => 9236,
    'icon' => 'weapon_arbalest_i00',
    'name' => 'Arbalest',
    'additionalname' => '',
    'description' => 'Kamael-exclusive Weapon: Crystallized Ice Bow\\Can bestow 1 regular Soul Crystal and 1 Special Soul Crystal.',
    'is_trade' => 1,
    'is_drop' => 1,
    'is_destruct' => 1,
    'crystal_type' => 'c',
    'consume_type' => 'consume_type_normal',
  ],
  9237 => 
  [
    'item_id' => 9237,
    'icon' => 'weapon_arbalest_i01',
    'name' => 'Arbalest',
    'additionalname' => 'Guidance',
    'description' => 'Kamael Exclusive Weapon: Crystallized Ice Bow Conversion <Soul Crystal Enhancement> Increases Accuracy by 5.',
    'is_trade' => 1,
    'is_drop' => 1,
    'is_destruct' => 1,
    'crystal_type' => 'c',
    'consume_type' => 'consume_type_normal',
  ],
  9238 => 
  [
    'item_id' => 9238,
    'icon' => 'weapon_arbalest_i01',
    'name' => 'Arbalest',
    'additionalname' => 'Evasion',
    'description' => 'Kamael Exclusive Weapon: Crystallized Ice Bow Conversion <Soul Crystal Enhancement> Increases Evasion by 2.',
    'is_trade' => 1,
    'is_drop' => 1,
    'is_destruct' => 1,
    'crystal_type' => 'c',
    'consume_type' => 'consume_type_normal',
  ],
  9239 => 
  [
    'item_id' => 9239,
    'icon' => 'weapon_arbalest_i01',
    'name' => 'Arbalest',
    'additionalname' => 'Quick Recovery',
    'description' => 'Kamael Exclusive Weapon: Crystallized Iced Bow <Soul Crystal Enhancement> Decreases re-use delay by about 17%.',
    'is_trade' => 1,
    'is_drop' => 1,
    'is_destruct' => 1,
    'crystal_type' => 'c',
    'consume_type' => 'consume_type_normal',
  ],
  9240 => 
  [
    'item_id' => 9240,
    'icon' => 'weapon_soldat_estoc_i00',
    'name' => 'Chevalier Rapier',
    'additionalname' => '',
    'description' => 'Kamael-exclusive Weapon: Shamshir
Can bestow 1 regular Soul Crystal and 1 Special Soul Crystal.
When enchanted to 4 or more, it Has a chance of increasing P. Atk., M. Atk., and healing power, and of decreasing MP consumption for skill use for you and your party members during a Critical Attack.',
    'is_trade' => 1,
    'is_drop' => 1,
    'is_destruct' => 1,
    'crystal_type' => 'c',
    'consume_type' => 'consume_type_normal',
  ],
  9241 => 
  [
    'item_id' => 9241,
    'icon' => 'weapon_soldat_estoc_i01',
    'name' => 'Chevalier Rapier',
    'additionalname' => 'Guidance',
    'description' => 'Kamael Exclusive Weapon: Shamshir <Soul Crystal Enhancement> Increases Accuracy by 6. When enchanted to 4 or more, it has a chance of increasing P. Atk., M. Atk., and healing power, and of decreaseing MP consumption for skill use for you and your party members during a critical attack.',
    'is_trade' => 1,
    'is_drop' => 1,
    'is_destruct' => 1,
    'crystal_type' => 'c',
    'consume_type' => 'consume_type_normal',
  ],
  9242 => 
  [
    'item_id' => 9242,
    'icon' => 'weapon_soldat_estoc_i01',
    'name' => 'Chevalier Rapier',
    'additionalname' => 'Back Blow',
    'description' => 'Kamael Exclusive Weapon: Shamshir <Soul Crystal Enhancement> Increases Critical Rate by 56 when attacking a target from behind. When enchanted to 4 or more, it has a chance of increasing P. Atk., M. Atk., and healing power, and of decreaseing MP consumption for skill use for you and your party members during a critical attack.',
    'is_trade' => 1,
    'is_drop' => 1,
    'is_destruct' => 1,
    'crystal_type' => 'c',
    'consume_type' => 'consume_type_normal',
  ],
  9243 => 
  [
    'item_id' => 9243,
    'icon' => 'weapon_soldat_estoc_i01',
    'name' => 'Chevalier Rapier',
    'additionalname' => 'Rsk. Evasion',
    'description' => 'Kamael Exclusive Weapon: Shamshir <Soul Crystal Enhancement> Increases Evasion by 7 when HP falls to 60% or lower. When enchanted to 4 or more, it has a chance of increasing P. Atk., M. Atk., and healing power, and of decreaseing MP consumption for skill use for you and your party members during a critical attack.',
    'is_trade' => 1,
    'is_drop' => 1,
    'is_destruct' => 1,
    'crystal_type' => 'c',
    'consume_type' => 'consume_type_normal',
  ],
  9244 => 
  [
    'item_id' => 9244,
    'icon' => 'weapon_soldat_estoc_i00',
    'name' => 'Chevalier Rapier',
    'additionalname' => '',
    'description' => 'Kamael-exclusive Weapon: Katana
Can bestow 1 regular Soul Crystal and 1 Special Soul Crystal.
When enchanted to 4 or more, it Has a chance of increasing P. Atk., M. Atk., and healing power, and of decreasing MP consumption for skill use for you and your party members during a Critical Attack.',
    'is_trade' => 1,
    'is_drop' => 1,
    'is_destruct' => 1,
    'crystal_type' => 'c',
    'consume_type' => 'consume_type_normal',
  ],
  9245 => 
  [
    'item_id' => 9245,
    'icon' => 'weapon_soldat_estoc_i01',
    'name' => 'Chevalier Rapier',
    'additionalname' => 'Focus',
    'description' => 'Kamael Exclusive Weapon: Katana <Soul Crystal Enhancement> Increases Critical by 82. When enchanted to 4 or more, it has a chance of increasing P. Atk., M. Atk., and healing power, and of decreaseing MP consumption for skill use for you and your party members during a critical attack.',
    'is_trade' => 1,
    'is_drop' => 1,
    'is_destruct' => 1,
    'crystal_type' => 'c',
    'consume_type' => 'consume_type_normal',
  ],
  9246 => 
  [
    'item_id' => 9246,
    'icon' => 'weapon_soldat_estoc_i01',
    'name' => 'Chevalier Rapier',
    'additionalname' => 'Critical Damage',
    'description' => 'Kamael Exclusive Weapon: Katana <Soul Crystal Enhancement> Increases P. Atk. by 194 on a critical attack. When enchanted to 4 or more, it has a chance of increasing P. Atk., M. Atk., and healing power, and of decreaseing MP consumption for skill use for you and your party members during a critical attack.',
    'is_trade' => 1,
    'is_drop' => 1,
    'is_destruct' => 1,
    'crystal_type' => 'c',
    'consume_type' => 'consume_type_normal',
  ],
  9247 => 
  [
    'item_id' => 9247,
    'icon' => 'weapon_soldat_estoc_i01',
    'name' => 'Chevalier Rapier',
    'additionalname' => 'Haste',
    'description' => 'Kamael Exclusive Weapon: Katana <Soul Crystal Enhancement> Increases Atk. Spd. by about 7%. When enchanted to 4 or more, it has a chance of increasing P. Atk., M. Atk., and healing power, and of decreaseing MP consumption for skill use for you and your party members during a critical attack.',
    'is_trade' => 1,
    'is_drop' => 1,
    'is_destruct' => 1,
    'crystal_type' => 'c',
    'consume_type' => 'consume_type_normal',
  ],
  9248 => 
  [
    'item_id' => 9248,
    'icon' => 'weapon_soldat_estoc_i00',
    'name' => 'Chevalier Rapier',
    'additionalname' => '',
    'description' => 'Kamael-exclusive Weapon: Spirit Sword
Can bestow 1 regular Soul Crystal and 1 Special Soul Crystal.
When enchanted to 4 or more, it Has a chance of increasing P. Atk., M. Atk., and healing power, and of decreasing MP consumption for skill use for you and your party members during a Critical Attack.',
    'is_trade' => 1,
    'is_drop' => 1,
    'is_destruct' => 1,
    'crystal_type' => 'c',
    'consume_type' => 'consume_type_normal',
  ],
  9249 => 
  [
    'item_id' => 9249,
    'icon' => 'weapon_soldat_estoc_i01',
    'name' => 'Chevalier Rapier',
    'additionalname' => 'Critical Damage',
    'description' => 'Kamael Exclusive Weapon: Spirit Sword <Soul Crystal Enhancement> Increases P. Atk. by 194 on a critical attack. When enchanted to 4 or more, it has a chance of increasing P. Atk., M. Atk., and healing power, and of decreaseing MP consumption for skill use for you and your party members during a critical attack.',
    'is_trade' => 1,
    'is_drop' => 1,
    'is_destruct' => 1,
    'crystal_type' => 'c',
    'consume_type' => 'consume_type_normal',
  ],
  9250 => 
  [
    'item_id' => 9250,
    'icon' => 'weapon_soldat_estoc_i01',
    'name' => 'Chevalier Rapier',
    'additionalname' => 'Critical Poison',
    'description' => 'Kamael Exclusive Weapon: Spirit Sword <Soul Crystal Enhancement> Inflicts Poison on the target with a 15% chance during an ordinary critical attack. When enchanted to 4 or more, there is a chance that party members including yourself will get increased P. Atk., M. Atk. and the amount of recieved heal, and decreased MP consumption per skill during a critical attack.',
    'is_trade' => 1,
    'is_drop' => 1,
    'is_destruct' => 1,
    'crystal_type' => 'c',
    'consume_type' => 'consume_type_normal',
  ],
  9251 => 
  [
    'item_id' => 9251,
    'icon' => 'weapon_soldat_estoc_i01',
    'name' => 'Chevalier Rapier',
    'additionalname' => 'Haste',
    'description' => 'Kamael Exclusive Weapon: Spirit Sword <Soul Crystal Enhancement> Increases Atk. Spd. by about 7%. When enchanted to 4 or more, it has a chance of increasing P. Atk., M. Atk., and healing power, and of decreaseing MP consumption for skill use for you and your party members during a critical attack.',
    'is_trade' => 1,
    'is_drop' => 1,
    'is_destruct' => 1,
    'crystal_type' => 'c',
    'consume_type' => 'consume_type_normal',
  ],
  9252 => 
  [
    'item_id' => 9252,
    'icon' => 'weapon_soldat_estoc_i00',
    'name' => 'Chevalier Rapier',
    'additionalname' => '',
    'description' => 'Kamael-exclusive Weapon: Raid Sword
Can bestow 1 regular Soul Crystal and 1 Special Soul Crystal.
When enchanted to 4 or more, it Has a chance of increasing P. Atk., M. Atk., and healing power, and of decreasing MP consumption for skill use for you and your party members during a Critical Attack.',
    'is_trade' => 1,
    'is_drop' => 1,
    'is_destruct' => 1,
    'crystal_type' => 'c',
    'consume_type' => 'consume_type_normal',
  ],
  9253 => 
  [
    'item_id' => 9253,
    'icon' => 'weapon_soldat_estoc_i01',
    'name' => 'Chevalier Rapier',
    'additionalname' => 'Focus',
    'description' => 'Kamael Exclusive Weapon: Raid Sword <Soul Crystal Enhancement> Increases Critical by 82. When enchanted to 4 or more, it has a chance of increasing P. Atk., M. Atk., and healing power, and of decreaseing MP consumption for skill use for you and your party members during a critical attack.',
    'is_trade' => 1,
    'is_drop' => 1,
    'is_destruct' => 1,
    'crystal_type' => 'c',
    'consume_type' => 'consume_type_normal',
  ],
  9254 => 
  [
    'item_id' => 9254,
    'icon' => 'weapon_soldat_estoc_i01',
    'name' => 'Chevalier Rapier',
    'additionalname' => 'Critical Drain',
    'description' => 'Kamael Exclusive Weapon: Raid Sword <Soul Crystal Enhancement> Absorbs the target\'s HP by 9 on a critical attack. When enchanted to 4 or more, it has a chance of increasing P. Atk., M. Atk., and healing power, and of decreaseing MP consumption for skill use for you and your party members during a critical attack.',
    'is_trade' => 1,
    'is_drop' => 1,
    'is_destruct' => 1,
    'crystal_type' => 'c',
    'consume_type' => 'consume_type_normal',
  ],
  9255 => 
  [
    'item_id' => 9255,
    'icon' => 'weapon_soldat_estoc_i01',
    'name' => 'Chevalier Rapier',
    'additionalname' => 'Critical Poison',
    'description' => 'Kamael Exclusive Weapon: Raid Sword <Soul Crystal Enhancement> Inflicts Poison on the target with a 15% chance during an ordinary critical attack. When enchanted to 4 or more, there is a chance that party members including yourself will get increased P. Atk., M. Atk. and the amount of recieved heal, and decreased MP consumption per skill during a critical attack.',
    'is_trade' => 1,
    'is_drop' => 1,
    'is_destruct' => 1,
    'crystal_type' => 'c',
    'consume_type' => 'consume_type_normal',
  ],
  9256 => 
  [
    'item_id' => 9256,
    'icon' => 'weapon_arbalest_i00',
    'name' => 'Ballista',
    'additionalname' => '',
    'description' => 'Kamael-exclusive Weapon: Elemental Bow
Can bestow 1 regular Soul Crystal and 1 Special Soul Crystal.',
    'is_trade' => 1,
    'is_drop' => 1,
    'is_destruct' => 1,
    'crystal_type' => 'c',
    'consume_type' => 'consume_type_normal',
  ],
  9257 => 
  [
    'item_id' => 9257,
    'icon' => 'weapon_arbalest_i01',
    'name' => 'Ballista',
    'additionalname' => 'Guidance',
    'description' => 'Kamael Exclusive Weapon: Elemental Bow <Soul Crystal Enhancement> Increases Accuracy by 5.',
    'is_trade' => 1,
    'is_drop' => 1,
    'is_destruct' => 1,
    'crystal_type' => 'c',
    'consume_type' => 'consume_type_normal',
  ],
  9258 => 
  [
    'item_id' => 9258,
    'icon' => 'weapon_arbalest_i01',
    'name' => 'Ballista',
    'additionalname' => 'Miser',
    'description' => 'Kamael Exclusive Weapon: Elemental Bow <Soul Crystal Enhancement> There is a 40% rate of chance that the number of soulshots consumed is reduced to 4.',
    'is_trade' => 1,
    'is_drop' => 1,
    'is_destruct' => 1,
    'crystal_type' => 'c',
    'consume_type' => 'consume_type_normal',
  ],
  9259 => 
  [
    'item_id' => 9259,
    'icon' => 'weapon_arbalest_i01',
    'name' => 'Ballista',
    'additionalname' => 'Quick Recovery',
    'description' => 'Kamael Exclusive Weapon: Elemental Bow <Soul Crystal Enhancement> Decreases re-use delay by about 20%.',
    'is_trade' => 1,
    'is_drop' => 1,
    'is_destruct' => 1,
    'crystal_type' => 'c',
    'consume_type' => 'consume_type_normal',
  ],
  9260 => 
  [
    'item_id' => 9260,
    'icon' => 'weapon_arbalest_i00',
    'name' => 'Ballista',
    'additionalname' => '',
    'description' => 'Kamael-exclusive Weapon: High Lv. Elven Bow
Can bestow 1 regular Soul Crystal and 1 Special Soul Crystal.',
    'is_trade' => 1,
    'is_drop' => 1,
    'is_destruct' => 1,
    'crystal_type' => 'c',
    'consume_type' => 'consume_type_normal',
  ],
  9261 => 
  [
    'item_id' => 9261,
    'icon' => 'weapon_arbalest_i01',
    'name' => 'Ballista',
    'additionalname' => 'Evasion',
    'description' => 'Kamael Exclusive Weapon: High Level Elven Bow <Soul Crystal Enhancement> Increases Evasion by 2.',
    'is_trade' => 1,
    'is_drop' => 1,
    'is_destruct' => 1,
    'crystal_type' => 'c',
    'consume_type' => 'consume_type_normal',
  ],
  9262 => 
  [
    'item_id' => 9262,
    'icon' => 'weapon_arbalest_i01',
    'name' => 'Ballista',
    'additionalname' => 'Miser',
    'description' => 'Kamael Exclusive Weapon: High Level Elven Bow <Soul Crystal Enhancement> There is a 40% rate of chance that the number of soulshots consumed is reduced to 4.',
    'is_trade' => 1,
    'is_drop' => 1,
    'is_destruct' => 1,
    'crystal_type' => 'c',
    'consume_type' => 'consume_type_normal',
  ],
  9263 => 
  [
    'item_id' => 9263,
    'icon' => 'weapon_arbalest_i01',
    'name' => 'Ballista',
    'additionalname' => 'Cheap Shot',
    'description' => 'Kamael Exclusive Weapon: High Level Elven Bow <Soul Crystal Enhancement> Decreased MP consumption by 12% during use of skill.',
    'is_trade' => 1,
    'is_drop' => 1,
    'is_destruct' => 1,
    'crystal_type' => 'c',
    'consume_type' => 'consume_type_normal',
  ],
  9264 => 
  [
    'item_id' => 9264,
    'icon' => 'weapon_blink_slasher_i00',
    'name' => 'Blinzlasher',
    'additionalname' => '',
    'description' => 'Kamael-exclusive Weapon: Caliburs
Can bestow 1 regular Soul Crystal and 1 Special Soul Crystal.
When enchanted to 4 or more, it Has a chance of increasing P. Atk., M. Atk., and healing power, and of decreasing MP consumption for skill use for you and your party members during a Critical Attack.',
    'is_trade' => 1,
    'is_drop' => 1,
    'is_destruct' => 1,
    'crystal_type' => 'c',
    'consume_type' => 'consume_type_normal',
  ],
  9265 => 
  [
    'item_id' => 9265,
    'icon' => 'weapon_blink_slasher_i01',
    'name' => 'Blinzlasher',
    'additionalname' => 'Guidance',
    'description' => 'Kamael Exclusive Weapon: Caliburs <Soul Crystal Enhancement> Increases Accuracy by 5. When enchanted to 4 or more, it has a chance of increasing P. Atk., M. Atk., and healing power, and of decreaseing MP consumption for skill use for you and your party members during a critical attack.',
    'is_trade' => 1,
    'is_drop' => 1,
    'is_destruct' => 1,
    'crystal_type' => 'c',
    'consume_type' => 'consume_type_normal',
  ],
  9266 => 
  [
    'item_id' => 9266,
    'icon' => 'weapon_blink_slasher_i01',
    'name' => 'Blinzlasher',
    'additionalname' => 'Focus',
    'description' => 'Kamael Exclusive Weapon: Caliburs <Soul Crystal Enhancement> Increases Critical by 77. When enchanted to 4 or more, it has a chance of increasing P. Atk., M. Atk., and healing power, and of decreaseing MP consumption for skill use for you and your party members during a critical attack.',
    'is_trade' => 1,
    'is_drop' => 1,
    'is_destruct' => 1,
    'crystal_type' => 'c',
    'consume_type' => 'consume_type_normal',
  ],
  9267 => 
  [
    'item_id' => 9267,
    'icon' => 'weapon_blink_slasher_i01',
    'name' => 'Blinzlasher',
    'additionalname' => 'Critical Damage',
    'description' => 'Kamael Exclusive Weapon: Caliburs <Soul Crystal Enhancement> Increases P. Atk. by 213 on a critical attack. When enchanted to 4 or more, it has a chance of increasing P. Atk., M. Atk., and healing power, and of decreaseing MP consumption for skill use for you and your party members during a critical attack.',
    'is_trade' => 1,
    'is_drop' => 1,
    'is_destruct' => 1,
    'crystal_type' => 'c',
    'consume_type' => 'consume_type_normal',
  ],
  9268 => 
  [
    'item_id' => 9268,
    'icon' => 'weapon_blink_slasher_i00',
    'name' => 'Blinzlasher',
    'additionalname' => '',
    'description' => 'Kamael-exclusive Weapon: Sword of Delusion
Can bestow 1 regular Soul Crystal and 1 Special Soul Crystal.
When enchanted to 4 or more, it Has a chance of increasing P. Atk., M. Atk., and healing power, and of decreasing MP consumption for skill use for you and your party members during a Critical Attack.',
    'is_trade' => 1,
    'is_drop' => 1,
    'is_destruct' => 1,
    'crystal_type' => 'c',
    'consume_type' => 'consume_type_normal',
  ],
  9269 => 
  [
    'item_id' => 9269,
    'icon' => 'weapon_blink_slasher_i01',
    'name' => 'Blinzlasher',
    'additionalname' => 'Focus',
    'description' => 'Kamael Exclusive Weapon: Sword of Delusion <Soul Crystal Enhancement> Increases Critical by 77. When enchanted to 4 or more, it has a chance of increasing P. Atk., M. Atk., and healing power, and of decreaseing MP consumption for skill use for you and your party members during a critical attack.',
    'is_trade' => 1,
    'is_drop' => 1,
    'is_destruct' => 1,
    'crystal_type' => 'c',
    'consume_type' => 'consume_type_normal',
  ],
  9270 => 
  [
    'item_id' => 9270,
    'icon' => 'weapon_blink_slasher_i01',
    'name' => 'Blinzlasher',
    'additionalname' => 'Health',
    'description' => 'Kamael Exclusive Weapon: Sword of Delusion <Soul Crystal Enhancement> Increases Max HP by 25%. When enchanted to 4 or more, it has a chance of increasing P. Atk., M. Atk., and healing power, and of decreaseing MP consumption for skill use for you and your party members during a critical attack.',
    'is_trade' => 1,
    'is_drop' => 1,
    'is_destruct' => 1,
    'crystal_type' => 'c',
    'consume_type' => 'consume_type_normal',
  ],
  9271 => 
  [
    'item_id' => 9271,
    'icon' => 'weapon_blink_slasher_i01',
    'name' => 'Blinzlasher',
    'additionalname' => 'Rsk. Haste',
    'description' => 'Kamael Exclusive Weapon: Sword of Delusion <Soul Crystal Enhancement> Increases Atk. Spd. by 12% when HP falls to 60% or lower. When enchanted to 4 or more, it has a chance of increasing P. Atk., M. Atk., and healing power, and of decreaseing MP consumption for skill use for you and your party members during a critical attack.',
    'is_trade' => 1,
    'is_drop' => 1,
    'is_destruct' => 1,
    'crystal_type' => 'c',
    'consume_type' => 'consume_type_normal',
  ],
  9272 => 
  [
    'item_id' => 9272,
    'icon' => 'weapon_blink_slasher_i00',
    'name' => 'Blinzlasher',
    'additionalname' => '',
    'description' => 'Kamael-exclusive Weapon: Tsurugi
Can bestow 1 regular Soul Crystal and 1 Special Soul Crystal.
When enchanted to 4 or more, it Has a chance of increasing P. Atk., M. Atk., and healing power, and of decreasing MP consumption for skill use for you and your party members during a Critical Attack.',
    'is_trade' => 1,
    'is_drop' => 1,
    'is_destruct' => 1,
    'crystal_type' => 'c',
    'consume_type' => 'consume_type_normal',
  ],
  9273 => 
  [
    'item_id' => 9273,
    'icon' => 'weapon_blink_slasher_i01',
    'name' => 'Blinzlasher',
    'additionalname' => 'Focus',
    'description' => 'Kamael Exclusive Weapon: Tsurugi <Soul Crystal Enhancement> Increases Critical by 77. When enchanted to 4 or more, it has a chance of increasing P. Atk., M. Atk., and healing power, and of decreaseing MP consumption for skill use for you and your party members during a critical attack.',
    'is_trade' => 1,
    'is_drop' => 1,
    'is_destruct' => 1,
    'crystal_type' => 'c',
    'consume_type' => 'consume_type_normal',
  ],
  9274 => 
  [
    'item_id' => 9274,
    'icon' => 'weapon_blink_slasher_i01',
    'name' => 'Blinzlasher',
    'additionalname' => 'Critical Damage',
    'description' => 'Kamael Exclusive Weapon: Tsurugi <Soul Crystal Enhancement> Increases P. Atk. by 213 on a critical attack. When enchanted to 4 or more, it has a chance of increasing P. Atk., M. Atk., and healing power, and of decreaseing MP consumption for skill use for you and your party members during a critical attack.',
    'is_trade' => 1,
    'is_drop' => 1,
    'is_destruct' => 1,
    'crystal_type' => 'c',
    'consume_type' => 'consume_type_normal',
  ],
  9275 => 
  [
    'item_id' => 9275,
    'icon' => 'weapon_blink_slasher_i01',
    'name' => 'Blinzlasher',
    'additionalname' => 'Haste',
    'description' => 'Kamael Exclusive Weapon: Tsurugi <Soul Crystal Enhancement> Increases Atk. Spd. by about 7%. When enchanted to 4 or more, it has a chance of increasing P. Atk., M. Atk., and healing power, and of decreaseing MP consumption for skill use for you and your party members during a critical attack.',
    'is_trade' => 1,
    'is_drop' => 1,
    'is_destruct' => 1,
    'crystal_type' => 'c',
    'consume_type' => 'consume_type_normal',
  ],
  9276 => 
  [
    'item_id' => 9276,
    'icon' => 'weapon_blink_slasher_i00',
    'name' => 'Blinzlasher',
    'additionalname' => '',
    'description' => 'Kamael-exclusive Weapon: Sword of Nightmare
Can bestow 1 regular Soul Crystal and 1 Special Soul Crystal.
When enchanted to 4 or more, it Has a chance of increasing P. Atk., M. Atk., and healing power, and of decreasing MP consumption for skill use for you and your party members during a Critical Attack.',
    'is_trade' => 1,
    'is_drop' => 1,
    'is_destruct' => 1,
    'crystal_type' => 'c',
    'consume_type' => 'consume_type_normal',
  ],
  9277 => 
  [
    'item_id' => 9277,
    'icon' => 'weapon_blink_slasher_i01',
    'name' => 'Blinzlasher',
    'additionalname' => 'Health',
    'description' => 'Kamael Exclusive Weapon: Sword of Nightmare <Soul Crystal Enhancement> Increases Max HP by 25%. When enchanted to 4 or more, it has a chance of increasing P. Atk., M. Atk., and healing power, and of decreaseing MP consumption for skill use for you and your party members during a critical attack.',
    'is_trade' => 1,
    'is_drop' => 1,
    'is_destruct' => 1,
    'crystal_type' => 'c',
    'consume_type' => 'consume_type_normal',
  ],
  9278 => 
  [
    'item_id' => 9278,
    'icon' => 'weapon_blink_slasher_i01',
    'name' => 'Blinzlasher',
    'additionalname' => 'Focus',
    'description' => 'Kamael Exclusive Weapon: Sword of Nightmare <Soul Crystal Enhancement> Increases Critical by 77. When enchanted to 4 or more, it has a chance of increasing P. Atk., M. Atk., and healing power, and of decreaseing MP consumption for skill use for you and your party members during a critical attack.',
    'is_trade' => 1,
    'is_drop' => 1,
    'is_destruct' => 1,
    'crystal_type' => 'c',
    'consume_type' => 'consume_type_normal',
  ],
  9279 => 
  [
    'item_id' => 9279,
    'icon' => 'weapon_blink_slasher_i01',
    'name' => 'Blinzlasher',
    'additionalname' => 'Light',
    'description' => 'Kamael Exclusive Weapon: Sword of Nightmare <Soul Crystal Enhancement> Increases weight gauge by 20%. When enchanted to 4 or more, there is a chance that party members including yourself will get increased P. Atk., M. Atk. and the amount of recieved heal, and decreased MP consumption per skill during a critical attack.',
    'is_trade' => 1,
    'is_drop' => 1,
    'is_destruct' => 1,
    'crystal_type' => 'c',
    'consume_type' => 'consume_type_normal',
  ],
  9280 => 
  [
    'item_id' => 9280,
    'icon' => 'weapon_blink_slasher_i00',
    'name' => 'Blinzlasher',
    'additionalname' => '',
    'description' => 'Kamael-exclusive Weapon: Ultimate Sword
Can bestow 1 regular Soul Crystal and 1 Special Soul Crystal.
When enchanted to 4 or more, it Has a chance of increases P. Atk., M. Atk., and the amount of received heal, and of decreasing MP consumption for skill use for you and your party members during a Critical Attack',
    'is_trade' => 1,
    'is_drop' => 1,
    'is_destruct' => 1,
    'crystal_type' => 'c',
    'consume_type' => 'consume_type_normal',
  ],
  9281 => 
  [
    'item_id' => 9281,
    'icon' => 'weapon_blink_slasher_i01',
    'name' => 'Blinzlasher',
    'additionalname' => 'Guidance',
    'description' => 'Kamael Exclusive Weapon: Sword of Limit <Soul Crystal Enhancement> Increases Accuracy by 5. When enchanted to 4 or more, it has a chance of increasing P. Atk., M. Atk., and healing power, and of decreaseing MP consumption for skill use for you and your party members during a critical attack.',
    'is_trade' => 1,
    'is_drop' => 1,
    'is_destruct' => 1,
    'crystal_type' => 'c',
    'consume_type' => 'consume_type_normal',
  ],
  9282 => 
  [
    'item_id' => 9282,
    'icon' => 'weapon_blink_slasher_i01',
    'name' => 'Blinzlasher',
    'additionalname' => 'Critical Drain',
    'description' => 'Kamael Exclusive Weapon: Sword of Limit <Soul Crystal Enhancement> Absorbs the target\'s HP by 9 on a critical attack. When enchanted to 4 or more, it has a chance of increasing P. Atk., M. Atk., and healing power, and of decreaseing MP consumption for skill use for you and your party members during a critical attack.',
    'is_trade' => 1,
    'is_drop' => 1,
    'is_destruct' => 1,
    'crystal_type' => 'c',
    'consume_type' => 'consume_type_normal',
  ],
  9283 => 
  [
    'item_id' => 9283,
    'icon' => 'weapon_blink_slasher_i01',
    'name' => 'Blinzlasher',
    'additionalname' => 'Health',
    'description' => 'Kamael Exclusive Weapon: Sword of Limit <Soul Crystal Enhancement> Increases Max HP by 25%. When enchanted to 4 or more, it has a chance of increasing P. Atk., M. Atk., and healing power, and of decreaseing MP consumption for skill use for you and your party members during a critical attack.',
    'is_trade' => 1,
    'is_drop' => 1,
    'is_destruct' => 1,
    'crystal_type' => 'c',
    'consume_type' => 'consume_type_normal',
  ],
  9284 => 
  [
    'item_id' => 9284,
    'icon' => 'weapon_invincible_blade_i00',
    'name' => 'Immortal Edge',
    'additionalname' => '',
    'description' => 'Kamael-exclusive Weapon: Pa\'agrian Sword
Can bestow 1 regular Soul Crystal and 1 Special Soul Crystal.',
    'is_trade' => 1,
    'is_drop' => 1,
    'is_destruct' => 1,
    'crystal_type' => 'c',
    'consume_type' => 'consume_type_normal',
  ],
  9285 => 
  [
    'item_id' => 9285,
    'icon' => 'weapon_invincible_blade_i01',
    'name' => 'Immortal Edge',
    'additionalname' => 'Focus',
    'description' => 'Kamael Exclusive Weapon: Pa\'agrian Sword <Soul Crystal Enhancement> Increases Critical by 77.',
    'is_trade' => 1,
    'is_drop' => 1,
    'is_destruct' => 1,
    'crystal_type' => 'c',
    'consume_type' => 'consume_type_normal',
  ],
  9286 => 
  [
    'item_id' => 9286,
    'icon' => 'weapon_invincible_blade_i01',
    'name' => 'Immortal Edge',
    'additionalname' => 'Health',
    'description' => 'Kamael Exclusive Weapon: Pa\'agrian Sword <Soul Crystal Enhancement> Increases Max HP by 25%.',
    'is_trade' => 1,
    'is_drop' => 1,
    'is_destruct' => 1,
    'crystal_type' => 'c',
    'consume_type' => 'consume_type_normal',
  ],
  9287 => 
  [
    'item_id' => 9287,
    'icon' => 'weapon_invincible_blade_i01',
    'name' => 'Immortal Edge',
    'additionalname' => 'Critical Drain',
    'description' => 'Kamael Exclusive Weapon: Pa\'agrian Sword <Soul Crystal Enhancement> User absorbs 9 HP from target during a critical attack.',
    'is_trade' => 1,
    'is_drop' => 1,
    'is_destruct' => 1,
    'crystal_type' => 'c',
    'consume_type' => 'consume_type_normal',
  ],
  9288 => 
  [
    'item_id' => 9288,
    'icon' => 'weapon_taslam_i00',
    'name' => 'Tathlum',
    'additionalname' => '',
    'description' => 'Kamael-exclusive Weapon: Akat Longbow
Can bestow 1 regular Soul Crystal and 1 Special Soul Crystal.',
    'is_trade' => 1,
    'is_drop' => 1,
    'is_destruct' => 1,
    'crystal_type' => 'c',
    'consume_type' => 'consume_type_normal',
  ],
  9289 => 
  [
    'item_id' => 9289,
    'icon' => 'weapon_taslam_i01',
    'name' => 'Tathlum',
    'additionalname' => 'Guidance',
    'description' => 'Kamael Exclusive Weapon: Akat Long Bow <Soul Crystal Enhancement> Increases Accuracy by 4.',
    'is_trade' => 1,
    'is_drop' => 1,
    'is_destruct' => 1,
    'crystal_type' => 'c',
    'consume_type' => 'consume_type_normal',
  ],
  9290 => 
  [
    'item_id' => 9290,
    'icon' => 'weapon_taslam_i01',
    'name' => 'Tathlum',
    'additionalname' => 'Evasion',
    'description' => 'Kamael Exclusive Weapon: Akat Long Bow <Soul Crystal Enhancement> Increases Evasion by 2.',
    'is_trade' => 1,
    'is_drop' => 1,
    'is_destruct' => 1,
    'crystal_type' => 'c',
    'consume_type' => 'consume_type_normal',
  ],
  9291 => 
  [
    'item_id' => 9291,
    'icon' => 'weapon_taslam_i01',
    'name' => 'Tathlum',
    'additionalname' => 'Miser',
    'description' => 'Kamael Exclusive Weapon: Akat Long Bow <Soul Crystal Enhancement> There is a 32% rate of chance that the number of soulshots consumed is reduced to 4.',
    'is_trade' => 1,
    'is_drop' => 1,
    'is_destruct' => 1,
    'crystal_type' => 'c',
    'consume_type' => 'consume_type_normal',
  ],
  9292 => 
  [
    'item_id' => 9292,
    'icon' => 'weapon_blink_slasher_i00',
    'name' => 'Admiral\'s Estoc',
    'additionalname' => '',
    'description' => 'Kamael-exclusive Weapon: Samurai Long Sword
Can bestow 1 regular Soul Crystal and 1 Special Soul Crystal.
When enchanted to 4 or more, it Has a chance of increasing P. Atk., M. Atk., and healing power, and of decreasing MP consumption for skill use for you and your party members during a Critical Attack.',
    'is_trade' => 1,
    'is_drop' => 1,
    'is_destruct' => 1,
    'crystal_type' => 'c',
    'consume_type' => 'consume_type_normal',
  ],
  9293 => 
  [
    'item_id' => 9293,
    'icon' => 'weapon_blink_slasher_i01',
    'name' => 'Admiral\'s Estoc',
    'additionalname' => 'Focus',
    'description' => 'Kamael Exclusive Weapon: Samurai Long Sword <Soul Crystal Enhancement> Increases Critical by 73. When enchanted to 4 or more, it has a chance of increasing P. Atk., M. Atk., and healing power, and of decreaseing MP consumption for skill use for you and your party members during a critical attack.',
    'is_trade' => 1,
    'is_drop' => 1,
    'is_destruct' => 1,
    'crystal_type' => 'c',
    'consume_type' => 'consume_type_normal',
  ],
  9294 => 
  [
    'item_id' => 9294,
    'icon' => 'weapon_blink_slasher_i01',
    'name' => 'Admiral\'s Estoc',
    'additionalname' => 'Critical Damage',
    'description' => 'Kamael Exclusive Weapon: Samurai Long Sword <Soul Crystal Enhancement> Increases P. Atk. by 231 on a critical attack. When enchanted to 4 or more, it has a chance of increasing P. Atk., M. Atk., and healing power, and of decreaseing MP consumption for skill use for you and your party members during a critical attack.',
    'is_trade' => 1,
    'is_drop' => 1,
    'is_destruct' => 1,
    'crystal_type' => 'c',
    'consume_type' => 'consume_type_normal',
  ],
  9295 => 
  [
    'item_id' => 9295,
    'icon' => 'weapon_blink_slasher_i01',
    'name' => 'Admiral\'s Estoc',
    'additionalname' => 'Haste',
    'description' => 'Kamael Exclusive Weapon: Samurai Long Sword <Soul Crystal Enhancement> Increases Atk. Spd. by about 7%. When enchanted to 4 or more, it has a chance of increasing P. Atk., M. Atk., and healing power, and of decreaseing MP consumption for skill use for you and your party members during a critical attack.',
    'is_trade' => 1,
    'is_drop' => 1,
    'is_destruct' => 1,
    'crystal_type' => 'c',
    'consume_type' => 'consume_type_normal',
  ],
  9296 => 
  [
    'item_id' => 9296,
    'icon' => 'weapon_invincible_blade_i00',
    'name' => 'Saber Tooth',
    'additionalname' => '',
    'description' => 'Kamael-exclusive Weapon: Berserker Blade
Can bestow 1 regular Soul Crystal and 1 Special Soul Crystal.',
    'is_trade' => 1,
    'is_drop' => 1,
    'is_destruct' => 1,
    'crystal_type' => 'c',
    'consume_type' => 'consume_type_normal',
  ],
  9297 => 
  [
    'item_id' => 9297,
    'icon' => 'weapon_invincible_blade_i01',
    'name' => 'Saber Tooth',
    'additionalname' => 'Focus',
    'description' => 'Kamael Exclusive Weapon: Berserker Blade <Soul Crystal Enhancement> Increases Critical by 73.',
    'is_trade' => 1,
    'is_drop' => 1,
    'is_destruct' => 1,
    'crystal_type' => 'c',
    'consume_type' => 'consume_type_normal',
  ],
  9298 => 
  [
    'item_id' => 9298,
    'icon' => 'weapon_invincible_blade_i01',
    'name' => 'Saber Tooth',
    'additionalname' => 'Critical Damage',
    'description' => 'Kamael Exclusive Weapon: Berserker Blade <Soul Crystal Enhancement> Increases P. Atk. by 270 on a critical attack.',
    'is_trade' => 1,
    'is_drop' => 1,
    'is_destruct' => 1,
    'crystal_type' => 'c',
    'consume_type' => 'consume_type_normal',
  ],
  9299 => 
  [
    'item_id' => 9299,
    'icon' => 'weapon_invincible_blade_i01',
    'name' => 'Saber Tooth',
    'additionalname' => 'Haste',
    'description' => 'Kamael Exclusive Weapon: Berserker Blade <Soul Crystal Enhancement> Increases Atk. Spd. by about 7%.',
    'is_trade' => 1,
    'is_drop' => 1,
    'is_destruct' => 1,
    'crystal_type' => 'c',
    'consume_type' => 'consume_type_normal',
  ],
];