<?php
return [
  1 => 
  [
    'id' => 1,
    'type' => 'weapon',
    'name' => 'Short Sword',
    'add_name' => '',
    'description' => '',
    'icon' => 'weapon_small_sword_i00',
    'weapon_type' => 'sword',
    'bodypart' => 'rhand',
    'weight' => 1600,
    'price' => 768,
    'soulshots' => 1,
    'spiritshots' => 1,
  ],
  2 => 
  [
    'id' => 2,
    'type' => 'weapon',
    'name' => 'Long Sword',
    'add_name' => '',
    'description' => '',
    'icon' => 'weapon_long_sword_i00',
    'weapon_type' => 'sword',
    'bodypart' => 'rhand',
    'weight' => 1560,
    'price' => 136000,
    'soulshots' => 1,
    'spiritshots' => 1,
    'commissionItemType' => 'ONE_HAND_SWORD',
  ],
  3 => 
  [
    'id' => 3,
    'type' => 'weapon',
    'name' => 'Broadsword',
    'add_name' => '',
    'description' => '',
    'icon' => 'weapon_broad_sword_i00',
    'weapon_type' => 'sword',
    'bodypart' => 'rhand',
    'weight' => 1590,
    'price' => 12500,
    'soulshots' => 1,
    'spiritshots' => 1,
    'commissionItemType' => 'ONE_HAND_SWORD',
  ],
  4 => 
  [
    'id' => 4,
    'type' => 'weapon',
    'name' => 'Club',
    'add_name' => '',
    'description' => '',
    'icon' => 'weapon_club_i00',
    'weapon_type' => 'blunt',
    'bodypart' => 'rhand',
    'weight' => 1870,
    'price' => 768,
    'soulshots' => 1,
    'spiritshots' => 1,
    'commissionItemType' => 'BLUNT_WEAPON',
  ],
  5 => 
  [
    'id' => 5,
    'type' => 'weapon',
    'name' => 'Mace',
    'add_name' => '',
    'description' => '',
    'icon' => 'weapon_mace_i00',
    'weapon_type' => 'blunt',
    'bodypart' => 'rhand',
    'weight' => 1880,
    'price' => 12500,
    'soulshots' => 1,
    'spiritshots' => 1,
    'commissionItemType' => 'BLUNT_WEAPON',
  ],
  6 => 
  [
    'id' => 6,
    'type' => 'weapon',
    'name' => 'Apprentice\'s Wand',
    'add_name' => '',
    'description' => '',
    'icon' => 'weapon_apprentices_wand_i00',
    'weapon_type' => 'blunt',
    'bodypart' => 'rhand',
    'weight' => 1350,
    'soulshots' => 1,
    'spiritshots' => 1,
    'is_tradable' => false,
    'is_dropable' => false,
    'is_sellable' => false,
    'is_depositable' => false,
    'commissionItemType' => 'ONE_HAND_MAGIC_BLUNT_WEAPON',
    'is_magic_weapon' => true,
  ],
  7 => 
  [
    'id' => 7,
    'type' => 'weapon',
    'name' => 'Apprentice\'s Rod',
    'add_name' => '',
    'description' => '',
    'icon' => 'weapon_apprentices_rod_i00',
    'weapon_type' => 'blunt',
    'bodypart' => 'rhand',
    'weight' => 1330,
    'price' => 768,
    'soulshots' => 1,
    'spiritshots' => 1,
    'commissionItemType' => 'ONE_HAND_MAGIC_BLUNT_WEAPON',
    'is_magic_weapon' => true,
    'is_sellable' => false,
  ],
  8 => 
  [
    'id' => 8,
    'type' => 'weapon',
    'name' => 'Willow Staff',
    'add_name' => '',
    'description' => '',
    'icon' => 'weapon_willow_staff_i00',
    'weapon_type' => 'blunt',
    'bodypart' => 'lrhand',
    'weight' => 1080,
    'price' => 12500,
    'soulshots' => 1,
    'spiritshots' => 1,
    'commissionItemType' => 'TWO_HAND_MAGIC_BLUNT_WEAPON',
    'is_magic_weapon' => true,
  ],
  9 => 
  [
    'id' => 9,
    'type' => 'weapon',
    'name' => 'Cedar Staff',
    'add_name' => '',
    'description' => '',
    'icon' => 'weapon_cedar_staff_i00',
    'weapon_type' => 'blunt',
    'bodypart' => 'lrhand',
    'weight' => 1090,
    'price' => 54100,
    'soulshots' => 1,
    'spiritshots' => 1,
    'commissionItemType' => 'TWO_HAND_MAGIC_BLUNT_WEAPON',
    'is_magic_weapon' => true,
  ],
  10 => 
  [
    'id' => 10,
    'type' => 'weapon',
    'name' => 'Dagger',
    'add_name' => '',
    'description' => '',
    'icon' => 'weapon_dagger_i00',
    'weapon_type' => 'dagger',
    'bodypart' => 'rhand',
    'weight' => 1160,
    'soulshots' => 1,
    'spiritshots' => 1,
    'is_tradable' => false,
    'is_dropable' => false,
    'is_depositable' => false,
    'commissionItemType' => 'DAGGER',
    'is_sellable' => false,
  ],
  11 => 
  [
    'id' => 11,
    'type' => 'weapon',
    'name' => 'Bone Dagger',
    'add_name' => '',
    'description' => '',
    'icon' => 'weapon_bone_dagger_i00',
    'weapon_type' => 'dagger',
    'bodypart' => 'rhand',
    'weight' => 1150,
    'price' => 768,
    'soulshots' => 1,
    'spiritshots' => 1,
    'commissionItemType' => 'DAGGER',
  ],
  12 => 
  [
    'id' => 12,
    'type' => 'weapon',
    'name' => 'Knife',
    'add_name' => '',
    'description' => '',
    'icon' => 'weapon_knife_i00',
    'weapon_type' => 'dagger',
    'bodypart' => 'rhand',
    'weight' => 1140,
    'price' => 12500,
    'soulshots' => 1,
    'spiritshots' => 1,
    'commissionItemType' => 'DAGGER',
  ],
  13 => 
  [
    'id' => 13,
    'type' => 'weapon',
    'name' => 'Short Bow',
    'add_name' => '',
    'description' => '',
    'icon' => 'weapon_short_bow_i00',
    'weapon_type' => 'bow',
    'bodypart' => 'lrhand',
    'weight' => 1950,
    'price' => 768,
    'soulshots' => 2,
    'spiritshots' => 1,
    'mp_consume' => 1,
    'commissionItemType' => 'BOW',
  ],
  14 => 
  [
    'id' => 14,
    'type' => 'weapon',
    'name' => 'Bow',
    'add_name' => '',
    'description' => '',
    'icon' => 'weapon_bow_i00',
    'weapon_type' => 'bow',
    'bodypart' => 'lrhand',
    'weight' => 1930,
    'price' => 12500,
    'soulshots' => 2,
    'spiritshots' => 1,
    'mp_consume' => 1,
    'commissionItemType' => 'BOW',
  ],
  15 => 
  [
    'id' => 15,
    'type' => 'weapon',
    'name' => 'Short Spear',
    'add_name' => '',
    'description' => '',
    'icon' => 'weapon_short_spear_i00',
    'weapon_type' => 'pole',
    'bodypart' => 'lrhand',
    'weight' => 2140,
    'price' => 136000,
    'soulshots' => 1,
    'spiritshots' => 1,
    'commissionItemType' => 'SPEAR',
  ],
  16 => 
  [
    'id' => 16,
    'type' => 'weapon',
    'name' => 'Great Spear',
    'add_name' => '',
    'description' => '',
    'icon' => 'weapon_long_spear_i00',
    'weapon_type' => 'pole',
    'bodypart' => 'lrhand',
    'weight' => 2120,
    'price' => 244000,
    'soulshots' => 1,
    'spiritshots' => 1,
    'commissionItemType' => 'SPEAR',
  ],
  17 => 
  [
    'id' => 17,
    'type' => 'etcitem',
    'name' => 'Wooden Arrow',
    'add_name' => '',
    'description' => 'An arrow made of wood. It is an arrow used for a no grade bow.',
    'icon' => 'etc_wooden_quiver_i00',
    'etcitem_type' => 'arrow',
    'weight' => 1,
    'price' => 1,
    'commissionItemType' => 'OTHER_ITEM',
    'is_stackable' => true,
  ],
  18 => 
  [
    'id' => 18,
    'type' => 'armor',
    'name' => 'Leather Shield',
    'add_name' => '',
    'description' => '',
    'icon' => 'shield_leather_shield_i00',
    'bodypart' => 'lhand',
    'weight' => 1430,
    'commissionItemType' => 'SHIELD',
    'price' => 39,
  ],
  19 => 
  [
    'id' => 19,
    'type' => 'armor',
    'name' => 'Small Shield',
    'add_name' => '',
    'description' => '',
    'icon' => 'shield_small_shield_i00',
    'bodypart' => 'lhand',
    'weight' => 1420,
    'commissionItemType' => 'SHIELD',
    'price' => 638,
  ],
  20 => 
  [
    'id' => 20,
    'type' => 'armor',
    'name' => 'Buckler',
    'add_name' => '',
    'description' => '',
    'icon' => 'shield_buckler_i00',
    'bodypart' => 'lhand',
    'weight' => 1410,
    'commissionItemType' => 'SHIELD',
    'price' => 2780,
  ],
  21 => 
  [
    'id' => 21,
    'type' => 'armor',
    'name' => 'Shirt',
    'add_name' => '',
    'description' => '',
    'icon' => 'armor_t02_u_i00',
    'armor_type' => 'light',
    'bodypart' => 'chest',
    'weight' => 4830,
    'commissionItemType' => 'ARMOR_TOP',
    'price' => 147,
  ],
  22 => 
  [
    'id' => 22,
    'type' => 'armor',
    'name' => 'Leather Shirt',
    'add_name' => '',
    'description' => '',
    'icon' => 'armor_t04_u_i00',
    'armor_type' => 'light',
    'bodypart' => 'chest',
    'weight' => 4830,
    'commissionItemType' => 'ARMOR_TOP',
    'price' => 2430,
  ],
  23 => 
  [
    'id' => 23,
    'type' => 'armor',
    'name' => 'Wooden Breastplate',
    'add_name' => '',
    'description' => '',
    'icon' => 'armor_t06_u_i00',
    'armor_type' => 'light',
    'bodypart' => 'chest',
    'weight' => 4820,
    'commissionItemType' => 'ARMOR_TOP',
    'price' => 7960,
  ],
  24 => 
  [
    'id' => 24,
    'type' => 'armor',
    'name' => 'Bone Breastplate',
    'add_name' => '',
    'description' => '',
    'icon' => 'armor_t32_u_i00',
    'armor_type' => 'light',
    'bodypart' => 'chest',
    'weight' => 4770,
    'commissionItemType' => 'ARMOR_TOP',
    'price' => 20300,
  ],
  25 => 
  [
    'id' => 25,
    'type' => 'armor',
    'name' => 'Piece Bone Breastplate',
    'add_name' => '',
    'description' => '',
    'icon' => 'armor_t33_u_i00',
    'armor_type' => 'heavy',
    'bodypart' => 'chest',
    'weight' => 8970,
    'price' => 31800,
    'commissionItemType' => 'ARMOR_TOP',
  ],
  26 => 
  [
    'id' => 26,
    'type' => 'armor',
    'name' => 'Bronze Breastplate',
    'add_name' => '',
    'description' => '',
    'icon' => 'armor_t34_u_i00',
    'armor_type' => 'heavy',
    'bodypart' => 'chest',
    'weight' => 8920,
    'commissionItemType' => 'ARMOR_TOP',
    'price' => 49200,
  ],
  27 => 
  [
    'id' => 27,
    'type' => 'armor',
    'name' => 'Durable Leather Shirt',
    'add_name' => '',
    'description' => '',
    'icon' => 'armor_t30_u_i00',
    'armor_type' => 'light',
    'bodypart' => 'chest',
    'weight' => 4720,
    'commissionItemType' => 'ARMOR_TOP',
    'price' => 36900,
  ],
  28 => 
  [
    'id' => 28,
    'type' => 'armor',
    'name' => 'Pants',
    'add_name' => '',
    'description' => '',
    'icon' => 'armor_t02_l_i00',
    'armor_type' => 'light',
    'bodypart' => 'legs',
    'weight' => 1740,
    'commissionItemType' => 'ARMOR_PANTS',
    'price' => 92,
  ],
  29 => 
  [
    'id' => 29,
    'type' => 'armor',
    'name' => 'Leather Pants',
    'add_name' => '',
    'description' => '',
    'icon' => 'armor_t04_l_i00',
    'armor_type' => 'light',
    'bodypart' => 'legs',
    'weight' => 1730,
    'commissionItemType' => 'ARMOR_PANTS',
    'price' => 1520,
  ],
  30 => 
  [
    'id' => 30,
    'type' => 'armor',
    'name' => 'Durable Leather Pants',
    'add_name' => '',
    'description' => '',
    'icon' => 'armor_t06_l_i00',
    'armor_type' => 'light',
    'bodypart' => 'legs',
    'weight' => 1700,
    'commissionItemType' => 'ARMOR_PANTS',
    'price' => 4970,
  ],
  31 => 
  [
    'id' => 31,
    'type' => 'armor',
    'name' => 'Bone Gaiters',
    'add_name' => '',
    'description' => '',
    'icon' => 'armor_t32_l_i00',
    'armor_type' => 'light',
    'bodypart' => 'legs',
    'weight' => 1680,
    'commissionItemType' => 'ARMOR_PANTS',
    'price' => 12700,
  ],
  32 => 
  [
    'id' => 32,
    'type' => 'armor',
    'name' => 'Piece Bone Gaiters',
    'add_name' => '',
    'description' => '',
    'icon' => 'armor_t33_l_i00',
    'armor_type' => 'heavy',
    'bodypart' => 'legs',
    'weight' => 4020,
    'commissionItemType' => 'ARMOR_PANTS',
    'price' => 19900,
  ],
  33 => 
  [
    'id' => 33,
    'type' => 'armor',
    'name' => 'Durable Leather Gaiters',
    'add_name' => '',
    'description' => '',
    'icon' => 'armor_t30_l_i00',
    'armor_type' => 'light',
    'bodypart' => 'legs',
    'weight' => 1610,
    'commissionItemType' => 'ARMOR_PANTS',
    'price' => 23000,
  ],
  34 => 
  [
    'id' => 34,
    'type' => 'armor',
    'name' => 'Bronze Gaiters',
    'add_name' => '',
    'description' => '',
    'icon' => 'armor_t34_l_i00',
    'armor_type' => 'heavy',
    'bodypart' => 'legs',
    'weight' => 3960,
    'commissionItemType' => 'ARMOR_PANTS',
    'price' => 30700,
  ],
  35 => 
  [
    'id' => 35,
    'type' => 'armor',
    'name' => 'Cloth Shoes',
    'add_name' => '',
    'description' => '',
    'icon' => 'armor_t02_b_i00',
    'bodypart' => 'feet',
    'weight' => 1320,
    'commissionItemType' => 'FEET',
    'price' => 37,
  ],
  36 => 
  [
    'id' => 36,
    'type' => 'armor',
    'name' => 'Leather Sandals',
    'add_name' => '',
    'description' => '',
    'icon' => 'armor_t03_b_i00',
    'bodypart' => 'feet',
    'weight' => 1320,
    'commissionItemType' => 'FEET',
    'price' => 37,
  ],
  37 => 
  [
    'id' => 37,
    'type' => 'armor',
    'name' => 'Leather Shoes',
    'add_name' => '',
    'description' => '',
    'icon' => 'armor_t05_b_i00',
    'bodypart' => 'feet',
    'weight' => 1320,
    'commissionItemType' => 'FEET',
    'price' => 2650,
  ],
  38 => 
  [
    'id' => 38,
    'type' => 'armor',
    'name' => 'Low Boots',
    'add_name' => '',
    'description' => '',
    'icon' => 'armor_t32_b_i00',
    'bodypart' => 'feet',
    'weight' => 1320,
    'commissionItemType' => 'FEET',
    'price' => 6770,
  ],
  39 => 
  [
    'id' => 39,
    'type' => 'armor',
    'name' => 'Boots',
    'add_name' => '',
    'description' => '',
    'icon' => 'armor_t30_b_i00',
    'bodypart' => 'feet',
    'weight' => 1310,
    'commissionItemType' => 'FEET',
    'price' => 12300,
  ],
  40 => 
  [
    'id' => 40,
    'type' => 'armor',
    'name' => 'Leather Boots',
    'add_name' => '',
    'description' => '',
    'icon' => 'armor_t09_b_i00',
    'bodypart' => 'feet',
    'crystal_count' => 38,
    'crystal_type' => 'd',
    'weight' => 1300,
    'price' => 20900,
    'commissionItemType' => 'FEET',
    'enchant_enabled' => true,
  ],
  41 => 
  [
    'id' => 41,
    'type' => 'armor',
    'name' => 'Cloth Cap',
    'add_name' => '',
    'description' => '',
    'icon' => 'armor_cloth_helmet_i00',
    'bodypart' => 'head',
    'weight' => 660,
    'price' => 55,
    'commissionItemType' => 'HELMET',
  ],
  42 => 
  [
    'id' => 42,
    'type' => 'armor',
    'name' => 'Leather Cap',
    'add_name' => '',
    'description' => '',
    'icon' => 'armor_leather_helmet_i00',
    'bodypart' => 'head',
    'weight' => 660,
    'commissionItemType' => 'HELMET',
    'price' => 911,
  ],
  43 => 
  [
    'id' => 43,
    'type' => 'armor',
    'name' => 'Wooden Helmet',
    'add_name' => '',
    'description' => '',
    'icon' => 'armor_leather_helmet_i00',
    'bodypart' => 'head',
    'weight' => 660,
    'commissionItemType' => 'HELMET',
    'price' => 3980,
  ],
  44 => 
  [
    'id' => 44,
    'type' => 'armor',
    'name' => 'Leather Helmet',
    'add_name' => '',
    'description' => '',
    'icon' => 'armor_leather_helmet_i00',
    'bodypart' => 'head',
    'weight' => 650,
    'commissionItemType' => 'HELMET',
    'price' => 10200,
  ],
  45 => 
  [
    'id' => 45,
    'type' => 'armor',
    'name' => 'Bone Helmet',
    'add_name' => '',
    'description' => '',
    'icon' => 'armor_leather_helmet_i00',
    'bodypart' => 'head',
    'crystal_count' => 56,
    'crystal_type' => 'd',
    'weight' => 640,
    'price' => 31300,
    'commissionItemType' => 'HELMET',
    'enchant_enabled' => true,
  ],
  46 => 
  [
    'id' => 46,
    'type' => 'armor',
    'name' => 'Bronze Helmet',
    'add_name' => '',
    'description' => '',
    'icon' => 'armor_helmet_i00',
    'bodypart' => 'head',
    'crystal_count' => 90,
    'crystal_type' => 'd',
    'weight' => 630,
    'price' => 50000,
    'enchant_enabled' => true,
    'commissionItemType' => 'HELMET',
  ],
  47 => 
  [
    'id' => 47,
    'type' => 'armor',
    'name' => 'Helmet',
    'add_name' => '',
    'description' => '',
    'icon' => 'armor_helmet_i00',
    'bodypart' => 'head',
    'crystal_count' => 138,
    'crystal_type' => 'd',
    'weight' => 640,
    'price' => 76200,
    'commissionItemType' => 'HELMET',
    'enchant_enabled' => true,
  ],
  48 => 
  [
    'id' => 48,
    'type' => 'armor',
    'name' => 'Short Gloves',
    'add_name' => '',
    'description' => '',
    'icon' => 'armor_t02_g_i00',
    'bodypart' => 'gloves',
    'weight' => 660,
    'commissionItemType' => 'GLOVES',
    'price' => 37,
  ],
  49 => 
  [
    'id' => 49,
    'type' => 'armor',
    'name' => 'Gloves',
    'add_name' => '',
    'description' => '',
    'icon' => 'armor_t06_g_i00',
    'bodypart' => 'gloves',
    'weight' => 660,
    'commissionItemType' => 'GLOVES',
    'price' => 2650,
  ],
  50 => 
  [
    'id' => 50,
    'type' => 'armor',
    'name' => 'Leather Gloves',
    'add_name' => '',
    'description' => '',
    'icon' => 'armor_t32_g_i00',
    'bodypart' => 'gloves',
    'weight' => 650,
    'commissionItemType' => 'GLOVES',
    'price' => 6770,
  ],
  51 => 
  [
    'id' => 51,
    'type' => 'armor',
    'name' => 'Bracer',
    'add_name' => '',
    'description' => '',
    'icon' => 'armor_t30_g_i00',
    'bodypart' => 'gloves',
    'weight' => 650,
    'commissionItemType' => 'GLOVES',
    'price' => 12300,
  ],
  57 => 
  [
    'id' => 57,
    'type' => 'etcitem',
    'name' => 'Adena',
    'add_name' => '',
    'description' => '',
    'icon' => 'etc_adena_i00',
    'price' => 1,
    'is_sellable' => false,
    'is_stackable' => true,
  ],
  58 => 
  [
    'id' => 58,
    'type' => 'armor',
    'name' => 'Mithril Breastplate',
    'add_name' => '',
    'description' => '',
    'icon' => 'armor_t19_u_i00',
    'armor_type' => 'heavy',
    'bodypart' => 'chest',
    'crystal_count' => 332,
    'crystal_type' => 'd',
    'weight' => 8670,
    'price' => 183000,
    'commissionItemType' => 'ARMOR_TOP',
    'enchant_enabled' => true,
  ],
  59 => 
  [
    'id' => 59,
    'type' => 'armor',
    'name' => 'Mithril Gaiters',
    'add_name' => '',
    'description' => '',
    'icon' => 'armor_t19_l_i00',
    'armor_type' => 'heavy',
    'bodypart' => 'legs',
    'crystal_count' => 230,
    'crystal_type' => 'd',
    'weight' => 3830,
    'price' => 127000,
    'commissionItemType' => 'ARMOR_PANTS',
    'enchant_enabled' => true,
  ],
  60 => 
  [
    'id' => 60,
    'type' => 'armor',
    'name' => 'Compound Armor',
    'add_name' => '',
    'description' => 'Full body armor.',
    'icon' => 'armor_t61_ul_i00',
    'armor_type' => 'heavy',
    'bodypart' => 'onepiece',
    'crystal_count' => 576,
    'crystal_type' => 'c',
    'weight' => 10980,
    'price' => 1440000,
    'commissionItemType' => 'FULL_BODY',
    'enchant_enabled' => true,
  ],
  61 => 
  [
    'id' => 61,
    'type' => 'armor',
    'name' => 'Mithril Gloves',
    'add_name' => '',
    'description' => '',
    'icon' => 'armor_t46_g_i00',
    'bodypart' => 'gloves',
    'crystal_count' => 177,
    'crystal_type' => 'd',
    'weight' => 630,
    'price' => 97800,
    'commissionItemType' => 'GLOVES',
    'enchant_enabled' => true,
  ],
  62 => 
  [
    'id' => 62,
    'type' => 'armor',
    'name' => 'Reinforced Mithril Boots',
    'add_name' => '',
    'description' => '',
    'icon' => 'armor_t47_b_i00',
    'bodypart' => 'feet',
    'crystal_count' => 50,
    'crystal_type' => 'c',
    'weight' => 1230,
    'price' => 126000,
    'enchant_enabled' => true,
    'commissionItemType' => 'FEET',
  ],
  63 => 
  [
    'id' => 63,
    'type' => 'armor',
    'name' => 'Gauntlets',
    'add_name' => '',
    'description' => '',
    'icon' => 'armor_t10_g_i00',
    'bodypart' => 'gloves',
    'crystal_count' => 92,
    'crystal_type' => 'd',
    'weight' => 640,
    'price' => 50800,
    'commissionItemType' => 'GLOVES',
    'enchant_enabled' => true,
  ],
  64 => 
  [
    'id' => 64,
    'type' => 'armor',
    'name' => 'Compound Boots',
    'add_name' => '',
    'description' => '',
    'icon' => 'armor_t61_b_i00',
    'bodypart' => 'feet',
    'crystal_count' => 98,
    'crystal_type' => 'c',
    'weight' => 1220,
    'price' => 245000,
    'enchant_enabled' => true,
    'commissionItemType' => 'FEET',
  ],
  66 => 
  [
    'id' => 66,
    'type' => 'weapon',
    'name' => 'Gladius',
    'add_name' => '',
    'description' => '',
    'icon' => 'weapon_gladius_i00',
    'weapon_type' => 'sword',
    'bodypart' => 'rhand',
    'weight' => 1570,
    'price' => 54100,
    'soulshots' => 1,
    'spiritshots' => 1,
    'commissionItemType' => 'ONE_HAND_SWORD',
  ],
  67 => 
  [
    'id' => 67,
    'type' => 'weapon',
    'name' => 'Orcish Sword',
    'add_name' => '',
    'description' => '',
    'icon' => 'weapon_orcish_sword_i00',
    'weapon_type' => 'sword',
    'bodypart' => 'rhand',
    'weight' => 1570,
    'price' => 54100,
    'soulshots' => 1,
    'spiritshots' => 1,
    'commissionItemType' => 'ONE_HAND_SWORD',
  ],
  68 => 
  [
    'id' => 68,
    'type' => 'weapon',
    'name' => 'Falchion',
    'add_name' => '',
    'description' => '',
    'icon' => 'weapon_falchion_i00',
    'weapon_type' => 'sword',
    'bodypart' => 'rhand',
    'weight' => 1530,
    'price' => 244000,
    'soulshots' => 1,
    'spiritshots' => 1,
    'commissionItemType' => 'ONE_HAND_SWORD',
  ],
  69 => 
  [
    'id' => 69,
    'type' => 'weapon',
    'name' => 'Bastard Sword',
    'add_name' => '',
    'description' => '',
    'icon' => 'weapon_bastard_sword_i00',
    'weapon_type' => 'sword',
    'bodypart' => 'rhand',
    'crystal_count' => 1170,
    'crystal_type' => 'd',
    'weight' => 1510,
    'price' => 644000,
    'change_weaponId' => 9213,
    'soulshots' => 1,
    'spiritshots' => 1,
    'commissionItemType' => 'ONE_HAND_SWORD',
    'enchant_enabled' => true,
  ],
  70 => 
  [
    'id' => 70,
    'type' => 'weapon',
    'name' => 'Claymore',
    'add_name' => '',
    'description' => '',
    'icon' => 'weapon_claymore_i00',
    'weapon_type' => 'sword',
    'bodypart' => 'lrhand',
    'crystal_count' => 3272,
    'crystal_type' => 'd',
    'weight' => 2090,
    'price' => 1800000,
    'change_weaponId' => 9226,
    'soulshots' => 1,
    'spiritshots' => 1,
    'enchant_enabled' => true,
    'commissionItemType' => 'TWO_HAND_SWORD',
  ],
  71 => 
  [
    'id' => 71,
    'type' => 'weapon',
    'name' => 'Flamberge',
    'add_name' => '',
    'description' => 'Bestows one of the following functions: Critical Damage, Focus or Light. ',
    'icon' => 'weapon_flamberge_i00',
    'weapon_type' => 'sword',
    'bodypart' => 'lrhand',
    'crystal_count' => 916,
    'crystal_type' => 'c',
    'weight' => 2010,
    'price' => 2290000,
    'change_weaponId' => 9232,
    'soulshots' => 1,
    'spiritshots' => 1,
    'enchant_enabled' => true,
    'commissionItemType' => 'TWO_HAND_SWORD',
  ],
  72 => 
  [
    'id' => 72,
    'type' => 'weapon',
    'name' => 'Stormbringer',
    'add_name' => '',
    'description' => 'Bestows one of the following functions: Critical Anger, Focus or Light.',
    'icon' => 'weapon_stormbringer_i00',
    'weapon_type' => 'sword',
    'bodypart' => 'rhand',
    'crystal_count' => 916,
    'crystal_type' => 'c',
    'weight' => 1430,
    'price' => 2290000,
    'change_weaponId' => 9228,
    'soulshots' => 1,
    'spiritshots' => 1,
    'enchant_enabled' => true,
    'commissionItemType' => 'ONE_HAND_SWORD',
  ],
  73 => 
  [
    'id' => 73,
    'type' => 'weapon',
    'name' => 'Shamshir',
    'add_name' => '',
    'description' => 'Bestows one of the following functions: Guidance, Back Blow, Rsk. Or Evasion.',
    'icon' => 'weapon_shamshir_i00',
    'weapon_type' => 'sword',
    'bodypart' => 'rhand',
    'crystal_count' => 1148,
    'crystal_type' => 'c',
    'weight' => 1420,
    'price' => 2870000,
    'change_weaponId' => 9240,
    'soulshots' => 1,
    'spiritshots' => 1,
    'commissionItemType' => 'ONE_HAND_SWORD',
    'enchant_enabled' => true,
  ],
  74 => 
  [
    'id' => 74,
    'type' => 'weapon',
    'name' => 'Katana',
    'add_name' => '',
    'description' => 'Bestows one of the following functions: Focus, Critical Damage or Haste.',
    'icon' => 'weapon_katana_i00',
    'weapon_type' => 'sword',
    'bodypart' => 'rhand',
    'crystal_count' => 1148,
    'crystal_type' => 'c',
    'weight' => 1420,
    'price' => 2870000,
    'change_weaponId' => 9244,
    'soulshots' => 1,
    'spiritshots' => 1,
    'commissionItemType' => 'ONE_HAND_SWORD',
    'enchant_enabled' => true,
  ],
  75 => 
  [
    'id' => 75,
    'type' => 'weapon',
    'name' => 'Caliburs',
    'add_name' => '',
    'description' => 'Bestows either Guidance, Focus or Critical Damage.',
    'icon' => 'weapon_caliburs_i00',
    'weapon_type' => 'sword',
    'bodypart' => 'rhand',
    'crystal_count' => 1720,
    'crystal_type' => 'c',
    'weight' => 1400,
    'price' => 4300000,
    'change_weaponId' => 9264,
    'soulshots' => 1,
    'spiritshots' => 1,
    'commissionItemType' => 'ONE_HAND_SWORD',
    'enchant_enabled' => true,
  ],
  76 => 
  [
    'id' => 76,
    'type' => 'weapon',
    'name' => 'Sword of Delusion',
    'add_name' => '',
    'description' => 'Bestows one of the following functions: Focus, Health, or Rsk. Haste.',
    'icon' => 'weapon_sword_of_delusion_i00',
    'weapon_type' => 'sword',
    'bodypart' => 'rhand',
    'crystal_count' => 1720,
    'crystal_type' => 'c',
    'weight' => 1400,
    'price' => 4300000,
    'change_weaponId' => 9268,
    'soulshots' => 1,
    'spiritshots' => 1,
    'commissionItemType' => 'ONE_HAND_SWORD',
    'enchant_enabled' => true,
  ],
  77 => 
  [
    'id' => 77,
    'type' => 'weapon',
    'name' => 'Tsurugi',
    'add_name' => '',
    'description' => 'Bestows one of the following functions: Focus, Critical Damage or Haste.',
    'icon' => 'weapon_tsurugi_i00',
    'weapon_type' => 'sword',
    'bodypart' => 'rhand',
    'crystal_count' => 1720,
    'crystal_type' => 'c',
    'weight' => 1400,
    'price' => 4300000,
    'change_weaponId' => 9272,
    'soulshots' => 1,
    'spiritshots' => 1,
    'commissionItemType' => 'ONE_HAND_SWORD',
    'enchant_enabled' => true,
  ],
  78 => 
  [
    'id' => 78,
    'type' => 'weapon',
    'name' => 'Great Sword',
    'add_name' => '',
    'description' => 'Bestows one of the following functions: Health, Critical Damage or Focus.',
    'icon' => 'weapon_great_sword_i00',
    'weapon_type' => 'sword',
    'bodypart' => 'lrhand',
    'crystal_count' => 1157,
    'crystal_type' => 'b',
    'weight' => 1930,
    'price' => 8680000,
    'change_weaponId' => 9308,
    'soulshots' => 1,
    'spiritshots' => 1,
    'enchant_enabled' => true,
    'commissionItemType' => 'TWO_HAND_SWORD',
  ],
  79 => 
  [
    'id' => 79,
    'type' => 'weapon',
    'name' => 'Damascus Sword',
    'add_name' => '',
    'description' => 'Bestows one of the following functions: Focus, Critical Damage or Haste.',
    'icon' => 'weapon_sword_of_damascus_i00',
    'weapon_type' => 'sword',
    'bodypart' => 'rhand',
    'crystal_count' => 1746,
    'crystal_type' => 'b',
    'weight' => 1350,
    'price' => 13100000,
    'change_weaponId' => 9316,
    'soulshots' => 1,
    'spiritshots' => 1,
    'enchant_enabled' => true,
    'commissionItemType' => 'ONE_HAND_SWORD',
  ],
  80 => 
  [
    'id' => 80,
    'type' => 'weapon',
    'name' => 'Tallum Blade',
    'add_name' => '',
    'description' => 'Bestows one of the following functions: Critical Poison, Haste or Anger.',
    'icon' => 'weapon_tallum_blade_i00',
    'weapon_type' => 'sword',
    'bodypart' => 'rhand',
    'crystal_count' => 1128,
    'crystal_type' => 'a',
    'weight' => 1330,
    'price' => 14098000,
    'change_weaponId' => 9328,
    'soulshots' => 1,
    'spiritshots' => 1,
    'commissionItemType' => 'ONE_HAND_SWORD',
    'enchant_enabled' => true,
  ],
  81 => 
  [
    'id' => 81,
    'type' => 'weapon',
    'name' => 'Dragon Slayer',
    'add_name' => '',
    'description' => 'Bestows one of the following functions: Health, Critical Bleed or Critical Drain.',
    'icon' => 'weapon_dragon_slayer_i00',
    'weapon_type' => 'sword',
    'bodypart' => 'lrhand',
    'crystal_count' => 1659,
    'crystal_type' => 'a',
    'weight' => 1840,
    'price' => 20741000,
    'change_weaponId' => 9344,
    'soulshots' => 1,
    'spiritshots' => 1,
    'enchant_enabled' => true,
    'commissionItemType' => 'TWO_HAND_SWORD',
  ],
  83 => 
  [
    'id' => 83,
    'type' => 'weapon',
    'name' => 'Sword of Magic',
    'add_name' => '',
    'description' => '',
    'icon' => 'weapon_sword_of_magic_i00',
    'weapon_type' => 'sword',
    'bodypart' => 'rhand',
    'crystal_count' => 1301,
    'crystal_type' => 'd',
    'weight' => 970,
    'price' => 716000,
    'soulshots' => 1,
    'spiritshots' => 1,
    'enchant_enabled' => true,
    'commissionItemType' => 'ONE_HAND_MAGIC_SWORD',
    'is_magic_weapon' => true,
  ],
  84 => 
  [
    'id' => 84,
    'type' => 'weapon',
    'name' => 'Homunkulus\' Sword',
    'add_name' => '',
    'description' => 'Bestows one of the following functions: Acumen, Conversion or Paralyze.',
    'icon' => 'weapon_homunkuluss_sword_i00',
    'weapon_type' => 'sword',
    'bodypart' => 'rhand',
    'crystal_count' => 1720,
    'crystal_type' => 'c',
    'weight' => 950,
    'price' => 4300000,
    'soulshots' => 1,
    'spiritshots' => 1,
    'enchant_enabled' => true,
    'is_magic_weapon' => true,
    'commissionItemType' => 'ONE_HAND_MAGIC_SWORD',
  ],
  86 => 
  [
    'id' => 86,
    'type' => 'weapon',
    'name' => 'Tomahawk',
    'add_name' => '',
    'description' => '',
    'icon' => 'weapon_tomahawk_i00',
    'weapon_type' => 'blunt',
    'bodypart' => 'rhand',
    'crystal_count' => 1170,
    'crystal_type' => 'd',
    'weight' => 1780,
    'price' => 644000,
    'soulshots' => 1,
    'spiritshots' => 1,
    'commissionItemType' => 'BLUNT_WEAPON',
    'enchant_enabled' => true,
  ],
  87 => 
  [
    'id' => 87,
    'type' => 'weapon',
    'name' => 'Iron Hammer',
    'add_name' => '',
    'description' => '',
    'icon' => 'weapon_iron_hammer_i00',
    'weapon_type' => 'blunt',
    'bodypart' => 'rhand',
    'weight' => 1850,
    'price' => 244000,
    'soulshots' => 1,
    'spiritshots' => 1,
    'commissionItemType' => 'BLUNT_WEAPON',
  ],
  88 => 
  [
    'id' => 88,
    'type' => 'weapon',
    'name' => 'Morning Star',
    'add_name' => '',
    'description' => '',
    'icon' => 'weapon_morning_star_i00',
    'weapon_type' => 'blunt',
    'bodypart' => 'rhand',
    'crystal_count' => 2545,
    'crystal_type' => 'd',
    'weight' => 1720,
    'price' => 1400000,
    'soulshots' => 1,
    'spiritshots' => 1,
    'commissionItemType' => 'BLUNT_WEAPON',
    'enchant_enabled' => true,
  ],
  89 => 
  [
    'id' => 89,
    'type' => 'weapon',
    'name' => 'Big Hammer',
    'add_name' => '',
    'description' => 'Bestows either Health, Rsk. Focus or Haste.',
    'icon' => 'weapon_big_hammer_i00',
    'weapon_type' => 'blunt',
    'bodypart' => 'rhand',
    'crystal_count' => 916,
    'crystal_type' => 'c',
    'weight' => 1710,
    'price' => 2290000,
    'soulshots' => 1,
    'spiritshots' => 1,
    'commissionItemType' => 'BLUNT_WEAPON',
    'enchant_enabled' => true,
  ],
  90 => 
  [
    'id' => 90,
    'type' => 'weapon',
    'name' => 'Goat Head Staff',
    'add_name' => '',
    'description' => '',
    'icon' => 'weapon_goathead_staff_i00',
    'weapon_type' => 'blunt',
    'bodypart' => 'lrhand',
    'crystal_count' => 2545,
    'crystal_type' => 'd',
    'weight' => 1000,
    'price' => 1400000,
    'soulshots' => 1,
    'spiritshots' => 1,
    'enchant_enabled' => true,
    'commissionItemType' => 'ONE_HAND_MAGIC_BLUNT_WEAPON',
    'is_magic_weapon' => true,
  ],
  91 => 
  [
    'id' => 91,
    'type' => 'weapon',
    'name' => 'Heavy War Axe',
    'add_name' => '',
    'description' => 'Bestows either Anger, Health, or Rsk. Focus.',
    'icon' => 'weapon_heavy_war_axe_i00',
    'weapon_type' => 'blunt',
    'bodypart' => 'rhand',
    'crystal_count' => 1157,
    'crystal_type' => 'b',
    'weight' => 1620,
    'price' => 8680000,
    'soulshots' => 1,
    'spiritshots' => 1,
    'commissionItemType' => 'BLUNT_WEAPON',
    'enchant_enabled' => true,
  ],
  92 => 
  [
    'id' => 92,
    'type' => 'weapon',
    'name' => 'Spirit\'s Staff',
    'add_name' => '',
    'description' => 'Bestows either Regeneration, Mental Shield or Hold.',
    'icon' => 'weapon_sprites_staff_i00',
    'weapon_type' => 'blunt',
    'bodypart' => 'lrhand',
    'crystal_count' => 1157,
    'crystal_type' => 'b',
    'weight' => 960,
    'price' => 8680000,
    'soulshots' => 1,
    'spiritshots' => 1,
    'enchant_enabled' => true,
    'commissionItemType' => 'TWO_HAND_MAGIC_BLUNT_WEAPON',
    'is_magic_weapon' => true,
  ],
  93 => 
  [
    'id' => 93,
    'type' => 'weapon',
    'name' => 'Winged Spear',
    'add_name' => '',
    'description' => '',
    'icon' => 'weapon_winged_spear_i00',
    'weapon_type' => 'pole',
    'bodypart' => 'lrhand',
    'crystal_count' => 2545,
    'crystal_type' => 'd',
    'weight' => 2060,
    'price' => 1400000,
    'soulshots' => 1,
    'spiritshots' => 1,
    'enchant_enabled' => true,
    'commissionItemType' => 'SPEAR',
  ],
  94 => 
  [
    'id' => 94,
    'type' => 'weapon',
    'name' => 'Bec de Corbin',
    'add_name' => '',
    'description' => 'Bestows either Critical Stun, Towering Blow or Light.',
    'icon' => 'weapon_bech_de_corbin_i00',
    'weapon_type' => 'pole',
    'bodypart' => 'lrhand',
    'crystal_count' => 1148,
    'crystal_type' => 'c',
    'weight' => 2020,
    'price' => 2870000,
    'soulshots' => 1,
    'spiritshots' => 1,
    'enchant_enabled' => true,
    'commissionItemType' => 'SPEAR',
  ],
  95 => 
  [
    'id' => 95,
    'type' => 'weapon',
    'name' => 'Poleaxe',
    'add_name' => '',
    'description' => 'Bestows one of the following functions: Wide Blow, Towering Blow or Critical Stun.',
    'icon' => 'weapon_poleaxe_i00',
    'weapon_type' => 'pole',
    'bodypart' => 'lrhand',
    'crystal_count' => 1720,
    'crystal_type' => 'c',
    'weight' => 2010,
    'price' => 4300000,
    'soulshots' => 1,
    'spiritshots' => 1,
    'enchant_enabled' => true,
    'commissionItemType' => 'SPEAR',
  ],
  96 => 
  [
    'id' => 96,
    'type' => 'weapon',
    'name' => 'Scythe',
    'add_name' => '',
    'description' => 'Bestows either Anger, Critical Stun or Light.',
    'icon' => 'weapon_scythe_i00',
    'weapon_type' => 'pole',
    'bodypart' => 'lrhand',
    'crystal_count' => 916,
    'crystal_type' => 'c',
    'weight' => 2040,
    'price' => 2290000,
    'soulshots' => 1,
    'spiritshots' => 1,
    'enchant_enabled' => true,
    'commissionItemType' => 'SPEAR',
  ],
  97 => 
  [
    'id' => 97,
    'type' => 'weapon',
    'name' => 'Lance',
    'add_name' => '',
    'description' => 'Bestows either Anger, Critical Stun or Towering Blow.',
    'icon' => 'weapon_lancia_i00',
    'weapon_type' => 'pole',
    'bodypart' => 'lrhand',
    'crystal_count' => 1746,
    'crystal_type' => 'b',
    'weight' => 1920,
    'price' => 13100000,
    'soulshots' => 1,
    'spiritshots' => 1,
    'enchant_enabled' => true,
    'commissionItemType' => 'SPEAR',
  ],
  98 => 
  [
    'id' => 98,
    'type' => 'weapon',
    'name' => 'Halberd',
    'add_name' => '',
    'description' => 'Bestows one of the following functions: Haste, Critical Stun or Wide Blow.',
    'icon' => 'weapon_halbard_i00',
    'weapon_type' => 'pole',
    'bodypart' => 'lrhand',
    'crystal_count' => 1128,
    'crystal_type' => 'a',
    'weight' => 1900,
    'price' => 14098000,
    'soulshots' => 1,
    'spiritshots' => 1,
    'enchant_enabled' => true,
    'commissionItemType' => 'SPEAR',
  ],
  99 => 
  [
    'id' => 99,
    'type' => 'weapon',
    'name' => 'Apprentice\'s Spellbook',
    'add_name' => '',
    'description' => '',
    'icon' => 'weapon_apprentices_spellbook_i00',
    'weapon_type' => 'sword',
    'bodypart' => 'rhand',
    'weight' => 650,
    'price' => 12500,
    'soulshots' => 1,
    'spiritshots' => 1,
    'commissionItemType' => 'OTHER_WEAPON',
    'is_magic_weapon' => true,
  ],
];