<?php
return [
  100 => 
  [
    'id' => 100,
    'type' => 'weapon',
    'name' => 'Voodoo Doll',
    'add_name' => '',
    'description' => '',
    'icon' => 'weapon_voodoo_doll_i00',
    'weapon_type' => 'sword',
    'bodypart' => 'rhand',
    'weight' => 630,
    'price' => 244000,
    'soulshots' => 1,
    'spiritshots' => 1,
    'commissionItemType' => 'OTHER_WEAPON',
    'is_magic_weapon' => true,
  ],
  101 => 
  [
    'id' => 101,
    'type' => 'weapon',
    'name' => 'Scroll of Wisdom',
    'add_name' => '',
    'description' => '',
    'icon' => 'weapon_scroll_of_wisdom_i00',
    'weapon_type' => 'sword',
    'bodypart' => 'rhand',
    'crystal_count' => 743,
    'crystal_type' => 'd',
    'weight' => 610,
    'price' => 409000,
    'soulshots' => 1,
    'spiritshots' => 1,
    'enchant_enabled' => true,
    'commissionItemType' => 'OTHER_WEAPON',
    'is_magic_weapon' => true,
  ],
  102 => 
  [
    'id' => 102,
    'type' => 'armor',
    'name' => 'Round Shield',
    'add_name' => '',
    'description' => '',
    'icon' => 'shield_round_shield_i00',
    'bodypart' => 'lhand',
    'weight' => 1390,
    'commissionItemType' => 'SHIELD',
    'price' => 7110,
  ],
  103 => 
  [
    'id' => 103,
    'type' => 'armor',
    'name' => 'Tower Shield',
    'add_name' => '',
    'description' => '',
    'icon' => 'shield_tower_shield_i00',
    'bodypart' => 'lhand',
    'crystal_count' => 103,
    'crystal_type' => 'c',
    'weight' => 1240,
    'price' => 258000,
    'commissionItemType' => 'SHIELD',
    'enchant_enabled' => true,
  ],
  107 => 
  [
    'id' => 107,
    'type' => 'armor',
    'name' => 'Compound Shield',
    'add_name' => '',
    'description' => '',
    'icon' => 'shield_composite_shield_i00',
    'bodypart' => 'lhand',
    'crystal_count' => 103,
    'crystal_type' => 'c',
    'weight' => 1230,
    'price' => 258000,
    'commissionItemType' => 'SHIELD',
    'enchant_enabled' => true,
  ],
  108 => 
  [
    'id' => 108,
    'type' => 'armor',
    'name' => 'Masterpiece Shield',
    'add_name' => '',
    'description' => '',
    'icon' => 'etc_ertheia2',
    'bodypart' => 'lhand',
    'crystal_count' => 103,
    'crystal_type' => 'b',
    'weight' => 5600,
    'price' => 845000,
    'commissionItemType' => 'SHIELD',
  ],
  110 => 
  [
    'id' => 110,
    'type' => 'armor',
    'name' => 'Doom Shield',
    'add_name' => '',
    'description' => '',
    'icon' => 'shield_doom_shield_i00',
    'bodypart' => 'lhand',
    'crystal_count' => 112,
    'crystal_type' => 'b',
    'weight' => 1200,
    'price' => 845000,
    'commissionItemType' => 'SHIELD',
    'enchant_enabled' => true,
  ],
  112 => 
  [
    'id' => 112,
    'type' => 'armor',
    'name' => 'Apprentice\'s Earring',
    'add_name' => '',
    'description' => '',
    'icon' => 'accessary_apprentices_earing_i00',
    'bodypart' => 'rear;lear',
    'weight' => 150,
    'commissionItemType' => 'EARRING',
    'price' => 49,
  ],
  113 => 
  [
    'id' => 113,
    'type' => 'armor',
    'name' => 'Mage Earring',
    'add_name' => '',
    'description' => '',
    'icon' => 'accessary_mage_earing_i00',
    'bodypart' => 'rear;lear',
    'weight' => 150,
    'commissionItemType' => 'EARRING',
    'price' => 811,
  ],
  114 => 
  [
    'id' => 114,
    'type' => 'armor',
    'name' => 'Earring of Strength',
    'add_name' => '',
    'description' => '',
    'icon' => 'accessary_earing_of_strength_i00',
    'bodypart' => 'rear;lear',
    'weight' => 150,
    'commissionItemType' => 'EARRING',
    'price' => 3510,
  ],
  115 => 
  [
    'id' => 115,
    'type' => 'armor',
    'name' => 'Earring of Wisdom',
    'add_name' => '',
    'description' => '',
    'icon' => 'accessary_earing_of_wisdom_i00',
    'bodypart' => 'rear;lear',
    'weight' => 150,
    'commissionItemType' => 'EARRING',
    'price' => 3510,
  ],
  116 => 
  [
    'id' => 116,
    'type' => 'armor',
    'name' => 'Magic Ring',
    'add_name' => '',
    'description' => '',
    'icon' => 'accessary_magic_ring_i00',
    'bodypart' => 'rfinger;lfinger',
    'weight' => 150,
    'commissionItemType' => 'RING',
    'price' => 33,
  ],
  117 => 
  [
    'id' => 117,
    'type' => 'armor',
    'name' => 'Corroded Ring of Mana',
    'add_name' => '',
    'description' => '',
    'icon' => 'etc_ertheia2',
    'bodypart' => 'rfinger;lfinger',
    'crystal_count' => 112,
    'crystal_type' => 'b',
    'weight' => 150,
    'price' => 404000,
    'commissionItemType' => 'RING',
  ],
  118 => 
  [
    'id' => 118,
    'type' => 'armor',
    'name' => 'Magic Necklace',
    'add_name' => '',
    'description' => '',
    'icon' => 'accessary_necklace_of_magic_i00',
    'bodypart' => 'neck',
    'weight' => 150,
    'commissionItemType' => 'NECKLACE',
    'price' => 66,
  ],
  119 => 
  [
    'id' => 119,
    'type' => 'armor',
    'name' => 'Necklace of Seal',
    'add_name' => '',
    'description' => '',
    'icon' => 'accessary_necklace_of_binding_i00',
    'bodypart' => 'neck',
    'crystal_count' => 226,
    'crystal_type' => 'c',
    'weight' => 150,
    'price' => 565000,
    'commissionItemType' => 'NECKLACE',
    'enchant_enabled' => true,
  ],
  120 => 
  [
    'id' => 120,
    'type' => 'weapon',
    'name' => 'Sword of Reflection',
    'add_name' => '',
    'description' => '',
    'icon' => 'weapon_sword_of_watershadow_i00',
    'weapon_type' => 'sword',
    'bodypart' => 'rhand',
    'weight' => 1550,
    'price' => 136000,
    'soulshots' => 1,
    'spiritshots' => 1,
    'commissionItemType' => 'ONE_HAND_SWORD',
  ],
  121 => 
  [
    'id' => 121,
    'type' => 'weapon',
    'name' => 'Sword of Watershadow',
    'add_name' => '',
    'description' => '',
    'icon' => 'weapon_sword_of_watershadow_i00',
    'weapon_type' => 'sword',
    'bodypart' => 'rhand',
    'weight' => 1540,
    'price' => 136000,
    'soulshots' => 1,
    'spiritshots' => 1,
    'commissionItemType' => 'ONE_HAND_SWORD',
  ],
  122 => 
  [
    'id' => 122,
    'type' => 'weapon',
    'name' => 'Handmade Sword',
    'add_name' => '',
    'description' => '',
    'icon' => 'weapon_handmade_sword_i00',
    'weapon_type' => 'sword',
    'bodypart' => 'rhand',
    'weight' => 1570,
    'price' => 54100,
    'soulshots' => 1,
    'spiritshots' => 1,
    'commissionItemType' => 'ONE_HAND_SWORD',
  ],
  123 => 
  [
    'id' => 123,
    'type' => 'weapon',
    'name' => 'Saber',
    'add_name' => '',
    'description' => '',
    'icon' => 'weapon_saber_i00',
    'weapon_type' => 'sword',
    'bodypart' => 'rhand',
    'crystal_count' => 743,
    'crystal_type' => 'd',
    'weight' => 1520,
    'price' => 409000,
    'change_weaponId' => 9209,
    'soulshots' => 1,
    'spiritshots' => 1,
    'commissionItemType' => 'ONE_HAND_SWORD',
    'enchant_enabled' => true,
  ],
  124 => 
  [
    'id' => 124,
    'type' => 'weapon',
    'name' => 'Two-handed Sword',
    'add_name' => '',
    'description' => '',
    'icon' => 'weapon_two_handed_sword_i00',
    'weapon_type' => 'sword',
    'bodypart' => 'lrhand',
    'crystal_count' => 1758,
    'crystal_type' => 'd',
    'weight' => 2180,
    'price' => 967000,
    'change_weaponId' => 9220,
    'soulshots' => 1,
    'spiritshots' => 1,
    'commissionItemType' => 'TWO_HAND_SWORD',
    'enchant_enabled' => true,
  ],
  125 => 
  [
    'id' => 125,
    'type' => 'weapon',
    'name' => 'Spinebone Sword',
    'add_name' => '',
    'description' => '',
    'icon' => 'weapon_spinebone_sword_i00',
    'weapon_type' => 'sword',
    'bodypart' => 'rhand',
    'crystal_count' => 1170,
    'crystal_type' => 'd',
    'weight' => 1510,
    'price' => 644000,
    'change_weaponId' => 9214,
    'soulshots' => 1,
    'spiritshots' => 1,
    'commissionItemType' => 'ONE_HAND_SWORD',
    'enchant_enabled' => true,
  ],
  126 => 
  [
    'id' => 126,
    'type' => 'weapon',
    'name' => 'Artisan\'s Sword',
    'add_name' => '',
    'description' => '',
    'icon' => 'weapon_artisans_sword_i00',
    'weapon_type' => 'sword',
    'bodypart' => 'rhand',
    'crystal_count' => 1170,
    'crystal_type' => 'd',
    'weight' => 1500,
    'price' => 644000,
    'change_weaponId' => 9215,
    'soulshots' => 1,
    'spiritshots' => 1,
    'commissionItemType' => 'ONE_HAND_SWORD',
    'enchant_enabled' => true,
  ],
  127 => 
  [
    'id' => 127,
    'type' => 'weapon',
    'name' => 'Crimson Sword',
    'add_name' => '',
    'description' => '',
    'icon' => 'weapon_crimson_sword_i00',
    'weapon_type' => 'sword',
    'bodypart' => 'rhand',
    'crystal_count' => 1758,
    'crystal_type' => 'd',
    'weight' => 1490,
    'price' => 967000,
    'change_weaponId' => 9218,
    'soulshots' => 1,
    'spiritshots' => 1,
    'commissionItemType' => 'ONE_HAND_SWORD',
    'enchant_enabled' => true,
  ],
  128 => 
  [
    'id' => 128,
    'type' => 'weapon',
    'name' => 'Knight\'s Sword',
    'add_name' => '',
    'description' => '',
    'icon' => 'weapon_knights_sword_i00',
    'weapon_type' => 'sword',
    'bodypart' => 'rhand',
    'crystal_count' => 1170,
    'crystal_type' => 'd',
    'weight' => 1500,
    'price' => 644000,
    'change_weaponId' => 10003,
    'soulshots' => 1,
    'spiritshots' => 1,
    'commissionItemType' => 'ONE_HAND_SWORD',
    'enchant_enabled' => true,
  ],
  129 => 
  [
    'id' => 129,
    'type' => 'weapon',
    'name' => 'Sword of Revolution',
    'add_name' => '',
    'description' => '',
    'icon' => 'weapon_sword_of_revolution_i00',
    'weapon_type' => 'sword',
    'bodypart' => 'rhand',
    'crystal_count' => 2545,
    'crystal_type' => 'd',
    'weight' => 1450,
    'price' => 1400000,
    'change_weaponId' => 9222,
    'soulshots' => 1,
    'spiritshots' => 1,
    'commissionItemType' => 'ONE_HAND_SWORD',
    'enchant_enabled' => true,
  ],
  130 => 
  [
    'id' => 130,
    'type' => 'weapon',
    'name' => 'Elven Sword',
    'add_name' => '',
    'description' => '',
    'icon' => 'weapon_elven_sword_i00',
    'weapon_type' => 'sword',
    'bodypart' => 'rhand',
    'crystal_count' => 1758,
    'crystal_type' => 'd',
    'weight' => 1470,
    'price' => 967000,
    'change_weaponId' => 9219,
    'soulshots' => 1,
    'spiritshots' => 1,
    'commissionItemType' => 'ONE_HAND_SWORD',
    'enchant_enabled' => true,
  ],
  131 => 
  [
    'id' => 131,
    'type' => 'weapon',
    'name' => 'Spirit Sword',
    'add_name' => '',
    'description' => 'Bestows either Critical Damage, Critical Poison or Haste',
    'icon' => 'weapon_spirits_sword_i00',
    'weapon_type' => 'sword',
    'bodypart' => 'rhand',
    'crystal_count' => 1148,
    'crystal_type' => 'c',
    'weight' => 1420,
    'price' => 2870000,
    'change_weaponId' => 9248,
    'soulshots' => 1,
    'spiritshots' => 1,
    'commissionItemType' => 'ONE_HAND_SWORD',
    'enchant_enabled' => true,
  ],
  132 => 
  [
    'id' => 132,
    'type' => 'weapon',
    'name' => 'Ultimate Sword',
    'add_name' => '',
    'description' => 'Bestows one of the following functions: Guidance, Critical Drain, or Health.',
    'icon' => 'weapon_sword_of_limit_i00',
    'weapon_type' => 'sword',
    'bodypart' => 'rhand',
    'crystal_count' => 1720,
    'crystal_type' => 'c',
    'weight' => 1400,
    'price' => 4300000,
    'change_weaponId' => 9280,
    'soulshots' => 1,
    'spiritshots' => 1,
    'commissionItemType' => 'ONE_HAND_SWORD',
    'enchant_enabled' => true,
  ],
  133 => 
  [
    'id' => 133,
    'type' => 'weapon',
    'name' => 'Raid Sword',
    'add_name' => '',
    'description' => 'Bestows either Focus, Critical Drain or Critical Poison',
    'icon' => 'weapon_raid_sword_i00',
    'weapon_type' => 'sword',
    'bodypart' => 'rhand',
    'crystal_count' => 1148,
    'crystal_type' => 'c',
    'weight' => 1420,
    'price' => 2870000,
    'change_weaponId' => 9252,
    'soulshots' => 1,
    'spiritshots' => 1,
    'commissionItemType' => 'ONE_HAND_SWORD',
    'enchant_enabled' => true,
  ],
  134 => 
  [
    'id' => 134,
    'type' => 'weapon',
    'name' => 'Sword of Nightmare',
    'add_name' => '',
    'description' => 'Bestows one of the following functions: Health, Focus, or Light.',
    'icon' => 'weapon_sword_of_nightmare_i00',
    'weapon_type' => 'sword',
    'bodypart' => 'rhand',
    'crystal_count' => 1720,
    'crystal_type' => 'c',
    'weight' => 1400,
    'price' => 4300000,
    'change_weaponId' => 9276,
    'soulshots' => 1,
    'spiritshots' => 1,
    'commissionItemType' => 'ONE_HAND_SWORD',
    'enchant_enabled' => true,
  ],
  135 => 
  [
    'id' => 135,
    'type' => 'weapon',
    'name' => 'Samurai Long Sword',
    'add_name' => '',
    'description' => 'Bestows one of the following functions: Focus, Critical Damage or Haste.',
    'icon' => 'weapon_samurai_old_longsword_i00',
    'weapon_type' => 'sword',
    'bodypart' => 'rhand',
    'crystal_count' => 2452,
    'crystal_type' => 'c',
    'weight' => 1380,
    'price' => 6130000,
    'change_weaponId' => 9292,
    'soulshots' => 1,
    'spiritshots' => 1,
    'enchant_enabled' => true,
    'commissionItemType' => 'ONE_HAND_SWORD',
  ],
  142 => 
  [
    'id' => 142,
    'type' => 'weapon',
    'name' => 'Keshanberk',
    'add_name' => '',
    'description' => 'Bestows one of the following functions: Guidance, Focus or Back Blow',
    'icon' => 'weapon_kshanberk_i00',
    'weapon_type' => 'sword',
    'bodypart' => 'rhand',
    'crystal_count' => 1157,
    'crystal_type' => 'b',
    'weight' => 1370,
    'price' => 8680000,
    'change_weaponId' => 9304,
    'soulshots' => 1,
    'spiritshots' => 1,
    'commissionItemType' => 'ONE_HAND_SWORD',
    'enchant_enabled' => true,
  ],
  143 => 
  [
    'id' => 143,
    'type' => 'weapon',
    'name' => 'Sword of Mystic',
    'add_name' => '',
    'description' => '',
    'icon' => 'weapon_sword_of_mystic_i00',
    'weapon_type' => 'sword',
    'bodypart' => 'rhand',
    'crystal_count' => 1301,
    'crystal_type' => 'd',
    'weight' => 980,
    'price' => 716000,
    'soulshots' => 1,
    'spiritshots' => 1,
    'enchant_enabled' => true,
    'commissionItemType' => 'ONE_HAND_MAGIC_SWORD',
    'is_magic_weapon' => true,
  ],
  144 => 
  [
    'id' => 144,
    'type' => 'weapon',
    'name' => 'Sword of Occult',
    'add_name' => '',
    'description' => '',
    'icon' => 'weapon_sword_of_occult_i00',
    'weapon_type' => 'sword',
    'bodypart' => 'rhand',
    'crystal_count' => 1301,
    'crystal_type' => 'd',
    'weight' => 970,
    'price' => 716000,
    'soulshots' => 1,
    'spiritshots' => 1,
    'enchant_enabled' => true,
    'commissionItemType' => 'ONE_HAND_MAGIC_SWORD',
    'is_magic_weapon' => true,
  ],
  145 => 
  [
    'id' => 145,
    'type' => 'weapon',
    'name' => 'Sword of Whispering Death',
    'add_name' => '',
    'description' => 'Bestows one of the following functions: Empower, Magic Power or Magic Silence.',
    'icon' => 'weapon_deathbreath_sword_i00',
    'weapon_type' => 'sword',
    'bodypart' => 'rhand',
    'crystal_count' => 1720,
    'crystal_type' => 'c',
    'weight' => 920,
    'price' => 4300000,
    'soulshots' => 1,
    'spiritshots' => 1,
    'enchant_enabled' => true,
    'commissionItemType' => 'ONE_HAND_MAGIC_SWORD',
    'is_magic_weapon' => true,
  ],
  146 => 
  [
    'id' => 146,
    'type' => 'weapon',
    'name' => 'Ghoulbane',
    'add_name' => '',
    'description' => '',
    'icon' => 'etc_ertheia2',
    'weapon_type' => 'sword',
    'bodypart' => 'rhand',
    'crystal_count' => 1720,
    'crystal_type' => 'b',
    'weight' => 910,
    'price' => 8680000,
    'soulshots' => 1,
    'spiritshots' => 1,
    'commissionItemType' => 'ONE_HAND_MAGIC_SWORD',
    'is_magic_weapon' => true,
  ],
  148 => 
  [
    'id' => 148,
    'type' => 'weapon',
    'name' => 'Sword of Valhalla',
    'add_name' => '',
    'description' => 'Bestows one of the following functions: Acumen, Magic Weakness or Magic Regeneration.',
    'icon' => 'weapon_sword_of_valhalla_i00',
    'weapon_type' => 'sword',
    'bodypart' => 'rhand',
    'crystal_count' => 1157,
    'crystal_type' => 'b',
    'weight' => 900,
    'price' => 8680000,
    'soulshots' => 1,
    'spiritshots' => 1,
    'enchant_enabled' => true,
    'is_magic_weapon' => true,
    'commissionItemType' => 'ONE_HAND_MAGIC_SWORD',
  ],
  150 => 
  [
    'id' => 150,
    'type' => 'weapon',
    'name' => 'Elemental Sword',
    'add_name' => '',
    'description' => 'Bestows one of the following functions: Magic Power, Magic Paralyze or Empower.',
    'icon' => 'weapon_elemental_sword_i00',
    'weapon_type' => 'sword',
    'bodypart' => 'rhand',
    'crystal_count' => 1128,
    'crystal_type' => 'a',
    'weight' => 830,
    'price' => 14098000,
    'soulshots' => 1,
    'spiritshots' => 1,
    'enchant_enabled' => true,
    'commissionItemType' => 'ONE_HAND_MAGIC_SWORD',
    'is_magic_weapon' => true,
  ],
  151 => 
  [
    'id' => 151,
    'type' => 'weapon',
    'name' => 'Sword of Miracles',
    'add_name' => '',
    'description' => 'Bestows one of the following functions: Magic Power, Magic Silence or Acumen.',
    'icon' => 'weapon_sword_of_miracle_i00',
    'weapon_type' => 'sword',
    'bodypart' => 'rhand',
    'crystal_count' => 1659,
    'crystal_type' => 'a',
    'weight' => 840,
    'price' => 20741000,
    'soulshots' => 1,
    'spiritshots' => 1,
    'enchant_enabled' => true,
    'is_magic_weapon' => true,
    'commissionItemType' => 'ONE_HAND_MAGIC_SWORD',
  ],
  152 => 
  [
    'id' => 152,
    'type' => 'weapon',
    'name' => 'Heavy Chisel',
    'add_name' => '',
    'description' => '',
    'icon' => 'weapon_heavy_chisel_i00',
    'weapon_type' => 'blunt',
    'bodypart' => 'rhand',
    'weight' => 1890,
    'price' => 8070,
    'soulshots' => 1,
    'spiritshots' => 1,
    'commissionItemType' => 'BLUNT_WEAPON',
  ],
  153 => 
  [
    'id' => 153,
    'type' => 'weapon',
    'name' => 'Sickle',
    'add_name' => '',
    'description' => '',
    'icon' => 'weapon_sickle_i00',
    'weapon_type' => 'blunt',
    'bodypart' => 'rhand',
    'weight' => 1850,
    'price' => 18500,
    'soulshots' => 1,
    'spiritshots' => 1,
    'commissionItemType' => 'BLUNT_WEAPON',
  ],
  154 => 
  [
    'id' => 154,
    'type' => 'weapon',
    'name' => 'Dwarven Mace',
    'add_name' => '',
    'description' => '',
    'icon' => 'weapon_dwarven_mace_i00',
    'weapon_type' => 'blunt',
    'bodypart' => 'rhand',
    'weight' => 1860,
    'price' => 54100,
    'soulshots' => 1,
    'spiritshots' => 1,
    'commissionItemType' => 'BLUNT_WEAPON',
  ],
  155 => 
  [
    'id' => 155,
    'type' => 'weapon',
    'name' => 'Flanged Mace',
    'add_name' => '',
    'description' => '',
    'icon' => 'weapon_buzdygan_i00',
    'weapon_type' => 'blunt',
    'bodypart' => 'rhand',
    'weight' => 1800,
    'price' => 244000,
    'soulshots' => 1,
    'spiritshots' => 1,
    'commissionItemType' => 'BLUNT_WEAPON',
  ],
  156 => 
  [
    'id' => 156,
    'type' => 'weapon',
    'name' => 'Hand Axe',
    'add_name' => '',
    'description' => '',
    'icon' => 'weapon_hand_axe_i00',
    'weapon_type' => 'blunt',
    'bodypart' => 'rhand',
    'crystal_count' => 743,
    'crystal_type' => 'd',
    'weight' => 1820,
    'price' => 409000,
    'soulshots' => 1,
    'spiritshots' => 1,
    'commissionItemType' => 'BLUNT_WEAPON',
    'enchant_enabled' => true,
  ],
  157 => 
  [
    'id' => 157,
    'type' => 'weapon',
    'name' => 'Spiked Club',
    'add_name' => '',
    'description' => '',
    'icon' => 'weapon_spike_club_i00',
    'weapon_type' => 'blunt',
    'bodypart' => 'rhand',
    'crystal_count' => 1758,
    'crystal_type' => 'd',
    'weight' => 1750,
    'price' => 967000,
    'soulshots' => 1,
    'spiritshots' => 1,
    'commissionItemType' => 'BLUNT_WEAPON',
    'enchant_enabled' => true,
  ],
  158 => 
  [
    'id' => 158,
    'type' => 'weapon',
    'name' => 'Tarbar',
    'add_name' => '',
    'description' => '',
    'icon' => 'weapon_tarbar_i00',
    'weapon_type' => 'blunt',
    'bodypart' => 'rhand',
    'crystal_count' => 2545,
    'crystal_type' => 'd',
    'weight' => 1730,
    'price' => 1400000,
    'soulshots' => 1,
    'spiritshots' => 1,
    'commissionItemType' => 'BLUNT_WEAPON',
    'enchant_enabled' => true,
  ],
  159 => 
  [
    'id' => 159,
    'type' => 'weapon',
    'name' => 'Bonebreaker',
    'add_name' => '',
    'description' => '',
    'icon' => 'weapon_bonebreaker_i00',
    'weapon_type' => 'blunt',
    'bodypart' => 'rhand',
    'crystal_count' => 3272,
    'crystal_type' => 'd',
    'weight' => 1720,
    'price' => 1800000,
    'soulshots' => 1,
    'spiritshots' => 1,
    'commissionItemType' => 'BLUNT_WEAPON',
    'enchant_enabled' => true,
  ],
  160 => 
  [
    'id' => 160,
    'type' => 'weapon',
    'name' => 'Battle Axe',
    'add_name' => '',
    'description' => 'Bestows either Anger, Rsk. Focus or Haste.',
    'icon' => 'weapon_battle_axe_i00',
    'weapon_type' => 'blunt',
    'bodypart' => 'rhand',
    'crystal_count' => 916,
    'crystal_type' => 'c',
    'weight' => 1720,
    'price' => 2290000,
    'soulshots' => 1,
    'spiritshots' => 1,
    'enchant_enabled' => true,
    'commissionItemType' => 'BLUNT_WEAPON',
  ],
  161 => 
  [
    'id' => 161,
    'type' => 'weapon',
    'name' => 'Silver Axe',
    'add_name' => '',
    'description' => 'Bestows either Anger, Rsk. Focus or Haste.',
    'icon' => 'weapon_war_pick_i00',
    'weapon_type' => 'blunt',
    'bodypart' => 'rhand',
    'crystal_count' => 916,
    'crystal_type' => 'c',
    'weight' => 1690,
    'price' => 2290000,
    'soulshots' => 1,
    'spiritshots' => 1,
    'commissionItemType' => 'BLUNT_WEAPON',
    'enchant_enabled' => true,
  ],
  162 => 
  [
    'id' => 162,
    'type' => 'weapon',
    'name' => 'War Axe',
    'add_name' => '',
    'description' => 'Bestows either Anger, Health or Haste.',
    'icon' => 'weapon_war_axe_i00',
    'weapon_type' => 'blunt',
    'bodypart' => 'rhand',
    'crystal_count' => 1720,
    'crystal_type' => 'c',
    'weight' => 1660,
    'price' => 4300000,
    'soulshots' => 1,
    'spiritshots' => 1,
    'commissionItemType' => 'BLUNT_WEAPON',
    'enchant_enabled' => true,
  ],
  164 => 
  [
    'id' => 164,
    'type' => 'weapon',
    'name' => 'Elysian',
    'add_name' => '',
    'description' => 'Bestows one of the following functions: Health, Anger, or a Critical Drain.',
    'icon' => 'weapon_elysian_i00',
    'weapon_type' => 'blunt',
    'bodypart' => 'rhand',
    'crystal_count' => 1659,
    'crystal_type' => 'a',
    'weight' => 1580,
    'price' => 20741000,
    'soulshots' => 1,
    'spiritshots' => 1,
    'enchant_enabled' => true,
    'commissionItemType' => 'BLUNT_WEAPON',
  ],
  166 => 
  [
    'id' => 166,
    'type' => 'weapon',
    'name' => 'Heavy Mace',
    'add_name' => '',
    'description' => '',
    'icon' => 'weapon_heavy_mace_i00',
    'weapon_type' => 'blunt',
    'bodypart' => 'rhand',
    'crystal_count' => 743,
    'crystal_type' => 'd',
    'weight' => 1800,
    'price' => 409000,
    'soulshots' => 1,
    'spiritshots' => 1,
    'commissionItemType' => 'BLUNT_WEAPON',
    'enchant_enabled' => true,
  ],
  167 => 
  [
    'id' => 167,
    'type' => 'weapon',
    'name' => 'Scalpel',
    'add_name' => '',
    'description' => '',
    'icon' => 'weapon_scalpel_i00',
    'weapon_type' => 'blunt',
    'bodypart' => 'rhand',
    'crystal_count' => 743,
    'crystal_type' => 'd',
    'weight' => 1810,
    'price' => 409000,
    'soulshots' => 1,
    'spiritshots' => 1,
    'commissionItemType' => 'BLUNT_WEAPON',
    'enchant_enabled' => true,
  ],
  168 => 
  [
    'id' => 168,
    'type' => 'weapon',
    'name' => 'Work Hammer',
    'add_name' => '',
    'description' => '',
    'icon' => 'weapon_work_hammer_i00',
    'weapon_type' => 'blunt',
    'bodypart' => 'rhand',
    'crystal_count' => 743,
    'crystal_type' => 'd',
    'weight' => 1790,
    'price' => 409000,
    'soulshots' => 1,
    'spiritshots' => 1,
    'commissionItemType' => 'BLUNT_WEAPON',
    'enchant_enabled' => true,
  ],
  169 => 
  [
    'id' => 169,
    'type' => 'weapon',
    'name' => 'Skull Breaker',
    'add_name' => '',
    'description' => '',
    'icon' => 'weapon_skull_breaker_i00',
    'weapon_type' => 'blunt',
    'bodypart' => 'rhand',
    'crystal_count' => 2545,
    'crystal_type' => 'd',
    'weight' => 1740,
    'price' => 1400000,
    'soulshots' => 1,
    'spiritshots' => 1,
    'commissionItemType' => 'BLUNT_WEAPON',
    'enchant_enabled' => true,
  ],
  171 => 
  [
    'id' => 171,
    'type' => 'weapon',
    'name' => 'Deadman\'s Glory',
    'add_name' => '',
    'description' => 'Bestows one of the following functions: Anger, Health or Haste.',
    'icon' => 'weapon_deadmans_glory_i00',
    'weapon_type' => 'blunt',
    'bodypart' => 'rhand',
    'crystal_count' => 1746,
    'crystal_type' => 'b',
    'weight' => 1600,
    'price' => 13100000,
    'soulshots' => 1,
    'spiritshots' => 1,
    'enchant_enabled' => true,
    'commissionItemType' => 'BLUNT_WEAPON',
  ],
  172 => 
  [
    'id' => 172,
    'type' => 'weapon',
    'name' => 'Heavy Bone Club',
    'add_name' => '',
    'description' => '',
    'icon' => 'weapon_heavy_bone_club_i00',
    'weapon_type' => 'blunt',
    'bodypart' => 'rhand',
    'crystal_count' => 2545,
    'crystal_type' => 'd',
    'weight' => 1730,
    'price' => 1400000,
    'soulshots' => 1,
    'spiritshots' => 1,
    'commissionItemType' => 'BLUNT_WEAPON',
    'enchant_enabled' => true,
  ],
  173 => 
  [
    'id' => 173,
    'type' => 'weapon',
    'name' => 'Skull Graver',
    'add_name' => '',
    'description' => 'Bestows one of the following functions: Anger, Health, or Rsk. Focus.',
    'icon' => 'weapon_skull_graver_i00',
    'weapon_type' => 'blunt',
    'bodypart' => 'rhand',
    'crystal_count' => 916,
    'crystal_type' => 'c',
    'weight' => 1640,
    'price' => 2290000,
    'soulshots' => 1,
    'spiritshots' => 1,
    'enchant_enabled' => true,
    'commissionItemType' => 'BLUNT_WEAPON',
  ],
  174 => 
  [
    'id' => 174,
    'type' => 'weapon',
    'name' => 'Nirvana Axe',
    'add_name' => '',
    'description' => 'Bestows one of the following functions: Magic Poison, Magic Power or Magic Weakness.',
    'icon' => 'weapon_nirvana_axe_i00',
    'weapon_type' => 'blunt',
    'bodypart' => 'rhand',
    'crystal_count' => 1720,
    'crystal_type' => 'c',
    'weight' => 1150,
    'price' => 4300000,
    'soulshots' => 1,
    'spiritshots' => 1,
    'enchant_enabled' => true,
    'commissionItemType' => 'ONE_HAND_MAGIC_BLUNT_WEAPON',
    'is_magic_weapon' => true,
  ],
  175 => 
  [
    'id' => 175,
    'type' => 'weapon',
    'name' => 'Art of Battle Axe',
    'add_name' => '',
    'description' => 'Bestows either Health, Rsk. Focus or Haste.',
    'icon' => 'weapon_art_of_battle_axe_i00',
    'weapon_type' => 'blunt',
    'bodypart' => 'rhand',
    'crystal_count' => 1746,
    'crystal_type' => 'b',
    'weight' => 1570,
    'price' => 13100000,
    'soulshots' => 1,
    'spiritshots' => 1,
    'enchant_enabled' => true,
    'commissionItemType' => 'BLUNT_WEAPON',
  ],
  176 => 
  [
    'id' => 176,
    'type' => 'weapon',
    'name' => 'Apprentice\'s Staff',
    'add_name' => '',
    'description' => '',
    'icon' => 'weapon_apprentices_staff_i00',
    'weapon_type' => 'blunt',
    'bodypart' => 'lrhand',
    'weight' => 1070,
    'price' => 136000,
    'soulshots' => 1,
    'spiritshots' => 1,
    'commissionItemType' => 'TWO_HAND_MAGIC_BLUNT_WEAPON',
    'is_magic_weapon' => true,
  ],
  177 => 
  [
    'id' => 177,
    'type' => 'weapon',
    'name' => 'Mage Staff',
    'add_name' => '',
    'description' => '',
    'icon' => 'weapon_apprentices_staff_i00',
    'weapon_type' => 'blunt',
    'bodypart' => 'lrhand',
    'weight' => 1050,
    'price' => 244000,
    'soulshots' => 1,
    'spiritshots' => 1,
    'commissionItemType' => 'TWO_HAND_MAGIC_BLUNT_WEAPON',
    'is_magic_weapon' => true,
  ],
  178 => 
  [
    'id' => 178,
    'type' => 'weapon',
    'name' => 'Bone Staff',
    'add_name' => '',
    'description' => '',
    'icon' => 'weapon_apprentices_staff_i00',
    'weapon_type' => 'blunt',
    'bodypart' => 'lrhand',
    'crystal_count' => 743,
    'crystal_type' => 'd',
    'weight' => 1060,
    'price' => 409000,
    'soulshots' => 1,
    'spiritshots' => 1,
    'enchant_enabled' => true,
    'commissionItemType' => 'TWO_HAND_MAGIC_BLUNT_WEAPON',
    'is_magic_weapon' => true,
  ],
  179 => 
  [
    'id' => 179,
    'type' => 'weapon',
    'name' => 'Mace of Prayer',
    'add_name' => '',
    'description' => '',
    'icon' => 'weapon_mace_of_prayer_i00',
    'weapon_type' => 'blunt',
    'bodypart' => 'rhand',
    'crystal_count' => 1170,
    'crystal_type' => 'd',
    'weight' => 1300,
    'price' => 644000,
    'soulshots' => 1,
    'spiritshots' => 1,
    'enchant_enabled' => true,
    'commissionItemType' => 'ONE_HAND_MAGIC_BLUNT_WEAPON',
    'is_magic_weapon' => true,
  ],
  180 => 
  [
    'id' => 180,
    'type' => 'weapon',
    'name' => 'Mace of Judgment',
    'add_name' => '',
    'description' => '',
    'icon' => 'weapon_mace_of_judgment_i00',
    'weapon_type' => 'blunt',
    'bodypart' => 'rhand',
    'crystal_count' => 1170,
    'crystal_type' => 'd',
    'weight' => 1280,
    'price' => 644000,
    'soulshots' => 1,
    'spiritshots' => 1,
    'enchant_enabled' => true,
    'commissionItemType' => 'ONE_HAND_MAGIC_BLUNT_WEAPON',
    'is_magic_weapon' => true,
  ],
  181 => 
  [
    'id' => 181,
    'type' => 'weapon',
    'name' => 'Mace of Miracle',
    'add_name' => '',
    'description' => '',
    'icon' => 'weapon_mace_of_miracle_i00',
    'weapon_type' => 'blunt',
    'bodypart' => 'rhand',
    'crystal_count' => 1170,
    'crystal_type' => 'd',
    'weight' => 1250,
    'price' => 644000,
    'soulshots' => 1,
    'spiritshots' => 1,
    'enchant_enabled' => true,
    'commissionItemType' => 'ONE_HAND_MAGIC_BLUNT_WEAPON',
    'is_magic_weapon' => true,
  ],
  182 => 
  [
    'id' => 182,
    'type' => 'weapon',
    'name' => 'Doom Hammer',
    'add_name' => '',
    'description' => '',
    'icon' => 'weapon_doom_hammer_i00',
    'weapon_type' => 'blunt',
    'bodypart' => 'rhand',
    'crystal_count' => 1170,
    'crystal_type' => 'd',
    'weight' => 1200,
    'price' => 644000,
    'soulshots' => 1,
    'spiritshots' => 1,
    'enchant_enabled' => true,
    'commissionItemType' => 'ONE_HAND_MAGIC_BLUNT_WEAPON',
    'is_magic_weapon' => true,
  ],
  183 => 
  [
    'id' => 183,
    'type' => 'weapon',
    'name' => 'Mystic Staff',
    'add_name' => '',
    'description' => '',
    'icon' => 'weapon_mystic_staff_i00',
    'weapon_type' => 'blunt',
    'bodypart' => 'lrhand',
    'crystal_count' => 1170,
    'crystal_type' => 'd',
    'weight' => 1040,
    'price' => 644000,
    'soulshots' => 1,
    'spiritshots' => 1,
    'enchant_enabled' => true,
    'commissionItemType' => 'TWO_HAND_MAGIC_BLUNT_WEAPON',
    'is_magic_weapon' => true,
  ],
  184 => 
  [
    'id' => 184,
    'type' => 'weapon',
    'name' => 'Conjuror\'s Staff',
    'add_name' => '',
    'description' => '',
    'icon' => 'weapon_conjure_staff_i00',
    'weapon_type' => 'blunt',
    'bodypart' => 'lrhand',
    'crystal_count' => 1170,
    'crystal_type' => 'd',
    'weight' => 1030,
    'price' => 644000,
    'soulshots' => 1,
    'spiritshots' => 1,
    'enchant_enabled' => true,
    'is_magic_weapon' => true,
    'commissionItemType' => 'TWO_HAND_MAGIC_BLUNT_WEAPON',
  ],
  185 => 
  [
    'id' => 185,
    'type' => 'weapon',
    'name' => 'Staff of Mana',
    'add_name' => '',
    'description' => '',
    'icon' => 'weapon_staff_of_mana_i00',
    'weapon_type' => 'blunt',
    'bodypart' => 'lrhand',
    'crystal_count' => 1170,
    'crystal_type' => 'd',
    'weight' => 1040,
    'price' => 644000,
    'soulshots' => 1,
    'spiritshots' => 1,
    'enchant_enabled' => true,
    'is_magic_weapon' => true,
    'commissionItemType' => 'TWO_HAND_MAGIC_BLUNT_WEAPON',
  ],
  186 => 
  [
    'id' => 186,
    'type' => 'weapon',
    'name' => 'Staff of Magic',
    'add_name' => '',
    'description' => '',
    'icon' => 'weapon_staff_of_magicpower_i00',
    'weapon_type' => 'blunt',
    'bodypart' => 'lrhand',
    'crystal_count' => 1758,
    'crystal_type' => 'd',
    'weight' => 1020,
    'price' => 967000,
    'soulshots' => 1,
    'spiritshots' => 1,
    'enchant_enabled' => true,
    'commissionItemType' => 'TWO_HAND_MAGIC_BLUNT_WEAPON',
    'is_magic_weapon' => true,
  ],
  187 => 
  [
    'id' => 187,
    'type' => 'weapon',
    'name' => 'Atuba Hammer',
    'add_name' => '',
    'description' => '',
    'icon' => 'weapon_atuba_hammer_i00',
    'weapon_type' => 'blunt',
    'bodypart' => 'rhand',
    'crystal_count' => 3272,
    'crystal_type' => 'd',
    'weight' => 1010,
    'price' => 1800000,
    'soulshots' => 1,
    'spiritshots' => 1,
    'enchant_enabled' => true,
    'commissionItemType' => 'TWO_HAND_MAGIC_BLUNT_WEAPON',
    'is_magic_weapon' => true,
  ],
  188 => 
  [
    'id' => 188,
    'type' => 'weapon',
    'name' => 'Ghost Staff',
    'add_name' => '',
    'description' => '',
    'icon' => 'weapon_ghost_staff_i00',
    'weapon_type' => 'blunt',
    'bodypart' => 'lrhand',
    'crystal_count' => 3272,
    'crystal_type' => 'd',
    'weight' => 1000,
    'price' => 1800000,
    'soulshots' => 1,
    'spiritshots' => 1,
    'enchant_enabled' => true,
    'commissionItemType' => 'TWO_HAND_MAGIC_BLUNT_WEAPON',
    'is_magic_weapon' => true,
  ],
  189 => 
  [
    'id' => 189,
    'type' => 'weapon',
    'name' => 'Staff of Life',
    'add_name' => '',
    'description' => '',
    'icon' => 'weapon_life_stick_i00',
    'weapon_type' => 'blunt',
    'bodypart' => 'rhand',
    'crystal_count' => 3272,
    'crystal_type' => 'd',
    'weight' => 1180,
    'price' => 1800000,
    'soulshots' => 1,
    'spiritshots' => 1,
    'enchant_enabled' => true,
    'is_magic_weapon' => true,
    'commissionItemType' => 'ONE_HAND_MAGIC_BLUNT_WEAPON',
  ],
  190 => 
  [
    'id' => 190,
    'type' => 'weapon',
    'name' => 'Atuba Mace',
    'add_name' => '',
    'description' => '',
    'icon' => 'weapon_atuba_mace_i00',
    'weapon_type' => 'blunt',
    'bodypart' => 'lrhand',
    'crystal_count' => 3272,
    'crystal_type' => 'd',
    'weight' => 1010,
    'price' => 1800000,
    'soulshots' => 1,
    'spiritshots' => 1,
    'enchant_enabled' => true,
    'is_magic_weapon' => true,
    'commissionItemType' => 'TWO_HAND_MAGIC_BLUNT_WEAPON',
  ],
  191 => 
  [
    'id' => 191,
    'type' => 'weapon',
    'name' => 'Heavy Doom Hammer',
    'add_name' => '',
    'description' => 'Bestows either Regeneration, Mental Shield or Hold.',
    'icon' => 'weapon_heavy_doom_hammer_i00',
    'weapon_type' => 'blunt',
    'bodypart' => 'rhand',
    'crystal_count' => 916,
    'crystal_type' => 'c',
    'weight' => 1020,
    'price' => 2290000,
    'soulshots' => 1,
    'spiritshots' => 1,
    'enchant_enabled' => true,
    'commissionItemType' => 'TWO_HAND_MAGIC_BLUNT_WEAPON',
    'is_magic_weapon' => true,
  ],
  192 => 
  [
    'id' => 192,
    'type' => 'weapon',
    'name' => 'Crystal Staff',
    'add_name' => '',
    'description' => 'Bestows either Rsk. Evasion, Mana Up, or Blessed Body.',
    'icon' => 'weapon_crystal_staff_i00',
    'weapon_type' => 'blunt',
    'bodypart' => 'lrhand',
    'crystal_count' => 916,
    'crystal_type' => 'c',
    'weight' => 1020,
    'price' => 2290000,
    'soulshots' => 1,
    'spiritshots' => 1,
    'enchant_enabled' => true,
    'is_magic_weapon' => true,
    'commissionItemType' => 'TWO_HAND_MAGIC_BLUNT_WEAPON',
  ],
  193 => 
  [
    'id' => 193,
    'type' => 'weapon',
    'name' => 'Stick of Faith',
    'add_name' => '',
    'description' => 'Bestows one of the following functions: Mana Up, Magic Hold or Mental Shield.',
    'icon' => 'weapon_stick_of_faith_i00',
    'weapon_type' => 'blunt',
    'bodypart' => 'rhand',
    'crystal_count' => 916,
    'crystal_type' => 'c',
    'weight' => 1160,
    'price' => 2290000,
    'soulshots' => 1,
    'spiritshots' => 1,
    'enchant_enabled' => true,
    'commissionItemType' => 'ONE_HAND_MAGIC_BLUNT_WEAPON',
    'is_magic_weapon' => true,
  ],
  194 => 
  [
    'id' => 194,
    'type' => 'weapon',
    'name' => 'Heavy Doom Axe',
    'add_name' => '',
    'description' => 'Bestows one of the following functions: Magic Poison, Magic Weakness, or Magic Chaos.',
    'icon' => 'weapon_heavy_doom_axe_i00',
    'weapon_type' => 'blunt',
    'bodypart' => 'lrhand',
    'crystal_count' => 916,
    'crystal_type' => 'c',
    'weight' => 1010,
    'price' => 2290000,
    'soulshots' => 1,
    'spiritshots' => 1,
    'enchant_enabled' => true,
    'commissionItemType' => 'TWO_HAND_MAGIC_BLUNT_WEAPON',
    'is_magic_weapon' => true,
  ],
  195 => 
  [
    'id' => 195,
    'type' => 'weapon',
    'name' => 'Cursed Staff',
    'add_name' => '',
    'description' => 'Bestows one of the following functions: Magic Hold, Magic Poison, or Magic Weakness.',
    'icon' => 'weapon_cursed_staff_i00',
    'weapon_type' => 'blunt',
    'bodypart' => 'lrhand',
    'crystal_count' => 1148,
    'crystal_type' => 'c',
    'weight' => 1000,
    'price' => 2870000,
    'soulshots' => 1,
    'spiritshots' => 1,
    'enchant_enabled' => true,
    'commissionItemType' => 'TWO_HAND_MAGIC_BLUNT_WEAPON',
    'is_magic_weapon' => true,
  ],
  196 => 
  [
    'id' => 196,
    'type' => 'weapon',
    'name' => 'Stick of Eternity',
    'add_name' => '',
    'description' => 'Bestows one of the following functions: Empower, Rsk., Evasion, or Blessed Body.',
    'icon' => 'weapon_stick_of_eternity_i00',
    'weapon_type' => 'blunt',
    'bodypart' => 'rhand',
    'crystal_count' => 1720,
    'crystal_type' => 'c',
    'weight' => 1130,
    'price' => 4300000,
    'soulshots' => 1,
    'spiritshots' => 1,
    'enchant_enabled' => true,
    'commissionItemType' => 'ONE_HAND_MAGIC_BLUNT_WEAPON',
    'is_magic_weapon' => true,
  ],
  197 => 
  [
    'id' => 197,
    'type' => 'weapon',
    'name' => 'Paradia Staff',
    'add_name' => '',
    'description' => 'Bestows either Regeneration, Mental Shield or Hold.',
    'icon' => 'weapon_paradia_staff_i00',
    'weapon_type' => 'blunt',
    'bodypart' => 'lrhand',
    'crystal_count' => 1720,
    'crystal_type' => 'c',
    'weight' => 1010,
    'price' => 4300000,
    'soulshots' => 1,
    'spiritshots' => 1,
    'enchant_enabled' => true,
    'commissionItemType' => 'TWO_HAND_MAGIC_BLUNT_WEAPON',
    'is_magic_weapon' => true,
  ],
  198 => 
  [
    'id' => 198,
    'type' => 'weapon',
    'name' => 'Inferno Staff',
    'add_name' => '',
    'description' => 'Bestows one of the following functions: Magic Silence, Acumen or Magic Paralyze.',
    'icon' => 'weapon_inferno_staff_i00',
    'weapon_type' => 'blunt',
    'bodypart' => 'lrhand',
    'crystal_count' => 1720,
    'crystal_type' => 'c',
    'weight' => 1000,
    'price' => 4300000,
    'soulshots' => 1,
    'spiritshots' => 1,
    'enchant_enabled' => true,
    'commissionItemType' => 'TWO_HAND_MAGIC_BLUNT_WEAPON',
    'is_magic_weapon' => true,
  ],
  199 => 
  [
    'id' => 199,
    'type' => 'weapon',
    'name' => 'Pa\'agrio Hammer',
    'add_name' => '',
    'description' => 'Bestows one of the following functions: Rsk. Evasion, Magic Poison, or Magic Weakness.',
    'icon' => 'weapon_paagrio_hammer_i00',
    'weapon_type' => 'blunt',
    'bodypart' => 'lrhand',
    'crystal_count' => 1720,
    'crystal_type' => 'c',
    'weight' => 1010,
    'price' => 4300000,
    'soulshots' => 1,
    'spiritshots' => 1,
    'enchant_enabled' => true,
    'commissionItemType' => 'TWO_HAND_MAGIC_BLUNT_WEAPON',
    'is_magic_weapon' => true,
  ],
];