<?php
return [
  2400 => 
  [
    'id' => 2400,
    'type' => 'armor',
    'name' => 'Tallum Tunic',
    'add_name' => '',
    'description' => '',
    'icon' => 'armor_t79_u_i00',
    'armor_type' => 'magic',
    'bodypart' => 'chest',
    'crystal_count' => 142,
    'crystal_type' => 'a',
    'weight' => 1860,
    'price' => 2671000,
    'enchant_enabled' => true,
    'commissionItemType' => 'ARMOR_TOP',
  ],
  2401 => 
  [
    'id' => 2401,
    'type' => 'armor',
    'name' => 'Elven Mithril Stockings',
    'add_name' => '',
    'description' => '',
    'icon' => 'armor_elven_hose_i00',
    'armor_type' => 'magic',
    'bodypart' => 'legs',
    'crystal_count' => 254,
    'crystal_type' => 'd',
    'weight' => 720,
    'price' => 140000,
    'commissionItemType' => 'ARMOR_PANTS',
    'enchant_enabled' => true,
  ],
  2402 => 
  [
    'id' => 2402,
    'type' => 'armor',
    'name' => 'Zubei\'s Stockings',
    'add_name' => '',
    'description' => '',
    'icon' => 'armor_t56_l_i00',
    'armor_type' => 'magic',
    'bodypart' => 'legs',
    'crystal_count' => 129,
    'crystal_type' => 'b',
    'weight' => 940,
    'price' => 973000,
    'commissionItemType' => 'ARMOR_PANTS',
    'enchant_enabled' => true,
  ],
  2403 => 
  [
    'id' => 2403,
    'type' => 'armor',
    'name' => 'Blue Wolf Stockings',
    'add_name' => '',
    'description' => '',
    'icon' => 'armor_t70_l_i00',
    'armor_type' => 'magic',
    'bodypart' => 'legs',
    'crystal_count' => 201,
    'crystal_type' => 'b',
    'weight' => 920,
    'price' => 1510000,
    'enchant_enabled' => true,
    'commissionItemType' => 'ARMOR_PANTS',
  ],
  2404 => 
  [
    'id' => 2404,
    'type' => 'armor',
    'name' => 'Doom Stockings',
    'add_name' => '',
    'description' => '',
    'icon' => 'armor_t73_l_i00',
    'armor_type' => 'magic',
    'bodypart' => 'legs',
    'crystal_count' => 201,
    'crystal_type' => 'b',
    'weight' => 910,
    'price' => 1510000,
    'enchant_enabled' => true,
    'commissionItemType' => 'ARMOR_PANTS',
  ],
  2405 => 
  [
    'id' => 2405,
    'type' => 'armor',
    'name' => 'Tallum Stockings',
    'add_name' => '',
    'description' => '',
    'icon' => 'armor_t79_l_i00',
    'armor_type' => 'magic',
    'bodypart' => 'legs',
    'crystal_count' => 134,
    'crystal_type' => 'a',
    'weight' => 920,
    'price' => 1670000,
    'enchant_enabled' => true,
    'commissionItemType' => 'ARMOR_PANTS',
  ],
  2406 => 
  [
    'id' => 2406,
    'type' => 'armor',
    'name' => 'Avadon Robe',
    'add_name' => '',
    'description' => 'Full body armor.',
    'icon' => 'armor_t59_ul_i00',
    'armor_type' => 'magic',
    'bodypart' => 'onepiece',
    'crystal_count' => 304,
    'crystal_type' => 'b',
    'weight' => 2540,
    'price' => 2280000,
    'commissionItemType' => 'FULL_BODY',
    'enchant_enabled' => true,
  ],
  2407 => 
  [
    'id' => 2407,
    'type' => 'armor',
    'name' => 'Dark Crystal Robe',
    'add_name' => '',
    'description' => 'Full body armor.',
    'icon' => 'armor_t76_ul_i00',
    'armor_type' => 'magic',
    'bodypart' => 'onepiece',
    'crystal_count' => 347,
    'crystal_type' => 'a',
    'weight' => 2450,
    'price' => 4341000,
    'enchant_enabled' => true,
    'commissionItemType' => 'FULL_BODY',
  ],
  2408 => 
  [
    'id' => 2408,
    'type' => 'armor',
    'name' => 'Robe of Nightmare',
    'add_name' => '',
    'description' => 'Full body armor.',
    'icon' => 'armor_t82_ul_i00',
    'armor_type' => 'magic',
    'bodypart' => 'onepiece',
    'crystal_count' => 528,
    'crystal_type' => 'a',
    'weight' => 2300,
    'price' => 6603000,
    'commissionItemType' => 'FULL_BODY',
    'enchant_enabled' => true,
  ],
  2409 => 
  [
    'id' => 2409,
    'type' => 'armor',
    'name' => 'Majestic Robe',
    'add_name' => '',
    'description' => 'Full body armor.',
    'icon' => 'armor_t85_ul_i00',
    'armor_type' => 'magic',
    'bodypart' => 'onepiece',
    'crystal_count' => 528,
    'crystal_type' => 'a',
    'weight' => 2330,
    'price' => 6603000,
    'commissionItemType' => 'FULL_BODY',
    'enchant_enabled' => true,
  ],
  2411 => 
  [
    'id' => 2411,
    'type' => 'armor',
    'name' => 'Brigandine Helmet',
    'add_name' => '',
    'description' => '',
    'icon' => 'armor_leather_helmet_i00',
    'bodypart' => 'head',
    'crystal_count' => 203,
    'crystal_type' => 'd',
    'weight' => 630,
    'price' => 112000,
    'enchant_enabled' => true,
    'commissionItemType' => 'HELMET',
  ],
  2412 => 
  [
    'id' => 2412,
    'type' => 'armor',
    'name' => 'Plate Helmet',
    'add_name' => '',
    'description' => '',
    'icon' => 'armor_leather_helmet_i00',
    'bodypart' => 'head',
    'crystal_count' => 267,
    'crystal_type' => 'd',
    'weight' => 630,
    'price' => 147000,
    'commissionItemType' => 'HELMET',
    'enchant_enabled' => true,
  ],
  2413 => 
  [
    'id' => 2413,
    'type' => 'armor',
    'name' => 'Chain Hood',
    'add_name' => '',
    'description' => '',
    'icon' => 'armor_leather_helmet_i00',
    'bodypart' => 'head',
    'crystal_count' => 75,
    'crystal_type' => 'c',
    'weight' => 620,
    'price' => 189000,
    'commissionItemType' => 'HELMET',
    'enchant_enabled' => true,
  ],
  2414 => 
  [
    'id' => 2414,
    'type' => 'armor',
    'name' => 'Full Plate Helmet',
    'add_name' => '',
    'description' => '',
    'icon' => 'armor_leather_helmet_i00',
    'bodypart' => 'head',
    'crystal_count' => 214,
    'crystal_type' => 'c',
    'weight' => 600,
    'price' => 536000,
    'commissionItemType' => 'HELMET',
    'enchant_enabled' => true,
  ],
  2415 => 
  [
    'id' => 2415,
    'type' => 'armor',
    'name' => 'Sealed Avadon Circlet',
    'add_name' => '',
    'description' => '',
    'icon' => 'armor_leather_helmet_i02',
    'bodypart' => 'head',
    'crystal_count' => 214,
    'crystal_type' => 'b',
    'weight' => 590,
    'price' => 778000,
    'enchant_enabled' => true,
    'commissionItemType' => 'HELMET',
  ],
  2416 => 
  [
    'id' => 2416,
    'type' => 'armor',
    'name' => 'Sealed Blue Wolf Helmet',
    'add_name' => '',
    'description' => '',
    'icon' => 'armor_leather_helmet_i02',
    'bodypart' => 'head',
    'crystal_count' => 214,
    'crystal_type' => 'b',
    'weight' => 580,
    'price' => 1210000,
    'enchant_enabled' => true,
    'commissionItemType' => 'HELMET',
  ],
  2417 => 
  [
    'id' => 2417,
    'type' => 'armor',
    'name' => 'Sealed Doom Helmet',
    'add_name' => '',
    'description' => '',
    'icon' => 'armor_leather_helmet_i02',
    'bodypart' => 'head',
    'crystal_count' => 214,
    'crystal_type' => 'b',
    'weight' => 580,
    'price' => 1210000,
    'enchant_enabled' => true,
    'commissionItemType' => 'HELMET',
  ],
  2418 => 
  [
    'id' => 2418,
    'type' => 'armor',
    'name' => 'Helm of Nightmare',
    'add_name' => '',
    'description' => '',
    'icon' => 'armor_leather_helmet_i00',
    'bodypart' => 'head',
    'crystal_count' => 214,
    'crystal_type' => 'a',
    'weight' => 560,
    'price' => 2032000,
    'commissionItemType' => 'HELMET',
    'enchant_enabled' => true,
  ],
  2419 => 
  [
    'id' => 2419,
    'type' => 'armor',
    'name' => 'Majestic Circlet',
    'add_name' => '',
    'description' => '',
    'icon' => 'armor_leather_helmet_i00',
    'bodypart' => 'head',
    'crystal_count' => 163,
    'crystal_type' => 'a',
    'weight' => 550,
    'price' => 2032000,
    'commissionItemType' => 'HELMET',
    'enchant_enabled' => true,
  ],
  2422 => 
  [
    'id' => 2422,
    'type' => 'armor',
    'name' => 'Reinforced Leather Boots',
    'add_name' => '',
    'description' => '',
    'icon' => 'armor_t13_b_i00',
    'bodypart' => 'feet',
    'crystal_count' => 92,
    'crystal_type' => 'd',
    'weight' => 1280,
    'price' => 50800,
    'commissionItemType' => 'FEET',
    'enchant_enabled' => true,
  ],
  2423 => 
  [
    'id' => 2423,
    'type' => 'armor',
    'name' => 'Boots of Knowledge',
    'add_name' => '',
    'description' => '',
    'icon' => 'armor_t41_b_i00',
    'bodypart' => 'feet',
    'crystal_count' => 92,
    'crystal_type' => 'd',
    'weight' => 1270,
    'price' => 50800,
    'commissionItemType' => 'FEET',
    'enchant_enabled' => true,
  ],
  2424 => 
  [
    'id' => 2424,
    'type' => 'armor',
    'name' => 'Manticore Skin Boots',
    'add_name' => '',
    'description' => '',
    'icon' => 'armor_t42_b_i00',
    'bodypart' => 'feet',
    'crystal_count' => 135,
    'crystal_type' => 'd',
    'weight' => 1260,
    'price' => 74700,
    'commissionItemType' => 'FEET',
    'enchant_enabled' => true,
  ],
  2425 => 
  [
    'id' => 2425,
    'type' => 'armor',
    'name' => 'Brigandine Boots',
    'add_name' => '',
    'description' => '',
    'icon' => 'armor_t43_b_i00',
    'bodypart' => 'feet',
    'crystal_count' => 135,
    'crystal_type' => 'd',
    'weight' => 1250,
    'price' => 74700,
    'commissionItemType' => 'FEET',
    'enchant_enabled' => true,
  ],
  2426 => 
  [
    'id' => 2426,
    'type' => 'armor',
    'name' => 'Elven Mithril Boots',
    'add_name' => '',
    'description' => '',
    'icon' => 'armor_t51_b_i00',
    'bodypart' => 'feet',
    'crystal_count' => 135,
    'crystal_type' => 'd',
    'weight' => 1250,
    'price' => 74700,
    'commissionItemType' => 'FEET',
    'enchant_enabled' => true,
  ],
  2427 => 
  [
    'id' => 2427,
    'type' => 'armor',
    'name' => 'Salamander Skin Boots',
    'add_name' => '',
    'description' => '',
    'icon' => 'armor_t45_b_i00',
    'bodypart' => 'feet',
    'crystal_count' => 177,
    'crystal_type' => 'd',
    'weight' => 1230,
    'price' => 97800,
    'commissionItemType' => 'FEET',
    'enchant_enabled' => true,
  ],
  2428 => 
  [
    'id' => 2428,
    'type' => 'armor',
    'name' => 'Plate Boots',
    'add_name' => '',
    'description' => '',
    'icon' => 'armor_t46_b_i00',
    'bodypart' => 'feet',
    'crystal_count' => 177,
    'crystal_type' => 'd',
    'weight' => 1240,
    'price' => 97800,
    'commissionItemType' => 'FEET',
    'enchant_enabled' => true,
  ],
  2429 => 
  [
    'id' => 2429,
    'type' => 'armor',
    'name' => 'Chain Boots',
    'add_name' => '',
    'description' => '',
    'icon' => 'armor_t48_b_i00',
    'bodypart' => 'feet',
    'crystal_count' => 50,
    'crystal_type' => 'c',
    'weight' => 1220,
    'price' => 126000,
    'commissionItemType' => 'FEET',
    'enchant_enabled' => true,
  ],
  2430 => 
  [
    'id' => 2430,
    'type' => 'armor',
    'name' => 'Karmian Boots',
    'add_name' => '',
    'description' => '',
    'icon' => 'armor_t53_b_i00',
    'bodypart' => 'feet',
    'crystal_count' => 50,
    'crystal_type' => 'c',
    'weight' => 1230,
    'price' => 126000,
    'enchant_enabled' => true,
    'commissionItemType' => 'FEET',
  ],
  2431 => 
  [
    'id' => 2431,
    'type' => 'armor',
    'name' => 'Plated Leather Boots',
    'add_name' => '',
    'description' => '',
    'icon' => 'armor_t47_b_i00',
    'bodypart' => 'feet',
    'crystal_count' => 50,
    'crystal_type' => 'c',
    'weight' => 1220,
    'price' => 126000,
    'enchant_enabled' => true,
    'commissionItemType' => 'FEET',
  ],
  2432 => 
  [
    'id' => 2432,
    'type' => 'armor',
    'name' => 'Dwarven Chain Boots',
    'add_name' => '',
    'description' => '',
    'icon' => 'armor_t60_b_i00',
    'bodypart' => 'feet',
    'crystal_count' => 50,
    'crystal_type' => 'c',
    'weight' => 1210,
    'price' => 126000,
    'commissionItemType' => 'FEET',
    'enchant_enabled' => true,
  ],
  2433 => 
  [
    'id' => 2433,
    'type' => 'armor',
    'name' => 'Boots of Seal',
    'add_name' => '',
    'description' => '',
    'icon' => 'armor_t44_b_i00',
    'bodypart' => 'feet',
    'crystal_count' => 50,
    'crystal_type' => 'c',
    'weight' => 1220,
    'price' => 126000,
    'enchant_enabled' => true,
    'commissionItemType' => 'FEET',
  ],
  2434 => 
  [
    'id' => 2434,
    'type' => 'armor',
    'name' => 'Rind Leather Boots',
    'add_name' => '',
    'description' => '',
    'icon' => 'armor_t49_b_i00',
    'bodypart' => 'feet',
    'crystal_count' => 64,
    'crystal_type' => 'c',
    'weight' => 1220,
    'price' => 161000,
    'commissionItemType' => 'FEET',
    'enchant_enabled' => true,
  ],
  2435 => 
  [
    'id' => 2435,
    'type' => 'armor',
    'name' => 'Demon\'s Boots',
    'add_name' => '',
    'description' => '',
    'icon' => 'armor_t54_b_i00',
    'bodypart' => 'feet',
    'crystal_count' => 98,
    'crystal_type' => 'c',
    'weight' => 1220,
    'price' => 245000,
    'commissionItemType' => 'FEET',
    'enchant_enabled' => true,
  ],
  2436 => 
  [
    'id' => 2436,
    'type' => 'armor',
    'name' => 'Theca Leather Boots',
    'add_name' => '',
    'description' => '',
    'icon' => 'armor_t63_b_i00',
    'bodypart' => 'feet',
    'crystal_count' => 110,
    'crystal_type' => 'c',
    'weight' => 1210,
    'price' => 275000,
    'commissionItemType' => 'FEET',
    'enchant_enabled' => true,
  ],
  2437 => 
  [
    'id' => 2437,
    'type' => 'armor',
    'name' => 'Drake Leather Boots',
    'add_name' => '',
    'description' => '',
    'icon' => 'armor_t45_b_i00',
    'bodypart' => 'feet',
    'crystal_count' => 143,
    'crystal_type' => 'c',
    'weight' => 1210,
    'price' => 358000,
    'commissionItemType' => 'FEET',
    'enchant_enabled' => true,
  ],
  2438 => 
  [
    'id' => 2438,
    'type' => 'armor',
    'name' => 'Full Plate Boots',
    'add_name' => '',
    'description' => '',
    'icon' => 'armor_t62_b_i00',
    'bodypart' => 'feet',
    'crystal_count' => 143,
    'crystal_type' => 'c',
    'weight' => 1200,
    'price' => 358000,
    'commissionItemType' => 'FEET',
    'enchant_enabled' => true,
  ],
  2439 => 
  [
    'id' => 2439,
    'type' => 'armor',
    'name' => 'Sealed Blue Wolf Boots',
    'add_name' => '',
    'description' => '',
    'icon' => 'armor_t68_b_i02',
    'bodypart' => 'feet',
    'crystal_count' => 107,
    'crystal_type' => 'b',
    'weight' => 1130,
    'price' => 804000,
    'enchant_enabled' => true,
    'commissionItemType' => 'FEET',
  ],
  2440 => 
  [
    'id' => 2440,
    'type' => 'armor',
    'name' => 'Boots of Nightmare',
    'add_name' => '',
    'description' => '',
    'icon' => 'etc_ertheia2',
    'bodypart' => 'feet',
    'crystal_count' => 107,
    'crystal_type' => 'a',
    'weight' => 1110,
    'price' => 1355000,
    'commissionItemType' => 'FEET',
  ],
  2446 => 
  [
    'id' => 2446,
    'type' => 'armor',
    'name' => 'Reinforced Leather Gloves',
    'add_name' => '',
    'description' => '',
    'icon' => 'armor_t13_g_i00',
    'bodypart' => 'gloves',
    'crystal_count' => 92,
    'crystal_type' => 'd',
    'weight' => 640,
    'price' => 50800,
    'commissionItemType' => 'GLOVES',
    'enchant_enabled' => true,
  ],
  2447 => 
  [
    'id' => 2447,
    'type' => 'armor',
    'name' => 'Gloves of Knowledge',
    'add_name' => '',
    'description' => '',
    'icon' => 'armor_t41_g_i00',
    'bodypart' => 'gloves',
    'crystal_count' => 92,
    'crystal_type' => 'd',
    'weight' => 640,
    'price' => 50800,
    'commissionItemType' => 'GLOVES',
    'enchant_enabled' => true,
  ],
  2448 => 
  [
    'id' => 2448,
    'type' => 'armor',
    'name' => 'Manticore Skin Gloves',
    'add_name' => '',
    'description' => '',
    'icon' => 'armor_t42_g_i00',
    'bodypart' => 'gloves',
    'crystal_count' => 135,
    'crystal_type' => 'd',
    'weight' => 630,
    'price' => 74700,
    'commissionItemType' => 'GLOVES',
    'enchant_enabled' => true,
  ],
  2449 => 
  [
    'id' => 2449,
    'type' => 'armor',
    'name' => 'Brigandine Gauntlets',
    'add_name' => '',
    'description' => '',
    'icon' => 'armor_t43_g_i00',
    'bodypart' => 'gloves',
    'crystal_count' => 135,
    'crystal_type' => 'd',
    'weight' => 630,
    'price' => 74700,
    'commissionItemType' => 'GLOVES',
    'enchant_enabled' => true,
  ],
  2450 => 
  [
    'id' => 2450,
    'type' => 'armor',
    'name' => 'Elven Mithril Gloves',
    'add_name' => '',
    'description' => '',
    'icon' => 'armor_t51_g_i00',
    'bodypart' => 'gloves',
    'crystal_count' => 135,
    'crystal_type' => 'd',
    'weight' => 640,
    'price' => 74700,
    'commissionItemType' => 'GLOVES',
    'enchant_enabled' => true,
  ],
  2451 => 
  [
    'id' => 2451,
    'type' => 'armor',
    'name' => 'Sage\'s Worn Gloves',
    'add_name' => '',
    'description' => '',
    'icon' => 'armor_t44_g_i00',
    'bodypart' => 'gloves',
    'crystal_count' => 177,
    'crystal_type' => 'd',
    'weight' => 630,
    'price' => 97800,
    'commissionItemType' => 'GLOVES',
    'enchant_enabled' => true,
  ],
  2452 => 
  [
    'id' => 2452,
    'type' => 'armor',
    'name' => 'Reinforced Mithril Gloves',
    'add_name' => '',
    'description' => '',
    'icon' => 'armor_t47_g_i00',
    'bodypart' => 'gloves',
    'crystal_count' => 50,
    'crystal_type' => 'c',
    'weight' => 620,
    'price' => 126000,
    'commissionItemType' => 'GLOVES',
    'enchant_enabled' => true,
  ],
  2453 => 
  [
    'id' => 2453,
    'type' => 'armor',
    'name' => 'Chain Gloves',
    'add_name' => '',
    'description' => '',
    'icon' => 'armor_t48_g_i00',
    'bodypart' => 'gloves',
    'crystal_count' => 50,
    'crystal_type' => 'c',
    'weight' => 620,
    'price' => 126000,
    'enchant_enabled' => true,
    'commissionItemType' => 'GLOVES',
  ],
  2454 => 
  [
    'id' => 2454,
    'type' => 'armor',
    'name' => 'Karmian Gloves',
    'add_name' => '',
    'description' => '',
    'icon' => 'armor_t53_g_i00',
    'bodypart' => 'gloves',
    'crystal_count' => 50,
    'crystal_type' => 'c',
    'weight' => 620,
    'price' => 126000,
    'enchant_enabled' => true,
    'commissionItemType' => 'GLOVES',
  ],
  2455 => 
  [
    'id' => 2455,
    'type' => 'armor',
    'name' => 'Plated Leather Gloves',
    'add_name' => '',
    'description' => '',
    'icon' => 'armor_t47_g_i00',
    'bodypart' => 'gloves',
    'crystal_count' => 59,
    'crystal_type' => 'c',
    'weight' => 610,
    'price' => 149000,
    'commissionItemType' => 'GLOVES',
    'enchant_enabled' => true,
  ],
  2456 => 
  [
    'id' => 2456,
    'type' => 'armor',
    'name' => 'Dwarven Chain Gloves',
    'add_name' => '',
    'description' => '',
    'icon' => 'armor_t60_g_i00',
    'bodypart' => 'gloves',
    'crystal_count' => 64,
    'crystal_type' => 'c',
    'weight' => 600,
    'price' => 161000,
    'commissionItemType' => 'GLOVES',
    'enchant_enabled' => true,
  ],
  2457 => 
  [
    'id' => 2457,
    'type' => 'armor',
    'name' => 'Gloves of Seal',
    'add_name' => '',
    'description' => '',
    'icon' => 'armor_t44_g_i00',
    'bodypart' => 'gloves',
    'crystal_count' => 64,
    'crystal_type' => 'c',
    'weight' => 620,
    'price' => 161000,
    'commissionItemType' => 'GLOVES',
    'enchant_enabled' => true,
  ],
  2458 => 
  [
    'id' => 2458,
    'type' => 'armor',
    'name' => 'Rind Leather Gloves',
    'add_name' => '',
    'description' => '',
    'icon' => 'armor_t49_g_i00',
    'bodypart' => 'gloves',
    'crystal_count' => 64,
    'crystal_type' => 'c',
    'weight' => 600,
    'price' => 161000,
    'enchant_enabled' => true,
    'commissionItemType' => 'GLOVES',
  ],
  2459 => 
  [
    'id' => 2459,
    'type' => 'armor',
    'name' => 'Demon\'s Gloves',
    'add_name' => '',
    'description' => '',
    'icon' => 'armor_t54_g_i00',
    'bodypart' => 'gloves',
    'crystal_count' => 98,
    'crystal_type' => 'c',
    'weight' => 610,
    'price' => 245000,
    'commissionItemType' => 'GLOVES',
    'enchant_enabled' => true,
  ],
  2460 => 
  [
    'id' => 2460,
    'type' => 'armor',
    'name' => 'Theca Leather Gloves',
    'add_name' => '',
    'description' => '',
    'icon' => 'armor_t63_g_i00',
    'bodypart' => 'gloves',
    'crystal_count' => 110,
    'crystal_type' => 'c',
    'weight' => 600,
    'price' => 275000,
    'commissionItemType' => 'GLOVES',
    'enchant_enabled' => true,
  ],
  2461 => 
  [
    'id' => 2461,
    'type' => 'armor',
    'name' => 'Drake Leather Gloves',
    'add_name' => '',
    'description' => '',
    'icon' => 'armor_t45_g_i00',
    'bodypart' => 'gloves',
    'crystal_count' => 143,
    'crystal_type' => 'c',
    'weight' => 600,
    'price' => 358000,
    'commissionItemType' => 'GLOVES',
    'enchant_enabled' => true,
  ],
  2462 => 
  [
    'id' => 2462,
    'type' => 'armor',
    'name' => 'Full Plate Gauntlets',
    'add_name' => '',
    'description' => '',
    'icon' => 'armor_t62_g_i00',
    'bodypart' => 'gloves',
    'crystal_count' => 143,
    'crystal_type' => 'c',
    'weight' => 600,
    'price' => 358000,
    'commissionItemType' => 'GLOVES',
    'enchant_enabled' => true,
  ],
  2463 => 
  [
    'id' => 2463,
    'type' => 'armor',
    'name' => 'Divine Gloves',
    'add_name' => '',
    'description' => '',
    'icon' => 'armor_t57_g_i00',
    'bodypart' => 'gloves',
    'crystal_count' => 143,
    'crystal_type' => 'c',
    'weight' => 610,
    'price' => 358000,
    'commissionItemType' => 'GLOVES',
    'enchant_enabled' => true,
  ],
  2464 => 
  [
    'id' => 2464,
    'type' => 'armor',
    'name' => 'Sealed Avadon Gloves',
    'add_name' => '',
    'description' => '',
    'icon' => 'armor_t66_g_i02',
    'bodypart' => 'gloves',
    'crystal_count' => 69,
    'crystal_type' => 'b',
    'weight' => 590,
    'price' => 519000,
    'enchant_enabled' => true,
    'commissionItemType' => 'GLOVES',
  ],
  2465 => 
  [
    'id' => 2465,
    'type' => 'armor',
    'name' => 'Chain Gloves of Silence',
    'add_name' => '',
    'description' => '',
    'icon' => 'etc_ertheia2',
    'bodypart' => 'gloves',
    'crystal_count' => 69,
    'crystal_type' => 'b',
    'weight' => 590,
    'price' => 519000,
    'commissionItemType' => 'GLOVES',
  ],
  2466 => 
  [
    'id' => 2466,
    'type' => 'armor',
    'name' => 'Guardian\'s Gloves',
    'add_name' => '',
    'description' => '',
    'icon' => 'etc_ertheia2',
    'bodypart' => 'gloves',
    'crystal_count' => 69,
    'crystal_type' => 'b',
    'weight' => 590,
    'price' => 399100,
    'commissionItemType' => 'GLOVES',
  ],
  2468 => 
  [
    'id' => 2468,
    'type' => 'armor',
    'name' => 'Blessed Gloves',
    'add_name' => '',
    'description' => '',
    'icon' => 'armor_t67_g_i00',
    'bodypart' => 'gloves',
    'crystal_count' => 143,
    'crystal_type' => 'c',
    'weight' => 600,
    'price' => 358000,
    'commissionItemType' => 'GLOVES',
    'enchant_enabled' => true,
  ],
  2472 => 
  [
    'id' => 2472,
    'type' => 'armor',
    'name' => 'Dark Crystal Gloves',
    'add_name' => '',
    'description' => '',
    'icon' => 'armor_t15_g_i00',
    'bodypart' => 'gloves',
    'crystal_count' => 71,
    'crystal_type' => 'a',
    'weight' => 580,
    'price' => 890000,
    'commissionItemType' => 'GLOVES',
    'enchant_enabled' => true,
  ],
  2475 => 
  [
    'id' => 2475,
    'type' => 'armor',
    'name' => 'Sealed Doom Gloves',
    'add_name' => '',
    'description' => '',
    'icon' => 'armor_t71_g_i02',
    'bodypart' => 'gloves',
    'crystal_count' => 107,
    'crystal_type' => 'b',
    'weight' => 580,
    'price' => 804000,
    'enchant_enabled' => true,
    'commissionItemType' => 'GLOVES',
  ],
  2478 => 
  [
    'id' => 2478,
    'type' => 'armor',
    'name' => 'Tallum Gloves',
    'add_name' => '',
    'description' => '',
    'icon' => 'etc_ertheia2',
    'bodypart' => 'gloves',
    'crystal_count' => 107,
    'crystal_type' => 'a',
    'weight' => 580,
    'price' => 890000,
    'commissionItemType' => 'GLOVES',
  ],
  2479 => 
  [
    'id' => 2479,
    'type' => 'armor',
    'name' => 'Gauntlets of Nightmare',
    'add_name' => '',
    'description' => '',
    'icon' => 'etc_ertheia2',
    'bodypart' => 'gloves',
    'crystal_count' => 107,
    'crystal_type' => 'a',
    'weight' => 550,
    'price' => 1355000,
    'commissionItemType' => 'GLOVES',
  ],
  2480 => 
  [
    'id' => 2480,
    'type' => 'armor',
    'name' => 'Elemental Gloves',
    'add_name' => '',
    'description' => '',
    'icon' => 'etc_ertheia2',
    'bodypart' => 'gloves',
    'crystal_count' => 107,
    'crystal_type' => 'b',
    'weight' => 580,
    'price' => 804000,
    'commissionItemType' => 'GLOVES',
  ],
  2481 => 
  [
    'id' => 2481,
    'type' => 'armor',
    'name' => 'Gloves of Grace',
    'add_name' => '',
    'description' => '',
    'icon' => 'etc_ertheia2',
    'bodypart' => 'gloves',
    'crystal_count' => 107,
    'crystal_type' => 'b',
    'weight' => 580,
    'price' => 804000,
    'commissionItemType' => 'GLOVES',
  ],
  2482 => 
  [
    'id' => 2482,
    'type' => 'armor',
    'name' => 'Majestic Gauntlets',
    'add_name' => '',
    'description' => '',
    'icon' => 'etc_ertheia2',
    'bodypart' => 'gloves',
    'crystal_count' => 107,
    'crystal_type' => 'a',
    'weight' => 540,
    'price' => 1355000,
    'commissionItemType' => 'GLOVES',
  ],
  2485 => 
  [
    'id' => 2485,
    'type' => 'armor',
    'name' => 'Implosion Gauntlets',
    'add_name' => '',
    'description' => '',
    'icon' => 'etc_ertheia2',
    'bodypart' => 'gloves',
    'crystal_count' => 107,
    'crystal_type' => 'b',
    'weight' => 580,
    'price' => 804000,
    'commissionItemType' => 'GLOVES',
  ],
  2486 => 
  [
    'id' => 2486,
    'type' => 'armor',
    'name' => 'Paradia Gloves',
    'add_name' => '',
    'description' => '',
    'icon' => 'etc_ertheia2',
    'bodypart' => 'gloves',
    'crystal_count' => 107,
    'crystal_type' => 'b',
    'weight' => 580,
    'price' => 804000,
    'commissionItemType' => 'GLOVES',
  ],
  2487 => 
  [
    'id' => 2487,
    'type' => 'armor',
    'name' => 'Sealed Blue Wolf Gloves',
    'add_name' => '',
    'description' => '',
    'icon' => 'armor_t68_g_i02',
    'bodypart' => 'gloves',
    'crystal_count' => 107,
    'crystal_type' => 'b',
    'weight' => 590,
    'price' => 804000,
    'enchant_enabled' => true,
    'commissionItemType' => 'GLOVES',
  ],
  2493 => 
  [
    'id' => 2493,
    'type' => 'armor',
    'name' => 'Brigandine Shield',
    'add_name' => '',
    'description' => '',
    'icon' => 'shield_brigandine_shield_i00',
    'bodypart' => 'lhand',
    'crystal_count' => 142,
    'crystal_type' => 'd',
    'weight' => 1320,
    'price' => 78400,
    'commissionItemType' => 'SHIELD',
    'enchant_enabled' => true,
  ],
  2494 => 
  [
    'id' => 2494,
    'type' => 'armor',
    'name' => 'Plate Shield',
    'add_name' => '',
    'description' => '',
    'icon' => 'shield_plate_shield_i00',
    'bodypart' => 'lhand',
    'crystal_count' => 187,
    'crystal_type' => 'd',
    'weight' => 1310,
    'price' => 103000,
    'commissionItemType' => 'SHIELD',
    'enchant_enabled' => true,
  ],
  2495 => 
  [
    'id' => 2495,
    'type' => 'armor',
    'name' => 'Chain Shield',
    'add_name' => '',
    'description' => '',
    'icon' => 'shield_chain_shield_i00',
    'bodypart' => 'lhand',
    'crystal_count' => 53,
    'crystal_type' => 'c',
    'weight' => 1280,
    'price' => 133000,
    'commissionItemType' => 'SHIELD',
    'enchant_enabled' => true,
  ],
  2496 => 
  [
    'id' => 2496,
    'type' => 'armor',
    'name' => 'Dwarven Chain Shield',
    'add_name' => '',
    'description' => '',
    'icon' => 'shield_dwarven_chain_shield_i00',
    'bodypart' => 'lhand',
    'crystal_count' => 62,
    'crystal_type' => 'c',
    'weight' => 1280,
    'price' => 156000,
    'commissionItemType' => 'SHIELD',
    'enchant_enabled' => true,
  ],
  2497 => 
  [
    'id' => 2497,
    'type' => 'armor',
    'name' => 'Full Plate Shield',
    'add_name' => '',
    'description' => '',
    'icon' => 'shield_full_plate_shield_i00',
    'bodypart' => 'lhand',
    'crystal_count' => 150,
    'crystal_type' => 'c',
    'weight' => 1220,
    'price' => 375000,
    'commissionItemType' => 'SHIELD',
    'enchant_enabled' => true,
  ],
  2498 => 
  [
    'id' => 2498,
    'type' => 'armor',
    'name' => 'Shield of Nightmare',
    'add_name' => '',
    'description' => '',
    'icon' => 'shield_shield_of_nightmare_i00',
    'bodypart' => 'lhand',
    'crystal_count' => 114,
    'crystal_type' => 'a',
    'weight' => 1180,
    'price' => 1422000,
    'commissionItemType' => 'SHIELD',
    'enchant_enabled' => true,
  ],
  2499 => 
  [
    'id' => 2499,
    'type' => 'weapon',
    'name' => 'Elven Long Sword',
    'add_name' => '',
    'description' => '',
    'icon' => 'weapon_elven_long_sword_i00',
    'weapon_type' => 'sword',
    'bodypart' => 'rhand',
    'crystal_count' => 3272,
    'crystal_type' => 'd',
    'weight' => 1440,
    'price' => 1800000,
    'change_weaponId' => 9225,
    'soulshots' => 1,
    'spiritshots' => 1,
    'commissionItemType' => 'ONE_HAND_SWORD',
    'enchant_enabled' => true,
  ],
];