<?php
return [
  32249 => 
  [
    'id' => 32249,
    'type' => 'etcitem',
    'name' => 'Infinite Wooden Quiver',
    'add_name' => '',
    'description' => '',
    'icon' => 'br_cashtex.item.br_cash_quiver_of_bone_arrows_i00',
    'etcitem_type' => 'arrow',
    'price' => 1580,
    'commissionItemType' => 'OTHER_ITEM',
    'is_infinite' => 'true',
  ],
  32250 => 
  [
    'id' => 32250,
    'type' => 'etcitem',
    'name' => 'Infinite Bone Quiver',
    'add_name' => '',
    'description' => '',
    'icon' => 'br_cashtex.item.br_cash_quiver_of_bone_arrows_i00',
    'etcitem_type' => 'arrow',
    'price' => 7320,
    'crystal_type' => 'd',
    'commissionItemType' => 'OTHER_ITEM',
    'is_infinite' => 'true',
  ],
  32251 => 
  [
    'id' => 32251,
    'type' => 'etcitem',
    'name' => 'Infinite Steel Quiver',
    'add_name' => '',
    'description' => '',
    'icon' => 'br_cashtex.item.br_cash_quiver_of_fine_steel_arrows_i00',
    'etcitem_type' => 'arrow',
    'price' => 11490,
    'crystal_type' => 'c',
    'commissionItemType' => 'OTHER_ITEM',
    'is_infinite' => 'true',
  ],
  32252 => 
  [
    'id' => 32252,
    'type' => 'etcitem',
    'name' => 'Infinite Silver Quiver',
    'add_name' => '',
    'description' => '',
    'icon' => 'br_cashtex.item.br_cash_quiver_of_silver_arrows_i00',
    'etcitem_type' => 'arrow',
    'price' => 34630,
    'crystal_type' => 'b',
    'commissionItemType' => 'OTHER_ITEM',
    'is_infinite' => 'true',
  ],
  32253 => 
  [
    'id' => 32253,
    'type' => 'etcitem',
    'name' => 'Infinite Mithril Quiver',
    'add_name' => '',
    'description' => '',
    'icon' => 'br_cashtex.item.br_cash_quiver_of_mithril_arrows_i00',
    'etcitem_type' => 'arrow',
    'price' => 364800,
    'crystal_type' => 'a',
    'commissionItemType' => 'OTHER_ITEM',
    'is_infinite' => 'true',
  ],
  32254 => 
  [
    'id' => 32254,
    'type' => 'etcitem',
    'name' => 'Infinite Quiver of Light',
    'add_name' => '',
    'description' => '',
    'icon' => 'br_cashtex.item.br_cash_quiver_of_shining_arrows_i00',
    'etcitem_type' => 'arrow',
    'price' => 1716000,
    'crystal_type' => 's',
    'commissionItemType' => 'OTHER_ITEM',
    'is_infinite' => 'true',
  ],
  32255 => 
  [
    'id' => 32255,
    'type' => 'etcitem',
    'name' => 'Infinite Orichalcum Quiver',
    'add_name' => '',
    'description' => '',
    'etcitem_type' => 'arrow',
    'price' => 1716000,
    'crystal_type' => 'r',
    'commissionItemType' => 'OTHER_ITEM',
    'is_infinite' => 'true',
  ],
  32256 => 
  [
    'id' => 32256,
    'type' => 'etcitem',
    'name' => 'Infinite Wooden Bolt Container',
    'add_name' => '',
    'description' => '',
    'icon' => 'br_cashtex.item.br_cash_quiver_of_bone_bolts_i00',
    'etcitem_type' => 'bolt',
    'price' => 1580,
    'commissionItemType' => 'OTHER_ITEM',
    'is_infinite' => 'true',
  ],
  32257 => 
  [
    'id' => 32257,
    'type' => 'etcitem',
    'name' => 'Infinite Bone Bolt Container',
    'add_name' => '',
    'description' => '',
    'icon' => 'br_cashtex.item.br_cash_quiver_of_bone_bolts_i00',
    'etcitem_type' => 'bolt',
    'price' => 7320,
    'crystal_type' => 'd',
    'commissionItemType' => 'OTHER_ITEM',
    'is_infinite' => 'true',
  ],
  32258 => 
  [
    'id' => 32258,
    'type' => 'etcitem',
    'name' => 'Infinite Steel Bolt Container',
    'add_name' => '',
    'description' => '',
    'icon' => 'br_cashtex.item.br_cash_quiver_of_fine_steel_bolts_i00',
    'etcitem_type' => 'bolt',
    'price' => 11490,
    'crystal_type' => 'c',
    'commissionItemType' => 'OTHER_ITEM',
    'is_infinite' => 'true',
  ],
  32259 => 
  [
    'id' => 32259,
    'type' => 'etcitem',
    'name' => 'Infinite Silver Bolt Container',
    'add_name' => '',
    'description' => '',
    'icon' => 'br_cashtex.item.br_cash_quiver_of_silver_bolts_i00',
    'etcitem_type' => 'bolt',
    'price' => 34630,
    'crystal_type' => 'b',
    'commissionItemType' => 'OTHER_ITEM',
    'is_infinite' => 'true',
  ],
  32260 => 
  [
    'id' => 32260,
    'type' => 'etcitem',
    'name' => 'Infinite Mithril Bolt Container',
    'add_name' => '',
    'description' => '',
    'icon' => 'br_cashtex.item.br_cash_quiver_of_mithril_bolts_i00',
    'etcitem_type' => 'bolt',
    'price' => 364800,
    'crystal_type' => 'a',
    'commissionItemType' => 'OTHER_ITEM',
    'is_infinite' => 'true',
  ],
];