<?php
return [
  5900 => 
  [
    'id' => 5900,
    'type' => 'etcitem',
    'name' => 'Coin Collecting Album',
    'add_name' => '',
    'description' => 'A high quality coin collecting album made of leather.',
    'icon' => 'etc_ertheia2',
    'is_tradable' => false,
    'is_dropable' => false,
    'is_sellable' => false,
    'is_depositable' => false,
    'is_questitem' => true,
    'is_stackable' => true,
  ],
  5901 => 
  [
    'id' => 5901,
    'type' => 'etcitem',
    'name' => 'Blood Offering',
    'add_name' => '',
    'description' => 'Blood that can be obtained by killing a Monster of Offering. The number of this item will determine your score.',
    'icon' => 'etc_dragon_blood_i00',
    'is_tradable' => false,
    'is_dropable' => false,
    'is_sellable' => false,
    'is_depositable' => false,
    'is_stackable' => true,
    'is_questitem' => true,
  ],
  5902 => 
  [
    'id' => 5902,
    'type' => 'etcitem',
    'name' => 'Scroll of Ancient Magic',
    'add_name' => '',
    'description' => 'A scroll that contains ancient magic. Take it to Gatekeeper Ziggurat.',
    'icon' => 'etc_scroll_of_enchant_weapon_i01',
    'is_tradable' => false,
    'is_dropable' => false,
    'is_sellable' => false,
    'is_depositable' => false,
    'is_stackable' => true,
    'is_questitem' => true,
  ],
  5903 => 
  [
    'id' => 5903,
    'type' => 'etcitem',
    'name' => 'Ancient Ash Urn',
    'add_name' => '',
    'description' => 'An ancient urn that was found in the Tower of Insolence. Take it to Seer Reva of Aden Castle Town.',
    'icon' => 'etc_oil_pot_black_i00',
    'is_tradable' => false,
    'is_dropable' => false,
    'is_sellable' => false,
    'is_depositable' => false,
    'is_stackable' => true,
    'is_questitem' => true,
  ],
  5916 => 
  [
    'id' => 5916,
    'type' => 'etcitem',
    'name' => 'Spellbook Page',
    'add_name' => '',
    'description' => 'A torn piece of paper that seems to have been ripped out of a spellbook. If you double-click it, you can examine it closely.',
    'icon' => 'etc_piece_of_paper_white_i00',
    'price' => 80,
    'is_stackable' => true,
    'handler' => 'itemskills',
    'commissionItemType' => 'OTHER_ITEM',
    'is_depositable' => false,
  ],
  5917 => 
  [
    'id' => 5917,
    'type' => 'etcitem',
    'name' => 'Kranvel\'s Spellbook: Chapter of Fire',
    'add_name' => '',
    'description' => 'Great Magus Kranvel\'s Spellbook: Chapter of Fire. Collect the Chapters on Fire, Water, Wind and Earth and take all of them to Elder Casian.',
    'icon' => 'etc_paper_red_i00',
    'price' => 80,
    'commissionItemType' => 'OTHER_ITEM',
    'is_stackable' => true,
    'is_depositable' => false,
  ],
  5918 => 
  [
    'id' => 5918,
    'type' => 'etcitem',
    'name' => 'Kranvel\'s Spellbook: Chapter of Water',
    'add_name' => '',
    'description' => 'Great Magus Kranvel\'s Spellbook: Chapter of Water. Collect the Chapters on Fire, Water, Wind and Earth and take all of them to Elder Casian.',
    'icon' => 'etc_paper_blue_i00',
    'price' => 80,
    'commissionItemType' => 'OTHER_ITEM',
    'is_stackable' => true,
    'is_depositable' => false,
  ],
  5919 => 
  [
    'id' => 5919,
    'type' => 'etcitem',
    'name' => 'Kranvel\'s Spellbook: Chapter of Wind',
    'add_name' => '',
    'description' => 'Great Magus Kranvel\'s Spellbook: Chapter of Wind. Collect the Chapters on Fire, Water, Wind and Earth and take all of them to Elder Casian.',
    'icon' => 'etc_paper_white_i00',
    'price' => 80,
    'commissionItemType' => 'OTHER_ITEM',
    'is_stackable' => true,
    'is_depositable' => false,
  ],
  5920 => 
  [
    'id' => 5920,
    'type' => 'etcitem',
    'name' => 'Kranvel\'s Spellbook: Chapter of Earth',
    'add_name' => '',
    'description' => 'Great Magus Kranvel\'s Spellbook: Chapter of Earth. Collect the Chapters on Fire, Water, Wind and Earth and take all of them to Elder Casian.',
    'icon' => 'etc_paper_black_i00',
    'price' => 80,
    'commissionItemType' => 'OTHER_ITEM',
    'is_stackable' => true,
    'is_depositable' => false,
  ],
  5921 => 
  [
    'id' => 5921,
    'type' => 'etcitem',
    'name' => 'Worthless Piece of Paper',
    'add_name' => '',
    'description' => 'A paper piece that has useless scribbles written on it.',
    'icon' => 'etc_piece_of_paper_black_i00',
    'price' => 80,
    'commissionItemType' => 'OTHER_ITEM',
    'is_stackable' => true,
  ],
  5922 => 
  [
    'id' => 5922,
    'type' => 'etcitem',
    'name' => 'Blueprint: Giant Golem 1',
    'add_name' => '',
    'description' => 'Part of the golem blueprints from the Titan era. The first page out of five pages.',
    'icon' => 'etc_paper_black_i00',
    'commissionItemType' => 'OTHER_ITEM',
    'is_stackable' => true,
  ],
  5923 => 
  [
    'id' => 5923,
    'type' => 'etcitem',
    'name' => 'Blueprint: Giant Golem 2',
    'add_name' => '',
    'description' => 'Part of the golem blueprints from the Titan era. The second page out of five pages.',
    'icon' => 'etc_paper_black_i00',
    'commissionItemType' => 'OTHER_ITEM',
    'is_stackable' => true,
  ],
  5924 => 
  [
    'id' => 5924,
    'type' => 'etcitem',
    'name' => 'Blueprint: Giant Golem 3',
    'add_name' => '',
    'description' => 'Part of the golem blueprints from the Titan era. The third page out of five pages.',
    'icon' => 'etc_paper_black_i00',
    'commissionItemType' => 'OTHER_ITEM',
    'is_stackable' => true,
  ],
  5925 => 
  [
    'id' => 5925,
    'type' => 'etcitem',
    'name' => 'Blueprint: Giant Golem 4',
    'add_name' => '',
    'description' => 'Part of the golem blueprints from the Titan era. The fourth page out of five pages.',
    'icon' => 'etc_paper_black_i00',
    'commissionItemType' => 'OTHER_ITEM',
    'is_stackable' => true,
  ],
  5926 => 
  [
    'id' => 5926,
    'type' => 'etcitem',
    'name' => 'Blueprint: Giant Golem 5',
    'add_name' => '',
    'description' => 'Part of the golem blueprints from the Titan era. The fifth page out of five pages.',
    'icon' => 'etc_paper_black_i00',
    'commissionItemType' => 'OTHER_ITEM',
    'is_stackable' => true,
  ],
  5927 => 
  [
    'id' => 5927,
    'type' => 'etcitem',
    'name' => 'Book: Basics of Giants\' Magic, Chapter 1',
    'add_name' => '',
    'description' => 'A book on the magic of the giants from the era of Titans, 1st chapter.',
    'icon' => 'etc_paper_blue_i00',
    'commissionItemType' => 'OTHER_ITEM',
    'is_stackable' => true,
  ],
  5928 => 
  [
    'id' => 5928,
    'type' => 'etcitem',
    'name' => 'Book: Basics of Giants\' Magic, Chapter 2',
    'add_name' => '',
    'description' => 'A book on the magic of the giants from the era of Titans, 2nd chapter.',
    'icon' => 'etc_paper_blue_i00',
    'commissionItemType' => 'OTHER_ITEM',
    'is_stackable' => true,
  ],
  5929 => 
  [
    'id' => 5929,
    'type' => 'etcitem',
    'name' => 'Book: Basics of Giants\' Magic, Chapter 3',
    'add_name' => '',
    'description' => 'A book on the magic of the giants from the era of Titans, 3rd chapter.',
    'icon' => 'etc_paper_blue_i00',
    'commissionItemType' => 'OTHER_ITEM',
    'is_stackable' => true,
  ],
  5930 => 
  [
    'id' => 5930,
    'type' => 'etcitem',
    'name' => 'Book: Basics of Giants\' Magic, Chapter 4',
    'add_name' => '',
    'description' => 'A book on the magic of the giants from the era of Titans, 4th chapter.',
    'icon' => 'etc_paper_blue_i00',
    'commissionItemType' => 'OTHER_ITEM',
    'is_stackable' => true,
  ],
  5931 => 
  [
    'id' => 5931,
    'type' => 'etcitem',
    'name' => 'Book: Basics of Giants\' Magic, Chapter 5',
    'add_name' => '',
    'description' => 'A book on the magic of the giants from the era of Titans, 5th chapter.',
    'icon' => 'etc_paper_blue_i00',
    'commissionItemType' => 'OTHER_ITEM',
    'is_stackable' => true,
  ],
  5932 => 
  [
    'id' => 5932,
    'type' => 'etcitem',
    'name' => 'Handbook: Giants\' Architecture, Chapter 1',
    'add_name' => '',
    'description' => 'An architectural handbook of the giants from the era of Titans, 1st chapter.',
    'icon' => 'etc_paper_red_i00',
    'commissionItemType' => 'OTHER_ITEM',
    'is_stackable' => true,
  ],
  5933 => 
  [
    'id' => 5933,
    'type' => 'etcitem',
    'name' => 'Handbook: Giants\' Architecture, Chapter 2',
    'add_name' => '',
    'description' => 'An architectural handbook of the giants from the era of Titans, 2nd chapter.',
    'icon' => 'etc_paper_red_i00',
    'commissionItemType' => 'OTHER_ITEM',
    'is_stackable' => true,
  ],
  5934 => 
  [
    'id' => 5934,
    'type' => 'etcitem',
    'name' => 'Handbook: Giants\' Architecture, Chapter 3',
    'add_name' => '',
    'description' => 'An architectural handbook of the giants from the era of Titans, 3rd chapter.',
    'icon' => 'etc_paper_red_i00',
    'commissionItemType' => 'OTHER_ITEM',
    'is_stackable' => true,
  ],
  5935 => 
  [
    'id' => 5935,
    'type' => 'etcitem',
    'name' => 'Handbook: Giants\' Architecture, Chapter 4',
    'add_name' => '',
    'description' => 'An architectural handbook of the giants from the era of Titans, 4th chapter.',
    'icon' => 'etc_paper_red_i00',
    'commissionItemType' => 'OTHER_ITEM',
    'is_stackable' => true,
  ],
  5936 => 
  [
    'id' => 5936,
    'type' => 'etcitem',
    'name' => 'Handbook: Giants\' Architecture, Chapter 5',
    'add_name' => '',
    'description' => 'An architectural handbook of the giants from the era of Titans, 5th chapter.',
    'icon' => 'etc_paper_red_i00',
    'commissionItemType' => 'OTHER_ITEM',
    'is_stackable' => true,
  ],
  5937 => 
  [
    'id' => 5937,
    'type' => 'etcitem',
    'name' => 'Book: Giants\' Medical Science, Chapter 1',
    'add_name' => '',
    'description' => 'A medical book of the giants from the era of Titans, 1st chapter.',
    'icon' => 'etc_paper_white_i00',
    'commissionItemType' => 'OTHER_ITEM',
    'is_stackable' => true,
  ],
  5938 => 
  [
    'id' => 5938,
    'type' => 'etcitem',
    'name' => 'Book: Giants\' Medical Science, Chapter 2',
    'add_name' => '',
    'description' => 'A medical book of the giants from the era of Titans, 2nd chapter.',
    'icon' => 'etc_paper_white_i00',
    'commissionItemType' => 'OTHER_ITEM',
    'is_stackable' => true,
  ],
  5939 => 
  [
    'id' => 5939,
    'type' => 'etcitem',
    'name' => 'Book: Giants\' Medical Science, Chapter 3',
    'add_name' => '',
    'description' => 'A medical book of the giants from the era of Titans, 3rd chapter.',
    'icon' => 'etc_paper_white_i00',
    'commissionItemType' => 'OTHER_ITEM',
    'is_stackable' => true,
  ],
  5940 => 
  [
    'id' => 5940,
    'type' => 'etcitem',
    'name' => 'Book: Giants\' Medical Science, Chapter 4',
    'add_name' => '',
    'description' => 'A medical book of the giants from the era of Titans, 4th chapter.',
    'icon' => 'etc_paper_white_i00',
    'commissionItemType' => 'OTHER_ITEM',
    'is_stackable' => true,
  ],
  5941 => 
  [
    'id' => 5941,
    'type' => 'etcitem',
    'name' => 'Book: Giants\' Medical Science, Chapter 5',
    'add_name' => '',
    'description' => 'A medical book of the giants from the era of Titans, 5th chapter.',
    'icon' => 'etc_paper_white_i00',
    'commissionItemType' => 'OTHER_ITEM',
    'is_stackable' => true,
  ],
  5942 => 
  [
    'id' => 5942,
    'type' => 'etcitem',
    'name' => 'Giant\'s Love Letter',
    'add_name' => '',
    'description' => 'It seems like even the giants used to have a love life.',
    'icon' => 'etc_piece_of_report_i00',
    'price' => 200,
    'commissionItemType' => 'OTHER_ITEM',
    'is_stackable' => true,
  ],
  5943 => 
  [
    'id' => 5943,
    'type' => 'etcitem',
    'name' => 'Giants\' Doodle',
    'add_name' => '',
    'description' => 'A crude picture drawn by a would-be painter giant.',
    'icon' => 'etc_painting_i00',
    'price' => 200,
    'commissionItemType' => 'OTHER_ITEM',
    'is_stackable' => true,
  ],
  5944 => 
  [
    'id' => 5944,
    'type' => 'etcitem',
    'name' => 'Ancient Parchment',
    'add_name' => '',
    'description' => 'A piece of parchment from the Titan era. If you double-click it, you can read the contents.',
    'icon' => 'etc_roll_of_paper_black_i00',
    'is_stackable' => true,
    'handler' => 'itemskills',
    'commissionItemType' => 'OTHER_ITEM',
    'is_depositable' => false,
  ],
  5945 => 
  [
    'id' => 5945,
    'type' => 'etcitem',
    'name' => 'Book: Giants Science and Technology, Chapter 1',
    'add_name' => '',
    'description' => 'A part of the theory book that describes the science and technology of the Titan era. The 1st of five chapters.',
    'icon' => 'etc_spell_books_white_i00',
    'commissionItemType' => 'OTHER_ITEM',
    'is_stackable' => true,
  ],
  5946 => 
  [
    'id' => 5946,
    'type' => 'etcitem',
    'name' => 'Book: Giants Science and Technology, Chapter 2',
    'add_name' => '',
    'description' => 'A part of the theory book that describes the science and technology of the Titan era. The 2nd of five chapters.',
    'icon' => 'etc_spell_books_white_i00',
    'commissionItemType' => 'OTHER_ITEM',
    'is_stackable' => true,
  ],
  5947 => 
  [
    'id' => 5947,
    'type' => 'etcitem',
    'name' => 'Book: Giants Science and Technology, Chapter 3',
    'add_name' => '',
    'description' => 'A part of the theory book that describes the science and technology of the Titan era. The 3rd of five chapters.',
    'icon' => 'etc_spell_books_white_i00',
    'commissionItemType' => 'OTHER_ITEM',
    'is_stackable' => true,
  ],
  5948 => 
  [
    'id' => 5948,
    'type' => 'etcitem',
    'name' => 'Book: Giants Science and Technology, Chapter 4',
    'add_name' => '',
    'description' => 'A part of the theory book that describes the science and technology of the Titan era. The 4th of five chapters.',
    'icon' => 'etc_spell_books_white_i00',
    'commissionItemType' => 'OTHER_ITEM',
    'is_stackable' => true,
  ],
  5949 => 
  [
    'id' => 5949,
    'type' => 'etcitem',
    'name' => 'Book: Giants Science and Technology, Chapter 5',
    'add_name' => '',
    'description' => 'A part of the theory book that describes the science and technology of the Titan era. The 5th of five chapters.',
    'icon' => 'etc_spell_books_white_i00',
    'commissionItemType' => 'OTHER_ITEM',
    'is_stackable' => true,
  ],
  5950 => 
  [
    'id' => 5950,
    'type' => 'etcitem',
    'name' => 'Almanac: Lesser Giant Culture, Chapter 1',
    'add_name' => '',
    'description' => 'Part of the almanac that contains information about the culture of the Titan era. The 1st of five chapters.',
    'icon' => 'etc_spell_books_summon_i00',
    'commissionItemType' => 'OTHER_ITEM',
    'is_stackable' => true,
  ],
  5951 => 
  [
    'id' => 5951,
    'type' => 'etcitem',
    'name' => 'Almanac: Lesser Giant Culture, Chapter 2',
    'add_name' => '',
    'description' => 'Part of the almanac that contains information about the culture of the Titan era. The 2nd of five chapters.',
    'icon' => 'etc_spell_books_summon_i00',
    'commissionItemType' => 'OTHER_ITEM',
    'is_stackable' => true,
  ],
  5952 => 
  [
    'id' => 5952,
    'type' => 'etcitem',
    'name' => 'Almanac: Lesser Giant Culture, Chapter 3',
    'add_name' => '',
    'description' => 'Part of the almanac that contains information about the culture of the Titan era. The 3rd of five chapters.',
    'icon' => 'etc_spell_books_summon_i00',
    'commissionItemType' => 'OTHER_ITEM',
    'is_stackable' => true,
  ],
  5953 => 
  [
    'id' => 5953,
    'type' => 'etcitem',
    'name' => 'Almanac: Lesser Giant Culture, Chapter 4',
    'add_name' => '',
    'description' => 'Part of the almanac that contains information about the culture of the Titan era. The 4th of five chapters.',
    'icon' => 'etc_spell_books_summon_i00',
    'commissionItemType' => 'OTHER_ITEM',
    'is_stackable' => true,
  ],
  5954 => 
  [
    'id' => 5954,
    'type' => 'etcitem',
    'name' => 'Almanac: Lesser Giant Culture, Chapter 5',
    'add_name' => '',
    'description' => 'Part of the almanac that contains information about the culture of the Titan era. The 5th of five chapters.',
    'icon' => 'etc_spell_books_summon_i00',
    'commissionItemType' => 'OTHER_ITEM',
    'is_stackable' => true,
  ],
  5955 => 
  [
    'id' => 5955,
    'type' => 'etcitem',
    'name' => 'Ancient Lesser Giant Book',
    'add_name' => '',
    'description' => 'A book from the Titan era. If you double-click it, you can examine its contents.',
    'icon' => 'etc_spell_books_black_i00',
    'is_stackable' => true,
    'handler' => 'itemskills',
    'commissionItemType' => 'OTHER_ITEM',
    'is_depositable' => false,
  ],
  5956 => 
  [
    'id' => 5956,
    'type' => 'etcitem',
    'name' => '15-year-old Wine',
    'add_name' => '',
    'description' => 'A gift from Harlan as a token of gratitude. It is aged 15 years. Average quality wine.',
    'icon' => 'etc_luxury_wine_a_i00',
    'weight' => 20,
    'price' => 5900,
    'is_questitem' => true,
    'commissionItemType' => 'OTHER_ITEM',
    'is_stackable' => true,
    'is_depositable' => false,
  ],
  5957 => 
  [
    'id' => 5957,
    'type' => 'etcitem',
    'name' => '30-year-old Wine',
    'add_name' => '',
    'description' => 'A gift from Harlan as a token of gratitude. It is aged 30 years. High quality wine.',
    'icon' => 'etc_luxury_wine_b_i00',
    'weight' => 20,
    'price' => 7900,
    'is_questitem' => true,
    'commissionItemType' => 'OTHER_ITEM',
    'is_stackable' => true,
    'is_depositable' => false,
  ],
  5958 => 
  [
    'id' => 5958,
    'type' => 'etcitem',
    'name' => '60-year-old Wine',
    'add_name' => '',
    'description' => 'A gift from Harlan as a token of gratitude. It is aged 60 years. Excellent quality wine.',
    'icon' => 'etc_luxury_wine_c_i00',
    'weight' => 20,
    'price' => 30900,
    'is_questitem' => true,
    'commissionItemType' => 'OTHER_ITEM',
    'is_stackable' => true,
    'is_depositable' => false,
  ],
  5959 => 
  [
    'id' => 5959,
    'type' => 'etcitem',
    'name' => 'Ritron\'s Dessert Recipe',
    'add_name' => '',
    'description' => 'A secret recipe for making dessert by using ritron fruit as its ingredient. It can to sold at a store.',
    'icon' => 'etc_paper_white_i00',
    'weight' => 10,
    'is_questitem' => true,
    'commissionItemType' => 'OTHER_ITEM',
    'price' => 40000,
    'is_depositable' => false,
  ],
  5960 => 
  [
    'id' => 5960,
    'type' => 'etcitem',
    'name' => 'Ritron Jelly',
    'add_name' => '',
    'description' => 'Delicious jelly made from ritron fruit. It can be sold at a store.',
    'icon' => 'etc_cobol_i04',
    'weight' => 10,
    'is_questitem' => true,
    'commissionItemType' => 'OTHER_ITEM',
    'price' => 920,
    'is_depositable' => false,
  ],
  5961 => 
  [
    'id' => 5961,
    'type' => 'etcitem',
    'name' => 'Kail\'s Silver Basilisk',
    'add_name' => '',
    'description' => 'Royal-grade coin',
    'icon' => 'etc_kyles_silver_basilisk_i00',
    'price' => 1000,
    'is_questitem' => true,
    'commissionItemType' => 'OTHER_ITEM',
    'is_stackable' => true,
    'is_depositable' => false,
  ],
  5962 => 
  [
    'id' => 5962,
    'type' => 'etcitem',
    'name' => 'Kail\'s Gold Golem',
    'add_name' => '',
    'description' => 'Royal-grade coin',
    'icon' => 'etc_kyles_gold_golem_i00',
    'price' => 1000,
    'is_questitem' => true,
    'commissionItemType' => 'OTHER_ITEM',
    'is_stackable' => true,
    'is_depositable' => false,
  ],
  5963 => 
  [
    'id' => 5963,
    'type' => 'etcitem',
    'name' => 'Kail\'s Blood Dragon',
    'add_name' => '',
    'description' => 'Royal-grade coin',
    'icon' => 'etc_kyles_blood_dragon_i00',
    'price' => 1000,
    'is_questitem' => true,
    'commissionItemType' => 'OTHER_ITEM',
    'is_stackable' => true,
    'is_depositable' => false,
  ],
  5964 => 
  [
    'id' => 5964,
    'type' => 'etcitem',
    'name' => 'Warehouse Keeper\'s Medal',
    'add_name' => '',
    'description' => 'A medal that is issued by the Iron Gate Guild to Warehouse Keepers according to their productivity. If you collect them, you can use them to play bingo.',
    'icon' => 'etc_irongate_medal_i00',
    'price' => 100,
    'is_questitem' => true,
    'commissionItemType' => 'OTHER_ITEM',
    'is_stackable' => true,
    'is_depositable' => false,
  ],
  5971 => 
  [
    'id' => 5971,
    'type' => 'etcitem',
    'name' => 'Joke Book of Ancient Times',
    'add_name' => '',
    'description' => 'A collection of jokes of Galfredo Romer, a Royal Clown.',
    'icon' => 'etc_piece_of_paper_black_i00',
    'price' => 400,
    'commissionItemType' => 'OTHER_ITEM',
    'is_stackable' => true,
  ],
  5972 => 
  [
    'id' => 5972,
    'type' => 'etcitem',
    'name' => 'Revelation of the Seals: Chapter of Avarice',
    'add_name' => '',
    'description' => 'An ancient record regarding the Seven Seals. The first of seven chapters.',
    'icon' => 'etc_piece_of_paper_white_i00',
    'price' => 400,
    'commissionItemType' => 'OTHER_ITEM',
    'is_stackable' => true,
  ],
  5973 => 
  [
    'id' => 5973,
    'type' => 'etcitem',
    'name' => 'Revelation of the Seals: Chapter of Gnosis',
    'add_name' => '',
    'description' => 'An ancient record regarding the Seven Seals. The second of seven chapters.',
    'icon' => 'etc_piece_of_paper_white_i00',
    'price' => 400,
    'commissionItemType' => 'OTHER_ITEM',
    'is_stackable' => true,
  ],
  5974 => 
  [
    'id' => 5974,
    'type' => 'etcitem',
    'name' => 'Revelation of the Seals: Chapter of Strife',
    'add_name' => '',
    'description' => 'An ancient record regarding the Seven Seals. The third of seven chapters.',
    'icon' => 'etc_piece_of_paper_white_i00',
    'price' => 400,
    'commissionItemType' => 'OTHER_ITEM',
    'is_stackable' => true,
  ],
  5975 => 
  [
    'id' => 5975,
    'type' => 'etcitem',
    'name' => 'Revelation of the Seals: Chapter of Punishment',
    'add_name' => '',
    'description' => 'An ancient record regarding the Seven Seals. The fourth of seven chapters.',
    'icon' => 'etc_piece_of_paper_white_i00',
    'price' => 400,
    'commissionItemType' => 'OTHER_ITEM',
    'is_stackable' => true,
  ],
  5976 => 
  [
    'id' => 5976,
    'type' => 'etcitem',
    'name' => 'Revelation of the Seals: Chapter of Awakening',
    'add_name' => '',
    'description' => 'An ancient record regarding the Seven Seals. The fifth of seven chapters.',
    'icon' => 'etc_piece_of_paper_white_i00',
    'price' => 400,
    'commissionItemType' => 'OTHER_ITEM',
    'is_stackable' => true,
  ],
  5977 => 
  [
    'id' => 5977,
    'type' => 'etcitem',
    'name' => 'Revelation of the Seals: Chapter of Calamity',
    'add_name' => '',
    'description' => 'An ancient record regarding the Seven Seals. The sixth of seven chapters.',
    'icon' => 'etc_piece_of_paper_white_i00',
    'price' => 400,
    'commissionItemType' => 'OTHER_ITEM',
    'is_stackable' => true,
  ],
  5978 => 
  [
    'id' => 5978,
    'type' => 'etcitem',
    'name' => 'Revelation of the Seals: Chapter of Descent',
    'add_name' => '',
    'description' => 'An ancient record regarding the Seven Seals. The seventh of seven chapters.',
    'icon' => 'etc_piece_of_paper_white_i00',
    'price' => 400,
    'commissionItemType' => 'OTHER_ITEM',
    'is_stackable' => true,
  ],
  5979 => 
  [
    'id' => 5979,
    'type' => 'etcitem',
    'name' => 'Ancient Epic, Chapter 1',
    'add_name' => '',
    'description' => 'A story of heroes written by ancient troubadours. The first of five chapters.',
    'icon' => 'etc_piece_of_paper_gray_i00',
    'price' => 400,
    'commissionItemType' => 'OTHER_ITEM',
    'is_stackable' => true,
  ],
  5980 => 
  [
    'id' => 5980,
    'type' => 'etcitem',
    'name' => 'Ancient Epic, Chapter 2',
    'add_name' => '',
    'description' => 'A story of heroes written by ancient troubadours. The second of five chapters.',
    'icon' => 'etc_piece_of_paper_gray_i00',
    'price' => 400,
    'commissionItemType' => 'OTHER_ITEM',
    'is_stackable' => true,
  ],
  5981 => 
  [
    'id' => 5981,
    'type' => 'etcitem',
    'name' => 'Ancient Epic, Chapter 3',
    'add_name' => '',
    'description' => 'A story of heroes written by ancient troubadours. The third of five chapters.',
    'icon' => 'etc_piece_of_paper_gray_i00',
    'price' => 400,
    'commissionItemType' => 'OTHER_ITEM',
    'is_stackable' => true,
  ],
  5982 => 
  [
    'id' => 5982,
    'type' => 'etcitem',
    'name' => 'Ancient Epic, Chapter 4',
    'add_name' => '',
    'description' => 'A story of heroes written by ancient troubadours. The fourth of five chapters.',
    'icon' => 'etc_piece_of_paper_gray_i00',
    'price' => 400,
    'commissionItemType' => 'OTHER_ITEM',
    'is_stackable' => true,
  ],
  5983 => 
  [
    'id' => 5983,
    'type' => 'etcitem',
    'name' => 'Ancient Epic, Chapter 5',
    'add_name' => '',
    'description' => 'A story of heroes written by ancient troubadours. The fifth of five chapters.',
    'icon' => 'etc_piece_of_paper_gray_i00',
    'price' => 400,
    'commissionItemType' => 'OTHER_ITEM',
    'is_stackable' => true,
  ],
  5984 => 
  [
    'id' => 5984,
    'type' => 'etcitem',
    'name' => 'Imperial Genealogy 1',
    'add_name' => '',
    'description' => 'The genealogy of the Elmoreden royal family. The first of five chapters.',
    'icon' => 'etc_letter_red_i00',
    'price' => 400,
    'commissionItemType' => 'OTHER_ITEM',
    'is_stackable' => true,
  ],
  5985 => 
  [
    'id' => 5985,
    'type' => 'etcitem',
    'name' => 'Imperial Genealogy 2',
    'add_name' => '',
    'description' => 'The genealogy of the Elmoreden royal family. The second of five chapters.',
    'icon' => 'etc_letter_red_i00',
    'price' => 400,
    'commissionItemType' => 'OTHER_ITEM',
    'is_stackable' => true,
  ],
  5986 => 
  [
    'id' => 5986,
    'type' => 'etcitem',
    'name' => 'Imperial Genealogy 3',
    'add_name' => '',
    'description' => 'The genealogy of the Elmoreden royal family. The third of five chapters.',
    'icon' => 'etc_letter_red_i00',
    'price' => 400,
    'commissionItemType' => 'OTHER_ITEM',
    'is_stackable' => true,
  ],
  5987 => 
  [
    'id' => 5987,
    'type' => 'etcitem',
    'name' => 'Imperial Genealogy 4',
    'add_name' => '',
    'description' => 'The genealogy of the Elmoreden royal family. The fourth of five chapters.',
    'icon' => 'etc_letter_red_i00',
    'price' => 400,
    'commissionItemType' => 'OTHER_ITEM',
    'is_stackable' => true,
  ],
  5988 => 
  [
    'id' => 5988,
    'type' => 'etcitem',
    'name' => 'Imperial Genealogy 5',
    'add_name' => '',
    'description' => 'The genealogy of the Elmoreden royal family. The fifth of five chapters.',
    'icon' => 'etc_letter_red_i00',
    'price' => 400,
    'commissionItemType' => 'OTHER_ITEM',
    'is_stackable' => true,
  ],
];