<?php
return [
  94200 => 
  [
    'id' => 94200,
    'type' => 'etcitem',
    'name' => 'Scroll of Random Escape: Black Anvil Guild Camp (Time-limited]',
    'add_name' => '',
    'description' => '',
    'icon' => 'freya_scroll',
    'weight' => 5,
    'is_tradable' => false,
    'is_dropable' => false,
    'is_sellable' => false,
    'is_stackable' => true,
  ],
  94201 => 
  [
    'id' => 94201,
    'type' => 'etcitem',
    'name' => 'Dark Bezoar (Time-limited]',
    'add_name' => '',
    'description' => '',
    'icon' => 'accessory_punishment_talisman_i01',
    'is_tradable' => false,
    'is_dropable' => false,
    'is_sellable' => false,
    'is_stackable' => true,
  ],
  94202 => 
  [
    'id' => 94202,
    'type' => 'etcitem',
    'name' => 'Transformation Scroll: Queen Ant (Time-limited]',
    'add_name' => '',
    'description' => '',
    'icon' => 'scroll_of_verification_i09',
    'etcitem_type' => 'potion',
    'is_tradable' => false,
    'is_dropable' => false,
    'is_sellable' => false,
    'is_stackable' => true,
    'handler' => 'itemskills',
  ],
  94203 => 
  [
    'id' => 94203,
    'type' => 'etcitem',
    'name' => 'Transformation Scroll: Orfen (Time-limited]',
    'add_name' => '',
    'description' => '',
    'icon' => 'scroll_of_verification_i02',
    'etcitem_type' => 'potion',
    'is_tradable' => false,
    'is_dropable' => false,
    'is_sellable' => false,
    'is_stackable' => true,
    'handler' => 'itemskills',
  ],
  94204 => 
  [
    'id' => 94204,
    'type' => 'etcitem',
    'name' => 'Transformation Scroll: Baium (Time-limited]',
    'add_name' => '',
    'description' => '',
    'icon' => 'scroll_of_verification_i05',
    'etcitem_type' => 'potion',
    'is_tradable' => false,
    'is_dropable' => false,
    'is_sellable' => false,
    'is_stackable' => true,
    'handler' => 'itemskills',
  ],
  94205 => 
  [
    'id' => 94205,
    'type' => 'etcitem',
    'name' => 'Transformation Scroll: Zaken (Time-limited]',
    'add_name' => '',
    'description' => '',
    'icon' => 'scroll_of_verification_i00',
    'etcitem_type' => 'potion',
    'is_tradable' => false,
    'is_dropable' => false,
    'is_sellable' => false,
    'is_stackable' => true,
    'handler' => 'itemskills',
  ],
  94206 => 
  [
    'id' => 94206,
    'type' => 'etcitem',
    'name' => 'Transformation Scroll: Anakim (Time-limited]',
    'add_name' => '',
    'description' => '',
    'icon' => 'scroll_of_verification_i01',
    'etcitem_type' => 'potion',
    'is_tradable' => false,
    'is_dropable' => false,
    'is_sellable' => false,
    'is_stackable' => true,
    'handler' => 'itemskills',
  ],
  94207 => 
  [
    'id' => 94207,
    'type' => 'etcitem',
    'name' => 'Transformation Scroll: Lilith (Time-limited]',
    'add_name' => '',
    'description' => '',
    'icon' => 'scroll_of_verification_i04',
    'etcitem_type' => 'potion',
    'is_tradable' => false,
    'is_dropable' => false,
    'is_sellable' => false,
    'is_stackable' => true,
    'handler' => 'itemskills',
  ],
  94208 => 
  [
    'id' => 94208,
    'type' => 'etcitem',
    'name' => 'Scroll of Blessing',
    'add_name' => '',
    'description' => '',
    'icon' => 'bless_scroll_wp',
    'etcitem_type' => 'bless_encht_wp',
    'is_tradable' => false,
    'is_dropable' => false,
    'is_sellable' => false,
    'is_freightable' => true,
    'is_stackable' => true,
    'is_oly_restricted' => true,
    'handler' => 'blessingscrolls',
    'commissionItemType' => 'SCROLL_OTHER',
  ],
  94209 => 
  [
    'id' => 94209,
    'type' => 'etcitem',
    'name' => 'Life Stone Lv. 1 - Weapon',
    'add_name' => '',
    'description' => '',
    'icon' => 'renewal_mineral_r',
    'weight' => 2,
    'is_tradable' => false,
    'is_dropable' => false,
    'is_sellable' => false,
    'is_stackable' => true,
  ],
  94210 => 
  [
    'id' => 94210,
    'type' => 'etcitem',
    'name' => 'Life Stone Lv. 2 - Weapon',
    'add_name' => '',
    'description' => '',
    'icon' => 'variation_mineral_wp',
    'weight' => 2,
    'is_tradable' => false,
    'is_dropable' => false,
    'is_sellable' => false,
    'is_stackable' => true,
  ],
  94211 => 
  [
    'id' => 94211,
    'type' => 'etcitem',
    'name' => 'Life Stone Lv. 1 - Armor',
    'add_name' => '',
    'description' => '',
    'icon' => 'renewal_mineral_r95',
    'weight' => 2,
    'is_tradable' => false,
    'is_dropable' => false,
    'is_sellable' => false,
    'is_stackable' => true,
  ],
  94212 => 
  [
    'id' => 94212,
    'type' => 'etcitem',
    'name' => 'Life Stone Lv. 2 - Armor',
    'add_name' => '',
    'description' => '',
    'icon' => 'variation_mineral_am',
    'weight' => 2,
    'is_tradable' => false,
    'is_dropable' => false,
    'is_sellable' => false,
    'is_stackable' => true,
  ],
  94213 => 
  [
    'id' => 94213,
    'type' => 'etcitem',
    'name' => 'Talisman Lucky Pack (Time-limited]',
    'add_name' => '',
    'description' => '',
    'icon' => 'bm_sheep_agathion_30d_box',
    'is_tradable' => false,
    'is_dropable' => false,
    'is_sellable' => false,
    'is_stackable' => true,
    'handler' => 'extractableitems',
    'extractableCountMin' => '1',
    'extractableCountMax' => '1',
  ],
  94214 => 
  [
    'id' => 94214,
    'type' => 'etcitem',
    'name' => 'Mark of Maestro (Time-limited]',
    'add_name' => '',
    'description' => '',
    'icon' => 'etc_badge_silver_i00',
    'is_tradable' => false,
    'is_dropable' => false,
    'is_sellable' => false,
    'is_stackable' => true,
  ],
  94215 => 
  [
    'id' => 94215,
    'type' => 'etcitem',
    'name' => 'Jewelry Box Lv. 1 (Time-limited]',
    'add_name' => '',
    'description' => '',
    'icon' => 'etc_bm_jewelbox_main_i00',
    'is_tradable' => false,
    'is_dropable' => false,
    'is_sellable' => false,
    'is_stackable' => true,
    'handler' => 'extractableitems',
    'extractableCountMin' => '1',
    'extractableCountMax' => '1',
  ],
  94216 => 
  [
    'id' => 94216,
    'type' => 'etcitem',
    'name' => 'Daily Kit: Charging (Time-limited]',
    'add_name' => '',
    'description' => '',
    'icon' => 'freya_box_i02',
    'is_tradable' => false,
    'is_dropable' => false,
    'is_sellable' => false,
    'is_stackable' => true,
    'handler' => 'extractableitems',
  ],
  94217 => 
  [
    'id' => 94217,
    'type' => 'etcitem',
    'name' => 'Kit: Enchant Scrolls (Time-limited]',
    'add_name' => '',
    'description' => '',
    'icon' => 'freya_box_i03',
    'is_tradable' => false,
    'is_dropable' => false,
    'is_sellable' => false,
    'is_stackable' => true,
    'handler' => 'extractableitems',
  ],
  94218 => 
  [
    'id' => 94218,
    'type' => 'etcitem',
    'name' => 'Sparkling Accessory Pack (Time-limited]',
    'add_name' => '',
    'description' => '',
    'icon' => 'BranchSys3.g_cash_fortuna_box_r',
    'is_tradable' => false,
    'is_dropable' => false,
    'is_sellable' => false,
    'is_stackable' => true,
    'handler' => 'extractableitems',
    'extractableCountMin' => '1',
    'extractableCountMax' => '1',
  ],
  94219 => 
  [
    'id' => 94219,
    'type' => 'etcitem',
    'name' => 'Boss\' Accessory Fragment (Time-limited]',
    'add_name' => '',
    'description' => '',
    'icon' => 'icon_material_renewal_mineral',
    'is_tradable' => false,
    'is_dropable' => false,
    'is_sellable' => false,
    'is_stackable' => true,
  ],
  94220 => 
  [
    'id' => 94220,
    'type' => 'etcitem',
    'name' => 'Special Growth Support Pack (Time-limited]',
    'add_name' => '',
    'description' => '',
    'icon' => 'sayha2017_box_i02',
    'is_tradable' => false,
    'is_dropable' => false,
    'is_sellable' => false,
    'is_stackable' => true,
    'handler' => 'extractableitems',
  ],
  94221 => 
  [
    'id' => 94221,
    'type' => 'etcitem',
    'name' => 'Growth Potion (Time-limited]',
    'add_name' => '',
    'description' => '',
    'icon' => 'bm_freya_potion',
    'is_tradable' => false,
    'is_dropable' => false,
    'is_sellable' => false,
    'is_stackable' => true,
  ],
  94222 => 
  [
    'id' => 94222,
    'type' => 'etcitem',
    'name' => 'Growth Formula\'s Pack - Lv. 60 (Time-limited]',
    'add_name' => '',
    'description' => '',
    'icon' => 'etc_crystal_spice_comp_i00',
    'is_tradable' => false,
    'is_dropable' => false,
    'is_sellable' => false,
    'is_stackable' => true,
    'handler' => 'extractableitems',
  ],
  94223 => 
  [
    'id' => 94223,
    'type' => 'etcitem',
    'name' => 'Growth Formula\'s Pack - Lv. 61 (Time-limited]',
    'add_name' => '',
    'description' => '',
    'icon' => 'etc_crystal_spice_comp_i00',
    'is_tradable' => false,
    'is_dropable' => false,
    'is_sellable' => false,
    'is_stackable' => true,
    'handler' => 'extractableitems',
  ],
  94224 => 
  [
    'id' => 94224,
    'type' => 'etcitem',
    'name' => 'Growth Formula\'s Pack - Lv. 62 (Time-limited]',
    'add_name' => '',
    'description' => '',
    'icon' => 'etc_crystal_spice_comp_i00',
    'is_tradable' => false,
    'is_dropable' => false,
    'is_sellable' => false,
    'is_stackable' => true,
    'handler' => 'extractableitems',
  ],
  94225 => 
  [
    'id' => 94225,
    'type' => 'etcitem',
    'name' => 'Growth Formula\'s Pack - Lv. 63 (Time-limited]',
    'add_name' => '',
    'description' => '',
    'icon' => 'etc_crystal_spice_comp_i00',
    'is_tradable' => false,
    'is_dropable' => false,
    'is_sellable' => false,
    'is_stackable' => true,
    'handler' => 'extractableitems',
  ],
  94226 => 
  [
    'id' => 94226,
    'type' => 'etcitem',
    'name' => 'Growth Formula\'s Pack - Lv. 64 (Time-limited]',
    'add_name' => '',
    'description' => '',
    'icon' => 'etc_crystal_spice_comp_i00',
    'is_tradable' => false,
    'is_dropable' => false,
    'is_sellable' => false,
    'is_stackable' => true,
    'handler' => 'extractableitems',
  ],
  94227 => 
  [
    'id' => 94227,
    'type' => 'etcitem',
    'name' => 'Growth Formula\'s Pack - Lv. 65 (Time-limited]',
    'add_name' => '',
    'description' => '',
    'icon' => 'etc_crystal_spice_comp_i00',
    'is_tradable' => false,
    'is_dropable' => false,
    'is_sellable' => false,
    'is_stackable' => true,
    'handler' => 'extractableitems',
  ],
  94228 => 
  [
    'id' => 94228,
    'type' => 'etcitem',
    'name' => 'Growth Formula\'s Pack - Lv. 66 (Time-limited]',
    'add_name' => '',
    'description' => '',
    'icon' => 'etc_crystal_spice_comp_i00',
    'is_tradable' => false,
    'is_dropable' => false,
    'is_sellable' => false,
    'is_stackable' => true,
    'handler' => 'extractableitems',
  ],
  94229 => 
  [
    'id' => 94229,
    'type' => 'etcitem',
    'name' => 'Growth Formula\'s Pack - Lv. 67 (Time-limited]',
    'add_name' => '',
    'description' => '',
    'icon' => 'etc_crystal_spice_comp_i00',
    'is_tradable' => false,
    'is_dropable' => false,
    'is_sellable' => false,
    'is_stackable' => true,
    'handler' => 'extractableitems',
  ],
  94230 => 
  [
    'id' => 94230,
    'type' => 'etcitem',
    'name' => 'Growth Formula\'s Pack - Lv. 68 (Time-limited]',
    'add_name' => '',
    'description' => '',
    'icon' => 'etc_crystal_spice_comp_i00',
    'is_tradable' => false,
    'is_dropable' => false,
    'is_sellable' => false,
    'is_stackable' => true,
    'handler' => 'extractableitems',
  ],
  94231 => 
  [
    'id' => 94231,
    'type' => 'etcitem',
    'name' => 'Growth Formula\'s Pack - Lv. 69 (Time-limited]',
    'add_name' => '',
    'description' => '',
    'icon' => 'etc_crystal_spice_comp_i00',
    'is_tradable' => false,
    'is_dropable' => false,
    'is_sellable' => false,
    'is_stackable' => true,
    'handler' => 'extractableitems',
  ],
  94232 => 
  [
    'id' => 94232,
    'type' => 'etcitem',
    'name' => 'Growth Formula\'s Pack - Lv. 70 (Time-limited]',
    'add_name' => '',
    'description' => '',
    'icon' => 'etc_crystal_spice_comp_i00',
    'is_tradable' => false,
    'is_dropable' => false,
    'is_sellable' => false,
    'is_stackable' => true,
    'handler' => 'extractableitems',
  ],
  94233 => 
  [
    'id' => 94233,
    'type' => 'etcitem',
    'name' => 'Growth Formula\'s Pack - Lv. 71 (Time-limited]',
    'add_name' => '',
    'description' => '',
    'icon' => 'etc_crystal_spice_comp_i00',
    'is_tradable' => false,
    'is_dropable' => false,
    'is_sellable' => false,
    'is_stackable' => true,
    'handler' => 'extractableitems',
  ],
  94234 => 
  [
    'id' => 94234,
    'type' => 'etcitem',
    'name' => 'Growth Formula\'s Pack - Lv. 72 (Time-limited]',
    'add_name' => '',
    'description' => '',
    'icon' => 'etc_crystal_spice_comp_i00',
    'is_tradable' => false,
    'is_dropable' => false,
    'is_sellable' => false,
    'is_stackable' => true,
    'handler' => 'extractableitems',
  ],
  94235 => 
  [
    'id' => 94235,
    'type' => 'etcitem',
    'name' => 'Growth Formula\'s Pack - Lv. 73 (Time-limited]',
    'add_name' => '',
    'description' => '',
    'icon' => 'etc_crystal_spice_comp_i00',
    'is_tradable' => false,
    'is_dropable' => false,
    'is_sellable' => false,
    'is_stackable' => true,
    'handler' => 'extractableitems',
  ],
  94236 => 
  [
    'id' => 94236,
    'type' => 'etcitem',
    'name' => 'Growth Formula\'s Pack - Lv. 74 (Time-limited]',
    'add_name' => '',
    'description' => '',
    'icon' => 'etc_crystal_spice_comp_i00',
    'is_tradable' => false,
    'is_dropable' => false,
    'is_sellable' => false,
    'is_stackable' => true,
    'handler' => 'extractableitems',
  ],
  94237 => 
  [
    'id' => 94237,
    'type' => 'etcitem',
    'name' => 'Growth Formula\'s Pack - Lv. 75 (Time-limited]',
    'add_name' => '',
    'description' => '',
    'icon' => 'etc_crystal_spice_comp_i00',
    'is_tradable' => false,
    'is_dropable' => false,
    'is_sellable' => false,
    'is_stackable' => true,
    'handler' => 'extractableitems',
  ],
  94238 => 
  [
    'id' => 94238,
    'type' => 'etcitem',
    'name' => 'Growth Formula\'s Pack - Lv. 76 (Time-limited]',
    'add_name' => '',
    'description' => '',
    'icon' => 'etc_crystal_spice_comp_i00',
    'is_tradable' => false,
    'is_dropable' => false,
    'is_sellable' => false,
    'is_stackable' => true,
    'handler' => 'extractableitems',
  ],
  94239 => 
  [
    'id' => 94239,
    'type' => 'etcitem',
    'name' => 'Growth Formula\'s Pack - Lv. 77 (Time-limited]',
    'add_name' => '',
    'description' => '',
    'icon' => 'etc_crystal_spice_comp_i00',
    'is_tradable' => false,
    'is_dropable' => false,
    'is_sellable' => false,
    'is_stackable' => true,
    'handler' => 'extractableitems',
  ],
  94240 => 
  [
    'id' => 94240,
    'type' => 'etcitem',
    'name' => 'Growth Formula\'s Pack - Lv. 78 (Time-limited]',
    'add_name' => '',
    'description' => '',
    'icon' => 'etc_crystal_spice_comp_i00',
    'is_tradable' => false,
    'is_dropable' => false,
    'is_sellable' => false,
    'is_stackable' => true,
    'handler' => 'extractableitems',
  ],
  94241 => 
  [
    'id' => 94241,
    'type' => 'etcitem',
    'name' => 'Growth Formula\'s Pack - Lv. 79 (Time-limited]',
    'add_name' => '',
    'description' => '',
    'icon' => 'etc_crystal_spice_comp_i00',
    'is_tradable' => false,
    'is_dropable' => false,
    'is_sellable' => false,
    'is_stackable' => true,
    'handler' => 'extractableitems',
  ],
  94242 => 
  [
    'id' => 94242,
    'type' => 'etcitem',
    'name' => 'Growth Formula\'s Pack - Lv. 80 (Time-limited]',
    'add_name' => '',
    'description' => '',
    'icon' => 'etc_crystal_spice_comp_i00',
    'is_tradable' => false,
    'is_dropable' => false,
    'is_sellable' => false,
    'is_stackable' => true,
    'handler' => 'extractableitems',
  ],
  94243 => 
  [
    'id' => 94243,
    'type' => 'etcitem',
    'name' => 'Growth Formula\'s Pack - Lv. 81 (Time-limited]',
    'add_name' => '',
    'description' => '',
    'icon' => 'etc_crystal_spice_comp_i00',
    'is_tradable' => false,
    'is_dropable' => false,
    'is_sellable' => false,
    'is_stackable' => true,
    'handler' => 'extractableitems',
  ],
  94244 => 
  [
    'id' => 94244,
    'type' => 'etcitem',
    'name' => 'Growth Formula\'s Pack - Lv. 82 (Time-limited]',
    'add_name' => '',
    'description' => '',
    'icon' => 'etc_crystal_spice_comp_i00',
    'is_tradable' => false,
    'is_dropable' => false,
    'is_sellable' => false,
    'is_stackable' => true,
    'handler' => 'extractableitems',
  ],
  94245 => 
  [
    'id' => 94245,
    'type' => 'etcitem',
    'name' => 'Growth Supply Pack - Lv. 60 (Time-limited]',
    'add_name' => '',
    'description' => '',
    'icon' => 'etc_golden_spice_comp_i00',
    'is_tradable' => false,
    'is_dropable' => false,
    'is_sellable' => false,
    'is_stackable' => true,
    'handler' => 'extractableitems',
  ],
  94246 => 
  [
    'id' => 94246,
    'type' => 'etcitem',
    'name' => 'Growth Supply Pack - Lv. 65 (Time-limited]',
    'add_name' => '',
    'description' => '',
    'icon' => 'etc_golden_spice_comp_i00',
    'is_tradable' => false,
    'is_dropable' => false,
    'is_sellable' => false,
    'is_stackable' => true,
    'handler' => 'extractableitems',
  ],
  94247 => 
  [
    'id' => 94247,
    'type' => 'etcitem',
    'name' => 'Growth Supply Pack - Lv. 68 (Time-limited]',
    'add_name' => '',
    'description' => '',
    'icon' => 'etc_golden_spice_comp_i00',
    'is_tradable' => false,
    'is_dropable' => false,
    'is_sellable' => false,
    'is_stackable' => true,
    'handler' => 'extractableitems',
  ],
  94248 => 
  [
    'id' => 94248,
    'type' => 'etcitem',
    'name' => 'Growth Supply Pack - Lv. 71 (Time-limited]',
    'add_name' => '',
    'description' => '',
    'icon' => 'etc_golden_spice_comp_i00',
    'is_tradable' => false,
    'is_dropable' => false,
    'is_sellable' => false,
    'is_stackable' => true,
    'handler' => 'extractableitems',
  ],
  94249 => 
  [
    'id' => 94249,
    'type' => 'etcitem',
    'name' => 'Growth Supply Pack - Lv. 74 (Time-limited]',
    'add_name' => '',
    'description' => '',
    'icon' => 'etc_golden_spice_comp_i00',
    'is_tradable' => false,
    'is_dropable' => false,
    'is_sellable' => false,
    'is_stackable' => true,
    'handler' => 'extractableitems',
  ],
  94250 => 
  [
    'id' => 94250,
    'type' => 'etcitem',
    'name' => 'Growth Supply Pack - Lv. 76 (Time-limited]',
    'add_name' => '',
    'description' => '',
    'icon' => 'etc_golden_spice_comp_i00',
    'is_tradable' => false,
    'is_dropable' => false,
    'is_sellable' => false,
    'is_stackable' => true,
    'handler' => 'extractableitems',
  ],
  94251 => 
  [
    'id' => 94251,
    'type' => 'etcitem',
    'name' => 'Growth Supply Pack - Lv. 78 (Time-limited]',
    'add_name' => '',
    'description' => '',
    'icon' => 'etc_golden_spice_comp_i00',
    'is_tradable' => false,
    'is_dropable' => false,
    'is_sellable' => false,
    'is_stackable' => true,
    'handler' => 'extractableitems',
  ],
  94252 => 
  [
    'id' => 94252,
    'type' => 'etcitem',
    'name' => 'Growth Supply Pack - Lv. 79 (Time-limited]',
    'add_name' => '',
    'description' => '',
    'icon' => 'etc_golden_spice_comp_i00',
    'is_tradable' => false,
    'is_dropable' => false,
    'is_sellable' => false,
    'is_stackable' => true,
    'handler' => 'extractableitems',
  ],
  94253 => 
  [
    'id' => 94253,
    'type' => 'etcitem',
    'name' => 'Growth Supply Pack - Lv. 80 (Time-limited]',
    'add_name' => '',
    'description' => '',
    'icon' => 'etc_golden_spice_comp_i00',
    'is_tradable' => false,
    'is_dropable' => false,
    'is_sellable' => false,
    'is_stackable' => true,
    'handler' => 'extractableitems',
  ],
  94254 => 
  [
    'id' => 94254,
    'type' => 'etcitem',
    'name' => 'Growth Supply Pack - Lv. 81 (Time-limited]',
    'add_name' => '',
    'description' => '',
    'icon' => 'etc_golden_spice_comp_i00',
    'is_tradable' => false,
    'is_dropable' => false,
    'is_sellable' => false,
    'is_stackable' => true,
    'handler' => 'extractableitems',
  ],
  94255 => 
  [
    'id' => 94255,
    'type' => 'etcitem',
    'name' => 'Growth Supply Pack - Lv. 82 (Time-limited]',
    'add_name' => '',
    'description' => '',
    'icon' => 'etc_golden_spice_comp_i00',
    'is_tradable' => false,
    'is_dropable' => false,
    'is_sellable' => false,
    'is_stackable' => true,
    'handler' => 'extractableitems',
  ],
  94256 => 
  [
    'id' => 94256,
    'type' => 'etcitem',
    'name' => 'Master\'s Blessing Pack (Time-limited]',
    'add_name' => '',
    'description' => '',
    'icon' => 'sayha2017_box_i01',
    'is_tradable' => false,
    'is_dropable' => false,
    'is_sellable' => false,
    'is_stackable' => true,
  ],
  94257 => 
  [
    'id' => 94257,
    'type' => 'etcitem',
    'name' => 'Master\'s Seal (Time-limited]',
    'add_name' => '',
    'description' => '',
    'icon' => 'etc_royal_seal_of_lord_i05',
    'is_tradable' => false,
    'is_dropable' => false,
    'is_sellable' => false,
    'is_stackable' => true,
  ],
  94258 => 
  [
    'id' => 94258,
    'type' => 'etcitem',
    'name' => 'Package: Einhasad\'s Pendant Lv. 1',
    'add_name' => '',
    'description' => '',
    'icon' => 'Icon.bm_pendant_pve_white_pack',
    'is_tradable' => false,
    'is_dropable' => false,
    'is_sellable' => false,
    'is_stackable' => true,
    'handler' => 'extractableitems',
  ],
  94259 => 
  [
    'id' => 94259,
    'type' => 'etcitem',
    'name' => 'Package: Einhasad\'s Pendant Lv. 2',
    'add_name' => '',
    'description' => '',
    'icon' => 'Icon.bm_pendant_pve_white_pack',
    'is_tradable' => false,
    'is_dropable' => false,
    'is_sellable' => false,
    'is_stackable' => true,
    'handler' => 'extractableitems',
  ],
  94260 => 
  [
    'id' => 94260,
    'type' => 'etcitem',
    'name' => 'Package: Einhasad\'s Pendant Lv. 3',
    'add_name' => '',
    'description' => '',
    'icon' => 'Icon.bm_pendant_pve_white_pack',
    'is_tradable' => false,
    'is_dropable' => false,
    'is_sellable' => false,
    'is_stackable' => true,
    'handler' => 'extractableitems',
  ],
  94261 => 
  [
    'id' => 94261,
    'type' => 'etcitem',
    'name' => 'Package: Einhasad\'s Pendant Lv. 4',
    'add_name' => '',
    'description' => '',
    'icon' => 'Icon.bm_pendant_pve_white_pack',
    'is_tradable' => false,
    'is_dropable' => false,
    'is_sellable' => false,
    'is_stackable' => true,
    'handler' => 'extractableitems',
  ],
  94262 => 
  [
    'id' => 94262,
    'type' => 'etcitem',
    'name' => 'Package: Einhasad\'s Pendant Lv. 5',
    'add_name' => '',
    'description' => '',
    'icon' => 'Icon.bm_pendant_pve_white_pack',
    'is_tradable' => false,
    'is_dropable' => false,
    'is_sellable' => false,
    'is_stackable' => true,
    'handler' => 'extractableitems',
  ],
  94263 => 
  [
    'id' => 94263,
    'type' => 'armor',
    'name' => 'Stun Gauntlets',
    'add_name' => '',
    'description' => '',
    'icon' => 'armor_t96_g_i03',
    'bodypart' => 'gloves',
    'crystal_count' => 71,
    'crystal_type' => 'a',
    'weight' => 540,
    'price' => 1355000,
    'enchant_enabled' => true,
    'commissionItemType' => 'GLOVES',
  ],
  94264 => 
  [
    'id' => 94264,
    'type' => 'armor',
    'name' => 'Stun Gauntlets',
    'add_name' => '',
    'description' => '',
    'icon' => 'armor_t96_g_i03',
    'bodypart' => 'gloves',
    'crystal_count' => 108,
    'crystal_type' => 'a',
    'weight' => 540,
    'price' => 1355000,
    'enchant_enabled' => true,
    'commissionItemType' => 'GLOVES',
    'is_tradable' => false,
    'is_dropable' => false,
    'is_sellable' => false,
  ],
  94265 => 
  [
    'id' => 94265,
    'type' => 'etcitem',
    'name' => 'Kit: Growth (Time-limited]',
    'add_name' => '',
    'description' => '',
    'icon' => 'bm_freya_dark_rune_box',
    'is_tradable' => false,
    'is_dropable' => false,
    'is_sellable' => false,
    'is_stackable' => true,
    'handler' => 'extractableitems',
  ],
  94266 => 
  [
    'id' => 94266,
    'type' => 'etcitem',
    'name' => 'Kit: Equipment (Time-limited]',
    'add_name' => '',
    'description' => '',
    'icon' => 'bm_gold_relic_box',
    'is_tradable' => false,
    'is_dropable' => false,
    'is_sellable' => false,
    'is_stackable' => true,
    'handler' => 'extractableitems',
  ],
  94267 => 
  [
    'id' => 94267,
    'type' => 'etcitem',
    'name' => 'Kit: Combat (Time-limited]',
    'add_name' => '',
    'description' => '',
    'icon' => 'etc_treasure_box_i10',
    'is_tradable' => false,
    'is_dropable' => false,
    'is_sellable' => false,
    'is_stackable' => true,
    'handler' => 'extractableitems',
  ],
  94268 => 
  [
    'id' => 94268,
    'type' => 'etcitem',
    'name' => 'Scroll: Boost Attack',
    'add_name' => '',
    'description' => '',
    'icon' => 'scrl_of_ladies_silver_knife_01',
    'etcitem_type' => 'scroll',
    'is_stackable' => true,
    'is_sellable' => false,
    'is_oly_restricted' => true,
    'handler' => 'itemskills',
    'commissionItemType' => 'SCROLL_OTHER',
  ],
  94269 => 
  [
    'id' => 94269,
    'type' => 'etcitem',
    'name' => 'Scroll: Boost Attack',
    'add_name' => '',
    'description' => '',
    'etcitem_type' => 'scroll',
    'is_stackable' => true,
    'is_oly_restricted' => true,
    'handler' => 'itemskills',
    'commissionItemType' => 'SCROLL_OTHER',
    'is_tradable' => false,
    'is_dropable' => false,
    'is_sellable' => false,
    'is_freightable' => true,
  ],
  94270 => 
  [
    'id' => 94270,
    'type' => 'etcitem',
    'name' => 'Scroll: Boost Defense',
    'add_name' => '',
    'description' => '',
    'icon' => 'scrl_of_ench_bracelet_lucien_01',
    'etcitem_type' => 'scroll',
    'is_sellable' => false,
    'is_stackable' => true,
    'is_oly_restricted' => true,
    'handler' => 'itemskills',
    'commissionItemType' => 'SCROLL_OTHER',
  ],
  94271 => 
  [
    'id' => 94271,
    'type' => 'etcitem',
    'name' => 'Scroll: Boost Defense',
    'add_name' => '',
    'description' => '',
    'etcitem_type' => 'scroll',
    'is_stackable' => true,
    'is_oly_restricted' => true,
    'handler' => 'itemskills',
    'commissionItemType' => 'SCROLL_OTHER',
    'is_tradable' => false,
    'is_dropable' => false,
    'is_sellable' => false,
    'is_freightable' => true,
  ],
  94272 => 
  [
    'id' => 94272,
    'type' => 'etcitem',
    'name' => 'Test - Test Item for Create Item 1',
    'add_name' => '',
    'description' => '',
    'icon' => 'etc_ertheia2',
    'is_tradable' => false,
    'is_dropable' => false,
    'is_sellable' => false,
    'is_stackable' => true,
    'handler' => 'extractableitems',
  ],
  94273 => 
  [
    'id' => 94273,
    'type' => 'etcitem',
    'name' => 'Chocolate (Time-limited]',
    'add_name' => '',
    'description' => '',
    'icon' => 'BranchSys.br_valentine_darkchoco_i00',
    'is_tradable' => false,
    'is_dropable' => false,
    'is_sellable' => false,
    'is_stackable' => true,
  ],
  94274 => 
  [
    'id' => 94274,
    'type' => 'etcitem',
    'name' => 'White Chocolate (Time-limited]',
    'add_name' => '',
    'description' => '',
    'icon' => 'BranchSys.br_valentine_whitechoco_i00',
    'is_tradable' => false,
    'is_dropable' => false,
    'is_sellable' => false,
    'is_stackable' => true,
  ],
  94275 => 
  [
    'id' => 94275,
    'type' => 'etcitem',
    'name' => 'Chocolate Doll - Lv. 1 (Time-limited]',
    'add_name' => '',
    'description' => '',
    'icon' => 'gomdori_chest_change',
    'is_dropable' => false,
    'is_sellable' => false,
    'is_tradable' => false,
    'etcitem_type' => 'encht_attr_rune',
    'handler' => 'itemskills',
  ],
  94276 => 
  [
    'id' => 94276,
    'type' => 'etcitem',
    'name' => 'Chocolate Doll - Lv. 2 (Time-limited]',
    'add_name' => '',
    'description' => '',
    'icon' => 'gomdori_chest_change',
    'is_dropable' => false,
    'is_sellable' => false,
    'is_tradable' => false,
    'etcitem_type' => 'encht_attr_rune',
    'handler' => 'itemskills',
  ],
  94277 => 
  [
    'id' => 94277,
    'type' => 'etcitem',
    'name' => 'Chocolate Doll - Lv. 3 (Time-limited]',
    'add_name' => '',
    'description' => '',
    'icon' => 'gomdori_chest_change',
    'is_dropable' => false,
    'is_sellable' => false,
    'is_tradable' => false,
    'etcitem_type' => 'encht_attr_rune',
    'handler' => 'itemskills',
  ],
  94278 => 
  [
    'id' => 94278,
    'type' => 'etcitem',
    'name' => 'Chocolate Doll - Lv. 4 (Time-limited]',
    'add_name' => '',
    'description' => '',
    'icon' => 'gomdori_chest_change',
    'is_dropable' => false,
    'is_sellable' => false,
    'is_tradable' => false,
    'etcitem_type' => 'encht_attr_rune',
    'handler' => 'itemskills',
  ],
  94279 => 
  [
    'id' => 94279,
    'type' => 'etcitem',
    'name' => 'Chocolate Doll - Lv. 5 (Time-limited]',
    'add_name' => '',
    'description' => '',
    'icon' => 'gomdori_chest_change',
    'is_dropable' => false,
    'is_sellable' => false,
    'is_tradable' => false,
    'etcitem_type' => 'encht_attr_rune',
    'handler' => 'itemskills',
  ],
  94280 => 
  [
    'id' => 94280,
    'type' => 'etcitem',
    'name' => 'Chocolate Doll - Lv. 6 (Time-limited]',
    'add_name' => '',
    'description' => '',
    'icon' => 'gomdori_chest_change',
    'is_dropable' => false,
    'is_sellable' => false,
    'is_tradable' => false,
    'etcitem_type' => 'encht_attr_rune',
    'handler' => 'itemskills',
  ],
  94281 => 
  [
    'id' => 94281,
    'type' => 'etcitem',
    'name' => 'Chocolate Doll - Lv. 7 (Time-limited]',
    'add_name' => '',
    'description' => '',
    'icon' => 'gomdori_chest_change',
    'is_dropable' => false,
    'is_sellable' => false,
    'is_tradable' => false,
    'etcitem_type' => 'encht_attr_rune',
    'handler' => 'itemskills',
  ],
  94282 => 
  [
    'id' => 94282,
    'type' => 'etcitem',
    'name' => 'Chocolate Doll - Lv. 8 (Time-limited]',
    'add_name' => '',
    'description' => '',
    'icon' => 'gomdori_chest_change',
    'is_dropable' => false,
    'is_sellable' => false,
    'is_tradable' => false,
    'etcitem_type' => 'encht_attr_rune',
    'handler' => 'itemskills',
  ],
  94283 => 
  [
    'id' => 94283,
    'type' => 'etcitem',
    'name' => 'Chocolate Doll - Lv. 9 (Time-limited]',
    'add_name' => '',
    'description' => '',
    'icon' => 'gomdori_chest_change',
    'is_dropable' => false,
    'is_sellable' => false,
    'is_tradable' => false,
    'etcitem_type' => 'encht_attr_rune',
    'handler' => 'itemskills',
  ],
  94284 => 
  [
    'id' => 94284,
    'type' => 'etcitem',
    'name' => 'Chocolate Doll - Lv. 10 (Time-limited]',
    'add_name' => '',
    'description' => '',
    'icon' => 'gomdori_chest_change',
    'is_dropable' => false,
    'is_sellable' => false,
    'is_tradable' => false,
    'etcitem_type' => 'encht_attr_rune',
    'handler' => 'itemskills',
  ],
  94285 => 
  [
    'id' => 94285,
    'type' => 'etcitem',
    'name' => 'Chocolate Doll - Lv. 11 (Time-limited]',
    'add_name' => '',
    'description' => '',
    'icon' => 'gomdori_chest_change',
    'is_dropable' => false,
    'is_sellable' => false,
    'is_tradable' => false,
    'etcitem_type' => 'encht_attr_rune',
    'handler' => 'itemskills',
  ],
  94286 => 
  [
    'id' => 94286,
    'type' => 'etcitem',
    'name' => 'Chocolate Doll - Lv. 12 (Time-limited]',
    'add_name' => '',
    'description' => '',
    'icon' => 'gomdori_chest_change',
    'is_dropable' => false,
    'is_sellable' => false,
    'is_tradable' => false,
    'etcitem_type' => 'encht_attr_rune',
    'handler' => 'itemskills',
  ],
  94287 => 
  [
    'id' => 94287,
    'type' => 'etcitem',
    'name' => 'Chocolate Doll - Lv. 13 (Time-limited]',
    'add_name' => '',
    'description' => '',
    'icon' => 'gomdori_chest_change',
    'is_dropable' => false,
    'is_sellable' => false,
    'is_tradable' => false,
    'etcitem_type' => 'encht_attr_rune',
    'handler' => 'itemskills',
  ],
  94288 => 
  [
    'id' => 94288,
    'type' => 'etcitem',
    'name' => 'Chocolate Doll - Lv. 14 (Time-limited]',
    'add_name' => '',
    'description' => '',
    'icon' => 'gomdori_chest_change',
    'is_dropable' => false,
    'is_sellable' => false,
    'is_tradable' => false,
    'etcitem_type' => 'encht_attr_rune',
    'handler' => 'itemskills',
  ],
  94289 => 
  [
    'id' => 94289,
    'type' => 'etcitem',
    'name' => 'Chocolate Doll - Lv. 15 (Time-limited]',
    'add_name' => '',
    'description' => '',
    'icon' => 'gomdori_chest_change',
    'is_dropable' => false,
    'is_sellable' => false,
    'is_tradable' => false,
    'etcitem_type' => 'encht_attr_rune',
    'handler' => 'itemskills',
  ],
  94290 => 
  [
    'id' => 94290,
    'type' => 'etcitem',
    'name' => 'Valentine\'s Day Gift Basket (Time-limited]',
    'add_name' => '',
    'description' => '',
    'icon' => 'etc_whiteday_choco',
    'is_tradable' => false,
    'is_dropable' => false,
    'is_sellable' => false,
    'is_stackable' => true,
  ],
  94291 => 
  [
    'id' => 94291,
    'type' => 'etcitem',
    'name' => 'White Day\'s Gift Basket (Time-limited]',
    'add_name' => '',
    'description' => '',
    'icon' => 'etc_whiteday_candy',
    'is_tradable' => false,
    'is_dropable' => false,
    'is_sellable' => false,
    'is_stackable' => true,
  ],
  94292 => 
  [
    'id' => 94292,
    'type' => 'etcitem',
    'name' => 'Jewel Essence Lv. 5 - Amber (Time-limited]',
    'add_name' => '',
    'description' => '',
    'icon' => 'etc_bm_jewel_amber_i00',
    'is_tradable' => false,
    'is_dropable' => false,
    'is_sellable' => false,
    'is_stackable' => true,
  ],
  94293 => 
  [
    'id' => 94293,
    'type' => 'etcitem',
    'name' => 'Jewel Essence Lv. 5 - Opal (Time-limited]',
    'add_name' => '',
    'description' => '',
    'icon' => 'etc_bm_jewel_opal_i00',
    'is_tradable' => false,
    'is_dropable' => false,
    'is_sellable' => false,
    'is_stackable' => true,
  ],
  94294 => 
  [
    'id' => 94294,
    'type' => 'etcitem',
    'name' => 'Jewel Essence Lv. 5 - Coral (Time-limited]',
    'add_name' => '',
    'description' => '',
    'icon' => 'etc_bm_jewel_coral_i00',
    'is_tradable' => false,
    'is_dropable' => false,
    'is_sellable' => false,
    'is_stackable' => true,
  ],
  94295 => 
  [
    'id' => 94295,
    'type' => 'etcitem',
    'name' => 'Jewel Essence Lv. 5 - Onyx (Time-limited]',
    'add_name' => '',
    'description' => '',
    'icon' => 'etc_bm_jewel_onyx_i00',
    'is_tradable' => false,
    'is_dropable' => false,
    'is_sellable' => false,
    'is_stackable' => true,
  ],
  94296 => 
  [
    'id' => 94296,
    'type' => 'etcitem',
    'name' => 'Jewel Essence Lv. 5 - Spinel (Time-limited]',
    'add_name' => '',
    'description' => '',
    'icon' => 'etc_bm_jewel_garnet_i00',
    'is_tradable' => false,
    'is_dropable' => false,
    'is_sellable' => false,
    'is_stackable' => true,
  ],
  94297 => 
  [
    'id' => 94297,
    'type' => 'etcitem',
    'name' => 'Jewel Essence Lv. 5 - Zircon (Time-limited]',
    'add_name' => '',
    'description' => '',
    'icon' => 'etc_bm_jewel_bloodstone_i00',
    'is_tradable' => false,
    'is_dropable' => false,
    'is_sellable' => false,
    'is_stackable' => true,
  ],
  94298 => 
  [
    'id' => 94298,
    'type' => 'etcitem',
    'name' => 'Jewel Essence Lv. 5 - Moonstone (Time-limited]',
    'add_name' => '',
    'description' => '',
    'icon' => 'etc_bm_jewel_moonstone_i00',
    'is_tradable' => false,
    'is_dropable' => false,
    'is_sellable' => false,
    'is_stackable' => true,
  ],
  94299 => 
  [
    'id' => 94299,
    'type' => 'armor',
    'name' => 'Sigil of Inevitability',
    'add_name' => '',
    'description' => '',
    'icon' => 'elos_i00',
    'armor_type' => 'sigil',
    'bodypart' => 'lhand',
    'crystal_type' => 'a',
    'weight' => 1200,
    'enchant_enabled' => true,
    'commissionItemType' => 'SIGIL',
  ],
];